### ISSUE TITLE
Buffer shim generated for javascript/esm files doesn't bundle buffer module

### ISSUE THREAD

**Issue by AsamK** [webpack/webpack#6913]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I use `rawBytes = new Buffer(new Uint8Array(byteArray));` in my code. By default, webpack correctly generates a buffer shim for that:
```
/* WEBPACK VAR INJECTION */(function(Buffer) { ...
/* WEBPACK VAR INJECTION */}.call(this, __webpack_require__(/*! ./../../node_modules/buffer/index.js */ "tjlA").Buffer))
```

But when I set the type of js files to `type: 'javascript/esm'`, webpack generates invalid code (`require` call is not replaced).
Error in browser console: `ReferenceError: require is not defined`
Generated code:
```
/* WEBPACK VAR INJECTION */(function(Buffer) { ...
/* WEBPACK VAR INJECTION */}.call(this, require("./../../node_modules/buffer/index.js").Buffer))
```
**If the current behavior is a bug, please provide the steps to reproduce.**

src/index.js:
```
const rawBytes = new Buffer(new Uint8Array([65]));
console.log(rawBytes)
```

webpack.config.js:
```
const webpack = require('webpack');
module.exports = {
        module: {
                rules: [
                        {
                                test: /\.js$/,
                                exclude: /node_modules/,
                                type: 'javascript/esm',
                        },
                ]
        }
}
```

run: `webpack-cli --mode=development`

The resulting `dist/index.js` script runs in node (which supports `require`) but it doesn't run in the browser.

**What is the expected behavior?**
`require` call should not appear in generated code if module `type` is set.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
node: v9.10.0
webpack: 4.4.1
OS: linux

**Comment by ooflorent** [comment]
This is because the mode ESM is applied to the `Buffer` polyfill. You must use `include` or `exclude` to only set the `type` for your source.

**Comment by AsamK** [comment]
hm, I'm seeing the same behaviour in a typescript project, that only sets `type` for `.ts`/`.tsx` files. That shouldn't influence the `Buffer` polyfill, right?

webpack.config.js snippet:
```
{
    test: /\.tsx?$/,
    loader: 'ts-loader',
    type: 'javascript/esm',
},
```

**Comment by ooflorent** [comment]
TypeScript will transpile the `import` statements to `require` calls which is not permitted with `javascript/esm`.

**Comment by AsamK** [comment]
Nope, I've configured typescript to keep `import`/`export` statements (tsconfig.js: `"module": "es6",`).
And bundling of all `imports` in the typescript code work and are correctly transformed by webpack, the only `require` call comes from the `Buffer` polyfill.

e.g. `import React from 'react'`:
`/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! react */ "q1tI");`

**Comment by ooflorent** [comment]
It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by AsamK** [comment]
The whole reproducable example is in the description (I've also added `exclude: /node_modules/,` to the webpack config, doesn't change anything)
* put the `src/index.js` and `webpack.config.js` file in a directory.
* run `npm install -D webpack-cli webpack`
* run `webpack-cli --mode=development`
* look at `dist/main.js`

**Comment by ooflorent** [comment]
Okay, got it. I apologise for misunderstanding the issue.

You are right, it's a bug. Since `require` calls are hooks at build time and `javascript/esm` skips them, the `require` call is not intercepted.

**Comment by sokra** [comment]
Using `Buffer` inserts a `require` statement.

try using `import Buffer from "buffer"` instead of relying on the global variable

**Comment by AsamK** [comment]
That would work, but it's rather a workaround, right?
And I need an additional constant for `Buffer`:
```
import buffer from 'buffer';
const Buffer = buffer.Buffer;
const rawBytes = new Buffer(new Uint8Array([65]));
```

Importing a single export doesn't work, because `buffer` is not an EcmaScript module:
Webpack error: `import {Buffer} from 'buffer';`
```
ERROR in ./src/index.js
3:21-27 Can't import the named export 'Buffer' from non EcmaScript module (only default export is available)
 @ ./src/index.js
```

There are also no TypeScript typings for the `buffer` package...

**Comment by ooflorent** [comment]
You cannot destructure a CJS module.
