### ISSUE TITLE
The imported variable isn't recognized when is shadowed

### ISSUE THREAD

**Issue by ma2ciek** [webpack/webpack#6914]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The imported variable isn't recognized when is shadowed.

**If the current behavior is a bug, please provide the steps to reproduce.**

`src/index.js`
```js
import foo from './foo';

function bar() {
	console.log( foo );

	for ( const foo of [ 1, 2 ,3 ] ) {
		console.log( foo );
	}
}

bar();
```

`foo.js`
```js
export default function foo() { }
```

It transforms to:
```js
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var _foo__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./foo */ "./src/foo.js");


function bar() {
	console.log( foo );

	for ( const foo of [ 1, 2 ,3 ] ) {
		console.log( foo );
	}
}

bar();
```

That leads to a Syntax Error.

**What is the expected behavior?**
```js
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var _foo__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./foo */ "./src/foo.js");


function bar() {
	console.log( _foo__WEBPACK_IMPORTED_MODULE_0__ );

	for ( const foo of [ 1, 2 ,3 ] ) {
		console.log( foo );
	}
}

bar();
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

webpack@3 and webpack@4, both production and development modes.
node@6.10.3
Mac OS

**Comment by nveenjain** [comment]
I think this is a bug in Parser, we don't check for block scope while parsing `for` (for of, for in, for loops) statements. We add declaration in current scope. https://github.com/webpack/webpack/blob/master/lib/Parser.js#L1041-L1043 , We should add definitions of const, let variables in block's scope while parsing `for` loops. I'm willing to work on this. Hope I'm right (Please guide if not).
cc: @ooflorent

**Comment by ma2ciek** [comment]
So the PR waits for 6 months now 😄

**Comment by evilebottnawi** [comment]
Bump

**Comment by ma2ciek** [comment]
I think that this issue is fixed and the https://github.com/webpack/webpack/pull/6921 is closed already.
