### ISSUE TITLE
splitChunks not working as expected

### ISSUE THREAD

**Issue by tanguy29** [webpack/webpack#6916]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When using splitChunks, if dealing with a simple project it's working but in more complexe project with multiples inclusions, some dependencies are created for entry points that are not needed. The old commonChunk plugin was behaving correctly.
Exemple : 

```
const groupsOptions = {chunks: "all", minSize:0, minChunks: 1, reuseExistingChunk: true, enforce: true};

const reactConfig = {
    entry: {
        "react": ["react", "react-dom"],
        "pageA": "./src/A.jsx",
		"pageB": "./src/B.jsx",
        "pageC": "./src/C.jsx",
        "pageD": "./src/D.jsx",
        "commonAB": [ "./src/ab_a.js", "./src/ab_b.js"],
        "commonCD": ["./src/cd_c.js", "./src/cd_d.js"]
    },
    output: {
        path: __dirname + '/build/',
        filename: PROD
            ? "[name].min.js"
            : "[name].js"
    },
    module: {
        rules: [
            {
                test: /\.jsx$/,
                use: {
                    loader: "babel-loader",
                    options: {
                        presets: ["es2015", "react"]
                    }
                }
            }
        ]
    },
    optimization: {
        splitChunks: {
            cacheGroups:{
                react: {test:'react', name: "react", ...groupsOptions},
                AB: {test:'commonAB', name: "commonAB", ...groupsOptions},
                CD: {test:'commonCD', name: "commonCD", ...groupsOptions}
            }
        }
    },
    plugins: [
    ]
};

module.exports = reactConfig;
```

This produce :
![image](https://user-images.githubusercontent.com/16226590/38137465-04162fc8-3425-11e8-9eb0-ade205bed7c4.png)
This exemple is very simple and everything is OK !
- pageA depends from pageA, react and commonAB -> OK
- pageB depends from pageB, react and commonAB -> OK
- pageC depends from pageC, react and commonCD -> OK
- pageD depends from pageD, react and commonCD -> OK

But then, when i modified the code of ab_a.js and add

`import React from 'react';`

the output is :

![image](https://user-images.githubusercontent.com/16226590/38137548-861455c2-3425-11e8-8bc1-1e4bfd98fd45.png)

As you can see pageC and pageD depends of commonAB.js that is not the case (again with commonChunks plugin it was behaving correctly) ! 
- pageA depends from pageA, react and commonAB -> OK
- pageB depends from pageB, react and commonAB -> OK
- pageC depends from pageC, react and commonAB AND commonCD -> Wrong
- pageD depends from pageD, react and commonAB AND commonCD -> Wrong

Same result when i modified the code of cd_d.js and add `import React from 'react';` the output is :
![image](https://user-images.githubusercontent.com/16226590/38137622-052c6d90-3426-11e8-9afd-9f60db78227f.png)

- pageA depends from pageA, react and commonAB AND commonCD -> Wrong
- pageB depends from pageB, react and commonAB AND commonCD -> Wrong
- pageC depends from pageC, react and commonCD AND commonAB -> Wrong
- pageD depends from pageD, react and commonCD AND commonAB -> Wrong

**If the current behavior is a bug, please provide the steps to reproduce.**
Here sources to reproduce the bug :
[testCommon.zip](https://github.com/webpack/webpack/files/1863545/testCommon.zip)

**What is the expected behavior?**
With `import React from 'react';` in ab_a.js, ab_b.js, cd_c.js and cd_d.js dependencies should be : 
- pageA depends from pageA, react and commonAB
- pageB depends from pageB, react and commonAB
- pageC depends from pageC, react and commonCD
- pageD depends from pageD, react and commonCD

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
OS : Window 10
Webpack : 4.4.1
Node : 8.9.4

**Comment by ooflorent** [comment]
The best I can get is using these options:

```js
  entry: {
    react: ["react", "react-dom"],
    pageA: "./src/A.jsx",
    pageB: "./src/B.jsx",
    pageC: "./src/C.jsx",
    pageD: "./src/D.jsx",
  },
  optimization: {
    minimize: false, // debugging purpose
    runtimeChunk: "single",
    splitChunks: {
      cacheGroups: {
        react: {
          test: "react",
          name: "react",
          chunks: "all",
        },
        commons: {
          minChunks: 2,
          minSize: 0,
          chunks: "initial",
        },
      },
    },
  },
```

It produces the following output:

```
$ webpack --config src.config.js --mode production
Hash: 7609b98252465e4e8dd2
Version: webpack 4.4.1
Time: 654ms
Built at: 2018-3-30 15:45:59
                 Asset       Size  Chunks             Chunk Names
              react.js    115 KiB       0  [emitted]  react
commons~pageC~pageD.js  743 bytes       1  [emitted]  commons~pageC~pageD
commons~pageA~pageB.js  888 bytes       2  [emitted]  commons~pageA~pageB
              pageD.js    7.6 KiB       3  [emitted]  pageD
              pageC.js    7.6 KiB       4  [emitted]  pageC
              pageB.js    7.6 KiB       5  [emitted]  pageB
              pageA.js    7.6 KiB       6  [emitted]  pageA
Entrypoint pageA = react.js commons~pageA~pageB.js pageA.js
Entrypoint pageB = react.js commons~pageA~pageB.js pageB.js
Entrypoint pageC = react.js commons~pageC~pageD.js pageC.js
Entrypoint pageD = react.js commons~pageC~pageD.js pageD.js
   [2] ./src/cd_d.js 271 bytes {1} [built]
   [3] ./src/cd_c.js 227 bytes {1} [built]
   [4] ./src/ab_b.js 197 bytes {2} [built]
   [5] ./src/ab_a.js 453 bytes {2} [built]
   [9] ./src/D.jsx 2.49 KiB {3} [built]
  [10] ./src/C.jsx 2.49 KiB {4} [built]
  [11] ./src/B.jsx 2.49 KiB {5} [built]
  [12] ./src/A.jsx 2.49 KiB {6} [built]
  [21] multi react react-dom 40 bytes {0} [built]
    + 13 hidden modules
```

I'm not sure if it's a bug or a configuration problem. `splitChunks` does not work the same way as CCP. @sokra Is it how chunks should be defined?

**Comment by tanguy29** [comment]
May be you're  right, but how to control common chunks ? I have a project with many reusables chunks... These chunks are generated in a controlled way... With the new version it seems that the splitchunks do it in his own way ... In this case how to use commun chunk across module in a controlled way ? How to use correctly the manifest.json ?

**Comment by ooflorent** [comment]
Do not worry about common chunks. Prior v4 you had to create them yourself. In v4, webpack automagically creates them for you. Then you have to read the `stats` object to discover the generated entry points.

**Comment by tanguy29** [comment]
May be, but for big application it's becoming a problem ...

**Comment by tanguy29** [comment]
Yes, you'r rights. But actually i 'm in multipages configuration. What i want to achieve is to mutualize through pages. Exemple : 
pageA.html depends from a main application A.js and a common.js
pageB.html depends from a main application B.js and a common.js
For that i have to explicitly generates common.js.
Or, like you suggests i have to re-thinks in terms of "splitChunks"... but for the moment i'm running out of ideas ...

**Comment by sokra** [comment]
Remove all entries except the pages itself. Use `splitChunks.chunks: "all"`

**Comment by tanguy29** [comment]
After much more research, this configuration is working like a charm:

```
const webpack = require('webpack');
const path = require('path');
const ManifestPlugin = require('webpack-manifest-plugin');

var PROD = JSON.parse(process.env.PROD_ENV || '0');

const groupsOptions = {chunks: "all", minSize:0, minChunks: 1, reuseExistingChunk: true, enforce: true};

const reactConfig = {
    entry: {
        "pageA": "./src/A.jsx",
		"pageB": "./src/B.jsx",
        "pageC": "./src/C.jsx",
        "pageD": "./src/D.jsx"
    },
    output: {
        path: __dirname + '/build/',
        filename: PROD
            ? "[name].min.js"
            : "[name].js"
    },
    module: {
        rules: [
            {
                test: /\.jsx$/,
                use: {
                    loader: "babel-loader",
                    options: {
                        presets: ["es2015", "react"]
                    }
                }
            }
        ]
    },
    optimization: {
        splitChunks: {
            chunks: 'all',
            name : false,
            cacheGroups:{
                react: {test:/react/, name: "react", ...groupsOptions},
                AB: {test:/ab_a.js/, name: "commonAB", ...groupsOptions},
                AB: {test:/ab_b.js/, name: "commonAB", ...groupsOptions},
                CD: {test:/cd_c.js/ , name: "commonAB", ...groupsOptions},
                CD: {test:/cd_d.js/, name: "commonCD", ...groupsOptions}
            }
        }
    },
    plugins: [
        new ManifestPlugin({})
    ]
};
```
producing the desired output :
```
> npm run build

> testcommon@1.0.0 build D:\dev\testCommon
> webpack --config src.config.js --colors --progress --watch --mode development

  0% compiling
Webpack is watching the files…
                                                                                                                                                                                                                                  Hash: 3ab0d2c347627bd736f0
Version: webpack 4.4.1
Time: 1917ms
Built at: 2018-4-3 10:26:02
        Asset       Size    Chunks             Chunk Names
  commonAB.js  657 bytes  commonAB  [emitted]  commonAB
  commonCD.js  987 bytes  commonCD  [emitted]  commonCD
     pageA.js   34.7 KiB     pageA  [emitted]  pageA
     pageB.js   34.7 KiB     pageB  [emitted]  pageB
     pageC.js   34.4 KiB     pageC  [emitted]  pageC
     pageD.js   34.4 KiB     pageD  [emitted]  pageD
     react.js    655 KiB     react  [emitted]  react
manifest.json  196 bytes            [emitted]
Entrypoint pageA = react.js commonAB.js pageA.js
Entrypoint pageB = react.js commonAB.js pageB.js
Entrypoint pageC = react.js commonCD.js pageC.js
Entrypoint pageD = react.js commonCD.js pageD.js
[./src/A.jsx] 2.49 KiB {pageA} [built]
[./src/B.jsx] 2.49 KiB {pageB} [built]
[./src/C.jsx] 2.49 KiB {pageC} [built]
[./src/D.jsx] 2.49 KiB {pageD} [built]
[./src/ab_a.js] 191 bytes {pageB} {pageA} [built]
[./src/ab_b.js] 116 bytes {commonAB} [built]
[./src/cd_c.js] 148 bytes {pageD} {pageC} [built]
[./src/cd_d.js] 191 bytes {commonCD} [built]
```
Which is simplier than previous CCP. Now i suppose i should work async ;-) ... 
Thanks to all !

**Comment by ooflorent** [comment]
I would suggest you to add `runtimeChunk: "single"`. It would produce a new entrypoint called `runtime.js` that is shared between all pages.

**Comment by tanguy29** [comment]
Yes ! To avoid hashes change everytime a piece of code change ? am i alright ?

**Comment by ooflorent** [comment]
> To avoid hashes change everytime a piece of code change ?

That is one of the reason. The other one is to save 4KB per entry.

**Comment by tanguy29** [comment]
yep ! I owe you a beer !

**Comment by deleteme** [comment]
Can the runtime.js file be designated to be moved into a single existing common chunk?

Or better yet, can a chunk group be designated to receive the Webpack runtime?

**Comment by mlrsoft** [comment]
@tanguy29 
Hi, is there typo's in the cacheGroups definition or is there some special extra processing going on?
Im asking because the value of the property names 'AB' and 'CD' on the cacheGroups object is duplicated, which normally result in the last entry taking precedence and the other being ignored.
eg.
```
AB: {test:/ab_a.js/, name: "commonAB", ...groupsOptions},
CD: {test:/cd_c.js/ , name: "commonAB", ...groupsOptions}
```
is being overwritten by the next entry with same property name.
```
AB: {test:/ab_b.js/, name: "commonAB", ...groupsOptions},
CD: {test:/cd_d.js/, name: "commonCD", ...groupsOptions}
```
so
```
cacheGroups:{
                react: {test:/react/, name: "react", ...groupsOptions},
                AB: {test:/ab_a.js/, name: "commonAB", ...groupsOptions},
                AB: {test:/ab_b.js/, name: "commonAB", ...groupsOptions},
                CD: {test:/cd_c.js/ , name: "commonAB", ...groupsOptions},
                CD: {test:/cd_d.js/, name: "commonCD", ...groupsOptions}
            }
```
would normally result in:
```
cacheGroups:{
                react: {test:/react/, name: "react", ...groupsOptions},
                AB: {test:/ab_b.js/, name: "commonAB", ...groupsOptions},
                CD: {test:/cd_d.js/, name: "commonCD", ...groupsOptions}
            }
```
could be you meant:
```
cacheGroups:{
                react: {test:/react/, name: "react", ...groupsOptions},
                AB: {test:/ab_(a|b).js/, name: "commonAB", ...groupsOptions},
                CD: {test:/cd_(c|d).js/, name: "commonCD", ...groupsOptions}
            }

```

**Comment by mlrsoft** [comment]
@tanguy29 
Hi, is there typo's in the cacheGroups definition or is there some special extra processing going on?
Im asking because the value of the property names 'AB' and 'CD' on the cacheGroups object is duplicated, which normally result in the last entry taking precedence and the first being ignored.
eg.
```
AB: {test:/ab_a.js/, name: "commonAB", ...groupsOptions},
CD: {test:/cd_c.js/ , name: "commonAB", ...groupsOptions}
```
is being overwritten by the next entry with same property name.
```
AB: {test:/ab_b.js/, name: "commonAB", ...groupsOptions},
CD: {test:/cd_d.js/, name: "commonCD", ...groupsOptions}
```
so
```
cacheGroups:{
                react: {test:/react/, name: "react", ...groupsOptions},
                AB: {test:/ab_a.js/, name: "commonAB", ...groupsOptions},
                AB: {test:/ab_b.js/, name: "commonAB", ...groupsOptions},
                CD: {test:/cd_c.js/ , name: "commonAB", ...groupsOptions},
                CD: {test:/cd_d.js/, name: "commonCD", ...groupsOptions}
            }
```
would normally result in:
```
cacheGroups:{
                react: {test:/react/, name: "react", ...groupsOptions},
                AB: {test:/ab_b.js/, name: "commonAB", ...groupsOptions},
                CD: {test:/cd_d.js/, name: "commonCD", ...groupsOptions}
            }
```
could be you meant:
```
cacheGroups:{
                react: {test:/react/, name: "react", ...groupsOptions},
                AB: {test:/ab_(a|b|c).js/, name: "commonAB", ...groupsOptions},
                CD: {test:/cd_d.js/, name: "commonCD", ...groupsOptions}
            }
```
or 
```
cacheGroups:{
                react: {test:/react/, name: "react", ...groupsOptions},
                AB: {test:/ab_(a|b).js/, name: "commonAB", ...groupsOptions},
                CD: {test:/cd_(c|d).js/, name: "commonCD", ...groupsOptions}
            }
```
