### ISSUE TITLE
webpack-dev-server not working with Webpack 4+

### ISSUE THREAD

**Issue by FlamesoFF** [webpack/webpack#6917]
**Info:**
```
"webpack": "^4.4.1",
 "webpack-cli": "^2.0.13",
"webpack-dev-server": "^2.11.2"
```
Node: v8.10.0
Npm: 5.6.0

**Config:**
 ```
devServer: {
            contentBase: path.join(__dirname, "dist/app"),
            index: 'index.html',
            compress: true,
            port: 9000,
            allowedHosts: [
                'https://fonts.googleapis.com'
            ]
        },
```

**What is the current behavior?**
After running npm script `webpack-dev-server --port 3000`
I getting this:
```
> webpack-dev-server --port 3000

module.js:549
    throw err;
    ^

Error: Cannot find module 'webpack/bin/config-yargs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (************\node_modules\webpack-dev-server\bin\webpack-dev-server.js:54:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**What is the expected behavior?**
Must work, damn it :)

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by ooflorent** [comment]
`webpack-dev-server` v2 requires webpack v3.

**Comment by FlamesoFF** [comment]
@ooflorent And how a user supposed to know that?

**Comment by ooflorent** [comment]
There are multiple places where is it written.

- The release note:
    > **Breaking change:** webpack v4 is now supported. Older versions of webpack are **not** supported.

- The installation warning:
    ```
    warning " > webpack-dev-server@2.11.2" has incorrect peer dependency "webpack@^2.2.0 || ^3.0.0".
    warning "webpack-dev-server > webpack-dev-middleware@1.12.2" has incorrect peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0".
    ```

**Comment by 0paIescent** [comment]
Not sure if this issue was resolved for you @FlamesoFF but I had the same problem. I've got webpack 4.6.0 and after reinstalling webpack-cli 2.0.15 it worked. Maybe uninstalling the package and reinstalling would do it for you.

**Comment by otroboe** [comment]
I can confirm, somehow maybe it's related.
Watching my files was not working anymore, since update to `webpack-cli 2.0.15`

I did that:
```
yarn remove webpack-cli
yarn add webpack-cli
```
And it's working again.

**Comment by FlamesoFF** [comment]
@ooflorent It was confusing, because at that moment the command `npm install webpack-dev-server@latest` gave me version something 2.x.x, but not 3.0.0.
That''s very strange at all, that your official plugin not synchronized with the webpack itself. 
Or if it's not official, why you haven't your own? That's very bizzare development approach, I would say.

**Comment by aguilarkimduron** [comment]
Change the following webpack versions to:
"webpack": "^4.32.2",
"webpack-cli": "^3.3.0",
"webpack-dev-server": "^3.11.0"

Run npm remove webpack webpack-cli webpack-dev-server
Run npm install
hope this help.
