### ISSUE TITLE
Problem  about Webpack DLL Plugin Module definition

### ISSUE THREAD

**Issue by gsmlg** [webpack/webpack#6927]
**Do you want to request a *feature* or report a *bug*?**
webpack DLL module define that using eval offent trigger browser bugs.

**What is the current behavior?**
DLL plugin define modules by using eval, that offen got memory leaks.

**If the current behavior is a bug, please provide the steps to reproduce.**
Using eval got memory leaks on binding dom events, etc.

**What is the expected behavior?**
Change Module define method in DLL

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

**Comment by sokra** [comment]
I don't understand your issue. Can you please give more details?

**Comment by gsmlg** [comment]
I found out that webpack dll plugin use `eval` to define a module.

Some module got momery leaks in `eval`.
*Redux immutable in Redux replaceReducer got memory leak in Chrome and Firefox*

I just suggest do not use `eval`.
