### ISSUE TITLE
Support for RequireJS configuration?

### ISSUE THREAD

**Issue by SomethingSexy** [webpack/webpack#693]
This might be a pretty dumb question and a simple no but I couldn't find a definitive answer. We have a few large AMD/RequireJS applications that I would love to try to switch over to using webpack for optimization and building.  My biggest concern though (because of requirements for the project) is the app utilizes the RequireJS map configuration for replacing/extending files.  Does webpack take into account RequireJS configuration when building or am I screwed?

Does webpack support something similar to the RequireJS map configuration? Is there something in the resolve configuration for that?

**Comment by sokra** [comment]
> Does webpack take into account RequireJS configuration when building or am I screwed?

No.

> Does webpack support something similar to the RequireJS map configuration? Is there something in the resolve configuration for that?

Yes. see http://webpack.github.io/docs/configuration.html#resolve

**Comment by jhnns** [comment]
Afaik every AMD feature can be replaced by a webpack feature. The most important features are:

- [Alias](http://webpack.github.io/docs/configuration.html#resolve-alias)
- [imports-and exports-loader for shimming modules](http://webpack.github.io/docs/shimming-modules.html)

**Comment by SomethingSexy** [comment]
Perfect, thanks for the answer guys!  So I would need to convert my requirejs config over to webpack configuration and that should allow me to build my existing application as I understand it?

**Comment by sokra** [comment]
yep
