### ISSUE TITLE
Chunk missing from runtime with `splitChunks.chunks: 'all'`.

### ISSUE THREAD

**Issue by robrichard** [webpack/webpack#6931]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
With `splitChunks.chunks: all` and the runtime chunk enabled, webpack attempts to load a chunk with id `1` that does not exist in the runtime. This causes the browser to make a request for a file with `undefined` in the file name.

**If the current behavior is a bug, please provide the steps to reproduce.**
excerpt from runtime chunk (notice a value for `1` is missing)
```
c.src = n.p + "buyer-mobile-" + ({
                    0: "vendors~AddToFolderModalWrapper~MultiRequestModal~PdpSharedCallDealerModalWrapper~PdpSharedDealerDet~a4eb5b0f",
                    2: "vendors~AddToFolderModalWrapper~MultiRequestModal~PdpSharedCallDealerModalWrapper~PdpSharedDealerDet~0160e5e7",
                    3: "SendToFriendModal",
                    4: "vendors~AuthModal",
                    5: "vendors~contactDealerModal~makeOfferModal",
                    6: "vendors~MultiRequestModal~PdpSharedShippingModal",
                    7: "vendors~AddToFolderModalWrapper",
                    8: "HeartWrapper",
                    9: "FolderWrapper",
                    10: "vendors~PromoCode",
                    11: "vendors~PdpSharedReturnModalWrapper",
                    12: "vendors~PdpSharedDepositModal",
                    13: "vendors~PdpSharedCallDealerModalWrapper",
                    14: "vendors~SendToFriendModal",
                    15: "makeOfferModal",
                    16: "MultiRequestModal",
                    17: "contactDealerModal",
                    18: "Tooltip",
                    19: "PdpSharedDealerDetailsForm",
                    20: "PdpSharedCallDealerModalWrapper",
                    21: "PdpSharedDepositModal",
                    22: "PdpSharedReturnModalWrapper",
                    23: "PdpSharedShippingModal"
                }[e] || e) + ".22.2.3." + {
                    0: "ccb05bcff0aa6a99b2e7",
                    2: "11a119f3717cd6021207",
                    3: "9e105ec932afdde82d01",
                    4: "da6beda689ba103c5099",
                    5: "4f56362323a48e953940",
                    6: "1b0ffbf9b201496b1aac",
                    7: "fd6c26f3d0b66ca045f5",
                    8: "ac02aedf4e7ebf17cd4f",
                    9: "bb6aa0b00d34d188f412",
                    10: "c1600a73ffa818ed9ec0",
                    11: "8be6a40bd61ccf1be0ce",
                    12: "72adf7d1745529bf94cf",
                    13: "cbb17b373c5f0d1b9978",
                    14: "91d39166c3892aaf06f3",
                    15: "28fcd43162430c15c3b0",
                    16: "8c55d42d090d0cea713a",
                    17: "4cec2bc64cf1e45720a3",
                    18: "3a5e48e4087a68518379",
                    19: "9582389b03ca36f312f2",
                    20: "7a2c8ad948ea9b629fab",
                    21: "4b24ed1030a4138a4ece",
                    22: "49079b7ccb4430d87c04",
                    23: "572a0bef69e88c7ae352"
                }[e] + ".js";
```
The browser tries to load `buyer-mobile-1.22.2.3.undefined.js`

Full stats are here: https://1stdibs-webpack-dev.s3.amazonaws.com/app-buyer-mobile-7c5a1250-3688-11e8-bb67-0592031a8a2e.json

**What is the expected behavior?**
Browser should successfully load the chunk

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
webpack 4.4.1, node v8.9.3, linux

**Comment by Legends** [comment]
Can you create a minimum reproducible test repo?

**Comment by robrichard** [comment]
I have not been able to create a minimum reproducible test repo yet as I have not yet figured out what specifically in my compilation is triggering this issue. I have debugged enough to understand the basic reason for this problem.

#### EntryPoint
* `pdp-mobile`
* * does not contain `chunkId 1`
* `sb-mobile`
* * contains `chunkId 1`

#### ChunkGroups
* `MultiRequestModal`
* * contains `chunkId 1`

When the `MultiRequestModal` async chunk is loaded on the `pdp-mobile` page, webpack attempts to load `chunkId 1` because it is a requirement of that chunk and not already loaded. However, the runtime `chunkMap` does not contain `chunkId 1` because it is excluded by `Chunk#getAllAsyncChunks` when it is generated (because it is part of the sb-mobile EntryPoint). 

Is it normal for a chunk to be a dependency of both an entry point and an async chunk?

**Comment by robrichard** [comment]
@Legends I was able to create a minimum reproducible test repo here: https://github.com/robrichard/webpack-splitchunks

**Comment by Legends** [comment]
This looks like a bug to me.
It works in `--mode development`.
In `--mode production` it only works when:

```
optimization: {
        runtimeChunk: "multiple" | true  // <-- "single" fails here!
```

A core team member will take care of this.
