### ISSUE TITLE
process.env.NODE_ENV be replaced when  target node

### ISSUE THREAD

**Issue by lerit** [webpack/webpack#6934]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
i use webpack for pack my nodejs application,it work fine before webpack4.
i have some code in nodejs '**process.env.NODE_ENV**',before webpack4,it was not replaced by webpack at compile time,but after update to webpack4,it was replaced with 'production' or 'development' constant  at compile time.

**If the current behavior is a bug, please provide the steps to reproduce.**
write some nodejs code that contain code  'process.env.NODE_ENV',build with webpack (target:node),you will see the bug

**What is the expected behavior?**
'process.env.NODE_ENV' not be replaced  when target node
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
nodejs:8.9.4
webpack:4.4.1

**Comment by nveenjain** [comment]
Actually, it's intended. https://webpack.js.org/concepts/mode/ mode NODE_ENV is set as per the mode supplied to webpack.  By default we use production mode, so it might be replaced with production.

**Comment by ooflorent** [comment]
Set `optimization.nodeEnv=false` to disable this.

**Comment by jamesdixon** [comment]
I just ran into this when using webpack for bundling Lambda functions via Serverless. I currently use `NODE_ENV` to toggle whether I'm using TLS for Redis and couldn't for the life figure out why `NODE_ENV` was always `production`.

Is it really necessary to set `NODE_ENV=production`?  Some value I may be missing?

**Comment by lerit** [comment]
you can Set optimization.nodeEnv=false ,so you node_env will not be replace

**Comment by jamesdixon** [comment]
I did but I don't necessarily want to lose all of the node optimizations even though I don't know exactly what they do...lol
