### ISSUE TITLE
why sourceURL with a hash string after set devtools value to be 'source-map'?

### ISSUE THREAD

**Issue by TastySummer** [webpack/webpack#6936]
![image](https://user-images.githubusercontent.com/13374074/38228280-1d2e0518-3735-11e8-9ea7-2bd274fcf6b0.png)

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
