### ISSUE TITLE
Error in output code when using 6to5-loader with coreAliasing

### ISSUE THREAD

**Issue by roman01la** [webpack/webpack#694]
I'm using `6to5-loader` with `coreAliasing` and getting the following error in browser's console:
```
Uncaught TypeError: Cannot read property 'TypeError' of undefined
```
It's referencing to `TypeError = _core.global.TypeError` inside of `core-js` module. `_core` object appears to be empty.

Try this [project](https://github.com/chicoxyzzy/real-world-react/tree/webpack) to reproduce error.

**Comment by Dashed** [comment]
Shouldn't this be reported to https://github.com/6to5/6to5-loader/?

**Comment by roman01la** [comment]
Ah, yes, sure.
