### ISSUE TITLE
jQuery dependency errors when using DllPlugin

### ISSUE THREAD

**Issue by hanxue** [webpack/webpack#6947]
**What is the current behavior?**

Using the DllPlugin will result in jQuery errors when running the built application

```
$ npm run dll && npm run dev
```

![image](https://user-images.githubusercontent.com/760008/38283626-94b34c38-37e9-11e8-998f-4eb2f0a9db44.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

The relevant node and webpack configuration files has been uploaded to https://gist.github.com/362e0a1a2d856d392688e47a251f4a22

In `webpack.base.dll.js` it uses `dependencies.dll.js`

```js
module.exports = {
  context: path.resolve(__dirname, '../'),
  entry: {
    app: './src/main.js',
  },
  output: {
    path: config.build.assetsRoot,
    library: '[name]_[hash]',
    filename: '[name].dll.js',
    publicPath: process.env.NODE_ENV === 'production'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath
  },
```

The relevant code in `webpack.dll.config.js`

```js
module.exports = {
  mode: 'development',
  context: process.cwd(),
  entry: {
    dependencies: [ //Object.keys(pkg.dependencies),
      'vue',
      'vue-material',
      'vue-router',
      'vuetable-2',
      'vuelidate',
      'handsontable',
      'chart.js',
      'vue-chartjs',
      'accounting',
      'semantic-ui-css',
      '@handsontable/vue',
    ],
output: {
    filename: "[name].dll.js",
    path: outputPath,
    library: "[name]",
  },

  plugins: [
    new webpack.DllPlugin({
      context: __dirname,
      name: "[name]",
      path: path.join(outputPath, "[name].dll.manifest.json"),
    }),
  ],
}
```

**What is the expected behavior?**

All dependencies should be generated and available in `dist/dependencies.dll.manifest.json`

### Environment

Node: v9.8.0
Yarn: 1.5.1
Webpack: 4.2.0

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by hanxue** [comment]
@sokra , I went through each dependency, and realized the problem occurs when I use `vue` and `vue-template-compiler` version `2.5.16`. Downgrading to version `2.5.2` for both will get rid of the jquery problem. 

I am still trying to reproduce the error starting from a clean https://github.com/vuejs-templates/webpack-simple project

**Comment by sokra** [comment]
Try to report it to the vue-template-compiler
