### ISSUE TITLE
Can't find the documents for SplitChunks

### ISSUE THREAD

**Issue by Shurlormes** [webpack/webpack#6949]
Is there any SplitChunks's document In https://webpack.js.org?

I found that CommonsChunkPlugin is still in the document.

https://webpack.js.org/plugins/commons-chunk-plugin/#src/components/Sidebar/Sidebar.jsx

Can someone update the document?

**Comment by ooflorent** [comment]
Please open an issue on [webpack/webpack.js.org](https://github.com/webpack/webpack.js.org/issues) repository.

**Comment by montogeek** [comment]
@webpack-bot move to webpack/webpack.js.org

**Comment by montogeek** [comment]
@webpack-bot move to webpack/webpack.js.org
