### ISSUE TITLE
Bulk require

### ISSUE THREAD

**Issue by thetutlage** [webpack/webpack#695]
Is there any way to require directories , something like https://www.npmjs.com/package/bulkify

**Comment by nelix** [comment]
http://webpack.github.io/docs/context.html covers some of this, basically you can called require.context('./things', regex).keys() and then require those keys

**Comment by thetutlage** [comment]
That seems to be good , thanks

**Comment by chrishomer** [comment]
This unfortunately breaks server-side.  For an isomorphic app, is there a way to have require.context work?
