### ISSUE TITLE
same code but different hash

### ISSUE THREAD

**Issue by rubyisapm** [webpack/webpack#6957]
Hi! I have a project, I didn't change any files, including filename or npm package version or anything else in this project. I build it for some times, I fond that the hash would change between different build, for example, first time, it could be 52f1b7c21d1cac97c391, second time, it could be 4eddd256ca6c410a6251, third time, it could be 4eddd256ca6c410a6251, but forth time, it could be 52f1b7c21d1cac97c391 again~~~~  Is that correct? Thank you.

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by montogeek** [comment]
Probably fixed by https://github.com/webpack/webpack/pull/6943, try with next version, if problem persist please submit an issue.
