### ISSUE TITLE
link in sample page leads nowhere -> "move-to-parent "

### ISSUE THREAD

**Issue by budarin** [webpack/webpack#6959]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I see a link but it leads nowhere
**If the current behavior is a bug, please provide the steps to reproduce.**
yes

**What is the expected behavior?**
a page with a sample
**If this is a feature request, what is motivation or use case for changing the behavior?**
I want to know how to move common modules from child bundles to parent.
I have not found it in docs
**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

**Comment by montogeek** [comment]
Which sample page?

**Comment by montogeek** [comment]
Which link?

**Comment by budarin** [comment]
https://github.com/webpack/webpack/tree/master/examples
section: Chunk
item: move-to-parent

**Comment by sokra** [comment]
Send a PR

**Comment by montogeek** [comment]
@budarin That example got removed in https://github.com/webpack/webpack/commit/18ae73dad4bb761593a9f5529a182601e1b57520

@sokra It is still possible? Commit message says
> remove moveToParent from AggressiveMergingPlugin

**Comment by budarin** [comment]
@sokra 
If if I knew how - I would send it without looking through the whole internet for an example or explanation

**Comment by montogeek** [comment]
@budarin You can see here how it was done in webpack 3 https://github.com/webpack/webpack/commit/18ae73dad4bb761593a9f5529a182601e1b57520#diff-f2c50caf4dbed7d790a21568c8c98296

**Comment by budarin** [comment]
but I need it in webpack 4

**Comment by budarin** [comment]
My config:

```js
mode: 'production',
    target: 'web',
    cache: true,
    entry: {
        client: './src/client/index.js',
    },
    output: {
        path: path.resolve('./dist'),
        filename: '[name].[hash].js',
        chunkFilename: '[name].[chunkhash].chunk.js',
        publicPath: '/',
    },
    // devtool: 'inline-cheap-module-source-map',
    optimization: {
        splitChunks: {
            cacheGroups: {
                vendor: {
                    test: /[\\/]node_modules[\\/]/, // you may add "vendor.js" here if you want to
                    name: 'vendor',
                    chunks: 'all',
                    enforce: true,
                },
            },
        },
        runtimeChunk: {
            name: 'runtime',
        },
        minimizer: [new MinifyPlugin(), new OptimizeJsPlugin({ sourceMap: false })],
        occurrenceOrder: true,
    },
```
below the result - a lot of common code in many bundles


![Uploading 2.png…]()
![Uploading 3.png…]()

**Comment by budarin** [comment]
![1](https://user-images.githubusercontent.com/8055157/39129001-ee874f70-4711-11e8-947f-9524b321e315.png)

**Comment by budarin** [comment]
![2](https://user-images.githubusercontent.com/8055157/39129028-0236395a-4712-11e8-8974-6fcce65c0e13.png)

**Comment by budarin** [comment]
producing a lot of async common chunks may be usefull for novices, but we dont use webpack in a wild 
  - we need full control over our bundles to dynamically include them into HTML on server side
  - also we need to minimize all amount of connections on mobiles.
  - and the last thing - we use PWA so we dont need to use the default webpack's behaviour for novices - we need to have full control over producing bundles and have minimal count of bundles - one per route
