### ISSUE TITLE
Webpack config function export error in express server / fails with Invalid configuration object

### ISSUE THREAD

**Issue by yyynnn** [webpack/webpack#6960]
**Do you want to request a *feature* or report a *bug*?**
This is a misfeature(?)

**What is the current behavior?**
Function export fails with
```
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration should be an object.
```
When using webpack/webpackMiddleware in express server import.
With regular object export - it works.
With webpack-dev-server function export works like a charm too.

**If the current behavior is a bug, please provide the steps to reproduce.**
Error logs right after this
 `var compiler = webpack(webpackConfig)`

**What is the expected behavior?**
Want working webpack config with function export in express server

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
webpack 4.5.0

**Comment by sokra** [comment]
What's the value of `webpackConfig`?

**Comment by ooflorent** [comment]
@sokra It's a function.
@yyynnn it's not a bug. `webpack` function does not accept a function. You must run it manually:

```js
const compiler = webpack(webpackConfig())
```

**Comment by Kovensky** [comment]
I'd argue that it's a misfeature of `webpack-cli`. Config loading should ideally be put in core, not in CLI; this leads a lot of projects all having to figure out how to be compatible with how `webpack-cli` loads configs.

A webpack 2 config function can expect up to 2 arguments; eslint-plugin-import's webpack config loader doesn't pass any arguments, your example code doesn't pass any arguments either. The function is also allowed to return a Promise in webpack 3, but that doesn't support the Promise case either. `webpack-serve` doesn't support function configs at all.

**Comment by yyynnn** [comment]
@ooflorent  Thank you. So this worked
`compiler = webpack(webpackConfig())`
i can pass e.g. `env` as an argument

**Comment by shellscape** [comment]
This is a deficit in the webpack documentation. The CLI supports both `function` and `Promise` types, but the documentation for webpack makes no mention of that. At the very least we need to get documentation up to date.

_Below the surface, choosing to allow different config export types between the API and CLI was a poor architectural choice, and not having those two in sync is a negative for the user experience. I'm working on a common config utility to handle all of the supported cases between the CLI and API correctly in one unified module._

**Comment by V1shvesh** [comment]
Can I help fix this issue?

**Comment by mahaveer0496** [comment]
If its still open can i help ?

**Comment by mszczepanczyk** [comment]
Oh man. I've just spent literally hours trying to debug it. Even started to update typescript typing along the way.

Here's a doc update: https://github.com/webpack/webpack.js.org/pull/2890

**Comment by evilebottnawi** [comment]
Somebody can create minimum reproducible test repo?

**Comment by MarchWorks** [comment]
The issue template should require a minimum reproduction repo because its really help

**Comment by ndeviant** [comment]
Too bad that this is closed. So there is no intension to have consistent export types between CLI and API? Or maybe there is another opened issue similar to this, so we can subscribe to updates? 
I totally agree with @shellscape :

> Below the surface, choosing to allow different config export types between the API and CLI was a poor architectural choice, and not having those two in sync is a negative for the user experience.

**Comment by evilebottnawi** [comment]
@ndeviant webpack@5 has API to fix it, so the next major release of webpack-cli fix these problems
