### ISSUE TITLE
Bug Report: Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by Hyurl** [webpack/webpack#6963]
webpack 4.5.0
webpack-cli 2.0.14

Observed behavior
Uncaught ReferenceError: global is not defined
    at :10:4

Desired behavior
There is a bug when packing to `umd`, webpack passes the variable `global` to the function
`webpackUniversalModuleDefinition()`, while the browser doesn't have this variable pre-defined, the
variable `window` should be passed instead, please fix this bug as soon as possible, I assume many users
are suffering from this problem.

The argument should be passed as `typeof window === 'object' ? window : global`

Bellow is the generated code for now:

    (function webpackUniversalModuleDefinition(root, factory) {
        if(typeof exports === 'object' && typeof module === 'object')
            module.exports = factory();
        else if(typeof define === 'function' && define.amd)
            define([], factory);
        else {
            var a = factory();
            for(var i in a) (typeof exports === 'object' ? exports : root)[i] = a[i];
        }
    })(global, function() { ... })

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
