### ISSUE TITLE
Question: Is it possible to acccess the [chunkHash] of a file?

### ISSUE THREAD

**Issue by AvraamMavridis** [webpack/webpack#6964]
**Do you want to request a *feature* or report a *bug*?**

Feature

**If this is a feature request, what is motivation or use case for changing the behavior?**

Imagine you have the following function:

```
  async setMessages(props) {
    let { locale } = props;
    const { id } = props;
    let messages;

    try {
      // try to load messages
      messages = await import('./translation.json');
    } catch (error) {
     console.log(error)
    }
    this.setState({ messages });
  }
```

This will generate a new chunk for the translation file which is just a json file (and you can have many different files e.g. per page or component). What I want to achieve is to store the messages to the localstorage, if the messages are not there do the actual fetch request, something like:

```js
localstorage.setItem('[chunkHash]', JSON.stringify(messages))
```

So my question is, is there a way to access/refer to the `[chunkHash]` of a file?

**Comment by mc-zone** [comment]
FYI, how about generate a manifest for your assets ([webpack-manifest-plugin](https://github.com/danethurber/webpack-manifest-plugin))? then you can add it to your page.

**Comment by AvraamMavridis** [comment]
@montogeek I deleted the irrelevant parts. Because this is mostly a question, and not so much an issue.

**Comment by Pymous** [comment]
@AvraamMavridis : Which have a specific part for you : 
`<!-- Please ask questions on StackOverflow or the webpack Gitter (https://gitter.im/webpack/webpack). -->`

That's why it exist ^^
