### ISSUE TITLE
Bug Report: Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by Hyurl** [webpack/webpack#6965]
**Do you want to request a *feature* or report a *bug*?**

report **BUG**.

**What is the current behavior?**

```
Uncaught ReferenceError: global is not defined
```

**If the current behavior is a bug, please provide the steps to reproduce.**

The following code is generated by the current version of webpack 4.5.0 when packing to `umd`:

```js
(function webpackUniversalModuleDefinition(root, factory) {
  if(typeof exports === 'object' && typeof module === 'object')
    module.exports = factory();
  else if(typeof define === 'function' && define.amd)
    define([], factory);
  else {
    var a = factory();
    for(var i in a) (typeof exports === 'object' ? exports : root)[i] = a[i];
  }
})(global, function() { … })
```

**What is the expected behavior?**

The first argument passed to `webpackUniversalModuleDefinition()` should be 

```js
typeof window === 'object' ? window : global
```

Otherwise, since the browser doesn't have a `global` variable, the error will thrown. 

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

I've tried in several browsers, and they all don't have the variable `global`, so please fix this bug as soon as possible, I assume many users are suffering from this problem.

And hope this time I post the issue in a right way, since I delete the comments that wrapped with 
`<!-- -->`, which are always considered to be replaced.

**Comment by ooflorent** [comment]
I don't understand why you have `global`. What is your build target? Is it `web`?

**Comment by Hyurl** [comment]
The `target` is 'node', and the `output.libraryTarget` is `umd`, I've done some research on other projects, they're using webpack 2.X, and the argument passed is `this` (which is good), I don't know why and how now webpack 4.X has changed it to `global`, please review the source code, I think this is a simple but very serious problem.

**Comment by ooflorent** [comment]
Since your target is `node`, `globalObject` is `global` which is defined by node. This is the expected behavior. You can change the global object using `output.globalObject` config option.

**Comment by danieldanielecki** [comment]
In case, if your **target** is **node** in webpack (`target: 'node'`), because you want to fix `"Can't resolve 'fs'`. Then you're getting the following error `Fix: "Uncaught ReferenceError: global is not defined"` do it as follows `node: { global: true, fs: 'empty' }`. **Bonus**: if you got error `"Uncaught ReferenceError: exports is not defined".` simply add `libraryTarget: 'umd'`. The complete webpack config code is below.

```
const webpackConfig = {
  node: { global: true, fs: 'empty' }, // Fix: "Uncaught ReferenceError: global is not defined", and "Can't resolve 'fs'".
  output: {
    libraryTarget: 'umd' // Fix: "Uncaught ReferenceError: exports is not defined".
  }
};

module.exports = webpackConfig; // Export all custom Webpack configs.
```
