### ISSUE TITLE
TypeError: object is not a function Tapable Compiler error

### ISSUE THREAD

**Issue by natew** [webpack/webpack#697]
Ran into this today using 1.5.1, just wondering where to start figuring out whats going on:

Webpack config:
```
{ entry: { main: './app/app.js' },
  output: 
   { path: '/Users/nw/projects/reapp/reapp-kitchen/build/public',
     filename: '[name].js',
     chunkFilename: '[id].js',
     publicPath: '/',
     sourceMapFilename: 'debugging/[file].map',
     libraryTarget: undefined,
     pathinfo: true },
  target: 'web',
  module: 
   { loaders: 
      [ { test: /\.json$/, loader: 'json-loader' },
        { test: /\.png|jgp|jpeg|gif|svg$/,
          loader: 'url-loader?limit=10000' },
        { test: /\.html$/, loader: 'html-loader' },
        { test: /\.jsx?$/,
          loader: '6to5-loader?experimental=true&runtime=true',
          exclude: /socket\.io/ },
        { test: /\.css$/,
          loader: 'style-loader!css-loader!autoprefixer-loader?browsers=last 2 version' },
        { test: /\.styl$/,
          loader: 'style-loader!css-loader!autoprefixer-loader?browsers=last 2 version!stylus-loader' } ] },
  devtool: 'eval',
  debug: true,
  resolveLoader: 
   { root: 
      [ '/Users/nw/projects/reapp/reapp-kitchen/node_modules',
        '/Users/nw/projects/reapp/reapp-kitchen/server_modules' ],
     alias: {} },
  externals: [],
  resolve: 
   { root: [ '/Users/nw/projects/reapp/reapp-kitchen/app/app' ],
     modulesDirectories: [ 'web_modules', 'node_modules', 'server_modules', 'app' ],
     extensions: [ '', '.web.js', '.js', '.jsx' ],
     alias: {} },
  plugins: 
   [ { definitions: { to5Runtime: 'imports?global=>{}!exports-loader?global.to5Runtime!6to5/runtime' } },
     { request: 'react' },
     { request: 'react/lib/ReactComponentBrowserEnvironment' },
     { definitions: { 'process.env': { NODE_ENV: '"development"' } } } ] }
```

Output:
```
/Users/nw/projects/reapp/reapp-pack/node_modules/webpack/lib/Compiler.js:190
						return callback(null, stats);
						       ^
TypeError: object is not a function
    at Tapable.<anonymous> (/Users/nw/projects/reapp/reapp-pack/node_modules/webpack/lib/Compiler.js:190:14)
    at Tapable.emitRecords (/Users/nw/projects/reapp/reapp-pack/node_modules/webpack/lib/Compiler.js:277:37)
    at Tapable.<anonymous> (/Users/nw/projects/reapp/reapp-pack/node_modules/webpack/lib/Compiler.js:183:11)
    at /Users/nw/projects/reapp/reapp-pack/node_modules/webpack/lib/Compiler.js:270:11
    at Tapable.applyPluginsAsync (/Users/nw/projects/reapp/reapp-pack/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Tapable.afterEmit (/Users/nw/projects/reapp/reapp-pack/node_modules/webpack/lib/Compiler.js:267:8)
    at Tapable.<anonymous> (/Users/nw/projects/reapp/reapp-pack/node_modules/webpack/lib/Compiler.js:262:14)
    at done (/Users/nw/projects/reapp/reapp-pack/node_modules/webpack/node_modules/async/lib/async.js:135:19)
    at /Users/nw/projects/reapp/reapp-pack/node_modules/webpack/node_modules/async/lib/async.js:32:16
    at Object.oncomplete (fs.js:107:15)
```

**Comment by loganfsmyth** [comment]
How are you actually calling `webpack`/passing that config in? That error sounds like you're passing an object to as the second argument, where it is expecting a callback function.

**Comment by natew** [comment]
If I use that config directly with the CLI I get this one:

```
/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:166
		arguments[i].apply(this);
		             ^
TypeError: Object #<Object> has no method 'apply'
    at Tapable.apply (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:166:16)
    at OptionsApply.WebpackOptionsApply.process (/usr/local/lib/node_modules/webpack/lib/WebpackOptionsApply.js:61:18)
    at webpack (/usr/local/lib/node_modules/webpack/lib/webpack.js:15:47)
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack/bin/webpack.js:121:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

**Comment by natew** [comment]
@loganfsmyth where am I passing an object though? I have no idea what that object it, is there a way to get a better stack trace here?

**Comment by natew** [comment]
If I log out in Tapable.js:166 right before it prints out arguments[i], here's the last few lines before the error:

```
{ moduleType: 'loader-module',
  directories: [ 'node_loaders', 'node_modules' ] }
{ moduleType: 'loader-module',
  targetModuleType: 'node',
  templates: [ '*-loader', '*' ] }
{ moduleType: 'node' }
{ moduleType: 'node' }
{ filename: 'package.json', fields: [ 'loader', 'main' ] }
{ files: [ 'index' ] }
{ appendings: [ '.loader.js', '', '.js' ] }
{}
{ definitions: { to5Runtime: 'imports?global=>{}!exports-loader?global.to5Runtime!6to5/runtime' } }
```

Looks like maybe something to do with the 6to5 setup.

**Comment by natew** [comment]
Ok I see that error, I was passing an object as the callback to webpack().

**Comment by loganfsmyth** [comment]
That new error is more like what I expected. Your plugin array looks weird to me. Normally you'd explicitly  instantiate some instance of a plugin. You are passing a simple array of objects as plugins, which would cause the `Object #<Object> has no method 'apply'` error. 

For example: http://webpack.github.io/docs/using-plugins.html

**Comment by natew** [comment]
Yea, I had some old code but after the refactor was just calling webpack directly, but instead passing an old argument to it like so: webpack(myConfig, someOptionObject).

Probably could have a helpful error message here like "You've passed an object as the second argument to webpack, when it should be a callback function". Because unfortunately the stack trace I got there didn't really tell me where that was coming from.

**Comment by Frikki** [comment]
If an object in the plugins array provided to webpack is wrong, the same error

    /usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:166
        arguments[i].apply(this);
                     ^
    TypeError: Object #<Object> has no method 'apply'

is thrown.

It is incredibly hard to debug, and only this issue helped me find out that it was my plugins array that had a wrongly constructed object.

I don’t think the issue has been completely resolved by [4099f66](https://github.com/webpack/webpack/commit/4099f66141161ef65c201e007273158cc8333cc6), or perhaps this is another issue?

**Comment by micky2be** [comment]
Getting the same error due to my own plugin.
It's working if I use it as CLI (module.exports = config;) but crashes when using the node API (webpack(config)).

**Comment by micky2be** [comment]
So just tested 2 cases.
Using a plugin with apply written on the prototype fails:
```
function FileListPlugin(options) {}

FileListPlugin.prototype.apply = function(compiler) {
    console.log('Yeah');
};
```

While writing the function in the constructor works:
```
function FileListPlugin(options) {
    this.apply = function(compiler) {
        console.log('Yeah');
    };
}
```

No need to say that the former shouldn't break

**Comment by 0x80** [comment]
I just ran into a similar issue. A better error message would be welcome! 

I wanted to conditionally enable a plugin like this
```
enableHmr ? new webpack.HotModuleReplacementPlugin() : null,
```

Which resulted in this error:

```
/Users/me/project/node_modules/webpack/node_modules/tapable/lib/Tapable.js:164
    arguments[i].apply(this);
                ^

TypeError: Cannot read property 'apply' of null
    at Compiler.apply (/Users/me/project/node_modules/webpack/node_modules/tapable/lib/Tapable.js:164:15)
```

I solved it by creating a dummy plugin and passing that instead of null: `
var NO_PLUGIN = { apply: function() {} }`

It's a bit of a hack but I didn't feel like creating a new plugin array with just this one plugin difference. It would be nice if the plugins array allows for nulls to be passed for conditional plugins.

**Comment by jaulz** [comment]
@0x80 Just as a workaround: use .filter(Boolean) at the end of your plug-in definition in order to filter null values from your array. Having this makes the dummy plugin be redundant.

**Comment by 0x80** [comment]
@jaulz yes that would be more elegant, thanks 👍

**Comment by jbe456** [comment]
Run into this issue also by mistakenly having in my array of plugin another array of plugin instead of a plugin. A better message like "invalid plugin" would be great!
