### ISSUE TITLE
installedChunks generates syntax error from entry points with dot (".") in name

### ISSUE THREAD

**Issue by haggholm** [webpack/webpack#6971]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

One entrypoint in our system is called `witcrypt.webworker.js`. When producing a non-minified build, we end up with the following (top of file):

```javascript
/******/ (function(modules) { // webpackBootstrap
/******/ 	self["webpackChunk"] = function webpackChunkCallback(chunkIds, moreModules) {
/******/ 		for(var moduleId in moreModules) {
/******/ 			modules[moduleId] = moreModules[moduleId];
/******/ 		}
/******/ 		while(chunkIds.length)
/******/ 			installedChunks[chunkIds.pop()] = 1;
/******/ 	};
/******/
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// object to store loaded chunks
/******/ 	// "1" means "already loaded"
/******/ 	var installedChunks = {
/******/ 		witcrypt.webworker: 1
/******/ 	};
/******/
/******/ 	// The require function
```

Note:

```javascript
/******/ 	var installedChunks = {
/******/ 		witcrypt.webworker: 1
/******/ 	};
```

Obviously, this is invalid.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Object literal keys should be quoted if necessary.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Webpack 4.4.1 and 4.5.0

**Comment by EugeneHlushko** [comment]
@haggholm close this one ? Looks like your fix was merged in 7 days ago into master
