### ISSUE TITLE
process.env.PORT is undefined in CI Build

### ISSUE THREAD

**Issue by jeliasson** [webpack/webpack#6975]
I'm in the process of deploying a webpack-supported node.js app to Azure App Service, but I have a problem using ```process.env.PORT``` in the source code. This environment variable is not available during CI Build, and when webpack compiles it becomes ```undefined```. 

An example:
```const NODE_PORT = process.env.PORT || 3000;``` will become ```var NODE_PORT = undefined || 3000;```. 

```process.env.PORT``` is defined at runtime (as a namepipe) and is dynamic, and therefore can't be defined (from what I know) in e.g. ```webpack --env.PORT=\\.\2sf12g3[...]```.
Any suggestion on how I can approach this? Can I tell webpack to not compile/parse specific lines?

Thanks! 

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`process.env.PORT` becomes `undefined`

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
`process.env.PORT` to be in the compiled version, literally. 

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Node: 8.10.0
Webpack: 4.5.0
OS: Windows 10, Windows Server 2016

**Comment by jeliasson** [comment]
Unfortunately, the `PORT` (named pipe) is dynamic and defined on runtime. This means that I don't know what the PORT will be during CI Build.
(Wrote HOST instead of PORT by mistake as example).

**Comment by sokra** [comment]
Do you use `target: "node"`?

**Comment by jeliasson** [comment]
I am not. I will look into this.

**Comment by jeliasson** [comment]
This issue was solved by stringify the statement as below.
`const NODE_PORT = 'process.env.PORT || 3000';`

**Comment by hasanali777h** [comment]
The issue was solved by giving absolute path to your .env file. like that; 
const path = require("path");
require("dotenv").config({ path: path.join(__dirname, "./.env") });
