### ISSUE TITLE
SplitChunk plugin keeps large dependencies in two seperate chunks.

### ISSUE THREAD

**Issue by jfrolich** [webpack/webpack#6976]
**Do you want to request a *feature* or report a *bug*?**

Bug 

**What is the current behavior?**

A few large dependencies (slate / react-slate / immutable) shared by two pages are not put in a shared chunk (a large number of dependencies are the same including components). See visualization below:

![image](https://user-images.githubusercontent.com/579279/38434493-260d0732-3a01-11e8-94c3-d4213cb94b5f.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
```
splitChunks: {
  chunks: 'all',
  name: false,
}
```

**What is the expected behavior?**

In my understanding this should not happen by default, so I'd like to see if this is incorrect behaviour. If this is the case I'll happily provide more information to investigate.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

webpack version: 4.5.0.

**Comment by Legends** [comment]
Please create a little repo which replicates this isssue. Thanks.

**Comment by sokra** [comment]
Maybe these modules are below the minimum size of 30kb so its not worth putting in a separate chunk

**Comment by jfrolich** [comment]
They are pretty big actually ContentPage in total is 675kb. I'd like to produce a repo but this is for a big closed source app, so I am not able to share.

**Comment by jfrolich** [comment]
@Legends: If I do that it put's all vendor scripts together in a single bundle in a very big file. This is not optimal because then the initial download is very large.

**Comment by jfrolich** [comment]
I could privately share the source code @sokra

**Comment by jfrolich** [comment]
This is the full overview:
![image](https://user-images.githubusercontent.com/579279/38439032-d596bc90-3a0e-11e8-93ad-3b9b3d9ad22a.png)

**Comment by jfrolich** [comment]
Fixed it by increasing the optimization parameters:

`
  {
        maxInitialRequests: 5,
          maxAsyncRequests: 7,
}
`

**Comment by sokra** [comment]
Your case is interesting.

Here is some background on the request limits: With HTTP1.1 browsers maintain a maximum of 6 connections per domain.

Could you check if changing this option affects your initial load performance, because requests are sequencialized?

**Comment by jfrolich** [comment]
Yeah that may be affected, but I use HTTP2, so it should be fine for most people. What I think can be improved with the chunk splitter is more intelligently splitting the bundles, because these are two async imports (2 pages) that share 90% of a pretty big chunk. So that should be one of the chunks that has priority, to optimally split.

Maybe also the mixInitialSplits are a bit tight because for a pretty standard setup you already have 4 async requests:

- Runtime (for long time caching)
- App (small entry point)
- Vendor (base vendor requirements for the app)
- (async) Page (the page itself)

**Comment by sokra** [comment]
I think with HTTP2 you can even set these limits to Infinity since parallel loading is no longer a problem.

**Comment by jfrolich** [comment]
Nice!

**Comment by lili21** [comment]
less then `maxAsyncRequests` or less then or equal `maxAsyncRequests`?

**Comment by z354392349** [comment]
I have never figured out how to use maxInitialRequests and maxAsyncRequests. Can you post the case? I want to learn. thank you.

**Comment by lili21** [comment]
@z354392349 

```javascript
module.exports = {
  //...
  optimization: {
    maxAsyncRequests: 8,
    ...
  }
};
```

**Comment by z354392349** [comment]
Thank you for your reply, I know this, but I have not tested the effect of this. The function of this property I have not tested.

**Comment by DurdenP** [comment]
Hi all, I want to be sure I properly understood the meaning of the **maxInitialRequests**/**maxAsyncRequests** optimization parameters:

Webpack decides if it is convenient or not the creation of new bundles with shared dependencies using also the values of these 2 parameters. 

The meaning is related to the fact that the currently browsers, in average, are able to handle 6 parallel connections per domain with a Server that use the HTTP1.1 protocol https://stackoverflow.com/questions/985431/max-parallel-http-connections-in-a-browser, 

The default conf is: 

- maxAsyncRequests: 5,
- maxInitialRequests: 3,

And the reason is because webpack wants to avoid that the number of bundle could 'explode', causing more that 6 parallel connections at the downloading of the bundles. 

Is it correct?

**Comment by alexander-akait** [comment]
Now we support http2 out of box https://github.com/webpack/webpack/blob/master/lib/config/defaults.js#L930 and https://github.com/webpack/webpack/blob/master/lib/config/defaults.js#L931
