### ISSUE TITLE
Webpack 4 doesn't support sharing modules from entries

### ISSUE THREAD

**Issue by deleteme** [webpack/webpack#6977]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Webpack 4.5 cannot be configured to create JavaScript files that both: a) bundle shared modules and b) runs them.

**If the current behavior is a bug, please provide the steps to reproduce.**

The following markup shows the use case of a large app that has pages that assumes a babel-polyfilled environment and may depend on either React or jQuery or both. A page often has a corresponding Webpack entry that shouldn't redundantly bundle babel-polyfill, React, jQuery, or the Webpack runtime.

```html
<html>
  <body>
    <!-- Download and run babel-polyfill, fetch polyfill modules, and webpack runtime. -->
    <script src="environment.js"></script>
    <!-- An ES6 environment should polyfilled -->
    <script>console.assert('Map exists.', typeof Map === 'function');</script>
    <script>console.assert('Set exists.', typeof Set === 'function');</script>

    <!-- Download react, react-dom -->
    <script src="vendor-react.js"></script>

    <!-- Download and run jquery, and a module that sets it on window -->
    <script src="vendor-jquery.js"></script>
    <script>console.assert('jQuery exists.', typeof jQuery === 'function');</script>

    <!-- Download and run page-specific code that may import react or jquery
      without bundling react or jquery in page-a.js -->
    <script src="page-a.js"></script>
  </body>
</html>

```

**What is the expected behavior?**

Webpack 3 and it's CommonsChunkPlugin supported this feature.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Webpack 4.5, Node 8.2, OS X 10.12.6.

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by sokra** [comment]
This is also supported in webpack 4 but in a different way

**Comment by paquette** [comment]
@sokra care to expand a bit on the _different way_?

**Comment by montogeek** [comment]
@paquette Using https://webpack.js.org/plugins/split-chunks-plugin/#src/components/Sidebar/Sidebar.jsx

**Comment by deleteme** [comment]
@montogeek @sokra Here's a reduction of the problem:

https://github.com/deleteme/webpack-4-issue-6977-module-sharing-from-entries

I started from this example https://github.com/webpack/webpack/tree/master/examples/common-chunk-and-vendor-chunk

**Comment by Legends** [comment]
@deleteme 
Vendor files are not entry points.. forget about the CommonsChunkPlugin in webpack 4.

**Comment by karolyi** [comment]
I have a vendor bundle, and my own commons module. With `libraryTarget: 'var'` I used to configure variables in my commons module (it has an `options` variable within, which is exported for the modules importing `common.js`).

Before 4.0, using `CommonsChunkPlugin` I could import the `common.js` module, then configure it from inlined code in my pages, and then use the options configured from the inline code in my modules. After 4.0, I can't get it working. It seems as the `options` within the same `common.js` is two separate variables: one which is configured via the `libraryTarget` behavior from the inlined code, and another which is basically an the original state of the defined `options` variable in `common.js`, imported by the underlying modules.

Reading the new configuration docs so far with `SplitChunks`, I could not find ways as to how to keep the 'one parent'-'many children' relation, so that my modules would see the same inline configured `common.js` `option` variable everywhere.

Am I missing something, or has this become completely unavailable with V4? Can someone enlighten me as to how I can achieve what was available with V3?

**Comment by karolyi** [comment]
bump

**Comment by TheLarkInn** [comment]
It sounds like you are trying to synthetically make certain modules and things available for other bundles not created from the same compilation?

**Comment by deleteme** [comment]
@TheLarkInn When you say "available for other bundles not created from the same compilation?"

Does that apply to this line in the original description?

```html
<script>console.assert('Map exists.', typeof Map === 'function');</script>
```

If so, do you think that this use case is unreasonable or unrealistic?

It seems to me that Webpack 4 assumes that it is responsible for the loading of all JavaScript on a site. While this may be true with code splits in a SPA, this is not always true for a site composed of html pages with script tags.

The hueristics system to determine what commons files to generate is a nice feature for SPA, but it is not practical for an html page app with script tags, where each script tag must be deliberately added.

I'm trying to avoid:

* Bundling jQuery or React for pages that do not need it.
* Downloading common modules more than once.
* Downloading the Webpack runtime more than once.
* Having common modules pulled into new, unexpected files (often named something like `a~b~c.js`).

I'm trying to preserve:

* My existing script tags throughout a large app.
* The ability to include babel-polyfill for any JavaScript that runs after it.
* The optimization of downloading React or jQuery once, in their own common script files, that are made available to other Webpack modules or to the global window.

Is this something that Webpack 4 supports?

**Comment by SevInf** [comment]
This is actually blocking update to webpack 4 for us. Some background: we have a pretty large app (4500+ modules, ~400 entry points). API is a mix of legacy and modern, webpack-built JS code. Every page could be a mix of legacy and modern widgets. For this cases, we create a separate webpack entry point for every modern-inside-legacy widget. Some global initialization is then put into another `init.js` entry point:

```js
import 'babel-polyfill';
import SomeLib from 'some-internal-library';

SomeLib.configure({ ...options });
```

This `init.js` is executed before widget entry points. Widgets expect `'some-internal-library'` to be configured. This worked us for every webpack version since `0.x`. On webpack 4 it broke, because it seems like every widget entry point now re-executes `some-internal-module` on the first import and `configure` call in `init.js` does not affect the rest.

Is there something we can do to make it work?

**Comment by karolyi** [comment]
@SevInf glad to hear I'm not the only one blocked changing to Webpack 4. what you just described, is more or less the same problem I'm facing.

**Comment by crazyfx1** [comment]
If I understand your problem correctly, you are trying to load multiple entry points on a single page. This should work if you create one `runtimeChunk` for all entry points.

```JavaScript
 optimization: {
      runtimeChunk: 'single'
}
```
This creates a "runtime.js", which you need to load as first script on the page. After that, you can load multiple entry points on your page.

**Comment by akx** [comment]
Adding a single runtime chunk also works around this React problem (copy-pasting for searchability, emphasis mine):

> Uncaught Error: Element ref was specified as a string (inner) but no owner was set. This could happen for one of the following reasons:
> 1 You may be adding a ref to a functional component
> 2 You may be adding a ref to a component that was not created inside a component's render method
> **3 You have multiple copies of React loaded**

Without a single runtime chunk, Webpack seems to have a multiple maps of loaded modules (within each runtime), so the modules (no matter which chunk might contain them) get initialized several times, which confuses React (I assume it's an issue with `Symbol`s being always-unique or something similar).

It would be nice to tell Webpack that the loaded-module-map can be stored as a global (on `window` or in `global`, or whatever) to avoid having the extra runtime chunk.

**Comment by devineloper** [comment]
> If I understand your problem correctly, you are trying to load multiple entry points on a single page. This should work if you create one runtimeChunk for all entry points.

@crazyfx1 Thank you! This solved my problem. jQuery was being imported 3 different times, each time overwriting any event bindings that were set up. Adding a separate runtime chunk solved this. I did not see this behavior in Webpack 3, so this was driving me nuts all day as I tried to upgrade to Webpack 4.

**Comment by akx** [comment]
To expand on my last comment, by the way, there's a slightly undocumented syntax for `optimization.runtimeChunk`: You can actually set it to ```
optimization: {
  runtimeChunk: {
    name: 'shared',
  },
}
```

to have Webpack inject the runtime into that chunk; this interoperates with `optimization.cacheGroups.***.name`, so if you have a shared chunk of dependencies that you swear every page of yours will load, you can use the above configuration to have Webpack inject the runtime there, to avoid the extra runtime-only chunk.

**Comment by ravihamsa** [comment]
Any updates on this problem? This was something working smoothly in earlier version of webpack.

**Comment by evaneus** [comment]
> It would be nice to tell Webpack that the loaded-module-map can be stored as a global (on window or in global, or whatever) to avoid having the extra runtime chunk.

Should this be a feature request? Or is there some better/other way to achieve the desired result?  

Some relevant code for reference:

https://github.com/webpack/webpack/blob/d5983ed62b1bcf0b5b3e8634aa243b055357b83a/lib/web/JsonpMainTemplatePlugin.js#L112

https://github.com/webpack/webpack/blob/d5983ed62b1bcf0b5b3e8634aa243b055357b83a/lib/web/JsonpMainTemplatePlugin.js#L466

https://github.com/webpack/webpack/blob/a4e5f63d9d370b191bb9586570bc22bf2947e390/lib/MainTemplate.js#L172

**Comment by mifopen** [comment]
How can I preserve my existing script and link tags if chunks can just disappear at random time? Can we do something like this https://github.com/webpack/webpack/issues/7064#issuecomment-437276739 ?

**Comment by sergei-startsev** [comment]
Here's [ExecutableDllPlugin ](https://github.com/sergei-startsev/ExecutableDllPlugin) that allows to bundle shared modules and execute them.

**Comment by OlegZavrazhin** [comment]
I'm having the same issue, any update or solution?

**Comment by deleteme** [comment]
I was able to upgrade from Webpack 3 to Webpack 4. This example configuration using the DllPlugin is pretty close to what worked for me: https://github.com/webpack/webpack/blob/master/examples/explicit-vendor-chunk/webpack.config.js

There were a few compromises:

* I had to combine several vendor files into one. I was unable to configure the DllPlugin to make multiple vendor files.
* I had to use the [ExecutableDllPlugin](https://github.com/sergei-startsev/ExecutableDllPlugin) to actually execute the bundled modules, otherwise the polyfills wouldn't run after the script is loaded. This plugin requires `optimization.moduleIds` to be set to either `natural`, `hashed`, or `named`, otherwise the modules will be called in an unexpected order.
* The DllPlugin uses a global variable to provide the bundled modules to other Webpack entries.

**Comment by sod** [comment]
We currently do this:

```typescript
        optimization: {
            splitChunks: {
                maxAsyncRequests: 1,
                cacheGroups: {
                    commons: {
                        name: 'first-entry-bundle',
                        chunks: 'initial',
                        minChunks: 2,
                        priority: 2,
                    },
                },
            },
        },
```

and have two entries `first-entry-bundle` and `second-entry-bundle`. The second one will reuse dependencies that are in the first one. And both are entries. The trick here is, that the `cacheGroup` has the same name as the first bundle.

But be warned thou, webpack 5 exists with an error, that a cache group mustn't have the same name as a bundle anymore :(

**Comment by h0jeZvgoxFepBQ2C** [comment]
This is really a nightmare for me, I nearly spent around 30 hours to make it work somehow - and it's still not working. I'm using rails webpacker and either the chunks are loaded multiple times or the JS code is not executing at all - even though I can see the "working" javascript include tags in the html. Until now webpack is absolutely killing my nerves & productivty :(

Basically I would like to have 1 base js file (imports polyfill, jquery,..), and several other js entry files which are included if one of our subpages is opened (different react components, depending on which site is opened)).

**Comment by rbarber1** [comment]
I'm seeing the same issue that @h0jeZvgoxFepBQ2C is having. I originally thought this had to do with source maps but what I'm finding is that if any of my code is chucked/split then none of it gets executed.

I created an example project where I have code splitting turned on and only import jQuery to print to the console. [Github Project](https://github.com/rbarber1/Webpack-Chunk-Sourcemap-Bug).

Webpack version: 4.31.0

When code splitting is turned on nothing is printed to the console. When code splitting is turned off everything works as expected. The only code splitting comes from importing jQuery and the issue still occurs.

**Comment by DominicTobias** [comment]
I'm trying to make a library of components from one repo, I can compile multiple entries however I want to extract the shared larger dependencies out to a "base" file which they can all use but not build into their own files.

Bit confused reading above how I can achieve this, does anyone have pointers please?

e.g.

```
components/Base <-- shared dependencies exported as base.js
components/Button <-- imports Base stuff but should not compile it into button.js
components/Tabs <-- imports Base stuff but should not compile it into tabs.js
```

**Comment by sergei-startsev** [comment]
@DominicTobias Have you used [DllPlugin](https://webpack.js.org/plugins/dll-plugin/#dllplugin) and [DllReferencePlugin](https://webpack.js.org/plugins/dll-plugin/#dllreferenceplugin)? You can also take a look at [ExecutableDllPlugin](https://github.com/sergei-startsev/ExecutableDllPlugin) and its [code-splitting](https://github.com/sergei-startsev/ExecutableDllPlugin/tree/master/examples/code-splitting) example.

**Comment by DominicTobias** [comment]
@sergei-startsev thanks I'll look into those next if this doesn't work, it seems that it might work though:

```
optimization: {
    splitChunks: {
      chunks: 'all',
      name: 'base',
    },
  },
```

This is creating a base.js of node_modules, and later if I want to add other local shared resources I can modify `chunks` or maybe `cacheGroups` (not sure which)

**Comment by jdelStrother** [comment]
I'm also struggling with this.  I have 3 entrypoints - `preload`, `polyfill`, and `application`.

`preload` is responsible for checking the browser supports promises, loading the `polyfill` entrypoint if not, and then loading the `application` entrypoint.  It loads these via regular old document.createElement("script") so that it's not reliant on webpack's promise-based chunk loader. I disable code splitting in `preload` & `polyfill` for the same reason.

```js
config.entry = {
  preload: "./src/preload",
  polyfill: "./src/polyfill",
  application: "./src/application"
};
config.optimization.splitChunks = {
  chunks: chunk => chunk.name !== "preload" && chunk.name !== "polyfill",
};
config.optimization.runtimeChunk = {
  name: "preload"
};
```

This bit works fine, and webpack's runtime chunk is successfully only inserted into preload.js.  However any dependencies loaded in both preload & application get duplicated - once in the `preload` entrypoint, and once in `application`'s split modules.  How can I persuade webpack that any modules referenced in the runtimeChunk entrypoint don't need to be duplicated?

**Comment by ahamid** [comment]
I will just echo @h0jeZvgoxFepBQ2C's observation, as I have come from using rails webpacker as well, which seems to encourage separate entry points/packs per page/controller, which means the discussed issue can arise when attempting to share common chunk state (e.g. initialized jQuery plugins) between a layout/application/vendor entrypoint and a page/controller-specific entry point.

**Comment by jdelStrother** [comment]
FWIW I'm still seeing duplicate chunks with my approach (https://github.com/webpack/webpack/issues/6977#issuecomment-521997595) in Webpack 5.

**Comment by karolyi** [comment]
This issue is more than a year old, and gets extremely frustrating for many devs trying to use a singleton-like module usage.

Webpack devs, is there not solution in sight? As it is now, webpack 4 **does not have an upgrade path for us**.

**Comment by karolyi** [comment]
@sokra can you please help us out here?

**Comment by adi518** [comment]
I have two entrypoints and I use this setup to build:

```js
entry: {
  profile: ['./src/index.ts'],
  tooltip: ['./src/tooltip-index.ts'],
},
optimization: {
  splitChunks: {
    chunks: 'all',
    name: 'profile-tooltip-common',
  },
},
```

The result is three bundles: `profile-bundle.js`, '`tooltip-bundle.js` and `profile-tooltip-common-bundle.js`. The issue I'm facing is having to include the common bundle for the two entries to execute. I watch each entry to load the common bundle on its own. How do I achieve that?

**Comment by maykefreitas** [comment]
Did you tried `chunks: 'async'`?

**Comment by Lalitha-Iyer** [comment]
> I'm also struggling with this. I have 3 entrypoints - `preload`, `polyfill`, and `application`.
> 
> `preload` is responsible for checking the browser supports promises, loading the `polyfill` entrypoint if not, and then loading the `application` entrypoint. It loads these via regular old document.createElement("script") so that it's not reliant on webpack's promise-based chunk loader. I disable code splitting in `preload` & `polyfill` for the same reason.
> 
> ```js
> config.entry = {
>   preload: "./src/preload",
>   polyfill: "./src/polyfill",
>   application: "./src/application"
> };
> config.optimization.splitChunks = {
>   chunks: chunk => chunk.name !== "preload" && chunk.name !== "polyfill",
> };
> config.optimization.runtimeChunk = {
>   name: "preload"
> };
> ```
> 
> This bit works fine, and webpack's runtime chunk is successfully only inserted into preload.js. However any dependencies loaded in both preload & application get duplicated - once in the `preload` entrypoint, and once in `application`'s split modules. How can I persuade webpack that any modules referenced in the runtimeChunk entrypoint don't need to be duplicated?

I have a configuration similar to this. However I noticed `polyfill` and `application` are no longer initial entrypoints and are treated as non-initial chunks. So they are not available as routes in webpack-dev-middleware.

The usecase I have is I want to have a `multi entrypoint` configuration with runtime chunk included in one of them.

**Comment by vivkr** [comment]
It's almost three years since this issue was opened, and no solution in sight. Has anyone using webpack with rails figured out a good work-around?
