### ISSUE TITLE
Webpack runtime doesn't work on Safari 5

### ISSUE THREAD

**Issue by kaisermann** [webpack/webpack#6978]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

The current webpack v4 runtime uses Function.prototype.bind which is not available in Safari 5.

![image](https://user-images.githubusercontent.com/12702016/38439562-7632fff2-39b4-11e8-840e-a9097df4dd02.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

Just try to run any bundle built by webpack v4 in a Safari 5/Webkit ~534.

**What is the expected behavior?**

The runtime code should work on old Webkit versions. 

I can manually insert a `bind` polyfill in my template before the bundles, but I'd really like to avoid doing this manually. I've tried to insert the polyfill inside the runtime, but as you can guess it, the runtime is executed before the polyfill.

**If this is a feature request, what is motivation or use case for changing the behavior?**

I know `Function.prototype.bind` is essential and that `Safari 5` is an old browser, but since I didn't find any general "browser support" for webpack, the runtime should work on old Webkit versions.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Webpack version: 4.5.0
Node: 9.8.0

**Comment by Legends** [comment]
[StatCounter GlobalStats](https://caniuse.com/usage-table)
Safari
5: 0.01%
5.1: 0.07%

**Comment by lucasvanhalst** [comment]
I don't think webpack should support a 7 year old browser, that would be a waste of time

**Comment by Janpot** [comment]
Me neither, but I think it should be decided and documented which browsers are supported.

**Comment by ooflorent** [comment]
Please send a PR which updates the README to clarify the browser support.

**Comment by Janpot** [comment]
@ooflorent sure, which browsers does webpack support? And if this was never defined before, what do you think is a reasonable target? Last 3 versions of major browsers or something?

**Comment by ooflorent** [comment]
Not sure either. I like the way Vue.js is phrasing its compatibility node:

> Vue does not support IE8 and below, because it uses ECMAScript 5 features that are un-shimmable in IE8. However it supports all ECMAScript 5 compliant browsers.

Open a PR, that would start a discussion.

**Comment by montogeek** [comment]
@Janpot ES5 browsers

**Comment by sokra** [comment]
You can concatenate it to the chunk with the runtime.
