### ISSUE TITLE
Let loader pass function

### ISSUE THREAD

**Issue by kentcdodds** [webpack/webpack#698]
Would be way awesome if I could do this:

```js
{test: /\.js$/, loader: source => "'use strict';\n" + source, exclude: /node_modules/}
```

I tried this and turns out loaders must be a string (understandable). Would it be possible to make this work? As of now, I have to put this tiny bit of code in a totally separate file. Just would love to avoid putting so few characters in an entirely different file...

**Comment by sokra** [comment]
Sorry that's not possible. The loader filename is part of the unique identifier of the module. So it must be a separate file.

**Comment by kentcdodds** [comment]
Understood. No worries :-) webpack rocks!
