### ISSUE TITLE
DLLPlugin and DLLReferencePlugin are using different modules

### ISSUE THREAD

**Issue by zslucky** [webpack/webpack#6984]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Some dependencies doesn't split out, like `vue`, `vue-router`. I think this may due to `DLLPlugin` extract the code from `package.json / module`, but `DLLReferencePlugin` will find the code from `package.json / main`. 

**If the current behavior is a bug, please provide the steps to reproduce.**

e.g. dependencies `vue` and `vue-router`, the definition in vue's package.json bellow:
```json
{
  "main": "dist/vue.common.js",
  "module": "dist/vue.esm.js"
}
```
1. In my project I used `import Vue from 'vue'`
2. Define `vue` and some other dependencies in a new project with `DLLPlugin`
3. After DLLPlugin building finished, I can see it used `dis/vue.esm.js` in `manifest` file.
4. Add `DLLReferencePlugin` in my project, but after building, most dependencies are split out, except `vue` , `vue-router` ...

**What is the expected behavior?**

`DLLPlugin` and `DLLReferencePlugin` will use the same module.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Not a feature

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

`OS: MacOS 10.13.3`
`browser: no needed`
`webpack: ^3.1.0`
`node: ^8.9.4`
`vue: ^2.5.16`
`vue-router: ^3.0.1`

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by sokra** [comment]
Both use the `resolve` configuration in your configuration. Make sure that match.

**Comment by zslucky** [comment]
@sokra do you mean the path to use resolve?
```javascript
new webpack.DllPlugin({
    context: __dirname,
    name: "[name]",
    path: path.join(__dirname, "manifest.json"),
}),
```
```javascript
new webpack.DllReferencePlugin({
    context: path.resolve(__dirname, '.'),
    manifest: require(path.resolve(__dirname, 'manifest.json'))
}),
```
missing any?

**Comment by sokra** [comment]
This one: https://webpack.js.org/configuration/resolve/

**Comment by zslucky** [comment]
@sokra thanks, so you mean this `reslove: { alias: { vue: 'vue/dist/vue.common.js' } }` ? This can be a workaround, also I did `import Vue from 'vue/dist/vue.common.js'` to instead of `import Vue from 'vue'`, I think these 2 ways are the same.
