### ISSUE TITLE
Webpack cannot handle Semantic-UI .css files?

### ISSUE THREAD

**Issue by aguyinmontreal** [webpack/webpack#6990]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

Using Webpack, I want to minimize and bundle the semantic.css file available [here](https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.12/semantic.css).

Webpack doesn't throw any any error messages, however the outputted css has slight differences from the inputted css. (The CSS doesn't work the same.)

[this validator](https://jigsaw.w3.org/css-validator/validator.html.en#validate_by_input) says the file is full of errors. (However, it's working well when directly used in a browser). Is it the reason it is not working with Webpack?

Here's part of my webpack.config.js file:

    output: {
            path: __dirname + '/publicProduction/v2/bundle/',
            filename: '[name]'
        },
        resolve: {
            modules: ['node_modules']
        },
        module: {
            loaders: [
                {
                    test: /\.js$/,
                    loader: 'babel-loader',
                    query: {
                        presets: [
                            'es2015',
                            'stage-0'
                        ],
                        plugins: []
                    },
                    exclude: /node_modules/
                },
                {
                    test: /\.css$/,
                    loader: ExtractTextPlugin.extract({
                        fallback: 'style-loader',
                        use: ['css-loader', 'postcss-loader']
                    })
                },
                {
                    test: /\.(eot|svg|ttf|woff|woff2|png|jpg|jpeg|gif)$/,
                    loader: 'file-loader?name=resources/[name].[ext]'
                }
            ]
        },
        plugins: [
            new ExtractTextPlugin('./[name]'),
            new Webpack.ProvidePlugin({
                $: 'jquery',
                jQuery: 'jquery',
                'window.jQuery': 'jquery',
                'window.$': 'jquery'
            })
        ]

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
webpack version 3.11.0

**Comment by PlayMa256** [comment]
Which errors? Could you create a slightly minimum reproduction repository so it is easy to help?

**Comment by aguyinmontreal** [comment]
@PlayMa256  I'm currently working on bulding a repo :)  Give me 15 minutes.  There are no errors, but the output CSS file is working differently as the input.

**Comment by aguyinmontreal** [comment]
@PlayMa256  So, here is my repo:  https://github.com/aguyinmontreal/webpack_mangling_example

before Webpack:
![image](https://user-images.githubusercontent.com/19701656/38475918-f05b034a-3b78-11e8-89e8-42df9bf36e27.png)

after Webpack:
![image](https://user-images.githubusercontent.com/19701656/38475901-c9334d2c-3b78-11e8-8a39-a8a7af738962.png)

I  located the issues for two elements:

1-For the following element: `<div class="twelve wide tablet eight wide large screen ten wide computer column menu_first" style="font-size:1.14285714rem;white-space:nowrap">`

this first rule is incorrectly getting an higher priority
```
.ui.column.grid > [class*="ten wide computer"].column, .ui.grid > .column.row > [class*="ten wide computer"].column, .ui.grid > .row > [class*="ten wide computer"].column, .ui.grid > [class*="ten wide computer"].column {
    width: 62.5% !important;
}
```
than the following rule
```
.ui.column.grid > [class*="eight wide large screen"].column, .ui.grid > .column.row > [class*="eight wide large screen"].column, .ui.grid > .row > [class*="eight wide large screen"].column, .ui.grid > [class*="eight wide large screen"].column {
    width: 50% !important;
}
```

2-For the following element: `<div class="twelve wide mobile eight wide tablet eight wide computer four wide large screen column right floated">`

this first rule is incorrectly getting an higher priority
```
.ui.column.grid > [class*="eight wide computer"].column, .ui.grid > .column.row > [class*="eight wide computer"].column, .ui.grid > .row > [class*="eight wide computer"].column, .ui.grid > [class*="eight wide computer"].column {
    width: 50% !important;
}
```
than the following rule
```
.ui.column.grid > [class*="four wide large screen"].column, .ui.grid > .column.row > [class*="four wide large screen"].column, .ui.grid > .row > [class*="four wide large screen"].column, .ui.grid > [class*="four wide large screen"].column {
    width: 25% !important;
}
```

**Comment by montogeek** [comment]
What is the expected output?

**Comment by PlayMa256** [comment]
@aguyinmontreal interesting enough, i was not able to reproduce that either. As you can see here, this looks the same as the `beforeWebpack`. 

[After bundle](http://prntscr.com/j2v9dt)
[Unbundled example](http://prntscr.com/j2va53)

Are these things right, or the spacing was supposed to be smaller?

**Comment by montogeek** [comment]
@aguyinmontreal Yeah, smaller, this is not a webpack issue, I don't even think it is an issue, if any, it is probably on PostCSS side.
CSS Specificity in this case is a mess.

**Comment by aguyinmontreal** [comment]
@montogeek and @PlayMa256   Good morning guys! :D

@montogeek @PlayMa256 Have you compared the `beforeWebpack.html` with the `afterWebpack.html`.?  

I think the difference is pretty obvious without rerunning Webpack.  

In case you want to rerun Webpack, please do `npm install` before in order to get the exact same packages (maybe your globally installed Webpack/PostCSS version is better, in this case please let me know which version it is, because I tried many of them).

@montogeek You're right it's a PostCSS issue, sorry for posting about this here.  But it is a big issue for me. There are **multiple** differences like that on my web pages, and this is completely destroying the work I have been doing in the past 5 months.  I have been working on this issue for the past week.

Which loaders do you suggest I use, if the postCSS one is not working?  Should I simply concatenate the minimized css files by hand?  My only goal is to minimize the css files as much as possible and to bundle them into a single css file for each web page. (instead of having 30 different css files)

**Comment by PlayMa256** [comment]
@aguyinmontreal yes i did. I also rebundled the file and linked this new one in the `afterWebpack` html.

I would ask you to have a look at `css-mqpacker`. Since the problem seems to be at media queries, and this `post-css` plugin touchs on those things, this can be the root of your problems.

**Comment by montogeek** [comment]
@aguyinmontreal Good morning!
What it your objetive? Override semantic-ui default styles?

**Comment by aguyinmontreal** [comment]
@PlayMa256 

If this is really working on your side, I would really like to hear more about your computer configuration.  On my side, I'm using windows 7.

**Comment by PlayMa256** [comment]
@aguyinmontreal Your goal is to pack your css files into just one and apply optimizations to it?

**Comment by aguyinmontreal** [comment]
@montogeek 

My objective is to bundle only the necessary SemanticUI css files (not the whole SemanticUI package) and add my custom css files to them. At the end, I want to only have 1 optimized/minimized css file for each web page.
