### ISSUE TITLE
Add a maxSize option for splitChunks

### ISSUE THREAD

**Issue by bhollis** [webpack/webpack#6991]
**Do you want to request a *feature* or report a *bug*?**

I'd like to request a feature.

**What is the current behavior?**

Using `optimization.splitChunks`in Webpack 4, I can nicely split out common code. However, common chunks like "vendor" can grow to be very large.

**What is the expected behavior?**

I'd like to be able to specify a `maxSize` configuration option, which would automatically subdivide files until they are under the max size. For example, I could specify `maxSize: 200000` to limit files to 200kb, and if they are larger than that, they will be split into two or more files.

**If this is a feature request, what is motivation or use case for changing the behavior?**

The motivation is to allow for files to be loaded and parsed in parallel, rather than having to handle a single very large file.

**Comment by ooflorent** [comment]
Have you tried `AggressiveSplittingPlugin`?

**Comment by bhollis** [comment]
Interesting, I didn't know about that. Trying it out, it doesn't seem to work well (though the docs are sparse, so I'm not sure if I'm missing something) - the large chunks do get split up, but they don't get included in my HTML. I'm using `HtmlWebpackIncludeSiblingChunksPlugin` which may be causing issues (I needed it to work around `splitChunks` not including all its files in the HTML either).

**Comment by ooflorent** [comment]
This plugin produces async chunks so it is expected that they don't appear in the HTML.

**Comment by sokra** [comment]
It also splits initial chunks. That they are not included in the html could be a bug in the html-webpack-plugin.

**Comment by lauterry** [comment]
Hi

Can AggressiveSplittingPlugin work to split vendors using the conf below  :  

```
optimization: {
			runtimeChunk: "single",
			splitChunks: {
				chunks: "all",
				maxInitialRequests: 30,
				maxAsyncRequests: 50,
				cacheGroups: {
					commons: {
						name: "commons",
						chunks: "initial",
						minChunks: 2
					},
					vendors: {
						test: /node_modules/,
						chunks: "all",
						priority: -10,
						minChunks: 1
					},
					default: {
						minChunks: 1,
						chunks: "all",
						priority: -20,
						reuseExistingChunk: true
					}
				}
			}
		},
```

**Comment by andyrichardson** [comment]
I totally agree - the ability to limit chunk sizes would be a huge help. Using _AggressiveSplittingPlugin_ breaks automatic script tag inserts handled by _HTMLWebpackPlugin_.

I'm not sure why others might need this feature but my justification is because [_sw-precache-webpack-plugin_](https://www.npmjs.com/package/sw-precache-webpack-plugin) won't cache files more than 2.1mb.
