### ISSUE TITLE
Tree shaking not working with webpack 4.5

### ISSUE THREAD

**Issue by cdhgee** [webpack/webpack#6992]
**Do you want to request a *feature* or report a *bug*?**

I'd like to report a bug

**What is the current behavior?**

Tree shaking does not appear to be working. Dead code should be identified in the output bundle with a comment such as 

`/* unused harmony export _functionname_ */`

**If the current behavior is a bug, please provide the steps to reproduce.**

Refer to the basic configuration in [https://github.com/cdhgee/webpack-tree-shaking](https://github.com/cdhgee/webpack-tree-shaking). 

1. Run `npm install`
2. Run `npm run build`
3. Examine the output in `dist/bundle.js`. Around line 83, the exports from `another-module.js` should be shown. 

**What is the expected behavior?**

Functions c and d are not used anywhere in the project and should be identified with a comment such as 

`/* unused harmony export c */`

Because these comments are missing, I conclude that either (a) tree shaking is not running, or (b) tree shaking is running but is not identifying c and d as dead code. 

**If this is a feature request, what is motivation or use case for changing the behavior?**

n/a

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

NodeJS version: 9.11.1 (64-bit)
Webpack version: 4.5.0
OS: Windows 10 1709 (64-bit)

These versions are all the most recent available as of today (2018-04-08).

**Comment by Legends** [comment]
I am not sure, I guess `sideEffects` is for library devs only..??
I just `git cloned` your example and 
extracted `another-module` to `node_modules` and 
added a `package.json` with `sideEffects:false`,
build it with `--mode production` but still no `treeshaking`.

It works in any way if you add:

```
optimization: {
    minimizer: [
      new UglifyJsPlugin({ // https://github.com/webpack-contrib/uglifyjs-webpack-plugin
        sourceMap: false, 
        uglifyOptions: {
          ecma: 5,
          warnings: true,
          comments: true,
          beautify: true
        },
      })
    ]
  }
```

@sokra Shouldn't it work without explicitly adding the `UglifyJsPlugin`, just by adding `--mode production`, at least when `another-module.js` would be a regular npm package with `sideEffects:false` ?

**Comment by sokra** [comment]
Tried your repo @cdhgee and it works fine. Note that tree shaking is only enabled in production mode:

```
$ npm run build -- --mode production --display-used-exports
Hash: c665586af0bb888f4551
Version: webpack 4.5.0
Time: 529ms
Built at: 2018-4-9 09:46:10
    Asset       Size  Chunks             Chunk Names
bundle.js  599 bytes       0  [emitted]  main
Entrypoint main = bundle.js
   [0] ./index.js + 1 modules 264 bytes {0} [built]
       | ./index.js 48 bytes [built]
       | ./another-module.js 216 bytes [built]
       |    [only some exports used: a]
```

**Comment by montogeek** [comment]
@sokra It is only enable in production mode via a plugin or something internal? Want to document it in Tree shaking guide https://webpack.js.org/guides/tree-shaking/

**Comment by Legends** [comment]
@montogeek 
There is also a  `sideEffects?: boolean;` in the Optimization Interface.

If you set `sideEffects` in package.json and under optimization, which one has higher priority?
At least this should be documented..

**Comment by Legends** [comment]
No it works, without explicitly adding the plugin, just `--mode production`

**Comment by cdhgee** [comment]
@sokra Thanks for the update. Can I suggest updating the [Tree Shaking Documentation](https://webpack.js.org/guides/tree-shaking/) page on webpack.js.org?

The current documentation states that dead code will be identified **without production mode** (the **dist/bundle.js output** part of section [Add a Utility](https://webpack.js.org/guides/tree-shaking/#add-a-utility). This doesn't seem to be the case.

**Comment by zhongds** [comment]
webpack: 4.5.0.
I also have the same problem.
`webpack --mode production` take effects, but when I use **mode** in webpack config, tree-shaking do not work (I had setted **sideEffects** on package.json).

I followed the steps in [Tree Shaking Documentation](https://webpack.js.org/guides/tree-shaking/#src/components/Sidebar/Sidebar.jsx):
- Use ES2015 module syntax (i.e. import and export).
- Add a "sideEffects" entry to your project's package.json file.
- Include a minifier that supports dead code removal (e.g. the UglifyJSPlugin).

what's the problem? @Legends

**Comment by jmurzy** [comment]
@sokra I can also confirm that `/* unused harmony export */` comments are missing from the `production` output when `optimizations.minimize=false`. Using the same repo @cdhgee provided above, given:

```js
module.exports = {
  mode: "production",
  devtool: "none",
  entry: "./index",
  output: {
    filename: "bundle.js",
    path: path.resolve(__dirname, "dist"),
  },
  optimization: {
    minimize: false,
    sideEffects: false,
  }
};
```

I get the following output:

```js
/******/ ([
/* 0 */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);

// CONCATENATED MODULE: ./another-module.js
function a(i) {
  console.log("a is " + i);
}

function b(i) {
  console.log("b is " + i);
}

function c(i) {
  console.log("c is " + i);
}

function d(i) {
  console.log("d is " + i);
}

// CONCATENATED MODULE: ./index.js

a(3);

/***/ })
/******/ ]);
``` 
I have a babel-minify step in my gulp pipeline to which I want to delegate all minimization and dead code removal. Is such a setup currently possible outside the Webpack realm?

**Comment by hanyulo** [comment]
@zhongds I follow the [Tree Shaking guide document](https://webpack.js.org/guides/tree-shaking/) and do exactly what it inform. My code work like a charm without UglifyJsPlugin.

**Comment by zhangolve** [comment]
@zhongds like a charm ?
So you solved your problem?

**Comment by apptaro** [comment]
As @sokra said [above](https://github.com/webpack/webpack/issues/6992#issuecomment-379665061), **tree shaking is only enabled in production mode**.

Doc [here](https://webpack.js.org/guides/tree-shaking/) needs improvements because it's not only UglifyJsPlugin but a bunch of plugins are needed for tree shaking to work. See [the mode doc here](https://webpack.js.org/concepts/mode/#usage).

**Comment by AndrewSouthpaw** [comment]
Also, check if you're using `babel-loader`. That was my problem, it was transpiling ES6 modules into CommonJS, thus breaking tree shaking.

**Comment by dabrowne** [comment]
@AndrewSouthpaw Which versions of babel-core/babel-loader are you using? I'm using `babel-core==6.26.3` and `babel-loader==7.1.5` and using `modules: false` in my root .babelrc gives me an error:

```
Using removed Babel 5 option: [path-to-config].modules - Use the corresponding module transform plugin in the `plugins` option.
```

Any idea how to avoid module transpiling on the newer babel-core?

**Comment by dabrowne** [comment]
@AndrewSouthpaw Thanks that seems to make a difference.

Still not getting any improvements on ramda, which I'm importing using `import * as R from 'ramda';`. Does anyone know if tree-shaking should be able to optimize these imports?

**Comment by AndrewSouthpaw** [comment]
IIRC you need to use the ramda-es version, which is optimized for ES6 imports.

We could never get it to work (because we didn't know about the modules issue from before), so we solved it this way: we created a `ramda_loader.js` file which just grabs all the exports from Ramda in their cherry-picked format, comment them all, then incrementally uncomment them as they're needed. It took an hour or two to set it up, but now auto-imports work a lot better through our IDE as an added benefit.

```js
export const any = require('ramda/src/any')
// export const anyPass = require('ramda/src/anyPass')
```

YMMV. You can also just check out the ramda docs about ramda-es and that may work for you.

**Comment by dabrowne** [comment]
Thanks mate I'll have a look at ramda-es. I just realized I already ran into your post on Ramda, Webpack and Tree shaking when googling the issue :sweat_smile:

**Comment by AndrewSouthpaw** [comment]
Hahaha. Yeah that's why I wrote it, because it caused us so much pain figuring it out. 😆

**Comment by SassNinja** [comment]
> For mine I do this:
> { "presets": ["env", { "modules": false }] } – @AndrewSouthpaw 

Thanks for this hint! I was facing the same problem and setting modules to `false` in my `.babelrc` did fix it!

**Comment by Vsion** [comment]
`"@babel/core": "^7.0.0-rc.1",
    "@babel/preset-env": "^7.0.0-rc.1",
    "@babel/preset-react": "^7.0.0-rc.1",
    "antd": "^3.8.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^8.0.0-beta.4",
    "babel-plugin-import": "^1.8.0",
    "babel-preset-env": "^1.7.0",`
with these devDependencies, how should i set my .babelrc
`
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "current"
        }
      }
    ],
    "@babel/preset-react"
  ]
}
`

**Comment by jbcazaux** [comment]
@Vsion After reading the docs, it seems you just have to put `"sourceType": "module"` in your `.babelrc` file (it is the default value btw). It still doesnt work for me :/

my webpack.config.js:
`optimization: {
    usedExports: true,
    sideEffects: true
  },`
in my package.json (seems not important ):`"sideEffects": false,`
I m using webpack 4.17.1, babel 7.0.0-rc.2, babel-loader 8.0.0-beta.3 and i run webapck with` --mode production`

What am i missing ? 

FYI, i have a math.js file:
`export const add = (a, b) => a + b;
export const sub = (a, b) => a - b;
`
and a main.js file:
`import { add } from './math';
console.log('4 + 2 = ', add(4, 2));`

I can still see the `sub` method declaration in my bundle.

**Comment by skipjack** [comment]
@webpack/documentation-team the updated [Tree Shaking][1] instructions worked perfectly for me, big thanks to whoever did that update!

In my case, I had a linked npm package containing some big modules that should've been shook as they weren't used. Adding `"sideEffects": false` to the package's `package.json` file cut the production build size for the main project in half (shaved hundreds of kbs). Double checked the build stats on [webpack visualizer][2] and tested the output bundles.

🎉 🎉 🎉

[1]: https://webpack.js.org/guides/tree-shaking
[2]: https://chrisbateman.github.io/webpack-visualizer/

**Comment by GuillaumeCisco** [comment]
Does tree shaking work with `mode: development` and `ModuleConcatenationPlugin` only?
I've tried and was not successful. Only the production mode made it work.

Is there a detailed way how to setup tree shaking in development mode?
The current documentation makes it look easy and working with the development mode by default, but it is not the case.

Thank you,

**Comment by alexmiddeleer** [comment]
@GuillaumeCisco tree shaking does not work in development mode per the docs [here](https://webpack.js.org/guides/tree-shaking/#conclusion)
