### ISSUE TITLE
Error: Cannot find module 'webpack/lib/removeAndDo' when building a project

### ISSUE THREAD

**Issue by nschubach** [webpack/webpack#6994]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

Running my build returns an error:

"build": "node ./node_modules/webpack/bin/webpack.js -p",

> npm run-script build

Error: Cannot find module 'webpack/lib/removeAndDo'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

**Comment by sokra** [comment]
make sure to only have one webpack version installed

**Comment by nschubach** [comment]
That was part of my problem (was trying to update and had an old version... wipe out node_modules and start clean!)  Sorry about that.  Thanks for the quick response.

**Comment by zengxiaoluan** [comment]
@nschubach did you solved this problem?

**Comment by nschubach** [comment]
@zengxiaoluan : yeah

> wipe out node_modules and start clean!

**Comment by beatlecz** [comment]
Same to me. I've just upgraded my webpack to latest version and I got this error

**Comment by montogeek** [comment]
Please try to run `npm install` or `yarn install` again.

**Comment by beatlecz** [comment]
`C:\my_project\node_modules\webpack-cli\bin\webpack.js:243
                                throw err;
                                ^

Error: Cannot find module 'webpack/lib/removeAndDo'
...`

When I see into source of webpack/lib I don't see the module. So maybe webpack-cli has wrong reference?

**Comment by beatlecz** [comment]
It seems like the file has been removed from version 4.x.x+

**Comment by LocalAsh** [comment]
Hey @beatlecz did you manage to fix the above? Experiencing the same issue.

**Comment by paigeflourin** [comment]
do we have a fix for this? i am also experiencing this issue.

  "dependencies": {
    "@angular/animations": "^4.2.2",
    "@angular/common": "~4.2.2",
    "@angular/compiler": "~4.2.2",
    "@angular/core": "~4.2.2",
    "@angular/forms": "~4.2.2",
    "@angular/http": "~4.2.2",
    "@angular/platform-browser": "~4.2.2",
    "@angular/platform-browser-dynamic": "~4.2.2",
    "@angular/router": "~4.2.2",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.26",
    "@reactivex/rxjs": "^5.5.3",
    "@types/sharepoint": "^2013.1.6",
    "angular2-toaster": "^6.0.0",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "helpers": "0.0.6",
    "rxjs": "^5.5.2",
    "sp-pnp-js": "^1.0.6",
    "typescript": "^2.8.3",
    "zone.js": "^0.6.25"
  },
  "devDependencies": {
    "@types/core-js": "^0.9.34",
    "@types/node": "^6.0.45",
    "angular2-template-loader": "^0.4.0",
    "awesome-typescript-loader": "^5.0.0",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.23.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.8.5",
    "gulp": "^3.9.1",
    "gulp-replace": "^0.5.4",
    "gulp-spsave": "^3.0.0",
    "html-loader": "^0.4.3",
    "html-webpack-plugin": "^2.15.0",
    "null-loader": "^0.1.1",
    "raw-loader": "^0.5.1",
    "replace-webpack-plugin": "^0.1.2",
    "rimraf": "^2.5.2",
    "style-loader": "^0.13.1",
    "webpack": "^4.8.3",
    "webpack-cli": "^2.1.3"
  }

**Comment by itsprakash87** [comment]
For me `extract-text-webpack-plugin` was causing the issue.
Older version of this package is not compatible with webpack 4.
Upgrading this package to latest version solved the issue.

**Comment by itsprakash87** [comment]
For me the issue was caused by `extract-text-webpack-plugin` module. Older version of this package are not compatible with webpack 4. 
As per this [comment](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/701#issuecomment-368475240), updating `extract-text-webpack-plugin` solved the issue for me.

@paigeflourin  You are using older version of `extract-text-webpack-plugin`.

**Comment by dhanesh-p** [comment]
From this [Usage](https://github.com/webpack-contrib/extract-text-webpack-plugin#usage) , have to [use](https://github.com/webpack-contrib/mini-css-extract-plugin) for CSS it seems.

**Comment by LiLister** [comment]
I am quite confused that, after run 'yarn', then 'npm start', the problem disappeared!

**Comment by llccing** [comment]
my case, update package.json, remove webpack older verison devDependencies, then `npm i`. resolved

**Comment by MilanP28** [comment]
Link globally installed package to your project

npm link webpack

Full Code [Here](https://icetutor.com/question/error-cannot-find-module-webpack/)

**Comment by cjohnweb** [comment]
> my case, update package.json, remove webpack older verison devDependencies, then `npm i`. resolved

Could you list off the specific packages you updated?

**Comment by hargrave81** [comment]
I easily replicate this issue with the following Dockerfile

### Stage 1 BUILD
FROM node:12.7-alpine AS build
WORKDIR /usr/src/app
COPY ClientApp/package.json ./
RUN npm install
COPY ClientApp/. .
RUN  npm run build


the npm run build fails with the Cannot find module 'webpack/lib/removeAndDo' error on a fresh Angular CLI version 9 created website.

**Comment by chdharm** [comment]
I started my React project using CRA(Create React App) and the added server side rendering using Express. 

tatic/js/main.6413eec0.js from UglifyJs
SyntaxError: Unexpected token: keyword (XXXX)

And started facing this issue so after going through an article I figured out that by changing webpack version I can fix it. So I have added latedt version of webpack in project. Deleted nodemodule and then did npm i. Still facing this error.

Error: Cannot find module 'webpack/lib/removeAndDo'

**Comment by metao1** [comment]
```
I have the same problem
[22:25:27] Error: Cannot find module 'webpack/lib/removeAndDo'
Require stack:
- /Users/projects/task-runner-bundler-comparison/node_modules/extract-text-webpack-plugin/ExtractedModule.js
- /Users/projects/task-runner-bundler-comparison/node_modules/extract-text-webpack-plugin/index.js
- /Users/projects/task-runner-bundler-comparison/webpack.config.js
- /Users/projects/task-runner-bundler-comparison/gulpfile.js
- /usr/local/lib/node_modules/gulp-cli/lib/shared/require-or-import.js
- /usr/local/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js
- /usr/local/lib/node_modules/gulp-cli/index.js
- /usr/local/lib/node_modules/gulp-cli/bin/gulp.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/projects/task-runner-bundler-comparison/node_modules/extract-text-webpack-plugin/ExtractedModule.js:30:42)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .js] (/Users/mehrdadkarami/projects/task-runner-bundler-comparison/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
[22:25:27] 'default' errored after 698 ms

```

**Comment by evilebottnawi** [comment]
Do not use `extract-text-webpack-plugin`, please migrate on `mini-css-extract-plugin`

**Comment by huwanthehuman** [comment]
how to fix this?

[webpack-cli] Error: Cannot find module 'webpack/lib/rules/DescriptionDataMatcherRulePlugin'
Require stack:
- c:\xampp\htdocs\employees\node_modules\vue-loader\lib\plugin-webpack5.js
- c:\xampp\htdocs\employees\node_modules\vue-loader\lib\plugin.js
- c:\xampp\htdocs\employees\node_modules\vue-loader\lib\index.js
- c:\xampp\htdocs\employees\node_modules\laravel-mix\src\components\Vue.js
- c:\xampp\htdocs\employees\node_modules\laravel-mix\src\components\ComponentRegistrar.js
- c:\xampp\htdocs\employees\node_modules\laravel-mix\src\Mix.js
- c:\xampp\htdocs\employees\node_modules\laravel-mix\setup\webpack.config.js
- c:\xampp\htdocs\employees\node_modules\webpack-cli\lib\webpack-cli.js
- c:\xampp\htdocs\employees\node_modules\webpack-cli\lib\bootstrap.js
- c:\xampp\htdocs\employees\node_modules\webpack-cli\bin\cli.js
- c:\xampp\htdocs\employees\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (c:\xampp\htdocs\employees\node_modules\vue-loader\lib\plugin-webpack5.js:6:42)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\xampp\\htdocs\\employees\\node_modules\\vue-loader\\lib\\plugin-webpack5.js',
    'c:\\xampp\\htdocs\\employees\\node_modules\\vue-loader\\lib\\plugin.js',
    'c:\\xampp\\htdocs\\employees\\node_modules\\vue-loader\\lib\\index.js',
    'c:\\xampp\\htdocs\\employees\\node_modules\\laravel-mix\\src\\components\\Vue.js',
    'c:\\xampp\\htdocs\\employees\\node_modules\\laravel-mix\\src\\components\\ComponentRegistrar.js',
    'c:\\xampp\\htdocs\\employees\\node_modules\\laravel-mix\\src\\Mix.js',
    'c:\\xampp\\htdocs\\employees\\node_modules\\laravel-mix\\setup\\webpack.config.js',
    'c:\\xampp\\htdocs\\employees\\node_modules\\webpack-cli\\lib\\webpack-cli.js',
    'c:\\xampp\\htdocs\\employees\\node_modules\\webpack-cli\\lib\\bootstrap.js',
    'c:\\xampp\\htdocs\\employees\\node_modules\\webpack-cli\\bin\\cli.js',
    'c:\\xampp\\htdocs\\employees\\node_modules\\webpack\\bin\\webpack.js'
  ]
}

**Comment by jdgabriel** [comment]
Any solutions?
