### ISSUE TITLE
Stats usedExports:true claims 'only some exports used' when all exports are used

### ISSUE THREAD

**Issue by chrisnojima** [webpack/webpack#6995]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
I'm attempting to use webpack's treeshaking to understand if I have any code that should be removed from my code base.

If i set 
```
stats: {
              exclude: undefined,
              maxModules: Infinity,
              providedExports: true,
              usedExports: true,
}
```
I see output like:
```
 | ./native/log/logui.js 327 bytes [built]
           |    [exports: log]
           |    [only some exports used: log]
or
[3] ./styles/colors.js 2.44 KiB {0} {1} [built]
           [exports: default]
           [only some exports used: default]
```
etc.

I assume if exports === exports used , it shouldn't say 'only some' right? In that case it's using all exports (and i would argue it shouldn't even output in this case)

or better yet maybe stats could just have a flag that's to show the unused exports (basically the inverse of usedExports)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Happens on osx webpack 0.4.4/0.4.5

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by chrisnojima** [comment]
sure:
1. Checkout https://github.com/keybase/webpack-example
2. `yarn`
3. `yarn bug`

**Comment by chrisnojima** [comment]
You'll see
```
> yarn bug
yarn run v1.5.1
warning package.json: No license field
$ webpack --mode production --display-used-exports --display-provided-exports
Hash: 8a99789cb72e1930c4d2
Version: webpack 4.5.0
Time: 73ms
Built at: 4/9/2018 3:55:01 PM
  Asset       Size  Chunks             Chunk Names
main.js  648 bytes       0  [emitted]  main
Entrypoint main = main.js
   [0] ./src/index.js + 2 modules 232 bytes {0} [built]
       [no exports]
       | ./src/index.js 49 bytes [built]
       |    [no exports]
       | ./src/a.js 122 bytes [built]
       |    [exports: unused, default]
       |    [only some exports used: default]
       | ./src/b.js 61 bytes [built]
       |    [exports: default]
       |    [only some exports used: default]
```

**Comment by ooflorent** [comment]
@chrisnojima I've submit a PR for this. Could you give some feedback on it?

**Comment by chrisnojima** [comment]
cool, looks good!
