### ISSUE TITLE
2 different entries in folders, url must include index.html

### ISSUE THREAD

**Issue by tzahiba** [webpack/webpack#7001]
*bug*?**

I have 2 entry points in folders, example:
I'm trying to go to the url http://MYSERVER/dashboard, so it will point to dashboard/index.html,

**What is the expected behavior?**
That going to the folder, will redirect me to index.html.

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
