### ISSUE TITLE
2 different entries in folders, url must include index.html

### ISSUE THREAD

**Issue by tzahiba** [webpack/webpack#7002]
**Do you want to request a *feature* or report a *bug*?**
a bug i guess

**What is the current behavior?**
Entering a folder which includes index.html, wont show index.html, instead it would return "could not 
Cannot GET *****

**What is the expected behavior?**
That entering a folder which contains index.html will pop up, like a regular express.js server

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
webpack version 3, nodejs v8.10.0

**Comment by Legends** [comment]
nodejs v0.12 ?

**Comment by tzahiba** [comment]
@Legends Edited, accidently put my npm version.. haha

**Comment by montogeek** [comment]
This is not a webpack bug, whatever you are using to serve your html files doesn't support `index.html` as default index file.

**Comment by tzahiba** [comment]
What do you mean? am i not using webpack to serve it?

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by ooflorent** [comment]
@tzahiba webpack is a **bundler**. It compiles your JavaScript codebase into one (or multiple) files. You should have a look at `webpack-dev-server` or `webpack-serve` documentation if you want to host your generated files during development. If you want to generate an `index.html` file, you could try `html-webpack-plugin`.
