### ISSUE TITLE
How can I get "mode" parameter in webpack.config.js of webpack 4

### ISSUE THREAD

**Issue by heju123** [webpack/webpack#7005]
I‘m creating a script as "webpack --mode production" in package.json,and how can i get this "mode" parameter in webpack.config.js
If someone konw,plz tell me the good way

**Comment by montogeek** [comment]
It looks like some paths are misconfigured. I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.

**Comment by montogeek** [comment]
Use environment variables, `webpack --env.mode="production"`,
```
const mode = process.env.mode

config = {
  mode,
  ...
}
```

**Comment by heju123** [comment]
ok,thx for answering

**Comment by robertmain** [comment]
A much better way is 


```js

module.exports = ({mode = 'development'}) => ({
    mode,
    // Other webpack config goes here
});
