### ISSUE TITLE
Webpack Parser API is not comprehensibly documented and the example does not work.

### ISSUE THREAD

**Issue by theS3ns** [webpack/webpack#7006]
Hello

Your [API documentation](https://webpack.js.org/api/parser/#hooks) is not understandable. We tried again and again to read the own written functions in the parser but none of it is understandable or properly documented.

`compiler.hooks.normalModuleFactory.tap(factory => {
  factory.hooks.parser.tap((parser, options) => {
    parser.hooks.someHook.tap(...)
  })
})`
 
After several attempts with searches on Google, stackoverflow and repository "tapable" we decided to open a GitHub Webpack ticket.  

Our goal is to mark your own API function calls as deprecated in the build process.

We ask you to extend the API documentation with a comprehensible example.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
"webpack": "^4.5.0"

**Comment by ooflorent** [comment]
@webpack-bot move to webpack/webpack.js.org
