### ISSUE TITLE
Watch Mode re-emitting/re-building untouched files

### ISSUE THREAD

**Issue by Pymous** [webpack/webpack#7007]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In Watch Mode, using ExtractTextPlugin/SASS-Loader in a multi-entry context, and editing a JS file emit the .css too, even if not modified

**If the current behavior is a bug, please provide the steps to reproduce.**
I made the smallest code to reproduce the issue, available here : https://gist.github.com/Pymous/3f73d4f7f6e69cf9ced909b384a11d13

**What is the expected behavior?**
Editing the JS file should re-emit only the JS file.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Webpack : 4.5.0

Thanks for your work !

**Comment by ooflorent** [comment]
Don’t use ETWP with webpack 4. Use `mini-css-extract-plugin` instead.

**Comment by Pymous** [comment]
Thanks for the advice, I tried it on my local code and it's working just fine !

Weirdly, I still have the issue on our dev server (a Debian), editing the .JS file re-built the .SCSS, but not on my local machine ; same versions of everything (as far as I can tell).

**Comment by jgidlow** [comment]
@Pymous would you mind sharing your new config file? 

I'm having the same issue with `mini-css-extract-plugin` (0.4.0) and `sass-loader` (6.07) with multi-main entries that has entries pointing to scss files. A rebuild in watch mode has become about 1.5s slower with Webpack 4.5.0 compared to 3.11.0 for me and I'm guessing it's related to Webpack re-emitting all scss files in all entry points even when I just change something in an unrelated js file.

**Comment by Pymous** [comment]
Actually, I was wrong, we have Node v6.10.3 on our dev server, while I have Node v9.11.1 on my local machine, could the issue be related to that ? 

@jgidlow : Here is my minimal WebPack config triggering the issue on Debian (but not on my local machine) :

```const MiniCssExtractPlugin = require("mini-css-extract-plugin");

module.exports = {
    entry: {
        app: './src/js/main.js',
        style: './src/css/main.scss'
    },
    output: {
        path: './',
        filename: '[name].js'
    },
    module: {
        rules: [
            {
                test: /\.scss$/,
                use: [MiniCssExtractPlugin.loader, 'css-loader', 'sass-loader']
            }
        ]
    },
    plugins: [
        new MiniCssExtractPlugin({
            filename: "[name].css",
            chunkFilename: "[id].css"
        })
    ]
};```

**Comment by Pymous** [comment]
Quick update to my previous question, even with NodeJS 8.11.1 the issue is present on Debian.

**Comment by altphi** [comment]
I may have the same or similar issue.   Using 4.5.0,  I have multiple entry points and when `mode` is `development` the expected watch behavior occurs.  But when `mode` is `production` or `none`, then _ALL_ the entry points are rebuilt with only a single file change (a file which is only in 1 entry point). 

So, question for @Pymous: what mode(s) are you building with?

**Comment by Pymous** [comment]
@altphi : Sadly, it's development mode, so it's not related to the mode I guess.

You're using --watch in production mode ? (none is production if I recall the documentation)

**Comment by altphi** [comment]
Yeah, a sidebar from your issue, but, I need to build bundles that do not use `eval`.  AFAICT mode=development bootstraps/wraps everything with it.

**Comment by Pymous** [comment]
And what is your OS ? I have the issue on Debian, but not Windows.

**Comment by Pymous** [comment]
That's interesting for @altphi , thanks @sokra !

So, we can go back to the main issue, dev mode on Debian, triggering the rebuilt of every file (including SCSS) when you edit a JS file ! :D

**Comment by sokra** [comment]
Could you create a repro without the extract-text-webpack-plugin? It's kind of unsupported/broken for webpack 4.

**Comment by AndrewRayCode** [comment]
If I change a javscript file, every single file in my project is printed out, and re-emitted:

```
webpack built 9a36c407af14d6e358de in 32446ms
... many more ...
[0]             assets/images/charismas-world.gif   4.78 MiB          [emitted]  [big]
[0]        35de1859f04f5fb9ddd6cf91d3a681e7.woff2   14.6 KiB          [emitted]
[0]         3f13495780aa8f7e4c740d2f572e74cc.woff   18.8 KiB          [emitted]
[0]          b71e6db6d7a9562e83c71fcc6f43b005.ttf   40.1 KiB          [emitted]
[0]        18a2daa23573a7f50324cc253c25f25b.woff2   17.5 KiB          [emitted]
[0]         f7f3401c7c215b71ac1bc432859eff08.woff   22.4 KiB          [emitted]
[0]          b1f78ea61371d0e09ff69f5f0985871d.ttf   47.2 KiB          [emitted]
[0]                 assets/images/ajax-loader.gif   9.21 KiB          [emitted]
[0]                   assets/images/icon-jump.png   3.76 KiB          [emitted]
[0]              assets/images/icon-down-pipe.png   4.14 KiB          [emitted]
[0]                assets/images/icon-up-pipe.png   4.12 KiB          [emitted]
[0]               assets/images/icon-zoom-out.png   2.64 KiB          [emitted]
[0]                assets/images/icon-zoom-in.png   5.21 KiB          [emitted]
[0]                  main-9a36c407af14d6e358de.js   3.96 MiB       0  [emitted]  [big]  main
[0]          0.c5976ad082c8eab36bd5.hot-update.js   40.8 KiB       0  [emitted]         main
[0]          c5976ad082c8eab36bd5.hot-update.json   43 bytes          [emitted]
```

Here's my plugin list:

```
plugins: [
    new webpack.DllReferencePlugin({
        context: path.join(__dirname, '../'),
        manifest: require(path.join(
            assetsPath,
            'manifests/vendor-manifest.json',
        )),
    }),
    webpackIsomorphicToolsPlugin.development(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoEmitOnErrorsPlugin(),
    new webpack.IgnorePlugin(/webpack-stats\.json$/),
    new webpack.DefinePlugin({
        __SERVER__: false,
        __DEVELOPMENT__: true,
    }),
    new WebpackNotifierPlugin({ title: 'Dev build complete' }),
],
```

I don't currently do any code splitting. I tried removing `ModuleConcatenationPlugin` to test if it was doing some top level re-creating of things, but it didn't affect the re-emitting of everything.

I've updated a lot of dependencies while upgrading to webpack 4, so i'm not sure what the culprit is, but my already slow bundle build/rebuild time has gotten significantly slower. I'm trying to track down what's going on.
