### ISSUE TITLE
Document pathinfo is on for dev builds.

### ISSUE THREAD

**Issue by jdalton** [webpack/webpack#7008]
Current docs [state it defaults to `false`](https://webpack.js.org/configuration/output/#output-pathinfo ) but it is [enabled for dev builds](https://github.com/webpack/webpack/blob/b30de38eb5311051388db05287aa3fd951fa41de/lib/WebpackOptionsDefaulter.js#L147-L150).

**Comment by Legends** [comment]
Send a PR..

**Comment by montogeek** [comment]
@webpack-bot move to webpack/webpack.js.org
