### ISSUE TITLE
Webpack 4 bundles wrong javascript

### ISSUE THREAD

**Issue by salahassi** [webpack/webpack#7022]
I'm building an SSR Vue project, and I'm using webpack to bundle my files. The bundled file for the server works fine but the client one shows an error on the console and the code does not work.

I use these scripts:

    "scripts": {
        "serve": "cross-env NODE_ENV=serve webpack-dev-server --config webpack/webpack.client.js --open --inline --hot",
        "dev": "cross-env NODE_ENV=dev && npm run build-client && npm run build-server",
        "prod": "cross-env NODE_ENV=prod && npm run build-client && npm run build-server",
        "build-serve": "cross-env NODE_ENV=dev npm run build-server && npm run build-client && node server.js",
        "build-client": "webpack --config webpack/webpack.client.js --progress --bail",
        "build-server": "webpack --config webpack/webpack.server.js --progress --bail"
      }

and these are the webpack related packages:

    "webpack": "^4.5.0",
    "webpack-cli": "^2.0.14",
    "webpack-dev-server": "^3.1.3",
    "webpack-merge": "^4.1.2"

The weird thing is when using `webpack-dev-server`, the code works fine. Also when bundling the server file, it shows the results fine. But when using the client bundled file, it's not working.

and here is the error:

[![enter image description here][1]][1]
[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/Egz4i.png
  [2]: https://i.stack.imgur.com/2zmYz.png

**UPDATE:**

webpack.client.js:
    
    var path = require('path')
    var webpack = require('webpack')
    var merge = require('webpack-merge')
    var base = require('./webpack.config')
    
    base.resolve.modules = (base.resolve.modules || []).concat([
    
    ])
    base.plugins = (base.plugins || []).concat([
      new webpack.DefinePlugin({
        isServer: false
      })
    ])
    
    if (process.env.NODE_ENV == 'prod') {
      base.plugins = (base.plugins || []).concat([
        new webpack.optimize.UglifyJsPlugin({
          compress: {
            warnings: false,
            drop_console: true
          },
          output: {
            comments: false
          }
        })
      ]);
    }
    
    module.exports = merge(base, {
      entry: path.resolve(__dirname, '../src/entry/client-entry.js'),
      output: {
        path: path.resolve(__dirname, '../dist'),
        publicPath: '/',
        filename: 'assets/build-client.js?[hash]',
      }
    
    });

webpack.config.js:

    var path = require('path')
    var webpack = require('webpack')
    var CopyWebpackPlugin = require('copy-webpack-plugin');
    var ExtractTextPlugin = require("extract-text-webpack-plugin");
    var extractCSS = new ExtractTextPlugin('assets/styles.css');
    
    
    module.exports = {
      // devtool: "source-map",
      mode: 'none',
      module: {
        noParse: /es6-promise\.js$/, // avoid webpack shimming process
        rules: [
          {
            test: /\.vue$/,
            loader: 'vue-loader',
          },
          {
            test: /\.html$/,
            loader: 'raw-loader'
          },
          // {
          //   test: /\.js$/,
          //   loader: 'babel-loader',
          //   exclude: [/node_modules/, 'src/pages', 'src/components', 'src/layouts']
          // },
          {
            test: /\.(png|jpg|gif|svg|woff|woff2|eot|ttf)$/,
            loader: 'file-loader',
            options: {
              name: 'assets/[name].[ext]?[hash]'
            }
          },
          {
            test: /\.scss$/,
            loader: extractCSS.extract('css-loader!sass-loader')
          },
          {
            test: /\.css$/,
            loader: 'vue-style-loader!css-loader'
          }
        ]
      },
      plugins: [
        extractCSS,
        new webpack.ContextReplacementPlugin(/moment[\\\/]locale$/, /^\.\/(en|zh-tw)$/),
        new webpack.DefinePlugin({
            'process.env': {
                'NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'dev')
            }
        }),
        // new webpack.optimize.CommonsChunkPlugin({
        //   name: 'vendor'
        // }),
        // generate output HTML
      ],
      resolve: {
        modules: [
          'src',
          'node_modules',
        ],
        alias: {
          '_': 'lodash',
          'vue$': 'vue/dist/vue',
          'assets': path.resolve(__dirname, '../src/assets'),
        }
      },
      devServer: {//this handles the webpack router
        historyApiFallback: true,
        noInfo: true
      }
    }
    
    if (process.env.NODE_ENV != 'serve') {
    
      module.exports.plugins = (module.exports.plugins || []).concat([
        new CopyWebpackPlugin([
          {from: './assets', to: 'assets'},
          {from: './index.html'},
          {from: './index.server.html'}
        ])
      ])
    }
    
    if (process.env.NODE_ENV == 'prod') {
      module.exports.plugins = (module.exports.plugins || []).concat([
        new webpack.LoaderOptionsPlugin({
          minimize: true
        })
      ])
    }

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by sokra** [comment]
This can happen when multiple processes write to the same file.

**Comment by evilebottnawi** [comment]
@salahassi problem still exists?

**Comment by salahassi** [comment]
The problem was solved. The plugin `CopyWebpackPlugin` was messing things up.

**Comment by chrisharrison** [comment]
How was it solved?
