### ISSUE TITLE
webpack 4 - Adding minChunks to optimization.splitChunks breaks common chunk

### ISSUE THREAD

**Issue by johannes-z** [webpack/webpack#7026]
**Do you want to request a *feature* or report a *bug*?**

**BUG**

**What is the current behavior?**

When adding the `minChunks` property to `optimization.splitChunks.cacheGroups.X`, the common chunk breaks, e.g. either isn't emitted at all, or contains ALL the code of all entries.

**If the current behavior is a bug, please provide the steps to reproduce.**

This configuration doesn't produce a `commons.js` file at all, although there are multiple entry points with the same `node_modules` dependencies (adding `test` doesn't change anything either).
```js
  optimization: {
    splitChunks: {
      cacheGroups: {
        'commons': {
          minChunks: 2,
          chunks: 'all',
          name: 'commons',
          priority: 10,
          enforce: true,
        },
      },
    },
  },
```

This emits a `common.js` that includes ALL the source code. All the other chunks are basically empty.
```js
  optimization: {
    splitChunks: {
      minChunks: 2,
      cacheGroups: {
        'c4.commons': {
          chunks: 'all',
          name: 'c4.commons',
          priority: 10,
          enforce: true,
        },
      },
    },
  },
```

**What is the expected behavior?**

I expect that there'd be a `common.js` that has all the chunks that are used more than once across all entry points.

**If this is a feature request, what is motivation or use case for changing the behavior?**

-

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

```
node v9.5.0
yarn 1.5.1
Window 10 r1709

    "webpack": "^4.5.0",
    "webpack-cli": "^2.0.14",
```

**Comment by Legends** [comment]
Can you create minimal repo, which reproduces your issue. Thanks.

**Comment by johannes-z** [comment]
So actually I came across a very strange behaviour while creating the minimal repo. Using 2 simple `index.js` files with a `node_module` import worked just fine with the parameters provided in my initial message. Then I realized that it probably has to do with one of the node_modules I'm using (my own in fact). Instead of updating with npm directly, I created symlinks in the `node_modules` folders of the project.

Before I added the dependency to the symlinked project this was emitted:

```
commons.js  90.1 KiB       0  [emitted]  commons
 entry2.js  1.66 KiB       1  [emitted]  entry2
 entry1.js  1.66 KiB       2  [emitted]  entry1
```

and afterwards:

```
commons.js   180 KiB       0  [emitted]  commons
 entry2.js  1.67 KiB       1  [emitted]  entry2
 entry1.js  1.67 KiB       2  [emitted]  entry1
```

In my case, `entry1` and `entry2` both have a dependency to `Vue`, so it's extracted into the `commons.js` file. The other (symlinked) `node_module` **also** has a dependency to `Vue`, which is included in the emitted `build.js` of the `node_module`. With the `node_module` dependency added to `entry1` and `entry2`, the `commons.js` build now includes everything from the `build.js` and the `Vue` dependency. So now `Vue` is included twice, as indicated by the file sizes.

I suspect that this is the problem that also leads to the chunk splitting not working in my (much bigger) project.

You can find the repo here: https://github.com/johannes-z/webpack-minChunks 

For my testcases I ran these commands on windows inside the project folder: 

```sh
mklink /J "./src/app1/node_modules/external" "external"
./src/app1/node_modules/external <<===>> external

mklink /J "./src/app2/node_modules/external" "external"
./src/app2/node_modules/external <<===>> external
```

**Comment by sokra** [comment]
`mklink /J` creates a "Hard Link". This is NOT a symlink. webpack doesn't see that `app1/node_modules/external` and `app2/node_modules/external` resolve to the same directory.

You should use `mklink /D` instead, which creates a "Soft Link" (symlink).

**Comment by sokra** [comment]
And the first `splitChunks` snippet is correct.

**Comment by johannes-z** [comment]
Ok I will try using `/D`. Also, I tried finding the *new* docs for `chunks: '...'`, describing what the difference for all the options were, but couldn't find it. Can you point me to it?

**Comment by johannes-z** [comment]
So I don't know if this is relevant but in my real life application case `app1`

**Comment by johannes-z** [comment]
Thanks @sokra!

So I don't know if this is relevant, but in my real-life application, `app1` and `app2` both had `external` in their node_modules, rather than the *umbrella* project. I removed it from there and explicitly added it to the *umbrella* project, and now the chunks are extracted correctly.
