### ISSUE TITLE
EvalSourceMapDevToolPlugin is not working as described in documentation

### ISSUE THREAD

**Issue by barcicki** [webpack/webpack#7030]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

EvalSourceMapDevToolPlugin is not working as described in documentation (https://webpack.js.org/plugins/eval-source-map-dev-tool-plugin/) - it is not supporting options the same way as SourceMapDevToolPlugin.

**If the current behavior is a bug, please provide the steps to reproduce.**

Use following configuration:
```js
const webpack = require('webpack');
const path = require('path');

module.exports = {
    mode: 'none',
    entry: {
        'prod': './src/index.js',
        'dev': './src/index.js',
    },
    output: {
        path: path.resolve(__dirname, './dist/'),
        filename: '[name].js',
        libraryTarget: 'umd'
    },
    plugins: [
        new webpack.EvalSourceMapDevToolPlugin({
			filename: '[name].map.js',
            exclude: /prod/
        })
    ]
};
```
where contents of `src/index.js` is irrelevant but should be valid JS.

**What is the expected behavior?**

I expect that Webpack produces 3 files: 
* prod.js (without sourcemap), 
* dev.js (with link to source map in external file), 
* dev.map.js (sourcemap for dev.js)

The exact behavior can be achieved by changing `EvalSourceMapDevToolPlugin` to `SourceMapDevToolPlugin` in above example

Currently Webpack produces 2 identical files.

My observations:
- `filename` prop is ignored
- `exclude` or `include` doesn't work for entry names (it works for deep modules)

**If this is a feature request, what is motivation or use case for changing the behavior?**

N/A

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Webpack @ 4.5.0
Node @ 9.10.1
NPM @ 5.8.0
Windows 10 x64

**Comment by ooflorent** [comment]
@sokra Is it a bug or a documentation issue?

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack.js.org

There is no `filename` option.

It works on module base so `include` etc. filter on modules.

**Comment by DaniJG** [comment]
I agree with @barcicki. The [docs](https://webpack.js.org/plugins/eval-source-map-dev-tool-plugin/#exclude-vendor-maps) specifically mention how to avoid generating source maps for vendor bundles but the plugin doesn't seem to handle the `exclude` property as expected:
```
new webpack.EvalSourceMapDevToolPlugin({
  filename: '[name].js.map',
  exclude: ['vendor.js']
})
```
