### ISSUE TITLE
ProvidePlugin injection into .mjs files seems to be broken

### ISSUE THREAD

**Issue by xandris** [webpack/webpack#7032]
**Do you want to request a *feature* or report a *bug*?**

A bug, I think.

**What is the current behavior?**

At runtime, a `.mjs` module with injections from `ProvidePlugin` will throw an error at runtime, indicating that `require` is not defined. The final module code produced by webpack looks like this:

```javascript
/*! no static exports found */
/***/ (function(module, exports) {

/* WEBPACK VAR INJECTION */(function(foo) {console.log(foo);
/* WEBPACK VAR INJECTION */}.call(this, require("/Users/aparker/src/notes/webpack4upgrade/mjs-provide/foo.js")))

/***/ })

/******/ });
```

(Note the call to `require`.)

**If the current behavior is a bug, please provide the steps to reproduce.**

[You can reproduce the behavior using this repository.](https://github.com/xandris/webpack-provideplugin-mjs-bug)

**What is the expected behavior?**

The module should look more like this:

```javascript
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

/* WEBPACK VAR INJECTION */(function(foo) {console.log(foo);
/* WEBPACK VAR INJECTION */}.call(this, __webpack_require__(/*! ./foo.js */ "./foo.js")))

/***/ })

/******/ });
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

* `node -v`: `v9.11.1`
* `webpack -v`: `4.5.0`
* OS: Mac OS 10.13.4

**Comment by xandris** [comment]
I am completely willing to debug and submit a PR if this is indeed a valid bug, I just need some guidance figuring out what code to look at. Webpack is a big project!

**Comment by TheLarkInn** [comment]
Thanks so much for the report!

Some initial thoughts. The .mjs extension signals a very strict handling of only ESM syntax and dependencies within modules, so at face value I'm not the most surprised this isn't working.

Before thinking about a PR, would you be able to shed some light on the requirements for needing both the .mjs and using ProvidePlugin? Or is the plugins injection something you only need in specific places etc.

**Comment by TheLarkInn** [comment]
My initial thoughts is that we definitely shouldn't throw if the two are being used independently. Before guiding you through a contribution, (which is super exciting nonetheless), I wanted to make sure this is Bug vs "Feature" (heavily quoted 😅)

**Comment by TheLarkInn** [comment]
cc @sokra @ooflorent thoughts?

**Comment by ooflorent** [comment]
This is expected since `ProvidePlugin` injects a `require` call and `javascript/esm` skips `require` interception. There are a few ways to solve this:

1. Disable `ProvidePlugin` for `javascript/esm`
2. Or generate an `import` statement in `javascript/esm`

I think option 1 is the way to go.

**Comment by TheLarkInn** [comment]
I agree. 1 sounds the best to me as well.

@xandris how can I help you in submitting this PR?

**Comment by sokra** [comment]
1

send a PR

**Comment by motiz88** [comment]
To add some context here, I'm getting an identical error when trying to bundle a [module that references `process`](
https://github.com/graphql/graphql-js/blob/5fe39262a308df944a87cc85b225228e7556aaa4/src/jsutils/instanceOf.js#L19) with close to no config on my part (i.e. no explicit use of `ProvidePlugin`). Would option 1 address the use case of referencing node builtins in `.mjs` files?

**Comment by motiz88** [comment]
I can't seem to find any official comms from node.js on their plan for this, but can verify that with Node 9.11.1 and `--experimental-modules`, `process` is automatically available without importing anything.

**Comment by motiz88** [comment]
Respectfully, would anyone care to elaborate on why option 2 isn't the preferred one? I mean, I know next to nothing about the Webpack codebase, but I see `import` injection as the closest thing to "correct" in this scenario. Especially with regards to keeping Node globals working, which otherwise is quite the breaking change for users of libraries that rely on them.

**Comment by sokra** [comment]
Actually option 2 is preferred, but it's really complex to do. The way these stuff is injected is pretty old (and I hope we could get rid of this soon). So option 1 will disable this feature for now, so it doesn't break anymore and we can figure out a way to improve the variable injection workflow.

**Comment by xandris** [comment]
I changed our approach to polyfilling, which obviated the need to use `ProvidePlugin` for most of our use cases, but we too are using `graphql` which is publishing `.mjs` files and referencing Node APIs. How do you suggest we proceed in this case?

I would prefer fixing this to actually perform the variable injection where needed into ES modules (i.e. have these global node APIs available) and am willing to work towards a PR for that. I am not willing to submit a PR that disables this kind of injection on .mjs files and breaks support for these libraries.

**Comment by sokra** [comment]
@ooflorent already did some refactoring to fix these injection problem in the `next` branch. You can send a PR adding a few test cases to check if it works correctly.

**Comment by felixfbecker** [comment]
This is breaking [`graphiql`](https://github.com/graphql/graphiql). It depends on [`graphql`](https://github.com/graphql/graphql-js), which contains a reference to `process.env`: https://github.com/graphql/graphql-js/blob/dec24f9/src/jsutils/instanceOf.js#L19-L36

Now, this file uses the `.js` extension, but it's Flow, and all files get compiled to an ESM build which uses `.mjs` and is referenced in package.json with the `module` field: https://github.com/graphql/graphql-js/blob/dec24f9/package.json#L7

So when you want to use `graphiql`, and bundle your project with webpack, you get a `.mjs` file with a reference to `process.env.NODE_ENV` which is not getting replaced and triggers the above error.

**Comment by felixfbecker** [comment]
Filed https://github.com/graphql/graphql-js/issues/1536 and https://github.com/graphql/graphiql/issues/721, but to me it seems like this is a webpack bug. I don't see why a ESM file shouldn't be allowed to use `process.env.NODE_ENV` like other files can.

**Comment by felixfbecker** [comment]
so now ProvidePlugin is disabled, but process.env references as those found in graphiql still won’t work. Could this be reopened?

**Comment by felixfbecker** [comment]
Oh, I thought it was handled by ProvidePlugin. What is handling process.env.NODE_ENV?

**Comment by vpzomtrrfrt** [comment]
If ProvidePlugin is now disabled for mjs files, what's the replacement?

**Comment by Chudesnov** [comment]
@vpzomtrrfrt depends on your use case. If you simply need a module available globally, use the [global scope](https://github.com/tc39/proposal-global). If you need to keep it clean and only inject the dependency into some modules, you may use the [BannerPlugin](https://webpack.js.org/plugins/banner-plugin/) with `raw` option to prepend a simple `import ${defaultExportName} from '${modulePath};` to every file (or only a subset, like .mjs files, using the [`test`](https://webpack.js.org/plugins/banner-plugin/#options) config option).

As sokra mentioned, work is being done in the webpack 6 branch to refactor variable injection, so, if you're really interested in the long-term solution, you should check out the [`next`](https://github.com/webpack/webpack/tree/next) branch to figure out what needs to be done to restore ProvidePlugin functionality for .mjs files.

**Comment by simonbuchan** [comment]
Hmm, I'm on webpack 4.27.1, but I'm still getting `/* WEBPACK VAR INJECTION */}.call(this, require("./../../process/browser.js")))` injected into `graphql/jsutils/instanceOf.mjs`, despite https://github.com/webpack/webpack/commit/7c8f0c94271c3c5e5f67256aad366244f7525d44 looking like it would stop this happening? Or does webpack not automatically class `.mjs` as `javascript/esm`?

**Comment by Chudesnov** [comment]
> Or does webpack not automatically class .mjs as javascript/esm?

It does, unless you have configured it to be javascript/auto in your config, or one of your loaders mutates the module type during transpilation.
