### ISSUE TITLE
I have a few loaders that I want added to the list

### ISSUE THREAD

**Issue by dschissler** [webpack/webpack#704]
* [po-loader](https://github.com/perchlayer/po-loader)
* [nunjucks-loader](https://github.com/perchlayer/nunjucks-loader)

nunjucks-loader needs a lot of work.

**Comment by sokra** [comment]
If you think they are ready for the public, feel free to add them to the list... (Edit button top right)

**Comment by dschissler** [comment]
@sokra I can see where I added it to the source almost four months ago but its not showing up on the live page.
