### ISSUE TITLE
resolveWeak returns an empty object for JSON split chunks

### ISSUE THREAD

**Issue by malliapi** [webpack/webpack#7044]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**

resolveWeak returns an empty object when used with an entry point.

**If the current behavior is a bug, please provide the steps to reproduce.**
using translations =`__webpack_require__(require.resolveWeak(`../../translations/${market}.json`));`
with a script from an equivalent entry point loaded prior to the main app, returns an empty object.

**What is the expected behavior?**
the translation is loaded.
webpack version : 4.5.0

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by malliapi** [comment]
Prior to webpack 4 i had achieved this via using a normal require and simply including the translations bundle i needed, however, since webpack 4 - using splitChunks.chunks "all", means that the main app will not run until ALL of the chunks are present, is there a way to circuimvent this?

**Comment by malliapi** [comment]
I hsve now further analysed the issue and it seems that entry points loaded with resolveWeak work fine when they are js files, but do not work when they are json files. @montogeek i believe that now an example is not needed?  The issue is quite clear, since as soon as the file is transformed to a js file with an export everything is working as expected.

**Comment by malliapi** [comment]
not sure if this is relevant but i can see a difference where in the json file entry point the file produced does not include the following code `.call(this, __webpack_require__(/*! ./../node_modules/webpack/buildin/module.js */ "./node_modules/webpack/buildin/module.js")(module)))`

**Comment by malliapi** [comment]
@sokra is this expected behaviour? What is the difference between bundling a js vs a json file? should there be any?

**Comment by sokra** [comment]
Use ``import(/* webpackChunkName: "[request]" */ `../../translations/${market}`);`` to load the translations.

This creates a output chunk per translation. You can preload these translations by adding the output chunk as `<script>` tag.

**Comment by malliapi** [comment]
oh dear - yes it does work. It was one of the first things i tried but in my tiredness to find a solution i think i missed that it in fact worked. @sokra so many thanks. .clossing issue
