### ISSUE TITLE
Webpack 4: why not remove “webpackBootstrap” code after "concatenateModules" is true

### ISSUE THREAD

**Issue by weifeiyue** [webpack/webpack#7045]
Webpack 4: why not remove “webpackBootstrap” code after "concatenateModules" is true?
“webpackBootstrap” code is dead code

**Comment by ooflorent** [comment]
Actually it is dead code if there is no bailout and no async chunks. In a real application, it never happens.

**Comment by egoroof** [comment]
It happens if you build a library

**Comment by vankop** [comment]
Should work with `webpack@next`. Feel free to report new issue with reproducible repo.
