### ISSUE TITLE
Cannot find module './deps/node_modules/imports-loader/index.js'

### ISSUE THREAD

**Issue by ianbytchek** [webpack/webpack#705]
Upgraded the webpack recently, now webpack fails with the following exception when loading the configuration.

```sh
$ webpack -v

module.js:340
    throw err;
    ^
Error: Cannot find module './deps/node_modules/imports-loader/index.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at DependenciesBlock.loadPitch (/usr/local/lib/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:190:16)
    at DependenciesBlock.doBuild (/usr/local/lib/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:224:4)
    at DependenciesBlock.build (/usr/local/lib/node_modules/webpack/lib/NormalModule.js:66:14)
    at Tapable.Compilation.buildModule (/usr/local/lib/node_modules/webpack/lib/Compilation.js:120:9)
    at Tapable.<anonymous> (/usr/local/lib/node_modules/webpack/lib/Compilation.js:292:9)
    at /usr/local/lib/node_modules/webpack/lib/NormalModuleFactory.js:104:13
```

I narrowed this down to `output.filename` config option, when I comment it out, the exception disappears.

```js
output: {
    path:     path.join(configuration.rootDir, '/public/js'),
    pathinfo: true,
    filename: '[name].js'
},
```

This might be related to aliased `node_modules`, which sits a few levels up, but this never was an issue before.

**Comment by sokra** [comment]
Pass an absolute path to `module.loaders[x].loader`.

**Comment by ianbytchek** [comment]
Not sure if I got you right, trying this doesn't work:

```js
module: {
    loaders: [
        {test: /\.hbs$/, loader: path.join(configuration.rootDir, 'node_modules/handlebars-loader'), query: {helperDirs: path.join(configuration.rootDir, '/src/hbs')}}
    ]
},
```

There are a lot of similar issues, I don't think this is webpack-related, but it used to work just fine a few hours ago. I'll update once research more.

**Comment by sokra** [comment]
`path.join` doesn't make sure it's absolute... maybe `rootDir` is relative. Try `path.resolve` instead.

**Comment by ianbytchek** [comment]
```
project
    build
        js
            webpack.config
    node_modules -> ./deps/node_modules/
```

This is roughly what I have. When I turn the `node_modules` in the root into the symlink, everything works again, but that's a no-goer as that symlink is in git, changing it every time I checkout the project invalidates the whole point of the alias…

`configuration.rootDir` is an absolute path, I tried wrapping `path.join(configuration.rootDir, 'node_modules/handlebars-loader')` with `path.resolve` – that doesn't do anything.

**Comment by ianbytchek** [comment]
Basically it seems that it understands that it's dealing with the symlink, located at `/foo/bar/project/node_modules` but uses that symlink's value './deps/node_modules/' out of the context of the absolute path.

**Comment by sokra** [comment]
Ah OK. It's a bug in symlink handling... I'll check tomorrow...

**Comment by ianbytchek** [comment]
Thanks Tobias. Sleep time…

**Comment by sokra** [comment]
Should work now... Could you try again with updated enhanced-resolve version?

**Comment by ianbytchek** [comment]
Works. Thanks for the fast fix, as always!

**Comment by datwheat** [comment]
This is how i solved my issue https://webpack.github.io/docs/configuration.html#resolve-modulesdirectories
