### ISSUE TITLE
Can't control log level in Node.js API or webpack-dev-middleware

### ISSUE THREAD

**Issue by cnshenj** [webpack/webpack#7052]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
CLI watch mode has a info-verbosity option. It also respects the `stats` config.
Node.js API and webpack-dev-middleware doesn't have the same control.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Node.js API and webpack-dev-middleware can control log level the same way as CLI, e.g. `{ stats: { all: false } }`.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Calling Node API in task runners, such as Gulp. It is not obvious file change is detected and webpack starts compilation (especially when compilation takes some time). Only when compilation is completed then the callback can be used to print some information.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Node.js 8.11.1
webpack 4.5.0
Windows 10 x64

**Comment by cnshenj** [comment]
Probably related to #1872

**Comment by sokra** [comment]
The node.js API doesn't print anything by default. You need to print it manually i. e. via `console.log(stats.toString())`. `toString()` can be passed options.

webpack-dev-middleware has a `stats` option, which allows to control the output.
