### ISSUE TITLE
__webpack_require__ is too slow

### ISSUE THREAD

**Issue by korbinzhao** [webpack/webpack#7054]
I have the same problem like issue [2219](https://github.com/webpack/webpack/issues/2219). 2 years past, it sames still not have an official solution to solve this problem. I wanna know whether webpack team has done something to solve this problem. I hope an elegant way supported by webpack. It will help me a lot in my mobile project, thx a lot.

**Comment by evilebottnawi** [comment]
@korbinzhao Thanks for issue, close in favor https://github.com/webpack/webpack/issues/2219 (reopen)
