### ISSUE TITLE
Loader can't modify resource type without accessing private API

### ISSUE THREAD

**Issue by cletusw** [webpack/webpack#7057]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Now that webpack has the concept of module type (JSON, JS, CSS, WASM), loaders which convert resources from one type to another do not work without either requiring the end user to modify their config (i.e. for a loader that converts to JS the user must add `type: 'javascript/auto'` to their config) or resorting to modifying private internal webpack APIs. The former leaks internal loader implementation details onto the user and doesn't work if the user wants to pipe the output of that loader into another, while the latter is brittle and prone to breakage in future webpack versions.

See https://github.com/webpack/webpack/issues/6572#issuecomment-374987270, #6586, #6725, webpack-contrib/file-loader#264, webpack-contrib/file-loader#259, webpack-contrib/bundle-loader#74

**If the current behavior is a bug, please provide the steps to reproduce.**
Contrived example: https://github.com/cletusw/webpack-issue-7057

**What is the expected behavior?**
Webpack should support loaders that convert between resource types, probably via the loader API.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Node v8.11.0
webpack 4.5.0
Linux

**Comment by sokra** [comment]
Makes sense. Maybe a `this.setModuleType("javascript/auto")` in the loader API.

Do you want to send a PR? Note that module type set by loader should not leak between rebuilds. It need to be reset on unbuild.

**Comment by evilebottnawi** [comment]
Bump

**Comment by evilebottnawi** [comment]
bump

**Comment by Lyrkan** [comment]
Bump so it doesn't get closed

I tried adding the new method here: https://github.com/webpack/webpack/pull/10097

**Comment by Lyrkan** [comment]
@evilebottnawi I think it can be closed based on @sokra's comment here: https://github.com/webpack/webpack/pull/10097#issuecomment-567031319

**Comment by evilebottnawi** [comment]
Yes, you are right, in webpack@5 it is possible to achieve that using plugin (you can look on asset or json plugin)

**Comment by ScriptedAlchemy** [comment]
@Lyrkan @evilebottnawi 
Im wondering if you might be able to provide a hint here. Im attempting to upgrade the translation loader used at my company- which mentioned this git issue. 

The error getting thrown in Webpack 5 is as followed
```
Module parse failed: Abstract method Parser.parse. Must be overridden.
File was processed with these loaders:
 * ./loaders/lingui.js
```

https://gist.github.com/ScriptedAlchemy/4d3f8e63d16d9b9150e30e8083d91048

It sounds like I need to replace the this._module.parser with another one? Does anyone have any hints on how I could achieve this?

The likely code in question is 
```

  // Webpack 4 uses json-loader automatically, which breaks this loader because it
  // doesn't return JSON, but JS module. This is a temporary workaround before
  // official API is added (https://github.com/webpack/webpack/issues/7057#issuecomment-381883220)
  // See https://github.com/webpack/webpack/issues/7057
  if (JavascriptParser && JavascriptGenerator) {
    this._module.type = "javascript/auto";
    this._module.parser = new JavascriptParser();
    this._module.generator = new JavascriptGenerator();
  }
```

**Comment by Lyrkan** [comment]
@ScriptedAlchemy I haven't tested it with the latest version of Webpack 5 but it worked a while ago:

```js
const LoaderDependency = require('webpack/lib/dependencies/LoaderDependency');

const requiredType = 'javascript/auto';
if (this._module.type !== requiredType) {
    // Try to retrieve the factory used by the LoaderDependency type
    // which should be the NormalModuleFactory.
    const factory = this._compilation.dependencyFactories.get(LoaderDependency);
    if (factory === undefined) {
        throw new Error('Could not retrieve module factory for type LoaderDependency');
    }

    this._module.type = requiredType;
    this._module.generator = factory.getGenerator(requiredType);
    this._module.parser = factory.getParser(requiredType);
}
```

**Comment by ScriptedAlchemy** [comment]
@Lyrkan thank youuuuuuuu ill try this out
