### ISSUE TITLE
Add glob support to directory parameter of require.context

### ISSUE THREAD

**Issue by penx** [webpack/webpack#7058]
**Do you want to request a *feature* or report a *bug*?**

Request a feature - add glob support to directory parameter of [require.context](https://github.com/webpack/docs/wiki/context#requirecontext)

**What is the current behavior?**

```js
const req = require.context('../../../../components/*/src', true, /stories.js$/);
```

Errors with:

```
Module not found: Error: Can't resolve '../../../components/*/src' in './storybook/src/stories'
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

I have a monorepo (using yarn workspaces) and want to use require.context from one package to load in files following a certain pattern from all other workspaces. I want to target the src sub folder of these packages and not the transpiled lib/dist/es folders.

e.g.

```js
const req = require.context('../../../../components/*/src', true, /stories.js$/);
```

**Comment by sokra** [comment]
``` js
const req = require.context('../../../../components', true, /src\/.*stories.js$/);
```

**Comment by penx** [comment]
My understanding is that:

``js
 require.context('../../../../components', true, /src\/.*stories.js$/);
``

would match `components/some-component/node_modules/some-module/src/stories.js`, whereas my proposal above wouldn't.

I tried using `^` at the start of the regex but am not sure what string this is matching against - is it the full file path or a relative path? The wiki just says ["a regular expression to match files against"](https://github.com/webpack/docs/wiki/context#requirecontext).

I guess I could also use `(?!node_modules)` or similar in the regex but things could start getting complex compared to using a glob.

**Comment by penx** [comment]
I think the following regex should work:

```
const req = require.context('../../../../', true, /(packages|components)\/[^/]+\/src\/([^/]+\/)*stories.js$/);
```

**Comment by sokra** [comment]
When using `^` at the start consider it's matched with the relative request (like returned in `.keys()`).

i. e. `/^\.\/some\/folder\/stories\.js$/`
