### ISSUE TITLE
Browser fails to load async chunk. References file with "chunkhash" undefined.

### ISSUE THREAD

**Issue by b12k** [webpack/webpack#7061]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
Browser fails to import chunk because file```chunkhash``` is ```undefined``` in ```vendor.js```.
But chunks generated correctly.
Screenshots:
- [Webpack output](http://prntscr.com/j6bq66)
- [Generated files](http://prntscr.com/j6bpuc)
- [Browser console output](https://prnt.sc/j6bp3n)

It works in WP3. It also works if ```[chunkhash]``` is removed or ```[hash]``` is used in ```output.filename```

**If the current behavior is a bug, please provide the steps to reproduce.**
I have a tree of async chunks which are imported the following way:
```import(/* webpackChunkName: "home" */ './home.js')```
when home is mounded it imports
```import(/* webpackChunkName: "socketio" */ 'socket.io-client')``` 
WP4 config:
```javascript
// config written in ES6 class syntax
...
output.filename = 'js/[name].[chunkhash].js';
optimization = {
    namedChunks: true,
    runtimeChunk: {
      name: 'vendor',
    },
    splitChunks: {
      cacheGroups: {
        vendors: {
          test: /[\\/]node_modules[\\/]/,
          name: 'vendor',
          chunks: 'all',
        },
      },
    },
  };
...
```

**What is the expected behavior?**
Correct file name reference in ```vendor.js``` is expected. 

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
- Win10x64
- Node 9.11.1
- NPM 5.6.0
- Webpack 4.5.0

**Comment by TheLarkInn** [comment]
Is it possible that you could reproduce this with a standalone minimal github repo.

**Comment by sokra** [comment]
fixed in 4.6.0

**Comment by evilebottnawi** [comment]
Fixed

**Comment by maclockard** [comment]
Reason I ask is I'm currently seeing this on `4.24.0`. I would recreate a minimal repro, but making an example that does as much chunking as my prod build would be non trivial.
