### ISSUE TITLE
Webpack builds successfully but no bundled file

### ISSUE THREAD

**Issue by seunzone** [webpack/webpack#7065]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
I tried to run webpack 4, it compiles successfully as seen in the console but not bundle.js file or dist folder is created.

Here is the webpack.config.js file
`
const webpack = require('webpack');
const path = require('path');

const DIST_DIR = path.resolve(__dirname, 'dist');
const SRC_DIR = path.resolve(__dirname, 'client/src');

module.exports = {
  mode: 'development',
  entry: './client/src/js/index.js',
  output: {
    path: DIST_DIR,
    filename: 'bundle.js',
    publicPath: '/'
  },
  devServer: {
    contentBase: SRC_DIR
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
  ],
  resolve: {
    extensions: ['*', '.js', '.jsx']
  },
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        include: SRC_DIR,
        exclude: /node_modules/,
        loader: 'babel-loader',
        query: {
          presets: ['env', 'react', 'stage-2']
        }

      },
      {
        test: /\.css$/,
        use: [{ loader: 'style-loader' }, { loader: 'scss-loader' }, { loader: 'sass-loader' }]
      },
      {
        test: /\.scss$/,
        use: [{ loader: 'style-loader' }, { loader: 'css-loader' }, { loader: 'sass-loader' }]
      },
      {
        test: /\.png|jpg$/,
        use: [{ loader: 'url-loader' }],
        exclude: /node_modules/
      },
    ]
  },
};
`
 Here is the message logged to the console
`
webpack built 10140f6c991900482d36 in 1135ms
ℹ ｢wdm｣: Hash: 10140f6c991900482d36
Version: webpack 4.5.0
Time: 1135ms
Built at: 2018-4-17 14:25:48
    Asset     Size  Chunks             Chunk Names
bundle.js  713 KiB    main  [emitted]  main
Entrypoint main = bundle.js
[./client/src/js/index.js] 403 bytes {main} [built]
[./node_modules/fbjs/lib/ExecutionEnvironment.js] 935 bytes {main} [built]
[./node_modules/fbjs/lib/emptyFunction.js] 959 bytes {main} [built]
[./node_modules/fbjs/lib/emptyObject.js] 332 bytes {main} [built]
[./node_modules/fbjs/lib/getActiveElement.js] 912 bytes {main} [built]
[./node_modules/fbjs/lib/hyphenateStyleName.js] 848 bytes {main} [built]
[./node_modules/fbjs/lib/invariant.js] 1.47 KiB {main} [built]
[./node_modules/fbjs/lib/shallowEqual.js] 1.58 KiB {main} [built]
[./node_modules/fbjs/lib/warning.js] 1.85 KiB {main} [built]
[./node_modules/object-assign/index.js] 2.06 KiB {main} [built]
[./node_modules/prop-types/checkPropTypes.js] 2.81 KiB {main} [built]
[./node_modules/react-dom/cjs/react-dom.development.js] 592 KiB {main} [built]
[./node_modules/react-dom/index.js] 1.33 KiB {main} [built]
[./node_modules/react/cjs/react.development.js] 45.4 KiB {main} [built]
[./node_modules/react/index.js] 190 bytes {main} [built]
    + 7 hidden modules
ℹ ｢wdm｣: Compiled successfully.
`

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
It's expected to create a dist folder and generate a bundle.js file

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
I am using the node version 9.5.0 on ubuntu linux 16 and also running webpack 4.

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.
