### ISSUE TITLE
Consolidate the optimization.runtimeChunk true and 'single' options

### ISSUE THREAD

**Issue by edmorley** [webpack/webpack#7066]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
If `optimization.runtimeChunk` is set to `true`, multiple runtime chunks are created if there is more than one entrypoint. To avoid this, `optimization.runtimeChunk` has to be set to `'single'` instead.

**What is the expected behavior?**
That `optimization.runtimeChunk: true` does the right thing even when there are multiple entrypoints, and the `'single'` option be deprecated then eventually removed.

**If this is a feature request, what is motivation or use case for changing the behavior?**
* as an end-user it's confusing to have two options (`true` and `'single'`) to switch on what is mostly the same feature, where one (`true`) is actually 'broken'/suboptimal for multi-entrypoints. (In the docs and blog posts, people often forget to emphasise the need to use `'single'`)
* I can't see a disadvantage for using `'single'` even when there is only one entry-point - so why not make that be the behaviour for `true`?

Many thanks :-)

**Comment by sokra** [comment]
> is actually 'broken'/suboptimal for multi-entrypoints

What makes you believe it's broken/suboptimal?

Assuming the runtimeChunk is inlined into the HTML page, non-single runtime chunks are better in my opinion. A single runtime chunk only makes sense for scenarios where multiple entrypoints are included into a single page.

**Comment by edmorley** [comment]
Oh, mine wasn't being inlined. 

Digging in more, html-webpack-plugin doesn't support doing so by default, and instead requires use of either [inline-manifest-webpack-plugin](https://github.com/szrenwei/inline-manifest-webpack-plugin) or [webpack-inline-chunk-plugin](https://github.com/rohitlodha/html-webpack-inline-chunk-plugin).

So I guess this is a documentation issue - since neither of those plugins are listed anywhere on:
https://webpack.js.org/guides/caching/#extracting-boilerplate
https://webpack.js.org/guides/output-management/#the-manifest
https://webpack.js.org/concepts/manifest/
https://webpack.js.org/plugins/html-webpack-plugin/

It might also be worth clarifying the `optimization.runtimeChunk` entry here to explain that `true` is recommended when inlining the manifest and `'single'` when not inlining:
https://webpack.js.org/plugins/split-chunks-plugin/#optimization-runtimechunk

**Comment by armaanahluwalia** [comment]
@edmorley Were you ever able to figure this out? Trying to use ```optimization.runtimeChunk: 'single'``` but having trouble understanding where or how the runtime chunk can be included in our html templates ( complicated a bit further since we're using Django but that would be step 2 )

**Comment by edmorley** [comment]
I've not looked at this since - I was partly hoping someone would comment with an answer to the above :-)
