### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by UlisesTJ** [webpack/webpack#7068]
Hello! I'm a Graphic Designer interested in collaborating with this project _for free_ delivering a new logo, if theres such a possibility I would like to know how we can get in touch. Cheers!

**Comment by sokra** [comment]
What's wrong with the current logo?

**Comment by langpavel** [comment]
Why you didn't provide your proposal here? Disclaimer: I love current logo

**Comment by UlisesTJ** [comment]
The current logo does not have anything bad, if you wish I can present a proposal if you like to use it for free, you think? @langpavel  @sokra

**Comment by sokra** [comment]
Thanks for offering your help, but I don't feel the need for a new logo. I like the current logo, and changing it (again) would risk confusing users. So thanks for the offer, but I don't want you to waste your time creating a logo, when we probably won't switch logo regardless how good your proposal is.

**Comment by UlisesTJ** [comment]
ok no problem, thanks for your time @sokra

**Comment by TheLarkInn** [comment]
I'm sure there could be opportunity to help contribute to any of our documentation graphics though if this interests you.
