### ISSUE TITLE
Refused to execute script from 'http://localhost:8080/dist/main.js

### ISSUE THREAD

**Issue by Cariaga** [webpack/webpack#7069]
- i'm currently using node
- when i use the npm run build it builds the dist/main.js along with the ./script/tryingwebpack.js
- the ./script/tryingwebpack.js only contains console.log('');
- i have no webpack.config.js do i need to use that?
in my package.json i have 

`  "scripts": {
    "build" :"webpack --mode production --display-error-details --progress --colors  ./scripts/tryingwebpack.js",
    "dev" :"webpack --mode development --display-error-details --progress --colors  ./scripts/tryingwebpack.js",
    "start": "node server.js",
    "test": "IP=0.0.0.0 PORT=3030 mocha --timeout 5000 tests/*_test.js",
  },`

` "devDependencies": {
    "webpack": "^4.0.1"
  }`
`  "dependencies": {
    "bufferutil": "^3.0.3",
    "chai": "^3.5.0",
    "chai-http": "^2.0.1",
    "ejs": "^2.4.1",
    "express": "^4.13.4",
    "mongodb": "^2.1.16",
    "mongoose": "^5.0.11",
    "morgan": "^1.7.0",
    "npm": "^5.7.1",
    "object-assign": "4.1.0",
    "utf-8-validate": "^4.0.0",
    "ws": "^5.1.0",
    "webpack": "^4.0.1"
  },`

but the issue is when i import it on the html file using
`<script src="dist/main.js"></script>` nothing shows up

**Comment by Cariaga** [comment]
SLOVED IT by adding
`app.use("/dist", express.static(__dirname + "/dist"));`
but not sure if its the right thing to do

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by Greg919617** [comment]
@Cariaga did you paste app.use("/dist", express.static(__dirname + "/dist")); into your app.js file?
