### ISSUE TITLE
dynamic import use hash to replace the map's key?

### ISSUE THREAD

**Issue by toobull** [webpack/webpack#7070]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
I use import() just like the example:
https://github.com/webpack/webpack/tree/master/examples/code-splitting-native-import-context

And, I want to know it's any way to do that, replace the var map's key as a hash, but not the import path? I dont want to expose the import path.(I google a lot of dynamic import's info, but none solution), it's there anyway to solve it?

`
var map = {
	"./bar": [
		2,
		2
	],
	"./bar.js": [
		2,
		2
	],
	"./baz": [
		1,
		1
	],
	"./baz.js": [
		1,
		1
	],
	"./foo": [
		0,
		0
	],
	"./foo.js": [
		0,
		0
	]
};
`

**If the current behavior is a bug, please provide the steps to reproduce.**
not bug

**What is the expected behavior?**
replace the var map's key as a hash

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
npm: 5.6.0
node: v9.2.0
webpack: 4.6.0
OS: Mac
browser: Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by sokra** [comment]
The key is needed to map the result of `` `./templates/${templateName}` `` to a chunk and module id. To replace it with a hash we would actually need to hash the argument value at runtime. That's pretty expensive.
When used the real path is passed anyway.

It actually only makes sense when not using the keys like in this snippet:

``` js
var ctx = require.context("./templates");
ctx.keys().forEach(key => {
  var value = ctx(key);
  // do something with value but not with key
});
```

It's possible to write a plugin to do that if you really need it.

**Comment by toobull** [comment]
@sokra 
thx for your reply, I should think about your suggestion.

**Comment by TheLarkInn** [comment]
I'm not sure that we would support this capability out of the box (vs a custom plugin written) @toobull I'm going to close but if you have objections you can reopen given the info provided.
