### ISSUE TITLE
HotModuleReplacementPlugin confuses react component type

### ISSUE THREAD

**Issue by zlk89** [webpack/webpack#7071]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
If I use `new webpack.HotModuleReplacementPlugin()` in plugin, react node's type has dynamic function location, which I believe is a dynamic generated, see screenshot:
<img width="340" alt="screenshot 2018-04-17 23 15 25" src="https://user-images.githubusercontent.com/7234480/38914704-64693aea-4295-11e8-81b0-ea55f70aee53.png">

`[[FunctionLocation]]: VMxxx` is a dynamically generated file in chrome.

While if I remove `HotModuleReplacementPlugin`, then it would become correct one:
<img width="322" alt="screenshot 2018-04-17 23 14 58" src="https://user-images.githubusercontent.com/7234480/38914749-99a461ee-4295-11e8-9d72-61e6310d029a.png">

This bug affects all codes like `node.type === Component`. This assertion will always be false.
And this is very common in many codebases, like react bootstrap.

**If the current behavior is a bug, please provide the steps to reproduce.**

Reproduce steps:
- git clone https://github.com/zlk89/react-hot-loader-clear/tree/hmr-function-location-bug, checkout branch `hmr-function-location-bug`
- `npm install`
- `npm run start` and open `localhost:3000` in browser
  - You should see `Correct!`
- Then enable this [line](https://github.com/zlk89/react-hot-loader-clear/blob/hmr-function-location-bug/webpack.config.babel.js#L27), and then rerun `npm run start`
    - Refresh page, you should see `Wrong!` in browser

Note that I even didn't enable HMR in client side [here](https://github.com/zlk89/react-hot-loader-clear/blob/hmr-function-location-bug/server.js#L27)

**What is the expected behavior?**
`node.type === Component` should be true, if this node is an instance of `Component`. This was working in webpack 3, and no longer works since webpack 4.0 

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

npm: 5.8.0
node: v6.9.5
webpack: 4.5.0
OS: Mac
browser: Chrome Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by sokra** [comment]
This is caused by the `react-hot-loader`. It modifies `React.createElement` to return proxy components.

Not caused by webpack.
