### ISSUE TITLE
Is documentation not updated with new releases?

### ISSUE THREAD

**Issue by edarioq** [webpack/webpack#7076]
I've just started to implement webpack on our project and a bit frustrated following this guide for SASS but apparently it's not working because of compatability issues with plugins, could the maintainers please keep the docs updated?
https://webpack.js.org/loaders/sass-loader/

**Comment by glen-84** [comment]
The docs are not up to date, and I agree that it's very frustrating, esp. for those who are new to webpack (myself included).

In webpack 4, you should use the [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin) instead of the `extract-text-webpack-plugin`.

**Comment by buoyantair** [comment]
Incompatible documentation sucks
I agree, but I guess most of the contribution in FOSS projects is voluntary? So I guess you have to give it a little bit of time for someone like you or me to point it out and send a PR ^-^
I mean yeah webpack 4 is released like just a month ago, but it's a bit late in relation to how fast js goes but still :3 
:v: No complaining here :v:

**Comment by montogeek** [comment]
@webpack-bot move to webpack/webpack.js.org
