### ISSUE TITLE
Load split code from a different origin

### ISSUE THREAD

**Issue by cnshenj** [webpack/webpack#7077]
**Do you want to request a *feature* or report a *bug*?**
Feature (or question if it is already supported)

**What is the current behavior?**
Using dynamic import, I can split my scripts to into 2 files: init.js and main.hash.js. When hosted on `my.host.com`, `http://my.host.com/init.js` will load `http://my.host.com/main.hash.js`. This works perfectly. However, `my.host.com` is like a CDN, it allows other sites to load scripts from it.

Let's say I have a page `http://my.app.com/index.html` which loads `http://my.host.com/init.js`. `http://my.host.com/init.js` then will load `http://my.app.com/main.hash.js`, which doesn't exist!

Note that code splitting is needed since `init.js` is really small and never cached. While `main.hash.js` is big and should be cached when not changed (the `hash` will change).

**What is the expected behavior?**
`init.js` can use something like `currentScript` to determine its location and load other scripts from that location. A polyfill may be needed since `currentScript` is not supported by IE11

**If this is a feature request, what is motivation or use case for changing the behavior?**
Bundled scripts with code splitting used via CDN.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
webpack 4.5.0

**Comment by sokra** [comment]
There is a `output.publicPath` option and also a runtime variant `__webpack_public_path__`.

**Comment by cnshenj** [comment]
Can you be more specific? In my example, what value should publicPath have?

Reading the documentation, it seems publicPath changes the path, but not the host. Or you mean including the host in publicPath, like this: `publicPath: "http://my.host.com/"`?

**Comment by cnshenj** [comment]
I tried to include host in publicPath: `http://my.host.com/`, and it worked. However, this is not as good as dynamically getting path based on entry bundle URL. For example, if I have to deploy to multiple CDNs, (e.g. cdnjs and jsDelivr), I have to build separate bundles for each of them. And every time I need to publish a new version, I have to modify the publicPath too.

If possible, a boolean `output.relativePublicPath` would be best. When enabled, webpack entry bundle will find its own script tag (probably via `currentScript`), parse the path, then use it as base of publicPath.

For example:
HTML location: http://my.app.com/index.html
HTML script tag: <script src="http://cdn.com/foo/bar/1.1/init.js" />
publicPath: "/"
relativePublicPath: true

When init.js requests main.hash.js, it will calculate path by
1. Get current script path: http://cdn.com/foo/bar/1.1/init.js
2. Strip the file name: http://cdn.com/foo/bar/1.1
3. Add publicPath: http://cdn.com/foo/bar/1.1/
4. Add bundle file name: http://cdn.com/foo/bar/1.1/main.hash.js

**Comment by glen-84** [comment]
Would this work?


### public-path.js

```js
const url = new URL(document.currentScript.src);

__webpack_public_path__ = (url.origin + __webpack_public_path__);
```

### init.js

```js
import "public-path";

import("main.hash.js");

// other code.
```

**Comment by cnshenj** [comment]
@glen-84 This looks like a very good workaround - only if `__webpack_public_path__` existed.

I added this line in my entry file: `console.log(__webpack_public_path__)`. It prints `undefined`. I also looked at the generated entry JS, it doesn't define a global `__webpack_public_path__`. Instead, I see this:
```
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "/";
```
So the public path is actually saved in property `p` of `__webpack_require__` - which my code can't access. And that's only search result of `__webpack_public_path__` in entry JS.

**Comment by cnshenj** [comment]
Sorry I misunderstood __webpack_public_path__. When @sokra said it is "runtime" variable I thought it would be visible during execution. It is actually mapped to __webpack_require__.p and never really appears in generated code.

I tried @glen-84 solution (except I didn't create a separate file, instead I just added one line to bootstrap script), and it worked. Thanks you so much!

**Comment by rrubiorr81** [comment]
I've tried all this suggestion but none of them are working for me. I have a similar problem, where i need to load mu chunks from a different origin. Currently using CRA -create-react-app-, i have in my entry file:


`index.js`

`
import './src/containers/async/build';
import React from 'react'
import {render} from 'react-dom'
import {Provider} from 'react-redux'
import store from './store'
import App from './containers/app'

import './index.css'

const target = document.querySelector('#root');

render(
    <Provider store={store}>
        <React.Fragment>
            <App/>
        </React.Fragment>
    </Provider>,
    target
);`

in `src/containers/async/build.js`

`__webpack_public_path__ = 'http://my-server-assets.com';`

Am i missing something? Thank you in advance..!

**Comment by feaswcy** [comment]
this is useless, if you provide as npm packages, others will not be able to pack all needed chunks in their  project's output...

**Comment by yazonnile** [comment]
https://www.npmjs.com/package/dynamic-pub-path-plugin

**Comment by MrToxy** [comment]
@yazonnile could you provide an example on how to use it maybe?

**Comment by yazonnile** [comment]
@MrToxy 
https://github.com/hslayers/hslayers-ng/pull/665

**Comment by MrToxy** [comment]
> @MrToxy
> [hslayers/hslayers-ng#665](https://github.com/hslayers/hslayers-ng/pull/665)

I've seen that, but there's no example whatsoever how to set that option on webpack config. or what options it takes in

**Comment by yazonnile** [comment]
Just one option.
`expression`
This expression puts as dynamic path
https://github.com/inferpse/dynamic-pub-path-plugin/blob/master/index.js

**Comment by MrToxy** [comment]
> Just one option.
> `expression`
> This expression puts as dynamic path
> https://github.com/inferpse/dynamic-pub-path-plugin/blob/master/index.js

And what does that `expression` look like?

**Comment by yazonnile** [comment]
Sorry, I cant spoon-feeding you ˆ)
Check this PR once more. 
https://github.com/hslayers/hslayers-ng/pull/665
Its about adding dynamic-pub-path-plugin into existing project. And you can find how expression looks like in file `scripts/webpack.common.js` - just check the changes

**Comment by MrToxy** [comment]
> Sorry, I cant spoon-feeding you ˆ)
> Check this PR once more.
> [hslayers/hslayers-ng#665](https://github.com/hslayers/hslayers-ng/pull/665)
> Its about adding dynamic-pub-path-plugin into existing project. And you can find how expression looks like in file `scripts/webpack.common.js` - just check the changes

"Spoon-feeding you", really?

The package you keep mentioning has 0 documentation, 0 examples, there's no reference to it anywhere other than another package by the same author.

```
'expression': `(window.HSL_PATH || './node_modules/hslayers-ng/dist/')`,
```
how is someone supposed to understand where `HSL_PATH` comes from or why is another module referenced?

**Comment by yazonnile** [comment]
`HSL_PATH` is something specific from `hslayers` package. Not from the `dynamic-path...`

You need to set something yours into `expression` option. I dont know how to explain more detailed, coz its just a string option and `hslayers` PR did exactly what you asking for - example of implementing `dynamic-path..` into existing project.

**Comment by MrToxy** [comment]
> `HSL_PATH` is something specific from `hslayers` package. Not from the `dynamic-path...`
> 
> You need to set something yours into `expression` option. I dont know how to explain more detailed, coz its just a string option and `hslayers` PR did exactly what you asking for - example of implementing `dynamic-path..` into existing project.

can you share your configuration? I'm having a hard time understanding what `expression` means here

**Comment by raitisbe** [comment]
I'm not even sure it's the best approach, but the one-time need was there and dynamic-pub-path-plugin came to the rescue.
HSL_PATH is really project speciffic as @yazonnile mentioned, so lets just name it SOME_VARIABLE. 
<script>window.SOME_VARIABLE='path-where-the-chunks-are/'</script>
<script src="path-where-the-chunks-are/hslayers-ng.main.js"></script>

When you load the bundle this way, chunks will be loaded from path-where-the-chunks-are, not from directory where index.html resides. Can be even different domain if im not mistaken.

the webpack config which was used to build hslayers-ng.main.js file includes
plugins: [
new DynamicPubPathPlugin({
      'expression': `(window.SOME_VARIABLE || './node_modules/hslayers-ng/dist/')`,
    }), ...

SOME_VARIABLE can be set globally, but in case it is not, then hardcoded path to dist directory is used.

**Comment by iamphonghg** [comment]
Thanks so much for your workaround! @glen-84 
Recently I had to find a way to optimize loading speed with a CDN for my Laravel React project.
On the `app.blade.php`, I did:
`<script src="{{ config('cdn_base_script_tag') . mix('js/app.js') }}"></script>`
Then I realized that the lazy load chunk files were loaded from the main domain, not from CDN. It tooks me several days to find a workaround and then I see you.
Simply add this code to the `index.js` file and everything works perfectly:
`__webpack_public_path__ = `${config.cdnUrl}/`;`

**Comment by s16tom** [comment]
I came across the same issue and adding the following to my webpack config resolved it for me:

```
output: {
  publicPath: "auto",
}
```

From: https://webpack.js.org/guides/public-path/#automatic-publicpath

**Comment by michhyun1** [comment]
Is there any way to do this if using create react app defaults?
