### ISSUE TITLE
Webpack Configuration for React App with hot module realoding

### ISSUE THREAD

**Issue by prakashchandrabarnwal** [webpack/webpack#7078]
**Do you want to request a *feature* or report a *bug*?**

[https://stackoverflow.com/questions/49913368/webpack-configuration-for-react-app-with-hot-module-realoding](https://stackoverflow.com/questions/49913368/webpack-configuration-for-react-app-with-hot-module-realoding)

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

**Comment by PlayMa256** [comment]
Which version of webpack are you using?

Supposing it is version 4, the error: `Webpack has been initialised using a configuration o bject that does not match the API schema.`, can be fixed following the supported schema [here](https://webpack.js.org/configuration/#options).

**Comment by evilebottnawi** [comment]
@prakashchandrabarnwal you have answer on your question in stackoverflow. Thanks!
