### ISSUE TITLE
webpackPrefetch not prefetching dynamic imports from entry chunk

### ISSUE THREAD

**Issue by MLoughry** [webpack/webpack#7084]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Dynamic imports tagged with `/* webpackPrefetch: true */` in the entry chunk are not being prefetched. Per the [FAQ](https://medium.com/webpack/link-rel-prefetch-preload-in-webpack-51a52358f84c), it seems this was intentional; however, I'm not sure why webpack can't handle this on its own, rather than offloading that to the consumer.

**If the current behavior is a bug, please provide the steps to reproduce.**

Minimal repo: https://github.com/MLoughry/webpack-7084-repro

Here, the `index` dynamically imports `a`, which dynamically imports `b`. However, the resulting `chunkPrefetchMap` is merely:

```js
/******/ 		var chunkPrefetchMap = {
/******/ 			"a": [
/******/ 				"b"
/******/ 			]
/******/ 		}
```

And nothing is in place to prefetch `a`

**What is the expected behavior?**
Dynamic imports tagged with `/* webpackPrefetch: true */` in the entry chunk are prefetched

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
webpack@4.6.0

**Comment by tdd** [comment]
Can confirm, FWIW

**Comment by tdd** [comment]
From what I see, switching to `webpackPreload: true` (for now; said code will end up in a non-entry chunk) doesn't help, either. No relevant `link` element is injected in the DOM.

**Comment by MLoughry** [comment]
It may make sense for webpack to offload this work in the case where the HTML page is generated at the same time. 

However, in our case, we just upload the output to a version directory on a CDN, and a server page just takes in a version parameter and serves the scripts from there. We *could* modify the build to upload the manifest of entry-child chunks, and have the server page make an additional request to the CDN for said manifest and add the prefetch links; but it seems simpler to simply have webpack handle that.

**Comment by satazor** [comment]
From what I understood, webpack doesn't prefetch/preload chunks that are direct children of entrypoints. It seems that it assumes that developers are using `html-webpack-plugin` or similar.

Anyway, I think it would be useful to have some option to change the behavior to prefetch the direct children as well.
