### ISSUE TITLE
Incremental load time is slow ~9s

### ISSUE THREAD

**Issue by jfrolich** [webpack/webpack#7086]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Incremental load is pretty slow, the initial load doesn't take very long (20s or so), and it's not a huge app, but the incremental load takes ~9 seconds.

**If the current behavior is a bug, please provide the steps to reproduce.**
[CPU profile](https://cogo.cogo.ai/download/attachments/2321/webpack-incremental-load.cpuprofile?sltoken=SFMyNTY.g3QAAAACZAAEZGF0YWEVZAAGc2lnbmVkbgYACAor4WIB.WUM-iBqG43_FkZ5wAqzCcJlImGKPsgM6b56o4u9_rqE)

[webpack.config.js](https://gist.github.com/jfrolich/26cb10fb5efe7f03a6133102ca460446)

**What is the expected behavior?**
It was faster in previous versions of webpack, but also the config changed

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Webpack 4.6
MacOS 10.13.3
NodeJS 9.11.1

**Comment by jfrolich** [comment]
A lot of the work seem to happen in `optimizeChunksAdvanced`:
![image](https://user-images.githubusercontent.com/579279/39030945-e614a7b0-4497-11e8-8f2d-fcbc257e3533.png)

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by jfrolich** [comment]
I wish I could do that. This is not an issue, as far as I know that is reproducible in in a small environment as everything works as expected except that it loads slower than expected.

As far as the code itself. It is not an open source project. So I cannot share the code publicly. I am happy to share anything else though. As I shared the config and the CPU profile of the incremental load.

**Comment by evilebottnawi** [comment]
@jfrolich can you disable/enable loaders/plugins and check perf again to ensure problem inside webpack?

**Comment by montogeek** [comment]
Also could use https://webpack.js.org/plugins/profiling-plugin/

**Comment by jfrolich** [comment]
> @jfrolich can you disable/enable loaders/plugins and check perf again to ensure problem inside webpack?

Thanks, I did some extra testing, turning on and off loaders. It looks like `thread-loader` was the main culprit. When removing that the incremental load became significantly faster!

**Comment by sokra** [comment]
From the CPU profile image it looks like the SplitChunksPlugin causes this?

**Comment by jfrolich** [comment]
@sokra It's still not sub-second as I would really like :D, but removing the thread-loader has shaved off a lot of time in incremental load so it's ok. I have no special configuration for SplitChunksPlugin, but indeed it looks like a lot of time is spent there.

But yes you can close the issue as it's good enough for me at the moment. Happy to supply more data for performance testing.

**Comment by sokra** [comment]
I took a look at the CPU profile. Seems really like the SplitChunksPlugin take most of the time. This probably can be improved.

**Comment by jfrolich** [comment]
Thanks! I didn't find a big difference in setting the poolTimeout:

`poolTimeout: 500ms (default)`: ~4s
`poolTimeout: Infinity`: ~4s
no `thread-loader`: ~2.5s

**Comment by sokra** [comment]
I'm trying to improve the split chunks performance too. Could you give me some info about your app? Number of modules? Number of chunks?

**Comment by jfrolich** [comment]
Can you email me at `jaap at cogo.ai`, then I can share the whole source code. I have lazy loading on a route level with ~ 16 dynamic module imports. Then I have a code snippet component that dynamically loads syntax highlighting for ~114 languages using dynamic import. The total number of modules is 296 javascript files.

**Comment by sejoker** [comment]
@jfrolich you try 2 things:
- disable `splitChunks` in dev mode:
```
optimization: isDev ? {
  splitChunk: false
} : {} 
```
- swap thread-loader with [happypack](https://github.com/amireh/happypack), latest beta version supports webpack v4, use 4 threads (3 is a default), from our comparison it produces better results.

**Comment by jfrolich** [comment]
@sejoker: Thank you! I am interested in the pro/cons of enabling disabling splitChunks in development? (Maybe also of interest of other people reading this issue).
Maybe it should be off by default in development?

**Comment by sokra** [comment]
Ok here is some early results: when using `removeAvailableModules: false`, `splitChunks` becomes very slow in some cases.
