### ISSUE TITLE
Using code splitting if custom load mode (etc commonjs)

### ISSUE THREAD

**Issue by k8w** [webpack/webpack#7089]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Code splitting only works on webpack custom loading methods.(__webpackJsonp__ ...)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Code be splitted, and can be loaded in custom way.
For example : commonjs/requirejs, and so on...
So that it can support more platform.(for example NodeJS...)

**If this is a feature request, what is motivation or use case for changing the behavior?**
Code splitting is very useful, and should be used in various way, not only `the webpackJsonp`.
**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

**Comment by sokra** [comment]
The method used for code splitting depends on the `target` option. I.e. `target: "node"` uses commonjs require to load chunks.
