### ISSUE TITLE
semver for webpack versions (breaking changes versioned as "major")?

### ISSUE THREAD

**Issue by protron** [webpack/webpack#709]
Last 2 versions of webpack (v1.5 & v1.4) have "API: Breaking change" documented in the [changelog](http://webpack.github.io/docs/changelog.html#1-5).

Shouldn't they have been versioned (according to [semver.org](http://semver.org/)) as 2.0 (instead of 1.4) and 3.0 (instead of 1.5)?

For instance, people having a npm dependency on `"webpack": "^1.0.0"` will now receive "1.5.1" expecting no breaking changes since "1.0.0" (which is false). But if the rules at semver were respected, I think they probably should have received "1.3" (which I suppose is last one without breaking changes). Isn't that right?

I'm not asking you to rename the existing versions. I know cannot just do that. I suppose you could, for instance, revert those 2 breaking changes in a new patch version (maybe "1.5.2") in order to fix backwards compatibility in that broken branch, and then release those breaking changes in a new major version ("2.0.0"). But even if those breaking changes are insignificants, and you think fixing it would only bring more trouble for everyone. I raised the question because I still think is appropriate to have a least some understanding on why are you changing the API in minor releases.

**Comment by sokra** [comment]
You are right.

---

* API: *Breaking change*: changed casing for `node.Buffer` option

Changed this to be backward-combatible.

---

* API: *Breaking change*: added options parameter to `module.hot.accept/check

Adding an optional parameter should not be flagged as breaking change. Removed the flag. This wasn't a breaking change

**Comment by protron** [comment]
Cool. Thank you!

**Comment by jhnns** [comment]
Sorry @sokra :grin:

But we should probably also add a deprecation warning.
