### ISSUE TITLE
output.chunkFilename cannot be a function

### ISSUE THREAD

**Issue by CLL80** [webpack/webpack#7090]
#### Bug report

**What is the current behavior?**
When using a function for `output.chunkFilename`, this error is returned:
```js
configuration.output.chunkFilename should be a string.
```

**What is the expected behavior?**

As per the docs, configuration.output.chunkFilename [can be a function](https://webpack.js.org/configuration/output/#output-chunkfilename).

I would expect this to work in the same way as an `output.filename` function:
```js
config.output.filename = info => '[name].bundle.js'
```

#### Version

| library         | version
| ---------------- | -------
| Webpack | 4.6.0

**Comment by sokra** [comment]
Please fix the docs. For technical reasons it must be a string.

**Comment by ooflorent** [comment]
@webpack-bot move to webpack/webpack.js.org
