### ISSUE TITLE
Axios (when using production config in Webpack 4) return entire HTML code instead of data

### ISSUE THREAD

**Issue by janswist** [webpack/webpack#7095]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
It returns html page in data when using production config.
![zrzut ekranu 2018-04-23 o 09 08 22](https://user-images.githubusercontent.com/5583954/39111624-14104620-46d6-11e8-8cfb-0bf6730934dc.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
It works perfectly when using `webpack-dev-server` (refer to image below) and when I build a production code and run it results in returning html page in `data`.

Here is my configuration file for `webpack.prod.conf.js`: [link](https://gist.github.com/janswist/c3260875383e94b92c7a4fc17451a454)

**If this is a feature request, what is motivation or use case for changing the behavior?**
No 

**What is the expected behavior?**
The same as when using `webpack-dev-server`
![zrzut ekranu 2018-04-23 o 09 08 07](https://user-images.githubusercontent.com/5583954/39111592-f7ddbc94-46d5-11e8-8393-238a572ef14d.png)

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Google Chrome v. 65.0.3325.181 (64 bit)
Node.js v.9.3.0
webpack v.4.6.0
macOS High Sierra 10.13.3

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by janswist** [comment]
Don't how to make a reproducible example since it's a private project with private API that I can't share. However, I have read about 0CJS and used simply `webpack` and it did everything right and now it's working (except I have to still copy manually `index.html` to `/dist`, but that's easily solvable).

May I ask how in the world without any config file (and especially Vue and sass loaders) it just works?

**Comment by montogeek** [comment]
This issue is probably not related with webpack, that response comes from, as you said, a private API, there is lot of possibilities:
1. What are you using, fetch or XMLHttpRequest or a library to make those requests?
2. What are the response headers on development and production? Maybe they differ in your production API.
3. `webpack-dev-server` purpose is to serve files with hot reloading, as far as I know it doesn't modify/intercept requests.

Check each one of above possibilities.

**Comment by janswist** [comment]
1. I'm using library called Axios (since it's recommended one for Vue.js)
2. They differed.
3. So `webpack` does modify requests? That would be really strange.

However, using no config resolved this so maybe the problem lied in config that was made for Webpack 3.
