### ISSUE TITLE
Code from entry doesn't fall into output file

### ISSUE THREAD

**Issue by SilencerWeb** [webpack/webpack#7096]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Webpack doesn't take entry file into the output file

**If the current behavior is a bug, please provide the steps to reproduce.**
[Repo](https://github.com/SilencerWeb/fruit-machine/tree/webpack-bug)
[Config](https://github.com/SilencerWeb/fruit-machine/blob/webpack-bug/webpack.config.js)

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
node.js - v9.9.0
webpack - v4.6.0
OS - MacOS 10.12.6

P.S. everything works great with webpack version 3.11.0

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by SilencerWeb** [comment]
@montogeek I'm sorry about that, already fixed

**Comment by SilencerWeb** [comment]
Already fixed. Thanks to @brycehill with his demonstrating issue #7094 demo.

[Fixed config](https://gist.github.com/SilencerWeb/56c74dd020ecea88669cce04ca9a0944)
