### ISSUE TITLE
Webpack isn't "watching" on Windows (Working on Mac) resolving modules

### ISSUE THREAD

**Issue by gabrielenosso** [webpack/webpack#710]
I have a project in which I require other files as modules (as indicated here as "resolving a module path": http://webpack.github.io/docs/resolving.html).

I have a directory structure like that:
app.js
scripts/components/Nav.js

So I have that in my app.js file:
<code>
var Nav = require('components/Nav');
</code>

In the webpack.config.js file I specify how to resolve modules using the resolve.root property:
<code>
resolve: {root: [__dirname + '/scripts']}
</code>

Now the problem is that Webpack doesn't "watch" the required files in Windows.
It means that Webpack isn't rebuilding the bundle automatically if I change the scripts/components/Nav.js file.
But it recompiles it if I require using a relative path:
<code>
var Nav = require('./components/Nav');
</code>

This problem is present only in Windows: it works like a charm on Mac (didn't try on Unix though).

**Comment by gabrielenosso** [comment]
The solution was to use path.sep in the webpack.config.js file to let paths be compatible both in Windows and Mac (and Unix):
<code>
resolve: {root: [__dirname + path.sep + 'scripts']}
</code>

**Comment by jhnns** [comment]
You can also use node's `path.join()`:

```javascript
path.join(__dirname, "scripts")
```

**Comment by xieaolin** [comment]
Thx a lot ! And I found it is only need to change `resolve.root` , no need to change `/` to `path.sep` in   `resolve.alias` .

**Comment by hsrobmln** [comment]
Using path.sep fixed it for me. Thanks @gabrielenosso

**Comment by SamAI-Software** [comment]
@gabrielenosso I'm really frustrated about this issue. Nothing works in my case.
Can you visit [this stackoverflow link](http://stackoverflow.com/questions/38397231/webpack-watch-does-not-work-on-windows-nor-webpack-dev-server) and check 3 questions on the bottom?
Thanks!

**Comment by shoko436** [comment]
`path.join(__dirname, 'src')` works for me.

**Comment by ddnatu** [comment]
where to write this path.join() statement , inside config object ?

**Comment by shoko436** [comment]
@ddnatu Yes, inside config object.
