### ISSUE TITLE
Build hangs on windows, progress not working, no errors or output

### ISSUE THREAD

**Issue by SergeyShablenko** [webpack/webpack#7100]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Build hangs without output or logs or errors

**If the current behavior is a bug, please provide the steps to reproduce.**

Just run npm start 

**What is the expected behavior?**

Successful build

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Operating system Windows 2012 R2 Standart

Node: 6.0.0

Webpack: 3.11.0

All paths are resolved with `Path.resolve`, config perfectly works on ubuntu
I noticed, that webpack is trying to build project, but at some point of time it start creating subprocesses, and after creating 3-4 subproceses they stop using cpu and hang

Also I`ve tried reducing version of sass-loader, removing uglify-paralel, runing build in debug mode, nothing helped

**Comment by evilebottnawi** [comment]
@SergeyShablenko can you create minimum reproducible test repo?

**Comment by SergeyShablenko** [comment]
I can share configurations

**Comment by SergeyShablenko** [comment]
I`ll try to reproduce with a test project, and share link to repo
