### ISSUE TITLE
Chrome 66 + Webpack + Node: Breakpoints don't stop the control flow

### ISSUE THREAD

**Issue by mitchhentges** [webpack/webpack#7101]
**Do you want to request a *feature* or report a *bug*?**

I'm reporting a *bug*.

**What is the current behavior?**

When inspecting a webpack-built bundle (running with Node) in Chrome, breakpoints are not triggered.
![demonstration](https://user-images.githubusercontent.com/7784737/39153975-a0749a3c-4701-11e8-88d3-2ace9533e5c5.gif)

**If the current behavior is a bug, please provide the steps to reproduce.**

I've created a [reproduce repository on GitLab](https://gitlab.com/mitchhentges/chrome-66-webpack-breakpoints-not-stopping-flow).

Clone that repository, then:

1. `npm i`
2. `./node_modules/.bin/webpack --mode development app.js -o out.js`
3. `node --inspect-brk out.js`
4. Open Chrome and go to `chrome://inspect`
5. Click "Open dedicated DevTools for Node"
6. Ensure you're on the "Sources" tab
7. Click the blue "resume script execution" button - the control flow will continue, then pause at the `debugger` line in `app.js`, which is good.
8. In the middle pane, put a breakpoint on the line with the `console.log` (click the grey "3")
9. Click the blue "resume script execution" button again - the control flow *should* stop at your breakpoint on the `console.log`. Instead, it continues, prints the log, *doesn't stop*, and finishes execution.

**What is the expected behavior?**

Breakpoints should stop the control flow.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Note that this functionality was working :100:-ly on Chrome 65, the recent Chrome 66 changes have broken this. I'm reporting this under the `webpack` issue tracker because non-webpack-ify'd files still work properly in the Chrome Node debugger.

* Chrome: `66.0.3359.117`
* Node: `v8.10.0`
* NPM: `5.6.0`
* OS: Arch Linux / macOS `10.13.4`
* Webpack `4.6.0`

**Comment by mitchhentges** [comment]
Note that setting the `devtool` to `source-map` is a functional workaround, at a cost to build time.

So, if you're using the cli: `webpack --devtool source-map ...`
Or via the `webpack.config.js` file:
```
{
    // ...
    devtool: 'source-map'
}
```

**Comment by sokra** [comment]
Looks like a browser bug... Could you try other browsers?

**Comment by mitchhentges** [comment]
Debugging node primarily only works with the Chrome (V8) debugger, so I
can't use a different browser as a debugger client.

And, for running the code, I'm using node, not a browser, to be clear haha.

**Comment by mitchhentges** [comment]
I'm less familiar with node debugging though: can you recommend a non-Chrome debugging client?

**Comment by manish2535** [comment]
Any updates on this?

**Comment by evilebottnawi** [comment]
@manish2535 need investigate, but looks chrome bug

**Comment by Curiousite** [comment]
Probably related: Chrome also got rid of the Node-Inspect Button in version 66.
https://stackoverflow.com/questions/50152331/i-lost-the-node-js-debug-button-in-chrome

Another workaround would be to use Chrome 65 until the problem is fixed. You can get it here: https://www.slimjet.com/chrome/google-chrome-old-version.php

**Comment by june07** [comment]
@mitchhentges You can actually use any Chromium based browser.  The breakpoints issue has cropped up again

https://bugs.chromium.org/p/chromium/issues/detail?id=851853

Using Chrome and NiM https://june07.com/nim works now with version 1.0.0 as shown in the link above.

**Comment by ygmarchi** [comment]
Same problem here, switching to Firefox
