### ISSUE TITLE
SourceMapDevToolPlugin not generating a sourcemap

### ISSUE THREAD

**Issue by zecuria** [webpack/webpack#7103]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
option of  `devtool: "source-map"` generates a correct source mapping

however adding SourceMapDevtoolPlugin to plugins array does not produce any source map (tested with the following options):
```
new webpack.SourceMapDevToolPlugin({
    filename: '[file].map',
    moduleFilenameTemplate: undefined,
    fallbackModuleFilenameTemplate: undefined,
    append: null,
    module: true,
    columns: true,
    lineToLine: false,
    noSources: false,
    namespace: '' 
})
```
I am not using any other plugins in my config files.

**If the current behavior is a bug, please provide the steps to reproduce.**

The full configs being used are available in the following gists:

[Valid Source Map Config](https://gist.github.com/zecuria/23db4aea486460a04f3a505b309c8220)

[No Source Map Config](https://gist.github.com/zecuria/d0cf1c2787631d2d455a7fbc9cf504f1)

**What is the expected behavior?**
They should produce the same mappings

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Node.js Version: v8.1.2
Webpack Version: 4.6.0
Webpack Cli: 2.0.15

**Comment by sokra** [comment]
add `devtool: false`

**Comment by zecuria** [comment]
That worked, I went through the documentation multiple times but didn't see that.

my bad and thank you

**Comment by MaximSemenov** [comment]
I had the same problem but i was lucky enough  to see this from Webpack website

> 
If you want to use a custom configuration for this plugin in development mode, make sure to disable the default one. I.e. set devtool: false.
>

**Comment by fregante** [comment]
For some reason for me it wasn't generating the source maps until I specified a `filename`. 

```js
new webpack.SourceMapDevToolPlugin({
    filename: '[file].map[query]', // Default value
    publicPath: 'etc……',
})
```
