### ISSUE TITLE
Webpack production mode cause ReferenceError

### ISSUE THREAD

**Issue by hjin-me** [webpack/webpack#7108]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

mode production, code was formatted, causing some variable be used before be declared(const).
This will causing ReferenceError in runtime.

**If the current behavior is a bug, please provide the steps to reproduce.**

I simplify code and put it here <https://github.com/hjin-me/webpack-uglify-bug>
clone it && `npm i && npm run build`

the result code formatted in /dist/main.js

<img width="884" alt="uglify____site_test_uglify__-_____dist_main_js" src="https://user-images.githubusercontent.com/876951/39168772-bad73c7e-47c7-11e8-960a-ee37ea265816.png">

**What is the expected behavior?**
should not ReferenceError.

Node: v9.11.1
Webpack: ^4.6.0
webpack-cli: ^2.0.15

**Comment by hjin-me** [comment]
update test case make sure code will ReferenceError

**Comment by AngeIII** [comment]
this helped me in codemirror I think same will be there - https://github.com/graphql/graphiql/issues/665#issuecomment-381919771
