### ISSUE TITLE
webpack2.7  node api  question?

### ISSUE THREAD

**Issue by ibeeger** [webpack/webpack#7109]
<img width="555" alt="qq20180424-150828 2x" src="https://user-images.githubusercontent.com/1124832/39171452-722b8822-47d1-11e8-8bae-ba3ce3e4315e.png">
this image
<img width="340" alt="2" src="https://user-images.githubusercontent.com/1124832/39171777-613623b4-47d2-11e8-8048-938c60ee0d1a.png">

I use webpack2.7 node api  
but  uglifyjs  compression uneffect (not effect);
and I think  tow point 
1、when I use "webpack -p -config ./xxxconfig.js  "  this "-p" how transfer（Configuration）  to my  node api 
2、the second image has bug

**Comment by evilebottnawi** [comment]
@ibeeger `webpack@2` is deprecated. Also i recommended use https://github.com/webpack-contrib/uglifyjs-webpack-plugin plugin, he is support cache and parallel by default. Thanks!

**Comment by ibeeger** [comment]
@evilebottnawi thank you 
solved
