### ISSUE TITLE
webpack3打包有bug

### ISSUE THREAD

**Issue by hduhdc** [webpack/webpack#7111]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

**Comment by hduhdc** [comment]
css样式
-webkit-transform: translate(0, 0);
  -moz-transform: translate(0, 0);
  -ms-transform: translate(0, 0);
  -o-transform: translate(0, 0);
  transform: translate(0, 0);
打包后   只有transform: translate(0, 0);没有前缀
css样式
  transform: translate(0, 0);
-webkit-transform: translate(0, 0);
  -moz-transform: translate(0, 0);
  -ms-transform: translate(0, 0);
  -o-transform: translate(0, 0);

打包后   只有transform: translate(0, 0);有前缀

这个是有css的顺序吗？？？？？？？？？？？？？？？？？？

**Comment by montogeek** [comment]
We are sorry but we don't understand your language. Please try to submit your issues in English language.
