### ISSUE TITLE
Template string optimization incorrectly result in "undefined"

### ISSUE THREAD

**Issue by Cellule** [webpack/webpack#7121]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Bad optimization in template string. Changes a valid result to `undefined`

**If the current behavior is a bug, please provide the steps to reproduce.**

Js file to repro
```js
// test.js
var msg = getMsg({value: 1});
console.log(`${ msg } <= should not be undefined`);
function getMsg({value}) {
// Doesn't seem to repro if there is no multiline here
  return `\
${value}`;
}
```
Command to run
```
npx webpack test.js -o out.js
node out.js
```

The `console.log` is reduced to `console.log("undefined <= should not be undefined")`

**What is the expected behavior?**
The resulting bundle should print `1 <= should not be undefined`

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Node v9.5.0
Webpack v4.6.0
Webpack-cli v2.0.15

**Comment by sokra** [comment]
Sounds like an uglify-es bug. It only happens in production mode, does it?

**Comment by Cellule** [comment]
Yes, I confirmed it doesn't repro in development mode

**Comment by evilebottnawi** [comment]
@webpack-bot move to `webpack-contrib/uglifyjs-webpack-plugin`

**Comment by evilebottnawi** [comment]
I will investigate this in near future (today)

**Comment by evilebottnawi** [comment]
@webpack-bot move to webpack-contrib/uglifyjs-webpack-plugin
