### ISSUE TITLE
Create and add a guideline for typings

### ISSUE THREAD

**Issue by sokra** [webpack/webpack#7122]
The CONTRIBUTION guide should have a guideline how typings for files in this repo should be writting.

Here is my initial proposal. Nothing set in stone yet. This is open for discussion.

# Guideline for adding types to webpack files

## Arrow functions

* no arrow functions. Use `@typedef {Function}`, `@param` and `@return` instead.

``` js
/**
 * @callback SortingFunction
 * @param {Chunk} a first chunk
 * @param {Chunk} b second chunk
 * @returns {-1|0|1} sort result
 */
```

*Why? You can add comments to each parameter. Array functions are not valid JSDoc.*

* [ ] TypeScript support pending https://github.com/Microsoft/TypeScript/issues/7515

## Inline objects

* no inline object definitions. Use `@typedef {Object}` and `@property`

``` js
/**
 * @typedef {Object} ObjectWithId
 * @property {number} id module id
 */
```
 
*Why? You can add comments to each property.*

## Return

* no `@return`. Use `@returns` instead.
* `@returns {never}` has a different meaning and should be used when always throwing
* `@returns {void}` can omit a description

*Why? It's recommended in the JSDoc documentation.*

## typedef

* typedef should be in a separate comment

``` js
/**
 * @typedef {Function} SomeFunction
 * @param {number} n some number
 * @returns {number} result number
 */
```

*Why? Clear separation. Readablility.*

## Class

* no `@extends`, this is inferred from the code
* each property must be assigned in the constructor
* each property assignment in the constructor must have a `@type` comment
* each private property assignment in the constructor must have `@private`
* format it in a single line: `/** @private @type {number} */`

``` js
class X {
  constructor() {
    /** @type {number} */
    this.n = undefined;
    /** Description for member m */
    /** @private @type {string} */
    this.m = "";
  }
}
```

*Why? All properties are typed. Hidden class doesn't change (Performance). Readablility.*

## Optional arguments

* no `[name]`. no `Type?`. Use `{Type=}` instead.
* 

``` js
/** 
 * @param {SortFunction=} defaultSort
 */
```

*Why? Consistency. = is only a single char compared to [name]. `?` is not valid jsdoc.*

## Imports

Type-only imports should be done this way:

``` js
/** @typedef {import("./Chunk")} Chunk */
```

``` js
/** @typedef {import("webpack-sources").ConcatSource} ConcatSource */
```

The comment should be standalone and just below the real imports.

* Single line
* Separated comments
* All imports on top of the file below the real imports

*Why? Consistency. All Imports on top.*

## Arrays

* no `Array<number>`. Use `number[]` instead.

*Why? Consistency. Recommended tslint rule.*

## Formatting

* no markdown/html. Use only text.

## Allowed JSDoc tags

Only use these tags

``` 
@typedef
@param
@callback
@returns
@type
@private
@property
@template
@abstract
@implements
```

Not allowed and reasons:

* `@memberof` unneeded because we use only real classes
* `@inheritdoc` unneeded as it's the default
* `@description` unneeded as simple text on top does the same job
* `@return` for consistency use `@returns`
* `@readonly` use a getter instead so it's obvious

## `any`

* Use `any` when really need `any`. Don't use `*`.
* Use `TODO` as type when it could be typed but not in the current state.

## Open Questions

* ~`@returns {void}` or no annotation for no return value.~
* ~`@typedef` with `@template` argument~
* ~Syntax for adding a description to a property `/** blah blah @private @type {number} */`?~
* ~`Array<number>` vs. `number[]` (Consistency with `Map` `Set` or shorter and default)~
* ~`{any}` vs `{*}`~
* When does Typescript support `@private` and `@abstract`?

**Comment by sokra** [comment]
@mohsen1 @TheLarkInn @ooflorent Would be great to hear your opinion. What's missing? What should be changed?

**Comment by ooflorent** [comment]
I like what's proposed here except:

> no `Array<number>`. Use `number[]` instead.

Coming from Flow, I must admit I prefer the `Array` syntax because it matches `Map`, `Set` and other generic classes and it is less ambiguous. Brackets should be preferred to type tuples: `[number, string]`.

---

A few things that needs to be decided:

### Descriptions

Do functions/methods/whatever always require a description?
If so, how do we write it?

1. Using `@description`

    ```js
    /**
     * @description Do something
     */
    ```

2. Using a simple phrase:

    ```js
    /**
     * Do something
     *
     * Detailed behavior if required.
     * Could use multiple lines.
     */
    ```

How to _style_ description?

1. Don't
2. Using markdown
3. Using HTML

### Empty returns

When a function returns nothing:

1. `@returns {void}`
2. `@returns {undefined}`
3. `@returns {never}`
4. no annotation

### Allowed annotations

We should list which annotations are allowed and which are not (e.g. `memberof`, `inheritdoc`, etc). I don't know which ones are supported by TypeScript but it would be a good start to have the list.

**Comment by mohsen1** [comment]
> Arrow functions

ESLint doesn't like arrow functions in JSDoc (https://github.com/webpack/webpack/pull/7046#discussion_r183595371) but TypeScript doesn't like your proposed syntax either (https://github.com/Microsoft/TypeScript/issues/23722)

I personally like arrow functions but declaring parameter description is important so I think we should go with the JSDoc syntax once TS understands it.



> Inline objects 

+1 to `Use @typedef {Object} and @property`


> typedef should be in a separate comment

What if they are generic? Can we use a `@template` with `@typedef`?

> Class
+1 to everything 

> Optional arguments
+1

> Imports
+1

> Arrays

This is purely style preference and I'm happy either way. Prettier and TSLint(default) likes `number[]` I think

**Comment by sokra** [comment]
> What if they are generic? Can we use a `@template` with `@typedef`?

That's a good question.

How is `@template` scoped?

Does this work?

``` js
/**
 * @template T
 */
class X {
  /** @typedef {T[]} TArray */

  constructor() {
    /** @type TArray */
    this.array = [];
  }
}
```

**Comment by sokra** [comment]
I updated the issue text with all the feedback. If you could take another look that would be great. 😃 

I'll copy this to `CONTRIBUTING.md` once done.

**Comment by glen-84** [comment]
FWIW, the tslint recommended configuration uses [this rule](https://palantir.github.io/tslint/rules/array-type/) with the `array-simple` option:

```
"array-simple" enforces use of T[] if T is a simple type (primitive or type reference).
```

I use this option as well.

I realize that you're not using TypeScript directly, but it may still be relevant to the decision.

**Comment by TheLarkInn** [comment]
I personally like having @description because it allows this code to become
reference documentation. Maybe I would say not _disallowed_ but not
_required_ either.

**Comment by TheLarkInn** [comment]
cc @weswigham for question https://github.com/webpack/webpack/issues/7122#issuecomment-384899656

**Comment by TheLarkInn** [comment]
Actually seeing that JSDOC interperets @description in the same way, I guess I'd have to see what the downsides would be if any to omitting it?

**Comment by sandersn** [comment]
@TheLarkInn  `@typedef` captures type parameters from its scope, so @sokra's example works fine. `@typedef` doesn't work correctly with `@template` right now though: 

```js
/**
 * @template T
 * @typedef {[T, T]} TPair
 */
```

is not equivalent to the typescript `type TPair = [T, T]` the way it should be. Tracked by Microsoft/TypeScript#23745.

Note that `@callback` isn't supported yet either; Microsoft/TypeScript#9546 is a start that was never finished. I'll take another look at it.

**Comment by sandersn** [comment]
Also, the Typescript compiler doesn't understand `@private` and `@abstract` right now either, although they are simple to add. If you use them without compiler support now, it means that the compiler will become suddenly strict about your usage after some future Typescript update.

**Comment by sokra** [comment]
> Maybe I would say not _disallowed_ but not _required_ either.

For consistency I would try to avoid this. Either choose "must" or "must not".

> it allows this code to become reference documentation

I guess for a reference documentation we eventually generate it from the comments into some kind of markdown/html file. In this case it won't matter if you add `@description` or not.

> @typedef captures type parameters from its scope, so @sokra's example works fine.

Great

> Note that @callback isn't supported yet either; Microsoft/TypeScript#9546 is a start that was never finished. I'll take another look at it.

It would be great to add support for that. Currently there is no way to declare function is a way that is jsdoc-valid and typescript understand it.

> Also, the Typescript compiler doesn't understand @private and @abstract right now either

We can live with that for now. Adding them doesn't hurt and we can get the benefit later when this is supported in typescript.

**Comment by weswigham** [comment]
> Currently there is no way to declare function is a way that is jsdoc-valid and typescript understand it.

Both the closure compiler and the TS compiler recognize syntax for inline function definitions like

```ts
/* @typedef {function(string, string): number} MyCallback */
```

Which you _could_ use until `@callback` is supported. (That's partly why `@callback` was deferred - we found few usages of it in the wild other than the usejsdoc site (compared to other patterns), and it's practical usage is mostly subsumed by typedefs and the function syntax above). You still don't get recognized per-argument comments (though nothing else gets you that right now, either), but afaik it _is_ valid jsdoc.

**Comment by TheLarkInn** [comment]
@sokra @ooflorent @mohsen1 How should we treat situations where we need to define a `/** @typedef */` in multiple files, should we opt to add this to `declarations`? 

If so, can we import classes into this definitions file.

**Comment by mohsen1** [comment]
Can we export `@typedef`s?

**Comment by TheLarkInn** [comment]
Also, I had a great comment from @Kovensky who suggested: 

> I generally prefer to do type TODO = any and then only use TODO if it's being used as a temporary thing

This is something we could define in `declarations.d.ts` and then use throughout in any places we can't or need follow up on an `any` type.

**Comment by sandersn** [comment]
@TheLarkInn @mohsen1 As of Microsoft/TypeScript#23723, typedefs are always exported. That went in yesterday so should be available in typescript@next.

Previously we recommended that people use a declarations.d.ts. typedef/callback tags still don't support some corner cases, like a function that also has properties:

```ts
interface Fobj {
  (a: number): string
  ok: boolean
}
declare var combo: Fobj;
```

But besides that, you might be OK with a declarations.js instead.

**Comment by evilebottnawi** [comment]
Bump

**Comment by evilebottnawi** [comment]
Bump

**Comment by evilebottnawi** [comment]
Bump
