### ISSUE TITLE
sourcemap don't show full path when use cheap-module-source-map

### ISSUE THREAD

**Issue by lichliu** [webpack/webpack#7125]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When i use 'source-map',the map file can show the full path, like "webpack:///./src_fe/page/index/App.vue",but when i use 'cheap-module-source-map', it only show "webpack:///App.vue", so if I have two files named App.vue, only one could match exactly.
**If the current behavior is a bug, please provide the steps to reproduce.**
set devtool 'cheap-module-source-map',then build

**What is the expected behavior?**
show the full path like "webpack:///./src_fe/page/index/App.vue"
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
webpack@4.6.0, node v8.3.0

**Comment by sokra** [comment]
> set devtool 'cheap-module-source-map',then build

I tried that, but it shows the full path
