### ISSUE TITLE
Duplicate files in developer tools when using eval source maps

### ISSUE THREAD

**Issue by lorenzodallavecchia** [webpack/webpack#7128]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

When using any `devtool` strategy that uses `eval`, such as `cheap-module-eval-source-map`, the browser developer tools show _two_ sets of files with quasi-identical names. The first set under the `webpack://` origin contains original sources. The second set under `webpack-internal://` origin contains transpiled sources.

Note that this has changed in webpack 4. In the previous version that `webpack-internal://` files used numeric identifiers, so there was no risk to open them by accident and they did not show up when using Ctrl+P in Chrome.

**If the current behavior is a bug, please provide the steps to reproduce.**

    git clone https://github.com/lorenzodallavecchia/webpack-bug-duplicatesource.git
    cd webpack-bug-duplicatesource
    npm install
    npm start

**What is the expected behavior?**

I would expect to only see original sources (under `webpack://`) or at least give the "internal" sources a numeric identifier so that they do not show up when searching with Ctrl+P.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

webpack 4
Node 6.11.0
Chrome 65
Windows 10 1709

**Comment by sokra** [comment]
This is a hack required for Chrome. Elsewise breakpoints doesn't work in Chrome.

Actually `webpack://` uses the name of the module and `webpack-internal://` the identifier. They are just equal in development mode.

**Comment by lorenzodallavecchia** [comment]
> This is a hack required for Chrome. Elsewise breakpoints doesn't work in Chrome.

Yes, I also did some research before opening the issue and found the place where the URL is appended and the motivation.

To be honest, I never noticed `webpack-internal` before version 4. Going back to version 3 I realized that this was because it used numbers, so the modules never showed up in the Chome "Open File" command.

Is there a way to go back to the old behavior of using numbers as ids? Is it something controlled by `mode: "development"`? May it cause adverse side effects?

**Comment by sokra** [comment]
`optimization.namedModules: false` should do the trick.

**Comment by lorenzodallavecchia** [comment]
Thanks @sokra it worked: I can easily select the right files now.
Do you think there is something better that webpack could do or should we close the issue?

**Comment by JonWallsten** [comment]
I'm seeing three copies. One internal and two others. One is the correct typescript file and the other is a file with the actual eval command. Is this as designed? The file with the eval-command always has a questionmark after the path.
![image](https://user-images.githubusercontent.com/5993909/48490708-4e02ae80-e826-11e8-8113-0fdf83073ff9.png)

**Comment by douglyuckling** [comment]
I'm surprised this hasn't received more attention, and I'm surprised that `optimization.namedModules` is on by default given that it causes this issue in Chrome. Am I in the minority by using eval source maps and developing in Chrome?
