### ISSUE TITLE
Webpack bundle causing PhantomJS crashes

### ISSUE THREAD

**Issue by christophercliff** [webpack/webpack#713]
This may be an illegitimate issue and I don't know all the details yet but I wanted to raise it just in case. 

Started experiencing nondeterministic PhantomJS crashes after updating test runner to use a Webpack bundle. These are not JavaScript errors but the PhantomJS process crashes without explanation. It appears to be a function of output settings rather than file size or a memory leak or something. E.g. `devtool: 'eval'` doesn't crash but `devtool: null` does. I can't share the source code, unfortunately.

I'm investigating on the PhantomJS side as well, will update if I learn anything.

**Comment by sokra** [comment]
We just emit Javascript...

**Comment by christophercliff** [comment]
Yeah, probably not a bug on your end. Hoping somebody in the Webpack community has insight into the problem. Feel free to close.

**Comment by JalfResi** [comment]
Updated #14335 with sample script that demonstrates that loading a WebPack resource can crash PhantomJS: https://github.com/ariya/phantomjs/issues/14335
