### ISSUE TITLE
Feature request: support "lazy" webpackMode (async) for the AMD require calls

### ISSUE THREAD

**Issue by mstarets** [webpack/webpack#7130]
**Do you want to request a *feature* or report a *bug*?** feature

**What is the current behavior?**
Dynamic imports allow lazy and lazy-once bundling behavior, while the dynamic (AMD) require only seem to support lazy-once.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**
We are trying to use Webpack with a project that was written to use Require.js at runtime. We understand that the dynamic require() calls could be replaced with the dynamic imports, but it would be somewhat painful for us.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Webpack version: 4.6.
Consider two following ways to  dynamically load a module:
1. require(['./folder/' + name + '.js'], function(v){console.log(v);});
2. import('./folder/' + name + '.js').then(v=>{console.log(v);});
For any module within the './folder/' context, I would like Webpack to create a separate bundle that would be loaded when that particular module is requested by the application. For the dynamic imports, this is known as 'lazy' mode. Although Webpack compiles both to the same code, (2) supports lazy loading of bundles while (1) seems to support only lazy-once. I have debugged the Webpack code a bit, and it seems that the 'async' flag on the AMDRequireDependency is always undefined, and there is no way to control it with comments like you could do with the import. The behavior with the undefined async flag seems to match lazy-once: all modules within the  './folder/' context are placed in a single lazily-loaded bundle.
I also tried hacking on the ContextReplacementPlugin (as an experiment only) to set the async flag to "lazy" on AMDRequireDependency. That produced strange results:
1) I got a separate bundle for each module within the './folder/' context - Hurrah!
2) I got a separate bundle containing a map of the dynamically loaded bundles within the context. With the dynamic import, that map lives in the bundle that makes a dynamic request. :(
3) Instead of getting a value returned by the lazily loaded module, the callback function got a Promise! :( :(
Thanks! I am new to Webpack, so I apologize if I missed something obvious.

**Comment by sokra** [comment]
As you noticed this mode is not supported AMD require, either are "magic comments". I don't think it's worth the work of adding support for "magic comments" for AMD require. Migration to `import()` makes sense and AMD is old. There are no technical reasons why this can't be implemented and if you would send a  PR I would probably accept it, but I recommend to mirgate your code to ESM `import()`.

**Comment by mstarets** [comment]
Thanks, Tobias. I will look into replacing our require() calls with imports during the Webpack build (we still have to support Require.js by a large number of our framework's users). Any pointers on implementing an efficient plugin for that (perhaps examples of plugins performing similar tasks)?

**Comment by TheLarkInn** [comment]
@mstarets You could start by looking at the `ImportParserPlugin.js` and then also the `AMDParserPlugin` which gives you examples on how webpack listens to Parser hooks as it traverses module ast's and creates Dependency objects on that module.
