### ISSUE TITLE
Feature Request: better CSS support for native Web Components

### ISSUE THREAD

**Issue by Hanterdro** [webpack/webpack#7135]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
With the extract CSS plugin (or similar ones) it is not possible to add the extracted CSS manually to the document/template.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Webpack 5 will include the extract CSS plugin.
It would be a great when importing a css file we would have an option that the CSS file would be but not added automatically to the document. Instead of that we would get back the PATH of the file.

Example:

```
{
            test: /\.scss$/,
            oneOf: [{
                resourceQuery: /getUrl/,
                doNotAddToDocument: true, //find a better name for this
                use: [
                    {
                        loader: 'css-loader',
                    }, {
                        loader: 'resolve-url-loader'
                    }, {
                        loader: 'sass-loader
                    }]
            }]
        }
```

```
  import fileUrl from './myDesign.scss?getUrl‘;
```

For Web Components I need the CSS inside the shadow DOM of the Web Component. If I get the URL I could add  the file path in the template of my Web Component.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Better support for vanilla Web Components

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Webpack 5

**Comment by evilebottnawi** [comment]
@Hanterdro Can you provide repo what you have right now and what you expected. In near future we will implement build-in css support. But your issue is some measleading.

**Comment by Hanterdro** [comment]
I am not sure what is misleading, but your wish is my command.

Here is a small demo of what I meant:

https://github.com/Hanterdro/webpack-web-component-issue-demo

**Comment by evilebottnawi** [comment]
@Hanterdro Thanks!

**Comment by CarterLi** [comment]
@Hanterdro You can easily get the whole css string with `css-loader`

https://github.com/webpack-contrib/css-loader#tostring
