### ISSUE TITLE
Dynamic binding src attribute for an image in VueJS

### ISSUE THREAD

**Issue by TeodorDre** [webpack/webpack#7136]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Wrong parsing images by webpack

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Current binding a src attribute from 'string'

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Hello!

I'im using webpack + vue-loader for insert my images from unsplash api.

Here a code https://gist.github.com/TeodorDre/742a244039e2ea6f3f7ceede4d2e4d30

On 11 line i try dinamically binding my images. But instead of string src attribute, i got this -> http://tinypic.com/r/t7kfbm/9 first link
https://imgur.com/6mckmWM second link

I'have no idea what is a trouble. It can be file-loader or url-loader, but i cant understand why webpack trying to do something with image. It is remote an api link.

Webpack 3.10.0. Here is my config https://gist.github.com/TeodorDre/5865d1b5bcc45dc02e7245ded2237b16

example string that comes from api `https://images.unsplash.com/photo-1522205940279-d75807ebcd91?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE5NzE1fQ&s=7cd6765ea295c5b917e921e8ea4aa007`

**Comment by sokra** [comment]
webpack doesn't do that. Maybe file this issue in the vue repository. cc @yyx990803

**Comment by TeodorDre** [comment]
I have found something interesting in my bundle. 

https://imgur.com/a/tTqVZ2G 

why it is duplicate?

**Comment by evilebottnawi** [comment]
@TeodorDre I think it is out of scope `webpack`, can you enable/disable loader and looks who is do it. When create issue in their repo(s). Thanks!

**Comment by TeodorDre** [comment]
I'll try to wait Evan`s answer. Please dont close this issue, i do it myself, when i resolve problem.

**Comment by sokra** [comment]
> I'll try to wait Evan`s answer.

He probably won't answer, it's not his repo.

> Please dont close this issue, i do it myself, when i resolve a problem.

Closing because it's not a webpack issue. Copy it to your own issue tracker if you want to keep it.
