### ISSUE TITLE
bug: `chunkhash` changes for `js` when `css` was changed

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack#7138]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

I use https://github.com/webpack-contrib/mini-css-extract-plugin with options

```js
new ExtractCSSPlugin({
      chunkFilename: '`[name]-[contenthash].chunk.css'
      filename: '[name]-[contenthash].css'
})
```

And 

```js
output: {
    chunkFilename: '[name]-[chunkhash].chunk.js',
    filename: '[name]-[chunkhash].js',
  }
```
for long term caching. 
When i change something in `js` only `chunkhash` changes (i.e. all works as expected).
When i change something in `css` `chunkhash` for `js` changes, but `js` content is same and `chunkhash` should not changes.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create simple config with options above.
2. Add `js` entry point.
3. Inside `js` entry point `import` css file.
4. Change something in `js` and look on `chunkhash`
5. Change something in `css` and look what `chunkhash` changes.

**What is the expected behavior?**

`chunkhash` should not changes when i something change in `css`.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

`node@10.0.0` and `webpack@4.6.0`

**Comment by evilebottnawi** [comment]
Other example of problem https://github.com/webpack-contrib/mini-css-extract-plugin/issues/117

**Comment by mishelen** [comment]
Confirm that behaviour. This is repo for reproduction https://github.com/mishelen/reproduce_hash_invalidation

**Comment by sokra** [comment]
Use `ouput.chunkFilename: "[contenthash].js"` instead.

**Comment by evilebottnawi** [comment]
@sokra it is recommendation? should we send PR to docs or it is workaround?

**Comment by mishelen** [comment]
works! Are here some downgrades use-cases?

**Comment by mishelen** [comment]
@evilebottnawi  @sokra 
I have example of other workaround without changing `[chunkthash]` on `[contenthash]`. As I understand it done under hood.

```js
// ...
import WebpackMd5Hash from 'webpack-md5-hash';

export default merge(baseConfig, {
    output: {
        filename: '[name].[chunkhash].js'
    },
    plugins: [
        new webpack.HashedModuleIdsPlugin(),
        new WebpackMd5Hash(),
        new ExtractCSS({
            filename: '[name].[contenthash].css'
        })
    ]
});
```

**Comment by evilebottnawi** [comment]
@mishelen `webpack-md5-hash` is workaround for very old hash problem, and use logic as  `contenthash`. We should fix this problem inside `webpack` and/or add note about this do docs.

**Comment by evilebottnawi** [comment]
@mishelen looks we should use `[contenthash]` instead `[hash]` and `[chunkhash]`, issue about update readme https://github.com/webpack/webpack.js.org/issues/2096

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack/webpack.js.org/issues/2096.
Short: use `[contenthash]` instead `[hash]` and `[chunkhash]`.

**Comment by evilebottnawi** [comment]
@mishelen `[chunkhash]` only for backward compatibility
