### ISSUE TITLE
Polyfills.ts is loading before main.ts, hence failing in ie11.

### ISSUE THREAD

**Issue by foo-baar** [webpack/webpack#7139]
Hello,

I am trying to use the default polyfills.ts file provided with Angular boiler plate, However I replaced the bootstraping from cli to webpack, this results in an unusual lading behaior of files:

![image](https://user-images.githubusercontent.com/13655874/39378881-a041e4ce-4a27-11e8-957e-3322f7875c22.png)

Resulting in code failing to work on IE 11, here is my webconfig code:
```
let config = {
  entry: {
    polyfills: `${SRC_PATH}/polyfills.ts`,
    main: `${SRC_PATH}/main.ts`
  },
  output: {
    path: DIST_PATH,
    filename: 'js/[name].js',
  },
  resolve: {
    extensions: ['.ts', '.js']
  },
```
Highly appreciate your time.

**Comment by ooflorent** [comment]
It looks like you just deleted our [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template.
