### ISSUE TITLE
typescript const enum + lodash + webpack

### ISSUE THREAD

**Issue by sevaTechoPark** [webpack/webpack#7146]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Uncaught ReferenceError: someEnumName is not defined

**If the current behavior is a bug, please provide the steps to reproduce.**
if typescript enum is const, and use _.values(someEnumName) webpack crashed.
if enum isn't const everything is okay

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Chromium 65.0.3325.181 Built on Ubuntu , running on Ubuntu 16.04
node v9.4.0 (npm v5.6.0)

**Comment by Legends** [comment]
Please provide a minimal reproducible example, thanks

**Comment by sevaTechoPark** [comment]
ok this is **file.ts**

## does'not work
```
import _ from 'lodash';

export const enum someEnumName {
   someEnumField1 = 'SOME_ENUM_FIELD_1,
   someEnumField1 = 'SOME_ENUM_FIELD_2',
   someEnumField3 = 'SOME_ENUM_FIELD_3',
}

export const SOME_VARIANTS = _.values(someEnumName);
```

## work

```
import _ from 'lodash';

export enum someEnumName {
   someEnumField1 = 'SOME_ENUM_FIELD_1,
   someEnumField1 = 'SOME_ENUM_FIELD_2',
   someEnumField3 = 'SOME_ENUM_FIELD_3',
}

export const SOME_VARIANTS = _.values(someEnumName);
```

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by sevaTechoPark** [comment]
Okey i will try do it later

**Comment by sokra** [comment]
This is not a webpack issue. It's maybe a typescript issue, but I guess it's not an issue at all since `someEnumName` is a type and `_.values` doesn't take type. It depends on the error message you get (which you didn't provided).
