### ISSUE TITLE
[Proposal]: hook for when HMR cannot update for Nodejs apps

### ISSUE THREAD

**Issue by Toxicable** [webpack/webpack#7150]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
There is no way to know when a process restart is required, when a Nodejs application is running in hot mode

**If the current behavior is a bug, please provide the steps to reproduce.**
It's not a bug but you can reproduce this here 
https://github.com/Toxicable/nodejs_target_demo
1. `yarn`
2. `yarn architect api1:binary`
3. edit `main.hmr.ts`
-> error thrown: `[HMR] You need to restart the application`

**What is the expected behavior?**
There should be a hook, possibly a WebSocket which can optionally notify a host process to restart the app.

**If this is a feature request, what is motivation or use case for changing the behavior?**
This would allow my process to fallback to restarting the process itself if a hot module update failed.
And possibly display the update text in a different format.

Proposed API:
Since the Child Process hierarchy can become a bit of a mess I think circumventing that with a WebSocket connection would be best.

I propose we enable it through options in the `HotModuleReplacementPlugin`.
```
hotModuleFailNotiferServer: {
  enabled: boolean;
  address: string;
}
```
Although a nicer approach might be to forward an object similar to `stats` from the compiler.
With all the normal information that would be instead be going through stdout

which might look like
```typescript
hotModuleStats: {
  enabled: boolean;
  address: string;
}
```

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
N/A

**Comment by sokra** [comment]
There are callback to notify about that: https://webpack.js.org/api/hot-module-replacement/#apply

**Comment by Toxicable** [comment]
Unless i misunderstand it that is only available to the process being hot reloaded, not the host.
Therefore it would be impossible for the process to kill itself and recreate it

**Comment by sokra** [comment]
Only the running process knows when the update happens and if it failed. You can send a message back to the parent process if you need to.

**Comment by Toxicable** [comment]
@sokra The idea here is that webpack should be able to serve this websocket server so that I have a reliable, and well known message bus to connect to.
Your proposed solution will not work for my use case since I do not control the script being hot loaded.
