### ISSUE TITLE
what reuseExistingChunk: true means, can give a sample?

### ISSUE THREAD

**Issue by 8427003** [webpack/webpack#7151]
**Do you want to request a *feature* or report a *bug*?**
document not clear

**What is the current behavior?**
what optimization.splitChunks reuseExistingChunk: true means, can give a sample?
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
can give a sample?  `reuseExistingChunk`: true or false,  what different?

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

**Comment by 8427003** [comment]
@PlayMa256  that's no clear, can give a sample?

**Comment by ooflorent** [comment]
@webpack-bot move to webpack/webpack.js.org
