### ISSUE TITLE
webpack-cli doesn't execute 

### ISSUE THREAD

**Issue by TobiasBaumgarten** [webpack/webpack#7156]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
webpack doesn't execute and doesn't show any errors. After a while there comes an fatal memory error.

**If the current behavior is a bug, please provide the steps to reproduce.**
I just installed webpack (npm i -D webpack) without the cli.
It's the version 4.6.0. After I was setting up my typescript pack, i wanted to run npx webpack. For sure I had to install the webpack-cli, the cl asked me if I want to fix it. I did what the cl wanted.
The cl installed the webpack-cli 2.1.0, and I believe that is wrong.
With the webpack-cli 2.1.0 and the webpack 4.6.0 nothing happen after I run npx webpack (see below). After upgrading to the webpack-cli 2.1.2 everything works fine.

**What is the expected behavior?**
The cl should install the right version.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
windows 10, npm 5.6.0

**Comment by evilebottnawi** [comment]
@TobiasBaumgarten `webpack-cli 2.1.0 ` was broken. Also it is related to `webpack-cli`. We release new very light and fast CLI https://github.com/webpack-contrib/webpack-command. Feel free to try it first. Thanks!

**Comment by montogeek** [comment]
@evilebottnawi What is the distinction between both CLI, it seems that this is going to confuse our users a lot.
