### ISSUE TITLE
Chunks in different folders

### ISSUE THREAD

**Issue by i-have-no-name** [webpack/webpack#716]
It's possible to place chunk file with entry file in the same folder ? 
<pre>
var webpack = require('webpack');
var path = require('path');
var compiler = webpack({
	context: 'root',
	entry: {
		'folder-a/all': './main/folder-a/all',
		'folder-b/all': './main/folder-b/all',
		'folder-c/all': './main/folder-c/all'
	},
	resolve: {
		root: 'root'
	},
	output: {
		path: 'output/',
		filename: '[name].js',
	}
});

compiler.run(function(err, stats) {
	console.log(stats.toJson());
});
</pre>
I need that chunk file located with all.js file in entry folder:
folder-a/
all.js
1.chunk.js

folder-b/
    all.js
    2.chunk.js
...
It's possible? thanks)

**Comment by sokra** [comment]
chunks are not assigned to entry points (i. e. two entries could share a chunk). If you want to keep them separate you better use multiple configurations (pass an array of config to webpack).

**Comment by i-have-no-name** [comment]
Thanks you!
