### ISSUE TITLE
jQuery plugins available for all modules?

### ISSUE THREAD

**Issue by DanielApt** [webpack/webpack#717]
I'm noticing that when requiring jQuery plugins, they are suddenly available to all modules. I'd expect the plugin function to only be available to the module which required this plugin.

I've got an example of this at [my repo](https://github.com/DanielApt/webpack-bug). I also explain the general setup below:

Let's say you have a script, which requires two components:
```
// script.js
// requirements
var Component1 = require('./component-1');
var Component2 = require('./component-2');

$(function () {
	// initialise components
	new Component1();
	new Component2();
});
```

Each component looks very simple. The big difference is that **Component 1 requires a plug-in; Component 2 does not.** 

```
//component-1.js
// call our fancy fade out plug-in
require('./fancy-fade-out');

module.exports = function () {
	$('#component-1').click(function () {
		$(this).fancyFadeOut();
	});
}
```

```
//component-2.js
module.exports = function () {
	$('#component-2').click(function () {
		$(this).fancyFadeOut();
	});
}
```

Lastly this is the fancy-fade-out plugin
```
//fancy-fade-out.js
(function ($) {
	$.fn.fancyFadeOut = function () {
		this.animate({marginLeft: '200'}, 2000)
			.fadeOut();
	}
}(jQuery));
```

I'd expect a click on `#component-2` to result in an error. **It is calling a function it hasn't required. Yet for some reason no error occurs.**

I think this is very misleading, as technically Component 2 has a bug, but this bug will only surface when Component 1 is absent.

So there are two questions:
1. Do people agree this is an issue?
2. How would I make sure that jQuery plugins are attached to the jquery within the module's scope, and not beyond it?

**Comment by jhnns** [comment]
That's not a webpack issue at all ^^. jQuery plugins register themselves to a global namespace, which is bad practice, but not explicitly prohibited by CommonJS.

But to be honest: Most jQuery plugins are poorly written and most of the time you'll find better libraries without jQuery dependency.

**Comment by DanielApt** [comment]
Ok, glad to hear this is at least not a webpack issue.

Would you have any suggestions on how to make a jQuery plugin work in a local namespace?

PS, some context: We want to run tests on each module, and of course then we'd realise a vast amount of components are using plugin functions without importing them.

**Comment by jhnns** [comment]
Sorry, I don't think that this is possible without too much effort. jQuery plugins are monolithic by design and should all work on the same instance.

But you could [alias](http://webpack.github.io/docs/configuration.html#resolve-alias) all jquery plugins with a local module, which initializes the requested plugin and then exports `jquery`:

``` javascript
// lib/jquery-plugins/plugin-a.js

var $ = require("jquery");

// explicit path is important here, because otherwise
// the module would require() itself
require("../../node_modules/jquery-plugin-a");

module.exports = $;
```

``` javascript
// webpack.config.js

var path = require("path");

    ...
    resolve: {
        ...
        alias: {
            "jquery-plugin-a": path.resolve(
                __dirname,
                "path/to/lib/jquery-plugins/plugin-a.js"
            ),
            "jquery-plugin-b": path.resolve(
                __dirname,
                "path/to/lib/jquery-plugins/plugin-b.js"
            )
        }
    },
    ...
```

Then you can just `require()` the plugin like you're used to do:

```javascript
$ = require("jquery-plugin-a");
```

However, all plugins still work on the same instance. But that's how jQuery plugins are designed...

**Comment by DanielApt** [comment]
Thanks for that @jhnns! I know enough now, and I'll close this as it's not a webpack issue.

**Comment by ldong** [comment]
+1 Thank you @jhnns

**Comment by rubyisapm** [comment]
But it doesn't work like mentioned above, even in the file lib/jquery-plugins/plugin-a.js, the $ is also not global.

**Comment by Quadriphobs1** [comment]
Hello @jhnns  I am sorry, I am a little bit confused with that approach, after setting the module in webpack, if I want to make a call to the JQuery plugin like say 
```
var path = require("path");

    ...
    resolve: {
        ...
        alias: {
            "slider": path.resolve(
                __dirname,
                "path/to/lib/jquery-plugins/slider.js"
            )
        }
    },
    ...
```

and i did `$ = require("slider");` in my `main.js` , how can i call like say `$('#hello').slider({ // slider options })`
