### ISSUE TITLE
Webpack with Typescript: "inline-source-map" does not map Typescript correctly - wrong typescript mapping

### ISSUE THREAD

**Issue by MrSantaCloud** [webpack/webpack#7172]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Since I've migrated to webpack 4.6.0, Visual Studio breakpoints started positioning in the end of the file as a wrong mapping symptom. With the same configuration but with webpack 3.11.0, it used to work fine

**If the current behavior is a bug, please provide the steps to reproduce.**
See my webpack.config file below and [THIS stackoverflow question](https://stackoverflow.com/questions/50006292/) which is well detailed about it. With this configuration, simply try to place a breakpoint on a typescript file in visual studio 2017 and start debug.
Breakpoints will be moved on the bottom of the file during debug.
**I've also tried with other configurations but the problem persists**.
So it looks like a source map issue.

**What is the expected behavior?**
Breakpoints should not move from where they are. Mapping should be correct and it should have a similar behavior to what it had on the previous webpack version. (3.11.0)

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
_____________________________________________________________________________
**NOTE:** I've also enabled sourcemap from tsconfig
_____________________________________________________________________________
**VERSIONS**
    "typescript": "^2.8.3"
    "webpack": "^4.6.0"
    "webpack-cli": "^2.0.15"
_____________________________________________________________________________
**WHAT CHANGED BETWEEN 3.11.0 and 4.6.0:**
Changed this from "PLUGINS":
```
new AngularCompilerPlugin({
                tsConfigPath: './tsconfig.json',
                entryModule: path.join(__dirname, 'ClientApp/app/app.server.module#AppModule'),
                //exclude: ['./**/*.browser.ts']
                exclude: ['./**/*.browser.ts','/node_modules/']
            })
```
in this, under "OPTIMIZATION":
```
minimizer: [
                // we specify a custom UglifyJsPlugin here to get source maps in production
                new UglifyJsPlugin({
                    //cache: true,
                    cache: isDevBuild ? false : true,
                    parallel: true,
                    uglifyOptions: {
                        //compress: false,
                        compress: isDevBuild ? false : {
                            sequences: true,
                            dead_code: true,
                            conditionals: true,
                            booleans: true,
                            unused: true,
                            if_return: true,
                            join_vars: true,
                            drop_console: true
                        },
                        ecma: 6,
                        mangle: isDevBuild ? false : true
                    },
                    sourceMap: isDevBuild ? true : false
                })
            ]
```
_____________________________________________________________________________

**WEBPACK CONFIG FILE**
```
const path = require('path');
const webpack = require('webpack');
const merge = require('webpack-merge');
const AngularCompilerPlugin = require('@ngtools/webpack').AngularCompilerPlugin;
const CheckerPlugin = require('awesome-typescript-loader').CheckerPlugin;
var nodeExternals = require('webpack-node-externals');
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');

const isClient = typeof window !== 'undefined';

module.exports = (env) => {
    // Configuration in common to both client-side and server-side bundles
    const isDevBuild = !(env && env.prod);

    const sharedConfig = {
        stats: { modules: false },
        context: __dirname,
        resolve: { extensions: ['.js', '.ts'] },
        output: {
            filename: '[name].js',
            publicPath: 'dist/', // Webpack dev middleware, if enabled, handles requests for this URL prefix
            globalObject: 'self'
        },
        module: {
            rules: [
                { test: /\.ts$/, include: /ClientApp/, use: ['awesome-typescript-loader?silent=true', 'angular2-template-loader', 'angular2-router-loader'] },
                { test: /\.html$/, use: 'html-loader?minimize=false' },
                { test: /\.css$/, use: ['to-string-loader', 'style-loader', isDevBuild ? 'css-loader' : 'css-loader?minimize'] },
                { test: /\.(png|jpg|jpeg|gif|svg)$/, use: 'url-loader?limit=25000' },
                //font management
                {
                    test: /\.(svg|eot|ttf|woff|woff2)$/,
                    use: [{
                        loader: 'file-loader',
                        options: {
                            name: 'images/[name].[hash].[ext]'
                        }
                    }]
                }
            ]
        },
        plugins: [new CheckerPlugin()]
    };

    // Configuration for client-side bundle suitable for running in browsers
    const clientBundleOutputDir = './wwwroot/dist';
    const clientBundleConfig = merge(sharedConfig, {
        entry: { 'main-client': './ClientApp/boot.browser.ts' },
        output: { path: path.join(__dirname, clientBundleOutputDir) },
        optimization: {
            minimizer: [
                // we specify a custom UglifyJsPlugin here to get source maps in production
                new UglifyJsPlugin({
                    cache: isDevBuild ? false : true,
                    parallel: true,
                    uglifyOptions: {
                        compress: isDevBuild ? false : {
                            sequences: true,
                            dead_code: true,
                            conditionals: true,
                            booleans: true,
                            unused: true,
                            if_return: true,
                            join_vars: true,
                            drop_console: true
                        },
                        ecma: 6,
                        mangle: isDevBuild ? false : true
                    },
                    sourceMap: isDevBuild ? true : false
                })
            ]
        },
        plugins: [
            new webpack.DllReferencePlugin({
                context: __dirname,
                manifest: require('./wwwroot/dist/vendor-manifest.json')
            })
        ].concat(isDevBuild ? [
            // Plugins that apply in development builds only
            new webpack.SourceMapDevToolPlugin({
                filename: '[file].map', // Remove this line if you prefer inline source maps
                moduleFilenameTemplate: path.relative(clientBundleOutputDir, '[resourcePath]') // Point sourcemap entries to the original file locations on disk
            })
        ] : [])
    });

    // Configuration for server-side (prerendering) bundle suitable for running in Node
    const serverBundleConfig = merge(sharedConfig, {
        resolve: { mainFields: ['main'] },
        entry: { 'main-server': './ClientApp/boot.server.ts' },
        plugins: [
            new webpack.DllReferencePlugin({
                context: __dirname,
                manifest: require('./ClientApp/dist/vendor-manifest.json'),
                sourceType: 'commonjs2',
                name: './vendor'
            })
        ].concat(isDevBuild ? [] : []),
        output: {
            libraryTarget: 'commonjs',
            path: path.join(__dirname, './ClientApp/dist')
        },

        target: 'node',
        externals: [nodeExternals()], // in order to ignore all modules in node_modules folder

        devtool: 'inline-source-map'
    });

    return [clientBundleConfig, serverBundleConfig];
};

```

**Comment by MrSantaCloud** [comment]
🍻 🎉 **SOLVED** 🎉 🍻 

ADOPTED SOLUTION:
**Disabling "browser link" on my visual studio 2017 dropdown list worked**

Seems not to be a webpack related issue. Feel free to close this.
Also, excuse me for every time-waste that I could have caused to webpack staff with this. 
Hope this would be helpful to other users too!

**Comment by MrSantaCloud** [comment]
@webpack-bot close

**Comment by MrSantaCloud** [comment]
Seems like that the problem is not solved yet.
This time, I also get the following error:

> WARNING in configuration The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment. You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

Even if I explicitly define mode in my configuration or in every command.

**Comment by mrbar42** [comment]
This has been an issue for me as well. after digging deeply into what goes wrong with type script files i ended up adding `SourceMapDevToolPlugin` jsut for `.ts` files which fixed it in my case.

```js
module.exports = {
  devTools: 'inline-source-map', // this will handle .(.js|css) files
  // ...
  plugins: [
      // apply this plugin only to .ts files - the rest is taken care of
      new webpack.SourceMapDevToolPlugin({
        filename: null,
        exclude: [/node_modules/],
        test: /\.ts($|\?)/i
      })
  ]
};
```

the problem is that webpack defaults to this pattern `/\.(js|css)($|\?)/i` [here](https://github.com/webpack/webpack/blob/a02bf9960db209909b04a1ace23b07b0717d0964/lib/SourceMapDevToolPlugin.js#L87) which in turn ignores the `.ts` files [here](https://github.com/webpack/webpack/blob/a02bf9960db209909b04a1ace23b07b0717d0964/lib/ModuleFilenameHelpers.js#L162).
unfortunately the `test` options doesn't seem to be changeable from the outside, not even through hooks

**Comment by evilebottnawi** [comment]
Hi, sorry for delay, you can send a PR with fix :+1:

**Comment by evilebottnawi** [comment]
I was wrong here, no problems with webpack, here problems with `awesome-typescript-loader`, my recommendation is migration on `ts-loader`, feel free to feedback

Solution here https://github.com/webpack/webpack/issues/7172#issuecomment-414115819 is very strange, because inside webpack you should have js/css/html/etc assets, ts/tsx/jsx should be transpiled in js

Also maybe it was bug in webpack@3, anyway please consider to migrate on webpack@5 and feel free to open an issue if you faced with the problem again
