### ISSUE TITLE
caching problem: delete js file or add js file, many js files's hash will change 

### ISSUE THREAD

**Issue by jinxin479** [webpack/webpack#7175]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I use react-router to spilt chunks,but when I delete a route or add a route,almost all the chunks's hash has changed even the chunk'content has not been changed
**If the current behavior is a bug, please provide the steps to reproduce.**
**this is a github repo 
[webpack-reproduce-repo](https://github.com/jinxin479/webpack-repo)**

**What is the expected behavior?**
only content-changed chunk's hash will changed
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
node 8.1
webpack 4.6
OS  OSX
I have used HashedModuleIdsPlugin

the output config is 

```webpackConfig.output = {
    filename: "[name].[chunkhash].js",
    path: paths.dist(),
    publicPath: config.compiler_public_path,
    chunkFilename: "[name].[chunkhash].chunk.js"
}
```

**here is a github repo  [webpack-reproduce-repo](https://github.com/jinxin479/webpack-repo)**

**Comment by evilebottnawi** [comment]
@jinxin479 Please use all points fo issue template and create minimum reproducible test repo. Feel free to reopen after your fix issue. Thanks!

**Comment by jinxin479** [comment]
please reopen this issue.thanks

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a **small** reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by jinxin479** [comment]
I have create a github repo  [](https://github.com/jinxin479/webpack-repo) .

**Comment by jinxin479** [comment]
I have create a github repo .[webpack-repo](https://github.com/jinxin479/webpack-repo)

**Comment by lili21** [comment]
You should use `webpack.NamedChunksPlugin` or `optimization.namedChunks: true` in production mode.
