### ISSUE TITLE
Webpack errors when combined with jsdom

### ISSUE THREAD

**Issue by DanielApt** [webpack/webpack#718]
I'm trying to compile this file with webpack:
```
var jsdom = require('mocha-jsdom');

describe('WatchlistAsset', function () {
    jsdom();

    it('has document', function () {
        var div = document.createElement('div');
        expect(div.nodeName).eql('DIV');
    });
});

It seems quite simple, yet the presence of jsdom breaks everything.
```
First of all it can't find `fs`:
```
ERROR in ~/webpack-project/~/jsdom/lib/jsdom.js
Module not found: Error: Cannot resolve module 'fs' in ~/webpack-project/node_modules/jsdom/lib
 @ ~/webpack-project/~/jsdom/lib/jsdom.js 1:9-22
```

Afterwards a *huge* amount of errors are thrown by webpack, and it's even parsing files I wouldn't expect it to parse e.g. `~/webpack-project/node_modules/jsdom/node_modules/htmlparser2/node_modules/entities/maps/entities.json`

PS: I have tried setting `node: {fs: 'empty'}` as suggested at https://github.com/webpack/jade-loader/issues/8, but no luck

**Comment by jhnns** [comment]
jsdom can't be used in the browser afaik because of native dependencies. You can't run C-code in the browser.

And why would you want to emulate a browser in a browser? ^^

**Comment by DanielApt** [comment]
Because we wanted to start testing our components automatically in the command line.

Either way, we got a working solution using [`mocha-phantomjs`](https://github.com/metaskills/mocha-phantomjs). I'm happy to close, as this is no longer an issue for us, and it is very niche an issue.

**Comment by sokra** [comment]
If you want to run bundles in node.js, use `--target node`. And you maybe also need the [`node-loader`](https://github.com/webpack/node-loader).

**Comment by Gijsjan** [comment]
Also with `--target node` and `node-loader`, I can't get it work.

**Comment by jhnns** [comment]
@Gijsjan error message?

**Comment by ColCh** [comment]
@DanielApt thank you for the link!

**Comment by tukushan** [comment]
I had this problem, but just ignored jsdom:
```
    plugins: [
        new webpack.IgnorePlugin(/jsdom$/)
    ]
```

So my dev and production bundles don't include jsdom, and I can run (mocha) tests from the command line.

**Comment by maoziliang** [comment]
I had the save problem. I introduced a file which construct the global document and window objects by jsdom, and the file import the webpack bundles contain the test code.
``` javascript
var JsDom = require('jsdom');

global.document = JsDom.jsdom('<!DOCTYPE html><html><head></head><body></body></html>');
global.window = document.defaultView;
global.navigator = window.navigator;

require('./build/test.bundle.js');
```
