### ISSUE TITLE
Move vendors cacheGroup to a mode more specific than 'none'

### ISSUE THREAD

**Issue by MilosRasic** [webpack/webpack#7182]
**Do you want to request a *feature* or report a *bug*?**

Requesting a feature, well, more of a change to existing feature.

**What is the current behavior?**

With webpack 4.6.0, with mode: 'none', webpack is still building vendors~ chunks because of the default settings for optimization.splitChunks.cacheGroups. We have to explicitly pass vendors: false to disable this behaviour.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

I would expect mode: 'none' to not have any explicit cacheGroups settings so that webpack would generate only the chunks implied by dynamic imports in my code.

**If this is a feature request, what is motivation or use case for changing the behavior?**

mode: 'none' is supposed to let users opt out of zero-config and take control of their bundling. split-chunks-plugin should respect this.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

node 8.11.1
webpack 4.6.0
Linux

**Comment by evilebottnawi** [comment]
@MilosRasic It is breaking changes, we can't do this in `webpack@4`, also mode for enable optimization, `splitChunks.cacheGroups` is code splitting, not optimization

**Comment by MilosRasic** [comment]
> It is breaking changes, we can't do this in webpack@4

True, and I'm not asking for it in webpack 4, but I think it's the right thing to do at some point.

> also mode for enable optimization, splitChunks.cacheGroups is code splitting, not optimization

idk, it's optimization.splitChunks, makes me think splitting is part of optimization

**Comment by evilebottnawi** [comment]
Need discussion around this

**Comment by sokra** [comment]
> mode: 'none' is supposed to let users opt out of zero-config and take control of their bundling. split-chunks-plugin should respect this.

`mode: "none"` is supposed to not do any development or production specific optimizations. It's doesn't disable all optimizations. `optimization.splitChunks` is not development or production specific, like `optimization.availableModule` `optimization.mergeDuplicationChunk`, etc. It's a general chunk graph transformation. So in my opinion that makes sense.

Anyway as @evilebottnawi already said, changing it would be a breaking change, so we can't change it now.

**Comment by MilosRasic** [comment]
Makes sense, but I still think there should be a more elegant way to opt out of the defaults.

One way I can think of that wouldn't be a breaking change is a flag, for example `optimization.useDefaultCacheGroups`, that defaults to true. Not a perfect solution but better than passing `defaults: false` and `vendors: false` and `optimization.splitChunks.cacheGroups`

Ideally I'd love to see it as opt-in feature in webpack 5, something like:

```
optimization: {
	splitChunks: {
		...myOptions,
		cacheGroups: {
			...webpack.defaultCacheGroups,
			...myCacheGroups,
		},
	},
},
```

**Comment by evilebottnawi** [comment]
@MilosRasic great idea about `webpack.defaultCacheGroups` :+1: It is not breaking changes, you can send PR

**Comment by MilosRasic** [comment]
@evilebottnawi It is because it would only make sense if users had to explicitly spread it into their `optimization.splitChunks.cacheGroups`, which breaks it for current webpack 4 users who don't but rely on the chunks output by the defaults :(

**Comment by evilebottnawi** [comment]
But i think code splitting and dev/prod mode is very difference and better to avoid mixed this options. 

We should find way to better enable and disable `cacheGroups` without `isDevelopmentEnv ? {} : { //Splitting }` construction.

**Comment by evilebottnawi** [comment]
@MilosRasic 
Maybe `splitChunks.modeSwitcher: true` (maybe better name)? If `modeSwitcher` enable `cacheGroups` for production and disable for development. \

**Comment by MilosRasic** [comment]
@evilebottnawi I suggested `optimization.useDefaultCacheGroups` but it could also be `optimization.splitChunk.useDefaultCacheGroups`

tbh, I find it a bit confusing that there's `optimization.splitChunks` with a bunch of properties but `optimization.runtimeChunk` is not part of it.
