### ISSUE TITLE
vendors.bundle.js:formatted:1 Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by venkikonamma458** [webpack/webpack#7183]
`module.exports = {
    entry: [
        './src/client/index'
    ],
    output: {
        filename: '[name].bundle.js',
        path: path.resolve(__dirname, 'public/assets/scripts')
    },
    resolve: {
        extensions: ['.webpack.js', '.web.js', '.ts', '.tsx', '.js'],
        modules: [
            'node_modules'
        ]
    },
    module: {
        rules: [
            {
                test: /\.tsx?$/, 
                loader:'ts-loader',
                options:{
                    transpileOnly: true
                },
                exclude: /node_modules/
            },
            {
                test: /\.scss$/,
                loaders: [
                    'style-loader',
                    'css-loader',
                    'sass-loader'
                ]
            }
        ]
    },
    externals:[
        // nodeExternals({
        // })
    ],
    optimization: {
        splitChunks: {
            cacheGroups: {
                commons: {
                    test: /[\\/]node_modules[\\/]/,
                    name: "vendors",
                    chunks: "all"
                }
            }
        }
    },
    plugins:[
        new ForkTsCheckerWebpackPlugin({
            checkSyntacticErrors: true,
            watch: ['./src']
        }),
        new webpack.NamedModulesPlugin(),
        new webpack.NoEmitOnErrorsPlugin()
    ],
    watch:process.env.NODE_ENV === 'development'? true : false,
    mode: process.env.NODE_ENV,    
    target: 'node'
}`

Above is my webpack configuration. After running webpack, vendors.bundle.js and mai.bundle.js is created. The problem is that i get the following errors when these files are loaded from the browser.

`vendors.bundle.js:formatted:1 Uncaught ReferenceError: exports is not defined
    at vendors.bundle.js:formatted:1
(anonymous) @ vendors.bundle.js:formatted:1
main.bundle.js:1 Uncaught TypeError: Cannot read property 'call' of undefined
    at i (main.bundle.js:1)
    at Object../src/client/index.tsx (main.bundle.js:1)
    at i (main.bundle.js:1)
    at Object.0 (main.bundle.js:1)
    at i (main.bundle.js:1)
    at ./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/client/common/components/app-shell/shell.scss (main.bundle.js:1)
    at main.bundle.js:1`

I am using webpack - v4.6.0, Nodejs -v9.9.0 and OS - windows

**Comment by evilebottnawi** [comment]
@venkikonamma458 please use issue template. Feel free to reopen issue after fix it. Thanks!
