### ISSUE TITLE
No error is given if output filename not specified

### ISSUE THREAD

**Issue by jbrantly** [webpack/webpack#719]
Take the following config file:

```
module.exports = {
    entry: './app.js'
}
```

Running webpack with it results in the help info being presented (as if `webpack --help` had been executed). If an output filename is specified then everything works correctly.

```
module.exports = {
    entry: './app.js',
    output: {
        filename: 'bundle.js'
    }
}
```

This threw me through a loop for awhile since the node API will still process the first example but the CLI just shows the help info. I think either the CLI should go ahead and process like the node API does (potentially confusing if there is no output) or the CLI should show an error message stating that an output filename must be specified.

**Comment by jbrantly** [comment]
Or a third option: default filename to 'bundle.js'.

**Comment by raulferras** [comment]
Same is happening to me, but I got the `output` option defined and can't find where the error is... 
Definitely an error message would be appreciated.

**Comment by jhnns** [comment]
Throwing an error is probably the best option, because these automatisms are rarely useful.

**Comment by SpaceK33z** [comment]
Closing since this was fixed a year ago (see commit above).
