### ISSUE TITLE
Bundle still contains all exports after sideEffects: false 

### ISSUE THREAD

**Issue by pravdomil** [webpack/webpack#7190]
**Do you want to request a *feature* or report a *bug*?**
possible bug

**What is the current behavior?**
Output bundle contains `index.js` `a.js` `b.js` `c.js` from `big-module`, and `a.js` `b.js` `c.js` from `big-module-with-flag`.

```js
/* 8 */
/*!************************************************!*\
  !*** ./node_modules/big-module-with-flag/c.js ***!
  \************************************************/
/*! exports provided: c */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "c", function() { return c; });
const c = "c";
```

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/webpack/webpack/tree/master/examples/side-effects

**What is the expected behavior?**
Output bundle contains `index.js` `a.js` `b.js` `c.js` from `big-module`, and `a.js` and `b.js` **but not `c.js`** from `big-module-with-flag`.

**If this is a feature request, what is motivation or use case for changing the behavior?**
unsed imports are built (which can fail if you target specific target like `web`)

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
macos10.13 node10 npm6 webpack4.6.0

**Comment by sokra** [comment]
It only works when `optimization.sideEffects: true` is enabled, which is only enabled in `mode: "production"`

**Comment by pravdomil** [comment]
hi guys, I have set `mode: "none"` that was the issue, do you consider removing the unused exports even if mode is set to nothing? I have this case:

```js
// main.js
import { clientCode } from "b"
clientCode()
```

```js
// lib/index.js
export * from "./client-code"
export * from "./server-code"
```

but it fails to run because the `export * from "./server-code"` is still evaluated (even with sideEffects: false)  in `mode: "none"` and that server part fails to build for specific targets

I will update the example so that is more clear the whole situation.

**Comment by edmorley** [comment]
@sokra, it seems that there are quite a few cases of user confusion over `mode: 'none'`. Has it been considered to remove support for it in webpack 5, and make `mode` mandatory at all times? (Or at least make the default be `production` rather than `none`?)

**Comment by sokra** [comment]
The default is `production`. You have explicitly add `mode: "none"` to the configuration and the documentation tells you to not do that.

**Comment by nicewahson** [comment]
i found that production mode can remove unuse exports,so, does sideEffects can work correctly?

**Comment by luckydrq** [comment]
>i found that production mode can remove unuse exports,so, does sideEffects can work correctly?

I have the same confusion. Uglify Plugin is enabled in production mode which would do dead code elimination. Actually i am still confused with how `sideEffects: false` works. The docs are not very clear and [this example](https://github.com/webpack/webpack/blob/master/examples/side-effects/README.md) seems confused too, why `big-module-with-flag` still contains `./c`.

**Comment by luckydrq** [comment]
>It only works when optimization.sideEffects: true is enabled, which is only enabled in mode: "production"

It works when set `optimization.sideEffects: true` manually under `mode: 'development'`. I think the words should be `It only works when optimization.sideEffects: true is enabled, which is enabled in mode: "production" by default`

**Comment by kushalmahajan** [comment]
I am following the docs very precisely and I am not able to see my used "cube" function either in prod bundle. Second, if I happen to use previously build file for exporting functions functions remain in the bundle. Something is not right. 

Again, I more than triple checked with docs as in what am I doing.
