### ISSUE TITLE
document.Rt is not a function

### ISSUE THREAD

**Issue by kylops** [webpack/webpack#7191]
Hi all,

I am using "uikit": "^3.0.0-beta.42", "webpack": "^3.11.0"
When doing `import UIkit from 'uikit'` in the entry, console throws this error`TypeError: document.Rt is not a function`.

Also very wired, if I import font-awesome `require('font-awesome/css/font-awesome.css')`, the error is `Uncaught TypeError: document.Z is not a function`,

 If I do `window.UIkit = UIkit` without the window.UIkit, the error changes to `Uncaught TypeError: document.Un is not a function`

This is my index.js:
```
import UIkit from 'uikit'
window.UIkit = UIkit
```

webpack config rules:
```
rules: [
            {
                test: /\.js/,
                loaders: ['babel-loader'],
                exclude: /node_modules/,
            },
            {
                test: /\.vue$/,
                loaders: ['vue-loader'],
                exclude: /node_modules/,
            },
            {
		    	test  : /\.scss$/,
		    	loader:  ExtractTextPlugin.extract({
		    		fallback:"style-loader",
		    		use:"css-loader!sass-loader"
		    	})
            },
            {
                test: /\.css$/,
                loader: 'style-loader!css-loader?sourceMap'
            },
            {
                test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
                loader: 'url-loader',
                options: { limit: 10000, name: '/fonts/[name].[hash:7].[ext]' }
            },
              {
                test: /\.(jpe?g|png|gif|svg)$/i,
                use: [
                  'file-loader?name=images/[name].[ext]',
                  'image-webpack-loader?bypassOnDebug'
                ]
              },
            {
                test: require.resolve('uikit'),
                loader: 'expose-loader?UIkit'
            },
                  // font-awesome
            {
                test: /font-awesome\.config\.js/,
                use: [
                    { loader: 'style-loader' },
                    { loader: 'font-awesome-loader' }
                ]
            },
            {
                test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
                loader: "url-loader?limit=10000&mimetype=image/svg+xml"
            }
        ],
```

webpack 4 is very buggy and causes more issues for me.

Anyone saw this issue before?

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
