### ISSUE TITLE
Build error because of npm link?

### ISSUE THREAD

**Issue by jasonkuhrt** [webpack/webpack#720]
This error isn't very clear to me. It only started happening after I did:

```
⧑ npm ln ../littlebitselectronics-ui                                                                                                               

npm WARN package.json pad-component@0.0.1 No repository field.
npm WARN package.json transform-property@0.0.1 No repository field.
npm WARN package.json swipe@1.7.4 repo should probably be repository.
javascript-detect-element-resize@0.5.3 ../littlebitselectronics-ui/node_modules/javascript-detect-element-resize

futura-round-family@1.0.0 ../littlebitselectronics-ui/node_modules/futura-round-family

iconic-web-family@0.0.1 ../littlebitselectronics-ui/node_modules/iconic-web-family

iconic-svg@0.1.1 ../littlebitselectronics-ui/node_modules/iconic-svg
/usr/local/lib/node_modules/littlebits-ui -> /Users/jasonkuhrt/projects/littlebitselectronics-ui
unbuild littlebits-ui@1.2.8
/Users/jasonkuhrt/projects/cloud-app-cloud-control/node_modules/littlebits-ui -> /usr/local/lib/node_modules/littlebits-ui -> /Users/jasonkuhrt/projects/littlebitselectronics-ui
```

The build error is:

```
> cloud-app-cloud-control@0.1.12 start /Users/jasonkuhrt/projects/cloud-app-cloud-control
> webpack-dev-server --progress --colors --devtool eval

 70% 1/1 build moduleshttp://localhost:8080/webpack-dev-server/
webpack result is served from /
content is served from /Users/jasonkuhrt/projects/cloud-app-cloud-control/build
dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/jasonkuhrt/projects/cloud-app-cloud-control/node_modules/webpack-dev-server/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/build/Release/fse.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/jasonkuhrt/projects/cloud-app-cloud-control/node_modules/webpack-dev-server/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/build/Release/fse.node
  Expected in: dynamic lookup

[1]    11444 trace trap  npm run dev
```

**Comment by sokra** [comment]
@es128 Any idea?

**Comment by es128** [comment]
Never seen something like this before. Try `npm rebuild` to make sure fsevents is compiled correctly for the version of node you're running.

**Comment by jhnns** [comment]
Funny, I had the same error yesterday. After switching back to node `0.10.35` and re-compiling (via `npm rebuild`) everything was working was expected.

**Comment by es128** [comment]
@jhnns which version of node were you using when you saw the error?

**Comment by es128** [comment]
I just reproduced this error. In my case it had to do with switching from io.js back to node without doing an `npm rebuild`.

**Comment by jhnns** [comment]
> @jhnns which version of node were you using when you saw the error?

`0.11.14`

**Comment by es128** [comment]
You should be able to switch back, as long as you `npm rebuild` again before running it.

**Comment by realchaseadams** [comment]
Ran into this as well, `npm rebuild` also worked for me, thanks @jhnns.

**Comment by elsigh** [comment]
I have this same error (as does a colleague).
$ node --version
v0.12.0
$ npm --version
2.5.1

Tried npm rebuild too.

lsigh@Lindseys-MBP:~/src/shift/s0 (master) $ ./scripts/grunt webpack
Running "webpack:app" (webpack) task
Version: webpack 1.7.2
                       Asset     Size  Chunks             Chunk Names
    ./.tmp/scripts/bundle.js  1435731       0  [emitted]  main
./.tmp/scripts/bundle.js.map  1697013       0  [emitted]  main
dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/elsigh/project/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/build/Release/fse.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/elsigh/project/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/build/Release/fse.node
  Expected in: dynamic lookup

**Comment by timkendall** [comment]
I'm on node `0.10.35` and `npm rebuild` fixed this for me also

**Comment by jonnywyatt** [comment]
@es128 good call, fixed it for me thanks

**Comment by lorem--ipsum** [comment]
`npm rebuild` fixed the error too for me. I recently started using io.js with nvm, which created this error on another project. Thanks !

**Comment by vikashvverma** [comment]
`npm rebuild` and it works.

**Comment by AChaoZJU** [comment]
npm rebuild not working for me
