### ISSUE TITLE
splitChunks : none of the options is self-explanatory and documentation is cryptic

### ISSUE THREAD

**Issue by gkatsanos** [webpack/webpack#7203]
I know this ticket might not conform with the issue creation policy but I will try to compile a list of questions here hoping that they can be addressed (I am willing to make PRs to improve the documentation)

**1. optimization.runtimeChunk**
I guess this makes sense if you have more than one entry points.  In any other case, the appropriate value should be `'false'` , correct?

**2. optimization.occurrenceOrder**
Does this option still exist? (not found in documentation using search)

**3. optimization.namedChunks**
Same as above.

**4. maxInitialRequests**
I had cases when a cacheGroup was not generating a file until I increased the default maxInitialRequests value to something like "10". I have no idea why that is.

(and most importantly)
**5. test**
I am migrating a setup with which we were using simple strings to target individual node_modules which we wanted in a separate generated file to split the end result of vendors in smaller files. Some of the test rules don't seem to be doing what I think they should - is there a way to debug this? Can I just use a simple string like "moment.js" or should I target the parent directory using a regexp : `/[\\/]moment[\\/]/`. 

**6. chunks**
The documentation of the options "initial", "async" and "all" is just a repetition of the option word itself. Desperately looking for a tangible example.

**Comment by montogeek** [comment]
@webpack-bot move to webpack/webpack.js.org

**Comment by Birdy1234** [comment]
How do I remove this so I can see my messages
