### ISSUE TITLE
Cannot read property 'compilation' of undefined | ProvidePlugin.js

### ISSUE THREAD

**Issue by Octavector** [webpack/webpack#7205]
I'm in the process of updating the workflow of a website which is _currently_ dependant on jQuery (a number of slider plugins require it etc.).

This workflow uses Gulp and Webpack-stream to bundle(Webpack) and then move(Gulp) the files to another destination.

Everything works fine until I tried to implement JQuery. I have tried a number of methods but the most promising looked to be the ProvidePlugin method as outlined in the Webpack docs: https://webpack.js.org/plugins/provide-plugin/#usage-jquery

Below is my webpack.config.js:

**webpack.config.js**

```js
const webpack = require('webpack'); 
const config = {
  module: {

  },
  plugins: [
    new webpack.ProvidePlugin({
      $: "jquery",
      jQuery: "jquery",
      "window.jQuery": "jquery",
    })
  ]
};

module.exports = config;
```

Prior to adding the declaration of a `new webpack.ProvidePlugin` instance the Gulp/Webpack combo would run perfectly, yet as soon as I uncomment the `new webpack.ProvidePlugin()` I receive the following error in the console:

```
.../node_modules/webpack/lib/ProvidePlugin.js:19
		compiler.hooks.compilation.tap(
		              ^
TypeError: Cannot read property 'compilation' of undefined
```

I'm using Webpack 4.7.0 and webpack-stream 4.0.3
Any ideas, greatly appreciated!

**Comment by Octavector** [comment]
UPDATE: To rule out any Gulp related issues from what appeared to be a Webpack problem, I made some amendments to my webpack.config.js and ran webpack directly:

**webpack.config.js**
```js
const webpack = require('webpack'); 
const path = require('path');

const config = {
  entry: './js/index.js',
  output: {
    path: '/path/to/output/js',
    filename: 'output.js'
  },
  module: {

  },
  plugins: [
    new webpack.ProvidePlugin({
      $: "jquery",
      jQuery: "jquery",
      "window.jQuery": "jquery",
    })
  ]
};

module.exports = config;
```

This succeeded, and JQuery appeared to be bundled correctly. 
Knowing this, I removed webpack-stream and used [gulp-shell](https://www.npmjs.com/package/gulp-shell) to simply run the webpack script directly.

Despite the error coming from webpack/lib/ProvidePlugin.js the issue may be one for [webpack-stream ](https://github.com/shama/webpack-stream)?

**Comment by enscope** [comment]
@Octavector It would be very nice of you to add that replacement configuration of yours to serve as a temporary override for others (myself included) until it is properly fixed by the team.

**Comment by GregLevenhagen** [comment]
I believe this is an issue with [webpack-stream](https://github.com/shama/webpack-stream), since passing in the second argument to it tells _webpack-stream_ to override its built-in version of _webpack_ and use whatever version of _webpack_ you've **required**.

**Comment by ooflorent** [comment]
```
TypeError: Cannot read property 'compilation' of undefined
```

This error means that webpack 3 is used because `hooks` is defined within the compiler constructor. Please open an issue in webpack-stream repository.
