### ISSUE TITLE
[Documentation] Css-Bundle examples are broken in the docs

### ISSUE THREAD

**Issue by UiCandy** [webpack/webpack#7208]
Following the examples on the readme I found the documentation & the respective directory `/css-bundle` for the following links is broken:
#### CSS Bundle
- css-bundle
- multiple-entry-points-commons-chunk-css-bundle

It would help if we could remove the links for greater clarity or even better, someone can push the required files, as I'm sure the multiple-entry-points example will be a good springboard for a lot of developers working on larger applications.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
