### ISSUE TITLE
what does the file 'webpack.web.js' in the lib folder for?

### ISSUE THREAD

**Issue by webfrontzhifei** [webpack/webpack#7211]
In the package.json, I find a this mapping '"web": "lib/webpack.web.js"', but i have not found anyone else use this file, so i want to the the usage scenarios of that file. Thank you all!

**Comment by evilebottnawi** [comment]
For run webpack in browser, also please don't remove issue template in future.

**Comment by webfrontzhifei** [comment]
thank you

**Comment by SeifESlimene** [comment]
> For run webpack in browser,

@alexander-akait What does it mean "For run webpack in browser"?
How this field "web" is called from?
I wanna know the code or tool that use it

I don't find anything on the web about a package.json field called "web", this is enigmatic for me now.
