### ISSUE TITLE
_newArrowCheck failing for webpack 4.6.0 and above

### ISSUE THREAD

**Issue by r-tock** [webpack/webpack#7213]
# Bug report

**What is the current behavior?**
In webpack 4.5.0  a global arrow function generates the following code gen

Original code
```javascript
const foo = (a) => something();
```

Generated code 4.5.0 and below;
```javascript
var _this = undefined;
function foo(a) {
  _newArrowCheck(undefined, _this);
  something();
}.bind(undefined);
```

In webpack 4.6.0 and above the same thing generated
```javascript
var _this = this;
function foo(a) {
  _newArrowCheck(this, _this);
  something();
}.bind(this);
```

And the newArrowCheck fails. This seem to be happening for global functions under Both safari 11 and Chrome 66. So I am thinking this is a webpack bug.

**If the current behavior is a bug, please provide the steps to reproduce.**
See above.

**Other relevant information:**
webpack version:  Webpack 4.5.0, 4.6.0, 4.7.0
Node.js version: N/A
Operating System: Mac OS

**Comment by r-tock** [comment]
Both tests were done with optimize: false and mode: 'development'

**Comment by sokra** [comment]
cc @ooflorent
