### ISSUE TITLE
splitChunks.chunks option is too limited

### ISSUE THREAD

**Issue by noahgrant** [webpack/webpack#7217]
## Feature request

Please feel free to close if I've missed something, but after spending a couple days trying to upgrade to webpack 4 (`CommonsChunkPlugin` -> `optimization.splitChunks`), it seems like while we've gotten a lot of great additional behavior, we've also lost a really important one: I can no longer specify which chunks I want to contribute to the splits.

With `CommonsChunkPlugin`, I had a vendor chunk that I specified be extracted explicitly from `entryA.js` via the `chunks` property. Of course, the vendor chunk was _not_ extracted from any of the async chunks (which is a great feature of `splitChunks`!), but I have a few other entry points that I _don't_ want split up, and I don't know how to do it:

* I have `entryB.js`, which should be a standalone js file for its own page.
* I have `workerA.js`, `workerB.js`, and `workerC.js`, which don't share a runtime environment with the main thread (no `window` or `document`, for example), so these _must_ be standalone files. Yet, say `workerA.js` imports `underscore`—well, I have no way for it _not_ to be split up if I want `entryA.js` split up. Unless I'm missing something, this seems like a huge issue.

**What is the expected behavior?**
I would like to have a `chunks` property inside a `cacheGroup` that allows us to specify the entry file the splits should be taken from, or at least have a way to say 'all (initial and async) except these files.'

**What is motivation or use case for adding/changing the behavior?**
I'm not sure I see a reasonable path forward here otherwise; maybe I should create multiple webpack configs and put the non-split files in those?

**How should this be implemented in your opinion?**
Bringing back the Commons-style `chunks` property to some extent would be lovely.

**Are you willing to work on this yourself?**
possibly

**Comment by linaspasv** [comment]
I have the same problem. Is there any workaround?

**Comment by lili21** [comment]
I guess you can use the `test` option.

```javascript
...
test: (module, chunks) => {
  // 
}
...

**Comment by evilebottnawi** [comment]
@noahgrant can you provide current your configuration and describe what behavior you need and can't setup?

**Comment by lili21** [comment]
```javascript
...
splitChunks: {
  common: {
    test: /\.js$/,
    chunks: [ 'chunkA', 'chunkB', 'chunkC']
  }
...
}
...
```

split common stuff of `chunksA`, `chunkB`, and `chunkC`.  I need this.

**Comment by noahgrant** [comment]
@evilebottnawi here are the highlights of my config, annotated with the issue(s) as well as what i'd like to see:

```js
module.exports = {
  module: {
    noParse: [
      /d3$/,
      /jquery$/,
      /moment$/,
      /underscore$/
    ],
    rules: [{
      test: /\.jsx?$/,
      exclude: /(node_modules|vendor)/,
      use: (!env.prod() ? ['react-hot-loader'] : []).concat(['babel-loader?cacheDirectory=true'])
    }, {
      test: /\.s?css$/,
      use: ['style-loader', 'css-loader', 'sass-loader']
    }, {
      test: /\.svg$/,
      use: ['babel-loader', 'svg-react-loader']
    }]
  },

  optimization: {
    splitChunks: {
      automaticNameDelimiter: '-',
      // common chunks are extracted from split files only here--which we need so
      // that our console.js entry file doesn't depend on anything else
      chunks: 'async',
      name: true,
      maxAsyncRequests: 3,
      cacheGroups: {
        vendor: {
          // the big issue for us is right here. we want the vendor file to be taken from our _main_
          // entry file as well as all of our async chunks, since it is a top-level script executed before
          // anything else. but our main entry file is not our _only_ entry file. we have others that are worker
          // scripts, and as worker scripts don't share the same thread/scope, they _can't_ have any vendor
          // files split out. so i'd like an array option here for the `chunks` property, where i can add
          // keywords like 'all', 'async', etc, but also provide names of entry chunks as we could with
          // CommonChunks, to whitelist which bundles become source bundles for the splits.
          chunks: 'all',
          test: ({resource}) => /(node_modules|js\/vendor)/.test(resource),
          name: 'vendor'
        }
      }
    }
  },

  output: {
    // as a sidenote, while you're looking at this, i think it's a bug that the vendor file, if taken from 'all'
    // (both async and initial files) takes the chunkFilename pattern instead of the filename pattern. if
    // we're taking from the initial files, shouldn't it be safe to assume that the chunk itself will be a
    // sibling to those files? issue for this is at https://github.com/webpack/webpack/issues/7235
    filename: '[name].js',
    chunkFilename: env.prod() ? '[name]-[chunkhash].js' : '[name].js',
    // important for ensuring the HMR runtime won't crash our worker scripts
    globalObject: 'this',
    path: `${root}build/js`,
    publicPath: '/js/'
  },

  plugins: _.compact([
    // exports our chunk hashes to a json file to keep them out of our entry js file
    new ChunkManifestPlugin({
      outputType: 'js',
      filename: 'chunkManifest',
      manifestVariable: 'chunkManifest'
    }),
    !env.prod() ? new webpack.HotModuleReplacementPlugin() : null,
    new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
    new webpack.NormalModuleReplacementPlugin(
      /moment-timezone\/data\/packed\/latest\.json/,
      require.resolve(`${root}/src/js/constants/timezone_constants.json`)
    ),
    (argv.s || argv.stats) ? new BundleAnalyzerPlugin({analyzerMode: 'static'}) : null
  ])
};

**Comment by lili21** [comment]
@evilebottnawi that's what I do right now. But I hope the chunks option can accept array.

**Comment by noahgrant** [comment]
@evilebottnawi won't that _only_ take from the specified entry chunks? What if we want to specify all async chunks (which we don't know entirely in advance) in addition to specified entry chunks? That's my ideal solution.

**Comment by evilebottnawi** [comment]
@noahgrant `chunks: (chunk) => { return !chunk.canBeInitial() && ["array", "of", "my", "async" "lovely", "chunks"].includes(chunk); }`

**Comment by evilebottnawi** [comment]
`chunk` is object what have all possible properties

**Comment by noahgrant** [comment]
@evilebottnawi thanks! Let me look into it and get back to you. Would love it if this functionality were documented!

**Comment by chrisdothtml** [comment]
@evilebottnawi From my comment above:

> I tried providing a `test` function to my `cacheGroup` to exclude certain entries from being subjected to the plugin, but it seems that even if I return `false` for those entires, they still have commons extracted out of them; which seems to indicate that the `test` option is for filtering chunks _that are candidates for extraction_, rather than chunks _that are subjected to it_

**Comment by noahgrant** [comment]
@evilebottnawi this works great—small modification in that we need to check `chunk.name` instead of `chunk`, but this did the trick for me:

```js
chunks: (chunk) => !chunk.canBeInitial() || chunk.name === <my_entry_file_name>
```

thanks again! feel free to close this issue, but i would really love this to be added to the documentation.

**Comment by chrisdothtml** [comment]
@evilebottnawi Ignore my previous comment. I didn't realize you were suggesting providing a function for the `chunk` parameter.

I also think I misunderstood the original problem of this issue. It sounds like I have a bit of a different use case, and am hoping I can find a solution, as this is the only thing holding my team back from upgrading to webpack v4.

My problem is that I have the entry points `a.js`, `b.js`, and `c.js`, and I want to be able to specify that I _don't want common chunks excluded from_ `c.js` (i.e. `a.js` and `b.js` should still have them extracted out, but `c.js` should have all the chunks in its bundle). Is this something that's possible with the method you're suggesting?

**Comment by noahgrant** [comment]
@chrisdothtml your problem seems very similar to mine, and this fixed it for me. prior to this, i was using an array of webpack configs, but with this, if you do:

```js
chunks: (chunk) => chunk.name !== 'c'
```

that should work. in my example from my previous comment, that snippet took out common chunks from:

* other async chunks (as represented by `!chunk.canBeInitial()`)
* one of our entry files (represented by `chunk.name === <my_entry_file_name>`). but we actually have a few entry files—they just need to have all their dependencies except the one represented by `<my_entry_file_name>`.

if i'm understanding correctly, this should cover it?

**Comment by chrisdothtml** [comment]
@noahgrant You're totally right! Looks like that fixes it for me.

I made [a PR](https://github.com/webpack/webpack.js.org/pull/2183) to add this to the docs

**Comment by evilebottnawi** [comment]
Thanks everyone and thanks for PR to docs. Solved.

**Comment by adrienharnay** [comment]
Hey, I believe this feature could still be useful. Here is my use case:
- one entry point (which I will call `main`)
- several async chunks

The defaults work really great for everything, except for one tiny thing: `chunks: 'async'`. In the `main` chunk, I conditionally import some polyfills (e.g. `intl`), and they end up bundled in `main`. If I want to split `intl` from 'main', and modify the config like this:
```
    splitChunks: {
      chunks: chunk =>
        !chunk.canBeInitial() || chunk.name === 'main',
      cacheGroups: {
        intl: {
          test: /[/\\]node_modules[/\\]intl[/\\]/,
          name: 'intl',
        },
      },
    },
```

Then I modify all of Webpack's defaults, and all `vendors` end up in a separate chunk.
cc @evilebottnawi

**Comment by KrishnaPG** [comment]
Earlier, multiple `CommonsChunkPlugin` can be inserted into the pipeline to split the chunks in  different ways. For example,

````
      // split vendor js into its own file
      new webpack.optimize.CommonsChunkPlugin({
        name: 'dependencies',
        minChunks(module) {
          // any required modules inside node_modules are extracted to vendor
          return ( module.resource &&  /\.js$/.test(module.resource) &&   module.resource.indexOf(path.join(__dirname, '../node_modules')) === 0 )
        }
      }),
      // extract webpack runtime and module manifest to its own file in order to
      // prevent vendor hash from being updated whenever app bundle is updated
      new webpack.optimize.CommonsChunkPlugin({
        name: 'manifest',
        minChunks: Infinity
      }),
      // This instance extracts shared chunks from code splitted chunks and bundles them
      // in a separate chunk, similar to the vendor chunk
      // see: https://webpack.js.org/plugins/commons-chunk-plugin/#extra-async-commons-chunk
      new webpack.optimize.CommonsChunkPlugin({
        name: 'app',
        async: 'dependencies-async',
        children: true,
        minChunks: 3
      })    
````

How to arrive at this behavior with `splitChunks`. Does it accept array?
