### ISSUE TITLE
[Documentation] Css-Bundle examples are broken in the docs

### ISSUE THREAD

**Issue by UiCandy** [webpack/webpack#7222]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The documentation & the respective directory `/css-bundle` for the following links is broken
##### CSS Bundle
- css-bundle
- multiple-entry-points-commons-chunk-css-bundle

**If the current behavior is a bug, please provide the steps to reproduce.**
Just follow the examples on the main readme file and click on the link under `css-bundles`

**What is the expected behavior?**
The link should resolve to something, It would help if we could remove the links for greater clarity or even better, push the required files.

**If this is a feature request, what is motivation or use case for changing the behavior?**
The multiple-entry-points example would be a great springboard for a lot of developers working on larger applications.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
None

**Comment by evilebottnawi** [comment]
@UiCandy where documentation broken?

**Comment by montogeek** [comment]
@evilebottnawi Here https://github.com/webpack/webpack/tree/master/examples#css-bundle
I haven't tested but half of those links don't work, a lot of examples were deleted when CommonChunkPlugins were refactored.

**Comment by evilebottnawi** [comment]
@montogeek yep, we need delete broken examples, maybe fix other

**Comment by UiCandy** [comment]
I'll go through the links later today and send a PR truncating all the broken links : )

**Comment by BeniCheni** [comment]
Hello, @UiCandy. Would you happen to be still helping update the links in the css-bundle doc? (Saw you comment from 2 days ago. Just wondering if I can pick up this "_D0: My First Commit_" labeled open issue, if you not working on it anymore. 🙏

**Comment by khanghoang** [comment]
@BeniCheni I'd like to take this if @UiCandy is busy atm.

**Comment by UiCandy** [comment]
I'm really sorry for being away, I'll be creating a PR soon.

**Comment by arkadyt** [comment]
@sokra I think issue has to be closed.

**Comment by evilebottnawi** [comment]
@arekkas thanks!
