### ISSUE TITLE
ERROR in v20180507182839/js/main.ca1d7fad.js from UglifyJs

### ISSUE THREAD

**Issue by chenyiqi** [webpack/webpack#7224]
new webpack.optimize.UglifyJsPlugin({
        // 压缩文件
        compress: {
            warnings: false,
            drop_console: true,
            drop_debugger: true
        }
    })

![image](https://user-images.githubusercontent.com/3357208/39698198-70ffd1ec-5226-11e8-8fc2-3bb650668de5.png)

# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
