### ISSUE TITLE
Optionally include plugins in config via ternary operator

### ISSUE THREAD

**Issue by grgur** [webpack/webpack#7226]
## Feature request

I would find it useful to be able to optionally pass plugins to a configuration. 

**What is the expected behavior?**
A quick way to turn plugins on or off based on ternary operator.

**What is motivation or use case for adding/changing the behavior?**
I'm too lazy to create new modes and combinations of modes for specific environmental configurations (e.g. specific CI situations)

**How should this be implemented in your opinion?**
Something like this:

```js
plugins: [
  maybeFoo ? new Foo() : null,
]
```

I feel `null` is the right _type_ for this, but `null` is also not part of WebpackOptionsValidation right now.

I tested this by adding a simple `typeof` check in `lib/webpack.js` and it seems to work fine (only when options validation is bypassed).

```js
for (const plugin of options.plugins) {
	if (typeof plugin === 'function') plugin.apply(compiler);
}
```

WebpackOptionsDefaulter coupled with mode flags could be another way to achieve this. The defaulter certainly makes things organized and easier to read, but being able to switch things up ad-hoc is often a huge plus, IMHO. 

If this is something the team decides would be useful, I reckon an update to WebpackOptions is due since `null` is not currently an expected type. I tried to mimic the behavior with boolean (false) and it seems to yield the right results.

**Are you willing to work on this yourself?**
yes!

**Comment by evilebottnawi** [comment]
@grgur why not
```
plugins: [
  new Plugin(),
].concat(isDev: ? [new DevPlugin ()] : [new ProdPlugn()])
```

**Comment by grgur** [comment]
@evilebottnawi good thinking. This goes to my point that organizing plugins based on `modes` would be clean and maintainable. However, it's often the case that we need to turn things on and off based on finer criteria, or even temporary (e.g. debugging a CI failure, tweaking a specific environment setup, or similar).

This can obviously be achieved as such:
```js
const noop = () => {};

plugins: [
  maybeFoo ? new Foo() : noop,
]
```

... but that just doesn't feel right.

**Comment by evilebottnawi** [comment]
@grgur you can create noop plugin with empty apply :smile:

**Comment by sokra** [comment]
also possible:

``` js
plugins: [
  maybeFoo && new Foo()
].filter(Boolean)
```

This can be solved on user level and don't need special handling in webpack
