### ISSUE TITLE
Dot starting folders not matching in require.context result regex

### ISSUE THREAD

**Issue by valvic66** [webpack/webpack#7233]
# Bug report

We are working on a project built with lerna and storybook.
One of the folders we are trying to match in require.context starts with dot: .stories
We have folders like this in the root folder:
packages/name1/src/.stories/one.js
packages/name2/src/.stories/two.js
packages/name3/src/.stories/three.js

**What is the current behavior?**
The below is not matching and is returning an empty array
`
const allStories = require.context('../packages', true, /[^\/]+\/src\/[.]stories\/.*\.js/);
`

The below is working if we change the name of the folder from .stories to stories
`
const allStories = require.context('../packages', true, /[^\/]+\/src\/stories\/.*\.js/);
`

**If the current behavior is a bug, please provide the steps to reproduce.**
The regex matches in any regex tester and also in console.
Maybe require.context regex behaves differently?

**What is the expected behavior?**
Should return an array with all .js files within all the folders starting with .stories
Should find a way to match the folder .stories!

**Other relevant information:**
webpack version: 3.8.1  
Node.js version: 8.10.0
Operating System: Linux Ubuntu 16.04 LTS
Additional tools: Lerna, Storybook, React

**Comment by sokra** [comment]
They are intentionally excluded. Rename them.

**Comment by valvic66** [comment]
Thanks a lot for your quick reply.

**Comment by evilebottnawi** [comment]
@valvic66 can we close issue?

**Comment by valvic66** [comment]
Yes pls. We have already changed the name of the folders. Thanks a lot.
