### ISSUE TITLE
Webpack 4 'loader' docs should explain difference between 'query' and 'options'

### ISSUE THREAD

**Issue by mnieber** [webpack/webpack#7234]
Hi, the Webpack 4 documentation states that loader options can be set via `options` or `query`, but doesn't explain how to choose between them (e.g. can you just use either one? or does the choice depend on the option that you are trying to set?). Since these 2 choices are in different bullet points, I get the impression that they are not aliases for the same thing.

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.

**Comment by montogeek** [comment]
Documentation says https://webpack.js.org/configuration/module/#rule-options-rule-query:
> Rule.query is deprecated in favor of Rule.options and UseEntry.options

`.query` exists for backward compatibility reasons, nothing more. We encourage to use the new way `.options`.
