### ISSUE TITLE
dynamic publicPath for SourceMapDevToolPlugin 

### ISSUE THREAD

**Issue by florian-bd** [webpack/webpack#7237]
## Feature request

**What is the expected behavior?**
Define a dynamic publicPath for sourceMaps

**What is motivation or use case for adding/changing the behavior?**
Having different enviromnents when deploying the code makes it impossible to have statically defined sourceMaps publicPath

**How should this be implemented in your opinion?**
Provide a global variable like ``` __webpack_public_path__```

**Are you willing to work on this yourself?**
yes

**Comment by sokra** [comment]
That does work for technical reasons. SourceMap reference is defined by special comment. It can't contain dynamic values.
