### ISSUE TITLE
requiring a missing module throws a different error message than native

### ISSUE THREAD

**Issue by odedniv** [webpack/webpack#7238]
# Bug report

The pattern thrown by exceptions is important when attempting to ensure we catch the exception we expect to catch.

**What is the current behavior?**

```javascript
require('missing-module');
```

throws: `Cannot find module "missing-module".` (with double quotes and period)

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
require('missing-module');
```

**What is the expected behavior?**

Should throw: `Cannot find module 'missing-module'` (with single quotes and no period)

**Other relevant information:**
webpack version:  4.8.1
Node.js version: 8.11.1
Operating System: macOS 10.13.4
Additional tools:

**Comment by shellscape** [comment]
![meme](http://i0.kym-cdn.com/photos/images/original/000/288/186/d7d)

**Comment by ooflorent** [comment]
Feel free to send a PR.

**Comment by Janpot** [comment]
Doesn't seem like the most solid practice to make your code depend on what's in an error message. I don't think they're guaranteed to be always the same. Seems like webpack rather needs something like [error.code](https://nodejs.org/api/errors.html#errors_error_code)?

**Comment by odedniv** [comment]
1. There's an e.code, it only tells the error type - not which module is missing (e.g successfully requiring a module that then requires another module that is missing - I want to crash there).
2. There is no reason to have this tiny deviation from the standard which is seen across v4,6,8,9 of nodejs (I'm guessing it's through all of them - those are the ones I tested). Our code (which is a dependency) needs to work both when the depender uses webpack and when it doesn't.

**Comment by Janpot** [comment]
I'm not at all against aligning with what node does. I'm only mentioning it because I don't think the message is as "standardized" as the error code. If by "the standard" you mean "canonical across node versions". To me it feels a bit brittle to rely on the error message and parse out the intended required module through some regex or something.

**Comment by odedniv** [comment]
Yes @Janpot it is brittle, unfortunately this is the error object NodeJS supplies :disappointed:  I definitely would wish that it had a `module` property as well as the `code` property, but I don't think that's something to fix here in webpack (it wouldn't help my use case since I can't rely on the project getting webpacked).

**Comment by odedniv** [comment]
Closed by #7303

**Comment by odedniv** [comment]
Closed by #7303
