### ISSUE TITLE
Webpack production mode should have uglifyOptions.output.comments = false by default

### ISSUE THREAD

**Issue by Maximaximum** [webpack/webpack#7246]
## Feature request

**What is the expected behavior?**
I'd expect the webpack bundles to be as small as possible in the production mode. Currently, however, the comments don't get removed from the bundles.

**What is motivation or use case for adding/changing the behavior?**
The very idea of a "production" mode is that the bundles should be as small as possible and load as fast as possible. Removing the comments decreases the bundle size incredibly.

**How should this be implemented in your opinion?**
`uglifyOptions.output.comments` should be set to `false` by default in the production mode.

**Are you willing to work on this yourself?**
No, I'm totally new to webpack so I don't want to break something

**Comment by evilebottnawi** [comment]
@Maximaximum Expected behavoiour, webpack don't remove legal comment (copyright, licenses and etc), we should respect other developers. You can configure uglify plugin in `minimizer` option and set `comments: false`. Thanks!

**Comment by txiaocao** [comment]
if I use mode "production" how to remove comments? too mush comment by libs

**Comment by markusenglund** [comment]
@txiaocao Installing uglifyjs-webpack-plugin from npm worked for me. It seems that the docs are wrong about the supposed existence of `webpack.optimize.UglifyJsPlugin`.

My config:
`const UglifyPlugin = require("uglifyjs-webpack-plugin");`
...
`plugins: [
    new UglifyPlugin({
      uglifyOptions: {
        output: {
          comments: false
        }
      }
    })
  ],`

**Comment by txiaocao** [comment]
very thanks!!! because I just removed uglifyjs-webpack-plugin...囧，installed it is ok ~~~

**Comment by evilebottnawi** [comment]
All legal comments don't removed. Some package can have license what require has license, also it is disrespectful to the package authors.

**Comment by txiaocao** [comment]
I just installed `uglifyjs-webpack-plugin` but use 
```
mode: "production",
...
plugins: [ new UglifyPlugin({ uglifyOptions: { output: { comments: false } } }) ],
```
not ok~囧

**Comment by evilebottnawi** [comment]
@txiaocao please read my comment above

**Comment by txiaocao** [comment]
okay~~thanks
