### ISSUE TITLE
when I use webpack@4, modifyVars in less-loader can not work

### ISSUE THREAD

**Issue by sunny920406** [webpack/webpack#7247]
"webpack": "^4.8.0",
"less-loader": "^4.1.0",
![image](https://user-images.githubusercontent.com/8424604/39777938-8a867ea6-5337-11e8-94ad-6ae24fa3377c.png)
modifyVars: theme this code can not work!

**Comment by ooflorent** [comment]
@webpack-bot move to webpack-contrib/less-loader
