### ISSUE TITLE
Two entry points, nested dynamic imports, and one require.context(...) breaks output

### ISSUE THREAD

**Issue by mikedll** [webpack/webpack#7248]
# Bug report

**What is the current behavior?**

When compiling with two entry points and dynamic import statements, it's possible for webpack to become confused and output calls to `__webpack_require__.e` even though that function will not be defined in the resulting bundle.

This occurs when you have one entry point use a require.context call to load up all of your components in preparation for a server-side render. Suppose you also have a client entry point which you expect to be ready to do code splits based on dynamic imports of your components.

If you do this and have a top-level component that dynamically imports other components (thus achieving the webpack code splits), your server side entry point will be built with broken calls to an undefined `__webpack_require__.e`.

This is unnecessary because the server-side entry point could simply use the no-op Promise that is the default return of `DepBlockHelpers.getDepBlockPromise` inside of `lib/dependencies/DocBlockHelpers.js`. If one disables (erases) the client entry point in the configuration and invokes the webpack compiler, then this is exactly what happens. But, when the client entry point is included in the configuration, the server-side entry point bundle breaks.

**If the current behavior is a bug, please provide the steps to reproduce.**

    # Simplified repo to reproduce issue.
    git clone git@github.com:mikedll/webpacktest.git
    cd webpacktest
    git checkout crash1demo                # Ensure you're on my tag which shows the crash.
    npm i                                  # Install packages (there's a security warning from npm about a package, but it's not relevant to this problem).
    npm run build                          # Invoke the compiler

    # Snippet of the output
                 Asset       Size      Chunks             Chunk Names
    products.bundle.js  382 bytes           0  [emitted]  products
     careers.bundle.js  367 bytes           1  [emitted]  careers
       about.bundle.js  399 bytes           2  [emitted]  about
      server.bundle.js    5.58 kB  3, 0, 1, 2  [emitted]  server
      client.bundle.js    7.14 kB           4  [emitted]  client
            index.html  255 bytes              [emitted]  

Open `dist/index.html` in a web browser (I used Chrome) and you will see on the console:
`TypeError: __webpack_require__.e is not a function`.

I know there is no reason to include a server-side entry point in `dist/index.html`, but that doesn't mean this isn't a bug. Loading the code on the server results in the same crash for the same reason. You can inspect `dist/server.bundle.js` to see that `__webpack_require__.e` is being called, but not defined at the top of the bundle.

**What is the expected behavior?**

Since `require.context('components', true)` loads all of the components in the `components` directory for the server side entry point, the server side entry point should compile dynamic import statements into lines like this:

    new Promise(function(resolve) { resolve(); }).then(__webpack_require__.bind(null, 0));
    
Instead of this:

    __webpack_require__.e/* import() */(2).then(__webpack_require__.bind(null, 1));

**Other relevant information:**
webpack version: 3.11.0 (**I've verified that the same problem exists in webpack 4.8.1**)
Node.js version: 8.11.1
Operating System: Ubuntu 16.04.4 LTS (xenial)
Additional tools: None

The background of this issue is that I am trying to make a modern Rails app using Webpacker, React, server-side rendering, and code splits. I'm using Rails 5.2 and react-rails. I'm using react-loadable and import-inspector to do code splits via dynamic imports. I'm using react-router for route handling in my components.

**Comment by mikedll** [comment]
I devised a workaround for now. I added the following code to my server entry point:
```
if(typeof(__webpack_require__.e) === "undefined") {
  __webpack_require__.e = function(unusedChunkId) {
    return new Promise(function(resolve) { resolve(); });
  };
}
```
That allow the code to proceed server-side, and my code splits are being dynamically loaded on the client side.

**Comment by vzaidman** [comment]
may be related to #7239
