### ISSUE TITLE
deep-extend security vulnerability

### ISSUE THREAD

**Issue by isopen** [webpack/webpack#7255]
# Bug report

**What is the current behavior?**
```
npm i webpack
+ webpack@4.8.1
added 315 packages from 275 contributors in 34.396s
[!] 1 vulnerability found [3518 packages audited]
    Severity: 1 low
    Run `npm audit` for more detail
npm audit
```
<a href="https://nodesecurity.io/advisories/612">https://nodesecurity.io/advisories/612</a>

**If the current behavior is a bug, please provide the steps to reproduce.**
npm i webpack

**What is the expected behavior?**
There should be no errors. Temporarily to correct it is possible so(decision at the end of the document):
https://github.com/isopen/ngx-cable/blob/master/out_dir/native_build.help.md
I think you need to fix the package.json or package.json in dependencies.
Then test the build and publish version 4.8.x. Very much I expect :)

**Other relevant information:**
webpack version:  4.8.1, 4.4.0, 3.0.0
Node.js version: v8.9.4
Operating System: debian 9.3

**Comment by isopen** [comment]
Guys, I obviously do not understand something in this world, but the error in the installation is the same.
npm install
+ webpack@4.8.1
added 314 packages from 274 contributors in 22.636s
[!] 1 vulnerability found [3517 packages audited]
    Severity: 1 low
    Run `npm audit` for more detail

**Comment by mobimation** [comment]
I get this with 4.8.2

├─┬ webpack@4.8.2
│ └─┬ watchpack@1.6.0
│   └─┬ chokidar@2.0.3
│     └─┬ fsevents@1.2.3
│       └─┬ node-pre-gyp@0.9.1
│         └─┬ rc@1.2.6
│           └── deep-extend@0.4.2

**Comment by isopen** [comment]
I used to like the behavior of webpack in my Angular project, but from now on I still switched to standard `ng serve` and replaced the command in the documentation.
It is very sad. Previously, both teams worked in the project.
Later I will deal with it. there are some inconsistencies with the package `dev-webpack-server`, etc.
`ng serve` works after updating without superfluous telodvizheny.
There can be who knows that it is possible to undertake on the permission of a problem with webpack. Thank you.
https://github.com/isopen/soc/blob/master/frontend/package.json

**Comment by isopen** [comment]
I started my open project through a new web package. Soon I will reset the settings. But I would say that work for an astronaut who does not want to write anything, but must write. Precisely not for the novice.

**Comment by ooflorent** [comment]
@isopen Please open a new issue to discuss the other problems you encountered. Moreover, feel free to send a PR to change the _vulnerable_ dependency is the proposed solution does not cover your use-case.
