### ISSUE TITLE
Upgrading to Webpack 4.8.0 results in "Error: Cannot find module Debug"

### ISSUE THREAD

**Issue by christiango** [webpack/webpack#7258]
# Bug report

**What is the current behavior?**
Webpack is throwing the error "Cannot: find module debug" as of version 4.8.0.

I attached a node debugger and that module is being required by 
@webassemblyjs\ast\1.3.1\node_modules\@webassemblyjs\ast\lib\traverse.js

The relevant line of code is here:
https://github.com/xtuc/webassemblyjs/blob/master/packages/ast/src/traverse.js

Looking at the package.json for @webassemblyjs/ast, I don't see any dependency on debug.
https://github.com/xtuc/webassemblyjs/blob/master/packages/ast/package.json

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Expected webpack to compile without an error due to the webassemblyjs imports. Seems like this might have been related to #7245

**Other relevant information:**
webpack version:  4.8.0
Node.js version: 8.11.1
Operating System: Windows 10 RS4
Additional tools:

**Comment by xtuc** [comment]
That's correct, the dependency is missing. 

Would you mind sending a PR against https://github.com/xtuc/webassemblyjs? I'll release it asap.

**Comment by christiango** [comment]
Sure thing @xtuc , I'll do so later today.

**Comment by christiango** [comment]
@xtuc I'm having issues cloning a fork of the repo on windows. I keep getting this error:
fatal: cannot create directory at 'packages/wast-parser/test/tokenizer/number-literals/+nan:0x304050': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

Is there someone on webassemblyjs that can quickly fix this in the relevant packages? Or can we roll back the version used by webpack until this is fixed?

**Comment by xtuc** [comment]
Ok, sorry about that. I'll fix the missing dependency and ensure that it works on windows.

**Comment by christiango** [comment]
Thanks for the quick fix!

**Comment by sokra** [comment]
4.8.2

**Comment by christiango** [comment]
Unfortunately it still repros, now in a different package of webassemblyjs. I submited a pr that will hopefully address this: https://github.com/xtuc/webassemblyjs/pull/308/files

**Comment by evilebottnawi** [comment]
@christiango can you double check webpack version in `node_modules` (cat `node_modules/webpack/package.json`) and look on version field?

**Comment by evilebottnawi** [comment]
@christiango hm, looks regression

**Comment by evilebottnawi** [comment]
@christiango feel free to PR

**Comment by xtuc** [comment]
Thanks for the PR. I don't understand why the CI doesn't catch that. Sorry

**Comment by sneakyfildy** [comment]
I have this error
   "webpack": "^4.26.1",
   "webpack-cli": "^3.1.2"
