### ISSUE TITLE
Webpack 4.8.1 [dev] deep-extend security vulnerability

### ISSUE THREAD

**Issue by mattjbrent** [webpack/webpack#7259]
# Bug report

**What is the current behavior?**
Installing webpack 4.8.1 in [dev] has an outdated dependency of deep-extend with this vulnerability https://snyk.io/vuln/npm:deep-extend:20180409

with the path:

webpack > watchpack > chokidar > fsevents > node-pre-gyp > rc > deep-extend

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Not to have security vulnerabilities in webpack

**Other relevant information:**
webpack version:  4.8.1
Node.js version: 9.7.1
Operating System: osx 10.13.3
Additional tools:

**Comment by isopen** [comment]
https://github.com/webpack/webpack/issues/7255

**Comment by ooflorent** [comment]
Duplicates #7255
