### ISSUE TITLE
Question: usage of webpack for non-JS environment

### ISSUE THREAD

**Issue by geekyme** [webpack/webpack#726]
Hi @sokra , 

I am interested to use webpack for asset management along with its hot reloading capabilities. Is this possible to integrate with non-node backends? For instance, django / flask?

**Comment by sokra** [comment]
You can use a node.js server to serve the assets along with any other http server (development). The built assets are server independend (production).

http://webpack.github.io/docs/webpack-dev-server.html#combining-with-an-existing-server

**Comment by geekyme** [comment]
But how does this work with cache-busted assets? Since I couldn't predict the md5 hashes, I can't hardcode a script source to point to the generated assets (build.xxxx.js)

**Comment by jhnns** [comment]
You could write the generated `stats` into a `stats.json` file and read that with python. It contains all the necessary information.

For instance: Try `webpack --json >> stats.json` (about [--json](http://webpack.github.io/docs/cli.html#json))

**Comment by geekyme** [comment]
cool yeah i think that is possible :)

**Comment by nickjj** [comment]
@geeky I've recently written a webpack plugin to do this, you might be interested:
https://github.com/nickjj/manifest-revision-webpack-plugin

Here's a way to implement the file it produces into Flask. It would be pretty easy to make it work with Django too. https://github.com/nickjj/flask-webpack
