### ISSUE TITLE
I tried to install the webpack 4.8.1 from the sources.

### ISSUE THREAD

**Issue by isopen** [webpack/webpack#7260]
# Bug report

I probably do not understand something in this world

**What is the current behavior?**
```
git clone https://github.com/webpack/webpack.git
.npmrc => package-lock=true
npm install or npm install --prod
added 1170 packages from 851 contributors in 55.252s
[!] 27 vulnerabilities found [26552 packages audited]
    Severity: 11 low | 12 moderate | 4 high
    Run `npm audit` for more detail
npm audit
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN notice [SECURITY] uglify-js has 2 low vulnerabilities. Go here for more details: https://nodesecurity.io/advisories?search=uglify-js&version=2.2.5 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] negotiator has 1 high vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=negotiator&version=0.5.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] mime has 1 moderate vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=mime&version=1.3.4 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] fresh has 1 high vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=fresh&version=0.3.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] constantinople has 1 critical vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=constantinople&version=3.0.2 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
```

**What is the expected behavior?**
We need to do something...If you have a solution, tell me please.
Has helped: npm install express@4.16.3
In general, again you need to edit the package.json and check as many versions as possible.
In some cases, the replacement occurred at the package name level.
Perhaps in this everything was Yarn, so that's what happens. Apparently it does not have built-in security similar to the one described above.
In the course of tests through it there are many obsolete dependencies, but everything seems to be fine :)

**Other relevant information:**
webpack version:  4.8.1
Node.js version: 8.9.4
Operating System: debian 9.3

**Comment by montogeek** [comment]
What is the issue?

**Comment by isopen** [comment]
If you do not see any problems, you can close the ticket for technical support.

**Comment by isopen** [comment]
The result for today is similar.
npm install (method by contradiction)
[!] 27 vulnerabilities found - Packages audited: 26634 (23087 dev, 650 optional)
    Severity: 11 low | 12 moderate | 4 high
The list is also deep-extend@0.4.x and other obsolete dependences.

**Comment by evilebottnawi** [comment]
@isopen we don't use `deep-extend` directly, looks you should create issue in loader/plugin where `deep-extend` used. Thanks!
