### ISSUE TITLE
[Webpack 4] Percentage in ProgressPlugin is NaN

### ISSUE THREAD

**Issue by Rohit-L** [webpack/webpack#7261]
# Bug report

**What is the current behavior?**

Prior to webpack 4, when running webpack-cli with `--progress` percentage was shown during the build. After upgrading to webpack 4, the percentage stopped appearing.

**If the current behavior is a bug, please provide the steps to reproduce.**

Run webpack-cli with `--progress`

**What is the expected behavior?**

Percentage should be shown through the build.

**Other relevant information:**

I narrowed the bug down to a change in the ProgressPlugin in this commit.
https://github.com/webpack/webpack/commit/f7c2f8e470d44686a2758c2debe59b86b3396c12
See ProgressPlugin.js

`states[idx]` was previously set to all the passed in arguments and now it is only set to the remaining arguments after pecentage and message. This causes the percentage to be `NaN` when the handler is called.

I left a comment in the commit.

webpack version:  4.8.1
Node.js version: 9.4
Operating System: Ubuntu 14.04

**Comment by Rohit-L** [comment]
@evilebottnawi Here is a repo: https://github.com/Rohit-L/webpack-test

I have narrowed the problem down to when the webpack config returns an array of configurations. This causes the ProgressPlugin to go into the `if (compiler.compilers)` check, which is where the bug I described above lies.

**Comment by Rohit-L** [comment]
@evilebottnawi Did you get a change to look at this. The fix should be very simple.

**Comment by evilebottnawi** [comment]
@Rohit-L WIP

**Comment by evilebottnawi** [comment]
@Rohit-L don't reproducible

**Comment by evilebottnawi** [comment]
All works fine

**Comment by cokencode** [comment]
@evilebottnawi I got the list of process logs from test repo. 
In the picture below, the left side is the current behavior, and the right side is the behavior after fixing the line that @Rohit-L mentions in the report.
![webpack-error](https://user-images.githubusercontent.com/7133704/39933761-d9bca848-5511-11e8-940f-b128c749c11f.PNG)
