### ISSUE TITLE
Requiring AMD-style local modules as relative paths

### ISSUE THREAD

**Issue by wbinnssmith** [webpack/webpack#727]
First off, thanks for webpack. It's great.

Require.js seems to be able to require a path relative to a named module being defined. This is nicely illustrated by a test case:

```js
it("should define and require a local module that is relative", function () {
  define("my-dir/my-module3", [], function() {
    return 1234;
  });
  define("my-dir/my-other-dir/my-module4", [], function() {
    return 2345;
  });
  define("my-dir/my-other-dir/my-module5", ["./my-module4", "../my-module3"], function(myModule4, myModule3) {
    myModule3.should.be.eql(1234);
    myModule4.should.be.eql(2345);
    return 3456;
  });
  require("my-dir/my-other-dir/my-module5").should.be.eql(3456);
})
``` 

Though this seems not to be best practice, even for AMD, I'm wondering if this should be considered as functionality for local named amd module resolution in webpack. I'm actually working with a large library that distributes itself as a series of named modules with deeply nested paths.

Thanks for your insight!

**Comment by sokra** [comment]
Yeah, theoretically this can be support, but is not implemented. The resolution happens on compile time so this doesn't cause runtime overhead.

Doesn't look too complex...
