### ISSUE TITLE
Regular Expression Denial of Service  

### ISSUE THREAD

**Issue by TimeBandit** [webpack/webpack#7271]
![webpack 2 screenshot from 2018-05-10 16-37-39](https://user-images.githubusercontent.com/2059850/39878783-1b9dfd6c-5471-11e8-8743-43f1e17e9ddf.png)
![webpack screenshot from 2018-05-10 16-35-24](https://user-images.githubusercontent.com/2059850/39878784-1bb9259c-5471-11e8-95ec-054ae4387849.png)

# Bug report

**What is the current behavior?**
running `npm audit` with the latest webpack `"webpack": "^4.7.0"` flags up two security issues marked as `HIGH`

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  4.7.0
Node.js version:  8.6.0
Operating System:  ununtu 16.04 LTS
Additional tools:

**Comment by evilebottnawi** [comment]
@TimeBandit please update you lock, also issue don't related to webpack, please create issue in chokidar if you have their after update. Also before create issue please looks on `path` where problem places. We can't control all repositories. Thanks!

**Comment by TimeBandit** [comment]
Yes i am aware of the path, that is why I posted the screenshot, but as latest version of webpack relies on this doesn't it make sense to at least add an advisory sentence in the webpack release notes asking devs to install the latest version of `sshpk` separate before installing webpack etc etc

**Comment by evilebottnawi** [comment]
@TimeBandit We can't do this because at any time other packages may be mark as vulnerable. Better solution is create issue about security problem in each package. Also `webpack` packages don't uses in 99% in production code and in theory it is not important security problem.

**Comment by TimeBandit** [comment]
Great, that is clear, I have raised a PR against one of the dependencies; PRs for both can be found at [tough-cookie](https://github.com/salesforce/tough-cookie/issues/112) and [node-http-signature](https://github.com/joyent/node-http-signature/issues/70) thanks and have a nice day :+1:

**Comment by evilebottnawi** [comment]
@TimeBandit joynet looks as abadoned, not sure what https://github.com/joyent/node-http-signature/issues/70 will fix it one day
