### ISSUE TITLE
please deploy webpack-3 branch with latest fixes

### ISSUE THREAD

**Issue by justinhelmer** [webpack/webpack#7273]
# Bug report

**What is the current behavior?**

`hot.accept` breaks with used in conjunction with `webpack.definePlugin`

I am not getting any traction on https://github.com/webpack/webpack/pull/7083. I think it might just be because the code has been merged and the webpack bot set labels for the PR and the parent issue https://github.com/webpack/webpack/issues/6919 such that its falling off the map.

**What is the expected behavior?**

PR has been merged to `webpack-3` branch; the code just needs to get published so our projects can consume it.

**Comment by evilebottnawi** [comment]
@justinhelmer Done in https://github.com/webpack/webpack/releases/tag/v3.12.0
