### ISSUE TITLE
How to use webpack in server

### ISSUE THREAD

**Issue by thepian** [webpack/webpack#728]
I'm making a webpack plugin for the Socketstream server. It is run with one or more client view definitions. For each a single JS bundle is created. At dev time they are kept up-to-date and served from memory. In production they are saved to disk.

Should I make one webpack instance per client, or a single common one?

I had the idea that I could create a webpack compiler instance without an entry point specified and with a MemoryFileSystem as the output fs, and then call compiler.run each time I need to generate a client view JS bundle to serve. I do not see any way to specify the entry point when calling compiler.run, so I assume this is not a supported use case.

**Comment by jhnns** [comment]
If both clients are completely separate, you should separate the webpack bundles too. If both contain common modules and the user is likely to switch from one to the other, it would make sense to use a common webpack bundle to benefit from caching.

**Comment by thepian** [comment]
Is there a good example of how to output to an in-memory buffer? I've tried to emulate how other projects have done it, but I seem to get path errors rather than results.

**Comment by sokra** [comment]
The webpack-dev-middleware does this: https://github.com/webpack/webpack-dev-middleware/blob/master/middleware.js#L18

* set `outputFileSystem` to a memory-fs instance
* set `options.output.path` to `"/"`

**Comment by bebraw** [comment]
@thepian Did you figure this out?

**Comment by thepian** [comment]
Not as I recall, I tried what sokra suggested and it didn't work for me.

https://github.com/thepian/ss-build/blob/master/lib/webpack/index.js

**Comment by bebraw** [comment]
@thepian Any update?
