### ISSUE TITLE
[WIP] - investigation - fail doesn't process exit 1 all the time

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#7281]
`bail: true` was set on a webpack 4 build, and not _everytime_ was the process not  exiting completely

![screen shot 2018-05-11 at 2 52 51 pm](https://user-images.githubusercontent.com/3408176/39948494-17ea8054-552b-11e8-8bcb-72f3b9303f83.png)

You can checkout https://github.com/thelarkinn/webpack-workshop-2018

**Comment by TheLarkInn** [comment]
branch feature/0502-not-so-dynamic-code-splitting

**Comment by cokencode** [comment]
@TheLarkInn `webpack-dev-middleware` occurs this issue. In `webpack-dev-middleware`, callback for compiler does not fail process exit 1 with an error.
https://github.com/webpack/webpack-dev-middleware/blob/27b6c1af28487263d30888751982b979ff267941/index.js#L50-L56
https://github.com/webpack/webpack-dev-middleware/blob/27b6c1af28487263d30888751982b979ff267941/lib/context.js#L81-L87

**Comment by evilebottnawi** [comment]
I think we can close it, if you faced with this issue again feel free to open a new issue with reproducible test repo/configurations/screenshots/videos
