### ISSUE TITLE
Guys! I do not understand how at the current moment you can use the webpack

### ISSUE THREAD

**Issue by isopen** [webpack/webpack#7285]
# Bug report
```
create-react-app my-app
npm install webpack
+ webpack@4.8.3
added 64 packages from 29 contributors, removed 1 package, updated 5 packages and moved 20 packages in 43.137s
[!] 4 vulnerabilities found [17962 packages audited]
    Severity: 4 low
    Run `npm audit` for more detail
```
![image](https://user-images.githubusercontent.com/7373292/39963528-dcb6b6d8-5697-11e8-8c47-98858bb29abf.png)

**What is the current behavior?**
Everything as before. From Yarn you need to leave. Npm followed my common sense and I like it.

**If the current behavior is a bug, please provide the steps to reproduce.**
All errors are presented above. Earlier I asked to fix this. Please remove this deep-extend. If it is important, then write your own.
I do not understand how much shamelessness is needed to surrender projects using this.

**What is the expected behavior?**
Adherence to common sense

**Other relevant information:**
webpack version:  <= 4.8.3
Node.js version: 8.9.4
Operating System: debian 9.3
Additional tools: npm audit

**Comment by aweary** [comment]
The issue you reported in the Webpack repo is related to react-scripts, a package thats used by create-react-app. Somebody already reported the issue here: https://github.com/facebook/create-react-app/issues/4446

This repo is used only for bug reports and feature requests for React itself.

**Comment by isopen** [comment]
The fact is that I have already started to update the project to new dependencies. You can say that everything is cool, as necessary, and lowered his fingers. But this is complete ... :)

**Comment by mohsen1** [comment]
This is where this is stuck: https://github.com/dominictarr/rc/pull/103

**Comment by isopen** [comment]
I completely agree with this, but it's a complete thrash. At the moment, this is all a good solution for landings where such things are not particularly monitored. Translation into native javascript is good, but at the same time you need to control dependencies, and not take everything in a row. But the result for this reason, for some reason, is at the level of the user of the collectors etc. Therefore only for landings it fits well. This is an opinion from practice.
