### ISSUE TITLE
Prefer .js files over .wasm files

### ISSUE THREAD

**Issue by yishn** [webpack/webpack#7287]
# Bug report

**What is the current behavior?**

Assume we have a `.js` file and a `.wasm` file with the same file name in the same directory. When importing the file (without file extension), webpack will prefer the `wasm` file over the `js` file.

**If the current behavior is a bug, please provide the steps to reproduce.**

Provide an `a.js` file and an `a.wasm` file in the same directory with `index.js`:

~~~js
require('./a')
~~~

Inspecting the webpack output bundle yields that webpack tries to bundle `a.wasm` instead of `a.js`.

**What is the expected behavior?**

Webpack should prefer the `.js` file over the `.wasm` file for compatibility.

**Other relevant information:**
webpack version:  4.8.3
Node.js version: 8.9.1
Operating System: Windows 10
Additional tools: -

**Comment by ooflorent** [comment]
There are multiple ways to solve this:

1. This is my favorite solution: always specify the extension
2. Override `resolve.extensions` in you configuration to specify your favorite order
