### ISSUE TITLE
nodejs __dirname and __filename invalid separator for cross platform 

### ISSUE THREAD

**Issue by no-more** [webpack/webpack#7288]
# Bug report

**What is the current behavior?**
I run webpack on windows to compile a nodejs application with `__dirname` and `__filename` set to `true` in my config.
The polyfill replace the dynamic behavior with a static string of the original path, but the issue is that I as the compilation is done on windows, the path contains windows separators. But then I'm running the package on a linux platform. The issue is on the separator, `path.sep` does not work neither most of `path` functions.

**If the current behavior is a bug, please provide the steps to reproduce.**
Compile a nodejs project on windows, but run it on linux. (set `__dirname: true` and `__filename: true` in webpack config file)
Use `__dirname`, `__filename` and `path` in the project

**What is the expected behavior?**
Make the string dynamic according to the running OS in order to be runnable accross multiple platforms.
Or add an option to specify target OS or at least file separator to be used.

**Other relevant information:**
webpack version:   4.2.0
Node.js version: 8.9.4
Operating System: Windows/linux
Additional tools:

**Comment by no-more** [comment]
Hello,

I'm still looking for a clean solution, without success till now.
Compiled code with webpack should be able to run on any platform, even if it was not build on the same OS.

Please help.
Thanks.

**Comment by no-more** [comment]
Issue still active, needs someone to look at it.

Thanks

**Comment by evilebottnawi** [comment]
@no-more what is problem? It is impossible detect __dirname and __filename in browser

**Comment by evilebottnawi** [comment]
Please provide minimum reproducible test repo, hard to understand what you want

**Comment by no-more** [comment]
Hello,

The issue is not in the browser, but when using on nodejs

I have a server application written in typescript. I'm using webpack to compile it for nodejs.
But my dev platform is running windows while my server is running linux.

In this specific case file separator management/detection seems to be fixed to the environment where webpack was run (in this case windows)

**Comment by evilebottnawi** [comment]
@no-more please create minimum reproducible test repo

**Comment by no-more** [comment]
Hello,

Sorry, I'm stuck at the moment, I'll try to find some time to create a sample project, but it cannot be hosted as it requires to be run on the device and zip/archive files are usually not accepted here.
What would be the best way to send you the project ?

**Comment by evilebottnawi** [comment]
Create git repo
