### ISSUE TITLE
Scheduled small breaking changes for 2.0

### ISSUE THREAD

**Issue by sokra** [webpack/webpack#729]
* [x] `-d` now uses `eval-source-map` instead of `source-map`
* [x] loader regExp compares to `resourcePath` instead of `resource`
* [x] Remove compatibly mode for `node.Buffer`
* [x] Remove `loaderContext.minimize` from `UglifyJsPlugin` (all loaders delegate to minimize hook offered by plugins)
* [x] All plugins take only `options` objects as parameters
* [x] remove `resolveLoader.moduleTemplates`
* [x] disable full dynamic require by default (`require(expr)`)
* [x] remove `(...)` from `DefinePlugin`.
* [x] report exit code on Errors
* [x] OccurrenceOrderPlugin by default

**Comment by jhnns** [comment]
Thx :+1:

**Comment by sirlancelot** [comment]
:+1: for "loader regExp compares to resourcePath instead of resource"
