### ISSUE TITLE
set css-loader in webpack.config.js, but not work

### ISSUE THREAD

**Issue by sqw2016** [webpack/webpack#7293]
I require two simple css file in my main.js
![image](https://user-images.githubusercontent.com/24272627/39977425-762dce12-576c-11e8-90c7-929db5359f42.png)
and i set it in webpack.config.js
![image](https://user-images.githubusercontent.com/24272627/39977481-cebf4dc6-576c-11e8-9157-695497aa21cb.png)
when i build,got a error:
ERROR in ./src/css/test.css
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .test {
|     color: red;
| }
 @ ./src/js/main.js 4:0-26

what`s wrong with my code or it`s a bug of webpack? Thank you for your help!

**Comment by michael-ciniawsky** [comment]
=> No `'`

```diff
- test: '/\.css$/'
+ test: /\.css$/
```

A `{RegExp}` isn't a `{String}` :)

**Comment by sqw2016** [comment]
@michael-ciniawsky Thank you very much! I`m too stupid.

**Comment by zoltanka** [comment]
With the following webpack config I still got the same error message.

![image](https://user-images.githubusercontent.com/15962063/41798369-b20d25b6-766d-11e8-90e9-db60dd17c443.png)

```
ERROR in ./src/style.css 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> .hallo {
|     color: red;
| }
 @ ./src/index.js 2:0-21
```
