### ISSUE TITLE
ImportDeclaration should appear when the mode is ES6 and in the module context

### ISSUE THREAD

**Issue by arunprakashpj** [webpack/webpack#7294]
ESLint Version: 3.19.0
Node Version:8.9.1
npm Version: >=5.0.0

"babel-eslint": "7.2.2",

The eslint was fine until I upgraded the web pack version from 1.x to 4.x
Currently, my web pack version is 4.8.

```
   "@babel/cli": "^7.0.0-beta.46",
    "@babel/core": "^7.0.0-beta.46",
    "@babel/preset-react": "^7.0.0-beta.46",
    "@babel/register": "^7.0.0-beta.46",
    "babel-eslint": "7.2.2",
    "babel-loader": "^7.1.4",
    "sass-loader": "^7.0.1",
    "webpack": "^4.8.1",
```

I am getting the following error when i run eslint .

> ImportDeclaration should appear when the mode is ES6 and in the module context.
AssertionError [ERR_ASSERTION]: ImportDeclaration should appear when the mode is ES6 and in the module context.

The webpack 4 upgrade has triggered this particular error i believe.

**Comment by evilebottnawi** [comment]
@arunprakashpj you have invalid `eslint` configuration, please read docs how linting `import`, also you should use `babel-eslint` for better support async `import`. Thanks!

**Comment by arunprakashpj** [comment]
@evilebottnawi I am using babel-eslint of version 7.2.2 . My question is , will the webpack upgrade as any relation with this particular error ?

**Comment by evilebottnawi** [comment]
@arunprakashpj I don't understand you, how `webpack` related to `eslint` errors?

**Comment by arunprakashpj** [comment]
I raised the concern with [eslint repo ](https://github.com/eslint/eslint/issues/10349) as well . Webpack upgrade has some dependency upgrade in my package json  which leads to this issue. I made webpack version changes / webpack dependency upgrade changes with package json alone . No other changes were done so i suspect if this webpack upgrade has something to do with my issue . (I believe yes)

**Comment by jakebolam** [comment]
I bumped `eslint` to v > 4 and it fixed it, I also needed to bump `babel-eslint` to a version greater than 8.1.1 (https://github.com/eslint/eslint/issues/9767)
