### ISSUE TITLE
splitChunks can create initial chunks that are empty after CSS extraction

### ISSUE THREAD

**Issue by edmorley** [webpack/webpack#7300]
# Bug report

**What is the current behavior?**

The `splitChunks` feature (using `chunks: 'all'`) doesn't take into account CSS extraction (via `mini-css-extract-plugin`) when deciding whether to create a new inital chunk. A new chunk can end up being created that is empty (other than the webpack functions) and under the default 30KB `splitChunks.minSize` threshold so shouldn't have been created.

eg:
[`dist/vendors~pageA~pageB.js`](https://github.com/edmorley/testcase-webpack-splitchunks-css/blob/master/dist/vendors%7EpageA%7EpageB.js)

For webpack build log output see:
https://github.com/edmorley/testcase-webpack-splitchunks-css#actual

**If the current behavior is a bug, please provide the steps to reproduce.**

1. `git clone https://github.com/edmorley/testcase-webpack-splitchunks-css.git`
2. `yarn install`
3. `yarn build`

**What is the expected behavior?**

There is no `dist/vendors~pageA~pageB.js` chunk generated, since after the CSS is extracted, there should be no common JS code between the two pages.

**Other relevant information:**
webpack version:  4.8.3
Node.js version: 10.1.0
Operating System: Windows 10
Additional tools: mini-css-extract-plugin@0.4.0

**Comment by evilebottnawi** [comment]
@edmorley Maybe related https://github.com/webpack-contrib/mini-css-extract-plugin/issues/85?

**Comment by sokra** [comment]
Yep that's true

**Comment by jpdesigndev** [comment]
@sokra Is there any workaround for this issue you can think of? I'm simply trying to split out all vendor css, but this is creating an "empty" (`(window.webpackJsonp=window.webpackJsonp||[]).push([[0],[]]);`) js file. Any suggestions?

**Comment by azamat-sharapov** [comment]
@jpdesigndev try prepending those files' contents into you main entry manually.

**Comment by louisscruz** [comment]
Any news on this? I think this is the final blocker for our upgrade to Webpack 4.

**Comment by kasperpeulen** [comment]
This is blocking me to upgrade to webpack 4, but it is planned for webpack 5. I guess I will stop trying to upgrade until 5 comes out.

**Comment by evilebottnawi** [comment]
Yes, it is breaking change

**Comment by sokra** [comment]
hmm... maybe there is a way we could add it for webpack 4 too

**Comment by ev1stensberg** [comment]
If this needs help, I'm happy to help out

**Comment by Igloczek** [comment]
Seems like related to https://github.com/webpack-contrib/mini-css-extract-plugin/issues/151

**Comment by danechitoaie** [comment]
Right now I'm using this "workaround":

```
class MiniCssExtractPluginCleanup {
    apply(compiler) {
        compiler.hooks.emit.tapAsync("MiniCssExtractPluginCleanup", (compilation, callback) => {
            Object.keys(compilation.assets)
                .filter(asset => {
                    return ["*/scss/**/*.js", "*/scss/**/*.js.map"].some(pattern => {
                        return minimatch(asset, pattern);
                    });
                })
                .forEach(asset => {
                    delete compilation.assets[asset];
                });

            callback();
        });
    }
}
```
It's very specific for my use case and has things hardcoded and I even have just put it directly in the webpack.config.js file (so not published on npm).

So it would be awesome if this could be fixed at webpack level.

**Comment by maapteh** [comment]
@sokra will this still be fixed in 4? We are migrating to 4 currently and everything works except this "empty" file.

Or wait for 5 with https://webpack.js.org/plugins/css-webpack-plugin/? Awesome work by the way, i only had problems with the optimise part!

**Comment by toastal** [comment]
@danechitoaie 's _workaround_ worked, for me, but it does unnecessary looping, incurs a dependency in `minimatch`, and isn't very flexible as mentioned. I wrote this which passes in a RegExp to be reused for what to delete, and doesn't do extra loops via higher-order functions:

```javascript
class MiniCssExtractPluginCleanup {
  constructor(deleteWhere = /\.js(\.map)?$/) {
    this.shouldDelete = new RegExp(deleteWhere)
  }
  apply(compiler) {
    compiler.hooks.emit.tapAsync("MiniCssExtractPluginCleanup", (compilation, callback) => {
      Object.keys(compilation.assets).forEach((asset) => {
        if (this.shouldDelete.test(asset)) {
          delete compilation.assets[asset]
        }
      })
      callback()
    })
  }
}
```

Which then in their case could be used by passing in the RegExp  
```javascript
module.exports = {
   ...,
   plugins: [
     new MiniCssExtractPluginCleanUp(/scss\/.*\.js(\.map)?$/),
   ],
  ...,
}
```

**Comment by Kajeczko** [comment]
Also remember you can just run console command to delete this files after webpack done his job.
```
// package.json
"scripts": {
    "clean-css": "rm ./build/normalize.bundle.js",
    "build": "webpack --config webpack.dev.js && npm run clean-css",
}
```
Can be useful: [Pre and Post hooks for npm scripting](http://www.marcusoft.net/2015/08/pre-and-post-hooks-for-npm-scripting.html)

**Comment by usebaz** [comment]
@Kajeczko in some cases this file can have code that run webpack. Example:
```
⇒  cat build/_js/route.styles.js 
(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["styles"],[]]);
```

**Comment by usebaz** [comment]
@Dwood15 without this code, webpack modules are not started on the client

**Comment by timurgarif** [comment]
@Dwood15 @usebaz
I thought the code in styles.js exports all the names generated by css-modules. 
```
import styles from 'some.css'
...
<div className={styles.myClass} />
```
If you don't use auto generated css class names (e.g using css-modules), then probably you don't need this file.

**Comment by thaoms** [comment]
Any news on this? Removing the file is not an option, without including it the entry js doesn't run and fails silently.

**Comment by gkostov** [comment]
And my solution happened to be to drop `mini-css-extract-plugin` and revert to `extract-text-webpack-plugin` but just upgrade it to "^4.0.0-beta.0". Now there are no empty files and no strange "conflicts" ( webpack-contrib/mini-css-extract-plugin#151 ) - all back to normal!

**Comment by thasmo** [comment]
@sokra :wave: Has there been a decision about fixing this for webpack 4? Thanks!

**Comment by rowanoulton** [comment]
Is #9040 the fix for this?

**Comment by thasmo** [comment]
@rowanoulton, thanks for mentioning me. Does someone know if this will/can be backported to v4?

**Comment by jimblue** [comment]
> @rowanoulton, thanks for mentioning me. Does someone know if this will/can be backported to v4?

agreeeeeeee!! that would ne awesome!

**Comment by evilebottnawi** [comment]
It is breaking change, maybe we can implement this behavior under option
/cc @sokra

**Comment by unstoppablecarl** [comment]
Looking for a solution to this. I have documented my case here https://github.com/unstoppablecarl/vue-webpack-css-bug

**Comment by wintercounter** [comment]
For me the temp solution was to `html-webpack-inline-source-plugin` to inline these empty chunks, still better than having 2 extra requests for nothing.

I have files generated like this:
```
chunk0
(window.webpackJsonp=window.webpackJsonp||[]).push([[0],{464:function(n,o,c){},465:function(n,o,c){},466:function(n,o,c){},467:function(n,o,c){},553:function(n,o,c){},554:function(n,o,c){},558:function(n,o,c){},565:function(n,o,c){},566:function(n,o,c){},570:function(n,o,c){},571:function(n,o,c){},581:function(n,o,c){},582:function(n,o,c){},601:function(n,o,c){},605:function(n,o,c){},606:function(n,o,c){},651:function(n,o,c){},657:function(n,o,c){},658:function(n,o,c){},659:function(n,o,c){},660:function(n,o,c){},664:function(n,o,c){},665:function(n,o,c){},669:function(n,o,c){},673:function(n,o,c){},677:function(n,o,c){},681:function(n,o,c){},685:function(n,o,c){},689:function(n,o,c){},693:function(n,o,c){},697:function(n,o,c){},701:function(n,o,c){},702:function(n,o,c){},706:function(n,o,c){},710:function(n,o,c){},714:function(n,o,c){},715:function(n,o,c){},718:function(n,o,c){},722:function(n,o,c){},729:function(n,o,c){},742:function(n,o,c){},743:function(n,o,c){},744:function(n,o,c){},745:function(n,o,c){},746:function(n,o,c){},748:function(n,o,c){},749:function(n,o,c){},750:function(n,o,c){},751:function(n,o,c){},752:function(n,o,c){},753:function(n,o,c){},754:function(n,o,c){},755:function(n,o,c){},756:function(n,o,c){},757:function(n,o,c){},758:function(n,o,c){},759:function(n,o,c){},760:function(n,o,c){},761:function(n,o,c){},762:function(n,o,c){},763:function(n,o,c){},764:function(n,o,c){},765:function(n,o,c){},766:function(n,o,c){},767:function(n,o,c){},768:function(n,o,c){},769:function(n,o,c){},770:function(n,o,c){},771:function(n,o,c){},772:function(n,o,c){},773:function(n,o,c){},774:function(n,o,c){},775:function(n,o,c){},776:function(n,o,c){},777:function(n,o,c){},778:function(n,o,c){},779:function(n,o,c){},780:function(n,o,c){},781:function(n,o,c){},782:function(n,o,c){},789:function(n,o,c){},790:function(n,o,c){},791:function(n,o,c){}}]);
```

```
chunk1
(window.webpackJsonp=window.webpackJsonp||[]).push([[1],[],[[797,3,0,6,4,7,9,8,5,2]]]);
```

**Comment by evilebottnawi** [comment]
Partial solved in webpack@5:
```js
{
  optimization: {
    splitChunks: {
      cacheGroups: {
        styles: {
          type: 'css/mini-extract',
          chunks: 'all',
          // If you need this uncomment
          // enforce: true,
        },
      },
    },
  },
}
```

**Comment by evilebottnawi** [comment]
https://github.com/webpack/webpack/pull/11585 should fix it, I will put couple tests in mini-css-extract-plugin to ensure all works fine

**Comment by evilebottnawi** [comment]
Done https://github.com/webpack-contrib/mini-css-extract-plugin/pull/599 :star:

**Comment by martinherweg** [comment]
@evilebottnawi I've tried with the following packages
webpack: 5.0.0
mini-css-extract-plugin: 1.0.0
css-loader: 4.3.0

and this config
```
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = () => {
  return {
    entry: {
      test: './src/test.css',
    },
    mode: 'production',
    optimization: {
      removeEmptyChunks: true,
      splitChunks: {
        cacheGroups: {
          styles: {
            type: 'css/mini-extract',
            chunks: 'all',
          },
        },
      },
    },
    module: {
      rules: [
        {
          test: /\.css$/i,
          use: [
            {
              loader: MiniCssExtractPlugin.loader,
              options: {
                esModules: false,
              },
            },
            {
              loader: 'css-loader',
            },
          ],
        },
      ],
    },
    plugins: [new MiniCssExtractPlugin()],
  };
};
```

but it still outputs a `dist/test.css` and `dist/test.js` with the latter being empty, any hint what might be wrong here?

**Comment by evilebottnawi** [comment]
@martinherweg Please create reproducible test repo, I think you still on old webpack

**Comment by martinherweg** [comment]
@evilebottnawi https://github.com/martinherweg/webpack-css-chunks here I've created a very small test repo.

**Comment by evilebottnawi** [comment]
@martinherweg to be honestly it is not related to this issue, we create empty js because you need js entrypoint, but because you don't have js it is just empty, it's a bit like this problem, but it's a different problem, can you open a new issue about this?

**Comment by martinherweg** [comment]
@evilebottnawi just to confirm my understanding. For which cases is your fix where it doesn't generate an empty JS file?

I've added an additional entry point with a JS file, still it generates an empty JS file for the CSS only entry.

I understand it's not related to that issue, I just read various threads about this and read your comment here that it's fixed.

Do you think it's webpack or mini-css-extract-plugin related?

Thanks.

**Comment by evilebottnawi** [comment]
@martinherweg 

> @evilebottnawi just to confirm my understanding. For which cases is your fix where it doesn't generate an empty JS file?

For all cases, except non js entry points

> Do you think it's webpack or mini-css-extract-plugin related?

webpack

**Comment by Gnodesign** [comment]
So there still isn't a fix for this?

**Comment by alexander-akait** [comment]
Partial fixed

**Comment by MichaelDurfey** [comment]
I created a plugin to fix this for us and hold us over until webpack 5. Works fine after the webpack 5 upgrade, but this plugin did the job until then: https://github.com/michaeldurfey/fix-style-emits-webpack-plugin Just concats the empty js files onto the main entrypoint js.

**Comment by meglio** [comment]
Still not fixed for me when using webpack 5:

```
cacheGroups: {
                    styles: {
                        name: 'styles',
                        test: /\.(sa|sc|c)ss$/,
                        //type: 'css/mini-extract',
                        chunks: 'all',
                        enforce: true,
                        minSize: 0,
                        minChunks: 1,
                        priority: 20
                    },
                    vendor: {
                        test: /node_modules/,
                        chunks: "initial",
                        name: "vendor",
                        priority: 10,
                        enforce: true
                    },
                    commons: {
                        chunks: "initial",
                        name: "commons",
                        minChunks: 1,
                        enforce: true,
                        maxInitialRequests: 4,
                        minSize: 0
                    },
                }
}
```
Produces the following js file:

<img width="379" alt="image" src="https://user-images.githubusercontent.com/282177/113572424-55c18880-9657-11eb-8c83-814fd00a1391.png">

**Comment by alexander-akait** [comment]
@meglio Not all chunks can be dropped, please create reproducible test repo, I will look

**Comment by meglio** [comment]
@alexander-akait , I've been playing with various options and made the following discoverty:

Using `test: /\.(sa|sc|c)ss$/` in the chunk configuration does emit the `js` file besides the `css` file.

Removing that and using `type: 'css/mini-extract'` instead stops emitting the `js` file and only emits the `css` file.

Does this make any sense, and is there an explanation of this behaviour?

**Comment by alexander-akait** [comment]
@meglio 

> Does this make any sense, and is there an explanation of this behaviour?

`type` was implement for this, `test` doesn't know which modules should be dropped, it is right solution, can you help update docs?

**Comment by meglio** [comment]
Is there any way to contribute to docs without running a full local developer copy of the webpack website?

**Comment by alexander-akait** [comment]
You can send improve here https://github.com/webpack-contrib/mini-css-extract-plugin

**Comment by meglio** [comment]
Do you suggest adding a note in [this section](https://github.com/webpack-contrib/mini-css-extract-plugin#extracting-all-css-in-a-single-file)?

**Comment by rvramesh** [comment]
Hi, I am still seeing an empty js file in my setup. The issue can be seen in https://github.com/rvramesh/empty-js-webpack-repo 

Steps

1. Clone the repo
2. execute `npm run build`
3. In the dist folder we see main.js which is empty and I don't expect the file to be there.

Please let me know if I am missing something.

**Comment by phil-lgr** [comment]
Thanks @toastal for your minimal plugin, it does the job!

**Comment by alexanderadam** [comment]
> @alexander-akait , I've been playing with various options and made the following discovery:
> 
> Using `test: /\.(sa|sc|c)ss$/` in the chunk configuration does emit the `js` file besides the `css` file.
> 
> Removing that and using `type: 'css/mini-extract'` instead stops emitting the `js` file and only emits the `css` file.

In my case I'm running out of memory if I remove the test entry:

```
[116765:0x613fc70]    18299 ms: Mark-sweep (reduce) 4086.4 (4109.8) -> 4086.2 (4103.0) MB, 5.5 / 0.0 ms  (+ 39.2 ms in 1 steps since start of marking, biggest step 39.2 ms, walltime since start of marking 57 ms) (average mu = 0.947, current mu = 0.814) al[116765:0x613fc70]    18482 ms: Mark-sweep (reduce) 4099.7 (4115.8) -> 4099.0 (4115.8) MB, 49.8 / 0.0 ms  (average mu = 0.901, current mu = 0.728) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb95be0 node::Abort() [webpack]
 2: 0xa9a7f8  [webpack]
 3: 0xd6f5b0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [webpack]
 4: 0xd6f957 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [webpack]
 5: 0xf4ceb5  [webpack]
 6: 0xf5f38d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [webpack]
 7: 0xf39a7e v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [webpack]
 8: 0xf3ae47 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [webpack]
 9: 0xf1c04a v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [webpack]
10: 0x12e139f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [webpack]
11: 0x170e079  [webpack]
error Command failed with signal "SIGABRT".
```

**Comment by alexander-akait** [comment]
Can you profile your memory and look where is a problem?
