### ISSUE TITLE
Need update docs: Dynamic import doesn't work as shown in the docs

### ISSUE THREAD

**Issue by TienDo1011** [webpack/webpack#7302]
# Bug report

**What is the current behavior?**
As shown in the [documentation](https://webpack.js.org/guides/code-splitting/#dynamic-imports) about dynamic imports, we should get lodash from `import(/* webpackChunkName: "lodash" */ 'lodash').then(_ => doSomething());` but instead the lodash value is wrapped inside a namespace with default property.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
The docs should show that we need to access _ via `namespace.default`

**Other relevant information:**
webpack version:  4.8.3
Node.js version: 8.9.4
Operating System: Mac OS X
Additional tools:

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack.js.org
