### ISSUE TITLE
What would it take to create multiple types of bundles for production and serve those based on browser support?

### ISSUE THREAD

**Issue by wintercounter** [webpack/webpack#7308]
I don't really know what this would exactly take, but I'm sure it would involve multiple projects across the eco-system to achieve this seamlessly (webpack, babel, babel-preset-env, etc). Currently you always have to transpile code to support older browsers and you need to serve that to modern browsers as well.

What if Webpack would create transpiled, semi transpiled (async/await/generators, class properties, decorators, etc) and native (almost) bundles then Webpack's bootstrap can decide which one to load. This would have both performance benefits both execution speed/size wise.

Why I think this is related to Webpack too is because it's bootstrap code, imo decision should be made as low level as possible.

I really couldn't find any effort trying to do this, but please point this discussion to the right direction/project there's such.

I've found few people doing multiple bundles on their own manually to solve this, but I feel like there would be space for a more painless/configless/out of the box solution.

**Comment by ooflorent** [comment]
You should have a look at the [HNPWA](https://hnpwa.com) project. Some demos use webpack and per-browser builds.

**Comment by wintercounter** [comment]
I see. They are making many efforts to make it work and you always have to update separate Webpack configs manually.
I've checked: https://github.com/kristoferbaxter/preact-hn
All the configs: https://github.com/kristoferbaxter/preact-hn/tree/master/config
The code determining the correct environment: https://github.com/kristoferbaxter/preact-hn/blob/master/src/server/resources.ts

Basically this is what should be prevented somehow.

**Comment by TheLarkInn** [comment]
The problem is that if you are to create this from a single build, you then have to code-split (async lazy load) your vendor specific code up front, which can incur a load-time hit.

**Comment by wintercounter** [comment]
I think that would be a hit I'd take rather than adjusting multiple bundles each time a new browser version coming out. Transpiled/polyffiled codes may cost much more in performance and load time than the hit taken from async loading. Not to mention the size differences. Most people also wouldn't care setting these things up manually, they would serve transpiled code always and done which I consider pretty harmful, but if there would be an out-of-box solution nobody would hesitate on using it imo.

**Comment by lili21** [comment]
https://philipwalton.com/articles/deploying-es2015-code-in-production-today/
