### ISSUE TITLE
Bundles and Conditional Externals

### ISSUE THREAD

**Issue by jonjaques** [webpack/webpack#731]
Hello, 

I currently have a use case where I'm outputting multiple bundles based on the same code base, but I want to conditionally externalize modules depending on which bundle.

I believe the function form of externals is what I want, however the information passed isn't enough to determine the *right* context.

```javascript
entry: {
  'app': ['./src/app/index'],
  'legacy': ['./src/legacy/index']  // legacy calls into /src/app and /src/components
},

externals: [               // would like something like this passed too??
  function(context, request, bundleName, callback) {
    if (bundleName === 'legacy' && request === 'jquery') {
      callback(null, 'var jQuery');
    }
    callback();
  }
]
```

So the result would be `app` bundle would use npm's jQuery, and `legacy` would use `window.jQuery`, as this bundle runs in a different environment.

Is this possible through another method?

**Comment by sokra** [comment]
modules are independent of entry points... you need to use multiple configs to do that:

``` js
[
  {
    entry: { app: ['./src/app/index'] }
  },
  {
    entry: { app: ['./src/app/index'] },
    externals: { jquery: "var jQuery" }
  }
]
```

**Comment by jonjaques** [comment]
Whoa, so can I export an array as my config?

**Comment by sokra** [comment]
yep

**Comment by jonjaques** [comment]
Saweet. Thanks for your help!
