### ISSUE TITLE
Ability to Disable the ModuleConcatenationPlugin in Production Mode

### ISSUE THREAD

**Issue by Silvenga** [webpack/webpack#7312]
## Feature request

Consider the following:

This feature request is around the `production` option in the `mode` flag. According to the docs, the production mode modifies the following:

```
Provides process.env.NODE_ENV with value production. 
Enables:
 FlagDependencyUsagePlugin, 
 FlagIncludedChunksPlugin, 
 ModuleConcatenationPlugin, 
 NoEmitOnErrorsPlugin, 
 OccurrenceOrderPlugin, 
 SideEffectsFlagPlugin,
 UglifyJsPlugin
```

**What is the expected behavior?**

We, as developers, should use the defaults when possible. When using the defaults are not possible, we should be able to explicitly reproduce the defaults (which we can then modify if needed). 

Currently, the production mode flag modifies configuration options that cannot be reproduced, as it uses undocumented plugins. For example, `FlagDependencyUsagePlugin` is not documented or included in the Webpack typings.

**What is motivation or use case for adding/changing the behavior?**

Some libraries, notably the `aurelia-dialog` breaks when the `ModuleConcatenationPlugin` is active (https://github.com/aurelia/dialog/issues/298). I would expect an easy way to disable this plugin in webpack.

**How should this be implemented in your opinion?**

I have a couple of suggestions:

1. All modifications by the mode flag should be reproducible when set to `none`.
2. The mode flag is kept as is, but another option is added to selectively disable the modifications that this flag makes.
3. A function that is called at the end of the configuration stage (I have no idea how webpack works internally, this is just my assumption) that allows final modifications to the configurations before the processing pipeline.

**Are you willing to work on this yourself?**

I could, but I'm not a JS developer.

**Comment by sokra** [comment]
1. Yes. It's implemented that way.
2. See optimization config option.

**Comment by Silvenga** [comment]
Oh crap, completely missed that. Do you know where the documentation is? 

https://webpack.js.org/configuration/optimization/ is where I would assume it would be.

**Comment by ooflorent** [comment]
The documentation isn’t complete. You could take a look at the option schema to discover the available options: https://github.com/webpack/webpack/blob/master/schemas/WebpackOptions.json#L1285
