### ISSUE TITLE
this._eventBus.asObservable().filter not working

### ISSUE THREAD

**Issue by isopen** [webpack/webpack#7316]
# Bug report

With the help of a standard project collector, everything works out correctly.
Next, I tried to compile via webpack.

**What is the current behavior?**

This stopped working correctly. Can not find a method.
```
return this._eventBus.asObservable()
          .filter(function (event) {
            return event.key === key;
          })
          .map(function (event) {
            return event.data;
          });
```

**If the current behavior is a bug, please provide the steps to reproduce.**
You can play this in the soc or ngx-cable project from my repository.
npm install
npm start

**What is the expected behavior?**
The method exists
I looked for a solution in a repository, but it was in such an abstraction that I did not find anything :(

**Other relevant information:**
webpack version:  4.8.3
Node.js version: 8.9.4
Operating System: debian 9.3

Regards

**Comment by montogeek** [comment]
This is now a webpack bug, it is a bug in your code.

**Comment by isopen** [comment]
Interesting.
Through `ng serve` it starts correctly and work.
I can give you some examples of where this solution is used.
So. What exactly is wrong with this code?
