### ISSUE TITLE
typeof+module.exports

### ISSUE THREAD

**Issue by wusfen** [webpack/webpack#7318]
# Bug report

**What is the current behavior?**
```
Cannot assign to read only property 'exports' of object '#<Object>'
```

**If the current behavior is a bug, please provide the steps to reproduce.**
```javascfiprt
//a.js
typeof 1 // <-------------********
module.exports = 2


//b.js
var a = require('./a.js')
```

**What is the expected behavior?**
期望能正常运行

**Other relevant information:**
webpack version:  3.12.0
Node.js version: v8.11.1
Operating System: windows
Additional tools:

**Comment by sokra** [comment]
`Cannot assign to read only property 'exports' of object '#<Object>'`

This message occurs when trying to use `module.exports` in a ESM module (containing `import`).

**Comment by wusfen** [comment]
sorry, I write more details

**Comment by wusfen** [comment]
if you remove the line with 'typeof', it can run
