### ISSUE TITLE
SideEffectsFlagPlugin does not resolve the right descriptionFileData in nested packags

### ISSUE THREAD

**Issue by shlomiassaf** [webpack/webpack#7327]
I'm not sure it's `SideEffectsFlagPlugin`, the data is resolved else where where but I found it there.

Consider 1 npm package with internal packages.
  - **`@scope/root`**
  - **`@scope/root/root-child`**

All of the bundles are set inside dedicated directories so:

## UMD (main)
  - **`@scope/root/bundle/root.js`** 
  - **`@scope/root/bundle/root-child-root.js`**

## FESM5 (module)
  - **`@scope/root/fesm5/root.js`** 
  - **`@scope/root/fesm5/root-child-root.js`**

The `package.json`:
  - **`@scope/root/package.json`** 
  - **`@scope/root/child-root/package.json`**

Each package.json will point to the proper bundles, which means that child package will use
a relative import, e.g for **`@scope/root/child-root`**:
```
  "main": "../bundles/root-child-root.js",
  "module": "../fesm5/root-child-root.js",
```

 for **`@scope/root`**:
```
  "main": "bundles/root.js",
  "module": "fesm5/root.js",
```

Importing `@scope/root` works fine.

Importing `@scope/root/child-root` works, it will import to proper file but when the package.json
data is needed in `SideEffectsFlagPlugin` (to determine sideEffect) it will use the data of **`@scope/root/package.json`** 

What I think happens is that to get the package.json webpack search's for the file on the current dir then goes up until it finds it, in this case its in **`@scope/root/fesm5/`** and goes up to **`@scope/root`**  which is not the right file.

The end result is the the `sideEffect` property set for **`@scope/root/root-child`** is ignored and the one of **`@scope/root`** is used.

**Comment by sokra** [comment]
That's working as intended.

It's not relevant from which package.json you are coming from. For a module that next package.json found in parent folders provides the information. The main/module field is only a redirect.

**Comment by shlomiassaf** [comment]
Well, this works as intended but very confusing.

I guess this might be coming from some sort of spec, but what it says is:

  - Resolving a module is done using **package.json**
  - Resolving **package.json** is done using file-system

The example above is the output of `@angular/cli` library builder using `ng-packgr`.

When this happen it not trivial to debug...
