### ISSUE TITLE
webpack 3 handles json files with BOM while webapack 4 does not

### ISSUE THREAD

**Issue by gatimus** [webpack/webpack#7330]
# Bug report

**What is the current behavior?**
Requiring or importing a json file starting with the zero length, white space character, byte order mark (\ufeff), commonly added by Microsoft editors, in webpack 4 causes the following error:

> Unexpected token ﻿ in JSON at position 0

webpack 3 handles this with out error though.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/gatimus/webpack-json-bom/tree/webpack-4
- clone https://github.com/gatimus/webpack-json-bom
- checkout branch webpack-4
- `npm i`
- `npm start`
> Unexpected token ﻿ in JSON at position 0

**What is the expected behavior?**
https://github.com/gatimus/webpack-json-bom/tree/webpack-3
- clone https://github.com/gatimus/webpack-json-bom
- checkout branch webpack-3
- `npm i`
- `npm start`
no errors

**Other relevant information:**
webpack version: 4.8.3
Node.js version: 8.11.1
Operating System: Win 10

I don't know how webpack 3 handles it but calling `.trim()` or `.replace('\ufeff', '')` on the file contents before passing to `JSON.parse()` would solve.

**Comment by sokra** [comment]
Send a PR

**Comment by gatimus** [comment]
@sokra I'll make a PR, I don't have a full grasp of the source, is [this](https://github.com/webpack/webpack/blob/master/lib/JsonParser.js#L15) the `JSON.parse()` that the json file contents gets passed to?

**Comment by ooflorent** [comment]
Fixed by #7334
