### ISSUE TITLE
Incorrect scoping behavior for default parameter values when using a prior parameter which shadows an import

### ISSUE THREAD

**Issue by queerviolet** [webpack/webpack#7335]
# Bug report

When a default parameter references a prior positional argument that is shadowing an imported name, webpack incorrectly references the import, rather than the prior positional argument.

**If the current behavior is a bug, please provide the steps to reproduce.**

*a.js*
```js
export default 'fail'
```

*index.js*
```js
import x from './a.js'

const sum = (x, y, total=x + y) => total
console.log('2 + 3 =', sum(2, 3))
```

Repro repo: https://github.com/queerviolet/webpack-import-default-param-bug

**What is the expected behavior?**
I'd expect that to print `2 + 3 = 5`. Instead it prints `2 + 3 = fail3`.

The `esm` package for node binds as I'd expect, allowing the positional arg to shadow the import, and printing `2 + 3 = 5`.

The generated code for the function is:
```js
(x, y, total=_a_js__WEBPACK_IMPORTED_MODULE_0__["default"] + y) => total
```

So it's definitely binding to the import.

**Other relevant information:**
webpack version:  3.12.0, 4.0.0, 4.8.3
Node.js version: v10.0.0
Operating System: macOS High Sierra 10.13.4 / Darwin 17.5.0
Additional tools:

**Comment by queerviolet** [comment]
This is so wild to me! I'm the first person to try and webpack code that does this? Even since webpack 3? Do I code funny? 😉

**Comment by sokra** [comment]
default parameters has mean transpiled for a long time and may browser support got good enough to leave it untranspiled...

**Comment by sokra** [comment]
cc @ooflorent
