### ISSUE TITLE
Explicit vendor chunk example does not seem to work as expected

### ISSUE THREAD

**Issue by imjeremyhi** [webpack/webpack#7337]
I'm upgrading to webpack 4 from webpack 3 but have been unable to replicate the described behaviour in: webpack/examples/two-explicit-vendor-chunks/. I was originallly using CommonsChunkPlugin.

I expect that when an explicit vendor bundle is used, entry point bundles no longer need to bundle up the code that is now in the vendor bundle. Is this the case? It doesn't seem evident that this is so since there's no compare and contrast between using the vendor bundle and not.

Below are the relevant config parts for when I have tried to replicate the behaviour for my own project but with no success. I tried to copy the example as closely as possible. And yet my entry points are not smart enough to use the vendor bundle I have specified in the cache group as per the example in the docs. Is this an issue with my config or is there an issue with webpack's behaviour?

```js
    entry: {
        dummypage: ['./src/entry/dummypage'],
        vendor: ['./src/vendor/vendor']
    },
    mode: 'none',
    output: {
        path: path.join(__dirname, 'build'),
        filename: '[name].js',
        chunkFilename: '[name].js',
        publicPath,
        sourceMapFilename: sourcemapOutputFileName,
        crossOriginLoading: 'anonymous',
    },
    resolve: {
        modules: [path.join(__dirname, 'src'), 'node_modules'],
    },
   optimization: {
       splitChunks: {
            cacheGroups: {
                vendor: {
                    name: 'vendor',
                    test: 'vendor',
                    enforce: true,
                }
            }
        }
  },
 ```

**Comment by sokra** [comment]
You need to reference the vendor module in the dummypage. If it's not reference they are not connected because it's not needed.

i. e. `import "./vendor"` in dummypage

**Comment by sokra** [comment]
`chunks: 'initial'` looks good to me
