### ISSUE TITLE
Dynamic require()'s generate records that vary on different machines

### ISSUE THREAD

**Issue by jdelStrother** [webpack/webpack#7339]
# Bug report

**What is the current behavior?**

If you enable recordsPath and use a dynamic require (eg `require("./dependencies/" + dependency)`), the resulting line in your recordsPath file looks like:

```
    "src/dependencies sync ../../../../^/.//.*$": "./src/dependencies sync recursive ^\\.\\/.*$"
```

AFAICT, the number of `../`s corresponds to the depth of your project in your local filesystem (on mine, that file was built from `/Users/jon/Developer/require-test`).

This seems undesirable - it means that if you're version controlling recordsPath and build it on a different machine, a new record will be generated depending on the depth of the project on that other filesystem.

**If the current behavior is a bug, please provide the steps to reproduce.**

Checkout https://github.com/jdelStrother/webpack-require-test, built it.  Move it to a different directory (at a different depth in the filesystem).   Build it, note how webpack-records.json has changed.

**What is the expected behavior?**

The records should be the same regardless of where the project was built from

**Other relevant information:**
webpack version:  4.8.3
Node.js version: 8.4.0
Operating System: OS X 10.13.5
Additional tools:

**Comment by sokra** [comment]
Send a PR to improve

https://github.com/webpack/webpack/blob/6323b173de6ec5d1e8137706cf6ab50dd4fe997b/lib/util/identifier.js#L15

to not match on these regexp things.
