### ISSUE TITLE
Automatic generated require.ensure() wrapper

### ISSUE THREAD

**Issue by cowwoc** [webpack/webpack#734]
Looking at the `require.ensure()` code found at https://github.com/webpack/docs/wiki/code-splitting, is there a tool that will automatically generate a `require.ensure()` wrapper on behalf of the user?

Meaning, given:
```
var a = require("module-a");
var b = require("module-b");
```

the tool would scan for `require()` statements, and generate the following `output.js`:

```
require.ensure(["module-a", "module-b"], function(require) {
    var a = require("module-a");
    var b = require("module-b");
});
```

This way, the end-user codes in terms of simple synchronous `require()` and webpack generates the correct bundles with asynchronous loads under the hood.

**Comment by sirlancelot** [comment]
Webpack does it automatically, you can write `require.ensure([], function() { var a = require("module-a") })` and it will work just fine.

**Comment by cowwoc** [comment]
Excellent stuff. Please add this to the documentation (ideally on https://github.com/webpack/docs/wiki/code-splitting). Thank you.

**Comment by sirlancelot** [comment]
It's an opt-in feature. You can define split points in your code base. webpack takes care of the dependencies, output files and runtime stuff.

**Comment by sirlancelot** [comment]
You have to tell webpack where to split the bundle.

**Comment by cowwoc** [comment]
@sirlancelot Okay. Why/when would users want to populate the dependencies array of `require.ensure()`? Is there a legitimate use-case for doing so?

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#105
