### ISSUE TITLE
Watch facility: pause when files have merge conflicts

### ISSUE THREAD

**Issue by OliverJAsh** [webpack/webpack#7341]
## Feature request

**What is the expected behavior?**

webpack shouldn't needlessly rebuild when files have merge conflicts

**What is motivation or use case for adding/changing the behavior?**

When I am working with git, I often have merge conflicts, as I merge or rebase branches and pop my stashes.

However, every time I have merge conflicts, webpack's watch is triggered (because the files changed). This is a wasted rebuild because it will inevitably fail due to the merge conflicts. For large projects, this can be quite a painful experience, as you try to resolve a merge conflict whilst your computer grinds to a halt (as webpack rebuilds).

A much nicer experience would be if webpack's watch facility paused/bailed as soon as it noticed files with merge conflicts.

**How should this be implemented in your opinion?**

When webpack detects files with merge conflicts, avoid triggering a rebuild, or bail the rebuild as soon as the fails are detected.

**Are you willing to work on this yourself?**
yes

**Comment by ev1stensberg** [comment]
You can do something like this:

```js
const fs = require('fs');
"use strict";

module.exports = class ConflictPlugin {
    constructor(options) {
    }
	apply(compiler) {
        let shouldWait = false;
        compiler.hooks.watchRun.tap("ConflictPlugin", p => {
           const entries = Object.values(p.options.entry);
           entries.forEach( (f) => {
               const file = fs.readFileSync(f, 'utf8');
                if(file.indexOf('<<<') >= 0) {
                    shouldWait = true;
                }
            })
        })
        compiler.hooks.shouldEmit.tap("ConflictPlugin", compilation => {
			return shouldWait ? false : true;
        });
        
	}
};
```.

Keep in mind you'll still get error messages in the console, I don't think that compilation will freeze. If there's a way to stop compilation, then that should be done instead of `shouldEmit`

**Comment by OliverJAsh** [comment]
To be clear, this will only prevent the compilation from emitting. Compilation itself would still occur?

I'm looking to pause compilation itself, as that's the biggest CPU hog.

**Comment by OliverJAsh** [comment]
@ev1stensberg Where would you use the promise? Is there a `shouldCompile` hook?

**Comment by ev1stensberg** [comment]
I believe this one is the appropriate https://webpack.js.org/api/compiler-hooks/#beforerun, but I'm sure  Tobias might have a workaround that's better

**Comment by sokra** [comment]
> what you could do is to add a thread blocker to the plug-in, so that webpack will be blocked to run. I.e an unresolved promise until the conflict has been fixed.

this won't work, as you also prevent watching this way and won't get noticed about new changes.

A custom WatchFileSystem (decorator) could be a solution.

**Comment by OliverJAsh** [comment]
> A custom WatchFileSystem (decorator) could be a solution.

@sokra Can you link to any docs, or provide any examples, so I can have a go at implementing this?

**Comment by ev1stensberg** [comment]
@OliverJAsh If webpack has a tapable instance like `compiler.hooks.stopCompilation` or similar I can help you

**Comment by SassNinja** [comment]
I'd really like to see this feature in webpack! 
I know this problem quite well and it's the reason why many of my coworkers still avoid the watch mode.

> A custom WatchFileSystem (decorator) could be a solution. – @sokra 

Same question @OliverJAsh  did ask: would provide some more details regarding this idea and what you had in mind?

Are you talking about freezing the webpack watchmode (in the `beforeRun` hook as described by @ev1stensberg ) and use custom watcher (such as [fs.watch](https://nodejs.org/api/fs.html#fs_fs_watch_filename_options_listener)) to detect the solved merge conflict?

**Comment by SassNinja** [comment]
poke @sokra 

did you already manage to take a look at the question above?

I'm currently trying to convince all of my colleagues to use 100% webpack for our assets building – incl watching/HMR.

But they don't trust any watch mode because of bad experience with it (rebuild after git pull with merge conflicts). Thus it would be really helpful if webpack could catch this and pauses the watch mode.

I would like to help if knew what solution I should try.

**Comment by OliverJAsh** [comment]
Ping @sokra, if you could answer this question, I'd love to give this a shot. https://github.com/webpack/webpack/issues/7341#issuecomment-402488503
