### ISSUE TITLE
Babel don't transpiling code in local package

### ISSUE THREAD

**Issue by perevezencev** [webpack/webpack#7342]
# Bug report

My folders structure looks like this:
```
/testproject
    /local-package
      package.json
    /src
package.json
```
/testproject/package.json
```
  "dependencies": {
    "local-package": "file:./local-package",
```

/testproject/webpack.config.js
```
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules(?!\/local-package)/,
        use: ["babel-loader"]
      }
    ]
  },
```

**What is the current behavior?**

When I am run `webpack --mode production` I get an error

```
ERROR in ./local-package/components/NotFound.jsx
Module build failed: SyntaxError: /Users/pavel/Projects/JS/testproject/local-package/components/NotFound.jsx: Unexpected token (4:2)

  2 |
  3 | const NotFound = () => (
> 4 |   <div>
    |   ^
  5 |     <h3>404 page not found</h3>
  6 |     <p>We are sorry but the page you are looking for does not exist.</p>
  7 |   </div>
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. clone repo `git clone https://github.com/perevezencev/webpack-error.git`
2. run `yarn link` inside `/webpack-error/local-package`
3. run `yarn link "local-package"` inside `/webpack-error`
4. run `yarn` inside `/webpack-error`
5. run `yarn build` inside `/webpack-error`

https://gist.github.com/perevezencev/2c985c5a4f2c2ab9a89b9afd2989d409

**Other relevant information:**
webpack version:  4.8.3
Node.js version: 9.3.0
Operating System: osx
Additional tools: 
yarn: 1.6.0
webpack-cli: 2.1.3

**Comment by sokra** [comment]
There is no .babelrc in local-package.

**Comment by perevezencev** [comment]
@sokra thanks for the answer, but it did not work

**Comment by ev1stensberg** [comment]
@perevezencev You'll need to add the react preset to babel: 

https://babeljs.io/docs/plugins/preset-react/

**Comment by ev1stensberg** [comment]
Hope this gets you going @perevezencev https://medium.freecodecamp.org/part-1-react-app-from-scratch-using-webpack-4-562b1d231e75

**Comment by perevezencev** [comment]
I already use `@babel/preset-react` in `.babelrc`
```
{
  "presets": [
    "@babel/react",
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "usage",
        "modules": false
      }
    ]
  ]
}
```

**Comment by ev1stensberg** [comment]
This looks like a transpilation issue you see. Might bringing that to SO? That might be a better arena for you to get help on!

**Comment by sokra** [comment]
You should file this in babel. webpack does its job here as it applies the babel-loader to the file (you can see this from the stack trace).

So this is not a webpack issue.
