### ISSUE TITLE
[Documentation] Webpack4 with splitChunks produces unwanted chunks

### ISSUE THREAD

**Issue by philipnilsson** [webpack/webpack#7343]
As part of migrating webpack2 with `CommonsChunkPlugin` to webpack4 using `splitChunks` I've observed that I now have additional chunks created by webpack of the form

```
- vendor~foo.js
- vendor~foo~bar.js
```
These are loaded asynchronously. I'm sure this is as intented, but in my (quite large) project, these don't appear to really add any value other than introducing additional requests. 

I'm wondering if there is a way to get rid of these (specifically I'd like these chunks added into the respective non-vendor chunk).

I've been unable to find any documentation on how webpack decides on how to create these additional files, but perhaps I'm just not familiar enough with the terminology. I've tried reading https://webpack.js.org/plugins/split-chunks-plugin/ carefully, but I've been unable to figure out how any of the configuration options relate to this behaviour.

I'm using webpack `v4.8.3`. My config looks roughly like this. I've been unable to reproduce this in a small example

```
  entry: {
    // multiple entry points
  },
  optimization: {
    runtimeChunk: {
      name: 'runtime'
    },
    splitChunks: {
      cacheGroups: {
        vendor: {
          chunks: 'all',
          name: 'vendor',
          test: 'vendor'
        }
      }
    }
  },
```

I'm happy to figure this out myself if pointed in the right direction, reading relevant source is potentially ok, and to contribute additional docs if that'll make sense.

**Comment by sokra** [comment]
You can disable it with `optimization.splitChunks.cacheGroups.vendors: false`.

They add value. It separates vendor libs from your application so they can be cached individual (as they probably change less often).

vendor~foo~bar.js is shared between too and bar so you don't have to download it twice.

**Comment by philipnilsson** [comment]
@sokra That got me half way there. For anyone who comes across this - I've also set `optimization.splitChunks.cacheGroups.default: false` - this get's rid of a couple other unwanted chunks. 

I understand the use case for this, but the chunks that were generated this way just didn't really end up making much sense in my case, thanks for providing this escape hatch. Does documenting this somewhere make sense to you before I close this? That is if I didn't just miss something obvious.

Thanks for the quick feedback (and the amazing work on webpack4).

**Comment by montogeek** [comment]
@philipnilsson Can we close this issue then?
