### ISSUE TITLE
Explain what happens if require() is not listed in require.ensure() dependencies

### ISSUE THREAD

**Issue by cowwoc** [webpack/webpack#735]
With respect to the code sample found at https://github.com/webpack/docs/wiki/code-splitting#requireinclude please document what happens if the code invokes `require("foo")` inside a `require.ensure()` block, but `foo` is not one of the listed dependencies.

Will the `require()` fail? Or will it load the dependency lazily?
Will `foo.js` get packaged outside of the Javascript bundle file?

**Comment by sokra** [comment]
see http://webpack.github.io/docs/code-splitting.html#chunk-content

>If you pass a function expression (or bound function expression) as callback to the split point, webpack automatically puts all dependencies required in this function expression into the chunk too.

So

> Will the require() fail?

require() will never fail when the module exists.

> Or will it load the dependency lazily?

yes

> Will foo.js get packaged outside of the Javascript bundle file?

yes

**Comment by cowwoc** [comment]
Thank you. I am marking this issue as closed.

**Comment by lauterry** [comment]
Hello

I don't understand what is exactly the difference between 

```
require.ensure(['a.js'], (require) => {
   require('a.js')
})
```

and 

```
require.ensure([], (require) => {
   require('a.js')
})
```

Thanks

Best regards

**Comment by liqiang372** [comment]
appending to @lauterry 
What is the use case for 

```javascript
require.ensure(['a.js'], (require) => { // it seems require as argument is optional
   require('b.js');
});
```
`a.js` and `'b.js` are all included in the new chunk, but `a.js` is never executed, why bother doing this way then?

**Comment by cowwoc** [comment]
My guess, is that you want to force a certain loading order. Maybe `a.js` does something (e.g. injecting global variables or modifying the DOM) that needs to happen before the body can execute.
