### ISSUE TITLE
CommonJS modules are not handled properly with ES6 star imports

### ISSUE THREAD

**Issue by surma** [webpack/webpack#7351]
# Bug report

A star import should _always_ resolve to a module object in ES6 module land. However, when importing CommonJS modules, webpack does not behave this way.

**If the current behavior is a bug, please provide the steps to reproduce.**

Create these two files:
```js
// ./src/index.js
import * as thing from "./cjs.js";

console.log(thing);
```

```js
// ./src/cjs.js
module.exports = function() {
  return 4;
}
```
then do 

```
$ webpack
$ node ./dist/main.js`
```

**What is the current behavior?**

`thing` is a function.

**What is the expected behavior?**

`thing` should be a `Module` (or at least an object):
```
{
  default: function() {/*...*/}
}
```

**Other relevant information:**
webpack version:  4.8.3
Node.js version: 10
Operating System: Mac OS 10.13.4
Additional tools:

**Comment by TheLarkInn** [comment]
Hmm, how did we miss this one. 

@sokra have we stated a varied behavior here.

**Comment by sokra** [comment]
This behaves correctly in `.mjs` files. We can't change this for `.js` because it would break some stuff. Best avoid using `import *` for commonjs files, it has no benefit over `import default` anyway (for CJS).

#7177 makes is a `Module` instead of an object, but I'm too afraid of merging it...

**Comment by sokra** [comment]
We can consider changing this for .js files too in webpack 5

**Comment by arkadyt** [comment]
@sokra, I would like to work on this. Which files should I look at?

**Comment by patrickabkarian** [comment]
@babel/plugin-transform-modules-commonjs is a workaround but honestly this is a major issue :/

**Comment by gharabaghi** [comment]
i have same problem. i used some external files. they have codes for defining modules. after bundling i get 'jquery is not defined' in web page. any solutions? am i making some misatkes?
