### ISSUE TITLE
HtmlWebpackPlugin shows Browsersync error (and space or linebreak is missing)

### ISSUE THREAD

**Issue by rowild** [webpack/webpack#7359]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If Browsersync is configured wrongly (here: proxy AND server are configured), the console shows an error by HtmlWebpackPlugin directly attached to the "progress bar", like this:
```
Build [========== 95% emitting HtmlWebpackPluginInvalid config. You cannot specify both server & proxy options.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const ProgressBarPlugin = require('progress-bar-webpack-plugin')
const BrowserSyncPlugin = require('browser-sync-webpack-plugin')
const HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {
plugins: [
    new BrowserSyncPlugin({
      // browse to http://localhost:3000/ during development, ./public directory is being served
      host: 'localhost',
      port: 8080,
      // proxy the Webpack Dev Server endpoint through BrowserSync
      proxy: 'http://localhost:3100/',
      server: {
        baseDir: ['dev']
      },
      // prevent BrowserSync from reloading the page and let Webpack Dev Server take care of this
      reload: false
    }),
    new HtmlWebpackPlugin({
      title: 'John Van der Slice | Composer - Music Scientist - Teacher',
      filename: 'index.html',
      template: path.resolve(DIR_ROOT, 'src/index.html')
    }),
]
}
```

**What is the expected behavior?**
Show that the error stems from Browsersync. 
Add a linebreak before the error message.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
nodejs 10.1, webpack 4.8

Further comment: 
You do not only make webpack difficult, you also make it very difficult to support you with feedback. It is no fun to help!

**Comment by evilebottnawi** [comment]
@rowild how it is related to `webpack`? We can't control what happens in other plugins. Please create issue in `HtmlWebpackPlugin` repo plugin. Thanks!

**Comment by rowild** [comment]
Why would this be a htmlWebpackPlugin problem? Or, for that matter, a browsersync problem?
To me it seems to a  web-dev-server and what it prints out to the console. Maybe it is a progressWebpackPlugin problem... but who am I to know that. I report here at the center. If the devs of webpack wish to improve the quality of their product, you can pick up this problem or leave it alone. But since this stuff is so complicated, I will not jump around in different repos...
