### ISSUE TITLE
Allow loaders to emit wasm

### ISSUE THREAD

**Issue by xtuc** [webpack/webpack#7361]
## Feature request

**What is the expected behavior?**

Loader can emit wasm

**What is motivation or use case for adding/changing the behavior?**

WebAssembly is just a compilation target and can be abstracted away from the user.

They should be able to write C, rust, etc and interact with JavaScript. Some loaders already offer a similar experience but Webpack restrict their usage.

**How should this be implemented in your opinion?**

A loader can already ask for an ArrayBuffer but still need to emit JavaScript. I would suggest to allow an ArrayBuffer in `emit` since wasm has a magic header and can reliably be detected.

In the future we could even concat all wasm modules together or treeshake them. Webpack will basically act as a linker.

**Are you willing to work on this yourself?**
yes

**Comment by sokra** [comment]
Loaders can return wasm. You just have to add `type: "webassembly/experimental"` to the rule.

i. e. 

``` js
module.rules: [{
  test: /\.c$/,
  loader: "compile-c-to-wasm-loader",
  type: "webassembly/experimental"
}]
```

**Comment by PaulRBerg** [comment]
With webpack 4, do you even need any wasm loader? In this [official-example][official-example], they don't seem to be using anything.

[official-example]: https://github.com/webpack/webpack/tree/master/examples/wasm-simple
