### ISSUE TITLE
Move module lookups and resolution to webpack-cli

### ISSUE THREAD

**Issue by ev1stensberg** [webpack/webpack#7362]
## Feature request

**What is the expected behavior?**
Right now webpack takes care of looking up modules used internally. Entrypoint is getting checked in webpack, but also in webpack-cli. Would it be more convenient to check it in webpack-cli and discard the checks in webpack itself?

**What is motivation or use case for adding/changing the behavior?**
Improvement

**How should this be implemented in your opinion?**

Remove lookups internally, move the checks for configuration based lookups to the CLI

**Are you willing to work on this yourself?**
yes

**Comment by ev1stensberg** [comment]
Like checking if the entry point is valid, the entryModuleNotFoundError is an example. We can do that before running the compilation

**Comment by evilebottnawi** [comment]
@ev1stensberg i don't think it is good idea, what about non CLI usage or usage throw other CLI?

**Comment by ev1stensberg** [comment]
Just wanted to air the possibility 👍
