### ISSUE TITLE
splitChunks output unnecessary vendors~main.js

### ISSUE THREAD

**Issue by pldg** [webpack/webpack#7366]
# Bug report

**What is the current behavior?**
splitChunks output unnecessary *vendors~main.js* containing only few line of codes.

**If the current behavior is a bug, please provide the steps to reproduce.**
I've created a [testing repository](https://github.com/pldg/learn-webpack/tree/master/bundle-splitting-4)

**What is the expected behavior?**
The expected behavior is to have only *vendors~main.css* in the *dist* folder: extract *bootstrap.css* in a separate file.

**Other relevant information:**
Node.js version: 8.11.1

**Comment by Legends** [comment]
If you remove the following part from your `webpack.config.js`:

```
 optimization: {
    runtimeChunk: false,
    splitChunks: {
      chunks: 'all'
    }
  },
```
no `vendor~main.js` will be in the dist folder.

**Comment by pldg** [comment]
@Legends The expected behavior is to have only `vendors~main.css` in the *dist* folder: I'd like to extract `bootstrap.css` in a separate file.

**Comment by Legends** [comment]
I think, that this is not possible yet... webpack is a JavaScript Bundler in the first place.
But let's wait to hear the opinion of one of the core contributors..

**Comment by pldg** [comment]
@Legends Seems it's possibile. A css file called `vendors~main.css` is begin outputted correctly, that file contain the code from *bootstrap.css*. The problem is that a javascript file called `vendors~main.js` is also begin outputted, and it has only one line of code in it. It make no sense to me. It make sense only if I import React: if I do so then `vendors~main.js` will contain React in it. I used React as an example, the same behavior should occur with any file larger then 30kb, see [split-chunks-plugin defaults](https://webpack.js.org/plugins/split-chunks-plugin/#defaults). But yes, waiting to hear more from one of the core contributors :)

**Comment by Legends** [comment]
Just one hint, you have a `src/index.js` file, if no entry is specified, this file will be the entry **by default**.
Now we can rename it, but then wp complains that there is no entry point specified.
Even if you set `styles.css` as the only entry-point you still get `js` generated.

The question is, is this possible with wp4.... we will see...

**Comment by evilebottnawi** [comment]
@pldg use https://github.com/webpack-contrib/mini-css-extract-plugin for extract css for bundle. Thanks!

**Comment by Legends** [comment]
@evilebottnawi  He uses `mini-css-extract-plugin` already...

**Comment by pldg** [comment]
@evilebottnawi 

I already use `mini-css-extract-plugin`.

I've simplified my repository, should be simpler to understand. I've also created another branch called "test" in which I import *bootstrap.css* in a different entry point but the output result are similar.

Looking my repository, can you please explain me how do you extract *bootstrap.css* in a separate file **without** creating an additional (and unnecessary) javascript file in the output directory? Thanks

**Comment by sokra** [comment]
This isn't implemented yet.

**Comment by edmorley** [comment]
Dupe of #7300?
