### ISSUE TITLE
Can't name a variable "module" when devtool is "source-map"

### ISSUE THREAD

**Issue by noppa** [webpack/webpack#7369]
# Bug report

**What is the current behavior?**
Having a variable/const declaration with name "module" in an ES6 module causes a runtime error because of a conflicting webpack helper variable.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here's a repo with an easy to reproduce setup: https://github.com/noppa/webpack-module-var-name-issue. It also contains an example that uses Babel to first transpile the same ES6 module to a CommonJS syntax for comparison.

The gist of it is that the following module and config:

```JavaScript
// index.js
const module = 'Hello World'
console.log(module)

// webpack.config.js
module.exports = {
    devtool: 'source-map',
    target: 'web',
    entry: path.join(__dirname, 'index.js'),
    output: {
      filename: '[name].bundle.js',
      path: __dirname
    },
    mode: 'development'
}
```
gets compiled to something like this (parts of the output boilerplate omitted):
```
/***/ (function(module, exports) {

const module = 'Hello World'
console.log(module)

/***/ })
```
which causes a runtime exeption `SyntaxError: Identifier 'module' has already been declared`. This doesn't happen when `devtool` is one of the eval-based options.

**What is the expected behavior?**
Compiling the example and running it in the browser (or Node) should print "Hello World" without errors.
The use of a variable name "module" isn't restricted when using ES6 modules natively in the browser.

The example in the repo can also be tested with native ES6 modules in Chrome without any compilation or with Babel compilation from ES6 modules to CommonJS before giving it to webpack. Both of these examples work as expected. This is actually how we run into this issue: we used to compile the modules to CommonJS with Babel, but disabled it because we wanted to experiment with some of the webpack's _ES6-modules only_ -features like tree shaking. Babel renames the local variable to `_module`. Adding an IIFE around the user-defined code or renaming/obfuscating the `module` argument that webpack uses could also work.

**Other relevant information:**
webpack version:  4.8.3, although the same thing seems to happen with versions 2 and 3, too
Node.js version: 9.11.1
Operating System: Arch Linux
Additional tools: The Babel-example in the demo repo uses [transform-es2015-modules-commonjs](https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/) Babel plugin to do the ES6 --> CommonJS transpilation and variable renaming.

**Comment by evilebottnawi** [comment]
Looks like bug, PR welcome

**Comment by sokra** [comment]
That's working correctly.

Try the same in node.js and you get the same error:

``` js
> node index.js
.../index.js:1
(function (exports, require, module, __filename, __dirname) { const module = 'Hello World'
                                                                    ^

SyntaxError: Identifier 'module' has already been declared
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by noppa** [comment]
True, the target of the example project is "web", though, which makes it a bit confusing that usage of a node-specific variable name is not allowed. It's not a huge deal, of course, we'll just need to do something about those variables.

**Comment by filipesilva** [comment]
@sokra I don't quite follow why this is correct behaviour. 

Webpack supports a few different [targets](https://webpack.js.org/configuration/target/), one of which is `web`, described as `Compile for usage in a browser-like environment (default)`.

In the example above the target is set to `web`. But even if it wasn't, it would default to `web` anyway.

In the browser, the provided code is valid. I tried it in the Chrome devtools:

![image](https://user-images.githubusercontent.com/4172079/56585915-a65c8a00-65d6-11e9-8c51-6d398c354597.png)

I don't understand why it is correct that the `web` target should be subject to the limitations of node.js (which I assume is the `node` target). This looks like a bug to me.

**Comment by filipesilva** [comment]
Here's an example of how this bug can affect existing code: https://github.com/angular/angular/issues/30050

In this issue, a user has a project that runs correctly when built with Angular CLI (which uses webpack) and using `es5` entry points. When the same app is using `es2015` entry points, it fails at runtime with the error described in this issue.

The difference between these entry points is that the `es5` one has:
```
var module = function (prefix, dependencies) {
    return angular.module(prefix, dependencies);
};
```

And the `es2015` one has:
```
const module = (prefix, dependencies) => angular.module(prefix, dependencies);
```

Since the webpack module wrapper uses `module` as an parameter, the it cannot be redeclared via `const`.

This isn't a problem in any browser environment, but it is a problem when bundling code with webpack.

**Comment by noppa** [comment]
What makes this particularily difficult to deal with is that top level variable `module` _is_ allowed when `devtool'` is some of the eval-based options, so things will work in development but break on production (at runtime, not at compile time).

I ended up making [a simple Babel plugin](https://github.com/noppa/babel-plugin-disallow-top-level-identifier) that changes those problematic top-level variables to something else. We are using that as a workaround, because just avoiding "module" as a variable name and trusting that everyone remembers to avoid it doesn't sound very good idea in the long term.

**Comment by trotyl** [comment]
@sokra

> Try the same in node.js and you get the same error:

That's not true, it's only an error in CommonJS source file, not ES Module source file.

Try `node --experimental-modules index.mjs` and it will work correctly:

```bash
$ node --experimental-modules index.mjs
(node:62165) ExperimentalWarning: The ESM module loader is experimental.
Hello World
```

I don't think anyone here is trying to redeclare a `module` variable in CommonJS file.

**Comment by mgol** [comment]
I've just hit the same issue with latest Webpack in the exactly analogous scenario as what @filipesilva mentioned above - configuring a TS modern build for using with a differential loading approach.

I don't understand why the issue is closed. Webpack bundles correctly written modules in a way that breaks them; quite an obvious bug in Webpack, not in user code.
