### ISSUE TITLE
Webpack introduced an error message with less of the mixin function.

### ISSUE THREAD

**Issue by 540548050** [webpack/webpack#7370]
# Bug report

**What is the current behavior?**
Webpack introduced an error message with less of the mixin function.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  4.6.0
Node.js version: 8.4.0
Operating System: win10
Additional tools:

**Comment by montogeek** [comment]
Could you please describe your issue?

**Comment by evilebottnawi** [comment]
@540548050 not related to `webpack`, looks you use `less`, please create issue in `less-loader`, also please provide more information (what error you get/not get). Thanks!
