### ISSUE TITLE
Externals not working anymore in production

### ISSUE THREAD

**Issue by screendriver** [webpack/webpack#7371]
# Bug report

**What is the current behavior?**

My application behaves different in `development` than in `production`. In development everything gets rendered and parsed but in production I get a `ReferenceError: a is not defined`

**If the current behavior is a bug, please provide the steps to reproduce.**

Just check out [my project](https://github.com/screendriver/webpack-production-bug) and do a `yarn start`. Everything works.
Do a `yarn build` and after that either a `yarn http-server dist -o` or just open the `dist/` directory with a web server as you like and you can see the error.

**What is the expected behavior?**

It should behave in `production` like in `development`

**Other relevant information:**
webpack version:  4.8.2
Node.js version: 9.11.1
Operating System: macOS
Additional tools:

**Comment by screendriver** [comment]
Hi @sokra 

this repo is already extremely small, but I created an even [smaller repository](https://github.com/screendriver/webpack-production-bug) for you with a self explaining README 😉 

In the meantime I found out that when I remove my [externals](https://github.com/screendriver/webpack-production-bug/blob/master/webpack.common.js#L17) from my `webpack.common.js` it works for production. But not when I leave them.

**Comment by screendriver** [comment]
I believe this has something to do with [Emotion](https://emotion.sh) because with every other library it works as expected. Maybe the UMD built is broken or something 🤔 

I will close this for now.

**Comment by AdamRamberg** [comment]
@screendriver How did you solve this issue? I'm running into the same problem, but with styled-components. My library target is also UMD and I add styled components as an external, works great in development mode but not in production mode :crying_cat_face:

**Comment by screendriver** [comment]
I can't remember 🤷‍♂️ Too long ago. Sorry.
