### ISSUE TITLE
Webpack bundle.js remote debug

### ISSUE THREAD

**Issue by Aptashkin** [webpack/webpack#7372]
How can I debug a bundle script after executing the webpack command without dev server? It is assumed that the script will work separately in the vs project and debug it will need to be actually remotely.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
