### ISSUE TITLE
Terser output for ES6 import

### ISSUE THREAD

**Issue by staeke** [webpack/webpack#7374]
## Feature request

Option to optimize away extraneous property access for ES6 module imports.

**What is motivation or use case for adding/changing the behavior?**
With ES6 modules a typical import looks like
```js
import {fn} from 'lib';
fn();
```
...resulting in something like

```js
var _lib = __webpack_require__('lib');
_lib.fn();
```

I understand this allows for non-constant exports, handling of circular dependencies etc.. But in 99% (my gut feeling) of the cases the extra propertly lookup is unnecessary and you can do fine with (assuming ES2015 output)

```js
const {fn} = __webpack_require__('lib');
fn();
```

This may look minor, but has some advantages:
- Easier to parse for the eye during debugging
- Easier to run intermediate code during debugging (e.g. calling `fn()` manually) since you don't have to lookup the name of the generated module import
- Faster (I admit - no benchmarks)
- Allows for smaller bundle size

The hard part:
Need to determine if the exported variable is a constant and that there are no circular dependencies between the modules in question.

**How should this be implemented in your opinion?**
This could technically be implemented as a minification step, but I think it'd be hard to do the module dependency detection. And...the benefit that it'd be easier to read in development wouldn't apply.

That leads me to think that this should be handled in webpack itself.

**Are you willing to work on this yourself?**
yes - I would benefit from some directions. More specifically about how to detect circular dependencies.

**Comment by Janpot** [comment]
Webpack [supports ES5](https://github.com/webpack/webpack#browser-compatibility) compatible browsers. Sadly, destructuring is not part of that.
I also doubt there would be any performance improvement here.

**Comment by staeke** [comment]
@Janpot ES5 compatibility is of course important. I’m not suggesting this should be a default behavior, only someting turned on through some config propeerty - primarily for use during development and possibly when targeting new browsers only. 

As for speed - yeah consider it a minor (if applicable at all)

**Comment by Janpot** [comment]
I also want to add that the `import` statement
```js
import {fn} from 'lib';
```
is **not** the same as destructuring assignment. Even though it looks very similar.
for instance
```js
import {a:{b}} from 'lib';
```
Is invalid syntax even though
```js
const {a:{b}} = foo;
```
is perfectly valid.

**Comment by sokra** [comment]
Technically you are right we could optimize some cases. Scope Hoisting already optimize most cases in production mode. I guess it's not worth the work.

**Comment by Janpot** [comment]
> I don’t see how that’s relevant.

Nevermind, seemed like you were suggesting these were equivalent constructs. Just wanted to make sure.
To be honest, I don't understand what's the optimisation here. no speed or correctness improvements. Would this allow for better tree-shaking? Maybe there is a slightly improved readability in code that is not meant to be read. At the cost of added complexity and an extra configuration point.

**Comment by staeke** [comment]
>  I don't understand what's the optimisation here

@Janpot As I wrote in my original post, the primary benefit would be easier debugging. 

> Maybe there is a slightly improved readability in code that is not meant to be read. 

What do you mean with "not meant to be read"? My code is full of `Object(myLib['fn'])()`. It's meant to be read when in the debugger. People (including myself) spend significant time there. You and @sokra may not think "it's not worth the work" - a normative statement where we clearly disagree. I guess it's a matter of how much time you spend reading (and manually executing) code in the debugger.

**Comment by Janpot** [comment]
> What do you mean with "not meant to be read"?

It's transpiled code. It's not optimized to be read. Aren't sourcemaps working as expected for you here? 

> @sokra may not think "it's not worth the work" - a normative statement where we clearly disagree.

Making transpiled code debuggable is definitely worth the work. I don't think we disagree on that. What we probably disagree on is the way to achieve this.

**Comment by staeke** [comment]
> Aren't sourcemaps working as expected for you here?

Source maps destroy the mapping between shown variable names and "real" variable names, meaning I can no longer 
- hover a variable to see its value
- type the value in a watch inspection or the console to inspect its value

Furthermore, they are slow. Hence they're not an option for me (and I'm sure many others)

> Making transpiled code debuggable is definitely worth the work. I don't think we disagree on that. What we probably disagree on is the way to achieve this.

Ok, nice! What's your solution to this problem then?

**Comment by staeke** [comment]
Also I might add that `const` and destructuring is by no means required. You might as well go with something like 

```js
var _lib = __webpack_require__('lib'), fn = _lib.fn;
fn();
```

**Comment by sokra** [comment]
Note that afaik FF debugger can handle these import indirection in SourceMaps and allows to use `fn` in console and watch.

**Comment by staeke** [comment]
@sokra Just tested with FF 60.0.1. Did not work

**Comment by staeke** [comment]
> Is it possible to statically verify a binding will never be updated if it isn't declared as const? I'm not sure the export const ... satisfies 99% of the use-cases as you claim.

Great question. Yes, I think this is definitely the challenging part. I did a quick search on my current code base (sure, not scientific at all, but at least a hint). ~98% (`const`, `function`, `class`). ~2% `let`. The same with angular (@6.0.0) yielded 100% `const`,`function`, `class` (and re-exports).  But...if you import the non-ES2015 angular module, you wouldn't have `const` etc. there so that'd be harder. You could resort to statical analysis, or always err on the safe side for libraries then. Or provide a config flag like `unsafeLibImportShortening` for libraries (since I can't recall ever stumbling upon a library that did some reassignment to an export, but of course there exists such a library). Left then are circular dependencies of course.

> Sounds like there's a problem with sourcemaps. Do you think this is rather a problem with the specification, a missing browser implementation, or a missing webpack implementation?

Again, good question. Judging by this thread https://bugs.chromium.org/p/chromium/issues/detail?id=327092 it seems the symbol mapping feature exists in Chrome, so an example such as 

```js
import * as lib from 'lib';
debugger
console.log(core);
```

...should work, but it doesn't. I should really read up to give you a better answer but if I were to guess, I'd say that: 

1. Webpack should provide symbol mappings for the case above, and it doesn't (?)
2. I'd guess the source map spec probably doesn't support symbol mapping to a property access of another symbol, which is ultimately what this use case is about.

**Comment by Janpot** [comment]
> Ok, nice! What's your solution to this problem then?

My opinion is that this is an issue with sourcemaps, and needs to be solved (or attempted to be solved first) in that area. I think your proposal will be incompatible with ES6 modules spec (live bindings) and will hinder future alignment with the spec. I don't think what you propose is significantly more readable, and I don't think readability of output should come before correctness or speed. 

Prior discussion: https://github.com/facebook/create-react-app/issues/1557.

**Comment by sokra** [comment]
1. yes, because of 2.

Note that SourceMaps don't have range mappings only position mappings.

I tried to map `Object(a.b)` to `x` and `x` yields `Object`. I also tried to map `a.b` to `x` and `x` yields `a`.

so this is a bit broken (in the spec?)

---

Note that you can throw `function` and `class` in the same category as `const`, because they are not const:

``` js
export class A {}
export function B {}

// Don't do that, but it works
A = 1; B = 2;
```

Next challenge: `const` is not really const. It actually has two different values. TDZ and the value.

``` js
// a.js
// ...
export const X = 1;
// ...

// somewhere else
import { X } from "./a"; // never throw here
export function Y() {
  return X; // may throw TDZ error here
}
```

Rewriting this with your proposed style changes the semantics.

``` js
const { X } = ...; // may throw here too
export function Y() {
  return X; // may throw TDZ error here
}
```

**Comment by staeke** [comment]
> so this is a bit broken (in the spec?)

@sokra thanks for clarifying

> Note that you can throw function and class in the same category as const, because they are not const

Good point. This is a strong argument for how hard it would be to build a ES2015 compliant fool-proof solution

> Next challenge: const is not really const. It actually has two different values. TDZ and the value.

Sure, but doesn't this only apply to circular dependencies? There'd be no TDZs in the unidirectional dependency graph case, right? Or am I missing something?

**Comment by staeke** [comment]
@Janpot 

> My opinion is that this is an issue with sourcemaps, and needs to be solved (or attempted to be solved first) in that area. 

I'm not against this, but don't see it happen anytime soon. Also, source maps take significant time to produce in webpack builds, so they're not this unicorn either. In general I'm very skeptical to the "should be solved by someone else" argument. There is a problem, here and now. Deal with what you can control to solve it.

> I think your proposal will be incompatible with ES6 modules spec (live bindings) and will hinder future alignment with the spec. 

I think there are basically two ways of implementing import rewriting - one _pragmatic_ way and one _robust_ way. In the pragmatic way people would have to turn it on if wanted during development, potentially facing some incompatibilities for edge cases, because it's a tradeoff but they still value this. For the robust case, a prerequisite for rewriting would be **guaranteed compatibility**. Then by design they would be compatible (or no rewriting should take place). But it would be much harder to pull that off. 

I fail to see how any of these approaches would hinder alignment with future TC39 work. For the _pragmatic_ approach it's an opt-in that you go for knowing about the risks. Or, for the _robust_ approach compatibility should be guaranteed. I think @sokra made a good case for that you actually need to statically analyze if a variable is overwritten for e.g. `function` cases. Not impossible, but lots of work it seems, potentially hurting performance. There's always gonna be edge cases, e.g. with `eval` where it'd be pretty close to impossible to always be correct.

> I don't think what you propose is significantly more readable, and I don't think readability of output should come before correctness or speed.

Speed should be faster or the same if you mean outputted code. If you mean build time you may be right depending on ambition. Again, my strongest argument has been ease of debugging - which you do not address. As for correctness, I think it only matters if it's ever noticeable. Building the _robust_ approach above, that should be a requirement. Going for the _pragmatic_ approach, then it's an opt-in and you'd pay the consequences. But if the compatibility is bad, I can understand why the webpack core couldn't/wouldn't stand behind it

So, assuming a solution that builds on a plugin or opt-in configuration...let's sum up the arguments

\+ better debugging experience
\+ somewhat better readability
\- potentially slower builds
\- edge case incompatibilities that will increase webpack support issues or problems

I clearly value the pros higher than the cons. 

So, maybe I'll go with a plugin instead.
