### ISSUE TITLE
Modules initialized multiple times

### ISSUE THREAD

**Issue by uncleyo** [webpack/webpack#7375]
# Bug report

**What is the current behavior?**

In webpack v4, it appears that *shared modules are initialized for every runtime chunk (and each entry chunk by default contains one), and not just once*.

In my case, a common vendor chunk and two entry chunks are loaded on the same page.
In v3, the modules from the vendor chunk were only initialized once, now they are initialized for every entry chunk containing runtime if they are required in that chunk.

**If the current behavior is a bug, please provide the steps to reproduce.**

Will gladly do so if this is considered a bug.

**What is the expected behavior?**

Modules from the same build are always initialized once on a page, regardless of number of runtime chunks included on a page.

This can be avoided with `optimization.runtimeChunk` configuration to only have one runtime chunk, but I am still not sure the current default behavior is expected.

**Other relevant information:**
webpack version: 4.8.3
Node.js version: 9.11.1
Operating System: Windows 10 1803
Additional tools: n/a

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by uncleyo** [comment]
@evilebottnawi, reopen please?

**Comment by evilebottnawi** [comment]
@uncleyo Thanks for using issue template :+1: In near future we will investigate this

**Comment by sokra** [comment]
When using multiple entrypoints in a page you need to use runtimeChunk single.

I guess you are abusing entry to create a vendor chunk, which is not the correct way.

**Comment by uncleyo** [comment]
@sokra, no, I am _abusing_ it that way. The vendor chunk is generated by `splitChunks` and isn't configured in the `output`. Two entries are loaded by the same page and both load a module from vendor chunk.

These entry chunks can be used separately or together on a page. I did configure the `runtimeChunk: {name: "vendor"}` now to put it there once and it works. But it still feels weird that by default a shared module would be evaluated twice in this case. Even if the shared module doesn't have side effects like mine did, it can be pretty expensive for large modules: for example, stuff like `react` would be initialized twice.

Also, this is not how it worked in webpack v3 with no runtime related configuration tweaks...

**Comment by sokra** [comment]
Ok. I did it right.

But yes, it actually work this way. When using multiple entry points on a page you need to use `runtimeChunk: "single"` or with name.

**Comment by Legends** [comment]
Having multiple entry-points on a single page, how is this possible?

**Comment by evilebottnawi** [comment]
@Legends yep, example i can have `app.js` and have `visual editor` which loading script using own api (example plugins for `TinyMCE`).

**Comment by uncleyo** [comment]
Thanks for the answer, @sokra! I kinda _does_ make some sense the way it isolates the runtimes now, so I rather wanted to check first if this wasn't an unintended change.

I guess the biggest problem is that this goes unnoticed and many might run into this without knowing with default behavior, since there are no warning signs anywhere.

I wouldn't notice if my legacy script didn't blow up in Edge. Also, apart from the time wasted reevaluating the same modules, it can probably cause some equality checks and such to fail if code from different entries would interoperate through the global state.

Not sure what can be done about it. Just improving the docs on `runtimeChunk` is an option, but people on defaults might not read those. And warning from `webpack-cli` feels a bit too severe, since not many who has multiple entries loads them to the same page, I reckon.

**Comment by uncleyo** [comment]
@Legends, while not recommended or needed in most cases, it is actually useful sometimes, especially when dealing with legacy stuff.

For example, one entry is the app itself and another entry is loaded right before it to apply localization to the legacy framework through the global state. They are not baked together, because only one (of many) localization entry chunks is being loaded at a time.

**Comment by ooflorent** [comment]
Can we close this? Is the problem solved?

**Comment by uncleyo** [comment]
Yes, working as intended and it is now explained in the documentation
