### ISSUE TITLE
First time user confusion when running webpack without arguments

### ISSUE THREAD

**Issue by shamrin** [webpack/webpack#738]
I'm just starting to use webpack. So far so good! But I've got a minor (and easy to solve?) problem with it.

Here's my story. I've made a mistake and put `webpack.config.js` into the wrong directory and run `webpack` without arguments. It didn't find config file and just printed help screen. I was very confused because I was still thinking `webpack.config.js` is in the current directory.

I think It could be very helpful if running `webpack` would print some message about the config file. E.g.: `Looking for webpack.config.js: none found.` Or something like that. It could also be nice if `webpack` didn't show the whole help screen. It was too big and increased my confusion. Telling that `webpack --help` would show help is good enough I think.

Wrapping up:

```
$ webpack
webpack: config file: <none>
webpack: nothing to do. Try webpack --help.
```

**Comment by jhnns** [comment]
I ran into this a long time ago too :grinning:

**Comment by SpaceK33z** [comment]
Looks like this has been fixed a while ago, at least webpack 2 shows this when executing without command:

```
$ webpack
No configuration file found and no output filename configured via CLI option.
A configuration file could be named 'webpack.config.js' in the current directory.
Use --help to display the CLI options.
```
