### ISSUE TITLE
How to make Webpack replace object values?

### ISSUE THREAD

**Issue by BamItsPixel** [webpack/webpack#7390]
I have a module that looks like this:

> let Info = {};
> 
> Info.VALUE_ONE = 123;
> Info.VALUE_TWO = 456;
> Info.VALUE_THREE = 789;
> 
> module.exports = Info;

I'd like this module to disappear completely from the code after it's compiled and just have the values 123, 456 and 789 inlined where applicable- how would one do this with Webpack?

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
