### ISSUE TITLE
DefinePlugin definition not set in ReactJS v16 Component

### ISSUE THREAD

**Issue by rajiff** [webpack/webpack#7393]
# Bug report

**What is the current behavior?**
Definitions defined in DefinePlugin from webpack is not referencable or not set in ReactJS component 

**If the current behavior is a bug, please provide the steps to reproduce.**
From any webpack config driven react app, use DefinePlugin in the webpack config, set some definition, access the same from a ReactJS v16 component

**What is the expected behavior?**
Expecting DefinePlugin definitions to be able to reference inside ReactJS v16 components

**Other relevant information:**
webpack version:  4.3.0
Node.js version: 8.11
Operating System: Mac OS X
Additional tools: babel

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by rajiff** [comment]
Never mind
I had to completely kill existing web pack builds and rebuild totally to get this resolved, not sure if it is some kind of cache issue

If we are in watch mode, the plugin effect is not visible, so we have to stop, remove built bundle and then rebuild to see the effect

Hence I am closing this issue
