### ISSUE TITLE
different content output same content hash

### ISSUE THREAD

**Issue by lili21** [webpack/webpack#7394]
# Bug report

**What is the current behavior?**

the content of the output files are different, but the content hash are same.

**If the current behavior is a bug, please provide the steps to reproduce.**

[reproduce repo](https://github.com/lili21/webpack4-contenthash-issue)

**What is the expected behavior?**

content hash should respect the **real content** of the output file. looks like it only respect the content which wrapper in `webpackJsonp.push` function.

**Other relevant information:**
webpack version:  4.8.3
Node.js version: 8.11.1
Operating System: macOS 10.13.1
Additional tools:

**Comment by evilebottnawi** [comment]
Please use `webpack.NamedChunksPlugin` plugin for `webpack@3` and `optimization.namedChunks: true` in production mode. Long term caching will be improved in `webpack@5`. Thanks!. Feel free to feedback.

**Comment by lili21** [comment]
and I thought contenthash is better than chunkhash.

**Comment by lili21** [comment]
@evilebottnawi

**Comment by holm** [comment]
Any chance to get some more help on this? Everything in the docs indicate that `contenthash` is the right way to go. We see the same problem as this issue, and it's very unclear how NamedChunksPlugin solves this problem.

**Comment by lili21** [comment]
I would recommend you to use `chunkhash`.
