### ISSUE TITLE
Parser.getCommentOptions is swallowing import() build comment compilation errors

### ISSUE THREAD

**Issue by ronanamsterdam** [webpack/webpack#7395]
Simple repro use case:
```
import(/* webpackPreload: foo, webpackChunkName: "bar", webpackchunkname="fooBar" */ './someComponent')
```
the following line contains two errors:
1. webpackPreload: foo -> no quotes around "foo"
2. webpackchunkname="fooBar" -> invalid declaration, cuz it get's compiled to ```return {webpackchunkname="fooBar"}```

it's easy to miss those without a clue on wha't might be the case and the whole comment line will be cancelled without a propagated reason

An easy fix in Parser.getCommentOptions:
line 1997: from ```return {};``` to ```throw e;```

the only problem is that currently covering tests are allowing any input to be added as a comment to ```import()```
So either only webpack/build comments should be allowed in the ```import()``` statements or the parsing in ```getCommentOptions()``` should be modified to indicate invalid webpack/build comments particularly

was not sure if that's a feature request or a bug :\

**Comment by ooflorent** [comment]
It's a feature request. Instead of throwing an error (which would be a breaking change), webpack could add a warning. Please send a PR.

**Comment by sokra** [comment]
Note that you could have normal comments here too, which should not cause problems.

Maybe only process comments if they contain the word `webpack`. A warning would be better than an error.

**Comment by ronanamsterdam** [comment]
alrighty. Will work on a PR with the following:
1. Process all webpack build comments in import()
2. Throw a warning if compile of webpack comment fails, but allow any other random comment

thanks guys

**Comment by sokra** [comment]
> but allow any other random comment

there is already a test for this.
