### ISSUE TITLE
Strange with extract-text-webpack-plugin^4.0.0-beta.0

### ISSUE THREAD

**Issue by h476564406** [webpack/webpack#7397]
# Bug report

**What is the current behavior?**
I use  "webpack": "^4.8.3"  and  "extract-text-webpack-plugin": "^4.0.0-beta.0", there are something strange. My code repository: [https://github.com/h476564406/webpack4.8.3/tree/isBug](url).

In  my config webpack.prod.js, 
The entry: index.js

![image](https://user-images.githubusercontent.com/19324642/40544883-52d26cae-605c-11e8-9794-fda70a19de38.png)

The output:

![image](https://user-images.githubusercontent.com/19324642/40545047-f2cd11aa-605c-11e8-9932-3621a2306345.png)

Use  optimization  like follow picture.

![image](https://user-images.githubusercontent.com/19324642/40544871-47638880-605c-11e8-9d46-3cf1a3d1eb23.png)

However,  if  run  'npm run build', I found
![image](https://user-images.githubusercontent.com/19324642/40545023-dd669e58-605c-11e8-9257-3c654ee0d890.png)

- Why produce manifest.css and  vendors.css? I did not use css in these file.
- Why index use  chunkFilename rather than filename?   I think the index is entry chunk which use filename.
- If I config allChunks:false, it report error.
` new ExtractTextPlugin({
            filename: '[name].css',
            allChunks: false,
        }),`
The code logic is if I click the button, will ` import('./A.js') `  and in 'A.js',  `import styles from './a.css'`.
The error:
![image](https://user-images.githubusercontent.com/19324642/40545513-b1605a18-605e-11e8-905f-67dbbfbd2c2e.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

There is my code repository: [https://github.com/h476564406/webpack4.8.3/tree/isBug](url)

The step to reproduce error:

1.  pull branch 
2.  npm install
3.  npm run build
4.  node server.js
5.  Go to [http://localhost:3001/](url) , click button and console will show error.

**What is the expected behavior?**
In my view, it will use 'style-loader' to process the style in 'a.css'. If I click button, I think it will add style in the html.

**Other relevant information:**
webpack version:   "^4.8.3",
Node.js version:  "v8.9.1",
Operating System:  "MacOS",
Additional tools:

**Comment by evilebottnawi** [comment]
Don't use `extract-text-webpack-plugin` for extract css use instead https://github.com/webpack-contrib/mini-css-extract-plugin
