### ISSUE TITLE
Recompilation in development mode generates incorrect imports

### ISSUE THREAD

**Issue by tamelbrun** [webpack/webpack#7400]
# Bug report

**What is the current behavior?**

We have an import from an ES module which is compiled correctly when webpack is started, but starts failing when changes are made in other files while webpack is running in watch mode: a warning is emitted about an import that was not found and the generated code stops working. When inspecting the output file, we can see that the expected individual import has been replaced by a (non-equivalent) import of the entire module where the import is from.

The problem first appeared for us when we upgraded `date-fns` from version `2.0.0-alpha7` to `2.0.0-alpha8`, but we were able to construct a minimal reproduction project without any dependencies other than webpack itself.

**If the current behavior is a bug, please provide the steps to reproduce.**

- Unzip the attached reproduction project: [webpack-import-recompile-bug.zip](https://github.com/webpack/webpack/files/2039509/webpack-import-recompile-bug.zip)
- Run `npm i` and `npm start`
- Observe that the initial compilation does not produce any warnings
- While webpack is running, make any change to `main.js` (e.g. a comment line)
- Observe that a warning is generated on `require-me.js`:
```
WARNING in ./src/require-me.js
4:16-26 "export 'default' (imported as 'myFunction') was not found in './my-module'
 @ ./src/require-me.js
 @ ./src/main.js
```
- Now make any change to `require-me.js` (e.g. a comment line)
- Observe that compilation succeeds again

The problem only appears when running in `mode: "development"`, not `"production"`. If `sideEffects: false` is removed from `src/my-module/package.json`, or if `sideEffects: true` is removed from `webpack.config.js`, the problem also disappears.

**What is the expected behavior?**

The compilation output remains consistent while webpack is running in watch mode, without warnings about missing imports appearing and disappearing when making unrelated changes. Our only workaround is to restart webpack, which increases our wait time from ± 5 seconds to more than 20 seconds after each change.

**Other relevant information:**
webpack version: 4.8.3
Node.js version: 8.9.4
Operating System: Windows 10
Additional tools: -

**Comment by tryzniak** [comment]
Can confirm all of the above.

**Other relevant information**:
webpack version: 4.8.3
Node.js version: 8.9.4
Operating System: MacOS 10.12 Sierra
Additional tools: -

**Comment by hk144** [comment]
Very good
