### ISSUE TITLE
Invalid Character in boundle when JS script is UTF-8 encoded

### ISSUE THREAD

**Issue by koljagava** [webpack/webpack#7402]
# Bug report

**What is the current behavior?**
Webpack produces a invalid character in bundle file in development mode when the js file encoding is UTF-8

**If the current behavior is a bug, please provide the steps to reproduce.**
1. create an empty project
2. Install webpack 4.8.3 and webpack-cli 2.1.4 packages
3. create a simple index.js file in src folder UTF-8 encoded containing "const test= 100;"
4. Run webpack --mode development
5. The dist/main.js file contains an invalid character before "const test= 100;"

**What is the expected behavior?**
avoid invalid character and able to boundle script files UTF-8 encoded

**Other relevant information:**
webpack version:  4.8.3
Node.js version: 10.1.0
Operating System: Windows 7
Additional tools: npm v5.6.0, webpack-cli 2.1.4

**Comment by ooflorent** [comment]
I'm not able to reproduce the issue.  It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by koljagava** [comment]
Hi ooflorent,
here it is 
https://github.com/koljagava/webpack_Issue7402.git
kolja

**Comment by tryzniak** [comment]
I checked OP's repo, and can confirm that there's [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) added to the beginning of a bundled file. Here a screenshot of my vim:
<img width="544" alt="screen shot 2018-05-25 at 22 16 03" src="https://user-images.githubusercontent.com/10567153/40562374-48ece9be-6069-11e8-9967-828293b2b653.png">
Notice `<feff>` thing. 
I should also add, that the bundle still runs fine, tested on node v8.9.4.

**Comment by ooflorent** [comment]
@koljagava why is it an issue for you? It seems that _you_ (or your tools) added that character, which is fine! Is this causing some kind of weird behavior? If you don't want BOM in your files, don't use it!

@tryzniak Thanks for the investigation. This character is not added by webpack.

**Comment by koljagava** [comment]
@ooflorent & @tryzniak 
i got an error loading the script using IE11 and debugging with VS2015, 
especially if js is loaded as an AMD module.
I change the example , if you want to do a double check. 
anyway , checking with vim, i can not see the BOM in index.js file but only in main.js 

let me know you yoou can reproduce it IE11 error, otherwise i'll do a screenshot

regards
  kolja

**Comment by koljagava** [comment]
Hi @ooflorent 
here is the javascript error scrrenshot
![immagine](https://user-images.githubusercontent.com/20150345/40642941-d3b95f0c-631e-11e8-8af4-a534ea63355c.png)

Please consider to reopen the issue, 'im trying to migrate an application with tons of js scripts and VS.
consider also that witn minimized option to true the BOM char is not added.

regards
   kolja

**Comment by ooflorent** [comment]
@koljagava This issue is not related to webpack but to your files. You need to properly encode them. If you don't want BOM, don't use it!

You can use the following command to find which files are using BOM:

```
grep -rl $'\xEF\xBB\xBF' .
```
