### ISSUE TITLE
Webpack final bundle size is too big 

### ISSUE THREAD

**Issue by PradeepJaiswar** [webpack/webpack#7405]
# Bug report
**What is the current behavior?**
Making build using webpack 4.9.1 using `npm run build` 
Package.json file command 
`"build": "webpack --mode production --config webpack.config.prod.js",`

After build my bundle size is 1010 KiB which is too huge. trying to figure out since day but no success so finally putting here 

![image](https://user-images.githubusercontent.com/4545996/40577418-dd5f0b04-6122-11e8-9b33-3bf0d72653fe.png)

my webpack.config.prod.js
 
```
var path = require('path');
var webpack = require('webpack');
var CopyWebpackPlugin = require('copy-webpack-plugin');
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;

module.exports = {
  mode: 'production',
  devtool: 'none',
  entry: {
    index: './src/index.js',
  },
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: '/'
  },
  optimization: {
    minimize: true,
  },
  plugins: [
    new webpack.LoaderOptionsPlugin({ options: {} }),
    new webpack.optimize.AggressiveMergingPlugin(),
    new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
    new CopyWebpackPlugin([
      {
        from: 'style.css',
      },
      {
        from: 'bootstrap.min.css',
      },
      {
        from: 'index.html',
      }
    ]),
    new BundleAnalyzerPlugin(),
  ],
  module: {
    noParse:[ /node_modules\/localforage\/dist\/localforage.js/],
    rules: [
      {
        test: /\.js$/,
        enforce: "pre",
        loaders: ['eslint-loader'],
        include: path.join(__dirname, 'src')
      },
      {
        test: /\.js$/,
        loaders: ['babel-loader'],
        include: [path.join(__dirname, 'src'), path.join(__dirname, 'translations')]
      },
      {
        // do not exclude node_modules, since map.json is in node_modules
        test: /\.json$/,
        loader: 'json'
      },
      {
        test: /\.css$/,
        loaders: [ 'style-loader', 'css-loader' ]
      },
    ]
  }
};
```
my .babelrc looks like below

```
{
  "presets": ["react", "es2015", "stage-2"],
  "env": {
    "development": {
      "plugins": [
        ["react-transform", {
          "transforms": [{
            "transform": "react-transform-hmr",
            "imports": ["react"],
            "locals": ["module"],
            "preventFullImport": true
          }, {
            "transform": "react-transform-catch-errors",
            "imports": ["react", "redbox-react"],
            "preventFullImport": true
          }]
        }]
      ]
    }
  },
  "plugins": [
    ["transform-object-rest-spread"],
    ["transform-react-display-name"],
    ["module-resolver", {
      "root": ["./src"]
    }]
  ]
}
```

**What is the current behavior?**
Should be somewhere near to or more than webpack recommendations but 1010 KB is too much

FROM BUILD LOGS 

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  index (1010 KiB)
      bundle.js

**Other relevant information:**
webpack version:  webpack 4.9.1
Node.js version: v6.10.0
Operating System: mac OS
Additional tools: npm -v = 4.1.2

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).

**Comment by PradeepJaiswar** [comment]
Thanks for the reply
https://stackoverflow.com/questions/50544207/webpack-final-bundle-size-is-too-big/50545078#50545078 not much help though. 

My actual app is too small only three-page simple app and i cant afford this big bundle. Now looking for webpack alternative  ☹️
