### ISSUE TITLE
First class hot reload support in Multi-Compiler mode

### ISSUE THREAD

**Issue by Kronuz** [webpack/webpack#7406]
## Feature request

Make easy and transparent hot updates for any chunks in any bundle just by having a single "hot client" running and receiving updates from the server.

**What is the expected behavior?**

To have a single hot client and one hot-update connection to the server to the in MultiCompiler projects running and just work.

**What is motivation or use case for adding/changing the behavior?**

In Multi-Compiler mode, the "hot" clients (`dev-server`, `only-dev-server`, etc.) they all use `module.hot`, which works fine when there's only one bundle, however, when multiple bundles are built, if one has several clients running, they all try to update and possibly pass `check()` to all bundles, making it fail with 404 when there really are not changes there (no `*.hot-update.js`).

**How should this be implemented in your opinion?**

I believe there are a few possible ways to implement this, one (that I have actually tried and verified it works) is make it so the client has access to every bundle's "module.hot" object by name (modifying the Main Template plugins), and when the client receives an update, the update should come with the name of the bundle being updated, such update would call it's appropriate `hot.check()` and `hot.apply()` for the bundle being updated.

**Are you willing to work on this yourself?**
yes

**Comment by TrejGun** [comment]
please reopen

**Comment by zachintosh** [comment]
I agree that this needs a revisit.

**Comment by evilebottnawi** [comment]
bump

**Comment by TrejGun** [comment]
ping

**Comment by TrejGun** [comment]
pew pew

**Comment by TrejGun** [comment]
pew pew
