### ISSUE TITLE
Improve readability of "size" output

### ISSUE THREAD

**Issue by cowwoc** [webpack/webpack#741]
Webpack outputs the size of each bundle after processing it. Example:

```
   Asset     Size  Chunks             Chunk Names
Index.js   131102       0  [emitted]  Index
```

Please consider making `size` more readable by inserting a separator every 3 digits (e.g. `131,102`), or outputting "131k" instead of "131102" (bytes).

**Comment by sokra** [comment]
Good idea... Would you like to do a PR? => `Stats.js`

**Comment by cowwoc** [comment]
Is this the relevant line? https://github.com/webpack/webpack/blob/master/lib/Stats.js#L364

**Comment by sokra** [comment]
yes, and you can do the same for module and chunks size:

https://github.com/webpack/webpack/blob/master/lib/Stats.js#L427
https://github.com/webpack/webpack/blob/master/lib/Stats.js#L470

**Comment by Dashed** [comment]
+1. Make it more human friendly :D

**Comment by hkal** [comment]
Went ahead and implemented both of the suggested outputs since there was no clear direction here. Take whichever you prefer, or neither.

**Comment by cowwoc** [comment]
For what it's worth, I prefer the version that prints kB (easier to read, and I doubt anyone will need the size down to the exact byte)
