### ISSUE TITLE
 source code learn

### ISSUE THREAD

**Issue by hehos** [webpack/webpack#7414]
I'm learning the source code，But I found that there were few comments in the code !  Excuse me, is the project itself like this ?

**Comment by ooflorent** [comment]
**tl;dr:** Yes it is.

The source code of webpack is not straightforward. We try to put more and more comments on the newer part and to describe the used algorithms but the codebase is huge. However, what I like to do when learning a codebase that lacks of comments is commenting it! It helps to understand what's happening and to remember what _you_ previously learned. If you start such process, I'll be happy to review a PR merging your comments.
