### ISSUE TITLE
Resolve file referencing itself further up the folder structure rather than itself

### ISSUE THREAD

**Issue by kentcdodds** [webpack/webpack#742]
I need to be able to require a file that has the same name as the file doing the requiring, and have webpack skip itself and look further up the folder structure to find the file.

Here's the relevant part of the `resolve` part of my webpack config

```
resolve: {
  modulesDirectories: ['shared', 'node_modules'],
}
```

Here's my file structure

``` 
 ├── azWeb/ <-- this folder's index.js does require('ngCommon') which correctly resolves to #1
 ├─┬ shared/
 │ └── ngCommon/   <-- #1 this is the root ngCommon.
 └─┬ states/
   ├── error/
   ├── loading/
   ├── login/
   └─┬ root/
     ├─┬ children/
     │ └─┬ partition/
     │   ├─┬ children/
     │   │ ├─┬ accounts/
     │   │ │ ├─┬ children/
     │   │ │ │ ├─┬ account/
     │   │ │ │ │ ├─┬ children/
     │   │ │ │ │ │ ├── advanced/
     │   │ │ │ │ │ ├── router/
     │   │ │ │ │ │ └── simple/  <-- this folder's index.js wants to require('ngCommon') and it correctly resolves to #2
     │   │ │ │ │ ├─┬ shared/
     │   │ │ │ │ │ └── ngCommon/  <-- #2 this folder's index.js wants to require('ngCommon') which should resolve to #3
     │   │ │ │ │ └── some-file.js <-- this file wants to require('ngCommon') and it correctly resolves to #2
     │   │ │ │ └── recent/
     │   │ │ └─┬ shared/
     │   │ │   └─┬ ngCommon/  <-- #3 this folder's index.js wants to require('ngCommon') which should resolve to #4
     │   │ │     └── services/
     │   │ └─┬ reports/
     │   │   └─┬ children/
     │   │     └─┬ invoice-audit/  <-- this folder's index.js wants to require('ngCommon') and it correctly resolves to #4
     │   │       └── components/
     │   └─┬ shared/
     │     └─┬ ngCommon/  <-- #4 this folder's index.js wants to require('ngCommon') which should resolve to #1
     │       ├── directives/
     │       └─┬ services/
     │         └── EditCSR/
     └─┬ components/
       ├── directives/
       └── services/
```       
 
So, the idea is that when #2 does require('ngCommon'), it should exclude itself and look further up the tree for another shared/ngCommon. Currently, it resolves to itself (and I believe webpack just ignores that or something).

However, if an ngCommon/index.js tries to require('ngCommon') that resolves to itself. I need to be able to have it skip itself and find the next one up the tree. Is this possible with webpack?

**Comment by kentcdodds** [comment]
Note, I want to be able to `require('ngCommon')` without having to point directly to the file.

**Comment by kentcdodds** [comment]
Basically, I want to configure webpack to instead of doing this:

> An array of directory names to be resolved to the current directory as well as its ancestors, and searched for modules. This functions similarly to how node finds “node_modules” directories. For example, if the value is ["mydir"], webpack will look in “./mydir”, “../mydir”, “../../mydir”, etc.

To do this:

> An array of directory names to be resolved to the current directory as well as its ancestors, and searched for modules. This functions similarly to how node finds “node_modules” directories. For example, if the value is ["mydir"], webpack will look in “../mydir”, “../../mydir”, etc.

(note the difference at the end). Copied from the `resolve.moduleDirectories` option documentation.

**Comment by kentcdodds** [comment]
I'm thinking this may be possible if I create my own [enhanced-require](https://github.com/webpack/enhanced-require) function. What do you think?

**Comment by kentcdodds** [comment]
I didn't really have success with `enhanced-require`, but I think I may be getting somewhere by doing something like:

```
{
  resolve: {
    moduleDirectories: ['../../shared', '../shared', 'shared', 'node_modules']
  }
}
```

This is a little crazy though and I'm not certain it actually works. Still looking at it. Feedback appreciated.

**Comment by kentcdodds** [comment]
I don't think the `moduleDirectories` thing is going to work either. I updated the requirements for what I'm asking for help with. Basically, I want to prevent a file from requiring itself. If it's requiring itself, I want the resolver to look for other modules that would satisfy the dependency using the `moduleDirectories`. Is this possible with webpack currently? If not, is there any way that I can make it possible via a PR? This would greatly help me in my efforts to make angular applications truly modular.

**Comment by sokra** [comment]
Just to clearify this: According to CommonJs it's correct to resolve to itself.

I see 3 options here:
* A custom resolver plugin, but this is a bit work...
* Use a relative path in the ngCommon to the parent ngCommon: `require("../../../../shared/ngCommon")` or alias `ngCommon-parent` to `../../../../shared/ngCommon`.
* A `before-resolve` plugin: You can use the `NormalModuleReplacementPlugin` for this:
``` js
new NormalModuleReplacementPlugin(/^ngCommon$/, function(r) {
	if(/ngCommon$/.test(r.context))
		// when resolving `ngCommon` from `ngCommon`
		r.context = path.resolve(r.context, "../../../");
})
```
Last one looks good...

**Comment by jhnns** [comment]
> Just to clearify this: According to CommonJs it's correct to resolve to itself.

And that can be [really useful](https://www.npmjs.com/package/link-package)...

**Comment by kentcdodds** [comment]
Oh yeah, thanks for clarifying. I know that this is how CommonJS is supposed to work. But what you've done for my project with that little snippet of code is incredible. Thank you so much! This is huge for me. I'm looking forward to showing this concept to the world soon. It could not be possible without webpack. Thanks for all the work you do @sokra!

**Comment by sokra** [comment]
:+1:
