### ISSUE TITLE
compiled bundle moduleId is null

### ISSUE THREAD

**Issue by warfrogsdf** [webpack/webpack#7420]
# Bug report

**What is the current behavior?**
my problem happens on vue ssr project。by config webpack，new webpack instance and start by webpack-dev-server，the output dectory bundle.js，in this js file，moduleId is null

**If the current behavior is a bug, please provide the steps to reproduce.**
1、normal webpack config
2、new webpack instance
3、instacnce watch
4、the output bundle ， moduleId is null

this is the output code，like this：
/***/ null:
/***/ (function(module, exports, __webpack_require__) {
/***/ }),

**What is the expected behavior?**
module have right moduleId

**Other relevant information:**
webpack version:  3.12.0
Node.js version: 8.9.4
Operating System: win 10
Additional tools: webstorm

**Comment by mc-zone** [comment]
Could you please show your config or give a small repo to reproduce it ?

**Comment by warfrogsdf** [comment]
at webpack code console，the log is blow:
[ { id: './node_modules/html-webpack-plugin/lib/loader.js!./src/index.html',
    source: ConcatSource { children: [Array] } },
  { id: './node_modules/lodash/lodash.js',
    source: ConcatSource { children: [Array] } },
  { id: './node_modules/webpack/buildin/global.js',
    source: ConcatSource { children: [Array] } },
  { id: './node_modules/webpack/buildin/module.js',
    source: ConcatSource { children: [Array] } } ]
[ { id: './node_modules/html-webpack-plugin/lib/loader.js!./src/index.html',
    source: ConcatSource { children: [Array] } },
  { id: './node_modules/lodash/lodash.js',
    source: ConcatSource { children: [Array] } },
  { id: './node_modules/webpack/buildin/module.js',
    source: ConcatSource { children: [Array] } } ]
[ { id: './node_modules/css-loader/index.js!./node_modules/less-loader/dist/cjs.js!./node_modules/element-ui/lib/theme-chalk/index.css',
    source: ConcatSource { children: [Array] } },
  { id: './node_modules/css-loader/lib/css-base.js',
    source: ConcatSource { children: [Array] } },
  { id: './node_modules/css-loader/lib/url/escape.js',
    source: ConcatSource { children: [Array] } },
  { id: './node_modules/element-ui/lib/theme-chalk/fonts/element-icons.ttf',
    source: ConcatSource { children: [Array] } },
  { id: './node_modules/element-ui/lib/theme-chalk/fonts/element-icons.woff',
    source: ConcatSource { children: [Array] } } ]
[ { id: './node_modules/css-loader/index.js!./node_modules/less-loader/dist/cjs.js!./node_modules/element-ui/lib/theme-chalk/index.css',
    source: ConcatSource { children: [Array] } },
  { id: './node_modules/css-loader/lib/css-base.js',
    source: ConcatSource { children: [Array] } },
  { id: './node_modules/css-loader/lib/url/escape.js',
    source: ConcatSource { children: [Array] } },
  { id: './node_modules/element-ui/lib/theme-chalk/fonts/element-icons.ttf',
    source: ConcatSource { children: [Array] } },
  { id: './node_modules/element-ui/lib/theme-chalk/fonts/element-icons.woff',
    source: ConcatSource { children: [Array] } } ]
[ { id: './node_modules/css-loader/index.js!./node_modules/less-loader/dist/cjs.js!./node_modules/element-ui/lib/theme-chalk/index.css',
    source: ConcatSource { children: [Array] } },
  { id: './node_modules/css-loader/lib/css-base.js',
    source: ConcatSource { children: [Array] } },
  { id: './node_modules/css-loader/lib/url/escape.js',
    source: ConcatSource { children: [Array] } },
  { id: './node_modules/element-ui/lib/theme-chalk/fonts/element-icons.ttf',
    source: ConcatSource { children: [Array] } },
  { id: './node_modules/element-ui/lib/theme-chalk/fonts/element-icons.woff',
    source: ConcatSource { children: [Array] } } ]
[ { id: './node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/pages/main/index.vue',
    source: ConcatSource { children: [Array] } },
  { id: './node_modules/vue-loader/lib/template-compiler/index.js?{"id":"data-v-6b974fe6","hasScoped":false,"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/pages/main/index.vue',
    source: ConcatSource { children: [Array] } },
  { id: './src/pages/main/index.vue',
    source: ConcatSource { children: [Array] } } ]
[ { id: './node_modules/vue-loader/lib/template-compiler/index.js?{"id":"data-v-618d2e71","hasScoped":false,"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/pages/login/index.vue',
    source: ConcatSource { children: [Array] } },
  { id: './src/pages/login/index.vue',
    source: ConcatSource { children: [Array] } } ]
[ { id: './node_modules/vue-loader/lib/template-compiler/index.js?{"id":"data-v-5aa48595","hasScoped":false,"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/pages/about/index.vue',
    source: ConcatSource { children: [Array] } },
  { id: './src/pages/about/index.vue',
    source: ConcatSource { children: [Array] } } ]
[ { id: './src/pages/friendlist/index.vue',
    source: ConcatSource { children: [Array] } } ]
[ { id: './src/pages/chatlist/index.vue',
    source: ConcatSource { children: [Array] } } ]
[ { id: './src/pages/chat/index.vue',
    source: ConcatSource { children: [Array] } } ]
[ { id: 'vuex/dist/logger',
    source: ConcatSource { children: [Array] } },
  { id: './src/entry-server.js',
    source: ConcatSource { children: [Array] } },
  { id: 'vue', source: ConcatSource { children: [Array] } },
  { id: './src/app.vue',
    source: ConcatSource { children: [Array] } },
  { id: 'vue-router', source: ConcatSource { children: [Array] } },
  { id: 'vuex', source: ConcatSource { children: [Array] } },
  { id: 'element-ui', source: ConcatSource { children: [Array] } },
  { id: './node_modules/element-ui/lib/theme-chalk/index.css',
    source: ConcatSource { children: [Array] } },
  { id: './src/store/index.js',
    source: ConcatSource { children: [Array] } },
  { id: './src/routes.js',
    source: ConcatSource { children: [Array] } },
  { id: './src/app.js',
    source: ConcatSource { children: [Array] } },
  { id: './src/store/common/index.js',
    source: ConcatSource { children: [Array] } },
  { id: './src/store/page1/index.js',
    source: ConcatSource { children: [Array] } },
  { id: './src/store/page2/index.js',
    source: ConcatSource { children: [Array] } },
  { id: './src/store/action-types.js',
    source: ConcatSource { children: [Array] } },
  { id: './src/store/mutation-types.js',
    source: ConcatSource { children: [Array] } },
  { id: 'axios', source: ConcatSource { children: [Array] } },
  { id: './node_modules/vue-loader/lib/component-normalizer.js',
    source: ConcatSource { children: [Array] } },
  { id: './node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/app.vue',
    source: ConcatSource { children: [Array] } },
  { id: './node_modules/vue-loader/lib/template-compiler/index.js?{"id":"data-v-bced26ea","hasScoped":false,"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/app.vue',
    source: ConcatSource { children: [Array] } } ]
[ { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } } ]
[ { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } } ]
[ { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } } ]
[ { id: null, source: ConcatSource { children: [Array] } } ]
[ { id: null, source: ConcatSource { children: [Array] } } ]
[ { id: null, source: ConcatSource { children: [Array] } } ]
[ { id: null, source: ConcatSource { children: [Array] } },
  { id: 0, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  { id: null, source: ConcatSource { children: [Array] } },
  ... 121 more items ]
[ { id: './node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/pages/main/index.vue',
    source: ConcatSource { children: [Array] } },
  { id: './node_modules/vue-loader/lib/template-compiler/index.js?{"id":"data-v-6b974fe6","hasScoped":false,"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/pages/main/index.vue',
    source: ConcatSource { children: [Array] } },
  { id: './src/pages/main/index.vue',
    source: ConcatSource { children: [Array] } } ]
[ { id: './node_modules/vue-loader/lib/template-compiler/index.js?{"id":"data-v-618d2e71","hasScoped":false,"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/pages/login/index.vue',
    source: ConcatSource { children: [Array] } },
  { id: './src/pages/login/index.vue',
    source: ConcatSource { children: [Array] } } ]
[ { id: './node_modules/vue-loader/lib/template-compiler/index.js?{"id":"data-v-5aa48595","hasScoped":false,"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/pages/about/index.vue',
    source: ConcatSource { children: [Array] } },
  { id: './src/pages/about/index.vue',
    source: ConcatSource { children: [Array] } } ]
[ { id: './src/pages/friendlist/index.vue',
    source: ConcatSource { children: [Array] } } ]
[ { id: './src/pages/chatlist/index.vue',
    source: ConcatSource { children: [Array] } } ]
[ { id: './src/pages/chat/index.vue',
    source: ConcatSource { children: [Array] } } ]
[ { id: './node_modules/babel-runtime/core-js/symbol/iterator.js',
    source: ConcatSource { children: [Array] } },
  { id: 0, source: ConcatSource { children: [Array] } },
  { id: './node_modules/webpack/hot/dev-server.js',
    source: ConcatSource { children: [Array] } },
  { id: './node_modules/webpack-dev-server/client/index.js?http://127.0.0.1:9000/',
    source: ConcatSource { children: [Array] } },
  { id: './src/entry-client.js',

**Comment by warfrogsdf** [comment]
const HtmlWebpackPlugin = require('html-webpack-plugin'); // 通过 npm 安装
const webpack = require('webpack'); // 用于访问内置插件
const path = require('path');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const ExtractTextPlugin = require("extract-text-webpack-plugin");

const config = {
  entry: {
    /*main: ['./src/entry-client.js'],*/
  },
  output: {
    path: path.resolve(__dirname, '../dist'),
    //filename: '[id]-[chunkhash:8].js'
    filename: '[name].js',
    //publicPath: 'https://static.bilibili.com/bmall/'
  },
  devServer: {
    contentBase: './dist',
    compress: true,
    port: 9000,
    /*allowedHosts: [
        'a.com'
    ],*/
    proxy: {
      "/api": "http://localhost:3000"
    },
    hot: true,
    /*open: true,*/
    disableHostCheck: true,
    headers: {
      "Access-Control-Allow-Origin": "*"
    }
  },
  resolve: {
    extensions: [".vue", ".js", ".json"],
    alias: {
      //xyz$: path.resolve(__dirname, 'path/to/file.js')
    }
  },
  module: {
    rules: [
      {test: /\.txt$/, use: 'raw-loader'},
      {
        test: /\.js$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['es2015'],
            plugins: ['syntax-dynamic-import', 'add-module-exports']
          }
        }
      },
      {
        test: /\.vue$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: 'vue-loader',
          options: {
            loaders: {
              'less': 'vue-style-loader!css-loader!less-loader',
            }
          }
        }
      },
      /*{
          test: /\.(less|css)$/,
          use: [{
              loader: "style-loader" // creates style nodes from JS strings
          }, {
              loader: "css-loader" // translates CSS into CommonJS
          }, {
              loader: "less-loader" // compiles Less to CSS
          }]
      },*/
      {
        test: /\.(less|css)$/,
        use: ExtractTextPlugin.extract({
          fallback: {
            loader: "style-loader" // creates style nodes from JS strings
          },
          use: [{
            loader: "css-loader" // translates CSS into CommonJS
          }, {
            loader: "less-loader" // compiles Less to CSS
          }]
        })
      },
      {
        test: /\.(png|jpg|gif|jpe?g|svg|woff|ttf)$/i,
        use: [
          {
            loader: 'url-loader',
            options: {
              name: '[name]-[hash:8].[ext]',
              limit: 10/*,
                            outputPath: 'img/',
                            publicPath: 'img/'*/
            }
          }
        ]
      }
    ]
  },
  plugins: [
    //new webpack.optimize.UglifyJsPlugin(),
    new CleanWebpackPlugin(['dist']),
    new HtmlWebpackPlugin({
      template: './src/index.html'
    }),
    new webpack.NamedModulesPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new ExtractTextPlugin({
      allChunks: true,
      filename: '[name]-[contenthash:8].css',
    }),
  ]
};

module.exports = config;

i use this client config to start a webpack instacne, but output code moduleId is null

**Comment by warfrogsdf** [comment]
@mc-zone 你有qq吗，这样联系快一些。

**Comment by ooflorent** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by warfrogsdf** [comment]
@ooflorent @mc-zone https://github.com/warfrogsdf/webpack-demo this is a small reproducible example

**Comment by sokra** [comment]
Upgrade to webpack 4 and you would get an error telling you the problem.

You are using `clientCompiler.watch` and `new WebpackDevServer(clientCompiler, ` which runs the compiler twice in parallel

**Comment by warfrogsdf** [comment]
@sokra 毕竟你是个大神呀（big god）
