### ISSUE TITLE
test/README update

### ISSUE THREAD

**Issue by ronanamsterdam** [webpack/webpack#7424]
## Feature request

Seems like use case of ```expected.txt + actual.txt``` described int [test/README](https://github.com/webpack/webpack/tree/master/test#statscases-statstestcasestestjs) is outdated and jest's ```toMatchSnapshot()``` is being used

- I would want to update the relevant info in README to avoid confusion

- remove [accept-stats.js](https://github.com/webpack/webpack/blob/master/test/statsCases/accept-stats.js) as it's not being used anywhere anymore 

**What is the expected behavior?**

updated test/README related to StatsTestCases.test.js with jest's ```toMatchSnapshot()``` info and flow and unused test module to be removed  

**What is motivation or use case for adding/changing the behavior?**

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
yes

**Comment by ooflorent** [comment]
Send a PR
