### ISSUE TITLE
(4.10.0) "Module has no id. This should not happen" when using dynamic import and sideEffects flag

### ISSUE THREAD

**Issue by sqal** [webpack/webpack#7428]
# Bug report

**What is the current behavior?**
`RuntimeTemplate.moduleId(): Module <path>\packages\components\src\CompAB\CompA.js has no id. This should not happen.`

**If the current behavior is a bug, please provide the steps to reproduce.**
- Clone https://github.com/sqal/webpack-bug-reproduction
- `npm install && npm run build`

This error occurs only in the following situation:
- `"sideEffects: false"` is required (is set in components package.json) - if you remove it, you won't see the error
- Module is imported twice (using static import and dynamic import) - if you remove dynamic import of `./foo` from main.js or static import of `CompA` - no error

**What is the expected behavior?**
Should compile without the error

**Other relevant information:**
webpack version:  4.10.0
Node.js version: 9.6.1
Operating System: Windows 10 x64
Additional tools: -

**Comment by theodorejb** [comment]
I'm still getting this error with webpack v4.10.1, when I try to compile an Angular 6 project:

```
ERROR in chunk app [entry]
    dist/[name].js
    C:\MyProject\node_modules\@angular\core\fesm5\core.js
    RuntimeTemplate.moduleId(): Module C:\MyProject\node_modules\rxjs\_esm5\internal\Subscription.js has no id. This should not happen.
```

**Comment by sqal** [comment]
Thank you for quick fix @sokra I can confirm everything works once again on my end :) 👍

**Comment by exah** [comment]
Error still happening with webpack v4.10.1
