### ISSUE TITLE
Add debug option to place the require statement string as a comment on the same line

### ISSUE THREAD

**Issue by kentcdodds** [webpack/webpack#743]
I would love it if when I'm debugging I see this:

![screen shot 2015-01-30 at 3 57 11 pm](https://cloud.githubusercontent.com/assets/1500684/5984955/c227a184-a898-11e4-96f3-34bb040249d4.png)

Instead of just this:

![screen shot 2015-01-30 at 3 58 10 pm](https://cloud.githubusercontent.com/assets/1500684/5984968/d2ed22be-a898-11e4-89e3-b7f9d5a3a180.png)

:+1:

**Comment by sirlancelot** [comment]
In your webpack.config.js, add `exports.output.pathinfo = true`

**Comment by kentcdodds** [comment]
Huzzah! Just as good!

![screen shot 2015-01-30 at 4 05 04 pm](https://cloud.githubusercontent.com/assets/1500684/5985026/c79bfa9c-a899-11e4-8113-88f615e7dda3.png)

**Comment by kentcdodds** [comment]
Though, just as a side, it would be even cooler if it resolved my modules that were resolved using `moduleDirectories` with the full path...

**Comment by sirlancelot** [comment]
I honestly don't use `pathinfo` anymore and have switched to just using sourcemaps. Chrome & Firefox debuggers go right to the source file and I never even have to look at the webpack bundle.

**Comment by kentcdodds** [comment]
Yeah, I just use sourcemaps as well, however, when you're trying to debug `resolve` stuff, this is pretty handy. Thanks again for the tip :-)
