### ISSUE TITLE
webpack4 sideEffects:false cause compile error

### ISSUE THREAD

**Issue by AMDvsTMD** [webpack/webpack#7436]
when set sideEffects=false causes module.id==null then throw exceptions, how to solve that?

`RuntimeTemplate.moduleId(): Module D:\mobile-chat\node_modules\happypack\loader.js?id=jsx!D:\mobile-chat\node_modules\@xxx\configs\app\index.js has no id. This should not happen.`

**Comment by ooflorent** [comment]
It looks like you just deleted our [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template.
