### ISSUE TITLE
definition of the [contenthash] ?

### ISSUE THREAD

**Issue by lili21** [webpack/webpack#7438]
Can anyone tell me the definition of the `[contenthash]` which added in `webpack@4.3.0` ?

According to the [source code](https://github.com/webpack/webpack/blob/d2aca5638c2269fd00ef30e570953b3dc93711b7/lib/JavascriptModulesPlugin.js#L138), it's definitely not the the hash of the content(source code or bundle result).

But it should be the hash of the content, just works like [extract-text-webpack-plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/0b69b72aa7cf702a01a42a733432da5c344eed1c/src/index.js#L221). right ?

and why using `md4` algorithm while [loader-utils](https://github.com/webpack/loader-utils) using `md5` ?

**Comment by evilebottnawi** [comment]
@lili21 it is not QA. Better use gitter in future.
1. [contenthash] require for long term caching when bundle contain `css/wasm/etc`.
2. `md4` is faster than `md5`

Simple - yes it is just hash of content. Feel free to feedback.

**Comment by lili21** [comment]
> it is just hash of content?

what content ? source code ? no, it's not.

**Comment by lili21** [comment]
the way webpack create `contenthash`

```javascript
const hash = require('crypto').createHash('md4')

hash.update('ChunkTemplate')
hash.update('2')
hash.update('JsonpChunkTemplatePlugin')
hash.update('4')
hash.update('webpackJsonp')
hash.update('window')
hash.update(chunk.hash)

chunk.contentHash.javascript = hash.digest('hex').substr(0, 20)
```

**Comment by evilebottnawi** [comment]
@lili21 
> why loader-utils doesn't use the same algorithm ?

Work on this :+1: 

@lili21 it is was simple answer, building hashes more complex when just hash of content

**Comment by lili21** [comment]
using the word **contenthash** which was introduced by `extract-text-webpack-plugin`  while behaving total different, IMO, doesn't make sense and lead misunderstanding.

Hope there will be some document about this.

**Comment by z827101859** [comment]
@lili21 
I am confused about the way webpack create contenthash too .
if you realize why they do this way，can you give me a reply ?

**Comment by lili21** [comment]
@z827101859  I can't tell you why webpack do it this way, but I can show you how webpack do it.

src/index.js
---

```javascript
console.log('Hello, contenthash')
```

webpack.config.js
---

```javascript
module.exports = {
  mode: 'none',
  output: {
    filename: '[name].[contenthash].js'
  },
  optimization: {
    runtimeChunk: true
  }
}
```

First of all, webpack using `md4` algorithm to create hash by default.

```javascript
const hash = require('crypto').createHash('md4')
```

Secondly, I hope you're already familiar with the concept of `Chunk` and `Module`. For this example, we have a `main` chunk which contain the module `src/index.js`.  `Chunk` and `Module` both have the `hash` property. the good news is, we only need to figure out how `module.hash` be created, by now.

**how `module.hash` be created**

`module` also has a private property called `_buildHash`, and here is how it be generated.

```javascript
hash.update('source')
hash.update("console.log('Hello, contenthash')") // the source code
hash.update('meta')
hash.update('{}')
module._buildHash = hash.digest('hex')
```

and the `module.hash`

```javascript
hash.update(module._buildHash)
hash.update(`${module.id}`)
hash.update('null')
module.hash = hash.digest('hex')
```

Finally, the **contenthash**

```javascript
hash.update('ChunkTemplate')
hash.update('2')
hash.update('JsonpChunkTemplatePlugin')
hash.update('4')
hash.update('webpackJsonp') // output.jsonpFunction
hash.update('window') // output.globalObject
for (const module of chunk.modules) {
  hash.update(module.hash)
}
const contenthash = hash.digest('hex').substr(0, hashDigestLength) // by default hashDigestLength equal 20, you can configure by [name].[contenthash:8].js. notice the number 8 ?
```


we made it.

**Comment by lili21** [comment]
I simplify it a little. the final step would be little different depends on whether chunk has runtime or nor. Notice the `runtimeChunk: true` configuration? I'm splitting runtime chunk from the main chunk.

**Comment by z827101859** [comment]
@lili21 so，the final contenthash is not the hash of source code。
but in my opinion，[webpack-plugin-hash-output](https://github.com/scinos/webpack-plugin-hash-output) maybe more suitable as contenthash

**Comment by kimown** [comment]
@lili21 

thanks for your explanation.

I thought when I change to `md5`, after webpack emit files, we get bundle file `bundle.XXX.js`,  the hash `XXX` should equal  the result of `openssl dgst -md5 bundle.XXX.js`, but now it isn't not equal definitely, I know the reason, thanks.
