### ISSUE TITLE
Webpack stopped working after upgrading to 4.10.1 "RuntimeTemplate.moduleId(): Module ...  has no id. This should not happen."

### ISSUE THREAD

**Issue by finom** [webpack/webpack#7443]
# Bug report

**What is the current behavior?**

WP throws on build: 

```
ERROR in chunk main [entry]
assets/[name].js
/Users/finom/Work/djavan-front-end/open-source/import-glob-webpack-loader/index.js!/Users/finom/Work/djavan-front-end/node_modules/babel-loader/lib/index.js!/Users/finom/Work/djavan-front-end/src/components/entities/ClientForm/FocalsArray/FocalForm.js
RuntimeTemplate.moduleId(): Module /Users/finom/Work/djavan-front-end/open-source/import-glob-webpack-loader/index.js!/Users/finom/Work/djavan-front-end/node_modules/redux-form/es/reduxForm.js has no id. This should not happen.
```

![image](https://user-images.githubusercontent.com/1082083/40681558-26827354-6392-11e8-91e0-9412f4ebe88f.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

Don't know how to reproduce yet. The temporary fix was to downgrade back to 4.9.1. Config is split into many small files don't know would that be useful to paste them all there. Let me know if it is.

**What is the expected behavior?**

It should build without the error.

**Other relevant information:**
webpack version:  4.10.1
Node.js version: 10
Operating System: MacOS
Additional tools: Babel, React and stuff

**Comment by christiango** [comment]
Can confirm that I'm also seeing this issue on one of my webpack configs. Also had to revert back to 4.9.1

**Comment by jeremy-clearlabs** [comment]
Appears to be related to #7425.
