### ISSUE TITLE
Hook for modifying entrypoint from plugin

### ISSUE THREAD

**Issue by whs** [webpack/webpack#7452]
## Feature request

**What is the expected behavior?**
There should be a function that allow entrypoint to be changed after the compiler is created, but before compilation has started.

**What is motivation or use case for adding/changing the behavior?**
See [this issue in webpack-serve](https://github.com/webpack-contrib/webpack-serve/issues/156#issuecomment-393177870). In short, iterating entrypoints from a compiler, process, and calling `compiler.hooks.entryOption` with the new value does not works well with `runtimeChunk: single` as the old entrypoint plugin will still exists.

**How should this be implemented in your opinion?**
- Plan A: Creating a registry of active entrypoint plugin instances (MultiEntryPlugin/SingleEntryPlugin/DynamicEntryPlugin), then when EntryOptionPlugin trigger again:
  - A: Ask the old instance of the same entrypoint to deregister.
  - B: Recreate all instances. This allow entrypoints to be removed, but caller now has to send list of ALL entrypoints which is a breaking change.
- Plan B: Investigate in why RuntimeChunkPlugin does not work with duplicated entrypoints. This might resolve this issue, but could run into more issues in the future.

**Are you willing to work on this yourself?**
If I have some guideline.

**Comment by shellscape** [comment]
IMHO it's flawed that creating a compiler instance automatically creates and applies entry plugins at that point in the process. There are some reasons for it as I understand it, but it's still flawed. I'd also consider it a flaw that we cannot examine or modify entrypoints after the chosen type of entry plugin has been applied. Too much black-box here.
