### ISSUE TITLE
wasm: element segment with get_global as offset refering to an imported global

### ISSUE THREAD

**Issue by xtuc** [webpack/webpack#7454]
# Bug report

**What is the current behavior?**

The module:
```wat
(module
  (global (import "spectest" "global_i32") i32)
  (table 1000 anyfunc)
  (func $f)
  (elem (get_global 0) $f)
)
```

will be transformed to:

```wat
(module
  (global (mut i32) (i32.const 1))
  (table 1000 anyfunc)
  (func $f)
  (elem (get_global 0) $f)
)
```

which isn't valid because initializer expression cannot reference a mutable global.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

It's similar to #7413 but the solution is not the same.

We should probably start inlining values at build-time. Maybe we can do it for every imported globals, @sokra what do you think?

**Comment by sokra** [comment]
You can't put an `i32` in a `anyfunc` table anyway. No other table type is in the spec currently.

**Comment by xtuc** [comment]
My idea is to inline the value, like:

```wat
(module
  (global (mut i32) (i32.const 1))
  (table 1000 anyfunc)
  (func $f)
  (elem (i32.const 666) $f)
)
```

we could use this technique for every global import since we have access to the JS source. Getter are not called anyway. Do you know any edge case with this technique?

**Comment by sokra** [comment]
We may need to drop the global handling anyway, because of two reasons:

* Globals have now changed with the mutable globals proposal merged
* The ESM-integration spec may not allow importing globals from JS.

**Comment by xtuc** [comment]
I think we can even close this.

> The ESM-integration spec may not allow importing globals from JS.

What do you mean? Based on https://github.com/WebAssembly/esm-integration/pull/21 it will.

**Comment by sokra** [comment]
> > The ESM-integration spec may not allow importing globals from JS.
> 
> What do you mean? Based on [WebAssembly/esm-integration#21](https://github.com/WebAssembly/esm-integration/pull/21) it will.

I said "may". It's not merged yet, it's still a proposal, and I hope importing non-functions from JS will be disallowed by spec. That simplify a lot of stuff and is better for performance anyway.

**Comment by sokra** [comment]
> I hope importing non-functions from JS will be disallowed by spec.

I don't want to despise the work you put into making globals work, it's great, but even better if we don't need that complexity.

**Comment by xtuc** [comment]
No worries, our work is used for experimenting and helped make the proposal move forward, so I really don't mind. More importantly I want to have the right behavior.

> That simplify a lot of stuff and is better for performance anyway

For performance, calling a function is quite expensive since it requires translation between JS and Wasm types. On the other hand constant values are copied and used natively, which is faster.
