### ISSUE TITLE
AggressiveSplittingPlugin does not work after v4.6.0 

### ISSUE THREAD

**Issue by BarryYan** [webpack/webpack#7455]
# Bug report

**What is the current behavior?**
webpack AggressiveSplittingPlugin config:
```js
new webpack.optimize.AggressiveSplittingPlugin({
      minSize: 50000,
      maxSize: 240000
    })
```
when I updated webpack from v4.6.0 to 4.10.2, I fund the same config for `AggressiveSplittingPlugin` didn't work, so I roll back to v4.6.0, it worked well. I updated to v4.7.0, it's wrong again. 
I saw `AggressiveSplittingPlugin.js` file after v4.6.0 commits, there was just some code style changed. 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
AggressiveSplittingPlugin can split big chunk into many small chunks.

**Other relevant information:**
webpack version:  4.7.0 ~4.10.2
Node.js version:  10.0.0
Operating System: Mac OS X 10_13_4
Additional tools:

**Comment by superlbr** [comment]
when set maxSize > 0 (in config.optimization.splitChunks), there will be an error
> demo

https://codesandbox.io/s/m7vrn8q32y

> error
```
/Users/dva/admin/node_modules/webpack/lib/util/deterministicGrouping.js:168
                                leftSize += group.nodes[left].size;
                                                              ^

TypeError: Cannot read property 'size' of undefined
    at module.exports (/Users/dva/admin/node_modules/webpack/lib/util/deterministicGrouping.js:168:35)
    at compilation.hooks.optimizeChunksAdvanced.tap.chunks 
    ...
error Command failed with exit code 1.
```

**Comment by alexander-akait** [comment]
For v5 - `AggressiveSplittingPlugin is deprecated in favor of SplitChunksPlugin` and see https://github.com/webpack/webpack/pull/7651, let's close, feel free to feedback
