### ISSUE TITLE
Misleading error if require expression finds no files

### ISSUE THREAD

**Issue by SystemParadox** [webpack/webpack#7457]
# Bug report

**What is the current behavior?**

If a require expression is used which finds no files, webpack replaces the entire require statement with a `webpackMissingModule` error function, but error text shows only the first part of the expression.

This message is very misleading. I found this especially difficult to debug because I had a require expression looking in a `modules` directory, but I also had a `modules.js` file.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create client.js:

```js
function loadModule(name) {
    require('./modules/' + name + '/client.js');
}
loadModule('foo');
```

2. `mkdir modules`
3. `webpack --entry ./client.js --output-filename bundle.js`
4. Observe that the `bundle.js` contains:

```js
!(function webpackMissingModule() { var e = new Error("Cannot find module \"./modules\""); e.code = 'MODULE_NOT_FOUND'; throw e; }())
```

5. Observe that the code throws a very confusing error:

```js
loadModule('foo');
// Cannot find module "./modules"
```

**What is the expected behavior?**

The require expression should be replaced with a require context as usual, and should give meaningful error messages:

```js
loadModule('foo');
// Cannot find module "./modules/foo/client.js"
```

**Other relevant information:**

webpack version:  3.12.0
Node.js version:  6.14.1
Operating System: Linux

**Comment by sokra** [comment]
yep this should be fixed. Do you want to send a PR?

**Comment by mc-zone** [comment]
I'd like to do this, but it seems to work well in v4. Should we add a fix for v3?

**Comment by arkadyt** [comment]
@sokra, I confirm what @mc-zone have said.
v4 outputs `Error: Cannot find module './foo/client.js'`.
Should we add fix for a v3?

**Comment by SystemParadox** [comment]
If it's fixed in v4 I am happy if you want to close this issue. Thanks.

**Comment by sokra** [comment]
No we don't need a fix for v3.
