### ISSUE TITLE
wasm: allow import memory

### ISSUE THREAD

**Issue by xtuc** [webpack/webpack#7458]
## Feature request

**What is the expected behavior?**

Loader can enhance wasm features by accessing the memory of a module directly.

Take the following example (uses holyc):

```c
#include <webassembly.h>
#include <webassembly/console.h>

export void test() {
    console_log("test");
}
```

most of the backends for wasm, including LLVM one, will emit code similar to:

```wat
(module
  (import "holycjs" "console_log" (func $console_log (param i32)))
  (memory $0 1)
  (data (i32.const 16) "test\00")
  (export "memory" (memory $0))

  (func
    (call $console_log
      (i32.const 16) ;; address in memory
    )
  )
)
```

The consequence is that the JS function `console_log` has to deal with the pointer to get the string ([example](https://github.com/xtuc/holyc/blob/5606efc950d2bd8624fbdb75b24db9061cb79fad/lib/js/index.js#L31-L36)).

**What is motivation or use case for adding/changing the behavior?**

A workaround: using a mutable state the user can pass the memory after the instantiation manually.

```js
// holycjs:
let memory;

module.exports = {
  init(m) { memory = m }
}

// user.js:
const {init} = require("holycjs");

import("./add.c").then(({add, test, memory}) => {
  init(memory);
  // ...
});
```

Impacts rust-bindgen, emscripten or Golang and the current API is not user-friendly.

**How should this be implemented in your opinion?**

A JavaScript module should be able to declare the memory and exposes it to a wasm module. Once that we have multiple memories it will be safer as well.

The module would look like that:

```wat
(module
  (import "holycjs" "console_log" (func $console_log (param i32)))
  (import "holycjs" "memory" (memory 1))
  (data (i32.const 16) "test\00")

  (func
    (call $console_log
      (i32.const 16) ;; address in memory
    )
  )
)
```

The user won't need to pass the memory, it will be handled by Webpack under the hood.

An Implementation I have in mind is: if a wasm module import a memory and a JavaScript module exposes one, Webpack can move the js declaration in its runtime and rewrire everything. 

**Are you willing to work on this yourself?**
yes

**Comment by fitzgen** [comment]
FWIW, with `wasm-bindgen`, compiling the `dobble` Rust crate to wasm gives both the `dobble.js` JS bindings to the crate and `dobble_bg.wasm` raw wasm file. The memory for the wasm can be imported from the wasm in JS like this:

```js
import { memory } from "./dobble_bg";
```

In fact, we do this in the Rust+Wasm Game of Life tutorial:

https://github.com/rustwasm/wasm_game_of_life/blob/3253fa3a1557bdb9525f3b5c134b58efa1041c55/index.js#L2

https://github.com/rustwasm/wasm_game_of_life/blob/3253fa3a1557bdb9525f3b5c134b58efa1041c55/index.js#L103

**Comment by sokra** [comment]
see also #7462 

https://github.com/webpack/webpack/blob/530e1fb172be65c4a4107f4d48961c7a19cf2632/test/cases/wasm/two-files-loader/wrapper-loader.js#L1-L17

**Comment by fitzgen** [comment]
> @fitzgen yes, but that's actually not working in Webpack right now. When you will import the .wasm binary it will be managed (wiring imports and instantiating) by Webpack.

Did this just recently break then? Is this the same thing that broke the wasm-bindgen tests? Because it definitely worked when I wrote that tutorial ;)

> Ideally instead of having JS -> wasm, we are enforcing wasm -> JS*.

I don't understand what this means, could you explain a little more?

**Comment by xtuc** [comment]
> Did this just recently break then? Is this the same thing that broke the wasm-bindgen tests? Because it definitely worked when I wrote that tutorial ;)

My answer isn't super accurate, sorry. The issue is when you have imports in wasm, Webpack will consider them being like JavaScript modules, so a file and a named export. Ideally https://github.com/rustwasm/wasm-bindgen/issues/185. 

> Ideally instead of having JS -> wasm, we are enforcing wasm -> JS*.

Instead of having a JS entrypoint that manages the wasm module, we could let Webpack manages the wasm module which then imports JS functions. 

That's more features proof, allowing other wasm import and I believe that's simpler.

**Comment by alexcrichton** [comment]
It seems that anecdotally it's pretty rare for wasm modules to import their memory seemingly making this a somewhat niche feature, but with the upcoming threads proposal for WebAssembly I think that one of the more idiomatic things to do is to have memory imported to ensure the exact same `SharedArrayBuffer` can be shared amongst all wasm instances on all threads.

To that end I was trying to get support in Rust for the upcoming threads proposal and quickly ran into this. The tooling I'm working with, `wasm-bindgen`, handles all the memory pieces itself, so it basically looks like a JS file that exports a `WebAssembly.Memory` which is then imported by a wasm file.

@xtuc is there perhaps something I could do to help out w/ this?

**Comment by xtuc** [comment]
We could take advantage of https://github.com/webpack/webpack/pull/7462 (I've haven't really look into it yet, sorry...), we can probably hide it in our plugin/loader.
