### ISSUE TITLE
Error bundling q.js

### ISSUE THREAD

**Issue by cowwoc** [webpack/webpack#747]
1. Clone https://github.com/cowwoc/webpack-q.js
2. Run "gulp build" in the root directory
3. You should get this output:

```
[23:09:31] Using gulpfile ~\Documents\webpack-q.js\Gulpfile.js
[23:09:31] Starting 'package'...
[23:09:32] Compiling webpack config ~\Documents\webpack-q.js\gulp\webpack.config.js
[23:09:32]
Time: 137ms
   Asset   Size  Chunks             Chunk Names
Index.js  66710       0  [emitted]  Index

ERROR in (webpack)/~/node-libs-browser/~/timers-browserify/main.js
Module not found: Error: Cannot resolve 'file' or 'directory' C:\Users\Gili\Documents\webpack-q.js\node_modules\webpack\node_modules\node-libs-browser\node_modu
les\process\browser.js/browser.js in C:\Users\Gili\Documents\webpack-q.js\node_modules\webpack\node_modules\node-libs-browser\node_modules\timers-browserify
 @ (webpack)/~/node-libs-browser/~/timers-browserify/main.js 1:15-44

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Webpack cannot compile config
    at DestroyableTransform.<anonymous> (C:\Users\Gili\Documents\webpack-q.js\node_modules\gulp-webpack-build\index.js:170:23)
    at DestroyableTransform.g (events.js:180:16)
    at DestroyableTransform.emit (events.js:117:20)
    at C:\Users\Gili\Documents\webpack-q.js\node_modules\gulp-webpack-build\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16
    at process._tickCallback (node.js:442:13)
```

Focusing on `ERROR in (webpack)/~/node-libs-browser/~/timers-browserify/main.js`, I have two questions:

1. Why am I getting this error message? Meaning, it's not clear that I'm doing anything wrong.
2. Is there a way to improve the stack-trace for this kind of error so it includes the user code that requires q.js? (It took me a long time to track down the problem because of this vague stack-trace)

**Comment by mdreizin** [comment]
@sokra Could you please clarify?

`stats` object has some errors/warnings on `windows` environment, but it works fine without any errors/warnings on `os x`.

**Comment by sokra** [comment]
You removed all defaults from `resolve.root` and `resolve.modulesDirectories`. So it doesn't try to look in `node_modules` and doesn't find the `process` module. (The error message is a bit confusing...)

The defaults in `webpack-config`: https://github.com/mdreizin/webpack-config/blob/master/lib/config.js#L17-L18 :cry:

**Comment by cowwoc** [comment]
@sokra I'm a bit confused. The defaults you linked to are empty arrays. Why would removing them cause a problem?

And also, why would this issue be OS-specific?

**Comment by mdreizin** [comment]
@sokra Thanks a lot! I will fix that.

**Comment by cowwoc** [comment]
Oh, I see. I didn't realize that @sokra was pointing to code in gulp-webpack-build. I thought the defaults were coming from webpack itself.

Closing this issue as it is fixed by https://github.com/mdreizin/webpack-config/issues/1

**Comment by max-mykhailenko** [comment]
Have similar problem with reflux https://github.com/spoike/refluxjs when I add it to entry

```
ERROR in (webpack)/~/node-libs-browser/~/timers-browserify/main.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/max/Work/Projects/kata.im/build/node_modules/webpack/node_modules/node-libs-browser/node_modules/process/browser.js/browser.js in /Users/max/Work/Projects/kata.im/build/node_modules/webpack/node_modules/node-libs-browser/node_modules/timers-browserify
 @ (webpack)/~/node-libs-browser/~/timers-browserify/main.js 1:15-44
```

When I can download updated version of webpack?

**Comment by cowwoc** [comment]
@max-mykhailenko The reported issue was actually a problem in the `gulp-webpack-build` plugin, not in webpack itself.
