### ISSUE TITLE
Chunks loading from multiple bundles interfer with each other

### ISSUE THREAD

**Issue by VincentBailly** [webpack/webpack#7474]
# Bug report

When two different webpack bundles are running on the same page and both use chunks, the loading of the chunks of one bundle makes the loading of the chunks of the other bundle fail.
This is due to the fact that both bundle use the same function to load their chunks (window.webpackJsonp)

**If the current behavior is a bug, please provide the steps to reproduce.**

Steps to reproduce:
- Clone this repo: https://github.com/VincentBailly/WebpackChunkBugRepro
- Run `yarn`, then `yarn build`
- start a server to serve index.html and the js bundles
- observe the bundle2 failing in the console due to the bundle1

**What is the expected behavior?**

The expected behavior is that the bundle 2 should run the same way whether bundle1 is executed or not.

**Other relevant information:**
webpack version:  4.10.2
Node.js version: 9.11.1
Operating System: Windows 10
Additional tools: yarn

**Comment by sokra** [comment]
You can (must) change the function name if using multiple different bundles on the same page -> `output.jsonpFunctionName`

**Comment by ooflorent** [comment]
Please use `output.jsonpFunction` to avoid conflicts.
