### ISSUE TITLE
Webpack emits unused functions in production mode

### ISSUE THREAD

**Issue by mgroenhoff** [webpack/webpack#7475]
# Bug report

**What is the current behavior?**
Webpack emits unused functions in production mode.

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
// a.js
console.log("a");
export function a1() {
    console.log("a1");
}
export function a2() {
    console.log("a2");
}
```
```js
// b.js
import * as a from "./a";
export { a };
```
```js
// index.js
import { a } from "./b";
a.a1();
```
```js
// webpack.config.js
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
module.exports = {
    optimization: {
        minimizer: [
            new UglifyJsPlugin({
                uglifyOptions: {
                    mangle: false,
                    output: {
                        beautify: true
                    }
                }
            })
        ]
    }
};
```
Running `webpack -p index.js` results in:
```js
// ... omitted webpack header ...
}([ function(module, __webpack_exports__, __webpack_require__) {
    "use strict";
    __webpack_require__.r(__webpack_exports__);
    var a_namespaceObject = {};
    function a1() {
        console.log("a1");
    }
    function a2() { // <-- this function is not referenced anywhere
        console.log("a2");
    }
    __webpack_require__.r(a_namespaceObject), __webpack_require__.d(a_namespaceObject, "a1", function() {
        return a1;
    }), __webpack_require__.d(a_namespaceObject, "a2", function() { // <-- yet this is generated
        return a2;
    }), console.log("a"), a_namespaceObject.a1();
} ]);
```

But if I run this with `rollup -f iife index.js` the result is:
```js
(function () {
    'use strict';
    console.log("a");
    function a1() {
        console.log("a1");
    }
    a1();
}());
```

**What is the expected behavior?**
It should omit the `a2` function entirely

**Other relevant information:**
webpack version:  4.10.2
Node.js version: 9.4.0
Operating System: Win 10
Additional tools: N/A

**Comment by evilebottnawi** [comment]
@mgroenhoff please provide you babel config

**Comment by mgroenhoff** [comment]
@evilebottnawi it is included

**Comment by evilebottnawi** [comment]
@mgroenhoff please provide **.babelrc** content, looks you use have `"modules": true`

**Comment by mgroenhoff** [comment]
Oh sorry I thought you said webpack config... my bad. I do not use babel so it is not generated code.

**Comment by sokra** [comment]
Yep this doesn't optimize yet. Best avoid using namespace objects (`import * as a`) directly (without property access).

**Comment by evilebottnawi** [comment]
@sokra good catch.
@mgroenhoff Also tree shaking it not job of `uglify`.

**Comment by sokra** [comment]
Note: [this case](https://rollupjs.org/repl?version=0.59.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGElMjAlN0QlMjBmcm9tJTIwJTVDJTIyLiUyRmIlNUMlMjIlM0IlNUNuYS5hMSgpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwKiUyMGFzJTIwYSUyMGZyb20lMjAlNUMlMjIuJTJGYSU1QyUyMiUzQiU1Q25leHBvcnQlMjAlN0IlMjBhJTIwJTdEJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyY29uc29sZS5sb2coJTVDJTIyYSU1QyUyMiklM0IlNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjBhMSgpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGNvbnNvbGUubG9nKCU1QyUyMmExJTVDJTIyKSUzQiU1Q24lNUN0JTIwJTIwdGhpcy5hMigpJTNCJTVDbiU3RCU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMGEyKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc29sZS5sb2coJTVDJTIyYTIlNUMlMjIpJTNCJTVDbiU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==) also need to be considered.

**Comment by mgroenhoff** [comment]
@sokra Is the 'this' in this.a2() intentional?

**Comment by sokra** [comment]
yep

**Comment by mgroenhoff** [comment]
@sokra
If you would run your example in node with `--experimental-modules`, or in the browser with `type="module"`, `this` is indeed referring to the module itself but the way rollup generates its bundles, `this` will always be undefined so it is correct to remove the `a2` function. I wonder if what rollup generates is intended or a bug.

Webpack however correctly handles that `this` and it resolves to the module and it is correct to retain `a2` if it is referenced. It can be removed though if nothing in the module directly references `this.a2`. But then you maybe also want to keep it if `this` is being returned somewhere or referenced (think `Object.keys(this).includes("a2")`.

Is this an optimization that can be made in Webpack?
