### ISSUE TITLE
Dynamic Import Json (Splitted Chunk) returns string instead

### ISSUE THREAD

**Issue by SoaresMG** [webpack/webpack#7480]
# Bug report

**What is the current behavior?**

Dynamic Imports with Json's are returning .js files.
Added file-loader to preserve the json using the following configuration

```
{
    test: /\.json$/,
    type: "javascript/auto",
    loader: "file-loader",
    options: { name: "i18/[name].[ext]" },
    include: [
        path.resolve(__dirname, "../src"),
    ],
},
```

With this the `.json` keeps intact as shown in the following image:

![capture4](https://user-images.githubusercontent.com/8335203/40971944-0dfbbd8e-68b7-11e8-9d4e-8b2f6e36a0b0.PNG)

In the image you can see `i18n.<...>` files being created, it's a proxy to the `.json` files. 
It contains the following:

```
(window.webpackJsonp = window.webpackJsonp || [])
    .push(
        [[2], {
            "./src/translations/i18n/en-US.json": function (n, o, s) {
                n.exports = s.p + "i18/en-US.json"
            }
        }]
    );
```

In Source code i'm calling the file like this:

```
/* This loading must be async, it will load the file from the server on-demand */
export const getLanguageFile = async (lang = "en-US") 
   => await import(/* webpackChunkName: "i18n." */ `../i18n/${lang}.json`);
```

**What is the expected behavior?**

Without `file-loader` the chunk is well created and the file loads fine, however I need to keep it to read from the `.json` instead of the `.js`.

My function `getLanguageFile` which loads the file, returns the following:

![capture5](https://user-images.githubusercontent.com/8335203/40972150-b84e6264-68b7-11e8-9a80-734f21a63fc7.PNG)

I was expecting the `.json` file to be returned instead of a string..

**Other relevant information:**
webpack version:  4.10.1
Node.js version: 6.9.5
Operating System: Win 10 Pro (Latest Updates)
Additional tools: 
- Babel-loader: 7.1.4
- File-loader: 1.1.11

**Comment by SoaresMG** [comment]
Yesterday I created a post in [SO](https://stackoverflow.com/questions/45149010/why-is-file-loader-working-for-images-and-videos-but-not-for-audio-file-in-my-re) with no success.

**Comment by ooflorent** [comment]
I think you should remove these lines:

```js
type: "javascript/auto",
loader: "file-loader",
```

**Comment by SoaresMG** [comment]
If I remove it, it works but I need those .json's, it may be edited in the server (aspnet core)

**Comment by sokra** [comment]
That works correctly. `import()` returns a ESM namespace object, which only contains the `default` export for CJS modules (the file-loader emits a CJS module).

**Comment by SoaresMG** [comment]
So... that means that what I'm trying to do, isn't possible this way?
If so, I'll try another approach...

**Comment by SoaresMG** [comment]
If anyone coming here for a similar situation and is interested in the solution, verify my [SO](https://stackoverflow.com/questions/50686102/webpack-es6-load-json-with-dynamic-import-preserve-json-file) answer.

Instead of using `import()` I just made a request to the file.

But there was a problem, I still needed the files to be in the dist folder.

To do that, I used `copy-webpack-plugin`, with this you can dump files and folders to anywhere during the bundling process.

I removed my json rule, and added the plugin like this:

`new CopyWebpackPlugin([{ from: "src/translations/i18n", to: "i18n" }]),`
Dumping the i18n folder into the dist:

![S1](https://i.stack.imgur.com/vrW6G.png)

After this, I changed my function `getLanguageFile` to:

```
export const getLanguageFile = async (lang = "en-US") 
   => (await axios.get(`/i18n/${lang}.json`)).data;
```

This will return the file as json and it all works perfectly.

**Note**

Development build: webpack-dev-server (Server) + ASP.Net Core (API)

Production build: ASP.Net Core (Server and API)
