### ISSUE TITLE
Can't find package @webassemblyjs/helper-code-frame's version: 1.5.10

### ISSUE THREAD

**Issue by aa1011372655** [webpack/webpack#7481]
webpack version:  4.11.0
Node.js version: v8.5.0
Operating System: mac
Additional tools:
I failed to install webpack@4.11.0 ，because this is error："Can't find package @webassemblyjs/helper-code-frame's version"
I find @webassemblyjs/helper-code-frame module，but it is null
Don't know if this is a bug or not，Hope to reply, thank you very much

**Comment by xtuc** [comment]
The version exists on npm: https://www.npmjs.com/package/@webassemblyjs/helper-code-frame/v/1.5.10.

It's likely due to a proxy or npm registry mirror?

**Comment by aa1011372655** [comment]
@xtuc @evilebottnawi  , thanks，it's OK now，May be mirroring sync problem
