### ISSUE TITLE
Parse `evaluate` hook does not capture all expression evaluations

### ISSUE THREAD

**Issue by nehz** [webpack/webpack#7484]
**What is the expected behavior?**
The hook seems to miss quite a few events

**What is motivation or use case for adding/changing the behavior?**
`evaluate` hook should capture all expression events

**How should this be implemented in your opinion?**
```
walkExpression(expression) {
   this.hooks.evaluate.for(expression.type).call(expression)
   ...
}
```
and removing it from `evaluateExpression ()`

Thought I am not quite sure on the internals of walkExpression vs evaluateExpression, so maybe just a new hook type would be better

**Are you willing to work on this yourself?**
yes, with guidance

**Comment by nehz** [comment]
Updated original post

**Comment by ooflorent** [comment]
Can you give an example of what you are trying to do and how you use the _evaluation_ feature of the parser?

**Comment by nehz** [comment]
file_to_parse.js:
```
calling()
```

```
class TestPlugin {
  apply (compiler) {
    compiler.hooks.normalModuleFactory.tap('TestPlugin', factory => {
      let handler = (parser, options) => {
        parser.hooks.evaluate.for("CallExpression").tap('TestPlugin', node => {
          if (node.callee.type === 'MemberExpression') {
            console.log('CALL', `${node.callee.object.name}.${node.callee.property.name}`)
          } else {
            console.log('CALL', node.callee.name)
          }
        })
      }
      factory.hooks.parser.tap('javascript/auto', 'TestPlugin',  handler)
      factory.hooks.parser.tap('javascript/dynamic', 'TestPlugin',  handler)
      factory.hooks.parser.tap('javascript/esm', 'TestPlugin',  handler)
    })
  }
}
```

If you add the call in `walkExpression` the above works

**Comment by ooflorent** [comment]
Are you sure that `evaluate` is what you are looking for? `evaluate` hook is called when an expression needs to be evaluated. In the above example, webpack won't try to evaluate `calling()`. However, you can _catch_ the call using `call` hook.

**Comment by nehz** [comment]
The hooks are only useful if you know what you are looking for, e.g the name of the method "calling", e.g `hooks.call.for("calling")...` however if you want to parse all calls in the module this can't be done this way.

Also I was assuming the `evaluate` hook meant walking into an expression? If this is not the case what does "evaluating" mean in the context of parsing and walking the ast ?

**Comment by ooflorent** [comment]
> If this is not the case what does "evaluating" mean in the context of parsing and walking the ast?

When walking the AST, webpack tries to optimize which branches must be traversed by pruning the dead ones. Let's consider the following program:

```js
if (calls > 2) {
  // …
} else {
  // …
}
```

webpack will _evaluate_ the test:

1. Enters `walkIfStatement`
1. Calls `this.hooks.statementIf`
    1. `ConstPlugin` hook get called
    1. Uses `Parser#evaluateExpression` to get a _basic evaluator_
    1. Optimizes the _output source code_ is possible
1. If a decision has been made, ignore the dead branch

`Parser#evaluateExpression` is what is starting the evaluation. If the method isn't called, nothing gets evaluated. If you call it over a `CallExpression`, then `hooks.evaluate.for("CallExpression")` is fired.

> Also an unrelated question, does modifying the ast (from `hooks.program`) get propagated down stream, so e.g babel/uglify will pick up changes?

Yes and no. webpack parses your file twice, at most. The first parsing retrieves the AST and traverses it to **apply source changes**. The AST is memoized but it isn't modified. Every change happens on the source code to avoid _recasting_ the AST. When _module concatenation_ is enabled, the newly generated file is parsed to enable scope analysis.

So let's recap:

- If you change the AST, it will be picked up by _post loaders_ (Babel runs before `Parser`)
- Modifying the AST affects the traversal but would most likely break the codegen

**Comment by nehz** [comment]
Cool thanks for taking the time in explaining `evaluate`! 

I am guessing then that Babble does it's own parsing with it's own internal AST as it is run before Parser?

How would you go about modifying the source in response to Parser events? I am guessing there is some dirty watch that triggers a 2nd AST pass if the source is modified during the 1st pass?

**Comment by ooflorent** [comment]
> I am guessing then that Babble does it's own parsing with it's own internal AST as it is run before Parser?

That’s correct.

> How would you go about modifying the source in response to Parser events?

Having a look at `lib/ConstPlugin.js` may be a good start. I’m closing this issue since the answer to the original question has been provided. Feel free to continue the conversation here if it does not turn into a dedicated support channel :wink:
