### ISSUE TITLE
Version > 4.9 does not generate WASM module correctly

### ISSUE THREAD

**Issue by kayleg** [webpack/webpack#7485]
# Bug report

**What is the current behavior?**

When using a version above 4.8 and if the module is importing multiple JS functions the resulting `.wasm` module has an invalid structure and the browser will error with `expected valid import module name`.

**If the current behavior is a bug, please provide the steps to reproduce.**

The following example builds fine using 4.8 but not when using the latest:

https://github.com/rustwasm/wasm-bindgen/tree/master/examples/console_log

If you comment out the additional `#[wasm_bindgen]` on the console log binding functions so only one is being included the module will build correctly.

**What is the expected behavior?**

The generated module should be valid for a browser to understand.  

**Other relevant information:**
webpack version:  4.10
Node.js version: 10.0.0
Operating System: Mac OS 10.13.4
Additional tools: Firefox Nightly, Rust Nightly, wasm-bindgen 0.2.11

**Comment by xtuc** [comment]
Does it work using 4.9? We introduced a mangle feature in 4.10 IRC which causes that error.

**Comment by kayleg** [comment]
Yes 4.9 - works

**Comment by sokra** [comment]
see #7487

**Comment by xtuc** [comment]
The `console_log` example works now.
