### ISSUE TITLE
ReactNative target

### ISSUE THREAD

**Issue by sokra** [webpack/webpack#749]
_We need Hot Module Replacement for ReactNative._

List of things needed:
- Mechanism to load and eval JS code from a remote server. (something similar to XHR and eval on ReactNative)
- Mechanism to notify the runtime about updates. (something similar to WebSockets or TcpSocket on ReactNative)

cc @Vjeux @gaearon

**Comment by jhnns** [comment]
Nice :+1:

**Comment by nelix** [comment]
What about sending unix signals?
