### ISSUE TITLE
Webpack removes code that shouldn't be removed in mode=production

### ISSUE THREAD

**Issue by sod** [webpack/webpack#7491]
Followup to https://github.com/webpack/webpack/issues/7425

## Issue
mode=development & mode=proudction behave differently with import exports over multiple modules.

## Reproduction:
https://github.com/sod/webpack-issue-7425

Clone the reproduction branch, do `npm install` and do:
* `npm run prod` => See in http://localhost:3000 console that Observable.prototype.skip is `undefined`
* `npm run dev` => See in http://localhost:3000 console that Observable.prototype.skip is defined

The source code has the dependencies `"rxjs": "^6.2.0"` & `"rxjs-compat": "^6.2.0"` and the entry file contains:

```javascript
import 'rxjs/add/operator/skip';
import {Observable} from 'rxjs';

console.log('Observable.prototype.skip:', Observable.prototype.skip);
```

Btw., changing `import 'rxjs/add/operator/skip';` to `import 'rxjs-compat/add/operator/skip';` fixes the prod mode.

Mabe these changes in the release notes of webpack 4.10 introduced this issue?

> webpack v4.10.0
> Bugfixes
>   side-effect-free modules referenced by export * from are no longer including in the bundle
>   the side-effects optimization is now possible in incremental compilation

**What is the expected behavior?**
Prod mode should also import and execute the import.

**Other relevant information:**
webpack version:  4.11.1
Node.js version: 8.11.1
Operating System: macOS

**Comment by sokra** [comment]
rxjs explicitly says that these import can be skip:

https://github.com/ReactiveX/rxjs/blob/47665fd619add032caeceaeb69246a6110658b41/package.json#L6

This means no module has side-effects (expect for the exports) so `import 'rxjs/add/operator/skip';` can be skipped.

**Comment by sokra** [comment]
Maybe this is the better choice?

``` js
"sideEffects": [
  "./add/**"
]
```

**Comment by sod** [comment]
So the sideEffects:false is incorrect as soon as I use rxjs-compat because rxjs-compat causes side effects upon rxjs? Interesting.

Could the tree shake plugin emit a warning as soon as a module thats configured as `"sideEffects":false` imports another module thats not explicitly declared side effect free?

**Comment by sokra** [comment]
> Could the tree shake plugin emit a warning as soon as a module thats configured as "sideEffects":false imports another module thats not explicitly declared side effect free?

no sorry, this is explicitly allowed. i. e. component.js imports styles.css. styles.css has side-effects (adding styles to the dom), but component.js can still be side-effect-free. This way it hides the side-effects of the styles. So when not using the component exports, styles are also not added.
