### ISSUE TITLE
Some badges are broken in the README

### ISSUE THREAD

**Issue by ooflorent** [webpack/webpack#7497]
# Bug report

**What is the current behavior?**

Some badges are broken in `README.md`.

**If the current behavior is a bug, please provide the steps to reproduce.**

Open [webpack's README](https://github.com/webpack/webpack).

<img width="608" alt="broken badges" src="https://user-images.githubusercontent.com/168498/41085007-fbafd004-6a35-11e8-97ec-44b53c645882.png">

**What is the expected behavior?**

Badges should be correctly displayed.

**Comment by waterfoul** [comment]
They all appear to be working for me

**Comment by ooflorent** [comment]
You're right. Things got back to normal!
