### ISSUE TITLE
Comparison Page Table is Very Difficult to View

### ISSUE THREAD

**Issue by machineghost** [webpack/webpack#7503]
**What is the current behavior?**

Goto https://webpack.js.org/comparison/ see a giant table ... but you can't actually see most of the table because the scroll bars are several pages down, and if you try to use them you've already lost whatever it was you were trying to scroll to see at the top of the table.

**If the current behavior is a bug, please provide the steps to reproduce.**
See above.

**What is the expected behavior?**

Either:

A) Remove CSS truncation code and let the browser do the scrolling as God intended, or

B) Use the appropriate table tags so that the table body scrolls naturally, but the table headers are always visible, then cap its height at the page's height.

**Other relevant information:**

Browser: Latest Chrome

**Comment by evilebottnawi** [comment]
@webpack-bot mote to webpack/webpack.js.org

**Comment by machineghost** [comment]
>I've moved it to webpack/webpack.js.org.

Ah, my mistake; thanks.
