### ISSUE TITLE
`cacheGroups` overrides `libraryTarget` output in webpack4

### ISSUE THREAD

**Issue by smokir** [webpack/webpack#7506]
# Bug report

**What is the current behavior?**

When both options `optimization.splitChunks.cacheGroups` and `output.libraryTarget` are in webpack.config and existing entry is used in `cacheGroups` there is no [library output ](https://webpack.js.org/configuration/output/#module-definition-systems) in such entry.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/smokir/webpack-migration/tree/master/webpack4
https://github.com/smokir/webpack-migration/blob/master/webpack4/dist/library.js

**What is the expected behavior?**

https://github.com/smokir/webpack-migration/tree/master/webpack3
https://github.com/smokir/webpack-migration/blob/master/webpack3/dist/library.js

**Other relevant information:**
webpack version: 4.29.6 vs 3.12.0 
Node.js version: v8.9.4 
Operating System: macOS Sierra 10.12.6
Additional tools:

**Comment by kondei** [comment]
Maybe I have the same problem.
When I Use `spllitChunks.cacheGroups` with `libraryTarget: window` or `umd`, my output `window.Foo` will be undefined.

**Comment by sokra** [comment]
This should help

``` diff
    entry: {
-       library: '../library/library.js',
-       'extension-a': '../library/extension-a.js',
-       'extension-b': '../library/extension-b.js',
+       'extension-a': ['../library/library.js', '../library/extension-a.js'],
+       'extension-b': ['../library/library.js', '../library/extension-b.js'],
    },

    optimization: {
        minimize: false,
        splitChunks: {
            chunks: 'all',
            minSize: 0,
            cacheGroups: {
                default: false,
                vendors: false,
                library: {
                    name: 'library',
                    minChunks: 2
                }
            }
        },
```

**Comment by Checksum** [comment]
Just ran into this as well. @sokra's solution doesn't seem to work for me. Anyone figured this out?

**Comment by smokir** [comment]
@sokra thank you for your answer, but even with your solution on the latest webpack 4.27.0 there is still missing code in [such entry](https://github.com/smokir/webpack-migration/blob/master/webpack4-sokra/dist/library.js).

**Comment by Checksum** [comment]
I figured out why the library is `undefined` in my case. When specifying chunks, all the chunks have to be loaded manually *before* the main chunk. That is, if you have a `vendor.js` and `main.js`, webpack doesn't dynamically import `vendor.js` for you - that is up to you to load before `main.js` is initialized. 

However, splitting chunks using `import` does cause webpack to dynamically load them.

**Comment by maksimsemenov** [comment]
@Checksum Thanks so much! It solves the issue for me. It was so simple

**Comment by VictorWu90** [comment]
@Checksum I have the same issue. Can you show what you did to solve the issue ?
Thanks so much!

**Comment by maksimsemenov** [comment]
@VictorWu90 make sure that you load chunks before the main chunk. Soin your `html` it should be something like that:
```
<script type="text/javascript" src="some_chunk.js></script>
<script type="text/javascript" src="main_chunk.js></script>
```

**Comment by VictorWu90** [comment]
@Checksum  Thank you ! 
Solve the issue by using HtmlWebpackPlugin and HtmlWebpackTagsPlugin

**Comment by FIGHTING-TOP** [comment]
> @VictorWu90 make sure that you load chunks before the main chunk. Soin your `html` it should be something like that:
> 
> ```
> <script type="text/javascript" src="some_chunk.js></script>
> <script type="text/javascript" src="main_chunk.js></script>
> ```

When use dynamic import ,how to resolve?
I'm in this trouble.
