### ISSUE TITLE
wasm: cache IndexedDB

### ISSUE THREAD

**Issue by xtuc** [webpack/webpack#7508]
## Feature request

**What is the expected behavior?**

- Webpack should cache the compiled wasm module in IndexedDB (using url as the key).
- Webpack should invalidate the module if it has changed and refetch it
- Webpack should use the compiled module from the cache (IndexedDB) if available

**What is motivation or use case for adding/changing the behavior?**

If the module is cached and compiled locally we don't need to download it again

**How should this be implemented in your opinion?**

Here's an example: https://github.com/mdn/webassembly-examples/blob/master/wasm-utils.js

**Are you willing to work on this yourself?**
yes

cc @MaxGraey

**Comment by MaxGraey** [comment]
But I should mentioned it seems Chrome and Safai doesn't support structural copy and need somehow workarounds for this. [More detail about that](https://github.com/mdn/webassembly-examples/issues/4)

**Comment by sokra** [comment]
I hope browsers do this automatically when using instantiateStreaming.

**Comment by MaxGraey** [comment]
Unfortunately not:
> "module: A WebAssembly.Module object representing the compiled WebAssembly module. This Module can be instantiated again, shared via postMessage() or cached in IndexedDB." [source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiateStreaming)

Browsers only cache response's data but not compiled `WebAssembly.Module`.

**Comment by xtuc** [comment]
The storage of a `WebAssembly.Module` is not going to be in the v1 spec. Other solutions are being investigated currently, I will be updating the issue to reflect the changes needed in Webpack.

**Comment by xtuc** [comment]
Actually, I don't think we need to keep that open (or I will re-open it once we're ready). I wouldn't expect Wasm Module structural caching soon-ish.
