### ISSUE TITLE
webpack4 load module(file) multiple times when multiple entries import this module(file)

### ISSUE THREAD

**Issue by imwtr** [webpack/webpack#7509]
**Do you want to request a *feature* or report a *bug*?**
Bug, I guess.

**What is the current behavior?**
There's a common parent module `parent.js`, which imports a function from `util.js`
`import {getMsg} from './components/util';`
And another module `task.js` imports another function
`import {showMsg} from './components/util';`
I also put a  `import 'babel-polyfill';` in my `util.js`  module,  
and error reports with `Uncaught Error: only one instance of babel-polyfill is allowed`. 
I think the util module may have loaded twice, console.log in `util.js` log twice.

**If the current behavior is a bug, please provide the steps to reproduce.**
Just like the behavior

**What is the expected behavior?**
Just like what webpack3 does, which loads module only once.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Not a feature

**Please mention other relevant information such as the browser version, Node.js version, webpack Version, and Operating System.**
OS: win10
Node: 8.9.3
Webpack: 4.12.0
Browser: chrome 65

**Comment by ooflorent** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by montogeek** [comment]
Can we close this issue then?

**Comment by imwtr** [comment]
Sure, but what's the `initial` means ?
