### ISSUE TITLE
`Chunk.integrate()` can arbitrarily rename entry name chunk

### ISSUE THREAD

**Issue by nicolas-cherel** [webpack/webpack#7516]
# Bug report

I've a webpack config with a "server" entry whose chunk name is renamed with the name of a split chunk when using `LimitChunkCountPlugin`. Then `webpackHotServerMiddleware(compiler, { chunkName: 'server',  })` fails to retrieve the handler with given chunk name.

**What is the current behavior?**
webpackHotServerMiddleware, or anything that uses chunk names of chunk that reveived a call to  `Chunk.integrate()` might fail.

**If the current behavior is a bug, please provide the steps to reproduce.**

See example repo: https://github.com/nicolas-cherel/WebpackNameChunkBug

**What is the expected behavior?**
The entry chunk name should not be renamed.

The following code might not need to override receiving chunk name into the otherChunk name. (given that callee respects chunks hierarchy in calls).

https://github.com/webpack/webpack/blob/master/lib/Chunk.js#L380-L389

**Other relevant information:**
webpack version:  4.12.0
Node.js version: v8.10.0 // should be irrelevevant here
Operating System: macOS high Sierra
Additional tools: N/A

*edit: as discussed bellow you can mitigate the issue using long chunks name to avoid override of short chunk names you want to keep*

**Comment by threehams** [comment]
I've run into this as well. Can confirm it's been present at least 4.0.0-beta.1, likely earlier. (Versions before this error out on the demo repo for various reasons.)

**Comment by yamafaktory** [comment]
We are facing the same crazy issue in our build pipeline (private repo) with the exact same error... would be nice to figure out what's going on 👍.

**Comment by dan-lee** [comment]
This is a really nasty bug, which keeps biting us.
Removing following lines, mentioned by @nicolas-cherel, works in the particular case with `LimitChunkCountPlugin({ maxChunks: 1 })`: 
https://github.com/webpack/webpack/blob/482ff200303e84a65bdd5c456ce232309a6ce450/lib/Chunk.js#L396-L405

(_My takeaway here is that the shortest chunk name wins, even when there's only one chunk to be created eventually._)

Sadly, I don't know much about the chunk architecture to work out a proper solution. I'd be happy to put together a PR, if someone could give me some directions.

**Comment by nicolas-cherel** [comment]
@dan-lee about names length:  yes exactly, so you have to make sure to use longer names for others chunks. I mentioned that when I twitted about it, forgot to talk about it in the issue https://twitter.com/keebarhisk/status/1006469653600796672

**Comment by yamafaktory** [comment]
cc/ @sokra I'd be glad to help on that one since this is quite a big breaking issue... However, I'm not quite sure where this should be ideally handled in the source code...

**Comment by MKKuhn** [comment]
We've run into the same issue recently as well. We're using a workaround at the moment which just uses a short entry point to get around it:
Dev server: `app.use(webpackHotServerMiddleware(compiler, { chunkName: 'm' }))`
Server config: `{ entry: { m: [entry] } }`
Thanks for the workaround @threehams and the info @dan-lee !
