### ISSUE TITLE
npm run build is not working in latest version for typescript with vue

### ISSUE THREAD

**Issue by iksdatoo** [webpack/webpack#7517]
I am using the latest web pack version which is:  build "4.12.0". I am using Vue JS with TypeScript and I have converted the web pack code to latest version and development version is working with vue-loader and ts-loader. When I try to run `npm run build` command. This error pop up:

ERROR in static/js/main.83a6b91b74635e099969.js from UglifyJs
module redeclared [./src/components/lister-grid/vuex/index.ts:228,6][static/js/main.83a6b91b74635e099969.js:56497,6]
Done in 16.90s.

Any body knows the solution for this issue?

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
