### ISSUE TITLE
ConstPlugin should remove dead branches in LogicalExpressions

### ISSUE THREAD

**Issue by rtsao** [webpack/webpack#7519]
## Feature request

**What is the expected behavior?**

For example, given the following code:

```js
var foo = false && thing1() && thing2();
```

ConstPlugin should produce the following:

```js
var foo = false;
```

**What is motivation or use case for adding/changing the behavior?**

This will result in more optimal import pruning. Let's look at a concrete example:

Suppose "some-pkg" has been declared as side effect free. In the code below, the "some-pkg" import declaration will be correctly pruned.

```js
import {foo} from "some-pkg";

if (false) {
  foo();
}
```

However, in the code below, "some-pkg" will *not* be pruned, which is a suboptimal result. Instead, `foo` should be considered unused.

```js
import {foo} from "some-pkg";

var bar = false && foo();
```

**How should this be implemented in your opinion?**

I'm not totally sure, but probably something along the lines of:
- Add a `logicalExpression` hook to Parser
- Use the `logicalExpression` hook in ConstPlugin to remove dead branches

**Are you willing to work on this yourself?**
Yes

**Comment by ooflorent** [comment]
If you need help, feel free to ask  👋

**Comment by sokra** [comment]
Search the code base for `expressionConditionalOperator` to see how it's done for the `?:` operator. Do it similar.

**Comment by ljqx** [comment]
OK to close this now, #8233 has already fixed it.

**Comment by rtsao** [comment]
Marking as closed (https://github.com/webpack/webpack/pull/8233)

**Comment by rtsao** [comment]
There are still cases where this is broken (webpack v5.30.0)

```js
false && unreachable() // <-- works, unreachable is pruned
something && false && unreachable() // <-- not working, unreachable is bundled
```

(Full repo: https://github.com/rtsao/webpack-repro-7519):

Inline reproduction:

```js
// index.js
import unreachable from "./unreachable.js";

function something() {
  return Math.random();
}

function app() {
  something() && false && unreachable();
}

app();
```

```js
// unreachable.js
module.exports = function unreachable() {
  console.log("Unreachable function should not be bundled!");
};
```

#### Expected

`unreachable` should not be bundled

#### Actual

`unreachable` is bundled

**Comment by alexander-akait** [comment]
Mark as `enhancement` should be easy to fix, if you want to help I can provide place where you can improve it

**Comment by alexander-akait** [comment]
bump
