### ISSUE TITLE
AggressiveSplittingPlugin with recordsPath set js goes wrong when compiled second time

### ISSUE THREAD

**Issue by AMDvsTMD** [webpack/webpack#7520]
# Bug report

**What is the current behavior?**

I'm using AggressiveSplittingPlugin when set config.recordsPath = path.join(outputPath, 'records.json'); if there is no  records.json it will generate one
the second time compile the records.json changed even do nothing and the js code in browser gos wrong

**If the current behavior is a bug, please provide the steps to reproduce.**

delete records.json compile works ok
compile  the second time js error

**What is the expected behavior?**
this  records.json should not change if nothing did
and js run well

**Other relevant information:**
webpack version:  4.6.0
Node.js version: 8.10.0
Operating System: windows7
Additional tools:

**Comment by ooflorent** [comment]
Could you test using the latest webpack version? There have been a lot of fixes on records.

**Comment by AMDvsTMD** [comment]
that's right when use the lastest version everything goes well thks
