### ISSUE TITLE
website visit 404

### ISSUE THREAD

**Issue by Unfantasy** [webpack/webpack#7521]
# Bug report

**What is the current behavior?**
![default](https://user-images.githubusercontent.com/16619996/41344980-0159be8a-6f35-11e8-94fa-4c002463df0c.png)
![2](https://user-images.githubusercontent.com/16619996/41344981-0193f1c2-6f35-11e8-9f3b-2de43e450b6a.png)
and `https://www.webpackjs.com/configuration/` is OK

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by ooflorent** [comment]
@webpack-bot move to webpack/webpack.js.org
