### ISSUE TITLE
Dynamic import not working on target: 'webworker' with custom output.publicPath

### ISSUE THREAD

**Issue by lordfido** [webpack/webpack#7529]
# Bug report

**What is the current behavior?**
When I use a dynamic import and I've setup `target: 'webworker'` on my webpack config, and I setup a custom `output.publicPath`, that path is not being set in that require, so file is not found when executing the code.

**If the current behavior is a bug, please provide the steps to reproduce.**
* Create any proyect using webpack
* Setup `target: 'webworker'` on your webpack config's main level
* Setup your `output.publicPath` to a custom directory (different than root)
* On your `index.js` import a file on the following way `import(/* webpackChunkName: "my-module" */ 'my-module');` 
* Build/launch your app and open network inspector
* Look for a 404 error, looking for any bundle, and verify it's trying to be imported from `localhost:xxxx/chunkname-without-path.ext`

**What is the expected behavior?**
It's expected to inject the output path before the chunkname, so it's properly found.

I think that `mainTemplate.outputOptions.chunkFilename` in https://github.com/webpack/webpack/blob/510b68a828d4fa07dd889638c25f251cf1d84cc0/lib/webworker/WebWorkerMainTemplatePlugin.js#L39 comes without `path`

**Other relevant information:**
webpack version:  4.8.3
Node.js version: 8.9.1
Operating System: ElementaryOS 0.4.1 Loki (64 bits)
Additional tools:

**Comment by prateekbh** [comment]
@sokra is this still open? i am experiencing similar issues

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo

**Comment by prateekbh** [comment]
creating a PR

**Comment by prateekbh** [comment]
@evilebottnawi just create a js file and add a dynamicImport with target as `webworker` and a publicPath.
