### ISSUE TITLE
webpack should use dependencies firstly but not node-libs-browser

### ISSUE THREAD

**Issue by Aqours** [webpack/webpack#7536]
# Bug report

**What is the current behavior?**
```js
// TypeScript Code
// node_modules/events (my dependencies and webpack.config target: 'web')
import events from 'events';
export function f() {}
```
The bundle `events` package from `node-libs-browser`.

**If the current behavior is a bug, please provide the steps to reproduce.**
Use webpack to bundle the above code in `development` mode, then you can find some path infomations in dist file.

**What is the expected behavior?**
The bundle `events` package from `node_modules/events`.

**Other relevant information:**
webpack version:  4.12.0
Node.js version: 8.x
Operating System: Window 10
Additional tools: TypeScript 2.9.2

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by ooflorent** [comment]
If you need a quick fix, you can add this to your config:

```js
node: {
  events: "events",
}
```

**Comment by Aqours** [comment]
@ooflorent emm.. I known, but It's boring green man.

**Comment by sokra** [comment]
We copied the behavior of node.js.

**Comment by Aqours** [comment]
Should webpack consider to use dependencies firstly when webpack.config using `target: 'web'`? Most often these user don't relay on node core modules, otherwise adding dependencies is the better choice.

Most important of all, the implement of alike node core modules in node-libs-browser mismatch the real node core modules because some feature being added, deprecated or removed in different node version. In this case, the implement of `events` webpack bundled isn't same with node core modules and maybe different from my `event` dependencies.
