### ISSUE TITLE
 How to let the user do not clear the cookies to implement the update after removing the version number

### ISSUE THREAD

**Issue by BossGuo** [webpack/webpack#7538]
Hello,Thank you replying me，I have a question, that is If i remove version number,how to let the user do not clear the cache to implement the update ? Because every time i publish my project to the server,i must delete old file and then put my new file, so i remove the version number，but it must let user clear the cookies. So I don't know how to do it ? can you give me some suggestions？ Thank you very much!

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.

**Comment by BossGuo** [comment]
OK,just now ,I have an idea to solve it, Think you very much!
