### ISSUE TITLE
[docs] more information / code comments for plugin devs

### ISSUE THREAD

**Issue by SassNinja** [webpack/webpack#7539]
I know this is quite general, but are there any plans to extend the plugin development docs and/or add more comments in the source code?

I'm currently working on my first webpack plugin (precisely it's about splitting a css file from mini-css-extract-plugin into multiple files).
The docs have been a good starting point but after getting into more details I'm missing many information (e.g. how to create new chunks with my extracted css, create sourcemap for them, add them into the dependency tree etc.)

As suggested in the docs I'm looking in the plugin source code
https://webpack.js.org/contribute/writing-a-plugin/#compiler-and-compilation

But unfortunately there are only little comments and it's quite exhausting (for me) to understand how all parts play together.
I usually only find this at the beginning but no explanation what it is supposed to do.
```javascript
/*
	MIT License http://www.opensource.org/licenses/mit-license.php
	Author Tobias Koppers @sokra
*/
```

Right now I'm looking at other plugins to get a better idea how it works.
But it's a lot of debugging and would be so much easier if there are more information in docs or the source code.

**Comment by ooflorent** [comment]
@webpack-bot move to webpack/webpack.js.org
