### ISSUE TITLE
Provide the option to specify --json in webpack.config.js

### ISSUE THREAD

**Issue by mac9416** [webpack/webpack#7543]
## Feature request
Provide the option to specify --json in webpack.config.js.

**What is the expected behavior?**
When I add something like this to the config object...
```
{
    // ...
    jsonOutput: true,
    jsonOutputPath: 'pack.json',
    // ...
}
```
...I would like Webpack to behave the same as if I called `webpack --json > pack.json`.

**What is motivation or use case for adding/changing the behavior?**
I'm running Webpack in nodejs from a Gulp task. I don't have the opportunity to pass command line parameters.

**How should this be implemented in your opinion?**
I'm not familiar enough with the code base to make that call.

**Are you willing to work on this yourself?**
no

**Comment by evilebottnawi** [comment]
@mac9416 what is use case?

**Comment by mac9416** [comment]
I'm on a large team using VS for an IDE. Since its Task Runner Explorer tool only supports Grunt and Gulp natively, we use Gulp for automation. So running Webpack via Gulp is by far the most convenient method.

Rather than jankily spawning a webpack child process, I invoke webpack directly in the gulpfile.

I need the JSON file for external tooling (for example, bundle analysis). But I can't generate it without using command line arguments. 

I would like the ability to specify JSON output via the config object, instead of just the command line.

**Comment by mac9416** [comment]
@evilebottnawi sorry I wasn't clear. I'm _not_ using the CLI. That's why I (apparently) don't have access to `--json` output.

**Comment by ooflorent** [comment]
`--json` outputs the `stats` on the build. You can get using the `webpack()` callback:

```js
webpack({
  // Configuration Object
}, (err, stats) => {
  if (err || stats.hasErrors()) {
    // Handle errors here
  }
  // Done processing
});
```

Another solution is to use a plugin to write the stats to file. [`webpack-stats-plugin`](https://github.com/FormidableLabs/webpack-stats-plugin) does it really well.

**Comment by mac9416** [comment]
@ooflorent thanks for the answer, either solution is good enough for me! I'll post my config for Googlers once I get it running.
