### ISSUE TITLE
Tree shaking not working with spread operator

### ISSUE THREAD

**Issue by BetterCallSky** [webpack/webpack#7548]
# Bug report

**What is the current behavior?**
Tree shaking is broken (the whole library is included) if a spread operator is used.  

**If the current behavior is a bug, please provide the steps to reproduce.**

Example code:
```ts
import * as Rx from 'rxjs/operators';

const foo = (...args: any[]) => Rx.concat(...args);
console.log(foo);
```
![image](https://user-images.githubusercontent.com/4478684/41501611-127baea6-71a8-11e8-9637-70ddebabf1c9.png)

if I change `Rx.concat(...args)` to `Rx.concat(args)` then everything works correctly.
Example code:
```ts
import * as Rx from 'rxjs/operators';

const foo2 = (...args: any[]) => Rx.concat(args);
console.log(foo2);
```
![image](https://user-images.githubusercontent.com/4478684/41501622-4e620370-71a8-11e8-8730-5669abd4608d.png)

Please check my repo here https://github.com/BetterCallSky/ts-webpack-treeshaking-bug

**What is the expected behavior?**
Tree shaking should work in both cases.

**Other relevant information:**
webpack version:  4.12.0
Node.js version: v8.9.1
Operating System: macOS 10.13.4
Additional tools: Typescript 2.9.2

**Comment by BetterCallSky** [comment]
I don't know the implementation details but I think
```
Rx.concat(...args)
```
is transpiled to
```
Rx.concat.call(null, args)
```
and `Rx.concat` is marked as a side effect and the whole module is included.

There are two workarounds:
1. `import {concat} from 'rxjs'`, instead of `import * as Rx from 'rxjs'`
2. Avoid using `...args`, and just use arrays

But it easy to make a mistake and break tree shaking.

**Comment by sokra** [comment]
It's transpiled to:

``` js
Rx.concat.apply(Rx, args);
//              ^^
//        Because of this the whole Rx lib need to be included
```

---

We can't fix that. We could detect `X.y.apply(X, ...)` but this could lead to false positives if `X.y` is not a function but an object with a `apply` property. We can't do that...

**Comment by lukaswelinder** [comment]
@sokra Perhaps I'm unfamiliar with the implementation details, but I'm not sure how the following two would differ:

```js
Rx.concat(args);
// vs
Rx.conat(...args);
```

The two should transpile to the following respectively:

```js
Rx.concat.call(Rx, args);
// vs
Rx.concat.apply(Rx, args);
```

So, shouldn't both result in the same code getting pulled in?

**Comment by lukaswelinder** [comment]
@BetterCallSky Fair enough; I should have been more specific.

Calling `Rx.concat(args)` is effectively the same as calling `concat.call(Rx, args)`. It implies that the `this` context of `concat` is the whole of `Rx`.

My point is, since tree shaking is preserved in your example,

```ts
import * as Rx from 'rxjs/operators';

const foo2 = (...args: any[]) => Rx.concat(args);
console.log(foo2);
```

it should not be expected that a spread would change the way the import is interpreted.

**Comment by edmorley** [comment]
> Is it possible to print a warning if the whole library marked as `sideEffect: false` is included in the bundle, and show which line caused it? As I wrote in my 2nd post, tree-shaking can be broken by our code accidentally, and it can take hours to debug it.

@sokra is ^ viable? Worth me filing an issue about it?
