### ISSUE TITLE
Watch doesn't doesn't pick up changes

### ISSUE THREAD

**Issue by kayone** [webpack/webpack#755]
I can't get the webpack watch to pick up changes in the modules, It builds the initial input just fine but doesn't pick up any changes after that. You can see our config here 
https://github.com/Sonarr/Sonarr/blob/webpack/webpack.config.js

and I'm running using `webpack -w`

I would really appreciate any help as I'm completely out of ideas. 

I'm running Windows, with webpack `1.5.3`

**Comment by kayone** [comment]
Some more info, I just downgraded to version 1.4.15 and it works there but not after 1.5. It seems like it's a change introduced in 1.5.

**Comment by sokra** [comment]
`resolve.root` must be an absolute path.

**Comment by kayone** [comment]
I'm probably missing something here, but wouldn't that make the config file not portable. eg. if one user clones to `c:\src` and another to `c:\git`?

**Comment by sokra** [comment]
``` js
path.join(__dirname, "path", "to", "file.js")
```

**Comment by kayone** [comment]
Thanks. That worked perfectly.
