### ISSUE TITLE
How to ignore native modules of mac in windows using webpack while bundling (eg: node-mac-notifier)

### ISSUE THREAD

**Issue by manipandi** [webpack/webpack#7552]
Module not found error in windows.

It happens when I tried to require like this

if(/^darwin/.test(process.platform)) {
let macNotifier = require ('node-mac-notifier');
}

Even though it is windows, it is trying to get the node-mac-notifier module which is declared as optional dependency.

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
