### ISSUE TITLE
Issue with optimization (production build)

### ISSUE THREAD

**Issue by rapkin** [webpack/webpack#7555]
# Bug report

Webpack optimization works wrong in my case. Details in example

**What is the current behavior?**

Development build works fine. But when i try to build project for production (with -p option) i receive infinite loop when page loads.

**If the current behavior is a bug, please provide the steps to reproduce.**

I'll try to make test repo later.

**What is the expected behavior?**

Optimized code should be compiled without issues with loops.

**Part of source code with problem**
```js
const renderCanvasOnMap = ($canvas, map, data) => {
    ...
    const drawHLine = (y) => {
        g.moveTo(0, y)
        g.lineTo(rect.width, y)
    }

    const drawVLine = (x) => {
        g.moveTo(x, 0)
        g.lineTo(x, rect.height)
    }
    ...

    const [sx, sy] = [
        minx - minx % ss,
        miny - miny % ss
    ]
    const [ex, ey] = [
        maxx - maxx % ss + ss,
        maxy - maxy % ss + ss
    ]

     if (cfg.zoom - map.getZoom() < 2) {
        g.strokeStyle = '#fff'
        g.strokeWidth = '0.5px'

        for (let x = sx; x < ex; x += ss)
            drawVLine(x - mapPixelBounds.min.x)

        for (let y = sy; y < ey; y += ss)
            drawHLine(y - mapPixelBounds.min.y)

        g.stroke()
    }
    ...
}
```

**Part of compiled code**
```js
T = (t, e, i) => {
    ....
    const h = t.getContext("2d"),
        ...
        [m, g] = [d - d % l, p - p % l],
        [v, y] = [_ - _ % l + l, f - f % l + l];
    if (o.a.zoom - e.getZoom() < 2) {
        h.strokeStyle = "#fff", h.strokeWidth = "0.5px";
        for (let t = m; t < v; t += l) t -= c.min.x, h.moveTo(t, 0), h.lineTo(t, a.height);
        for (let t = g; t < y; t += l) t -= c.min.y, h.moveTo(0, t), h.lineTo(a.width, t);
        h.stroke()
    }
    ....
    })
}
```

As you can see compiled example try to increment variable `t += l` but after that decrement this variable ` t -= c.min.y` inside loop body. Actually optimizer should use another variable to make this calculation. So here problem with optimization.

**Other relevant information:**
webpack version:  4.12.0
Node.js version: v10.1.0
Operating System: Mac OS 10.13.4

**Comment by sokra** [comment]
see https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/308

**Comment by evilebottnawi** [comment]
Already fixed in uglify, wait for the release, thanks!
