### ISSUE TITLE
Webpack v4.12 is not respecting setting the mode via webpack.config.js file

### ISSUE THREAD

**Issue by 1Marc** [webpack/webpack#7559]
# Bug report

Webpack v4.12 is not respecting setting the mode via config file.

**What is the current behavior?**

If I set the mode with module.exports in the webpack.config.js, I receive the configuration warning that the mode is not set.

**If the current behavior is a bug, please provide the steps to reproduce.**

If I make a `webpack.config.js` in the root with this configuration:

```javascript
module.exports = {
  mode: 'none'
};
```

And I run `npm run webpack` via the webpack in scripts in my package.json:

```javascript
 "scripts": {
    "webpack": "webpack",
  }
```

But I receive the configuration warning that the mode is not set.

```
configuration
  0:0  warning  The 'mode' option has not been set, webpack will fallback to
                'production' for this value. Set 'mode' option to 'development' or
                'production' to enable defaults for each environment.
```

**What is the expected behavior?**

Same exact config sets the mode just fine in v4.8 with no configuration warning.... but not in v4.12. The webpack documentation does not outline any sort of changes with this process https://webpack.js.org/concepts/mode/#mode-none -- so I'm guessing this is a bug.

**Other relevant information:**
webpack version:  v4.12
Node.js version: v9.9
Operating System: macOS
Additional tools: VS Code

**Comment by timneutkens** [comment]
There are a few things missing in your reproduction:

- entry points
- dependencies (I guess webpack-command based on the message)

The `webpack` npm package doesn't ship with a CLI but does ask if you want to install `webpack-command` when you haven't installed `webpack-command` or `webpack-cli`.

Providing a minimal reproducible GitHub repository makes it easier for anyone to talk a look at the issue you're experiencing 🙏

**Comment by 1Marc** [comment]
Sure, just FYI I'm QA'ing Sean's upcoming course on Webpack Fundamentals for Frontend Masters.

I'm on this repo: https://github.com/thelarkinn/webpack-workshop-2018 `feature/031-all-module-types` branch.

**Comment by 1Marc** [comment]
Looks like `webpack-cli@2.1.5` and `webpack-command@0.1.1`

I can go ahead and try to create a stripped-down repo to duplicate this issue with the minimal amount of code necessary to reproduce.

**Comment by evilebottnawi** [comment]
@1Marc You should use or `webpack-cli` or `webpack-command`

**Comment by timneutkens** [comment]
@evilebottnawi it's coming from `webpack-command` and I can reproduce. Checking it out now.

**Comment by evilebottnawi** [comment]
@timneutkens should be fixed in `0.2.x`, can you upgrade and test again?

**Comment by timneutkens** [comment]
Works with latest `webpack-command` 👍

**Comment by evilebottnawi** [comment]
@timneutkens Thanks!

@1Marc please upgrade `webpack-command` to `0.2` version.

Also don't use `webpack-cli` and `webpack-command` together, they do same thing

**Comment by timneutkens** [comment]
Sent a PR to Sean's workshop repo

**Comment by 1Marc** [comment]
It works! Thank you!
