### ISSUE TITLE
Conflicting ESM star re-exports should yield a SyntaxError

### ISSUE THREAD

**Issue by rtsao** [webpack/webpack#7562]
# Bug report

**What is the current behavior?**

If a file has conflicting star exports, the first export takes precedence, and no error is raised. In the inline example below, `"foo1"` is logged.

**If the current behavior is a bug, please provide the steps to reproduce.**

Repo with reproduction steps: https://github.com/rtsao/webpack-esm-bug-repro

Inline example for convenience:

```js
// index.mjs
import {foo} from "./foo.mjs";
console.log(foo);
```

```js
// foo.mjs
export * from "./foo1.mjs";
export * from "./foo2.mjs";
```

```js
// foo1.mjs
export const foo = "foo1";
```

```js
// foo2.mjs
export const foo = "foo2";
```

**What is the expected behavior?**

If there is conflicting re-exports for `foo`, then a `SyntaxError` should be thrown (preferably at build-time).

This happens in:

*Node 8*:
> SyntaxError: The requested module contains conflicting star exports for name 'foo'

*Chrome 67*
> Uncaught SyntaxError: The requested module './foo.mjs' contains conflicting star exports for name 'foo'

*Safari 11*
> SyntaxError: Importing binding name 'foo' cannot be resolved due to ambiguous multiple bindings.

**Other relevant information:**
webpack version: 4.12.0
Node.js version: 8.11.2
Operating System: Mac OS X 10.13
Additional tools:

**Comment by rtsao** [comment]
I believe this is still an issue.

**Comment by rtsao** [comment]
This is still an issue. I've just updated https://github.com/rtsao/webpack-esm-bug-repro to the latest stable version of webpack and this bug persists.

**Comment by evilebottnawi** [comment]
Can you test next version?

**Comment by rtsao** [comment]
> Can you test next version?

Yes, this is still broken in `webpack@5.0.0-beta.0`

**Comment by evilebottnawi** [comment]
bump

**Comment by rtsao** [comment]
I updated the reproduction to `webpack@5.0.0-beta.12` and this still persists

**Comment by ClassicOldSong** [comment]
What if foo1.mjs exports morethan `foo`, like `foo` and `bar`, while foo2.mjs exports `foo` and `baz`, while foo.mjs wants to export `foo` and `baz` from foo2.mjs and `bar` from foo1.mjs?

This is a catch IMO, re-exporting just can have such conflicts that cannot be solved simply by throwing an error.

**Comment by evilebottnawi** [comment]
bump
