### ISSUE TITLE
webworker target + dynamic import + chunkhash gives error "Path variable [chunkhash] not implemented in this context"

### ISSUE THREAD

**Issue by TimHambourger** [webpack/webpack#7563]
# Bug report

**What is the current behavior?**
Combining `target: 'webworker'`, an `output.filename` that uses `[chunkhash]`, and an entry file that does a dynamic import leads to a webpack exception like
```
ERROR in chunk index [entry]
[name].[chunkhash].js
Path variable [chunkhash] not implemented in this context: "[name].[chunkhash].js"
```
Changing any one of those conditions (use default web target, replace `[chunkhash]` with, say, `[hash]`, or remove dynamic import) removes the error.

**If the current behavior is a bug, please provide the steps to reproduce.**

webpack.config.js
```js
const path = require('path');

module.exports = {
    target: 'webworker',
    entry: {
        index: './src/index.js'
    },
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: '[name].[chunkhash].js'
    },
    mode: 'development'
};
```

src/index.js
```js
import(/* webpackChunkName: "imported" */ './imported').then(({ hello }) =>
    console.log(`Imported says: ${hello()}`)
);
```

src/imported.js
```js
export const hello = () => 'Hello from imported!';
```

**What is the expected behavior?**

`[chunkhash]` should be available for webworker target and dynamic imports and should generally behave the same as it does for default web target or no dynamic imports.

**Other relevant information:**
webpack version:  4.12.0
Node.js version: 8.9.2
Operating System: OSX 10.10.5

**Comment by sokra** [comment]
hmm yep, send a PR and implement it.

**Comment by TimHambourger** [comment]
Sure, I'll take a crack.

**Comment by TimHambourger** [comment]
@sokra Closing as this has been merged (and it looks like published to boot). Thanks for the fast turnaround!
