### ISSUE TITLE
exclusion using absolute paths matches out of project context

### ISSUE THREAD

**Issue by max-scopp** [webpack/webpack#7564]
# Bug report

Our freshly made webpack4 config was working on any device inside the company, except of one Person. This report is partially for clarification as I don't know if the following behaviour is intended.

**What is the current behavior?**

The project was saved on a path similar to `/Users/person/docroot/typo3/<project-root>` and inside our loader(s) we used:
```javascript
  {
    test: /\.jsx?$/,
    exclude: /(node_modules(?!\/auw-framework)|typo3(?!(conf))\w*|sysext).*/,
    ...
  },
```

Now, the Regex part `typo3(?!(conf))` will rightfully match that path to ignore.
![screen shot 2018-06-20 at 09 45 25](https://user-images.githubusercontent.com/11851540/41645417-40df0718-7471-11e8-8c31-242cabea62a5.png)
The consequence is that (in case of the jsx-loader) the generic error message
```
Module parse failed: Unexpected token (21:6)
You may need an appropriate loader to handle this file type.
```
is thrown that those files cannot be processed.
If this may be a bug, I'm more than happy to set up a test case.

**What is the expected behavior?**

Apply ignore rules only on Project context.

**Other relevant information:**
webpack version:  4.12.0
Node.js version: v8.9.4
Operating System: macOS 10.13.3

**Comment by sokra** [comment]
Prefer using `include` instead of `exclude`. You can also pass absolute paths to `include` and `exclude` or arrays of them.

**Comment by evilebottnawi** [comment]
Answer https://github.com/webpack/webpack/issues/7564#issuecomment-398718199
