### ISSUE TITLE
wasm: use importable mutable globals?

### ISSUE THREAD

**Issue by xtuc** [webpack/webpack#7565]
## Feature request

**What is the expected behavior?**

When a constant global is imported, we remove the import, we replace it with a mutable global and the runtime will then fill the global after instantiation.

**What is motivation or use case for adding/changing the behavior?**

While this seems to work so far, we could simplify the transformation by switching constant global imports into mutable globals.

The value can then be changed by Webpack's runtime once the dependecies are available.

One issue is that importable mutable global just reached the shipping phase, I doubt that we can reliably use it across all the browser.

Questions:
- Should we switch to it yet?
    - What it the browser doesn't support it?

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
yes!

**Comment by sokra** [comment]
Is there a list/overview of browser support for these wasm feature?

@bmeurer

**Comment by bmeurer** [comment]
cc @mathiasbynens @linclark

**Comment by TheLarkInn** [comment]
cc @liminzhu are we currently supporting this capability?

**Comment by liminzhu** [comment]
We don't have this yet but it is been tracked https://github.com/Microsoft/ChakraCore/issues/4745.

**Comment by linclark** [comment]
Mutable globals are shipping in beta for us. We'll be shipping it in release soon, and Chrome will be doing the same soon. But it will probably be a year before all browsers are shipping this feature in release.

However, we might have a solution here. The Rust folks are working on `wasm2js` (formerly `wasm2asm`) which compiles wasm to JS. If someone uses a mutable global, webpack could feature detect (based on `WebAssembly.Global` being available). If it is, fetch the wasm version. If it's not, fetch the JS version.

This feature detection is something we wanted to raise with you all anyway, so @TheLarkInn, let's talk about it in our meeting tomorrow.

**Comment by linclark** [comment]
I just realized that the issue is suggesting using mutable globals wherever globals are used, which would make it fallback to JS in most cases. So that does not seem like a good solution.

The motivation is a little unclear to me. What gets simpler about the transformation by doing this?

**Comment by xtuc** [comment]
I don't think fallback'ing to JS would make sense here.

My explains might be a bit unclear sorry, i'm trying to avoid the runtime we're injecting to fill in the global "from the inside" of the module.

Instead we could keep the global import but transforming them to mutable, which would allow Webpack to fill them from the outside later.

This aims to work arround the esm-integration issue.

**Comment by sokra** [comment]
I don't get the benefit of doing that. It's only another way in doing global importing, which has worse browser support.

**Comment by xtuc** [comment]
Ok @sokra, let's close this for now.

**Comment by xtuc** [comment]
I'm re-opening this issue because it can be used in an environement we are interested in and should be behind a flag for now.

**Comment by evilebottnawi** [comment]
bump

**Comment by sokra** [comment]
No longer relevant with the new wasm spec
