### ISSUE TITLE
Generator definition shorthand outputs as function

### ISSUE THREAD

**Issue by ningyuansg** [webpack/webpack#7566]
# Bug report

**What is the current behavior?**

The [shorthand for defining a generator method in an object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions) is sometimes parsed as a function. In some cases, this raises an uncaught syntax error in the browser (because keywords such as `yield`, `yield*` cannot be used in functions), causing the site to fail in executing the bundled js file.

**If the current behavior is a bug, please provide the steps to reproduce.**

Input `src/index.js`:

```javascript
export const foo = {
  *bar() { return yield 'something' }
}
```

Output `dist/main.js`:

```javascript
...const n={bar:()=>yield"something"}}]);
```

**What is the expected behavior?**

The output should be,

```javascript
...const n={*bar(){return yield"something"}}}]);
```

**Other relevant information:**
webpack version:  4.12.0
Node.js version: v9.11.1
Operating System: Debian 9.4 stretch
Additional tools: -

**Comment by sokra** [comment]
Does this only happens when minimizing?

**Comment by ningyuansg** [comment]
@sokra I'm sorry, I'm not very familiar with webpack so I'm not sure what you mean. I've been using it only as part of [react-scripts-ts](https://github.com/wmonk/create-react-app-typescript). If you can direct me as to how else to test this behaviour, I'd definitely be willing to follow and report the results here.

**Comment by sokra** [comment]
Ok is this only happening in cra build or also in cra start?

**Comment by ningyuansg** [comment]
Only on [build](https://github.com/wmonk/create-react-app-typescript/blob/master/packages/react-scripts/template/README.md#npm-run-build).

**Comment by sokra** [comment]
@webpack-bot move to webpack-command/uglifyjs-webpack-plugin
