### ISSUE TITLE
HMR & History API / PushState

### ISSUE THREAD

**Issue by altano** [webpack/webpack#757]
Hey There,

I'm using HMR and it works fine except when I'm using pushState and I'm 2 directory levels deep.  When that happens, it starts doing full page reloads instead of HMR.  For example, when I'm on http://localhost:8000/blah, HMR works.  When I "navigate" (using history API) to http://localhost:8000/blah/moo, HMR stops working and webpack switches to full page reloads.

It might be worth noting that webpack 1.5.3 is having the reload issue, but 1.4.15 didn't even do a full reload: I would just get an error in the console that the hot update JSON file couldn't be found.  So this behavior is at least better than before.

Any idea what might be happening?

**Comment by sokra** [comment]
You propably used a relative `publicPath` and the runtime cannot find the chunks. (This also breaks Code Splitting)

Either use a server-relative `publicPath` i. e. `"/assets"` (with a leading `/`) or use the HTML `<base>` tag.

**Comment by altano** [comment]
AAAAaand that did the trick.  I actually had an absolute path that I was passing in to the WebpackDevServer constructor, but the webpack config option was a relative path.

Thanks again :)
