### ISSUE TITLE
Can webpack.DllReferencePlugin exclude some chunks ?

### ISSUE THREAD

**Issue by imwtr** [webpack/webpack#7572]
## Feature request

**What is the expected behavior?**
`webpack.DllReferencePlugin` can exclude some chunks 

**What is motivation or use case for adding/changing the behavior?**
Some chunks may be independent but still need to be bundled together in a same webpack processon. We don't need to set `dll` vendor files for them (just keep dll vendor content in these chunks), I think It should be an option `exclude`  in this plugin. 

**How should this be implemented in your opinion?**
Add an option, or is there a workaound for this ?

**Are you willing to work on this yourself?**
No

**Comment by rozzzly** [comment]
You can just add those "excluded" modules to externals which can be a string, function, regex, etc. It's pretty flexible.

https://webpack.js.org/configuration/externals/#function

**Comment by evilebottnawi** [comment]
bump
