### ISSUE TITLE
The order of loaders applied doesn't match with documentation

### ISSUE THREAD

**Issue by just-boris** [webpack/webpack#7576]
# Bug report

**What is the current behavior?**

Normal loaders are applied before inline.

**If the current behavior is a bug, please provide the steps to reproduce.**

The simplest webpack config to reproduce this is the following

```js
module.exports = {
  entry: 'loader-one!./src/index.js',
  resolveLoader: {
    modules: [__dirname + '/loaders']
  },

  mode: 'none',

  module: {
    rules: [
      {
        test: /src\/index\.js/,
        use: "loader-two"
      }
    ]
  }
};
```

[Link to the repository with the demo](https://github.com/just-boris/webpack-7576)

The test file `index.js` supposed to be processed by two loaders: `loader-one` (inline) and then `loader-two` (normal, defined in rules). But actually `loader-two` is getting called first.

**What is the expected behavior?**

The `loader-one` should be executed first, then `loader-two`. As [the documentation](https://webpack.js.org/configuration/module/#rule-enforce) says: 

> All loaders are sorted in the order pre, inline, normal, post and used in this order.

So I expect inline to be called first.

**Other relevant information:**
webpack version:  4.12.0
Node.js version: 8.9.4
Operating System: MacOS
Additional tools: n/a

**Comment by sokra** [comment]
The documentation is wrong here.

**Comment by montogeek** [comment]
@sokra How should it be?

**Comment by sokra** [comment]
Here is an example:

Assuming `{test: /\.js$/, use: "babel-loader}`.

`require("./file.js")` => `babel-loader!./file.js`
`require("bundle-loader!./file.js")` => `bundle-loader!babel-loader!./file.js`
`require("!ts-loader!./file.js")` => `ts-loader!./file.js`

**Comment by just-boris** [comment]
If the current behavior is intended, the documentation should be updated.

Sent a PR to the docs repository: https://github.com/webpack/webpack.js.org/pull/2291
