### ISSUE TITLE
chunkhash not getting updated when module ids change

### ISSUE THREAD

**Issue by jdelStrother** [webpack/webpack#7577]
# Bug report

**What is the current behavior?**

We use chunk-splitting with `output.filename` set to `split.[chunkhash].js`.  We recently had a bug where webpack generated `split.bae9ebeb0655f4c56c9c.js` once containing this content:

```js
(window.webpackJsonp=window.webpackJsonp||[]).push([[35],{ ... }, },[["Q9lF",32,40,41]]]);
```

and then a later build generated the same filename, with this content:

```js
(window.webpackJsonp=window.webpackJsonp||[]).push([[35],{ ... }, },[["Q9lF",32,41,42]]]);
```

Aside from the module ids at the end, the entire rest of the file was identical.   Since we assume our `split.[chunkhash].js` files are immutable once they've been created, they have long-lived cache headers, and so our CDN continued serving the old version of the file, causing module loading to fail.  

**If the current behavior is a bug, please provide the steps to reproduce.**

Sorry, been struggling to come up with a minimal reproduction.  Will keep trying if the cause isn't obvious.
We're using the HashedModuleIdsPlugin, and webpack records.

**What is the expected behavior?**

If entry chunk ids change, the chunk's chunkhash should change.
(A bit of a stab in the dark, but maybe the hash here - https://github.com/webpack/webpack/blob/master/lib/web/JsonpChunkTemplatePlugin.js#L50 - needs to be updated with the same entries that are calculated here https://github.com/webpack/webpack/blob/master/lib/web/JsonpChunkTemplatePlugin.js#L26 ?)

**Other relevant information:**
webpack version:  4.12.0
Node.js version: 8.11
Operating System: Alpine & Ubuntu

**Comment by sokra** [comment]
Yep that looks like a bug
