### ISSUE TITLE
Serve up an .htm page

### ISSUE THREAD

**Issue by blachawk** [webpack/webpack#7578]
The ability to serve up a .htm default page when we run webpack.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by blachawk** [comment]
My apologies for deleting the template.  I also found my solution in the process.  Thanks anyway.
