### ISSUE TITLE
require.ensure error handling

### ISSUE THREAD

**Issue by richardscarrott** [webpack/webpack#758]
I'm implementing split points using commonJS however I can't see a way to handle failed chunk requests. I also haven't seen anything in the commonJS async proposal mentioning error handling. I have however seen implementations doing this:

```javascript
require.ensure(['foo'], function(err) {
    if (err) {
        // error
        return;
    }
    // success
    var foo = require('foo');
});
```

Although I'm not sure if the spec requires the first argument to be `require`?

I think the same goes for AMD as I can't see anything in the spec re: error handling but almost all implementations do this:

```javascript
require(['foo'], function(foo) {
    // success
}, function() {
    // error
});
```

In terms of implementation for webpack I imagine it could easily be handled by binding to the script tags 'error' event?

**Comment by zxcabs** [comment]
we are discussing it in https://github.com/webpack/webpack/issues/686

**Comment by adriaanmeuris** [comment]
So it seems this issue got resolved, but can't seem to find an example how to implement it and make sure to catch errors.
http://stackoverflow.com/questions/37578699/webpack-require-ensure-catch-jsonp-error

Any guidance how to do this, or do you still need a loader like https://github.com/NekR/async-module-loader for this?

**Comment by sokra** [comment]
The webpack 2 API returns a Promise:

``` js
System.import("module").then(() => { ... }).catch(err => { ... });
```

**Comment by adriaanmeuris** [comment]
Got it, didn't realise this was for v2 - thanks!
