### ISSUE TITLE
Stats.hasWarnings() returns true but compilation.warnings is empty

### ISSUE THREAD

**Issue by dharkness** [webpack/webpack#7580]
# Bug report

**What is the current behavior?**

The first compilation with `yarn watch` shows a warning about a URL in one of our SASS rules. This is fine, and Yarn waits for changes. Changing a SASS file results in a new compilation, but this time no warning is shown. Instead, the `webpack-notifier` plugin fails trying to access a property of undefined. The reason is that `stats.hasWarnings()` returns `true`, but `stats.compilation.warnings` is an empty array. While the plugin can avoid it (and I've added a work-around), even Webpack can't handle it.

The top of the output from webpack (or Yarn?) says this:

    WARNING Compiled with 0 warnings

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a project with a SASS file that will generate a warning. Run `yarn watch` and then change that SASS file to cause a recompile.

We're using this as part of Laravel Mix 2.1.11 which further complicates the issue, but it does seem isolated to the `stats` object passed to the `done` compiler hook.

**What is the expected behavior?**

`stats.hasWarnings()` should return `false` whenever the array of warnings is empty. The same should apply to `stats.hasErrors()` and the array of errors, but I haven't run into issues with that yet.

**Other relevant information:**
webpack version:  3.12.0
Node.js version: 10.5.0
Operating System: Ubuntu 17.10 x64
Additional tools: Laravel Mix 2.1.11, Webpack Notifier 1.6.0
See also: https://github.com/Turbo87/webpack-notifier/issues/44

**Comment by sokra** [comment]
Maybe there is a warning in a child compilation

**Comment by evilebottnawi** [comment]
@dharkness Can you create minimum reproducible test repo?

**Comment by dharkness** [comment]
Unfortunately, I doubt it as I'm using Webpack as part of Laravel Mix, and it uses a different build file format.

However, I'm happy to try out what @sokra mentioned. Are the properties of the `stats` object documented somewhere, or do you know how I can access the child compilations? Maybe I can determine where the bug lies and find a real fix.
