### ISSUE TITLE
Why does my bundle file contain \n characters?

### ISSUE THREAD

**Issue by datmt** [webpack/webpack#7587]
# Bug report

**What is the current behavior?**
My bundle files contain strange \n characters . I have many javascript errors. 

Part of the js file as below:

`innerRow.render();\n\n        var rowHTML = innerRow.$el.html();\n        content = content.replace('rowPlaceholder', rowHTML);\n\n        this.$el.html(content);\n    }\n});\n\nvar Box = C37FormElement.extend({\n    initialize: function initialize() {\n        C37FormElement.prototype.initialize.apply(this, arguments);\n    },\n\n    render: function render() {\n        var content = _.template(jQuery('#wplx-box').html())(this.model.toJSON());\n        this.$el.html(content);\n    }\n\n});\n\nvar Wall = C37FormElement.extend({\n    initialize: function initialize() {\n        C37FormElement.prototype.initialize.apply(this, arguments);\n    },\n\n    `

**Here is my webpack.config.js**
`var path = require('path');

module.exports = {
  entry: {
   "/js/editor-bundle.js": './src/js/Editor.js',
   "/js/widget-bundle.js": './src/js/Widget.js',
   "/js/popup-bundle.js": './src/js/Popup.js',
   "/js/settings-bundle.js": './src/js/Settings.js',
   "/js/front-bundle.js": './src/js/Front.js',
   "/css/editor-bundle.js" : "./src/css/editor.js",
   "/css/popup-manager-bundle.js" : "./src/css/popup.js",
   "/css/widget-manager-bundle.js" : "./src/css/widget.js",
   "/css/front-styles-bundle.js" : "./src/css/front.js",
   "/css/settings.js" : "./src/css/settings.scss",
  },
  module: {
	rules: [
		{
			test: /\.(js|jsx)$/,
			exclude: /node_modules/,
			use: ['babel-loader']

    },
    // { // sass / scss loader for webpack
    //   test: /\.(sass|scss)$/,
    //   loader: ExtractTextPlugin.extract(['css-loader', 'sass-loader'])
    // }
		{
			test: /\.scss$/,
        use: [
          {
            loader: "style-loader" // creates style nodes from JS strings
          },
          {
            loader: "css-loader" // translates CSS into CommonJS
          },
          {
            loader: "sass-loader" // compiles Sass to CSS
          }
        ]

		}
	]
  },
  output: {
    path: path.resolve(__dirname, 'bundle'),
    publicPath: '/',
    filename: '[name]'
  },
  externals: {
    // require("jquery") is external and available
    //  on the global var jQuery
    "jquery": "jQuery"
  },
  optimization: {
		// We no not want to minimize our code.
		minimize: false
	}
};

`

**Here is my package.json**
`{
  "name": "wp-lead-plus-x",
  "version": "1.0.0",
  "description": "=== Free Squeeze Page, Landing Page Builder & Templates Creator For WordPress=== Contributors: codingpuss, core37 Tags: squeeze page, page builder, landing pages, squeeze page plugin, squeeze page creator, splash page, splash page templates, page builder, landing page creator, squeeze page templates, WordPress squeeze page, best squeeze page, squeeze page for WordPress, sales page builder, free landing pages creator, video landing page, free landing page templates Requires at least: 3.8 Donate link: https://wpleadplus.com/ Tested up to: 4.9.4 Requires PHP: 5.3 Stable tag: 2.0.8 License: GPLv2 or later License URI: https://www.gnu.org/licenses/gpl-2.0.html",
  "main": "index.js",
  "scripts": {
    "start": "webpack --watch --mode development"
  },
  "repository": {
    "type": "git",
    "url": "git+https://gatoloco@bitbucket.org/gatoloco/wp-lead-plus-x.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "homepage": "https://bitbucket.org/gatoloco/wp-lead-plus-x#readme",
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.4",
    "babel-preset-env": "^1.7.0",
    "bable-loader": "0.0.1-security",
    "css-loader": "^0.28.11",
    "extract-text-webpack-plugin": "^3.0.2",
    "lodash": "^4.17.10",
    "node-sass": "^4.9.0",
    "sass-loader": "^7.0.3",
    "style-loader": "^0.21.0",
    "webpack": "^4.12.1",
    "webpack-command": "^0.2.1"
  },
  "babel": {
    "presets": [
      "env"
    ]
  }
}
`

**Other relevant information:**
webpack version:  4.12.1
Node.js version: 10.4.1
Operating System: MacOS
Additional tools:

Thank you very much!

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by datmt** [comment]
I've updated the template. Thanks
