### ISSUE TITLE
HTML entry-points

### ISSUE THREAD

**Issue by notlmn** [webpack/webpack#7589]
## Feature request
Webpack currently uses (only?) JS files as main entry-points via the `entry` property in configuration options, and then resolves dependencies from there. I request to support HTML files as entry points and resolve dependencies from there.

### What is the expected behavior?
Currently webpack throws an error saying there is no loader associated to handle the file type.

### What is motivation or use case for adding/changing the behavior?
Whenever a user (browser/UA) loads a page, the first thing it gets is an HTML response. The UA then resolves other resource files (CSS, JS, images, ...) from the HTML content and loads them as required. So it is intuitive for webpack to start from an HTML file and resolve dependencies from there. Parcel already does this, but [comparing webpack with other module bundlers](https://x-team.com/blog/rollup-webpack-parcel-comparison/), webpack is still the fastest.

I know that I can write some code like `require('./component.html')` and use something like `html-webpack-plugin` to also get the HTML files and process them. But this feels very disconnected from requiring all the files in JS code, and only handling HTML code through a separate plugin (yes, there may be a way to do this, but I'm sure its just another hack/plugin/loader).

Module bundlers started with JS entry points when they only handled JS, but **webpack evolved to be more than just a module bundler for JS**, which is now used to load all kinds of files. **A JS file is a dependency to an HTML file, not the other way around**.

```
                 html <-- start from here
        ┌──────────┼─────────┐
       css        img        js <-- not from here
   ┌────┴────┐          ┌────┼────┐
  css       css         js   js  js
```

Because c'mon man, how standard (isomorphic?) is writing something like `import styles from './styles.css';`? **Why couldn't webpack think (and also act) as a browser instead!?**

Some people (who write HTML inside JS) may not like this feature, but I want to make it clear that I want webpack to support HTML entry-points along side JS entry-points, not replace the existing behavior.

### How should this be implemented in your opinion?
Let HTML files be included in the `entry` option and webpack should handle it by default (without any need of plugins), then provide loaders for different file types.

_**Sidenote:** I think one advantage of this approach may be for people to move their existing static/dynamic applications move to wepack without (re-)writing CSS and HTML imports in JS files. They can just include webpack and point it to some HTML files._

### Are you willing to work on this yourself?
I'm a regular webpack user, but haven't looked into the source code yet. If someone can guide me on the internals, then yes!

**Comment by evilebottnawi** [comment]
@notlmn thanks for request, duplicate https://github.com/webpack/webpack/issues/536, please write ideas and how it can be solved in https://github.com/webpack/webpack/issues/536 issue, thanks!

**Comment by webdiscus** [comment]
@notlmn 

5 years later...
 
The [html-bundler-webpack-plugin](https://github.com/webdiscus/html-bundler-webpack-plugin) allows you to use an HTML template as an entry point for all referenced source assets, exactly as you described.

See please the details in [my comment](https://github.com/webpack/webpack/issues/536#issuecomment-1676452331) by the #536 issue
