### ISSUE TITLE
The dependency on micromatch package should be removed

### ISSUE THREAD

**Issue by prahladyeri** [webpack/webpack#7591]
I've observed that you have a dependency on [micromatch npm package](https://www.npmjs.com/package/micromatch) which pulls in additional trivial packages like `nanomatch`, `is-odd`, `is-even` and `is-number`. The only place you're using this module is in the [/lib/optimize/SideEffectsFlagPlugin.js](https://github.com/webpack/webpack/blob/3415a983301bbaeffd1bf250e3c7b139a392315b/lib/optimize/SideEffectsFlagPlugin.js) which should be trivial to implement in pure JS.

    return mm.isMatch(moduleName, flagValue, {
					matchBase: true
    });

I hope you'll do it and remove this dependency soon. I also hope you understand that adding dependencies for trivial functionality like this is a worst practice presently plaguing the javascript world and the idea of "don't repeat yourself" is being carried too far with packages like `is-odd` and `is-even`.

**Comment by montogeek** [comment]
That `isMatch` function is doing more than you think.
It also have a internal cache which is an optimization.

**Comment by davidtimovski** [comment]
I agree about the `isMatch` function. I'm waiting to see the justification of `is-odd`, `is-even`, and `is-number`.

**Comment by sokra** [comment]
Send a PR

**Comment by arkadyt** [comment]
Hmm, should globbing then support only a limited set of wildcards?
Plugin unittest tests with *, **, !, [a-z], {a, ..., n} and [[:lower:]] only.

**Comment by sokra** [comment]
any limitation would be a breaking change. So only try to reduce dependencies without reducing functionality. You could also consider sending a PR to micromatch, or dependencies, to remove `is-odd` etc.

**Comment by jonschlinkert** [comment]
I'm the author of micromatch. 

- is-odd was removed from the entire micromatch tree months ago. 
- is-number checks string values that are parsed from bash-like ranges in brace and bracket patterns in globs. 

> You could also consider sending a PR to micromatch, or dependencies, to remove is-odd etc.

This would be fantastic. We're actively working to improve micromatch. As long as all 36k unit tests continue passing and we keep parity with bash, we'll take any PR that improves the performance or reduces code. Reducing deps and leveraging new es syntax is a top priority.

**Comment by sokra** [comment]
Great, so I guess we can close this one.
