### ISSUE TITLE
TreeShaking not working in webpack 4.5.0

### ISSUE THREAD

**Issue by galenyuan** [webpack/webpack#7594]
# Bug report

Just tried the tree shaking feature but it looks not working, checkout code here: https://github.com/galenyuan/tree-shake

**What is the current behavior?**

when I try to `import { moduleA } from './test-module/esm'`, cli told me `[only some exports used: moduleA]` but nothing changed in bundle file.
![image](https://user-images.githubusercontent.com/10335062/41894274-fe5b95a2-7950-11e8-83aa-840d3c027710.png)
![image](https://user-images.githubusercontent.com/10335062/41894357-3ab771b0-7951-11e8-8979-ee04e13c0699.png)

and when I try to `import { moduleA } from 'test-module/esm'`, cli told me nothing and same bundle file in dist.js

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/galenyuan/tree-shake
```
npm install
npm start
```

**What is the expected behavior?**
should have `/* unused harmony export _functionname_ */` comment in bundle file

**Other relevant information:**
webpack version: 4.5.0
Node.js version: 8.11.2
Operating System: macOS
Additional tools: -

**Comment by sokra** [comment]
This is working as expected. A minimizer is now able to remove `moduleB` via DCE. Enable minimizing to see the effect.
