### ISSUE TITLE
obvious typo in doc: "loader: MiniCssExtractPlugin.loader", with loader missing

### ISSUE THREAD

**Issue by MagicPoulp** [webpack/webpack#7596]
**Do you want to request a *feature* or report a *bug*?**
clear and obvious bug

**What is the current behavior?**
https://webpack.js.org/plugins/mini-css-extract-plugin/
in the example, the json is invalid.
"loader: MiniCssExtractPlugin.loader", with loader missing
This is quite obvious.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
fix doc.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

**Comment by montogeek** [comment]
@webpack-bot move to webpack-contrib/mini-css-extract-plugin
