### ISSUE TITLE
Creating a workflow optimizer plugin

### ISSUE THREAD

**Issue by christianalfoni** [webpack/webpack#760]
Hi,

After researching webpack and writing [this article](http://christianalfoni.github.io/javascript/2014/12/13/did-you-know-webpack-and-react-is-awesome.html) on how to use it with React JS, it sparked some discussions and interest, especially regarding the optimizations for the workflow. I am writing up a react-webpack-cookbook with @bebraw to share some best practices using React JS with Webpack.

## The issue
When using the webpack-dev-server, running your workflow, it quickly becomes very slow as you require files from *node_modules* that often has huge dependency trees. The thing is that you do not really need  Webpack to handle these modules during development, only when building the production bundle.

## The solution
The best practice this far is to create two different webpack configuration files. One for development and one for production. In the development version you create aliases for your vendor dependencies, like React JS, that points directly to the minified version of the library. The path is also added to the "noParse" array. This keeps the rebundle speed at a pretty good level.

```javascript
var path = require('path');
module.exports = {
  resolve: {
    alias: {
      'react': path.resolve(node_modules, 'react/dist/react.min.js'
    }
  },
  module: {
    noParse: [path.resolve(node_modules, 'react/dist/react.min.js']
  }
};
```

## The question
Based on this, would it be possible to get some pointers into how we could create a plugin to handle this? A plugin that would let you configure this optimization, and making webpack automatically choose the correct version based on its environment? An example:

```javascript
module.exports = {
  module: {
    plugins: [new VendorOptimizerPlugin({
      'react': '~react/dist/react.min.js'
    })]
  }
};
```

When running webpack with `-p` the config would use react normally and do the packaging optimizations. When running a workflow though, it would use the minified version, keeping a low rebundle speed.

1. Does it seem like a good idea to create a plugin for this?
2. Can a plugin manipulate the config?
3. Can a plugin know if webpack is running in production mode?

Thanks for any pointers on this! :-)

**Comment by jhnns** [comment]
Some thoughts:

- You can't predict where the development and where the production file will be
- How long is your re-bundle time? Ours is below 1s so this is no problem for us at all...

**Comment by christianalfoni** [comment]
Hi @jhnns and thanks for the response :-)

I am working on a huge project where it takes several seconds without optimizations. Even so, it is ideal to bring it down to 200 ms, as that is where it starts to feel instant. Working on two screens with auto-refresh. It is very comfortable :-)

> You can't predict where the development and where the production file will be

Referring to question 3.? I was thinking more of checking if webpack was running the config with the `-p` argument, just to avoid having two different configs. But maybe that is better nevertheless. hm...

**Comment by jhnns** [comment]
> You can't predict where the development and where the production file will be

Forget it, I didn't get your question right :grinning: 

Concerning `-p`: #775
