### ISSUE TITLE
Array Webpack config incompatible with single-compile plugins

### ISSUE THREAD

**Issue by ChrisBAshton** [webpack/webpack#7602]
# Bug report

It is currently not possible to write plugins which compile once per Webpack run, when using array Webpack configs (as opposed to single JSON Webpack configs). Instead, plugins run for EVERY `compilation` object that is created.

**What is the current behavior?**

Given a webpack.config.js like this:

```js
const languages = ['afrique', 'arabic', 'english', 'mundo', 'russian'];
const webpackConfig = [];
languages.forEach(lang => {
  webpackConfig.push({
    plugins: [ new IncludeCompilerPlugin({ language } ]
  });
});
return webpackConfig;
```

And an IncludeCompilerPlugin something like:

```js
class IncludeCompiler {
  constructor(language) {
      this.language = language;
      console.log(`constructed one includecompiler instance app in ${language}`);
  }

  apply(compiler) {
      compiler.hooks.afterEmit.tapAsync('IncludeCompiler', (compilation, done) => {
         console.log(`compiling.... app in ${this.language}`);
         done();
      });
  }
}
```

I would expect the following output:

```
constructed one includecompiler instance app in afrique
constructed one includecompiler instance app in arabic
constructed one includecompiler instance app in english
constructed one includecompiler instance app in mundo
constructed one includecompiler instance app in russian
compiling.... app in afrique
compiling.... app in arabic
compiling.... app in english
compiling.... app in mundo
compiling.... app in russian
```

This is what I _actually_ get in my output:

```
constructed one includecompiler instance app in afrique
constructed one includecompiler instance app in arabic
constructed one includecompiler instance app in english
constructed one includecompiler instance app in mundo
constructed one includecompiler instance app in russian
compiling.... app in afrique
compiling.... app in arabic
compiling.... app in english
compiling.... app in mundo
compiling.... app in russian
compiling.... app in afrique
compiling.... app in arabic
compiling.... app in english
compiling.... app in mundo
compiling.... app in russian
compiling.... app in afrique
compiling.... app in arabic
compiling.... app in english
compiling.... app in mundo
compiling.... app in russian
compiling.... app in afrique
compiling.... app in arabic
compiling.... app in english
compiling.... app in mundo
compiling.... app in russian
compiling.... app in afrique
compiling.... app in arabic
compiling.... app in english
compiling.... app in mundo
compiling.... app in russian
```

The number of `compiling` logs grows exponentially for each language (e.g. 5 languages = 25 logs, 6 languages = 36, etc)

I've tried swapping out `compiler.hooks.afterEmit.tapAsync` for every single hook on the [compiler hooks documentation](https://webpack.js.org/api/compiler-hooks/) but can't find a hook which triggers once per 'Webpack runtime' (as opposed to once for every Webpack compilation that is created). 

I would expect at least the `compiler.hooks.done` hook to work here, but again that compiles for every `compilation` instance (so, exponentially).

**Other relevant information:**
webpack version:  4.12.0
Node.js version: 9.11.1
Operating System: OSX
Additional tools: N/A

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by ChrisBAshton** [comment]
Thanks @sokra - I just tried doing that and realised it was my own stupid mistake 😓 

I was _actually_ doing something like this:

```js
const webpackConfig = [];
languages.forEach(language => {
    const configForLang = Object.assign({
        entry: `./source/${include}/app.js`,
        plugins: [
            new IncludeCompiler(envMode, language, include),
        ],
    }, defaultConfig);
    webpackConfig.push(configForLang);
});
```

I removed the `Object.assign` when raising the issue, for simplification, but that was actually the issue - I think I'm tainting the `defaultConfig` object and adding new `IncludeCompiler` instances to already defined configs!

Apologies for wasting your time.
