### ISSUE TITLE
Specify additional resolve.paths but fall back to default Webpack resolving if module not found in specified path.

### ISSUE THREAD

**Issue by josh08h** [webpack/webpack#7606]
## Feature request

**What is the expected behavior?**
Change Webpack resolving as such:
`resolve: [../some/path/, ..another/path/]`
If the Webpack resolution is unsuccessful then Webpack should fall back to it's default resolution algorithm which is stepping up recursively through `node_modules` directory.

**What is motivation or use case for adding/changing the behavior?**
We have obscure locations for some modules inside of our monorepo.

**How should this be implemented in your opinion?**
Perhaps a `module.resolve.defaultFallback` flag inside webpack config.

**Are you willing to work on this yourself?**
potentially..

**Comment by sokra** [comment]
```  js
resolve.modules: [
  path.resolve(__dirname, "some/path"),
  path.resolve(__dirname, "another/path"),
  "node_modules
]
```
