### ISSUE TITLE
commonjs module under web_modules is not treated is not loaded properly

### ISSUE THREAD

**Issue by njleonzhang** [webpack/webpack#7608]
```
web_modules
   test-module
       index.js

import xxx from 'test-module'

// error: "export 'default' (imported as 'XXXX') was not found in 'message-box'
```

move the `test-module` folder to node_modules, the build pass.

```
node_modules
   test-module
       index.js
```

Do I need any more configuration? 

webpack version: 4.12.2

```
// webpack config

resolve: {
    modules: ['node_modules', 'web_modules'],
    ....
}
```

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
