### ISSUE TITLE
DefinePlugin does not handle nested object correctly

### ISSUE THREAD

**Issue by myagoo** [webpack/webpack#761]
If I try to inject a complex (objects in object) configuration object via DefinePlugin, objects under the root one are casted to string.

**Comment by sokra** [comment]
Can you provide an example?

**Comment by myagoo** [comment]
I expected the following object to be injected correctly :

{
  foo: {
    bar: 'value'
  }
}

But what I got was :

{
  foo: [object Object]
}

2015-02-04 19:29 GMT+01:00 Tobias Koppers <notifications@github.com>:

**Comment by mderrick** [comment]
I have noticed the same issue:

```
new webpack.DefinePlugin({
    FOO: {
        BAR: {
            VALUE: JSON.stringify('Test Value')
        }
    }
})
```


```
FOO
FOO.BAR
```

Outputs:

```
({"BAR":[object Object]})
({"VALUE":"Test Value"})
```

I had a go at fixing it here: https://github.com/webpack/webpack/pull/791

**Comment by bebraw** [comment]
#791 has been merged so closing.
