### ISSUE TITLE
Provide multi-config plugin hook at higher level than `compilation`

### ISSUE THREAD

**Issue by ChrisBAshton** [webpack/webpack#7613]
## Feature request

We are using Webpack multi config to compile different language versions of our project.

What we need is a pre-install script that runs only once, then all of the language compilations, and then a post-install script that runs only once.

What we actually have is a config that runs our pre-install script before each language compilation, and our post-install script after each language compilation (i.e. multiple times).

This should be possible by just hooking into a different compiler hook. I've consulted the [plugin API](https://webpack.js.org/api/plugins/) docs, [writing a plugin](https://webpack.js.org/contribute/writing-a-plugin/) guide, [compiler hooks](https://webpack.js.org/api/compiler-hooks/) and [compilation hooks](https://webpack.js.org/api/compilation-hooks/) and it looks as though such a hook does not exist.

## webpack.config.js

```js
const webpackConfig = [];
utils.getIncludes().forEach((include, index) => {
    utils.getServices(include).forEach(language => {
        const configForLang = {
            entry: `./source/${include}/app.js`,
            output: {
                filename: `[name].${language}.js`,
            },
            plugins: [
                scaffoldCompilerInstance,
                new I18nPlugin(utils.getVocabJson(language, include)),
            ],
        };
        webpackConfig.push(configForLang);
    });
});
return webpackConfig;
```

## example plugin (pre-install and post-install hooks)

Our scaffold compiler plugin looks something like this:

```js
class ScaffoldCompiler {
    apply(compiler) {
        compiler.hooks.beforeCompile.tapAsync('ScaffoldCompiler', (compilation, done) => {
            this.executePreInstallScripts.then(done);
        });

        compiler.hooks.done.tapAsync('ScaffoldCompiler', (compilation, done) => {
            this.executePostInstallScripts.then(done);
        });
    }
```

**What is motivation or use case for adding/changing the behavior?**

We want to do some setup in the pre-install phase, e.g. make network requests to update local fixture files. And we want to do some tidying up in the post-install phase, e.g. deleting files, copying output into different directories.

**How should this be implemented in your opinion?**

The `compiler` parameter passed to the `apply` method in a Webpack plugin should expose a new hook, e.g.

```js
apply(compiler) {
  compiler.hooks.beforeAnyCompilation.tapAsync('...', () => {});
  compiler.hooks.afterAllCompilation.tapAsync('...', () => {});
}
```

**Are you willing to work on this yourself?**
I'm happy to give it a go, but am by no means a Webpack expert!

**Comment by ooflorent** [comment]
You can do this using the programmatic API of webpack instead of using the CLI:

```js
async function build() {
  const config = await getBuildConfig()
  await preBuildScripts()
  await new Promise(resolve => {
    webpack(config, () => {
      // Note: Dummy implementation
      resolve()
    })
  })
  await postBuildScripts()
}

build()
```

**Comment by sokra** [comment]
or add the script to the `npm scripts`.

**Comment by ChrisBAshton** [comment]
Want to avoid using `npm scripts` because we still want this setup to work with `webpack-dev-server`, which is why we're trying to go for a config-only approach.

**Comment by ChrisBAshton** [comment]
Still got my fingers crossed for a couple of extra hooks! 🤞

**Comment by celeryclub** [comment]
I'd love to see this too. My use case is measuring the total compilation time of a multi-config build while running in watch mode. As far as I know, there's no current programmatic workaround to this use case.

**Comment by wille** [comment]
My intention is to watch a multi config build and start a process depending of both the builds.

**Comment by msegers** [comment]
Also looking for something similar, I'd love to use the current (quite simple) plugins on the full build.
I'm also using plugins on both configurations to generate legacy and modern bundles and this setup could be simplified lots when multi-compiler plugins would be supported.

**Comment by atdiff** [comment]
Any chance this is still being considered? It'd be great to have some overall hooks before and after a multi compiler config.

**Comment by evilebottnawi** [comment]
Feel free to send a PR

**Comment by bcis-kassel** [comment]
Im also interested in this feature. My use case is an electron app which by design needs two configurations (one for electron-renderer and one for electron-main) because it is only possible to specify one target per configuration. 

However, in watch mode my electron app should restart on file changes, but it restarts twice per file change.

**Comment by Zomono** [comment]
I have posted a workaround for this problem on stackoverflow here 
https://stackoverflow.com/questions/68496721/webpack-execute-task-after-all-configurations-are-done-or-before-all/68496722#68496722

**Comment by alexander-akait** [comment]
I looked deeply on the issue and I think we don't need it you can do it using:
- https://webpack.js.org/api/compiler-hooks/#beforerun
- https://webpack.js.org/api/compiler-hooks/#shutdown (or https://webpack.js.org/api/compiler-hooks/#done)

Just create `let isRun = false;`, set it to `true` on first run and do not run your logic again, also there is `npm` scripts, orchestrator systems and etc, I really to a lot of different approaches to solve it without new hooks.

Feel free to ask me or ping me if you think another and please provie a case, thank you
