### ISSUE TITLE
require.resolve in "development" mode return path (behavior as in node.js)

### ISSUE THREAD

**Issue by sunkenwave** [webpack/webpack#7614]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**
webpack config with development mode
require.resolve return path (behavior as in node.js)

**What is the expected behavior?**
require.resolve in "development" mode return path (behavior as in node.js)

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by ooflorent** [comment]
I don’t understand what is the issue here. Could you provide an example to reproduce the problem? Best put it in a GitHub repository.
