### ISSUE TITLE
Entry points

### ISSUE THREAD

**Issue by heyflo** [webpack/webpack#7617]
Hello there,

Not an issue but a matter of sanity, is it correct to refer to a .scss file as an entry point ? As shown here : 
https://stackoverflow.com/a/42815934

I've seen a lot of people doing this but I actually never saw anything like that in the documentation. Is it correct to do that or should I import my main sass file in a *.js entry ?

Thanks for clarifying 👍

**Comment by ooflorent** [comment]
Yes it’s fine. I also do it this way when I don’t need css modules.
