### ISSUE TITLE
css-loader generate different [hash:base64:5] hash when i used LoaderOptionsPlugin 

### ISSUE THREAD

**Issue by MrKou47** [webpack/webpack#7619]
# Bug report

**What is the current behavior?**

i have clientEntry and serverEntry for build the universal react app, both these entryConfig use `css-loader`, but only clientEntry used `LoaderOptionsPlugin` and `transform-loader`.

**If the current behavior is a bug, please provide the steps to reproduce.**
I read the source code and find that css-loader used [interpolateName#L36](https://github.com/webpack/loader-utils/blob/master/lib/interpolateName.js#L36) to generate `localIdentName` hash. But when i used `LoaderOptionsPlugin` with `options` property, the css-loader generate different cssName with different hash. I add the breakpoint in the `interpolateName` function and find that has different context, so i guess that `LoaderOptionsPlugin` set `conetxt` to `undefined`, and then webpack generate a new context to cover that context.

I think that should we ignore the `key` if `key === context` or `context === undefined` [LoaderOptionsPlugin.js#L44](https://github.com/webpack/webpack/blob/master/lib/LoaderOptionsPlugin.js#L44), for avoid rewrite context key?

[gist](https://gist.github.com/MrKou47/d5ba3e38b6f69deedc9b67ea7350973c#file-css-loader-with-optionplugin-js)

**What is the expected behavior?**

Generate the same hash.

**Other relevant information:**
webpack version:  3.11.0
Node.js version: 9.11.1
Operating System:  osx
Additional tools:

**Comment by sokra** [comment]
Pass a `context` to the LoaderOptionsPlugin. It's only for backward-compatibility.

**Comment by MrKou47** [comment]
I try to add the `options.context` and then it works fine. Thanks.
