### ISSUE TITLE
path must be absolute or specify root to res.sendFile

### ISSUE THREAD

**Issue by muturgan** [webpack/webpack#7630]
# Bug report

**What is the current behavior?**
I have the node.js server:
```
const express = require('express');
const path = require('path');
const app = express()
  .use(express.static( path.join(__dirname, '../static') ))
  .use(express.json())
  .use(express.urlencoded({ extended: true }))
  .get('/', (req, res) => {res.sendFile( path.join(__dirname, '/../static/index.html') )});

const http = require('http').Server(app);
const io = require('socket.io')(http);
const PORT = process.env.PORT || 3333;

http.listen(PORT, () => {
  console.log(`server listening on ${ PORT }`);
});
```
I prefer to write:
`res.sendFile(__dirname +  '/../static/index.html')`
but I have the Angular on frontend and it needs
`path.join(__dirname, '/../static/index.html')`

it works nice, but now I want to concat and minimize my files.
so I use this config:
```
var path = require('path');
var nodeExternals = require('webpack-node-externals');

module.exports = {
  entry: './server/src/index.js',
  output: {
    path: path.resolve(__dirname, './server'),
    filename: 'server.js'
  },
  mode: 'production',
  devtool: false,
  target: 'node',
  externals: [nodeExternals({
        modulesFromFile: true,
    })],
}
```
it builds fine and the server starting fine.
but when I try to see the resut in browser, I get the error:
`TypeError: path must be absolute or specify root to res.sendFile`

**If the current behavior is a bug, please provide the steps to reproduce.**
you just need to run:
webpack
node server/server

Here's the repository: https://github.com/muturgan/pretty-chat

**What is the expected behavior?**
minimized code contains absolute or specify root paths
the server can give my static

**Other relevant information:**
webpack version:  4.14.0
Node.js version: 8.11.3
Operating System: windows 8
Additional tools: express 4.16.3, angular 6.0.8, webpack-node-externals 1.7.2

**Comment by sokra** [comment]
add

``` js
node: {
  __dirname: false,
}
```

to the config

**Comment by muturgan** [comment]
it works!
thank you wery much!

**Comment by junkkerrigan** [comment]
@sokra could u please explain what the problem is and why this solution works?

**Comment by sokra** [comment]
webpack polyfills __dirname in bundles. This disables that.

**Comment by rimtoken** [comment]
res.sendFile("./views/home.hotml",
{root:__dirname});} 

It is also a solution to the root problem.
