### ISSUE TITLE
pkg.module root dir

### ISSUE THREAD

**Issue by ichernev** [webpack/webpack#7631]
Hello webpack, I know moment is probably responsible for half of yor issues in the tracker, but I'm hoping to get this right in our next major release.

I know about [pkg.module](https://github.com/rollup/rollup/wiki/pkg.module), but I'm wondering if there is a way to specify root directory, instead of just a single file.

For example, if we have the following folder structure:

```
.
└── dist
    ├── esm
    │   ├── locale
    │   │   ├── de.js
    │   │   └── ru.js
    │   └── moment.js
    └── umd
        ├── locale
        │   ├── de.js
        │   └── ru.js
        └── moment.js
```

Is there a nice way to have both of these to work

```
// UMD
requre('moment');            // requires dist/umd/moment.js
require('moment/locale/ru'); // requires dist/umd/locale/ru.js
// ESM
import moment from 'moment'; // requires dist/esm/moment.js
import 'moment/locale/ru';   // requires dist/esm/locale/ru.js
```

**Comment by ichernev** [comment]
I was adviced here https://github.com/rollup/rollup/issues/2311 to use .js and .mjs per the node.js esm spec.

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
