### ISSUE TITLE
Debug is not defined after webpack start

### ISSUE THREAD

**Issue by jfnadev** [webpack/webpack#7632]
# Bug report

**What is the current behavior?**
When using  `webpack --watch` or `npx webpack --watch --config webpack.config.js`

**If the current behavior is a bug, please provide the steps to reproduce.**
Debug is not defined after using  `webpack --watch` or `npx webpack --watch --config webpack.config.js`

**What is the expected behavior?**
Any idea

**Other relevant information:**
webpack version:  4.12.1
Node.js version: 8.11.3
Operating System: Fedora 25/64 bits
Additional tools: jdotnet/.npm/_logs/2018-06-30T06_46_32_251Z-debug.log
// my log file
0 info it worked if it ends with ok
1 verbose cli [ '/home/jdotnet/.nvm/versions/node/v8.11.3/bin/node',
1 verbose cli   '/home/jdotnet/.nvm/versions/node/v8.11.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'watch' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle helpscout@1.0.0~prewatch: helpscout@1.0.0
6 info lifecycle helpscout@1.0.0~watch: helpscout@1.0.0
7 verbose lifecycle helpscout@1.0.0~watch: unsafe-perm in lifecycle true
8 verbose lifecycle helpscout@1.0.0~watch: PATH: /home/jdotnet/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/html/helpscout/node_modules/.bin:/home/jdotnet/.nvm/versions/node/v8.11.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/jdotnet/.composer/vendor/bin:/home/jdotnet/.local/bin:/home/jdotnet/bin
9 verbose lifecycle helpscout@1.0.0~watch: CWD: /var/www/html/helpscout
10 silly lifecycle helpscout@1.0.0~watch: Args: [ '-c', 'npx webpack --watch --config webpack.config.js' ]
11 silly lifecycle helpscout@1.0.0~watch: Returned: code: 1  signal: null
12 info lifecycle helpscout@1.0.0~watch: Failed to exec watch script
13 verbose stack Error: helpscout@1.0.0 watch: `npx webpack --watch --config webpack.config.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/jdotnet/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/jdotnet/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid helpscout@1.0.0
15 verbose cwd /var/www/html/helpscout
16 verbose Linux 4.13.16-100.fc25.x86_64
17 verbose argv "/home/jdotnet/.nvm/versions/node/v8.11.3/bin/node" "/home/jdotnet/.nvm/versions/node/v8.11.3/bin/npm" "run" "watch"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error helpscout@1.0.0 watch: `npx webpack --watch --config webpack.config.js`
22 error Exit status 1
23 error Failed at the helpscout@1.0.0 watch script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.
