### ISSUE TITLE
Error "ENOENT: no such file or directory" on migrating from webpack 2 to weback 4

### ISSUE THREAD

**Issue by AyushiS27** [webpack/webpack#7635]
# Bug report
I am migrating my application from webpack 2 to 4. I installed latest babel 7 modules and changed webpack config accordingly. But I am getting this error:

**What is the current behavior?**
`Module build failed (from ../node_modules/babel-loader/lib/index.js):
    (SystemJS) ENOENT: no such file or directory, open '/Users/abc/Documents/Projects/insurance-frontend/babel-core'`

`Error loading /Users/abc/Documents/Projects/insurance-frontend/babel-core as "babel-core" from /Users/abc/Documents/Projects/insurance-frontend/node_modules/babel-loader/lib/index.js
`

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  4.12.2
Node.js version: 6.13.1
Operating System: Mac
Additional tools:

**Comment by sokra** [comment]
It clearly states that this is related to babel.
