### ISSUE TITLE
Typings: Webpack.Compiler is not assignable to Compiler

### ISSUE THREAD

**Issue by jantimon** [webpack/webpack#7643]
# Bug report

**What is the current behavior?**

Passing a new compiler instance from  to a function which expects a `Compiler` instance causes a type error.

The following example will log the context twice without any errors however the typescript compiler will show two type errors:

```
const webpack = require("webpack");
/** @typedef {import('webpack').Compiler} WebpackCompiler */
/** @typedef {import('webpack/lib/Compiler')} Compiler */

const compiler = webpack(config);
console.log(compiler.context); // <- [ts] Property 'context' does not exist on type 'Compiler'.
someFunction(compiler); // <- [ts] Argument of type 'webpack.Compiler' is not assignable to parameter of type 'Compiler'.
/**
 * @param {Compiler} compiler
 */
function someFunction(compiler) {
   console.log(compiler.context);
}
```

![type-error](https://user-images.githubusercontent.com/4113649/42212948-d18bdd22-7eb7-11e8-8fa5-7f2d44c349a7.png)

**What is the expected behavior?**

`webpack(config)` should return an instance of `Compiler` or `Webpack.Compiler` should have a context property

**Other relevant information:**
webpack version:  4.14.0

**Comment by ooflorent** [comment]
Actually `webpack` returns either a `Compiler` or a`MultiCompiler` or a `Watching`  or a `MultiWatching`. All mentioned classes are not typed yet.

**Comment by sokra** [comment]
It looks like an inconsistency between webpack and `@types/webpack`. Eventually we will generate our own type definition from the source.

**Comment by KristijanJovanovski** [comment]
This is still an issue.

**Comment by evilebottnawi** [comment]
If you use `webpack@4` please open an issue in `@types/webpack`, if you use `webpack@5` please tests and if you faced with the problems, feel free to open a new issue
