### ISSUE TITLE
Option for using browser native dynamic import()

### ISSUE THREAD

**Issue by mizchi** [webpack/webpack#7644]
## Feature request

I need build option to handle dynamic import to load outer sources or just use native one to optimize.

https://stackoverflow.com/questions/50960619/can-i-use-browser-native-import-in-webpack-4

**What is the expected behavior?**

webpack just ignore dynamic import if options are given.

**What is motivation or use case for adding/changing the behavior?**

I want to use webpack for UI but in some case I use dynamic import() with string to load but webpack always handle this.

I'm trying service-worker side transform. That need this feature  https://github.com/mizchi/trans-loader

**Are you willing to work on this yourself?**

no. I don't know webpack internal yet.

**Comment by sokra** [comment]
`import(/* webpackIgnore: true */"...")`

**Comment by mizchi** [comment]
@sokra oh, it looks good to my  use case

**Comment by lptn** [comment]
is there any option for webpack v3?

**Comment by krutoo** [comment]
How can i ignore some dynamic imports from configuration file?

**Comment by rmorshea** [comment]
Another (non-ideal) solution is to do:

```javascript
eval(`import('${moduleURL}')`).then(...)
```

Since webpack will ignore the contents inside `eval()`
