### ISSUE TITLE
Typescript + webpack encore + foundation [syntax error on IE 11]

### ISSUE THREAD

**Issue by alex83130** [webpack/webpack#7645]
Hello all, 

I have a problem for many hours now and i can't find the solution...

On my Symfony 3 project I've decided to use webpack-encore to manage my assets. I use ES6 JS and Typescript to develop in a modern javascript code. Then Babel transpile the code in ES2015 to be interpreted by all browsers. I use also the framework Foundation CSS.

My first issu is a Syntax Error, everythink is ok on Chrome/Firefox/Edge but on IE 11 I have many error ....

![capture](https://user-images.githubusercontent.com/15250423/42218922-6c8babf6-7eca-11e8-91cf-e677102fef8a.PNG)

1. First error: Error Syntax
2. Second error: Unable to get the "call" property of a null or undefined reference
3. Third error: The object does not handle the property or method "each"

The error syntax comes from a "class" tag that is still present. I don't understand because the code should be in ES2015 and so there should not have this tag...

![capture2](https://user-images.githubusercontent.com/15250423/42218931-797b7828-7eca-11e8-979a-b22b5911ce80.PNG)

I put you the code of the foundation import, Maybe I don't have the right way :

        // webpack.config.js
       const  Encore = require('@symfony/webpack-encore');
       const webpack = require('webpack');
       const  path = require("path");
       const UglifyJsPlugin = require("uglifyjs-webpack-plugin");
       const ResponsiveSharp = require("responsive-loader/sharp");
       const DashboardPlugin = require('webpack-dashboard/plugin');

    Encore

    // enable source maps during development
    .enableSourceMaps(!Encore.isProduction())

    // the project directory where all compiled assets will be stored
    .setOutputPath('web/dist/')

    // the public path used by the web server to access the previous directory
    //Todo: In production remove web
    .setPublicPath('/dist')
    .setManifestKeyPrefix('dist')

    .createSharedEntry('vendor', [
        './web/assets/ts/app.ts',

        //vendor.css
        './web/assets/fonts/foundation-icons/foundation-icons.css',
        './web/assets/scss/app.scss',
    ])

     //Script
    .addEntry('polyfill', ["babel-polyfill"])
    .addEntry('home_page', ['./web/assets/ts/home_page.ts'])
    .addEntry('common', ['./web/assets/ts/common.ts'])
    .addEntry('essentiel_page', ['./web/assets/ts/essentiel_page.ts'])
    .addEntry('essentiels_mosaic_page', ['./web/assets/ts/essentiels_mosaic_page.ts'])
    .addEntry('creation_page', ['./web/assets/ts/creation_page.ts'])
    .addEntry('creations_mosaic_page', ['./web/assets/ts/creations_mosaic_page.ts'])
    .addEntry('creer_recette_page', ['./web/assets/ts/creer_recette_page.ts'])
    .addEntry('favoris_page', ['./web/assets/ts/favoris_page.ts'])
    .addEntry('login_page', ['./web/assets/ts/login_page.ts'])
    .addEntry('test', ['./web/assets/ts/test.ts'])

     //Style
     .addStyleEntry('home_style',[
     './web/assets/scss/home.scss'
    ])
    .addStyleEntry('common_style',[
        './web/assets/scss/common.scss'
    ])
    .addStyleEntry('essentiels_style',[
        './web/assets/scss/essentiels.scss'
    ])
    .addStyleEntry('creations_style',[
        './web/assets/scss/creations.scss'
    ])
    .addStyleEntry('creer_recette_style',[
        './web/assets/scss/creer_recette.scss'
    ])
    .addStyleEntry('custom_style',[
        './web/assets/scss/custom.scss'
    ])
    .addStyleEntry('var_style',[
        './web/assets/scss/var.scss'
    ])
    .addStyleEntry('login_style',[
        './web/assets/scss/login.scss'
    ])
    .addStyleEntry('print_style',[
        './web/assets/scss/print.scss'
    ])

    //Enable Typescri^t
    .enableTypeScriptLoader(function (typeScriptConfigOptions) {
        typeScriptConfigOptions.transpileOnly = true;
        typeScriptConfigOptions.configFile = 'tsconfig.json';
    })

    // allow legacy applications to use $/jQuery as a global variable
    .autoProvidejQuery()

    // empty the outputPath dir before each dist
    .cleanupOutputBeforeBuild()

    // show OS notifications when dists finish/fail
    .enableBuildNotifications()

    // allow sass/scss files to be processed
     .enableSassLoader(function(sassOptions) {}, {
             resolveUrlLoader: false
     })
    .enablePostCssLoader()
    .enableVersioning(Encore.isProduction())//Todo : Correct bug

     /*** Uglify accept ES6 ****/
     const webpackConfig = Encore.getWebpackConfig();

     /******************************/

    // Remove the old version first
    webpackConfig.plugins = webpackConfig.plugins.filter(
        plugin => !(plugin instanceof webpack.optimize.UglifyJsPlugin)
    );

    // Add the new one
    webpackConfig.plugins.push(new UglifyJsPlugin({
    /*    sourceMap: true*/
    }));
    /*********************/

    /** Watch options **/
    webpackConfig.watchOptions = { ignored: [/node_modules/] };
    /*******************/

    global.$ = global.jQuery = require('jquery');

    // export the final configuration
    module.exports = webpackConfig;

And my .babelrc :

    {
      "presets": [
         ["env", {
    /*      "modules": false,*/
          "targets": {
            "browsers": ["last 2 versions", "ie >= 10"]
          },
          "useBuiltIns": true,
          "debug": false,
          "sourceMaps": true
        }]
      ],
      "plugins": ["transform-runtime", "add-module-exports", "transform-property- 
     literals", "transform-member-expression-literals", "syntax-class- 
    properties","transform-class-properties","transform-es2015-template- 
    literals"]
    }

 view a similar issu : [https://foundation.zurb.com/forum/posts/39766-ie9-ie10-ie11-getting-a-syntax-error-in-plugins-code](url) but it's always not resolved in my case.

Thank you in advance for your held, I need it greatly -_-

**Comment by ooflorent** [comment]
This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons.
