### ISSUE TITLE
import  node_modules module ,Error: Can't resolve (Window10, Mac normal)

### ISSUE THREAD

**Issue by seekwe** [webpack/webpack#7649]
# Bug report
```js
// index.js
import axios from 'axios'
console.log('index:Promise',typeof Promise)
```
Module not found: Error: Can't resolve 'Promise' in node_modules/axios/lib/core/Axios.js

index.js have Promise, Axios.js not Promise.

Unless axios is also processed by babel, otherwise it will be given an error.

```js
    babel: {
      plugins: [
        require.resolve('babel-plugin-syntax-dynamic-import'),
        [
          require.resolve('babel-plugin-transform-runtime'),
          {
             helpers: true,
             polyfill: true,
             regenerator: true,
             moduleName: path.dirname(require.resolve('babel-runtime/package'))
          }
        ],
        require.resolve('babel-plugin-transform-vue-jsx')
      ],
      cacheDirectory: true,
      presets: [
        [
          require.resolve('babel-preset-env'),
          {
            modules: false,
            targets: {
              ie: 9,
              uglify: true
            },
            useBuiltIns: true
          }
        ],
       require.resolve('babel-preset-stage-2')
      ]
    }

...
{
          test: /\.js$/,
          use: {
            loader: 'babel-loader',
            exclude: /(node_modules)/,
            options: babel
          }
        }
```

**Other relevant information:**
webpack version:  4.14
Node.js version:  10 / 8

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by montogeek** [comment]
This is not related to webpack:
axios docs (https://github.com/axios/axios#promises) says:
> axios depends on a native ES6 Promise implementation to be supported. If your environment doesn't support ES6 Promises, you can polyfill.

Please install a polyfill.

It works with Babel because https://babeljs.io/docs/en/babel-plugin-transform-runtime#polyfill
> Toggles whether or not new built-ins (Promise, Set, Map, etc.) are transformed to use a non-global polluting polyfill.

**Comment by seekwe** [comment]
@sokra  This is one of my projects https://github.com/sohaha/zls-cli. there is no way to get an independent example in a short period of time. you can try `npm install -g zls-cli@dev && zls init test && cd test && npm run dev `. as long as it is not js in node_modules, promise can be used, but as long as it is js file in node_modules, it cannot be used.


@montogeek Thank you for your reply, but this is not the problem. axios calls the global, the web pack should not report the error, pointing to the wrong, and can use promise in indexjs. I mean, the node _ modules module needs to be processed by babel - loader before it can be used, and the module itself is es5 already.

**Comment by seekwe** [comment]
Added, Window and Mac have no problem, Linux reports an error.

**Comment by lxfu** [comment]
> @sokra This is one of my projects https://github.com/sohaha/zls-cli. there is no way to get an independent example in a short period of time. you can try `npm install -g zls-cli@dev && zls init test && cd test && npm run dev `. as long as it is not js in node_modules, promise can be used, but as long as it is js file in node_modules, it cannot be used.
> 
> @montogeek Thank you for your reply, but this is not the problem. axios calls the global, the web pack should not report the error, pointing to the wrong, and can use promise in indexjs. I mean, the node _ modules module needs to be processed by babel - loader before it can be used, and the module itself is es5 already.

Solve it ? i have the same problem!
