### ISSUE TITLE
Aliases for files?

### ISSUE THREAD

**Issue by ream88** [webpack/webpack#765]
I'm using [suitcss-base](https://github.com/suitcss/base) in a project I'm trying to bundle with webpack.

I'm not to able to bundle it, and the problem is located in suitcss-base's first line:

``` css
@import "normalize.css";
@import "./lib/base.css";
```

Both node's and webpack's `resolve` function fail to find normalize.css (probably due to the period in the name), and aliasing it like so doesn't work either:

``` js
alias: {
  'normalize.css': __dirname + '/node_modules/normalize.css/normalize.css'
}
```

Any ideas how to solve this problem?

**Comment by DavidSouther** [comment]
We had something similar and ended up using the `packageAlias`.
