### ISSUE TITLE
Watch facility: pause/resume

### ISSUE THREAD

**Issue by OliverJAsh** [webpack/webpack#7653]
Related to https://github.com/webpack/webpack/issues/7341

## Feature request

**What is the expected behavior?**

When I am working with git, I:

- often have merge conflicts, as I merge or rebase branches and pop my stashes
- intermittently jump between commits, e.g. when rebasing

When I am working in this way, I would like a way to pause webpack's watch facility, in order to reduce the amount of unnecessary load on my CPU/computer, as I don't need webpack to rebuild until I've finished this work (e.g. a rebase). When I am finished, I would like to be able to resume watching again.

Alternatively, watch could be disabled altogether, and I could just instruct webpack when I wanted it to rebuild (without having to restart my whole server, which has considerable overhead).

**How should this be implemented in your opinion?**

I could type "pause" or "resume" into the terminal where webpack is running (like you can type "rs" into a nodemon terminal to tell it to restart).

**Are you willing to work on this yourself?**
yes

**Comment by sokra** [comment]
You could start by implementing support for this to the node.js API. Send a PR
