### ISSUE TITLE
Bundle does not include 3rd party lib from node_modules after an update

### ISSUE THREAD

**Issue by lehno** [webpack/webpack#7666]
# Bug report

**What is the current behavior?**
Bundle does not include 3rd party lib from node_modules after an update on the lib.
The main project was upgraded from angular 5 to 6 one month ago using @angular/cli.
I don't believe the issue is with angular as webpack generates the bundle files. (Correct me if I am wrong)
If I install the lib using the tgz file directly "my-lib": "file:../../my-project/dist/my-lib", ng-build --prod works and the code in included in the bundle.
If I install the lib using the tgz file from cloud "my-lib": "https://myserver/my-lib.0.0.1.tgz", it does not include the lib code into the bundle file
If I install the lib using "@org/my-lib":"0.0.1", ng build --prod doesn't include the lib code into the bundle.

**If the current behavior is a bug, please provide the steps to reproduce.**
1 - Created I lib in a different workspace from the main project.
2- Published to a private npm.
3 - Installed the lib in the same workspace with a test project, npm install @org/my-lib, ng serve works and ng-build works, (it has the lib code in the bundle file)
4 - Installed the lib in my main project (that will consume the lib), its in another workspace.
5- ng serve works, ng build --prod does not include the lib code into the bundle.
6 - There is no error from angular-cli

**What is the expected behavior?**
If I have a private lib on npm and I update the version, when I build my files, it should include the updated version, it looks like it uses the cached version.

**Other relevant information:**
webpack version:  4.15
Node.js version:  8.10
Operating System: Windows 10
Additional tools: @angular/cli 6.0.8

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by lehno** [comment]
Its a cache problem, I need to delete node_modules, npm cache clear --force, npm install, ng build for every single change on my lib. Its been very hard to work like that. Im looking for a way of not caching private npm packages.
