### ISSUE TITLE
WebAssembly modules don't work with target electron-renderer

### ISSUE THREAD

**Issue by zroug** [webpack/webpack#7677]
# Bug report

Wasm files can't be imported when target is set to `electron-renderer`.

**What is the current behavior?**

When I `import()` a wasm file and target is set to `web` it works like intended, but when I change target to `electron-renderer` it doesn't work anymore because `__webpack_require__.w` is undefined.

**If the current behavior is a bug, please provide the steps to reproduce.**

 - Take any working project that uses WebAssembly modules like https://github.com/webpack/webpack/tree/master/examples/wasm-simple.
- Change target to electron-renderer.
- Display result in electron.

**What is the expected behavior?**

Wasm modules should be usable just like with target `web`.

**Other relevant information:**
webpack version: 4.15.1
Node.js version: 10.6.0
Operating System: Ubuntu 18.04
Additional tools: electron-webpack (error happens independent of it)

**Comment by ooflorent** [comment]
cc @xtuc @sokra: is WASM supported inside Electron?

**Comment by sokra** [comment]
It's not activated from electron. I guess it's supported in electron.

Add this:

https://github.com/webpack/webpack/blob/69f03be1ea5187e681d3295e679789aa0e6364a5/lib/WebpackOptionsApply.js#L100

and this:

https://github.com/webpack/webpack/blob/69f03be1ea5187e681d3295e679789aa0e6364a5/lib/WebpackOptionsApply.js#L91-L93

here:

https://github.com/webpack/webpack/blob/69f03be1ea5187e681d3295e679789aa0e6364a5/lib/WebpackOptionsApply.js#L172-L194

**Comment by xtuc** [comment]
WebAssembly should work on Electron. I don't really know what v8 version it uses tho.

**Comment by sokra** [comment]
Do you want to send a PR?

**Comment by zroug** [comment]
Closing since #7685 has been merged.
