### ISSUE TITLE
Stats config option is not used in watch mode

### ISSUE THREAD

**Issue by vladshcherbin** [webpack/webpack#7680]
# Bug report

**What is the current behavior?**

When using `stats` set to `none` or other, info is shown in console accordingly. However, in watch mode after a rebuild stats are shown differently. 

**If the current behavior is a bug, please provide the steps to reproduce.**

- set `stats` to `none` or other and start webpack in watch mode
- change something in a project
- see console output even if `stats` option is set to `none`

**What is the expected behavior?**

Watch mode should respect `stats` config option and output info accordingly.

**Other relevant information:**
webpack version:  4.15.1
Node.js version: 10.5.0
Operating System: mac os 10.13.4
Additional tools: none

**Comment by sokra** [comment]
> see console output even if stats option is set to none

which kind of output?

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by vladshcherbin** [comment]
Hm, I tried to reproduce now, but it's working which is very strange since I tried it multiple times.

Will create a reproducible example first next time, sorry 🙏
