### ISSUE TITLE
hot-update :__webpack_exports__["default"] Pointing error

### ISSUE THREAD

**Issue by seekwe** [webpack/webpack#7681]
# Bug report

There is no problem at ordinary times, but when I start the web pack and then import a module, there will be problems.

I am not very good at expressing it. please take a look at the screenshot below.

Normal startup, hot has not been triggered yet:

![](http://ww1.sinaimg.cn/large/63a61209gy1ft3l3izqloj20uv0jxq45.jpg)

**What is the current behavior?**

import module,Trigger hot update:

![](http://ww1.sinaimg.cn/large/63a61209gy1ft3l5cgh89j20v40mc0u8.jpg)

```js
 var pages_homevue_type_script_lang_js = __webpack_exports__["default"] = (qr["default"]);
```

**What is the expected behavior?**
```js
 var pages_homevue_type_script_lang_js = __webpack_exports__["default"] = (homevue_type_script_lang_js);
```

**Other relevant information:**
webpack version:  4.15.1
Node.js version: 10
Operating System: Windows
Additional tools:

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by seekwe** [comment]
Reproduce using lazy -loading
```js
import(/* webpackChunkName: "home" */'@/pages/home.vue'),
```

**Comment by sokra** [comment]
> import(/* webpackChunkName: "home" */'@/pages/home.vue'),

I can't reproduce it with this single line of code.

Create a repo, which can be cloned, easily ran and is small with the minimal amount of code and config needed to reproduce the issue.
