### ISSUE TITLE
Solve why Error 。ES6

### ISSUE THREAD

**Issue by timehdl** [webpack/webpack#7683]
![image](https://user-images.githubusercontent.com/22724502/42444957-266a94dc-83a4-11e8-882f-623e8a2f6868.png)
![image](https://user-images.githubusercontent.com/22724502/42444977-37dadd8a-83a4-11e8-8285-bd65546ca44e.png)
![image](https://user-images.githubusercontent.com/22724502/42444993-3de25cda-83a4-11e8-95e4-3d8a54766476.png)

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
