### ISSUE TITLE
Watcher.close shouldn't require a callback

### ISSUE THREAD

**Issue by fresheneesz** [webpack/webpack#769]
Its cool that the `close` method has a callback so you know when its actually closed. But if you  just wanna close it and don't care when it closes, you shouldn't have to pass in a callback. It throws a confusing internal error if you don't pass the callback currently.

**Comment by sokra** [comment]
Please send a PR

**Comment by fresheneesz** [comment]
@sokra Look good?

**Comment by hkal** [comment]
With #778 being merged, this can be closed.
