### ISSUE TITLE
ProfilingPlugin unhandled Promise rejection "Session is not connected" on rebuild

### ISSUE THREAD

**Issue by lencioni** [webpack/webpack#7690]
# Bug report

When running the ProfilnigPlugin and then updating a file to trigger a rebuild, I noticed an unhandled Promise rejection.

I added this code to get a stack trace:

```js
process.on('unhandledRejection', (unhandledRejectionError) => {
  throw unhandledRejectionError;
});
```

And the stack trace shows:

```
Error: Session is not connected
    at Session.post (inspector.js:66:13)
    at Promise (/path/to/project/node_modules/webpack/lib/debug/ProfilingPlugin.js:49:25)
    at new Promise (<anonymous>)
    at Profiler.sendCommand (/path/to/project/node_modules/webpack/lib/debug/ProfilingPlugin.js:48:11)
    at Profiler.stopProfiling (/path/to/project/node_modules/webpack/lib/debug/ProfilingPlugin.js:71:15)
    at compiler.hooks.done.tapAsync (/path/to/project/node_modules/webpack/lib/debug/ProfilingPlugin.js:197:21)
    at args (/path/to/project/node_modules/webpack/lib/debug/ProfilingPlugin.js:382:11)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/path/to/project/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:9:1)
    at Watching._done (/path/to/project/node_modules/webpack/lib/Watching.js:99:28)
    at compiler.emitRecords.err (/path/to/project/node_modules/webpack/lib/Watching.js:73:19)
```

The code in the stack trace is:

```js
sendCommand(method, params) {
  if (this.hasSession()) {
    return new Promise((res, rej) => {
      return this.session.post(method, params, (err, params) => {
        if (err !== null) {
          rej(err);
        } else {
          res(params);
        }
      });
    });
  } else {
    return Promise.resolve();
  }
}
```

line 49 there is 

```js
return this.session.post(method, params, (err, params) => {
```

**What is the current behavior?**

A rebuild when using ProfilingPlugin causes an unhandled Promise rejection.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Add the following code to your webpack compiler:

```js
process.on('unhandledRejection', (unhandledRejectionError) => {
  throw unhandledRejectionError;
});
```

2. Start webpack with the ProfilingPlugin and wait for it to build.
3. Modify a file and wait for it to rebuild.

**What is the expected behavior?**

There should not be an unhandled Promise rejection, and the events.json file should be updated for the rebuild.

**Other relevant information:**
webpack version: 4.15.1
Node.js version: 8.9.1
Operating System: macOS 10.13.5
Additional tools:

cc @samccone

**Comment by montogeek** [comment]
Check #7655

**Comment by sokra** [comment]
Yeah, it seem like the error handling in this plugin is really bad.

* the returned Promise of `startProfiling` is ignored
* the returned Promise of `stopProfiling` has no `catch` (best use `tapPromise` here instead)
* the returned Promise of `destroy` is ignored (but it's probably unneeded at all, return type can be changed to void)
* It looks like `Session.post` throws an sync error instead of calling the callback. That seem to be a weird API problem.

**Comment by samccone** [comment]
Happy to take a look when I'm back from holiday, thanks for filling.

**Comment by samccone** [comment]
@sokra @TheLarkInn feel free to assign me to this bug, I am looking into this now.

Thanks

**Comment by samccone** [comment]
Confirmed I am able to reproduce this error with the following

    webpack-cli -w  --plugin webpack/lib/debug/ProfilingPlugin

And then editing a file after initial save.

**Comment by filipesilva** [comment]
@samccone did you have a chance to look at how ProfilingPlugin should be working on rebuilds?
