### ISSUE TITLE
Watch breaks files outputted by CommonsChunkPlugin

### ISSUE THREAD

**Issue by cowwoc** [webpack/webpack#770]
I am running across a bug where Webpack generates an invalid Javascript file when running in watch mode. This bug occurs 100% of the time, the first time I modify `Cards.js` in watch mode. Once the file is in a bad state, I keep on getting the following error:

```
 undefined is not a function
__webpack_require__@http://localhost:8080/com/realestate/frontend/page/Common.js:51:30
Object.webpackJsonp.0@http://localhost:8080/com/realestate/frontend/page/Cards.js:21:2
__webpack_require__@http://localhost:8080/com/realestate/frontend/page/Common.js:51:30
webpackJsonpCallback@http://localhost:8080/com/realestate/frontend/page/Common.js:22:20
(?)()@http://localhost:8080/com/realestate/frontend/page/Cards.js:1:1Common.js:1256 printUncaughtErrorCommon.js:1285 window.onerror
Common.js:51 Uncaught TypeError: undefined is not a function
```

The only way to fix the problem is to clean-build the entire project (further incremental changes to the file do not fix the problem).

Here is a copy of `Common.js`: https://gist.github.com/cowwoc/b752cf667c049af05cec
Here is a copy of `Cards.js`: https://gist.github.com/cowwoc/5cfcc58edc3b1a8aee40

I am modifying `Cards.js` line 54 over and over in order to trigger this problem.

I walked through the code and discovered that the browser hits line 51 with `module[moduleId]` equal to 29. This is problematic for two reasons:
1. Usually `module[moduleId]` points to a function, not a number.
2. Module 29 is generated by a call to `require("./ResourceTable.scss")`. If you look for it in `Common.js` you will notice it is not defined.

**Comment by cowwoc** [comment]
I think I figured out the problem.

1. I have multiple entry points, one of them is called `Cards.js`
2. At build-time, webpack outputs `Cards.js`, `Common.js` and JS files for other entry points.
3. At watch-time, I modify `Cards.js` and Webpack outputs:

```
[00:11:48] Compiling webpack config ~\Documents\realestate\frontend\webpack.config.js
[00:11:48] 
              Asset  Size  Chunks             Chunk Names
Authentications.css   335       4  [emitted]  Authentications
          Index.css   510       2  [emitted]  Index
          Cards.css   531       3  [emitted]  Cards
         Common.css   190       5  [emitted]  Common
```

Fortunately, I've got http://www.browsersync.io/ enabled, and its plugin outputs:

```
[BS] 4 files changed (Authentications.css, Index.css, Cards.css, Common.css)
```

Meaning, in step 3 Webpack is modifying `Cards.js` but not `Common.js`. This means that module IDs change in `Cards.js` which will cause `Common.js` to break.

Here is a copy of my `webpack.config.js`:

```
var buildConfig = require("./buildConfig.js");
var namespace = "com/realestate/frontend/";
var srcEntryDir = buildConfig.srcDir + namespace + "page/";
var targetEntryDir = buildConfig.targetDir + namespace + "page/";
var path = require("path");
var resolve =
{
	alias: {}
};
var noParse = [];
/**
 * @param {String} literal the literal string to escape
 * @return {String} a regular expression containing the literal string
 * @see http://stackoverflow.com/a/6969486/14731
 */
function escapeRegExp(literal)
{
	return literal.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&");
}

/**
 * Indicates that a dependency won't be changing at runtime (improves performance).
 *
 * @param {String} name the module name
 * @param {String} relativePath the dependency path
 * @see http://christianalfoni.github.io/javascript/2014/12/13/did-you-know-webpack-and-react-is-awesome.html
 */
function addStaticDependency(name, relativePath)
{
	resolve.alias[name] = path.resolve(relativePath);
	noParse.push(new RegExp(escapeRegExp(relativePath) + "$"));
}

/**
 * Registers a webjar.
 *
 * @param {String} name the webjar name
 * @param {String} relativePath the webjar path relative to the "webjars" directory
 * @see http://www.webjars.org/
 */
function addWebjar(name, relativePath)
{
	addStaticDependency("webjars/" + name, "target/webjars/META-INF/resources/webjars/" + relativePath);
}

addWebjar("log4javascript.js", "log4javascript/1.4.10/log4javascript.js");
addWebjar("prefixfree.js", "prefixfree/b44a065/prefixfree.js");
addWebjar("cowwoc-alphanum-sort.js", "cowwoc-alphanum-sort/1.0.0/alphanum-sort.js");
addWebjar("cowwoc-jquery-address.js", "cowwoc-jquery-address/1.6/cowwoc-jquery-address.js");
var webpack = require("webpack");
// See https://github.com/petehunt/webpack-howto
var commonsPlugin = new webpack.optimize.CommonsChunkPlugin(
{
	name: "Common",
	filename: "Common.js",
	minChunks: 2
});
var dedupePlugin = new webpack.optimize.DedupePlugin();
var ExtractTextPlugin = require("extract-text-webpack-plugin");
var fontPath = "[path]/[name].[ext]";
var imagePath = "[path]/[name].[ext]";
var cssPath = "[name].css";
var context = srcEntryDir;
var extractTextPlugin = new ExtractTextPlugin(cssPath);

module.exports =
{
	resolve: resolve,
	entry:
	{
		Authentications: srcEntryDir + "Authentications.js",
		Cards: srcEntryDir + "Cards.js",
		Index: srcEntryDir + "Index.js",
		Properties: srcEntryDir + "Properties.js",
		Users: srcEntryDir + "Users.js"
	},
	output:
	{
		path: path.resolve(targetEntryDir),
		// Template based on "entry" keys
		filename: "[name].js"
	},
	module:
	{
		noParse: noParse,
		loaders:
		[
			{
				test: /\.woff$/,
				loader: "url-loader?limit=10000&mimetype=application/font-woff&name=" + fontPath + "&context=" + context
			},
			{
				test: /\.ttf$/,
				loader: "url-loader?limit=10000&mimetype=application/octet-stream&name=" + fontPath + "&context=" + context
			},
			{
				test: /\.eot$/,
				loader: "file-loader?name=" + fontPath + "&context=" + context
			},
			{
				test: /\.svg$/,
				loader: "url-loader?limit=10000&mimetype=image/svg+xml&name=" + imagePath + "&context=" + context
			},
			{
				test: /\.png$/,
				loader: "url-loader?limit=10000&mimetype=image/png&name=" + imagePath + "&context=" + context
			},
			{
				test: /\.css$/,
				loader: extractTextPlugin.extract("style-loader", "css-loader")
			},
			{
				test: /\.scss$/,
				// use ! to chain loaders
				loader: extractTextPlugin.extract("style-loader", "css-loader!sass-loader")
			},
			{
				test: /\.json$/,
				loader: "json"
			}
		]
	},
	plugins:
	[
		commonsPlugin,
		dedupePlugin,
		extractTextPlugin
	],
	externals:
	{
		// Push 3rd-party libraries out to CDN.
		// @see http://stackoverflow.com/a/558494/14731
		stripe: "Stripe",
		jquery: "$",
		q: "Q",
		URIjs: "URI",
		"stacktrace-js": "printStackTrace",
		log4javascript: "log4javascript"
	},
	debug: true
};
```

**Comment by cowwoc** [comment]
Quoting @sokra on IRC:

> @cowwoc I may have an explanation... but still think it's related to the dedupe plugin (DP)...
DP inserts deduplication code when modules are deduplicated. ETP replaces extracted modules with an empty module when extracted. In the first build there are no duplicate modules. In the second build the DP finds the empty modules from the ETP and flag them as duplcated (this means references to equal modules are inserted, a number as module instead of a function), but the entry chunk is not rewritten and deduplication code is missing...

**Comment by cowwoc** [comment]
@sokra Unfortunately, https://github.com/webpack/webpack/commit/13b60359f42980099c57ac7626d79dfa5b1efcea did not fix the problem for me. Please reopen this issue and I will provide some sort of testcase to it so you can reproduce this on your end.

**Comment by sokra** [comment]
> I will provide some sort of testcase to it so you can reproduce this on your end.

ok... Thanks

**Comment by spalger** [comment]
@cowwoc I think we may be experiencing this now, did you ever track it down?

**Comment by cowwoc** [comment]
@spalger sorry, no. I did not. My project got dropped suddenly (the company declared bankruptcy) so I moved on to more urgent matters.

Please let us know if you are able to reproduce this problem consistently.

**Comment by janusch** [comment]
I also have this bug. This happens when I change a file in a bundle with several chunks and the bundle is part of the CommonChunksPlugin.

It would be extremely nice if this could get fixed, since it is a major annoyance in the development workflow.

**Comment by kgdev** [comment]
Here is the assets.json output:

  "commons": [
        "/public/assets/c",
        "/public/assets/o",
        "/public/assets/m",
        "/public/assets/n",
        "/public/assets/s",
        "/public/assets/.",
        "/public/assets/b",
        "/public/assets/d",
        "/public/assets/4",
        "/public/assets/f",
        "/public/assets/2",
        "/public/assets/7",
        "/public/assets/3",
        "/public/assets/0",
        "/public/assets/6",
        "/public/assets/5",
        "/public/assets/8",
        "/public/assets/u",
        "/public/assets/l",
        "/public/assets/e",
        "/public/assets/j"
    ]

**Comment by pontusdacke** [comment]
Error is still present. Watch breaks code, while manual run works correctly.
