### ISSUE TITLE
Can I use Webpack in production(revision needed)?

### ISSUE THREAD

**Issue by jiyinyiyong** [webpack/webpack#771]
I want to try migrating Gulp to Webpack but by going through Webpack's docs I found nothing on this. Is that part of Webpack's jobs?

**Comment by Chrazy** [comment]
Are you looking for a migration guide? There is no specific guide as how to migrate from X to webpack but you can start by looking through the docs and you'll see that you can do pretty much everything it does (regarding to building).

**Comment by jiyinyiyong** [comment]
Revision is a pain to me: https://github.com/smysnk/gulp-rev-all

**Comment by sokra** [comment]
http://webpack.github.io/docs/long-term-caching.html

JS: Use `[hash]` or `[chunkhash]` in `output.filename`.
CSS: Use `[hash]` or `[contenthash]` in `ExtractTextPlugin`
OTHER: Use `[hash]` with `file-loader (default)

**Comment by jiyinyiyong** [comment]
@sokra Thanks, looks nice, I'll try it.

**Comment by jiyinyiyong** [comment]
Long term cache is nice to me.
Do you have tool to replace urls in template engine then. I found replacing the contents in the `assets.json` is quite hard to be reused across projects.

**Comment by Chrazy** [comment]
You can look how it's done in https://github.com/webpack/react-starter where the css- and js-bundle are hashed and handled by the server.

**Comment by jiyinyiyong** [comment]
@Chrazy quite interesting when we have a server.

**Comment by bebraw** [comment]
@jiyinyiyong Safe to close?
