### ISSUE TITLE
webpackPrefetch should take netinfo API data into consideration.

### ISSUE THREAD

**Issue by malchata** [webpack/webpack#7711]
## Feature request

**What is the expected behavior?**
Currently, prefetches initiated by the [`webpackPrefetch` inline directive](https://webpack.js.org/guides/code-splitting/#prefetching-preloading-modules) fire regardless of a user's connection quality. [The netinfo API](https://wicg.github.io/netinfo/) should be used (where available) to respect [a user's preference for reduced data usage](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/save-data/), or abort speculative prefetching where connection quality is sufficiently poor.

**What is motivation or use case for adding/changing the behavior?**
In some cases, a user's network quality may be sufficiently poor or data plans may be restrictive enough that an unused prefetch could effectively be a waste of a data.

**How should this be implemented in your opinion?**
Currently, Chrome exposes downlink speed, effective connection type, and the Save-Data client hint status in the `network.connection` object. [Because support for the netinfo API](https://caniuse.com/#feat=netinfo) is not ubiquitous, it would be ill-advised to _only_ prefetch in this presence of this API. Instead, we may want an approach such as the following:

```javascript
if ("connection" in navigator) {
  if (navigator.connection.saveData === false && navigator.connection.effectiveType === "4g") {
    // Only prefetch in these conditions!
  }
} else {
  // Prefetch anyway
}
```

In this simplified example, the browser will always prefetch in the presence of a `webpackPrefetch` inline directive if `navigator.connection` is unavailable. This is because we don't want to effectively confine the benefits of prefetching to Chrome. If `navigator.connection` _is_ available, though, the browser will then inspect the `effectiveType` object to ensure the network connection is sufficiently fast, and if the user has not turned on [Data Saver mode](https://support.google.com/chrome/answer/2392284?hl=en&co=GENIE.Platform%3DAndroid) (which we can interpret to mean that the user does not want to waste data through speculative prefetching).

**Are you willing to work on this yourself?**
Yes, if given some guidance to know where I can implement the behavior! I'm very new to the webpack codebase.

**Comment by montogeek** [comment]
Maybe via a plugin? This doesn't feel right to be implemented in the core.

**Comment by beldur** [comment]
[guess-js](https://github.com/guess-js) from Google actually takes NetInfo into account. See: https://github.com/guess-js/guess/blob/master/experiments/guess-static-sites/server.js#L22
