### ISSUE TITLE
a dependency of webpack, eslint-scope@3.7.2 has been hacked

### ISSUE THREAD

**Issue by buhichan** [webpack/webpack#7714]
see https://github.com/eslint/eslint-scope/issues/39
eslint-scope@3.7.2 is a hacked version, which sends your ~/.npmrc to the hacker.
currently webpack depends on eslint-scope@^3.7.1, it's harmful.

**Comment by selbekk** [comment]
The hacked version has been unpublished now - but the harm may already have been done. 

You - the user - might have lost your NPM auth tokens. If not you, it might have happened to your CI servers. Chances are you are affected. This is what you do:

1. Turn on 2-factor authentication on NPM. Just do it.
2. Revoke all of your NPM auth tokens ([see how to here](https://docs.npmjs.com/cli/token)) and create new ones.

**Comment by sokra** [comment]
That's bad...

**Comment by shellscape** [comment]
Following up on removing tokens, it's far easier to go to https://www.npmjs.com/settings/<username>/tokens and remove them there. You'll have to `npm login` locally and recreate any tokens for services that connect to your account.

**Comment by CharlesStover** [comment]
npmjs has invalidated all tokens to resolve this issue; however, `eslint-scope@3.7.3` is published to fix this. `webpack` should upgrade immediately, imo, to resolve this issue for all users as simply as installed `webpack@latest`.

**Comment by montogeek** [comment]
It seems issue is resolved.
