### ISSUE TITLE
DefinePlugin / add support for watch mode

### ISSUE THREAD

**Issue by crazyx13th** [webpack/webpack#7717]
## Feature request

**What is the expected behavior?**
For Example: I have a build nr, which increments each "runWatch" hook. But DefinePlugin  only define variables at start, not on re-compile.

**What is motivation or use case for adding/changing the behavior?**
Now you can use a Function as a value (https://github.com/webpack/webpack/issues/6749). DefinePlugin only should update value with this defined function.

**How should this be implemented in your opinion?**
Only update values with the user defined function. Many other Plugins use a function for updates values on re-compile.

**Are you willing to work on this yourself?**
I will support this as good as I can :-)

**Comment by crazyx13th** [comment]
thx!
if someone need's it, here is an example:
```javascript
this.plugins.push(new webpack.DefinePlugin({
	'app.env': {
		'appVersion': `"${this.settings.appVersion}"`,
		'appHash': `"${this.settings.appHash}"`,
		'buildNr': webpack.DefinePlugin.runtimeValue(() => `"${this.settings.buildNr}"`, []),
		'apiPath': `"${process.env.APP_APIPATH}"`,
		'stage': `"${this.configuration.mode}"`,
	}
}));
```

**Comment by ZuBB** [comment]
Thanks @crazyx13th it does work!

**Comment by kettanaito** [comment]
For anybody wondering, this is how you provide a runtime define variable:

```js
// webpack.config.js
const webpack = require('webpack')

module.exports = {
  plugins: [
    new webpack.DefinePlugin({
      MY_VARIABLE_NAME: webpack.DefinePlugin.runtimeValue(
        () => JSON.stringify('ANY_VALUE'),
        // Passing the second argument as `true` reevaluates the defined expression.
        // Beware that this disables module caching and must be used with caution.
        true,
      ),
    })
  ]
}

```
