### ISSUE TITLE
localForage 1.2.2 + webpack 1.5.3 doesn't want to collaborate

### ISSUE THREAD

**Issue by ALF-er** [webpack/webpack#772]
Hello. It seems that this PR don't fix problem of using localForage with webpack. I've created gist to illustrate problem https://gist.github.com/ALF-er/83325c24019de4edc851 (just place file index.html in ./src/ dir and main.js in ./src/js/ dir).
If I run "npm run dev" (it just copy index.html in ./dist/ dir, compile main.js with webpack and then run webpack-dev-server for ./dist/) I get:
```
WARNING in ./~/localforage/src/localforage.js
Critical dependencies:
332:20-336:22 the request of a dependency is an expression
 @ ./~/localforage/src/localforage.js 332:20-336:22

ERROR in ./~/localforage/src/drivers/localstorage.js
Module not found: Error: Cannot resolve module 'localforageSerializer' in C:\dev\projects\wp_lf_test\node_modules\localforage\src\drivers
 @ ./~/localforage/src/drivers/localstorage.js 70:16-59

ERROR in ./~/localforage/src/drivers/websql.js
Module not found: Error: Cannot resolve module 'localforageSerializer' in C:\dev\projects\wp_lf_test\node_modules\localforage\src\drivers
 @ ./~/localforage/src/drivers/websql.js 63:16-59
```
If in main.js uncomment second line (and comment first ofc) then it builds w/o errors but in browser console I get `localForage.getItem` - undefined function...

Maybe you can suggest something?

**Comment by gaearon** [comment]
Crossposted from https://github.com/mozilla/localForage/issues/344.

Relevant lines in source:

https://github.com/mozilla/localForage/blob/master/src/drivers/localstorage.js#L70

fails statically, with serializer being declared here:

https://github.com/mozilla/localForage/blob/master/src/utils/serializer.js#L224

**Comment by gaearon** [comment]
For now, the workaround we found is to put `'localforageSerializer': '../utils/serializer'` in `resolve.alias`.

**Comment by hurelu** [comment]
Even when localforage is in a script  tag and included in `externals` in an attempt to completely bypass webpack I still get an error in the browser: 
```
bootstrap 011107a16ec9e1c5c1a1:19 Uncaught TypeError: Cannot read property 'call' of undefined

**Comment by hurelu** [comment]
@gaearon could you please elaborate a little more on how it was resolved? I've added serializer in alias but I still get errors.

**Comment by MattKunze** [comment]
Even with that workaround I'm still seeing warnings from the wildcard AMD require:

https://github.com/mozilla/localForage/blob/1406da2c31b8f2027ace1b6e02e324b2ea179a1b/src/localforage.js#L332

did you figure out a way to avoid that? I'm using script-loader to work around it work now, but I'd prefer to require it natively

**Comment by dev101** [comment]
check out https://github.com/gowravshekar/webpack-localForage

**Comment by bebraw** [comment]
@ALF-er Any update on this? Apparently [1.2.10](https://github.com/mozilla/localForage/issues/344#issuecomment-135988529) should have fixed it.

**Comment by MattKunze** [comment]
Not sure about 1.2.10, but 1.3.0 seems to work with webpack. I don't need to use script-loader any more, just `var localforage = require('localforage);`
