### ISSUE TITLE
Documentation: is webpack now multithreaded by default?

### ISSUE THREAD

**Issue by misterfresh** [webpack/webpack#7720]
In monitoring tools of Task Manager, with webpack 3 I can see only one thread active when compiling.

With Webpack 4 I can see 4 cores 8 threads active at 100% when compiling.

Can you clarify that latest webpack is now multithreaded by default? in the docs. 
This is useful to know if its worth it to install additional plugins like happypack to enable multithreading. Thanks

**Comment by evilebottnawi** [comment]
@misterfresh no, `webpack` doesn't in `multithreading` mode, only some plugins works in `multithreading` mode, also please use issue template in future
