### ISSUE TITLE
Unable to externalize context/dynamic require

### ISSUE THREAD

**Issue by aczekajski** [webpack/webpack#7734]
## Feature request
There should be an easy way to make `require` calls external for a `node` target. For now the behaviour seems to be inconsistent because `require('./someModule')` is treated completely different than `require('./modules/' + name)`.

**What is the expected behavior?**
Making module external should be possible to accomplish purely by webpack configuration, without using webpack-specific code like `__non_webpack_require__`.

**What is motivation or use case for adding/changing the behavior?**
I have a scenario where my application (`target: 'node'`) automatically loads external middlewares (not built in by webpack) from certain folder. If middlewares paths were predefined, it's not a problem, I can do
```js
const m1 = require('./middlewares/first/index.js');
const m2 = require('./middlewares/second/index.js');
```
and in my webpack configuration I can specify:
```js
{
  externals: [
    (context, request, callback) => {
       if (/middlewares/.test(request)) {
          return callback(null, 'commonjs ' + request);
       }
       callback();
    },
  ],
}
```
and the above require statements will be evaluated during runtime of built app. There's no need for them to be present anywhere in project during build. 

However, my case is all about dynamic loading. I'd like to load the modules based on folder contents or based on some list known only in runtime:
```js
for (const name of middlewareNames) {
  middlewares[name] = require('./middlewares/' + name + '/index.js');
}
```
That way, unfortunately, the path from this `require` statement never reaches the function specified in `externals`. Since `middlewares` folder is not present in project during build, it ends up throwing
```
ERROR in ./src/server.ts
Module not found: Error: Can't resolve './middlewares' in 'C:\...'
```
I see no way to just mark this dynamic require call as external. The same thing happens if I try using context:
```js
require.context('./middlewares', false, /index\.js/);
```

One workaround for this problem is using `__non_webpack_require__` for my dynamic middlewares loading mechanism. But this is vendor-locking. If I ever decide to change from webpack to something else, I'd need to replace `__non_webpack_require__` with something else. Or, if I want to build-in some middlewares and still be able to load other middlewares dynamically during runtime, it will again require code changes while in fact a simple `require` in a loop and some configuration in webpack should be enough to accomplish the task.

**How should this be implemented in your opinion?**
Since webpack does a static code analysis anyway, it might be achieved by webpack-specific comments in code. This way, it doesn't break the original code and won't require any changes if one choose to build app in different way or to run it directly.

1. It should be possible to explicitly mark require as external:
```js
require(/* webpack-require-external */'./middlewares/' + name + '/index.js');
require(/* webpack-require-external */moduleName);
```
2. All require calls not marked as external should be passed to the externals resolver and in this case:
```js
require('./middlewares/' + name + '/index.js');
```
it should still try to find all possible existing files in project that match the expression (like `'./middlewares/builtInMiddleware/index.js'`) and these (if the exist) will be passed to externals resolver, but besides that, a special request like this should be passed too: `'./middlewares/*/index.js'`. If user doesn't explicitly do
```js
return callback(null, 'commonjs ' + request);
```
the resulting app will behave as usual, throwing module not found error in runtime if you try to import something that's not already built-in. But if you do mark it as `commonjs` module, resulting app will try to perform standard `require` call (equivalent of `__non_webpack_require__`) for all require calls to modules that are not already built-in.
3. It might be useful to also do require like this:
```js
require(/* webpack-require-fallback-external */moduleName);
```
which in runtime will try to use a built-in module and if module like that is not present, it will perform standard require.

**Are you willing to work on this yourself?**
I think my knowledge on internal webpack mechanisms is too week for now

**Comment by ooflorent** [comment]
Have you tried this? https://github.com/liady/webpack-node-externals

It works like a charm. Using `externals` is the way to go.

**Comment by aczekajski** [comment]
@ooflorent I've explained in the issue that dynamic requires do not reach functions passed to `externals` at all.

**Comment by vankop** [comment]
@sokra I think it is solved in webpack@5, am I right?

**Comment by vankop** [comment]
@aczekajski there is `__non_webpack_require__ ` https://webpack.js.org/api/module-variables/#__non_webpack_require__-webpack-specific that is looks like what you are expect. Feel free to feedback.
