### ISSUE TITLE
Bill Of Materials

### ISSUE THREAD

**Issue by hrieke** [webpack/webpack#7735]
## Feature request

Hi guys,

It would be really nice if you produced a Bill Of Materials file next to the compiled output that lists where the snippets come from. 
From time to time I'll spot something like this:
Copyright (c) Microsoft, All rights reserved. See License.txt in the project root for license information.

Says nothing of the file's orgin, it's license, or anything else expect that it's code from Microsoft.
The purpose is when audits are performed, these files are not a nightmare.

Thank you for your consideration.

**What is the expected behavior?**
Generate a file that contains the file name and license name if possible, bonus points for source location (project URL if external).

**What is motivation or use case for adding/changing the behavior?**
Passing source code audits with flying colors.

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
Sadly, no

**Comment by evilebottnawi** [comment]
@hrieke it is hard to implements, difference projects keep copyright in difference places, better create plugin for this purpose

**Comment by ooflorent** [comment]
You could also use uglify to extract the licenses to another file.

**Comment by evilebottnawi** [comment]
Out of scope `webpack`, sorry, feel free to start implement plugin
