### ISSUE TITLE
Expose the documentation for older versions

### ISSUE THREAD

**Issue by Pomax** [webpack/webpack#7736]
With four versions of webpack alive and kicking on tens of thousands -if not more- production instances, it would be incredibly valuable to have a way to quick get to the documentation for whatever modern or ancient version of webpack developers are faced with. Currently the webpack docs seem to only cover the most recent version, but the olds docs hopefully still exist somewhere... if so, can the documentation site be updated so that there's a version infix like `https://webpack.js.org/4.10/`, `https://webpack.js.org/1.8`, `https://webpack.js.org/stable`, etc. much like how readthedocs.io allows concurrent version documentation to be online?

**Comment by montogeek** [comment]
@webpack-bot move to webpack/webpack.js.org
