### ISSUE TITLE
Webpack can only compile a simple setup with Fontawesome SVG icons in development mode

### ISSUE THREAD

**Issue by madflow** [webpack/webpack#7742]
# Bug report

**What is the current behavior?**

Webpack can only compile a simple setup with Fontawesome SVG icons in ```development``` mode.

In ```production``` mode the compilation never finishes, there is no log output, the node process spikes to 100% cpu usage.

I have not created a ```webpack.config.js``` in order to tests the zero-conf approach from Webpack 4.

**If the current behavior is a bug, please provide the steps to reproduce.**

```git clone git@bitbucket.org:freiss/webpack-fontawesome.git```

```BASH
yarn
yarn run dev # finishes
yarn run prod #no avail
```

**What is the expected behavior?**

I should compile or throw errors.

**Other relevant information:**
webpack version:  4.16.1
Node.js version: 8.11.3
Operating System: Arch Linux
Additional tools: -

**Comment by evilebottnawi** [comment]
@madflow please create minimum reproducible test repo

**Comment by madflow** [comment]
I have managed to complete the ```yarn prod``` script. It took ``` 5:43,29 total```. (5 minutes) I was too impatient I guess. If this is a time period is acceptable for such a task - then this issue can be closed.

**Comment by evilebottnawi** [comment]
@madflow looks you use image compression, it is increase build time

**Comment by madflow** [comment]
Mmmh. I have not configured anything. Also there are no images to compress as far as I can see. The SVG definitions are exported from .js files.

**Comment by sokra** [comment]
Seems like you hit a edge-case in uglify-es.

The problem seem to be the `collapse_vars` optimization. This loop

https://github.com/mishoo/UglifyJS2/blob/569757d14dbbe04f66af65d7bf0600b3a75efd96/lib/compress.js#L1161-L1218

tries to find places where variable definitions can be collapsed to.

and the file `@fortawesome\free-solid-svg-icons\lib\index.es.js` contains a many definitions (740).

There is nothing I can do about that, but you can file the issue in the uglify-es repo and see if somebody can reduce the complexity of this piece of code.

btw. you can disable the optimization this way:

``` js
const UglifyJsPlugin = require("uglifyjs-webpack-plugin");

module.exports = {
    optimization: {
        minimizer: [
            new UglifyJsPlugin({
                uglifyOptions: {
                    compress: {
                        collapse_vars: false
                    }
                }
            })
        ]
    }
}
```

cc @kzc

**Comment by kzc** [comment]
Why is `webpack` still defaulting to the use of the unmaintained `uglify-es` package for minification?

This issue was already [reported](https://github.com/fabiosantoscode/terser/issues/50) and [fixed](https://github.com/fabiosantoscode/terser/pull/51) in [`terser`](https://github.com/fabiosantoscode/terser). 

See also: https://github.com/fabiosantoscode/terser#replacing-uglify-es-with-terser-in-a-project-using-yarn

**Comment by sokra** [comment]
> i think we can update plugin in webpack@4, because it is fork of uglify-es and contains only fixes

@kzc Could you confirm that uglify-es to terser is not a breaking change upgrade?

**Comment by kzc** [comment]
> Could you confirm that uglify-es to terser is not a breaking change upgrade?

Terser is a superset of and drop in replacement for `uglify-es`. Like any open source project by unpaid volunteers there is no guarantee. As was the case with `uglify-es`, every point release can potentially introduce errors. Although there's an extensive test suite with close to 2000 tests, you'd be well advised to test it with your project as you would with any library. Feel free to check the Terser open issues and commit log.

**Comment by kzc** [comment]
Speed/size comparison to other ES minifiers: 

* https://github.com/babel/minify#benchmarks

Other JS bundlers that are using Terser:

* https://www.npmjs.com/browse/depended/terser

**Comment by madflow** [comment]
@sokra @evilebottnawi  I see that there is a Terser Webpack Plugin now (https://github.com/webpack-contrib/terser-webpack-plugin) - which is great news! However - maybe you could shed some light on where the default optimization.miminizer story is going in Webpack? Is Terser or any other other stable miminizer going to replace UglifyJs as the default in the near future? I was "bought" by the zero conf approach in Webpack 4 - but was stopped pretty abruptly by the issue above.
