### ISSUE TITLE
Prefetched chunks ignore __webpack_public_path__ value

### ISSUE THREAD

**Issue by no23reason** [webpack/webpack#7744]
# Bug report

**What is the current behavior?**

When marking a chunk with `/* webpackPrefetch: true */` the value of `__webpack_public_path__ ` is ignored and the value specified in `webpack.config.js` or the default is used instead. This is not the case for "normal" imports as well as `/* webpackPreload: true */` imports, only prefetched imports are affected.

**If the current behavior is a bug, please provide the steps to reproduce.**

I made the existing test case for prefetch/preload stricter in my fork [here](https://github.com/webpack/webpack/compare/master...no23reason:features/prefetch-public-path). All the changed assertions pass, only the one on [line 27](https://github.com/webpack/webpack/compare/master...no23reason:features/prefetch-public-path#diff-5c81e3d588a59ab32cb1db13062686e1R27) fails (it is the one for prefetched import).

Repro steps:
```
git clone https://github.com/no23reason/webpack.git
cd webpack
git checkout features/prefetch-public-path
yarn
yarn jest ConfigTestCases
```

**What is the expected behavior?**

I believe the prefetched chunks should respect the `__webpack_public_path__ ` value, just like preloaded ones do.

**Other relevant information:**
webpack version:  4.16.1
Node.js version: 8.11.3
Operating System: macOS High Sierra 10.13.6
Additional tools: N/A

**Comment by sokra** [comment]
This is probably the case because prefetching runs before your code is executed and can change the variable.

**Comment by no23reason** [comment]
@sokra How is that possible? The test case explicitly sets the `__webpack_public_path__` value (line 16) before importing the prefetched chunk (line 29) ?
I also don't really understand why the behaviours of prefetch and preload differ 😕

**Comment by Rebulus** [comment]
Unfortunately, I have the same issue with prefetch and `__webpack_public_path__`. Could you tell me, you've resolve its or not?

**Comment by Rebulus** [comment]
@no23reason thank you. I've decided to do the same - use `preload` instead of `prefetch`.

**Comment by terrymun** [comment]
Can confirm that this issue can be reliably reproduced in webpack 4.20.2 😢

**Comment by ahmed-sigmalux** [comment]
This bug makes prefetching useless for anyone who defines __webpack_public_path__ inline.

**Comment by darkowic** [comment]
Confirm - the same issue here.

**Comment by darkowic** [comment]
![Screenshot_2019-05-15_13-49-38](https://user-images.githubusercontent.com/11510581/57773472-5fb30900-7718-11e9-921a-93f53fb9eea6.png)

I installed today the master version and looks like not all chunks are correctly prefixed with the `__webpack_public_path__`
```js
// prefetch possible future routes
import('containers/CategoryView'/* webpackChunkName: "CategoryView", webpackPrefetch: true */);
```
ideas?
@sokra

**Comment by darkowic** [comment]
What I found also is that this happens only on app initialization. When I go to the page, which is adding the prefetch chunk, from another page (client side routing) it has a correct public path.

**Comment by evilebottnawi** [comment]
@darkowic can you open new issue with reproducible test repo, thanks

**Comment by ganapativs** [comment]
Webpack bootstrap code uses `output.publicPath` for initial requests till it finds the `__webpack_public_path__` in source. 

AFAIK, Resource prefetching code(using `/* webpackPrefetch: true */`) is executed before the actual source code(containing `__webpack_public_path__`) is executed.

Configuring dynamic `output.publicPath` is the solution to the problem, but, not sure how to achieve this though!

**Comment by smddzcy** [comment]
Same issue here, prefetched resources don't use `__webpack_public_path__`.

An easy solution is just changing `output.publicPath` to accept a function.
