### ISSUE TITLE
Heap out of memory

### ISSUE THREAD

**Issue by BartJanvanAssen** [webpack/webpack#7746]
Hi all, 

# Bug report
We as a team encounter a lot of heap errors on our development (approx 1 an hour, sometimes even faster). Can we have a look at this /work this out? I know @sokra is already fixing some memory leaks, however we would like to get ours fixed as well.

**What is the current behavior?**

ℹ ｢wdm｣: Compiling...
 92% after chunk asset optimization SourceMapDevToolPlugin
<--- Last few GCs --->

[2697:0x102801e00]  1924201 ms: Mark-sweep 1374.6 (1457.5) -> 1374.5 (1458.0) MB, 620.1 / 0.0 ms  allocation failure GC in old space requested
[2697:0x102801e00]  1924928 ms: Mark-sweep 1374.5 (1458.0) -> 1374.4 (1427.0) MB, 726.4 / 0.0 ms  last resort GC in old space requested
[2697:0x102801e00]  1925655 ms: Mark-sweep 1374.4 (1427.0) -> 1374.4 (1427.0) MB, 727.3 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1b8f8f7a5879 <JSObject>
    1: /* anonymous */ [/Users/BartJanvanAssen/Code/PROJECT/frontend/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:~342] [pc=0x2840bdf8bd5](this=0x1b8faab8c209 <JSGlobal Object>,chunk=0x1b8fc45e2921 <String[26]\:         var _this = this;\n>,original=0x1b8fb4588a71 <Object map = 0x1b8f2f840739>)
    2: SourceNode_walk [/Users/BartJanvanAssen/Code/PROJECT...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewUninitializedFixedArray(int) [/usr/local/bin/node]
 5: v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::GrowCapacity(v8::internal::Handle<v8::internal::JSObject>, unsigned int) [/usr/local/bin/node]
 6: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x2840a1042fd

**If the current behavior is a bug, please provide the steps to reproduce.**
I m working on this... 

**What is the expected behavior?**
to just run with HMR and don't break

**Other relevant information:**
webpack version:  cli 2.1.3 webpack-dev-server@3.1.4: webpack@4.16.0:
Node.js version: v8.11.2
Operating System: MacOS

**Comment by ooflorent** [comment]
Could you create a reproducible example? Best put it in a GitHub repository.

**Comment by evilebottnawi** [comment]
Doesn't looks like memory leak :confused:  Do you have big project with enabled source map?

**Comment by BartJanvanAssen** [comment]
@evilebottnawi ye, I have a pretty big config + project, it's really though to get that in an reproduce repo, i'm working on it. @montogeek i updated the template. Currently i'm making heapdump every 30 secs to get the right dump ready. using tool: https://github.com/bnoordhuis/node-heapdump

**Comment by evilebottnawi** [comment]
@BartJanvanAssen try to disable source map on production build

**Comment by BartJanvanAssen** [comment]
@evilebottnawi We're having issues on our dev build, when i'm working and the HMR is on, after some time the thing will break. So i dont think this will be caused by the prod build, because it should affect, right?

**Comment by evilebottnawi** [comment]
@BartJanvanAssen can you try just disable source map and look on head files

**Comment by BartJanvanAssen** [comment]
i was able to debug the webpack dev server however memory heap dumps takes ages to load in the dev inspector, and simply cannot check into the issues, i'll have some tryouts on the @evilebottnawi setting's suggestion devtool to 'none'

**Comment by BartJanvanAssen** [comment]
We disabled the FaviconsWebpackPlugin and it resolved all of our issues! 👍 Thanx all for the input.

**Comment by yairEO** [comment]
I also facing this problem and while disabling the *source maps* helps, I cannot work without them on `dev` for obvious reasons.

**Comment by evilebottnawi** [comment]
increase you node memory

**Comment by fabriciofrontarolli** [comment]
I'm having issues with memory leak after i migrated to from webpack 3 to 4. both in DEV and while building in PROD it breaks lots of time, so I have to keep retrying untill it passes. PS. I'm already using --max-old-space-size
