### ISSUE TITLE
Webpack compiler `name` is undefined which is used in webpack-hot-client log messages

### ISSUE THREAD

**Issue by joshunger** [webpack/webpack#7754]
# Bug report

**What is the current behavior?**

Webpack compiler `name` is undefined which is used in webpack-hot-client log messages

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Install the following -
```
    "webpack": "^4.16.0",
    "webpack-command": "^0.4.1",
    "webpack-serve": "^2.0.2"
```

2. Execute `webpack-serve`

3. Change js file.

4. View `webpack-hot-client` output -

```
｢hot｣ App updated. Recompiling src/grid/grid.js
｢hot｣ webpack: Compiling (<unnamed compiler>)
```

See https://github.com/webpack-contrib/webpack-hot-client/blob/master/lib/index.js#L25
See https://github.com/webpack/webpack/blame/master/lib/Compiler.js#L124

**What is the expected behavior?**
Should `Compiler.js` have a name?

**Other relevant information:**
webpack version:  4.16.1
Node.js version: 10.0.0
Operating System:  Darwin 17.7.0

**Comment by sokra** [comment]
You can set a name in the config.

**Comment by joshunger** [comment]
@sokra got it. Should I close out this issue?

**Comment by mattcarlotta** [comment]
@joshunger Can you share what you did to fix this? Thanks.

**Comment by joshunger** [comment]
@mattcarlotta I can't reproduce it at the moment.
