### ISSUE TITLE
Optimize Webpack bundling speed

### ISSUE THREAD

**Issue by hmuhdkamran** [webpack/webpack#7756]
I am developing an application, at first it was pretty good, but as the application grows the build speed reduce considerably, currently it generates about 180 app chunks which take about 12 to 15 min, which is quite long time, it will appreciated if some one help me to optimize my web pack.
`webpack-base.js

const path = require('path');
const webpack = require('webpack');
const merge = require('webpack-merge');
const autoprefixer = require('autoprefixer');
const webpackHtml = require('html-webpack-plugin');

module.exports = (outputPath, srcPath, publicPath) => {

    const plugins = [
    ];

    const config = {
        devtool: '#eval-source-map',
        entry: {},
        module: {
            rules: [{
                    test: /\.ts$/,
                    loader: 'lodash-ts-imports-loader',
                    exclude: /node_modules/,
                    enforce: "pre"
                },
                {
                    test: /\.ejs$/,
                    use: {
                        loader: 'ejs-loader'
                    }
                },
                {
                    test: /\.html$/,
                    use: {
                        loader: 'vue-html-loader'
                    }
                },
                {
                    test: /\.css$/,
                    use: ['css-loader']
                },
                {
                    test: /\.(png|jpg|jpeg|gif)$/,
                    exclude: /node_modules/,
                    use: {
                        loader: 'url-loader',
                        options: {
                            prefix: 'img',
                            limit: 10000
                        }
                    }
                },
                {
                    test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
                    use: {
                        loader: 'url-loader',
                        options: {
                            limit: 10000,
                            mimetype: 'image/svg+xml'
                        }
                    }
                },
                {
                    test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
                    use: {
                        loader: "file-loader",
                        options: {
                            name: '[name].[ext]',
                            publicPath: '/assets/fonts'
                        }
                    }
                },
                {
                    test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
                    use: {
                        loader: 'url-loader',
                        options: {
                            prefix: 'font',
                            limit: 10000,
                            mimetype: 'application/octet-stream'
                        }
                    }
                },
                {
                    test: /\.(woff|woff2)$/,
                    use: {
                        loader: 'url-loader',
                        options: {
                            prefix: 'font',
                            limit: 50000
                        }
                    }
                }
            ]
        },
        output: {
            path: outputPath,
            publicPath: publicPath,
            filename: '[name].js'
        },
        plugins: plugins,
        resolve: {
            alias: {
                'src': path.resolve(srcPath, './src'),
                'assets': path.resolve(srcPath, './assets'),
                'components': path.resolve(srcPath, './components'),
                'state': path.resolve(srcPath, './state'),
                'vue$': path.resolve(__dirname, './node_modules/vue/dist/vue.esm.js')
            },
            extensions: ['.js', '.ts', '.html'],
            enforceExtension: false,
            modules: [path.resolve(__dirname, './node_modules')],
            symlinks: false,
            cacheWithContext: false
        },
        target: 'web'
    };

    return config;
}`

and another file 
`webpack.config.js

const path = require('path');
const webpack = require('webpack');
const merge = require('webpack-merge');
const autoprefixer = require('autoprefixer');
const webpackBase = require('./webpack-base');
const webpackHtml = require('html-webpack-plugin');
const webpackExtractTextPlugin = require('extract-text-webpack-plugin');

const outputPath = path.join(__dirname, '../server/wwwroot');
const srcPath = path.resolve(__dirname, './app');

module.exports = () => {

    let configs = [
        createMount(),
        createAreas()
    ];

    configs.forEach(o => extendConfig(o));

    return configs;
}

// emits a small webpack file for bootstrapping the application (displays a loading animation until required resources are loaded)
function createMount() {

    // set publicPath to '/mount/' so that .net core webpack middleware can proxy incoming requests to node.js middleware
    const config = webpackBase(outputPath, srcPath, '/mount/');

    // remove source maps
    delete config.devtool;

    // emit css to an external file
    const extractTextRule = {
        exclude: /node_modules/,
        test: /mount\.scss$/,
        use: webpackExtractTextPlugin.extract({
            fallback: 'style-loader',
            use: ['css-loader', 'sass-loader']
        })
    };

    config.module.rules.splice(1, 0, extractTextRule);

    // clear plugins
    config.plugins.length = 0;

    config.plugins.push(
        new webpackExtractTextPlugin('mount.css')
    );

    // add entry points to be built
    config.entry = {
        mount: [
            path.resolve(srcPath, './mount/mount.ts')
        ]
    };

    return config;
}

// emits the root and admin area applications
function createAreas() {
    // set publicPath to '/dist/' so that .net core webpack middleware can proxy incoming requests to node.js middleware
    const config = webpackBase(outputPath, srcPath, '/dist/');

    // emit all css to an external file
    const extractTextRule = {
        exclude: /node_modules/,
        test: /\.scss$/,
        use: webpackExtractTextPlugin.extract({
            fallback: 'style-loader',
            use: ['css-loader', 'sass-loader']
        })
    };

    config.module.rules.splice(0, 0, extractTextRule);

    config.plugins.push(
        new webpackExtractTextPlugin('[name].css')
    );

    config.plugins.push(new webpackHtml({
        chunksSortMode: 'dependency',
        excludeChunks: ['admin'],
        favicon: path.resolve(srcPath, './root/favicon.ico'),
        filename: 'index.html',
        inject: false,
        template: path.resolve(srcPath, './root/root.ejs')
    }));

    config.plugins.push(new webpackHtml({
        chunksSortMode: 'dependency',
        excludeChunks: ['app'],
        favicon: path.resolve(srcPath, './admin/favicon.ico'),
        filename: 'admin.html',
        inject: false,
        template: path.resolve(srcPath, './admin/admin.ejs')
    }));

    config.plugins.push(new webpack.optimize.CommonsChunkPlugin({
        name: 'vendor'
    }));

    config.plugins.push(new webpack.optimize.CommonsChunkPlugin({
        name: 'common',
        minChunks: 2
    }));

    // add entry points to be built
    config.entry = {
        vendor: [
            'vue', 'vue-router', 'vuex', 'vuelidate', 'vue-i18n', 'bootstrap-vue'
        ],
        admin: [
            path.resolve(srcPath, './admin/admin.ts')
        ],
        app: [
            path.resolve(srcPath, './root/root.ts')
        ]
    };

    return config;
}

function extendConfig(config) {

    const providePlugin =  new webpack.ProvidePlugin({
        Popper: ['popper.js', 'default']
    })

    const definePlugin = new webpack.DefinePlugin({
        'process.env.NODE_ENV': '"development"'
    });

    config.plugins.splice(0, 0, providePlugin);
    config.plugins.splice(0, 0, definePlugin);

    const tsLoader = {
        test: /\.ts$/,
        include: /app/,
        use: ['babel-loader', 'vue-hot-typescript-loader', 'ts-loader']
    };

    config.module.rules.splice(1, 0, tsLoader);
}`

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
