### ISSUE TITLE
wasm fails to decode when using webpack -p

### ISSUE THREAD

**Issue by Alexendoo** [webpack/webpack#7760]
# Bug report

**What is the current behavior?**

When bundling with `-p` webpack warns that `LEB128 encoding changed, this might lead to bugs` on the console, when attempting to load the file an error is thrown:  `CompileError: AsyncCompile: Wasm decoding failed: table index 101 out of bounds (1 entry) @+346`

**If the current behavior is a bug, please provide the steps to reproduce.**

Here is a repository to reproduce the above: https://github.com/Alexendoo/bugs/tree/master/01-webpack-wasm-bug, it has a few npm scripts

- `build` and `bindgen` to output the wasm file using cargo and [wasm-bindgen](https://github.com/rustwasm/wasm-bindgen)
- `webpack:p` and `webpack:d` to run webpack -p and -d respectively
- `serve` runs a webserver to browse the result

The first two scripts require a rust environment to be set up, but the repository has the results of running all the build steps committed into it so they don't necessarily need to be ran again, you can jump straight to `serve` to see the result.

**What is the expected behavior?**

webpack -p should produce usable wasm modules, like webpack -d does in this case

**Other relevant information:**
webpack version:  4.16.1
Node.js version: v10.7.0
Operating System: Windows 10
Additional tools: Cargo, wasm-bindgen

**Comment by sokra** [comment]
Cc @xtuc

**Comment by xtuc** [comment]
https://github.com/webpack/webpack/pull/7732 seems to have fixed it.

**Comment by TimHambourger** [comment]
Yes, this sounds a lot like [webassemblyjs #407](https://github.com/xtuc/webassemblyjs/issues/407#issuecomment-403191947), which is consistent w/ #7732 fixing it.

**Comment by xtuc** [comment]
Also I would like to re-enable the `optimization.mangleWasmImports` but i'm not able to write a failing test. I'll try on real world example, before submitting a PR.

**Comment by blandinw** [comment]
Had the exact same issue and can confirm that setting @TimHambourger's `usedExports: false` fixed it for me.

**Comment by fitzgen** [comment]
We have a battle tested LEB128 crate in the rust community, that we could compile to wasm if that would be useful ;)

https://github.com/gimli-rs/leb128

**Comment by sokra** [comment]
webpack v.4.18.0 should fix it
