### ISSUE TITLE
DeprecationWarning cannot be suppressed with stats.warnings or warningsFilter

### ISSUE THREAD

**Issue by ZhangYiJiang** [webpack/webpack#7763]
# Bug report

**What is the current behavior?**

DeprecationWarning emitted when plugins use deprecated features cannot be suppressed using `stats.warnings` or `stats.warningsFilter` 

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const FlowStatusWebpackPlugin = require('flow-status-webpack-plugin');

module.exports = {
  plugins: [
    // Or any plugins that still use the old API 
    new FlowStatusWebpackPlugin(),
  ],
  stats: {
    warnings: false,
    // Or 
    warningsFilter: warning => !warning.includes('Tapable.plugin'),
  },
};
```

Running this causes the warning to be printed 

```
(node:25184) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
``` 

**What is the expected behavior?**

The error should not be emitted 

**Other relevant information:**
webpack version:  4.16.1
Node.js version: v8.9.4
Operating System: Ubuntu 18.04 
Additional tools: NA

**Comment by ooflorent** [comment]
The error **should** be emitted. It is raised by node, not by webpack. `process.emitWarning` (called by `util.deprecate`) logs directly into the console.

**Comment by ooflorent** [comment]
If you no longer want to see the warning:

- use [`--no-deprecation`](https://nodejs.org/docs/latest/api/cli.html#cli_no_deprecation) or [`--no-warnings](https://nodejs.org/docs/latest/api/cli.html#cli_no_warnings)
- or try to fix the plugin (unfortunately its development seems to be stale)
