### ISSUE TITLE
Using Jest with NormalModuleReplacementPlugin 

### ISSUE THREAD

**Issue by ParadeTo** [webpack/webpack#7768]
# Bug report
We used NormalModuleReplacementPlugin in out project:

```
    new webpack.NormalModuleReplacementPlugin(
      /(.*)__APP_COUNTRY__(.*)/,
      resource => {
        resource.request = resource.request.replace(/__APP_COUNTRY__/, process.env.COUNTRY)
      }
    )
```

When we run test `COUNTRY=id node scripts/test.js --env=jsdom --modulePaths=src` in our project, it reports:

```
cannot find module './__APP_COUNTRY__' from 'index.js'
```

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version: 3.8.1
Node.js version: 9.8.0
Operating System: macOS High Sierra 10.13.6
Additional tools:

**Comment by montogeek** [comment]
Jest doesn't know about your webpack config. You may need to use `moduleNameMapper` Jest option.
