### ISSUE TITLE
Adding a loader dynamically through CLI

### ISSUE THREAD

**Issue by nvrsprasad** [webpack/webpack#7773]
I am building a project and all my configuration is available under webpack.config.js file. But due to some requirement, we wanted t pass eslint loader dynamically.  

Previous configuration in webpack.logcal.config.js:

```
{	
       test: /\.js$/,include: [/src/], exclude: /node_modules/,  loader: 'eslint-loader', 
	                options: { 
	                			configFile: './.eslintrc',
	      						useEslintrc: true,
	      						emitWarning: true,
	      						emitError: false,  /*https://github.com/webpack-contrib/eslint-loader*/  //
	      						formatter: function(results){   
	      							var formatters =  {
	      									checkstyle: require('eslint/lib/formatters/checkstyle'),
	      									junit: require('eslint/lib/formatters/junit'),
	      									html: require('eslint/lib/formatters/html'),
	      									jslint : require('eslint/lib/formatters/jslint-xml'),
	      									json : require('eslint/lib/formatters/json')
	      									};
	      							
	      							// parse the lint result in checkstyle format and write out a file
	      							var formatedRes = formatters.html(results);
	      							
	      							//fs.writeFile( path.resolve(__dirname + '/dist') + '/resultToday.json', formatedRes,(error) => { throw error; });
	      							fs.writeFile('../AXEresultToday_junit.html', formatedRes);
	      						}
	      					}				
	      		}//end eslint
```
As I wanted to pass the loader info dynamically, I have removd above code and wanted to use it through CLI:

bat "webpack -d --module-bind js=eslint-loader  --config webpack.local.config.js --colors"

> bat "webpack -d --module-bind js=eslint-loader  --config webpack.local.config.js --colors"

But please let me know,how ot pass
**bat "webpack -d --module-bind js=eslint-loader  --config webpack.local.config.js --colors"**

Bur, would like to know, how to pass "options' informration

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
