### ISSUE TITLE
Is it `side-effects` or `sideEffects` or are both supported?

### ISSUE THREAD

**Issue by jedwards1211** [webpack/webpack#7775]
I have both in various examples/documentation and I assume both are supported but I wanted to make 100% sure because confirming that tree shaking was performed isn't quick and easy.  If both are supported we should update the docs to reflect that, if it's not already mentioned somewhere.

**Comment by montogeek** [comment]
Which documentation? It is `sideEffects`.

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. Please either update the issue with the template and reopen, or open a new issue.

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.

**Comment by jedwards1211** [comment]
sorry for the confusion, I must have stumbled upon some outdated examples, because when I was trying to find them I saw this commit: https://github.com/webpack/webpack/commit/35d7f51b8812517728c6815cae735d685d67c17f
