### ISSUE TITLE
Module not found: Error: Can't resolve ... on 4.16.2

### ISSUE THREAD

**Issue by safareli** [webpack/webpack#7777]
Webpack [v4.16.2](https://github.com/webpack/webpack/releases/tag/v4.16.2) broke our build, It looks the root cause is this change #7750 `handle module.require like require`.

For example after that change this condition will take first path: https://github.com/zudov/purescript-websocket-simple/blob/v2.0.0/src/WebSocket.js#L13-L19 and result in node lib being included in bundle and as some of the node modules can't be resolved they fail.

Also before this for example https://github.com/uber/luma.gl/blob/v6.0.0/src/utils/is-browser.js#L12
was true but now it's false and results in some node specific modules being required. it's not quite related to #7750 but started happening from v4.16.2.

for now we fixed version to 4.16.1 and it fixed our issue.

on CI we use node v8.9.1.

**Comment by sokra** [comment]
``` js
    if (typeof module !== "undefined" && module.require) {
      // We are on node.js
      platformSpecific.WebSocket = module.require('ws');
    } else {
      // We are in the browser
      platformSpecific.WebSocket = WebSocket;
    }
```

There is the [`browser` package.json field](https://github.com/defunctzombie/package-browser-field-spec) for such stuff. No need to write such hacks.

``` js
platformSpecific.WebSocket = require('ws');
```

``` js
// package.json
"browser": {
  "ws": "./browser-ws.js"
}
```

``` js
// browser-ws.js
module.exports = WebSocket;
```

**Comment by evilebottnawi** [comment]
Answer https://github.com/webpack/webpack/issues/7777#issuecomment-407686373

**Comment by playground** [comment]
I run into similar issue when bundling typescript.

`WARNING in ./node_modules/websocket/lib/BufferUtil.js
Module not found: Error: Can't resolve '../build/Release/bufferutil' in '/Users/myapp/node_modules/websocket/lib'
 @ ./node_modules/websocket/lib/BufferUtil.js
 @ ./node_modules/websocket/lib/WebSocketFrame.js
 @ ./node_modules/websocket/lib/websocket.js
 @ ./node_modules/websocket/index.js
 @ ./node_modules/ibm-watson/lib/synthesize-stream.js
 @ ./node_modules/ibm-watson/text-to-speech/v1.js
 @ ./src/services/tts.ts
 @ ./src/services/index.ts
 @ ./src/watson-service.ts

WARNING in ./node_modules/websocket/lib/Validation.js
Module not found: Error: Can't resolve '../build/Release/validation' in '/Users/myapp/node_modules/websocket/lib'
 @ ./node_modules/websocket/lib/Validation.js
 @ ./node_modules/websocket/lib/WebSocketConnection.js
 @ ./node_modules/websocket/lib/websocket.js
 @ ./node_modules/websocket/index.js
 @ ./node_modules/ibm-watson/lib/synthesize-stream.js
 @ ./node_modules/ibm-watson/text-to-speech/v1.js
 @ ./src/services/tts.ts
 @ ./src/services/index.ts
 @ ./src/watson-service.ts

WARNING in ./node_modules/websocket/lib/BufferUtil.js
Module not found: Error: Can't resolve '../build/default/bufferutil' in '/Users/myapp/node_modules/websocket/lib'
 @ ./node_modules/websocket/lib/BufferUtil.js
 @ ./node_modules/websocket/lib/WebSocketFrame.js
 @ ./node_modules/websocket/lib/websocket.js
 @ ./node_modules/websocket/index.js
 @ ./node_modules/ibm-watson/lib/synthesize-stream.js
 @ ./node_modules/ibm-watson/text-to-speech/v1.js
 @ ./src/services/tts.ts
 @ ./src/services/index.ts
 @ ./src/watson-service.ts

WARNING in ./node_modules/websocket/lib/Validation.js
Module not found: Error: Can't resolve '../build/default/validation' in '/Users/myapp/node_modules/websocket/lib'
 @ ./node_modules/websocket/lib/Validation.js
 @ ./node_modules/websocket/lib/WebSocketConnection.js
 @ ./node_modules/websocket/lib/websocket.js
 @ ./node_modules/websocket/index.js
 @ ./node_modules/ibm-watson/lib/synthesize-stream.js
 @ ./node_modules/ibm-watson/text-to-speech/v1.js
 @ ./src/services/tts.ts
 @ ./src/services/index.ts
 @ ./src/watson-service.ts`
