### ISSUE TITLE
Documentation confusion: manually configure DefinePlugin with `mode` present or not?

### ISSUE THREAD

**Issue by SevenOutman** [webpack/webpack#7779]
As the [docs on Mode concept](https://webpack.js.org/concepts/mode/#usage) goes, when `mode` is set, webpack automatically configures some plugins like `DefinePlugin`.
![image](https://user-images.githubusercontent.com/8225666/43136750-3389b3d0-8f7c-11e8-9d48-2cb596f4142c.png)

But as the [production guide](https://webpack.js.org/guides/production/#specify-the-environment) goes, even with `mode` set to `'production'`, I should manually set `process.env.NODE_ENV` in `DefinePlugin`.
![image](https://user-images.githubusercontent.com/8225666/43136782-455e7e88-8f7c-11e8-9bfd-f0d62349f4ff.png)

This really confused me. Which one should I follow?

**Comment by montogeek** [comment]
@webpack-bot move to webpack/webpack.js.org
