### ISSUE TITLE
on AWS EC2 instance unable to access environment variables in webpack.config.js

### ISSUE THREAD

**Issue by rajiff** [webpack/webpack#7785]
# Bug report

**What is the current behavior?**
on AWS EC2 instance unable to access environment variables in webpack.config.js, though it works in my local machine

my file webpack.config.js is as bellow

```javascript
const MY_ENV_VARIABLE = (process.env.MY_ENV_VARIABLE || 'default_value');

module.exports = {
  entry..
  ...
  ...
  plugins: [
    new webpack.DefinePlugin({
      MY_ENV_VARIABLE: JSON.stringify(MY_ENV_VARIABLE),
    })
  ]
}
```
I am blank, unable to figure out what I am doing wrong, can't find much useful solution on stackoverflow or google either, sorry if this is spam

I also did this 

`webpack --env.MY_ENV_VARIABLE=my_value --env.production --progress`

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  `^4.3.0`
Node.js version: `v8.11.3`
Operating System: `Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-1062-aws x86_64)`
Additional tools:  `yarn` latest version

**Comment by sokra** [comment]
Not a webpack problem.

`--env` doesn't set `process.env` it passes these values as argument when exporting an function from `webpack.config.js`
