### ISSUE TITLE
Parser should provide hook to return the AST AND file path which the AST lives in

### ISSUE THREAD

**Issue by takmanlee** [webpack/webpack#7788]
## Feature request

**What is the expected behavior?**
A parser hook should return the file path where the AST under investigation lives.

**What is motivation or use case for adding/changing the behavior?**
It will benefit developers who need to traverse AST and know exactly where the AST lives.

**How should this be implemented in your opinion?**
Either the chunk instance provides tappable AST or the parser instance provides file location property.

**Are you willing to work on this yourself?**
yes with guidance.

**Comment by sokra** [comment]
See `parser.state.module`

**Comment by takmanlee** [comment]
Given the following code, `parser.state` is undefined:
```
        compiler.hooks.compilation.tap(
            'Plugin',
            (compilation, { normalModuleFactory }) => {
                const handler = (parser, parserOptions) => {
                    console.log(parser.state.module);
                    parser.hooks.evaluate
                        .for('ArrowFunctionExpression')
                        .tap('Plugin', expression => {
                          ...
                };
                normalModuleFactory.hooks.parser
                    .for('javascript/auto')
                    .tap('DibsAsyncCheckPlugin', handler);
            }
        );
```
Directly tapping into `normalModuleFactory` with `compiler.hooks.normalModuleFactory.tap('DibsAsyncCheckPlugin', compilation => {` also returns an undefined `parser.state`. Given that the src indicates `parser.state = OldState`, what will be the appropriate hook that I should use?

**Comment by takmanlee** [comment]
I also tried the code below but the callbacks seem to be asynchronous so the file paths don't correspond to the target file. 
```
    compiler.hooks.normalModuleFactory.tap('Plugin', factory => {

        factory.hooks.module.tap('Plugin', (data, param) => {

            console.log(data.request);

            data.parser.hooks.evaluate
                .for('ArrowFunctionExpression')
                .tap('Plugin', expression => {

                     console.log(data.request);

                });
        });
```
