### ISSUE TITLE
Question: why is context required?

### ISSUE THREAD

**Issue by fresheneesz** [webpack/webpack#779]
I'm noticing that files in the ancestory directories of 'context' aren't available for requiring. Is there a reason that's done?

**Comment by fresheneesz** [comment]
Is it to support dynamic requires?

**Comment by sokra** [comment]
You should be able to require every file. `context` is only used to resolve relative paths in entries.

**Comment by fresheneesz** [comment]
So I had a situation where I had something like the following structure:

* root/src/someFile.js
* root/test/testFile.js

And I had the context set to "root/test" and bundled "./testFile" which had a `require("../src/someFile.js")` and it couldn't locate it. Is this something that's expected?

**Comment by sokra** [comment]
Was context set to an absolute path?

**Comment by fresheneesz** [comment]
Yup

**Comment by sokra** [comment]
I don't know. This should work. You can prepare an example so I can take a look.

**Comment by fresheneesz** [comment]
I have the following files:

<root>/buildModules/webpackTest.js
<root>/buildModules/test/testDependency.js
<root>/buildModules/test/a/innerModule.js

in <root>/buildModules/webpackTest.js:

```
var webpack = require('webpack')

var webpackConfig = {
    context: __dirname+'/test/a',
    entry: "./innerModule"
}

webpack(webpackConfig, function(err, stats) {
    if(err) {
        console.log("Got Error: "+err)
    } else {
        var jsonStats = stats.toJson()

        if(jsonStats.warnings.length > 0)
            jsonStats.warnings.forEach(function(w) {
                console.log("Got Warning: "+w)
            })

        if(jsonStats.errors.length > 0)
            jsonStats.errors.forEach(function(e) {
                console.log("Got Error (2): "+e)
            })
        else {
            console.log("Success!")
        }
    }
})
```

in <root>/buildModules/test/a/innerModule.js:

```
var x = require("../testDependency")
module.exports = x
```

in <root>/buildModules/test/testDependency.js:

```
module.exports = {v:6}
```

And I get the following console output:

Got Error (2): ./test/a/innerModule.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../testDependency in <root>\buildModules/test/a
resolve file
  <root>\testDependency doesn't exist
  <root>\testDependency.webpack.js doesn't exist
  <root>\testDependency.web.js doesn't exist
  <root>\testDependency.js doesn't exist
  <root>\testDependency.json doesn't exist
resolve directory
  <root>\testDependency doesn't exist (directory default file)
  <root>\testDependency\package.json doesn't exist (directory description file)
[<root>\testDependency]
[<root>\testDependency.webpack.js]
[<root>\testDependency.web.js]
[<root>\testDependency.js]
[<root>\testDependency.json]
 @ ./test/a/innerModule.js 1:8-36

Note this is on windows 8.1, node 0.10.29, webpack 1.5.3

**Comment by sokra** [comment]
` context: __dirname+'/test/a',`

should be

` context: path.join(__dirname, 'test', 'a'),`

because windows uses `\` as path separator. `__dirname+'/test/a'` fails because it's not a valid absolute path.

**Comment by fresheneesz** [comment]
Oh i see. Those kinds of invalid paths work for pretty much everything else i've come across tho. Is there a reason webpack can't/shouldn't deal with them?

**Comment by sokra** [comment]
It propably can be implemented to deal with it... but currently it only likes correct paths.

**Comment by fresheneesz** [comment]
Looks like `path.normalize(weirdPath)` fixes the issue for me too. Might not be a bad idea to use that in webpack. Btw, I built a module that simplifies package building using webpack. I basically made it because I don't want to build a whole nother webpack config for every project I put out there. Wondering what you think of it: https://github.com/fresheneesz/buildModules
