### ISSUE TITLE
EnvironmentPlugin - error

### ISSUE THREAD

**Issue by krasevych** [webpack/webpack#7790]
Hi!
I have a problem with EnvironmentPlugin.
I try to use the plugin like this:
```
/...
new webpack.EnvironmentPlugin(['VT_ENV'])
/...
```

and I got the error:
```
TypeError: Cannot read property 'compilation' of undefined
 at DefinePlugin.apply (...\node_modules\webpack\lib\DefinePlugin.js:93:17
```

Please, help me to fix it.

webpack version:  4.16.2
Node.js version: 8.1.3
Operating System: Windows 8

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
