### ISSUE TITLE
[ignorePlugin] - Possibility to provide a function instead of regexp

### ISSUE THREAD

**Issue by AoDev** [webpack/webpack#7794]
## Feature request

**What is the expected behavior?**
I'd like to be able to provide a **check function** to the `ignorePlugin`.

**What is motivation or use case for adding/changing the behavior?**
Using regexp may be challenging in certain situations while providing a custom function makes ignorePlugin far more flexible.

**How should this be implemented in your opinion?**
The current behaviour, using regexp is actually a particular case of my proposal. The plugin itself has hardcoded check functions `checkContext` && `checkResource`.

We would allow the user to be able to provide these functions instead.

https://github.com/webpack/webpack/blob/master/lib/IgnorePlugin.js#L29
https://github.com/webpack/webpack/blob/master/lib/IgnorePlugin.js#L41

### Backward compatibility
The issue with the current signature is that it's tailored to regexp and I guess a breaking change would be needed to keep the code clean.

### Public API
Ideas of how the usage could look like to avoid too much hassle on end users:

```javascript
// old behaviour
new webpack.IgnorePlugin({
  resourceRegExp: /someregex/, 
  contextRegExp: /someregex/
})
```

```javascript
// with check functions
new webpack.IgnorePlugin({
  checkContext (context) {
    return true|false // do something with context
  },
  checkResource (resource) {
    return true|false // do something with resource
  }
})
```

**Are you willing to work on this yourself?**
yes

**Comment by sokra** [comment]
Send a PR

**Comment by yvele** [comment]
Looks like the PR has been merged https://github.com/webpack/webpack/pull/7827 🤔 

I'm actually using it with Webpack `4.19.1`

But the documentation still is missing this wonderful feature https://webpack.js.org/plugins/ignore-plugin/

**Comment by iliakan** [comment]
Also, why two functions, not one with two arguments? Could be so much more convenient!

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack/webpack.js.org/issues/2720

@iliakan don't write about new features in old issue, you request will be losted in ton of messages, feel free to create new issue, thanks
