### ISSUE TITLE
[ext] does not place the extension ion outputted files

### ISSUE THREAD

**Issue by janrevis** [webpack/webpack#7795]
# Bug report

**What is the current behavior?**

When I specify the [ext] in output.filename field in webpack.config.js, the outputted file shows a literal .[ext] as the extension.

**If the current behavior is a bug, please provide the steps to reproduce.**

create a webpack.config.js file with the following:

       entry: {
            'css/my-styles' : `${css}/my-styles.css`
        },
        output: {
            filename: '[name]-[hash].[ext]',
            path: path.resolve(modules, 'dist')
        },

run webpack
check the outputted files.  File name should be my-styles.css.  Actual filename is my-styles.[ext]

**What is the expected behavior?**
The correct extension is placed on the exported files.

**Other relevant information:**
webpack version:  4.16.2
Node.js version: 8.11.3, 7.10.1
Operating System: osx
Additional tools: N/A

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by montogeek** [comment]
This is not supported: https://webpack.js.org/configuration/output/#output-filename

**Comment by Legends** [comment]
Besides that I think having css files as entry points is not valid in webpack 4.

**Comment by janrevis** [comment]
@montogeek I found some examples of using that pattern, but I see now that it's not supports, at least in webpack 4.

I was eventually able to minify my css using mini-css-extract-plugin with optimize-css-assets-webpack-plugin

new MiniCssExtractPlugin({
       filename: [name]-[hash].min.css,
        chunkFilename: "[id].css"
}),

        optimization: {
            minimizer: [
                new OptimizeCSSAssetsPlugin({})
            ]
        },
