### ISSUE TITLE
webpack doesn't run on Windows

### ISSUE THREAD

**Issue by jhnns** [webpack/webpack#78]
Seems like the current implementation of [webpack/lib/MemoryOutputFileSystem.js](https://github.com/webpack/webpack/blob/master/lib/MemoryOutputFileSystem.js) doesn't run on windows machines. It utilizes unix-style separators. 

I've replaced all occurences with `path.sep` and uncommented the checks like this:

``` javascript
path = path.split(pathUtil.sep);
//if(path[0] != "") return callback(new Error("Invalid path " + path.join("/")));
```

and now it's running.

**Comment by chrisiDC** [comment]
ridiculous. tried to use it. not working with windows? lol. 
hopefully this framework will be not succesful.

**Comment by jhnns** [comment]
@chrisiDC webpack is working on Windows. Check your configuration and stop flaming.

**Comment by chrisiDC** [comment]
with 20 years of experience i must be a complete fool not to be able to set it up within 4 hours.. have to quit my job.
but sorry if i flame u. anyways, i dont think it works in windows out of the box...
cheers

**Comment by jhnns** [comment]
I'm sorry. I used to have a Windows machine and I had no problems. Even @sokra, the owner of the project, has a Windows machine, so I bet webpack runs on Windows. Without any error or hint, we can't help you.

**Comment by chrisiDC** [comment]
i will provide an error hint asap. currently i am in the office :)
thx for your feedback
