### ISSUE TITLE
Common Chunks Plugin doesn't add webpackBootstrap when there are no common chunks

### ISSUE THREAD

**Issue by trappar** [webpack/webpack#780]
As far as I can tell this is what the issue is. I'm just setting up Webpack right now so I'm working on converting over the first few pages of my application. So far there aren't any common chunks, but I'm enabling the common chunks plugin since I know it will become useful as soon as I add more pages.

So as of right now, with one entry point I have a couple modules and a single chunk, but nothing in the common chunk. As far as I can tell, this is resulting in [this statement](https://github.com/webpack/webpack/blob/76f1c2fa0e4a5c254d401afade203f36a0d261f4/lib/JsonpMainTemplatePlugin.js#L79) evaluating to false, so that segment of code doesn't run, except in this case that's a problem since I do have chunks which require that code to exist.

The result is that as soon as I enable the common chunks plugin, my pages fail to load with an error "ReferenceError: Can't find variable: webpackJsonp"

I suppose you could say that this is not a bug - that I shouldn't be enabling the common chunks plugin until my project is ready for it, but if that's the case that should be documented somewhere. In any case, as an end user this really feels like a bug.

**Comment by sokra** [comment]
Can you post your configuration?

**Comment by trappar** [comment]
It's a little tricky because my configuration is fairly ingrained with our grunt process, but here it is.

```
// this is what is available in the data variable later
static_resources: {
    main: {
        base: 'app/resources/js',
            path: 'main/**/*'
    },

    widgets: {
        base: 'app/resources/js',
            path: 'widget/**/*'
    }
}
```

```
// webpack config
var webpack = require('webpack');
var BowerWebpackPlugin = require('bower-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var path = require('path');

module.exports = function(grunt, data) {
    function buildEntry(info) {
        return grunt.file.expand({cwd: info.base}, info.path + '.js').reduce(function(obj, value){
            obj[value.slice(0, -3)] = './' + path.join(info.base, value);
            return obj;
        }, {})
    }

    return {
        options: {
            resolve: {
                root: path.join(process.cwd(), 'app/resources/js')
            },
            output: {
                path: path.join(process.cwd(), 'web/public'),
                publicPath: data.app_config.asset_base_url + '/public/',
                filename: "[name].js",
                chunkFilename: "chunk/[name].js"
            },
            module: {
                preLoaders: [
                    {test: /\.js$/, loader: "source-map-loader"}
                ],
                loaders: [
                    {test: /\.css$/, loader: ExtractTextPlugin.extract("style-loader", "css-loader")},
                    {test: /\.(png|woff|svg|ttf|eot)([\?]?.*)$/, loader: "file-loader?name=[path][name].[ext]"},
                    {test: /\.ejs$/, loader: "ejs"}
                ]
            },
            plugins: [
                new webpack.ProvidePlugin({
                    $: "jquery",
                    jQuery: "jquery",
                    "windows.jQuery": "jquery",
                    _: "underscore"
                }),
                new BowerWebpackPlugin(),
                new webpack.optimize.CommonsChunkPlugin("commons.js"),
                new ExtractTextPlugin('[name].css', {
                    allChunks: true
                })
            ],
            amd: {jQuery: true},
            progress: false,
            stats: {
                assets: false,
                cached: false,
                modules: true,
                reasons: false,
                timings: false,
                version: false
            },
            cache: {},
            storeStatsTo: 'webpackStats'
        },
        main: {
            entry: buildEntry(data.static_resources.main)
        },
        widgets: {
            entry: buildEntry(data.static_resources.widgets)
        }
    };
};
```

**Comment by trappar** [comment]
Adding a second entry point that has a module which is common with the first entry point (causing that to be available through the common chunk does result in the bootstrap stuff being added to the common chunk.

**Comment by trappar** [comment]
Ah, crap.. sorry nevermind. The "widget" common chunk was overwriting the "main" common chunk and since there weren't any chunks at all in the widget common chunk this behavior was correct.
