### ISSUE TITLE
emitAssets(compilation, callback) in file "webpack/lib/Compiler.js" cannot handle resources in another drive on Windows.

### ISSUE THREAD

**Issue by ShenHongFei** [webpack/webpack#7801]
# Bug report

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/15074472/43356633-eec37b04-92a6-11e8-96cc-100e1be66cff.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
Symlink local node_modules directory to global node_modules. ( D:/0/node_modules -> C:\Users\shf\AppData\Roaming\npm\node_modules )
Include third-party styles that contains fonts. ( e.g.  import 'element-ui/lib/theme-chalk/icon.css' )
Webpack stucks.

**What is the expected behavior?**
Fonts and other resources should be emitted and put in correct location relative to build directory. In my example, it should be in D:/0/build/...

**Other relevant information:**
webpack version:  4.16.3
Node.js version:  v10.7.0
Operating System: Windows
Additional tools: None

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.
