### ISSUE TITLE
How to completely ignore a require from webpack?

### ISSUE THREAD

**Issue by mistrykaran91** [webpack/webpack#7802]
IgnorePlugin is not working for my Angular app. I'm lazily loading modules, my root folder is src and in that app\modules\app-routing.module.ts which has the lazily loading code, so it is not ignoring the require statement. What should I be writing to ignore it

Currently have given this 
   new IgnorePlugin(/test\/test\.module/),

throws the context error and what context I should be giving.

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
