### ISSUE TITLE
DefinePlugin: Code Only excluded if true is first

### ISSUE THREAD

**Issue by hipstersmoothie** [webpack/webpack#7811]
# Bug report

**What is the current behavior?**

Code is only eliminated if `true` is first.

<img width="686" alt="screen shot 2018-07-29 at 11 39 11 pm" src="https://user-images.githubusercontent.com/1192452/43381193-bcf65316-9388-11e8-81a8-daf9fce4187e.png">

<img width="812" alt="screen shot 2018-07-29 at 11 40 56 pm" src="https://user-images.githubusercontent.com/1192452/43381243-e93044c8-9388-11e8-9479-71b0959d64fa.png">

**If the current behavior is a bug, please provide the steps to reproduce.**

use `webpack.DefinePlugin` to inject some variable that's in an if statement

**What is the expected behavior?**

It should eliminate the code if the expression resolve to true regardless of `true` placement.

**Other relevant information:**
webpack version:  4.16.1
Node.js version: 9.10.0
Operating System: mac 10.13.5 
Additional tools:

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by hipstersmoothie** [comment]
cant seem to reproduce now. closing!
