### ISSUE TITLE
Hot Module Replacement of a particular module only works once while the App component can be HMR-ed all the time

### ISSUE THREAD

**Issue by ghost** [webpack/webpack#7814]
# Bug report

**What is the current behavior?**
Hot Module Replacement works every other time but not all of the time. A more detailed explanation is [available here](https://stackoverflow.com/q/51594983/796036).

**If the current behavior is a bug, please provide the steps to reproduce.**
A complete MWE can be found here: https://gitlab.com/NearAutomata/webpack-hmr-issue. Clone and run the following commands:

    yarn
    yarn run build-main
    yarn run build-renderer-hot

And in a second terminal run

    yarn run start-hot

**What is the expected behavior?**
I expect the other module to be HMR-ed every time.

**Other relevant information:**
webpack version:  4.16.3
Node.js version: 10.7.0
Operating System: Windows 10 Build 1803
Additional tools: Electron 2.0.5 and Electron 3.0.0@beta, Redux 4.0.0

According to reduxjs/redux#3079, the `replaceReducer` works correctly, so it's most likely an issue with HMR in general or how I accept updates via `module.hot.accept`.

**Comment by NearAutomata** [comment]
For testing purposes I have added `module.hot.accept();` without arguments right after the first call to `accept` in [this file](https://github.com/NearAutomata/redux-hmr-issue/blob/master/Source/Index.tsx) to prevent a complete reload. Surprisingly enough I am getting the following error:

![](https://i.imgur.com/sRvUdkD.png)

This might actually be an indicator that [this particular line](https://github.com/NearAutomata/redux-hmr-issue/blob/703a8710da8d2d8bec055dabb8f5d42bbee90a29/Source/Store/App.Store.ts#L61) is never triggered on every second compilation.

**Comment by NearAutomata** [comment]
@sokra Literally all examples require a new version of the reducer. I am personally just using `import()` instead of `require("Reducers/App.Reducer").AppReducer`. Your suggestion does not replace anything and I assume the `AppReducer` is cached.

**Comment by NearAutomata** [comment]
Minor update, I have created a new and completely stripped down MWE which makes testing this issue even easier now. I have updated the initial post and the Stackoverflow post as well to reflect the changes.

**Comment by sokra** [comment]
Could you remove the `import("App")` from the accept handler. That's wrong.

When using ESM symbols are automatically reloaded. When using CJS you need to call `require`.

``` js
import Something from "somewhere";

set(Something);

if(module.hot) {
  module.hot.accept("somewhere", () => {
    // Something is now the new module
    set(Something);
  });
}
```

``` js
let Something = require("somewhere");

set(Something);

if(module.hot) {
  module.hot.accept("somewhere", () => {
    Something = require("somewhere");
    // Something is now the new module
    set(Something);
  });
}
```

Be careful when transpiling ESM (i. e. with babel or typescript). These tools should be configured to not transpile ESM!

**Comment by NearAutomata** [comment]
Once again the `import()` regarding hot reloading the `App` isn't erroneous, in fact it works properly. For testing purposes I even removed the HMR of the `App` component just figure out the way `module.hot.accept` behaves when it is only used once throughout the entire codebase. And it still doesn't work.

I tried replacing imports with requires as well - for example in my newest MWE I am calling

    const configureStore: Function = require("App.Store").default;

as well as

    const { AppReducer } = require("App.Reducer");

along the dependency path, but it doesn't help. It is clear to me that the `module.hot.accept` isn't called a second time after the initial replacement. Therefore not HMR listener is setup for `App.Reducer`.

Please refer to my newest MWE once again as I removed almost everything.

**Comment by ChibiBlasphem** [comment]
Hello,
I kinda have the same issue, the only way "to accept again" the changes on the same modules is to to re call `module.hot.accept`

Like this:
```javascript
const updateReducer = () => {
  const config = require('agora-config')
  store.replaceReducer(getReducer(config))

  module.hot.accept('agora-config', updateReducer)
}
module.hot.accept('agora-config', updateReducer)
```

**Comment by sokra** [comment]
@NearAutomata In your repo there are these issues:

* `tsconfig.json` `"module": "commonjs"` should be `"ESNext"` instead, otherwise you are not using ESM in webpack.
* `Source/Index.tsx` Don't use async code in accept. Don't use `import()` in accept. With above setting `App` will be the new App in the accept method.

``` ts
import App from "App";

ReactDOM.render(
    <Provider store={appStore}>
        <App />
    </Provider>,
    document.getElementById("app")
);

if (module.hot !== undefined) {
    module.hot.accept(
        "App",
        (): void => {
            try {
                ReactDOM.render(
                    <Provider store={appStore}>
                        <App />
                    </Provider>,
                    document.getElementById("app")
                );
            } catch (error) {
                ReactDOM.render(
                    <Provider store={appStore}>
                        <RedboxReact error={error} />
                    </Provider>,
                    document.getElementById("app")
                );
            }
        }
    );
}
```

**Comment by jchabotamica** [comment]
for hot reloading the reducers - i actually had to move the if(module.hot)... logic OUTSIDE of the configure-store function. so..

`configureStore = () => {
   const store = createStore(...);
   return store;
}
if (module.hot) {
  module.hot.accept(() => {
    configureStore().replaceReducer(rootReducer);
  });
}
`
When doing it your way, it seems that it only gets hit once because configureStore only gets called the first time maybe?  Putting it outside, allows it to get hit anytime a change propagates up...or something like that.

**Comment by vankop** [comment]
@alexander-akait is it still an issue?

**Comment by vankop** [comment]
If this still an issue, please provide a reproducible repo with webpack@5.

**Comment by shashank-brightness** [comment]
I am still getting this issue and not able to get the reason behind this. Webpack documentation is not properly explained with examples. Here console logs only for the first time and all other times are ignored. 

 ```
module.hot.accept('../output/css/custom.css', function(mod) {
     console.log('custom css accepted')
 });
```
