### ISSUE TITLE
Weird [resource-path] for files that are not part of context directory

### ISSUE THREAD

**Issue by dimsmol** [webpack/webpack#782]
For files that aren't located within context directory [resource-path] used in output.devtoolModuleFilenameTemplate is being substituted with weird value that contains absolute path to the package.

For instance, it happens for files located in `node_modules` directory.

Final url in source map `source` array may look like `webpack:////Users/myuser/myproject/~/react/lib/invariant.js`

It would be nice at least to chop off absolute path part and have it like `webpack:////~/react/lib/invariant.js` or something.

**Comment by dimsmol** [comment]
Not sure, but maybe it would be useful to allow function as a value of output.devtoolModuleFilenameTemplate and possibly for other templates as well.

Something like 
```js
output.devtoolModuleFilenameTemplate = function (parts) {
  return 'webpack://' + modifyAsYouWish(parts.resourcePath);
}
```

**Comment by bebraw** [comment]
Closing given #1224 was merged.
