### ISSUE TITLE
Example for moved NuGet cache

### ISSUE THREAD

**Issue by milbrandt** [webpack/webpack#7820]
## Feature request

Default behaviour should be to follow symbolic links on the drives.
Also a example with `symlinks: false` would be welcomed.

**What is the expected behavior?**
Default behaviourof webüpack to follow the symbolic links.

**What is motivation or use case for adding/changing the behavior?**
As on system drive C: there was only little remaining space I move the NuGet cache to a secondary drive. The original directory got a symbolic link. By default configuration webpack failed to follow the link.

Original [issue at Fable](https://github.com/fable-compiler/Fable/issues/1490) is linked.

**How should this be implemented in your opinion?**
If `symlinks` is not defined in the configuration, today webpack assumes `true`. This should be inverted: if not present, then `false`.

**Are you willing to work on this yourself?**
yes

**Comment by sokra** [comment]
`symlinks: true` follows symlinks. You want to propose to not follow symlinks by default.

**Comment by TheLarkInn** [comment]
This would be a pretty big breaking change no?

**Comment by milbrandt** [comment]
No, I don't think so. With the proposed change my colleagues and I are now already working for several weeks on a Fable project - see the link above. Neither me with relocated Nuget cache nor the co-workers with only one bigger drive have had any issues yet.Von meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [webpack/webpack] Example for moved NuGet cache (#7820)Von: Sean Larkin An: webpack/webpack Cc: Volker Milbrandt ,Author This would be a pretty big breaking change no?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/webpack/webpack","title":"webpack/webpack","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/webpack/webpack"}},"updates":{"snippets":[{"icon":"PERSON","message":"@TheLarkInn in #7820: This would be a pretty big breaking change no?\r\n"}],"action":{"name":"View Issue","url":"https://github.com/webpack/webpack/issues/7820#issuecomment-411440341"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/webpack/webpack/issues/7820#issuecomment-411440341",
"url": "https://github.com/webpack/webpack/issues/7820#issuecomment-411440341",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [webpack/webpack] Example for moved NuGet cache (#7820)",
"sections": [
{
"text": "",
"activityTitle": "**Sean Larkin**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@TheLarkInn",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"webpack/webpack\",\n\"issueId\": 7820,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"webpack/webpack\",\n\"issueId\": 7820\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/webpack/webpack/issues/7820#issuecomment-411440341"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 362512645\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by sokra** [comment]
```
ERROR: F:/.nuget/packages/fable.elmish/1.0.3/fable/cmd.fs doesn't belong to any of loaded projects [[F:/Repos/Company.EcoPage/source/Client/Client.fsproj, F:/Repos/Company.EcoPage/source/Client/Client.fsproj]]
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
   at Fable.CLI.StateUtil.loop@232-6.Invoke(Tuple\`2 _arg1)
```

This is not a webpack error. Seem like some plugin (?) has problems with these symlinks

**Comment by milbrandt** [comment]
As mentioned above, with `symlinks: false` the problem is fixed for me.

**Comment by evilebottnawi** [comment]
https://github.com/webpack/webpack/issues/7820#issuecomment-447430307
