### ISSUE TITLE
Bug: HotModuleReplacementPlugin incorrectly calls chunkAsset hook

### ISSUE THREAD

**Issue by EECOLOR** [webpack/webpack#7828]
# Bug report

`compilation.hooks.chunkAsset.call("HotModuleReplacementPlugin", currentChunk, filename)` should be `compilation.hooks.chunkAsset.call(currentChunk, filename)`

https://github.com/webpack/webpack/commit/6192e5b4131ca630ae7f71bd2eca23b99e82d391#r29912152

**What is the current behavior?**

[`lib/HotModuleReplacementPlugin.js#L288`](https://github.com/webpack/webpack/blob/master/lib/HotModuleReplacementPlugin.js#L288):
```js
compilation.hooks.chunkAsset.call(
    "HotModuleReplacementPlugin",
    currentChunk,
    filename
);
```

**What is the expected behavior?**

```js
compilation.hooks.chunkAsset.call(
    currentChunk,
    filename
);
```
as described by: 

[`lib/Compilation.js#L357`](https://github.com/webpack/webpack/blob/master/lib/Compilation.js#L357):

```js
chunkAsset: new SyncHook(["chunk", "filename"]),
```

**Comment by sokra** [comment]
yep that's true. Send a PR
