### ISSUE TITLE
 node_modules are not excluded

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [webpack/webpack#7834]
# Bug report

**What is the current behavior?**
node_modules is not excluded from the build.

**If the current behavior is a bug, please provide the steps to reproduce.**
Download:
https://github.com/Sebastian-Nielsen/zinuku

Install the (dev)dependencies by running:
`npm install --save`(-dev)`NAME OF DEPENDENCY`

Run the command:
`npm run start`

**What is the expected behavior?**
To exclude the node_modules

Exclude each file in the node_modules folder

**Other relevant information:**
webpack version:  4.16.2
Node.js version: 5.6.0
Operating System: windows 10

Please note that the issue was present before I tried correcting it by using the `webpack-node-externals` library.

Addtional information:
`webpack-cli` version = 3.1.0

 **package.json**

       {
      "name": "zinuku",
      "version": "1.0.0",
      "description": "",
      "main": "index.jsx",
      "scripts": {
        "build": "webpack-cli",
        "start": "webpack-dev-server"
      },
      "dependencies": {
        "react": "^16.4.1",
        "react-dom": "^16.4.1"
      },
      "devDependencies": {
        "babel-core": "^6.26.3",
        "babel-loader": "^7.1.5",
        "babel-preset-react": "^6.24.1",
        "html-webpack-plugin": "^3.2.0",
        "webpack": "^4.16.3",
        "webpack-cli": "^3.1.0",
        "webpack-dev-server": "^3.1.5",
        "webpack-node-externals": "^1.7.2"
      }
    }
**webpack.config.js**

    const webpack = require('webpack');
    const nodeExternals = require('webpack-node-externals');
    
    var HTMLWebpackPlugin = require('html-webpack-plugin');
    var HTMLWebpackPluginConfig = new HTMLWebpackPlugin({
        template: __dirname + '/app/index.html',
        filename: 'index.html',
        inject: 'body'
    });
    
    
    module.exports = {
        entry: __dirname + '/app/index.jsx',
        mode: 'development',
        target: 'node', // in order too ignore built-in modules like path, fs, etc.
        externals: [nodeExternals()], // in order to ignore all modules in node_modules folder
        module: {
            rules: [
                {
                    test: /\.js$/,
                    exclude: /node_modules/,
                    loader: 'babel-loader'
                },
                {
                    test: /\.jsx$/,
                    exclude: /node_modules/,
                    loader: 'babel-loader'
                }
            ]
        },
        output: {
            filename: 'transformed.js',
            path:  __dirname + '/build'
        },
        plugins: [HTMLWebpackPluginConfig]
    };

**Bash (displaying that node_modules got build too!)**

npm run start

    > zinuku@1.0.0 start C:\Users\sebas\pycharmProjects\zinuku
    > webpack-dev-server
    
    i ｢wds｣: Project is running at http://localhost:8081/
    i ｢wds｣: webpack output is served from /
    i ｢wdm｣: Hash: 94790fc256e631986c59
    Version: webpack 4.16.3
    Time: 873ms
    Built at: 2018-07-31 20:44:54
             Asset       Size  Chunks             Chunk Names
    transformed.js     27 KiB    main  [emitted]  main
        index.html  221 bytes          [emitted]
    Entrypoint main = transformed.js
    [./app/components/App.jsx] 386 bytes {main} [built]
    [./app/components/HeaderComponent/NavBar.jsx] 294 bytes {main} [built]
    [./app/index.jsx] 209 bytes {main} [built]
    [./node_modules/webpack-dev-server/client/index.js?http://localhost:8081] (webpack)-dev-server/client?http://localhost:8081 7.78 KiB {main} [built]
    [./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.58 KiB {main} [built]
    [./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {main} [built]
    [./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
    [loglevel] external "loglevel" 42 bytes {main} [built]
    [react] external "react" 42 bytes {main} [built]
    [react-dom] external "react-dom" 42 bytes {main} [built]
    [sockjs-client/dist/sockjs] external "sockjs-client/dist/sockjs" 42 bytes {main} [built]
    [strip-ansi] external "strip-ansi" 42 bytes {main} [built]
    [url] external "url" 42 bytes {main} [built]
    [webpack/hot/emitter] external "webpack/hot/emitter" 42 bytes {main} [built]
    [0] multi (webpack)-dev-server/client?http://localhost:8081 ./app/index.jsx 40 bytes {main} [built]
        + 3 hidden modules
    Child html-webpack-plugin for "index.html":
         1 asset
        Entrypoint undefined = index.html
        [./node_modules/html-webpack-plugin/lib/loader.js!./app/index.html] 372 bytes {0} [built]
        [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
        [./node_modules/webpack/buildin/module.js] 497 bytes {0} [built]
    i ｢wdm｣: Compiled successfully.

My file structure: https://gyazo.com/670cf8afbae2fb213d759d455221d7f3

**Comment by sokra** [comment]
Seem to work.

`[react] external "react" 42 bytes {main} [built]` => react is not included in the build

**Comment by TheLarkInn** [comment]
The plugin doesn't ignore transient dependencies I believe. (This may be the cause, however you would have to check with the repository owner)

**Comment by sokra** [comment]
> Bash (displaying that node_modules got build too!)

I can't see where it shows that node_modules are included in the bundle.

These lines:

```
[loglevel] external "loglevel" 42 bytes {main} [built]
[react] external "react" 42 bytes {main} [built]
[react-dom] external "react-dom" 42 bytes {main} [built]
[sockjs-client/dist/sockjs] external "sockjs-client/dist/sockjs" 42 bytes {main} [built]
[strip-ansi] external "strip-ansi" 42 bytes {main} [built]
[url] external "url" 42 bytes {main} [built]
[webpack/hot/emitter] external "webpack/hot/emitter" 42 bytes {main} [built]
```

show only references to **not included** node_modules.

**Comment by Sebastian-Nielsen** [comment]
[screenshot](https://gyazo.com/8e25b816a4ef2039d4ae3906d3dfe753)
Forgive me, but why does several of the paths start with ".node_modules" then?

**Comment by sokra** [comment]
The first one is webpack-dev-server and webpack HMR, that dev-only and not in the production bundle.

The second one are resources to build your index.html and not in the main compilation.
