### ISSUE TITLE
While bundling a file got error => Module not found: Error: Can't resolve

### ISSUE THREAD

**Issue by jvkiran** [webpack/webpack#7837]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  4.16.3
Node.js version: 7.10.1
Operating System: ubuntu 16.0.4
Additional tools:

Command : node_modules/.bin/webpack static/App.js static/app.bundle.js --display-error-details

Error: Hash: f79e00c910e602845f02
Version: webpack 4.16.3
Time: 674ms
Built at: 08/02/2018 1:01:25 PM
 1 asset
Entrypoint main = main.js
[0] multi ./static/App.js static/app.bundle.js 40 bytes {0} [built]
[1] ./static/App.js 9.45 KiB {0} [built]

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in multi ./static/App.js static/app.bundle.js
Module not found: Error: Can't resolve 'static/app.bundle.js' in '/home/gtcoder/Sites/pro-mern-stack'
resolve 'static/app.bundle.js' in '/home/gtcoder/Sites/pro-mern-stack'
  Parsed request is a module
  using description file: /home/gtcoder/Sites/pro-mern-stack/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/gtcoder/Sites/node_modules doesn't exist or is not a directory
      /home/gtcoder/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/gtcoder/Sites/pro-mern-stack/node_modules
        using description file: /home/gtcoder/Sites/pro-mern-stack/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /home/gtcoder/Sites/pro-mern-stack/package.json (relative path: ./node_modules/static/app.bundle.js)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/gtcoder/Sites/pro-mern-stack/node_modules/static/app.bundle.js doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /home/gtcoder/Sites/pro-mern-stack/node_modules/static/app.bundle.js.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/gtcoder/Sites/pro-mern-stack/node_modules/static/app.bundle.js.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/gtcoder/Sites/pro-mern-stack/node_modules/static/app.bundle.js.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/gtcoder/Sites/pro-mern-stack/node_modules/static/app.bundle.js.json doesn't exist
            as directory
              /home/gtcoder/Sites/pro-mern-stack/node_modules/static/app.bundle.js doesn't exist
[/home/gtcoder/Sites/node_modules]
[/home/gtcoder/node_modules]
[/home/node_modules]
[/node_modules]
[/home/gtcoder/Sites/pro-mern-stack/node_modules/static/app.bundle.js]
[/home/gtcoder/Sites/pro-mern-stack/node_modules/static/app.bundle.js.wasm]
[/home/gtcoder/Sites/pro-mern-stack/node_modules/static/app.bundle.js.mjs]
[/home/gtcoder/Sites/pro-mern-stack/node_modules/static/app.bundle.js.js]
[/home/gtcoder/Sites/pro-mern-stack/node_modules/static/app.bundle.js.json]
 @ multi ./static/App.js static/app.bundle.js main[1]

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
