### ISSUE TITLE
Sym or npm link with module loader confuse file lookup

### ISSUE THREAD

**Issue by totty90** [webpack/webpack#784]
With a sym or npm link node module the output is this (totty-project is the node module):

```
ERROR in ../totty-project/src/core/fixes/validate.js-shim.js
Module not found: Error: Cannot resolve module 'script' in C:\web\totty-project\src\core\fixes
 @ ../totty-project/src/core/fixes/validate.js-shim.js 1:17-46
```

This means that he can't find the file `"Cannot find module \"validate.jsUnFixed\` from file `totty-project/src/core/fixes/validate.js-shim.js`. 

File `totty-project/src/core/fixes/validate.js-shim.js`:

```
module.exports = require('validate.jsUnFixed');
```

Webpack config aliases:

```
            'validate.jsUnFixed' : absPath("node_modules/validate.js/validate.min"),
            'validate.js'        : absPath("node_modules/totty-project/src/core/fixes/validate.js-shim.js"),
```

Webpack config module loaders:

```
            {
                test   : /validate\.min\.js/,
                loader : 'script'
            },
```

I don't know why with a sym link he looks into the original path of the sym link c:\web\totty-project instead of the c:\web\main-project\node_modules\totty-project.

Is very interesting to note that if I remove the module loader it works as expected. I think the module loader might influence this behaviour.

I've also noticed that puts my `totty-project` in a different path in the source list in chrome. With sym link it shows below `../totty-project` while as normal folder shows below `./~/totty-project`. This only happens with this module. I have other sym linked modules and work fine. It should not even include into the web bundle those files, because are just webpack/build config/tools.
# It might be because of this too:

`webpack.config.js`:

```
module.exports = require('totty-project').webpackConfig({
    rootPath: __dirname
});
```

With a normal folder copy this works ok.

**Comment by jsg2021** [comment]
I'm experiencing this too.  I have a webapp with a shared library.
```
- SharedLibrary
- WebApp
  |--node_modules/
     |--(symlink)SharedLibrary
```

Both library and app use 6to5, when I compile the webapp, the dependencies that are shared between the library (6to5-runtime) and webapp should come from the WebApp's node_modules... webpack is looking in the resolved library path. (which it will not find since the shared library is actually a sibling)

I'm on WebPack v1.5.3

**Comment by mpolichette** [comment]
+1
Me and my team are experiencing this symlink issue also.  We often are looking to update code in a shared repository and we symlink so we can test the updated code before committing and deploying a new version of the shared library.

**Comment by sokra** [comment]
> `Cannot resolve module 'script'`

It cannot find the `script-loader` because it's not in a `node_modules` folder in a parent directory of the file. (Loaders resolve like modules.)

You can overwrite this behavior with `resolveLoader.root = path.join(__dirname, "node_modules")`.

**Comment by sokra** [comment]
This will change with webpack 2.0

**Comment by totty90** [comment]
Thanks that did work ok (:

**Comment by speigg** [comment]
`resolveLoader.root = path.join(__dirname, "node_modules")` only partially worked for me, unfortunately. 

I'm using the babel-loader like this: 
```
  module: {
    loaders: [
      { test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader?optional=runtime' },
      { test: /\.json$/, loader: 'json' }
    ]
  }
```


Setting the `resolveLoader.root` fixed some of the problems, but I'm still seeing these errors:
```
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/keys' in /<path>/<module>.js
...
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/freeze' in /<path>/<module>.js
```

**Comment by speigg** [comment]
I switched from an `exclude` to `include` rule for the `babel-loader` and it seems to be working now.

**Comment by totty90** [comment]
Thanks I might try it some time (:

**Comment by gravityrail** [comment]
@speigg - I got around the module resolution issue by resolving the full path of my modules inside the webpack config:

```javascript
{
	test: /\.jsx$/,
	loaders: [require.resolve('react-hot-loader'), require.resolve('babel-loader')+"?stage=1"],
	include: [path.join(__dirname, 'client'), path.join(__dirname, 'node_modules')]
},
```

**Comment by JSteunou** [comment]
+1 on this issue

I understand that the resolver follows the symlink, and I expect this behavior for modules inside my shared libraries, but I dont understand why the loader paths are resolved from target module and not from caller path. This could solve a bunch of issues when working with ln -s or npm link.

**Comment by arielschiavoni** [comment]
+1

**Comment by abrkn** [comment]
+1

**Comment by ben-eb** [comment]
+1

**Comment by kof** [comment]
this issues makes it inpossible to work on a project which is linked from some parent. In other words I can't fix a dep while building the main project and testing it within main project.

**Comment by JSteunou** [comment]
I worked around this bug by aliasing some dep using full path `__dirname + 'node_modules/...'` and using node `fs.realpathSync` to find real path for linked module when I need those. But jeeez, what a workaround just for dev mode.

**Comment by dallonf** [comment]
A decent workaround for this is to set `resolveLoader.fallback` to `path.join(__dirname, 'node_modules')`; this makes sure it looks in your local `node_modules` directory for loaders if it can't find one in the tree where it's currently working.

**Comment by apazzolini** [comment]
+1 on this, but dallonf's workaround did resolve my issue.

**Comment by loudwinston** [comment]
+1, my team is having this same issue.

**Comment by chemoish** [comment]
+1, dem resolving follows

**Comment by vvo** [comment]
Adding:

```js
  // for modules
  resolve: {
    fallback: [join(__dirname, 'node_modules')]
  },
  // same issue, for loaders like babel
  resolveLoader: {
    fallback: [join(__dirname, 'node_modules')]
  },
```

worked very well

**Comment by Aaronius** [comment]
Sure glad I found this. Thanks @vvo.

**Comment by geoctrl** [comment]
switching from `exclude` to `include` worked for me - thanks @speigg

**Comment by esayemm** [comment]
include worked for me too thanks @speigg

**Comment by paulpooch** [comment]
If you're here you're probably looking for this solution (at least I was):

http://webpack.github.io/docs/troubleshooting.html#npm-linked-modules-doesn-t-find-their-dependencies

**Comment by lingjieding** [comment]
config webpack resolve.symlinks = false fix my problem
ps： webapck3 + babel6
