### ISSUE TITLE
Where is the documentation for the Tapable.plugin deprecation?

### ISSUE THREAD

**Issue by givanse** [webpack/webpack#7845]
> (node:63533) DeprecationWarning: Tapable.plugin is deprecated. Use new API on .hooks instead

I'm trying to find docs for this use case:

```
const compiler = webpack(webpackConfig);
compiler.plugin('done', function(stat) {
});
```
[How to I rewrite compiler.plugin('done'…) with the new Webpack API?](https://stackoverflow.com/q/51679022/7852)

**Comment by givanse** [comment]
Ok, found the docs: https://webpack.js.org/api/compilation-hooks/

So, I should me doing:

```
    compiler.hooks.done.tap('some-string', function(stat) {
      console.log('first build complete');
    });
```

Is `some-string` a key of my choosing, perhaps to allow me to unregister the hook later?

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
