### ISSUE TITLE
ERROR in Module build failed: TypeError: Cannot read property 'replace' of undef                                                                                                                ined

### ISSUE THREAD

**Issue by manojcena** [webpack/webpack#7846]
Hi ,

I am building a application using angular 6. Every things works fine and when i regenerate build using ng build every thing is fine But when i generate ng-build --prod --aot i am getting error. please look at attachment. 
![capture](https://user-images.githubusercontent.com/15008735/43672562-42120f2e-97ce-11e8-8f69-00088cab35c1.PNG)

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
