### ISSUE TITLE
Error in installing webpack from npm

### ISSUE THREAD

**Issue by satan17** [webpack/webpack#7847]
I'm getting this line stuck from hours, I'm using windows 10 and running same command with admin priviliges. 

fetchMetadata: sill resolveWithNewModule chokidar@2.0.4 checking installable status

Anyone here getting the same issue, Please help me

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
