### ISSUE TITLE
Adding few lines at top of build files

### ISSUE THREAD

**Issue by krishna5737** [webpack/webpack#7848]
## Feature request

**What is the expected behavior?**
Want to add different-different lines at top of different output files of webpack build

**What is motivation or use case for adding/changing the behavior?**
- Adding companies copyright at top of files
- Adding somelines which needs to be there at starting of .js file for my application to work

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
yes

BannerPlugin works in same manner but it doesn't allow adding specific lines at specific file. PLease correct if I misunderstood something

**Comment by sokra** [comment]
The BannerPlugin will work for you. You can pass a function to generate a header per file.

**Comment by krishna5737** [comment]
Can I get some explanation on how to use functions (or some examples) as there is no such thing explained in webpack BannerPlugin Doc?

**Comment by montogeek** [comment]
```const webpack = require('webpack');

new webpack.BannerPlugin({
  banner: 'this string will be at the top of the output files'
});
```

**Comment by krishna5737** [comment]
@montogeek 
This is working fine but my problem is not solved yet.
 
//Let's assume entry files are a.js and b.js and
I want to append _require(test1.js) at the top of a.js_ and _require(test2.js) at the top of b.js_
then we want to check **if(["file"]== test1.js))** which will always return false and I can't append separate text in 2 different files.
