### ISSUE TITLE
Pls help fix compatibility webpack-stream and gulp4

### ISSUE THREAD

**Issue by mrG0bliN** [webpack/webpack#7851]
## OS
windwos 10 x64
λ node -v && npm -v
v10.8.0
6.3.0

---

I understand that this applies to other developers, but they say that it should be addressed to you, since the added functions inside the webpack are not related to their configuration.

```
	watch: true,
	watchOptions: {
		poll: 1000,
		ignored: /node_modules/

	},
```
this params not work correct, webpack not see any changes in my js files

## package.js
```
	"devDependencies": {
		"uglifyjs-webpack-plugin": "^1.2.7",
		"webpack": "^4.16.5",
		"webpack-cli": "^3.1.0",
		"webpack-stream": "^5.1.0"
	},
```

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
