### ISSUE TITLE
performance and devserver

### ISSUE THREAD

**Issue by TrustyWork** [webpack/webpack#7854]
# Bug report

**What is the current behavior?**
Special files are counted in the final size

webpack dev server. mode production
http://picua.org/img/2018-08/07/q9wdl1dgah7y7no0pxjo53mrv.png
build. mode production
http://picua.org/img/2018-08/07/lif2pwzbzb34h4aeryb6dak1k.png

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
The size of the working version should be displayed

**Other relevant information:**
webpack version:  4.16.3
Node.js version:  10.7.0
Operating System: Ubuntu MATE 18.04
Additional tools:

**Comment by TrustyWork** [comment]
hot reload scripts. In the build they are not, but they are in the webpack-dev-server.

**Comment by flyyang** [comment]
Webpack use that scripts do hot module reloading.

So yes, they are in webpack-dev-server. Just for better dev experience. They won't appear in prod mode.

**Comment by TrustyWork** [comment]
The size displays true but it is meaningless. I know that these files will not be there. As a developer, I need to see the build size and not the service size.
