### ISSUE TITLE
when i use npm run build  find  not have chunk Names  in  webpack 4.X

### ISSUE THREAD

**Issue by yehoan** [webpack/webpack#7855]
when i input npm run build then i find 
![image](https://user-images.githubusercontent.com/22631753/43758414-9b34b778-9a4e-11e8-97e8-b90af0820837.png)
and i  want to become 
![image](https://user-images.githubusercontent.com/22631753/43758469-c7ce4d30-9a4e-11e8-9fda-31ae60879ad5.png)
yeah  i  just update webpack  i not know  how to do    i have search  a lot  and test  please  help us  thanks

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/43758559-0ad3301e-9a4f-11e8-9b39-f3236095286e.png)
this is my webpack.config.js

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by montogeek** [comment]
You can find more info about `filename` https://webpack.js.org/configuration/output/#output-filename

**Comment by yehoan** [comment]
i  have  watch  but  no use sir
