### ISSUE TITLE
concatenateModules with cyclic referencies

### ISSUE THREAD

**Issue by Diademe** [webpack/webpack#7857]
# Bug report

**What is the current behavior?**
Some files with cyclic hard dependencies are concatenated (thank to the concatenateModules optimization).
I call a dependencies hard if it is one of the following:
- inline initialized static variable
- inherited class
- reference to a variable in another module in the global scope (ie not inside a function body)
- typed and decorated variable

The first three are dependencies that need to be resolved before the file is parsed.
The last one also needs to be resolved before the file is parsed, but it is due to the fact that typescript adds a decorator with the type of the variable while it transpil the file to javascript. Decorator are also evaluated during the parse of the file/module, so the type added by typescript must be resolved during the parse of the file.

the problem is that webpack concatenate those files in the same anonymouse function. It create references to class that are not defined yet with lead to a runtime error 
```__metadata("design:type", A)
ReferenceError: A is not defined
```

**If the current behavior is a bug, please provide the steps to reproduce.**
### step to reproduce:
- `git clone https://github.com/Diademe/webpack-concatenateModules-error.git`
- `cd webpack-concatenateModules-error`
- `npm install`
- `npm run build`
- `npm run start`

In this repo, there are two classes A and B, A reference B with a member of type B, B reference A with a member of type A. Both members are decorated (the decorator implementation doesn't matter).
typescript will add a decorator one each decorated member with the type of the member.

### workaround:
Disable the option concatenateModules in wepack.config.js

**What is the expected behavior?**
the files a.ts and b.ts should not be concatenated in the same function by webpack

**Other relevant information:**
webpack version:  4.16.5
Node.js version: 8.11.1
Operating System: windows

**Comment by sokra** [comment]
You have a cyclic dependency in your code. It's not visible directly in the source code and caused by `"emitDecoratorMetadata": true`. This options adds a reference to the member type (when decorated). This is not valid because it's circular.

Set `"emitDecoratorMetadata": false` to avoid this.

**Comment by sokra** [comment]
> I am curiouse about why it does.

It incorrectly gives you `undefined` when a TDZ-Error should be thrown.
