### ISSUE TITLE
Passing loader options as a function

### ISSUE THREAD

**Issue by bencergazda** [webpack/webpack#7858]
## Feature request

**What is the expected behavior?**
It would be really useful if we could pass a function on the loader's options property. The first argument of the function should be the loaderContext.

webpack.config.js
```
module: {
    rules: [
        {
            loader: 'loader-name',
            options: (loaderContext) => ({
                ...
            })
        }
    ]
}
```

**What is motivation or use case for adding/changing the behavior?**
Like this, it would be possible to use the loader API even when customizing the loader. My usecase is to be able to use the loader API in a custom node-sass importer function, which is declared in the loader's options object. A somewhat similar [PR is waiting in sass-loader](https://github.com/webpack-contrib/sass-loader/pull/513), which I really like, but in my opinion, it would be nice to solve the problem on an other level, so it would be available in any loaders. 

**How should this be implemented in your opinion?**
The implementation would affect `webpack` and `loader-utils`, I would call the options in loader-utils' getOptions (if typeof query === "function").
Unfortunately, I don't know how to pass a function over the `loaderToIdent()` in webpack's `NormalModuleFactory.js` (even whether it is possible or not).

**Are you willing to work on this yourself?**
yes

**Comment by TheLarkInn** [comment]
@sokra at first glance I'm not sure we want to add a function as another type for options, however I know that properties can be functions. I assigned to you for a recommendation, but I'll move to Send a PR, if we are okay with having this added capability.

**Comment by sokra** [comment]
I don't think this feature is needed. If a loader want to allow to use the loader context in functions pass via options they can do so. This should be solved on loader level.
