### ISSUE TITLE
Not work babel async/await with code splitting

### ISSUE THREAD

**Issue by ariran5** [webpack/webpack#7859]
# Bug report

**What is the current behavior?**
If i use babel-transform-runtime and use optimization splitChunks app.bundle.js not start in browser.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
clone https://github.com/ariran5/webpack-splitting-error
```
open index.html in dist
or 
```
clone https://github.com/ariran5/webpack-splitting-error
cd webpack-splitting-error
npm i
npm run webpack
```
and open index.html in dist

in order for this to work, you need to remove optimization in webpack config

**What is the expected behavior?**
JavaScript is expected to start working

**Other relevant information:**
webpack version:  4.16.5
Node.js version: 10.8
Operating System: windows 10
Additional tools:

**Comment by TheLarkInn** [comment]
There is technically no code-splitting (the use of `import()` to lazy load parts of your application on demand). 

I see you are trying to use splitChunks, which is a _cachability feature_ to optimize your network time or removing duplicate code across entry points.

![image](https://user-images.githubusercontent.com/3408176/43811550-e508ea9a-9a71-11e8-9285-43808c1bda9b.png)

The problem appears to me is that in your sample code, you have an index.html with only the app.js bundle included, however when you use splitChunks it means that you have to have both the shared bundle and the entry bundle in the html file up front at runtime. 

![image](https://user-images.githubusercontent.com/3408176/43811558-f10fc61a-9a71-11e8-931b-cc0d1010ad30.png)

This here will create not just a app.js bundle, but also this: ( a vendors~app.js shared bundle ).

![image](https://user-images.githubusercontent.com/3408176/43811565-fce5a630-9a71-11e8-8b4c-c8bbdc8cfdde.png)

If you are trying to leverage lazy loading, I would encourage you to check out webpack.js.org/guides and webpack.js.org/concepts.
