### ISSUE TITLE
Bug: Scoped externals not working

### ISSUE THREAD

**Issue by Hanterdro** [webpack/webpack#7860]
# Bug report

**What is the current behavior?**

```
    externals: {
        foo: 'foo‘, //is working
        pizza: {
            root: ['food', 'pizza‘] //is not working
        }
    }
```
As soon as I use scoped externals the import returns undefined.

I implemented the scoped externals as in the manual described:

https://webpack.js.org/configuration/externals/#object

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/Hanterdro/webpack-externals-bug

Clone my repo, open html/index.html and look at the console.

The `pizza` import is not working.

**What is the expected behavior?**

Working scoped externals.

**Other relevant information:**
webpack version:  4.16.5
Node.js version: v8.11.1
Operating System: macOS
Additional tools: "webpack-cli": "^3.1.0"

**Comment by CarreraPHP** [comment]
I too, face the same issue. The externals is not working when I had the root config. In my case, I have a iife format angular 4 library as a is file included in script tag. The angular/core lib is available as ng._angular_core externally. I have added the same in the external config. Yet, I am receiving undefined error.
