### ISSUE TITLE
HMR doesn't reload on change in pug-plain-loader included symlinks

### ISSUE THREAD

**Issue by webmasterslava** [webpack/webpack#7862]
```
<template lang="pug">

  div
    include ./normal_file.pug
    include ./symlinked_file.pug

</template>
```

When I make changes in "normal_file.pug" HMR works perfect, I see messages in console and changes are applied without reloading the page.

When I make changes in "symlinked_file.pug" HMR doesn't see any changes, no messages in console. I'm trying to reload the page manually and again I don't see changes. To see changes I should fully reload webpack-dev-server.

I use normal symlinks in Debian 9 x64.

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
