### ISSUE TITLE
`resolve.modules` doesn't respect order

### ISSUE THREAD

**Issue by catamphetamine** [webpack/webpack#7863]
Using latest Webpack 4.16.3.

```js
resolve: {
  modules: [
    'node_modules',
    path.resolve(__dirname, 'node_modules')
  ]
}
```

It's supposed to search in `node_modules` first, then search in the project's root `node_modules` folder.
Yet when I `import` module `a` which depends on module `b` it doesn't bundle the module `b` from `node_modules/a/node_modules/b`: instead it bundles `node_modules/b` (which is a different major version).

Is it supposed to respect the order of `resolve.modules`?

**Comment by catamphetamine** [comment]
Found a workaround: use relative paths instead of absolute paths.
Seems that absolute paths take precedence over relative ones.

```js
resolve: {
  modules: [
    'node_modules',
    path.basename(__dirname) + '/node_modules'
  ]
}
```

**Comment by sokra** [comment]
> Is it supposed to respect the order of resolve.modules?

yes

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.
