### ISSUE TITLE
I may be doing it wrong

### ISSUE THREAD

**Issue by qchroman** [webpack/webpack#7864]
Good day webpack experts!

I'm new to this wonderful product and I think I may be thinking about webpack in wrong terms and it may be affecting the project I'm trying to build.

Very simple task - bundle two CSS files into one and put it into the ./dist/styles folder where I also put one .js file.

First of all, I understand there is no way to bundle CSS w/o first importing it in main JS file and using mini-css-extract-plugin on on the module. I do just that:

```
test: /\.css$/,
use: [
    {
        loader: MiniCssExtractPlugin.loader
    },
    'css-loader'
]
```

The bundle of the css is loaded into the /dist folder. I then want to copy it into styles folder inside the dist folder. I do 

```
plugins: [
    new CopyWebpackPlugin([
        { from: './src/style/style-default.js', to: './styles/style-default.js', toType: 'file' },
        { from: './dist/style-default.css', to: './styles/style-default.css', toType: 'file' }
    ]),
    new MiniCssExtractPlugin({
        filename: 'style-default.css'
    })
],
```

And it fails because by the time the plugin runs it can't find the bundled css file because it isn't created yet.

I start wondering that I need to use task runners + webpack and not the webpack alone, but I may be missing something.

Your comments are greatly appreciated.

Thank you.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by qchroman** [comment]
Got it, sorry.
