### ISSUE TITLE
Intermittent browser console errors using watch in development mode 

### ISSUE THREAD

**Issue by tmpjr** [webpack/webpack#7872]
# Bug report

**What is the current behavior?**
* Run "yarn watch"
* App works initially and after 3-4 saves and rebuilds from the --watch
* After 4-5 saves the following error shows up on the Chrome console. I must ctrl-c my "yarn watch" and run it again. Rinse, repeat.
`
Uncaught Error: Module build failed: Error: ENOENT: no such file or directory, open '/apps/env27/project/fl_gca_sc/main/static/node_modules/node-libs-browser/node_modules/process/browser.js'
    at eval (browser.js:1)
    at Object../node_modules/node-libs-browser/node_modules/process/browser.js (build.js:638)
    at __webpack_require__ (build.js:20)
    at eval (setImmediate.js?6017:186)
    at Object../node_modules/setimmediate/setImmediate.js (build.js:649)
    at __webpack_require__ (build.js:20)
    at Object.eval (main.js?5118:54)
    at eval (main.js?5118:63)
    at Object../node_modules/timers-browserify/main.js (build.js:682)
    at __webpack_require__ (build.js:20)
`

**If the current behavior is a bug, please provide the steps to reproduce.**
Run a watch command:
1. Run "yarn watch"
2. Update source code a few different times to allow watch 3-4 rebuilds.

Here's my webpack config and package.json files including npm scripts:
https://gist.github.com/tmpjr/5ab082322a36a41a82952f31cc8b1bfc

**What is the expected behavior?**
App rebuilds without having to ctrl-c and restart npm script

**Other relevant information:**
webpack version:  4.16.5
Node.js version: 10.8.0
Operating System: MacOS 10.12.6 (Sierra)
Additional tools: Yarn 1.9.4

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by tmpjr** [comment]
Thanks for the fast response. I will try to do contrive an example over the weekend. Deadlines demand I work around this issue for now.  One thing I had not thought of was to reboot my Mac and just noticed it's been 45 days! Maybe there's some sort of corruptions issue going on.
