### ISSUE TITLE
webpackPrefetch always creates link rel inside if statement

### ISSUE THREAD

**Issue by againksy** [webpack/webpack#7873]
# Bug report

**What is the current behavior?**
If i use the dynamic import with webpackPrefetch like here
` 
 componentDidMount() {
    if(this.props.getcomponent){
      import(/* webpackChunkName: "Component", webpackPrefetch: -999 */'../components/Component').then(Component => {
        this.setState({ Component });
      })
    }
  }
`
i always got the link rel with this component created - it happens also if i do 
` 
 componentDidMount() {
    if(undefined){
      import(/* webpackChunkName: "Component", webpackPrefetch: -999 */'../components/Component').then(Component => {
        this.setState({ Component });
      })
    }
  }
`

webpack version:  ^4.16.2
Node.js version:  v8.11.3
Operating System: macos sierra

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by againksy** [comment]
@montogeek i answered everything from issue pattern, or should i keep the patter in the issue?
