### ISSUE TITLE
Name delimiter be applied to runtime chunk

### ISSUE THREAD

**Issue by PlayMa256** [webpack/webpack#7875]
## Feature request

**What is the expected behavior?**
When declaring property `automaticNameDelimiter: '-'` this should be applied to runtime files too, i.e: `runtime-main.js`.

**What is motivation or use case for adding/changing the behavior?**
Some authentication providers/proxies ([Siteminder](https://www.ibm.com/support/knowledgecenter/en/SSEP7J_11.0.0/com.ibm.swg.ba.cognos.inst_cr_winux.doc/c_configurereportnettousenetegritysiteminder.html), [Single sign ](https://docops.ca.com/ca-single-sign-on/12-52-sp1/en/configuring/web-agent-configuration/user-protection-and-tracking/help-prevent-attacks#HelpPreventAttacks-SpecifyBadURLCharacters)on solutions) does not allow some characters on files they are proxying.

**How should this be implemented in your opinion?**
When declaring property `automaticNameDelimiter: '-'` and having `runtimeChunk: true` the defined delimiter should be applied to runtimeChunks, i.e: `runtime-main.js`.

**Are you willing to work on this yourself?**
Totally.

**Comment by sokra** [comment]
Workaround:

``` js
runtimeChunk: {
  name: entrypoint => `runtime-${entrypoint.name}`
}
```

**Comment by sokra** [comment]
I think I would be a bit weird that an option from `splitChunks` affect `runtimeChunk`. It could make sense to have an `runtimeChunk.automaticNameDelimiter`. Considering that the "workaround"/solution takes the same config space, it probably doesn't make sense to add such an option.

**Comment by PlayMa256** [comment]
Indeed, that works too.

Thanks.
