### ISSUE TITLE
Why is lodash in my bundle file when i don't use it anywhere

### ISSUE THREAD

**Issue by darasi** [webpack/webpack#7878]

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
