### ISSUE TITLE
The problem in split app and vendor code

### ISSUE THREAD

**Issue by zxcabs** [webpack/webpack#788]
Hello,
In [documentation](http://webpack.github.io/docs/code-splitting.html#split-app-and-vendor-code) for code spliting, you recomend use CommunsChunkPlugin for build vendor.bundle, but that method have some problems.

The problem is: my app have many dynamic code, which loaded with the require.ensure, and when I add or remove a new chunk, it changes vendor.bundle.js, because the vendor.bundle is a main bundle and contains the names of all the app chunks.

Is there any other way to build vendor.bundle?

**Comment by sokra** [comment]
see #660
