### ISSUE TITLE
[contenthash] not working for .js files

### ISSUE THREAD

**Issue by jousi592** [webpack/webpack#7884]
# Bug report

**What is the current behavior?**

When adding `[contenthash]` to `.js` files, webpack doesnt compile the `contenthash` correctly and outputs `js/main.[contenthash].js`.

But when doing the same to `.css` files, the output is correct: `static/css/main.142c3dccf1d3eb2c02c84322b0cf2ef7.css`

**If the current behavior is a bug, please provide the steps to reproduce.**

Add `filename: utils.assetsPath('js/[name].[contenthash].js')` to `output` object in`webpack.conf.js`

**What is the expected behavior?**
Getting correct `contenthash` for `.js` files.

**Other relevant information:**
If Is try using `[hash]`, then it gets added correctly.

webpack version:  4.16.5
Node.js version: v8.11.2
Operating System: High Sierra
Additional tools:

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

` utils.assetsPath('js/[name].[contenthash].js')` is not from webpack.

**Comment by jousi592** [comment]
Unfortunately it doesnt work, even if I just use `filename: 'js/[name].[contenthash].js'`.
I am working on a large project and wanted to move away from building and versioning FE files with Webloader to doing it through webpack, but I will try getting you that reproduction on a smaller scale.

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by jousi592** [comment]
@montogeek here is the git repo you wanted https://github.com/jousi592/webpack_contenthash_bug , if you look into the `/dist` folder or try to build the project, you will see that `.css` files have a correct `contnthash`, but `.js` files dont.

**Comment by montogeek** [comment]
webpack is showing show the error:
```bash
ERROR in chunk manifest [entry]
[contenthash].js
Conflict: Multiple assets emit to the same filename [contenthash].js
```

**Comment by montogeek** [comment]
webpack 3.6 doesn't support `[contenthash]`, please use > 4.3 https://github.com/webpack/webpack/releases/tag/v4.3.0

**Comment by montogeek** [comment]
Please next time, write correct information in the issue template.

**Comment by jousi592** [comment]
@montogeek Well on our project we are using 4.16.5, just the new project I started for this issue has the old one, I will update it and try again.

**Comment by omeryousaf** [comment]
For those looking to achieve this with webpack 2, try [hash] instead of [contenthash].

**Comment by tGodson** [comment]
thanks @omeryousaf it worked
