### ISSUE TITLE
[Question] Documentation for webpack 4

### ISSUE THREAD

**Issue by Sibiraj-S** [webpack/webpack#7885]
In Readme it is said that

> This README reflects webpack v2.x and v3.x. The webpack v1.x documentation has been deprecated and deleted.

Is there is reason why it is not updated. It seems to be kept on purpose.

Is document for webpack 4 out there is a complete one?

**Comment by montogeek** [comment]
Use webpack.js.org for webpack 4 docs.

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.

**Comment by Sibiraj-S** [comment]
Hi, @montogeek Thanks for the tip. I agree this question is too generalised.

I have pointed out a line in the `README` of this repo. Hence I asked here. I was thinking of editing that thing in the README. 

I am aware that docs is available at https://webpack.js.org/. Today my proposal to upgrade to webpack 4 was rejected because of that one line in this repo as it is not clear or outdated.

**Comment by montogeek** [comment]
That line is outdated, it should say something similar to:
- Check https://webpack.js.org for webpack 4 documentation.
- Check our full documentation at https://webpack.js.org

**Comment by Sibiraj-S** [comment]
I think @montogeek That line is not at all needed.

**Comment by montogeek** [comment]
Yeah, we could delete it.
