### ISSUE TITLE
"use strict" optimization bug

### ISSUE THREAD

**Issue by chuckdumont** [webpack/webpack#7891]
# Bug report

**What is the current behavior?**
`Uncaught SyntaxError: Strict mode code may not include a with statement` from Chrome when webpack is used with production mode.  Does not reproduce with development mode.

**If the current behavior is a bug, please provide the steps to reproduce.**
The following test case reproduces the error:
```javascript
(function(context, factory) {
  'use strict';

  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define([], factory);
  } else if (typeof exports === 'object') {
    // Node/CommonJS
    module.exports = factory();
  }
}(this, (function() {
  var context = {msg: "hello"};
  with (context) {
    console.log(msg);
  }
})));
```
Note that the `with` statement is outside the strict mode scope.  This remains the case when compiled with webpck in development mode, however, when compiled in production mode, the body of the factory method is moved so that it is now within the strict mode scope, resulting in the specified error.

Note that I'm experiencing this issue with a third-party library, and modifying the offending code is not an option.

**What is the expected behavior?**
The optimizer should respect strict mode scoping and not move non-strict mode code into a strict mode scope.

**Other relevant information:**
webpack version:  4.16.5
Node.js version: v8.11.1
Operating System: Windows 10
Additional tools:

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by chuckdumont** [comment]
Should I open an issue against UglifyJS?

**Comment by sokra** [comment]
No the uglify-es branch is unmaintained anyway. terser is the maintained fork.

**Comment by evilebottnawi** [comment]
Use `terser` plugin, also you can try latest `uglify` plugin
