### ISSUE TITLE
webpack 4 entry point not working on windows

### ISSUE THREAD

**Issue by richardry** [webpack/webpack#7892]
# Bug report

**What is the current behavior?**
Got error "Insufficient number of arguments or no entry found. Alternatively, run 'webpack(-cli) --help' for usage info. ERROR in Entry module not found: Error: Can't resolve './src' 

**Please note this only happens on windows, so please verify it on windows before the issue is closed!**
I've tried the same configuration on webpack 3 and it doesn't have any problem on webpack 3. I've seen people raised the issue previously but be closed without resolution. It works on mac and linux but not on windows probably due to the path separator on windows are different and this wasn't counted for in the code, just a guess. 

**If the current behavior is a bug, please provide the steps to reproduce.**

I have entry point:
  entry: {
    book: 'WebContent/js/booking/book.js',
    change: 'WebContent/js/booking/change.js',
  },

**What is the expected behavior?**
It should work on windows as well as other platforms

**Other relevant information:**
webpack version:  4.16.5
Node.js version: 8.9.3
Operating System:  windows only
Additional tools:

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by sokra** [comment]
It doesn't seem to find your webpack.config.js.

**Comment by richardry** [comment]
I started over by clearing everything, removed node_modules. After that it works! So I think it is just my local environment's problem.

I am sorry to raise a fake bug.

I'm closing it.
