### ISSUE TITLE
Proposal: auto add same name file dependency plugin

### ISSUE THREAD

**Issue by acrazing** [webpack/webpack#7895]
**What is the expected behavior?**

Allow webpack add dependencies for a module by configuration, rather than use `require` in source file.

**What is motivation or use case for adding/changing the behavior?**

This is useful for avoid adding require style file in js like file, just like `require('./index.scss')`.

**How should this be implemented in your opinion?**

It could be a plugin, just like this:

```js
// webpack.config.js
module.exports = {
  // ...
  plugins: [
    new webpack.AutoImportPlugin([
      {
        test: /\.(ts|tsx|js|jsx)$/,
        exclude: /node_modules/,
        add: (request) => {
          const basename = request.replace(/[^.]+$/, '')
          return ['css', 'less', 'scss'].map((item) => basename + item)
        },
        watch: true,
      },
      {
        test: /node_modules\/antd\/.+\/index\.js$/,
        add: (request) => {
          return path.dirname(request) + '/style/index.js'
        },
        watch: false,
      },
    ]),
  ],
}
```

It:

- allow input a object or an array of object to configure it, just like `module.rules`.
- use `test` to check if the module should be processed
- use `exclude` to check if the module is ignored
- `add` is a function, with one parameter, which is the filename of the module, and returns an array of the filename which need to be added.
- `watch` means should add the added files to watch list even if it does not exist. please note that all the dependencies is **optional**, which means if the `add` method returns filename does not exist, will not emit error, and if `watch` option is `true`, will add all the files to watch list, if the file is added then, it will be tracked automatically.

**Are you willing to work on this yourself?**

yes, but the problem is the webpack module does not support `addOptionalDependency`.

**Comment by sokra** [comment]
There is https://github.com/deepsweet/baggage-loader
You can use this as base to implement a loader which does that.

You can use `loaderContext.resolve` to check if a file exists.
