### ISSUE TITLE
extract mutiple js files from node_modules

### ISSUE THREAD

**Issue by Ingrid881012** [webpack/webpack#7897]
# Bug report
I have a project which created by vue-cli2.0 and has multiple pages.  Each page has imported the module vue and vue-router, some of these pages import other module, like vue-lazyload, vue-awesome-swiper or picker. Now I update my project from webpack3 to Webpack4. I encountered one issue. I want to extract 'vue' and 'vue-router' module into vendor.js and extract other modules into its seperate js file. But in webpack4, splitChunks not fullfill my requirement.

Below is my webpack config:

* in webpack3 ( which works well )

```
plugins:[
new webpack.optimize.CommonsChunkPlugin({
        name: 'vendor',
        minChunks: (m) => /node_modules/.test(m.context)
    }),
    new webpack.optimize.CommonsChunkPlugin({
        name: 'swiper',
        minChunks: (m) => /node_modules\/(?:vue-lazyload|vue-awesome-swiper|swiper|dom7|object-assign)/.test(m.context)
    }),
    new webpack.optimize.CommonsChunkPlugin({
        name: 'lazyload',
        minChunks: (m) => /node_modules\/(?:vue-lazyload)/.test(m.context)
    }),
]
```

* in webpack4

```
splitChunks:{
      cacheGroups: {
        lazyload: {
          test: /[\\/]node_modules[\\/](?:vue-lazyload)/,
          name: 'vendor',
          chunks: 'all'
        },
        swiper: {
          test: /[\\/]node_modules[\\/](?:vue-lazyload|vue-awesome-swiper|swiper|dom7|object-assign)/,
          name: 'swiper',
          chunks: 'all'
        },
        commons: {
          test: /[\\/]node_modules[\\/]/,
          name: 'vendor',
          chunks: 'all'
        },
      }
    }
```

But in webpack4, the extracted js file will always the last one, I got vendor.js finally.

**What is the current behavior?**

Cannot extract multiply common js files from node_modules folder.

**If the current behavior is a bug, please provide the steps to reproduce.**

1) create a project with two pages
2) on page import vue and vue-lazyload and another page import vue and vue-awesome-swiper
3) config webpack to extract vendor file.

**What is the expected behavior?**

can extract mutiple js file from node_modules

**Other relevant information:**
webpack version:  4.16.5
Node.js version: 8.9.3
Operating System:  mac os
Additional tools:

**Comment by sokra** [comment]
Try adding `enforce: true`. Maybe the min size is not reached.

**Comment by Ingrid881012** [comment]
Thank you for your quick response. I tried your suggestion and the expected files are generated. But the vendor.js is a little strange. I got vue-router ahead of vue in vendor.js. It's not extract the file according to its dependency.

Blow is my configuration:

splitChunks:{
      cacheGroups: {   
        lazyload: {
          test: /[\\/]node_modules[\\/](?:vue-lazyload)/,
          name: 'lazyload',
          enforce: true
        },
        swiper: {
          test: /[\\/]node_modules[\\/](?:vue-lazyload|vue-awesome-swiper|swiper|dom7|object-assign)/,
          name: 'swiper',
          enforce: true
        },  
        commons: {
          test: /[\\/]node_modules[\\/]/,
          name: 'vendor',
          enforce: true
        }, 
      }

Thanks for your time.

**Comment by sokra** [comment]
`vue-router` matches `/[\\/]node_modules[\\/]/` so it's in `vendor.js`.

**Comment by Ingrid881012** [comment]
yes, but in vendor.js, vue-router is packed before vue.  A little strange. Is there any way  to control the sort mode of modules that packed in vendor.js?  Many thanks.

**Comment by sokra** [comment]
The order of modules in the file doesn't matter. It's ordered by id for consistency. Why do you care about that.

**Comment by Ingrid881012** [comment]
Thanks sokra, my issue has been solved. Below configuration works fine.

config
    .optimization
    .splitChunks({
      cacheGroups: {
        vendors: {
          name: 'vendors',
          test: /[\\\/]node_modules[\\\/]/,
          priority: -10,
          chunks: 'all'
        },
        swiper: {
          name: 'swiper',
          test: /[\\\/]node_modules[\\\/](?:(vue-awesome-swiper|swiper|ssr-window|dom7|object-assign))/,
          priority: -8,
          enforce: true,
          chunks: 'initial'
        },
        axios:{
          test: /[\\\/]node_modules[\\\/](?:(axios|follow-redirects|is-buffer|follow-redirects[\\\/]node_modules[\\\/]debug|ms))/,
          name: "axios",
          priority: -6,
          enforce: true,
          chunks: "all"
        },
        vuex: {
          test: /[\\\/]node_modules[\\\/](?:vuex)/,
          name: "vuex",
          priority: -4,
          enforce: true,
          chunks: "all"
        },
        "vue-router": {
          test: /[\\\/]node_modules[\\\/](?:vue-router)/,
          name: "vue-router",
          priority: -2,
          enforce: true,
          chunks: "all"
        },
        common: {
          name: 'chunk-common',
          minChunks: 2,
          priority: -20,
          chunks: 'initial',
          reuseExistingChunk: true
        }
      }
    })

The order of modules in my *.html file can be configured in HtmlWebpackPlugin.
