### ISSUE TITLE
Webpack compiles invalid CSS even though the CSS is valid?

### ISSUE THREAD

**Issue by JamesTheHacker** [webpack/webpack#7898]
Webpack is bundling my CSS but when it's loaded in the browser it's been interpreted as invalid even though the CSS is perfectly valid.

Here is my **index.css** file. All it contains is a couple of selectors:

    img {
        height: auto;
    }
    
When it compiles using Webpack it gets outputted like so. I get no errors when compiling:

    img {
      height: auto; }
    

When I then load in chrome I get this error:

[![enter image description here][1]][1]

For some reason the `{` is invalid. I have no idea what is causing this as the CSS is valid.

My **webpack.prod.config.js** file is:

    const path = require('path')
    const MiniCssExtractPlugin = require("mini-css-extract-plugin")
    
    
    module.exports = {
        entry: './src/index.js',
        output: {
            path: path.resolve(__dirname, 'dist'),
            filename: 'index.js'
        },
        module: {
            rules: [
    
                {
                    test: /\.js$/,
                    exclude: /node_modules/,
                    use: {
                        loader: "babel-loader"
                    }
                },
                {
                    test: /\.svg$/,
                    loader: 'svg-inline-loader',
                },
                {
                    test: /\.(png|woff|woff2|eot|ttf|svg)$/,
                    loader: 'url-loader?limit=100000'
                },
                {
                    test: /\.(gif|png|jpe?g)$/i,
                    use: [
                        'file-loader',
                        {
                            loader: 'image-webpack-loader',
                            options: {
                                disable: true,
                            },
                        },
                    ],
                },
                {
                    test: /\.css$/,
                    use: [{
                            loader: MiniCssExtractPlugin.loader,
                            options: {
                                // you can specify a publicPath here
                                // by default it use publicPath in webpackOptions.output
                                publicPath: '../'
                            }
                        },
                        "css-loader"
                    ]
                },
            ],
        },
        plugins: [
            new MiniCssExtractPlugin({
                filename: "index.css",
                chunkFilename: "[id].css"
            })
        ],
    
    }

And here is my **index.js**:

    import $ from "jquery"
    import Flickity from "flickity"
    import jQueryBridget from "jquery-bridget"
    import particlesJS from "particlesjs"
    import slick from "slick-carousel"
    
    import accordion from "../node_modules/bulma-extensions/bulma-accordion/dist/js/bulma-accordion.min.js"
    
    /*
     * Styles
     */
    import './test.css'

I've been stuck on this for hours and my client is going nuts because I missed the deadline to have it uploaded by midnight. This is the only thing stopping me. I've had to create a new repo and reduce it down to try and find the issue but I'm still baffled.

  [1]: https://i.stack.imgur.com/5gMwh.png

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by JamesTheHacker** [comment]
Closing this. While I was creating the repo I realised someone had included the stylesheet with a script tag when adding the content. Not an issue.

**Comment by montogeek** [comment]
Next time, please open the file itself.
