### ISSUE TITLE
require returns empty object in angular project

### ISSUE THREAD

**Issue by TomRed97** [webpack/webpack#7899]
Hi, I have question with require in typescript. I have project with angular and build it with webpack.
But I have require in it. (var temp = require('some.js')). And this require returns empty object. it works fine with system.config.js.
Any ideas?

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.
