### ISSUE TITLE
Webpack packing two copies of the exact same script, with a different query string appended

### ISSUE THREAD

**Issue by Kamshak** [webpack/webpack#7900]
# Bug report

When packing an app a dependency is included multiple times inside the vendor chunk, with an id appended to it in a query string. In the case of firebase this breaks their "module registration" system.

**What is the current behavior?**

When having an app like this:

index.js
```js
import { auth } from 'firebase/app';
import { AngularFireAuth } from 'angularfire2/auth';
import { AngularFireDatabase } from 'angularfire2/database';

```
angularfire2/auth with ```
node_modules/angularfire2/auth.js
```js
import '@firebase/auth';
```

angularfire2/database with ```
node_modules/angularfire2/database.js
```js
import '@firebase/database';
```

@firebase/database with ```/node_modules/@firebase/database/dist/index.esm.js```
```js
import firebase from '@firebase/app';
```

@firebase/auth with ```node_modules/@firebase/auth/dist/auth.esm.js```
``` js
import firebase from '@firebase/app';
``` 

@firebase/app with ```node_modules/@firebase/app/dist/index.esm.js```
``` js
// code here 123
``` 

Webpack generates something like this:
```
/***/ "./node_modules/@firebase/database/dist/index.esm.js":
/* harmony import */ var _firebase_app__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__("./node_modules/@firebase/app/dist/index.esm.js?96d7");


/***/ "./node_modules/@firebase/auth/dist/auth.esm.js":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* WEBPACK VAR INJECTION */(function(global) {/* harmony import */ var _firebase_app__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__("./node_modules/@firebase/app/dist/index.esm.js?3dc3");


/***/ "./node_modules/@firebase/app/dist/index.esm.js?96d7":
    (function(module, __webpack_exports__, __webpack_require__) {
    __webpack_require__.r(__webpack_exports__);
    /* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "firebase", function() { 
    return firebase; });
...

/***/ "./node_modules/@firebase/app/dist/index.esm.js?3dc3":  
    (function(module, __webpack_exports__, __webpack_require__) {
    __webpack_require__.r(__webpack_exports__);
    /* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "firebase", function() { 
    return firebase; });
...
```

The code of ```/node_modules/@firebase/app/dist/index.esm.js?3dc3``` and ```node_modules/@firebase/app/dist/index.esm.js?96d7``` is the same.

**If the current behavior is a bug, please provide the steps to reproduce.**
see above

**What is the expected behavior?**
It should include only one ```/node_modules/@firebase/app/dist/index.esm.js``` instead of two different copies ( ```/node_modules/@firebase/app/dist/index.esm.js?3dc3``` and ```node_modules/@firebase/app/dist/index.esm.js?96d7```) with the exact same code.

**Other relevant information:**
webpack version:  4.16.5
Node.js version: v8.11.1
Operating System: Ubuntu x64
Additional tools:

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by Kamshak** [comment]
@montogeek unfotunately i have not managed to replicate this when using just js without TS/angular :(
Unfortunately i don't understand enough of webpack internals to have any clue where these ?3dc3/?96d7 could come from. Do you perhaps have an intuition into which direction i could look into?

**Comment by sokra** [comment]
> where these ?3dc3/?96d7 could come from

These strings are appended when two modules would have the same name. It's added to avoid conflicts.

The name uses only the resource name, while identity also includes loaders and loader options. These modules probably have different loaders applied.

**Comment by Kamshak** [comment]
Thanks!
