### ISSUE TITLE
More flexible options for `output.library`, `output.libraryTarget` and `output.libraryExport`

### ISSUE THREAD

**Issue by mrksbnch** [webpack/webpack#7904]
## Feature request

**What is the expected behavior?**

The `output` options (`output.library`, `output.libraryTarget` and `output.libraryExport`) should allow functions in addition to the current possibilities (arrays, strings etc.).

**What is motivation or use case for adding/changing the behavior?**

The current way to specify options for `output.library`, `output.libraryTarget` and `output.libraryExport` is very limiting and e.g. doesn't allow us to specify different `library` or  `output.libraryTarget` for every entry file. The only workaround for this (AFAIK) is to run webpack multiple times with different configs / environment variables.

**How should this be implemented in your opinion?**

I'm not familiar with the internals of webpack but it could be implemented similar to `output.filename` (https://github.com/webpack/webpack/issues/6098), e.g.

```
{
    output: {
        library: (bundle) => {
            return bundle.name === 'file' ? 'something' : ['something', '[name]'];
        }
    }
}
```

**Are you willing to work on this yourself?**

If someone is able to give me some direction on where to start and how this can be implemented, I'm willing to work on this myself (although I'm not at all familiar how webpack works internally).

**Comment by sokra** [comment]
Send a PR.

See https://github.com/webpack/webpack/blob/master/lib/LibraryTemplatePlugin.js

**Comment by mrksbnch** [comment]
@sokra Thanks, I'll look into that.

**Comment by byzyk** [comment]
Hey @mrksbnch , thanks for your feature request!

I was wondering if you're still going to work on this one? I could pick this one up so let me know, please.

**Comment by mrksbnch** [comment]
Hi @byzyk, I was looking at the needed changes and the how webpack generally works at the weekend but haven't directly started with this feature yet due to some project deadlines end of this week. So, feel free to pick this up if you have time. Thanks!

**Comment by defcc** [comment]
@byzyk Are you still working on this feature ? I could try to follow it up if you do not have enough time currently.

**Comment by byzyk** [comment]
Hi @defcc!

Yeah, that would be just great since I'm a bit short on time at the moment. Feel free to pick up #8000 where I left it, I'd suggest starting from addressing Tobias' comments and let me know if you need any assistance from my end. Thanks!

**Comment by evilebottnawi** [comment]
bump

**Comment by evilebottnawi** [comment]
Bump

**Comment by sokra** [comment]
The library option is supported per entrypoint now
