### ISSUE TITLE
how to connect external urls?

### ISSUE THREAD

**Issue by alfblasco** [webpack/webpack#7909]
Can you help me?
module.exports = {

    entry: {
        publicPath: 'https://cdn.jsdelivr.net/npm/vue@2.5.17/dist/vue.js'
    },
    output: {
        filename: './build/bundle.js',
        path: __dirname
    }
};
//

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.

**Comment by alfblasco** [comment]
sorry!
