### ISSUE TITLE
Async import - docs improving / clarifications

### ISSUE THREAD

**Issue by damianobarbati** [webpack/webpack#7911]
**1) publicPath trailing slash and async chunk loading**

I noted that not appending a trailing slash to `output.publicPath` will cause wrong url when loading async chunks. *Should this be mentioned in the docs?*

Bad:
```
publicPath: path.join('./dist/visitor'), 
=> results in
https://localhost:8443/dist/visitorvendors~recharts.js?hash=6eb54aa48c40138921d0
```

Good:
```
publicPath: path.join('./dist/visitor') + '/', 
=> results in
https://localhost:8443/dist/visitor/vendors~recharts.js?hash=6eb54aa48c40138921d0
```

Note: appending a trailing slash to publicPath will cause url-loader and file-loader to generate urls like the following (double slash!):
```
import file from './file.woff';
consoe.log(file);
dist/visitor//assets/fonts/montserrat-latin-400.woff2?hash=501ce09c42716a2f6e1503a25eb174c9
```

**2) Tree shaking**

Async-importing a dependency results in the whole file being imported.
*Is there any way to three shake that the imported chunk providing the named imports we're interested in?*

```
import(/* webpackChunkName: "recharts", names: ["LineChart", "YAxis", "XAxis", "CartesianGrid"] */'recharts')
```
Since we are resolving to the `main` of the node_module, solutions like the following can't work if we're not transpiling node_modules and furthermore that requires us to know where the named exports are located on filesystem/dependency folder (if they are separated as files, which we cannot be sure about).
```
import(/* webpackChunkName: "recharts/Line"*/'recharts/Line');
import(/* webpackChunkName: "recharts/Legend"*/'recharts/Legend');
etc etc
```

**3) "vendors" prefix**

*Is "vendors" prefix always applied to imported chunk?*

With the following configuration:
```
output: {
    path: path.resolve('./dist', name),
    publicPath: path.join('./dist', name) + '/',
    chunkFilename: '[name].chunk.js?hash=[chunkhash]',
    filename: '[name].js?hash=[hash]',
},
```
And code:
```
import(/* webpackChunkName: "recharts" */'recharts');
```

The resulting chunk url is:
`https://localhost:8443/dist/visitor/vendors~recharts.chunk.js?hash=c8f59ac9e1114ac6f2ce`

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.

**Comment by damianobarbati** [comment]
Hey @montogeek, serious? StackOverflow? 😅

- It's been a dead spot for years by now, did you have a look around recently?
https://stackoverflow.com/questions/tagged/webpack?sort=newest&days=1
https://stackoverflow.com/questions/tagged/webpack-4?sort=newest&days=7

- Webpack is like Babel: it changes so fast that there's no way to get help on it but asking directly mantainers/developers for advanced usage (when specific details are not covered in docs). 
By the time community users will build proper knowledge about Webpack v4 to answer each other, there will be Webpack v9 out which everybody will be adopting because of whatever new shiny features, and guess what... nobody will know about them yet but developers. And here we go again 😅

Truth is GitHub is the best and only place today to ask for details like these.
Please stop asking developers to go on SO: an honest "closing this for lack of time, you're on your own man" is way better and accepted. 👍🏻

******
By the way please consider at least mentioning (if not investigating) the `output.publicPath` trailing slash issue causing wrong url loading. 
It may not be a problem when importing into code, but it kills preload/prefetching because of the url mismatch.
It can cause several hours waste to be identified for lots.
******

Good work though, keep going like this guys.
