### ISSUE TITLE
Webpack4 codesplitting duplicate Error

### ISSUE THREAD

**Issue by gladsonrobinson** [webpack/webpack#7914]
```
module.exports = {
  entry: {
    vendors: "./src/vendor",
    main: "./src/index.js",
    auth: "./src/auth.js",
    search: "./src/search.js",
    cinema: "./src/cinema.js"
  },
optimization: {
    splitChunks: {
      cacheGroups: {
        vendors: {
          test: /[\\/]node_modules[\\/]/,
          name: "vendors",
          chunks: "all"
        }
      },
    },
    runtimeChunk: "single",
  }
```

This is working good. But the chunks for cinema.js and main.js have duplicate entries. Please help me on how to avoid it. I need to move duplicate code from cinema.js to main.js

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
