### ISSUE TITLE
Dynamic async import not working

### ISSUE THREAD

**Issue by Patcher56** [webpack/webpack#7916]
# Bug report

**What is the current behavior?**
When you look at the minimal reproduction link you can see the Icon.vue. There I built my dynamic component, where the dynamic svgs get loaded.
The svgs can only be loaded with a svg-loader. You can see my implementation in the vue.config.js.

The build runs without errors and creates a .js file for every chunk - perfect.

When I try to import the model in another vue project and use the component, the following error appears and the icon will not be loaded.

It parses the file right but it can't be found.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. clone repo above
2. put some svgs into assets/fa/light
3. build the project using `yarn build`
4. creating a link using `yarn link`
4. create a new vue project (e.g. `vue create <projectname>`)
5. link the project using `yarn link 'v-icon'`
6. import the component using `import icon from 'v-icon'`
7. in the templates section write `<icon name="trash"></icon>` while 'trash' is one of the icon names you added before
8. serve the app using yarn serve
9. watch the error appearing

```
Failed to resolve async component: function(){return n("2eab")("./".concat(i,".svg"))}
Reason: Error: Loading chunk 11 failed.
(missing: http://localhost:8080/v-icon.umd.min.11.js)
```

Repository:
https://gitlab.com/patcher56/v-icon/tree/master

**What is the expected behavior?**
It should load the requested icon dynamically

**Other relevant information:**
webpack version:  4.15.1
Node.js version: 10.9
Operating System: macOS
Additional tools: vuejs @vue/cli

**Comment by Patcher56** [comment]
I already tried to push the issue in the vue repository
vuejs/vue#8678

**Comment by Patcher56** [comment]
Yes. I put some icon into the assets/fa/light folder and built the package.
After that it creates the v-icon.umd.min.js and for every icon a v-icon.umd.min.<number>.js file
It also creates a demo.html. If I view this demo.html, everything works.

It only doesn't work when importing the package in an existing project.

To your question: I don't believe that the v-icon.umd.min.11.js exists in the root directory. The v-icon-package is an imported package. Therefore I believe, the files do not exist somewhere in the root directory..

**Comment by sokra** [comment]
Seems like your `publicPath` configuration is incorrect.

**Comment by igordymbovskyi** [comment]
Have the same issue with React application.

**Comment by Patcher56** [comment]
Any ideas?
