### ISSUE TITLE
this transformed to undefined in webpack 4

### ISSUE THREAD

**Issue by uribro** [webpack/webpack#7917]
# Bug report

**What is the current behavior?**
module this is being replace to undefined when switching to webpack 4 from webpack 3.
 

**If the current behavior is a bug, please provide the steps to reproduce.**

thisTest.js:

```
this.hello = 'helloworld';
console.log(this.hello);
```

index.js
```
import a from './thisTest';

```

package.json

`"build:dev": "webpack --config ./build/webpack.dev.js --mode development"`

webpack.dev.js

```
const PATH = require('path');
//-------------------
// Modes
//-------------------
const ENV_MODES = {
    DEV: 'development',
    PROD: 'production'
};
const ENV_MODE = process.env.NODE_ENV;

const ROOT = PATH.resolve(__dirname, '../');
const SRC_FOLDER = PATH.resolve(__dirname, ROOT, 'src/');
const BUILD_FOLDER = PATH.resolve(__dirname, ROOT, 'dist/');

const publicPath = (ENV_MODE === ENV_MODES.DEV) ? '/' : '/retail/';

module.exports = {
    mode: 'development',
    cache: true,
    context: ROOT,
    entry: {
        bundle: PATH.resolve(SRC_FOLDER, 'index.js'),
    },
    output: {
        filename: '[name].js',
        publicPath,
        path: BUILD_FOLDER,
        chunkFilename: '[name].chunk.js'
    },
    module: {
        rules: [
            {
                test: /(\.jsx|\.js)$/,
                include: [SRC_FOLDER],
                use: {
                    loader: 'babel-loader',
                },
            },
        ]
    },
};

```

npm run build:dev

output: bundle.js

actual:
undefined.hello = 'helloworld'

expected:
this.hello = 'helloworld'

try to run `node bundle.js`

Cannot set property 'hello' of undefined

**What is the expected behavior?**
this.hello = 'helloworld'

**Other relevant information:**
webpack version:  4.6.15 (tried with every webpack version on 4)
Node.js version: 8.11.3 (same issue on node 6)
    "webpack": "~4.16.5",
    "webpack-cli": "~3.1.0",
    "babel-cli": "~6.26.0",
    "babel-loader": "~7.1.4",
    "babel-preset-env": "~1.7.0",

Operating System: 
Windows 10

Additional tools:

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by uribro** [comment]
@montogeek I reproduce it in this repo:  https://github.com/uribro/webpack_this_issue

you can run node dist/bundle.js to see the error
or npm run build:dev to rebuild the bundle.

**Comment by uribro** [comment]
@sokra are you saying it's babel issue? how do I solve this ?

**Comment by sokra** [comment]
It's not a bug. `this` is undefined in ESM.

**Comment by uribro** [comment]
@sokra The problem is that it worked before in Webpack 3 with babel. 
and assume that you are correct then making this  presets: [['env', {"modules": false}]] configuration is passing the given example but same issue is happening when adding export

like so:

```
this.hello = "hello world";
console.log(this.hello);
export const sliceSelector =  state => state; // this line causes "this" to be undefined
```

**Comment by sokra** [comment]
This behavior is correct. `this` is `undefined` in ESM. See spec.

**Comment by montogeek** [comment]
@uribro Change `modules` to `commonjs` https://babeljs.io/docs/en/babel-preset-env/#modules

**Comment by uribro** [comment]
@montogeek tried to change to 

  `presets: [['env', {"modules": "commonjs"}]]`

and 

  `presets: [['env', {"modules": "umd"}]]`

Still I have the same issue

**Comment by atlanteh** [comment]
@montogeek I just upgraded my webpack, and it happens to me as well.. Tried going according to the advices you guys gave, but nothing seems to work.

**Comment by akshaynaik404** [comment]
@sokra Any ideas on how I can make this work with webpack 4. I am hearing about ESM for the first time here.
This is happening at runtime, so impact is very large as we have deployed webpack 4 to production. 
Manually detecting and fixing the issue will take lot of time and will be a tedious task.

Thanks in advance.
