### ISSUE TITLE
WASM bundles fail when loaded via `file://` URLs

### ISSUE THREAD

**Issue by bspeice** [webpack/webpack#7918]
# Bug report

**What is the current behavior?**
Electron apps fail to load WASM code because WASM bundles served via `file` URL's aren't allowed to be loaded via `instantiateStreaming` (specifically because MIME `application/wasm` must be set.

**If the current behavior is a bug, please provide the steps to reproduce.**
No configuration is specifically necessary, but I've included a reproducing project at [this git repo](https://git.speice.io/bspeice/rust_electron). To run:

```
yarn install
./build.sh
yarn start
```

Running will require a recent Rust nightly build, but I'm happy to add the bundle files if necessary to skip that step.

**What is the expected behavior?**
Webpack would detect that file URLs are not eligible for inclusion via `instantiateStreaming` and prioritize filling the `arrayBuffer` and `instantiate`ing that instead.

Please note that I can specifically reproduce the *correct* behavior by snipping out the `else if(...) WebAssembly.instantiateStreaming` branch. I'm not sure what the right way of fixing this is, but I'm happy to work on a PR if someone can point me in the right direction.

**Other relevant information:**
webpack version:  4.16.5
Node.js version: 8.10
Operating System: Linux
Additional tools: Rust nightly

---

Alright, some updates after I spent more time looking at this: the actual URL request goes to "<hash>.wasm", so adding checks for "./" or "file://" don't fix this specific issue (though may not be a bad idea in general). Is this something that should potentially have a config value added instead, where we can disable streaming load?

**Comment by xtuc** [comment]
I think that's something that browser should change. `arrayBuffer` + `instantiate` too has many disadvantages.

I can try

**Comment by xtuc** [comment]
Btw here's some previous discussions: https://github.com/WebAssembly/design/issues/1200

**Comment by bspeice** [comment]
I'm admittedly totally unfamiliar with `fs` in node - my expectation is that you could load just fine, but you'd still have issues with the `instantiateStreaming` support. Some people I've talked with recommended effectively spinning up a static file server in-process to load the resource bundles (with appropriate MIME types) but this strikes me as a bit strange - I don't particularly want to host a server inside the electron app.

**Comment by schmidtk** [comment]
Emscripten's boilerplate to load WebAssembly modules handles this situation with a [graceful fallback](https://github.com/kripken/emscripten/blob/8914c5cd5e4ac35a806430e8c77c88cd8c65b234/src/preamble.js#L2295) to ArrayBuffer instantiation. A similar approach could be [applied here](https://github.com/webpack/webpack/blob/a4e5f63d9d370b191bb9586570bc22bf2947e390/lib/wasm/WasmMainTemplatePlugin.js#L273) in webpack.

I tested this solution in the webpack output and it solved my problem in Electron. If anyone with more (any) webpack contribution experience would like to fix this via PR I would be forever grateful, otherwise I may be able to make time to take a crack at it.

**Comment by sokra** [comment]
Yep send a PR

**Comment by xtuc** [comment]
Thanks @bspeice for the PR.

Maybe we can override `window.fetch` to throw an error only the first call, so the fallback will still work.

**Comment by bspeice** [comment]
Apologies for not responding - I'm not a JS developer so would have no idea how to safely apply an override like that. If everyone's committed to that path, I'd need some help.

**Comment by evilebottnawi** [comment]
bump

**Comment by evilebottnawi** [comment]
bump

**Comment by vankop** [comment]
`file://path/some.wasm` should work.

Feel free to create issue with bug if does not work.

**Comment by bspeice** [comment]
Can confirm, everything does seem to be fixed in webpack 5.

**Comment by evilebottnawi** [comment]
@bspeice thanks!

**Comment by bspeice** [comment]
One quick clarification after I did some further testing: while Webpack 5 _does_ contain fixes needed to load WASM blobs asynchronously, it doesn't change the underlying issue (`Content-Type` unset for `file://` URLs). I'm having issues trying to find when this was changed in Chrome (and thus Electron as well), but when using `window.fetch('file://*.wasm')`, the `Content-Type` now comes back as `application/wasm`.

**Comment by evilebottnawi** [comment]
@bspeice Can you open a new issue with reproducible steps?

**Comment by bspeice** [comment]
@evilebottnawi: no need for a new issue. My intention was to clarify that the underlying issue was Chrome-related, and thus not something webpack could fix. The combination of browser and webpack changes that have come since this issue was opened make it so that everything works correctly. No further work needed, thanks all for the assistance.
