### ISSUE TITLE
webpackPreload not working at all

### ISSUE THREAD

**Issue by mwanago** [webpack/webpack#7920]
**What is the current behavior?**
I am experiencing issues while using `webpackPreload`.
No script with `rel="preload"` is added to the `<head>`.

**Steps to reproduce**
```
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  mode: 'none',
  plugins: [
      new HtmlWebpackPlugin({template: './src/index.html'}),
  ]
};
```
```
export function divide(a, b) {
    return a / b;
}
```
```
document.addEventListener("DOMContentLoaded", () => {
    const button = document.querySelector('#divideButton');
    button.addEventListener('click', () => {
        import(
            `./utilities/divide`
            /* webpackPreload: true */
            /* webpackChunkName: "utilities" */
            )
            .then(divideModule => {
                console.log(divideModule.divide(6, 3)); // 2
            })
    });
});
```
```
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <button id="divideButton">Click</button>
    </body>
</html>
```
I am using `webpack@4.16.5`.

**What is the expected behavior?**
I expect the `<link rel="preload" as="script" href="utilities.js">` to be added.

**Other relevant information:**
webpack version:  4.16.5
Node.js version: 8.11.3
Operating System: Ubuntu 18.04

**Comment by sokra** [comment]
I think this is not yet supported by the html-plugin. You could file an issue there.

Anyway using preload in your example is incorrect. It should use prefetch instead.

Note that prefetch doesn't require html-plugin support and should work.

**Comment by mwanago** [comment]
@sokra The docs do not mention the need to use html-plugin for preload.
Prefetch is working without problems.
https://webpack.js.org/guides/code-splitting/#prefetching-preloading-modules

**Comment by sokra** [comment]
That's true. It's mentioned here: https://medium.com/webpack/link-rel-prefetch-preload-in-webpack-51a52358f84c in the FAQ

Please send a PR to the docs adding it.

**Comment by mwanago** [comment]
@sokra "When prefetch/preload is used in import()s in a entry chunk the html generation is resposible for adding the <link> tags to the HTML. "
The prefetch works without problems for me though. Is it connected to that PR?
https://github.com/webpack/webpack/pull/7444

**Comment by sokra** [comment]
> Is it connected to that PR?

Yes. This PR allows to use prefetch without need to generate `<link>` tags in the HTML. It will be injected by the js bundle instead. This is possible because prefetching starts after the initial load. Preloading starts in parallel to the js bundle, so this is not possible for preload.

**Comment by mwanago** [comment]
@sokra I understand. I will work on a PR to the docs. Thanks ;)

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack.js.org

> @sokra The docs do not mention the need to use html-plugin for preload.
> Prefetch is working without problems.
> https://webpack.js.org/guides/code-splitting/#prefetching-preloading-modules

> That's true. It's mentioned here: https://medium.com/webpack/link-rel-prefetch-preload-in-webpack-51a52358f84c in the FAQ
> 
> Please send a PR to the docs adding it.
