### ISSUE TITLE
Source maps aren't added to .mjs output files

### ISSUE THREAD

**Issue by philipwalton** [webpack/webpack#7927]
# Bug report

**What is the current behavior?**

Source maps don't get added when defining an output file with an `mjs` extension. If I change nothing about my config except for the output extension from `mjs` to `js`, it works as expected.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here's a minimal repo:

**`webpack.config.js`:**

```js
const webpack = require("webpack");
const path = require('path');

module.exports = {
  mode: 'development',
  entry: {
    main: "./main.mjs"
  },
  output: {
    path: path.resolve(__dirname),
    filename: "[name].[chunkhash].mjs",
  },
  devtool: '#source-map',
};
```

**`main.mjs`:**

```js
console.log('Hello World');
```

**Other relevant information:**
webpack version:  4.17.0
Node.js version: 10.8
Operating System: MacOS 10.13.6
Additional tools: N/A

**Comment by montogeek** [comment]
Not sure this is even supported.

**Comment by montogeek** [comment]
Which source map options have you tried?

**Comment by mathiasbynens** [comment]
`.mjs` is supported *by default* elsewhere in webpack. I think applying the same logic (if `*.js` or `*.mjs` → generate source maps) would make sense here.

**Comment by philipwalton** [comment]
In my example I show that I'm using the option `devtool: '#source-map'`.

And I agree with @mathiasbynens, Webpack claims in many places that it supports `.mjs`, and it's able to process the file correctly. The only thing it's not doing is generating the source map and appending a reference to it in the original file.

**Comment by philipwalton** [comment]
Filed https://github.com/webpack/webpack/pull/7947.
