### ISSUE TITLE
providedExports: true in 4.17.0 breaks project that worked in 4.16.5

### ISSUE THREAD

**Issue by Pajn** [webpack/webpack#7930]
# Bug report

**What is the current behavior?**
In 4.17.0 the production build breaks on a project build correctly with 4.16.5.
I have narrowed it down to the `providedExports` setting as setting that to `false` will fix the build again. The error seems to be caused by either a missing or a incorrectly named export from `apollo-link` as `apollo-link-dedup` imports `ApolloLink` from `apollo-link` (in the build compied to `a`) but only `b` and `d` exist on the exported object from `apollo-link`.

**If the current behavior is a bug, please provide the steps to reproduce.**
See the repo at https://github.com/Pajn/webpack-bug/tree/master

The bug only seems to be present if I import both 'apollo-link-error' and 'apollo-link-ws'. If I remove either of those imports, the page did work.

The webpack config is still far from minimal, but I didn't think that detracted from displaying the bug. If you think otherwise, please tell and I can try to clean it up. The application is however the most minimal example I could manage.

**What is the expected behavior?**
A non-broken build 😄 

**Other relevant information:**
webpack version:  5.17.0
Node.js version: 8.11.3
Operating System: OSX 10.13.6
Additional tools: Babel 7.0.0-rc.1

**Comment by stnwk** [comment]
I can confirm this behaviour, happens to me too exactly as described by @Pajn

**Comment by zyy7259** [comment]
Same problem here.

It seems that it only occurred under certain import/export usage. In my case, I re-export another lib, then import from the re-export, that’s where things go wrong.

The lib I use is an internally lib, so it’s hard to re-produce without it.

I tried to set up a minimal project to re-produce this problem but failed. Glad you did it. @Pajn

**Comment by dotansimha** [comment]
same here :(

**Comment by sokra** [comment]
fix is on the way...

**Comment by sokra** [comment]
Try v4.17.1
