### ISSUE TITLE
splitChunks can't split common chunk

### ISSUE THREAD

**Issue by yangguansen** [webpack/webpack#7936]
# Bug report

splitChunks can't split common chunk

**What is the current behavior?**

the split rules:
```
optimization: {
        splitChunks: {
            cacheGroups: {
                commons: {
                    test: /\.js$/,
                    name: 'commons',
                    chunks: 'all',
                    minChunks: 3,
                    minSize: 0
                },
                vendors: {
                    test: /[\\/]node_modules[\\/]/,
                    name: 'vendors',
                    chunks: 'all'
                }
            }
        }
    }
``` 

**If the current behavior is a bug, please provide the steps to reproduce.**
I make a demo, there are four chunks, they are `componentOne` ,`componentTwo`, `componentThree`, `common`, both of `component*` import `common`, I want to split `common` in a alone file. But it still split in main.js

**What is the expected behavior?**
the `common` chunk can be splited in a alone file

**Other relevant information:**
webpack version:  4.16.3
Node.js version: 8.11.2
Operating System: windows10
Additional tools: none

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by yangguansen** [comment]
This is demo address: https://github.com/yangguansen/react-cli/tree/dev
*How to get the problem*
- git clone the repository
- npm install
- npm run build

The problem is that there isn't common.js in `dist/js` directory. But the split rules is set split `common` module to a alone file which named `commons.js`

If you have some advice to me, hope your guide, thanks.

**Comment by yangguansen** [comment]
`import ... from ...`doesn't means a chunk?
Could u pls explain the difference between `import()` with `import ... from ...` or anywhere about that?
Thanks

**Comment by yangguansen** [comment]
Or if I want to split common component in a alone file, which API in webpack could achieve that?

**Comment by montogeek** [comment]
Please see https://webpack.js.org/guides/code-splitting/#dynamic-imports

**Comment by yangguansen** [comment]
Got it, thanks
