### ISSUE TITLE
Harmony export in bundle breaks ESLint `no-use-before-define` rule

### ISSUE THREAD

**Issue by kstratis** [webpack/webpack#7937]
**Do you want to request a *feature* or report a *bug*?**

It may be a bug or a future bug source. Not sure yet.

**What is the current behavior?**

Everything works as expected.

**If the current behavior is a bug, please provide the steps to reproduce.**

It's not a bug, but you can reproduce it using the snippet below or just by exporting something from within a javascript module.

**What is the expected behavior?**

Everything works as expected but this can produce bugs in the future. Even though it's not syntactically 'illegal' it's considered bad practise unless there is a good reason for that. ESLint supports my view with [this rule](https://eslint.org/docs/rules/no-use-before-define).

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Chrome v68
node v10
webpack v4.17.0
macOS

---

For the following sample snippet:

```javascript
const top = document.createElement("div");
top.innerText = "This is the top";
top.style = red;

export { top };
```

Webpack produces the following chunk:

```javascript
// ...

"use strict";
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, "top", function() { return top; });

// ...

const top = document.createElement("div");
top.innerText = "This is the top";
top.style = red;
```

Even though it works because [JavaScript allows variables to be declared after they are used](https://medium.com/@bluepnume/theres-no-need-to-define-all-javascript-vars-once-at-the-top-of-a-function-and-there-hasn-t-been-a66b31f21822), the way `top` is exported breaks the `no-use-before-define` [ESLint](https://eslint.org/docs/rules/no-use-before-define) rule. 

Is there a particular reason for placing module exports at the top instead of at the bottom of the file?

**EDIT**: I have already asked the same question on [StackOverflow](https://stackoverflow.com/questions/51978704/order-of-exports-in-webpack-bundle) but the response I got was along the lines: "It's perfectly valid since the export is guaranteed to not be used before `top` is defined."

However it doesn't justify why webpack does it. Why not use best practises and place the export at the bottom instead?

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

**Comment by montogeek** [comment]
Also, Why are you using ESLint in a minified/bundled file? That is not a good practice and also ESLint was created to lint JS source code, not production code.

**Comment by kstratis** [comment]
I am updating the template as we speak... my apologies...

**Comment by kstratis** [comment]
@montogeek I have fully updated the issue.

**Comment by kstratis** [comment]
Thanks for the prompt response @sokra.

Could you possibly give me (or point me to) a small example that would demonstrate how exporting from a module this way handles circular dependancies that would otherwise pose a problem?

Also, what spec are you referring to?

**Comment by montogeek** [comment]
ESM Spec: https://www.ecma-international.org/publications/standards/Ecma-262.htm

**Comment by kstratis** [comment]
The spec is chaotic at best but thanks.

> This way TDZ and functions are correctly exported from the module when using circular dependencies.

**Why** and **how**? Please point me to something that demonstrates what you say.

**Comment by sokra** [comment]
``` js
// entry.js
import "./module";

export const value = 42;
export function fn() {
  return 42;
}
```

``` js
import { value, fn } from "./entry.js";

console.log(fn()); // should log 42

try {
  console.log(value); // should throw a TDZ error
  console.log("Broken");
} catch(e) {
  console.log("Works correctly");
}
```

When exporting `fn` or `value` after the location it's being defined, these two cases would behave incorrectly.

**Comment by kstratis** [comment]
That's great @sokra! 
Thank you for spending time on this.

For future readers, allow me to elaborate a bit cause it took me a while to figure out what exactly @sokra meant.

After some experimentation and skimming through some [StackOverflow posts](https://stackoverflow.com/a/42704874/178728)
I finally realised (not that you didn't warn me) that **harmony exports** are hoisted by default.

So I ran your examples through babel and that's the result I got back:

```javascript
// entry.js (after babel)
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.value = undefined;
exports.fn = fn;

require("./module.js");

const value = exports.value = 42;
function fn() {
  return 42;
}
```
```javascript
// module.js (after babel)
"use strict";

var _entry = require("./entry.js");

try {
  console.log((0, _entry.fn)()); // should log 42
  console.log("Works correctly");
} catch (e) {
  console.log("Broken " + e);
}

try {
  console.log(_entry.value); // should throw a TDZ error
  console.log("Broken");
} catch (e) {
  console.log("Works correctly");
}
```

the produced files totally make sense if the expected result is this:

    (1) 42
    (2) Works correctly
    (3) undefined
    (4) Broken

**Justification**: Lines (1) and (2) totally make sense since functions are hoisted and so are harmony exports therefore by the time `fn` is required it will already be defined and print 42. 
However lines (3) and (4) are not totally in line with @sokra's "good case" since by using `const` we should have fallen in a TDZ, get a `ReferenceError` and catch it by printing out a second "Works correctly". Instead we get `undefined` and `Broken`. 

The reason for this (I think) is because we are not operating in a pure ES6 environment but we are **using babel** instead. If you take a look at the babel generated `module.js` code you'll notice that `exports.value` is assigned `undefined` at the top which justifies the `undefined` result of this line `console.log(_entry.value);` in `module.js`. Therefore @sokra is correct that it's a TDZ but since we are using babel we get undefined (and consequently the next line which just prints `Broken`).

The "bad case" @sokra refers to, hypothetically transfers the exports at the bottom of the babel generated files after the variable and the function declaration (and thus complying with the `no-use-before-define` ESLint rule). This way however the functions wouldn't be exported by the time they would be required (used) by `module.js` which would justify the `Broken undefined is not a function` line and then `undefined` and `Broken` would totally make sense since nothing would be exported for `value` which would make it undefined.

That's about it. It's a long read but I believe it definitely worths it. 
Please correct me if my reasoning is wrong otherwise let me know and I'll close the issue.

**Comment by sokra** [comment]
> Is there any way at all to make export const value = 42; actually print 42 in module.js using circular dependancies?

``` js
// module.js
import { value, fn } from "./entry.js";

try {
  console.log(fn()); // should log 42
  console.log("Works correctly");
} catch(e) {
  console.log("Broken " + e);
}

try {
  console.log(value); // should throw a TDZ error
  console.log("Broken");
} catch(e) {
  console.log("Works correctly");
}

Promise.resolve().then(() => {
  try {
    console.log(value); // should log 42
    console.log("Works correctly");
  } catch(e) {
    console.log("Broken " + e);
  }
});
