### ISSUE TITLE
output.devtoolNamespace not getting the correct automatic value

### ISSUE THREAD

**Issue by Moghul** [webpack/webpack#7939]
# Bug report

**What is the current behavior?**
Currently, if you are building multiple libraries in the same webpack file (via the multiple entries functionality), the `sourceURLs` in these bundles seem broken.

`//# sourceURL=webpack://%5Bname%5D/./path/to/my/node_modules/loggly-jslogger/dist/loggly.tracker-2.2.2.min.js?`

**If the current behavior is a bug, please provide the steps to reproduce.**
This is a sample of the entry and output setups that create this issue.

```
    entry: {
        Preview: [
            vendor + 'loggly-jslogger/dist/loggly.tracker-2.2.2.min.js',
            utilities + 'setup.preview.js'
        ],
        Signup: [
            vendor + 'loggly-jslogger/dist/loggly.tracker-2.2.2.min.js',
            utilities + 'setup.signup.js'
        ]
    },
    output: {
        path: destinationDirectory,
        filename: '[name].bundle.[contenthash].js',
        libraryTarget: 'var',
        library: '[name]'
    },
```

This bug is "fixable" by setting a value to [output.devtoolNamespace](https://webpack.js.org/configuration/output/#output-devtoolnamespace) like:

```
    output: {
        path: destinationDirectory,
        filename: '[name].bundle.[contenthash].js',
        libraryTarget: 'var',
        devtoolNamespace: 'whateverYouWantGoesHere',
        library: '[name]'
    },
```

and your sourceURLs will become

`webpack://whateverYouWantGoesHere/./path/to/my/node_modules/loggly-jslogger/dist/loggly.tracker-2.2.2.min.js`

This seems to be caused by the fact that, as per documentation, 'output.devtoolNamespace' takes the value of 'output.library' by default.

**What is the expected behavior?**

I expect that 'output.devtoolNamespace' would take the entry's name just like the file name and libraries do.

**Other relevant information:**
webpack version:  4.16.5
Node.js version: 10.1.0
Operating System: Ubuntu 16.04
Additional tools:

EDIT: This also happens with single libraries being built if you use `output.library : [name]`

**Comment by Moghul** [comment]
Looks like this is about to be closed, but obviously, I don't think the problem is solved, so I'm making a comment to keep it alive.

**Comment by vankop** [comment]
fixed in main branch https://github.com/webpack/webpack/pull/15002
