### ISSUE TITLE
Webpack fails with many errors when you use a variable as path in require

### ISSUE THREAD

**Issue by thestonefox** [webpack/webpack#794]
When requiring a file like this

```
var mypath = "./files/";
var myfile = "file.js";
require(mypath + myfile)
```

I get loads of errors, but this works:

```
require('./files/' + myfile)
```

I'm guessing because webpack tries to parse a string and expects the string for the path to be hard-coded and not to evaluate a variable?

It makes it quite restrictive though IMOH

**Comment by sokra** [comment]
webpack need to figure out dependencies statically. You propably can refactor your code to use static dependencies. (ES6 modules disallow dynamic dependencies anyway)

see also http://webpack.github.io/docs/context.html

**Comment by thestonefox** [comment]
I did refactor to provide static paths in the end (which is cleaner and less magic anyway).

at least I know you can only pass through the file name as a variable in webpack now and that directories are statically parsed. Thanks for the info
