### ISSUE TITLE
Module not found: Error: Can't resolve 'hello.boudle.js'

### ISSUE THREAD

**Issue by horizon188** [webpack/webpack#7940]
打包的时候报错了，请问怎么解决
D:\HBuilder Folder 2\imoo\webpack-test>webpack hello.js hello.boudle.js
Hash: dcbb5281ebd9bca81449
Version: webpack 4.17.1
Time: 318ms
Built at: 2018-08-23 17:24:18
 1 asset
Entrypoint main = main.js
[0] multi ./hello.js hello.boudle.js 40 bytes {0} [built]
[1] ./hello.js 36 bytes {0} [built]

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in multi ./hello.js hello.boudle.js
Module not found: Error: Can't resolve 'hello.boudle.js' in 'D:\HBuilder Folder 2\imoo\webpack-test'
 @ multi ./hello.js hello.boudle.js main[1]

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
