### ISSUE TITLE
Module.rule.sideEffects not properly supported

### ISSUE THREAD

**Issue by iambalaam** [webpack/webpack#7944]
# Bug report
module.rule.sideEffects does not support an array of paths
[The documentation](https://webpack.js.org/configuration/module/#rule-sideeffects) says `sideEffects` should be `false | an array of paths`

**What is the current behavior?**
When using a rule like
``` js
{
    test: /\.tsx?$/,
    use: [{
        loader: 'ts-loader',
    }],
    sideEffects: ['./src/index.tsx']
}
```
Webpack outputs:
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[0].sideEffects should be a boolean.
   -> Flags a module as with or without side effects
```
**If the current behavior is a bug, please provide the steps to reproduce.**
Add `sideEffects: false` to a rule *note this works*.  
Change to `sideEffects: ['./some/path/to/file.js']` and see schema violation.

**What is the expected behavior?**
To avoid tree-shaking side effects from given paths

**Other relevant information:**
webpack version:  4.16.5
Node.js version: 10.9.0
Operating System: MacOS
Additional tools:

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack.js.org

The documentation is incorrect here. Only true or false are allowed. One can do fine matching via `test`.
