### ISSUE TITLE
Integrated UglifyJS minification generates unnecessarily large files

### ISSUE THREAD

**Issue by manuelkiessling** [webpack/webpack#7946]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

In mode *production* without any explicit UglifyJSPlugin setup, a JS file is generated which is 4.7x the size of a file that is generated when explicitly setting up UglifyJSPlugin in the Webpack config.

**If the current behavior is a bug, please provide the steps to reproduce.**

- `git clone https://github.com/manuelkiessling/nodebeginner.org.git`
- `cd nodebeginner.org`
- `git checkout 32193eb9d8d290678ec67449b9fcf27dd9cb5a77`
- `cd code/playground`
- `npm install`
- `npm run build-frontend`
- `ls -lah dist/*.js`
- Realize that the resulting file has a size of 677 KiB
- `git checkout dee91b0816893efcdb28c8f065f2ee249e66ca51`
- `npm run build-frontend`
- `ls -lah dist/*.js`
- Realize that the resulting file now has a size of only 142 KiB

**What is the expected behavior?**

Reading that UglifyJS minification is integrated and applied per default in Webpack 4, I expected Webpack to reduce at least nearly-as-small-as-possible JS files without additional configuration.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

- Node v10.6.0
- Webpack 4.16.5
- macOS 10.13.6

**Comment by sokra** [comment]
Please try without `devtool: "inline-source-map"` since this way you also compare the size of the source map. Use `devtool: "source-map"` or `devtool: false`

**Comment by manuelkiessling** [comment]
Looks good, with `devtool: "source-map"` it's down to 144 KiB. Thank you very much!
