### ISSUE TITLE
Target for "electron-renderer" shouldn't have `browser` in `resolve.mainFields`

### ISSUE THREAD

**Issue by cxa** [webpack/webpack#7953]
# Bug report

**What is the current behavior?**

Issue #6811 assumption is wrong. Electron renderer is not only a browser, it utilities the node power.

> Each web page in Electron runs in its own process, which is called the renderer process.
> In normal browsers, web pages usually run in a sandboxed environment and are not allowed access to native resources. Electron users, however, have the power to use Node.js APIs in web pages allowing lower level operating system interactions.
> https://electronjs.org/docs/tutorial/application-architecture

 When target browser, you'll lose all the node power. 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

The pr to the issue #6811 should be reverted.

**Other relevant information:**
webpack version:  4.16.5

**Comment by sokra** [comment]
cc @sindresorhus

**Comment by sindresorhus** [comment]
@cxa Can you provide a real-world example of when this is problematic?

**Comment by sindresorhus** [comment]
Yes, you can use Node.js in the renderer too, but if I import a module that works in both Node.js and the browser, I would personally prefer the browser version which uses browser APIs.

**Comment by cxa** [comment]
We need some node power for some cases, the browser part is not power enough. So maybe add some configure-able options is the solution.

**Comment by 2Pacalypse-** [comment]
Another real-world example where this is a problem:
- engine.io-client library uses `browser` field to load the browser version of XMLHttpRequest - https://github.com/socketio/engine.io-client/blob/master/package.json#L73
- the node version is much more appropriate in Electron apps, as it has some extra functionality not allowed in browsers

But even conceptually, it doesn't make much sense to me to treat Electron as *just* a browser. If that were true, why does webpack itself has a special target for `electron-renderer`?

**Comment by mingyuan-xia** [comment]
Another problematic example is with [axios](https://github.com/axios/axios), an HTTP client that supports both browser (XHR) and node (http). It problems two backends and it is quite common to use both in an Electron renderer (XHR for regular GETs and node API for streaming support). Yet, it has a `browser` field in its `package.json` and when packed with webpack, the node backend is discarded...
We have to manually vendorize its node backend to workaround.

**Comment by elyulka** [comment]
Webtorrent is affected too: webtorrent/webtorrent#1597

**Comment by DrSensor** [comment]
I think this issue needs special attention and test out how it works with nodejs to browser polyfill.

**Comment by justintaddei** [comment]
This also breaks the `ws` WebSocket package.

**Comment by mx2323** [comment]
any update on a fix for this?

**Comment by esperantic** [comment]
Our application in renderer process uses a lot of node.js features.
With new version of the webpack we cannot do this.

**Comment by esperantic** [comment]
I found temporary solution for electron-renderer target :
![image](https://user-images.githubusercontent.com/13432379/66203038-f4aaa480-e6af-11e9-9a8e-260890616e7a.png)



CC: @cxa @DrSensor @mx2323

**Comment by zeevl** [comment]
https://github.com/webpack/webpack/issues/6796 . :(

Instead of using `electron-renderer`, use `target: 'node'` and include `electron` in externals.

**Comment by hammadzz** [comment]
I am still experiencing this issue using https://github.com/electron-react-boilerplate/electron-react-boilerplate

Adding mainFields doesn't work as it isn't being respected. From what I see this boilerplate doesn't use electron-renderer

**Comment by yinjun1991** [comment]
Another real-world example：
I use  `nedb` to store the user data into a local file.
nedb apply a browser version which store data into browser indexedDB instead of a local file.
So, the target 'electron-renderer' import the `browser` entry will cause the user data lost when user uninstall the app.

**Comment by pettyron** [comment]
> All this time wasted on troubleshooting, thousands of developers suffering because of one guy's preference. I've seen literally more than 20 issues being tracked and ignored because of this. Devs are using forks of popular libraries because there's no way to overcome this on mature projects. Whole point of Electron is having Node's powerful capabilities on a browser renderer, with or without `nodeIntegration`. Been in the open-source world for almost 2 decades and I thought community driven software was built on majority's opinion. Oh well. 🤷🏻‍♂️

If only give this statement a million thumbs up.

**Comment by m4heshd** [comment]
@pettyron Thank you for agreeing with my frustrated rant.

For anybody who's dealing with this hell of an issue, use the following webpack configuration. Not actually a solid workaround in my opinion but feel free to fiddle around and get the best out of it for your use case.

```js
{
    resolve: {
        aliasFields: []
    }
}
```
