### ISSUE TITLE
UglifyJsPlugin does not work when added manually, in optimization.minimizer

### ISSUE THREAD

**Issue by barbu110** [webpack/webpack#7957]
# Bug report

**What is the current behavior?**

When adding `minimize: true` to my Webpack config (as said [here](https://webpack.js.org/configuration/optimization/#optimization-minimize)), JavaScript is indeed minified, but when I add it manually, exactly as said [here](https://webpack.js.org/configuration/optimization/#optimization-minimizer), the output is not minified.

I set my `mode` to `none` so I can have complete control over what happens.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

It should allow me to configure the plugin, add it manually and minify the output JavaScript files.

**Other relevant information:**
webpack version:  4.17.1
Node.js version: v8.11.4
Operating System: macOS High Sierra

**Comment by evilebottnawi** [comment]
@barbu110 please provide you configuration here

**Comment by sokra** [comment]
`minimizers` is used when `minimize: true`
