### ISSUE TITLE
Babel not compiling vendors chuck

### ISSUE THREAD

**Issue by jousi592** [webpack/webpack#7959]
I migrated to Webpack 4 and set up everything according to the Docs, however, my `vendors.js `chuck is not getting compiled with Babel like the `main.js` chunk.

I have placed the vendors into the `optimization.splitChunks.cacheGroups` object, as the docs suggested, but didnt find a way to make these `"cacheGroups"` get compiled with babel.

My problem is that one of the libraries has a ES6 class and now IE11 isnt working due to this fact.

My webpack optimization object looks like:

```
optimization: {
    splitChunks: {
      cacheGroups: {
        styles: {
          name: 'styles',
          test: /\.css$/,
          chunks: 'all',
          enforce: true
        },
        vendor: {
          name: 'vendor',
          test: /[\\/]node_modules[\\/]/,
          chunks: 'all',
          enforce: true
        }
      }
    }
  }
```
Is there a way to force webpack to compile vendors with babel as well?

**Comment by sokra** [comment]
`optimization.splitChunks.cacheGroups` has nothing to do with transpiling. Check `module.rules`

**Comment by evilebottnawi** [comment]
Answer https://github.com/webpack/webpack/issues/7959#issuecomment-416198928
