### ISSUE TITLE
UglifyJsPlugin ruins images

### ISSUE THREAD

**Issue by ALF-er** [webpack/webpack#796]
Hello,
I'm trying simply build application with image used in css which used in js... But when I'm using production config build:
`webpack -p --colors`

I'm receiving error:
```
ERROR in ./src/img/cross.png
Module build failed: TypeError: Cannot read property 'length' of undefined
    at Object.module.exports (C:\dev\projects\wp_test\node_modules\url-loader\index.js:15:26)
 @ ./~/css-loader!./src/css/main.css 2:54-81
```

It's only happens when UglifyJsPlugin used (via --optimize-minimize option). If I run `webpack -d --colors` it builds without any errors.

For illustration I've created repository with simplest project: https://github.com/ALF-er/wp_test

What I'm doing wrong? =)

**Comment by jhnns** [comment]
You're additionally applying the image-loader in production. Given from [the README](https://github.com/tcoopman/image-webpack-loader), the image-loader *replaces* the url-loader. It should not be used in conjunction.

The image-loader doesn't return any content, thus `Cannot read property 'length' of undefined`.

**Comment by ALF-er** [comment]
Uh... Thanks! I thought that "url?limit=50000"-loader will process all images with size less than 50000 b. And then all others will be processed with "image-loader"... Thank you
