### ISSUE TITLE
automatically generate declarations for schema

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#7965]
If there is a tool that exists already (@sokra).

We should: 

* Read the JSON Schema for our Configuration Validation
* Convert it into Type Definition Files (for each plugin also)
* This can schema can be named `WebpackOptions` or something similar. 
* This is then to be tied to any place the configuration is tied (`this.options`).

NOTE: We need a tool that supports reading and converting AJV custom declarations to valid TS Declarations.

**Comment by montogeek** [comment]
What is a Type Definition File?

**Comment by michael-ciniawsky** [comment]
@montogeek `.d.ts` for TypeScript only containing the types of a `.ts` file

```
index.ts
index.d.ts (Type Definition File)
```

**Comment by montogeek** [comment]
That sounds like it already exists.

**Comment by evilebottnawi** [comment]
bump

**Comment by sokra** [comment]
This is fixed. We generate declarations from the schema now.
