### ISSUE TITLE
add development section of config

### ISSUE THREAD

**Issue by andykais** [webpack/webpack#7967]
## Feature request

**What is the expected behavior?**
webpack 4 has an `optimization` section of the config, where you can configure options specific to `--mode=production`. I would like to see a similar section for development mode. 

**What is motivation or use case for adding/changing the behavior?**
There is definite interest in combining development & production configs, and currently there is an issue discussing the best way to distinguish `development` mode from `production` mode in v4 (#6460). This will mean using less static configs and using more js logic inside the config object for those who want separate dev and prod behavior. The hope is that most of that logic can be pushed into the `optimization` (and perhaps `development`) fields.

**How should this be implemented in your opinion?**
the simplest solution would be to add a section
```javascript
// this name can change
development: {
  plugins: []
}
```
which can house anything useful to development in there. The `optimization` field is nice because it is simple, just showing common patterns that are needed for production builds. The `development` field could slowly progress to common dev patterns, e.g. 
- build caching
- exec after each build
- clear terminal

**Are you willing to work on this yourself?**
yes, with guidance

**Comment by evilebottnawi** [comment]
@andykais what about another env like `staging`, `testing` and etc?

**Comment by andykais** [comment]
true, those are also common build environments. Personally I just use a `development` build for testing and development, and a `production` build for staging and production. 

As a follow up to this FR, I suppose everything I mentioned here can be accomplished by separating your builds into different webpack files

```
webpack/
  webpack.config.base.js
  webpack.config.development.js
  webpack.config.production.js
  webpack.config.testing.js
  webpack.config.staging.js
```
however, what I really wanted to accomplish was to identify common build configurations for a development environment give them sensible defaults when the mode is `'development'`, just like how optimization works for `'production'`
