### ISSUE TITLE
Code splitting. Chunk path relative to the main.js file path, not to the hosting index.html path 

### ISSUE THREAD

**Issue by slava-lu** [webpack/webpack#7968]
## Feature request

**What is the expected behavior?**

I have a web page at http://domain/index.html. 
This web page downloads a main JS file from http://anotherDomain/main.056363.js
The chunk.js file will be downloaded from `domain` rather than from `anotherDomain` as main.js reads the current base url rather than the url its was downloaded from.

This prevents making libraries for third party use with code spiting. Ideally chunk files should be downloaded not from the current domain but from the domain the main file was downloaded from. 

**What is motivation or use case for adding/changing the behavior?**
Creating libraries for third party use. It can be achieved with absolute path, but it is not very convenient.

**How should this be implemented in your opinion?**
There should be a setting in webpack config that ask the main file  to somehow get the info about url it was downloaded from and use this url to search for chunk files.

**Are you willing to work on this yourself?**
Not sure i have enough skills.

**Comment by flyyang** [comment]
have you tried public path?  https://webpack.js.org/guides/public-path/

**Comment by slava-lu** [comment]
Public path itself is not what I need as I need to get the path at runtime rather than build time.  I found that you have something like `__webpack_public_path__` and a plugin https://github.com/agoldis/webpack-require-from but they are all hacks rather than  the clean solution to server all parts of the bundle from where you serve the main JS file.

**Comment by glen-84** [comment]
Does [this](https://github.com/webpack/webpack/issues/7077#issuecomment-383029585) help?

**Comment by slava-lu** [comment]
@glen-84 Yes it helps, thanks, but this solution does not come to mind easily. My point is that many developers will struggle before they come up to something like:
```const url = new URL(document.currentScript.src);
__webpack_public_path__ = (url.origin + __webpack_public_path__);
```
So as this is the feature request, not the issue I still recommend to introduce the parameter like `respectMainScriptPath` and if set to true add the above code to the bundle.

**Comment by slava-lu** [comment]
I have done more tests  of the proposed solution ( [this ](https://github.com/webpack/webpack/issues/7077#issuecomment-383029585)) and it is actually not that I want. 
The problem is that it relies on some _public path_, which is configured during the build time. So you cannot just take your script and copy it to a different server with different path structure. You will have to rebuild it. 
I have come up with different approach. It does not have this drawback but it requires that all files ( main and chunk) be placed in the **root build folder**. i.e. no path in file names in webpack config.
I believe it is much lesser evil than relying on the public path. 

So my solution is:
```
const url = new URL(document.currentScript.src);
const widgetLink = url.href.substring(0, url.href.lastIndexOf('/') + 1);
__webpack_public_path__ = widgetLink;
```

**Comment by ecrofeg** [comment]
> I have done more tests of the proposed solution ( [this ](https://github.com/webpack/webpack/issues/7077#issuecomment-383029585)) and it is actually not that I want.
> 
> The problem is that it relies on some _public path_, which is configured during the build time. So you cannot just take your script and copy it to a different server with different path structure. You will have to rebuild it.
> 
> I have come up with different approach. It does not have this drawback but it requires that all files ( main and chunk) be placed in the **root build folder** during build. i.e. no path in file names in webpack config. After that you can place built main and chuck everywhere in the world., just make sure they are placed in the same place. I believe it is much lesser evil than relying on the public path.
> 
> So my solution is:
> 
> ```
> const url = new URL(document.currentScript.src);
> const widgetLink = url.href.substring(0, url.href.lastIndexOf('/') + 1);
> __webpack_public_path__ = widgetLink;
> ```

Great tip, but keep in mind that IE11 does not support `currentScript` and it's quite a challenge to polyfill it.

**Comment by robchristian** [comment]
This is still an issue. Even just the ability to specify a different public path, like `chunksPath`, would be very helpful. We shouldn't assume that JS bundles will necessarily have the same base URL as other asset types, in all projects.

**Comment by shixiaobao17145** [comment]
set publicPath to be `auto` will make it work.   https://webpack.js.org/guides/public-path/#automatic-publicpath
