### ISSUE TITLE
How to make the whole gulp abort when webpack has an error?

### ISSUE THREAD

**Issue by binarykitchen** [webpack/webpack#797]
Hello guys

I have the gulp (pseudo)code below. But when an error occurs, i.E. a module couldn't be found due to a wrong path, then the error is shown on gulp BUT the gulp task continues.

What change is required to make the gulp task stop?

Thanks!

```js
var webpackCompiler = webpack({
     ...
  },
  plugins: _.compact([
    ...
});

gulp.task('webpack', function(cb) {
  return webpackCompiler.run(function(err, stats) {
    if (err) {
      throw new gutil.PluginError('webpack', err);
    }
    gutil.log("[webpack]", stats.toString({
      ...
    }));
    return cb();
  });
});
```

**Comment by sirlancelot** [comment]
Pass `err` in to `cb`

```javascript
gulp.task('webpack', function(cb) {
  return webpackCompiler.run(function(err, stats) {
    if (err) return cb(err);
    gutil.log("[webpack]", stats.toString({
      ...
    }));
    return cb();
  });
});
```

**Comment by binarykitchen** [comment]
Oh right, thanks man! You might want to add that to the documentation. Because I believe this is better behavior than `throw new gutil.PluginError('webpack', err);`?

**Comment by jhnns** [comment]
Go ahead, the documentation is editable for everyone :)

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#104
