### ISSUE TITLE
Can not use other module types(except es6 module) with tree shaking!

### ISSUE THREAD

**Issue by ccqgithub** [webpack/webpack#7971]
# Bug report
Ccommonjs modules stop whole project tree shaking!

**What is the current behavior?**

The babelrc:

```
["@babel/preset-env", {
      "modules": false,
      "targets": {
        "browsers": ["> 1%", "ie > 9"]
      },
      "useBuiltIns": "usage"
}]
```

When i use bebel-preset-env with webpack4,` require or import` a commonjs module(now many module have no esm)

```js
// a.js
module.exports = {};

// b.js
const a = require('./a'); // or import a from './a';
```

it throw the errors in the browser:

```
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
```

When i set the ` "modules": "commonjs"`, no error. but becaulse babel transform all the es6 module to commonjs, can get the `tree shakings`.

**If the current behavior is a bug, please provide the steps to reproduce.**

`module.exports` is read-only when `module:  false`, but is writable when `"modules": "commonjs"`.

If this is right, so can't use any other module types in the project when i want  use `tree shaking` ?

**What is the expected behavior?**

Can use `tree shaking` with `commonjs modules`.

maybe need to change the `module.exports` in `harmony-module.js` to`writable`?

```js
Object.defineProperty(module, "exports", {
    enumerable: true,
    writable: true
});
```

**Other relevant information:**
webpack version:  4.17.1
Node.js version: 8.9
Operating System: macos
Additional tools: bebel-preset-env, bebel7

**Comment by bplok20010** [comment]
same problem

webpack version: 4.17.1
Additional tools: bebel-preset-env, bebel7

**Comment by philipwalton** [comment]
Yes, same problem. And note that even if you *think* you're not using any commonjs module, you may be without realizing it if you're using the new `{useBuiltIns: "usage"}` feature of `babel-present-env` (new in Babel 7), which automatically adds `core-js` polyfills for you.

Since the `core-js` source is published as commonjs, you either can't use it or you have to transpile everything to commonjs.

/cc @hzoo in case this isn't on your radar.

**Comment by crloshro** [comment]
I have the same problem: 

> message.js:17 Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
>     at Module.eval (message.js:17)
>     at eval (message.js:51)
>     at Module../react/src/js/message.js (bundle.js:3999)
>     at __webpack_require__ (bundle.js:20)
>     at eval (index.js:6)
>     at Module../react/src/js/index.js (bundle.js:3975)
>     at __webpack_require__ (bundle.js:20)
>     at eval (index.js:2)
>     at Object.0 (bundle.js:4033)
>     at __webpack_require__ (bundle.js:20)

This is my webpack.config:

```
const path=require('path')
const ExtractTextPlugin=require('extract-text-webpack-plugin')
module.exports={
  mode:'development',
  entry:['babel-polyfill',path.resolve(__dirname,'src/js/index.js')],
  output:{
    path:path.resolve(__dirname,'dist'),
    filename:'bundle.js',
  },
  module:{
    rules:[
      {
        test:/\.m?js$/,
        exclude:/(node_modules|bower_components)/,
        use:{
          loader:'babel-loader',
          options:{
            presets: ['@babel/preset-env','@babel/preset-react']
          }
        }
      },
      {
        test:/\.(jpg|png|gif|woff|eot|ttf|svg)$/,
        use:{
          loader:'url-loader',
          options:{
            limit:1000000
          }
        }
      },
      {
        test:/\.css$/,
        use:ExtractTextPlugin.extract({
          use:"css-loader"
        }),
      }
    ]
  },
  plugins:[
    new ExtractTextPlugin("css/[name].css")
  ]
}

```I don't know how con I fix this bug 

Please need some help

**Comment by fvonellerts** [comment]
Here is how I fixed this problem:
```javascript
// webpack config, babel-loader options
presets: [
  ['@babel/preset-env', {
    useBuiltIns: 'entry'
  }]
]

// js entry file, first line
import '@babel/polyfill'
```
