### ISSUE TITLE
--watch don't work with git bash on Windows and files as list of entires

### ISSUE THREAD

**Issue by jcubic** [webpack/webpack#7972]
# Bug report

**What is the current behavior?**

running webpack --watch from git bash din't respond to file changes. the same happen running:

```
npm run webpack:watch
```

and

```
./node_modules/.bin/webpack --watch
```

the same running from cmd.exe works fine.

node builtin fs.watch works fine when I run example code in git bash, so the problem is in config and in webpack, not in git bash like in #2949

this code works (it also works for directories, but for unknown reason it execute twice):

```javascript
var fs = require('fs');
var fname = 'C:\\projects\\idaapp\\inst\\shiny\\www\\js\\ga.js';
fs.watch(fname, { encoding: 'buffer' }, (eventType, filename) => {
  if (filename) {
    console.log(filename);
  }
});
```

I've check the source code and found this project: [webpack/watchpack](https://github.com/webpack/watchpack)

this code works in git bash:

```javascript
var fname = 'C:\\projects\\idaapp\\inst\\shiny\\www\\js\\ga.js';

var Watchpack = require("watchpack");

var wp = new Watchpack({});

wp.watch([fname], [], Date.now() - 10000);

wp.on("change", function(filePath, mtime) {
    console.log(filePath);
});
```

and gives single console unlike fs.watch.

**If the current behavior is a bug, please provide the steps to reproduce.**

I think that the problem is list of entries instead of require or import in files with single entry point

```javascript
module.exports = {
  mode: 'production',
  entry: {
    'style': [
      path.resolve(__dirname, 'inst/shiny/www/css/analysisTab.css'),
      ..
   'other files': []
```

Here is my whole config file (sorry it's complicated, it's simple app with 4 files but webpack was giving me hard times and it was not working until it looks like this).
https://gist.github.com/jcubic/216e56027d5ad1010f47aae267ac3228

**What is the expected behavior?**

I expect that if I change one file that's inside entry then webpack will rebuild that entry when I run webpack --watch from git bash on Windows.

**Other relevant information:**
webpack version:  

    "webpack": "^4.17.1",
    "webpack-cli": "^3.1.0"

Node.js version: v10.9.0 installed using nvm from older version
Operating System: Windows 7
Additional tools: (package.json included in gist).

**Comment by jcubic** [comment]
Sorry for this issue, it seems that it work but there is longer delay then in cmd.exe

**Comment by CreativSpeed** [comment]
in your package.json add --watch-poll
``` json
"scripts": {
    "dev": "webpack -- --mode development --watch --watch-poll"
  },
```
