### ISSUE TITLE
System global rewriting

### ISSUE THREAD

**Issue by guybedford** [webpack/webpack#7974]
# Bug report

**What is the current behavior?**

I'm writing code with Webpack that uses the SystemJS `System` global. Webpack seems to rewrite the `System` reference to the global, stopping SystemJS from working in webpack code.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

It would be great if there was an easy way to opt-out of this behaviour, ideally with it disabled by default since there are no active specifications for `System` anymore.

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by sokra** [comment]
You can opt-out with:

``` js
{
  module: {
    rules: [
      { parser: { system: false } }
    ]
  }
}
```

btw. this is off by default in webpack 5

**Comment by guybedford** [comment]
Thanks Tobias, and great to know that it's off in Webpack 5. I've only just noticed https://github.com/erights/proposal-System-object since posting this, so perhaps the System global conflict will still happen yet :) Hard to predict the future :p

Will make a note of this in the SystemJS documentation.
