### ISSUE TITLE
Allow rules/Conditions to be included/excluded based on package.json contents

### ISSUE THREAD

**Issue by timneutkens** [webpack/webpack#7975]
## Feature request

Currently, webpack's resolver requires the package.json of every file that is imported (module). This data is however not exposed to the user through the configuration. So `module.rules` can't be configured based on for example a certain flag in package.json, or based on `engines`.

**What is the expected behavior?**

The `Condition` logic should allow for something like `package` or `packageJson` which gets the package.json contents passed in and works similar to `issuer`.

Another case for this is the `externals` configuration key, if a function is passed it should receive the package.json contents as a parameter.

**What is motivation or use case for adding/changing the behavior?**

In Next.js we want to transpile node_modules based on their usage in React components, but it might not be the best idea to run Babel over every possible `import`, for example when the user imports a gigantic library that doesn't need compilation at all). So we're investigating alternatives like providing a key in package.json of a module to opt-in to compilation using Babel.

**How should this be implemented in your opinion?**

As defined above in expected behavior. The naming can be better though 👍 

**Are you willing to work on this yourself?**
yes

**Comment by vankop** [comment]
implemented in https://github.com/webpack/webpack/releases/tag/v5.0.0-beta.23 
`add Rule.descriptionData to allow matching data from the package.json`

**Comment by timneutkens** [comment]
I saw, awesome work 🎉
