### ISSUE TITLE
Progress message showing many spaces

### ISSUE THREAD

**Issue by mengxk2018** [webpack/webpack#7979]
# Bug report

**What is the current behavior?**
Progress message showing weird: percent building modules message show many space. maybe issue due to nextMessage lineCaretPosition computed incorrect.

**If the current behavior is a bug, please provide the steps to reproduce.**
Env: win10+vscode + vue-cli (with latest version of webpack )
1: vue create myapp
2. npm install
3. npm run serve

**What is the expected behavior?**
Progress message should output with correctly line cart start postion.

**Other relevant information:**
webpack version:  4.17.1
Node.js version:  8.11.3
Operating System: Windows 10
Additional tools: vscode + vue-cli 3.0.1

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack/webpack/pull/7961

**Comment by mengxk2018** [comment]
Thanks very much, after I opend issue, i just note it is a duplication issue, apologies here, I just fixed it by using temp solution on my project:
line 26:  node_modules/webpack/lib/progressPlugin.js , change  `…${detail to `...${detail
