### ISSUE TITLE
Console.log can not print any information when writing custom loader.

### ISSUE THREAD

**Issue by zxc0254** [webpack/webpack#7980]
Console.log can not print any information when writing custom loader.
![1](https://user-images.githubusercontent.com/13687817/44951710-e6cb9400-ae9d-11e8-91f3-680d38cfb834.png)
![2](https://user-images.githubusercontent.com/13687817/44951713-05318f80-ae9e-11e8-9412-3313c7e27833.png)

**Comment by michael-ciniawsky** [comment]
Remove the include in the `wtemplate` rule, and 

```diff
{
  test: /\.wtemplate$/,
  use: {
+   { loader: path.resolve(__dirname, 'path/to/wesearch-loader/src/') }  
  }
- include: [ path.resolve(__dirname, 'node_modules/wsearch-loader') ]
}
```
