### ISSUE TITLE
Entry bundles are not generated with single runtimeChunk option

### ISSUE THREAD

**Issue by Rody-Kirwan** [webpack/webpack#7982]
# Bug report

**What is the current behavior?**
On webpack 4.17 when I add a single runtime option to my config `runtimeChunk: { name: shared }` my entry bundles are not generated. 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I may be mistaken but my understanding of adding the single runtime option would extract the runtime code from each entry point into a single runtime chunk but leave the necessary module-exports within each entry bundle.

The issue I am currently experiencing is that splitChunks is creating multiple instances of my store for each entry point (The store we are using is extremely old and outdated, but that is out of my control ATM).

Without a single runtime option,  runtime code is being added to each entry point which executes the same module multiple times - I succeeded in recreating the issue in a sandboxed environment and when I added a single runtimeChunk to my config this extracted the runtime code into a single file and resolved my issue - however when I applied this to my application - a runtime file WAS created, but my entry bundles were not. 

here is my optimization config:
```
optimization: {
  splitChunks: {
    cacheGroups: {
      commons: {
        name: 'commons',
        filename: "js/[name].js",
        test: /\.js(x)?$/,
        chunks: "initial",
        minChunks: 1
      }
    }
  },
  runtimeChunk: {
    name: 'shared',
  },
},
```

**Other relevant information:**
webpack version:  4.17
Node.js version: 8.9
Operating System: OSX
Additional tools:

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by Rody-Kirwan** [comment]
Hi @sokra, 

On further inspection the issue seems to be caused by an inconsistency when using `runtimeChunk` with `output.filename` I recreated the scenario and steps to reproduce here:
https://github.com/Rody-Kirwan/webpack-single-runtime/blob/master/README.md

**Comment by Rody-Kirwan** [comment]
Would really appreciate an update on this as it's blocking our upgrade

**Comment by sokra** [comment]
`output.filename` is only used for chunks with runtime. All other chunks use `output.chunkFilename`. This is going to change with webpack 5, but that's the current state with webpack 4.

Your files are not missing, they just have another name. Best read the final filenames for the entries from the stats, as they are included there.

**Comment by Rody-Kirwan** [comment]
@sokra Hmm - Okay that solves that issue but it causes some difficulty when using chunkhash right?
`'js/[id]-[name].[chunkhash].js'`
Would it be possible to create a PR where chunkFilename accepts a function - something like
```
chunkFilename: (chunk) => (chunk.name === 'entry' ? 'js/[name].js : 'js/[id]-[name].[chunkhash].js')

```

**Comment by sokra** [comment]
No it's not possible to make chunkFilename a function (it need to generated at runtime).

> Okay that solves that issue but it causes some difficulty when using chunkhash right?

When using chunkhash you should also use chunkhash in `output.filename` so it's not more difficult than doing it correctly.

Read the final filenames from the stats.

**Comment by Rody-Kirwan** [comment]
Sorry, I'm not sure I understand how this will work. Our index.html is server-side rendered as the inclusion of certain entry scripts is dependant on environment-specific configs. The src url of these files needs to be predetermined. i.e. - without knowing the hash of each chunk created during a build.

**Comment by sokra** [comment]
> The src url of these files needs to be predetermined. i.e. - without knowing the hash of each chunk created during a build.

You should reconsider this. Otherwise you can't call it Long Term Caching. Filenames need to have hashes in their filenames.

You can get the filenames from stats.

**Comment by Rody-Kirwan** [comment]
Okay, thank you. Unfortunately I'm not sure we're in a position to change this at the moment.
If you can think of any "dirty" workaround using WP that would be great. Otherwise you can close this.
I appreciate the help.

**Comment by sokra** [comment]
In a plugin you can set the `filenameTemplate` property of chunks to override the filename. You can do this on all chunks referenced by compilation.entrypoints

**Comment by Rody-Kirwan** [comment]
Excellent. Thank you very much @sokra.
I found this https://www.npmjs.com/package/webpack-chunk-rename-plugin
Seems to do the trick

**Comment by sokra** [comment]
Great it does exactly this.
