### ISSUE TITLE
contenthash changing even though file remains identical

### ISSUE THREAD

**Issue by rightaway** [webpack/webpack#7984]
# Bug report

```js
	output: {
		filename: 'file-[contenthash].js',
		chunkFilename: 'chunk-[contenthash].js'
	},
        optimization: {
        	splitChunks: {
		chunks: 'all',
		cacheGroups: {
				vendors: {
					test: /[\\/]node_modules[\\/]/,
				},
			},
		},
       }
```

**What is the current behavior?**

If I have the above config, in my build I get a file called `file-XXX.js` and `chunk-XXX.js`. If I change the config line from `chunkFilename: 'chunk-[contenthash].js'` to `chunkFilename: 'CHUNK-[contenthash].js'`, then the files are `file-YYY.js` and `chunk-XXX.js`. So `chunk-` has the same name but `file-` has a different name when the `chunkFilename` changes.

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a webpack bundle when the chunkFilename is set to one value, then create another bundle after changing the chunkFilename. You'll see the the contenthash has changed even though the file contents are identical.

**What is the expected behavior?**

I'm using `[contenthash]` and in both cases the file contents are identical so the contenthash shouldn't change and the filename should remain the same.

**Other relevant information:**
webpack version:  4.17.1
Node.js version: 10.9.0
Operating System: linux 
Additional tools:

**Comment by sokra** [comment]
Is this causing any problems?

**Comment by rightaway** [comment]
Also it is unexpected and unintuitive behavior, as it would be reasonable to expect that a `contenthash` value is based only on the file contents and nothing more, so contenthash should change only when the file contents have changed and not in situations like described above.

**Comment by michael-ciniawsky** [comment]
Ideally only the (rendered) asset's contents are contributing to `[contenthash]` since that's the only thing, which matters for browser caching in case everything else stays the same. chunkGroup/chunk/module graph and config changes should already be indirectly reflected by the resulting content changes to an particular asset. Something simple like e.g `const hash = createHash(asset.source(), ...)` maybe sufficient for `[contenthash]` and is likely the most stable solution, since the implementation complexity is trivial and it has a single source of truth without 'side effects' like e.g `chunk(id|name)` contributing to it aswell. Imho, in case a chunk name changes it should be solely reflected by the `[name]` placeholder instead or not having an effect at all (e.g if an explicit name is provided via config etc etc).

**Comment by rightaway** [comment]
@michael-ciniawsky Agreed, your solution would certainly fix our browser caching issue and confusion about the unexpected behavior.

**Comment by rightaway** [comment]
Is this fix working for you? The same problem exists in the latest version.

**Comment by MarcPer** [comment]
I am using webpack version 4.19.1 and still see this problem as well.

**Comment by anthw** [comment]
I had the same issue with my vendor files from node_modules always generating a new hash, even though I hadn't changed anything. (webpack 4.26.0)

I generated 2 builds and diffed the contents. It showed a difference with only one dependency in particular (within the whole vendor file), @uirouter/angularjs.

The `exports provided` and `harmony reexport`/`import` JS comments were what was showing in different orders each build.

If anyone know why that might be happening I'm happy to try help fix with some direction.

**Comment by ishaiborovoy** [comment]
I encountered that issue too, same as the guys describe above

**Comment by montogeek** [comment]
Please create a new issue

**Comment by ishaiborovoy** [comment]
@montogeek there is one => contenthash changing even though file remains identical #8419

**Comment by jothikg** [comment]
Still, I was able to reproduce the same issue with 4.32.0 version. It is a blocker feature and this was working perfectly in Webpack 3. anyone working on this issue? its very critical for long term cache busting.
