### ISSUE TITLE
Create a loader that would replace original call with content

### ISSUE THREAD

**Issue by no-more** [webpack/webpack#7985]
I would like to inline replace a require statement. For example :
```
let title = require('./title.txt'); // title.txt contains `"my title"`
```
would generate 
```
let title = "my title"
```
Of course this is a basic usage but it could be of great help in many case. Angular AOT does not work well with dynamic component creation this could solve some issues.
I couldn't find out how to modify the caller file after all loaders applied in the current file (title.txt)

Thanks for your help.

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by no-more** [comment]
I didn't fill it because it's neither a bug report nor a feature request. It's a question I couldn't find any answer after hours of search.
