### ISSUE TITLE
Path to webpack's own modules cause new bundles to be created on different machines.

### ISSUE THREAD

**Issue by Moghul** [webpack/webpack#7988]
# Bug report

**What is the current behavior?**
I have two machines. Webpack is building different bundles without the content changing.

**If the current behavior is a bug, please provide the steps to reproduce.**
Relative to where I build my bundles, webpack is located at:
`../../.npm_installs/lib/node_modules/webpack`
and
`../../home/moghul/.npm_installs/lib/node_modules/webpack`

When building the bundles on the different machines, bundles with different names are created due to the path used to get `webpack/buildin/module.js` and other contents of the webpack module directory.

The only difference between the bundles, outside of their name, is 
`__webpack_require__(__webpack_require__.s=0)}({"../../home/moghul/.npm_installs/lib/node_modules/webpack/buildin/module.js":`
versus
`__webpack_require__(__webpack_require__.s=0)}({"../../.npm_installs/lib/node_modules/webpack/buildin/module.js":`

and 
`* WEBPACK VAR INJECTION */}.call(this, __webpack_require__(/*! ./../../../../../../../../../../home/moghul/.npm_installs/lib/node_modules/webpack/buildin/module.js */ \"../../home/moghul/.npm_installs/lib/node_modules/webpack/buildin/module.js\")`
versus
`* WEBPACK VAR INJECTION */}.call(this, __webpack_require__(/*! ./../../../../../../../../../../.npm_installs/lib/node_modules/webpack/buildin/module.js */ \"../../.npm_installs/lib/node_modules/webpack/buildin/module.js\")`

Which probably have so many "../" because of where the webpack config file itself is located in the project.

**What is the expected behavior?**
I don't particularly understand why paths are in the resulting bundle. The bundles are self-sufficient and don't require the original modules to exist in order to function.

It seems to me like either the paths should not be there in the first place, or there should be an option to turn them off, or to only use the file name instead of the path.

If there is a way get around this already, then please let me know.

**Other relevant information:**
webpack version:  4.17.1
Node.js version: 10.1.0
Operating System: Ubuntu 16.04
Additional tools:

**Comment by Moghul** [comment]
Sorry for taking so long to reply. Here's a link to a pretty minimal repo
https://github.com/Moghul/bad-path-content-reproducible

For the purposes of this, I just went into Private and ran `webpack --config setup.webpack.config.js`
You'll notice that the bundle in Public contains a path to jquery that looks like
`/home/silviu/Documents/bad-path-content-reproducible/Private/node_modules/jquery/dist/jquery.js`

And that's because I use 
`const vendorDirectory = path.resolve(__dirname, './node_modules');`
Which I need because in the original version, alongside the `bad-path-content-reproducible` project, there are another half dozen projects each with their own specific dependencies.

Because there are so many, I need a way to build all of them at once. If I use relative paths for the resources, I can only build them from where the config is located. But if I use these resolved paths, it works fine, except that the bundle, for whatever reason, contains the path to the original script.

This means that if my colleague takes the same project and builds the bundles, the bundles will differ in content because his usr name is different.

**Comment by Moghul** [comment]
Sorry for taking so long, here's a pretty minimal repo:
https://github.com/Moghul/bad-path-content-reproducible

It seems like this issue occurs when using expose-loader. However, the path in question is pointing specifically to a webpack. The bundle contains
`./../../../../../../.npm-global/lib/node_modules/webpack/buildin/global.js`

If the node_modules containing webpack are somewhere else, it will result in bundles with the same content, except for those paths.

**Comment by evilebottnawi** [comment]
@Moghul Maybe bug in `expose-loader`, need investigate

**Comment by Moghul** [comment]
@evilebottnawi this is probably the case. However, other portions of the bundle have specific paths in them:
`/home/silviu/Documents/bad-path-content-reproducible/Private/node_modules/jquery/dist/jquery.js`

My guess is "the solution" is to just use relative paths instead of `path.resolve(__dirname, './node_modules');` but this is not an option due to the fact that I have about a half dozen parallel projects with different dependencies and I build all the bundles at once from a parent directory further up the file tree.

In the end, webpack bundles have paths in them in one form or another, which identify the source of the code. However, the bundles are self-containing and don't need the sources to run. I would really like to be able to opt out of these paths in the bundles.
