### ISSUE TITLE
Unexpected token punc «:», expected punc «,»

### ISSUE THREAD

**Issue by akprgm** [webpack/webpack#7989]
My webpack configuration has this piece of code.
```
plugins: [
    new webpack.DefinePlugin({
      CONFIG: {
        API_URL: process.env.API_URL,
      },
    }),
]
```
When i try to access CONFIG in my script i get the above error.
```
(function(){
   console.log(CONFIG);
}());
```

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by Code2Life** [comment]
got same error

**Comment by ljqx** [comment]
@akprgm , @Code2Life , suppose you have definition like `process.env.API_URL === "http://abc.com"`, you should 
```diff
plugins: [
    new webpack.DefinePlugin({
      CONFIG: {
-        API_URL: process.env.API_URL,
+        API_URL: JSON.stringify(process.env.API_URL),
      },
    }),
]
```
Or you will get code like
```js
(function(){
  console.log(Object({"API_URL":http://abc.com}));
}());
```
Which is surely wrong.
