### ISSUE TITLE
Got a invalid JSON file with the webpack.DllPlugin  when there are  many entry points

### ISSUE THREAD

**Issue by imjeen** [webpack/webpack#7992]
# Bug report

**What is the current behavior?**

Recently, Migrating webPack version from 3.10.0 to 4.17.2.

I want to make a DLL file for my project, but then I got a error JSON file with `webpack.DllPlugin`, it only occurred when I use the multiple entry points. Like example below, if I have an another entry point: `entry_B`, the result JSON file: `vendor.json` is invalid JSON file.

**If the current behavior is a bug, please provide the steps to reproduce.**

My config like below:

```
export default  {
  entry: {
    entry_A: [
      'babel-polyfill',
     //  more other JS files or node modules
     ], 
    entry_B: [ // another entry point
      'es6-promise',
      //  more other JS files or node modules
     ], 
  },
  output: {
    path: path.resolve(__dirname, './dist'),
    filename: "js/[name].js?[hash:8]",
    library: "[name]",
  },
  plugins: [
    new webpack.DllPlugin({
      context: ".",
      name: "[name]",
      path: path.resolve(__dirname, `./dist/manifest/vendor.json`),
    }),
  ],
}
```
and I got the `vendor.json` file, then when I use the JSON file width `webpack.DllReferencePlugin`, it tell me  that the vendor.json is invalid JSON file, the error message is like below:

```
/project/admin/node_modules/webpack-cli/bin/cli.js:244
				throw err;
				^

SyntaxError: /project/admin/dist/manifest/vendor.json: Unexpected token / in JSON at position 1117
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:708:27)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
```

Obviously, I got a invalid JSON file: `vendor.json`

**What is the expected behavior?**

 I should get a valid JSON file with `webpack.DllPlugin` when I have more than entry points.

**Other relevant information:**
webpack version:  4.17.2
Node.js version: 9.10.0
Operating System: Mac
Additional tools:

**Comment by sokra** [comment]
Try this:

``` js
    new webpack.DllPlugin({
      context: ".",
      name: "[name]",
      path: path.resolve(__dirname, `./dist/manifest/[name].json`),
    }),
```

**Comment by imjeen** [comment]
@sokra Yes, it's also a good way to solve it.

by the way, how can I configure it to format the manifest JSON file?

 I want have a parameter `formatted` Like below:

```
new webpack.DllPlugin({
      formatted: true, // default false,  wish the parameter
      context: ".",
      name: "[name]",
      path: path.resolve(__dirname, `./dist/manifest/[name].json`),
}),
```

**Comment by sokra** [comment]
> by the way, how can I configure it to format the manifest JSON file?

Send a PR

**Comment by NaviMarella** [comment]
@sokra 

 I would like to send a PR for this. 

Can you guide me which folder the tests for this feature would go ??

**Comment by evilebottnawi** [comment]
Bump

**Comment by evilebottnawi** [comment]
bump

**Comment by evilebottnawi** [comment]
bump

**Comment by vankop** [comment]
bump

**Comment by sokra** [comment]
What's open here? To me it seems like everything is done towards this issue

**Comment by vankop** [comment]
Auto-bump..

**Comment by arshmeetsr** [comment]
@sokra 
`new webpack.DllPlugin({
      formatted: true, // default false,  wish the parameter
      context: ".",
      name: "[name]",
      path: path.resolve(__dirname, `./dist/manifest/[name].json`),
}),`

how to use the same in DllReferencePlugin?
