### ISSUE TITLE
bail not work

### ISSUE THREAD

**Issue by AMDvsTMD** [webpack/webpack#7993]
# Bug report

**What is the current behavior?**
webpack --config webpack.config --bail when error occured webpack don't exit 

and i debuged the case and found maybe is here a bug in NormalModule?

`			// if we have an error mark module as failed and exit
			if (err) {
				this.markModuleAsErrored(err);
				this._initBuildHash(compilation);
				return callback();
			}`

should  return callback to be return callback(err) then the bail can work

**If the current behavior is a bug, please provide the steps to reproduce.**

use mini-css-extract-plugin loader but not use mini-css-extract-plugin plugin

**What is the expected behavior?**

bail parameter works as what it meaned

**Other relevant information:**
webpack version:  lastest
Node.js version: v8.11.3
Operating System: window7
Additional tools:

**Comment by montogeek** [comment]
#7994

**Comment by benpolinsky** [comment]
#7994 is not a solution. It just tells us to wait for webpack 5.

**Comment by irudoy** [comment]
Workaround for webpack@4

```javascript
// webpack config
{
  plugins: [
    {
      apply: ({ hooks: { failed } }) =>
        failed.tap('HandleFailurePlugin', e => {
          console.log(e)
          process.exit(1)
        })
    }
  ]
}
```

**Comment by evilebottnawi** [comment]
Somebody can create minimum reproducible test repo?

**Comment by irudoy** [comment]
That was my fault. In my case, I didn't handle errors in the compilers [run](https://webpack.js.org/api/node/#run) method. Using Node API you should call `process.exit` manually if something went wrong. Seems like the `bail` option works as expected.
