### ISSUE TITLE
Watcher startTime is too early

### ISSUE THREAD

**Issue by jods4** [webpack/webpack#7997]
# Bug report

**What is the current behavior?**
When running `--watch`, `Watching` class performs this:
- Captures `startTime`
- Runs the whole thing: `watchRun` -> `compile` -> etc.
- Starts a watcher based on `startTime`. If any file was modified during compilation (i.e. after `startTime`) then recompilation happens.

**If the current behavior is a bug, please provide the steps to reproduce.**
I'm writing a plugin that modifies some file before compilation happens. I'm using `beforeRun` for that in normal mode and `watchRun` in watch mode.

The issue is that it goes into a recompilation loop because `watchRun` happens after `startTime` was captured (there's no earlier event unfortunately).

This is unfortunate because compilation happens later and no file is actually read before `compile`. So this is an unnecessary recompile. Not only a perf problem, but in my case an infinite loop because the file is updated again...

**What is the expected behavior?**

`startTime` can be kept for the `stat` object but I suggest using another time for watching files.
`compileTime` should be captured _after_ `watchRun` and _before_ `compile`.
When the watcher is started at end of compilation, `compileTime` should be used for checking files.

This way, plugins have a chance to modify the FS before compilation runs and not go into a loop.

**Other relevant information:**
webpack version: 4.17.1 
Node.js version: 10.3.0
Operating System: Windows
Additional tools: -

**EDIT**: I've hacked (literally, by monkey patching) the solution I describe above and things aren't _that_ simple. `Watchpack` adds an arbitrary amount (`FS_ACCURACY = 1000`) to `mtime` before comparing.
This means that taking the time just after writing a file is bound to fail anyway, unless we mess up with the file time or start time in some way.
I also noticed that `Date.now()` has poor accuracy and can sometimes be smaller than a file you've just written. Doesn't seem to be a way to get the FS time in node. That seem to matter less because I observe it as typically < 10ms, which is a lot less than the time a compilation takes.

**Comment by sokra** [comment]
Some filesystems have a accuracy of 1 second, so using a later time won't work too.

I would recommend to not write files that are later used by the compilation. If you try to generate files, use a loader instead to generate these files. (Not sure what you want to do exactly.)

If you really have to write these files, update the mtime with `fs.utimes` to some earlier time. If you generate these files based on some input files, you may use the highest timestamp of the input files as new mtime.

To avoid looping you could additional check if the file content matches before writting and only update the file if the content is different.

**Comment by jods4** [comment]
Thanks for the tips, I noticed by hacking at this that the situation is ugly.

I am indeed generating files based on other files. To make it work, I ended up doing what you suggested: I'm setting `mtime` to some earlier time. The idea of using the highest timestamp of input file makes a lot of sense, I didn't think of it! 

That solved the first pass loop.

The problem happens again on incremental changes and the pre-dating of file doesn't seem to work this time. I solved it by updating the file synchronously in the (sync) `invalidate` hook, so that the generated file changes before the next run starts.

It's not beautiful code but it works.

If you want to close this issue, go ahead. 
I think there is a design problem when it comes to generating additional build content before compilation but I realize there doesn't seem to be a simple fix for that.

**Comment by sokra** [comment]
> I think there is a design problem when it comes to generating additional build content before compilation

Did you try to use loaders to generate the content. They are basically intended to content transformation. As you said you have "input files", it sounds like a content transformation.

**Comment by jods4** [comment]
It's not content transformation. 
I generate a file based on analysis of all other files in the compilation.

I would be interested if you have suggestions for the best way to go about it.

**Comment by sokra** [comment]
A loader can have many input files. Here is an example:

``` js
module.exports = function() {
  const loader = this;
  return new Promise((resolve, reject) => {
    // register dependency to make caching and watching work
    loader.addContextDependency("/some/directory");
    // Do anything with the files
    fs.readdir("/some/directory", (err, files) => {
      if(err) return reject(err);
      // emit some generated code
      resolve(`export default ${JSON.stringify(files)};`);
    });
  });
}
```

``` js
// use it
import files from "./loader!";
console.log(files);
```

**Comment by jods4** [comment]
Thanks, that is very interesting!

I'm not sure if that design is better (maybe it is). It would be cleaner when it comes to watch, etc. but:
1. A loader requires an exising target file, right? (I could live with that)
2. Users won't be able to examine the generated content. For complex scenarios this might make debugging build issues harder.
3. I might need complex configuration options, including logic (functions). This won't work as an inline loader but I guess it might work if I register a loader for specific files in config.
4. Generated code needs to be fed into Typescript. Would that really work? I know I can chain a `ts-loader` but given how `ts-loader` works (esp. with `transpileOnly` and a forked checker) I'm unsure if it would actually work?

For context, what I'm trying to do is:
- Look at all source TS files in a project (or for faster execution: a subset determined by a glob);
- Parse them to look for specific metadata (e.g. `@part(Contract)` on exported classes);
- Generate a new source file that exports all that collected metadata in a slightly transformed way (with `import` to the original files).

**Comment by sokra** [comment]
> A loader requires an exising target file, right? (I could live with that)

No, this is not neccessary. See example above. `./loader!./file` and `./loader!` is possible.

> Users won't be able to examine the generated content. For complex scenarios this might make debugging build issues harder.

Depending on the chosen devtool you would be able to see/debug the generated source. If you are very diligent and emit SourceMaps to the input files you could even debug these, if this makes sense.

> I might need complex configuration options, including logic (functions). This won't work as an inline loader but I guess it might work if I register a loader for specific files in config.

Yes this won't work as inline loader. You can apply the loader via configuration. You can also use itself as input file if you want to.

> Generated code needs to be fed into Typescript. Would that really work? I know I can chain a ts-loader but given how ts-loader works (esp. with transpileOnly and a forked checker) I'm unsure if it would actually work?

Technically the loader system supports chaining loaders, but at least the forked checker doesn't support this. So this probably won't work. I think it would work without forked checker, but I guess that's not acceptable for performance reasons.

So you are back the the non-loader approach.

**Comment by jods4** [comment]
Thanks for taking the time to answer.

I think I'm also going to generate multiple files from the same input, so I guess I'm gonna stick with the plugin.

Feel free to decide if you want to design something for easier file generation or close this issue.

**Comment by sokra** [comment]
> Feel free to decide if you want to design something for easier file generation or close this issue.

Technically loaders are designed this way. The typescript flow is the problem...
