### ISSUE TITLE
Unable to access global variable in definePlugin functions 

### ISSUE THREAD

**Issue by saiumesh-letznav** [webpack/webpack#7999]
# Bug report

**What is the current behavior?**
Unable to access global variable in global function defined in definePlugin

**If the current behavior is a bug, please provide the steps to reproduce.**

```
// webpack.js

new DefinePlugin({
    'ENV': JSON.stringify(options.env),
    'letzConsole': letzConsole
});
```

```
// helper.js

function letzConsole(message, data) {
  try {
    if (ENV === "development" || IsDev) {
      console.error(new Date().toISOString(), message, data);
    }
  } catch (err) {
    console.error("still initializing.......", err);
  }
}
```

```
// app.module.ts
letzConsole('dummy', 'dummy');
```

error: **ReferenceError: ENV not defined**

**What is the expected behavior?**
We should be able to access definePlugin variables in global functions. 

**Other relevant information:**
webpack version:  3.6.0
Node.js version: >= 6.9.0
Operating System: Windows 10

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by sokra** [comment]
the DefinePlugin doesn't do recursive replacements. Try this:

``` js
new DefinePlugin({
    'ENV': JSON.stringify(options.env),
    'letzConsole': options.env === "development" ? letzConsoleDev : letzConsole
});
```

**Comment by saiumesh-letznav** [comment]
Hello @sokra thanks for quick reply. In our project **IsDev** global variable is dynamic one, unfortunately the solution you provided fails in that case.

**Comment by sokra** [comment]
A dynamic one like with `DefinePlugin.runtimeValue`?

**Comment by saiumesh-letznav** [comment]
Thank you @sokra it worked. but, webpack documentation doesn't have information on **DefinePlugin.runtimeValue** it would be great if you include them.

**Comment by sokra** [comment]
Yep, please file an issue to webpack/webpack.js.org.
