### ISSUE TITLE
resolve.alias is not resolving to 'main' file specified in package.json

### ISSUE THREAD

**Issue by trentgrover-wf** [webpack/webpack#800]
I have an external dependency that is set up like this:

`require('xyz')` should resolve to `node_modules/xyz/dist/xyz.js`
and
`require('xyz/abc')` should resolve to `node_modules/xyz/dist/abc.js`

I tried this webpack resolve:
```
    resolve: {
        extensions: ['', '.js', '.jsx'],
        alias: {
            'xyz': 'xyz/dist'
        }
    }
```

This works for the 2nd case, but not for the 1st.  The 1st case will work if I rename `xyz/dist/xyz.js` to `xyz/dist/index.js`.  The resolve documentation indicates that `index.js may resolve to another file if defined in the package.json`, but this isn't fixed by specifying `xyz.js` or `dist/xyz.js` as main in the package.json.

Is there a workaround?  Is this a bug in the `main` resolution?

**Comment by jhnns** [comment]
I think this must be solved with two aliases

```javascript
    alias: {
        // matches require('xyz')
        'xyz$': 'xyz/dist/xyz.js',
        // matches require('xyz/a'), require('xyz/b'), and so on
        'xyz': 'xyz/dist'
    }
```

**Comment by trentgrover-wf** [comment]
that works perfectly for me.  thanks so much
