### ISSUE TITLE
Cannot use module resolution on webpack libraries

### ISSUE THREAD

**Issue by repraze** [webpack/webpack#8002]
# Bug report

**What is the current behavior?**

When creating a library with a webpack configuration containing a module resolution rule to a local dir, it will allow the library to be bundled. However, if another package imports the lib, module resolved path within the library will not work.

**If the current behavior is a bug, please provide the steps to reproduce.**

*libname library*
config
``` js
{
    output: {
        library: 'libname'
    },
    resolve: {
        modules: ['./src'],
    }
}
```
src/index.js
``` js
import a from 'components/a'
a();
```
src/components/a.js
``` js
export default function(){}
```

*app*
config
``` js
{
    resolve: {
        modules: ['node_modules'],
    }
}
```
index.js
``` js
import 'libname'
```

> Can't resolve 'components/a'

**What is the expected behavior?**

Webpack should be able to resolve module paths from imported libraries. In this case the library can be built as a standalone, but not imported and build by another package. I am assuming that webpack does not read imported library configuration for path resolution.

All the libraries I found are using relative path within their source code, even if many of them do contain a module resolution path. (They probably realized it did not work.) The documentation does not hold any information about that.

**Other relevant information:**
webpack version:  4.17.2 (^4.12.1)
Node.js version: 8.11.4
Operating System: Windows 7

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.
