### ISSUE TITLE
while I am running my ionic aap it showing error

### ISSUE THREAD

**Issue by dnayak696** [webpack/webpack#8004]
[screen shot 2018-09-06 at 8 41 36 pm](https://user-images.githubusercontent.com/37681598/45168380-c478a400-b218-11e8-8b77-18adc3947d67.png)

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
