### ISSUE TITLE
Webpack's alias doesn't work when target module is in node_modules

### ISSUE THREAD

**Issue by stanleyyylau** [webpack/webpack#8005]
# Bug report

**What is the current behavior?**

alias doesn't work when target module is in node_modules folder

**If the current behavior is a bug, please provide the steps to reproduce.**

## Background

I'm writing an SSR react app with typescript, there's a client-side module I have to use (``client-logger``) and it can only be run on client-side since it's AMD module system. running on Node will give errors.

My current solution is to replace the ``client-logger`` module with a ``rewrite-client-logger`` module at compile time ONLY for server bundle.

I have tried Webpack's ``NormalModuleReplacementPlugin`` and ``alias``, even write my own loader, none of them works, this is my [Webpack config][1] for the alias.

This is the demo link for repro: https://github.com/stanleyyylau/demo

### Repro Steps:

+ Git clone and checkout to Master branch
+ ``npm install`` to install all dependencies
+ copy ``client-logger`` to node_modules with ``cp -rf ./client-logger ./node_modules``
+ ``npm run build`` to trigger the build
+ ``npm run start`` to run the universal app

**What is the expected behavior?**

+ Server should be running with no error
+ Server bundle's ``client-logger`` should be replaced by ``rewrite-client-logger`` ( You can verify this by searching for the string ``register event`` in ``assets/server.js`` file.)

**Other relevant information:**
webpack version:  4.17.2
Node.js version: v8.11.3
Operating System: MacOS 10.12.6 (16G1036)
Additional tools: Check this https://stackoverflow.com/questions/52201186/webpacks-alias-doesnt-work-when-target-module-is-in-node-modules

**Comment by sokra** [comment]
You flagged `client-logger` as external. It's never part of the build, so you can't alias it. Remove it from `externals`

**Comment by stanleyyylau** [comment]
I didn't  flag client-logger as external, where did you see that part?

**Comment by sokra** [comment]
`externals: [nodeExternals()]`

**Comment by sokra** [comment]
See documentation of webpack-node-externals

**Comment by stanleyyylau** [comment]
Getting another error when adding client-logger to whitelist

Thanks for your reply Juho, But it is still not working, after adding it to whitelist, I think it's been replaced, but I'm getting another error:

```
2018-09-10T02:29:16Z: identifier="routes:build-info" level="WARN" message="Build Info file not found, and hence not set up to inform actual version of the app." 
Warning: React depends on requestAnimationFrame. Make sure that you load a polyfill in older browsers. https://fb.me/react-polyfills
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.dirname (path.js:1349:5)
    at Object.<anonymous> (/Users/stanley/Desktop/X/epc-photos-pwa-app/assets/server.js:1:928603)
    at t (/Users/stanley/Desktop/X/epc-photos-pwa-app/assets/server.js:1:419)
    at Object.<anonymous> (/Users/stanley/Desktop/X/epc-photos-pwa-app/assets/server.js:1:928105)
    at t (/Users/stanley/Desktop/X/epc-photos-pwa-app/assets/server.js:1:419)
    at Object.defineProperty.value (/Users/stanley/Desktop/X/epc-photos-pwa-app/assets/server.js:1:926987)
    at t (/Users/stanley/Desktop/X/epc-photos-pwa-app/assets/server.js:1:419)
    at Object.<anonymous> (/Users/stanley/Desktop/X/epc-photos-pwa-app/assets/server.js:1:854113)
    at t (/Users/stanley/Desktop/X/epc-photos-pwa-app/assets/server.js:1:419)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! epc-photos-pwa-app@1.0.0 start: `node --use_strict ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the epc-photos-pwa-app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
