### ISSUE TITLE
`loader.options.publicPath` not being honored

### ISSUE THREAD

**Issue by 4lph4-Ph4un** [webpack/webpack#8009]
# Bug report

**What is the current behavior?**

Loader options publicPath doesn't seem to have any effect of for given outputs.
See more info on this [issue](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/222) originally made for `mini-css-extract-plugin`

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

publicPath given to loader options should effectively make given assets be served from their given destination - what happens instead is:

```
module: {
  rules: [
    {
      test: /\.css$/,
      use: [
        {
          loader: MiniCSSExtractPlugin.loader,
          options: {
            publicPath: "/styles/",
	   }
         },
         "css-loader?-url",
	 "postcss-loader"
      ]
    }
  ]
}

// The given assets do NOT end in said directory:
plugins: [
   new MiniCSSExtractPlugin({ 
     filename:      "[name].[hash].css",
     chunkFileName: "[id].[hash].css" 
   })
]
```
The said styles directory is ignored and all of the files are bundled with the rest of the JS bundles.

**Other relevant information:**

Even the simplest configuration without `mini-css-extract-plugin` does not work.
Tested with `html-webpack-plugin` and without, no difference in   ##behaviour.

webpack version:  Multiple, see issue referenced
Node.js version: Multiple, see issue referenced
Operating System: Multiple, see issue referenced
Additional tools: Multiple, see issue referenced

**Comment by sokra** [comment]
Duplicate
