### ISSUE TITLE
Dynamic requires not being rewrited correctly

### ISSUE THREAD

**Issue by raulferras** [webpack/webpack#801]
I'm bundling select2 (https://github.com/select2/select2) and it makes use of dynamic requires.  
Specifically in translation.js file (https://github.com/select2/select2/blob/select2-ng/src/js/select2/translation.js#L26).

This require is being rewrited as:

    var Query = __webpack_require__(19)(""options.amdBase + 'compat/query');

Which results in a **syntax error**. Shouldn't write it like this?

    var Query = __webpack_require__(19)("" + options.amdBase + 'compat/query');

**Comment by jhnns** [comment]
I can't find your referenced line in your example...

**Comment by raulferras** [comment]
Oh, you're correct, I'm refering to this: https://github.com/select2/select2/blob/a0c26e11140fa852989892a583d5d7263030e9bf/src/js/select2/defaults.js#L98

**Comment by jhnns** [comment]
Did you configure a [`ContextReplacementPlugin`](http://webpack.github.io/docs/list-of-plugins.html#contextreplacementplugin)?

**Comment by raulferras** [comment]
erm... nope, I though this was a "native" feature. Are there any docs besides what you linked to?

**Comment by sokra** [comment]
It's a bug
