### ISSUE TITLE
Static ish runtime

### ISSUE THREAD

**Issue by victornpb** [webpack/webpack#8013]
## Feature request

Change the webpack runtime template and modules template to be more friendly to static analysis tools.

**What is the expected behavior?**
Be able to take advantage of other tools that do dead code removal, advanced optimisations like code inlining, compile time evaluation, etc

**What is motivation or use case for adding/changing the behavior?**
Looking manually at the generated bundle, I see that minification tools have a hard time eliminating obviously dead code, and this is mainly caused by the way webpack template is designed, making it hard to be analysed statically. Clever things like what the closure compiler is able to do is ineffective, because the runtime obscure the code.

**How should this be implemented in your opinion?**
 I would like to see things like __webpack_require__() being simplified to variable declarations 

**Are you willing to work on this yourself?**
### yes

I understand this would not be compatible universally, things like the commons js and ES import interop webpack has to do, but I would like to give it a try, but I would like to have opinions/guidance with the codebase.

**Comment by sokra** [comment]
I'm open for new ideas. How do you image the bundle should be designed.

**Comment by victornpb** [comment]
I really like Google Closure Compiler and rollup approach that just create local variables and just do rename variables as necessary to avoid collision. I know that just encapsulating every module in its own function is easier but it comes with a cost.

When every export is just a variable declaration, a lot of tools like uglify will just strip unused variables, eliminating a whole bunch of unused modules.
