### ISSUE TITLE
Import file but get undefined

### ISSUE THREAD

**Issue by SnowFlowers** [webpack/webpack#8014]
# Bug report

**What is the current behavior?**
![285fd306-fa01-49f2-83bc-b2c3a3109c36](https://user-images.githubusercontent.com/16875486/45401576-d4164380-b683-11e8-8940-fc944cc1ef0d.png)

![731c7019-adaa-48df-b1b1-0f857271af2f](https://user-images.githubusercontent.com/16875486/45401599-f314d580-b683-11e8-9315-3592f7c82e73.png)

import Utils from a File, I can’t use it immediately
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
 I can use it immediately.

**Other relevant information:**
webpack version:  3.8.0
Node.js version: 8.10.0
Operating System: MacOs
Additional tools:

**Comment by sokra** [comment]
Looks like a circular dependency. Too few information provided to say more.

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
