### ISSUE TITLE
Support for plugin platforms (like WordPress)

### ISSUE THREAD

**Issue by hobbeshunter** [webpack/webpack#8019]
## Feature request

**What is the expected behavior?**
Basically what @fresheneesz described in his comment [here](https://github.com/webpack/webpack/issues/118#issuecomment-40000400). It would be nice to be able to develop web platforms that allow the integration of arbitrary plugins.

**What is motivation or use case for adding/changing the behavior?**
Web platforms with plugin APIs like WordPress. Also, this could be used to dynamically load i18n files.

**How should this be implemented in your opinion?**
Basically it should work the following: Some web server should host the core web platform. This web app can then query an API to retrieve a list of all available plugins. If a user enables such a plugin, it should be loaded (via JSONP).

For this the core has to define some kind of entry point, e.g.:
```
function importPlugin(plugin) {
    import(
        /* webpackMode: "webPlugin" */
        `./plugins/${plugin}`
    ).then(function(loadedPlugin) {
        console.log(loadedPlugin);
    }).catch(function(e) {
        console.error(e);
    })
}
```
If webpack stumbles across the magic comment `webpackMode: "webPlugin"` it should provide a JSONP function.

In my opinion plugins should be compiled separately from the core. To do so one could use the stats from the core to know which modules and chunks are already available through the core. Otherwise they should just be like chunks.

**Are you willing to work on this yourself?**
Yes, but I definitely need help.

Cheers,
Martin

**Comment by andreiglingeanu** [comment]
This sounds super interesting. But can't this be achieved in user-land, without special support from webpack?

**Comment by hobbeshunter** [comment]
> But can't this be achieved in user-land, without special support from webpack?
Don't know. But if webpack would support it, it would be the easiest for developers. Especially when one could `import` modules provided by the core in a plugin and webpack would automatically manage it.

**Comment by evilebottnawi** [comment]
@hobbeshunter can you clarify, do you mean UI for plugins?

**Comment by hobbeshunter** [comment]
Sorry @evilebottnawi, I don't get your question.

I want webpack to compile webapps that can be extended by plugins and therefore offer an API for that. Primarily this has nothing to do with an UI, but of course those plugins could extend the UI.
