### ISSUE TITLE
Problem with NewWatchingPlugin and less files OldWatchingPlugin kind of works

### ISSUE THREAD

**Issue by eisisig** [webpack/webpack#802]
I'm having problems with with less and the watching plugin.

I have a js file that imports a .less file (parent). In the less file I import other .less files. I use style, css and less loaders.

The watcher doesn't rebuild when editing any of the imported .less files (children). It only detects changes in the parent.

I tried switching to the OldWatchingPlugin and then it detects the changes. But I am also using the HotModuleReplacementPlugin and that doesn't seem to work with the OldWatchingPlugin

I will use the OldWatchingPlugin untill I find out what's happening and just do a manual browser reload

MAC OS X 10.10.2

**Comment by jhnns** [comment]
Do you use symlinks in your project (e.g. via `npm link` or `bower link`)?

**Comment by eisisig** [comment]
No I have no symlinks :-/ I was experimenting with webpack alias (with/without) in the import line for the less to see if that was causing something. But It doesn't matter.

I'm gonna setup a basic project and see if any of my configs are causing this

**Comment by jhnns** [comment]
Thx!

**Comment by sokra** [comment]
OS X?

**Comment by eisisig** [comment]
Yes sorry... OS X 10.10.2

**Comment by sokra** [comment]
maybe https://github.com/webpack/webpack/issues/793#issuecomment-75069334

**Comment by eisisig** [comment]
I'll try that also! Thanks for this pointer

**Comment by eisisig** [comment]
Doing repair permissions on the HDD with OS X Disk Utility seems to have fixed it! So It seems that this was in fact related to the file system rather than webpack
