### ISSUE TITLE
Dynamic import() with webpackPrefetch cause duplicate request

### ISSUE THREAD

**Issue by pldg** [webpack/webpack#8023]
# Bug report

**What is the current behavior?**

When I click the button to lazy-load a module which was already been prefetched (I can see it in the network tab), another network request for the same module is done.

**If the current behavior is a bug, please provide the steps to reproduce.**

Minimal repository: [test-webpack-dynamic-import-prefetch](https://github.com/pldg/test-webpack-dynamic-import-prefetch)

**What is the expected behavior?**

If the button is clicked that lazy-module should be called from the browser's cache without additional network request.

**Other relevant information:**

webpack version: 4.18
Node.js version: 8.11
Operating System: Windows 10
Additional tools: Chrome 69

**Comment by sokra** [comment]
> When I click the button to lazy-load a module which was already been prefetched (I can see it in the network tab), another network request for the same module is done.

That's correct, but the second request should be fulfilled from (disk) cache. (Make sure to not "disable cache" in devtools)

**Comment by niieani** [comment]
Damn, I just spend too many hours debugging this! I think we should document this (although it's actually more of a Chrome issue).

I couldn't for the life of me understand why Chrome shows two requests for the same file, while Firefox doesn't. Switching off "disable cache" and doing a hard reload instead solved the mystery.

I first thought this is an issue of webpack not adding the `crossorigin` attribute to the requests (according to [spec](https://github.com/w3c/preload/issues/32), this will cause the prefetch and actual request to be re-downloaded). Interestingly, what's the story here, does webpack add the crossorigin attribute correctly to the prefetch tags?
