### ISSUE TITLE
sideEffects doesn't work

### ISSUE THREAD

**Issue by jddxf** [webpack/webpack#8024]
# Bug report

**What is the current behavior?**
`sideEffects` doesn't work.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/jddxf/webpack4-side-effects-demo

**What is the expected behavior?**

**Other relevant information:**
webpack version:  4.18.1

**Comment by sokra** [comment]
That's not related to the `sideEffects` flag. It's about ESM reexports.

You should take a look at the `/*#__PURE__*/` flag if you want to optimize this case.

**Comment by sokra** [comment]
Good idea send a PR to the docs page to make it clear.

The sideEffects flag allows to drop the evaluation (and inclusion in the bundle) of a module if none of the exports is used.

**Comment by jddxf** [comment]
@kzc this may be related to the weird behavior of terser.

```
$ cat test1.js
const identity = f => f;
const foo = identity(() => {
  console.log('foo');
});
console.log();
```

```
$ cat test2.js
const identity = f => f;
const foo = identity(() => {
  return 'foo';
});
console.log();
```

```
$ terser test1.js -c toplevel,passes=2
(f=>()=>{console.log("foo")})(),console.log();
```

```
$ terser test2.js -c toplevel,passes=2
console.log();
```

**Comment by kzc** [comment]
ES6+ code is only minimally optimized by Terser due to its complexity. Terser tends to optimize ES5 code better due to its `uglify-js` heritage, and the fact that ES5 is much simpler.

```
$ cat test1.js | buble
var identity = function (f) { return f; };
var foo = identity(function () {
  console.log('foo');
});
console.log();
```
```
$ cat test1.js | buble | terser --toplevel -mc
console.log();
```

You're welcome to submit pull requests to improve ES6 optimizations in Terser. It's a volunteer effort.

**Comment by evilebottnawi** [comment]
bump

**Comment by vankop** [comment]
I think flag is clarified https://webpack.js.org/guides/tree-shaking/#clarifying-tree-shaking-and-sideeffects . Feel free to open issue in https://github.com/webpack/webpack.js.org , if you think it does not.
