### ISSUE TITLE
Webpack hangs suddenly, in compiler.run stage of prod build and never finishes

### ISSUE THREAD

**Issue by JustinMoser** [webpack/webpack#8028]
# Bug report

**What is the current behavior?**

When I run `yarn build` and trigger the webpack prod build, the process hangs when it reaches the line:

```
let compiler = webpack(config);
  return new Promise((resolve, reject) => {
    compiler.run((err, stats) => { ... }
  });
});
```

I have removed everything from the body of the promise I am returning and it still hangs, so it is not hanging in the body of the callback function passed to `compiler.run`

There is no output either to tell me where it is within the compile.run process, and it was working fine up until this morning. No code changes have been made but some packages have been reinstalled. However its impossible to determine if this is the cause as there is no output from the compiler at all.

**If the current behavior is a bug, please provide the steps to reproduce.**

Execute `yarn build` with the contents of my build.js file and the prod config which I can provide if needed. I can also provide my yarn.lock or my package.json file as the code in the build.js file and prod config file has not changed, and this problem has only started recently appearing.

**What is the expected behavior?**
- It should not hang indefinitely during the `compiler.run` stage, and should finish by executing the body of the callback function.

Ultimately (and fairly obviously), triggering a production build should finish without errors and produce a new contents in the build directory.

**Other relevant information:**
webpack version:  4.18.1
Node.js version:  v8.12.0 (using NVM)
Operating System: macOS High Sierra 10.13
Additional tools: VS Code, Zsh

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by JustinMoser** [comment]
FYI I solved the issue. It was hanging because there were two fairly large JSON files in my project, and for whatever reason it causes the compilation stage to hang. Other solutions recommend increasing the size of the memory limit in your build script, and this is what worked for me. 

It is annoying though that there was no feedback on this from the compiler / yarn.
