### ISSUE TITLE
Some browser field in bundling modules are ignored when target = "electron-renderer"

### ISSUE THREAD

**Issue by stomita** [webpack/webpack#8031]
# Bug report

**What is the current behavior?**

When bundling modules which have [`browser` field](https://github.com/defunctzombie/package-browser-field-spec) in package.json, the alternative script specified in the field will be used for webpack bundling by default. It is also true when the target is set to `electron-renderer`, but only when the `browser` field has [object-style replacement](https://github.com/defunctzombie/package-browser-field-spec#replace-specific-files---advanced), the replacement is not working in target="electron-renderer".

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/stomita/webpack-browser-field-test

To reproduce the issue:

1. Checkout the repos above
2. Run `npm install`
3. Run `npm run build` to generate bundled scripts
4. Run `npm test` to get the result

The output will be:
```
----------
target = web
module with browser field (string) => browser.js
module with browser field (object) => browser.js
----------
target = electron-renderer
module with browser field (string) => browser.js
module with browser field (object) => index.js
```

**What is the expected behavior?**

A webpack config with target: "electron-renderer" should handle modules with object-style browser field correctly as the config without target (= target: "web").

So the above example result should be like:

```
----------
target = web
module with browser field (string) => browser.js
module with browser field (object) => browser.js
----------
target = electron-renderer
module with browser field (string) => browser.js
module with browser field (object) => browser.js
```

**Other relevant information:**
webpack version:  4.19.0
Node.js version: 8.11.4
Operating System: macOS High Sierra (10.13.6)
Additional tools: no

**Comment by sokra** [comment]
Please send a PR:

This line

https://github.com/webpack/webpack/blob/5258471fa13ea450992255767faf38f01c143511/lib/WebpackOptionsDefaulter.js#L330

need to be similar to 

https://github.com/webpack/webpack/blob/5258471fa13ea450992255767faf38f01c143511/lib/WebpackOptionsDefaulter.js#L337-L341

**Comment by avengerweb** [comment]
Nice that PR was broke applications which use axios for example (or webtorrent) by default...
