### ISSUE TITLE
Module loaded with mixed slashes on windows when target: 'electron-main'

### ISSUE THREAD

**Issue by roblourens** [webpack/webpack#8032]
VS Code issue https://github.com/Microsoft/vscode/issues/54689

See the repo at https://github.com/kwonoj/vscode-node-async-import-webpack-repro

It has `target: 'electron-main'`. When I build and run it, the bundle is loaded at the path `C:\\Users\\roblou\\Documents\\vscode-node-async-import-webpack-repro\\dist/0.bundle.js`. Debugging this doesn't work in vscode, because we always expect backslashes on windows. Even if you `require()` with forward slashes, they are always normalized to backslashes.

If I build with `target: 'node'` then the bundle is loaded at `C:\\Users\\roblou\\Documents\\vscode-node-async-import-webpack-repro\\dist\\0.bundle.js`, and debugging works.

I'm not really clear on the difference between the two targets. I see the docs https://webpack.js.org/configuration/target/ and source https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsApply.js#L70-L185

Should this be fixed by one of the different plugins, or does vscode need to handle mixed slashes on windows? How does one make node load a module with a path with forward slashes?

**Comment by kwonoj** [comment]
I was originally reported this in vs code repo and bit bitten for some time, so made changes here : https://github.com/webpack/webpack/pull/8035 .

**Comment by roblourens** [comment]
Thanks @kwonoj! Beat me to it 😁
