### ISSUE TITLE
Mock some file in webpack. Is it doable?

### ISSUE THREAD

**Issue by dmngu9** [webpack/webpack#8037]
This is just a general question. Im working on a project that migrate Backbone to React. Some components in React use some functions in Backbone and webpack in storybook throw error because of it.

Can i use webpack alias to mock out backbone modules? I have been trying and not sure if i do it right

Basically, I did as below to alias backbone file to lodash:

alias: {
  'lodash': path to back bone file
}

Is that right?

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.
