### ISSUE TITLE
Comments in a default export next to the exported value are removed by webpack

### ISSUE THREAD

**Issue by jddxf** [webpack/webpack#8039]
# Bug report

**What is the current behavior?**
Webpack generates output
```
/* harmony default export */ __webpack_exports__["default"] = (Math.abs(0));
```
for the code below
```
export default /*@__PURE__*/Math.abs(0);
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Webpack should reserve the comments as below
```
/* harmony default export */ __webpack_exports__["default"] = /*@__PURE__*/(Math.abs(0));
```

**Other relevant information:**
webpack version:  4.19.0

**Comment by sokra** [comment]
Yeah that's a bug.
