### ISSUE TITLE
Target "atom" incompatible with React Router

### ISSUE THREAD

**Issue by akrieger** [webpack/webpack#804]
I am working in a project, and I am attempting to convert it to being able to run inside of atom-shell. Just adding calls to, for example, require('remote'), causes the expected error.

```
[4624:0218/193652:INFO:CONSOLE(816)] "Uncaught ReferenceError: remote is not defined", source: file:///C:/open/atom-shell/app/app/build/bundle.js (816)
```

After poking around with various externals configs and getting nowhere, I found the configuration option for target: "atom", and gave that a shot. Then I got this error:

```
WARNING in ./~/react-router/~/when/lib/async.js
Module not found: Error: Cannot resolve module 'vertx' in C:\open\atom-shell\skyline\skyline\node_modules\react-router\node_modules\when\lib @ ./~/react-router/~/when/lib/async.js 48:12-31
```
Here is a link to the problem code line: https://github.com/cujojs/when/blob/f6d74d265b7931a31a9639bd4fbe5660803831c5/lib/async.js#L47

react-router 0.11.6 depends on when 3.4.6. It is entirely possible that if I upgrade our react-router dependency, it'll upgrade our when dependency, to a version which does not have this issue. However, I'd like to resolve this problem if at all possible.

Obviously, we are using react. Here is our webpack configuration file:

```
module.exports = {
  cache: true,
  entry: './js/index',
  output: {
    filename: 'build/bundle.js'
  },
  target: "atom", // Added, causes problem.
  module: {
   loaders: [
     { test: /\.js$/, loader: 'jsx-loader?harmony&stripTypes' },
     { test: /\.less%/, loader: 'style-loader!css-loader!less-loader' }
    ]
  }
}
```

Let me know what other information is needed. Is what I'm asking for just impossible? Is there a way for me to get the externals option to shim/ignore specific atom modules and otherwise not need a special target? Thanks in advance!

**Comment by kmalakoff** [comment]
For a workaround, instead of using target: 'atom', I just added the following (that I found in the atom target) to my plugins: new webpack.ExternalsPlugin("commonjs", "remote").

**Comment by bebraw** [comment]
@akrieger Is this relevant still? Did the workaround work?

**Comment by akrieger** [comment]
I don't remember if the specific workaround worked or not, but this is definitely not relevant anymore. We have been successfully using webpack in our atom shell project for a while now. Thanks for following up!
