### ISSUE TITLE
Example from documentation fails: externals with array as property value

### ISSUE THREAD

**Issue by RubenVerborgh** [webpack/webpack#8041]
# Bug report

**What is the current behavior?**

Having an array as property value for the `externals` object, despite being documented at https://webpack.js.org/configuration/externals/#array, fails with `Invalid configuration object`.

```
module.exports = {
  //...
  externals: {
    subtract: ['./math', 'subtract']
  }
};
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```bash
npm install --save-dev webpack@4.19.0 webpack-cli@3.1.0
mkdir src
touch src/index.js
echo "
module.exports = {
  mode: 'production',
  externals: {
    subtract: ['./math', 'subtract']
  }
};" > webpack.config.js
node_modules/.bin/webpack
```

**What is the expected behavior?**

Webpack respects the configuration and looks up the subtract submodule of math.

**Other relevant information:**
webpack version:  4.19.0
Node.js version: ﻿v10.0.9
Operating System: macOS 10.13.6
Additional tools: none

**Comment by sokra** [comment]
Seems like the schema is to strict here.

Please send a PR to allow arrays of strings here too:

https://github.com/webpack/webpack/blob/2f78aae8d8f78ce9c9221ff25a0483d81809bd81/schemas/WebpackOptions.json#L117-L130
