### ISSUE TITLE
Allow configuration for injecting local Promise polyfill into runtime templates

### ISSUE THREAD

**Issue by rjgotten** [webpack/webpack#8048]
## Feature request

**What is the expected behavior?**

Various parts of Webpack's (semi-)internal runtime depend on a native `Promise` being available.
Currently, browsers which do not have a native implementation require that it be polyfilled globally.

It would be nice if Webpack would provide a way to hook in a _local_ polyfill instead; one which does not require writing to `window`.

**What is motivation or use case for adding/changing the behavior?**

Projects that act as third-parties inside the websites of others generally need to minimize the way in which they affect the global environment. Currently it is impossible to avoid injecting a global polyfill for `Promise` when you really on key functionalities like ES6 dynamic `import()`.

**How should this be implemented in your opinion?**

1. Centralize creation of `Promise` instances by code generators. (Seems a lot of it is already being done through `RuntimeTemplate`'s `blockPromise`, actually.)
2. Add a configuration property that can be set to a user-space module to be pulled in, instead of accessing the global `Promise`.

**Are you willing to work on this yourself?**

Willing; yes. Able; no.
Simply don't have the time.

**Comment by borela** [comment]
Wouldn't https://babeljs.io/docs/en/babel-preset-env suffice? It injects the necessary polyfills on the final bundle based on the target browsers.

**Comment by rjgotten** [comment]
> Wouldn't https://babeljs.io/docs/en/babel-preset-env suffice? It injects the necessary polyfills on the final bundle based on the target browsers.

No it doesn't. At all.

The normal way to use Babel is to apply it via `babel-loader`, which means it runs at the individual module source level and afaict never runs on Webpack-generated intermediate code - such as the boilerplate for async context modules - or the Webpack-runtime code.

The notion that using `@babel/preset-env` would suddenly magically make Babel run on a build output artefact that was never passed to the Babel compiler is ridiculous.


What the new mode of operation in `@babel/preset-env` does, is inspect the individual modules' source for signatures that match polyfillable behavior; match that against the targeted browsers list; and then add imports at the top of the individual module sources for the individual necessary polyfills.

It does not run on the output bundle and it does not run on Webpack-generated intermediate code. It only runs on 'user-land' modules that match a configured `babel-loader` in the webpack configuration.

Furthermore, the polyfills from `@babel/polyfill` that `@babel/preset-env` adds are _global_ polyfills, i.e. , they are added to `window`. Which is exactly what this feature request is aiming to **avoid**.

**Comment by borela** [comment]
After looking at webpack's source I confirmed my assumptions were wrong, thank you.

**Comment by rjgotten** [comment]
Just reporting in to let you know this is still an issue, and still something I'd like to see a solution to at one point.

**Comment by rjgotten** [comment]
Reporting in again that this is still an issue. Note that also within Babel's development, there is work being prepared/done for a new polyfilling implementation aimed at local polyfilling.

Webpack should anticipate on this and put in place a mechanism to have dependencies of the runtime itself be made injectable or have the runtime system itself be made subject to loaders and thus transpilation.

**Comment by evilebottnawi** [comment]
Duplicate #3531
