### ISSUE TITLE
When I used code split, I found that the chunk file was loaded earlier than the corresponding CSS file

### ISSUE THREAD

**Issue by xuchenchenBoy** [webpack/webpack#8049]
### Is this a bug report?

No

### Did you try recovering your dependencies?

No.

### Which terms did you search for in User Guide?

Code split.

### Environment

Environment:
  OS:  Windows 7
  Node:  8.9.3
  Yarn:  1.9.4
  npm:  5.1.0
  Watchman:  Not Found
  Xcode:  N/A
  Android Studio:  Not Found

Packages: (wanted => installed)
  react: ^16.4.2 => 16.4.2
  react-dom: ^16.4.2 => 16.4.2

### Steps to Reproduce

1.I used code split in tutorials.
```
import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { Router, Route, browserHistory, IndexRoute  } from 'react-router'
import createStore from './store/createStore'
import registerServiceWorker from './registerServiceWorker';
import sagas from './sagas'
import './styles/main.less'
import RouterWrapper from './components/Layouts/RouterWrapper'
import asyncComponent from './components/AsyncComponent'
import { isTokenExpire } from './utils/authority'
import { push } from 'react-router-redux'
import * as userTypes from './actions/user'

const { store, history } = createStore(window.__INITIAL_STATE__ || {}, browserHistory);
store.runSaga(sagas);

const Page404 = asyncComponent(() => import('./pages/Page404'))
const Login = asyncComponent(() => import('./pages/User/Login'))

function onEnterRoute(route, replace) {
  if (location.pathname !== '/login' && isTokenExpire()) {
    store.dispatch({ type: userTypes.USER_LOGOUT })
  }
}

ReactDOM.render((
  <Provider store={store}>
      <Router history={history}>
        <Route path="/" onEnter={onEnterRoute}>
          <IndexRoute component={Login} />
          <Route path="login" component={Login} />
          <Route path="*" component={Page404} />
        </Route>
      </Router>
  </Provider>
), document.getElementById('root'));
registerServiceWorker();
```

2. Then i executed ```npm run build```
3. When the login page is loaded, the corresponding JS is loaded earlier than CSS, causing page jitter.
![image](https://user-images.githubusercontent.com/14016766/45672329-789ff600-bb5a-11e8-8f8f-fe95c8f3973c.png)

### Expected Behavior

 I want that the chunk file was loaded later than the corresponding CSS file.

### Actual Behavior
The chunk file was loaded earlier than the corresponding CSS file.Cause page shake when loading.

**Comment by sokra** [comment]
What's your CSS config?

**Comment by xuchenchenBoy** [comment]
@sokra 
webpack.config.prod.js
```
        {
            test: /\.css$/,
            loader: ExtractTextPlugin.extract(
              Object.assign(
                {
                  fallback: {
                    loader: require.resolve('style-loader'),
                    options: {
                      hmr: false,
                    },
                  },
                  use: [
                    {
                      loader: require.resolve('css-loader'),
                      options: {
                        importLoaders: 1,
                        minimize: true,
                        sourceMap: shouldUseSourceMap,
                      },
                    },
                    {
                      loader: require.resolve('postcss-loader'),
                      options: {
                        // Necessary for external CSS imports to work
                        // https://github.com/facebookincubator/create-react-app/issues/2677
                        ident: 'postcss',
                        plugins: () => [
                          require('postcss-flexbugs-fixes'),
                          autoprefixer({
                            browsers: [
                              '>1%',
                              'last 4 versions',
                              'Firefox ESR',
                              'not ie < 9', // React doesn't support IE8 anyway
                            ],
                            flexbox: 'no-2009',
                          }),
                        ],
                      },
                    }
                  ],
                },
                extractTextPluginOptions
              )
            ),
            // Note: this won't work without `new ExtractTextPlugin()` in `plugins`.
          }
```

**Comment by catcpp** [comment]
I think it's not Webpack bug because I don't have such issues with latest Webpack

**Comment by michael-ciniawsky** [comment]
@xuchenchenBoy Please provide the `webpack` version you are currently using (disclaimer `webpack >= v4.0.0` doesn't work (correctly) with the `ExtractTextPlugin`, use the `mini-css-extract-plugin` instead). Otherwise with the current information provided we can't help you, please provide your `CommonChunksPlugin` (`webpack =< v3.0.0`) or `SplitChunkPlugin` (`optimization.splitChunks`) for `webpack >= v4.0.0` and feel free to reopen

**Comment by xuchenchenBoy** [comment]
> I think it's not Webpack bug because I don't have such issues with latest Webpack

Thanks.

**Comment by xuchenchenBoy** [comment]
> @xuchenchenBoy Please provide the `webpack` version you are currently using (disclaimer `webpack >= v4.0.0` doesn't work (correctly) with the `ExtractTextPlugin`, use the `mini-css-extract-plugin` instead). Otherwise with the current information provided we can't help you, please provide your `CommonChunksPlugin` (`webpack =< v3.0.0`) or `SplitChunkPlugin` (`optimization.splitChunks`) for `webpack >= v4.0.0` and feel free to reopen

Thanks.
