### ISSUE TITLE
When using HotModuleReplacementPlugin(HMR),  one file‘s change cause all files to emit.

### ISSUE THREAD

**Issue by wxlworkhard** [webpack/webpack#8054]
# Bug report

**What is the current behavior?**
In the increment build time, when I use HMR and change one file, all chunks will emit. It is deserve that 
only chunk corresponding to the changed file should rerender and emit.

I find the problem is in  `webpack/lib/JavascriptModulesPlugin.js`  at line 61.

When use HMR
```js
const useChunkHash = compilation.mainTemplate.useChunkHash(chunk);
```
`useChunkHash` is always `false`. So it is cannot use `chunk.hash`. Why?

**If the current behavior is a bug, please provide the steps to reproduce.**

webpack.config.js

```js
const path = require('path');
const webpack = require('webpack');

module.exports = {
    devtool: 'cheap-module-source-map',
    mode: 'development',
    entry: {
        'dd3': './app/pages/dd3/export.js',
        'dd4': './app/pages/dd4/export.js',
        'dd5': './app/pages/dd5/export.js',
    },

    output: {
        path: path.resolve(__dirname, "webpackdist"),
        filename: `[name].js`,
        chunkFilename: `[name]_chunk.js`
    },

    devServer: {
        hot: true,
        port: 8804,
    },

    optimization: {
        splitChunks: {
            chunks: 'all',
            name: 'vendor',
            minSize: 0,
            minChunks: 2,
        },
    },

    plugins: [
        new webpack.HotModuleReplacementPlugin()
    ]
}
```

**What is the expected behavior?**

**Other relevant information:**
webpack version:  4.17.1
Node.js version: 8.9.4
Operating System: Mac
Additional tools:

**Comment by chentianyuan** [comment]
i got the same problem
