### ISSUE TITLE
Webpack doesn't tree-shake simple case

### ISSUE THREAD

**Issue by bterlson** [webpack/webpack#8057]
**What is the current behavior?**

In a module called `index`, when re-exporting another module via `import * as module from "module"; export { module  }`, the members of `module` will not be tree-shaken, leaving all of its members in-tact even if consumers of `index` only use one of its exports.

If I had to guess, I'd say Webpack thinks the usage of the namespace `module` in export position is a generic usage and thus won't tree-shake things further.

**If the current behavior is a bug, please provide the steps to reproduce.**

Sample repo: https://github.com/RikkiGibson/nested-reexports-demo

Specifically, see this file: https://github.com/RikkiGibson/nested-reexports-demo/blob/master/index.js#L1

If you use the new module export form `export * as module from "module"`, tree-shaking works as expected. Unfortunately this syntax is not widely supported across the ecosystem as yet.

**What is the expected behavior?**

`module` should be tree-shaken.

**Other relevant information:**
webpack version:  latest
Node.js version: 10.x
Operating System: Windows

**Comment by ooflorent** [comment]
> If you use the new module export form `export * as module from "module"`, tree-shaking works as expected. **Unfortunately this syntax is not widely supported across the ecosystem as yet.**

This is a stage 1 proposal. It is not part (yet) of JavaScript.

**Comment by TheLarkInn** [comment]
We should be able to refactor pieces of our code now (during v5 changes) that would make this easy to implement after we land v5. (Thus the Maybe in webpack 5) tag.

**Comment by marcofugaro** [comment]
I can't get tree-shaking to work either, I have this in my index.js

```js
import Button from './components/Button'
import Checkbox from './components/Checkbox'
import FlexView from './components/FlexView'
import Radio from './components/Radio'
import Select from './components/Select'
import TextInput from './components/TextInput'
import Toggle from './components/Toggle'

export { Button, Checkbox, FlexView, Radio, Select, TextInput, Toggle }
```

and in my webpack config I have sideEffects set to true: 

```js
module.exports = {
  mode: 'production',
  entry: './src/index.ts',
  output: {
    path: path.resolve('./lib'),
    filename: 'react-components.js',
    libraryTarget: 'commonjs2',
  },

  // loaders and stuff...
  // terser-webpack-plugin...

  externals: {
    // don't include react in the bundle
    react: {
      root: 'React',
      commonjs2: 'react',
      commonjs: 'react',
      amd: 'react',
    },
  },
  optimization: {
    splitChunks: false,
    sideEffects: false,
  },
}```

Is this correct? the `sideEffects: false` doesn't help at all

**Comment by Jessidhia** [comment]
It's interesting to note that even webpack 4 is aware of how it is reexported (it writes `/* harmony reexport (module object) */` in the annotation comment); but it's probably lacking some metadata to rewrite the imports correctly in a way that is tree-shakable.

**Comment by joshjg** [comment]
Has anyone found a workaround for this issue?

**Comment by sokra** [comment]
fixes in webpack 5
