### ISSUE TITLE
Is there a way to provide the file contents

### ISSUE THREAD

**Issue by thepian** [webpack/webpack#806]
When a module has been resolved as a file, there doesn't seem to be any plugin for providing the content.

The callback seems to only search valid paths but no content byte array/string option.

Or is there?

**Comment by thepian** [comment]
I'm looking at after-resolve, is that the place to provide the content ? It seems that resource might be the thing, but I see no documentation for that.

**Comment by sokra** [comment]
There is no way.

**Comment by sokra** [comment]
Ok, you could provide a custom inputFileSystem to the compiler...

**Comment by thepian** [comment]
That seems like an acceptable solution even if a bit of a workaround

**Comment by thepian** [comment]
This doesn't seem to work with watching

The build keeps being triggered.

**Comment by sokra** [comment]
you also need a custom `watchFileSystem`.

**Comment by thepian** [comment]
I made a simple modification to the new Watcher.

    NewWatchingPlugin.prototype.apply = function(compiler) {
    	compiler.plugin("environment", function() {
    		compiler.watchFileSystem = new NodeWatchFileSystem(compiler.inputFileSystem.forWatching || compiler.inputFileSystem);
    	});
    };

This works except for having virtual entry files. It seems to work differently. I need to add a couple of require statements in addition to the main JS to kick off the application. Is there another way I might do that, perhaps with a loader.

**Comment by thepian** [comment]
It seems that the watching is relying on something other than inputFileSystem.stat 

After looking around quite a bit I can't seem to find anything. Even so the rebuild gets constantly triggered.

**Comment by bebraw** [comment]
@thepian Any luck with this?
