### ISSUE TITLE
include global functions in webpack

### ISSUE THREAD

**Issue by RomanYar** [webpack/webpack#8060]
In my company we recently moved to bundling using webpack (instead of some old bundling script that concats all the js files and creates a bundle.js). At first we pretty much did the same thing with webpack - we used the concat plugin, added the folder with all the js files and all worked well.

The issue began when I needed to require a module, and saw that because we use the concat plugin, the babel-loader doesn't apply to the concated files.

After some research i found how to "babelize" it and made the following modification - I removed the oncat plugin, and in the webpack.config.js aded the following:

entry: {
    ...
    "builder": glob.sync("./path/to/folder/**/*.js")
}
The issue now is that in some of the js files there are functions defined, that originally ment to be global, but now i guess because the order of the array, they are not defined.

Is there a way to tell webpack that all global functions and variables should be mapped to the window?

Thanks

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
