### ISSUE TITLE
ModuleConcatenationPlugin is setting `modules[].reasons[].moduleId` to null in some cases

### ISSUE THREAD

**Issue by joeljeske** [webpack/webpack#8062]
# Bug report

**What is the current behavior?**

It would appear that when using `ModuleConcatenationPlugin` (which is default for mode = production), that the modules that it concatenated do not properly have module ids in the output stats. More specifically, if a `reason` for given `module` is from a module that has been concatenated, then the `moduleId` of that `reason` is `null`. I would not expect that to be the case. 

**If the current behavior is a bug, please provide the steps to reproduce.**

Reproduction Project: 
https://github.com/joeljeske/webpack-module-concatenation-plugin-issue

**What is the expected behavior?**

Every `reason` for `module` should have a `moduleId` that corresponds with the `id` of a `module`

**Other relevant information:**
webpack version:  4.19.1
Node.js version:  v8.11.3
Operating System: MacOS 10.13.4
Additional tools: N/A

**Comment by sokra** [comment]
Concatenated modules don't have ids. All modules have identifiers.

**Comment by joeljeske** [comment]
How would you recommend that I traverse the dependency tree using the stats? Is there any way to do this?

**Comment by sokra** [comment]
You can use `moduleIdentifier` and `identifier`. This is always set and unique.

**Comment by evilebottnawi** [comment]
Answer above
