### ISSUE TITLE
[ProgressPlugin] webpack progress shows deranged on windows 10.1803 with new console terminal

### ISSUE THREAD

**Issue by Aqours** [webpack/webpack#8066]
# Bug report

**What is the current behavior?**
webpack progress shows deranged
![qq 20180921174833](https://user-images.githubusercontent.com/8586286/45874532-bb1a3a80-bdc7-11e8-94d9-9d9f79e8125e.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
1. run `npx webpack -w` (with webpack.ProgressPlugin)

**What is the expected behavior?**
![qq 20180921175009](https://user-images.githubusercontent.com/8586286/45874743-3c71cd00-bdc8-11e8-8b99-ed85d8fddd71.png)
https://github.com/webpack/webpack/blob/3b6d1495c3858d59cfdb46b2343c07f2e4c1316d/lib/ProgressPlugin.js#L126
It conflict with webpack-cli's logs, ` handler(0, "compiling");` should invoked async.
Changing this to `process.nextTick(() => handler(0, "compiling"));` seem to work fine.

**Other relevant information:**
webpack version:  4.19.0 (with `new webpack.ProgressPlugin()`)
Node.js version: 10.10.0
Operating System: Windows 10.1803 with default new console terminal (cmd/powershell)
Additional tools:

**Comment by evilebottnawi** [comment]
@Aqours problem still exists? Can you create minimum reproducible test repo?

**Comment by Aqours** [comment]
Clone this repo https://github.com/Semibold/webpack-issues-8066
then run below commend in new  Windows 10 CMD
```
npm install
npm run watch
```
