### ISSUE TITLE
Urm... stats.toJson() doesn't actually return Json

### ISSUE THREAD

**Issue by Izhaki** [webpack/webpack#8073]
*By far* the most minor issue I have ever filed, yet...

`stats.toJson()` doesn't actually return a [valid JSON](http://www.json.org/), where, for example, keys are strings and MUST (by the parser) be enclosed with quotation marks.

To get the actual JSON, one needs:
```javascript
JSON.stringify(stats.toJson());
```

`stats.toJson()` returns an object, and javascript object (JSO) is not JSON.

A better name for this function might be `serialize` or `toSerializable`.

I know that changing the name of the method will trigger riots; but maybe just add an alias for correctness' sake? Deprecate in v8?

**Comment by ooflorent** [comment]
Actually `toJson` returns an object _that is safe to serialize using JSON, hence the name.

**Comment by Izhaki** [comment]
@ooflorent 

Indeed, as both of us said - it returns an object, not JSON.

You wouldn't expect a function called `toNumber` to return a string (albeit one that can be converted to a number) would you?

```javacript
console.log(toNumber('Twenty two')); // => "22"
console.log(typeof(toNumber('Twenty two'))); // => "string" 
```

**Comment by eemeli** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON()_behavior

**Comment by Izhaki** [comment]
@eemeli The two are different.

To begin with the method name is `toJson` in webpack, whereas it is `toJSON` in the standard.

Then, the standard method takes a key, whereas the webpack's method takes options.

Also, to replicate the example given on MDN:

```javascript
var obj = {
    data: 'data',
    
    toJSON(key){
        if(key)
            return `Now I am a nested object under key '${key}'`;
        
        else
            return this;
    }
};

JSON.stringify(obj);
// '{"data":"data"}'

JSON.stringify({ obj })
// '{"obj":"Now I am a nested object under key 'obj'"}'

JSON.stringify([ obj ])
// '["Now I am a nested object under key '0'"]'
```

Can you see what happens when you just provide an object?

`JSON.stringify(stats)` yields a `circular reference error`.

I don't think this was the original intent of the function.

**Comment by sokra** [comment]
@Izhaki yeah, maybe you are right... The method was originally really named like the standard method `toJSON` (which also returns an js object).

I thinks removing the method would confuse a lot a people, but if we can agree on a better name, we could add an additional method and deprecate `toJson` over the next few major version.

**Comment by sokra** [comment]
One could also claim the Objects are the parsed representation of JSON.

**Comment by montogeek** [comment]
Maybe `toJSObject`?

**Comment by montogeek** [comment]
`toJson` reads what it will return  JSON.

**Comment by Izhaki** [comment]
@montogeek Not sure `toJSObject` is good enough - `stats` is, by all means` a JS object... just not one that is serialisable due to circular references.

Having looked up both [serialization](https://developer.mozilla.org/en-US/docs/Glossary/Serialization) and [JSON.stringify()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) I feel:

`toSerializable()`

is probably best.
