### ISSUE TITLE
Module parse failed: Unexpected character '@'

### ISSUE THREAD

**Issue by winwin2013** [webpack/webpack#8074]
#I had issue of webpack like following

```
ERROR in ./css/style.css 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
```
this is my style.css
```

@charset "UTF-8";
@import url("https://fonts.googleapis.com/css?family=Oxygen:400,300,700");
* {
  outline: 0;
  margin: 0;
  padding: 0;
}
```
i think issue is from "@" of style.css.
 **how can i add some loader to resolve this issue?**
this is my webpack.config.js
```
const path = require('path');
module.exports = {
    entry: './src/index.js',
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'bundle.js'
    },
    module: {
        rules: [
            {
                test: /\.css$/,use: [ 'style-loader', 'css-loader' ],
                test: /\.(png|jpg|gif)$/,use: [ 'url-loader' ]
            }
        ]
    }
};

```

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
