### ISSUE TITLE
HMR: Pass downstream updated dependencies to accept()

### ISSUE THREAD

**Issue by Sebazzz** [webpack/webpack#8075]
## Feature request

**What is the expected behavior?**
HMR should provide the information which modules are outdated, even if those modules are indirectly loaded (loaded by the dependency of the current module).

**What is motivation or use case for adding/changing the behavior?**
Core problem: It is not always feasible to handle module reloads in the dependent module, but only in a few modules upstream. The modules upstream do not have the information they need to check which downstream modules have changed and currently need to workaround in alternative means.

For instance: I develop a small SPA in which the "page" modules themselves carry the `import()` template that is applied in the DOM. If a page template is changed, and the page module does not handle the update, the update bubbles up to the page loader. The page loader can't tell whether page module itself or the page template (that has been imported by the page module) has changed. Currently need to work around by checking whether the exported template in the page module has changed compared to the current loaded template, but this is cumbersome.

**How should this be implemented in your opinion?**
The hot module replacement calls the `accept()` callback function. The accept callback function currently retrieves one parameter: The name of the upstream module. The accept callback should be called with a second parameter: an array `string[]` of the upstream modules that are outdated. This allows the downstream module to do a selective replacement of sub dependencies.

**Are you willing to work on this yourself?**
Yes, if you give me some pointers.

**Comment by sokra** [comment]
I'm not sure if this behavior makes sense. It kind of breaks encapsulating of the module (i. e. the "page").

Even if you would have this argument, it would be a opaque module id in production and you can't do much with it.

**Comment by Sebazzz** [comment]
This is for development purposes, as is HMR.

**Comment by Sebazzz** [comment]
Any comments?
