### ISSUE TITLE
Did rules include/exclude behavior change in Webpack 4?

### ISSUE THREAD

**Issue by martpie** [webpack/webpack#8077]
Hello,

(If you think the problem is not coming from Webpack, feel free to close this directly)

This is not a bug report (I'm pretty sure it's not), nor a feature request.

I am the maintainer of a [Next.js plugin](https://github.com/martpie/next-plugin-transpile-modules), basically, it allows a Next app to transpile on-demand modules from node_modules (in case of a local TypeScript library for example) by specifying the name of those modules in Next's config file.

Since Next 7.0 (and their jump to Webpack 4), this plugin does not work anymore. I have tried a loooot of different things, but I still can't figure out if the problem comes from the Loader or Webpack, and maybe some one here can help me.

The error is quite simple: the modules are just not correctly transpiled:

```
Syntax Error: SyntaxError: C:\...\website\node_modules\shared\utils\calc.ts: Unexpected token, expected "," (1:21)

> 1 | export const add = (a: number, b: number) => a + b;
    |                      ^
  2 | export const substract = (a: number, b: number) => a - b;
  3 |

```

Basically, I have the following in the generated Webpack config:

- `resolve.symlinks` is set to `false`

```
// Rules...
...
{
   test: /\.(ts|tsx)$/,
   include: ['C:\\...\\website'],
   exclude: /node_modules/, // HERE
   use: {
    loader: 'next-babel-loader',
   }
  },
  {
   test: /\.+(js|jsx|ts|tsx)$/,
   loader: {
    loader: 'next-babel-loader',
   },
   include: [/shared(?!.*node_modules)/] // HERE
  }
```

My question now: do we agree that every TS file from `node_modules/shared` should be transpiled with `next_babel_loader`? regardless of the first `exclude` excluding the whole `node_modules` directory. 

The doc is a bit unclear (or I did not find the correct info) on how things actually "happen" at this level.

If the answer is yes, then the problem is probably coming from Next.js itself, and I will know where to look for, because I have spent hours on this issue without managing to resolve it.

The whole plugin file is [here](https://github.com/martpie/next-plugin-transpile-modules/blob/master/index.js) for those interested.

best  🙌

**Comment by sokra** [comment]
Rules are independent from each other. The second rule doesn't care about the first one.

You problem could be related to a different babel config used. Not sure...

**Comment by martpie** [comment]
Thank you very much, I guess something is wrong with Next's babel-loader then.
