### ISSUE TITLE
Webpack doesn't check for "index.js" in relative imports

### ISSUE THREAD

**Issue by appsforartists** [webpack/webpack#808]
Consider the following `index.js` file:

```javascript
var Immutable = require("immutable");

module.exports = Immutable.List(
  [
    "models",
    "actionsForRouterState",
    "definitions",
  ]
).toMap().mapEntries(
  ([i, name], _) => [name, require(`./${ name }`)]
).toObject();
```

It compiles to this:
```javascript
/* 390 */
/*!********************************************************************!*\
  !*** /Users/bresimpson/Projects/project-name/~/project-name-data/src ^\.\/.*$ ***!
  \********************************************************************/
/***/ function(module, exports, __webpack_require__) {

    var map = {
        "./actionsForRouterState": 257,
        "./actionsForRouterState.js": 257,
        "./definitions/CategoryTree": 143,
        "./definitions/CategoryTree.js": 143,
        "./definitions/index": 87,
        "./definitions/index.js": 87,
        "./definitions/mixins/getFromAPI": 88,
        "./definitions/mixins/getFromAPI.js": 88,
        "./index": 144,
        "./index.js": 144,
        "./models/CategoryModel": 89,
        "./models/CategoryModel.js": 89,
        "./models/ProductModel": 90,
        "./models/ProductModel.js": 90,
        "./models/index": 91,
        "./models/index.js": 91
    };
    function webpackContext(req) {
        return __webpack_require__(webpackContextResolve(req));
    };
    function webpackContextResolve(req) {
        return map[req] || (function() { throw new Error("Cannot find module '" + req + "'.") }());
    };
```

which throws `Cannot find module './models'.`  The above code works in io.js.  It can be made to work in Webpack by using this less DRY (and more explicit) version:

```javascript
module.exports = {
  "actionsForRouterState": require("./actionsForRouterState"),
  "models":                require("./models/index.js"),
  "definitions":           require("./definitions/index.js"),
};
```

Can the `map` be altered such that `"./models": 91`?

**Comment by jhnns** [comment]
I don't think that webpack should support dynamic requires any further... ES6 modules won't support them either [for well reasons](http://calculist.org/blog/2012/06/29/static-module-resolution/).

**Comment by appsforartists** [comment]
I wouldn't go so far as to call this a dynamic require.  `require(environment + ".settings.js")` would be a dynamic require.  This is simply a bug.

The `require` interface is well-defined and locked.  Part of that specification is that the contents of any folder can be enumerated in an `index.js` file, which [should be loaded if that folder is imported](https://iojs.org/api/modules.html#modules_folders_as_modules).

The correct implementation would be to observe that a path resolves to a folder, to check it for an `index.js`, and to rewrite the path to be `module/index.js` before passing it through the rest of the workflow.  Since the current implementation relies on this map, the easiest solve would just be to add `index.js` to each entry in the map (the same way that `.js` is added now).  

In any case, the `require` implementation should be fixed to correctly support `index.js` to maintain compatibility with the `npm` ecosystem.

**Comment by appsforartists** [comment]
After rereading the original post, I see why you're calling it a dynamic require.  DRYing it out did make it a bit dynamic, even if it can still be statically analyzed.

The real pain point I was trying to avoid is all this repetition:

```javascript
module.exports = {
  "thing1":   require("./thing1"),
  "thing2":   require("./thing2"),
  "thing3":   require("./thing3"),
  "thing4":   require("./thing4"),
  "thing5":   require("./thing5"),
  "thing6":   require("./thing6"),
  "thing7":   require("./thing7"),
}
```

It'd be great if I could just introspect the filesystem and export every file in a folder without manually writing an index, but that would be much more dynamic (and harder for Webpack to support without some feature development).  Perhaps another tool should be created to automate the maintenance of `index.js` files.

**Comment by sokra** [comment]
> Perhaps another tool should be created to automate the maintenance of index.js files.
