### ISSUE TITLE
Error while building project

### ISSUE THREAD

**Issue by allesan** [webpack/webpack#8080]
# Bug report

**What is the current behavior?**
When building my vue.js project I get

`(node:7019) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): CssSyntaxError: /home/drazen/dev/vue/backend/static/css/app.9f808bd91627fd4c6a24.css:1:22: Unknown word`
`(node:7019) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Although this project used to build just fine, two days ago.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Successfull build.

**Other relevant information:**
webpack version:  4.19.1
Node.js version: v8.9.3
Operating System: Linux
Additional tools: None

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.
