### ISSUE TITLE
Custom logic for ProgressPlugin percentage calculation

### ISSUE THREAD

**Issue by smelukov** [webpack/webpack#8088]
## Feature request

**What is the expected behavior?**

Ability to modify `ProgressPlugin` percentage value, in other words: apply a custom logic to percentage calculation (e.g. get a percentage by `built entry points`/`total entry points`)

**What is motivation or use case for adding/changing the behavior?**

We have many modules (over 9k) splitted into many entry points.
Current `ProgressPlugin` implementation is useless for our project because after some moment it shows the same percentage value (~67-69%) but in fact, only ~20% of modules were built.

![webpack stats](https://user-images.githubusercontent.com/6654581/46043083-b59e5680-c11f-11e8-88ba-f425eb5cddc6.gif)

**How should this be implemented in your opinion?**

I think that `ProgressPlugin` should do something like 
```js
const handler = wrapHandler(this.handler || createDefaultHandler(this.profile));
// ...
function wrapHandler(wrapped) {
  return (percentage, msg, ...args) {
      // compilation.hooks.progress - the SyncWaterfallHook
      const newProgress = compilation.hooks.progress.call(percentage, msg, ...args);
      wrapped(newProgress.percentage, newProgress.msg, ...newProgress.args);
  }
}
```

and the customization is something like
```js
compilation.hooks.progress.tap((percentage, msg, ...args) => {
  percentage = percentage < 0.7 ? (100 / totalEntrypoint * builtEntryPoints) : percentage;
  return { percentage, msg, args };
})
```

**Are you willing to work on this yourself?**
yes

**Comment by sokra** [comment]
There is a "magic" value in the ProgressPlugin, but you are welcome to send a PR to make it configurable. Allow options objects instead of adding an additional parameter.

**Comment by sokra** [comment]
btw. entrypoints are build in parallel, so your idea probably won't work.

**Comment by sokra** [comment]
https://github.com/webpack/webpack/blob/5c5e902c8e89afeb51ad130f12a908b89d627fc5/lib/ProgressPlugin.js#L98

**Comment by smelukov** [comment]
👌 will see what we can do

**Comment by smelukov** [comment]
Sent PR 😄
