### ISSUE TITLE
When compiling bootstrap.less how to put glyphicons in another folder?

### ISSUE THREAD

**Issue by ruifortes** [webpack/webpack#809]
I'm using the less-loder and ExtractTextPlugin to compile bootstrap and url-loader to extract all fonts inside.
Is there a away to define a different output for the font files?

**Comment by ruifortes** [comment]
Ok...got it. Loaders accept query parameters so...

```
      {
        test: /\.(otf|eot|svg|ttf|woff|woff2)$/,
        loader: 'url-loader?limit=10000&name=./public/fonts/[name].[ext]'
      }
```

**Comment by jhnns** [comment]
Self-solving issues :+1:
