### ISSUE TITLE
More going on with `mode: "development"` then in the docs!

### ISSUE THREAD

**Issue by mrichmond** [webpack/webpack#8091]
# Bug report

**What is the current behavior?**
These two configuration produce very different results, including wildly different bundle sizes, that are not documented properly or misleading in the [documentation](https://webpack.js.org/concepts/mode/#mode-development). I believe `mode: "development"` is also setting some optimization config parameters that prevent minification, but it's not documented. At minimum can the docs be updated to reflect exactly what mode is doing?

```
module.exports = {
  mode: "development
}
```

```
module.exports = {
  devtool: 'eval',
  plugins: [
    new webpack.NamedModulesPlugin(),
    new webpack.NamedChunksPlugin(),
    new webpack.DefinePlugin({ "process.env.NODE_ENV": JSON.stringify("development") }),
  ]
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Try and replicate `mode: "development"` based on the [documentation](https://webpack.js.org/concepts/mode/#mode-development). Note the difference in package sizes and minification.

**What is the expected behavior?**
The documentation should be accurate. I should be able to replicate whatever `mode: "development"` is doing. Documentation:
https://webpack.js.org/concepts/mode/#mode-development

**Other relevant information:**
webpack version:  4.16.2
Node.js version: 9.8.0
Operating System: MacOS High Sierra 10.13.6
Additional tools:

**Comment by montogeek** [comment]
@webpack-bot move to webpack/webpack.js.org
