### ISSUE TITLE
Unexpected behavior with loader dependencies

### ISSUE THREAD

**Issue by s-panferov** [webpack/webpack#810]
I have been writing a custom loader plugin for TypeScript language and I have fond some unexpected behavior in cache invalidation. 

I have such dependency structure (`=>` means `addDependency` call):

```
app.ts => fake/index.ts => fake/auth.ts
```

In watch mode after I update `fake/index.ts` I have:

```
Hash: 7db881429d4b1c229891
Version: webpack 1.5.3
Time: 784ms
chunk    {0} app.js, app.js.map (app) 424736 {1}
    [0] ./src/app/app.ts 2105 {0} [built]
    [1] ./src/fake/index.ts 220 {0} [built]
     + 82 hidden modules
chunk    {1} vendor.js, vendor.js.map (vendor) 0
webpack: bundle is now VALID.
```

In watch mode after I update `fake/auth.ts` I have:

```
webpack: bundle is now INVALID.
Hash: 7db881429d4b1c229891
Version: webpack 1.5.3
Time: 751ms
chunk    {0} app.js, app.js.map (app) 424736 {1}
    [1] ./src/fake/index.ts 220 {0} [built]
   [23] ./src/fake/auth.ts 1096 {0} [built]
     + 82 hidden modules
chunk    {1} vendor.js, vendor.js.map (vendor) 0
webpack: bundle is now VALID.
```

**Expected:** I expect webpack to invalidate the whole chain when I update `fake/auth.ts`. 
**Result:** Webpack invalidates only direct dependencies.

Is this behavior by design?

**Comment by sokra** [comment]
addDependency is not recursive. In fact you doesn't pass another module. The parameter is just a simple file path.

A loader must tell about all files it depend on.

**Comment by s-panferov** [comment]
@sokra so it is by design, right? It is OK, I just wanted to ask if it is not a bug or TODO. I can live with it.

**Comment by sokra** [comment]
Are you infering typeinformation from dependencies?

**Comment by s-panferov** [comment]
Yes, I need this for the watch support in [awesome-typescript-loader](https://github.com/s-panferov/awesome-typescript-loader). In TypeScript each file can have a big *tree* of dependencies. I have resolved this problem by making my own dependency manager which I use to flatten the tree before `addDependency` calls. Also this manager helps me to show the reason of recompilation (is shows actual changed subtree). I use this for debug.

**Comment by sokra** [comment]
yeah, than you need to call addDependency for each file in the tree of dependencies as the result depends on all this files.
