### ISSUE TITLE
NormalModuleReplacementPlugin: newResource is not resolved relative to the previous resource

### ISSUE THREAD

**Issue by x-yuri** [webpack/webpack#8105]
# Bug report

**What is the current behavior?**

The [docs][1] says:

[1]: https://github.com/webpack/webpack.js.org/blob/v3.11.0/src/content/plugins/normal-module-replacement-plugin.md

> If newResource is relative, it is resolved relative to the previous resource.

It probably appeals to [the following lines][2]. But `afterResolve` hook is called only if the request was resolved [successfully][3]. And generally, the request is resolved relative to a file that made the request (its directory). So either documentation is wrong, or... `NormalModuleReplacementPlugin` should temporarily change context? Doesn't seem like an easy thing to do. And most likely is out of the context of the plugin.

[2]: https://github.com/webpack/webpack/blob/v4.20.2/lib/NormalModuleReplacementPlugin.js#L38-L41
[3]: https://github.com/webpack/webpack/blob/v4.20.2/lib/NormalModuleFactory.js#L130-L138

**If the current behavior is a bug, please provide the steps to reproduce.**

You can, for instance, take the [Tour of Heroes][4], and try to build it with the following config:

```js
const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = (env, args) => ({
    entry: [
        './src/polyfills.ts',
        './src/styles.css',
        './src/main.ts',
    ],
    module: {
        rules: [{
            test: /\.html$/,
            loader: 'raw-loader',
        }, {
            test: /\.css$/,
            include: path.resolve('src/styles.css'),
            use: [
                'style-loader',
                'css-loader',
            ],
        }, {
            test: /\.css$/,
            include: path.resolve('src/app'),
            use: [
                'raw-loader',
            ],
        }, {
            test: /\.ts$/,
            use: [
                'ts-loader',
                'angular2-template-loader',
            ],
        }, {
            // https://github.com/angular/angular-cli/blob/v6.2.2/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts#L292-L297
            // Mark files inside `@angular/core` as using SystemJS style dynamic imports.
            // Removing this will cause deprecation warnings to appear.
            test: /[\/\\]@angular[\/\\]core[\/\\].+\.js$/,
            parser: { system: true },
        }],
    },
    resolve: {
        extensions: ['.ts', '.js'],
    },
    plugins: [
        new webpack.ContextReplacementPlugin(
            /(.+)?angular(\\|\/)core(.+)?/
        ),
        new HtmlWebpackPlugin({
            template: './src/index.html',
        }),
    ].concat(args.mode == 'production' ? [
        new webpack.NormalModuleReplacementPlugin(
            /^\.\/environments\/environment$/,   // src/main.ts
            './environment.prod.ts',
        ),
    ] : []),
    devServer: {
        historyApiFallback: true,
    },
});
```

Additional dependencies,

```
$ npm i angular2-template-loader@0.6.x css-loader@1.x html-webpack-plugin@3.x \
raw-loader@0.5.x style-loader@0.23.x ts-loader@5.x uglifyjs-webpack-plugin@2.x \
webpack@4.x webpack-cli@3.x
```

Then `./node_modules/.bin/webpack-dev-server --mode production`, and in the shell you see,

> Module not found: Error: Can't resolve './environment.prod.ts' in '/srv/http/s3/src'

Without `NormalModuleReplacementPlugin` in the Chrome's console you get,

> Angular is running in the development mode. Call enableProdMode() to enable the production mode.

[4]: https://github.com/johnpapa/angular-tour-of-heroes

**What is the expected behavior?**

No above-mentioned error in the shell and no message in the Chrome's console.

**Other relevant information:**
webpack version:  4.19.1
Node.js version: 10.9.0
Operating System: Arch Linux
Additional tools: head :)

**Comment by sokra** [comment]
Best try to avoid the `NormalModuleReplacementPlugin`. It's very old and has issues.

To replace a file use `resolve.alias`

``` js
resolve: {
  alias: {
    [path.resolve(__dirname, "src/environments/environment")]:
      path.resolve(__dirname, "src/environments/environment.prod.ts")
  }
}
```

---

Also a good option:

``` js
resolve: {
  extensions: ['.prod.ts', '.ts', '.js'],
}
```
