### ISSUE TITLE
Webpack dependencies fail with npm linked package.

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#811]
My project depends on a package that works perfectly when installed normally, but when I `npm link` that package for local development, webpack fails finding dependencies like so:

```
[14:38:15] Version: webpack 1.5.3
                      Asset     Size  Chunks             Chunk Names
    tcc-ip-client.bundle.js  2690831       0  [emitted]  client
tcc-ip-client.bundle.js.map  3223307       0  [emitted]  client

ERROR in ../blah/src/js/utils/features.js
Module not found: Error: Cannot resolve module 'foobar/src/js/utils/endpoint' in /Users/josephpea/src/blah/src/js/utils
 @ ../blah/src/js/utils/features.js 10:0-109:2
```

**Comment by trusktr** [comment]
100% certain these errors happen only after I've npm linked that package in the project.

**Comment by trusktr** [comment]
Any info I can provide? I can't really provide access to the repo I'm linking because it's internal/private, but maybe there's some useful specific info I can provide?

**Comment by sokra** [comment]
http://webpack.github.io/docs/troubleshooting.html#npm-linked-modules-doesn-t-find-their-dependencies

**Comment by trusktr** [comment]
Ah, ok. Thanks!! I would've had no idea!

**Comment by trusktr** [comment]
@sokra This problem isn't intuitive at all. For example, it just happened to me again: https://github.com/krasimir/cssx/issues/15

**Comment by sokra** [comment]
for loaders the behavior was changed to webpack 2. They now resolve relative to the configuration file instead of relative to the affected module

**Comment by sokra** [comment]
also related https://github.com/webpack/webpack/issues/2937

**Comment by SpaceK33z** [comment]
Closing this since it appears to have been fixed in webpack 2. @trusktr, if you still have this issue in webpack 2, please re-open.

**Comment by MatteoWebDesigner** [comment]
Hi I am using webpack 2 and I cannot figure out why I am having this issue:

ERROR in ./src/index.js
Module not found: Error: Can't resolve 'webpack-test-import' in '/user/test-webpack/src'
 @ ./src/index.js 7:25-55
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./index.js

here the webpack config

```
import path from 'path';
import HtmlWebpackPlugin from 'html-webpack-plugin';

export default {
    context: path.resolve(__dirname, 'src'),
    entry: './index.js',
    output: {
        path: path.resolve(__dirname, 'build'),
        filename: 'bundle.js',
        chunkFilename: 'bundle-[id].js'
    },
    resolve: {
        modules: [path.resolve(__dirname, './node_modules')]
    },
    module: {
        rules: [{
            test: /\.js$/,
            exclude: /node_modules/,
            use: {
                loader: 'babel-loader',
                options: {
                    cacheDirectory: 'cache/'
                }
            }
        }]
    },
    plugins: [
        new HtmlWebpackPlugin({
            template: './index.html',
            minify: {
                collapseWhitespace: true
            }
        }),
    ],
    devtool: "cheap-eval-source-map",
    devServer: {
        contentBase: path.join(__dirname, "build"),
        compress: true,
        port: 8080,
        open: true
    }
};
```

index.js
```
import internalModule from './module.js';
import externalModule from 'webpack-test-import';

console.log('internal import, ' + internalModule);
```

**Comment by septagram** [comment]
@SpaceK33z no it's not fixed, having the same problem here.
```
ERROR in ../react-calendar-component/lib/Calendar.js
Module not found: Error: Can't resolve 'react' in 'd:\Dropbox\Code\react-calendar-component\lib'
```
Worse yet, the [workaround](http://webpack.github.io/docs/troubleshooting.html#npm-linked-modules-doesn-t-find-their-dependencies) doesn't work anymore:
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.resolve has an unknown property 'fallback'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }
 - configuration.resolveLoader has an unknown property 'fallback'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }
```

**Comment by damianobarbati** [comment]
Same here with webpack 2.x, npm-link'ed modules hangs compilation...

**Comment by miketeix** [comment]
Same here, using yarn link in my case

**Comment by erquhart** [comment]
+1

**Comment by thescientist13** [comment]
thanks @erquhart , that helped resolve the issue for me!

**Comment by joaoreynolds** [comment]
Turning off symlink resolution also makes it so webpack can't watch for changes in the linked dependency :( Any other solutions?

**Comment by jcjolley** [comment]
Still an issue.

**Comment by mesqueeb** [comment]
Actually I'm still having this problem, where I do `npm link a-package` to another one i'm working on. The symlink works fine but some dependencies inside that linked package don't get resolved...
It's on Webpack": "4.8.3".

Any ideas?

**Comment by yuvke** [comment]
@mesqueeb, I also still experienced this. Tried to play with the `symlinks` property but it didn't help.

What I ended up doing is looking through the `node_modules` folder, and if a folder was in fact a symlink, I would add the resolved address + `node_modules` to the `modules` array.

For example something like this:
``` javascript
const path = require('path');
const projectPath = 'full/path/to/project'
const projectNodeModulesPath = path.resolve(projectPath, 'node_modules');
const modules = [ projectNodeModulesPath ];
    
await Promise.all((await fse.readdir(projectNodeModulesPath)).map(async el => {
    const modulePath = path.resolve(projectNodeModulesPath, el);
    if ((await fse.lstat(modulePath)).isSymbolicLink()) {
        const realModulePath = path.resolve(await fse.realpath(modulePath), 'node_modules');
        resolves.push(realModulePath);
    }
}));
```

**Comment by mesqueeb** [comment]
Yeah, what I do is usually `npm i` all dependencies of the package I'm linking to in the package I'm working on. Works like a charm.

**Comment by diachedelic** [comment]
I adapted @yuvke 's solution, making it sync and supporting scoped packages.  [See this gist for a webpack config example](https://gist.github.com/diachedelic/6ded48f5c6442482fa69e91ec7ab1742).

**Comment by chovy** [comment]
@diachedelic that doesn't work for me, same error.

**Comment by diachedelic** [comment]
@chovy could you try printing the results of `findLinkedModules` to console, and comparing it with the pathname in the error message?

**Comment by chovy** [comment]
i goofed. i didn't know i had to build the library first. now it works fine w/o any changes.

**Comment by victmo** [comment]
@diachedelic solution worked for me as well

**Comment by raffomania** [comment]
How is this issue still closed when the only solution is a noisy workaround?

**Comment by xthilakx** [comment]
@raffomania Set `resolve.symlinks` to false. By default, it's set to true in webpack4.  

https://webpack.js.org/configuration/resolve/#resolve-symlinks

**Comment by fabb** [comment]
@xthilakx that‘s not an option in the case HMR is needed where webpack needs to watch updates to the linked package. This is necessary when developing a library together with the client app.

https://github.com/webpack/webpack/issues/811#issuecomment-317875352

**Comment by J-Rojas** [comment]
This issue should be reopened as it is not properly solved. A module that is linked cannot be debugged with symlinks disabled.

**Comment by evenfrost** [comment]
Any update on this?

**Comment by senikiti** [comment]
In my case following webpack config worked:
for development mode - `resolve: {  modules: [path.resolve("./node_modules")] },`
for production mode - `resolve: { symlinks: false, modules: [path.resolve("./node_modules")] }`
Note, I have disabled babel for development and HMR.
Also my imported module was in ES6 (not transpiled).

**Comment by xthilakx** [comment]
> @xthilakx that‘s not an option in the case HMR is needed where webpack needs to watch updates inside of the linked package. This is necessary when developing a library together with the client app.
> 
> [#811 (comment)](https://github.com/webpack/webpack/issues/811#issuecomment-317875352)

@fabb I understand that it would be awesome to HMR from the linked package, but you should reconsider your development setup, if symlinking packages is the only for you to test your lib.

**Comment by fabb** [comment]
@xthilakx I want to develop my lib together with my main app in tandem because it would be faster to get all the requirements right. I can develop the library on its own, and I have Storybook and jest there, but when developing new features for my app, it‘s easy to forget about an edge case, and then I have to build another package version with the fix. And yes, I already have building a new package version optimized to a single click, but it‘s still another roundtrip and takes time to build and then install in my app.

**Comment by xthilakx** [comment]
@fabb I have exactly the same setup as you (Storybook/Jest), but I do not develop my components with projects symlinked using `npm link`. Of course, it is important to test it end to end before you ship your code or publish it to npm registry, but you can do that during the testing phase (before you commit your changes)

Symlinking has other quirks too, [such as this](https://github.com/yarnpkg/yarn/issues/1761#issuecomment-259706202), so I use [verdaccio](https://verdaccio.org/) as a local npm registry for testing.

Symlinking to develop locally defeats the purpose of using tools like Storybook, IMHO.

**Comment by fabb** [comment]
@xthilakx don‘t get me wrong, I love developing my components with storybook, and I would keep doing so. HMR with storybook is much quicker than with my large app. I would just like to be able to quickly try out some changes of the components in my main app without releasing a package version. I use Verdaccio too, since we release our components only for internal use (not open source).
