### ISSUE TITLE
Combination of `output.libraryTarget: 'window'` and `output.library: string[]` gives a `window[undefined]` as result.

### ISSUE THREAD

**Issue by dthpth** [webpack/webpack#8111]
# Bug report

**What is the current behavior?**

Combination of `output.libraryTarget: 'window'` and `output.library: string[]` gives an erroneous rusult:
```
window[undefined] = 
...
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const config = {
  mode: 'development',
  entry: {
    templates: './tpl.js'
  },
  output: {
    path: `${__dirname}/build`,
    filename: '[name].js',
    library: ['MyLib', '[name]'],
    libraryTarget: 'window'
  }
};
```

**What is the expected behavior?**

This config should generate output like this:
```
window["MyLib"] = window["MyLib"] || {}; window["MyLib"]["templates"] =
...
```

**Other relevant information:**
webpack version:  4.20.2
Node.js version: v10.7.0
Operating System: win10

Looks like the issue is here: https://github.com/webpack/webpack/blob/master/lib/LibraryTemplatePlugin.js#L28-L29
```
const accessorAccess = (base, accessor, umdProperty, joinWith = "; ") => {
	const normalizedAccessor =
		typeof accessor === "object" ? accessor[umdProperty] : accessor;
	const accessors = Array.isArray(normalizedAccessor)
		? normalizedAccessor
		: [normalizedAccessor];
```
if `accessor` parameter is an array it passes the `typeof accessor === "object"` condition anyway (thanks JS).

PS.
Sorry for not sumbiting a PR - I am not so familar with github processes.

**Comment by sokra** [comment]
https://github.com/webpack/webpack/blob/df7da2cdd58e9534ae5e73a25e9c064b02c4d625/lib/LibraryTemplatePlugin.js#L28-L29

Yes you are right this is the bug.

Need to be changed to 

``` js
 const normalizedAccessor = 
 	typeof accessor === "object" && !Array.isArray(accessor) ? accessor[umdProperty] : accessor; 
```

and a test need to be added.

Please send a PR. Or somebody else.

**Comment by evilebottnawi** [comment]
Fixed https://github.com/webpack/webpack/pull/8122
