### ISSUE TITLE
[HMR] Update check failed: ReferenceError: installedChunks is not defined

### ISSUE THREAD

**Issue by zhiyingzzhou** [webpack/webpack#8114]
# Bug report

**What is the current behavior?**
webpack HotModuleReplacementPlugin report error: 
[HMR] Update check failed: ReferenceError: installedChunks is not defined

![image](https://user-images.githubusercontent.com/16408285/46256062-0a532000-c4d8-11e8-9f37-169a3a662a98.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

webpack.config.js
```
   module.exports = {
    entry: {
        'demo1': '../demo1/src/entry.js',
        'demo2': '../demo2/src/entry.js',
        'demo3': '../demo3/src/entry.js'
    },
    output: {
        path: path.resolve(__dirname, '..', spa),
        filename: '[name]/assets/scripts/build' + '.js',
        chunkFilename: '[name].[id].chunk.js',
        publicPath: '/' + spa + '/',
        hotUpdateChunkFilename: './.temp/[id].[hash].hot-update.js',
        hotUpdateMainFilename: './.temp/[hash].hot-update.json',
    },
    devServer: {
        "hot": true,
    },
    plugins: [
        new webpack.NamedModulesPlugin(),
        new webpack.HotModuleReplacementPlugin(),
    ],
}
```

**What is the expected behavior?**
fix error

**Other relevant information:**
webpack version:   v4.20.2
Node.js version:  v8.11.3
Operating System: macos high sierra 10.13.6
Additional tools: vscode

**Comment by davydhong** [comment]
I am getting the exact same warning. What was the fix?

**Comment by aztack** [comment]
I got the same error.

**Comment by ycr6708536** [comment]
I got the same error.
