### ISSUE TITLE
Config "extends"

### ISSUE THREAD

**Issue by artola** [webpack/webpack#8119]
# Bug report

**What is the current behavior?**
Using config "extends" with `webpack-cli` reports an invalid config, while it was supported before (e.g., webpack-command) and it is accordingly the [documentation](https://webpack.js.org/loaders/config-loader/#extending-configuration-files).

**If the current behavior is a bug, please provide the steps to reproduce.**
In documentation:
```
// webpack.config.js
module.exports = {
  extends: path.join(..., 'base-config.js'),
  name: 'dev'
````
My use case: 
```
module.exports = {
  extends: '@sl/rdk.webpack-preset-proactive',
};
```
Error:
```sh
yarn webpack

// => 
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
```

**What is the expected behavior?**

"extends" is pretty cool feature, it should just work without workarounds (e.g. `webpack-merge`).

**Other relevant information:**
webpack version:  ^4.20.2
Node.js version: v10.6.0
Operating System: OSX
Additional tools: NO

**Comment by sokra** [comment]
webpack-cli and webpack-command are different products, with different feature sets. I wouldn't consider this as bug.

You can propose this feature to webpack-cli, but do you really need that. This can be easily solved inside of your configuration file. Either with webpack-merge or in simple cases with:

``` js
module.exports = {
  ...require('@sl/rdk.webpack-preset-proactive'),
  /* ... */
}
```

Closing as it's the wrong repo

**Comment by evilebottnawi** [comment]
@artola Feel free to create issue in `webpack-cli` (looks `webpack-command` support this)
