### ISSUE TITLE
Provide plugin doesn't work with closure wrappers (IIFE)

### ISSUE THREAD

**Issue by jonjaques** [webpack/webpack#812]
Hello,

I have a dependency that is using a way too clever pattern of wrapping itself in a closure like so..

```javascript
// works
// var jQ = window.jQuery;
(function(window, document, undefined) {
  // doesn't work
  var jQ = window.jQuery;

  jQ(document).on('ready', function() {
    alert('works');
  });
})(window, document);
```

```javascript
plugins: [
  new webpack.ProvidePlugin({
    'window.jQuery': 'jquery'
  })
]
```

I'm trying to use the ProvidePlugin to patch that up, but having troubles. I have a work around in place using the imports loader, so not critical - just thought I'd report it.

Here's a [test case](https://github.com/jonjaques/webpack-provide-iife-testcase). `npm install && npm test`

**Comment by jhnns** [comment]
You're right, that looks like a bug. It seems like Esprima isn't recognizing the IIFE part as expression (how can that be?)...

**Comment by jonjaques** [comment]
It seems like 2.0 will read it? But looks like webpack uses 1.2. However I have no clue about the intricacies of parsing :D

http://esprima.org/demo/parse.html?code=(function(window%2C%20document%2C%20undefined)%20%7B%0A%20%20var%20jq%20%3D%20window.jQuery%3B%0A%20%20%0A%20%20jq('string')%3B%0A%0A%7D)(window%2C%20document)%3B

**Comment by sokra** [comment]
It's a bug but not related to esprima.
