### ISSUE TITLE
More useful stats output

### ISSUE THREAD

**Issue by petermikitsh** [webpack/webpack#8129]
## Feature request

When viewing the stats.json output of one of my bundles, nearly all of my files are grouped as single entity. That makes it challenging to analyze the bundle to see which files in the grouping are the largest.

When viewing my stats.json in https://chrisbateman.github.io/webpack-visualizer/, nearly 95% of my entry point is 106 files reported as a single one.

![screen shot 2018-10-02 at 10 54 54 am](https://user-images.githubusercontent.com/1571918/46376080-f0394f00-c649-11e8-85da-9edb866ad178.png)

Likewise, here's the analogous output from the official analyser (http://webpack.github.io/analyse/):

<img width="882" alt="screen shot 2018-10-02 at 1 01 36 pm" src="https://user-images.githubusercontent.com/1571918/46376203-4a3a1480-c64a-11e8-8956-1024545fd266.png">

**What is the expected behavior?**

More granular output. Each of these 106 files would be reported separately, so I had could see the size of each contributing file to the overall bundle size. As is, these visualizations don't help me form actionable decision to address bundle size.

**What is motivation or use case for adding/changing the behavior?**

As explained above, I want to know how much each individual file is contributing to my bundle. Helps to inspect where the low-hanging fruit exists for bundle size optimization. 

**How should this be implemented in your opinion?**

Maybe a way to control how things get grouped? Ideally, each file would be reported separately.

**Are you willing to work on this yourself?**

I don't know enough about webpack's implementation to know where to start.

**Comment by petermikitsh** [comment]
It appears that setting `{optimization.concatenateModules: false}` fixes the visualization output, but at the expense of increasing my bundle size from 107kb to 122kb. Is it possible to have the best of the both worlds? (small bundle size via module concatenation + more granular stats reporting)

**Comment by sokra** [comment]
webpack reports the nested modules (with sizes) in the stats. You can file an issue supporting this in webpack-analyser.

**Comment by petermikitsh** [comment]
Thanks for that info @sokra. Closing this story.
