### ISSUE TITLE
Class name mangled with default settings

### ISSUE THREAD

**Issue by LemonPi** [webpack/webpack#8132]
# Bug report

**What is the current behavior?**
webpack is mangling class names.

```javascript
export class Test {
    constructor() {
        this.test = 1;
    }
}

// importing somewhere else
Test.name; // should be "Test", but is instead some mangled character like "n"
Test.prototype.constructor.name; // similar to above
```

**If the current behavior is a bug, please provide the steps to reproduce.**
See minimum [demonstrating repo](https://github.com/LemonPi/issues_webpack_classname)

**What is the expected behavior?**

```javascript
// importing somewhere else
Test.name === "Test";
Test.prototype.constructor.name === "Test";

<!-- "It should work" is not a helpful explanation -->
<!-- Explain exactly how it should behave -->

**Other relevant information:**
webpack version:  4.20.2
Node.js version: 8.9.3
Operating System: Windows 10
Additional tools: webpack-dev-server 3.1.9

**Comment by sokra** [comment]
yes. Do not rely on class and function names!

Or disable the optimization (mangle), but it will increase bundle size.

**Comment by LemonPi** [comment]
For posterity the configs that solved this:

package.json
```
  "devDependencies": {
    "@babel/core": "^7.1.2",
    "@babel/preset-env": "^7.1.0",
    "babel-loader": "^8.0.4",
    "uglifyjs-webpack-plugin": "^2.0.1",
    "webpack": "^4.20.2",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.9"
  }
```

webpack.config.js
```javascript
    optimization: {
        minimizer  : [
            new UglifyJSPlugin({
                cache        : true,
                parallel     : true,
                uglifyOptions: {
                    compress: true,
                    ecma    : 6,
                    mangle  : false
                },
                sourceMap    : true
            })

        ]
    },
    module   : {
        rules: [
            {
                test   : /\.js$/,
                include: [/src/],
                use    : [
                    {
                        loader : 'babel-loader',
                        options: {
                            presets: ['@babel/preset-env']
                        }
                    }
                ],
            },
        ]
    },
```

Babel is needed if you have ES6+ source because Uglify can only deal with ES5.

**Comment by kzc** [comment]
Rather than disabling `mangle` altogether, these uglify/terser options would produce smaller minified output:

```
- `keep_classnames` (default: `undefined`) - pass `true` to prevent discarding or mangling
  of class names.

- `keep_fnames` (default: `false`) - pass `true` to prevent discarding or mangling
  of function names.  Useful for code relying on `Function.prototype.name`. If the
  top level minify option `keep_classnames` is `undefined` it will be overridden with
  the value of the top level minify option `keep_fnames`.
```

However, be aware that webpack's scope hoisting has been known to rename symbols even with minification disabled: https://github.com/mishoo/UglifyJS2/issues/3015#issuecomment-375185061

**Comment by steffanboodhoo** [comment]
@LemonPi  I have a similar issue and tried your solution, however i am experiencing [this issue](https://github.com/webpack/webpack/issues/2972), how did you set up webpack to use UglifyJS only after babel transpiled
I checked your repo however it seems it was not updated with the solution

**Comment by LemonPi** [comment]
@steffanboodhoo I just updated the repo and confirmed the solution works: [demonstrating repo](https://github.com/LemonPi/issues_webpack_classname)

**Comment by steffanboodhoo** [comment]
Hey thanks, it was one of my node modules that needed trans-piling as well, and I had _exclude: /node_modules/,_ in my rules for the _babel-loader_ which was causing UglifyJS to throw the unexpected token

**Comment by nebosite** [comment]
I wish there was a global function to translate class names:  realClassName(MyType) => string
For dev the function just returns MyType.name.   For prod, the function looks up the name from a map produced by the  minifier.  That way we get a small bundle, but don't break when we move to prod.

**Comment by arthabus** [comment]
@nebosite depending on your goal you can actually build one. Not in webpack config, but in your code. In my case I needed to be able to distinguish between class types so the below was sufficient:

```
class MyClass {
    constructor(){
        createClassId()
    }
    createClassId(){
        if(!this.constructor.prototype._customClassId){
	    this.constructor.prototype.._customClassId = uuidv4() //you choose what you want this classId to be. Or have a look at nanoId which can produce shorter names
	}
    }
}
```

then new MyClass()._customClassId would be the same for the same class. And if, for example, you inherit from MyClass, the subclasses will also have the same _customClassId but different from what the parent class holds.
