### ISSUE TITLE
is externnals can be css files?

### ISSUE THREAD

**Issue by leeseean** [webpack/webpack#8136]
I want some css files to be external
`
module.exports = {
  //...
  externals: 'main.css'
};
`
will it work if I write like this?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by leeseean** [comment]
> It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

dev make it style, and prod make it css file

**Comment by evilebottnawi** [comment]
@leeseean what?
