### ISSUE TITLE
Documentation site - UglifyjsWebpackPlugin section after header not loading properly

### ISSUE THREAD

**Issue by clenondavis** [webpack/webpack#8137]
# Bug report
Hi, webpack team, thanks for your sharing your knowledge with the community.

**What is the current behavior?**
The Uglify Plugin Section not loading properly.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Go to the tab [guide/production/#minification](https://webpack.js.org/guides/production/#minification) 
2. Open the [UglifyJsPlugin link](https://webpack.js.org/plugins/uglifyjs-webpack-plugin/)
3. After the **UglifyjsWebpackPlugin** header, you will see the next section not loading properly

**What is the expected behavior?**
I do not know what should render in this section. This is a screenshot of the section, see below

<img width="1169" alt="screen shot 2018-10-03 at 7 54 02 am" src="https://user-images.githubusercontent.com/4239218/46415835-60e07a00-c6e3-11e8-9658-599fcedc44f0.png">

**Comment by evilebottnawi** [comment]
@webpack-bot move to webpack/webpack.js.org

**Comment by evilebottnawi** [comment]
@clenondavis Thanks for issue

**Comment by clenondavis** [comment]
Thanks @evilebottnawi . If i can help just ping me. Have a nice day
