### ISSUE TITLE
better stats warning output with --colors flag

### ISSUE THREAD

**Issue by benigeri** [webpack/webpack#814]
Is there anyway to customize / improve the outputs for warning and errors when the error flag is turned on? This is what my output currently looks like: 
![screen shot 2015-02-22 at 4 58 15 pm](https://cloud.githubusercontent.com/assets/1163920/6326392/1c5de620-bb06-11e4-8d4f-1f0ac290c2d3.png)

I'd like to get rid of the bolding, at least. But something like this would be ideal:
![screenshot](https://cloud.githubusercontent.com/assets/1163920/6326415/3d05b5c4-bb06-11e4-8adc-c794f8df5a41.png)

I'd really appreciate it if someone could point me in the right direction. I dug around the web pack source a bit but couldn't find anything. 

Thanks!

**Comment by sokra** [comment]
webpack is only responsible for the first line: `WARNING in ...`.
The remaining message is generated by the eslint-loader. Maybe you can pass a custom reporter there.

**Comment by benigeri** [comment]
Ah, thanks!
