### ISSUE TITLE
Probably bug in source code

### ISSUE THREAD

**Issue by dumistoklus** [webpack/webpack#8141]
# Bug report

**What is the current behavior?**
In this file https://github.com/webpack/webpack/blob/next/lib/webpack.js#L46 probably bug

**If the current behavior is a bug, please provide the steps to reproduce.**
Unnecessary "if"

**What is the expected behavior?**
I don't know

**Other relevant information:**
webpack version:  5 (next)

**Comment by montogeek** [comment]
Already fixed in another PR, I can't find it though.

**Comment by montogeek** [comment]
I found it, it was closed for some reason: https://github.com/webpack/webpack/pull/8127/files

**Comment by sokra** [comment]
It's for typing reasons. Typescript doesn't like the code when written the other way:

https://github.com/webpack/webpack/pull/8127#issuecomment-426387680
