### ISSUE TITLE
Export WebAssembly Globals as WebAssembly.Global objects

### ISSUE THREAD

**Issue by littledan** [webpack/webpack#8145]
## Feature request

**What is the expected behavior?**

According to tests such as https://github.com/webpack/webpack/blob/master/test/cases/wasm/imported-global-preserve-ordering/index.js , a Wasm global exported to JavaScript is exposed as a Number. However, the [Wasm/ESM integration proposal](https://github.com/WebAssembly/esm-integration/blob/e098188221887871410616ba1e186740c9d4aa86/proposals/esm-integration/README.md) specifies that a WebAssembly.Global object should be exported instead. (Probably WebAssembly.Global came out after webpack had already implemented its current logic, so the gap wouldn't be surpising.)

**What is motivation or use case for adding/changing the behavior?**

Compatibility with native Wasm/ESM interaction and other bundlers that might implement the proposed specification.

**How should this be implemented in your opinion?**

No opinion (I haven't found the code path responsible for the current behavior)

**Are you willing to work on this yourself?**

I'm not sure yet; I was planning on focusing on tests first.

Broader issue: https://github.com/webpack/webpack/issues/8144

**Comment by littledan** [comment]
The new WebAssembly.Global semantics don't seem to be implemented in Safari or Edge, and they are only shipped recently in Chrome 69 and Firefox 62. Seems like Node 10.11 uses V8 6.8, which doesn't support WebAssembly.Global, but instead uses the semantics that webpack tests use. I don't think it makes much sense to polyfill WebAssembly.Global during this current transition, but instead to forward through the export that comes from the underlying implementation.

I'm not sure if there's any particular change we would make in the implementation, maybe just the tests to permit *either* the bare number *or* WebAssembly.Global. I downloaded Node 11 nightly, which uses V8 7.0, and ran the tests that involved using an exported WebAssembly global. Indeed, the tests that failed were the ones checking the actual exported global value, since it changed from a Number to a WebAssembly.Global object, in an apparently spec-compliant way.

One test failed due to apparently invalid WebAssembly, which I noted at https://github.com/webpack/webpack/pull/7467/files#r223454525 . Once that's fixed, I'd be happy to upload a PR with updated tests, of this style (taking wasm/imported-global-preserve-ordering as an example):

```js
it("should preserve the ordering of globals", function() {
        return import("./module.wat").then(function(e) {
                if (WebAssembly.Global) {
                        expect(e.c.constructor).toBe(WebAssembly.Global);
                        expect(e.d.constructor).toBe(WebAssembly.Global);

                        expect(+e.c).toBe(3);
                        expect(+e.d).toBe(4);
                } else {
                        expect(e.c).toBe(3);
                        expect(e.d).toBe(4);
                }
        });
});
```

(This test passes on Node 11)

**Comment by xtuc** [comment]
>  I don't think it makes much sense to polyfill WebAssembly.Global during this current transition, but instead to forward through the export that comes from the underlying implementation.

While probably not many environement will have the bare numbers, it would be simple one our side to lift the values into a `WebAssembly.Global`.

**Comment by littledan** [comment]
Yeah, it sounds simple to make this polyfill work, but it's also hard for me to see the motivation for doing that.

**Comment by littledan** [comment]
OK, it seems like the main code change needed here would be to ensure that re-exported Wasm globals become WebAssembly.Global objects, not Numbers, in environments where WebAssembly.Global exists.

**Comment by sokra** [comment]
There are further changes needed for exporting (mutable) globals from wasm-to-wasm, but it makes sense to do other spec-related changes before that, because it will be easier then.

**Comment by xtuc** [comment]
This reminds me that we could reimplement the constant global import in Webpack using mutable ones, which would simplify the transformation a lot.

**Comment by littledan** [comment]
Be aware, there are still two browsers (Safari and Edge) which do not support mutable globals yet.

**Comment by sokra** [comment]
> This reminds me that we could reimplement the constant global import in Webpack using mutable ones, which would simplify the transformation a lot.

We need to do major changes here anyway, since the spec disallows importing globals from JS. This removes all of the problems we are solving and we can remove this feature and no longer need to do this special thing for globals.

**Comment by littledan** [comment]
@sokra I'm thinking we should revisit that decision to ban the import of globals and Numbers. My early draft revision of the spec is [here](https://github.com/littledan/esm-integration/blob/5f5aae04810f2b03144e75278ab50f4a095f28e2/proposals/esm-integration/README.md).

**Comment by sokra** [comment]
Your draft runs wasm instantiation in the evaluation phase. Afaik this is not something we can do without either using sync instantiate or allowing async operations in the ESM spec.

**Comment by littledan** [comment]
@sokra You're right. I think we'll have to revisit allowing async operations in the ESM spec. If we do this spec change, would it be feasible for webpack to implement it?

**Comment by sokra** [comment]
> If we do this spec change, would it be feasible for webpack to implement it?

It would be, but I have to note that I'm voting against such a ESM spec change.

**Comment by littledan** [comment]
@sokra Could you explain the motivation for that vote?

**Comment by littledan** [comment]
What's the current CJS transpilation strategy for Wasm modules?

**Comment by littledan** [comment]
Oops, maybe that patch should not have said "fixes". Does it pass in Node 11?
