### ISSUE TITLE
Webpack breaks ExpressJS error handling

### ISSUE THREAD

**Issue by FaBeyyy** [webpack/webpack#8146]
# Bug report

**What is the current behavior?**

Building my simple API with Webpack breaks the error handling of ExpressJS.
Starting the node application being built with Webpack every error that is being thrown is handled as an internal servor error instead of the thrown error response.

**If the current behavior is a bug, please provide the steps to reproduce.**

Simple backend API using TypeScript, ExpressJS throwing an error in a route.

**What is the expected behavior?**

The API should respond with the right error message instead of internal server error.

**Other relevant information:**
webpack version:  Latest
Node.js version: 10.09
Operating System: Windows 10

webpack.config: 
```
module.exports = {
    target: 'node',
    entry: './src/server.ts',
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'server.js'
    },
    resolve: {
        // Add '.ts' and '.tsx' as a resolvable extension.
        extensions: [".webpack.js", ".web.js", ".ts", ".tsx", ".js"]
    },
    module: {
        rules: [
            { test: /\.ts$/, use: 'ts-loader' }
        ]
    },
    node: {
        fs: 'empty',
        net: 'empty'
    }
};

```

**Comment by alexander-akait** [comment]
Please use github repo, because it requires to spend a lot of time on creation and we have a lot of issues, big thanks for undestanding

**Comment by ap0h** [comment]
> Please use github repo, because it requires to spend a lot of time on creation and we have a lot of issues, big thanks for undestanding

There is no issue with  webpack in my example. The issue arose when minification altered all error object constructors, causing a comparison of this.name to yield a random letter instead of the intended custom error.
