### ISSUE TITLE
npm install fail : fsevents@1.2.4 

### ISSUE THREAD

**Issue by bensbenj** [webpack/webpack#8147]
### Environment 

node -v   ->  v10.11.0
npm -v    ->  v6.4.1
OS: linux / ubuntu 16.04

### npm install webpack
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ webpack@4.20.2
updated 1 package in 19.994s
[+] no known vulnerabilities found [4595 packages audited]

### webpack
webpack: command not found

### npm install fsevents@1.2.4
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ben/.npm/_logs/2018-10-05T12_12_47_404Z-debug.log

_I can't to use webpack, gulp, browserify ...
I need help_

**Comment by evilebottnawi** [comment]
@bensbenj how you run `webpack`?

**Comment by montogeek** [comment]
First error in the stack error:
```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

Try these solutions: https://github.com/angular/angular/issues/13935

**Comment by bensbenj** [comment]
@evilebottnawiI work on a project with my friend and we using git, he have ios, when he tape the command " webpack --watch" it's built, and in my output "webpack: command not found"

@montogeek  I already tried it does not work

**Comment by evilebottnawi** [comment]
@bensbenj Are you install `webpack-cli`?

**Comment by bensbenj** [comment]
yes

**Comment by evilebottnawi** [comment]
@bensbenj looks something wrong with your environment, please create minimum reproducible test repo

**Comment by evilebottnawi** [comment]
@bensbenj feel free to feedback, not related to `webpack`
