### ISSUE TITLE
Async functions handled incorrectly when building in production mode

### ISSUE THREAD

**Issue by artoale** [webpack/webpack#8148]
# Bug report

**What is the current behavior?**
When an async function returns an immediate value, if the app is compiled with `mode: 'production'`
the optimizer doesn't wrap the returned value in a Promise, causing a

`TypeError: {(intermediate value)}.then is not a function` error

**If the current behavior is a bug, please provide the steps to reproduce.**
I've created a minimal reproducible setup here: https://github.com/artoale/webpack-babel-async-issue

The gist of it is having an async function return an object literal, and then call it expecting a promise:

```javascript
const getObject = async () => ({ key: 'value' });

getObject().then(obj => console.log(obj));
```

That code works fine if run with `mode: development` (or with node directly) but breaks when run with 
`mode: production`

**What is the expected behavior?**

The compiled result should be something like this:

```javascript
Promise.resolve({
    key: "value"
}).then(e => console.log(e))
```

**Other relevant information:**
webpack version:  4.20.2
Node.js version:  8.11.2
Operating System: macOS High Sierra 10.13.6 (17G65)
Additional tools: babel

**Comment by ljqx** [comment]
setting `optimization.minimize` to `false` would fix it. Seems to be bug of `uglifyjs-webpack-plugin`

**Comment by evilebottnawi** [comment]
Better switch on `terser-webpack-plugin`
