### ISSUE TITLE
node.js api: Is there a "compile started" event?

### ISSUE THREAD

**Issue by epeli** [webpack/webpack#815]
I'm using the `compiler.watch(delay, cb)` api where the callback is called when the compiling is done. Is there a  way to define a callback for the moment when the compiling starts? I'd like to display a notification for the user.

**Comment by sokra** [comment]
`"watch-run"` or `"compile"` plugin hook.

``` js
compiler.plugin("compile", function() {
  // ...
});
```

**Comment by epeli** [comment]
Thanks. Exactly what I wanted.

**Comment by leoselig** [comment]
Where is this documented?

**Comment by epeli** [comment]
In plugins docs http://webpack.github.io/docs/plugins.html

**Comment by zamb3zi** [comment]
I'm having a problem getting `watch-run` to work. If I create a plugin as follows, the callback gets called but webpack does not continue packing. What am I missing? Thanks.
```javascript
    const EventsPlugin = function() {};
    EventsPlugin.prototype.apply = function(compiler) {
        compiler.plugin('watch-run', function() {
            console.log('watch-run');
        });
    };
```

**Comment by zamb3zi** [comment]
Ah never mind, it's an async method, so:
```javascript:
const EventsPlugin = function() {};
    EventsPlugin.prototype.apply = function(compiler) {
        compiler.plugin('watch-run', function(watching, cb) {
            console.log('watch-run');
            cb();
        });
    };
```

**Comment by gajus** [comment]
Is there an efficient way to subscribe to a single event? i.e. `once` event emitter equivalent.

**Comment by borm** [comment]
up for w4
