### ISSUE TITLE
Opt-in to `--experimental-modules`

### ISSUE THREAD

**Issue by jdalton** [webpack/webpack#8150]
## Feature Request

👋 Node core and Node Module WG member here.

It looks like [complications](https://github.com/facebook/create-react-app/pull/5258#issuecomment-426534689
) are emerging from folks [early adopting](https://developers.google.com/web/fundamentals/primers/modules#mjs) `.mjs` without fully understanding the consequences.

Where Node has the guard for `--experimental-modules`, tools like Babel and Webpack do not
and happily take `.mjs` without the context of “experimental” which leads to [frustration](https://github.com/facebook/create-react-app/issues/5234#issuecomment-426470816) from project maintainers. 

It’s the Node Module WG position that `--experimental-modules` **should not** be used in production code.

I think that adding a flag-like-mechanism for use matches nicely with Node, expresses caution, and gives users a better heads up to what they’re getting into.

*Note: This is a cross-post from https://github.com/babel/babel/issues/8813*

**Comment by sokra** [comment]
> It looks like [complications](https://github.com/facebook/create-react-app/pull/5258#issuecomment-426534689) are emerging from folks [early adopting](https://developers.google.com/web/fundamentals/primers/modules#mjs) `.mjs` without fully understanding the consequences.

Neither webpack nor the webpack documentation recommend using .mjs or even mention it. If there is any confusion how to use .mjs it may origins from some other documentation about it...

If would just ignore .mjs (or disable .mjs integration) it would be treated as javascript similar to .js, which has a bigger featureset compared to .mjs. So currently the way webpack handles .mjs is limiting the feature set, to reduce the surface of breaking changes.

We can remove `.mjs` from extensions for webpack 5 if you want this. Or we could emit a warning when using `.mjs` modules.

I'm actually a bit annoyed that the spec has not been finalized yet. The work on this took way to long so far...

**Comment by jdalton** [comment]
> If would just ignore .mjs (or disable .mjs integration) it would be treated as javascript similar to .js, which has a bigger featureset compared to .mjs. 

That would certainly fix integration/test/mock pain points. But may also mask that `.mjs` is experimental in the Node target.

> So currently the way webpack handles `.mjs` is limiting the feature set, to reduce the surface of breaking changes.

That's the route I've taken with the `esm` loader too. Where restricting features/functionality works for a loader I think it may be a little rougher for a bundler. Side note: I've seen folks suggest, that because of `.mjs` restrictions, that others should just switch their libraries to `.mjs` too _(becoming viral - spreading experimental features in production)_ to work around the integration restrictions.

> We can remove `.mjs` from extensions for webpack 5 if you want this. Or we could emit a warning when using .mjs modules.

I think removal for the Node target (explicit error) and then no special treatment beyond a warning for other targets (like browser) would do. The warning would be something along the lines of - 

> Your web server needs to be configured to serve .mjs files with the Content-Type header text/javascript. If your browser is failing to load your .mjs files, that may be why.

or

> Note: To deploy .mjs on the web, your web server needs to be configured to serve files with this extension using the appropriate Content-Type: text/javascript header, as mentioned above. Additionally, you may want to configure your editor to treat .mjs files as .js files to get syntax highlighting. Most modern editors already do this by default.

**Comment by sokra** [comment]
> Your web server needs to be configured to serve .mjs files with the Content-Type header text/javascript. If your browser is failing to load your .mjs files, that may be why.

I'm confused. I thought we are talking about consuming .mjs files not emitting .mjs files. Currently even when webpack consumes modules as .mjs files it still emits .js files. In compiles ESM to script tags.

**Comment by jdalton** [comment]
> I'm confused. I thought we are talking about consuming .mjs files not emitting .mjs files. Currently even when webpack consumes modules as .mjs files it still emits .js files. In compiles ESM to script tags.

Ah ya, sorry. Then nothing needed for non-node targets.

**Comment by temple** [comment]
> Neither webpack nor the webpack documentation recommend using .mjs or even mention it. If there is any confusion how to use .mjs it may origins from some other documentation about it...
> 
> If would just ignore .mjs (or disable .mjs integration) it would be treated as javascript similar to .js, which has a bigger featureset compared to .mjs. So currently the way webpack handles .mjs is limiting the feature set, to reduce the surface of breaking changes.
> 
> We can remove `.mjs` from extensions for webpack 5 if you want this. Or we could emit a warning when using `.mjs` modules.
> 
> I'm actually a bit annoyed that the spec has not been finalized yet. The work on this took way to long so far...

Thanks @sokra for the explanation. But, I'm a bit confused about.
If I take a look at ["Writing a Loader" page](https://webpack.js.org/contribute/writing-a-loader/), both kinds are mixed in the snippets (CommonJS and ES6).

Then, how we may handle this?
Thank you so much
