### ISSUE TITLE
ModuleConcatenationPlugin bailout because of undefined injected global

### ISSUE THREAD

**Issue by ludekstepan** [webpack/webpack#8152]
# Bug report

**What is the current behavior?**

The ModuleConcatenationPlugin fails to hoist modules that use a global variable even when the global variable is undefined in the target environment.

The example is `process`, `__dirname` and other variables from [Module Variables](https://webpack.js.org/api/module-variables/)

**Steps to reproduce.**

Please see a gist: https://gist.github.com/ludekstepan/368d5f56afc195e473a6a9d897a5e164

When compiled, the webpack outputs:

```
[./index.js] 64 bytes {0} [built]
    ModuleConcatenation bailout: Module is an entry point
[./some-dep.js] 98 bytes {0} [built]
    ModuleConcatenation bailout: Module uses injected variables (__dirname)
```
And the compiled `dist/main.js` contains two modules:

If I change the`__dirname` in the dependency module to some other undefined global (like: `__foo`), the concatenation works as expected.

I want to optimize for size and performance as much as possible, and the concrete application that causes me trouble is: [use of `process` in @most/scheduler](https://github.com/mostjs/core/blob/master/packages/scheduler/src/clock.js#L46)

**What is the expected behavior?**

I expect the ModuleConcatenationPlugin to consider only global variables specific to the target environment.

**Other relevant information:**
webpack version:  4.20.2

**Comment by sokra** [comment]
webpack <= 4 doesn't support concatenation of injected variables. webpack 5 does support it.

**Comment by sokra** [comment]
This is not new. `node.process: false` should disable it. `node: false` should disable all node polyfills.
