### ISSUE TITLE
consider process.exit on SIGINT timeout

### ISSUE THREAD

**Issue by kevinburke** [webpack/webpack#8153]
# Bug report

**What is the current behavior?**

If a loader does not hit a callback on SIGINT, webpack can hang forever. See for example this description of a hang in the thread-loader package: https://github.com/webpack-contrib/thread-loader/issues/33

**If the current behavior is a bug, please provide the steps to reproduce.**

See linked issue.

**What is the expected behavior?**

Sending a SIGINT to a program should shut it down after giving the program some amount of time to clean up.

For example, you could set a timeout of 5-10 seconds, and call `process.exit()` directly if there are still outstanding callbacks for a loader at that time. I think those would be better than hanging.

**Other relevant information:**
webpack version: Latest
Node.js version: Latest stable
Operating System: Any
Additional tools: thread-loader (though any poorly written loader could have this problem)

**Comment by sokra** [comment]
Node.js has default handlers for SIGINT, which already exit the process. Seem to be a thread-loader specific issue.
