### ISSUE TITLE
Creating target: "node" module with runtimeChunk: "single" doesn't work

### ISSUE THREAD

**Issue by bd041556** [webpack/webpack#8156]
# Bug report

**What is the current behavior?**
We have a large code base with a number of different packages. We want to make each package a separate umd module.

Some of the packages are used on both the server, using node, and in the browser.

When we attempt to webpack the packages for use in node, we are trying to make sure that there is only one webpack "runtime", so when we build each module we are using the runtimeChunk: "single" key. That separates the runtime chunk from the main package chunk. We want to use the runtime that is webpacked with the consumer of the package/modules, so that setting seems like what we want.

We specify target: "node", and in the consuming package we specify the modules as externals with "commonjs2 {webpacked package}.js".The modules are found at runtime, but the exports are not available to the consumer.

**If the current behavior is a bug, please provide the steps to reproduce.**
See the github repository https://github.com/bd041556/webpack-runtime-single

Look at the README.md for steps to reproduce.

**What is the expected behavior?**

It should create a module that can be used from node consumers.

**Other relevant information:**
webpack version:  4.20.2
Node.js version: 8.11.3
Operating System:  Windows 10
Additional tools: N/A

**Comment by sokra** [comment]
This has not been implemented yet.

**Comment by bd041556** [comment]
Is there a suggestion for a workaround and/or a timeframe for implementing this?
Thanks!
Barry

**Comment by sokra** [comment]
Don't use `runtimeChunk`. It doesn't make sense with a single entry point anyway. Different compilation can't share a runtime chunk.

**Comment by supasympa** [comment]
I'd really like to implement this feature. Can you give me any direction on where to start looking to make this commons / Node compatible?

**Comment by Dragons0458** [comment]
any solution? Thank you! :D

**Comment by Pisamad** [comment]
Hi,
Any progress on this issue ?

**Comment by evilebottnawi** [comment]
bump

**Comment by netusco** [comment]
interested

**Comment by Akryum** [comment]
bump

**Comment by misak113** [comment]
Me too... it's just fix the modules injecting to main chunk :)

*output of webpack server.js*
```js
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
// ...other generated code
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "/assets/";
/******/ })
/************************************************************************/
/******/ ([]); // This is the place where global modules injecting should come
//# sourceMappingURL=server.js.map
```

Example:
```js
/************************************************************************/
/******/ (global.WEBPACK_CHUNK_MODULES); // This is the place where global modules injecting should come
```


Or automatic require chunks as first argument of global main function.

Example:
```js
/************************************************************************/
/******/ ({ ...require('./chunk1.js'), ...require('./chunk2.js') }); // This is the place where modules require should come
```

**Comment by sokra** [comment]
Fixed in webpack 5

**Comment by micaelmbagira** [comment]
@sokra is it possible to port the fix to webpack 4?
