### ISSUE TITLE
Optionally expose WebAssembly.Module object for wasm ESM

### ISSUE THREAD

**Issue by alexcrichton** [webpack/webpack#8157]
## Feature request

**What is the expected behavior?**

Ideally it would be somehow possible, when importing a wasm file as an ESM, to get a hold of the `WebAssembly.Module` object. Currently, however, I believe that the instantiation of the `WebAssembly.Instance` is hidden in weback (that's good!) but it ends up burying the instance of `WebAssembly.Module` and `WebAssembly.Instance`, not allowing JS code to grab ahold of it and manipulate it.

**What is motivation or use case for adding/changing the behavior?**

The main motivation for this use case is the upcoming [threads proposal in WebAssembly](https://github.com/webassembly/threads). With threads one visions for idiomatic usage is to post a `WebAssembly.Module` to a set of worker threads (along with a `SharedArrayBuffer`). All worker threads would then use the exact same compiled code and shared memory, allowing for reduced resource usage and faster instantiation as the module no longer needs to be fetched and compiled once per thread.

To that end, the moviation here is implementing a method for Webpack to be used while also enabling this method of multithreaded wasm, posting a `WebAssembly.Module` instance to worker threads.

**How should this be implemented in your opinion?**

There's unfortunately no great way to implement this mapping to the ESM spec for wasm. I've [opened an issue](https://github.com/WebAssembly/esm-integration/issues/14) on the wasm ESM integration repository for this feature, but there's not consensus yet on what to do. The idea, though, is that just like how an wasm "ESM" can export its own memory it could also export its own instance/module (somehow). 

In any case in the meantime I'm hoping that we could polyfill https://github.com/WebAssembly/esm-integration/issues/14 somehow or otherwise enable it. I'd personally be ok with "magic names" that automatically and synthetically get added to a wasm ESM export list (like `__webpack_webassembly_module`). 

**Are you willing to work on this yourself?**

I can try! I'd need some assistance though in navigating around.

cc @xtuc, you likely have thoughts on this!

**Comment by sokra** [comment]
Instead of this manual way of using wasm in a worker I would like to evaluate an alternative way:

This need to be added to the spec, but browser could also implement it without spec change:

> When using `compileStreaming` or `instantiateStreaming` browser should keep the compiled WebAssembly.Module in their own Cache (Code Cache). When using `compileStreaming` or `instantiateStreaming` again and the request can be fulfilled from the memory or file cache browser should skip compiling the WebAssembly.Module and instead use the compiled code from the cache.

This would result in the following behavior:

Just use the same url for the wasm in the Worker and it will work. No manual posting of the module via postMessage. The worker could use esm-integration too.

**Comment by xtuc** [comment]
agreed with @sokra, especially since "structured cloning" of the `WebAssembly.Module` seems not wanted in the spec, the user won't need to have access to it.

What are the other use-cases of exposing `WebAssembly.Module`?

> I'd personally be ok with "magic names"

I'm not really fan of that idea; bad UX, might be overriden, difficult to debug, etc.

**Comment by alexcrichton** [comment]
Even if the module can get the same performance characteristics via other means the shared memory always has to be posted, right? 

I was struggling to figure out a way for webpack to totally transparently handle wasm in workers with shared memory and would love to have a way! In the meantime though my best thinking was to provide enough hooks for the main thread to do it
