### ISSUE TITLE
ES6 imports with require.ensure

### ISSUE THREAD

**Issue by cliren** [webpack/webpack#816]
How do I import ES6 modules to perform code splitting or load in AMD fashion?

In the below example, Sidebar is an ES6 module.

require.ensure([], (require) => {
    import {SidebarView} from './sidebar/sidebar'; // throws 'import' and 'export' may only appear at the top level 

  //var SidebarView = require('./sidebar/sidebar'); // this works but it exports SidebarView.SidebarView
    
  });

**Comment by zxcabs** [comment]
ES6 does not allow import in the middle of the code for dynamic loading is provided a method System # import that returns Promise. But webpack not support it.

[Here] (http://www.2ality.com/2014/09/es6-modules-final.html) can be read in more detail.

**Comment by MrKou47** [comment]
I wrote a tool named [ensure2import](https://github.com/MrKou47/ensure2import) to transform `require.ensure` to `import()`. Hoop this is helpful.

**Comment by jintao16** [comment]
> I wrote a tool named [ensure2import](https://github.com/MrKou47/ensure2import) to transform `require.ensure` to `import()`. Hoop this is helpful.

nice 大兄弟，哈哈哈。
