### ISSUE TITLE
[Feature] Split chunks for a node application

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack#8161]
## Feature request

**What is the expected behavior?**
At the moment, a `splitChunk` configuration like the following, works only for browsers

```js
splitChunks: {
 cacheGroups: {
   vendors: {
     async: 'initial',
     test: '/node_modules/'
   }
 }
}
```

This will create a `vendors.js` initial chunk that can be loaded before the bundle.

I would like to leverage this feature when the `target: "node"`. At the moment it's not possible to create a chunk that can be shared among entry points and loaded before the main bundle of the entry point itself.

On a node environment, I would expect to see something like

```js
// file a.js
require('./vendors.js');
require('./entryPointA.js')

// file B.js
require('./vendors.js');
require('./entryPointB.js')
```

**What is motivation or use case for adding/changing the behaviour?**
The main reason is not long term caching but the ability to split and share code among entry points on a node.js enviroment.

**How should this be implemented in your opinion?**
No idea as my knowledge of the internals is scarce.

**Are you willing to work on this yourself?**
Yes, if someone can help me and point me in the correct direction

**Comment by sokra** [comment]
see also #8156
