### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by neilime** [webpack/webpack#8164]
# Bug report

Hi,

I got an error when I try to run webpack and awesome-typescript-loader  (the same issue occurs with ts-loader) with a dependency package named `'imagemin-jpegtran'` :

- _Critical dependency: require function is used in a way in which dependencies cannot be statically extracted_

**Edit** : this error occurs because of bin-wrapper module which is using `require('import-lazy')(require);`
https://github.com/kevva/bin-wrapper/blob/master/index.js#L5

**What is the current behavior?**

> WARNING in ./node_modules/bin-wrapper/index.js 5:34-41
> Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
>  @ ./node_modules/jpegtran-bin/lib/index.js
>  @ ./node_modules/jpegtran-bin/index.js
>  @ ./node_modules/imagemin-jpegtran/index.js
>  @ ./src/index.ts

**If the current behavior is a bug, please provide the steps to reproduce.**

_package.json_

```json
{
  "name": "test-jpegtran-bin",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "imagemin-jpegtran": "^5.0.2"
  },
  "devDependencies": {
    "@types/imagemin-jpegtran": "^5.0.0",
    "@types/node": "^10.11.6",
    "@types/webpack": "^4.4.16",
    "awesome-typescript-loader": "^5.2.1",
    "source-map-loader": "^0.2.4",
    "ts-node": "^7.0.1",
    "typescript": "^3.1.2",
    "webpack": "^4.20.2",
    "webpack-cli": "^3.1.2"
  },
  "scripts": {
    "start": "webpack"
  },
  "author": "",
  "license": "ISC"
}
```

_webpack.config.js_
```js 
module.exports = {
    mode: 'production',
    entry: "./src/index.ts",
    output: {
        filename: "bundle.js",
        path: __dirname + "/dist"
    },
    devtool: "source-map",
    resolve: {
        extensions: [".ts", ".tsx", ".js", ".json"]
    },
    target: 'node',
    module: {
        rules: [
            { test: /\.tsx?$/, loader: "awesome-typescript-loader" },
        ]
    },
};
```

_tsconfig.json_
```json 
{
    "compilerOptions": {
        "outDir": "./dist/",
        "sourceMap": true,
        "noImplicitAny": true,
        "module": "commonjs",
        "target": "es5",
        "lib": [
            "es6"
        ]
    },
    "include": [
        "./src/**/*"
    ],
    "exclude": [
        "node_modules",
        "**/*.spec.ts"
    ]
}
```

_src/index.ts_

```typescript
import * as  imageminJpegtran from 'imagemin-jpegtran';
imageminJpegtran();
```

**Other relevant information:**
webpack version:  4.20.2
Node.js version: v10.11.0
Operating System: Windows 10

**Comment by sokra** [comment]
This package is not compatible with in-browser usage. You can't run executables there.

**Comment by neilime** [comment]
I'm using webpack to package a typescript serverless function, so it's not for "in-browser" usage

**Comment by y-lakhdar** [comment]
Same issue here with a different npm package: "update-notifier".
Similar use case: not for "in-browser" usage. I am building a command line app with node.

This error happened since I updated my webpack version from on 1 to 4 (I know... a pretty big jump).

**Comment by otto-dev** [comment]
Workaround while this is not fixed, if you need to reference require: 

```js
const foobarRequire = eval('require'); // trick webpack
```

**Comment by CodeSteele** [comment]
Same here, example code:

```typescript
// Nuxt module
async asyncData () {
	return {
		artists: await loadData<Artist[]>("~/data/artists", "artists")
	};
}


// Another file
export async function loadData<T>(path: string, type: string): Promise<T> {
    const data = require.context(path, false, /\.yml$/);
    return <T><any>await data
        .keys()
        .map((context: any) => ({
            ...data(context),
            key: context.replace("./", "").replace(".yml", "")
        }))
        .map((a: any) => ({ ...a, type: type }));
}
```


What works for me (but is a little more gross):
```typescript
// Nuxt Vue class
async asyncData () {
	return {
		artists: await loadData<Artist[]>(
			require.context("~/data/artists", false, /\.yml$/),
			"artists"
		)
	};
}


// Another file
export async function loadData<T>(dataContext: any, type: string): Promise<T> {
    return <T><any>await dataContext
        .keys()
        .map((context: any) => ({
            ...dataContext(context),
            key: context.replace("./", "").replace(".yml", "")
        }))
        .map((a: any) => ({ ...a, type: type }));
}
```

Being able the do the former would clean things up a bit, but the only option I can find is to rip the require.context out into the Vue class. Ick.

**Comment by otto-dev** [comment]
> Workaround while this is not fixed, if you need to reference require server-side in a code base that is (also) webpacked:
> 
> ```js
> const foobarRequire = m => eval('require')(m); // trick webpack
> ```

I'm curious, why are there so many thumbs down on this comment?

**Comment by emilioplatzer** [comment]
> I'm curious, why are there so many thumbs down on this comment?

May be, because the require is generated by the compiler. We cannot edit all the files every time that we compile our ts code.
