### ISSUE TITLE
Feature request: Error on invalid paths

### ISSUE THREAD

**Issue by fresheneesz** [webpack/webpack#817]
If I pass in a path like "c:\whatever\whatever/more/stuff" as the `context`, it accepts it and then only partially works. This confused me for a long time (related to: https://github.com/webpack/webpack/issues/779 ). So I suggest that if there are invalid paths, webpack throw an error so users don't continue to use invalid paths, but instead correct their config.

**Comment by bebraw** [comment]
Can you try this against webpack 2? There should be path validation in place now.

**Comment by fresheneesz** [comment]
I'm using webpack 3 now, and it gives me a good error message now! Thanks!
