### ISSUE TITLE
Webpack load "module" entry point when using require

### ISSUE THREAD

**Issue by ericmorand** [webpack/webpack#8171]
Consider the following code:

```
const parseFunction = require('parse-function');

console.warn(parseFunction());
```

`parse-function` module will be resolved by Wepack to `dist/index.es.js` instead of `dist/index.js` as hinted by parse-function package.json:

```
{
    ...,
    "main": "./dist/index.js",
    "module": "./dist/index.es.js",
    ...
}
```

This will make the bundle unusable since `parseFunction` will not be a function when it is required from `dist/index.es.js` - but `parseFunction.default` is.

**Other relevant information:**
webpack version:  3.6
Node.js version: 10.11.0
Operating System: Unbuntu 17.04

**Comment by sokra** [comment]
That's working as expected. When using `main` and `module` it's expected that the package exports the same API on both entries.

**Comment by ericmorand** [comment]
But is it expected that using `require` point WebPack to the `module` entry point? I'm evaluating if I need to open an issue upstream - i.e. parse-function.

**Comment by sokra** [comment]
> But is it expected that using `require` point WebPack to the `module` entry point?

yes
