### ISSUE TITLE
Piping into Webpack doesn't work

### ISSUE THREAD

**Issue by ericmorand** [webpack/webpack#8172]
Consider the following npm script:

`echo "console.log('test');" | webpack`

You'll get an error:

> Insufficient number of arguments or no entry found.

Consider the analoguous script using browserify:

`echo "console.log('test');" | browserify`

You'll get the bundle, as expected:

> (function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({},{},[]);

**What is the expected behavior?**

Well, the bundle should be built. Piping into webpack doesn't work.

**Other relevant information:**
webpack version:  4
Node.js version: 10

**Comment by evilebottnawi** [comment]
Maybe problem in `webpack-cli`
/cc @ev1stensberg

**Comment by sokra** [comment]
This is not intended to work

**Comment by ev1stensberg** [comment]
Open a feature request at webpack CLI with an example of what you wanna pipe along with an elaborative description
