### ISSUE TITLE
How to keep css modular and native css effective

### ISSUE THREAD

**Issue by l2en** [webpack/webpack#8173]
How can I open css modular at the same time and maintain the usability of native css? My current situation is that if the css modularization is enabled, the .css style file is invalid.thx!

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
