### ISSUE TITLE
Error when build 

### ISSUE THREAD

**Issue by TrinhVanDan** [webpack/webpack#8174]
[slots.zip](https://github.com/webpack/webpack/files/2471373/slots.zip)

use signalr core, typescript and webpack to write app. But when i build my app it has error.

` ERROR in ./node_modules/@aspnet/signalr/dist/esm/index.js
    Module not found: Error: Can't resolve './Errors' in 'D:\Zone\G1\Client\G1.Client\slots\node_modules\@aspnet\signalr\dist\esm'
     @ ./node_modules/@aspnet/signalr/dist/esm/index.js 6:0-51 6:0-51 6:0-51
     @ ./vq/hubs.ts
     @ multi ./vq/hubs.ts ./vq/contents.ts ./vq/bonus.ts ./vq/lines.ts ./vq/trial.ts ./vq/games.ts

    ERROR in ./node_modules/@aspnet/signalr/dist/esm/index.js
    Module not found: Error: Can't resolve './HttpClient' in 'D:\Zone\G1\Client\G1.Client\slots\node_modules\@aspnet\signalr\dist\esm'
     @ ./node_modules/@aspnet/signalr/dist/esm/index.js 7:0-75 7:0-75 7:0-75 7:0-75
     @ ./vq/hubs.ts
     @ multi ./vq/hubs.ts ./vq/contents.ts ./vq/bonus.ts ./vq/lines.ts ./vq/trial.ts ./vq/games.ts

    ERROR in ./node_modules/@aspnet/signalr/dist/esm/index.js
    Module not found: Error: Can't resolve './HubConnection' in 'D:\Zone\G1\Client\G1.Client\slots\node_modules\@aspnet\signalr\dist\esm'
     @ ./node_modules/@aspnet/signalr/dist/esm/index.js 8:0-48 8:0-48
     @ ./vq/hubs.ts
     @ multi ./vq/hubs.ts ./vq/contents.ts ./vq/bonus.ts ./vq/lines.ts ./vq/trial.ts ./vq/games.ts

    ERROR in ./node_modules/@aspnet/signalr/dist/esm/index.js
    Module not found: Error: Can't resolve './HubConnectionBuilder' in 'D:\Zone\G1\Client\G1.Client\slots\node_modules\@aspnet\signalr\dist\esm'
     @ ./node_modules/@aspnet/signalr/dist/esm/index.js 9:0-62 9:0-62
     @ ./vq/hubs.ts
     @ multi ./vq/hubs.ts ./vq/contents.ts ./vq/bonus.ts ./vq/lines.ts ./vq/trial.ts ./vq/games.ts

    ERROR in ./node_modules/@aspnet/signalr/dist/esm/index.js
    Module not found: Error: Can't resolve './IHubProtocol' in 'D:\Zone\G1\Client\G1.Client\slots\node_modules\@aspnet\signalr\dist\esm'
     @ ./node_modules/@aspnet/signalr/dist/esm/index.js 10:0-45 10:0-45
     @ ./vq/hubs.ts
     @ multi ./vq/hubs.ts ./vq/contents.ts ./vq/bonus.ts ./vq/lines.ts ./vq/trial.ts ./vq/games.ts

    ERROR in ./node_modules/@aspnet/signalr/dist/esm/index.js
    Module not found: Error: Can't resolve './ILogger' in 'D:\Zone\G1\Client\G1.Client\slots\node_modules\@aspnet\signalr\dist\esm'
     @ ./node_modules/@aspnet/signalr/dist/esm/index.js 11:0-37 11:0-37
     @ ./vq/hubs.ts
     @ multi ./vq/hubs.ts ./vq/contents.ts ./vq/bonus.ts ./vq/lines.ts ./vq/trial.ts ./vq/games.ts

    ERROR in ./node_modules/@aspnet/signalr/dist/esm/index.js
    Module not found: Error: Can't resolve './ITransport' in 'D:\Zone\G1\Client\G1.Client\slots\node_modules\@aspnet\signalr\dist\esm'
     @ ./node_modules/@aspnet/signalr/dist/esm/index.js 12:0-65 12:0-65 12:0-65
     @ ./vq/hubs.ts
     @ multi ./vq/hubs.ts ./vq/contents.ts ./vq/bonus.ts ./vq/lines.ts ./vq/trial.ts ./vq/games.ts

    ERROR in ./node_modules/@aspnet/signalr/dist/esm/index.js
    Module not found: Error: Can't resolve './JsonHubProtocol' in 'D:\Zone\G1\Client\G1.Client\slots\node_modules\@aspnet\signalr\dist\esm'
     @ ./node_modules/@aspnet/signalr/dist/esm/index.js 14:0-52 14:0-52
     @ ./vq/hubs.ts
     @ multi ./vq/hubs.ts ./vq/contents.ts ./vq/bonus.ts ./vq/lines.ts ./vq/trial.ts ./vq/games.ts

    ERROR in ./node_modules/@aspnet/signalr/dist/esm/index.js
    Module not found: Error: Can't resolve './Loggers' in 'D:\Zone\G1\Client\G1.Client\slots\node_modules\@aspnet\signalr\dist\esm'
     @ ./node_modules/@aspnet/signalr/dist/esm/index.js 13:0-39 13:0-39
     @ ./vq/hubs.ts
     @ multi ./vq/hubs.ts ./vq/contents.ts ./vq/bonus.ts ./vq/lines.ts ./vq/trial.ts ./vq/games.ts`

I attached my project. Anybody help me this error.

It is going to when i use pixijs. May be, config file is incorrect?
`ERROR in ./node_modules/pixi.js/lib/index.js
    Module not found: Error: Can't resolve './accessibility' in 'D:\Zone\G1\Client\G1.Client\slots\node_modules\pixi.js\lib'
     @ ./node_modules/pixi.js/lib/index.js 34:21-47
     @ ./libs/libs.ts
     @ ﻿multi ./libs/libs.ts

    ERROR in ./node_modules/pixi.js/lib/index.js
    Module not found: Error: Can't resolve './core' in 'D:\Zone\G1\Client\G1.Client\slots\node_modules\pixi.js\lib'
     @ ./node_modules/pixi.js/lib/index.js 18:12-29
     @ ./libs/libs.ts
     @ multi ./libs/libs.ts

    ERROR in ./node_modules/pixi.js/lib/index.js
    Module not found: Error: Can't resolve './deprecation' in 'D:\Zone\G1\Client\G1.Client\slots\node_modules\pixi.js\lib'
     @ ./node_modules/pixi.js/lib/index.js 30:19-43
     @ ./libs/libs.ts
     @ multi ./libs/libs.ts

    ERROR in ./node_modules/pixi.js/lib/index.js
    Module not found: Error: Can't resolve './extract' in 'D:\Zone\G1\Client\G1.Client\slots\node_modules\pixi.js\lib'
     @ ./node_modules/pixi.js/lib/index.js 38:15-35
     @ ./libs/libs.ts
     @ multi ./libs/libs.ts

    ERROR in ./node_modules/pixi.js/lib/index.js
    Module not found: Error: Can't resolve './extras' in 'D:\Zone\G1\Client\G1.Client\slots\node_modules\pixi.js\lib'
     @ ./node_modules/pixi.js/lib/index.js 42:14-33
     @ ./libs/libs.ts
     @ multi ./libs/libs.ts

    ERROR in ./node_modules/pixi.js/lib/index.js
    Module not found: Error: Can't resolve './filters' in 'D:\Zone\G1\Client\G1.Client\slots\node_modules\pixi.js\lib'
     @ ./node_modules/pixi.js/lib/index.js 46:15-35
     @ ./libs/libs.ts
     @ multi ./libs/libs.ts

    ERROR in ./node_modules/pixi.js/lib/index.js
    Module not found: Error: Can't resolve './interaction' in 'D:\Zone\G1\Client\G1.Client\slots\node_modules\pixi.js\lib'
     @ ./node_modules/pixi.js/lib/index.js 50:19-43
     @ ./libs/libs.ts
     @ multi ./libs/libs.ts

    ERROR in ./node_modules/pixi.js/lib/index.js
    Module not found: Error: Can't resolve './loaders' in 'D:\Zone\G1\Client\G1.Client\slots\node_modules\pixi.js\lib'
     @ ./node_modules/pixi.js/lib/index.js 54:15-35
     @ ./libs/libs.ts
     @ multi ./libs/libs.ts

    ERROR in ./node_modules/pixi.js/lib/index.js
    Module not found: Error: Can't resolve './mesh' in 'D:\Zone\G1\Client\G1.Client\slots\node_modules\pixi.js\lib'
     @ ./node_modules/pixi.js/lib/index.js 58:12-29
     @ ./libs/libs.ts
     @ multi ./libs/libs.ts

    ERROR in ./node_modules/pixi.js/lib/index.js
    Module not found: Error: Can't resolve './particles' in 'D:\Zone\G1\Client\G1.Client\slots\node_modules\pixi.js\lib'
     @ ./node_modules/pixi.js/lib/index.js 62:17-39
     @ ./libs/libs.ts
     @ multi ./libs/libs.ts

    ERROR in ./node_modules/pixi.js/lib/index.js
    Module not found: Error: Can't resolve './polyfill' in 'D:\Zone\G1\Client\G1.Client\slots\node_modules\pixi.js\lib'
     @ ./node_modules/pixi.js/lib/index.js 6:16-37
     @ ./libs/libs.ts
     @ multi ./libs/libs.ts

    ERROR in ./node_modules/pixi.js/lib/index.js
    Module not found: Error: Can't resolve './prepare' in 'D:\Zone\G1\Client\G1.Client\slots\node_modules\pixi.js\lib'`

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please read error message, webpack can't resolve this files - looks they doesn't exist or your aliasing is wrong
