### ISSUE TITLE
default export is compiled incorrectly

### ISSUE THREAD

**Issue by mvestergaard** [webpack/webpack#8176]
# Bug report

**What is the current behavior?**
After upgrading from `4.17.2` to `4.20.2`, we're having issues with default exports. I'm guessing it relates to the recent changes regarding comments near default exports.
```javascript
export default elementType;
```
becomes
```javascript
/* harmony default export */ __webpack_exports__["default"] = (undefined_default); 
```
Which causes a runtime error because `undefined_default` doesn't exist.

**If the current behavior is a bug, please provide the steps to reproduce.**
Our project is large and not open source. It's a bit difficult to extract the configuration required.
I am fairly sure I've narrowed down webpack to be the cause however. 
Downgrading back to `4.17.2` fixes the problem.

**What is the expected behavior?**
A working default export

**Other relevant information:**
webpack version:  4.20.2 (from 4.17.2)
Node.js version: 9.11.1
Operating System: win10
Additional tools:

**Comment by sokra** [comment]
this is a hard-source-webpack-plugin issue

**Comment by mvestergaard** [comment]
@sokra Thanks, that does sound very plausible. I assume you're referring to https://github.com/mzgoddard/hard-source-webpack-plugin/issues/455 ?
