### ISSUE TITLE
Documented "_entry_return_" default-value for libraryExport doesn't work with "umd" libraryTarget

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [webpack/webpack#8180]
# Bug report

**What is the current behavior?**
When building a package with,

```json5
"libraryTarget": "umd",
// ("libraryExport" is undefined)
```

I get a correct package; that is, something like this:

```js
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
	  // …
	else
		root["GameEngine"] = factory();
})(window, function() {
return /******/ (function(modules) { // webpackBootstrap

// … BUNDLE BODY …

/******/ });
});
//# sourceMappingURL=game-engine.js.map
```

I can, of course, change `libraryExport` to `"default"`, and things work as expected:

```json5
"libraryTarget": "umd",
"libraryExport": "default",
```

```diff
diff --git i/dist/game-engine.js w/dist/game-engine.js
@@ -50967,6 +50967,6 @@ function () {
 
 /***/ })
 
-/******/ });
+/******/ })["default"];
 });
 //# sourceMappingURL=game-engine.js.map
```

Now, if an upstream configuration changes the default value of this, I may wish to reset it to default. According to [the docs](https://webpack.js.org/configuration/output/#output-libraryexport), that's the value `"_entry_return_"` (o_O).

> ![](https://duaw26jehqd4r.cloudfront.net/items/351P2X1s1M3p0Z3W3i2j/Screen%20Shot%202018-10-12%20at%2012.16.01%20PM.png)

Okay, let's try that:

```json5
"libraryTarget": "umd",
"libraryExport": "_entry_return_",
```

```diff
diff --git i/dist/game-engine.js w/dist/game-engine.js
@@ -50967,6 +50967,6 @@ function () {
 
 /***/ })
 
-/******/ });
+/******/ })["_entry_return_"];
 });
 //# sourceMappingURL=game-engine.js.map
```

Well, that's certainly not correct.

I spent a few hours debugging this under our build-system, trying to figure out why our UMD builds were exporting an `undefined` value. Turns out that's 'cuz our projects don't export an `_entry_return_` property. 🤣

After sufficient testing, I found out that using a `null` JSON value will *not* reset the algorithm to its default behaviour, but using the empty string *will*:

```json5
"libraryTarget": "umd",
"libraryExport": "",
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```json5
// webpack.config.js
module.exports = {
  "output": {
    "library": "Blah",
    "libraryTarget": "umd",
    "libraryExport": "_entry_return_",
  }
}
```

**What is the expected behavior?**

Using the documented "default" value, verbatim, for `libraryExport`, should result in the exact same beahviour as omitting the value. (In particular, the string `_entry_return_` is pretty non-obvious; I'd suggest implementing, and then documenting, `null` as the default value.)

**Other relevant information:**
webpack version:  `v4.20.2`
Node.js version: `v8.12.0`
Operating System: macOS 10.14 “Mojave”

**Comment by sokra** [comment]
`_entry_return_` doesn't exist in the implementation. In fact using `undefined` or an empty string for `libraryExport` will export the whole (namespace) object. It defaults to `undefined`

This seems to be confusing in the documentation. There is a note below but that's difficult to find.

@webpack-bot move to webpack/webpack.js.org
