### ISSUE TITLE
Separate files in development

### ISSUE THREAD

**Issue by altano** [webpack/webpack#821]
Hello,

Is it possible to serve up separate files in development, something equivalent to each entry JS file being spat out with require.ensure() and some code to wire up require?

This is possible with RequireJS and JSPM.  With RequireJS, you just include require on the page and the AMD calls result in script being dynamically loaded.

For a large code base, this can make debugging in the browser and correlating errors back to your original source code much easier.  I know that source maps can help you *see* individual files, but they are terrible for live debugging (in the same way that debugging an optimized C++ app by viewing the C++ source is almost impossible).

**Comment by loganfsmyth** [comment]
As long as you disable minification during local development, sourcemaps should be fine for debugging, since things are basically just concatenated together with some glue, the maps are basically line-to-line mapping. For instance, we only enable minification when NODE_ENV is `production`.

Is that enough to address your primary issue?

**Comment by altano** [comment]
Interesting.  So if you disable all forms of minification, the source maps are only really used to display the same line in the context of the original file.  That makes sense.

I'm using TypeScript and not JS for my current project, so I thought I might have issues, but the `devtools: "eval-source-map"` seems to be working fine, like so:
```
a.ts -> a.js -> bundle.js
b.ts -> b.js -> bundle.js
        ^^^ source maps are for these JS files which never really actually get generated, but have the same name as the corresponding TS file in the dev tools, e.g. it shows compiled JS in the source window but the filename as "a.ts"
```
It slowed down full rebuilds a bit, but who cares about that.

I'll have to play with it more to know if this actually causes issues in a real debugging session, but provisionally my problem is solved.

Thanks for the idea.

**Comment by JonPSmith** [comment]
Hi @altano,

Did you get anywhere with producing individual files for development/debugging. I want to do the same when developing react.js with es2015 modules, e.g. `import * from './myFile'`. 

Have you got an example webpack config file that I could look at?

**Comment by altano** [comment]
@JonPSmith - I tried out the source map idea and it worked well.  I didn't go any further than that though.  I actually haven't used webpack in my last several hobby projects because they were too simple.
