### ISSUE TITLE
Strange behaviour after second watch build, possible bug

### ISSUE THREAD

**Issue by henk23** [webpack/webpack#8227]
# Bug report

**What is the current behavior?**
`webpack -d -w` compiles the app correctly. When I change something, the watcher fires and the app is correctly compiled again. On the next change the watcher fires but the compiled app throws an error.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Checkout minimal test repo: https://github.com/henk23/webpack-bug-test
2. Install dependencies and run webpack: `npm install && node_modules/.bin/webpack -d -w`
3. Open a local web server in the `dist` directory to load the resulting `index.html`. The app should load fine and display something in the console.
4. Change some code in the app (for example add another `console.log` in `my.controller.js`), wait for the build to finish and reload the page. Everything should still be fine.
5. Change some more code in the app (maybe add another `console.log`), wait for the build to finish and reload the page. There will be an error in the console now: "Error: AngularJS v1.x is not loaded!"

**What is the expected behavior?**
Webpack watch should compile the app in the same way on every consecutive build.

**Other relevant information:**
webpack version: 4.20.2
Node.js version: v8.12.0
Operating System: macOS Sierra 10.12.6
Additional tools: None

**Comment by sokra** [comment]
Could you try to reproduce the issue without the AngularCompilerPlugin? Try to figure out if this is a webpack or AngularCompilerPlugin issue.

**Comment by henk23** [comment]
Yes, thank you, it is indeed a problem with Angular's AOT, possibly related to https://github.com/angular/angular/issues/25424 and/or https://github.com/angular/angular-cli/issues/11835.
For anyone who should stumble upon this in the future: The suggested workaround (downgrading to 6.1.0 or even 6.0.0) unfortunately does _not_ work for this issue.
