### ISSUE TITLE
No tree shaking after dead code removal

### ISSUE THREAD

**Issue by eltonio450** [webpack/webpack#8228]
Hello,

# Bug report

**What is the current behavior?**

With `mode: production` on, imported modules that are unused after dead code removal remain in the bundle. Tree shaking and dead code removal work well separately (as far as I understand)

Example:

TreeShakingTest.js
```

const TreeShakingTest = () => console.log('TestKey: default export');
export default TreeShakingTest;

export const NormalExport = () => console.log('TestKey: normal export');
export const UnusedExport = () => console.log('TestKey: unused normal export');
export const UsedInAFalseStatementExport = () => console.log('TestKey: used in a false statement export');
```

main.js:
```

import TreeShakingTest, {
  NormalExport,
  UnusedExport,
  UsedInAFalseStatementExport,
} from '../../ovrlib/components/Error/TreeShakingTest';

//DO NOT TOUCH THIS LINE (TreeShakingTest)
if (false) UsedInAFalseStatementExport(); // TestKey: used in a false statement: not in the bundle
__DEV__ && NormalExport(); // TestKey: normal export: in the bundle
__DEV__ && TreeShakingTest(); // TestKey: default export: in the bundle
__DEV__ && console.log('TestKey: no import'); //  TestKey: no import: not in the bundle
```

__DEV__ is set up through the Define Plugin: webpack.config.js
```
new webpack.DefinePlugin({
      __DEV__: isDebug, // false in production mode
})
```

**What is the expected behavior?**

NormalExport and TreeShakingTest should not be included in the bundle and should be tree shaken. UsedInAFalseStatementExport is correctly tree shaken, and 'no import' is correctly removed, so I imagine everything works well and this is only a matter of order. 

**Other relevant information:**
webpack version:  4.20.2
Node.js version: 8.11.2
Operating System: Mac OS
Additional tools: 

I am not sur if it was pre or post webpack 4, but I am pretty sure this kind of pattern were correctly handled a few months ago

I hope it's clear enough, please let me know if I can help !

Best,

**Comment by sokra** [comment]
You can write it this way and it should work:

``` diff
- __DEV__ && NormalExport();
+ if(__DEV__) NormalExport();
```

**Comment by eltonio450** [comment]
Hi,

thank you for your answer. I tested with the current file:

```
if (false) UsedInAFalseStatementExport(); // TestKey: used in a false statement: not in the bundle
if(__DEV__) NormalExport(); // TestKey: normal export: not in the bundle
if(__DEV__) console.log('TestKey: no import'); //  TestKey: no import: not in the bundle
false && console.log('TestKey: false ternary'); //  TestKey: false ternary: not in the bundle
```

And you are right, none of them is included. Interestingly, the last line is not included.

Does it mean that the transforms should be reordered ? It feels as if the ternary expressions were transformed before the DefinePlugin application. 

Is it the expected behaviour ? IMO, the DefinePlugin should be almost the first thing to be applied, no ?

Thank you for your help,

Best regards

**Comment by eltonio450** [comment]
Ok got it ! Thank you

Would it be ok to have a warning on the Tree shaking documentation page ? Would you accept a PR in this sens ?

Same question for the implementation of the evaluation for ternary expressions

**Comment by montogeek** [comment]
@eltonio450 Feel free to send it :)

**Comment by sokra** [comment]
Send a PR

**Comment by eltonio450** [comment]
@ljqx defintively interested if you have the time to :)
