### ISSUE TITLE
Webpack hangs indefinitely when a plugin throws an error in `done` hook

### ISSUE THREAD

**Issue by robrichard** [webpack/webpack#8234]
# Bug report

**What is the current behavior?**
When using webpack in development mode with either webpack-dev-server or webpack-serve a plugin may throw an error in the `done` hook. When this happens, there is no indication this error has occurred and compilation halts. It is also not possible to see what the error is. It seems like the `done` hook does not get called for any plugins that are later in the plugin list so they have no way of reporting the error.

**If the current behavior is a bug, please provide the steps to reproduce.**
I set up a repository with a minimal reproduction: https://github.com/robrichard/webpack-repro

**What is the expected behavior?**
Webpack should log the errors or pass them to later plugins

**Other relevant information:**
webpack version:  4.21.0
Node.js version: 8.9.3
Operating System: macOS 10.13.6
Additional tools:

**Comment by ooflorent** [comment]
@webpack-bot move to webpack/webpack-dev-server
