### ISSUE TITLE
wasm: access bundler's API

### ISSUE THREAD

**Issue by xtuc** [webpack/webpack#8235]
## Feature request

**What is the expected behavior?**

A wasm module should be able to generate a route to an asset, like JS modues can do.

The wasm module doesn't import the asset, it's not detected as a dependency.

**What is motivation or use case for adding/changing the behavior?**

The discussion came up here https://github.com/rustwasm/wasm-bindgen/pull/972#discussion_r225871008.

Example:
```rust
let worker = Worker::new("./worker.js")?;
```

The Rust code points to a `./worker.js` file, but this file could have been renamed by the bundler and there's no way to know.

**How should this be implemented in your opinion?**

[Host-bindings](https://github.com/WebAssembly/host-bindings/blob/master/proposals/host-bindings/Overview.md) might give an idea. Ideally any module could call the bundler's runetime and file resolution mecanism.

Example:
```rust
extern {
  getAssetURL(name: string): string;
}

let worker = Worker::new(getAssetUrl("./worker.js"))?;
```

Note that it could be implement the same way to support other environments, like Nodejs.

Unfortunately, type representation are language specific; how do we pass a string?

URL generation is only one example, exposing bundler's API would fix https://github.com/webpack/webpack/issues/8157 too.

**Are you willing to work on this yourself?**
yes

cc @alexcrichton

**Comment by alexcrichton** [comment]
In the meantime it's probably easiest/best to rely on JS snippets to generate paths to assets, but long-term I agree that host bindings is probably the way to go here (with a "magical function" or something like that). With host bindings there should be a standard definition of just what a string is that Webpack can agree on with the wasm module. After that webpack will probably need to do some interpretation to figure out where exactly the string is in wasm's memory, but that may not be too too hard?

**Comment by sokra** [comment]
Currently I think the best way it to move this string into the JS part and generate the worker code there:

``` rs
WebWorker!("./worker.js");
```

=>

``` rs
_web_worker_1();
```

``` js
export function _web_worker_1() {
  return new Worker("./worker.js", { type: "module" });
  // + some wrapper code
}
```

and use something like: https://github.com/GoogleChromeLabs/worker-plugin
