### ISSUE TITLE
Help change function name and variable when build.

### ISSUE THREAD

**Issue by TrinhVanDan** [webpack/webpack#8236]
i write a class. example: 
`class Game { 
    private hello: string;   
   print(){
   }
  clear(){
  }
}`

How to after build, it change function name: print -> a, clear -> b or somthing. Thanks.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

use `mode: production` or use `terser-webpack-plugin` https://github.com/webpack-contrib/terser-webpack-plugin
