### ISSUE TITLE
Insert a test file in index.html file 

### ISSUE THREAD

**Issue by gj1118** [webpack/webpack#8241]
Hi, I have a question https://stackoverflow.com/questions/52883743/injecting-a-test-js-file-in-index-html . Can you please let me know how can I insert a file using webpack in my index.html file please . 
Thanks

Note:If this is is not the right template , please let me know and I will for sure adhere to the template, that I will be asked to adhere to. 

Thanks

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
