### ISSUE TITLE
FR: HMR - consuming modules which are not dependencies

### ISSUE THREAD

**Issue by merlinnot** [webpack/webpack#8244]
## Feature request

**What is the expected behavior?**

I'd expect to be able to [accept](https://webpack.js.org/api/hot-module-replacement/#accept) a HMR update for arbitrary files by providing absolute paths or relative to the module calling `module.hot.accept`.

**What is motivation or use case for adding/changing the behavior?**

Consider a web application with a following directory structure:
```
.
├── src
│   ├── actions
│   ├── components
│   ├── decorators
│   ├── images
│   ├── mixins
│   ├── reducers
│   ├── sagas
│   ├── selectors
│   ├── store
│   ├── styles
│   ├── types
│   └── utils
```

`components` directory contains only files (no directories) with a file name equal to names of Custom Elements which they implement.

Each Custom Element has to be styled inline to prevent FOUC on a component level (for more curious devs, it is possible to style Web Components (with Shadow DOM) using external stylesheets).

There is a variety of libraries and frameworks for creating Web Components, however there is a common pattern to use classes for that purpose, since that's a requirement of Custom Elements API (libraries which are not using classes from a developer perspective do use classes internally).

Custom Elements cannot be redeclared with the same tag, so it's not easy to reload it without full page reloads.

Styles for components are however quite easy to replace. Consider the following implementation of a component:

```ts
import { html, LitElement } from '@polymer/lit-element';
import { styled } from '../decorators/styled';
import * as styles from '../styles/my-web-component.scss';

// Here we provide 
@styled('my-web-component', styles)
export class MyWebComponent extends LitElement {
  public render() {
    return html`
      <div>I'm styled!</div>
    `;
  }
}

window.customElements.define('my-web-component', MyWebComponent);
```

It would be quite handy if `@styled` decorator could use HMR to reload styles, right?

**How should this be implemented in your opinion?**

I have a working implementation of `@styled` decorator, however I'm currently using [FuseBox](https://fuse-box.org) for my bundles:

```ts
// decorators/styled.ts

import { html, LitElement } from '@polymer/lit-element';
import { register, unregister } from '../fusebox/registry';

export const styled = (name: string, styles: any) => <
  T extends { new (...args: any[]): LitElement }
>(
  constructor: T,
) =>
  class StyledElement extends constructor {
    public static get properties() {
      return {
        styles: String,
      };
    }

    public styles: string;

    public constructor(...args) {
      super(...args);

      this.styles = styles;
    }

    public connectedCallback() {
      register(name, this);

      super.connectedCallback();
    }

    public disconnectedCallback() {
      unregister(name, this);

      super.disconnectedCallback();
    }

    public render() {
      return html`
        <style>${this.styles}</style>
        ${super.render()}
      `;
    }
  };
```

```ts
// fusebox/registry.ts

import { LitElement } from '@polymer/lit-element';

const instances: Map<string, Set<LitElement>> = new Map();

export const register = (name: string, element: LitElement) => {
  if (instances.has(name) === false) {
    instances.set(name, new Set());
  }

  const set = instances.get(name);
  if (set !== undefined) {
    set.add(element);
  }
};

export const unregister = (name: string, element: LitElement) => {
  const set = instances.get(name);
  if (set !== undefined) {
    set.delete(element);
  }
};

export const getAll = (name: string): Set<LitElement> | undefined =>
  instances.get(name);
```

```ts
// fusebox/hmr.ts

import 'fuse-box/modules/fuse-loader';
import { getAll } from './registry';

const componentNameRegexp = /^styles\/([a-z\-]*)\.scss$/;
const pathToComponentName = path => {
  const maybeMatch = componentNameRegexp.exec(path);

  return maybeMatch !== null ? maybeMatch[1] : undefined;
};

const customizedHMRPlugin = {
  hmrUpdate: ({ content, path, type }): boolean => {
    if (type !== 'js') {
      return false;
    }

    const name = pathToComponentName(path);
    if (name !== undefined) {
      FuseBox.dynamic(path, content);
      const elements = getAll(name);
      if (elements !== undefined) {
        // tslint:disable-next-line no-eval
        const styles = eval(content);

        elements.forEach(element => {
          (element as any).styles = styles;
        });
      }
    } else {
      window.location.reload();
    }

    return true;
  },
};

if (!window.hmrRegistered) {
  window.hmrRegistered = true;
  FuseBox.addPlugin(customizedHMRPlugin);
}
```

**Are you willing to work on this yourself?**

It depends on how easy this task is and how much support and guidance would I get from the community. Given the size and impact of WebPack I assume the code base is of high quality, so the biggest issue would be to agree on an API.

**Comment by sokra** [comment]
webpack is a lot about explicitness. The code you wrote does a lot stuff implicit while relying on naming conventions. When accidentally violating the naming scheme you are wondering why it does no longer work. i. e. when putting styles into another directory or have mismatching names between style and component.

With webpack you would put the HMR code into the module that should be HMR'ed. I. e. I could image a API like this:

```
import { html, LitElement } from '@polymer/lit-element';
import { styled } from '../decorators/styled';
import * as styles from '../styles/my-web-component.scss';

// Here we provide 
@styled('my-web-component', styles)
export class MyWebComponent extends LitElement {
  public render() {
    return html`
      <div>I'm styled!</div>
    `;
  }
}

window.customElements.define('my-web-component', MyWebComponent);

if(module.hot) module.hot.accept('../styles/my-web-component.scss', () => {
  styled.updateStyles(MyWebComponent, styles);
};
```

If you really like to have some implicit behavior, you can add these lines by a loader automatically.

**Comment by merlinnot** [comment]
Thanks for the answer, I gave it a shot and it worked kinda well, I'm pleased with the implementation.

I still believe that it would be nice to have such option, tho :)
