### ISSUE TITLE
Webpack Child Compiler does not track dependencies for the first child compilation

### ISSUE THREAD

**Issue by jantimon** [webpack/webpack#8245]
# Bug report

**What is the current behavior?**

The content of `fileTimestamps` of the first child compiler run is always **empty**.  
This leads to https://github.com/jantimon/html-webpack-plugin/issues/1072

**If the current behavior is a bug, please provide the steps to reproduce.**

In the attached [webpack-repro.zip](https://github.com/webpack/webpack/files/2496040/webpack-repro.zip) demo repository run: `npm start`:

![step1](https://user-images.githubusercontent.com/4113649/47221667-5564a280-d3b5-11e8-8944-be0a14d772ae.jpg)

Now while the server is still running change either: `src/index.js` or `main.js` or `dependency.js`

![step2](https://user-images.githubusercontent.com/4113649/47221743-8644d780-d3b5-11e8-951d-ee69cf1dc21c.jpg)

If you change any file after that it will work as expected:

![step3](https://user-images.githubusercontent.com/4113649/47221778-a07eb580-d3b5-11e8-9038-8091bd24ab33.jpg)

The code used in the zip for reference:

webpack.config.js
```js
module.exports = {

  plugins: [
    { apply: examplePlugin }
  ]
}

const NodeTemplatePlugin = require('webpack/lib/node/NodeTemplatePlugin');
const NodeTargetPlugin = require('webpack/lib/node/NodeTargetPlugin');
const LoaderTargetPlugin = require('webpack/lib/LoaderTargetPlugin');
const LibraryTemplatePlugin = require('webpack/lib/LibraryTemplatePlugin');
const SingleEntryPlugin = require('webpack/lib/SingleEntryPlugin');
const compilerName = 'exampleCompiler';

function examplePlugin(compiler) {
  let previousChildCompiler;
  compiler.hooks.make.tapAsync('DemoPlugin', (mainCompilation, callback) => {
    if (previousChildCompiler) {
      const trackedFiles = Array.from(previousChildCompiler.fileTimestamps.keys());
      console.log('\n\previous compilation tracked:\n', trackedFiles);
      console.log(trackedFiles.some((file) => file.indexOf('dependency.js') !== -1) ? 'dependency.js is watched' : 'dependency.js is not watched');
      console.log('\n')
    }
    
    const outputOptions = {
      filename: '[name]',
      publicPath: mainCompilation.outputOptions.publicPath
    };
    const childCompiler = mainCompilation.createChildCompiler(compilerName, outputOptions);
      // The file path context which webpack uses to resolve all relative files to
      childCompiler.context = mainCompilation.compiler.context;
      // Compile the template to nodejs javascript
      new NodeTemplatePlugin(outputOptions).apply(childCompiler);
      new NodeTargetPlugin().apply(childCompiler);
      new LibraryTemplatePlugin('GLOBAL', 'var').apply(childCompiler);
      new LoaderTargetPlugin('node').apply(childCompiler);

      // Fix for "Uncaught TypeError: __webpack_require__(...) is not a function"
      // Hot module replacement requires that every child compiler has its own
      // cache. @see https://github.com/ampedandwired/html-webpack-plugin/pull/179
      childCompiler.hooks.compilation.tap('DontKnowWhatThisDoes', compilation => {
        if (compilation.cache) {
          if (!compilation.cache[compilerName]) {
            compilation.cache[compilerName] = {};
          }
          compilation.cache = compilation.cache[compilerName];
        }
      });

      // Add all templates
      new SingleEntryPlugin(childCompiler.context, './main.js', `ChildCompiler-Main`).apply(childCompiler);
      childCompiler.runAsChild((err, entries, childCompilation) => {
        previousChildCompiler = childCompiler;
        callback();        
      });



    })
      
  }
```

**What is the expected behavior?**

All dependencies of the child compilation build should be tracked.

**Other relevant information:**
webpack version:  4.21.0
Node.js version: v8.10.0

**Comment by sokra** [comment]
> The content of `fileTimestamps` of the first child compiler run is always **empty**.

That's actually correct. `fileTimestamps` is the data passed from the Watcher to the Compilation. It will be used to invalidate cache entries for modules. The first compilation isn't triggered by the watcher and has no timestamps from it available. That's expected and will lead to all modules (re)building.

If you want to know which dependencies are "tracked" by the compilation you should take a look at `childCompilation.fileDependencies`, which includes `dependency.js`. You also see recompilation triggered when `dependency.js` is changed.

---

Anyway back to your original problem: Maybe it's recompiling successfully but doing a hot update (which is possible because no module in the main compilation has changed) which doesn't update the index.html.

**Comment by sokra** [comment]
see https://github.com/jantimon/html-webpack-plugin/issues/1072#issuecomment-431649644

**Comment by jantimon** [comment]
thank you so much @sokra I’ll take a look 👍👍
