### ISSUE TITLE
Is it possible to “simulate” hot updates from within the client code?

### ISSUE THREAD

**Issue by gaearon** [webpack/webpack#825]
I know it's a weird request but I want to be able to simulate a hot update of a particular module from within the app. The desired effect is to have Webpack re-execute the same code it used to load the module, and to propagate this as if this was a hot update.

The purpose is to experiment with force-wiping Stores' state and replaying Actions on them for time travel.

**Comment by sokra** [comment]
hmm... there is no API for this.

a) You could inject a update if you expose such a API with a plugin.

b) You could reimplement it on "user level". All information is available to modules: `require.cache` (list of all installed module objects), `module.parents` `module.children`, `module.hot._acceptedDependencies` `module.hot._selfAccepted` etc.

**Comment by gaearon** [comment]
These are good starting points, thank you! I'll close this for now, and will post here if I figure this out, or if I have additional questions.
