### ISSUE TITLE
HMR re-installs unchanged dependencies on every second save

### ISSUE THREAD

**Issue by gaearon** [webpack/webpack#826]
This may be by design and I may not understand HMR correctly but I noticed something odd about hot reloading.

Say we enable React Hot Loader for JSX files. Consider `app.jsx`:

```js
'use strict';

var React = require('react'),
    Child = require('./child');

var App = React.createClass({
  render() {
    return (
      <Child />
    );
  }
});

module.exports = App;
```

and `child.jsx`:

```js
'use strict';

var React = require('react');

alert('running child module');

var Child = React.createClass({
  render() {
    return <h1>Child</h1>;
  }
});

module.exports = Child;
```

For both, React Hot Loader will emit HMR code that accepts the update.

**You can find a reproducible example in [this branch of React Hot Boilerplate](https://github.com/gaearon/react-hot-boilerplate/compare/webpack-hot-reload-issue).**

Now follow these steps:

1.`npm start` and open `localhost:3000`
2. You will see “running child module” because `client.jsx` executes
3. Make any edit to `app.jsx`
4. You will see “Updated modules:  - 6” (corresponds to App)
5. Make **another** edit to `app.jsx`
6. You will see “Updated modules:  - 6” again..
7 ... but for some reason you will also see “running child module”

On every even save (2nd, 4th, 6th, ...) `child.jsx` will be missing from `installedModules` and re-installed. This is not a big deal most of the time, but may cause side effects you don't expect (you edit file A, side effects from file B occur—maybe B just doesn't properly handle them but you were *not* editing it).

Is this a bug?

**Comment by sokra** [comment]
Sounds like a bug...

**Comment by sokra** [comment]
Pretty weird... Normally updates only propagate only the parent not the children. And they should propagate at all with self accepted modules. And if they would propagate you would see it in the message...

**Comment by sokra** [comment]
Ok I have an idea: There is some mechanims in the hmr runtime which disposes modules that are no longer used. It could affect the child module as it is no longer referred while disposing the parent module. We should move this mechnism after the end of reloading.

**Comment by gaearon** [comment]
:+1:

**Comment by gaearon** [comment]
Thank you!

**Comment by frederickfogerty** [comment]
:+1:

**Comment by gaearon** [comment]
Looking forward to seeing this in a release :-)

**Comment by gaearon** [comment]
Thank you!
