### ISSUE TITLE
Can you PLEASE improve the SplitChunksPlugin error message?

### ISSUE THREAD

**Issue by matthew-dean** [webpack/webpack#8260]
## Feature request

**What is the expected behavior?**

Right now the error is:
```
Error: SplitChunksPlugin: You are trying to set a filename for a chunk which is (also) loaded on demand. The runtime can only handle loading of chunks which match the chunkFilename schema. Using a custom filename would fail at runtime. (cache group: default)
```

**What is motivation or use case for adding/changing the behavior?**

Often times this happens after a merge. Somewhere, someone on our team referenced a file. Someone, somewhere else, at some point in time, referenced the same component, but as an async import. Unfortunately this error message gives zero insight into what component or where this import was in conflict. We have no way of knowing aside from going through commit by commit to see what the SplitChunksPlugin is complaining about.

**How should this be implemented in your opinion?**

Tell us WHY this error occurred. What is the filename / chunk that is trying to be created? What is the source of this error?

**Are you willing to work on this yourself?**
no

**Comment by sokra** [comment]
Why: You are trying to set a filename for a chunk which is (also) loaded on demand.

Source: (cache group: default)

The error doesn't origin from a component. It's a incorrect configuration. You are trying to set the `filename` where it's not possible. Check either `optimization.splitChunks.filename` or `optimization.splitChunks.cacheGroups.default.filename` and remove it.

Send a PR to improve it

**Comment by douglasg14b** [comment]
I suppose the question is, why does Split Chunks start throwing this error from something as small as changing a filename (ie. xxx.vue to yyy.vue)?

The error provides no info that helps resolve or find the issue, the comment about a configuration issue would make sense if a configuration as changed, but it has not.

**Comment by leereichardt** [comment]
What @douglasg14b said is absolutely correct. I've just started using dynamic imports. I've used it successfully for 2 libraries and 2 of my own files. I then tried to use it for a third, and no matter what I set the Chunkname as, I got the above error with no information to help me figure out why. When I remove the dynamic import and rebuild, there are no files that would match the chunkname, yet I still get the above error.

Any help on how to diagnose what's going on here would be hugely appreciated!

**Comment by leereichardt** [comment]
@douglasg14b I managed to finally fix this by not specifying a filename for my 'vendors' chunk. I had to remove this, and I ended up using HTMLWebpackPlugin and build a template to output all my entry points (If you aren't already) to get the correct hashed vendors file name. Does that make sense? (Don't want to waffle :) )
