### ISSUE TITLE
Generate the output file based on the order defined inside the entry property

### ISSUE THREAD

**Issue by Rig-ved** [webpack/webpack#8264]
Hi Team ,

Need a small help !!  Below is my webpack.config.js

`webpack.config.js`
```
const path = require('path');
var config = {
    module: {},
};
//base min minification
var base = Object.assign({}, config, {
    mode: 'development',
    entry: [
    './scripts_common/common/base64.js',
    './scripts_common/constants.js',
    './scripts_common/common/classes/List.class.js',
    './scripts_common/common/classes/Map.class.js',
    './scripts_common/database/Event.db.js'
    ],
    watch:true,
    output: {
      path: path.resolve(__dirname, 'scripts1_min/common/package'),
      filename: 'base.min.js'
    }
});
module.exports = [
    base,
];
```
**What is the current behavior?**
The issue is when i run the npm run build option, it bundles the files which is fine 
but in wrong order (based on sort of folders).Incorrect order inside base.min.js:(base64 -- > List.class -->Map.class--> constants -->Event.db.js)

**What is the expected behavior?**
I need the order to be like (base64 --> constants -->List.class -- >Map.class --> Event.db.js) which is exactly similar to the order defined inside "entry" property.

**Why I need this way ?** 
I have a lot of files which needs to be bundled in different outputs, and one file has certain dependency with another file so cant change the bundling order as it may cause discrepancies ,Since its a legacy application (.jsp), the bundling also cant have its own htmltemplate directly .hence the need .

Please help guys

**Comment by Rig-ved** [comment]
@evilebottnawi  Sorry my bad .. updated the same

**Comment by sokra** [comment]
The order in the bundle file doesn't matter. It's executed in the order specified in the `entry` option.

**Comment by Rig-ved** [comment]
@sokra 

```
 entry: [
    './scripts_common/common/base64.js',
    './scripts_common/constants.js',
    './scripts_common/common/classes/List.class.js',
    "./scripts_common/common/classes/App.class.js",
    './scripts_common/common/classes/Map.class.js',
    './scripts_common/database/Event.db.js'
    ],
```
**Output (Inside base.min.js)**  
```

  ./scripts_common/common/base64.js 
  ./scripts_common/common/classes/App.class.js:
  ./scripts_common/common/classes/List.class.js',
  ./scripts_common/common/classes/Map.class.js,
   './scripts_common/constants.js'
```
**What is the current behavior?**
The output is generated in the alphabetical order inside the base.min.js which is creating problem. 

Is there any configuration to be placed to keep the same order ?

**Comment by evilebottnawi** [comment]
@Rig-ved 
```js
 entry: { 'my': [
    './scripts_common/common/base64.js',
    './scripts_common/constants.js',
    './scripts_common/common/classes/List.class.js',
    "./scripts_common/common/classes/App.class.js",
    './scripts_common/common/classes/Map.class.js',
    './scripts_common/database/Event.db.js'
    ] },
```
?

**Comment by Rig-ved** [comment]
@evilebottnawi 

I am not sure if i understand your answer correctly , can you please elaborate

**Comment by Rig-ved** [comment]
@sokra  @evilebottnawi 

Any inputs here would of great help !!!

**Comment by kp1007** [comment]
hi, rig-ved have u found any solution actually i also facing same issue

**Comment by onomemineadamu** [comment]
Hello Kp1007 have you been able to fix this
