### ISSUE TITLE
Hashed module ids by default

### ISSUE THREAD

**Issue by smelukov** [webpack/webpack#8268]
## Feature request

**What is the expected behavior?**

Consistent chunk hash

**What is motivation or use case for adding/changing the behavior?**

After [this PR](https://github.com/webpack/webpack/pull/8029) we have got worst long-term caching "out of the box" because modules id were changed very often (even if don't change these modules) and chunk hash was changed too (because modules id were in bootstrap code).

**How should this be implemented in your opinion?**

`optimization.moduleIds: 'hashed'` in prod-mode by default

**Are you willing to work on this yourself?**
yes

**Comment by ooflorent** [comment]
`moduleIds: hashed` is deprecated in the `next` branch in favor of `deterministic`.

**Comment by smelukov** [comment]
@ooflorent got it
I still think that `moduleIds` should be ~`hashed`~ `deterministic` by default

**Comment by smelukov** [comment]
If there are no objections then I would like to create PR

**Comment by ooflorent** [comment]
Sure! Then do it on `next` branch ;)

**Comment by smelukov** [comment]
done

**Comment by smelukov** [comment]
Seems like I've got some unexpected changes in tests - https://ci.appveyor.com/project/sokra/webpack/builds/19790456
Any ideas?

**Comment by smelukov** [comment]
Any ideas what’s wrong with tests? :)

**Comment by smelukov** [comment]
Is anyone can look at the test's error?

**Comment by smelukov** [comment]
PR was merged 🎉

**Comment by smelukov** [comment]
> moduleIds: hashed is deprecated in the next branch in favor of deterministic.

@ooflorent can you tell me please what's the biggest profit from using `DeterministicModuleIdsPlugin` instead of `HashedModuleIdsPlugin`? Why `HashedModuleIdsPlugin` will deprecated in webpack 5
