### ISSUE TITLE
Using global.X breaks concatenation

### ISSUE THREAD

**Issue by hlehmann** [webpack/webpack#8271]
# Bug report

**What is the current behavior?**
When a module contains `global` for example `if(global.MY_DEBUG) {...}`, `global` is treated as a `cjs require` dependency, breaking the concatenation.

**If the current behavior is a bug, please provide the steps to reproduce.**
Simply add a global.X in a module.

**What is the expected behavior?**
Allow concatenation for this module.

**Other relevant information:**
webpack version:  4.23.1
Node.js version: 10
Operating System: ubuntu
Additional tools:

**Comment by sokra** [comment]
already fixed in the `next` branch
