### ISSUE TITLE
Cannot resolve babel module when compiler ohter folder

### ISSUE THREAD

**Issue by HuangQiii** [webpack/webpack#8275]
# Bug report

**What is the current behavior?**

when i run webpack, `Module build failed: ReferenceError: Unknown plugin "transform-async-to-generator" specified`.

i tryed to don't import code in top folder, it `success`

my folder is like this
![image](https://user-images.githubusercontent.com/11797760/47499293-30c76980-d892-11e8-80ab-9e9422ac8259.png)

my basic folder is in generate-react, the file named `getWebpackCommonConfig.js` is webpack config and `getBabelCommonConfig.js` is babel config

```javascript
// getWebpackCommonConfig.js
...
resolve: {
    modules: ['node_modules', path.join(__dirname, '../../node_modules')],
    extensions: ['.web.tsx', '.web.ts', '.web.jsx', '.web.js', '.ts', '.tsx', '.js', '.jsx', '.json'],
  },
  resolveLoader: {
    modules: ['node_modules', path.join(__dirname, '../../node_modules')],
  },
...
```

```javascript
// getBabelCommonConfig.js
...
function getBabelCommonConfig() {
  return {
    presets: [
      'react',
      [
        'es2015',
      ],
      'stage-1',
    ],
    plugins: [
      'transform-async-to-generator',
      'transform-decorators-legacy',
      'transform-class-properties',
      'transform-runtime',
      'lodash',
      [
        'import',
        [
          {
            libraryName: 'choerodon-ui',
            style: true,
          },
          {
            libraryName: 'antd',
            style: true,
          }
        ]
      ],
    ],
  };
}

module.exports = getBabelCommonConfig;
...
```

**If the current behavior is a bug, please provide the steps to reproduce.**

i don't think is is a bug, but i have no idea to solve it.

**What is the expected behavior?**

can webpack success when i start in a folder (nodue_modules in this folder) but import code in other folder

**Other relevant information:**
webpack version:  3.12.0
Node.js version: v8.9.3
Operating System: win 10
Additional tools:in the blow pic

![image](https://user-images.githubusercontent.com/11797760/47499672-1e016480-d893-11e8-8ecf-e24ad9af5c5e.png)
![image](https://user-images.githubusercontent.com/11797760/47499679-23f74580-d893-11e8-82d6-5a720cb559c2.png)

and in the webpack 4 and babel7, this way can be success, so what i should do in webpack3 and babel6

**Comment by evilebottnawi** [comment]
@HuangQiii please format you issue using issue template, otherwise you issue will be closed

**Comment by evilebottnawi** [comment]
Not webpack problem, you need install plugin for babel-loader
