### ISSUE TITLE
Error bootstrapping maybe related to AMD

### ISSUE THREAD

**Issue by jasonkuhrt** [webpack/webpack#828]
I am having a build error with the `node-semver` module because of these two lines (so far as I've tracked up to now):

https://github.com/npm/node-semver/blob/master/semver.js#L1165-L1166

The error is:

```
 Uncaught TypeError: Invalid Version: function (request) {
/******/            if(me.hot.active) {
/******/                if(installedModules[request]) {
/******/                    if(installedModules[request].parents.indexOf(moduleId) < 0)
/******/                        installedModules[request].parents.push(moduleId);
/******/                    if(me.children.indexOf(request) < 0)
/******/                        me.children.push(request);
/******/                } else hotCurrentParents = [moduleId];
/******/            } else {
/******/                console.warn("[HMR] unexpected require(" + request + ") from disposed module " + moduleId);
/******/                hotCurrentParents = [];
/******/            }
/******/            return __webpack_require__(request);
/******/        }
```

When I remove the source code lines linked above then everything is fine.

So the error is because of some part of the bootstrapping process as related to `AMD`?

I need help here because I don't even know how to being to debug this issue. Something somewhere by someone needs to change. Any advice greatly appreciated.

Thanks

**Comment by jasonkuhrt** [comment]
Ok following anecdotes in https://github.com/webpack/webpack/issues/333#issuecomment-55099396

I was able to bypass this error `config.module.loaders` like so: 

```
      { test: /semver\.browser\.js/, loaders: ['imports?define=>undefined'] },
```

This gets me unblocked for now, but its awful to keep around forever. Any insight about how this could work ho-hum like any other dependency please let me know. Is the `semver` module using `AMD` incorrectly?

**Comment by jhnns** [comment]
They're using it wrong as far as I can tell. The line should be:

```javascript
if (typeof define === 'function' && define.amd)
  define(function () { return exports; });
```

Since they're checking for `define.amd` you can also use the [amd-option](http://webpack.github.io/docs/configuration.html#amd) to disable amd for this module.

**Comment by jasonkuhrt** [comment]
@jhnns Thanks for confirming. I will try a PR with them then.

> Since they're checking for define.amd you can also use the amd-option to disable amd for this module.

I tried without success sadly. Regardless of the value I assigned to `amd` it was always `{}` in the `semver` module.

**Comment by bebraw** [comment]
@jasonkuhrt Safe to close?

**Comment by jasonkuhrt** [comment]
Don't know, long time since I looked at this. Not going to any time soon I think.

**Comment by bebraw** [comment]
Looks like they did something about it, https://github.com/npm/node-semver/commit/41b56fa573d1ef0d1718777a8a21ae1b57ebcd83 .
