### ISSUE TITLE
页面编码格式是gbk，按需加载chunk.js文件时,script 标签自动添加charset=“utf-8”，造成js中的中文乱码

### ISSUE THREAD

**Issue by gaogao2017** [webpack/webpack#8281]
# Bug report

**What is the current behavior?**
网站整体编码是gbk，在使用vue-route按需加载功能时，发现webpack加载chunk.js 文件时，script标签自动添加charset="utf-8"，造成js中的中文在页面显示时乱码。

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
经排查，是webpack\lib\web\JsonpMainTemplatePlugin.js 文件中设置的script.charset=‘utf-8',建议去掉此行代码，或者能在配置项中设置chunk的编码格式

**Other relevant information:**
webpack version:  4.12.0
Node.js version: v8.11.3
Operating System: win7
Additional tools:

**Comment by evilebottnawi** [comment]
Please use English language
