### ISSUE TITLE
"Loading chunk failed" only for Windows users 

### ISSUE THREAD

**Issue by Manuelandro** [webpack/webpack#8283]
# Bug report
**What is the current behavior?**
Dynamic import splits correctly in chunks and everything works fine except for Windows users which seems unabled to load chunks from the dist folder.
No matter which browser they use,
Apart from the specific chunk you see in the screens, it happens to a whole set of files

**Webpack optimization and entries configuration**
```
   entry: {
        "app.bundle.js": "./app/js/components/app/app.js",
        "main.bundle.js": "./app/js/main.js",
    },
   output: {
        path: path.resolve(__dirname, '../dist'),
        publicPath: './dist/',
        filename: '[name]', // for multiple entry points
        chunkFilename: '[name].js',
    },
    optimization: {
         namedModules: true,
         namedChunks: true,
         minimizer: [
              new UglifyJSPlugin({
              sourceMap: true,
                   uglifyOptions: {
                        mangle: false,
                   },
               }),
          ],
          splitChunks: {
               cacheGroups: {
                   vendors: {
                          test: /[\\/]node_modules[\\/]/,
                          priority: 10,
                      },
                 }, 
           },
      }
```

**Example of dynamic import in the code**
```
    ....
    try {
        const module = await import(/* webpackChunkName: "checkToken" */ './globals/checkToken')
        module.default(someArgs)
    } catch (err) {
        SentryException(err)
    }
    ...
```

**Other relevant information:**
webpack version:  ^4.4.1
Node.js version:  8.0.0

Users are from Windows 7 to 10 and use any browser (Firefox, Chrome, IE11...)

**Here is some screen from my Sentry service**

![schermata 2018-10-26 alle 10 44 24](https://user-images.githubusercontent.com/3776546/47555461-2d70c400-d90c-11e8-9cae-cf7aa3c9e174.png)

![schermata 2018-10-26 alle 10 45 53](https://user-images.githubusercontent.com/3776546/47555534-598c4500-d90c-11e8-96e4-6c0b32eb87bd.png)

**Comment by evilebottnawi** [comment]
@Manuelandro please create minimum reproducible test repo, for me and many other developers all works fine, looks problem on your side

**Comment by sokra** [comment]
Try debugging on a windows machine. I'm pretty sure it's not a webpack issue.
