### ISSUE TITLE
I'm facing this error while getting new build, Error: LoadConfigError: Cannot find module 'sigmund'

### ISSUE THREAD

**Issue by kapilropani** [webpack/webpack#8285]

**Comment by kapilropani** [comment]
Here is the snapshot of Error that I'm facing.

![image](https://user-images.githubusercontent.com/14115896/47574618-700cbd80-d959-11e8-948e-34953f3c4add.png)

**Comment by ooflorent** [comment]
It looks like you just deleted/ignored our [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template.
