### ISSUE TITLE
 ﻿ message.js:17 Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by crloshro** [webpack/webpack#8290]
# Bug report

**What is the current behavior?**
The console of the browser gives me the bug:Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

**If the current behavior is a bug, please provide the steps to reproduce.**
I run npm at terminal and after this when I am refreshing index.html the console give me that bug.

[GitHub repository](https://github.com/crloshro/react-webpack)

**What is the expected behavior?**

That index.html give some examples that I'm doing 

**Other relevant information:**
node.js v 8.12
"devDependencies": {
    "@babel/core": "7.1.2",
    "@babel/plugin-transform-runtime": "^7.1.0",
    "@babel/preset-env": "7.1.0",
    "@babel/preset-es2015": "7.0.0-beta.53",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "8.0.4",
    "babel-polyfill": "6.26.0",
    "babel-preset-react": "^6.24.1",
    "css-loader": "1.0.0",
    "extract-text-webpack-plugin": "4.0.0-beta.0",
    "file-loader": "^2.0.0",
    "json-loader": "^0.5.7",
    "style-loader": "0.23.1",
    "url-loader": "1.1.2",
    "webpack": "4.23.1",
    "webpack-cli": "3.1.2",
    "webpack-dev-server": "3.1.10"
  },
  "dependencies": {
    "@babel/runtime": "7.1.2",
    "react": "^16.6.0",
    "react-dom": "^16.6.0"

**Comment by sokra** [comment]
pass `{modules: false}` to preset-env.

**Comment by crloshro** [comment]
I did it :

 use:{
          loader:'babel-loader',
          options:{
            presets: [
              ['@babel/preset-env',{
                modules:false
              }]
              ,'@babel/preset-react']
          }
        }
      },

But It doesn't work

**Comment by sokra** [comment]
You are not allowed to use `module.exports` in a ESM (using `import`).

Use `export` instead.
