### ISSUE TITLE
Webpack creates two tabs in browser when I save changes in code editor.

### ISSUE THREAD

**Issue by Ranguro** [webpack/webpack#8291]
# Bug report

**What is the current behavior?**
* Whenever I hit the save button in my text editor, webpack generates 2 new tabs in Google Chrome with the introduced changes. If there aren't changes and I hit the save button, webpack still opens the 2 new tabs. 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
* When there are changes in my code and I hit the save button, webpack should start the project in 1 tab and do "n" livereloads in the current tab. 

**Other relevant information:**
webpack version:  3.12.0 
Node.js version: 8.11.4  
Operating System: Windows
Additional tools: 
    webpack-bundle-analyzer: 2.13.1
    webpack-cl": 2.0.0
    webpack-dev-server: 2.11.3
    webpack-hot-middleware: 2.22.2
    webpack-merge: 4.1.3

**Comment by buoyantair** [comment]
Can you check  if you  share your webpack config file?

**Comment by Ranguro** [comment]
@buoyantair I don't understand your question.

**Comment by sokra** [comment]
This repo does not open any tab. Please check which plugin/tool/dependency cause this behavior and open an issue there.

**Comment by Ranguro** [comment]
Isn't webpack in charge of live reload?
