### ISSUE TITLE
Cannot find module 'redux-undo'

### ISSUE THREAD

**Issue by lidaof** [webpack/webpack#8292]
# Bug report

**What is the current behavior?**
Cannot find module 'redux-undo'

**If the current behavior is a bug, please provide the steps to reproduce.**
I am using the latest beta version of redux-undo, whenever I saved an edited file, webpack cannot find this module.

Cannot find module 'redux-undo'.

if I rerun `npm start` I will be fine

**What is the expected behavior?**

the module be loaded normally

redux-undo author think it's a webpack issue asked me to post issue here

https://github.com/omnidan/redux-undo/issues/212

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by lidaof** [comment]
hi @sokra sorry somehow I cannot reproduce it as current create-react-app require a new version of node.js....so the problem just happen to occur in my project...

you can close this issue.
