### ISSUE TITLE
DefinePlugin regression

### ISSUE THREAD

**Issue by FranckFreiburger** [webpack/webpack#8293]
# Bug report

**What is the current behavior?**

DefinePlugin does not replace things in all situations.
I encounter this issue while upgrading from webpack v3.6.0 to v4.23.1

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
new webpack.DefinePlugin({
	NAME: 'foobar'
})
```
then:
```js
import(`./${NAME}.yaml`)
```

expands to:

```js
__webpack_require__("../mytest lazy recursive ^\\.\\/.*\\.yaml$")('./' + NAME + '.yaml')
```

that is not correct.

**Other relevant information:**
webpack version:  4.23.1
Node.js version: 10.10
Operating System: win7
Additional tools:

**Comment by ljqx** [comment]
I got some initial investigation:
[ImportParserPlugin](https://github.com/webpack/webpack/blob/master/lib/dependencies/ImportParserPlugin.js#L257) stops `walk` on its param when creating context, but it shouldn't.

Changing the return value to `false` should fix it.

I can try to send out a fix for it.

**Comment by sokra** [comment]
``` diff
 new webpack.DefinePlugin({
-	NAME: 'foobar'
+	NAME: '"foobar"'
 })
```

**Comment by sokra** [comment]
hmm seems like to intentionally passed an expression. Than it seems to be a bug.

As workaround:

``` js
const name = NAME;
import(`./${name}.yaml`)
```

**Comment by FranckFreiburger** [comment]
Sorry for my wrong test, it should be:

```
new webpack.DefinePlugin({
	NAME: '"foobar"'
})
```

```
var tmp = '';
import(./${NAME}${tmp}.yaml)
```

expands to:
```
var x = '';
__webpack_require__("../myTest lazy recursive ^\\.\\/foobar.*\\.yaml$")(`./${NAME}${tmp}.yaml`)
```

**Comment by sokra** [comment]
ah ok. That seem to be different.

**Comment by FranckFreiburger** [comment]
Yes, but in both situations, something is not properly expanded.

**Comment by FranckFreiburger** [comment]
@sokra, it seems that the problem is still present (in v4.25.0)
NAME is not replaced by "foobar" as expected:
```
__webpack_require__("../myTest lazy recursive ^\\.\\/foobar.*\\.yaml$")('./' + NAME + tmp + '.yaml')
```

**Comment by ljqx** [comment]
It works at my side, check https://github.com/ljqx/webpack-test-import-parser.

The fix only works for template string, it doesn't include fix for string concated by `+`. That needs another fix to work.

I can have a try.

**Comment by sokra** [comment]
I already have a fix. Sorry didn't read your comment.

**Comment by sokra** [comment]
#8338
