### ISSUE TITLE
Promisifed webpack returns errors as a return value

### ISSUE THREAD

**Issue by yoav-lavi** [webpack/webpack#8298]
# Bug report

**What is the current behavior?**

When using promisify on Webpack as follows: `const asyncWebpack = promisify(webpack);`, any compilation errors are returned as a value rather than thrown.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. require and promisify Webpack
2. attempt to compile a file with a local require that does not exist

the result will be that a "dist" folder is not created but Webpack throws no error. (although does specify the error in it's return value)

This is my configuration: 

```js

const webpack = require("webpack");
const asyncWebpack = promisify(webpack);

// ...

// the following code is in a try / catch block

const result = await asyncWebpack({
  target: "node",
  entry: join(process.cwd(), normalize(folder), index),
  mode: "production",
  output: {
    library: name,
    libraryTarget: "umd",
    filename: join(name, index)
  },
  plugins: [new webpack.IgnorePlugin(/^hiredis*/)],
  externals: ["aws-sdk"]
});

// result contains error information!

```

**What is the expected behavior?**

Webpack should throw an error upon compilation issues.

**Other relevant information:**

webpack version:  ^4.17.2
Node.js version: v11.0.0
Operating System: macOS Mojave
Additional tools: -

**Comment by cacheflow** [comment]
I'm happy to take a look at this.

**Comment by cacheflow** [comment]
Hi @yoav-lavi after looking into this I'm not sure if this is an actual bug. It seems like when there's certain errors in Webpack they're deliberately not thrown and instead just returned attached to the result, so compiling can still continue. What are your thoughts? @sokra @timse?

**Comment by yoav-lavi** [comment]
Hey, this makes sense in a certain type of usage, although the only alternative to this would be using `bail`, which exits the process (even if webpack is just being used as a module) rather than throwing the error. The expected result would be `bail` throwing errors when used as a module, or adding a different flag to do so.

**Comment by cacheflow** [comment]
I have a branch that just throws an errors when a compilation has any errors via the callback passed in, but I'd be more than happy to implement it this way. 

However, I've only seen bail being used as a boolean check. Can you point me to somewhere in the code where bail is being used to throw errors? @yoav-lavi
