### ISSUE TITLE
Dynamic imports do no take the webpackJsonP index into account when generating their hash

### ISSUE THREAD

**Issue by stephan-v** [webpack/webpack#8300]
# Bug report

**What is the current behavior?**

Webpack does not take take the `webpackJsonP` index into account when generating the chunk hash for dynamic imports.

**If the current behavior is a bug, please provide the steps to reproduce.**

I am outputting my dynamically imported chunks like so:

    output: {
        publicPath: process.env.MIX_CDN,
        chunkFilename: 'js/chunks/[name].[chunkhash].js'
    }

These async chunks for my dynamic imports contain a `webpackJsonp` call with an index which represents the current module that I want to load. As an example:

    webpackJsonp([18],{F0ir:function(t,e,o){(t.exports=o("FZ+f")(!1)).push([...

The chunkhash is always updated properly when the content is changed, but it does not update when the `WebpackJsonP` index is updated. This index can change due to me removing or adding more dynamic imports. 

The dynamic imports fail to load because an outdated file is being fetched from the browser cache with a wrong index. The browser does not know of the existence of a new file because the chunkhash did not update.

What was once` webpackJsonp([18]` might now simply be `webpackJsonp([9]`.

My `manifest.js` contains references to the new index of `9` but the old file is still being served from cache due to the chunkhash not updating.

**What is the expected behavior?**

When the `webpackJsonP` index is updated the file should also generate a chunkhash which takes this into account.

**Other relevant information:**
webpack version:  3.11.0
Node.js version: 8.9.6
Operating System: Ubuntu 17.10
Additional tools: laravel-mix

**Comment by stephan-v** [comment]
Unfortunately the current application uses [laravel-mix](https://github.com/JeffreyWay/laravel-mix) which has not been updated yet. If we want to switch over we need to set up Webpack from the ground up without laravel-mix.

Are you sure that Webpack v4 contains fixes that help with this particular issue though?

**Comment by sokra** [comment]
Hmm in webpack 3 and 4 the chunk ids contribute to the hash:

https://github.com/webpack/webpack/blob/cce33c206abaeef26d06b62102adf74a989a4696/lib/Chunk.js#L353

**Comment by sokra** [comment]
Are you using any plugin which changes the hashing?

**Comment by stephan-v** [comment]
I think the only plugin for the chunk hash is this one:

https://github.com/alexindigo/webpack-chunk-hash

Which is used here:

https://github.com/JeffreyWay/laravel-mix/blob/a57fcf7e5ecd8ca3a8294d92fad1905c700cd6f6/src/components/Version.js

I would appreciate if you could take a look not just for me but for everyone who uses `laravel-mix`. If there is something going wrong I will make a pull request for `laravel-mix` which will help out everyone.

I will continue looking as well, thanks for the help so far.

**Comment by sokra** [comment]
yep this plugin is the problem.

**Comment by sokra** [comment]
Some people think if hashes change less often, the file is cached more often...
