### ISSUE TITLE
HMR doesn't update UI in Typescript/webpack-(dev + hot)-middlware

### ISSUE THREAD

**Issue by kuehlein** [webpack/webpack#8303]
# Bug report

**What is the current behavior?**
UI is not updated while using HMR.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/kuehlein/typescript-webpack-hmr

**What is the expected behavior?**
UI should reflect changes in client side code without having to refresh the page.

**Other relevant information:**
webpack version:  4.23.1
Node.js version:  v10.9.0
Operating System: mac os high sierra 10.13.6
webpack-dev-middleware: 3.4.0
webpack-hot-middleware: 2.24.3
typescript: 3.1.3
ts-loader: 5.2.2
react-hot-loader: 4.3.11

**Comment by evilebottnawi** [comment]
@kuehlein please reduce size of minimum reproducible test repo

**Comment by kuehlein** [comment]
@evilebottnawi I've reduced the size a bit. I think that's as small as it can get while still maintaining the control flow that may relate to this problem.
