### ISSUE TITLE
Path2D is not supported

### ISSUE THREAD

**Issue by mindrones** [webpack/webpack#8304]
# Bug report

[Path2D](https://developer.mozilla.org/en-US/docs/Web/API/Path2D) is not supported.

**What is the current behavior?**

Using `const path = new Path2D();` throws `ReferenceError: Path2D is not defined`.

**If the current behavior is a bug, please provide the steps to reproduce.**

First off, a config that works:

```js
npx degit sveltejs/sapper-template my-app
cd my-app
npm install
npm run dev
```
you should get something like:

```bash
✔ server (532ms)
✔ client (684ms)
✔ service worker (27ms)
> Listening on http://localhost:3000
```

Now in `src/routes/_layout.html`, add this `const path = new Path2D();` as the first line of the `<script>`.

You'll get something like:

```bash
src/routes/_layout.html changed. rebuilding...
✔ server (108ms)
✔ client (109ms)
> Server crashed
webpack:///./src/routes/_layout.html?:7
const path = new Path2D();
             ^
ReferenceError: Path2D is not defined
```

**What is the expected behavior?**

It should not throw the error as Path2D is part of the web API and it seems to be supported by major browsers (see the section on the bottom of the doc page).

**Other relevant information:**

webpack version: 4.7.0
Node.js version: v10.9.0
Operating System: MacOS High Sierra 10.13.6
Additional tools: sapper/svelte

**Comment by sokra** [comment]
Not webpack related. It throws in your server code. Seems like `Path2D` does not exist in node.js

**Comment by pierreneter** [comment]
Check your webpack config with: https://webpack.js.org/concepts/targets/
