### ISSUE TITLE
Code organization is too messy！！！！

### ISSUE THREAD

**Issue by dorado-lmz** [webpack/webpack#8305]
First of all, thank you for creating webpack.
However the souce code of webpack is so **messy**!!!
I really can't read the code.😱really hope you can sort it out , or reorganize source code.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
