### ISSUE TITLE
Webpack config option to generate patch instead of new bundle

### ISSUE THREAD

**Issue by imvetri** [webpack/webpack#8309]
## Feature request

**What is the expected behavior?**
Webpack bundle to have option to generate patch instead of a new bundle

**What is motivation or use case for adding/changing the behavior?**
This feature is meant for bug fixes in production and not for feature releases. Lets say I fix a bug making a line of change. Pushing a new bundle to production seems to be a heavy task. Instead of that, webpack should generate a patch file and only this patch will be pushed to production.

Doing this will help to make a proper use of browser's cache.

**How should this be implemented in your opinion?**
Any bundle should look for patches, If there are no patch bundle should run as it is.
If there is a patch(if a line of code is changed, patch should be the entire function), the patch code should be able to override the original function in the bundle. 

**Are you willing to work on this yourself?**
yes - Preferably If this can be done without relying on webpack code. Reason is, working from scratch helps building fast than working on existing code base.

**Comment by evilebottnawi** [comment]
@imvetri how do you imagine the implementation of this? It is sound very difficult and impossible.

**Comment by sokra** [comment]
Technically possible, but in my opinion not worth it. You can split your bundle into parts which are individually cached, which has similar effect.

**Comment by imvetri** [comment]
Thanks @sokra, @evilebottnawi . I think it is not a relevant topic to discuss here. Continuing it in stackoverflow.

**Comment by evilebottnawi** [comment]
@imvetri Can we close issue?

**Comment by imvetri** [comment]
Yes. Thanks !
