### ISSUE TITLE
export EvalSourceMapDevToolPlugin

### ISSUE THREAD

**Issue by stephanos** [webpack/webpack#831]
Currently only `SourceMapDevToolPlugin` and `EvalDevToolModulePlugin` are exported and can be used directly as a plugin. But `devtools` also supports `eval-source-map`, which internally uses `EvalSourceMapDevToolPlugin`. It would be great to export it since it would allow customization of the `eval-source-map`-behaviour (in my case the source map url).

So please export `EvalSourceMapDevToolPlugin`.

**Comment by jhnns** [comment]
Feel free to send a PR

**Comment by stephanos** [comment]
@jhnns @hkal @sokra  thanks :)
