### ISSUE TITLE
ES6 native modules with bundled fallback

### ISSUE THREAD

**Issue by richturner** [webpack/webpack#8310]
## Feature request

Ability to compile so that native ES6 modules can be used on browsers that support them with a fallback to the usual webpack bundles when modules aren't supported (fallback implemented using the script tags `nomodule` attribute).

**What is the expected behavior?**

It should be easy to configure webpack to allow easy use of native ES6 modules in the web browser but allow a fallback to standard bundles when required.

The biggest problem with native ES6 modules is url resolution of imports; assuming that all imports in the codebase are already ES6 modules then webpack needs to just copy these to the output folder (configurable of course) and replace the url in the import statements (to point to the output) - This mechanism should support all import url syntax options. Conversion of commonJS and UMD modules to ES6 would be nice but I'm sure over time most packages will provide ES6 modules in NPM.

**What is motivation or use case for adding/changing the behavior?**

Given most major browsers now support native ES6 modules coupled with HTTP/2, unbundled modules are becoming a reality. we are in a transition period now where we need to support older browsers but ideally provide unbundled native ES6 modules for browsers that support them. Given webpack is used for more than just bundling already it is well placed to provide this functionality and be a tool that is useful for a long time to come.

**How should this be implemented in your opinion?**

I'm no webpack expert but some ideas:

* Simple built in configuration option(s)?
* Documentation?
* New plugin or loader?

**Are you willing to work on this yourself?**
Not very familiar with webpack under the hood but can help with developing/testing a solution.

**Comment by atomless** [comment]
Any update on when Webpack will support outputting native es6 modules? Will it be included in v5?
