### ISSUE TITLE
'resolve.alias' support network address

### ISSUE THREAD

**Issue by qq326943819** [webpack/webpack#8312]
## Feature request

**What is the expected behavior?**

I hope 'resolve.alias' supports network addresses.

**What is motivation or use case for adding/changing the behavior?**

The network address used by the static resource in the project. When making changes, only need to modify the remote resource.

**How should this be implemented in your opinion?**

Add configuration options in the 'resolve.alias' configuration to support skip resource monitoring, like this:
`
resolve: {
    alias: {
      '@': path.join(__dirname, '../src/renderer'),
      'vue$': 'vue/dist/vue.esm.js',
      '@re':{
        path:'http://resourse.myserver.com',
        check:false
      }
    }
  }
`
Then use this:
`Background-image:url('~@rs/images/bg.png');`

**Are you willing to work on this yourself?**
Sorry, I think I can't finish it.

**Comment by sokra** [comment]
That's outside of the scope of webpack. For CSS you can use variables/constants in any preprocessor.
