### ISSUE TITLE
custom require function

### ISSUE THREAD

**Issue by kirill-zhirnov** [webpack/webpack#8313]
Hello!
Thank you for the great product!

I am working on a project which uses an own require function, instead of normal require:

```js
const requireAlias = require('requireAlias');
requireAlias('@some/aliased/path');
```

`requireAlias` - customized require function, which resolve pathes inside the project.

How would you recommend to solve it with webpack?

Thanks in advance!

**Comment by evilebottnawi** [comment]
@kirill-zhirnov please use issue template

**Comment by sokra** [comment]
You can write a plugin to learn webpack how to parse it.

**Comment by ooflorent** [comment]
There are 2 ways to achieve what you described:

1. **Simple:** Do not use a custom `require` function but use the [`resolve.alias`](https://webpack.js.org/configuration/resolve/#resolve-alias) configuration option.
1. **Hackish:** Create symlinks inside `node_modules`. This may seem clunky but it is actually how `npm link` works! If you create a symlink from `src/utils` to `node_modules/@acme/utils` you will be able to do `require("@acme/utils/foo")` within webpack.
1. **Hard:** Aliases are not what you are looking for and you need something powerful, then what you need is your own plugin and that won't be easy!

**Comment by veeramarni** [comment]
Regarding `1.`, can we do something like following to overwrite default `require`.
```
const requireNew = require('esm')(module, { cjs: true });
...
              resolve: {
                    alias: {
                        require: requireNew
                    }
...
```
                },
