### ISSUE TITLE
Webpack is putting JSON in main bundle, can't find a way to use outside of bundle.

### ISSUE THREAD

**Issue by GarrettJMU** [webpack/webpack#8314]
**What is the current behavior?**
In our web app we have a few JSON files that are ~10-80k lines each. These are getting included in our main bundle.

An example of our webpack.config.js

```js
module.exports = {
  entry: [
    './src/index.js'
  ],
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: ['babel-loader']
      },
      {
        test: /\.(jpg|png|gif|ico)$/,
        use: {
          loader: "file-loader",
          options: {
            name: "[path][name].[hash].[ext]"
          }
        }
      }
    ]
  },
  resolve: {
    extensions: ['*', '.js', '.jsx']
  },
  output: {
    path: __dirname + '/dist',
    publicPath: '/',
    filename: '[name].[hash].js'
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new HtmlWebpackPlugin({
      hash: false,
      template: 'src/index.html'
    }),
    new DashboardPlugin(),
    new CopyWebpackPlugin([{
      from: 'src/components/Assets/BookingBar.js',
      to: 'assets/BookingBar.js'
    }]),
    new BundleAnalyzerPlugin(),
  ],
  devServer: {
    contentBase: './dist',
    hot: true,
    historyApiFallback: true,
    port: 4000
  }
}
```

**What is the expected behavior?**

There should be a way to exclude .json files from the main bundle. I've tried File-Loader, json-loader, and `const someJson = require("./someJson")`

**Other relevant information:**
webpack version:  4.16.1
Node.js version: 10.12.0
Operating System: Mac OS 10.14 Mojave

**Comment by sokra** [comment]
https://webpack.js.org/guides/code-splitting/#dynamic-imports

**Comment by lambdabaa** [comment]
@GarrettJMU Did you ever figure out how to have the json imports included in the non-main bundle from which they're dynamically imported?
