### ISSUE TITLE
no warning when trying to externalize "require" module with amd as intermediate module format

### ISSUE THREAD

**Issue by dgoldstein0** [webpack/webpack#8316]
# Bug report

**What is the current behavior?**

when `"require"` is listed in the `externals`, it seems to be entirely ignored.  externalizing `"require"` is useful for amd libaries - as importing require should give the bundle access to the AMD loader's require so it can do async loading via the amd loader it's used with.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
// webpack.config.js
var path = require('path');

module.exports = {
  stats: "errors-only",

  entry: ['entry.ts'],
  externals: [
    "require"
  ],

  output: {
    filename: 'my_lib.js',
    libraryTarget: 'amd',
    library: "my_lib",
  },
  module: {
    rules: [
      { test: /\.ts$/, loader: 'ts-loader' }
    ]
  },

  resolve: {
    modules: [
      path.resolve(__dirname, "src"),
    ],
  },
};

// tsconfig.json
{"compilerOptions": {"module": "amd"}}

// src/entry.ts
/// <reference path="./require.d.ts" />
import amdRequire = require('require');

function doStuff(amdRequire) {
  amdRequire(['foo'], function() {});
}

doStuff(amdRequire);

// src/require.d.ts
declare module 'require' {
  const exports: any;
  export = exports;
}
```

**What is the expected behavior?**
the output should be an amd module with `["require"]` as the dependencies.  Instead, it ends up with `[]` as the deps.

**Other relevant information:**

Interestingly, changing module: amd to module: commonjs in the tsconfig solves the problem.  So it appears that having amd as the intermediate format somehow confuses the intent of this code; the compiled AMD of src/entry.ts looks like this:

```
define(["require", "exports", "require"], function (require, exports, amdRequire) {
    "use strict";
    exports.__esModule = true;
    function doStuff(amdRequire) {
        amdRequire(['foo'], function () { });
    }
    doStuff(amdRequire);
});
```
so possibly the repro could be minimized further, but that feels like it would lose some of the motivation

webpack version:  4.23.1
Node.js version: 8.9.3
Operating System: Ubuntu 16.04
Additional tools: ts-loader@5.3.0, typescript@3.1.6, webpack-cli@3.1.2

**Comment by sokra** [comment]
Not sure, but looks like a typescript issue. Could you try what happens when using typescript only.

**Comment by dgoldstein0** [comment]
What do you mean "use typescript only"?

**Comment by sokra** [comment]
Compile the module with `tsc` with the same options and check if the output is correct.

**Comment by dgoldstein0** [comment]
I already shared that above, but here it is again:

```
define(["require", "exports", "require"], function (require, exports, amdRequire) {
    "use strict";
    exports.__esModule = true;
    function doStuff(amdRequire) {
        amdRequire(['foo'], function () { });
    }
    doStuff(amdRequire);
});
```

In general, the `"require"` dependency in AMD is the AMD require function.  I think the problem here is that webpack assumes that all `"require"` deps are supposed to map to it's module loading, instead of an external loader - and doesn't treat the two `"require"`s differently.  When typescript compiles to AMD it always outputs the first two deps as `"require"` and `"exports"`.  Perhaps webpack could treat any additional requires beyond that as potentially external?  just brainstorming.  Perhaps a valid way to parse this is that the AMD format contains insufficient information to communicate the developer intent.

**Comment by sokra** [comment]
> I think the problem here is that webpack assumes that all `"require"` deps are supposed to map to it's module loading, instead of an external loader - and doesn't treat the two `"require"`s differently.

The AMD spec says `"require"` is special and maps to the require function. I think you can't have a module called `require` with AMD.

**Comment by dgoldstein0** [comment]
right, and that's not what I'm trying to do.  Perhaps I should explain my
setup: I am trying to build an amd library with webpack; I want to load my
amd library with an amd loader (say, requirejs), and I want to access
requirejs' require function within my bundle (without using a global
variable) - hence I require("require") in my typescript.  Compiling the
typescript to commonjs works, but compiling to amd makes webpack not
understand my import of "require".  My guess is that webpack assumes it's
supposed to override any `"require"` dependencies in an amd module when for
me that shouldn't be the case.

**Comment by sokra** [comment]
@dgoldstein0 I think that's totally possible.

There is no reason why typescript need to emit AMD modules. You can switch it to `{"compilerOptions": {"module": "esnext"}}`. That's actually better for other reasons too.

`libraryTarget: "amd"` will generate an AMD bundle in the final step.

This should enable you to use `externals: "require"` and access the requirejs function in this way:

`const amdRequire = require("require")`.

---

If this doesn't work for any reason try this:

`externals: { "amd-require": "require" }`

`const amdRequire = require("amd-require")`

This should even work with typescript `module: "amd"`, but I still don't recommend it.

**Comment by dgoldstein0** [comment]
Sorry to be clear I opened this thread not because I wanted to hear workaround suggestions (compiling to commonjs was fine for that - but thanks for the alternative ideas) but rather because I thought webpack should provide some warning or error here.

My rough understanding though is that no one piece of the system seems to have the whole picture, so the only ideas I can think of for such a warning are
- warning about unused externals - which doesn't really unveil the configuration mistake
- warning if trying to externalize require and all inputs are AMD

The latter would have certainly saved me some pain
