### ISSUE TITLE
Wildcard watches

### ISSUE THREAD

**Issue by simonzack** [webpack/webpack#832]
Is there a way to watch wildcards (globs)? This is important in testing, where new files are often added and removed. Browserify's watchify didn't have this either, but I put in a PR there so it works. If webpack has this I can make the switch, as webpack appears to have less runtime overhead.

**Comment by jhnns** [comment]
> This is important in testing, where new files are often added and removed

This does not explain why you need wildcards. 

How do you run your tests? With webpack, every file to test needs to be required somewhere. Alternatively you can use [contexts](http://webpack.github.io/docs/context.html)

**Comment by simonzack** [comment]
@jhnns I run my tests under each of the /test/ directories using mocha & karma. This means I need to use a `test/*` wildcard.

**Comment by hkal** [comment]
I don't think you need webpack to support globbing. If you are using karma checkout [karma-webpack](https://github.com/webpack/karma-webpack), I am fairly certain it'll fill your needs.

**Comment by simonzack** [comment]
@hkal Thanks for the suggestion, but I'm fairly certain that I need glob support for my project, for reasons I have explained above. If any of it is unclear please tell me and I will give more details.

**Comment by simonzack** [comment]
@hkal I'm not sure how karma-webpack does globbing, do you have any idea if adding new test files performs caching and is still performant? If not then there's still a need for webpack to support globbing.

**Comment by sokra** [comment]
You don't need to specify which files are watched by webpack. All files used are automatically watched.

You can use a [context](http://webpack.github.io/docs/context.html) load a bunch of files. The context content is watched by webpack and new files are detected.

**Comment by jhnns** [comment]
> All files used are automatically watched.

All *required files* are automatically watched.

**Comment by simonzack** [comment]
Thanks, I'll give context a try and report back if I find any problems.

**Comment by simonzack** [comment]
Works well enough for me, made the switch! :)
