### ISSUE TITLE
oops didn't do something right

### ISSUE THREAD

**Issue by lbyonder** [webpack/webpack#8325]

**Comment by sokra** [comment]
It looks like you just deleted/ignored our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template.

**Comment by sokra** [comment]
The parser we are using (acorn) is not able to parse this syntax.

**Comment by ljqx** [comment]
Try web version Github. There is no template in desktop version, which confused some before
