### ISSUE TITLE
Optimizing and adding vendors results in "TypeError: Cannot read property 'call' of undefined", on execution

### ISSUE THREAD

**Issue by supasympa** [webpack/webpack#8330]
# Bug report

**What is the current behavior?**

When I optimise my bundle and create a vendors.js file, then execute the previously working `index.js` output bundle results in an error:

    /******/ 		modules[moduleId].call(module.exports, module,
    module.exports, __webpack_require__);
             		                 ^
    
    TypeError: Cannot read property 'call' of undefined

**SO question:**
[https://stackoverflow.com/questions/53142650/webpack-vendor-bundle-not-imported-in-main-output](https://stackoverflow.com/questions/53142650/webpack-vendor-bundle-not-imported-in-main-output)

Files listed below at bottom of issue.

**If the current behavior is a bug, please provide the steps to reproduce.**
**Accompanying Github repo:**
[https://github.com/supasympa/webpack-vendors-issue](https://github.com/supasympa/webpack-vendors-issue)

Using the files detailed at the bottom of this post. 

1. Setup a webpack.config and add an optimisation block:

```
    optimization: {
        splitChunks: {
            cacheGroups: {
                vendors: {
                    priority: -10,
                    test: /[\\/]node_modules[\\/]/,
                    enforce: true
                },
            },
            chunks: 'all',
            minChunks: 1,
            minSize: 0,
            name: true
        }
    },
```

2. run webpack.
3. execute the index.js node ./dist/index

Thanks, in advance for any assistance.

**What is the expected behavior?**
My expectation is that if I try to optimise my bundle (see below) it will output two files:

    1. index.js
    2. vendors~main.index.js
(which it does)

_... and index.js would execute in the same way it does when not producing the vendors file (without raising the error). 

**Other relevant information:**
webpack version:  4.24.0
Node.js version: 8.4.0
Operating System: MacOS 10.14

Files are:

### main.js  

    const  moduleA  = require('./moduleA');

    moduleA.log('log from main.js');

---

## moduleA.js

    const moduleB = require('./moduleB');
    const flatten = require('array-flatten');
    
    module.exports.log = function(msg){
    	moduleB.log('logging from moduleA.js');
    	console.log(`ModuleA logging: ${msg}`);
    	console.log(`flattened: ${flatten([[1,2,3],[4,5],[6,7]])}`)
    };

--- 

## moduleB.js

    const flatten = require('array-flatten');
    
    module.exports.log = function(msg){
    	console.log(`ModuleB logging: ${msg}`);
        console.log(`flattened: ${flatten([[1,2,3],[4,5],[6,7]])}`)
    };

---

## webpack.config.js
 
    const CleanWebpackPlugin = require('clean-webpack-plugin');
        
        module.exports = {
            module: {
                rules: [{
                    include: [path.resolve(__dirname, 'src')],
                    loader: 'babel-loader',
        
                    options: {
                        plugins: ['syntax-dynamic-import'],
        
                        presets: [['env', {
                            'modules': 'commonjs'
                        }]]
                    },
        
                    test: /\.js$/
                }]
            },
        
            entry: './src/main',
            target: 'node',
        
            output: {
                filename: 'index.js',
                path: path.resolve(__dirname, 'dist')
            },
        
            mode: 'development',
        
            optimization: {
                splitChunks: {
                    cacheGroups: {
                        vendors: {
                            priority: -10,
                            test: /[\\/]node_modules[\\/]/,
                            enforce: true
                        },
                    },
                    // concatenateModules: false,
                    chunks: 'all',
                    minChunks: 1,
                    minSize: 0,
                    name: true
                }
            },
        
            plugins: [
                new CleanWebpackPlugin(['dist']),
            ]
        };

**Comment by sokra** [comment]
see #8161
