### ISSUE TITLE
simple client-routeing it works at  http://localhost:8080/edit  ,but didn't work at http://localhost:8080/edit/

### ISSUE THREAD

**Issue by AsfandYar2** [webpack/webpack#8332]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by ooflorent** [comment]
Please fill the issue template.
