### ISSUE TITLE
Dynamic Contexts don't register for Hot Module Replacement

### ISSUE THREAD

**Issue by jauco** [webpack/webpack#834]
The following code won't hot reload (it will log `[HMR] Cannot apply update. Need to do a full reload!`)

```javascript
var context = require.context("../../", true, /\.viewtest$/);
var s = context("../../app/screens/categories/view.jsx.viewtest");

if (module.hot) {
  module.hot.accept(["../../app/screens/categories/view.jsx.viewtest"], function (updatedDependencies) {
    console.log("Module reloaded!");
    s = context("../../app/screens/categories/view.jsx.viewtest");
  });
}
```

but the following code will
```javascript
var context = require.context("../../", true, /\.viewtest$/); //just to make sure the dynamic context itself isn't what disturbs the HMR

var test = require("../../app/screens/categories/view.jsx.viewtest");

if (module.hot) {
  module.hot.accept(["../../app/screens/categories/view.jsx.viewtest"], function (updatedDependencies) {
    console.log("Module reloaded!");
    require("../../app/screens/categories/view.jsx.viewtest");
  });
}
```

which means that I have a working HMR setup.

The code seems to be compiled okay:

```javascript
	var context = __webpack_require__(3);
	var s = context("./app/screens/categories/view.jsx.viewtest");
	
	if (true) {
	  module.hot.accept([5], function (updatedDependencies) {
	    console.log("Module reloaded!");
	    s = context("./app/screens/categories/view.jsx.viewtest");
	  });
	}
```

It looks like a require going through the context module isn't hooked into the hot module code. Based on what I understand of HMR this is because the the context module is marked as the parent of the to-be-reloaded module and since it doesn't accept the reload the module that creates the context must accept it. However, there is no way to say `hot.module.accept("dynamic context", cb);` or something like that.

Is this a bug or a design choice? If it is a bug: do you have tips for fixing it?

**Comment by sokra** [comment]
Only directly required modules can be accepted. A context is like a module so your tree is like this

```
module  -->  context /\.viewtest$/  -->  ./app/screens/categories/view.jsx.viewtest
```

So you need to accept the context module:

``` js
var context = require.context("../../", true, /\.viewtest$/);
if (module.hot) {
  module.hot.accept(context.id, function() {
    console.log("Module reloaded!");
    context = require.context("../../", true, /\.viewtest$/)
  });
}
```

**Comment by jauco** [comment]
Ah, I couldn't think of a way to accept the context module.

Is there a way to determine which of the modules inside the context module were changed?

**Comment by sokra** [comment]
> Is there a way to determine which of the modules inside the context module were changed?

no, but you can rerequire them and compare the exports.

**Comment by ericclemmons** [comment]
I've read this thread & #1790 _repeatedly_ and still can't seem to get this to `console.log`:

```js
const fixtures = require.context("./test", true, /\/fixtures\/.+\.js$/);

export default class Components extends React.Component {
  // Going the nuclear-route trying to accept _everything_, since nothing worked :(
  componentDidMount() {
    module.hot.accept(fixtures, function() {
      console.log("o", arguments);
    });

    module.hot.accept(fixtures.id, function() {
      console.log("id", arguments);
    });

    module.hot.accept(fixtures.keys(), function() {
      console.log("keys", arguments);
    });

    module.hot.accept(fixtures.keys()[0], function() {
      console.log("key", arguments);
    });
  }

  render() {
    return (
      <JSONPreview currentFixture={fixtures[0]} />
    );
  }
}
```

**Comment by ericclemmons** [comment]
For anyone else who comes along, I had to effectively run this:

```js
// This was the key to it all
fixtures.keys().map((path) => fixtures(path));
module.hot.accept(fixtures.id, () => { ... });
```

**Comment by fab1an** [comment]
What does that exactly do? I think I'm struggling with the same problem: 
https://github.com/webpack/webpack/issues/2237

**Comment by jauco** [comment]
for those of you who end up at this issue because you can't get HMR and require.context to work. I've uploaded a minimal working version here: https://github.com/jauco/webpack-hot-module-reload-with-context-example

**Comment by AlexLeung** [comment]
@jauco What would I do if I wanted to export the modules object from hmr_example.js to be made available to another file? When I tried to do this, I got the console.log that a particular file in ./filesToLoad changed, but then I do not see the changes propagated in the application itself.

**Comment by jauco** [comment]
Can you fork the repo and push the code that isn't working?

**Comment by AlexLeung** [comment]
Alright. Check this out: https://github.com/AlexLeung/webpack-hot-module-reload-with-context-example
I have entry.js requiring hmr_example.js, but it seems that entry.js is not aware of the exported modules object from hmr_example.js changing, even though I explicitly tell hmr to watch that resource.

**Comment by jauco** [comment]
I think that a670b83c8918c60dd6a1eaedea5b2d71fab7ee8d makes it more clear what is happening. A way to get the behaviour you seem to want is shown in 448b5f503c0a8922032f8449ef3e19dd33be3d03

**Comment by Cap32** [comment]
I tried `module.hot.accept(context.id, callback)` at webpack@v2.1.0-beta.22, but didn't work. ☹️

**Comment by jauco** [comment]
@Cap32 can fork  jauco/webpack-hot-module-reload-with-context-example and reproduce your failure? It will help me understand what goes wrong.

**Comment by Cap32** [comment]
I just upgraded `"webpack": "^1.12.14"` to `"webpack": "^v2.1.0-beta.22"` from your `webpack-hot-module-reload-with-context-example` repo, and then hot reload no longer works. ☹️

**Comment by aaronjensen** [comment]
@Cap32 it works fine for me. Be sure to upgrade webpack-dev-server as well:

```
    "webpack": "2.1.0-beta.25",
    "webpack-dev-server": "2.1.0-beta.5"
```

**Comment by flik930** [comment]
Hi @jauco, In my case, I want to import a react modules 
`import A from 'a';
ReactDOM.render(<A/>, document.getElementById('hello'))`

then a.js hot reload won't work, b.js and c.js is normal. I have not idea how to solve it.
here is my fork https://github.com/flik930/webpack-hot-module-reload-with-context-example

**Comment by felixmosh** [comment]
I'm trying the same method with `webpack v5`,
I've added an another entry point with this
```js
const context = require.context('./src', true, /\.liquid$/);

const modules = {};

context.keys().forEach(function (key) {
    modules[key] = context(key);
});

if (module.hot) {
    module.hot.accept(context.id, function () {
        debugger;
        console.log('Module reloaded!');
        const newContext = require.context('./src', true, /\.liquid$/);
        newContext.keys().forEach(function (key) {
            console.log(context(key));
        });
    });
}
```
Starting `dev-server` with `hmr` enabled, see all the HMR related logs in the console.
When I'm changing one of the `.liquid` files i do see some logs regarding the changed file, but my hot callback is not called.
![image](https://user-images.githubusercontent.com/9304194/99444676-35519580-2925-11eb-9796-8de10e6a6009.png)

Any pointers?
