### ISSUE TITLE
Can you loop over dynamic imports?

### ISSUE THREAD

**Issue by code-mattclaffey** [webpack/webpack#8340]
So the problem I am having is writing this repeated code 30+ times in my entry files and it makes my entry file pretty big.

Example:

```
const component = document.querySelector('[data-component]');

if (component !== null) {
  import(/* webpackChunkName: "component" */ 'path/to/component').then(componentModule =>{
 componentModule.default.init();
})
    .catch(err => console.error(`Error in: Samples - ${err}`));
}
```

And that fine, my webpack bundle creates `component.bundle.js` but when I tried to implement this for looping I could not get it working. Here is my approach:

```
const components = {
  component1: {
    el: document.querySelector('[data-component]'),
    fileName: 'component',
    path: '/path/to/'
  }
};

function importModule(el, fileName, path) {
  if (el !== null) {
      import(/* webpackChunkName: "[request]" */ '${path}${fileName}').then(componentModule =>{
        componentModule.default.init();
      })
        .catch(err => console.error(`Error in: ${fileName} - ${err}`));
  }
}

Object.keys(components).forEach(key => {
  const { el, fileName, path } = component[key];
  importModule(el, fileName, path);
});

```

The first error I get is the file extension. I have a cshtml file named the same as my component for consistency and it loads that in instead of my js file. This works fine when I am not using a template string. 

The second one webpack does not know what bundle file to generate because it is in a loop. 

is this possible? My bundle would end up being about 3kb if it could be possible therefore making a performance improvement.

**Comment by ooflorent** [comment]
It looks like you just deletedour [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template.
