### ISSUE TITLE
Dynamic Import from external URL will throw `Module not found` error

### ISSUE THREAD

**Issue by LASkuma** [webpack/webpack#8341]
# Bug report

**What is the current behavior?**
Dynamic Import from external URL will throw `Module not found` error

**If the current behavior is a bug, please provide the steps to reproduce.**
```javascript
// webpack.config.js
const path = require('path');

module.exports = {
  mode: 'development',
  entry: './js/main.js',
  output: {
    path: path.resolve(__dirname, 'dist')
  }
}
```
```javascript
// ./js/main.js
import('/js/hello.js').then(module => console.log(module.default));
```
Run `webpack` in console, will throw error 
```
ERROR in ./js/main.js
Module not found: Error: Can't resolve '/js/hello.js' in ...
```

**What is the expected behavior?**
First of all, I've gone through #150 before creating this issue. It's totally understandable that webpack is a **bundler** and it should not take care of loading script from another domain.

However, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Dynamic_Imports) and [Google Developer Website](https://developers.google.com/web/updates/2017/11/dynamic-import), dynamic import should support loading scripts from remote source. At the same time, webpack is preventing this by throwing the `Module not found` error. Therefore, I think it's definitely a bug.

**Other relevant information:**
webpack version:  4.25.1
Node.js version: 8.11.3
Operating System: OSX 10.13.6 (17G65)
Additional tools: None

**Comment by ooflorent** [comment]
You could use `webpackIgnore` comment if you want to use `import` to load an external file:

```js
import(/* webpackIgnore: true */ "/js/hello.js")
```

This _directive comment_ prevents webpack from parsing the `import` expression.

**Comment by evilebottnawi** [comment]
Answer above https://github.com/webpack/webpack/issues/8341#issuecomment-436550381, feel free to open issue if something not work as expected

**Comment by irotaev** [comment]
> You could use `webpackIgnore` comment if you want to use `import` to load an external file:
> 
> ```js
> import(/* webpackIgnore: true */ "/js/hello.js")
> ```
> 
> This _directive comment_ prevents webpack from parsing the `import` expression.

thats greate! thank you

**Comment by devamir** [comment]
@ooflorent Is it possible to import the bundle from external url in webpack for e.g. `import('http://example.com/some-module/some-module.bundle.js').then(module => console.log(module.default));`

**Comment by limeandcoconut** [comment]
This ^^^ would be very helpful

**Comment by sowinski** [comment]
How can I load an external resource from an external url? (In my case google maps api)

`import(/* webpackIgnore: true */ "https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true&libraries=places&key=" + gkey);`
This will not work because of CORS policy.

**Comment by salemhilal** [comment]
hey @sowinski, because that's an external script, you can't import it and access its contents directly. you can get around this by using that attribute as the `src` attribute in a script tag. I don't know if there's a cleaner way, but I've seen [script.js](https://github.com/ded/script.js) used with success for the google maps api specifically.
