### ISSUE TITLE
webpackPreload does not work for the async chunks generated in the initial chunk

### ISSUE THREAD

**Issue by gdorsi** [webpack/webpack#8342]
# Bug report

**What is the current behavior?**

When an async chunk is flagged with `webpackPreload: true` in the initial chunk it is not preloaded.

**If the current behavior is a bug, please provide the steps to reproduce.**

`src/index.js`
```javascript
import('./polyfills.js' /* webpackChunkName: "polyfills" */)
  .then(() => import('./chunk.js' /* webpackPreload: true, webpackChunkName: "chunk" */))
```
Minimal repro: https://github.com/gdorsi/webpack-preolad-issue

**What is the expected behavior?**

On `dist/main.js` evaluation `chunk.js` should be preloaded

**Other relevant information:**
webpack version:  4.25.0
Node.js version: 10.3.0
Operating System: macOS Sierra

**Comment by sokra** [comment]
As preloading need to start before the bundle is loaded, it need to be handled via `<link>` tag in html. It's not possible to solve this in JS (for the initial page load).

Note that preloading will start when the `import` becomes visible so in the code snippet you posted chunk will be preloaded when the app starts and not in parallel to loading polyfills.js

``` js
if(polyfillsNeeded()) {
  import('./polyfills.js' /* webpackChunkName: "polyfills" */)
    .then(() => import('./chunk.js' /* webpackPreload: true, webpackChunkName: "chunk" */))
    .then(chunkReady)
}
```

This will always preload chunk even if `polyfillsNeeded()` is false.

Better write the code this way:

``` js
if(polyfillsNeeded()) {
  import('./polyfillsAndChunk.js' /* webpackChunkName: "polyfills" */)
    .then(chunkReady)
}
```

``` js
// polyfillsAndChunk.js
import "polyfills.js";

export const then = () =>
  import('./chunk.js' /* webpackPreload: true, webpackChunkName: "chunk" */);
```

This will have the following behavior:

* When `polyfillsNeeded()` is true:
  * chunk-polyfills.js (including polyfillsAndChunk.js and polyfills.js) will start downloading
  * chunk-chunk.js will start downloading for preload
  * chunk-chunk.js may finished downloading here, but it won't be evaluated
  * Once chunk-polyfills.js is downloaded it will be evaluated (polyfillsAndChunk.js and polyfills.js run)
  * Once chunk-chunk.js finished downloading or has finished before it will be evaluated (chunk.js runs)
  * chunkReady is executed

**Comment by gdorsi** [comment]
Thank you for the exhaustive response.

Your first solution is still affected by the reported issue because `chunk.js` is actually loaded in the inital chunk.
```javascript
if(polyfillsNeeded()) {
  import('./polyfills.js' /* webpackChunkName: "polyfills" */)
    .then(() => import('./chunk.js' /* webpackPreload: true, webpackChunkName: "chunk" */))
    .then(chunkReady)
}
```

Your second solution works in the reported example but my use case is slightly different:
```javascript
import { loadPolyfills } from 'polyfills.js';

loadPolyfills()
  .then(() => import('./chunk.js' /* webpackPreload: true, webpackChunkName: "chunk" */));
```

In this case I can't implement your solution because the proxy module around `polyfills.js` won't cause the preload of `chunk.js` because it's still loaded in the initial chunk.

So I've found a similiar solution:
```javascript
import { loadPolyfills } from 'polyfills.js';

//This will cause the preload of `chunk.js` and will create an useless new chunk
import('./my-ugly-chunk-preload.js');

loadPolyfills()
  .then(() => import('./chunk.js' /* webpackPreload: true, webpackChunkName: "chunk" */));
```
```javascript
//my-ugly-chunk-preload.js
export default () => import('./chunk.js' /* webpackPreload: true, webpackChunkName: "chunk" */);
```

Even if this solution won't cause a perceivable performance degradation I think that it's still a workaround and would be nice to fix it directly in webpack.

**Comment by gdorsi** [comment]
I've updated the issue to make more clear the expected behavoir.

**Comment by sokra** [comment]
Ok so you want the preloading to start before the entry bundle is loaded. So this answer applies in this case:

> As preloading need to start before the bundle is loaded, it need to be handled via `<link>` tag in html. It's not possible to solve this in JS (for the initial page load).

webpack reports this in it's stats file and you can generate your HTML from this. See `entrypoints.main.children.preload` it's an array of files that should be injected as `<link>` tag.

**Comment by sokra** [comment]
No this would make people thinking it's working correctly, while it's not.
