### ISSUE TITLE
[HMR] and [WDS] set log level in config

### ISSUE THREAD

**Issue by maxmaxmaximus2** [webpack/webpack#8344]
not like this:
```coffeescript
import {setLogLevel} from 'webpack/hot/log'
setLogLevel('none')
```

but like this:

```webpack.config.js```
```
module.exports = {
  HMRLogLevel: 'none'
  WDSLogLevel: 'none'
}
```

since once hmr is written to the console before I can call setLogLevel ('none')
it's annoying.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
