### ISSUE TITLE
Error: Cannot find module 'webpack-core/lib/CheapOriginalSource'

### ISSUE THREAD

**Issue by apaatsio** [webpack/webpack#835]
Forgot to add the file in the commit d80cf1cddd369ffafe046f39a1ef9c7584b3d876?

**Comment by hkal** [comment]
@apaatsio, it's a bit deeper than that. Currently, in order for you to build master, you need https://github.com/mozilla/source-map/commit/98ef9b425acc22a849f12dba61f454c4d9ddb9c6 and https://github.com/webpack/core/commit/adcd6ae51e5d70c6c4c1934b7e41fe42947cb77f. Hopefully that gets you up and running.

**Comment by apaatsio** [comment]
Oh, I see. Thanks!
