### ISSUE TITLE
Better experience for library authors

### ISSUE THREAD

**Issue by benlesh** [webpack/webpack#8352]
## Feature request

I'm trying to build the RxJS 7 experimental branch with Webpack, and I've run into the following issues:

1. I'm required to run Webpack twice to build both a minified and unminified version of the library.
2. The sourcemaps have some crazy `webpack://rxjs/./src/...` URLs in them. I'm not sure what that's about, but I'd like to be able to clean that up to just be relative URLs like `./src/...`
3. The [documentation provided for Authoring libraries](https://webpack.js.org/guides/author-libraries/) is inadequate. It should include stuff about:
   a) Minified and unminified output
   b) Building libraries using loaders for TypeScript or Babel
   c) Any other information useful to library authors (a run down of what to look out for, what metrics to watch, other plugins or tools that might be useful, etc). This is the first page I found from a Google search, so it's a "landing page" or sorts for people like me.

This is just feedback from another OSS author trying to use Webpack for the first time.

1 is a minor inconvenience.

2 is an actual problem I'm not sure how to solve.

**Comment by montogeek** [comment]
Send a PR regarding your finds about Authoring libraries.

**Comment by evilebottnawi** [comment]
Bump

**Comment by evilebottnawi** [comment]
For `1` https://github.com/webpack-contrib/terser-webpack-plugin/issues/87

**Comment by evilebottnawi** [comment]
For `2` https://webpack.js.org/guides/author-libraries/

**Comment by evilebottnawi** [comment]
For `3`

a - we improve minimizer docuemntation
b - same as for any project, no need more information   
c - feel free to open any issue in https://github.com/webpack/webpack.js.org

Thanks for issue
