### ISSUE TITLE
what's the disadvantage of namedChunks?

### ISSUE THREAD

**Issue by Justin-Shen** [webpack/webpack#8354]
In production mode, namedChunks is default to false, so what is the disadvantage of namedChunks, I think it is necessary in production.

**webpack version:  4.25.1**

e.g.

## before
* I have 3 entries: entry-a & entry-b & entry-c

![image](https://user-images.githubusercontent.com/7840139/48177056-d9bf9b00-e34d-11e8-95bb-fc0cfd05a819.png)

## then
* Add a new entry: aa

![image](https://user-images.githubusercontent.com/7840139/48177171-4fc40200-e34e-11e8-8861-0265b2bf5534.png)
 
* as chunk name is **ids** in production, after I added this new entry, entry-a / entry-b / entry-c‘s chunkhash is also changed. because all this entries' chunk name is changed, from 1 to 2, from 2 to 3....

![image](https://user-images.githubusercontent.com/7840139/48177473-ac73ec80-e34f-11e8-87d2-e89c899b3860.png)

![image](https://user-images.githubusercontent.com/7840139/48177492-c7def780-e34f-11e8-923b-d99239435dfd.png)

---------------------
The outcome was undesired !

I think when I add a new entry, all the existed entries' chunkhash will not be changed. Or the cache will be failed, even though their contents have not changed.

To resolve this problem is add ``optimization.namedChunks: true`` in production mode. 

![image](https://user-images.githubusercontent.com/7840139/48178055-c6fb9500-e352-11e8-9917-0e0de62ae0f4.png)

But why it is default to false? Is that any problem?

And it will be removed in webpack 5 ?
![image](https://user-images.githubusercontent.com/7840139/48177826-bdbdf880-e351-11e8-8853-13d52757d29d.png)

**Comment by ooflorent** [comment]
> And it will be removed in webpack 5?

`namedChunks` will be removed because it is redundant with `chunkIds`. Here is a simplified representation of how `chunkIds` works:

```js
optimization.chunkIds = optimization.namedChunks ? "named" : …
```

**Comment by ooflorent** [comment]
> How to set the chunkId in webpack 4 ? Use the hook optimizeChunkIds ?

Unfortunately it is not possible in v4.
This option has landed on `next` branch (v5).

**Comment by smelukov** [comment]
> This option has landed on next branch (v5).

@ooflorent can you get a link to the source, please?
Want to get more info :)

**Comment by ooflorent** [comment]
@smelukov Here are the relevant parts:

- https://github.com/webpack/webpack/blob/next/lib/WebpackOptionsDefaulter.js#L238-L247
- https://github.com/webpack/webpack/tree/next/lib/ids

**Comment by smelukov** [comment]
@ooflorent thank you!
What do you think about https://github.com/webpack/webpack/issues/8355 ?

**Comment by sokra** [comment]
`chunkIds: "named"` is also available in webpack 4.

https://github.com/webpack/webpack/blob/2361995a429794d372d61e3fb628dea3929e0ca4/schemas/WebpackOptions.json#L406-L409

**Comment by evilebottnawi** [comment]
Answer above, feel free to feedback
