### ISSUE TITLE
Hashed chunk ids

### ISSUE THREAD

**Issue by smelukov** [webpack/webpack#8355]
## Feature request

**What is the expected behavior?**

Hashed chunk ids

**What is motivation or use case for adding/changing the behavior?**

After [this PR](https://github.com/webpack/webpack/issues/8268) we have got better long-term caching "out of the box", but we have many chunks and they have numeric ids and these ids changes very often and it still affects long-term caching.

Named chunk ids is too large

**How should this be implemented in your opinion?**

Clone `HashedModuleIdsPlugin` with the same login and adopt it for chunks. It looks like an easy solution...

**Are you willing to work on this yourself?**
yes

**Comment by sokra** [comment]
There is a open card for this in the webpack 5 project.

Better skip the hashed chunk ids and use the deterministic chunk ids algorithm similar to modules.

deterministic chunk ids is based on named chunk ids + the hashing part.

**Comment by smelukov** [comment]
Are you about clone the DeterministicModuleIds and adopt it for chunks?

**Comment by sokra** [comment]
Currently not, but this is planned. But you can go ahead and send a PR.

**Comment by smelukov** [comment]
👌
