### ISSUE TITLE
How to shim a file that ends with .call(this) ?

### ISSUE THREAD

**Issue by dschissler** [webpack/webpack#836]
I can't figure out how to shim this file.

```javascript
(function() {
...
this.QueryEngine = this.queryEngine = queryEngine;
...
}).call(this);

**Comment by cgeorg** [comment]
This looks similar to the problem I am having with rxjs (#863)... did you figure it out?

**Comment by jhnns** [comment]
The `this` value can be overridden by the [imports-loader](https://github.com/webpack/imports-loader). See also https://github.com/webpack/webpack/issues/869#issuecomment-78171916
