### ISSUE TITLE
how to append a new external module to  the entry chunk, help me!!!!

### ISSUE THREAD

**Issue by xujianshe** [webpack/webpack#8363]
## Feature request

**What is the expected behavior?**

**What is motivation or use case for adding/changing the behavior?**

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**

I'm developing a webpack plugin, the function is as follows：
1. custom extract third party modules to  new chunks  from the entry chunk
2. then append  external modules  to the entry chunk
but i failed 
`compiler.plugin("this-compilation", (compilation) => {`
`compilation.plugin(["optimize-chunks", "optimize-extracted-chunks"], (chunks) => {`
`let bundleChunk = chunks[0];`
`extract(bundleChunk);`
`removeCommonModules(bundleChunk);`
`bundleChunk.addModule(new ExternalModule("resisterContent", 'var', "moduleName"));`

I just wanted to append a new externalModule object to the bundleChunk, but it not work.
How can  i do that?
help me ！！！

**Comment by ooflorent** [comment]
It looks like you just ignored our [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template.
