### ISSUE TITLE
Ensure Safari 10 mangling for default optimization

### ISSUE THREAD

**Issue by garrettmaring** [webpack/webpack#8366]
## Feature request

**What is the expected behavior?**
 When using the default optimization with Webpack 4.8.2, the compiled code should be able to run on Safari 10.

However, the default UglifyJs configuration when using the default optimization with Webpack does not allow this to happen.

![screen shot 2018-11-09 at 3 15 22 pm](https://user-images.githubusercontent.com/8270120/48293125-6cd20100-e432-11e8-995d-f4a6419971d6.png)

**What is motivation or use case for adding/changing the behavior?**
Some code will error on load on Safari 10.

**How should this be implemented in your opinion?**
The override that I've specified in my config to prevent this error is: 

```
      optimization: {
        minimizer: [
          new UglifyJsPlugin({
            cache: true,
            parallel: true,
            uglifyOptions: {
              mangle: {
                safari10: true,
              },
            },
          }),
        ],
      },

```

**Are you willing to work on this yourself?**
possibly

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/webpack/webpack/issues/8350, please use `terser` plugin

**Comment by pbwei** [comment]
`safari10` is not a supported option
