### ISSUE TITLE
Not build library.

### ISSUE THREAD

**Issue by TrinhVanDan** [webpack/webpack#8367]
I use webpack with multi entry and i want to build each entry to one library. 
when I see the example: https://github.com/webpack/webpack/tree/master/examples/multi-part-library

I do with my project: 

`entry: {
        "VQ" : "./vq88/index.ts",
        "Ocean" : "./ocean/index.ts",
        "Oracle" : "./oracle/index.ts",
        "Dancing" : "./dancing/index.ts",
        "Predict" : "./predict/index.ts"
    },
    output: {
        path: path.resolve(__dirname, "public/js"),
        publicPath: "/",
        libraryTarget: "umd",
        umdNamedDefine: true,
        //filename: "[name].min.js",
        //library: "[name]"    }`
after build. It not export as library.
But when i comment like this:
`entry: {
        "VQ" : "./vq88/index.ts",
        //"Ocean" : "./ocean/index.ts",
        //"Oracle" : "./oracle/index.ts",
        //"Dancing" : "./dancing/index.ts",
        //"Predict" : "./predict/index.ts"
    },
    output: {
        path: path.resolve(__dirname, "public/js"),
        publicPath: "/",
        libraryTarget: "umd",
        umdNamedDefine: true,
        //filename: "[name].min.js",
        //library: "[name]"    }`
It build a file with export, work. Why?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
