### ISSUE TITLE
json-loader not applied on dependencies

### ISSUE THREAD

**Issue by Radivarig** [webpack/webpack#837]
I added `{ test: /\.json$/, loader: "json-loader" }` to webpack.config.js which I pass as `--config` on my npm run script and installed to project `npm install json-loader --save`, but I get errrors like this when I run it (these come from node-postgres `pg` package). Seems like the loader is not applied to dependencies?

```
WARNING in ./~/dns/~/hbo-dnsd/~/defaultable/defaultable.js
Critical dependencies:
49:13-31 the request of a dependency is an expression
 @ ./~/dns/~/hbo-dnsd/~/defaultable/defaultable.js 49:13-31

WARNING in ./~/dns/~/hbo-dnsd/~/defaultable/defaultable.js
Critical dependencies:
75:6-13 require function is used in a way, in which dependencies cannot be statically extracted
 @ ./~/dns/~/hbo-dnsd/~/defaultable/defaultable.js 75:6-13
...
```

**Comment by hkal** [comment]
It is not. Gotta make it a dependency of your project.

**Comment by Radivarig** [comment]
yeah, did that also, `npm install json-loader --save`

**Comment by sokra** [comment]
Why do you have the idea that this error is related to the json-loader?

**Comment by Radivarig** [comment]
Because the warnings were trying to parse some crazy stuff, I assumed it was the loader because I had no other idea, the only difference from the example was webpack so I came here. I'll issue at `pg`. Thanks

**Comment by Radivarig** [comment]
my problem was exactly this https://github.com/webpack/coffee-loader/issues/9
