### ISSUE TITLE
How to use webpack loader to convert *.{jpe?g|png|gif} as a react component <img src={src} />

### ISSUE THREAD

**Issue by kopax** [webpack/webpack#8370]
I want to load file type `*.{jpe?g|png|gif}` into react components, as does `https://github.com/smooth-code/svgr/tree/master/packages/webpack` for svg files.

This will be used with https://react-styleguidist.js.org/ which can render React component to build HTML documentation for showing assets static without having to write a bunch of code or to know JS. 

I have tried using `image-webpack-loader` 4.5.0 to do the following loader : 

```js
function imgLoader(source) {
  return '<img src="' + source + '" />';
  // return React.createElement('img', { src: source });
};


module.exports = {
  default: imgLoader,
};
```

It is configured with Webpack 4 as follow: 

```js
rules: [
        {
          test: /\.svg$/,
          use: ['@svgr/webpack'],
        },
        {
          test: /\.(gif|png|jpe?g)$/i,
          use: [
            'file-loader',
            {
              loader: 'image-webpack-loader',
              options: {
                disable: true, // webpack@2.x and newer
              },
            },
            {
              loader: path.resolve(__dirname, './loader/loader.js'),
            }
          ],
        }
      ],
```

For some reason, that does not work.

I may have misunderstood how to use loaders. 
It is definitely not converted in React component. I want to avoid having to write `<img src={src} />` when importing `.jpg|png|gif`, I want instead to have the following component `(props = {}) => <img src={src} {...props} />`

any idea ?

**Comment by ooflorent** [comment]
This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons.

**Comment by kopax** [comment]
Dear @ooflorent , I have posted on stackoverflow and unfortunately, they say Webpack can't do that:

https://stackoverflow.com/questions/53249705/how-to-use-webpack-loader-to-convert-jpegpnggif-as-react-component-props/53252392?noredirect=1#comment93405379_53252392

I am not sure if it's true through, could you please tell? 

Regards
