### ISSUE TITLE
Module not found: Error: Can't resolve 'console'

### ISSUE THREAD

**Issue by vladmir123** [webpack/webpack#8371]
ERROR in ./node_modules/html5-history/index.js
Module not found: Error: Can't resolve 'console' in '/blabla/node_modules/html5-history'
 @ ./node_modules/html5-history/index.js 13:16-34
 @ ./src/app/search/main-search.js
 @ ./src/index.js

hello every one i got this issue when development using webpack latest version 4.25.1 
when i'm bundle all js manifest i got this error ! please sometime help me please if u ever use plugin html5-history thankss

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by worc** [comment]
not a great reason to close the issue. this problem has been cropping up lately and every bit of information helps.

**Comment by montogeek** [comment]
Open a new one
