### ISSUE TITLE
ProgressPlugin output artifacts with multi-configs on v4.25.0+

### ISSUE THREAD

**Issue by gpoitch** [webpack/webpack#8373]
# Bug report

**What is the current behavior?**
When using multiple configs with the ProgressPlugin since v4.25.0, an artifact is left after 10% and a new progress starts.

![screen shot 2018-11-12 at 9 55 42 am](https://user-images.githubusercontent.com/411908/48355529-409cc700-e662-11e8-975d-1557201098c5.png)
 

**If the current behavior is a bug, please provide the steps to reproduce.**
Basic webpack config to reproduce:
https://github.com/gpoitch/webpack-progress-fail/blob/master/webpack.config.js

Or repo to fully reproduce: https://github.com/gpoitch/webpack-progress-fail
(It's hard to see without a big app since it's so fast.  I screen recorded the screenshot above.)

**What is the expected behavior?**
A single progress output line, as it worked prior to 4.25.0

**Other relevant information:**
webpack version:  4.25.1
Node.js version: 10.11.0
Operating System: macOS 10.14.1
Additional tools: no

**Comment by NaviMarella** [comment]
Is this issue still exists on latest build ??

**Comment by evilebottnawi** [comment]
bump, need add tests to ensure no problems

**Comment by evilebottnawi** [comment]
игьз

**Comment by evilebottnawi** [comment]
bump
