### ISSUE TITLE
Multiple entries has unique Vue instance with splitChunks

### ISSUE THREAD

**Issue by ToTheEnd0314** [webpack/webpack#8375]
## Feature request

**What is the expected behavior?**
### My demo structure below:
------------------------------ SomeVuePlugin.js ------------------------------
```
import Axios from 'axios';

export default {
    install(Vue) {
       Object.defineProperty(Vue.prototype, '$http', {
            get: () =>Axios
       })
    }
};
```
------------------------------------ base.js ------------------------------------
```
import Vue from "vue";
import SomeVuePlugin from "./SomeVuePlugin";
Vue.use(SomeVuePlugin);
```
------------------------------------ app.js ------------------------------------
```
import Vue from 'vue';
import App from './App.vue';

new Vue({
    el: "dom-selector",
    render: fn => fn(App)
});
```
------------------------------------- webpack.config.js ------------------------------------
```
... ...
entry: {
    base: ['./base.js'],
    app: ['./app.js']
}
... ...
optimization: {
     splitChunks: {
         chunks: "all",
      minSize: 30000,
      minChunks: 1,
      maxAsyncRequests: 5,
      maxInitialRequests: 3,
      name: true,
      cacheGroups: {
         vendors: {
            test: /[\\/]node_modules[\\/]/,
            priority: -10,
            name: 'renderer/js/vendors'
          }
       }
     }
}
... ...
```
### ==>Any friends can teach me how to make my excpted functionality came true,  THANK YOU!!!!!! :

**What is motivation or use case for adding/changing the behavior?**

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
no

**Comment by ToTheEnd0314** [comment]
**Really need nice guys helps**

**Comment by ljqx** [comment]
Try
```js
{
  optimization: { runtimeChunk: 'single' }
}
```
https://webpack.js.org/configuration/optimization/#optimization-runtimechunk

**Comment by ToTheEnd0314** [comment]
@ljqx Thank you, I have solve this with your suggested way, but there build a new file named runtime.js, just one extra file is ok,  sorry too too late response you, but the same thanks to @sokra
