### ISSUE TITLE
Dynamic import with variable + externals config not working

### ISSUE THREAD

**Issue by mrodal** [webpack/webpack#8377]
# Bug report

**What is the current behavior?**
I'm trying to use a dynamic import that uses a variable, and at the same time leave all these modules as external libraries, so I'm doing this:

```import(`library/${module}.js`);```

And my Webpack externals config is:

`externals : /library\/.*\.js/`

And right now, its not leaving those modules as external and its bundling them

If I do ```import(`library/specificModule.js`);``` it works even with the same regex on the externals config.

Looks like the externals config doesn't apply for the import() with variables, because I also tried using a function as the externals config and setting up a brakpoint inside it, and it doesn't hit for those files.

**If the current behavior is a bug, please provide the steps to reproduce.**
Take any library and import its modules with something like ```import(`library/${module}.js`);```
Add the regex to the externals webpack config
Run build
The modules are bundled

**What is the expected behavior?**
I think it should leave all those modules as external modules when using the variable on the import

**Other relevant information:**
webpack version:  4.23.1
Node.js version: 10.11.0
Operating System: Windows 10
Additional tools: -

**Comment by sokra** [comment]
`externals : /library[\\\/].*\.js/`

**Comment by mrodal** [comment]
Thanks for the rapid response @sokra 
That regex doesnt seem to work either 😞. What do you mean "the files have to exist in this directory"? those files are in node modules, so they exist.

**Comment by sokra** [comment]
hmm not sure. Could you create a minimal repro repo?

**Comment by mrodal** [comment]
Sorry I didnt explain: in src/main.js you have 
```
// Bundles all
let iconName = 'Ambulance';
let i = import(`@fortawesome/free-solid-svg-icons/fa${iconName}.js`);

// Doesnt bundle the imported module
// let i = import(`@fortawesome/free-solid-svg-icons/faAmbulance`);
```

Toggling comments on the `let i`s and running `npm run build` you can see the different results.

The externals config is in the vue.config.js file

**Comment by agv123** [comment]
谢谢

**Comment by marcos-abreu** [comment]
I'm having the same problem. My application depends on a configuration file where the a module can be chosen. I only want to load the module chosen on the configuration file... so then I load the configuration file get the module name as a variable and try to load the module:

```
  const module = config.module;
  import(
    /* webpackPreload: true */
    /* webpackChunkName: "my-module" */
    `${module}`)
      .then(({ Module }) => { app.services.set('module', Module); });
```
This **doens't split the code**

But if I hardcode the file to be imported:

```
  import(
    /* webpackPreload: true */
    /* webpackChunkName: "my-module" */
    `my-module`)
      .then(({ Module }) => { app.services.set('module', Module); });
```
Then it works.

**Comment by Muzietto** [comment]
I have an issue that my be linked to what is described here:

https://stackoverflow.com/questions/56362693/webpack-bundled-code-crashes-when-both-import-and-require-instructions-are-p

**Comment by nikonov91-dev** [comment]
here is i solved such problem in bundle with react-redux
https://stackoverflow.com/questions/48268507/react-dynamically-import-components/56456932#56456932

**Comment by mrodal** [comment]
bump

**Comment by ndugger** [comment]
Bump, guys, this seems pretty crucial. Dynamic imports that don't support a dynamic entry point are restrictive.

A use case that I was bouncing around in my head before finding this issue is for micro-frontends.

Having the addresses to your micro frontends stored in constants, and used to dynamically import a component from cross-origin.

```javascript
const BrowsePage = await import(constants.pages.browse);
```

This isn't possible now due to this above issue.
