### ISSUE TITLE
EnvironmentPlugin no work :(

### ISSUE THREAD

**Issue by george-norris-salesforce** [webpack/webpack#8379]
In Browserify / Gulp world, this took all but 5 minutes to setup via envify which 'filled in' the process.env vars in my React code. ...

Looking at this doc
https://webpack.js.org/plugins/environment-plugin/#src/components/Sidebar/Sidebar.jsx

I'm setting up..
```
    plugins: [
        new HtmlWebpackPlugin({
          template: 'views/index.handlebars',
          filename: 'views/index.handlebars'
        }),
        new MiniCssExtractPlugin({
          filename: '[name].css',
        }),
        new webpack.ProvidePlugin({
          $: 'jquery',
          jQuery: 'jquery'
        }),
        new webpack.SourceMapDevToolPlugin({
          filename: '[name].js.map',
        }),
        new webpack.HotModuleReplacementPlugin(),
        new webpack.EnvironmentPlugin(['HEROKU', 'HEROKU_PREFIX', 'LANG', 'NODE_ENV'])
      ]
```
in my webpack config. 

The process.env vars are still not being 'filled in'

https://stackoverflow.com/questions/53310224/webpack-process-env-vars-in-react

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
