### ISSUE TITLE
Lazy Loading / Code Splitting breaks tree shaking

### ISSUE THREAD

**Issue by bluepnume** [webpack/webpack#8381]
# Bug report

**What is the current behavior?**

When a file is imported with `import()`, tree shaking doesn't work as expected.

**If the current behavior is a bug, please provide the steps to reproduce.**

Please see this repo: https://github.com/bluepnume/webpack-lazy-loading

- Source: https://github.com/bluepnume/webpack-lazy-loading/tree/master/src
- Dist: https://github.com/bluepnume/webpack-lazy-loading/tree/master/dist

**What is the expected behavior?**

There are 6 functions defined in this repo:

- `foo`
- `lazyFoo`
- `bar`
- `lazyBar`
- `baz`
- `lazyBaz`

I expect the following:

- `foo`: should appear in main bundle since it's being required and called by `index.js` - 👍 works
- `lazyFoo`: should be tree-shaked, not being used by anyone - 👍 works
- `bar`: should appear in main bundle since it's being required and called by `index.js` - 👍 works
- `lazyBar`: should appear in lazy bundle since it's only being used after `import()` - ❌ doesn't work -- it's appearing in the main bundle
- `baz`: should appear in lazy bundle since it's only being used after `import()` - 👍works
- `lazyBaz`: should appear in lazy bundle since it's only being used after `import()` - 👍works

The main one not working here is `lazyBar`. It's not being directly imported by any other file, so it should never appear in the main bundle.

It should be tree shaked from the main bundle when the tree shaker does not see `import { lazyBar }` anywhere in the codebase.

**Other relevant information:**
webpack version: 4 
Node.js version: 8 
Operating System: osx
Additional tools: n/a

**Comment by NaviMarella** [comment]
As per Webpack scope hoisting, lazyBar() will be moved to main chunk.

**Comment by bluepnume** [comment]
@NaviMarella but isn't that incorrect? Since nothing in the main chunk (provably) needs `lazyBar`, and webpack/uglify can derive that?
