### ISSUE TITLE
ERROR : /node_modules/webpack-cli/bin/config-yargs.js: describe: optionsSchema.definitions.output.properties.path.description

### ISSUE THREAD

**Issue by ligne13** [webpack/webpack#8382]
# Bug report

**What is the current behavior?**
My build is not working anymore. I get the error : 
```
$ npm run start

> webpack-dev-server --config webpack.dev.js --mode development

/node_modules/webpack-cli/bin/config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at Object.<anonymous> (/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:40)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
The build should run succesfully like before.

**Other relevant information:**
webpack version:  4.25.1
Node.js version: 10.13.0
Operating System: MacOS 10.12.6
Additional tools: 
- npm 6.4.1, 
- webpack-cli 2.1.4, 
- webpack-dev-server 3.1.10

**Comment by evilebottnawi** [comment]
@ligne13 please update `webpack-cli` to `3` version (better latest)

**Comment by addejans** [comment]
I had the same issue and this solution worked as well. Thanks!

**Comment by danieltabarest** [comment]
> @ligne13 please update `webpack-cli` to `3` version (better latest)

it works for me!! thanks.
