### ISSUE TITLE
Project converting from RequireJS optimizer but some html uses `require` calls that aren't defined after switching to webpack bundles

### ISSUE THREAD

**Issue by ericnewton76** [webpack/webpack#8383]
I have several webapps that use RequireJS with a config.js for mapping everything. I've successfully gotten the whole project to webpack, but one last remaining issue: several of the HTML pages have script embedded that require those modules:

```
<html>
<head>
  <!--<script src="/assets/vendor/require.js"></script>-->
  <!--<script src="/assets/js/config.js"></script>-->
  <script src="/assets/js/main.js"></script><!-- this is the main bundle created by webpack -->
</head>
<body>
<script type="text/javascript">
require("modules/header", function(header) {
  header.init(); //header 'require' jquery to hook up events to elements in the <header>
})
</script>
</body>
</html>
```

```
Error: `require` is undefined              index.html:9
```

Since I removed the requirejs library, the `require` function is undefined now, so is there a proper `require` definition that maps modules to the webpack bundle, embedded in html?

This seems like a web runtime issue, where my particular project needs that `require` defined as a function that meets AMD specs, but is webpack's require definition.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by ericnewton76** [comment]
I didn't use Bug report or Feature request because it's neither.
