### ISSUE TITLE
Module concatenation causes React component to lose its state

### ISSUE THREAD

**Issue by volkanunsal** [webpack/webpack#8384]
# Bug report

**What is the current behavior?**

When `mode` is set to 'production' and `devtool` is set to a setting that produces source-maps, React produces unexpected results. After long experimentation, I believe the behavior is caused by module concatenation. It affects one particular library, which I have included in the repo below.

**If the current behavior is a bug, please provide the steps to reproduce.**

See my repo here:

https://github.com/volkanunsal/webpack_bug

**What is the expected behavior?**

The React component should only update the input field. But instead the encapsulating fieldset is updated, and key is changed, resulting in the entire component being replaced, and this causes input field to lose its focus. 

This behavior does not happen if the library is loaded as ES5 or when it uses an `eval` devtool or does not generate source maps.

**Other relevant information:**
webpack version:  4.25.1
Node.js version: 8.11.2
Operating System:  Mac
Additional tools: React

**Comment by evilebottnawi** [comment]
@volkanunsal try to disable `optimization.minimize` maybe bug in `uglify`

**Comment by volkanunsal** [comment]
Yes, that worked. But how else will I configure TerserPlugin?

**Comment by evilebottnawi** [comment]
@volkanunsal here example https://github.com/webpack-contrib/terser-webpack-plugin#getting-started, in near release we switch to terser by default

**Comment by volkanunsal** [comment]
Wait that’s what I had already. That doesn’t address my issue. I can also make it work by disabling module concatenation but that’s not fix either.

**Comment by sokra** [comment]
Has been fixed in terser
