### ISSUE TITLE
[Question] I build webpack with module in node_modules still typescript>

### ISSUE THREAD

**Issue by kimthangatm** [webpack/webpack#8387]
I use rushjs.io, it will helps us to to link library in local, 
I write library in ts and not build its to js. In main app, I import ts library to use and webpack cannot build link module.

Eg:

libraries: my-utilities and package.json/main => "src/`index.ts`"
app/: import { functionA } from 'my-utilities';

```
ERROR in /Users/abc/Desktop/project/libraries/my-utilities/src/index.ts
Module build failed (from /Users/abc/Desktop/project/common/temp/node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for /Users/abc/Desktop/project/libraries/my-utilities/src/index.ts.
```

**Comment by evilebottnawi** [comment]
@kimthangatm please create issue in `ts-loader`, not here, thanks!
