### ISSUE TITLE
ignoring node_modules

### ISSUE THREAD

**Issue by jlongster** [webpack/webpack#839]
I'm sure this has been talked about before, but I can't find a clear issue for it. I'm playing around with using webpack with server-side node modules (using `target: node`). I started to like the idea of bundling of everything into a single js file because that would be cool for deployment, but what kills that idea is binary dependencies. They definitely can't be bundled in, though you might know of a hack that lets me alias them or something.

Is there any way to tell the system ignore bundling anything coming from `node_modules`, and just leave it as a `require` statement?

I don't know if the `IgnorePlugin` means that, but if so, trying it results in an error: `plugins: [ new webpack.IgnorePlugin(/.*/, /.*node_modules.*/) ]`

```
% webpack --config webpack.node.config.js

/Users/james/projects/jlongster4/node_modules/webpack/lib/Compilation.js:203
                factory.create(module.context, dependencies[0], function(err, dependantModul
                                     ^
TypeError: Cannot read property 'context' of null
    at Tapable.<anonymous> (/Users/james/projects/jlongster4/node_modules/webpack/lib/Compilation.js:203:24)
```

**Comment by troutowicz** [comment]
Sounds like you may be looking for externals

http://webpack.github.io/docs/configuration.html#externals

**Comment by jlongster** [comment]
I suppose this works:

```js
  externals: [
    function(context, request, cb) {
      if(/^[a-z\-0-9]+$/.test(request)) {
        cb(null, 'commonjs ' + request);
        return;
      }
      cb();
    }
  ]
```

I haven't fully tested it though... I'd be surprised if nobody has tried this before?

**Comment by jlongster** [comment]
That code actually doesn't work. It doesn't take any aliases into account. I only have one alias, but I really don't want to have to duplicate all the aliases in the regexp.

Is there any way to run webpack's resolution algorithm and be able to test on the resulting path?

**Comment by jlongster** [comment]
So here's another solution. We could just manually list the modules in `node_modules` and check them explicity:

```
var node_modules = fs.readdirSync('node_modules').filter(function(x) { return x !== '.bin' });

// ...

  externals: function(context, request, cb) {
    if(node_modules.indexOf(request) !== -1) {
      cb(null, 'commonjs ' + request);
      return;
    }
    cb();
  }
```

I think this actually works pretty well. I'm still confused how anyone uses webpack with node without running into the binary dependency problem

**Comment by troutowicz** [comment]
Have you tried [node-loader](https://github.com/webpack/node-loader)? I've never used it, but it may fix your native dependencies. Ignoring node_modules in its entirety kind of defeats the purpose of webpack, doesn't it?

**Comment by ryanflorence** [comment]
what are you actually trying to do? package up identical code for node and the client? ignore some things for the client, but not for the server?

**Comment by jlongster** [comment]
There's no way I'm going to load my node modules any differently (having to prepend them with `node!` or something)

It doesn't defeat the purpose at all; if I get this working, I can entirely get rid of my gulp setup. I get the exact same transformations for my server code as I do with my frontend code and I get the watcher for free that is based on my dependency tree.

**Comment by jlongster** [comment]
> what are you actually trying to do? package up identical code for node and the client? ignore some things for the client, but not for the server?

It's not even that complicated: I just have some node code. I want to transform it (6to5, etc). I'm tired of using gulp & webpack and having two systems implement the same transformations. webpack is better in that it is based on my dependency graph, so the watcher automatically knows what to watch, and I'd rather just use it.

**Comment by sokra** [comment]
``` js
var node_modules = fs.readdirSync('node_modules').filter(function(x) { return x !== '.bin' });

{
  target: "node",
  externals: node_modules,
  output: {
    libraryTarget: "commonjs2"
  }
}
```

**Comment by troutowicz** [comment]
You wouldn't have to load your node modules any differently. You would add a loader in your webpack config.

```
module.exports = {
  ...
  module: {
    loaders: [
      { test: /\.node$/, loader: 'node-loader' }
    ]
  },
  ...
};

**Comment by jlongster** [comment]
@sokra yep, that's basically what I landed on in https://github.com/webpack/webpack/issues/839#issuecomment-76736465. thanks. How come I have to specify an external as { foo: 'commonjs foo' }? If I just pass 'foo' it turns this:

```
var foo = require('foo');
```

into this:

```
var foo = foo;
```

**Comment by jlongster** [comment]
> You wouldn't have to load your node modules any differently. You would add a loader in your webpack config.

Yes, you do, you have to now suffix all of them with ".node" which is unacceptable.

**Comment by troutowicz** [comment]
I thought that was the purpose of [resolve-extensions](http://webpack.github.io/docs/configuration.html#resolve-extensions)

**Comment by sokra** [comment]
It goes hand in hand with the library type (`output.libraryTarget`).

So when emitting a script module (which is the default) it tries to access the global var `foo`.
When emitting a CommonJs module (`output.libraryTarget = "commonjs2"`) it `require`s the module `require("foo")`
When emitting an AMD module (`output.libraryTarget = "amd"`) it puts the external in the `define` dependencies `define(["foo"], function(...) { ... })`.
And when emitting an UMD module it decides depending on environment.

https://github.com/webpack/webpack/tree/master/examples/externals

**Comment by jlongster** [comment]
@sokra ah interesting, thanks for the explanation. I actually want to generate a script module (my whole backend code) but I want it to use `require("foo")`... Ah well, I can do it with a custom function that manually forces the commonjs style. Still trying to figure out if this is worth it. Seems like the `node` target is supported but nobody really uses it.

**Comment by sokra** [comment]
> You wouldn't have to load your node modules any differently. You would add a loader in your webpack config.
> Yes, you do, you have to now suffix all of them with ".node" which is unacceptable.

> I thought that was the purpose of resolve-extensions

yep: `resolve.extensions: ["", ".js", ".json", ".node"]` is what node.js does.

**Comment by sokra** [comment]
> Seems like the node target is supported but nobody really uses it.

I'll do it for prerendering in https://github.com/webpack/react-starter/blob/master/make-webpack-config.js#L130

**Comment by jlongster** [comment]
> I'll do it for prerendering in https://github.com/webpack/react-starter/blob/master/make-webpack-config.js#L130

That's cool, but it's a pretty simple example that doesn't run into any of the issue that I'm running into. Just try to use it with `redis` and the `hiredis` parsing library and you'll run into the binary dependency problem.

**Comment by troutowicz** [comment]
node target is also useful when handling unit tests in the cli

**Comment by sokra** [comment]
> That's cool, but it's a pretty simple example that doesn't run into any of the issue that I'm running into. Just try to use it with redis and the hiredis parsing library and you'll run into the binary dependency problem.

I would use externals for all node_modules and only bundle your app code. Or is there any reason you don't want to do that?

**Comment by jlongster** [comment]
> I would use externals for all node_modules and only bundle your app code. Or is there any reason you don't want to do that?

That's fine with me! I just didn't know if I was doing it right. It doesn't seem like a well-trodden path and requires a bunch of manual work. Thanks!

**Comment by jlongster** [comment]
The externals node_modules solution seems to work for what I need.

**Comment by bman654** [comment]
@jlongster I tried your method and when my server code did ```import React from 'react'```, `react` was indeed marked "external", but then all of its library files got bundled anyway.

For example, these were all added to my bundle:

```
./~/react/lib/ReactComponentBrowserEnvironment.js
./~/react/lib/ReactDOMIDOperations.js
etc
```

Any idea why that happens?

**Comment by bman654** [comment]
Nevermind.  It was caused because I had this prefetch plugin defined for my server webpack config (taken from react-starter).  I guess I only need this for the client code:

```
new webpack.PrefetchPlugin("react/lib/ReactComponentBrowserEnvironment")
```

**Comment by Dindaleon** [comment]
Hello, I have been struggling with this issue the last couple of days. I am trying to import redis into my project but webpack is not allowing me to.

How can I import redis into my project if I exclude it from webpack?

**Comment by jachenry** [comment]
This thread is extremely helpful but the proposed solution does not account for submodules. I tried using `npm ls --only=production --parseable` to compile a flattened list of module names but couldn't figure out how to convert it into a utility method.

**Comment by kpdecker** [comment]
The solution that I found, which is a slight derivative of what is in the config docs is this:

```
  config.externals = [
    // Every non-relative module is external
    // abc -> require("abc")
    /^[a-z\/\-0-9]+$/i
  ];
```

The key difference between this and the docs is the addition of the `i` flag and the `/` character to the regular expression. It has a few holes, like if you have a `.` legitimately in the path name of the external require, but otherwise works great with things like:

```
import createMemoryHistory from 'history/lib/createMemoryHistory';
```

**Comment by prashaantt** [comment]
FWIW, I was following along @jlongster's [excellent series](http://jlongster.com/Backend-Apps-with-Webpack--Part-I) on using Webpack with node, and ran into similar issues with React and others as above. In my experience, the only reliable way is to include *all* node modules in `externals`. I did it this way: https://gist.github.com/prashaantt/257cf2a8cf4e8ee7f847.

**Comment by gimenete** [comment]
I've also had the same issue and based on the externals example I did this:

```javascript
var node_modules = {}
fs.readdirSync('node_modules').forEach(function(module) {
  node_modules[module] = "require('"+module+"')"
})
```

And then use `externals: node_modules`.

**Comment by jaydenseric** [comment]
This is all way too confusing for such a common use case: I have a universal ES6 Node app and I want webpack to transpile a server bundle without needlessly including node modules.

This is the only thing that has worked:

```js
var Fs = require('fs')
var nodeModules = {}
Fs.readdirSync('node_modules').forEach(function (module) {
  if (module !== '.bin') nodeModules[module] = 'commonjs ' + module
})
```

Then using `externals: nodeModules` in the config.

**Comment by gimenete** [comment]
I agree, this is a pretty common use case. There should be a configuration option to do just this.

**Comment by lingz** [comment]
Note that the above codes all have a bug when including a module with a "/" in its name to indicate a submodule,

e.g:
`import ReactDOMServer from "react-dom/server"`

This still will cause the entire react-dom package and all its subdependencies to be bundled. I was wondering why my hello world was 800kb, and saw that this import line was breaking it.

The following code can be used to handle this edge case and properly let it be imported by commonjs:

```
var Fs = require('fs')
var nodeModules = {}
Fs.readdirSync('node_modules').forEach(function (module) {
  if (module !== '.bin') {
    nodeModules[module] = true
  }
})
var nodeModulesTransform = function(context, request, callback) {
  // search for a '/' indicating a nested module
  var slashIndex = request.indexOf("/");
  var rootModuleName;
  if (slashIndex == -1) {
    rootModuleName = request;
  } else {
    rootModuleName = request.substr(0, slashIndex);
  }

  // Match for root modules that are in our node_modules
  if (nodeModules.hasOwnProperty(rootModuleName)) {
    callback(null, "commonjs " + request);
  } else {
    callback();
  }
}

...
externals: nodeModulesTransform
```

You can see my complete webpack config with this working here:
https://gist.github.com/lingz/14ad8ea44998f5009d5d

**Comment by liady** [comment]
You can also use [webpack-node-externals](https://github.com/liady/webpack-node-externals) to achieve this result:
```
var nodeExternals = require('webpack-node-externals');
...
module.exports = {
    ...
    externals: [nodeExternals()], // in order to ignore all modules in node_modules folder
    ...
};
```

**Comment by bman654** [comment]
@liady brilliant find.

On Thu, Feb 11, 2016 at 5:29 AM, Liad Yosef <notifications@github.com>
wrote:

> You can also use webpack-node-externals
> <https://github.com/liady/webpack-node-externals> to achieve this result:
>
> var nodeExternals = require('webpack-node-externals');
> ...
> module.exports = {
>     ...
>     externals: [nodeExternals()], // in order to ignore all modules in node_modules folder
>     ...
> };
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webpack/webpack/issues/839#issuecomment-182816233>.
>



-- 
Brandon Wallace
Palladium Consulting
http://www.palladiumconsulting.com/

**Comment by Morhaus** [comment]
I just published [webpack-externals-plugin](https://github.com/Morhaus/webpack-externals-plugin). It has the advantage of supporting external modules that were installed *after* the initialization of the webpack compiler.

```js
  plugins: [
    new ExternalsPlugin({
      type: 'commonjs',
      include: __dirname + '/node_modules',
    }),
  ],
```

**Comment by danwad** [comment]
@Morhaus: webpack-externals-plugin looks like a very neat solution. Going to give it a go. Thanks :)

**Comment by cchamberlain** [comment]
Bit different take but this is my preference. Instead of reading the file system, this just reads the package.json's dependency names and includes them all as externals.

The benefit to this approach is that I only exclude node_modules when compiling webpack libraries, and those dependencies should all be in the package.json for the library being webpack'ed.

(I transpile my config with Babel)

```js
import packageJSON from './package.json'
const { dependencies = {}, devDependencies = {}, peerDependencies = {}, optionalDependencies = {} } = packageJSON
const dependencyNames = Array.from(new Set( [ ...Object.keys(dependencies)
                                            , ...Object.keys(devDependencies)
                                            , ...Object.keys(peerDependencies)
                                            , ...Object.keys(optionalDependencies)
                                            ] ))
const externals = dependencyNames.reduce((externals, name) => ({ ...externals, [name]: true }), {})
export default { externals 
               , /** rest of config here */
               }
```


I have a few issues with the two popular approaches:

**regex to externalize non-relative paths**

* Almost good but frail when using webpack aliases to common areas in your app (they will look as though they are a node_module when really they should be bundled). 

**Reading node_modules approach**

* Scoped modules go in a subdirectory within node_modules, if you try and import '@myscoped/package' the external is only good for '@myscoped' and your scoped modules will be bundled when they shouldn't.
* If you haven't `npm prune`d prior to running webpack and your dependencies have changed there will be extra externals pulled in than should be.
* There should be no scenario when you are importing a node_modules package within your library that is not called out in your package.json dependencies, but there will likely be many sibling libraries that get pulled in by NPM that you do not need to externalize.
* npm 2 / 3 handle dependencies differently and there will be varying levels of recursion. Seems prone to breakage as library gets larger / more dependencies.

If I am off on anything here please set me straight.

**Comment by liady** [comment]
@cchamberlain Great suggestion. I updated [webpack-node-externals](https://www.npmjs.com/package/webpack-node-externals) to accept `modulesFromFile` flag, that will read the modules from the `package.json` file instead of the `node_modules` dir:
```js
// webpack.config.js
var nodeExternals = require('webpack-node-externals');
...
module.exports = {
    ...
    externals: [nodeExternals({
        modulesFromFile: true
    })], // in order to ignore all modules in package.json when bundling
    ...
};
```

**Comment by hinell** [comment]
Here is my way to prevent node_modules from being bundled: 
```js
{ externals: [function (context,req,cb) {
        !/^\./.test(req)
          ? cb(null,req)
          : cb(null,false);
  }] 
}
```
Output bundle requests then look like this (require isn't declared in result bundle):
```js
/***/ (function(module, exports) {

module.exports = require("path");

/***/ }),
```

**Comment by LikeDege** [comment]
Can the filtered external module be output to a node_modules dir?

**Comment by risabhkumar-cc** [comment]
Still getting 
`ERROR in ./node_modules/realm/lib/browser/index.js
Module not found: Error: Can't resolve 'react-native' in '/Volumes/Others/Project/realm-exporter/node_modules/realm/lib/browser'`.
Any updates?
