### ISSUE TITLE
Inconsistent mainFields resolution using Webpack 4 in a monorepo

### ISSUE THREAD

**Issue by TxHawks** [webpack/webpack#8391]
# Bug report

**What is the current behavior?**
In a monorepo that is wired using Lerna and Yarn workspaces, one of the packages is a Next.js app, which depends on several packages internal to the monorepo.

All of the consumable packages in the monorepo are written in modern javascript, and have both a `main` field and a `module` field in their `package.json`s. [As per convention](https://github.com/rollup/rollup/wiki/pkg.module), the `main` field points to transpiled code, that uses CJS, while the `main` field points to code that is transplied except for for the conversion of ES modules to CJS.

As mentioned before, the package consuming the these packages is a Next.js app, which is build using Webpack 4. Strangely enough, one of the consumed packages is resolved to the `main` field, while all the rest are properly resolved to the `module` field.

I have even tried to manually set `resolve.mainField` to `[ 'module', 'main', ]`, which had no effect.

I couldn't find anything in the documentation that could explain this behavior.

**If the current behavior is a bug, please provide the steps to reproduce.**
Not sure, because I couldn't figure out what causes webpack to resolve one package to `main` and another to `module`

**What is the expected behavior?**
All packages should be resolved to `module` consistently if it is defined in the package's `package.json`

**Other relevant information:**
webpack version:  4.20.2
Node.js version: 10.8.0
Operating System: osx
Additional tools: next.js

**Comment by sokra** [comment]
> Not sure, because I couldn't figure out what causes webpack to resolve one package to `main` and another to `module`

One reason I can think about is `.mjs`. `.mjs` files always resolve to only `main`.

---

It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by TxHawks** [comment]
Thanks for the prompt reply 

There are no `.mjs` files in the package itself, and both `main` and `module` point to `index.js`

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by tripodsan** [comment]
I think octokit's request with is-plain-object have the same issue:

https://github.com/jonschlinkert/is-plain-object/blob/master/package.json defines:
```
  "main": "index.cjs.js",
  "module": "index.js",
```

and octokit just uses:
https://github.com/octokit/request.js/blob/2df74980ae6b9ee410bbbeb17b973637daf14882/lib/request.js#L3

the bundle creates:

```
/***/ "./node_modules/@octokit/rest/node_modules/is-plain-object/index.js":
/*!**************************************************************************!*\
  !*** ./node_modules/@octokit/rest/node_modules/is-plain-object/index.js ***!
  \**************************************************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "default", function() { return isPlainObject; });
/* harmony import */ var isobject__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! isobject */ "./node_modules/@octokit/rest/node_modules/isobject/index.js");
/*!
 * is-plain-object <https://github.com/jonschlinkert/is-plain-object>
 *
 * Copyright (c) 2014-2017, Jon Schlinkert.
 * Released under the MIT License.
 */



function isObjectObject(o) {
  return Object(isobject__WEBPACK_IMPORTED_MODULE_0__["default"])(o) === true
    && Object.prototype.toString.call(o) === '[object Object]';
}

function isPlainObject(o) {
  var ctor,prot;

  if (isObjectObject(o) === false) return false;

  // If has modified constructor
  ctor = o.constructor;
  if (typeof ctor !== 'function') return false;

  // If has modified prototype
  prot = ctor.prototype;
  if (isObjectObject(prot) === false) return false;

  // If constructor does not have an Object-specific method
  if (prot.hasOwnProperty('isPrototypeOf') === false) {
    return false;
  }

  // Most likely a plain Object
  return true;
};
```

**Comment by tripodsan** [comment]
btw, I fixed the problem above ^^^^, by changing the resolve main field order:

```
resolve: {
        mainFields: ['main', 'module']
}
```
