### ISSUE TITLE
Allow customization of the bootstrap code

### ISSUE THREAD

**Issue by gforcada** [webpack/webpack#8394]
## Feature request
We are facing a problem were we are mixing bundles generated by webpack 2 and webpack 4. I know the solution in tongue (move all to webpack 4) but it is not possible right now.

We were able to mix them up until now because the webpack 4 generated bundles were splitting the bundles in smaller ones and loading them dynamically.

As soon as we enable bundle splitting on the webpack 4 bundles the bootstrapping code was failing on either of the two generated bundles (webpack 2 and webpack 4).

The problem is on this line:
```var jsonpArray = window["webpackJsonp"] = window["webpackJsonp"] || [];```

Our feature request would be to allow configuring this variable ``window["webpackJsonp"] `` so that it could be versioned per webpack version, i.e. ``window["webpack4Jsonp"]`` and thus avoiding conflicts between the two bootstrapping code.

**What is the expected behavior?**
That one can define the variable were jsonpArray is stored on the window object to avoid conflicts within other bundles loading on webpack but also potentially with other packages out in the will that could choose that name as well.

**What is motivation or use case for adding/changing the behavior?**
So that we can mix bundles that are dynamic loading other bundles that are coming from webpack 2 and webpack 4.

**How should this be implemented in your opinion?**
Providing a major version specific variable per webpack version (i.e. ``webpack4Jsonp``) and/or being a setting that can be overriden on webpack configuration itself.

**Are you willing to work on this yourself?**
*yes* provided some guidance :sweat_smile: we have been using webpack for a long time (thanks!!) but never ever had to dive into its code.

**Comment by sokra** [comment]
https://webpack.js.org/configuration/output/#output-jsonpfunction

---

> Providing a major version specific variable per webpack version (i.e. `webpack4Jsonp`) and/or being a setting that can be overriden on webpack configuration itself.

While this would help for your specific problem it's not useful in general.

Mixing two webpack bundles on the same page with the same `jsonpFunction` is always wrong, even if the webpack versions match.

**Comment by gforcada** [comment]
Cool :tada: that works for us already. :+1:
