### ISSUE TITLE
webpack4 minify javascript bug,  but webpack 3 has not this bug

### ISSUE THREAD

**Issue by martinko2009** [webpack/webpack#8399]
# Bug report

**What is the current behavior?**
After minify javascript, I deploy these code files , and access these code by browser, it throws
the error that xx is not function.
If I don't minify javascript, and just build code by mode development, everything is ok.

**If the current behavior is a bug, please provide the steps to reproduce.**

_**webpack.config.js**_
```

process.env.NODE_ENV = "production";
var path = require("path");
var webpack = require("webpack");
var MiniCssExtractPlugin = require("mini-css-extract-plugin");
var HtmlWebpackPlugin = require('html-webpack-plugin');
var HtmlReplaceWebpackPlugin = require('html-replace-webpack-plugin');
var SkeletonWebpackPlugin = require("vue-skeleton-webpack-plugin");
var UglifyJsPlugin = require('uglifyjs-webpack-plugin');
var VueLoaderPlugin = require('vue-loader/lib/plugin');
var glob = require('glob');
var entries = getEntry('./src/**/*.js');
var chunks = Object.keys(entries);
module.exports = {
	entry:entries,
	output:{
		path:path.resolve(__dirname, rootApp),
		filename:"js/[name].[hash].js",
		chunkFilename:"js/[name].[hash].js",
		publicPath:"/"+rootApp+"/"
	},
	module:{
		rules: [
		  {
			  test: /\.vue$/, 
		      loader: 'vue-loader',
			  options: {
				  loaders:{
					  js: [{
						  loader: 'babel-loader',
						  options: {
							  compact: false,
							  cacheDirectory: true,
							  presets: ['@babel/preset-env'],
							  plugins: ['@babel/plugin-transform-runtime','@babel/plugin-proposal-object-rest-spread']
						  }
					  }],
				      css: [MiniCssExtractPlugin.loader, 'css-loader'], 
					  scss: [MiniCssExtractPlugin.loader, 'css-loader', 'sass-loader'],
					  extractCSS:true
				  }
			  }
		  },
		  {
			test: /\.js$/,
			exclude: /node_modules/,
			loader: 'babel-loader',
			options: {
				compact: false,
				cacheDirectory: true,
				presets: ['@babel/preset-env'],
        		plugins: ['@babel/plugin-transform-runtime','@babel/plugin-proposal-object-rest-spread']
			}
		  },
		  {
			  test: /\.css$/,
			  use: [MiniCssExtractPlugin.loader, 'css-loader']
		  },
		  {
			  test: /\.scss$/, 
			  use: [MiniCssExtractPlugin.loader, 'css-loader', 'sass-loader']
		  },
		  {
			  test: /\.less$/, 
			  use: [MiniCssExtractPlugin.loader, 'css-loader', 'less-loader']
		  },		
		  {
			test: /\.(png|jpg|gif|svg)$/,
			loader: 'url-loader',
			options: {
				limit: 15000,
				name: 'imgs/[md5:hash].[ext]'
			}
		  },
		  //{ test: /\.(eot|woff|woff2|svg|ttf)$/, loader: "file-loader" },
		  { test: /\.(eot|woff|woff2|svg|ttf)([\?]?.*)$/, loader: "file-loader" },
		]
	},
	resolve:{
		modules:[process.cwd() + '/src', process.cwd() + '/node_modules', process.cwd() + '/'+rootPublic],
		extensions: ['.js'],
	},
	plugins:[
			new VueLoaderPlugin(),
            new webpack.ProvidePlugin({
                "$": 'jquery',
                "jQuery": 'jquery',
				"window.$": 'jquery',
                "window.jQuery": 'jquery',
				"Vue": "vue/dist/vue.min.js",
				"configuration": "configuration",
				"jcutils": "jcutils",
				"piwikIdGoal": "piwikIdGoal",
				"moment":"moment/moment.js"

            }),
			new webpack.DllReferencePlugin({
				context: __dirname,
				manifest: require('./'+rootPublic+'/dll/manifest/manifest_lib.json'),
			}),
			new MiniCssExtractPlugin({
		  　　	filename: 'css/[name].css'
	   　　 }),
    ],
    optimization: {
        splitChunks: {
            cacheGroups: {
                commons: {
                    name: "vendors",
                    chunks: "initial",
                    minChunks: 30
                }
            }
        },
		minimizer:[
			new UglifyJsPlugin({
				sourceMap:true,
				uglifyOptions: {
					warnings: false,
					mangle: {
						reserved: ['$super', '$', 'exports', 'require']
					},
					output: {comments: false},
				}
			})
		]
    },
	devtool: 'cheap-module-source-map'
};


var prod = process.env.NODE_ENV === 'production';
if (prod) {
//delete module.exports.devtool;
  module.exports.devtool = 'cheap-module-source-map';
  module.exports.plugins = module.exports.plugins.concat([
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify("production")
      }
    }),
    new webpack.optimize.OccurrenceOrderPlugin()
  ]);
}

var pages = getEntry("./src/**/*.html");
for (var pathname in pages) {
  // 配置生成的html文件，定义路径等
  var conf = {
    filename: './web/' + pathname + '.html', // html文件输出路径
    template: "html-withimg-loader?exclude=/"+rootPublic+"/!"+pages[pathname], // 模板路径
    inject: true,              // js插入位置
    minify: {
      removeComments: true,
      collapseWhitespace: false
    }
  };
  if (pathname in module.exports.entry) {
    conf.chunks = ['vendors', pathname];
    conf.hash = false;
  }
  // 需要生成几个html文件，就配置几个HtmlWebpackPlugin对象
  module.exports.plugins.push(new HtmlWebpackPlugin(conf));
}

function getEntry(globPath) {
  var entries = {},
    basename, tmp, pathname;

  glob.sync(globPath).forEach(function (entry) {
    basename = path.basename(entry, path.extname(entry));
	var tmpWholeArray = entry.split('/');
	if(tmpWholeArray.length >= 2 && path.extname(entry) == '.js'){
		var libFolder = tmpWholeArray.splice(-2,1);
		if(libFolder != "lib"){
			 var tmp = entry.split('/');
			 var tmp1 = entry.split('/').splice(2, tmp.length-3);
			 pathname = tmp1.join("/") + '/' + basename; // 正确输出js和html的路径
			 entries[pathname] = entry;
		}
	}else{
		var tmp = entry.split('/');
		var tmp1 = entry.split('/').splice(2, tmp.length-3);
		pathname = tmp1.join("/") + '/' + basename; // 正确输出js和html的路径
		entries[pathname] = entry;
	}
  });
  return entries;
}
```
**_aa.js_**
```
export function demo1() {
   return this.bb();
}
export function demo2(){
  return "bb";
}
```
After minify these code, I check the code, they became like below:
```
function f(){
      return this.bb();
}
function d(){
  return "bb";
}
```
so it throws the error that bb is not function in webpack 4.
but when I use webpack3 to minify these code, they became like below:
```
function f(){
      return this.bb();
}
function d(){
  return "bb";
}
t.bb = d;
```
so it is ok in webpack3

**What is the expected behavior?**
I expected it works in webpack4 like webpack 3

**Other relevant information:**
webpack version:  4.25.1
Node.js version: 6.4.1
Operating System:  windows 7
Additional tools:

**Comment by ljqx** [comment]
Try [Webpack 4.26.0](https://github.com/webpack/webpack/releases/tag/v4.26.0), it

> Switch from uglify-es to terser as default minimizer

**Comment by mdimovska** [comment]
I am getting a similar issue, when building the app in production mode: 'TypeError: Cannot read property 'sth' of undefined'. I assume it is related to the minification process (unfortunately I cannot provide such detailed examples as @martinko2009 did above).

This issue occurs in v4.16.5 (maybe in some previous versions as well, but I had this version installed at the point when I noticed the issue).
I switched to v4.26.0 to see if the problem was resolved with the introduction of the new minimizer, but it was not.

Building the code in development mode works ok.
Building the code in production mode with { optimization: { minimize: false }} also works ok.

**Comment by ljqx** [comment]
Ah, I've checked @martinko2009 's code.

Actually it's code issue:
`aa.js` is a module, which means all code inside is [in strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Strict_mode_for_modules), so the `this` inside `demo1` [should be `undefined`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this#Simple_call) instead of global object.

In the output of Webpack 3, the `t` should be some global object. Which means it wrongly consider code in `aa.js` as non-strict, which is a bug of Webpack 3.

@mdimovska , if you can give a reproducible repo I think we can know why. If it's a terser issue, we can solve it there.

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by sokra** [comment]
> `aa.js` is a module, which means all code inside is [in strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Strict_mode_for_modules), so the `this` inside `demo1` [should be `undefined`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this#Simple_call) instead of global object.

This only applies to top-level this. `this` in functions (not arrow-functions) is not affected. The `this` depends on the way you call the function.

Sadly in @martinko2009's code it's not visible how `demo1` is called, so it's impossible to say what's the correct value of `this` here.

**Comment by mdimovska** [comment]
@ljqx thanks for your input. I will check the code and try to detect the issue. I will open another github issue if I manage to narrow it down to a reproducible example and if it still occurs (we have a pretty big code base..).

**Comment by ljqx** [comment]
@sokra , as I know, for top-level `this`, there is [another rule](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this#Global_Context)

> In the global execution context (outside of any function), this refers to the global object whether in strict mode or not.

And yeah, the code is not clear how `demo1` is called. Being simply called as `demo1()` is just my guess.

And my another guess is in the original code, `demo1` is defined as 
```diff
export function demo1() {
-  return this.bb();
+  return this.demo2();
}
```

**Comment by martinko2009** [comment]
> @sokra , as I know, for top-level `this`, there is [another rule](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this#Global_Context)
> 
> > In the global execution context (outside of any function), this refers to the global object whether in strict mode or not.
> 
> And yeah, the code is not clear how `demo1` is called. Being simply called as `demo1()` is just my guess.
> 
> And my another guess is in the original code, `demo1` is defined as
> 
> ```diff
> export function demo1() {
> -  return this.bb();
> +  return this.demo2();
> }
> ```

sorry, the code is not clear.I regive the demo code like below:
**_aa.js_**
```
export function demo1() {
   return this.demo2();
}
export function demo2(){
  return "bb";
}
```
**_index.js_**
```
import * as aa from 'aa.js';
aa.demo1();
```
I have another problem.Even if I do not use 'this' object, like below:
```
export function demo1() {
   return demo2();
}
export function demo2(){
  return "bb";
}
```
after minified the code, it will be like below:
```
function f(){
      return demo2();
}
function d(){
  return "bb";
}
```
demo2 is still not a function.I just set terser-webpack-plugin's keep_fnames property to true, like below, and resolve the problem:
```
optimization: {
        splitChunks: {
            cacheGroups: {
                commons: {
                    name: "vendors",
                    chunks: "initial",
                    minChunks: 30
                }
            }
        },
		minimizer:[
			new TerserWebpackPlugin({
				sourceMap:true,
				terserOptions: {
					warnings: false,
					mangle: {
						reserved: ['$super', '$', 'exports', 'require']
					},
					output: {comments: false},
					keep_fnames:true
				}
			})
		]
    },
```
but I don't think this is a good idea. because I set keep_fnames to true, the file can not be smaller after it minified the code.

**Comment by ooflorent** [comment]
You cannot reliably use a _top level `this`_ in an Harmony module. What is your use-case?
In short, if you use `import` or `export`, do not use _top level `this`_.

**Comment by martinko2009** [comment]
@ooflorent, I have no idea about  if you use import or export, do not use top level this.
can you tell me the details?
