### ISSUE TITLE
sub node_modules directory won't resolve

### ISSUE THREAD

**Issue by deanshub** [webpack/webpack#840]
my config is:
```
resolve: {
        modulesDirectories: [
            'server/node_modules',
            'client/src/bower_components',
            'server/features'
        ],
        extensions: ['', '.js']
    }
```

and i have an npm module called 'ngraph' inside server/node_modules
the 'ngraph' module gets resolved as should, yet
inside ngraph's index.js file there is a require for 'ngraph.events' module, like so:
```
require('ngraph.events');
```
which resides in server/node_modules/ngraph/node_modules/
yet webpack doesn't search sub node_modules directories (and i don't want to specify every sub directory), please give me some guidness oh @sokra  wise one

**Comment by sokra** [comment]
http://webpack.github.io/docs/configuration.html#resolve-modulesdirectories

**Comment by deanshub** [comment]
(shouldn't modulesDirectories recursive down instead of up?)
i'm using it :cry: , and i don't think it should look like this:

```
resolve: {
        modulesDirectories: [
            'server/node_modules',
            'server/node_modules/ngraph.graph/node_modules',
            'server/node_modules/ngraph.forcelayout/node_modules',
            'server/node_modules/ngraph.physics.simulator/node_modules',
            'server/node_modules/ngraph.svg/node_modules',
            'server/node_modules/ngraph.svg/node_modules/simplesvg/node_modules',
            'server/node_modules/ngraph.three/node_modules',
            'server/node_modules/ngraph.three/node_modules/ngraph.forcelayout3d/node_modules',
            'client/src/bower_components',
            'server/features',
            __dirname
        ],
```

**Comment by sokra** [comment]
Read the fat NOTE in the documentation. You should only use `modulesDirectories` for tree structures.  Your directories should better be in the `resolve.root` config. `resolve.modulesDirectories` should be left untouched, so it's the default value of `[..., "node_modules"]`, which is required to find `node_modules`...

**Comment by deanshub** [comment]
:smile: Thank you, thank you very much!
you're awesome @sokra !
