### ISSUE TITLE
es6 imports with less file not working

### ISSUE THREAD

**Issue by JerryChin** [webpack/webpack#8402]
# Bug report

**What is the current behavior?**
try 
```
import styles from './index.less'
```

styles is an empty object.

index.less as follows:

    .main {
       width: 200px;
    }

webpack.config as follows:

           // 处理 CSS 和 Less 文件
            {
                test: /\.(css|less)$/,
                use: [
                    {
                        // 将返回的 css 内容插入到页面(<head><style>...</style></header>
                        // https://github.com/webpack-contrib/style-loader
                        // https://stackoverflow.com/questions/34039826/webpack-style-loader-vs-css-loader
                        loader: "style-loader"
                    },
                    {
                        // 读取并返回 css 内容 （并处理里面的@import and url() 语句）
                        // https://github.com/webpack-contrib/css-loader
                        // https://stackoverflow.com/questions/34039826/webpack-style-loader-vs-css-loader
                        loader: "css-loader",
                    },
                    {
                        // 将 Less 转成 CSS ，支持使用 ~ 来引用 node_modules 内的资源
                        loader: "less-loader",
                        options: {
                            javascriptEnabled: true
                        }
                    }
                ]
            },

**What is the expected behavior?**

I can reference style defined in index.less

for example:
```
styles.main == 'main'
```

**Other relevant information:**
webpack version:  4.26.0
Node.js version: 8.12.0
Operating System: Win64
Additional tools: WebStorm

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by sokra** [comment]
Seems like you want to enable CSS modules for the css-loader

```js
{
  loader: "css-loader",
  options: { modules: true }
}
```

**Comment by JerryChin** [comment]
@sokra  Holy Jesus! That's EXACTLY what I need! Thank you!
