### ISSUE TITLE
request a new placeholder for webpackChunkName 

### ISSUE THREAD

**Issue by luoguibin** [webpack/webpack#8403]
## Feature request

**What is the expected behavior?**
import(/* webpackChunkName: "[name]" */ `@/views/${vueName}.vue`)
The placeholder `[name]` will be the filename of `vueName`

**What is motivation or use case for adding/changing the behavior?**
In a situation a tablet, I store the js files in the sd, and record the hash codes into a db-table used for testing updates. When I change one of vue file or add a new vue file, so I can find  the target js file to update or load quickly.

**Comment by sokra** [comment]
There is `[request]` for this purpose.

**Comment by luoguibin** [comment]
@sokra [request] has a file extensions.

**Comment by wqjiao** [comment]
/* webpackChunkName:  'name' */ ,How to use variables 'name'

**Comment by wqjiao** [comment]
/ * webpackChunkName："name" * /,How to use variables for "name"?

**Comment by luoguibin** [comment]
Maybe it's a way change `import(/* webpackChunkName: "[request]" */ @/views/${vueName}.vue)` to `import(/* webpackChunkName: "[request]" */ @/views/${vueName})`
