### ISSUE TITLE
Module concatenation not working

### ISSUE THREAD

**Issue by jacobwindsor** [webpack/webpack#8404]
# Bug report

*This has been moved from [this babel issue](https://github.com/babel/babel/issues/8960)*

**What is the current behavior?**
webpack's module concatenation does not behave correctly. Everything builds okay but results in a runtime error:

![image](https://user-images.githubusercontent.com/5579270/47856953-58618900-dde0-11e8-8d56-426af67aabf5.png)

Disabling `optimization.concatenateModules` in the webpack production config fixes this.  `optimization.concatenateModules` is disabled by default in the development mode so this issue only arises in production.

As expected, setting `modules` to `commonjs` in the babel config also fixes the issue. 

Both of the above fixes just force module concatenation to be disabled.

**If the current behavior is a bug, please provide the steps to reproduce.**
Just run a build in production mode. I cannot share any project related code unfortunately except the webpack configs which are available at [this gist](https://gist.github.com/jacobwindsor/2b0d03ee90e376482f9140c594848c0a). 

**What is the expected behavior?**
Should be able to remove `"modules": "commonjs"` from .babelrc and expect that module concatenation will be enabled. Removing that config will make babel-loader automatically set it to false to disable module transformation. Webpack can then take care of modules and use module concatenation and tree shaking.

**Other relevant information:**
webpack version:  4.16.1
Node.js version: 8.9.4
Operating System: Windows 10
Additional tools: babel@7, babel-loader

**Comment by sokra** [comment]
Seems like a module is missing in the bundle. Hard to investigate without a repro case.

**Comment by jacobwindsor** [comment]
@sokra I'll try and boil down to a simple repro case. May take a while

**Comment by SleepWalker** [comment]
I've faced the similar issue. After debugging I've found, that this was due to recursive dependencies, e.g. when you have two modules, the both are exported from index.js and on of them is dependent from another:

index.js
```js
export { default as Foo } from './Foo';
export { default as Bar } from './Bar';
```

Bar.js
```js
import { Foo } from './';

// ...
```

This issue happens only in production build due to optimizations, that are hoisting some of the module requests to the top and due to recursive dependencies during code execution one of dependencies is cached as `undefined` in that hoisting optimization code.

To fix such error you need to request file directly to break recursion, e.g.:

Bar.js
```js
import { Foo } from './Foo';

// ...
```

**Comment by GiancarlosIO** [comment]
Same here :disappointed:

**Comment by jacobwindsor** [comment]
So turns out it was totally a human error. We have a fairly specific cacheGroups logic for pulling out common modules into two files. 

```js
cacheGroups: {
    ...
    , 'everywhere.top': {
        priority: 2
        , test: mod => utils.isInChunk('everywhere.top')(mod) && !utils.isVendorModule(mod) && !utils.isInChunk('polyfills')(mod) && mod.getNumberOfChunks() > 1
        , name: 'commons~everywhere.top'
    }
    , 'everywhere.bottom': {
        priority: 1
        , test: mod => utils.isInChunk('everywhere.bottom')(mod) && !utils.isVendorModule(mod) && !utils.isInChunk('everywhere.top')(mod) && mod.getNumberOfChunks() > 1
        , name: 'commons~everywhere.bottom'
    }
}

The test pulls out modules that are in the given chunk, and not a vendor module. Previously we didn't have the check for whether the module was in any other chunk (`mod.getNumberOfChunks() > 1`). This would make the `everywhere.bottom/top` chunk empty (apart from the webpack code).

I'm not entirely sure why this caused the issue I described. I suppose it was because webpack optimized and removed the empty chunk? If anyone can shed some light on this it would be appreciated
