### ISSUE TITLE
Entry point file wont resolve. Throws error cannot resolve 'file' or 'directory'

### ISSUE THREAD

**Issue by nikhildev** [webpack/webpack#841]
Hi,

I gave a shot at webpack today using gulp. Here is my task

```javascript
gulpWebpack = require('gulp-webpack');
gulp = require('gulp'),
gulp.task('webpack', function() {
  return gulp.src('src/components/app.js')
    .pipe(gulpWebpack({}, webpack))
    .pipe(gulp.dest('./public/assets/js/'));
});
```
The app.js exists. But it throws the following error
```
ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' /Users/nikhildev/Code/greatphotos/web/src/components/app.js in /Users/nikhildev/Code/greatphotos/web
```

I tried the CLI version and get the same error. Any idea what I might be doing wrong?

Thanks

**Comment by sokra** [comment]
`webpack --display-error-details`

**Comment by nikhildev** [comment]
@sokra Please excuse my stupidity. Commenting out unnecessary stuff in package.json is what was breaking it.
