### ISSUE TITLE
Cheap-module-source-map not generated with correct source file.

### ISSUE THREAD

**Issue by icewind7030** [webpack/webpack#8413]
# Bug report

I create a project with `Vue-Cli 3` and set webpack config `devtool` as `cheap-module-source-map`.

**What is the current behavior?**

The source map file generated just contain source content `webpack:///webpack/bootstrap` and content from `node_modules`, not with my actually source file.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here a repository you can reproduce with:
```
https://github.com/icewind7030/sentry-vue-debug.git
```

I commit the generated webpack config file named `config.js` with `vue inspect --mode production > config.js`.

And I also commit the webpack build files in `dist` folder. 

Please check the config file and the source map files.

**What is the expected behavior?**

`cheap-module-source-map` works like the webpack document says:
> original source (lines only)

Show the source code error with line location.

**Other relevant information:**
webpack version:  4.26.0
Node.js version: 10.13.0
Operating System: macOS 10.14.1
Additional tools: VS Code 1.29.1

**Comment by alianrock** [comment]
got the same bug

**Comment by evilebottnawi** [comment]
bump, need check

**Comment by evilebottnawi** [comment]
bump
