### ISSUE TITLE
splitChunks.chunk() method does not seem to iterate over all chunks

### ISSUE THREAD

**Issue by jakub-g** [webpack/webpack#8414]
# Bug report

**What is the current behavior?**

Our webpack build produces 15 chunks (3 initial `manifest`, `main`,  `vendor` + the rest are dynamic chunks via `import()` or `require.ensure()`).

I wanted to experiment with split chunks (https://webpack.js.org/plugins/split-chunks-plugin/#splitchunks-chunks) -- as explained `splitChunks.chunk` can be a method returning a `Boolean` to decide whether a given chunk should be optimized further (additional code splitting) or not.

I put in place the following config:

```
    optimization: {
      splitChunks: {
        chunks() {
            console.dir(chunk.name)
            return false
        },
```

**What is the expected behavior?**

I would expect to see all the 15 chunks names, one time each -- each callback would decide whether to optimize a given chunk or not

**What is the actual behavior?**

I don't see certain chunks getting callback at all, and I see some other chunks listed twice.
There's no clear pattern about which kinds of chunks are missing and which are duplicated.

I.e. expected output:

```
chunk1
chunk2
chunk3
...
chunk15
```

Actual:

```
chunk1
chunk2
chunk3
chunk4
chunk3
chunk4
chunk8
chunk9
chunk10
chunk9
chunk10
```

**Other relevant information:**
webpack version:  4.26.0
Node.js version: 8.11.3
Operating System: Win 10

Does this look like a bug? Did someone encounter this too? Is it work digging further to find a minimum repro?
Maybe I misunderstand how this is supposed to work? (the docs are scarce so I'm not fully sure)

**Comment by sokra** [comment]
There are some other filter criteria too. i. e. `minChunks` and `test` are applied before `chunks` is applied.
