### ISSUE TITLE
Huge performance drop after installing a package

### ISSUE THREAD

**Issue by jantimon** [webpack/webpack#8421]
**What is the current behavior?**

I came a cross a very strange behaviour which I can't explain.  
Webpack decreased a lot in speed after installing some npm packages although the source code is quite small.

```
import React from 'react';
const demo = <span />

console.log(demo);
```

and the following compile time (initial):
```
Version: webpack 4.26.1
Time: 5869ms
```

and the following compile time (incremental):

```
Version: webpack 4.26.1
Time: 3309ms
```

just for reference webpack 4.2.0 (almost the same amount of time):

initial

```
Version: webpack 4.2.0
Time: 4185ms
```

incremental
```
Version: webpack 4.2.0
Time: 3124ms
```

**Reproduction**

Here is a small repo to reproduce the bug: 

**[Reproduction Example - webpack-speed.zip](https://github.com/webpack/webpack/files/2620051/webpack-speed.zip)**

```
npm i
npm start
```

The ts-loader config used by the ts-config-webpack-plugin can be seen here (it is basically the same as the ts-loader example config):
https://raw.githubusercontent.com/namics/webpack-config-plugins/master/packages/ts-config-webpack-plugin/config/development.config.js

```
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const TsConfigPlugin = require('ts-config-webpack-plugin');
const SpeedMeasurePlugin = require("speed-measure-webpack-plugin");
const smp = new SpeedMeasurePlugin({outputFormat: 'humanVerbose'});

module.exports = smp.wrap({
  context: __dirname,
  mode: "development",
  devtool: "cheap-module-eval-source-map",
  plugins: [
    new TsConfigPlugin(),
    new HtmlWebpackPlugin(),
    new webpack.HotModuleReplacementPlugin(),    
  ],
  devServer: {
    hot: true
  },
});
```

**The strange part**

remove `@material-ui/core` and it will be fast again! 

**Other relevant information:**
webpack version:  4.26.1
Node.js version: v10.13.0
Operating System: 
Additional tools: 

```
   "html-webpack-plugin": "3.2.0",
    "speed-measure-webpack-plugin": "1.2.3",
    "ts-config-webpack-plugin": "0.4.4",
    "typescript": "3.1.6",
    "webpack": "4.26.1",
    "webpack-cli": "3.1.2",
    "webpack-dev-server": "3.1.10"
```

**Comment by DanielRuf** [comment]
Can you run some profiling step? Like `node_modules/.bin/webpack --mode=development --progress --profile`

https://bitspeicher.blog/profiling-mit-node-js-und-webpack/

For those who want to reproduce, `npm ci` creates the dependency tree form the lockfile.

**Comment by jantimon** [comment]
Hey Daniel :)

sorry for not updating this.  
sokra helped me to trace down the issue to the  fork-ts-checker-webpack-plugin which is checking types for all files inside the node_modules folder.

Maybe @johnnyreilly knows if thats a bug or intended.

![image](https://user-images.githubusercontent.com/4113649/49218324-6818c100-f3d0-11e8-8a22-b24aaf6cd963.png)

@johnnyreilly also proposed to use the `async` flag for development which will be part of the next ts-config-webpack-plugin:

https://github.com/namics/webpack-config-plugins/commit/49ef8c6342831f1945ca357a299931382059ea30#diff-230cebccad5a741b51ed658aa6a6e908R67

**Comment by johnnyreilly** [comment]
I'm afraid I'm snowed right now and so I'm unlikely to be able to help out much with this. One thing that occurs: using `"skipLibCheck": true` in your `tsconfig.json` may help

See https://www.typescriptlang.org/docs/handbook/compiler-options.html
