### ISSUE TITLE
Build failed in Linux because of case sensitive path name

### ISSUE THREAD

**Issue by aryaroudi** [webpack/webpack#8424]
# Bug report

**What is the current behavior?**

While bundling a project which is written in requirejs/AMD I see that it is failing on Prod environment because on MacOS it is able to resolve the uppercase paths but it is not possible in Linux so something like this is failing:
```
define([
    'Controllers/index',
    'Directives/index',
    'Services/index',
```

So I had to introduce **alias** for this in my config. Something like:
`
 Services:                       'services',
ConfigurationBlocks:            'configuration-blocks',
`
I can't go back and change more than 2300 modules! so changing all those files is not an option!

**If the current behavior is a bug, please provide the steps to reproduce.**

So if you have a module in current path ./controller/index and you are addressing it like that try to use: Controller/index and it will work on macOSX but fail on Linux.

**What is the expected behavior?**

provide a plugin or natively resolve these paths while building

**Other relevant information:**
webpack version:  4.25.1
Node.js version: 8.12.0
Operating System: macOSX
Additional tools:

**Comment by aryaroudi** [comment]
Ok here is the answer: 
I figure this out with **NormalModuleReplacementPlugin**

```
new webpack.NormalModuleReplacementPlugin(   
            /([A-Z])/, function(resource) {    
                // whatever you want to do (reqEx, toLowerCase(), etc) for example:   
                resource.request = resource.request.toLowerCase()
}  
```

I hope it helps someone!

**Comment by ikobe** [comment]
try this plugin: https://github.com/Urthen/case-sensitive-paths-webpack-plugin#readme

**Comment by aryaroudi** [comment]
> try this plugin: https://github.com/Urthen/case-sensitive-paths-webpack-plugin#readme

Thanks @ikobe I already tried this plugin and it didn't help. If i don't be wrong this plugin only warns you about this kind of error and not resolves the paths automatically while bundling.

**Comment by sokra** [comment]
Better don't try to workaround the wrong paths with build tooling. Fix the paths in the source files. They are wrong there, fix it there.

**Comment by aryaroudi** [comment]
Hi @sokra Thanks for the advice. I guess it would be ideal to do that but as I said there are more than 2500 files and it will take much time to fix all of them and I just have 1 week to move a big project from grunt to Webpack!

**Comment by Zver64** [comment]
I am new in this issue. Could anyone explain why is paths resolving not case sensitive in macos?
