### ISSUE TITLE
Compilation error while processing magic comment(-s)

### ISSUE THREAD

**Issue by whitecolor** [webpack/webpack#8428]
**What is the current behavior?**

I'm not sure if it is a bug or I probably doing something wrong but didn't find a like issue:
`iscroll` is a package in `node_modules`, importing is with dynamic `import` and trying to set name

```ts
import('iscroll' as any /* webpackChunkName: iscroll */)
```
I get warning in the console:

> Compilation error while processing magic comment(-s): /* webpackChunkName: iscroll*/: iscroll is not defined.

A bundle is produced with name `0.js` (not "iscroll")

if I remove `/* webpackChunkName: iscroll */` warning is gone, the same unnamed bundle produced.

**What is the expected behavior?**

No warning chunk is named as in comment "iscroll".

Webpack 4.26.1

**Comment by evilebottnawi** [comment]
@whitecolor please use issue template

**Comment by sokra** [comment]
`/* webpackChunkName: "iscroll" */`

**Comment by whitecolor** [comment]
hm, ok sorry, I definitely could not see it, once I wrote it =)
