### ISSUE TITLE
Module not found: Cannot resolve module "qs" in

### ISSUE THREAD

**Issue by guilherme90** [webpack/webpack#843]
Hello. Does anyone know how to solve this problem?
![react-router](https://cloud.githubusercontent.com/assets/2879939/6449813/5afec62c-c102-11e4-86dc-3117ce492909.png)

My webpack config: https://gist.github.com/guilherme90/f322a8653ca8e83fee55
Thanks.

**Comment by loganfsmyth** [comment]
Your usage of `modulesDirectories` is incorrect. You have specified one exact path, so react-router cannot resolve its own dependencies. I think you can probably remove that config option entirely.

**Comment by guilherme90** [comment]
Friend, thank you for your help. Now it's all right. Thank you so much! God be with you, hug!
