### ISSUE TITLE
npm  has deprecated  flatmap-stream` and `event-stream@3.3.6` 

### ISSUE THREAD

**Issue by pruthvi204** [webpack/webpack#8430]
**What is the current behavior?**
flatmap-stream and event-stream has been deprecated yesterday itself. while install npm getting error  E404
npm ERR! 404 Not Found: flatmap-stream@0.1.1
how to we install npm now 

**Other relevant information:**
webpack version:  4.20.2
Operating System: ubuntu
Additional tools:

**Comment by evilebottnawi** [comment]
@pruthvi204 please fill issue template

**Comment by evilebottnawi** [comment]
Also i can't find `flatmap-stream` and `event-stream` in webpack deps

**Comment by pruthvi204** [comment]
sorry this for webpack.cli
