### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by danwellman** [webpack/webpack#8431]
# Bug report?

**What is the current behavior?**
I have just upgraded a fully working Angular 5 app to Angular 6. The v5 version of the app had an ejected Webpack config, and I know this is generally considered unsupported, but we are using Java/Spring to run the app locally, and it is a multi-tenanted app, so we could not use an 'out of the box' solution unfortunately. 

In Angular 6, an ejected Webpack config is not supported, so I am using a custom builder (https://www.npmjs.com/package/@angular-builders/custom-webpack) to inject the Webpack config. The config is working, the app is being built, bundles and chunks are being emitted, and the app is running.

I have added my config to a gist here: https://gist.github.com/danwellman/954c74df23f2eb5ab635a5c6d08720d9

The problem I have is when using the `--watch` command with local builds. When I use the watch command, the app is built initially, then I can save .ts/.scss files and the app will automatically rebuild. This works maybe 4 or 5 times, and then I see this error in the terminal and the watch stops:

```
<--- Last few GCs --->

[35879:0x103000000]   521328 ms: Mark-sweep 1323.0 (1431.1) -> 1323.0 (1431.1) MB, 1197.9 / 0.0 ms  allocation failure GC in old space requested
[35879:0x103000000]   522634 ms: Mark-sweep 1323.0 (1431.1) -> 1323.0 (1424.1) MB, 1306.4 / 0.0 ms  last resort GC in old space requested
[35879:0x103000000]   523857 ms: Mark-sweep 1323.0 (1424.1) -> 1323.0 (1424.1) MB, 1222.8 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x431c8725879 <JSObject>
    1: from [buffer.js:~175] [pc=0xceeefb1981](this=0x431f6535c51 <JSFunction Buffer (sfi = 0x431c877e159)>,value=0x431308aa7d9 <Very long string[310412]>,encodingOrOffset=0x431158022d1 <undefined>,length=0x431158022d1 <undefined>)
    2: arguments adaptor frame: 1->3
    3: zlibBufferSync(aka zlibBufferSync) [zlib.js:137] [bytecode=0x431221d2b69 offset=19](this=0x431158022d1 <undefined>,engine=0...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::String::WriteUtf8(char*, int, int*, int) const [/usr/local/bin/node]
 7: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [/usr/local/bin/node]
 8: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [/usr/local/bin/node]
 9: node::Buffer::(anonymous namespace)::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
10: 0xceece54447
```
I've tried asking this question in the node, angular-cli, and Webpack Gitter rooms, and no one has been able to provide any help. 

I have tried running using the `--max_old_space_size=12000` flag and it has not helped.

I'm sorry I'm not able to provide a minimal solution - the app is huge and my company will not let me post source code publicly. 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  4.24.0
Node.js version: 8.12.0
Operating System: Mac OSX 10.14.1 Mojave
Additional tools: Angular 6, Custom builder

**Comment by evilebottnawi** [comment]
@danwellman please create minimum reproducible test repo

**Comment by evilebottnawi** [comment]
Also based on you stacktrace problem in `zlib`, something try to `gzip` big file and memory is not enough

**Comment by danwellman** [comment]
I fear it will not be easy to create a test repo that mimics the current environment well enough to reproduce the issue, but I will try. Thanks for the tip.

**Comment by dielangsea** [comment]
i had this problem too, when i set 4GB, it will out of memory, but when i set 10GB is ok.

**Comment by marcusjwhelan** [comment]
Same issue. but with 

```
0: ExitFrame [pc: 0x26066ef5be1d]
Security context: 0x2abf71f1e6e9 <JSObject>
    1: set [0x2abf71f11ea9](this=0x2f6c0e10ba41 <Map map = 0x158acc284359>,0x0803d4f1bf71 <String[114]: 6715,6667,6685,6466,6755,6676,6632,6641,6654,6558,6536,6734,6694,6549,6585,6625,6507,6485,6464,6785,6776,6612,6794>,0x0803d4f1bf99 <TypeObject map = 0x2556cee60089>)
    2: getIntersectionType(aka getIntersectionType) [0x16ee23d066f9] [/home/marcus/work/Cl...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0x8dc510 node::Abort() [/home/marcus/.nvm/versions/node/v10.15.3/bin/node]
 2: 0x8dc55c  [/home/marcus/.nvm/versions/node/v10.15.3/bin/node]

```

No matter how much memory I add it still crashes

**Comment by evilebottnawi** [comment]
@marcus Please provide full error stack or create minimum reproducible  test repo

**Comment by marcusjwhelan** [comment]
@evilebottnawi I have made a smaller repo. It looks like everything works fine but as I add more ts files are hooked up to the project with more interfaces the project then runs out of memory. My main error comes from /fork-ts-checker-webpack-plugin
Every time I get a memoryLimit error
Also cannot edit the plugin.

**Comment by evilebottnawi** [comment]
You can post issue in `fork-ts-checker-webpack-plugin` with reproducible test repo, maybe memory leak

**Comment by marcusjwhelan** [comment]
@evilebottnawi Their first response will be to edit the options of ForkTsCheckerWebpackPlugin. However much I try I can't seem to edit the plugin when using electron-webpack. It seems to always load ForkTsCheckerWebpackPlugin default values.

**Comment by evilebottnawi** [comment]
Maybe you can post issue in `electron-webpack` too
