### ISSUE TITLE
runtimeChunk=single & mode=production can cause unneeded output change

### ISSUE THREAD

**Issue by weaverryan** [webpack/webpack#8433]
# Bug report

**What is the current behavior?**

When using `optimization.runtimeChunk: 'single'` and `mode: 'production'`, adding a new entry may cause the output of existing entry files to change unnecessarily.

**If the current behavior is a bug, please provide the steps to reproduce.**

Reproducer: https://github.com/weaverryan/reproducer-webpack-runtime-unrelated-changes

In that reproducer, the `entry2` entry does NOT change between the 2 builds, but its output *does* change:

```diff
diff -u -r dist1/entry2.js dist2/entry2.js
--- dist1/entry2.js	2018-11-28 12:24:40.000000000 -0500
+++ dist2/entry2.js	2018-11-28 12:24:40.000000000 -0500
@@ -1 +1 @@
-(window.webpackJsonp=window.webpackJsonp||[]).push([[2],[,function(n,o){console.log("entry2")}],[[1,0]]]);
\ No newline at end of file
+(window.webpackJsonp=window.webpackJsonp||[]).push([[3],{2:function(n,o){console.log("entry2")}},[[2,0]]]);
\ No newline at end of file
```

**What is the expected behavior?**

The output for the unmodified entries would be the same between builds (or there should be some option that can be set in production to allow this). The part that's changing refers to a chunk id, and I believe it comes from here: https://github.com/webpack/webpack/blob/8e841feda3ef32c64df1a175d0d9f71e47cfbe8e/lib/web/JsonpChunkTemplatePlugin.js#L42-L44

**Other relevant information:**
webpack version:  4.26.1
Node.js version: 11.0.0
Operating System: OSX
Additional tools: None

**Comment by sokra** [comment]
Seem like module ids changed in your example. Try to use a long term caching compatible `optimization.moduleIds` option if you want to avoid this (at cost of bigger bundles).

**Comment by evilebottnawi** [comment]
Answer https://github.com/webpack/webpack/issues/8433#issuecomment-443418773
