### ISSUE TITLE
Unable to override optimization.namedModules and optimization.namedChunks defaults

### ISSUE THREAD

**Issue by chrisckc** [webpack/webpack#8437]
# Bug report

The docs currently state:

**optimization.namedModules**
> When optimization.namedModules is not set in webpack config, webpack will enable it by default for mode development and disable for mode production.

**optimization.namedChunks**
> Tells webpack to use readable chunk identifiers for better debugging. This option is enabled by default for mode development and disabled for mode production if no option is provided in webpack config.

**What is the current behavior?**

When specifying these in the webpack config like this:

```
optimization: {
    namedChunks: false,
    namedModules: false,
    moduleIds: 'hashed'
}
```

and then building in development mode, it seems that namedChunks and/or namedModules is enabled, overriding the config, which is not what the docs state and is undesirable.

My observation is based on the name of the generated chunks:

in production mode i get a chunk named like this:

`vendors~53127b40.da236ba505352285db0c.chunk.js`

In development mode i get a chunk named like this:

`vendors~._node_modules_scheduler_cjs_scheduler.development.js~30696716.21f236c249b3280ea481.chunk.js`

This is despite that fact that namedChunks and namedModules are both set to false. I expected that the name would remain like the first example when building in development mode.

Those above names appear to be composed of:
`{chunkname}~{someidentifier}.{chunkhash}.chunk.js` because i am using `output.chunkFilename: '[name].[chunkhash].chunk.js'` in the config.

It seems that {someidentifier} is either {modulename~somehash} when in dev mode or just {somehash}  when in production mode?

Note: This behaviour is only visible when using optimization.splitChunks.maxSize such that chunks are split down into smaller chunks. When not using maxSize, {someidentifier} is not generated, the name is simply: `{chunkname}.{chunkhash}.chunk.js`

I noticed that the 'moduleIds' setting has no effect on the filenames, it must not be something that is used when generating filenames?

**If the current behavior is a bug, please provide the steps to reproduce.**

Clone the following repo:
https://github.com/chrisckc/minimal-react-webpack-babel-setup

Build the project using both:

```
npm run build
```
and
```
npm run build:dev
```

Notice my observations,  namedChunks and namedModules setting is ignored and overriden by the build mode, this is also case when setting them to true.

**What is the expected behavior?**

namedChunks and namedModules specified in the config should take precedence over the build mode as stated in the docs.

**Other relevant information:**
webpack version:  v4.26.1

**Comment by sokra** [comment]
> optimization: { namedChunks: false, namedModules: false, moduleIds: 'hashed' }

These options only affect the module and chunk ids.

If you want to include the chunk id in filenames instead of the chunk name, use `[id]` instead of `[name]` in `output.[chunk]filename`.

splitChunks automatically generates **chunk names** for chunks split via `maxSize`. The difference you see here is controlled by the [optimization.splitChunks.hidePathInfo](https://webpack.js.org/plugins/split-chunks-plugin/#splitchunks-maxsize) option.

**Comment by chrisckc** [comment]
Thanks, it was not immediately clear from the docs what effect these options would have in terms of outputted filenames, but it makes sense now. I was not seeing any difference because i was not using [id] in output.chunkFilename

Adding [id] to output.chunkFilename and changing the value of namedChunks does affect the filename.  Maybe 'namedChunkIds' would be a better name.

The effect of namedModules can only be seen if i use `stats: 'verbose'. I can then see a difference in the build output when the value of namedModules is changed.

The optimization.splitChunks.hidePathInfo defaults are not covered in the docs, but it seems that it is true in production mode and false in dev mode. I prefer to have this always set to false because i am using [name] in output.chunkFilename and adding the path info to the filename does not add any value.

> > optimization: { namedChunks: false, namedModules: false, moduleIds: 'hashed' }
> These options only affect the module and chunk ids.

Expanding on the above i have a few questions:

- What is the relationship between 'moduleIds' and 'namedModules' ?
Does `namedModules: true` have the same effect as `moduleIds : 'named'` ? Which takes precedence?

- Why isn't there an equivalent option for chunks such as `chunkIds: 'named'` ?

- What is required for long term caching to work properly? is `moduleIds : 'hashed'` and `runtimeChunk: true` sufficient with namedChunks and namedModules set to false?

I understand that previous webpack versions required the use of HashedModuleIdsPlugin and HashedChunkIdsPlugin for long term caching to work well. Was the HashedChunkIdsPlugin only relevant if [id] was used in output.chunkFilename?

**Comment by sokra** [comment]
> What is the relationship between 'moduleIds' and 'namedModules' ?
Does namedModules: true have the same effect as moduleIds : 'named' ? Which takes precedence?

namedModules is deprecated, moduleIds take precedence.

> Why isn't there an equivalent option for chunks such as chunkIds: 'named' ?

I think there is such an option. At least in webpack 5.

> What is required for long term caching to work properly? is moduleIds : 'hashed' and runtimeChunk: true sufficient with namedChunks and namedModules set to false?

hashed is currently best for long term caching. This will be replaced by "deterministic" in webpack 5. Runtime chunk is optional but helps avoiding app chunk changes.

> I understand that previous webpack versions required the use of HashedModuleIdsPlugin and HashedChunkIdsPlugin for long term caching to work well. Was the HashedChunkIdsPlugin only relevant if [id] was used in output.chunkFilename?

IDs are always used inside of the files even if you don't use them in filenames.

**Comment by evilebottnawi** [comment]
Fixed in webpack@5, feel free to test it and leave feedback on this https://github.com/webpack/webpack/issues/9802
