### ISSUE TITLE
Suggested update to webpack GitHub description

### ISSUE THREAD

**Issue by RohanTalip** [webpack/webpack#8439]
Since the description for a GitHub project can't be affected by a pull request, I'm making a suggestion for a few minor grammatical changes here:
> A bundler for javascript and friends. Packs many modules into a few bundled assets. Code Splitting allows **for loading** parts **of** the application on demand. Through "loaders", modules can be CommonJs, AMD, ES6 modules, CSS, Images, JSON, Coffeescript, LESS, ... and your custom stuff.

Specifically:
- replace "allows _to load_" with "allows **for loading**"
- replace "parts _for_ the application" with "parts **of** the application"
- move the comma outside/after the quotes around "loaders", since it is not actually speech.

**Comment by evilebottnawi** [comment]
@RohanTalip send a PR

**Comment by sokra** [comment]
Updated

**Comment by RohanTalip** [comment]
@sokra, thanks :-)

@evilebottnawi, I would have but as I alluded to in my initial comment, I don't think the GitHub description is under version control; it has to be edited via an input field on GitHub, if you have the necessary permissions.  If you know otherwise, please let me know.

**Comment by RohanTalip** [comment]
@sokra, one more suggestion: replace the all-lowercase "javascript" with "JavaScript".
