### ISSUE TITLE
__dirname replacement is not absolute

### ISSUE THREAD

**Issue by jlongster** [webpack/webpack#844]
If you specify `node: { __dirname: true }` in your config, webpack will replace `__dirname` instances with the path of the module. However, if will only be a relative path. For example if a module is in `foo/bar.js`, `__dirname` will only be `foo` inside `bar.js`. Why not make it an absolute path like `/Users/james/foo/bar.js`, which is what `__dirname` usually is?

**Comment by sokra** [comment]
You usually don't want to publish absolute filenames in your bundle. It's relative to `context`.

**Comment by jlongster** [comment]
Yeah, that makes sense. Even if I'm not publishing something, I guess it would break if I deployed it on a different server.
