### ISSUE TITLE
Dynamic import make codes duplicates in chunks and loads

### ISSUE THREAD

**Issue by Inateno** [webpack/webpack#8441]
# Bug report

I made a repo here that shows all those behaviors, for making things easier I will use the names of the files from this repo. (click and press up/down/left/right to load everything dynamically).
https://github.com/Inateno/webpack4-full-dynamic

**What is the current behavior?**
1. Let's take dynamics module, Left, Down, both are using "Base". Base is included in both files.

2. Empty is using Left, we call Empty on the click during the execution, which include Left and Base sources, then we press Left key, this now download the Left bundle (but we already loaded this bundle while downloading Empty)..

**What is the expected behavior?**

For me, 2 options are acceptable.

1. include "Base" in the main chunk, actually to bypass the current behavior I include it in my main js file (this works but it's not cool).

2. create automatically a new chunk, it will be loaded when we call a module that require it (A,B,C or whatever).

Specific problem for Empty requiring Left:

This one is probably the easier to fix, when we download Empty, Left source is included, so the tree-shaking should "know" this Left dependency and it shouldn't ask for a download since it's already loaded in memory.

**Other relevant information:**
webpack version:  4,25,1 (check the package for more)
Node.js version: latest
Operating System: Mac OS 10,14 (but replicated on win8 to)
Additional tools: typescript, babel conf, webpack-dev-server

Let me know if I can provide more informations, but my demo is quite simple.

**Comment by sokra** [comment]
> 2\. create automatically a new chunk, it will be loaded when we call a module that require it (A,B,C or whatever).

We do that once the shared part reaches a certain size (30kb) to be worth the extra request.

**Comment by sokra** [comment]
> This one is probably the easier to fix, when we download Empty, Left source is included, so the tree-shaking should "know" this Left dependency and it shouldn't ask for a download since it's already loaded in memory.

We also do that. If chunk A is completely included in chunk B, downloading chunk B will also flag chunk A as loaded.

**Comment by Inateno** [comment]
Ok but in my case I have 180 different package to load, which mean 10kb * 180 of extra stuff, is there a way to enforce it? (I think it is the optimization options but not sure 'cause I tried it, maybe the wrong way).

For the second option, no it is not. If you try my sample you'll see that chunk A is included in chunk B, but then when calling chunk A it is loaded again (network call from the chrome tab is visible).
Maybe I did something wrong that's why I made the repo, hopefully you can help me understand what's going bad.

Thanks for your time.

**Comment by sokra** [comment]
Take a look at `optimization.splitChunks` i. e. the `minSize` option.
