### ISSUE TITLE
Should not prefer `.wasm` over other extensions in `resolve.extensions`

### ISSUE THREAD

**Issue by sodatea** [webpack/webpack#8445]
# Bug report

**What is the current behavior?**

Per the doc https://webpack.js.org/configuration/resolve/#resolve-extensions `resolve.extensions` defaults to `['.wasm', '.mjs', '.js', '.json']`, so if there's a `.wasm` with the same name of a `.js` file, the `.wasm` file will be loaded first.

**If the current behavior is a bug, please provide the steps to reproduce.**

See https://github.com/vuejs/vue-cli/issues/3023

**What is the expected behavior?**

Considering the standard way to load a wasm file for now is to use the methods under `WebAssembly` namespace, rather than require it directly, it should be legit to instantiate a wasm module in a js file with the same name. The [multimath](https://github.com/nodeca/multimath/) package required by the reproduction example had worked perfectly fine until webpack introduced its experimental wasm support. IMHO `.wasm` should have lower precedence than other extensions and this should be solved on the webpack side.

**Other relevant information:**
webpack version:  4.26.1
Node.js version: v10.13.0
Operating System: macOS 10.14.1
Additional tools: @vue/cli v3.2.1

**Comment by evilebottnawi** [comment]
Fixed https://github.com/webpack/webpack/pull/8448
