### ISSUE TITLE
Webpack config builder UI

### ISSUE THREAD

**Issue by akshatbhargava123** [webpack/webpack#8449]
## Feature request
This is just an idea which I want to share. Can we build a UI for generating webpack configuration?

**What is the expected behavior?**
The UI will have search box / dropdowns for all the existing plugins for webpack which user wishes to use and other configuration parameters.

**What is motivation or use case for adding/changing the behavior?**
This will make webpack easily configurable even by newbies and help understand configuration file easily.

**Are you willing to work on this yourself?**
Yes, I wish to work on this as my GSoC 2019 project. Please suggest if this is a good idea or not or if it can be improved in any way. Thanks community.

**Comment by ematipico** [comment]
We already working on it. It's a project under `webpack-cli` repository. We are working on a GUI and on a server. We just started, if wish to help you'd be very welcome!

https://github.com/webpack/webpack-cli/projects/2

**Comment by evilebottnawi** [comment]
Answer above, feel free to help, thanks!
