### ISSUE TITLE
Missing module dependency between shared and async bundles causing code updates to disappear

### ISSUE THREAD

**Issue by AnujRNair** [webpack/webpack#8455]
# Bug report

**What is the current behavior?**

I'm not sure if this is a webpack or a webpack dev server bug, but it looks like there might be a missing module dependency between async and shared bundles in some edge cases.

At @slackhq, we've run into an interesting bug where changing code, and allowing webpack-dev-server to recompile the code, has resulted in code simply disappearing from the updated bundles!

It's strange because webpack produces the correct bundles on initial load, but loses the dependency link on recompilations (when running webpack-dev-server for instance). Killing webpack and starting the bundling over again results in the correct bundles being produced with the updated code as expected.

I've narrowed this down to the relationship between shared bundles and async bundles which webpack / webpack-dev-server eventually creates - if you have a long dependency tree where you reexport modules over and over, webpack updates the import definitions for code in the shared bundle, but not in the async bundle. This means that there is a mismatch in variable names, and so that variable becomes undefined.

Note that this is only a bug with recompilations - when you use webpack to recompile code from cold, the updated code will be reflected in the changeset.

Also reported to webpack-dev-server here: https://github.com/webpack/webpack-dev-server/issues/1584 but it was recommended I post here from @evilebottnawi 

**If the current behavior is a bug, please provide the steps to reproduce.**

The bug has been replicated in this minimal reproducible repo here. Instructions on how to run have also been provided: https://github.com/AnujRNair/webpack-missing-module-dependency

**What is the expected behavior?**

Both the shared bundle and the async bundle should be updated to reflect the latest code changes.

**Other relevant information:**
webpack version: 4.26.1
Node.js version: 10.1.0
Operating System: Mac
Additional tools: NPM 6.0.1

**Comment by sokra** [comment]
Yep, it's a bug. I have a fix. Working on a test case and PR now.
