### ISSUE TITLE
[Bug] Webpack can't import css from nested modules

### ISSUE THREAD

**Issue by kopax** [webpack/webpack#8456]
# Bug report

Webpack can't import css from nested modules, I have 3 modules:

- A: is the one who import the css files
- B: is the one who tested it working with webpack 
- C: is the one who fail to test with webpack, but this time A was nested in B.

B and C have been tested with the same webpack config.

**What is the current behavior?**

The css file is importer from [font-awesome in module A](https://github.com/bootstrap-styled/rsg-components/blob/master/src/StyleGuide/StyleGuideRenderer.js#L11).

```js
import 'font-awesome/css/font-awesome.css';
```

This dependency is installed in B and tested working here https://travis-ci.org/rollup-umd/documentation/jobs/462953293

[The css loader configuration looks like this](https://github.com/rollup-umd/documentation/blob/master/src/createConfig.js#L273)

        {
          test: /\.css$/,
          use: ['style-loader', 'css-loader'],
        }

Note: I have been through both documentation : https://webpack.js.org/loaders/style-loader/ and https://github.com/webpack-contrib/css-loader without finding how to setup path.

I am now redoing the same tested but dependencies are nested `A > B > C`, I have the following error:

```
SyntaxError: Invalid or unexpected token
/home/travis/build/bootstrap-styled/documentation/node_modules/font-awesome/css/font-awesome.css:7
@font-face {
^
SyntaxError: Invalid or unexpected token
```

**What is the expected behavior?**

I expect nested dependencies to work fine with css and webpack the latest version.

You can see the error here: https://travis-ci.org/bootstrap-styled/documentation/jobs/462966861#L561

1. Is it possible to setup path for `style-loader` and `css-loader` ?
2. Otherwise, is there another way to work with css in nested module ? 

**Other relevant information:**
webpack version:  4.26.1
Node.js version: v10.10.0
Operating System: Linux dev-01 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
Additional tools: npm 6.4.1

**Comment by sokra** [comment]
```
SyntaxError: Invalid or unexpected token
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

This looks like you are trying to `require` css in node.js. This doesn't work. webpack isn't involved in the error here.

**Comment by sokra** [comment]
> 1. Can you please tell why webpack is not involved?

You can see it from the stack trace. That's the stack trace when calling `require("file.css")` in node.js without being compiled by webpack. I can't say where it's called (maybe longer stacktraces help here). Maybe related to SSR or any other prerendering.

**Comment by LuisAlejandro** [comment]
I'm having this same error :( @kopax, did you manage to solve it?
