### ISSUE TITLE
splitChunks.cacheGroups don't get loaded by webpack

### ISSUE THREAD

**Issue by adrienharnay** [webpack/webpack#8464]
# Bug report

**What is the current behavior?**

When putting code in chunks using splitChunks.cacheGroups, the produced chunks don't get executed by Webpack and ultimately crash the build.

**If the current behavior is a bug, please provide the steps to reproduce.**

I load the `intl` polyfill when the browser doesn't support it, but the default config bundles it with the main chunk, therefore everybody has to download it. So I tried this:

```
cacheGroups: {
  intl: {
    test: /node_modules[\\/]intl[\\/]/,
    chunks: 'entry',
  },
},
```

which creates a chunk `intl~main.[hash].js`, but it is never referenced. I searched for the hash in my build folder, and only found it in the manifest created by https://github.com/danethurber/webpack-manifest-plugin

Everything works without the cacheGroup.

**What is the expected behavior?**

I would expect Webpack to reference the chunk so that it could be lazy-loaded.

**Other relevant information:**
webpack version:  4.26.1
Node.js version: 10.14.0
Operating System: MacOS Mojave 10.14.1
Additional tools: /

Please let me know if you need a repro repository! Thanks in advance

**Comment by sokra** [comment]
For lazy-loading use `import("intl")` not splitChunks.

**Comment by adrienharnay** [comment]
I have a require statement in an if loop, e.g.

```js
if (!window.Intl) {
  window.Intl = require('intl');
}
```

Shouldn't that create a chunk?

**Comment by sokra** [comment]
No only async dependencies create chunks.

* `import("intl")` returning a Promise
* `require.ensure(["intl"], require => require("intl"))`
* `require(["intl"], (intl) => { .. })`

Prefer `import()`

**Comment by adrienharnay** [comment]
I was convinced `require` in an if statement would create a chunk. TIL! Thanks a lot.
