### ISSUE TITLE
Issue when spm is used in package.json

### ISSUE THREAD

**Issue by DanielApt** [webpack/webpack#847]
I'm loading [*Shepherd*](https://github.com/HubSpot/shepherd) as a github dependency.

Their[ `package.json`](https://github.com/HubSpot/shepherd/blob/master/package.json) does not use the `main` property, but instead uses `spm.main`. 

How can I instruct webpack to look at both the `main` and `spm.main` property inside a `package.json`? I've tried using the [`ResolverPlugin`](https://github.com/webpack/docs/wiki/list-of-plugins#resolverplugin) but have not succeeded in getting this to work.

Also should this become default behaviour in the product? I'm not familiar with [*spm*](https://github.com/spmjs/spm), but this could be an issue in the future again.

**Comment by sokra** [comment]
``` js
new webpack.ResolverPlugin([
    new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin("package.json", [["spm", "main"]])
], ["normal"])
```

**Comment by DanielApt** [comment]
Thanks! Mind if I ask, but why are you placing an array in an array?

We could change the `DirectoryDescriptFilePlugin` to accept `["spm", "main"] instead of `[["spm", "main"]]`

What are your thoughts on that? Happy to give it a shot if you want me to.

**Comment by sokra** [comment]
it accepts multiple fields:

``` js
DirectoryDescriptionFilePlugin("package.json", ["main", "browser", ["spm", "main"]])
```

**Comment by DanielApt** [comment]
Alright, thanks for explaining!
