### ISSUE TITLE
Feature: prefetch dynamic import on demand

### ISSUE THREAD

**Issue by dawidgarus** [webpack/webpack#8470]
## Feature request

**What is the expected behavior?**
I would be nice to have ability to customize when dynamic import are prefetch exactly

**What is motivation or use case for adding/changing the behavior?**
With magic comments like `/* webpackPrefetch: 1 */` we can say that we wan't this dynamic import to be prefetched and determine priority, but you can't specify when you wan't to prefetch them.
To be considerate for users with slow internet connection and/or for those who pay for every byte received, you may not want to prefetch all the dynamic imports but only imports for the routes that are directly accessible from you current route.
For example, from your home page you can go to "to do" list, so you want to prefetch list component, but don't prefetch item details component right away, only when you go to list.

**How should this be implemented in your opinion?**
We can use `webpackChunkName` to name a dynamic import and the use new kind of magic comment, lets say: `/* webpackPrefetchChunk: <CHUNK NAME> <PRIORITY>` */.
The magic comment should be replaced by webpack with code that adds `<link>` tag, for example:
```javascript
class MyComponent {
  constructor() {
    /* webpackPrefetchChunk: foo 0` */
  }
}
```
should be replaced with something like this:
```javascript
class MyComponent {
  constructor() {
    __webpackPrefetchChunk('foo', 0);
  }
}
```
**Are you willing to work on this yourself?**
no

**Comment by dawidgarus** [comment]
Any response?

**Comment by theKashey** [comment]
It would be better to have some __command__ to prefetch import. To be more concrete - import something without parsing and/or executing it (probably that's 2 different commands).

How it should look like? There are 3 options:
- another command, like `require.prefetch`. It would be not easy to start using it with existing libraries.
- magic method on import, like `import('./module').prefetch()`. But I don't feel like this, as long as import is a "standard".
- sandbox. A temporal zone, where `imports` are doing something different. Probably this is a mostly acceptable solution.

```js
 _webpack_no_execute_(() => import('./somemodule'));
 _webpack_prefetch_only_(someImporter);
 _webpack_in_import_mode_('webpackPrefetch', ReactLazy._ctor);
```
> inside `_webpack_no_execute_` imports would not "execute", but parse. `_webpack_prefetch_only_` - only prefetch the data. And `_webpack_in_import_mode_` just "overrides" magic methods.

**Comment by ScriptedAlchemy** [comment]
Additionally - while we are on the feature request. The ability to unload a chunk from the module manifest. 

```

 const someModule = _webpack_no_execute_(() => import('./somemodule'));
_webpack_clean_module_(someModule);
```

The idea being that i can load and unload chunks from the module cache like `calloc`  Or `free` 

Where’s this useful? When I’m loading chunks from other webpack bundles

https://github.com/ScriptedAlchemy/webpack-external-import

@theKashey does this in React when hot reloading, the ability to cleanly “unimport” code would let us power users build massive apps stitched together and manage memory. 

The idea being we remove references, remove it from the module cache in a way that doesnt trigger __webpack_modules__ to become a slow object. 

If later on, the code is dynamically imported again, well browser cache should make it as easy as loading from disk. 

I thunk unloading code would be a powerful tool.

**Comment by ScriptedAlchemy** [comment]
As apps are getting bigger, i know some that are 100mb of js, the ability to unload that code would be fantastic. Lets say i have moment, and i need to import it for literally one thing on one page. Now for the entire user journey - moment is chewing up memory and references. The ability to do something like “dynamically load moment.js, generate this one time stamp that will never (Like crypto key) then at the end of the function, unload moment.js from memory” 

This scenario is for a situation where i would need the code to execute something in order to create a variable, and would likely not need to ever execute that code again after i have my variable.

**Comment by theKashey** [comment]
Sorry @webpack-bot, but we still need this feature :)

**Comment by xiaogdgenuine** [comment]
@theKashey I run into this issue too, after few days of research, I end up with a hacky way(create a babel plugin to transform prefetch import), pls check here:

[Prefetch - Take control from webpack](https://medium.com/@migcoder/prefetch-preload-take-control-from-webpack-26d1e0f2c3)

I really appreciate if webpack team can look at implement this feature into webpack, so we don't have to do so much extra works :p

**Comment by xiaogdgenuine** [comment]
Hi all, I put all my knowledge into this plugin, feel free to have a try:

https://www.npmjs.com/package/webpack-prefetcher

**Comment by theKashey** [comment]
@xiaogdgenuine - simple and powerful 👍, and the problem is well pointed.

**Comment by dawidgarus** [comment]
@xiaogdgenuine Good work, but it wish it wouldn't require babel. It's webpack - it transform files, it should be possible to do it as webpack plugin using parser hooks: https://webpack.js.org/api/parser/
Perhaps it would be even possible to get rid of the need for manifest.

**Comment by xiaogdgenuine** [comment]
@dawidgarus U are totally right, I'm running to problem B when I try to solve problem A....I should try to only use webpack at the beginning...

I need some time to study these parser hooks, will update here if I can achieve this!

**Comment by gaurav5430** [comment]
I have a similar requirement where one of my lazy loaded chunk has references to 6-7 other chunks which should be prefetched conditionally, as only one or two of them would be required at a time. 

What is the reason that webpack doesn't have this as default? Is it because this is not possible with the magic comment syntax? Are there any technical limitations?
