### ISSUE TITLE
Add ability to setup separated bundles in one config

### ISSUE THREAD

**Issue by akopchinskiy** [webpack/webpack#8471]
**Do you want to request a *feature* or report a *bug*?**
Request a feature.

**What is the current behavior?**
not relevant

**If the current behavior is a bug, please provide the steps to reproduce.**
not relevant

**What is the expected behavior?**
not relevant

**If this is a feature request, what is motivation or use case for changing the behavior?**
It would be way more convenient and flexible than current approach.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
not relevant

## Description:
I suggest that, because it could be way more convenient and flexible than current approach.
The point is to create one config file to compile several separated scripts. It could be very convenient for creating electron apps or browser extensions with several scripts placed in separated folders, that runs in parrallel.

**Example:**
```js
const config =  {
    entry: {
        app: {    // all settings here override the common settings
            input: './src/app/app.ts',
            output: path.join(__dirname, './dist/app/app.js'),  // optional

            overrides: {    // optional
                target: "electron-main",

                module: {
                    rules: [
                        {
                            test: /\.vue?$/,
                            loader: 'vue-loader'
                        },

                        {
                            test: /\.scss$/,
                            use: [{
                                loader: 'to-string-loader'
                            }, {
                                loader: 'css-loader'
                            }, {
                                loader: 'sass-loader'
                            }]
                        }
                    ]
                }
            }
        },

        server: {    // Custom settings for the backend
            input: './src/server/backend.ts',
            output: path.join(__dirname, './dist/server/server.js'),

            overrides: {
                target: "node",
            }
        }
    },

    /*
    * Below follows the general settings.
    */
    output: {  // only for entries without explicit output settings
        path: path.join(__dirname, './dist'),
        filename: '[name].bundle.js'
    },

    target: "web",

    module: {
        rules: [
            {
                test: /\.ts$/,
                loader: 'ts-loader'
            },

            {
                test: /\.js?$/,
                loader: 'babel-loader'
            }
        ],
    },

    plugins: [
        ...
    ]
}

export default config;
```

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by akopchinskiy** [comment]
@montogeek Done. Please reopen.

**Comment by evilebottnawi** [comment]
@akopchinskiy It is hard for me to understand exactly what you are offering? Move `webpack-dev-server` in `entry`?

**Comment by akopchinskiy** [comment]
@akopchinskiy No, it's not `webpack-dev-server`, it's just a sample name. It could be web extension background script, for example.
The point is to create one config file to compile several separated scripts. It could be very convenient for creating electron apps or browser extensions with several scripts that runs in parrallel.

To clearify what I mean: https://developer.chrome.com/extensions/overview

**Comment by evilebottnawi** [comment]
@akopchinskiy why don't use multi compile mode? He was create for this case

**Comment by akopchinskiy** [comment]
@evilebottnawi I never seen that thing before, despite many search attempts. Thank you, seems like my suggestion is already implemented.
You are free to close this issue.
