### ISSUE TITLE
Doc Request: Strategies for structuring configuration

### ISSUE THREAD

**Issue by Ephem** [webpack/webpack#8475]
**Request:** Expand [the configuration section](https://webpack.js.org/concepts/configuration/) of the docs to include a few concrete examples/approaches/strategies/practical tips for _how_ to structure a complex webpack configuration well.

**Related issue (old):** #870 

---

The configuration section lists a few good starting tips and also says:

> The most important part to take away from this document is that there are many different ways to format and style your webpack configuration. The key is to stick with something consistent that you and your team can understand and maintain.

For less complex configurations I feel this is doable, but for complex setups I find this hard to achieve in practice.

If it's helpful, there are two tradeoffs I can think of that I especially struggle with:

* Having several targets (server, modern browsers, older browsers) as well as several modes (dev, test, prod) creates a kind of multi-dimensional configuration that no matter how I try to cut it, it's hard to understand and maintain.
* Being able to easily review and understand the entire configuration vs splitting it up into smaller maintainable pieces, I never quite seem to find a balance.

---

All projects are different and complex configurations are usually complex because the requirements are, so I'm not sure this is easily addressable in the docs, but a few more pointers wouldn't hurt. :)

Thanks for the already awesome docs and all your hard work! 👏 👏 👏

**Comment by montogeek** [comment]
@webpack-bot move to webpack/webpack.js.org
