### ISSUE TITLE
Why webpack will search and check another js file which entry js not import

### ISSUE THREAD

**Issue by LaiHuanMin** [webpack/webpack#8479]
# Bug report

**What is the current behavior?**
Why webpack will check and scan all js file inside src folder, even though I didn't import their files according to entry js.     
And because webpack scan all files, it causes webpack crash because the scan file is too many make memory increase (seems like it's v8 bug, it's will limit memory size which mainly is 200MB-280MB)    
So I wonder, how to disabled webpack don't check and warn not imported js file?Should I specify it in configuration?   

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  4.27.1
Node.js version:  8.4.0
Operating System:  Ubuntu 16.04
Additional tools: none

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.
