### ISSUE TITLE
library target umd - Uncaught TypeError: x is not a constructor

### ISSUE THREAD

**Issue by AhsanAbrar** [webpack/webpack#8480]
# Bug report

````
class Point {
    constructor(x, y) {
        this.x = x;
        this.y = y;
    }

    toString() {
        return `(${this.x}, ${this.y})`;
    }
}

export default Point;
````

````
const path = require('path');

module.exports = {
  entry: './src/index.js',
  output: {
    library: 'point',
    libraryTarget: 'umd',
    umdNamedDefine: true,
    path: path.resolve(__dirname, 'dist'),
    filename: 'bundle.js'
  }
};
````

so when i include in my index.html file like this:

````
<!DOCTYPE html>
<html>
<head>
    <title>Webpack</title>
</head>
<body>

    <!-- Scripts -->
    <script src="dist/bundle.js"></script>

    <script type="text/javascript">
        new point(1, 3).toString()
    </script>
</body>
</html>
````

so i have this error in console

> "Uncaught TypeError: point is not a constructor"

why i'm seeing this error while compile with webpack?

same scenario working fine with rollup

and one more thing i saw almost every developer use rollup for es6 package development to compile "esm", "umd" versions of the script.

but i want to use webpack instead of rollup.

any guide?

thanks

**Other relevant information:**
webpack version: 4.27.1
Node.js version: 11.3.0
Operating System: Windows 10
Additional tools:

**Comment by sokra** [comment]
What's the value of point?

Could you try https://webpack.js.org/configuration/output/#output-libraryexport

**Comment by AhsanAbrar** [comment]
@sokra it should show in console "(1, 3)" string.

same scenario working fine with rollup umd

i tried lot's of things but failed.

**Comment by sokra** [comment]
Try `console.log(point)` and check what it say. I assume is says `{ default: [Point] }` and this can be changed with `output.libraryExport: "default"`

**Comment by AhsanAbrar** [comment]
@sokra Thanks

webpack is rock!

**Comment by Jordancle** [comment]
> I had the same error message and discovered that the cause was circular import statements. That is: I had two files that imported each other, wherein one file contained an `export default class` that contained a method that was dependent upon an `export function` from the other file. My solution was to move one of the dependencies (functions) out of the class and into a `utils.js` file, which was a more appropriate place for it anyway!

@the1abel I've been trying to debug this issue for a few hours now and your comment helped me resolve it. Thanks!
