### ISSUE TITLE
Tree shaking doesn't seem to work with bson / immutable package

### ISSUE THREAD

**Issue by ulrichb** [webpack/webpack#8483]
# Bug report

**What is the current behavior?**

This is a follow up for #6992 where I extended the sample with partial [`bson`](https://www.npmjs.com/package/bson) and [`immutable`](https://www.npmjs.com/package/immutable) imports (like in my production case).

My partial imports:
```js
import {ObjectId} from 'bson';
import {hash} from 'immutable';
```

Tree shaking doesn't seem to work at all with these packages. [`ObjectId`](https://github.com/mongodb/js-bson/blob/master/lib/objectid.js) resp. [`hash`](https://github.com/facebook/immutable-js/blob/master/src/Hash.js) are pretty small parts of these libraries.

**Note:** I also tried to add `"sideEffects": false` to the local `package.json` within `bson` / `immutable`. => No effect.

The resulting source map:

![image](https://user-images.githubusercontent.com/388796/49708583-8a140e00-fc30-11e8-8e2b-0afd75423497.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

Full repro sample: [webpack-tree-shaking.zip](https://github.com/webpack/webpack/files/2661397/webpack-tree-shaking.zip)

**What is the expected behavior?**

Way smaller imported `bson` / `immutable` parts than 73 / 60 kB.

**Other relevant information:**
webpack version:  4.27.1
Node.js version: 11.4
Operating System: Win

**Comment by sokra** [comment]
Everything works as expected from webpack side. The minimizer isn't able remove the remaining code.

One reason is i. e. that bson uses `eval()` which prevents a lot of optimizations.

Immutable probably uses a wrapper with a lot of methods on the prototype, this basically references all of the methods.

=> These libraries are not optimized for tree-shaking. File issues there. That's probably not a webpack issue.

**Comment by ulrichb** [comment]
@sokra Okay. Thanks for having a look at this.

**Comment by ulrichb** [comment]
@sokra: Are there any tools from the webpack-side to analyze these libraries to find out the exact reason why tree-shaking doesn't work?
