### ISSUE TITLE
Webpack 4 build broke after rebuild

### ISSUE THREAD

**Issue by martin-svk** [webpack/webpack#8485]
# Bug report

**What is the current behavior?**

On https://github.com/webpack/webpack/releases/tag/v4.17.1 everything works fine, on https://github.com/webpack/webpack/releases/tag/v4.17.2 after updating code, webpack rebuilds and the css/styles are broken.

**If the current behavior is a bug, please provide the steps to reproduce.**

My webpack config snippet:

```
    module: {
        rules: [{
            test: /\.css/,
            use: ExtractTextPlugin.extract([{
                loader: 'css-loader',
                options: {
                    importLoaders: 1,
                    sourceMap: true
                }
            }, {
                loader: 'postcss-loader',
                options: postCssSettings
            }])
        }, {
            test: /\.scss/,
            use: ExtractTextPlugin.extract([{
                loader: 'css-loader',
                options: {
                    importLoaders: 2,
                    sourceMap: true
                }
            }, {
                loader: 'postcss-loader',
                options: postCssSettings
            }, {
                loader: 'sass-loader',
                options: {
                    sourceMap: true
                }
            }])
        }, {
            test: /\.less/,
            use: ExtractTextPlugin.extract([{
                loader: 'css-loader',
                options: {
                    importLoaders: 2,
                    sourceMap: true
                }
            }, {
                loader: 'postcss-loader',
                options: postCssSettings
            }, {
                loader: 'less-loader',
                options: {
                    sourceMap: true
                }
            }])
        }, {
            test: /\.(jpe?g|png|gif|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            use: [{
                loader: 'file-loader',
            }, {
                loader: 'image-webpack-loader',
                options: {
                    bypassOnDebug: true
                }
            }]
        }, {
            test: /\.(otf|ttf|eot)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            use: [{
                loader: 'file-loader',
            }]
        }, {
            test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            use: [{
                loader: 'url-loader',
                options: {
                    limit: 10000,
                    mimetype: 'application/font-woff'
                }
            }]
        }]
    }
```

On first build, all is ok, but when i change something in the JS code, webpack rebuilds and pushes changes which results into styles being broken. This didn't happen on 4.17.1.

**What is the expected behavior?**

It should compile assets the same way like in 4.17.1.

**Other relevant information:**
webpack version:  4.17.2 -> 4.27.1
Node.js version: 8.14.0
Operating System: OSX Mojave
Additional tools: ...

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by martin-svk** [comment]
@montogeek I know, unfortunately I am really busy now, and this might take some time. But I have a feeling it might have something to do with `ExtractTextPlugin`.

**Comment by montogeek** [comment]
Try using https://github.com/webpack-contrib/mini-css-extract-plugin

**Comment by evilebottnawi** [comment]
@martin-svk sorry, without reproducible test repo we can't help

**Comment by martin-svk** [comment]
Yes, migrating to `webpack-contrib/mini-css-extract-plugin` solved the issue for me. Thanks for help, closing.
