### ISSUE TITLE
Options missing in ProgressPlugin.json

### ISSUE THREAD

**Issue by jonwrede** [webpack/webpack#8487]
# Bug report

**What is the current behavior?**
ValidationError: Progress Plugin Invalid Options

**If the current behavior is a bug, please provide the steps to reproduce.**
check /schemas/plugins/ProgressPlugin.json color option is missing
I would fix it but i don't know which type to set.

**What is the expected behavior?**
Working lib

**Other relevant information:**
webpack version:  4.27.1
Node.js version:  10.13.0
Operating System:  Fedora 29
Additional tools: @angular/cli@6.2.4

**Comment by ooflorent** [comment]
`color` is not a valid option.

**Comment by jonwrede** [comment]
So not an error in ProgressPlugin but in Angular/CLI because its passing an invalid option?

**Comment by sokra** [comment]
Yes, error in angular-cli.

There is no `color` in this plugin: https://github.com/webpack/webpack/blob/master/lib/ProgressPlugin.js
