### ISSUE TITLE
Improving documentation

### ISSUE THREAD

**Issue by sporto** [webpack/webpack#849]
I have been using Webpack for a while and I still find the documentation difficult to follow. It would be really great if the documentation was more beginner friendly.

I don't offer myself to put a PR for this, because as I say I don't understand all of it. So I am not the right person to improve the documentation itself. 

But I would be happy to review it, make comments and ask questions with the aim that someone with better understanding can fill the documentation gaps. I'm thinking that a tool like https://hypothes.is/ could be really useful.

So would you be open to an effort like this?

**Comment by sokra** [comment]
> It would be really great if the documentation was more beginner friendly.

I would like it too.

> But I would be happy to review it, make comments and ask questions with the aim that someone with better understanding can fill the documentation gaps.

I'll add a commenting function to the documentation.

**Comment by sokra** [comment]
doen
