### ISSUE TITLE
Dynamic import in react is throwing an error

### ISSUE THREAD

**Issue by RabHaSa** [webpack/webpack#8497]
# Bug report

**What is the current behavior?**
I am using a dynamic import to read some text in a module.
 import(`./md/article/${file}.md`)

'file' is a variable carrying the file name the import has to read from, which changes dynamically.

I tried concatenating the text before the variable and after the variable separately, that is before the import call is made and put it in a new variable,  and tried. Added an empty string before the variable and tried concatenating empty string for the whole text inside the import call.

let f1 = file;
let a1 ='./md/article/';
let newFile = a1+file;
newFile = newFile+'.md';
import(''+newFile).then(article.....

This is not working, and throwing an error in the console saying 

Uncaught (in promise) Error: Cannot find module './md/article/xyz'

It works if i use a hard coded value instead of variable 'file'

that is `./md/article/xyz.md`

This issue, I m facing on a windows laptop but my colleague with mac is not facing the issue.

Could some one one provide with a solution? 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  -- webpack@4.27.1
Node.js version:  check-node-version@3.2.0
Operating System:  Windows 7 ("os":"win32","arch":"x64"})
Additional tools: Visual Studio Code.

**Comment by sokra** [comment]
``import(`./md/article/${file}.md)` `` will work.

`import(''+ newFile)` is not support as it's too dynamic to figure out the files at compile-time

**Comment by RabHaSa** [comment]
import(`./md/article/${file}.md`) is not working and throwing an error saying couldn't find the module.
