### ISSUE TITLE
Error: Callback was already called. when using `npm run dev` from docker on windows 

### ISSUE THREAD

**Issue by d3sandoval** [webpack/webpack#8498]
# Bug report
Whenever running `docker-compose up` on a windows machine whose volumes are mounted, I get this error.

**What is the current behavior?**
I recently starting working on a windows machine and found i cannot mount my directory without this issue occuring.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a Dockerfile for next (mine is in /ui):
```
FROM node:10

WORKDIR /usr/ui

COPY package.json .
RUN npm install --quiet

COPY . .

RUN npm run build

CMD npm start
```
2. In docker-compose, refer to that dockerfile and mount the directory
```
version: '3.1'
services:
  ui:
    image: us.gcr.io/anymessage-219921/ui:latest
    build: ./ui
    command: npm run dev
    volumes:
      - ./ui:/usr/ui/
      - /usr/ui/node_modules
    ports:
      - "3000:3000"
    env_file: .env
```
3. Run docker-compose up
```
ui_1          | [9:31:52 PM] Compiling server
ui_1          | [9:31:53 PM] Compiled server in 2s
ui_1          | [9:31:53 PM] Compiling server
ui_1          | /usr/ui/node_modules/neo-async/async.js:14
ui_1          |     throw new Error('Callback was already called.');
ui_1          |     ^
ui_1          |
ui_1          | Error: Callback was already called.
ui_1          |     at throwError (/usr/ui/node_modules/neo-async/async.js:14:11)
ui_1          |     at /usr/ui/node_modules/neo-async/async.js:2813:7
ui_1          |     at process._tickCallback (internal/process/next_tick.js:61:11)
ui_1          | npm ERR! code ELIFECYCLE
ui_1          | npm ERR! errno 1
ui_1          | npm ERR! @anymessage/ui@0.0.1 dev:80: `next -p 80`
ui_1          | npm ERR! Exit status 1
ui_1          | npm ERR!
ui_1          | npm ERR! Failed at the @anymessage/ui@0.0.1 dev:80 script.
ui_1          | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
ui_1          |
ui_1          | npm ERR! A complete log of this run can be found in:
ui_1          | npm ERR!     /root/.npm/_logs/2018-12-12T21_31_54_001Z-debug.log
anymessage_ui_1 exited with code 1
```

**What is the expected behavior?**
available on localhost:3000

**Other relevant information:**
webpack version:  4.20.2
Node.js version: Node:10 https://hub.docker.com/_/node/
Operating System: Windows 10 1803
Additional tools: 
See repo for more info: https://github.com/d3sandoval/anymessage

was sent here from a next.js bug report: https://github.com/zeit/next.js/issues/5872

**Comment by ssavinel** [comment]
@micku : Your questions scare me, I have the same issue in a docker-compose under WSL.
@d3sandoval : do you have any update ? I realized that we have almost the same setup (Dockerfile / docker-compose).

**Comment by d3sandoval** [comment]
@ssavinel i haven't tried it again since i switched to Pop! OS. Was tired of debugging Windows instead of my app. I can boot into windows and report back here.

**Comment by micku** [comment]
@d3sandoval I think the problem is exactly the reason why you switched to Pop! OS and I'm trying to switch to Manjaro... 
Unfortunately I do not have time and knowledge to track this down, so I'm using docker-compose only to run a Redis instance, and then I run the app directly with yarn dev.
