### ISSUE TITLE
IgnorePlugin: 1 function instead of 2

### ISSUE THREAD

**Issue by iliakan** [webpack/webpack#8499]
## Feature request

`IgnorePlugin` now accepts two functions instead of regexps, as discussed in #7794.

I'd suggest to allow passing a single function with 2 arguments instead. That's so much more convenient for logging purposes, and for complex logic that requires both params at the same time.

**Are you willing to work on this yourself?**
yes

**Comment by iliakan** [comment]
Is it ok that `options` become a function, like `IgnorePlugin((resource, context) => boolean)`?

Or it's better to make it an object like this: `IgnorePlugin({ checkIgnore: (resource, context) => boolean})` ?

Also, maybe it would be the most flexible if I pass the whole `result` object to the function?

```
new webpack.IgnorePlugin( ({request, context}) => {
  return request == '../moment'  && context.endsWith('moment/locale');
});
```

**Comment by sokra** [comment]
`options` is an object. Add it as property there.

You can align with the `checkResult` method in the plugin.
