### ISSUE TITLE
ProfilingPlugin error when using outputPath

### ISSUE THREAD

**Issue by atdiff** [webpack/webpack#8503]
# Bug report

**What is the current behavior?**
Following the example in https://webpack.js.org/plugins/profiling-plugin/, when setting the outputPath to a folder that doesn't exist, the build fails with the following error.
```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\workspaces\myApp\exampleFolder\compilation-stats.json'
Emitted 'error' event at:
    at WriteStream.onerror (_stream_readable.js:690:12)
    at WriteStream.emit (events.js:182:13)
    at lazyFs.open (internal/fs/streams.js:273:12)
    at FSReqWrap.oncomplete (fs.js:141:20)

```

**If the current behavior is a bug, please provide the steps to reproduce.**
Add this block to the plugins section:
```
new webpack.debug.ProfilingPlugin({
	outputPath: 'exampleFolder/compilation-stats.json'
}),
```

**What is the expected behavior?**
I would expect that if a relative folder doesn't exist, that the plugin would create one. The example indicates providing a folder path, so it's possible.

**Other relevant information:**
webpack version:  4.27.1
Node.js version: 10.12.0
Operating System: Windows 10
Additional tools:

**Comment by NaviMarella** [comment]
@sokra I would like to send a PR for this issue.

**Comment by NaviMarella** [comment]
@sokra Here is my initial thought.

#### Current Functionality

- events.json file is created at default root context, if user doesn't mention any outputPath.
- No validation for outputPath and file type. Creates any type of file with the name given in outputPath [ex:- test.ts].
- Throws an error, if folder path given by user doesn't exist [Main issue logged above](https://github.com/webpack/webpack/issues/8503).

#### Future Functionality

- **No outputPath property given:-** 
	events.json file will be always created in dist [output path]/debug folder, if user doesn't mention any outputPath.
- **outputPath property without folder path but with a file name ['sample.json']:-** 
	Validate file type and throw error if doesn't match json type. 

	'sample.json' file will be always created in dist[output path]/debug folder.
- **outputPath with just folder name ['sampleFolder']:-**
 	Create a folder at root context, if it doesn't exists and place events.json in the created folder 'sampleFolder'.
- **outputPath property with folder path and file name ['sampleFolder/sample.json']:-** 
	Create a sampleFolder at root context if it doesn't exists and place 'sample.json' file inside the folder.

**Comment by sokra** [comment]
I don't think it's a good idea to emit these kind of files into the `dist` folder. The `dist` folder is something the user deploys on a web server. `events.json` is not something that should be deployed.

In addition to that it would be a breaking change to change the default directory for that.

You don't have to put too much magic/work into that. Start by fixing the bug, as bugfix and feature should go into separate PRs anyway.

**Comment by NaviMarella** [comment]
@sokra 

Sure i will go ahead with fixing the bug. 

Also can you point at an example, on how to write unit tests for checking if folder is created or not [Tests for dealing with node file system].

**Comment by evilebottnawi** [comment]
Bump
