### ISSUE TITLE
Import star for json modules — unexpected "default" field

### ISSUE THREAD

**Issue by DeTeam** [webpack/webpack#8504]
# Bug report

**What is the current behavior?**

We're using a webpack with babel for bundling some typescript code. We use multi compiler (different targets) with multiple entries (independent pieces of code coming into the system).

Inside the entrypoints we somtimes import jsons. The way we we importing json was:

```
import * as config from './config.json'
```

^^^ Using `import as`.

Right now, some modules when imported have both `default` key and the actual keys inside default brought to the top level (can't reproduce in isolation) some other modules have just `default` parameter which is not what we expected (just wanted to get a normal object as if it's commonjs).

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/DeTeam/import-json-as — made a small repository to illustrate the issue

**What is the expected behavior?**

1. Would be good to understand webpack's guarantees on json modules imports (requirejs vs harmony vs harmony import *) — can be that we just have wrong expectations 🤷‍♀️  
1. Either one way (just runtime template based code or concat modules based code) is used to generate output

\* our expectations are fulfilled when `ModuleConcatenationPlugin` kicks in (sometimes) for a file

**Other relevant information:**
webpack version:  `4.27.1`
Node.js version: `v10.9.0`
Operating System: Mac os + ubuntu in docker
Additional tools: babel (sometimes, isolated example does not contain it)

**Comment by DeTeam** [comment]
@sokra thanks for clarification. 

>  This is the official way to import json data.

Is this behaviour part of some spec?

In any case, I'm wondering why in some cases content of the namespace object is different (depending on `ModuleConcatenationPlugin` being used or not).. Will try to reproduce it later upcoming week. Maybe you have some ideas what can it be?

**Comment by sokra** [comment]
> In any case, I'm wondering why in some cases content of the namespace object is different (depending on ModuleConcatenationPlugin being used or not).. 

That shouldn't be the case. If you can reproduce it than it's a bug

**Comment by grassator** [comment]
@sokra there is also an issue that depending on usage `import * as` will generate different code which seems to do with tree shaking. I.e. these 2 snippets result in different semantics:

```js
import * as config from "./config.json";
console.log(config.foo);
```

This will correctly print out the value of `.foo` field. While this will fail because object has only `default` field.

```js
import * as config from "./config.json";
const c = config;
console.log(c.foo);
```

I believe these two cases should either behave identically or generate some sort of warning, otherwise it is very easy to break your code with a change that should have no semantic difference.

**Comment by sokra** [comment]
hmm.. i see. seems like the namespace object is generated incorrectly.
