### ISSUE TITLE
Allow return outside function

### ISSUE THREAD

**Issue by guybedford** [webpack/webpack#8509]
# Bug report

**What is the current behavior?**

Webpack doesn't seem to support parsing the "return" statement top-level usage in CommonJS.

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a CommonJS file with a top-level return and try to build it with Webpack.

**What is the expected behavior?**

When the module being parsed is being treated as CommonJS, the `allowReturnOutsideFunction: true` acorn option should be set to correctly support the CommonJS semantics.

**Other relevant information:**
webpack version:  4.27.1, next
Node.js version: 10.x
Operating System: OSX
Additional tools:

**Comment by sokra** [comment]
Send a PR

**Comment by smelukov** [comment]
PR was merged. Can we close this PR?

**Comment by evilebottnawi** [comment]
@smelukov yep :+1:
