### ISSUE TITLE
Code splitting doesn't work

### ISSUE THREAD

**Issue by AlexPravdin** [webpack/webpack#8512]
# Bug report

I'm following the docs: https://webpack.js.org/guides/code-splitting/#dynamic-imports and trying to apply code splitting. My webpack.config.js is as follows:

```
const path = require('path')
const webpack = require('webpack')

module.exports = {
  devServer: {
    inline: true,
    port: 8081,
    host: '0.0.0.0',
    publicPath: '/static/build/',
    historyApiFallback: true,
  },
  entry: {
    'dashboard': './pages/dashboard/entry.js',
    'auth': './pages/auth/entry.js',
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        loaders: ['babel-loader'],
        exclude: /node_modules/
      },
      {
        test: /\.scss$/,
        use: [
          "style-loader", "css-loader", 'postcss-loader', 'sass-loader?sourceMap'
        ]
      },
      {
        test: /\.css$/,
        use: [
          "style-loader", "css-loader", 'postcss-loader'
        ]
      },
    ]
  },
  optimization: {
    splitChunks: {
      chunks: 'all',
    }
  },
  output: {
    path: path.resolve(__dirname, 'static/build'),
    filename: '[name].js'
  },
};

```

During `webpack --mode production` webpack generates the following files:

```
auth.js
auth~dashboard.js
dashboard.js
vendors~auth.js
vendors~auth~dashboard.js
vendors~dashboard.js

```
The html page for the Dashboard page is as follows:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dashboard</title>
</head>
<body>
<div id="root"></div>
<script src="/static/build/dashboard.js"></script>
</body>
</html>

```

**What is the current behavior?**
When html page is loaded nothing happen. The screen remain white. No JS console errors. Browser loads only the bashboard.js file and nothing more. If I remove code splitting the app works fine.

**If the current behavior is a bug, please provide the steps to reproduce.**
Just follow the steps in docs and apply code splitting to an existing application.

**What is the expected behavior?**
When I follow instructions in the documentation and add code splitting to the confing, my application is fully working with splitted chunks.

**Comment by sokra** [comment]
You need to include all scripts corresponding to the dashboard page in your HMTL:

``` html
<script src="/static/build/dashboard.js" async></script>
<script src="/static/build/auth~dashboard.js" async></script>
<script src="/static/build/vendors~auth~dashboard.js" async></script>
<script src="/static/build/vendors~dashboard.js" async></script>
``` 

Order is irrelevant.

The webpack output should print something like:

```
Entrypoint dashboard = auth~dashboard.js dashboard.js vendors~auth~dashboard.js vendors~dashboard.js
```

Best use a plugin to generate the correct HTML: i. e. html-webpack-plugin

**Comment by AlexPravdin** [comment]
Could you mention this in the docs please? To clarify it for beginners.

**Comment by AlexPravdin** [comment]
The html-webpack-plugin can not recognize which particular modules are used for each entry point so it always include all chunks to the resulting HTML. Or I need to list chunks manually. This is not a handy behaviour because I wish it to be fully automatic. Chunk list is dynamic and it will always take time to manually check are all the chunks for the entry are listed in config file orr not.

**Comment by evilebottnawi** [comment]
@AlexPravdin Better ask this in `html-webpack-plugin`, thanks
