### ISSUE TITLE
Loader exclude option not applied to entrypoint

### ISSUE THREAD

**Issue by PlayMa256** [webpack/webpack#8513]
# Bug report

**What is the current behavior?**
Having `node_modules` on `exclude` options of a loader (in this case, babel-loader) does not explicitly excludes an entry point that is part of `node_modules`. If i explicitly defines it, it is excluded, otherwise transpiled as well.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/PlayMa256/wp-bug/

**What is the expected behavior?**
Even being an entry point it should not be transpiled.

**Other relevant information:**
Node.js version: 10.14
Operating System: ubuntu 18

**Comment by sokra** [comment]
I don't see the problem from your repo. `webpack-plugin-serve/client` don't seem to be transpiled.

**Comment by PlayMa256** [comment]
Some problems of communication happened with a friend, which told me to look at it. I'll investigate further and get back if needed. Thanks and sorry!
