### ISSUE TITLE
sourcemaps and sourcemap + more errors all at once.

### ISSUE THREAD

**Issue by kaigouthro** [webpack/webpack#8514]
# Bug report

[gist of errors](https://gist.github.com/kaigouthro/52cf43833f1e7596524acc137f5f252e)

**What is the current behavior?**
giving errors about source maps

**If the current behavior is a bug, please provide the steps to reproduce.**
npm start.

**What is the expected behavior?**
to compile as normal without sourcemaps even turned on....

ejected CRA, updated all modules, packages, and plugins  to latest versions

at first it was compiling and having a problem reading "<" at the start of any html tag... it wouldn't get past  the first tag in index.js i updated babel-core and html-webpack-plugin to @next and that at least  changed it to these errors...

sourcemaps vs sourcemap, and problems coming fro internal webpack code

**Other relevant information:**
webpack version: 
4.27.1 
Node.js version: 
10.5
Operating System: 
![winver](https://user-images.githubusercontent.com/777603/50090823-ecd44f00-01c6-11e9-8c97-6626b6090688.JPG)
Additional tools:
not all enabled..... 

[Gist package json](https://gist.github.com/kaigouthro/1f254e37d5840ada064a547941302ca4)

**Comment by evilebottnawi** [comment]
@kaigouthro please use `gist` for code (or better create reproducible test repo), issue is unreadable, so nobody help you, fix it, thanks

**Comment by sokra** [comment]
Please read the Error Message. It tells you what's wrong. It's from Babel.
