### ISSUE TITLE
Dynamic require doesn't work with JSON file

### ISSUE THREAD

**Issue by rebornix** [webpack/webpack#8515]
# Bug report

**What is the current behavior?**

Dynamic require works fine with javascript modules and webpack can load json without any problem, however once you mix them, it will fail.

**If the current behavior is a bug, please provide the steps to reproduce.**

Say you have a node module which tries to reference its own `package.json`

```
const pkg = require('../../package.json')
```

In the bundled file the output will be like

```
const pkg = __webpack_require__(/*! ../../package.json */ "./node_modules/@octokit/rest/package.json")
```

however, if the way you reference the `package.json` requires reading from `__dirname` like below

```
const pkg = require(path.join(__dirname, "package.json"))
```

The output will always be 

```
const pkg = __webpack_require__("./node_modules/mymodule sync recursive")(path.join(__dirname, 'package.json'));
```

```
/***/ "./node_modules/mymodule sync recursive":
/*!********************************!*\
  !*** ./node_modules/mymodule sync ***!
  \********************************/
/*! no static exports found */
/***/ (function(module, exports) {

function webpackEmptyContext(req) {
	var e = new Error("Cannot find module '" + req + "'");
	e.code = 'MODULE_NOT_FOUND';
	throw e;
}
webpackEmptyContext.keys = function() { return []; };
webpackEmptyContext.resolve = webpackEmptyContext;
module.exports = webpackEmptyContext;
webpackEmptyContext.id = "./node_modules/mymodule sync recursive";
```

I tried to modify `options.node.__dirname` but all three possible values don't solve the problem.

**What is the expected behavior?**

**Other relevant information:**
webpack version: 4.1.0
Node.js version: v8.9.3
Operating System: macOS 10.14.1 
Additional tools:

**Comment by sokra** [comment]
Yeah, don't do that. Pass relative values to require.

**Comment by rebornix** [comment]
> Yeah, don't do that. Pass relative values to require.

@sokra thanks for your reply. I'd love to do that if the module is maintained by me but unluckily it's not. Do you think *Copy Webpack Plugin* is the right solution for this case, with which I can actually ignore this module and treat it as external dependency?

**Comment by rebornix** [comment]
BTW, is there any reason that this can not be supported? Since now JSON loader works without any configuration, users might expect it to work the same as JavaScript files. If this is a valid feature request, I can give it a try.

**Comment by ganyanchuan1989** [comment]
how fix it?
