### ISSUE TITLE
Async import of a wasm module throws an exception synchronously, instead of rejecting the returned promise, in browsers without WebAssembly

### ISSUE THREAD

**Issue by mstange** [webpack/webpack#8517]
# Bug report

**What is the current behavior?**

In browsers that don't expose a `WebAssembly` object, `import('some-wasm-module')` will throw a synchronous exception.

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a project that contains a WebAssembly module and use it via the async import syntax. Then run the project in an older browser that does not support WebAssembly, or in Firefox safe mode.

**What is the expected behavior?**

The case of the `WebAssembly` object not being defined should be handled intentionally. I think the best way to surface it would be by rejecting the promise that the async `import` function returns.

`import` can also fail asynchronously, so users should be handling promise rejections already.

At the moment, I have to wrap the `import()` invocation into an `async function` so that I can use the same error handling code for both failure cases.

**Other relevant information:**
webpack version:  4.26.1
Node.js version: 10.11.0
Operating System: macOS
Additional tools:

**Comment by sokra** [comment]
Yeah this is a bug and should be fixed.
