### ISSUE TITLE
Not sure if this is possible, but with multiple entries can I not minify some?

### ISSUE THREAD

**Issue by Ashwin117** [webpack/webpack#8519]
## Feature request
Ability to individually configure on multiple entries. For example on 3 entries, I want to un-minify and un-uglify 1 of them. But the other 2 it's alright to minify and uglify.

**What is the expected behavior?**
More control on webpack configuration.

**What is motivation or use case for adding/changing the behavior?**
Well, in my case, I have a library that exports multiple files (JS, CSS, and other JS file). I want some of my JS files to not be minified.

**How should this be implemented in your opinion?**
Not sure.

**Are you willing to work on this yourself?**
No

**Comment by sokra** [comment]
You have to use `terser-webpack-plugin` directly. There is a `include` `exclude` option there.

**Comment by evilebottnawi** [comment]
Answer here https://github.com/webpack/webpack/issues/8519#issuecomment-448115475
