### ISSUE TITLE
Wrong script charset when using dynamic import

### ISSUE THREAD

**Issue by irudoy** [webpack/webpack#8521]
# Bug report

Page encoded in windows-1251. All chunks are encoded in windows-1251 using the `webpack-encoding-plugin`.

**What is the current behavior?**
Doing dynamic `import()` call. Windows-1251 encoded chunk injected with `charset="utf-8"` attribute.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/irudoy/webpack-charset-repro

**What is the expected behavior?**
Doing dynamic `import()` call. Windows-1251 encoded chunk injected with `charset="windows-1251"` attribute.

**Other relevant information:**
webpack version: 4.27.1
Node.js version: 11.4.0
Operating System: macOS 10.14.1

Possible solution: https://github.com/webpack/webpack/pull/8288

**Comment by irudoy** [comment]
@sokra please take a look at this. The charset attribute value is hardcoded, and there is no workaround for this problem.

**Comment by alexey-sh** [comment]
this is my repo
https://github.com/alexey-sh/webpack_and_babel_broken_encoding

webpack converts 
"\u0002\u001E\u012E\b\u0001\b\u0001\u0004\u0002\t\u0002\u0004\u0003\t"

into 

"Į		"

browserify doesn't have such bad bad behaviour

**Comment by evilebottnawi** [comment]
Original answer https://github.com/webpack/webpack/pull/8288#issuecomment-510047730.

Ref (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script):

> charset 
> If present, its value must be an ASCII case-insensitive match for "utf-8". It’s unnecessary to specify the charset attribute, because documents must use UTF-8, and the script element inherits its character encoding from the document.

Also:

>Module scripts are always interpreted as UTF-8.

If you still need to use non `utf-8` charset you can use a plugin - https://github.com/dromru/encoding-plugin/blob/master/EncodingPlugin.js
