### ISSUE TITLE
if i want to exclude one file, it doesn't work

### ISSUE THREAD

**Issue by amiznikov** [webpack/webpack#8523]
Hello, i try to exclude only one file:
`  module: {
    rules: [
      {
        test: /\.(jpg|png|svg|jpeg)$/,
        exclude: /apple-touch-icon\.png/,
        loader: 'file-loader',
        options: {
          outputPath: 'assets/images/'
        },
      },`

but, it included

version webpack: 
`
    "file-loader": "^2.0.0",
    "webpack": "^4.6.0",
    "webpack-cli": "^3.1.1",
    "webpack-concat-plugin": "^3.0.0-beta.0",
    "webpack-dev-server": "^3.1.3",
    "webpack-merge-and-include-globally": "^1.0.1",
    "webpack-raw-bundler": "^1.3.6",
`

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
