### ISSUE TITLE
Micro Frontend architecture - many builds as one

### ISSUE THREAD

**Issue by ScriptedAlchemy** [webpack/webpack#8524]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**
Webpack bundles the context based on its given entry point. Works perfectly as expected. 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

I am working on architecture at scale, where micro Frontend verticals (stand-alone web apps) can build and deploy a specific user flow. 

The challenge comes in when I want to create an orchestration layer. The idea is that independent services can build their own Frontend. But when on the client, the application, which is made of many smaller builds, can act as one and Universally load code. 

I know there are ways to fiddle around with webpackJsonp but looking for the correct way. How can I smoothly merge two separate webpack asset manifests to allow a large application consisting of 70 micro Frontends to act as one on the client? 

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

As of now, I’ve done really crummy solutions like NPM installing a bunch of packages into a layout engine, then using common patterns, point the user to the static entry point. The issue is. React apps don’t behave as you expect because when going from one micro frontend to another, there’s usually a reload of the page as the next entry point is needed. 

What I’m looking for is a way to code split and share across builds without relying on externals. I want to require code that would exist in another build and dynamically load it as if it were bundled under the same Singleton build. 

Right now, think of Frontend as a monolith, if I want to code split pages. I must bundle them under the same single build. 

 However, in my case, I would like each microservice to build its own front and then have a layout engine of some sort which can concatenate only the manifests and deliver webpackJsonp an array that would theoretically contain modules from multiple other builds. Therefore when requiring a module from building number 7, webpack knows how to dynamically load it as if it were all done under one build. Right now it’s a guessworks and lots of manual labor, but how could I join many builds manifests so that the client would not know that one module came from another code split build rather than its own parent build. 

 While I do understand that there are hacks such as externals,  it does seem like more effort than one would expect.  My goal here is that some kind of layout engine could inject multiple manifests. Which allow webpack to treat various builds as if it were one single build on the client side. This allows for scale and ease of dependency management. 

I’ve been doing this in a basic manner. I have been able to implement things like scout files which attempt to fetch the entry points ahead of time, but it’s complex. 

I am more than willing to climb in and contribute to webpack. My co-author wrote require.resolveWeak for webpack, so we have had some exposure and would be willing to collaborate with webpack team again if this feature is not achievable. It’s the finale blocker on true standalone systems that can operate together as in-app one the client.

**Comment by ScriptedAlchemy** [comment]
Here’s a really simple example. I want a gateway, which can hold many manifests in one array, then everything else acts as normal. If a service goes down, the other builds - because they are standalone keep on operating. This also allows SSR to scale at a granular level. 

Would appreciate the input from webpack and would seriously enjoy working with the team to make this a reality / make a encapsulation system to help manage it. Any ideas you can throw this way would be priceless to me

![73ab03d8-5b50-47e9-9bfe-cd4ff5530c9a](https://user-images.githubusercontent.com/25274700/50267904-b7557e80-03dd-11e9-833a-88a0cb145b38.png)

**Comment by Pyrolistical** [comment]
https://microapps.netlify.com

**Comment by ScriptedAlchemy** [comment]
I want no page reload. True SPA capabilities

**Comment by Pyrolistical** [comment]
Then how about https://webpack.js.org/plugins/dll-plugin/

**Comment by ScriptedAlchemy** [comment]
It’s close. But not a exact hit. Unfortunately I’ll have to build this myself, then look at opening a PR to webpack if there’s anything that can be internalized. All the solutions still require passing context at build. I’m working on something where the client and client only has context of what resources are on the page. 

I don’t want to redeploy multiple apps because one installed something. They should be independent builds, on the client act as one. DLL still would make them incomplete builds unable to stand up on their own

**Comment by yoshi95** [comment]
@ScriptedAlchemy  how will this work with the current `universal` family?  especially on the SSR side, how will `flushChunks` know the latest chunk names to flush (i assume `clientStats` needs to be pull in every request from layout engine?)

i have hacked together something similar because i have different teams managing sitewide header stuff, vs page-specific stuff, and both teams wants independent releases

- a header app, with SSR flushed chunks to hydrate header components, with header/sitewide states 
- page-body apps, with page specific components/states to hydrate, 1 webpack build per page

SPA is achieved by
- when route changes, fetch html (no page reload, just browser fetch html response) from page-specific app, so it gets the lastest chunks for that app because of SSR, and hydrate takes over

issues ran into are
- double loading libs/frameworks increases initial js payload, so i decided header/sitewide app will expose libs/frameworks as externals, like
  - react, react-universal-component, etc
  - page specific app build will use them (so cant stand alone)
    - found out that `react-universal-component` cannot be shared because webpack cache is separate between the 2 builds
- if libs are shared, cant guaranteed things to work because 2 apps might depend on the same lib on different versions

**Comment by ScriptedAlchemy** [comment]
Okay. So I’ve actually been working on solving this whole problem and basically cracked most of it tonight. 

This is part of my wider project which will replace Most of my previous work. Respond framework, Rudy, Remixx. 

The primitive idea - get two builds loading bundles. This I cracked with scout file technology. But it’s just too simple and I want chunks, not entry points on the Frontend. However it’s a easy way to load another micro frontend without build context. 

Now for my new solution, it’s still rough & I’ll need to create a standalone counterpart which doesn’t lock users into respond. 

I made a Babel plugin which stencils out a function with __pending_chunk__. Then I wrote a webpack plugin that generates my own module IDs and replaced the pending chunk with the newly generated ID. 

In Respond we actually have ways to map the components and share it - but the standalone will need its own solution. 

So, this is the idea, I’ll hook into the splitChunks later and group some chunks together (or split everything) - webpack encapsulates it’s run time these days so Ive created my own miniature bootstrap mechanism. Which allows me to merge the internal _webpack_modules_ together, then patch the manifests back into each independent client side manifest. 

Because we hash and statically ask for modules, it comes down to splitting vendor chunks correctly. 

Simple concept: if the hash is the same, see if anyone loaded it on the page, otherwise go get it. If the hash isn’t the same, then you probably have two different versions of the same module. Therefore load each on its own. 

each build has its own deps, but I use the module cache from the Frontend manifest to check if it’s already there, well webpack actually does this for me. If it doesn’t have what it needs, it’ll get it’s own copy and supply it to anyone else who might need the lib. 

How will this work with universal? Same as always. It asks for something that’s either already there or it’ll go get it. Each SSR is still independent with its own libs needed to render. 

Chunk flushing: It’s still one of the best solutions and I think only(?) for instant TTI as it grabs alllll those webpack vendor bundles. 

However I really don’t like having to flush them. And I’m pretty sure that I’ll be able to just write a plugin that can self report. So rather than having to drag around a giant manifest, just have each file report it’s entry point. 

Code splitting and sharing is just a small aspect. I want to automate splitting altogether. Redux-first-router is getting a rewrite to Rudy, Remixx auto connects redux using hooks and is faster than react-redux. Because I’m injecting static stuff right into my own custom function, I am able to auto split stuff like reducers and component trees. End goal is non installing a component that hooks into your redux store with its own actions and reducers. You’d just use it like a normal React component though. 

It’s been hard and there’s plenty of skepticism around actually pulling it off - remember when code split SSR was impossible... till we went off and did it. 

Externals is a good way around the issue, but it still requires manual input and  maintenance . You could never load over the wire and hope to auto split unless you’re compiling that remote resource. 

When managing 100+ MFEs it’s hard to orchestrate. 

I’ve spent years building things to get around this issue, but it’s time to solve it once and for all. I can and will spin off the resource sharing once I’ve finalized some Remixx stuff. Sharing is actually one of the easier problems to tackle 

Follow me on twitter or something and we can keep In touch.

**Comment by ScriptedAlchemy** [comment]
So to sum it up. 

Modify splitChunks/plugin which does

Babel plugin to write some boilerplate if needed

Webpack plugin which hydrates stuff 

Some additional Babel magic to expose and unite as much of internal webpack as possible. 

Some utility functions and extra meta side loaded into the manifest (find by path, find by name, external require, import() an external url.

**Comment by yoshi95** [comment]
@ScriptedAlchemy thank you for the explanation and time.  

i drew a lil picture to help me digest what you have said, and have some remaining questions in the yellow box if you have some free time.

the picture is specific to MFE with `universal`, i understand that the vision is more generic.

![image](https://user-images.githubusercontent.com/1912743/55429989-bcc87600-5541-11e9-9460-6264a4919915.png)

**Comment by ScriptedAlchemy** [comment]
Ahhhh you’re leaning more towards LOSA architecture. 

So it will take another few weeks for Remixx to be built. 

But with universal, I’ve got a solution available. It’s by no means as awesome as what I’m working on, however it will work. 

I’ll need to setup a repo with two MFEs. I’ve already planned on introducing an article and webpack plugin on scout file technology (the most basic)

And another article on my initial FOSA architecture, a second revision will follow that offers a better code split capability.

**Comment by ScriptedAlchemy** [comment]
If anyone can help me improve this solution: https://github.com/ScriptedAlchemy/webpack-external-import

It allows me to interleave two bundles at runtime. Looking for feedback and collaborators, especially to solidify the solution

**Comment by yoshi95** [comment]
@ScriptedAlchemy thanks for the effort and keeping this going.

tested out locally using the demo run target and everything seems to work as advertised.

2 questions for prod build, in case this is not part of the scope for initial release just wanna get a sense on how it would work
- different vendor versions, this probably wont happen for major dependencies (like react), but might happen for small vendor dependencies (like lodash), cuz it s impossible to lock down every vendor version between teams.
  - app1,  depends on lodash@v1.x
  - app2, Title component depends on lodash@v2.x
  - app1 -> url import Title component from app2, the vendor lodash name will be the same as app1, but the component breaks at run time because it s using lodash@2.x specific function

- prod build dead code elimination
  - app1 depends externalFunc1 on Title from app2
  - app2 Title has 2 external functions, externalFunc1, and externalFunc2
  - app2 internally uses externalFunc2
  - prod build will remove externalFunc1 from Title.js? and breaks app1? or the new comment for /*external: SomeModule*/ will keep both?
  - how will this plugin impact webpack hash id generation (currently hash id is based on path + export usage within the package itself)

**Comment by ScriptedAlchemy** [comment]
Different vendor versions - needs thought. Im looking at dependency chain loading. The idea is vendor modules would be hashed (the ids) so if theres a missmatch on the version, the chunk loads its own vendor code. 

Dead code elementation. Considering a hack that would fake require the marked files / force them to be outputted. As you see right now, how i code-split the files is by having them literally code split within the application. So, technically they are required. 

As far as i know, manipulating the ID isnt a huge train smash as long as you dont conflict them.
I mean theres things like MD5 and moduleID plugins which alter the modules names. In my uses to this point, ive not had any problems. 

Ill the first to admit, there are gaps in the implementation. But my first use case is AB tests delivered over GTM. Now im able to deliver AB tests from a third party that actually use the VDOM and are not painted ontop. 

My biggest focus is to try and get dependency chain loading in place. So a chunk can load its own chunks if they are not found. The other thing im worried about and looking into is what happens when there's a collision. I think for the first iteration itll throw an error in the browser saying theres a collision with [name]. 

I'm not going to lie, this has been extremely hard and while my repo and its code isnt impressive - decyphering the problem has taken a long time. 

Im also aware of the kind of cumbersome naming needed. you have to give it a webpack chunk name, then you have to externalize it and give it a name (so i can require it by a nickname elsewhere) then you have to pull the module off you want. 

I'm also considering something like C interfaces. So you could name the externalized files somewhere centralized. 

```
//package.json

interface:{
'hello-world': '/src/components/HelloWorld.js'
}
```

This would prevent internal collisions. 

 Anyone interested, I'm more than willing to collaborate.


My trick for auto-splitting the modules out of webpack looks something like this. Though the naming is currently being used for splitting node-modules, you should get the idea. 

Doing something like this, might let me drop one level of naming. So externalize: [name] would be the chunk name as well.

``` apply(compiler) {
        const options = compiler?.options;
        const chunkSplitting = options?.optimization?.splitChunks?.cacheGroups || {}
        chunkSplitting.interleave = {
           // this needs to be passed in via options, not hard-coded
            test: /[\\/]src[\\/]/, 
            name(module, chunks, cacheGroupKey) {
                console.log('number of args', args.length)
                // get the name. E.g. node_modules/packageName/not/this/part.js
                // or node_modules/packageName
                const packageName = module.context.match(/[\\/]node_modules[\\/](.*?)([\\/]|$)/)[1];

                // npm package names are URL-safe, but some servers don't like @ symbols
                return `npm.${packageName.replace('@', '')}`;
            },
        };
        mergeDeep(options, {optimization: {splitChunks: {cacheGroups: chunkSplitting}}})
     ```

**Comment by yoshi95** [comment]
I am also concern about potentially worst case (unlikely to happen) that a big portion of dependencies mismatch due to versions/usage
- this will lead to a lot of scripts dynamically loaded in during bootstrap (h2 should make this better but don’t know the limit, especially on mobile network)

For AB testing above the fold showing a spinner on the phone for a couple seconds to bootstrap dependencies might not be ideal

Which leads to SSR some default version and supplement The experience with AB behavior on client side....worst case bootstrap time can delay time to interactive

**Comment by ScriptedAlchemy** [comment]
It’s a tough problem for sure. SSR will render the normal view for the time being, however I have found a way to use native import() even in IE, so I might apply this to SSR. There’s still some work that needs doing to solidify many of these concerns. If there’s a large miss match, then a less performant fallback isn’t a train smash in my opinion. I just need to figure out how to gracefully fallback. I might record dependency versions as part of the manifest and compare them to thenruntime versions. If the major version miss at he’s, then fallback and load in an alternative way, likely more wasteful. 

Your feedback is encouraging - this is a hard problem, but even a solution with some caveats opens the door to greater possibilities. I’m hoping I can get it to a point where it’s covering several scenarios. 

I’m considering a mechanism like how react universal component collects and flushed chunks. So I could reduce the amount of loading waves. 

I’m excited about driving AB tests through the VDOM, but I want to open this up to larger scale. 

I have a few ideas that might solve the problems mentioned. I’ll be working on this for the next 3 weeks, also during office hours so that goes a long way

**Comment by ScriptedAlchemy** [comment]
https://github.com/ScriptedAlchemy/webpack-external-import/pull/34 work in progress, eliminating the babel aspect

**Comment by ScriptedAlchemy** [comment]
Babel aspect eliminated, working on normalization of module.id so there’s no conflicts in finding shared dependencies in webpack manifest. 

Also about cracked origin dependency chain loading. So if a chunk needs a dependency that does not exist in the consumer build, it’ll load the file from an origin chunk

**Comment by ScriptedAlchemy** [comment]
To some it up @yoshi95 I’ve cracked the problem of multiple dependency versions. 

I found a project that converts module.id into a content hash of the code that module relates to. 

So if there’s a mismatch, in react versions - I can load the dependency chain. 

It also gets around problems like react = ‘../../node
_modules/react’ vs another build where react might be “../node_modules” 

This would mean they have different module ids and would cause a mismatch when interleaveing 

Module.ids for dependencies are now true hashes representing their content.

**Comment by ScriptedAlchemy** [comment]
![342C24B6-17C6-4C42-9950-E59E0AE629BD](https://user-images.githubusercontent.com/25274700/64926133-b99f0a80-d7ae-11e9-96f0-51f167205954.jpeg)

**Comment by ScriptedAlchemy** [comment]
Dependency chain loading now solved.
Module conflicts now solved

https://github.com/ScriptedAlchemy/webpack-external-import/pull/38

I still need to create a function to tie losing a chunk and it’s missing dependencies all in one go, but right now it could be done with two promises or a sync promise all. 

Getting close..

**Comment by ScriptedAlchemy** [comment]
Here we go!

https://github.com/ScriptedAlchemy/webpack-external-import/pull/38

**Comment by vonkanehoffen** [comment]
Just to add here in case it helps someone: If you're building an React MFA inside a monorepo managed with Yarn Workspaces and just need to code split packages inside that repo, it's possible to just do something in the unified app like:
```
import React, { Suspense, lazy } from "react";

const AppOne = lazy(() => import("@my-thing/AppOne"));
const AppTwo = lazy(() => import("@my-thing/AppTwo"));

function UnifedApp() {
  return (
    <div>
      <AppOne />
      <AppTwo />
    </div>
  );
}
```

Here I have `AppOne` and `AppTwo` bootstrapped with the CRA Typescript template and `"main": "dist/App.js",` in my their `package.json`s compiled with a plain `tsc` command.

The CRA Webpack config inside the unified app then takes care of the code-splitting like it would had I done a standard import within it's own package boundary. 

I'm aware this module federation project is dealing with a slightly different concern, where a sub package must be compiled with it's own webpack config first, but it took me ages to figure that out ;-) ...hope this saves someone that time!
