### ISSUE TITLE
More information provided in externals function

### ISSUE THREAD

**Issue by privatenumber** [webpack/webpack#8527]
## Feature request
More information in the [externals function](https://webpack.js.org/configuration/externals/#function) or the ability to determine which file is making the request (not just context).

**What is the expected behavior?**
To be able to determine the requesting file and the entry-point file of a request in the externals function.

**What is motivation or use case for adding/changing the behavior?**
In my particular situation, I'd like to know the entry-point that is making these requests. This is because the "external path" I provide via the callback is relative to the entry point (I am externalizing requests to peer entry points).

**How should this be implemented in your opinion?**
Since I think modifying the function signature would be a breaking change, I'd say invoke the externals function with a context that provides more information.
```
{
  //...
  externals: [
    function(context, request, callback) {
    	console.log(this.requestFilePath, this.entryPoint);
    }
  ]
};
```

**Are you willing to work on this yourself?**
yes

**Comment by sokra** [comment]
Using `this` doesn't work well with arrow functions. I think it makes sense to have a breaking change here and change the signature to `({ context, request }, callback) => {}` for the next next major.

**Comment by hirokiosame** [comment]
@sokra 

Is there a date in mind for the next major release?

If it's far off, I'd prefer to have it in `this` for the next minor, and then change the function signature & remove the `this` in the next major.

I think devs (including myself) usually use arrow functions when you don't need access to `this`.

**Comment by sokra** [comment]
Note that you can always copy `ExternalsPlugin` + `ExternalsModuleFactoryPlugin` into your application, modify it and use it directly when you need to feature now.

**Comment by hirokiosame** [comment]
Very cool! Thank you so much @sokra !
