### ISSUE TITLE
require.main.children is undefined in production mode

### ISSUE THREAD

**Issue by misterfresh** [webpack/webpack#8528]
# Bug report

**What is the current behavior?**
In dev mode, `console.log(require.main.children)` will output an array, and `require.main.children[1]` will be a string containing the path of the entrypoint.
I want to use `require.main.children[1]` to import some translations related to the specific entrypoint. 
It works fine in dev mode, but in production mode, `require.main.children` is `undefined`.

**If the current behavior is a bug, please provide the steps to reproduce.**

`console.log(require.main.children) ` will output an array in dev, but be `undefined` in production mode

**What is the expected behavior?**

`console.log(require.main.children)` should output an array containing the entrypoint
but in production mode it displays `undefined`.

**Other relevant information:**
webpack version:  4
Node.js version: 10
Operating System: ubuntu 18.04
Additional tools:

**Comment by sokra** [comment]
`module.children` is pretty expensive and usually not added to the bundle. It's only available when HMR is enabled and provided by this. Implement it in another way.

**Comment by misterfresh** [comment]
Thanks. What is the recommended way to have the entrypoint filename from within a module?

**Comment by sokra** [comment]
There is a ExtendedAPIPlugin which adds `__webpack_chunk_name__` which is the name of the entrypoint. You can try that.

**Comment by misterfresh** [comment]
Thanks. In the end I decided to explicitly pass the whole context `require.context('../../translations')` to a provideTranslations function called in the entrypoint, instead of trying to implicitly infer the correct translation folder from the entrypoint path.
