### ISSUE TITLE
devtool: inline-source-map broken due to TypeError

### ISSUE THREAD

**Issue by asprouse** [webpack/webpack#853]
56fb0fe6d955795ad86c086f15ef8187b26d241b seems to have broken `devtool: inline-source-map` since line 191 of `WebpackOptionsApply.js` is:

```
compiler.apply(new SourceMapDevToolPlugin(null, null, options.output.devtoolModuleFilenameTemplate, options.output.devtoolFallbackModuleFilenameTemplate)); 
```
Null is passed to the constructor of `SourceMapDevToolPlugin` and because of the new truthiness check it tries to get the filename property of null and causes the following error:

```
TypeError: Cannot read property 'filename' of null
```
For what it's worth `eval-source-map` still works just fine.

**Comment by jeffling** [comment]
I literally just found the same thing and came on to post it just to see you beat me by 20 minutes. Nice job :) This seems pretty critical to me.
