### ISSUE TITLE
[WASM] - experimental BigInt/I64 support

### ISSUE THREAD

**Issue by xtuc** [webpack/webpack#8531]
## Feature request

Allow WebAssembly i64 to be used in JavaScript; using the conversion to BigInt.

**What is the expected behavior?**

More info in https://github.com/WebAssembly/JS-BigInt-integration.

**What is motivation or use case for adding/changing the behavior?**

To move the proposal forward we need some toolchain support (https://github.com/WebAssembly/JS-BigInt-integration/issues/15), currently Webpack ensures that no I64 flows in JavaScript.

**How should this be implemented in your opinion?**

Behind a flag!

**Are you willing to work on this yourself?**
yes

**Comment by folex** [comment]
Hi! Thanks for all your work!

What's the status of this in wasm-pack? 

P.S. It seems to work for me in Chrome, but not in NodeJS

**Comment by folex** [comment]
> Are you willing to work on this yourself?
> yes
@xtuc had you had any chance to work on this?

**Comment by xtuc** [comment]
BigInt/I64 has now shipped in all major browser. I think we could just remove the webpack limitation now

**Comment by sokra** [comment]
The limitation has already been removed for `experiments.asyncWebAssembly`.
It's still in `experiments.syncWebAssembly`, but that's deprecated anyway.
