### ISSUE TITLE
webpack4.28.1 css modules not work

### ISSUE THREAD

**Issue by byte0** [webpack/webpack#8534]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

![image](https://user-images.githubusercontent.com/25864585/50337603-a8d9a500-054c-11e9-8b82-9f78e4a577f8.png)

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
