### ISSUE TITLE
Add "harmony" to "libraryTarget"

### ISSUE THREAD

**Issue by reggi** [webpack/webpack#8539]
I'd like to export using `commonjs2` or `commonjs-module` (not sure the difference) but with `export default` instead of `module.exports` within the bundle. Is this something that exists?

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
