### ISSUE TITLE
dllplugin error on ie9

### ISSUE THREAD

**Issue by Symboler** [webpack/webpack#8545]
when i use dllplugin to build some package,like react-dom,mobx-react(use es6 like Set),how to babel it?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
