### ISSUE TITLE
Webpack doesn't check for file again once it's not found

### ISSUE THREAD

**Issue by natew** [webpack/webpack#855]
Sorry, hard to describe this in the title. If I have a require for an absent file and save, Webpack will recompile with the not found error.

But, if I then go in and save a file that is in the right place, I have to restart Webpack before it will find that require, until then it still gives me:

```
Error: Cannot find module "..."
```

**Comment by sokra** [comment]
Which webpack version?

**Comment by natew** [comment]
I've noticed it since at least 1.3, using 1.7 now. I've tried newWatching and oldWatching. I run into it 5x a day or so lately and just accepted that restarting the webpack server was the solution.

Mac OSX 10.10.

**Comment by sokra** [comment]
I thought it may be relate to https://github.com/webpack/webpack/issues/668

**Comment by natew** [comment]
Yes. I thought there may be another. It still doesn't work for me in 1.7 though. I use dynamic route requires though maybe that is the cause?

**Comment by sokra** [comment]
Could you create a test case?

**Comment by natew** [comment]
I can reproduce it using `reapp`. If you do:

1. `sudo npm install -g reapp`
2. `reapp new testapp && cd testapp`
3  `reapp run` (runs webpack)

And then do the following:

1. In `./app/routes.js` change a `route('home')` to `route('home2')`
2. See the error
3. Move the `./app/components/Home.jsx` to `Home2.jsx`
4. Error still there
5. Restart webpack, error is gone

**Comment by bebraw** [comment]
@natew Can you see the issue still?

**Comment by natew** [comment]
We can close
