### ISSUE TITLE
Webpack's default doesn't work in IE

### ISSUE THREAD

**Issue by volokolamskspb** [webpack/webpack#8550]
# Bug report

Webpack generateds defaults which are reserved in IE11. Can't you replaces all the method.defaults with method["default"] ?? Default is reserved in IE, you can't use it as a property.

**What is the current behavior?**

Code generated by webpack gives errors at this line:

` var type = typeof rawScriptExports.default`

**If the current behavior is a bug, please provide the steps to reproduce.**

I'm using webpack vonfig to combine my .vue files in 1 bundle
webpack.config
```var path = require('path')
var webpack = require('webpack')
var merge = require('webpack-merge')
var baseWebpackConfig = require('./webpack.config')

var webpackConfig = merge(baseWebpackConfig, {
  target: 'node',
  entry: {
    app: './src/entry-server.js'
  },
  devtool: "none",
  output: {
    path: path.resolve(__dirname, './dist'),
    filename: 'server.bundle.js',
    libraryTarget: 'commonjs2'
  },
  externals: Object.keys(require('./package.json').dependencies),
  plugins: [
    new webpack.DefinePlugin({
      'process.env': 'production'
    })
    /* , new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      }
    }) */
  ]
})
module.exports = webpackConfig
```

**What is the expected behavior?**

Bundle generated by Webpack shouldn't have reserved variables.

**Other relevant information:**
webpack version:   "webpack": "^3.6.0",
Node.js version: v10.13.0
Operating System: Windows 7
Additional tools: Vue ssr, babel, webpack 
IE11

**Comment by evilebottnawi** [comment]
@volokolamskspb IE12?

**Comment by volokolamskspb** [comment]
Yes, IE

**Comment by evilebottnawi** [comment]
@volokolamskspb can you provide link on IE12?

**Comment by evilebottnawi** [comment]
@volokolamskspb please create minimum reproducible test repo, i think it is bug in plugin or loader, not in webpack

**Comment by sokra** [comment]
IE since 9 supports reserved words as properties. Maybe you using IE8 emulation mode?

**Comment by ljqx** [comment]
[Reserved words as property names support in browsers](http://kangax.github.io/compat-table/es5/#test-Object/array_literal_extensions_Reserved_words_as_property_names)

**Comment by volokolamskspb** [comment]
Yeah, I had IE7  on my Windows 7. Sorry, it's corporate standart. Told my boss that it works on IE10.
