### ISSUE TITLE
How to get webpack file correctly in django?

### ISSUE THREAD

**Issue by 1Sunn** [webpack/webpack#8556]
# Bug report

**What is the current behavior?**
I've made a webpack file(as `MainPage.js`) in output folder which I set up on `webpack.config.js` but, the page wasn't able to get webpack file(`MainPage.js`), it showed just error 404 (not found)

**If the current behavior is a bug, please provide the steps to reproduce.**

**Hierarchy of my folder**

```
Cebula4
    -  back
         - settings.py
         - manage.py
    -  front
         - webpack-stats.json
         - webpack.config.js
         - static
             - bundles
                  - MainPage.js (I checked that it was existed)
```

**Settings.py**

```
...

BASE_DIR = "C:\\Users\\1Sun\\Cebula4"

STATIC_URL = 'front/static/'
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'static'),
]

STATIC_ROOT=os.path.join(BASE_DIR,'staticfiles')

...

WEBPACK_LOADER = {
    'DEFAULT' : {
            'BUNDLE_DIR_NAME': 'bundles/',
            'STATS_FILE': os.path.join(BASE_DIR, 'front/webpack-stats.json'),

    }
}

...
```

**What is the expected behavior?**
The landing page is gonna be able to get `webpack file` well

**Other relevant information:**
webpack version:  ^4.17
Node.js version: v10.13.0
Operating System: Windows 
Additional tools: Django, react, babel, webpack

**Comment by evilebottnawi** [comment]
Better ask this question on stackoverflow or in cebula repo, it is bug tracker, not QA service, sorry
