### ISSUE TITLE
Webpack instances leaking?

### ISSUE THREAD

**Issue by KuNman** [webpack/webpack#8563]
# Bug report

**What is the current behavior?**
I create many objects of class which runs webpack inside nodejs app. I am passing to these objects other data, p.ex. ID. All created instances of webpack are returning 1st passed ID, instead of this which it took while creating it.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
export default class GeneratorService {
	constructor(order) {
		this.order = order;
	}

	generate() {
		this.webpack = new WebpackService(this.order).webpackRun();
	}

}
```

```
export default class WebpackService {
	constructor(order) {
		this.order = order;
	}

	webpackRun() {
		console.log('webpack start:'+this.order.ID);
//webpack start:PDF-360-3a55a180-054a-11e9-993d-b9b16b8777d3
//webpack start:PDF-360-3aae48d0-054a-11e9-993d-b9b16b8777d3
		webpack({
			target: 'node',
			mode: 'production',
			entry: [...],
			output: {...},
			resolve: {...},
			module: {...},
			plugins: [...],
		}, (err, stats) => {
			if (stats) {
				const info = stats.toJson();
				console.log('webpack finish: '+this.order.ID);
//webpack finish: PDF-360-3aae48d0-054a-11e9-993d-b9b16b8777d3
//webpack finish: PDF-360-3aae48d0-054a-11e9-993d-b9b16b8777d3			
                        }
		});
	}
}
```

**What is the expected behavior?**

Console.log in stats should return 2nd passed ID, but returns 1st.

**Other relevant information:**
webpack version:  4.2.6
Node.js version: 6.4.1
Operating System: macOS/Debian
Additional tools:

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

---

Looks unrelated to webpack
