### ISSUE TITLE
Webpack hangs

### ISSUE THREAD

**Issue by SebastianStehle** [webpack/webpack#8568]
# Bug report

**What is the current behavior?**

I have a bigger react application that builds totally fine under Windows, also the webpack dev server is working and tests all pass.

When I use the same config with docker it fails and hangs on the first file.

**If the current behavior is a bug, please provide the steps to reproduce.**

I eliminated everything from my application except the bare minimum to reproduce it: https://github.com/SebastianStehle/ts-bug

The webpack config:

    module.exports = {
        mode: "production",

        entry: "./app/app.tsx",

        module: {
            rules: [{
                test: /\.tsx?$/,
                loader: 'awesome-typescript-loader'
            }]
        }
    };

app.tsx:

    import * as React from "react";
    import * as ReactDOM from "react-dom";

    ReactDOM.render(
        <div />,
        document.getElementById("example")
    );

tsconfig.json:

    {
      "compilerOptions": {
        "jsx": "react",
        "moduleResolution": "node",
        "target": "es5"
      }
    }

The last log output I see is:

     10% building 0/1 modules 1 active ...cript-loader/dist/entry.js!/app/app.tsx

What is interesting:

* Using ts-loader does not change anything
* Renaming `index.tsx` to `index.ts` fixes the build error. (Of course I had to convert it to a valid ts-file and added the entry config)

Repository container dockerfile. Just run with `docker build .`

**What is the expected behavior?**

Should not hang

**Other relevant information:**
webpack version:  4.28.1
Node.js version: 10
Operating System: Docker/linux, Docker version 18.09.0, build 4d60db4, same behavior with 18.03.1-ce, build 9ee9f40
Additional tools:

**Comment by evilebottnawi** [comment]
@SebastianStehle how you run docker and what command in docker your use?

**Comment by evilebottnawi** [comment]
Please also provide docker version

**Comment by SebastianStehle** [comment]
Adde the docker version. The repository contains the Dockerfile, just run it with "docker build ."

**Comment by evilebottnawi** [comment]
@SebastianStehle Confirmed, let's see what is wrong and why it is happens

**Comment by sokra** [comment]
> * Renaming `index.tsx` to `index.ts` fixes the build error.

That's weird...

**Comment by evilebottnawi** [comment]
Looks like problem on `awesome-typescript-loader`

**Comment by evilebottnawi** [comment]
Hags on this call https://github.com/s-panferov/awesome-typescript-loader/blob/master/src/index.ts#L45

**Comment by SebastianStehle** [comment]
As I said, it also happens with ts-loader. I have added a second config and Dockerfile to use ts-loader

**Comment by evilebottnawi** [comment]
@SebastianStehle more deeply, hangs here https://github.com/s-panferov/awesome-typescript-loader/blob/master/src/instance.ts#L348

**Comment by SebastianStehle** [comment]
Thx, how do you debug it? This is a typescript function, explains why it also hangs with ts-loader.

**Comment by evilebottnawi** [comment]
@SebastianStehle I think related https://github.com/s-panferov/awesome-typescript-loader/issues/578, because you use `root` ts try to parse all directories of root (like `home`, `sbin`, `usr`, `lib` and etc) and parsing very very very slow, i am not familiar with ts very deep why it is happens, better ask this question in their repo.

Solution:
```
FROM node

RUN mkdir /home/build

COPY package.json /home/build

# Install Node packages 
RUN cd /home/build && npm install

COPY . /home/build/

RUN ls -l /home/build

# Build Frontend
RUN cd /home/build && npm run build
```

**Comment by evilebottnawi** [comment]
And all works fine

**Comment by SebastianStehle** [comment]
I just found a similar issue : https://github.com/Microsoft/TypeScript/issues/23607

And I solved it the same way :)

Thank you very much. This explains it, why it works in another project, where the frontend is placed in a subfolder.

**Comment by evilebottnawi** [comment]
@SebastianStehle Can we close issue?
