### ISSUE TITLE
Stitching Together Separate Webpack Project Builds

### ISSUE THREAD

**Issue by jstrimpel** [webpack/webpack#8574]
This is help question that I have been unable to get answered in any of the forums.

I am having difficulty accomplishing the following (and I am not sure if it is even valid use case for Wepack). 

## Goal
Load chunks built by separate Webpack project builds at runtime without a top level Webpack application build.

## Requirements
* Each project creates a main chunk and chunk for each dependency
* Chunks should be interchangeable between separate Webpack project builds
* Module and Chunk Ids should be deterministic across separate Webpack project builds
* Chunks should be able to be assembled by any web application and not require a top level Webpack application build

## Background
There are multiple teams building like projects for different web applications. Each project relies on some common shared dependencies and non-shared dependencies. There is **_not_** a top level Webpack application build that stitches these projects together. The usage of externals and globals is not desired. 

## Solution
Currently each project build generates chunks for each dependency, so that the project main only contains the project source. Each project dependency chunk should include its dependencies (this can be optimized later). I wrote a handful of Webpack plugins that normalize module and chunk ids to ensure that they are consistent across the separate builds. The Webpack runtime is a single  chunk. I am using the `optimization` and `entry` configurations to ensure that each dependency is a single chunk. This is working somewhat well, but I am coding by coincidence now as i tweak configurations and plugins. I do not understand Webpack internals and I do not know where to begin to solve this use case correctly. I do not think my current solution will scale.

**Comment by sokra** [comment]
webpack 5 will include deterministic chunk and module ids that should give you a high chance that chunks that include the same modules are identical. A high chance is not a guarantee, but it should work in pratice. There are some options which allow to increase the probability.

To make it work you follow these conditions:

Potential shared dependencies should have the same path relative to the `context` directory in webpack. This is true by default if you run webpack from the root of the project directory and dependencies are in `node_modules` which is also in the root. This makes sure that potential shared dependencies get the same module ids.

Config in each project should be similar enough to generate similar output. Best share a common webpack config between all projects, but this is optional.

Use `[contenthash]` in filename. Identical file will get the same filename. Not identical files will get different filenames.

Configure `optimization.splitChunks` in a way that create chunks per npm package, at least for the dependencies that are potential shared.

Deploy all output files from all project into the same output directory. This way identical files can be shared.

It's possible that different projects use a different version of a shared dependency. In this case module and chunk ids will be equal, but because the contenthash differs it won't use the same filename.

The deterministic ids algorithms only choose the same ids with a high chance. In case of id collisions they may choose a different id. You could increase the chance by increasing the id length, but check if it is necessary first.

This does not allow multiple projects on the same page! There is a chance that this will break, even if it works in 95%.

**Comment by jstrimpel** [comment]
@sokra Thank you so much for the detailed response. I really appreciate you taking the time to address my questions. 

### Follow Up Question
When you said "_This does not allow multiple projects on the same page!_", does this mean that chunks from separate Webpack projects cannot run on the same page together and use shared chunks interchangeably? In my small examples this is somewhat working, but if this not going to scale, which it sounds like it won't (my fear), then I will need to change directions rather quickly. My backup plan is `externals` and the `expose-loader`. Is that the best alternative?

### Response to Suggestions
It sounds like I am doing things as you suggested.  

The plugins I have written are doing a good job of creating deterministic module ids. Each project build generates a white list of module names and the plugins (`optimizeModuleIds`, `beforeModuleIds`) use this list to determine if the module id should be deterministic. I use (node) module name + version as the module id. In some cases, e.g., web components, I do not care about the version, I want the latest version to win always, so I only use the (node) module name. I am splitting on `?` for module ids that contain a hashed parameter and replacing it with a deterministic parameter - I use the path of the `module.resource` relative to its `main` (I know this is not a maintainable approach).

I am using the module name + version to create the file names. 

I am using `optimization.splitChunks` to create chunks per whitelisted module (I think :)).

All output files for each build are being written to the same directory path.

I have control over all project builds, to a certain degree, so it makes all of the above possible.

### Understanding Webpack Internals
Is there a learning path that you can suggest for better understanding Webpack internals? I have written numerous configs, scoured plugin source code, and written my own plugins and loaders, but I still don't understand Webpack enough to feel that I am making the correct design decisions for cases like this. 

Would it be possible to partner with someone from the Webpack team on fixing, implementing progressively challenging bugs and features? Are there are any other design docs or learning resources? 

I am very open to learning, so I don't mind taking on the tedious tasks that no one wants. :)

### Closing
Thanks again for your help.

**Comment by sokra** [comment]
> When you said "_This does not allow multiple projects on the same page!_", does this mean that chunks from separate Webpack projects cannot run on the same page together and use shared chunks interchangeably?

yes, that doesn't work. At least there is a chance that it don't work. Let me explain why:

Let's assume projectA uses depA@1 and projectB uses depA@2. depA@1 and depA@2 would get the same module ids and the chunk containing depA the same chunk id. Both projects are loaded into the page. Now projectA loads the chunk containing depA@1. This would also count as loading the depA@2 for projectB as they have the same module ids. projectB now runs with an incorrect version of depA that is potential incompatible. Usually it's recommended to use a different `output.jsonpFunction` to separate chunk loading from each other, but this would also prevent reuse of shared chunks.

The same could happen in case of id conflicts, which has more major impact as a totally different module is loaded.

---

If you need to have multiple projects on a page, there is an alternative approach which requires a bit more manual work.

You can build each shared library separately into a Dll bundle (DllPlugin), and reference these dll bundles with the DllReferencePlugin. Each of this dll bundles need to manually added to the HTML if needed by the projects on the page.

**Comment by jstrimpel** [comment]
Doesn't the following ensure that project bundles would reference the correct dependencies?

The module ids for depA@1 and depA@2 would be `depA_1` and `depA_2`. The projectA bundle would reference `depA_1`. The projectB bundle would reference `depA_2`. There would be separate bundles for `depA_1` and `depA_2`. Both would be loaded on the page in addition to the project bundles.

The case where only the module name is used as a module is very limited and very controlled, so version incompatibility is not concern. Occasional breakage is expected during development cycles.

**Comment by sokra** [comment]
> The module ids for depA@1 and depA@2 would be `depA_1` and `depA_2`.

The algorithms in webpack 5 doesn't use the package version in the module id. But assuming it would (or your custom algorithm do), full names are used as module ids (which would avoid hash conflicts) and the same config is applied, it should actually work.

In this case each of your projects should probably also has a unique prefix to avoid conflicts between similar named files in different project.

Another problem might be different lockfiles. They can make depA@1 and depA@1 in different projects to have different generated source code. In projectA depA@1 may depends on depB@1.0.0 and in projectB depA@1 depends on depB@1.0.1. Not sure if this can become a problem. I can't guarantee that it works fine. Maybe putting all projects in a monorepo with a single lockfile can avoid that.

**Comment by yoshi95** [comment]
hi @jstrimpel, wanna checkup on if you had success on this path? i am about to do the same and write some webpack plugins to unblock my teams to have independent deployments, and stitch the share chunks at runtime

**Comment by jstrimpel** [comment]
@yoshi95 We had to go down a more reliable path using a combination of the expose loader and externals configuration. We are still creating multiple bundles and re-assembling them at run time though.
