### ISSUE TITLE
splitChunks.name = false does not merge modules and generates more chunks

### ISSUE THREAD

**Issue by raulferras** [webpack/webpack#8582]
# Bug report
Playing with the option `splitChunks.name`, I've found that setting it to `false` generates more chunk files than if I specify a filename

Specifying a string to force a given filename, it outputs this:
![imagen](https://user-images.githubusercontent.com/1103977/50596250-dfe07c80-0ea3-11e9-925f-9436572926a2.png)

Setting it to `false`, I'm getting a totally different merging of chunks:
![imagen](https://user-images.githubusercontent.com/1103977/50596265-e7a02100-0ea3-11e9-914a-9bf4c99ac988.png)

Documentation is not very detailed in what exactly `false` value affects.

**What is the current behavior?**
Using this configuration:

```
module.exports = {
    entry: entries,
    output: {
        "filename": "[name].dist.js",
        "chunkFilename": "[id].dist.js",
        "path": "/xxxx",
        "publicPath": "http://localhost/js/"
    },
    mode: 'development',
    optimization: {
        splitChunks: {
            chunks: 'all',
            name: 'commons'
        }
    },
    resolve: {
        alias: aliases
    },
    plugins: [
        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery',
            'window.jQuery': 'jquery',
            'Translator': 'Translator'
        }),
        new BundleAnalyzer({
            analyzerMode: 'static'
        })
    ],
    devtool: 'source-map'
};
```
I get this [big chunk](https://user-images.githubusercontent.com/1103977/50596250-dfe07c80-0ea3-11e9-925f-9436572926a2.png) file containing all common modules used across the application.

When I change the value of `splitChunks.name` to false, I get this [output](https://user-images.githubusercontent.com/1103977/50596265-e7a02100-0ea3-11e9-914a-9bf4c99ac988.png).

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I guess I expect to have the same chunk file with the same modules inside it, instead of having them splitted in different chunks. According to documentation and other references found in issues, what I understood is that the name of the chunk would be simply a given ID, but what I see is a total different output.

**Other relevant information:**
webpack version:  4.28.2
Node.js version: 10.11.0
Operating System: OSX 10.13.6
Additional tools: -

**Comment by sokra** [comment]
Specifing `name` merges all common modules and vendors into a single chunk. This probably leads to more code downloaded than needed. Without `name` it splits them in chunks which contain only the code needed.

**Comment by raulferras** [comment]
Oh I understand.
This behaviour is not very well described in the Docs, I will open a PR on the docs repo:
From https://webpack.js.org/plugins/split-chunks-plugin/#splitchunks-name
```
The name of the split chunk. Providing true will automatically generate a name based on chunks and cache group key. Providing a string or function will allow you to use a custom name. If the name matches an entry point name, the entry point will be removed.
```

**Comment by pushkargupta9807** [comment]
_The name of the split chunk. Providing true will automatically generate a name based on chunks and cache group key. Providing a string or function will allow you to use a custom name. If the name matches an entry point name, the entry point will be removed._

@pherrymason  Can you please elaborate on this particular sentence:  "If the name matches an entry point name, the entry point will be removed."

i am trying to move a few modules to the main entry chunk and specifying the splitChunks.{cacheGroup}.name as "main" seems to do the trick. But the above sentence is somewhat confusing me.

**Comment by pherrymason** [comment]
Hello. Sorry I sincerely don't remember. Anyway, looks like _"If the name matches an entry point name, the entry point will be removed."_ is a quote from the link I pasted, so I cannot elaborate on the meaning as I'm not the author of that text.
