### ISSUE TITLE
Tree Shaking works differently with external (sideEffects false) and local code

### ISSUE THREAD

**Issue by gustavoschmidt** [webpack/webpack#8583]
# Bug report

**What is the current behavior?**
Tree Shaking does not eliminate imports from external libraries if they are not used (even when the library has the flag `sideEffects` set to false).

**If the current behavior is a bug, please provide the steps to reproduce.**
Following the example from the documentation, with a small difference:

```js
// math.js
import {values} from 'lodash-es';
export function square (x) { return x * x; }
export function cube (x) { return x * x * x; }
export function asdf (x) { return values({a: 1, b: 'asdf'}); }
```

```js
// index.js
import {cube} from './math.js';
export function cubecube (x) { return cube(cube(x)); }
```
Full code: https://github.com/gustavoschmidt/webpack-tree-shaking

One thing to notice is that if the function `asdf` is commented, the bundle size is reduced. This is inconsistent, since the function `asdf` is not used. Also, when this function depends on another local module, everything works as expected.

**What is the expected behavior?**
I expect a consistent behavior of local and external modules (when the flag `sideEffects` is set).

**Other relevant information:**
webpack version:  4.28.3
Node.js version: 8.15.0
Operating System: Linux
Additional tools: lodash-es

**Comment by sokra** [comment]
try https://github.com/vincentdchan/webpack-deep-scope-analysis-plugin

**Comment by gustavoschmidt** [comment]
Thanks @sokra! The plugin works perfectly.
Quick question: do you plan to add this to webpack?
