### ISSUE TITLE
Dynamically imported chunks don't get split properly with `webpackMode: eager`

### ISSUE THREAD

**Issue by jbasrai** [webpack/webpack#8585]
# Bug report

**What is the current behavior?**

Dynamically imported chunks with `webpackMode: eager` don't get split correctly.

**If the current behavior is a bug, please provide the steps to reproduce.**

I have a minimal example here: https://github.com/jbasrai/temp-webpack

Steps:
1. `yarn`
2. `cd loc`
3. `npx webpack-dev-server`
4. Open `localhost:8080`

**What is the expected behavior?**

The chunks get split out, but the app doesn't load. Removing `webpackMode: eager` from dynamic imports makes the app load, but the chunks don't get split out properly.

The reason for this setup is that I want to group dynamically loaded chunks by parent chunk to avoid multiple network requests. I do this in `splitChunksPlugin` because parent chunk data is not known before compilation. `webpackMode: eager` causes parent chunk info to be retained, but it seems that this comes with its own set of problems.

Example:
Chunk 1 contains Modules A, X.en, Y.en, X.ja, Y.ja

Modules X._ and Y._ are dynamically imported with something like:
```
import(/* webpackMode: 'eager' */ `./X.${loc}`)
```

Expected output after chunk splitting:
Chunk 1 contains Modules A
Chunk 1:en contains Modules X.en, Y.en
Chunk 1:ja contains Modules X.ja, Y.ja

This way, only 1 network request needs to be made to request the dynamically imported chunks.

`webpackChunkName` is NOT a working solution here because the chunk name can only be determined after compilation.

**Other relevant information:**
webpack version: v4.27
Node.js version: v8.12
Operating System: OSX v10.12
Additional tools:

**Comment by sokra** [comment]
eager means "don't put modules into new chunk". So that's probably not what you want. Even if you can separate it with a splitChunks configuration, the chunks will always load **eagerly**.

If you want to load only a single language at a time you must go with `lazy` mode which is the default.

---

On solution is to create a new module `apple+banana.en/fr.js` and reexport the both modules from it. This way you only have a single `import()` call which results in both modules are put together in a chunk.

---

Sadly the spec doesn't define a `import(["a", "b"])`, this would be a good option here.

**Comment by jbasrai** [comment]
Thanks for the explanation sokra. I found that a decent solution for us is to implement a naming convention for loc files and group chunks by locale:

```
	optimization: {
		splitChunks: {
			cacheGroups: {
				loc: {
					test: /\/\w+\.(\w+)\.json$/,
					name: (module, chunks) => {
						const match = /\/\w+\.(\w+)\.json$/.exec(module.resource);
						const language = match[1];

						return `loc-${language}`;
					},
					enforce: true,
					chunks: 'async',
				},
			},
		},
	},
```

The tradeoff is that we save a lot of network requests, but unused code is included in the payload.

**Comment by SorinGFS** [comment]
@sokra 

> eager means "don't put modules into new chunk".

Probably not the happiest choice for this `webpackMode` option. It confused me too, I would prefer something like `webpackMode: "include"` or `webpackMode: "exclude"` for the oposite.
