### ISSUE TITLE
Error: Cannot find module 'webpack/lib/removeAndDo'

### ISSUE THREAD

**Issue by rntvicente** [webpack/webpack#8586]
![image](https://user-images.githubusercontent.com/28707729/50619390-22c04580-0ee0-11e9-9c20-f058c130c63b.png)

**Other relevant information:**
webpack: **4.28.3**
webpack-cli: **3.1.2**
webpack-dev-server: **3.1.14**
React: **16.7.0**
Node.js version: **10.13.0**
Operating System: **Ubuntu 18.04.1 LTS**
Additional tools: **VSCode**

**Comment by sokra** [comment]
This doesn't exist anymore.

Maybe try to update extract-text-webpack-plugin, or better switch to mini-css-extract-plugin

**Comment by YangZhengXing0** [comment]
Error: Cannot find module 'webpack'，我也是遇到这个问题
![5wmq1nhqn xwdz u ld502c](https://user-images.githubusercontent.com/34296860/50740295-6cce6180-1227-11e9-94af-9d40175571f2.png)

**Comment by fenchu** [comment]
> This doesn't exist anymore.
> 
> Maybe try to update extract-text-webpack-plugin, or better switch to mini-css-extract-plugin
I've got into this problem when upgrading nodejs into a supported version, but this did not solve it
