### ISSUE TITLE
Better error message when resolveLoader alias not found

### ISSUE THREAD

**Issue by gitgrimbo** [webpack/webpack#8589]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

If I have some webpack config that wants to alias references to a "i18n" loader to another loader module...

```
resolveLoader: {
  alias: {
    "i18n": "amdi18n-loader-DELIBERATE-ERROR",
  },
},
```

and there is a mistake (e.g. typo) in the target module name (as above), then the error is

```
ERROR in ./webapp/modules/preview/harModel.js
Module not found: Error: Can't resolve 'i18n' in 'D:\dev\git_repos\harviewer\harviewer-react\webapp\modules\preview'
 @ ./webapp/modules/preview/harModel.js 8:0-365:2
 @ ./webapp/demo.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js whatwg-fetch ./webapp/demo.js
```

Although this error correctly tells me there is a problem with loading the "i18n" loader, I would like the error to tell me that the target module was not found (and maybe where webpack tried to find it).

The correct config is

```
resolveLoader: {
  alias: {
    "i18n": "amdi18n-loader",
  },
},
```

**If the current behavior is a bug, please provide the steps to reproduce.**

See above.

**What is the expected behavior?**

More detailed error message.

**If this is a feature request, what is motivation or use case for changing the behavior?**

More detailed error message.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

- Windows 10
- Node v11.3.0
-    "webpack": "^4.28.3",
-    "webpack-cli": "^3.2.0",
-    "webpack-dev-server": "^3.1.14"

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by gitgrimbo** [comment]
Done. Please reopen @evilebottnawi.

**Comment by evilebottnawi** [comment]
bump

**Comment by evilebottnawi** [comment]
bump

**Comment by vankop** [comment]
solved in latest webpack version
you will get stack trace like:
```
resolve 'i18n' in '<project path>'
  Parsed request is a module
  using description file: <project path>/package.json (relative path: ./src)
    aliased with mapping 'i18n': 'blabla1' to 'blabla1'
      Parsed request is a module
```
