### ISSUE TITLE
remove packages like core-js from the bundle

### ISSUE THREAD

**Issue by zsolt-dev** [webpack/webpack#8590]
## Feature request

My bundle is getting really big due to polyfills. Core-js in the bundle takes 58kB even if I use "useBuiltIns": "usage".

The problem is that many packages that I use include core.js polyfills. 

**What is the expected behavior?**

I would like to remove core.js package completelly from the bundle, so it will not be there even if some other libraries are using it. This was I would have a bundle without polyfills and would use polyfill.io so only old browsers would be polyfilled.

**What is motivation or use case for adding/changing the behavior?**

make bundle size smaller

**How should this be implemented in your opinion?**

I have no idea...

**Are you willing to work on this yourself?**
no, I am not that good with webpack

**Comment by evilebottnawi** [comment]
@zsolt-dev webpack don't include `core-js`, it is do `babel-loader`, you need setup `babel` to avoid `core-js`

**Comment by zsolt-dev** [comment]
@evilebottnawi it does not solve the problem that other packages from NPM are using it, that is why I want to remove it on the webpack level...

**Comment by ooflorent** [comment]
You can use `resolve.alias` to make the dependency empty but beware of runtime of runtime errors... I think the best option is to write a custom Babel plugin (or webpack) or codemod to remove the `require` statements.

**Comment by zsolt-dev** [comment]
@ooflorent Yes, webpack plugin sounds like a good idea. Is there someone having the skill and the time to write such a plugin?
