### ISSUE TITLE
Upgrade acorn in webpack v4.x

### ISSUE THREAD

**Issue by kiliancs** [webpack/webpack#8593]
I'm not sure if this would be acceptable. If it is, I can contribute a MR. It shouldn't be very different from https://github.com/webpack/webpack/pull/8125, I imagine.

The reasoning is that some valid JS is failing with "SyntaxError: Unexpected token" in acorn < 6:

```js
const example1 = (
  a


,
) => a;

const multiLineConst


 = {};
```

Now, indeed this is a weird syntax, but it is valid and more importantly it's the sort of output you get from perfectly normal TypeScript code through [sucrase](https://sucrase.io/). See https://github.com/alangpierce/sucrase/issues/391 for some more details.

**Comment by ooflorent** [comment]
Send a PR 👍

**Comment by sokra** [comment]
Maybe you can cherry-pick the acorn-upgrade from the next branch. Check if minimal node version is suitable.
