### ISSUE TITLE
"target" ignored when specified in custom angular builder

### ISSUE THREAD

**Issue by Roaders** [webpack/webpack#8594]
# Bug report

**What is the current behavior?**
When specifying `target="electron-renderer"` as part of a customsed Angular 7 build this is ignored and errors are thrown on `fs` or `path` imports

**If the current behavior is a bug, please provide the steps to reproduce.**
* checkout https://github.com/Roaders/angular-electron-chrome/tree/custom-webpack
* run `npm run build` to get errors
* run `npm run webpack` to run a working equivalent webpack build

**What is the expected behavior?**
It should resepct the `target="electron-renderer"` and successfully compile an application that import node functionality such as `fs` and `path`
I have verified that the config pass to webpack in both example builds has the same value for "target"

**Other relevant information:**
Angular CLI: 7.1.4
Node: 10.14.1
OS: win32 x64
Angular: 7.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.28.3

**Comment by evilebottnawi** [comment]
Sorry for delay, I think you should open an issue in `angular` repo, in webpack@5 we have `node` and `electron-renderer` globals, you can found list of them in `lib/node/NodeTargetPlugin.js` and `lib/electron/ElectronTargetPlugin.js` and you can use `fs` and `path` are exists, also I can't reproduce it using `webpack@5`, anyway feel free to feedback
