### ISSUE TITLE
concatenateModules causes "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by stevenvachon** [webpack/webpack#8605]
# Bug report

**What is the current behavior?**
```
ERROR in chunk app [entry]
app.js
Maximum call stack size exceeded
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I cannot narrow it down exactly, but the error presented itself when I finished refactoring a project of ~2000 modules from basic concatenation (Gulp) to a bundler (Webpack). Upon starting this refactor where there were far fewer ES modules, I was not experiencing the issue.

**What is the expected behavior?**
Bundle without error.

I was able to avoid the issue by disabling tree shaking (and anything else) via `concatenateModules: false`.

**Other relevant information:**
webpack version:  4.28.1
Node.js version: 10.14.2
Operating System: macOS 10.14.2 (hehe)
Additional tools: -

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.
