### ISSUE TITLE
NPM link local react hooks library reporting errors: Hooks can only be called inside the body of a function component.

### ISSUE THREAD

**Issue by mushan0x0** [webpack/webpack#8607]
# Bug report

This is a react hooks library [rc-form-hooks](https://github.com/mushan0x0/rc-form-hooks), which was [linked](https://github.com/mushan0x0/rc-form-hooks/blob/282ee4c2e792055e32295a219add5309b3b315d5/example/package.json#L26) in the example and will now report an error.
It looks like a compiled problem because I yarn installed it without errors

**What is the current behavior?**

Hooks can only be called inside the body of a function component.

![image](https://user-images.githubusercontent.com/29084441/50884403-c56b4d80-1425-11e9-849d-8641be17a7db.png)

![image](https://user-images.githubusercontent.com/29084441/50882690-90a8c780-1420-11e9-97e1-5c503f190458.png)

It should look like this:

![image](https://user-images.githubusercontent.com/29084441/50884279-69a0c480-1425-11e9-8efd-fd81b6c5821a.png)

![image](https://user-images.githubusercontent.com/29084441/50884233-3eb67080-1425-11e9-8972-b433edba1b94.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

1. `git clone https://github.com/mushan0x0/rc-form-hooks`
2. `cd rc-form-hooks`
3. `yarn && yarn start`
4. `cd example`
5. `yarn && yarn start`

**What is the expected behavior?**

no error

**Other relevant information:**
webpack version:  4.19.1
Node.js version:  10.6.0
Operating System:  mac os
Additional tools: react-scripts 2.1.3

**Comment by sokra** [comment]
Is there only a single `react` package in the bundle? Looks like you reference two react versions.

**Comment by mushan0x0** [comment]
All versions are 16.7.0-alpha.2

**Comment by sokra** [comment]
> All versions are 16.7.0-alpha.2

Yes, but this was not the question. react breaks when you include it twice (even if the version is equal). Make sure to only include a single react in the bundle. Try `resolve.alias: { react: require.resolve("react") }`.
