### ISSUE TITLE
NormalModuleReplacementPlugin doesn't handle external modules

### ISSUE THREAD

**Issue by o2genum** [webpack/webpack#8608]
# Bug report

**What is the current behavior?**
NormalModuleReplacementPlugin does not work for modules listed as 'externals'.

**If the current behavior is a bug, please provide the steps to reproduce.**
Somewhere in the sources:
```
import * as mymodule from 'mymodule'
```

Webpack config part:
```
  externals: [
    'mymodule-real',
    'mymodule-dummy'
  ],

  plugins: [
    new webpack.NormalModuleReplacementPlugin(/mymodule/, function(resource) {
      resource.request = USE_DUMMY ? 'mymodule-dummy' : 'mymodule-real';
    })
  ]
```

**What is the expected behavior?**
The expected behavor is that the plugin would handle external modules, too. Or it would emit some kind of error.

**Other relevant information:**
webpack version:  4.28.1
Node.js version: 10.11.0
Operating System: Windows 10
Additional tools: -

**Comment by sokra** [comment]
Yes it's the NormalModuleReplacementPlugin not the ExternalModuleReplacementPlugin.

You may want to do this:

``` js
  externals: (context, request, callback) => {
    if(/mymodule/.test(request) {
      return callback(null, USE_DUMMY ? 'mymodule-dummy' : 'mymodule-real'
    }
    callback();
  }
```

or this if you don't really need a regexp:

``` js
externals: {
  mymodule: USE_DUMMY ? 'mymodule-dummy' : 'mymodule-real'
}
```

**Comment by o2genum** [comment]
Thanks! I overlooked what `externals` section can do.

**Comment by evilebottnawi** [comment]
@o2genum Can we close issue?
