### ISSUE TITLE
Different transpilation/bundling behavior between ES6 and CJS modules

### ISSUE THREAD

**Issue by veltman** [webpack/webpack#8613]
# Bug report

[Note: unclear to me whether this issue comes from Webpack, Babel, or the combination of the two, @Timer suggested bringing this here]

**What is the current behavior?**

Bundling an ES6 module using the rest/spread syntax somewhere in the file works, but if the same file uses a CommonJS format instead, it throws a bundling error unrelated to the syntax.

**Steps to reproduce.**

1. Create a vanilla create-react-app app with react-scripts@2.1.2.

2. Create two files: `src/es6.js` and `src/cjs.js`.

```js
// es6.js
export default ({ foo, ...rest }) => true;

// cjs.js
module.exports = ({ foo, ...rest }) => true;
```

3. Run `npm start` or `yarn start`.

4. Import both of them into App.js, one at a time:

```js
import es6 from "./es6.js";
// then
import cjs from "./cjs.js";
```

A full repro is here: https://github.com/veltman/webpack-babel-bug-repro

**What is the expected behavior?**

Importing either file should bundle successfully. Instead, importing the ES6 module works, but importing the CJS version throws one of two errors during bundling, depending on whether it's the first attempt to build or a subsequent attempt:

```js
Attempted import error: './cjs.js' does not contain a default export (imported as 'cjs').

or

TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
```

This appears to be specific to the language features being used. If I replace the rest/spread with plain destructuring (`({ foo, bar }) => true`), both files work, they're transpiled and bundled without an error.

webpack version:  4.19.1
Node.js version: 10.13.0
Operating System: OS X
Additional tools: react-scripts

**Comment by veltman** [comment]
Also posted to https://github.com/babel/babel-loader/issues/757 and https://github.com/facebook/create-react-app/issues/6163

**Comment by agalatan** [comment]
I cloned your repo and ejected, and I just babel transpiled the cjs.js
1) When using spread, a mixture of ES6 + CJS happens, due to an import
```
[tw-mbp-agalatan webpack-babel-bug-repro (master)]$ NODE_ENV=development ./node_modules/.bin/babel ./src/cjs.js
import _objectWithoutProperties from "/Users/agalatan/workspace/webpack-babel-bug-repro/node_modules/@babel/runtime/helpers/esm/objectWithoutProperties";

module.exports = function (_ref) {
  var foo = _ref.foo,
      rest = _objectWithoutProperties(_ref, ["foo"]);

  return true;
};
```
2) When not spreading, things are simple and there's no need for imports:
```
module.exports = function (_ref) {
  var foo = _ref.foo,
      rest = _ref.rest;
  return true;
};
```

In the case of mixing ES6 + CJS, deciding what a default export should be could cause the issue.

Disabling minifcation for Webpack when building will should what a spaghetti is there (by disabling the //cjs(), so that it builds

But still, I can't see the precise thing causing it.

**Comment by sokra** [comment]
Babel adds polyfills as `import` which converts CJS modules into ESM in which `module.exports` is no longer valid.
