### ISSUE TITLE
Parameterize output.path with entry name?

### ISSUE THREAD

**Issue by JasonKleban** [webpack/webpack#8619]
Related to https://webpack.js.org/configuration/output/#output-path, is there a way to parameterize the path of the bundle AND all the related css, svg, etc, by entry point name?  Instead of index.html and some other html file, I want two index.html files in folders with their webpacked assets organized in those folders.  I can set output.filename with `[name]` in places but that pollutes the root with files.  If I try to use `[name]` in output.path, I get '[name] not implemented in this context`.  Is there another way?  If I only differentiate by filename (two peer .html files) everything works, but my links need to have .html instead of using default document conventions for shorter urls.

**Comment by sokra** [comment]
You can set `output.filename: "[name]/something.js"`

**Comment by JasonKleban** [comment]
@sokra - yes, but the only that .js file is put into the [name]'d folder - the  loaded css, svg, png and the HtmlWebpackPlugin-generated index.html files are all in the root.  If I include the _name_ as a literal portion of the `output.path`, it works, but obviously not for dealing with multiple entry points dynamically.

**Comment by JasonKleban** [comment]
related: https://github.com/jantimon/html-webpack-plugin/issues/218

**Comment by JasonKleban** [comment]
Ok makes sense.  Thanks.
