### ISSUE TITLE
Runtime error using Monaco editor and combining node_modules chunks

### ISSUE THREAD

**Issue by keaukraine** [webpack/webpack#8623]
# Bug report

I've set up a minimal example of monaco-editor with TypeScript and webpack 4.28.4. It has minimal code to set up 2 additional bundles for Monaco's web workers and `splitChunks` option to combine code from `node_modules` into separate chunk. Not the smallest code so I provide a link to repository instead of source code excerpts: https://github.com/keaukraine/monaco-webpack-typescript-test
Behavior of this example is inconsistent in `development` and `production` modes.

**What is the current behavior?**

In `development` mode, example builds and works in runtime.
In `production` mode, it builds successfully but fails in runtime with the following error:
```
TypeError: n.e is not a function
```

When `optimization: { minimize: false }` is added to test `webpack.config`, runtime error is:
```
TypeError: __webpack_require__.e is not a function
```

This makes me suspect that this issue is related to bug #8110 

**If the current behavior is a bug, please provide the steps to reproduce.**

Steps to reproduce:

1. Clone sample repository https://github.com/keaukraine/monaco-webpack-typescript-test/
2. run `npm install`
3. run `npm start`
4. In browser, open http://localhost:8080 (or another port shown in console).
5. Example will have working Monaco Editor, no errors in developer console.
6. Stop HTTP server.
5. Change mode to `production`  in `webpack.config.js` file. Optionally, add `optimization: { minimize: false }` config option.
6. Start server again with `npm start` command.
7. Refresh page at http://localhost:8080. Runtime errors can be observed. 

**What is the expected behavior?**

Expected behavior is for this example to run without runtime errors in both `development` and `production` modes.

**Other relevant information:**
webpack version:  4.28.4
Node.js version: 10.9.0
Operating System: Windows 10, Git bash.
Additional tools: None.

**Comment by sokra** [comment]
In webpack 4 with `target: "webworker"` `optimization.splitChunks.chunks: "all"` is not supported. It will be supported in webpack 5.

Switch to `chunks: "async"` at least for the webworker target.

If you need the vendor splitting, a workaround is to put the worker main code in a `import()`.
