### ISSUE TITLE
import() Run error after compiling on capitalize first character

### ISSUE THREAD

**Issue by gauseen** [webpack/webpack#8626]
# Bug report

```js
let testing01 = 'testing'
let testing02 = 'Testing'

// Ok
import('../pages/NotFound.vue')
// Ok
import('../pages/' + testing01  + '.vue')
// Run error after compiling on capitalize first character
import('../pages/' + testing02  + '.vue')
```

**What is the current behavior?**
Error in the first character uppercase dynamic import after compilation

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
// base vue cli 3.x cli

let testing01 = 'testing'
let testing02 = 'Testing'

// Ok
import('../pages/NotFound.vue')
// Ok
import('../pages/' + testing01  + '.vue')
// Run error after compiling
import('../pages/' + testing02  + '.vue')

// on chrome console
Uncaught TypeError: undefined is not a function
    at Array.map (<anonymous>)

```

**What is the expected behavior?**

**Other relevant information:**
webpack version: v4.28.4
Node.js version:  v10.13.0
Operating System:  window10
Additional tools:

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by gauseen** [comment]
```sh
git clone https://github.com/gauseen/import-bug
cd rootDir/
yarn install
yarn dev # No problem running in the browser


```

**Comment by mc-zone** [comment]
Looks like `__webpack_require__.e` doesn't packed into the bundle but be used in `webpackAsyncContext`.
