### ISSUE TITLE
Webpack changing .call(this) to .call(undefined) when packing RxJs

### ISSUE THREAD

**Issue by cgeorg** [webpack/webpack#863]
I'm using CycleJs, which uses RxJs.  The dist/rx.all.js looks like this:

```javascript
;(function(undefined) {...}.call(this));
```

Webpack is rewriting it as this:

```javascript
;(function(undefined) {...}).call(undefined);
```

Which causes "this" to be undefined when the function is executed, which makes stuff break because of "use strict"

**Comment by cgeorg** [comment]
For future readers, I was using babel-loader because my stuff is ES6.  It looks like that was the problem, because excluding node_modules made the issue go away.

```javascript
module.exports = {
  module:  {
    loaders: [
      {test: /\.js/, exclude: /node_modules/, loader: "babel-loader"}
    ]
  }
};
```

**Comment by libetl** [comment]
Many thanks... I wasted a lot of time before learning that.
