### ISSUE TITLE
Warning messages when installing webpack on Windows

### ISSUE THREAD

**Issue by David263** [webpack/webpack#8638]
# Bug report

**What is the current behavior?**

When I follow the installation instructions at https://webpack.js.org/guides/installation/, I get the following warning messages:

"C:\Web\git>npm install --save-dev webpack
npm WARN saveError ENOENT: no such file or directory, open 'C:\Web\git\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Web\git\package.json'
npm WARN git No description
npm WARN git No repository field.
npm WARN git No README data
npm WARN git No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.6 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.6: wanted {"os":"darwin","arch":"any"} (curr
ent: {"os":"win32","arch":"x64"})"

**If the current behavior is a bug, please provide the steps to reproduce.**

The steps are on your website (see above).

**What is the expected behavior?**

I expect no warning messages when installing a product according to instructions.

Note: I do not know if the installation was successful or not, as I'm not very familiar with npm or webpack.

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

Environment: Windows 10 Home, Command Prompt/Administrator, latest node.js (10.15.0). The npm version is 6.4.1.

**Comment by evilebottnawi** [comment]
You don't have `package.json`, please create `package.json` (you can run `npm init`)
