### ISSUE TITLE
Why I won't use webpack after all

### ISSUE THREAD

**Issue by David263** [webpack/webpack#8640]
I thought I'd give some feedback on why I am disappointed with webpack and will not use it.

The documentation implied that no config was needed and that webpack would combine all JS and CSS files into a single JS file and a single CSS file.

Disappointments always happen when there are expectations, and my expectation was that webpack would read my HTML files and parse all JavaScript <script> references and all CSS <link> references, then it would scan my project directories and locate all the referenced files and combine them, all very quickly.

I was disappointed that there is no HTML Loader in the list (https://github.com/webpack/docs/wiki/list-of-loaders), and that the project to add one seems to be stalled (https://github.com/webpack-contrib/html-loader/issues).

I guess webpack can still work for frameworks based on JavaScript, but I don't want to develop using them. I'd rather have static standard websites with some dynamic content than all dynamic websites.

Best wishes.

**Comment by TheLarkInn** [comment]
Hi David! I looks liike you are accessing our old documentation! Feel free and take a look at webpack.js.org/loaders which should show you the list of information you need! 

There are also great concepts and resources to learn how webpack works! (webpack.js.org/concepts).
