### ISSUE TITLE
Can CommonsChunkPlugin add `publicPath` support?

### ISSUE THREAD

**Issue by XuHanpeace** [webpack/webpack#8646]
webpack config:
```javascript
...lib_entries.map(
    ([key, value]) =>
      new CommonsChunkPlugin({
        name: `l-${key}`,
        filename: 'lib/[name].[chunkhash:6].js',
        chunks: [...project_names, ...vendor_names],
        minChunks: getLibSplitter(key, value)
      })
  )
```
html output:
```html
<script src="lib/l-redux.636d89.js"></script>
<script src="lib/l-reactRouter.0c7c32.js"></script>
```
expect:
```html
<script src="/publicPath/lib/l-redux.636d89.js"></script>
<script src="/publicPath/lib/l-reactRouter.0c7c32.js"></script>
```
as you can see, i need to translate the relative path to absolute path with **publicPath**

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
