### ISSUE TITLE
Json parameter includes console.log output

### ISSUE THREAD

**Issue by CyberAP** [webpack/webpack#8647]
# Bug report

**What is the current behavior?**
If you try watching webpack with profiler and json output then you'll get a corrupted json file, that includes webpack's console.log output.

**If the current behavior is a bug, please provide the steps to reproduce.**
Execute `webpack --watch --progress --profile --json > stats.json` and get this in your json file:

```
webpack is watching the files…
```

**What is the expected behavior?**
Json parameter should filter out console.log output from the json file.

I am using webpack 4 (can be reproduced on any version).

**Comment by evilebottnawi** [comment]
@CyberAP because `>` mean write all output in `stats.json`

**Comment by ooflorent** [comment]
@webpack-bot move to webpack/webpack-cli
