### ISSUE TITLE
DllReferencePlugin cannot consume exposed index.js correctly

### ISSUE THREAD

**Issue by creage** [webpack/webpack#8648]
# Bug report

**What is the current behavior?**
In ES6, having an index.js file in a folder lets you perform an import from the folder implicitly without specifying the index.js. 

**DllPlugin** correctly adds such files to **manifest.json**, but when you try to import such module consumed by **DllReferencePlugin** - it fails with error ```Cannot find module```. You have to append ```/index.js``` to the import statement explicitly to workaround this.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create simple Dll project, having a folder with some module in it, and  ```index.js``` within this folder, which should basically reexport the module
```
// example structure
//--MyModule
//  |_ MyModule.js
//  |_ index.js
```
```javascript
// index.js
export { default } from './MyModule';
```

2. Next, create another DllReference project, and try to consume the Dll from the step above
```javascript
// some Dll consumer code
import MyModule from 'Dll/MyModule'; // FAILS

import MyModule from 'Dll/MyModule/index'; // WORKS
```

**What is the expected behavior?**
**DllReferencePlugin** should be able to import such modules correctly if they exist in **manifest.json**

**Other relevant information:**
webpack version:  4.28.4
Node.js version: 11.6.0
Operating System: Windows 10

**Comment by creage** [comment]
@sokra I'm not sure I'm familiar enough with webpack internals for a PR, but after digging into code a bit, I found that this issue could have a workaround based on [this code](https://github.com/webpack/webpack/blob/6389e41e4c65bf32a916e6fffa5d65f66538d483/lib/DelegatedModuleFactoryPlugin.js#L53). Adding an ``extensions`` parameter to the **DllReferencePlugin** and defining a missing ``/index.js`` makes the module resolution work as expected

```javascript
new webpack.DllReferencePlugin({
    context: '.',
    scope: 'Wzc',
    manifest: path.resolve(DEST, '../../manifest.json'),
    extensions: ['.js', '/index.js']
})
```

I'm not sure if this approach is correct and good enough, otherwise appending of ``/index.js`` to the module path might fix the issue completely.

**Comment by creage** [comment]
@sokra would you accept the PR created by @mc-zone please?

**Comment by evilebottnawi** [comment]
bump

**Comment by alexander-akait** [comment]
Still valid

**Comment by alexander-akait** [comment]
@vankop Should we keep issues for dll? I think we can improve docs and mark it is legacy with recommendations to migrate on module federation

**Comment by vankop** [comment]
yeah. please migrate to module federatio. thanks.
