### ISSUE TITLE
Webpack plugins should be separate npm's

### ISSUE THREAD

**Issue by binarykitchen** [webpack/webpack#865]
So that they can be used in i.E. https://github.com/shama/gulp-webpack without adding `webpack` itself as a dependency.

**Comment by loganfsmyth** [comment]
Which plugin are you trying to use? I think they are all exposed, e.g.

    var gulpWebpack = require('gulp-webpack');
    var plugin = new gulpWebpack.webpack.DefinePlugin()

**Comment by bebraw** [comment]
@binarykitchen Is this relevant still?

**Comment by binarykitchen** [comment]
nope
