### ISSUE TITLE
Webpack with tsloader said TypeError: Class constructor  cannot be invoked without 'new'`

### ISSUE THREAD

**Issue by iamwwc** [webpack/webpack#8658]
# Bug report
I want to build my docker image but I don't want put `node_modules` in image, So I bundle all codes use webpack then delete `node_modules`

Plugins will have default export, which maybe ES6 Class or function, So I follow `https://stackoverflow.com/a/30760236/7529562` to check export is class or normal function,

```js
function isClass(v) {
  return typeof v === 'function' && /^\s*class\s+/.test(v.toString());
}
```

When I run `node index.js`, It's works

But after I bundle all codes into bundle.js, run with `node bundle.js`

It said 

`TypeError: Class constructor  cannot be invoked
without 'new'`

**What is the current behavior?**

Throw `TypeError: Class constructor  cannot be invoked
without 'new'`

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/iamwwc/webpack-isClass-report

Clone this repo and follow readme file

**What is the expected behavior?**

It should run without exception `TypeError: Class constructor  cannot be invoked
without 'new'`

**Other relevant information:**
webpack version:  4.25.0(global) /// ^4.29.0 (local)
Node.js version: v10.13.0
Operating System: Windows 10 pro 1809
Additional tools: typescript

**Comment by sokra** [comment]
TypeScript transpiles the `class`. `/^\s*class\s+/.test(v.toString())` do not handle transpiled classes.

**Comment by iamwwc** [comment]
> TypeScript transpiles the `class`. `/^\s*class\s+/.test(v.toString())` do not handle transpiled classes.

I don't know what that mean. my ts target is "es6", Typescript don't translate ES6 class..

Could you give me more detail?

**Comment by iamwwc** [comment]
> TypeScript transpiles the `class`. `/^\s*class\s+/.test(v.toString())` do not handle transpiled classes.

The focus is when I run use `node ./dist/index.js`, It works well, but If I run bundles codes used webpack

```
node bundle.js
```

It will throw above exception.

I don't know why..
