### ISSUE TITLE
Ability to predefine charset attribute for dynamically imported scripts

### ISSUE THREAD

**Issue by aberezkin** [webpack/webpack#8659]
## Feature request

It would be very useful to have an ability to choose file encoding for dynamically imported scripts, since some users (including myself) can use something other than 'utf-8' in their scripts.

**What is the expected behavior?**

I think an option in configuration would be perfectly fine. Something like this in `webpack.config.js` should work:

```
module.exports = {
...
  dynamicScripts: {
    encoding: 'maccyrillic',
  },
...
};
```

**What is motivation or use case for adding/changing the behavior?**

There's plenty of web pages in the internet that for some reason (mostly legacy code) use encoding different from UTF-8. I'm want to utilize webpack and deferred code loading on site with legacy cyrillic encoding that but I can't because UTF-8 charset for dynamic scripts seems to be hardcoded in webpack core. 

https://github.com/webpack/webpack/blob/master/lib/web/JsonpMainTemplatePlugin.js#L155

**How should this be implemented in your opinion?**

An option in webpack config that then should be used when injecting `<script>` tags with `import()`.

**Are you willing to work on this yourself?**
yes

**Comment by ooflorent** [comment]
The code block you highlighted is designed to work on webpack emitted assets. These assets are always output as utf-8 files. webpack cannot `import` external scripts. The `import()` expressions are used to load dynamic generated chunks.

**Comment by aberezkin** [comment]
Yes, webpack by default can't emit non utf-8 files but it supports plugins that can. For example `webpack-encoding-plugin`, I use it to change encoding of emmited files.  It seem that currently there's no ability to change that behaviour outside webpack's source code since this is just hardcoded.

**Comment by PTCNelsonSilva** [comment]
We should at least have the ability to remove the attribute on the generated <script> tags since its considered obsolete and causes HTML validation tests to fail.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#Deprecated_attributes

**Comment by irudoy** [comment]
@PTCNelsonSilva can you open an issue for that?

**Comment by aberezkin** [comment]
bmp

**Comment by UNDERCOVERj** [comment]
how to add attribute to dynamically imported scripts, for example : crossOrigin = 'annoynous'

**Comment by irudoy** [comment]
@UNDERCOVERj `config.output.crossOriginLoading = 'anonymous'`
