### ISSUE TITLE
error  'webpack-merge' should be listed in the project's dependencies. Run 'npm i -S webpack-merge' to add it  import/no-extraneous-dependencie

### ISSUE THREAD

**Issue by chandu89** [webpack/webpack#8663]
When I am adding Webpack merge, I am getting error.
I have  created separate webpack config for devlopment and prod.
> error  'webpack-merge' should be listed in the project's dependencies. Run 'npm i -S webpack-merge' to add it  import/no-extraneous-dependencies

Facing Above issue. And this('npm i -S webpack-merge') is not helpful. I have tried to change the rules in .eslintrc with devdependencies: true but its working for me.

**Comment by ooflorent** [comment]
It looks like you just deleted our [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template.

---

This error is raised by `eslint-plugin-import` (not webpack). You should submit this issue on their repository.

**Comment by Fried-Chicken** [comment]
You can add a glob to your eslint config file to fix this issue.

```
{
   "rules":{
      "import/no-extraneous-dependencies":[
         "error",
         {
            "devDependencies":[
               "**/webpack.*.js"
            ]
         }
      ]
   }
}
```
