### ISSUE TITLE
Unclear about the splitChunks

### ISSUE THREAD

**Issue by kwzm** [webpack/webpack#8671]
I find a problem, when my entry chunk and other chunk which is dynamic imported by entry have a common module, the splitChunks can't split a common chunk.

1. This is my entry chunk and I import the jquery.js which is bigger than minSize.
![3](https://user-images.githubusercontent.com/16114101/51585950-53f7c880-1f16-11e9-8b03-acf8fe7c2670.PNG)

2. Page1.js is my other chunk which is dynamic imported by entry chunk and it imports jquery.js too.
![2](https://user-images.githubusercontent.com/16114101/51586007-8275a380-1f16-11e9-8084-3d9b706a14dc.PNG)

3. I use the defalut splitChunks config, I wish the jquery.js will be split as a common chunk which name likes `default~page1~main.[chunkhash].js`, but it not, the jquery.js is packaged into the main chunk and the page1 chunk doesn't has jquery.js.
![default](https://user-images.githubusercontent.com/16114101/51586253-70e0cb80-1f17-11e9-9250-09e966f8d8bb.PNG)

I don't understand why.

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
