### ISSUE TITLE
Improve "there is another module with an equal name" error

### ISSUE THREAD

**Issue by Pomax** [webpack/webpack#8672]
# Bug report

https://github.com/webpack/webpack/issues/2815 got closed, even though there is a solid solution that shouldn't take someone familiar with the webpack codebase to implement. As per bot instructions, I am filing a new issue to make sure this still receives a fix _to the error message webpack generates_ (it is absolutely not expected that webpack itself gets a fix that solves a problem caused by Node itself)

It is possible to run into a problem where code requires two packages with the same name if case is ignored, such as `require('Buffer')` and `require('buffer')`, and webpack currently does not inform the user _what_ is causing the problem, just _that_ something is causing a problem

**What is the current behavior?**

Webpack generates an error that does not contain enough information to find and solve the problem flagged:

```
WARNING in ./somedir/somefile.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
```

**What is the expected behavior?**

Webpack should generate an error that contains all the information necessary for a developer to pinpoint and fix the problem immediately:

```
WARNING in ./somedir/somefile.js
The import of 'buffer' conflicts with an earlier import of 'Buffer' when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
```

**Comment by sokra** [comment]
Which version of webpack are you using?

The latest version also prints the modules and an example where they are used.

**Comment by Pomax** [comment]
Hm, package.json says 4.29.0, and you're right: I'm no longer seeing that error but the much more informative one if I now try to intentionally beak things. Sorry for the bother.
