### ISSUE TITLE
webpack vs. npm link - import fails when linked package's PARENT folder contains a package.json

### ISSUE THREAD

**Issue by fabb** [webpack/webpack#8673]
# Bug report

I have a next.js project where I `npm link` a dependency for development iteration speedup. The dependency only has `peerDependencies` but no `dependencies` or `devDependencies` in the build output folder. The project structure looks like this:

My project structures look like this:

Library Project:

* myLib/
    * package.json - the package file that contains all the dev dependencies needed to build the project, build output will be put into package/lib/
    * src/ - source files
    * package/
        * package.json - this is the package file that gets published, it just contains peerDependencies and the package name `@myorg/myLib`, and `"main": "lib/index.js"`
        * lib/ - contains the built code
            * index.js - the built code
            * more folders that contain files that are required by index.js

Client Project:

* myClient/ - next.js 7.0.2 based client project
    * package.json - contains the dependency on myLib
    * src/ - source files etc.
         * someSourceFile.js - contains an import of a named export, like `import {SomeComponent} from '@myorg/myLib'`
    * other folders

The client project compiles fine when `myLib` is added as a regular dependency in `myClient/package.json`.

Then for development I link myLib to myClient project like this:

* `cd /path/to/myLib`
* `npm run build` - builds the client project and puts the result in `myLib/package/lib`
* `cd package`
* `npm link`
* `cd /path/to/myClient`
* `npm link @myorg/myLib`

Now compiling the client project should still compile fine, but it doesn't.

**What is the current behavior?**

I get the following compile error:
`"export 'SomeComponent' was not found in '@myorg/myLib'`

Doing a console.log, I found out that the import actually does not import the `myLib/package/lib/index.js` content, but instead the `myLib/package/package.json` content 😱. This really is weird and looks like a bug.

Now even weirder: When I delete `myLib/package.json` (NOT the one in `myLib/package/package.json`), suddenly the client project builds fine! It's weird, as the link points to `/path/to/myLib/package` and not `/path/to/myLib`, and therefore the package.json in the parent folder should not modify anything. I can even replace the whole content of `myLib/package.json` with `{}` and it will still fail the build, just deleting the file resolves the problem.

**If the current behavior is a bug, please provide the steps to reproduce.**

I'll create a test project demonstrating the bug, but I need a few days for that.

**What is the expected behavior?**

The presence of `myLib/package.json` should not make a difference on whether the import works or not. `npm link` of a package that has just `peerDependencies` but no `dependencies` or `devDependencies` should work the same as regularly installing that package.

**Other relevant information:**
webpack version:  4.20.2 (dependency of the current stable next.js version)
Node.js version: 10.14.0
Operating System: macOS Mojave
Additional tools: next.js 7.0.2

**Comment by sokra** [comment]
> I'll create a test project demonstrating the bug, but I need a few days for that.

Yeah, I need that.

**Comment by fabb** [comment]
Here's the example project: https://github.com/fabb/linkwebpackbug

Note that I changed it from a next.js app to a CRA app - the bug appears with both, but with the latter the issue is more visible for demonstration purposes.
