### ISSUE TITLE
Hoe do I pass `-p` flag into webpack process via Node API?

### ISSUE THREAD

**Issue by pavelpichrt** [webpack/webpack#8674]
Webpack: 4.28.4
NodeJS: 10

I tried to set `mode: "production"` in the webpack config itself (doesn't work), `NODE_ENV=production` (doesn't work), also tried to set both `mode: 'prod'` and `mode: 'production'` to `compiler.watch` (doesn't work).

Thanks a lot

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
