### ISSUE TITLE
Split chunk fails to load with undefined hash

### ISSUE THREAD

**Issue by maclockard** [webpack/webpack#8677]
# Bug report

**What is the current behavior?**

Certain chunk requests use `undefined` instead of the hash. Example of the resulting error in chrome:

```
Uncaught (in promise) Error: Loading chunk 63 failed.
(error: https://{hostname}/app/63.undefined.feasContentHashV1.chunk.js)
    at HTMLScriptElement.i ({appName}.d5b0c78176fe6ff82a0f.bundle.js:1)
```

The request for chunk 63 looks like this:

```
https://{hostname}/app/63.undefined.chunk.js
```

Stepping through the webpack build, it appears as though the function `getScriptSrcPath` in `JsonpMainTemplatePlugin.js` ([link](https://github.com/webpack/webpack/blob/a0eab48f3799f5d3528b0c0c3a0e48161a43933c/lib/web/JsonpMainTemplatePlugin.js#L47)) creates a mapping of chunk Id to hash. Looking at the result, the entry for the chunk Id 63 is missing entirely, resulting in the `undefined` hash in the request.

However, looking through the resulting build, there appears to be a valid chunk 63 with a valid hash in the file name. I'm guessing that somewhere along the line, the reference is lost to this chunk?

**If the current behavior is a bug, please provide the steps to reproduce.**

This is somewhat difficult to reproduce, I think its related to the total number of async chunks made by `splitChunksPlugin`, but I'm not 100% sure. I'm unable to reproduce a build that can do this. please let me now what other information would be useful.

I think this may be related to https://github.com/webpack/webpack/issues/7061 since the behavior sounds similar. However, according to the maintainers that bug was fixed in 4.6.0. Since we are at a later version (4.29.0) I would expect that fix to be included.

**What is the expected behavior?**

I would expect `JsonpMainTemplatePlugin` to produce code that has a valid mapping of all chunk Id's to their respective hashes, and for all requests for chunks to have defined hashes.

**Other relevant information:**
webpack version:  4.29.0 (I also tried linking to a develop build of webpack)
Node.js version: v8.11.1
Operating System: MacOS
Additional tools:

**Comment by sokra** [comment]
Does this occur for a full build, watch build or with HMR?

**Comment by evilebottnawi** [comment]
@maclockard Can you create minimum reproducible test repo?

**Comment by maclockard** [comment]
This happens for both a full build and watch. However, it only happens when I set NODE_ENV=production.

I spent a bit longer stepping through the webpack build, and it seems as though chunk 63 doesn’t have the requesting chunk listed as a parent. It also only seems to happen when I have 2 or more entry points.

I don’t think I can make a minimally reproducible example since the application I encounter this with is very very large and has many dynamic imports. The total number of chunks we end up with is nearly a 100. If we lower how much it chunks, we no longer encounter this problem.

**Comment by wangrenyn** [comment]
---------- Továbbított üzenet ---------

**Comment by maclockard** [comment]
any thoughts of potentially problematic steps of the compilation? I can try to step through and see whats going wrong

**Comment by evilebottnawi** [comment]
@maclockard no, it is hard to debug without minimum reproducible test repo

**Comment by evilebottnawi** [comment]
@maclockard there are a lot of places in code where something wrong, or create minimum reproducible test repo as i written above, or start to debug line to line in you build

**Comment by maclockard** [comment]
@evilebottnawi @sokra what ended up being the solution to https://github.com/webpack/webpack/issues/7061 ? seems like it may be the best place to start debugging so I can verify if its the same issue or not

**Comment by evilebottnawi** [comment]
@maclockard issue not related to your problem, no solution, it was bug

**Comment by fleck** [comment]
I've noticed this bug also but didn't have the time to dig into it and ended up just doing without a dynamic import.

here's our webpack config:

```

**Comment by vuchan** [comment]
> @maclockard issue not related to your problem, no solution, it was bug

Does anyone fix it? Is it a bug really?

**Comment by maclockard** [comment]
@vuchan I ended up changing around the order of our dynamic imports and the issue went away. Which kinda sucks since it means this issue is very very build dependent.

Unsure if its been fixed in newer versions of webpack since you can't really directly test it, only way would be going back to that commit and bump webpack's version. I don't have access to the repo I was running into this with, so I can't check.

**Comment by evilebottnawi** [comment]
I close issue, unfortunately we did not receive a demonstration repo with problem, it doesn’t mean that we ignore you, perhaps the problem is related to a configuration or something external. In any case, if you encounter this problem, do not hesitate to open an issue again and try to provide minimum reproducible test repo. Thanks for using webpack!

**Comment by cdll** [comment]
i 've got same issue here with ``@vue/cli-service`` bundler.
here 's part of my ``package-lock.json`` file:
<details>
  <summary>package-lock.json
  </summary>

    "@vue/cli-service": {
      "version": "4.1.2",
      "resolved": "https://registry.npmjs.org/@vue/cli-service/-/cli-service-4.1.2.tgz",
      "integrity": "sha512-ljJ3qoR5NNHuG0HPqQyfO3xa4Ti5zCSmHp0tDYxgiVz1vMDvzPXBhGBGsc2Y1HH71BUyx3Ei+H7mWdML/+Bm9Q==",
      "dev": true,
      "requires": {
        "@intervolga/optimize-cssnano-plugin": "^1.0.5",
        "@soda/friendly-errors-webpack-plugin": "^1.7.1",
        "@vue/cli-overlay": "^4.1.2",
        "@vue/cli-plugin-router": "^4.1.2",
        "@vue/cli-plugin-vuex": "^4.1.2",
        "@vue/cli-shared-utils": "^4.1.2",
        "@vue/component-compiler-utils": "^3.0.2",
        "@vue/preload-webpack-plugin": "^1.1.0",
        "@vue/web-component-wrapper": "^1.2.0",
        "acorn": "^6.1.1",
        "acorn-walk": "^6.1.1",
        "address": "^1.1.2",
        "autoprefixer": "^9.7.2",
        "browserslist": "^4.7.3",
        "cache-loader": "^4.1.0",
        "case-sensitive-paths-webpack-plugin": "^2.2.0",
        "cli-highlight": "^2.1.4",
        "clipboardy": "^2.0.0",
        "cliui": "^5.0.0",
        "copy-webpack-plugin": "^5.0.5",
        "css-loader": "^3.1.0",
        "cssnano": "^4.1.10",
        "current-script-polyfill": "^1.0.0",
        "debug": "^4.1.1",
        "default-gateway": "^5.0.5",
        "dotenv": "^8.2.0",
        "dotenv-expand": "^5.1.0",
        "file-loader": "^4.2.0",
        "fs-extra": "^7.0.1",
        "globby": "^9.2.0",
        "hash-sum": "^1.0.2",
        "html-webpack-plugin": "^3.2.0",
        "launch-editor-middleware": "^2.2.1",
        "lodash.defaultsdeep": "^4.6.1",
        "lodash.mapvalues": "^4.6.0",
        "lodash.transform": "^4.6.0",
        "mini-css-extract-plugin": "^0.8.0",
        "minimist": "^1.2.0",
        "portfinder": "^1.0.25",
        "postcss-loader": "^3.0.0",
        "read-pkg": "^5.1.1",
        "ssri": "^7.1.0",
        "terser-webpack-plugin": "^2.2.1",
        "thread-loader": "^2.1.3",
        "url-loader": "^2.2.0",
        "vue-loader": "^15.7.2",
        "vue-style-loader": "^4.1.0",
        "webpack": "^4.0.0",
        "webpack-bundle-analyzer": "^3.6.0",
        "webpack-chain": "^6.0.0",
        "webpack-dev-server": "^3.9.0",
        "webpack-merge": "^4.2.2"
      },
      "dependencies": {
        "acorn": {
          "version": "6.4.0",
          "resolved": "https://registry.npmjs.org/acorn/-/acorn-6.4.0.tgz",
          "integrity": "sha512-gac8OEcQ2Li1dxIEWGZzsp2BitJxwkwcOm0zHAJLcPJaVvm58FRnk6RkuLRpU1EujipU2ZFODv2P9DLMfnV8mw==",
          "dev": true
        },
        "cacache": {
          "version": "13.0.1",
          "resolved": "https://registry.npmjs.org/cacache/-/cacache-13.0.1.tgz",
          "integrity": "sha512-5ZvAxd05HDDU+y9BVvcqYu2LLXmPnQ0hW62h32g4xBTgL/MppR4/04NHfj/ycM2y6lmTnbw6HVi+1eN0Psba6w==",
          "dev": true,
          "requires": {
            "chownr": "^1.1.2",
            "figgy-pudding": "^3.5.1",
            "fs-minipass": "^2.0.0",
            "glob": "^7.1.4",
            "graceful-fs": "^4.2.2",
            "infer-owner": "^1.0.4",
            "lru-cache": "^5.1.1",
            "minipass": "^3.0.0",
            "minipass-collect": "^1.0.2",
            "minipass-flush": "^1.0.5",
            "minipass-pipeline": "^1.2.2",
            "mkdirp": "^0.5.1",
            "move-concurrently": "^1.0.1",
            "p-map": "^3.0.0",
            "promise-inflight": "^1.0.1",
            "rimraf": "^2.7.1",
            "ssri": "^7.0.0",
            "unique-filename": "^1.1.1"
          }
        },
        "debug": {
          "version": "4.1.1",
          "resolved": "https://registry.npmjs.org/debug/-/debug-4.1.1.tgz",
          "integrity": "sha512-pYAIzeRo8J6KPEaJ0VWOh5Pzkbw/RetuzehGM7QRRX5he4fPHx2rdKMB256ehJCkX+XRQm16eZLqLNS8RSZXZw==",
          "dev": true,
          "requires": {
            "ms": "^2.1.1"
          }
        },
        "find-cache-dir": {
          "version": "3.2.0",
          "resolved": "https://registry.npmjs.org/find-cache-dir/-/find-cache-dir-3.2.0.tgz",
          "integrity": "sha512-1JKclkYYsf1q9WIJKLZa9S9muC+08RIjzAlLrK4QcYLJMS6mk9yombQ9qf+zJ7H9LS800k0s44L4sDq9VYzqyg==",
          "dev": true,
          "requires": {
            "commondir": "^1.0.1",
            "make-dir": "^3.0.0",
            "pkg-dir": "^4.1.0"
          }
        },
        "find-up": {
          "version": "4.1.0",
          "resolved": "https://registry.npmjs.org/find-up/-/find-up-4.1.0.tgz",
          "integrity": "sha512-PpOwAdQ/YlXQ2vj8a3h8IipDuYRi3wceVQQGYWxNINccq40Anw7BlsEXCMbt1Zt+OLA6Fq9suIpIWD0OsnISlw==",
          "dev": true,
          "requires": {
            "locate-path": "^5.0.0",
            "path-exists": "^4.0.0"
          }
        },
        "locate-path": {
          "version": "5.0.0",
          "resolved": "https://registry.npmjs.org/locate-path/-/locate-path-5.0.0.tgz",
          "integrity": "sha512-t7hw9pI+WvuwNJXwk5zVHpyhIqzg2qTlklJOf0mVxGSbe3Fp2VieZcduNYjaLDoy6p9uGpQEGWG87WpMKlNq8g==",
          "dev": true,
          "requires": {
            "p-locate": "^4.1.0"
          }
        },
        "make-dir": {
          "version": "3.0.0",
          "resolved": "https://registry.npmjs.org/make-dir/-/make-dir-3.0.0.tgz",
          "integrity": "sha512-grNJDhb8b1Jm1qeqW5R/O63wUo4UXo2v2HMic6YT9i/HBlF93S8jkMgH7yugvY9ABDShH4VZMn8I+U8+fCNegw==",
          "dev": true,
          "requires": {
            "semver": "^6.0.0"
          }
        },
        "ms": {
          "version": "2.1.2",
          "resolved": "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz",
          "integrity": "sha512-sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==",
          "dev": true
        },
        "p-locate": {
          "version": "4.1.0",
          "resolved": "https://registry.npmjs.org/p-locate/-/p-locate-4.1.0.tgz",
          "integrity": "sha512-R79ZZ/0wAxKGu3oYMlz8jy/kbhsNrS7SKZ7PxEHBgJ5+F2mtFW2fK2cOtBh1cHYkQsbzFV7I+EoRKe6Yt0oK7A==",
          "dev": true,
          "requires": {
            "p-limit": "^2.2.0"
          }
        },
        "path-exists": {
          "version": "4.0.0",
          "resolved": "https://registry.npmjs.org/path-exists/-/path-exists-4.0.0.tgz",
          "integrity": "sha512-ak9Qy5Q7jYb2Wwcey5Fpvg2KoAc/ZIhLSLOSBmRmygPsGwkVVt0fZa0qrtMz+m6tJTAHfZQ8FnmB4MG4LWy7/w==",
          "dev": true
        },
        "pkg-dir": {
          "version": "4.2.0",
          "resolved": "https://registry.npmjs.org/pkg-dir/-/pkg-dir-4.2.0.tgz",
          "integrity": "sha512-HRDzbaKjC+AOWVXxAU/x54COGeIv9eb+6CkDSQoNTt4XyWoIJvuPsXizxu/Fr23EiekbtZwmh1IcIG/l/a10GQ==",
          "dev": true,
          "requires": {
            "find-up": "^4.0.0"
          }
        },
        "semver": {
          "version": "6.3.0",
          "resolved": "https://registry.npmjs.org/semver/-/semver-6.3.0.tgz",
          "integrity": "sha512-b39TBaTSfV6yBrapU89p5fKekE2m/NwnDocOVruQFS1/veMgdzuPcnOM34M6CwxW8jH/lxEa5rBoDeUwu5HHTw==",
          "dev": true
        },
        "source-map": {
          "version": "0.6.1",
          "resolved": "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz",
          "integrity": "sha512-UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==",
          "dev": true
        },
        "ssri": {
          "version": "7.1.0",
          "resolved": "https://registry.npmjs.org/ssri/-/ssri-7.1.0.tgz",
          "integrity": "sha512-77/WrDZUWocK0mvA5NTRQyveUf+wsrIc6vyrxpS8tVvYBcX215QbafrJR3KtkpskIzoFLqqNuuYQvxaMjXJ/0g==",
          "dev": true,
          "requires": {
            "figgy-pudding": "^3.5.1",
            "minipass": "^3.1.1"
          }
        },
        "terser-webpack-plugin": {
          "version": "2.3.4",
          "resolved": "https://registry.npmjs.org/terser-webpack-plugin/-/terser-webpack-plugin-2.3.4.tgz",
          "integrity": "sha512-Nv96Nws2R2nrFOpbzF6IxRDpIkkIfmhvOws+IqMvYdFLO7o6wAILWFKONFgaYy8+T4LVz77DQW0f7wOeDEAjrg==",
          "dev": true,
          "requires": {
            "cacache": "^13.0.1",
            "find-cache-dir": "^3.2.0",
            "jest-worker": "^25.1.0",
            "p-limit": "^2.2.2",
            "schema-utils": "^2.6.4",
            "serialize-javascript": "^2.1.2",
            "source-map": "^0.6.1",
            "terser": "^4.4.3",
            "webpack-sources": "^1.4.3"
          }
        }
      }
    }

</details>
and i think its using ``webpack@4``.
and on my remote service production bundled, i got ``Error`` log such as:
````
Uncaught (in promise) ChunkLoadError: Loading chunk chunk-1bf0f48c failed.
(error: https://host.name/app/js/chunk-1bf0f48c.undefined.js)
    at Function.o.e (https://host.name/app/js/revision-report.ff1a2ba7.js:1:991)
    at _i.d [as $track] (https://host.name/app/js/chunk-common.64a9e56c.js:1:10617)
    at _i.hoorayAnimationEnd (https://host.name/app/js/revision-report.ff1a2ba7.js:1:9213)
    at animationEnd (https://host.name/app/js/revision-report.ff1a2ba7.js:1:11515)
    at ne (https://host.name/app/js/chunk-vendors.7693d6d1.js:7:11664)
    at s.n (https://host.name/app/js/chunk-vendors.7693d6d1.js:7:13459)
    at ne (https://host.name/app/js/chunk-vendors.7693d6d1.js:7:11664)
    at s.An.t.$emit (https://host.name/app/js/chunk-vendors.7693d6d1.js:7:26279)
    at https://host.name/app/js/revision-report.ff1a2ba7.js:1:8515
````
but after i make a local production bundle i got file ``chunk-1bf0f48c.f7594f71.js`` locally:
![image](https://user-images.githubusercontent.com/8576686/78347903-bdbc3980-75d3-11ea-8811-0572c3a2c489.png)

**Comment by yoannmoinet** [comment]
We have the same problem on a very large project with multiple entries.

It happens especially when we use the `SplitChunkPlugin` in addition to load a specific module both as a lazy import and regular import in the same bundle.

I'll try to make a minimal configuration to reproduce this, but it's quite difficult to pinpoint.

**Comment by woodhull** [comment]
We're also experiencing this, just started seeing it when I added a vue shared mixin between two dynamically loaded components.

**Comment by yoannmoinet** [comment]
So I wasn't able to reproduce it in a simpler setup.

But, I did found more details on the issue.

It appeared based on the size of chunks important lazy chunks.
Like, smaller chunks wouldn't trigger the bug.

One thing that fixed the issue temporarily was to use `optimization.splitChunks.cacheGroups.default.minSize: 0`.

But, it ended up re-occuring with another chunk, even with this option.

I've noticed that it's happening when we have `[contenthash]` in `output.chunkFileName`.

So I think that the `SplitChunksPlugin` might lose the `contenthash` somewhere somehow and replaces it by `undefined`.

Whenever you remove this part of your name template, the bug disappears, at least for us.
It's also happening with `chunkhash`.

We can't really remove this part from our namings, so I'm still investigating.
But if that rings a bell for anyone (cc @evilebottnawi @sokra), that would be helpful, it's a really annoying and blocking bug.

**Comment by evilebottnawi** [comment]
@yoannmoinet Without reproducible test repo it is hard to say why it broken, maybe you can provide more infromation? Plugins/configs/screenshots/etc

**Comment by yoannmoinet** [comment]
Tough, but fair 😉 
I'll continue trying to isolate the problem.

**Comment by arcanis** [comment]
I found a reproduction! Can this issue be reopened? The following repository triggers the bug if you follow the instructions:

https://github.com/arcanis/webpack-project-generator

**Comment by sokra** [comment]
As workaround you can use `optimization.runtimeChunk: "single"`

**Comment by sokra** [comment]
Thanks @arcanis I think I can fix that... Tomorrow...

**Comment by pubdreamcc** [comment]
I found the same problem that chunkHash would become unundefined, so what is the ultimate solution?， help，thanks！

**Comment by pubdreamcc** [comment]
Some j's files are not packaged and generated, but c's files are generated。
![image](https://user-images.githubusercontent.com/46315263/104431593-06713c00-55c3-11eb-983d-6bcd263dabf8.png)

**Comment by alexander-akait** [comment]
@pubdreamcc please create reproducible test repo

**Comment by pubdreamcc** [comment]
After upgrading webpack5, some modules are not packaged bundle.js , that is, some JS packages are missing. What's the problem? Webpack4 didn't have this problem before

**Comment by pubdreamcc** [comment]
@alexander-akait

**Comment by pubdreamcc** [comment]
Could it be that webpack 5 has upgraded tree shaking, resulting in some files not being packaged. Finally, the browser loads JS, and 404 appears. The file name is as above, and chunkhash is undefined

**Comment by alexander-akait** [comment]
Again https://github.com/webpack/webpack/issues/8677#issuecomment-759369152

**Comment by hnrchrdl** [comment]
i encountered the same issue with webpack 4, i can confirm it was fixed with https://github.com/webpack/webpack/tree/v4.44.2.

**Comment by nicolaelitvac** [comment]
@yoannmoinet Any luck solving this?

**Comment by akshaymhk** [comment]
Facing the same issue in Next.js with webpack 5. Any solution ?

**Comment by akshaymhk** [comment]
@nicolaelitvac, where can I find this config for changing chunkFileName? I have no custom webpack config. Using default webpack config with next.js

**Comment by nicolaelitvac** [comment]
I've got a custom config. So sorry can't help you.
