### ISSUE TITLE
dynamic import()  loaded an unexpected url when have an sub-route (Runtime issue)

### ISSUE THREAD

**Issue by morningtzh** [webpack/webpack#8683]
# Bug report

**What is the current behavior?**

Hello! I have a problem that Reate.Lazy (Using import() function ) loaded an unexpected url.

I have used Reate.Lazy (Using import() function ) success when I have only main route(Using React-Router v4). 

After I move the lazy into sub-route, I can't get the file.

On runtime, the lazy will get split file under main route, 

```
Uncaught (in promise) Error: Loading chunk /console/BlackList failed.
(missing: http://192.168.1.10:8000/console/BlackList.bundle.js)
    at HTMLScriptElement.onScriptComplete (runtime~index.bundle.js?7dbe5cbc88f836c06844:837)
```

**console** is the main route(also by react-router),  but the real file is packed on the path ` http://192.168.1.10:8000/BlackList.bundle.js`

**If the current behavior is a bug, please provide the steps to reproduce.**

This is the using of lazy
```
const About = lazy(() => import(/* webpackChunkName: "About" */ "./Pages/About"));
const BlackList = lazy(() => import(/* webpackChunkName: "BlackList" */ "./Pages/BlackList"));

const MeunList = {
    BlackList: { component: () => (<BlackList />), text: "BlackList", icon: "stop" },
    About: { component: () => (<About />), text: "About Us", icon: "environment" },
};

```

And this is the using of sub router  ( match.url = console) :
```
<Suspense fallback={<Icon type="loading" style={{ fontSize: 128 }} spin />} >
    <Switch>
        <Route exact path={`${match.url}`} component={initPage.component} />
        {
            Object.entries(MeunList).map(([meunKey, meunInfo]) => (
                <Route path={`${match.url}/${meunKey}`} key={`/${meunKey}`} component={meunInfo.component} />
          ))
     }
     </Switch>
</Suspense>
```

Main route
```
 <Route path="/console" component={MainPage} />
```

On runtime, the lazy will get split file under main route, 

```
Uncaught (in promise) Error: Loading chunk /console/BlackList failed.
(missing: http://192.168.1.10:8000/console/BlackList.bundle.js)
    at HTMLScriptElement.onScriptComplete (runtime~index.bundle.js?7dbe5cbc88f836c06844:837)
```

**console** is the main route(also by react-router),  but the real file is packed on the path ` http://192.168.1.10:8000/BlackList.bundle.js`

I have tried `const About = lazy(() => import(/* webpackChunkName: "../About" */ "./Pages/About"));` failed too~

And On the runtime, when getting url in   `jsonpScriptSrc` function at file runtime~index.bundle.js
 `__webpack_require__.p` is "" (empty string), the return value is `About.bundle.js`, but `script.src` is `http://192.168.1.10:8000/console/About.bundle.js`

This is in my webpack.config.js
```
        splitChunks: {
            chunks: "async",
            minSize: 100000,
            minChunks: 1,
            maxAsyncRequests: 5,
            maxInitialRequests: 3,
            automaticNameDelimiter: "~",
            name: true,
            cacheGroups: {
                vendors: {
                    test: /[\\/]node_modules[\\/]/,
                    minChunks: 1,
                    priority: -10,
                },
                default: {
                    minChunks: 2,
                    priority: -20,
                    reuseExistingChunk: true,
                },
            },
        },
        runtimeChunk: true,
```

**What is the expected behavior?**

It should get url `http://192.168.1.10:8000/About.bundle.js` but `http://192.168.1.10:8000/console/About.bundle.js` under front-end route `console` (full url `http://192.168.1.10:8000/console`)

**Other relevant information:**
webpack version:  4.25.1
Node.js version: v10.14.1
Operating System: Irrelevant
Additional tools: react / react-router V4

**Comment by tomasztomys** [comment]
similar here, since 4.29.0

**Comment by evilebottnawi** [comment]
@morningtzh Please format issue as template

**Comment by sokra** [comment]
Use the `output.publicPath` option

**Comment by morningtzh** [comment]
> Use the `output.publicPath` option

Thank you. It's worked!

**Comment by morningtzh** [comment]
> @morningtzh Please format issue as template

I'll format it~

**Comment by morningtzh** [comment]
> similar here, since 4.29.0

As sokra said, use `output.publicPath`  will solve this problem. I set `/`.  [document](https://webpack.js.org/configuration/output/#output-publicpath)

At last, I used `__webpack_public_path__` to separate release or debug. 
`__webpack_public_path__ = document.location.href.includes("debug") ? "/debug/" : "/";
`

**Comment by morningtzh** [comment]
The problem is solved. I'm going to close this issue.
