### ISSUE TITLE
Node.js child_process.spawn (webpack)

### ISSUE THREAD

**Issue by cvlr** [webpack/webpack#8685]
Hello,

how can I determine the end of webpack process? I want JSON (--json) output with --watch, but in my example, there are about 200 + chunks (it changes dynamically at change).

I want to make a UI for webpack with buil-in watch feature. But If first watch process ends, I can not catch that end.

In webpack test files I found something (example with chunkNumber) and I tried apply that in my example but I failed. 

```
const child_process = require('child_process');

const webpack = child_process.spawn(
  'npx',
  [
    'webpack',
    '--config',
    './webpack.config.js',
    '--json',
    '--watch',
  ],
  {
    env: {
      ...process.env,
      NODE_ENV: 'development',
    },
  }
);

webpack.on('close', () => {
  console.log('close');
});

let chunkNumber = 0;

webpack.stdout.on('data', (data) => {
  chunkNumber++;
  data = data.toString();

  console.log(chunkNumber);

  switch (chunkNumber) {
    case 1:
      console.log('A');
      break;
    default:
      break;
  }
});
```

**Comment by sokra** [comment]
When using `--watch` the process never exit.

**Comment by evilebottnawi** [comment]
Answer above https://github.com/webpack/webpack/issues/8685#issuecomment-459250038, please use issue template in future
