### ISSUE TITLE
Implement a jest-like <rootDir> for aliases

### ISSUE THREAD

**Issue by mgcrea** [webpack/webpack#8687]
## Feature request

Using a monorepo with webpack (in my case for backend), I haven't found a way to properly alias a `src` prefix as "src of the current package (eg. `./packages/foobar/src/`)" to address relative resolution hell (eg. `require('./../../../bar/foo.js')` vs `src/bar/foo.js`) for every sub-package in the monorepo.

[Jest resolves this](https://jestjs.io/docs/en/configuration.html#modulenamemapper-object-string-string) with a `<rootDir>` id that properly targets the current sub-package when used inside `moduleNameMapper`, eg:

```
  moduleNameMapper: {
    '^src/(.*)': '<rootDir>/src/$1'
  }
```

Haven't found a way to achieve the same with webpack.

**What is the expected behavior?**

Properly alias relative to every sub-package root inside a monorepo.

**What is motivation or use case for adding/changing the behavior?**

Missing feature as far as I know

**How should this be implemented in your opinion?**

I find jest `<rootDir>` to be convenient

**Are you willing to work on this yourself?**

Yes

**Hacky solution meanwhile**

```js
const monorepoSrcResolver = {
  apply(resolver) {
    const target = resolver.ensureHook('resolve');
    resolver.getHook('described-resolve').tapAsync(this.constructor.name, (request, context, callback) => {
      const {path: innerPath, request: innerRequest} = request;
      if (innerRequest.startsWith('src/')) {
        const newInnerRequest = `${innerPath.split('src/')[0]}${innerRequest}`;
        const newRequest = {...request, request: newInnerRequest};
        const message = `aliased with mapping: '${innerRequest}' to '${newInnerRequest}'`;
        return resolver.doResolve(target, newRequest, message, context, callback);
      }
      return callback();
    });
  }
};
```

**Comment by evilebottnawi** [comment]
@mgcrea yep, rare usage, let's close this issue, anyone feel free to feedback
