### ISSUE TITLE
smooth scroll lib getting window as undefined in umd style module definition

### ISSUE THREAD

**Issue by kellyrmilligan** [webpack/webpack#869]
https://github.com/cferdinandi/smooth-scroll/blob/master/dist/js/smooth-scroll.js

recently changed the UMD style, and it is now breaking in webpack on line 27 which checks for addEventListener on the window object. I've tried various combinations of the imports loader to include window, but to no avail. i've disabled define as well, and that let it be included, but the export was not the right object. 

any ideas on how to correctly use this module with webpack?

**Comment by jhnns** [comment]
It should be solvable with the imports-loader. Try this config:

```javascript
// webpack.config.js

module.exports = {
    ...
    module: {
        loaders: [
            {
                test: /[\/\\]node_modules[\/\\]smooth-scroll[\/\\]dist[\/\\]js[\/\\]smooth-scroll\.js$/
                loader: "imports?this=>window"
            }
        ]
};

```

**Comment by kellyrmilligan** [comment]
Yes after working with the module author, I ended up doing just that!
