### ISSUE TITLE
npx webpack, show ERROR in main.js from Terser

### ISSUE THREAD

**Issue by 15992033543** [webpack/webpack#8694]
I write a demo according to official documents。

npm i webpack webpack-cli --save-dev

the project directory like this:

index.html
-src
  -index.js
package.json

when i run npx webpack，Error occurred

ERROR in main.js from Terser
TypeError: Cannot read property 'minify' of undefined

**Comment by elvishp2006** [comment]
+1

**Comment by SamuelNitsche** [comment]
+1

**Comment by SayHeyD** [comment]
I was trying to get tailwinds working with Django and thought it's some compatibility problem, gonna post my repositories asap

**Comment by SamuelNitsche** [comment]
Head over to [https://github.com/webpack-contrib/terser-webpack-plugin/issues/66](https://github.com/webpack-contrib/terser-webpack-plugin/issues/66) for a workaround.

**Comment by TomCosta** [comment]
Simple run:
`npm install terser@3.14.1 --save-dev`
It solves my problem!

**Comment by Mspataro** [comment]
Is this a recent issue? The guide worked for me 2 weeks ago and my project still works. I noticed though when I tried to recreate my environment for a co-worker it kept failing because of this issue.

TomCosta's workaround solved my problem as well!

**Comment by SamuelNitsche** [comment]
Yeah, this issue occurred yesterday after a new release with breaking changes.

**Comment by SayHeyD** [comment]
@Mspataro I was trying to get this to work for the last week and stumbled across the same error everytime when I tried to change something. The first time i got the error was at thursday I think.

**Comment by YongzeYao** [comment]
I ran into the same issue today. TomCosta's workaround works.

**Comment by rowlandjumbo** [comment]
Tom Costa is da man! Thanks!

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/terser-webpack-plugin/issues/66

**Comment by dawsonc623** [comment]
I realize this is closed, but it looks like we are stuck until Webpack updates its dependency on `terser-webpack-plugin` to `1.2.2`. Is this happening soon?

**Comment by sokra** [comment]
Nothing to do on webpack side.
