### ISSUE TITLE
Async chunks not reusing code from sync chunks

### ISSUE THREAD

**Issue by CyberAP** [webpack/webpack#8697]
# Bug report

**What is the current behavior?**

If you force some async chunks to be in the sync chunk, then the code in other async chunks won't be reused from the sync chunk.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Import your sync chunks
    ```javascript
      import bar from 'foo/bar/index.js';
    ```
2. Use async import in the same directory
    ```javascript
      import(/* webpackChunkName: "page-[request]" */ `foo/${pageName}/index.js`)
    ```
3. Use `splitChunks.chunks: 'all'`;

The code in sync and async chunks will be duplicated.

```javascript
// app chunk (sync)
(window.webpackJsonp = window.webpackJsonp || []).push([[3, 1], {
    "/rhA": function(t, e, s) {
```
```javascript
// page A chunk (async)
(window.webpackJsonp = window.webpackJsonp || []).push([[4], {
    "/rhA": function(t, e, n) {
```
```javascript
// page B chunk (async)
(window.webpackJsonp = window.webpackJsonp || []).push([[7], {
    "/rhA": function(t, e, n) {
```

**What is the expected behavior?**

Async chunks should not have duplicated code.

**A more detalied example**

```javascript
// App entrypoint
import loadPages from '@modules/app/loadPages.js';
import homePage from '@pages/home/index.js';
import aboutPage from '@pages/about/index.js';

const criticalPages = {
  homePage,
  aboutPage
};

loadPages(criticalPages);
```

```javascript
// loadPages.js
const loadPage = criticalPages => async pageName => {
  if (pageName in criticalPages) {
    try {
      criticalPages[pageName]();
    }
    catch(err) {
      console.log(`Error loading page: '${pageName}'`);
      console.log(err);
    }
    return;
  }
  try {
    import(/* webpackChunkName: "page-[request]" */ `@pages/${pageName}/index.js`)
      .then(res => {
        res && res.default && res.default()
      });
  }
  catch(err) {
    console.log(`Page loader not found for page '${pageName}'`);
    console.log(err);
  }
};

export default function loadPages(criticalPages = {}) {
  const documentPages = document.documentElement?.dataset.pages;
  if (!documentPages) return;

  const pagesToLoad = JSON.parse(documentPages);

  const loadPageWithCritical = loadPage(criticalPages);

  pagesToLoad?.forEach(loadPageWithCritical);
};
```

**Comment by sokra** [comment]
Thanks for your report. This looks like a bug.

Which webpack version? Config?

It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by CyberAP** [comment]
Latest webpack 4. Tried reducing this to a small test case but had no luck, it worked as expected. I will try disabling my webpack plugins one by one on this weekend to see if one of them is the root cause of the issue.
For now here is my webpack base config: https://gist.github.com/CyberAP/2de813b072494a3af095e14df8d26ebf

**Comment by CyberAP** [comment]
That's actually a mistake of mine. I was cross-referencing async modules in different entries, while they should've been separated.
So I've changed a structure from this:

```
@pages
  -- a
  -- b
  -- c
```

To this:

```
@pages
  -- app
    -- a
    -- b
  -- foo
    -- c
```

And the issue is now gone.
