### ISSUE TITLE
compile.run not propagating thrown errors

### ISSUE THREAD

**Issue by aryzing** [webpack/webpack#8699]
# Bug report

**What is the current behavior?**
When using the node api, throwing an error within the `compiler.run` function does not propagate the error to the calling process:

```js
// scripts/build.js
let compiler = webpack(compilerConfig);

compiler.run(function(err, stats) {
  if (err) {
    throw new Error(err);
    
  } else if (stats.hasErrors()) {
    throw new Error(stats.toString({ colors: true })); // Error not propagated
  }
});

// index.js
const result = spawnSync(
  'node',
  [require.resolve('./scripts/build.js')].concat(args),
  { stdio: 'inherit' }
);

process.exit(result.status); // result.status is always 0
break;
```

The only way I can produce a non-zero exit status is if I manually call `process.exit(1)` within the `build.js` code.

**If the current behavior is a bug, please provide the steps to reproduce.**
Just throw an error in the `compiler.run` function

**What is the expected behavior?**
The error should be propagated, and the exit status of the script should not be 0.

**Other relevant information:**
webpack version: 4.26.0
Node.js version: 11.6.0
Operating System: Mac OSX
Additional tools: n/a

**Comment by aryzing** [comment]
Still an issue I believe

**Comment by evilebottnawi** [comment]
@aryzing hi, can you create minimum reproducible test repo?

**Comment by danvoyce** [comment]
The problem for me was related to this https://github.com/sass/node-sass/issues/2666, and the simplest solution for me was to do this instead ```process.kill(process.pid, 'SIGINT');```
