### ISSUE TITLE
How to solve unwanted dynamic requires

### ISSUE THREAD

**Issue by jhnns** [webpack/webpack#87]
I want to use [moment.js](http://momentjs.com/) for date formatting. Unfortunately they have a [dynamic require in their code](https://github.com/timrwood/moment/blob/develop/moment.js#L583) for language files - so webpack includes all of them.

What do you suggest, oh mighty sokra? :smile:

**Comment by rafaeleyng** [comment]
Just in case somebody else come here and follow the link @jhnns provided, the actual line with the dynamic require is [this one](https://github.com/moment/moment/blob/aea2a8961bc4dbff0471d0615af1f4fb98fc81d7/moment.js#L399).

**Comment by binki** [comment]
Shouldn’t webpack just create a chunk for each dynamically loadable language? The script already supports dynamic loading, probably to solve the exact problem webpack’s mishandling of it causes (it solves the problem of throwing irrelevant JavaScript that the browser will never call at the browser).

**Comment by liqiang372** [comment]
I came across similar cases in amd

```javascript
var deps = [];
if( some condition )
    deps = [dep1, dep2, ...]
else
    deps = [other1, other2, ...]
define(deps, function(arg1, arg2, ....){

});
```
My confiuration for `ContextReplacementPlugin` is 

```
new webpack.ContextReplacementPlugin(
      /directory of caller file/, 
      "the directory of dependecies",
      {
        'deps': [dep1, dep2, other1, other2]
      } 
    )
```
It seems `ContextReplacementPlugin` does not support dependency array.  Is any better way to do this?
