### ISSUE TITLE
Add translate-webpack-plugin to list of plugins

### ISSUE THREAD

**Issue by zakkudo** [webpack/webpack#8711]
I'm the owner of this package at https://www.npmjs.com/package/@zakkudo/translate-webpack-plugin .  It handles translations fundamentally differently than most javascript translation libraries, and I recommend you guys think about posting it to your docs. ;)  Either that or give feedback.

It's going to hit 1.0 in the next month when AI build a cli into the lower level library.

**Comment by evilebottnawi** [comment]
@zakkudo Please use this repo https://github.com/webpack-contrib/awesome-webpack for new plugins/loaders, thanks
