### ISSUE TITLE
Webpacks fetches 4 files for one dynamic import

### ISSUE THREAD

**Issue by shravan2x** [webpack/webpack#8722]
# Bug report

**What is the current behavior?**
When using an import() in the base level of a file (i.e. not inside any functions/classes), webpack fetches 4 files on the browser. It's possible that this is caused by two separate issues (one about the extra `vendor~` file and the other about the duplicate requests). The code I use is:

```
import(
    /* webpackChunkName: "brace_modes" */
    /* webpackMode: "lazy" */
    /* webpackPrefetch: true */
    './brace_modes'
);
```

and this is what the browser does:
![image](https://user-images.githubusercontent.com/4096676/52254179-da76b780-28d1-11e9-830a-e9deb309daca.png)

For my full webpack.config.js, go [here](https://gist.github.com/shravan2x/f2c37c3d365cfa8ec16a938cdd14045f).

Note that this seems to be a regression in Webpack 4.

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a dynamic import in the base level of a file. Run it.

**What is the expected behavior?**
Only a single file is imported dynamically - `brace_modes.<hash>.js`.

**Other relevant information:**
webpack version:  4.28.4 (I didn't use 4.29 due to the issues with import)
Node.js version: 10
Operating System: Windows 10
Additional tools: -

**Comment by shravan2x** [comment]
> The `vendor~` prefixed file bundles your `node_modules` separately from your application code to improve the long term caching for these modules.

That's interesting. I think this is a new feature since Webpack 2. In my case though, `'./brace_modes'` is just a file with 10 lines of imports. It's literally a file containing multiple other imports:

```
import 'brace/mode/c_cpp';
import 'brace/mode/csharp';
import 'brace/mode/css';
import 'brace/mode/html';
import 'brace/mode/java';
import 'brace/mode/javascript';
import 'brace/mode/json';
import 'brace/mode/plain_text';
```

So a `vendors~` file doesn't make much sense. Is there a simple way for me to tell Webpack not to use a separate file (and avoid making an extra request)? Ideally in the form of a comment config param so I don't have to pollute my webpack.config file?

> Actually using `webpackPrefetch` for a base level `import()` doesn't make much sense as the prefetching request is triggered at the same time as the normal request, but this shouldn't make any real difference expect how it looks like in devtools.

This makes sense to me, but where else could I include such an import that I want to be loaded lazily and as-soon-as-possible but only when the network is free (i.e. similar to prefetch)?

**Comment by sokra** [comment]
> This makes sense to me, but where else could I include such an import that I want to be loaded lazily and as-soon-as-possible but only when the network is free (i.e. similar to prefetch)?

Place the import() at this position where your need the exports.

Adding webpackPrefetch will fetch it as soon as possible.

> So a `vendors~` file doesn't make much sense. Is there a simple way for me to tell Webpack not to use a separate file (and avoid making an extra request)? Ideally in the form of a comment config param so I don't have to pollute my webpack.config file?

Sorry there is no comment config param for this. You could control it with `optimization.splitChunks`.

I guess I see your issue. In your case the remaining non-vendor chunk is pretty small.

**Comment by shravan2x** [comment]
> Place the import() at this position where your need the exports.

The thing is that I don't ever immediately need the exports. When imported, the file runs itself i.e. it contains code that registers itself with an existing component, which I can then access it through. This is why I'm unsure where to place the import.

> Sorry there is no comment config param for this. You could control it with `optimization.splitChunks`. I guess I see your issue. In your case the remaining non-vendor chunk is pretty small.

That's correct, my `brace_modes.<hash>.js` file is less than 1kb and does nothing but import the larger 500kb `vendors~...` file. If I'd like to request an enhancement for a comment config param for my use case, would you recommend I create a new issue or is this one sufficient?

**Comment by shravan2x** [comment]
@sokra Just saw that you had implemented this a while back. Thank you!
