### ISSUE TITLE
webpack --watch ignores changes in files that only export TS interfaces

### ISSUE THREAD

**Issue by chmielot** [webpack/webpack#8734]
# Bug report

**What is the current behavior?**
When the only thing a Typescript file exports is an interface, changes to the interface are not seen by `webpack --watch`.

**If the current behavior is a bug, please provide the steps to reproduce.**
I have created a very small example repository to reproduce the issue including instructions in the README file: https://github.com/chmielot/webpackwatch-bug

**What is the expected behavior?**
If a Typescript file only exports interfaces, changes to the interfaces should also force a recompile.

**Other relevant information:**
webpack version:  4.29.1
Node.js version: v11.8.0
Operating System: macOS Mojave 10.14.2
Additional tools: -

**Comment by sokra** [comment]
@johnnyreilly

**Comment by johnnyreilly** [comment]
The reason for this is that a file that contains only interfaces is, post transpilation, an empty file. So if an interface is changed, it makes no difference to transpilation output which is still empty. I don't have a good solution for this really. I've considered the possibility that in the case of interface only output you instead push out a commented out hash in dev mode which would change with file changes. That would likely trigger the desired behaviour.  Feels hacky but it would work. I'd potentially be open to receiving a PR that added this to ts-loader. If there's better options I'm all ears!

**Comment by chmielot** [comment]
You say that a file that contains only interfaces is an empty file after transpilation. For a better understanding, can you explain why it recompiles when changing the interface, when there is a function defined and used, like in my example? According to what you said, the output post transpilation should still be the same.

And to discuss your idea for a solution: Couldn't we just add a commented to hash to every file in dev mode? I'm not an expert to tell if it is easy or not to identify a file with only interfaces..

**Comment by rockResolve** [comment]
I had recompilation success with using Webpack dead code, that will be removed in my production build. That is adding at the bottom of the file:
```
if (process.env.NODE_ENV !== 'production') {
    // Webpack dev trigger recompile
}
```
I got this from a helpful bloke at https://blog.johnnyreilly.com/2018/03/its-not-dead-webpack-and-dead-code.html !!!

**Comment by johnnyreilly** [comment]
> can you explain why it recompiles when changing the interface, when there is a function defined and used, like in my example? According to what you said, the output post transpilation should still be the same.

I can't actually - I'd have to debug it to find out.

> Couldn't we just add a commented to hash to every file in dev mode? I'm not an expert to tell if it is easy or not to identify a file with only interfaces..

It's an idea worth exploring. If you'd like to submit a speculative PR to ts-loader I'd take a look. I'd probably only add the hash to files that were types / interfaces only as that's where the problem lies.
