### ISSUE TITLE
(optimization.splitChunks) Extracting true commons from multiple entry points relays on `minChunks` value

### ISSUE THREAD

**Issue by falsyvalues** [webpack/webpack#8735]
# Bug report

**What is the current behavior?**

When we are building with multiple entry points that share a common modules (but also have other deps):

```
entry: {
  page1: 'src/page1.js',
  page2: 'src/page2.js',
  page3: 'src/page3.js',
  page4: 'src/page4.js',
  page5: 'src/page5.js',
  page6: 'src/page6.js'
}
```

It's impossible to extract **true** commons that are shared across all modules without explicitly saying `minChunks: <number-of-entries->`.

```
optimization: {
        splitChunks: {
            cacheGroups: {
                vendors: {
                    chunks: 'initial',
                    name: 'vendor',
                    test: /[\\/]node_modules[\\/]/,
                    // minChunks: <x>
                }
            }
        }
    }
```

Also [documentation](https://webpack.js.org/plugins/split-chunks-plugin/#split-chunks-example-1) is not not entirely truthful because example from docs will extract commons even if they are shared only by two modules so it will bloat bundle size loaded by other entry points.

```
module.exports = {
  //...
  optimization: {
    splitChunks: {
      cacheGroups: {
        commons: {
          name: 'commons',
          chunks: 'initial',
          minChunks: 2
        }
      }
    }
  }
};
```
**If the current behavior is a bug, please provide the steps to reproduce.**

1. Configure multiple entry points 
2. Enable `optimization.splitChunks` using [configuration](https://webpack.js.org/plugins/split-chunks-plugin/#split-chunks-example-1) from documentation
3. Run webpack and inspect commons bundle
4. Bundle will contain content that is not shared by every entry point

**What is the expected behavior?**

It should be possible to configure `optimization.splitChunks` to extract **true** commons for all entry points without hacking it via `minChunks` option (equal to number of chunks).

**Other relevant information:**
webpack version: v4.29.1
Node.js version: v10.14.1
Operating System: macOS High Sierra 10.13.6 (17G3025)
Additional tools: -

**Comment by sokra** [comment]
`minChunks: Object.keys(entry).length` may work for your concrete case.

A more general advise it to omit the `name` option and set `minChunks: 2`. This will create a chunk for modules shared by all entries, and chunks for modules shared only by a few entries.

**Comment by falsyvalues** [comment]
@sokra Thanks for responding. `Object.keys(entry).length` is some kind of workaround in this case, but still it requires knowledge on this (and result of setting this to number of entry points). I would really like the possibility to create named **true** common then go with chunks without name as as lower priority splitting.

**Comment by falsyvalues** [comment]
Hi @sokra is there any chance that in webpack 5 it will be easier to handle this case?
