### ISSUE TITLE
Question: How to get changed files in custom plugin?

### ISSUE THREAD

**Issue by stnwk** [webpack/webpack#8739]
Hello!

I would like to know what would be the currently best way to figure out what files have changed in a compilation in watch mode when writing a custom plugin?

I found this example https://webpack.js.org/contribute/plugin-patterns/#monitoring-the-watch-graph in the documentation, but that doesn't seem to work anymore. Is this outdated?

Thanks :)

**Comment by evilebottnawi** [comment]
@stnwk please use stackoverflow or gitter for questions, it is bug tracker. Please create issue in webpack docs repo about example (example should work), thanks!
