### ISSUE TITLE
Using preloaded assets

### ISSUE THREAD

**Issue by danschumann** [webpack/webpack#874]
I have all my files in memory, for various reasons I won't get into ( maybe one is because I wrote a loading module `loaddir` and tend to use it ), but part of it is re-using code on the front end and back end.

My loaded files look like this (`asObject: true`):
```
require('loaddir')({path: './scripts', asObject: true }).then(function(directory) {
  /* directory == {
     'file1': 'console.log("file1");',
     'subDirectory': {
         'file2': 'console.log("subDir/file2");',
     },
  } */
});
```
or, my loaded files look like this (`asObject: false`)
```
require('loaddir')({path: './scripts' }).then(function(directory) {
  /* directory == {
    'file1': 'console.log("file1");',
    'subDirectory/file2': 'console.log("subDir/file2");',
  } */
});
```

How do I give a manifest like this to webpack, telling it "Hey webpack, I already loaded everything, can you just compile using this data plz?"

**Comment by sokra** [comment]
You can provide a custom `inputFileSystem` to the `Compiler` instance.

**Comment by danschumann** [comment]
K, searching the codebase for that.  Is there a doc somewhere with what structure it must be in before I dig through all the code?

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#141
