### ISSUE TITLE
Dynamic import cause the bundle chunks not gets loaded properly

### ISSUE THREAD

**Issue by aryaroudi** [webpack/webpack#8745]
I recently faced a problem that i couldn't find any example or the same issue about it. I don't know if it is a bug or a configuration issue. I explain.

I have an Angular/Angularjs application which gets built by Webpack 4. I realized that if I import the AJS `bootstrap` file statically inside the main.ts file of the new Angular, no chunk will be generated by Webpack. I use the same Webpack config in the AJS and it creates me the chunks automatically. 

Now the issue is If I import the `bootstrap` file as a dynamic import it will create the bundle's chunks but it is not getting loaded properly: I see that there are `0,1,2,3` chunks in dist folder but in the `bundle.js` only defined: 

```
return __webpack_require__.p + "bundle-" + ({}[chunkId]||chunkId) + "-" + {"2":"f3366b0a8b53abf25d5b","3":"249458b5c54cba92939d"}[chunkId] + ".js"
```
`2,3`. And missing `0, 1` bundle. Any idea what can cause this?

*Webpack.config*:

```
optimization: {
            minimize: ifProd(true, false),
            minimizer: ifProd([
                new TerserPlugin({
                    sourceMap: ifProd(false, true),
                    parallel: false,
                    cache: ifProd(false, './.build_cache/terser'),
                    exclude: [/transpiledLibs/, /.css$/, /node_modules/, /lib/, /dist/],
                    terserOptions: {
                        compress: {
                            drop_debugger: false
                        },
                        warnings: false,
                        ie8: false
                    }
                })
            ], []),
            splitChunks: {
                cacheGroups: {
                    camStyle: {
                        name: 'elasticbox',
                        test: (m, c, entry = 'camstyle') => m.constructor.name === 'CssModule' && recursiveIssuer(m) === entry,
                        chunks: 'all',
                        enforce: true
                    },
                    cyclopsStyles: {
                        name: 'cyclops',
                        test: (m, c, entry = 'cyclops') => m.constructor.name === 'CssModule' && recursiveIssuer(m) === entry,
                        chunks: 'all',
                        enforce: true
                    },
                    vendorStyles: {
                        name: 'vendor',
                        test: (m, c, entry = 'vendor') => m.constructor.name === 'CssModule' && recursiveIssuer(m) === entry,
                        chunks: 'all',
                        enforce: true
                    }
                }
            }
        },
```

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by aryaroudi** [comment]
The template got updated
