### ISSUE TITLE
Requiring 'browser' packages on the server

### ISSUE THREAD

**Issue by zol** [webpack/webpack#875]
We're writing isomorphic code for rendering views on the server. We're using webpack to build the client off of the same codebase used to render on the server. To prevent `require` from throwing exceptions on the server when loading modules designed for the browser, we're finding ourselves writing code like:

``` js
var PictureFill;
var FastClick;

try {
  PictureFill = require('picturefill');
  FastClick = require('fastclick');
} catch (e) {
  if (! e instanceof ReferenceError)
    throw e;
}
```

Is there a more idiomatic approach we should be using? (i.e what do others do?)

Cross posted with no love from the npm issue tracker [here](https://github.com/npm/npm/issues/7545)

**Comment by troutowicz** [comment]
Without try/catch:

```javascript
if (typeof window !== 'undefined') {
  // include modules here
}
```
If your views are built with React, you could instead place the component with client side only modules inside the if statement, and prerender a placeholder variable.

**Comment by zxcabs** [comment]
You can use [DefinePlugin](http://webpack.github.io/docs/list-of-plugins.html#defineplugin) to define environment.

**Comment by zol** [comment]
Thanks @troutowicz and @zxcabs . These answer my question.
