### ISSUE TITLE
Dynamic import cause the bundle chunks to not get loaded properly

### ISSUE THREAD

**Issue by aryaroudi** [webpack/webpack#8752]
# Bug report

recently faced a problem that I couldn't find any example or the same issue about it. I don't know if it is a bug or a configuration issue. I explain.

I have an Angular/Angularjs application which gets built by Webpack 4. I realized that if I import the AJS `bootstrap` file statically inside the main.ts file of the new Angular, no chunk will be generated by Webpack. I use the same Webpack config in the AJS and it creates me the chunks automatically. 

Now the issue is If I import the `bootstrap` file as a dynamic import it will create the bundle's chunks but it is not getting loaded properly: I see that there are `0,1,2,3` chunks in dist folder but in the `bundle.js` only defined: 

```
return __webpack_require__.p + "bundle-" + ({}[chunkId]||chunkId) + "-" + {"2":"f3366b0a8b53abf25d5b","3":"249458b5c54cba92939d"}[chunkId] + ".js"
```
`2,3`. And missing `0, 1` bundle. Is that possible that tsconfig cause this issue?

*Webpack.config*:

```
optimization: {
            minimize: ifProd(true, false),
            minimizer: ifProd([
                new TerserPlugin({
                    sourceMap: ifProd(false, true),
                    parallel: false,
                    cache: ifProd(false, './.build_cache/terser'),
                    exclude: [/transpiledLibs/, /.css$/, /node_modules/, /lib/, /dist/],
                    terserOptions: {
                        compress: {
                            drop_debugger: false
                        },
                        warnings: false,
                        ie8: false
                    }
                })
            ], []),
            splitChunks: {
                cacheGroups: {
                    camStyle: {
                        name: 'elasticbox',
                        test: (m, c, entry = 'camstyle') => m.constructor.name === 'CssModule' && recursiveIssuer(m) === entry,
                        chunks: 'all',
                        enforce: true
                    },
                    cyclopsStyles: {
                        name: 'cyclops',
                        test: (m, c, entry = 'cyclops') => m.constructor.name === 'CssModule' && recursiveIssuer(m) === entry,
                        chunks: 'all',
                        enforce: true
                    },
                    vendorStyles: {
                        name: 'vendor',
                        test: (m, c, entry = 'vendor') => m.constructor.name === 'CssModule' && recursiveIssuer(m) === entry,
                        chunks: 'all',
                        enforce: true
                    }
                }
            }
        },
```

*tsconfig*

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  }
}
```

**Other relevant information:**
webpack version:  4.1
Node.js version: 8

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by alex-ayala** [comment]
@sokra I have also been dealing on this and I was able to create an example repo that replicates this issue: https://github.com/alex-ayala/dynamic-import-issue.

**Comment by PerspectivesLab** [comment]
any news on this? it seems we cant use cachegroups on modules that use dynamic import ?

**Comment by z791483920** [comment]
how to fix it ····  I have same problem

**Comment by aryaroudi** [comment]
@PerspectivesLab @z791483920 Unfortunately couldn't find any solution for this but if I remember it right it was happening because of the way that I was importing a file in my bootstrap file which I was trying to import dynamically, So at the end, I could able to separate the bundle but the problem was when you have a hybrid application the AJS should be loaded first and couldn't manage that to load which bundle first
