### ISSUE TITLE
Error when building multiple configurations in production mode

### ISSUE THREAD

**Issue by rdelhommer** [webpack/webpack#8753]
# Bug report
**What is the current behavior?**
I am currently experiencing an odd issue where I get the following runtime error when building my multiple configuration application in production mode
>TypeError: Cannot read property 'call' of undefined at __webpack_require__

This error only occurs when both configurations are built.  If I pass the flag --config-name app1 to restrict the build to only a single configuration, the runtime error does not appear.

I went through a couple of the optimizations and found that forcing namedModules: true causes the runtime error to go away when I build all configurations at once
```
module.exports = {
  //...
  optimization: {
    namedModules: true
  }
};
```

I am currently using aurelia for this project and it's possible this could be an issue with their loader or bootstrapper.  

**If the current behavior is a bug, please provide the steps to reproduce.**
I can try to create a small example repository reproducing the bug when I get time if the description above is not enough

**What is the expected behavior?**
Building all configurations should not cause runtime errors
IE - both of these should produce the same output for a hypothetical app1
```
webpack --config-name app1
```
```
webpack
```

**Other relevant information:**
webpack version:  4.29.1
Node.js version:  8.11.4
Operating System:  Windows 10
Additional tools: AureliaJS, TypeScript, Less

**Comment by sokra** [comment]
Sound like a very bad problem.

Could you try to make a diff between good and bad build? Best with `optimization.minimize: false`.

**Comment by RedTn** [comment]
I've ran into a similar issue where forcing `namedModule: true` fixes my build, but then I get an error with `styled-components` https://www.styled-components.com/docs/faqs#why-am-i-getting-a-warning-about-several-instances-of-module-on-the-page. @rdelhommer did you find any solution?

**Comment by rdelhommer** [comment]
Unfortunately, I wasn't able to look into the issue further and ended up building each configuration separately

**Comment by evilebottnawi** [comment]
Maybe somebody can create minimum reproducible test repo?

**Comment by rdelhommer** [comment]
I actually no longer have access to the code base in which this was occurring.  Sorry... Wish I could be of more help

**Comment by evilebottnawi** [comment]
Thanks for answer, i am closing issue, but feel free to open new issue with reproducible test repo
