### ISSUE TITLE
Option to select specific extensions for CommonChunksPlugin

### ISSUE THREAD

**Issue by jeffling** [webpack/webpack#876]
I use the common chunks plugin but I don't want to have common css. As a result, I have a little filter to find css and extract it out in the `minChunks` property I pass into the plugin. 

Is there an easier way to do this I missed, or maybe this could be a option for the CommonChunksPlugin? To generalize this, maybe we can even select certain extensions/regex we want to add into common chunks?

**Comment by sokra** [comment]
3 lines function for `minChunks` should be easy enough...

**Comment by jeffling** [comment]
It's easy enough and it's the solution, but seems like more of a hack than solution. Do you think this functionality is outside the scope of this function?

**Comment by bebraw** [comment]
Is this relevant still?
