### ISSUE TITLE
webpack change the electron render env

### ISSUE THREAD

**Issue by 13banda** [webpack/webpack#8760]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
when i use ```process.env``` with webpack in electron renderer process it show empty object ```{}``` but without  webpack ```process.env``` working ok. 

**Other relevant information:**
webpack version:  latest
Node.js version: 
Operating System: ubuntu 
Additional tools: electron

**Comment by misterdev** [comment]
Can you share your Webpack configuration?

From my experience, this happens if you don't set a [target](https://webpack.js.org/configuration/target/) and it defaults to "web".

**Comment by 13banda** [comment]
```
webpack: {
       configure: {
         target: "electron-renderer",
         externals:{
           puppeteer : 'require("puppeteer")'
         },
         resolve: {
                modules: [
                  "node_modules"
                ]
        }
      }
    },
```

**Comment by misterdev** [comment]
I'm sorry, I'm not able to reproduce the error. Would be great if you could share a minimal setup to reproduce this problem, thanks

**Comment by 13banda** [comment]
check this repo [Reproduce Error repo.](https://github.com/13banda/electron-webpack)

**Comment by misterdev** [comment]
I've executed `npm run eject` to see how webpack in configured in create-react-app.
You can see here that in `env.js`it filters the `process.env` keys including only those starting with `REACT_APP_`, `NODE_ENV` and `PUBLIC_URL`.

<img width="1089" alt="screenshot 2019-02-09 at 00 52 14" src="https://user-images.githubusercontent.com/11232797/52512503-5c821b80-2c05-11e9-8f09-8c9213145017.png">

In the webpack configuration this filtered version of the `process.env` is replaced in the source code using the `DefinePlugin`

<img width="784" alt="screenshot 2019-02-09 at 01 09 23" src="https://user-images.githubusercontent.com/11232797/52512861-74f33580-2c07-11e9-80da-3c6d3628f18e.png">

The process `process.env` is intentionally nearly empty, this isn't a problem with Webpack but a create-react-app configuration :)

**Comment by 13banda** [comment]
thanks @misterdev
