### ISSUE TITLE
`Uncaught SyntaxError: Unexpected token !` with `new Method` usage

### ISSUE THREAD

**Issue by extempl** [webpack/webpack#8762]
# Bug report

**What is the current behavior?**
Fails with an expection

**If the current behavior is a bug, please provide the steps to reproduce.**
```
import Method from 'path/to/unexisting/module';
new Method();
```
It will be transpiled to 
```
new !(function webpackMissingModule() { var e = new Error("Cannot find module 'path/to/unexisting/module'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())(params);
```

**What is the expected behavior?**
Proper exception with proper error message and stack.

**Other relevant information:**
webpack version:  4.19.1
Node.js version: v10.13.0
Operating System: MacOS

**Comment by ajaygangarde** [comment]
do you got any solution for above problem. i am also stuck into it. any Help would be appreciate

**Comment by extempl** [comment]
@ajaygangarde as a workaround - just click on the link to the code place where the exception happened and you'll see the exact missing path in the generated code.

**Comment by extempl** [comment]
Hey, let it be active then! Why close?

**Comment by evilebottnawi** [comment]
Fixed https://github.com/webpack/webpack/pull/10424 (webpack@5)
