### ISSUE TITLE
moduleFilenameTemplate option to SourceMapDevToolPlugin does not seem to work

### ISSUE THREAD

**Issue by radcapitalist** [webpack/webpack#8764]
# Bug report

**What is the current behavior?**
Best I can tell, the **moduleFilenameTemplate** option to **webpack.SourceMapDevToolPlugin** does nothing.  The doc implies that **moduleFilenameTemplate** is equivalent to setting the **devtoolModuleFilenameTemplate** option in the **output** section of your webpack config.  However, in my experience, **devtoolModuleFilenameTemplate** works and **moduleFilenameTemplate** does not.

**If the current behavior is a bug, please provide the steps to reproduce.**

You'll want to start with a Node.js web application that is bundled with webpack (so **target: 'node'**.  I am using the WebStorm IDE, but I don't think that has an impact.

Include this in your webpack config:

	plugins: [
		// https://webpack.js.org/plugins/source-map-dev-tool-plugin/
		new webpack.SourceMapDevToolPlugin({
			filename: "[file].map",
			moduleFilenameTemplate: '[absolute-resource-path]',
		}),
	],

Debug your application, and put a "throw" in there so that you hit an error.  Look at the stack trace.  You will see lines like this:

       at module.exports.featured (webpack:///./src/server/app_server/controllers/packages.js?:351:6)
 
The presence of "webpack:///" up front in the path is a very bad thing.

Now, take out the **moduleFilenameTemplate** line and, instead, add this to the **output:** section of your webpack config:

		devtoolModuleFilenameTemplate: '[absolute-resource-path]',

Now, hit your breakpoint again, and this time check out your stack trace:

       at module.exports.featured (C:\jmpdev\usr\sasewh\Node\ServerNext\webjmp\src\server\app_server\controllers\packages.js:351:6)

You get a nice, beautiful correct path that your IDE can turn into a link you can click on to take you to that line in the original source.

Just seems like the **moduleFilenameTemplate** option should work the same but doesn't.

**What is the expected behavior?**

I would expect both of those options to produce the same path in the stack trace.  **moduleFilenameTemplate** should at least do **something**.  It seems to do nothing.

**Other relevant information:**
webpack version:  4.29
Node.js version: 10.15.1
Operating System: Windows
Additional tools:  WebStorm IDE

**Comment by sokra** [comment]
`devtoolModuleFilenameTemplate` is translated to a call to the plugin:

https://github.com/webpack/webpack/blob/2068a816edd2bb8d8ba424fd40ee3071bf9186c4/lib/WebpackOptionsApply.js#L270-L281

Try also passing `fallbackModuleFilenameTemplate`.

**Comment by sokra** [comment]
Also make sure to use `devtool: false` when using the Plugin.

**Comment by radcapitalist** [comment]
Hey, Tobias - I'm not quite sure how to interpret your first reply.  Are you saying that the plugin's **moduleFilenameTemplate** can only be set indirectly by setting the **devtoolModuleFilenameTemplate** option of **output**?

At any rate, here is what I am seeing for paths in the stack trace with various options:

devtool **not** set, no setting for **moduleFilenameTemplate**:
     webpack:///./src/server/app_server/controllers/test.js?:8:8

devtool set to **false**, no setting for **moduleFilenameTemplate**:
      C:\jmpdev\usr\sasewh\Node\ServerNext\webjmp\build\bundle-server.js:6704:8
(If devtool is explicitly set to **false**, the path looks just like this no matter how I set either plugin or output module filename template options.  It seems all moduleFilenameTemplate options are ignored if devtool is set to **false**).

devtool **not** set, plugin **moduleFilenameTemplate** set to absolute resource path:
      webpack:///./src/server/app_server/controllers/test.js?:8:8

devtool **not** set, plugin **fallbackModuleFilenameTemplate** set to absolute resource path:
      webpack:///./src/server/app_server/controllers/test.js?:8:8

devtool **not** set, output devtoolFallbackModuleFilenameTemplate set to abs resource path:
      webpack:///./src/server/app_server/controllers/test.js?:8:8

devtool **not** set output devtoolModuleFilenameTemplate set to absolute resource path:
      C:\jmpdev\usr\sasewh\Node\ServerNext\webjmp\src\server\app_server\controllers\test.js:8:8

The last one is what I need.  So it's confusing to me that the doc suggests that you can set **moduleFilenameTemplate** on the plug-in and have it do something, but in my experience, that is not the case.  I also don't see either **fallbackModuleFilenameTemplate** or **devtoolFallbackModuleFilenameTemplate** in output having any effect, but maybe my scenario does not cause those options to get exercises.

Thanks,

Eric

**Comment by sokra** [comment]
What's about devtool set to **false**, plugin **moduleFilenameTemplate** set to absolute resource path?

**Comment by radcapitalist** [comment]
Nope.  That test case was included in my "If devtool is explicitly set to false, the path looks just like this no matter what...".  I tried it again today just to make sure, and call stacks have bundle paths, not paths into the original source code:

        at ./src/server/app_server/controllers/test.js.exports.fail (C:\jmpdev\usr\sasewh\Node\ServerNext\webjmp\build\bundle-server-dev.js:6725:8)

HTH,

Eric

**Comment by sokra** [comment]
It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by radcapitalist** [comment]
We have a couple developers who work on the Mac (foregoing information was for Windows).  On the Mac, things are a bit worse.  Using the same configuration that works on Windows, on Mac, WebStorm does not hit breakpoints *and* paths are missing the leading "/" in the traceback:

![call_stack_devtool_not_present](https://user-images.githubusercontent.com/19542060/53195745-5405e980-35e4-11e9-9a1a-633efc493e35.png)

(Notice the top line points to the bundle, not my original source code.  Interestingly, the second line of the traceback has the path correct, but that is an external (something out of node_modules)).

This is of course with `devtool: false` **not present** on the config file.  If I put `devtool: false` in the config file, WebStorm hits breakpoints, but paths in the traceback point to the bundle, not my source code.

![call_stack_devtool_false](https://user-images.githubusercontent.com/19542060/53195987-e0181100-35e4-11e9-8aa6-eb6f4c0425b3.png)

Eric

**Comment by radcapitalist** [comment]
I am going to try to find time to make a repro and upload it to github.

**Comment by radcapitalist** [comment]
Okay, I went and did it: Here is a github repository with pretty much the Express boilerplate project that shows all the issues I've described here.
https://github.com/radcapitalist/webpack-issues
All the info you need is in README.md.

**Comment by radcapitalist** [comment]
One more thing:  If I set the mode option in the Webpack config to "production" instead of "development", the generated source map does not seem to be used.  Call stacks point into the bundle, not to original source code.  But I need call stacks to be correct in production builds of my back-end code.  I added information about this to the repro README.md.

**Comment by sokra** [comment]
Ok I tried your repo `dev-4` and changed config to:

``` js
		new webpack.SourceMapDevToolPlugin({
			filename: "[file].map",
			fallbackModuleFilenameTemplate: '[absolute-resource-path]',
			moduleFilenameTemplate: '[absolute-resource-path]',
		}),
```

and it results in the expected stack traces:

```
*** FAILURE TEST ROUTE ***
Error: *** FAILURE TEST ROUTE ***
    at C:\Users\tobia\Repos\_\webpack-issues\src\server\routes\index.js:13:1
    at Layer.handle [as handle_request] (C:\Users\tobia\Repos\_\webpack-issues\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\tobia\Repos\_\webpack-issues\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\tobia\Repos\_\webpack-issues\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\tobia\Repos\_\webpack-issues\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\tobia\Repos\_\webpack-issues\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\tobia\Repos\_\webpack-issues\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\tobia\Repos\_\webpack-issues\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\tobia\Repos\_\webpack-issues\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\tobia\Repos\_\webpack-issues\node_modules\express\lib\router\index.js:47:12)
```

**Comment by radcapitalist** [comment]
Thanks so much for trying this out!  You are absolutely correct - with the combination of **fallbackModuleFilenameTemplate** + **moduleFilenameTemplate** being set as options to **webpack.SourceMapDevToolPlugin**, **and** the **source-map-support** plugin being installed using **BannerPlugin**, all is well.  

Whether `devtool: false` is present or not seems to make a minor difference but not a significant one in what I've seen so far.

That same change to the `mode: "production"` config solves its issues as well.

I have updated my linked repository with Tobias's changes.

Thanks again!  I am closing this issue.

Eric
