### ISSUE TITLE
Long term caching breaks when import changes from unused to used (or vice versa)

### ISSUE THREAD

**Issue by OliverJAsh** [webpack/webpack#8766]
Originally discussed on Twitter:
- https://mobile.twitter.com/OliverJAsh/status/1093634152769994757
- https://mobile.twitter.com/wSokra/status/1093795423901401088

# Bug report

**What is the current behavior?**
Reproduction case: https://github.com/OliverJAsh/webpack-chunks-caching-issue

Given

``` js
// webpack.config.js
module.exports = {
    mode: 'production',
    entry: {
        main: './src/main.js'
    },
    optimization: {
        minimize: false
    }
}
```

``` js
// ./src/shared.js
export const foo = 'foo';
export const bar = 'bar';
```

``` js
// ./src/main.js
import { foo, bar } from './shared';

// before (`bar` import is unused):
console.log(foo);
// after (`bar` import is used):
// console.log(foo, bar);

import('./other-chunk');
```

``` js
// ./src/other-chunk.js
import { foo } from './shared';

console.log(foo);
```

When I:
1. Run `webpack` twice: once with only the first `console.log`, and again with only the second.
2. Compare outputs

**Expected behaviour**
Contents of chunk `1.js` (`/src/other-chunk.js`)—and thereby its hash—should not change, to avoid breaking long term caching.

**Actual behaviour**
Contents do change. This seems to be because the *export* IDs are shifted.

![image](https://user-images.githubusercontent.com/921609/52506867-d5727a80-2be7-11e9-8212-55d8701a10fb.png)

![image](https://user-images.githubusercontent.com/921609/52506878-ddcab580-2be7-11e9-8dea-df972474acb5.png)

**Other relevant information:**
webpack version: 4.29.3

**Comment by OliverJAsh** [comment]
This is still open. Was it fixed by https://github.com/webpack/webpack/pull/8816? /cc @sokra

**Comment by evilebottnawi** [comment]
Bump

**Comment by evilebottnawi** [comment]
Fixed in `webpack@5`, hard to fix in `webpack@4`, sorry
