### ISSUE TITLE
webpack broken by ajv@6.9.0, "custom keyword definition is invalid: data.errors should be boolean"

### ISSUE THREAD

**Issue by sky-coding** [webpack/webpack#8768]
# Bug report

**What is the current behavior?**
A fresh install of webpack will fail to run with the error "custom keyword definition is invalid: data.errors should be boolean" due to the latest version of ajv. See issue here https://github.com/epoberezkin/ajv/issues/941 referencing many other broken projects.

**If the current behavior is a bug, please provide the steps to reproduce.**
Install webpack and attempt to use it.

**What is the expected behavior?**
I expect webpack not to fail due to unreliable, auto-updating dependencies.

**Other relevant information:**
webpack version:  4.28.4
Node.js version: 10.15.1
Operating System: Windows 10
Additional tools:

**Comment by joacub** [comment]
same here

**Comment by ivangajic** [comment]
Same

**Comment by RusseII** [comment]
I have the same issue.

**Comment by diegowifi** [comment]
Same issue, just happened after doing a ```npm install```

**Comment by lucasfarias2** [comment]
same, thanks for posting, this might be something new

**Comment by kmeraz** [comment]
😢 🚑

**Comment by ivangajic** [comment]
Quick fix, in node_modules\ajv\lib\keyword.js I commented out 
 if (!validateDefinition(definition))
      throw new Error('custom keyword definition is invalid: '  + this.errorsText(validateDefinition.errors));
and it works, still waiting for fix

**Comment by diegowifi** [comment]
@ivangajic yes, that does the trick for now 👍

**Comment by devx97** [comment]
pls men fest repair

**Comment by acro5piano** [comment]
I've created minimal reproduction: https://github.com/acro5piano/webpack-issues-8768

**Comment by JesusViveros12** [comment]
@ivangajic, what's the line in the file? i don't found 😢 I have the same issue with my angular 7 project

**Comment by ivangajic** [comment]
> @ivangajic, what's the line in the file? i don't found 😢 I have the same issue with my angular 7 project

That's 64 and 65

**Comment by devx97** [comment]
@JesusViveros12 
node_modules/ajv/lib/keyword.js
64 and 65

**Comment by tyteen4a03** [comment]
Or add this to your `package.json`:

```
  "resolutions": {
    "ajv": "6.8.1"
  }
```

**Comment by youngzaphod** [comment]
> Or add this to your `package.json`:
> 
> ```
>   "resolutions": {
>     "ajv": "6.8.1"
>   }
> ```

Seems so simple I would love it to work, but getting same error, anything else I should look at?

**Comment by acro5piano** [comment]
@tyteen4a03 Thanks, it works!

**Comment by JesusViveros12** [comment]
@ivangajic , i have different code in these lines:

![image](https://user-images.githubusercontent.com/44211181/52527825-b5e55b80-2c94-11e9-906f-262b4470594d.png)

I'll try with the @tyteen4a03 solution too

**Comment by devx97** [comment]
> > Or add this to your `package.json`:
> > ```
> >   "resolutions": {
> >     "ajv": "6.8.1"
> >   }
> > ```
> 
> Seems so simple I would love it to work, but getting same error, anything else I should look at?

Have you reinstalled your packages with npm install? ;p

**Comment by ivangajic** [comment]
@JesusViveros12 
Should be somewhere at the beginning of the addKeyword function, if not, maybe you're using different version

**Comment by jackturnbull** [comment]
Note that reolutions is a yarn feature and not an npm feature. From the linked ajv issue:

> just add
> 
> ```
>   "resolutions": {
>     "ajv": "6.8.1"
>   }
> ```
> 
> to your package.json
> 
> if you use yarn:
> run `yarn install`
> 
> if you use npm:
> https://github.com/rogeriochaves/npm-force-resolutions TL;DR
> 
> ```
> rm -rf node_modules
> npx npm-force-resolutions
> npm install
> ```

**Comment by arielwolffe** [comment]
> > > Or add this to your `package.json`:
> > > ```
> > >   "resolutions": {
> > >     "ajv": "6.8.1"
> > >   }
> > > ```
> > 
> > 
> > Seems so simple I would love it to work, but getting same error, anything else I should look at?
> 
> Have you reinstalled your packages with npm install? ;p

I did, didn't seem to fix it for me either.

**Comment by tyteen4a03** [comment]
@jackturnbull Thanks - I was just about to clarify.

**Comment by youngzaphod** [comment]
npm 

> > > > Or add this to your `package.json`:
> > > > ```
> > > >   "resolutions": {
> > > >     "ajv": "6.8.1"
> > > >   }
> > > > ```
> > > 
> > > 
> > > Seems so simple I would love it to work, but getting same error, anything else I should look at?
> > 
> > 
> > Have you reinstalled your packages with npm install? ;p
> 
> I did, didn't seem to fix it for me either.

Didn't at first, but just did an no luck. I'm looking in the package-lock.json file and seeing it still has the code below, would that make a difference? New to all this.

`"ajv": {
      "version": "6.9.0",
      "resolved": "https://registry.npmjs.org/ajv/-/ajv-6.9.0.tgz",
      "integrity": "sha512-VsK2jpqRno3Hn+at4NGtBRpR5q3OW7n5INrTKqENDNQJB99DXATQEVHlnoD1BA7Uo/qGO+ijGA/vgSAlxP9E4A==",
      "requires": {
        "fast-deep-equal": "^2.0.1",
        "fast-json-stable-stringify": "^2.0.0",
        "json-schema-traverse": "^0.4.1",
        "uri-js": "^4.2.2"
      }
    },`

**Comment by tyteen4a03** [comment]
@youngzaphod Please see updated comment for npm (or switch to Yarn)

**Comment by ItsLeeOwen** [comment]
updating package-lock.json dependencies worked on my end.

https://stackoverflow.com/a/48524488

```json
"ajv": {
	"version": "6.8.1",
	"resolved": "https://registry.npmjs.org/ajv/-/ajv-6.8.1.tgz",
	"integrity": "sha512-eqxCp82P+JfqL683wwsL73XmFs1eG6qjw+RD3YHx+Jll1r0jNd4dh8QG9NYAeNGA/hnZjeEDgtTskgJULbxpWQ==",
	"requires": {
		"fast-deep-equal": "^2.0.1",
		"fast-json-stable-stringify": "^2.0.0",
		"json-schema-traverse": "^0.4.1",
		"uri-js": "^4.2.2"
	}
},
```

**Comment by amertoukan** [comment]
> Quick fix, in node_modules\ajv\lib\keyword.js I commented out
> if (!validateDefinition(definition))
> throw new Error('custom keyword definition is invalid: ' + this.errorsText(validateDefinition.errors));
> and it works, still waiting for fix

This worked with me

**Comment by Sergej-Popov** [comment]
Another option is to lockdown to 4.28.x
```
"webpack": "~4.28.0"
```

**Comment by DarkLink363** [comment]
To fix this error, just change:
`errors: 'full',`
to:
`errors: true`
in file **node_modules\ajv-errors\index.js**

**Comment by lenoraporter** [comment]
"resolutions": {
    "ajv": "6.8.1"
  }

with yarn install worked for me.

**Comment by ivangajic** [comment]
@DarkLink363 
Works :)

**Comment by youngzaphod** [comment]
> @youngzaphod Please see updated comment for npm (or switch to Yarn)

Damn, I tried all that, went over to https://github.com/rogeriochaves/npm-force-resolutions and followed instructions there, and now I'm getting a "Cannot find module uri-js" error. Looks like the original error is gone though - progress!

**Comment by JesusViveros12** [comment]
> @JesusViveros12
> Should be somewhere at the beginning of the addKeyword function, if not, maybe you're using different version

Sorry! One mistake.
My i have 2 files called "keyword.js" into my node_modules, the correct is: 
`node_modules/schema-utils/node_modules/ajv/lib/keyword.js`

![image](https://user-images.githubusercontent.com/44211181/52527982-f1355980-2c97-11e9-9900-7009dae2b422.png)

It's works now! :)

**Comment by ericelliott** [comment]
Would this failure have been prevented if Webpack pinned all versions in `package.json`, and only updated them when all tests pass?

**Comment by mochilor** [comment]
> > @youngzaphod Please see updated comment for npm (or switch to Yarn)
> 
> Damn, I tried all that, went over to https://github.com/rogeriochaves/npm-force-resolutions and followed instructions there, and now I'm getting a "Cannot find module uri-js" error. Looks like the original error is gone though - progress!

I  had the same problem. For me it only worked after installing yarn: https://yarnpkg.com/lang/en/docs/install/#debian-stable

Then run `yarn`.

**Comment by youngzaphod** [comment]
> > > @youngzaphod Please see updated comment for npm (or switch to Yarn)
> > 
> > 
> > Damn, I tried all that, went over to https://github.com/rogeriochaves/npm-force-resolutions and followed instructions there, and now I'm getting a "Cannot find module uri-js" error. Looks like the original error is gone though - progress!
> 
> I had the same problem. For me it only worked after installing yarn: https://yarnpkg.com/lang/en/docs/install/#debian-stable
> 
> Then run `yarn`.

Did you see the uri-js error also? After getting, that, I just installed uri-js and ran npm start again, and it seems to be working now. I'll try yarn if I run into further issues.

**Comment by aarontaylor** [comment]
@DarkLink363 that worked so thank you! 

This is enough to get by for the moment.

**Comment by agoiabel** [comment]
@youngzaphod, how did you install url-js

**Comment by mochilor** [comment]
@youngzaphod Yes, I saw the same error, and then installed yarn. I'm glad you also solved the problem in one way or another!

**Comment by jackturnbull** [comment]
> Would this failure have been prevented if Webpack pinned all versions in `package.json`, and only updated them when all tests pass?
> 
> I see this comment has a few thumbs downs already, but no discussion about _why_ it's a bad idea. I use this strategy in several open-source libraries with lots of projects depending on them. If it's a bad idea, I'd like to know why. Please educate me.

@ericelliott I can't say for certain on the downvotes as I would say that it's a reasonable enough suggestion on balance. In the strictest sense of the phrase, this breakage on a minor update from an upstream package would mean that semver hasn't been adhered to. By that I mean these sorts of breakages shouldn't occur on a minor version bump, which is what we've seen here, so by extension I couldn't say webpack are _at fault_ for not being more strict with their pinning.

The flip side is that perfect semver relies on perfect test suites and zero human error, which exists only in imagination, so your suggestion carries some value.

**Comment by jeffersonvalera** [comment]
Worked for me,
npm uninstall ajv
npm install ajv@6.8.1

**Comment by jaydenseric** [comment]
@ericelliott because pinning dependencies in anything published to npm is an anti-pattern. Imagine how bloated `node_modules` would be if thousands of nested dependencies pinned thousands of different versions. Also, consumers miss out on important patches until you get around to updating your pinned dependencies and publish a new version.

**Comment by ericelliott** [comment]
@jaydenseric I disagree strongly for actively maintained projects with lots of dependents. I added some tooling to help automate maintenance to keep dependencies up-to-date without risking breaking downstream projects.

> Dependency updates can be maintained automatically by something like the [renovate bot](https://renovatebot.com/), or pseudo-manually using [updtr](https://github.com/peerigon/updtr).

**Comment by youngzaphod** [comment]
> @youngzaphod, how did you install url-js

Easy peasy:
`npm install uri-js`

Which I got from here: https://www.npmjs.com/package/uri-js  (you gotta scroll down a while to the Usage section).

**Comment by hamit-zor** [comment]
Dealing with same issue!

**Comment by nickatnight** [comment]
> Worked for me,
> npm uninstall ajv
> npm install ajv@6.8.1

Thank you for this :D

**Comment by marcogpinto** [comment]
For those who "resolutions" method doesn't work, for some reason, just explicitly define "ajv": "6.8.1" in your package.json dependencies.

**Comment by MattGerard** [comment]
> For those who "resolutions" method doesn't work, for some reason, just explicitly define "ajv": "6.8.1" in your package.json dependencies.

This is working for me.

**Comment by mosesfinlay** [comment]
> npm uninstall ajv
> npm install ajv@6.8.1

This worked for me!

**Comment by mazer-rakham** [comment]
> Worked for me,
> npm uninstall ajv
> npm install ajv@6.8.1

Also working for me.

**Comment by damianobarbati** [comment]
Not working for me: help!

**Comment by blubMe** [comment]
same :/

**Comment by mazer-rakham** [comment]
> Not working for me: help!
Make sure your package.lock is also updating with the older ajv
![image](https://user-images.githubusercontent.com/11220261/52528224-fc43b600-2ca6-11e9-94d9-41b8b7a05df6.png)

**Comment by damianobarbati** [comment]
Sadly it is 😥

<img width="883" alt="screenshot 2019-02-10 at 02 14 17" src="https://user-images.githubusercontent.com/2225869/52528234-aa685380-2cd9-11e9-9c9d-eea6a492128c.png">

<img width="723" alt="screenshot 2019-02-10 at 02 14 36" src="https://user-images.githubusercontent.com/2225869/52528235-ad634400-2cd9-11e9-848b-72bfca2ea562.png">

**Comment by damianobarbati** [comment]
@mazer-rakham I'm using yarn: should I stick to npm to have it work?

**Comment by damianobarbati** [comment]
OK "resolutions" trick posted by @tyteen4a03 works

**Comment by mazer-rakham** [comment]
Looks liek he just rolled out a fix, maybe try recreating your create-react-app if can i will test.

https://github.com/fkleuver/ajv/commit/2f8806b9b7cc721045ac5e15d5e290b71abe78d5

**Comment by fkleuver** [comment]
Ran into this when updating the dev deps for Aurelia, it breaks just about everything. I have a PR open here: https://github.com/epoberezkin/ajv/pull/943

**Comment by Code4Three** [comment]
> Worked for me,
> npm uninstall ajv
> npm install ajv@6.8.1

This worked for. 
Cheers!!

**Comment by jeffersonvalera** [comment]
> Not working for me: help!

After 
npm unistall ajv
npm install ajv@6.8.1
/{projectname}/node_modules/webpack/package.json

try setting 
"_phantomChildren": {
    "ajv": "6.8.1",.......

**Comment by bellcc** [comment]
> Worked for me,
> npm uninstall ajv
> npm install ajv@6.8.1

Worked like a charm!

**Comment by hamzaBentahar** [comment]
What worked for me is to comment the line that throws the error in : node_modules\ajv\lib\keyword.js
thank you [ivangajic](/ivangajic)

**Comment by hiroppy** [comment]
It is fixed so let's wait a little more:) https://github.com/fkleuver/ajv/commit/2f8806b9b7cc721045ac5e15d5e290b71abe78d5

**Comment by yangchongduo** [comment]
Awesome

**Comment by arkhamRejek** [comment]
if it's not working for you after the resolutions addition to your packages, delete node modules before running the install and it should work.

**Comment by fkleuver** [comment]
@hiroppy The question is, when will the owner of the project be online again. I have a feeling he published right before going to bed, so it may take a few more hours at least before he's around and notices my PR :-) (and then the question is will he like the solution or not)

**Comment by tgrlbyrk** [comment]
> ### If you use yarn
> add below to package.json
> 
> ```
>   "resolutions": {
>     "ajv": "6.8.1"
>   }
> ```
> then run `yarn install`
> 
> ### if you use npm
> ```
> npm uninstall ajv
> npm install ajv@6.8.1
> ```

it took my 2 hours... you saved me!

**Comment by Gabrielfcs** [comment]
> npm uninstall ajv
npm install ajv@6.8.1 

Thanks, it works for me!

**Comment by jsbroks** [comment]
> npm uninstall ajv
> npm install ajv@6.8.1

When using this method it set ajv to `^6.8.1` for me, make sure it is just `6.8.1`.

**Comment by meep26** [comment]
![image](https://user-images.githubusercontent.com/35859813/52529536-d6adbf80-2d2d-11e9-9ee8-aa1a05ad1885.png)


Thanks for sharing. This will do the trick!

**Comment by ArchambaultP** [comment]
Hey, so I'm having trouble with this using docker-compose. any tips ?

**Comment by paichunwang** [comment]
In my MERN application im not using webpack, but still getting this error, any tipes? I tried replacing "ajv" but cant find it in node_modules and manual install doesn't seem to work, any tips on temp fixing this? Thanks!

**Comment by maisonm** [comment]
> ### If you use yarn
> add below to package.json
> 
> ```
>   "resolutions": {
>     "ajv": "6.8.1"
>   }
> ```
> then run `yarn install`
> 
> ### if you use npm
> ```
> npm uninstall ajv
> npm install ajv@6.8.1
> ```

This worked for me.

**Comment by jsbroks** [comment]
@ArchambaultP 
add
```
RUN npm uninstall ajv
RUN npm install ajv@6.8.1
```
to the dockerfile

**Comment by TheLarkInn** [comment]
Hey everyone thanks for all the quick feedback. We will reach out to AJV and see if we can tighten up the communication channels for their API and will consider pinning this dep for the future. I will lock the thread once I get off mobile (bad winter storm here right now and losing power intermittently 😂🥶)

**Comment by TheLarkInn** [comment]
Note that I just locked it as "resolved" not because the issue is fixed, but because we are aware of the issue and there are workarounds posted above. <3 Thanks for the patience and understanding everyone.

**Comment by sokra** [comment]
Fixed

**Comment by TheLarkInn** [comment]
TY @sokra was just checking on it ❤️
