### ISSUE TITLE
crash if require() not found

### ISSUE THREAD

**Issue by DelvarWorld** [webpack/webpack#877]
If you `require()` a file that doesn't exist, webpack will crash, at least when running watch

    node_modules/webpack/node_modules/watchpack/node_modules/chokidar/lib/index.js:289
      return Boolean(4 & parseInt((stats.mode & 0x1ff).toString(8)[0], 10));
                                        ^
    TypeError: Cannot read property 'mode' of undefined
        at EventEmitter.FSWatcher._hasReadPermissions (node_modules/webpack/node_modules/watchpack/node_modules/chokidar/lib/index.js:289:37)
        at EventEmitter.<anonymous> (node_modules/webpack/node_modules/watchpack/node_modules/chokidar/lib/fsevents-handler.js:296:13)
        at Object.oncomplete (fs.js:107:15)
    make: *** [watch] Error 8

**Comment by sokra** [comment]
Looka like a chokidar issue.

**Comment by BowlingX** [comment]
+1 same issue here

**Comment by sokra** [comment]
@es128

**Comment by es128** [comment]
Odd... chokidar handles watching non-existent files just fine on its own. Anyway, should be easy enough to bail out early there if `stats` isn't available.

**Comment by es128** [comment]
You must be setting the `ignorePermissionErrors` option. I'm finding bugs related to that. Should be able to get it fixed shortly.

**Comment by sokra** [comment]
@es128 If it helps: https://github.com/webpack/watchpack/blob/master/lib/DirectoryWatcher.js#L21-L28

**Comment by akre54** [comment]
+1 getting this too.

**Comment by chcokr** [comment]
+1

**Comment by bdefore** [comment]
+1

**Comment by es128** [comment]
Should be resolved in chokidar master branch. Would appreciate if any of you who have run into this problem can validate. Will be publishing and updated version soon.

**Comment by bdefore** [comment]
@es128 If I clone the latest chokidar into `webpack/node_modules/watchpack/node_modules/` it gives an error but does not crash like previously. In fact, I am now just realizing that it would only crash if the misspelling was in a directory, not in the filename. Looks good to me.

**Comment by es128** [comment]
What's the error? Is it expected?

**Comment by bdefore** [comment]
`ERROR in ./scripts/webpack_only.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../../app/asseasts/stylesheets/public.scss in /Users/d4/code/ga/profiles/client/scripts
 @ ./scripts/webpack_only.jsx 13:0-53`

**Comment by es128** [comment]
Doesn't seem related to chokidar anymore

**Comment by sokra** [comment]
@es128 :+1:

**Comment by bdefore** [comment]
I believe that whatever change chokidar has made in master has fixed the issue.

**Comment by aintnorest** [comment]
Cloned master in and still get the following error also as a side thought i don't set ignorePermissionErrors: /src/vizidrix/src/github.com/aintnorest/wearshareReact/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/lib/index.js:289
  return Boolean(4 & parseInt((stats.mode & 0x1ff).toString(8)[0], 10));
                                    ^
TypeError: Cannot read property 'mode' of undefined
    at EventEmitter.FSWatcher._hasReadPermissions (/src/vizidrix/src/github.com/aintnorest/wearshareReact/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/lib/index.js:289:37)
    at EventEmitter.<anonymous> (/src/vizidrix/src/github.com/aintnorest/wearshareReact/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/lib/fsevents-handler.js:296:13)
    at Object.oncomplete (fs.js:107:15)

**Comment by es128** [comment]
@aintnorest you're actually still running 1.0.0-rc4 there, not master branch. Can tell based on the call stack.

**Comment by aintnorest** [comment]
You obviously must know what your talking about but that puts me at a loss since I copied them over by hand. I just deleted it and cloned down a new version and got the same thing again. Since this only seems to be a problem when I miss spell I won't worry about it but odd.

/src/vizidrix/src/github.com/aintnorest/wearshareReact/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/lib/index.js:289
  return Boolean(4 & parseInt((stats.mode & 0x1ff).toString(8)[0], 10));
                                    ^
TypeError: Cannot read property 'mode' of undefined
    at EventEmitter.FSWatcher._hasReadPermissions (/src/vizidrix/src/github.com/aintnorest/wearshareReact/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/lib/index.js:289:37)
    at EventEmitter.<anonymous> (/src/vizidrix/src/github.com/aintnorest/wearshareReact/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/lib/fsevents-handler.js:296:13)
    at Object.oncomplete (fs.js:107:15)

**Comment by bebraw** [comment]
@DelvarWorld Safe to close?

**Comment by harole** [comment]
I have the some problem. In the case, I try to load a file by "require('filename')", but I do not know that the file exist or not. Anyone can help me? Thank you!

**Comment by bebraw** [comment]
@harole Would it be enough if you surrounded the `require` in a `try/catch`? That wouldn't crash. And you could deal with the failure case if there's one.

**Comment by DelvarWorld** [comment]
I haven't seen this since - doing my part to help clean up old issues!
