### ISSUE TITLE
Provide option to disable __WEBPACK_IMPORTED_MODULE_

### ISSUE THREAD

**Issue by inoyakaigor** [webpack/webpack#8778]
## Feature request

Provide an option to disable `__WEBPACK_IMPORTED_MODULE_`

**What is the expected behavior?**

An option in webpack.config.js to disable add `__WEBPACK_IMPORTED_MODULE_` for imported files

**What is motivation or use case for adding/changing the behavior?**

When I debug code in DevTools long names of imported files makes a lot of visual noise and code strings is too long. It's hard to reading and understanding.

Examples:
I commented out a code where this prefix is added. Code still works, more readable, and shorten.
Before:
![image](https://user-images.githubusercontent.com/1235286/52641877-e1fa1a00-2eea-11e9-9e3f-efd0dd555e6f.png)

After: 
![image](https://user-images.githubusercontent.com/1235286/52641657-69935900-2eea-11e9-97b1-51953911bbf9.png)

**How should this be implemented in your opinion?**
An option on same level with `devtool` option

**Are you willing to work on this yourself?**
yes (with additional instructions what and where I should to do)

**Comment by evilebottnawi** [comment]
@inoyakaigor You should use `devtool` where `quality` = `original source` https://webpack.js.org/configuration/devtool/#devtool. It is expected behavior.
