### ISSUE TITLE
acorn not installed, but it's a peerDependency of acorn-dynamic-import

### ISSUE THREAD

**Issue by worc** [webpack/webpack#8779]
versions:
* node 10.15.1
* npm 6.7.0
* @storybook/react ^4.1.11 (which requires webpack@^4.23.1)

when i install just @storybook/react into my project, i get the following error:

`npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.`

i've looked into acorn-dynamic-import (a plugin for acorn), and the issue isn't on their end. i've looked into acorn, but they're the main library and the problem isn't with them. i've looked into @storybook/react, but they're merely requiring webpack, the problem isn't with them. i've also opened a ticket with npm to see if there's a dependency resolution issue somewhere. the last place i haven't checked with is you guys, though i have my doubts here, both acorn and acorn-dynamic-import are "peer" dependencies in your dependency list. 

i've been chasing this issue for a few weeks now, and i can't seem to get any traction with it. but if there's any thoughts on what else i should be looking into, that would be super helpful. the last bit that seems like it might be off is that webpack is using yarn, but i'm using npm in my project for dependency installation.

**Comment by sokra** [comment]
It's an npm bug. See #8656

**Comment by worc** [comment]
there's an incoming fix for npm@6.8.0 (which hasn't dropped yet)

https://npm.community/t/unmet-peerdependency-but-its-listed-as-a-dependency/5322

**Comment by jaydenseric** [comment]
npm reverted @sokra's fix for the final npm@6.8.0 release: https://github.com/npm/cli/pull/152

It's unclear when npm will get around to fixing the issue.

**Comment by worc** [comment]
oof. it's been like this for **years**, so i guess it's not that bad to just keep using yarn. but man, that's a strange decision on their part.

**Comment by ekkis** [comment]
I have the problem with 6.10.3
