### ISSUE TITLE
Calling webpack(options, function(error) {}) never returns error, silently fails

### ISSUE THREAD

**Issue by DelvarWorld** [webpack/webpack#878]
If your source JS is invalid (either from a syntax error or from a missing require), running webpack on the command line will correctly show the error, for example `Unexpected token`. However, when running something like this:

    webpack(config, function(err) {
        if(err) {
          console.log(err);
          throw err;
        }
    });

nothing happens! Config is the same one used when run from the command line. I was trying to trace the source code a bit, it doesn't appear the errors happen anywhere in `Compiler.prototype.run`, so maybe there's some incorrect implementation with the tapable library?

**Comment by sokra** [comment]
http://webpack.github.io/docs/node.js-api.html#error-handling

``` js
webpack(config, function(err, stats) {
    if(err) {
      console.log(err);
      throw err;
    }
    console.log(stats.compilation.errors);
});
```

**Comment by DelvarWorld** [comment]
Ah, thank you! That didn't seem obvious since the very first example on that page makes it look like you can just do `function(err)`, with the "correct" way being a footnote :( that you wouldn't even know to look for. Either way, this doesn't seem properly "node-y" which passes *any* error as the first argument - I don't know what the webpack desired code style is but what about making any error go on that first argument? It might be less confusing.

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#103
