### ISSUE TITLE
Webpack does not process css files from node_modules in production mode

### ISSUE THREAD

**Issue by maksimsemenov** [webpack/webpack#8782]
# Bug report

**What is the current behavior?**
I'm importing css files from a third party library (installed in node_modules) into my main entry point. When I run webpack in `development` mode, the css files are correctly processed and extracted into the separate css file.
However, in `production` mode the css files are not processed at all.

**If the current behavior is a bug, please provide the steps to reproduce.**
Please take a look at [GitHub repository](https://github.com/maksimsemenov/webpack-css-issue)
Run:
```
yarn install

yarn build
yarn build:dev
```

Check the output of those commands. The webpack that run in `development` has a css files in the output, while the one that was in `production` does not.

**What is the expected behavior?**
Webpack should process css files from node_modules that are imported into entry point in `development` and `production` modes.

**Other relevant information:**
webpack version: 4.28.4
Node.js version: 11.6.0
Operating System: macOS Mojave
Additional tools: yarn 1.13.0

**Comment by evilebottnawi** [comment]
You have invalid configuration. Check example https://github.com/webpack-contrib/mini-css-extract-plugin#extracting-all-css-in-a-single-file.

Don't do `splitChunks` in `development`, it is not recommended and increase build time.

**Comment by maksimsemenov** [comment]
I'm sorry @evilebottnawi, I don't quite understand why you closed the issue. I have the same configuration that you provided (I omitted the 'name' param in `splitChunks.cacheGroups.styles` but it does not make any difference. I updated the repo and the issue is still there.

I use identical `dev` and `prod` config (the only difference is mode) to make it easier to spot the difference in output files.

The issue is not webpack being slow in `development` mode. The issue is that webpack does not process certain files (CSS styles from `node_modules`) in **production** mode.

Please reopen the issue.
