### ISSUE TITLE
Cannot assign to read only property 'name' of function

### ISSUE THREAD

**Issue by natew** [webpack/webpack#8787]
**What is the current behavior?**

Getting a runtime error only when running in `--target electron-renderer`.

It's happening when requiring the module `react-markdown` => `unified` => `vfile`, but the error happens because it hits this area and is processing `faker`, which has a file named `name`. Assigning it here causes the error:

![image](https://user-images.githubusercontent.com/12100/52805865-627c6000-303c-11e9-86fd-2d32cca6ce9c.png)

```
Uncaught (in promise) TypeError: Cannot assign to read only property 'name' of function 'function Require(name) {
	    if (name === undefined) return void ParseModuleData();
	    var id = GetIDForModu...<omitted>...	}'
    at AddModuleEntry (bundle.js:269467)
    at ParseModuleData (bundle.js:269434)
    at GetIDForModule (bundle.js:269474)
    at Require (bundle.js:269480)
    at Object.path (bundle.js:309851)
    at __webpack_require__ (bundle.js:767)
    at fn (bundle.js:130)
    at Object../node_modules/vfile/core.js (bundle.js:268994)
    at __webpack_require__ (bundle.js:767)
    at fn (bundle.js:130)
    at Object../node_modules/vfile/index.js (bundle.js:269176)
    at __webpack_require__ (bundle.js:767)
    at fn (bundle.js:130)
    at Object../node_modules/unified/index.js (bundle.js:267839)
    at __webpack_require__ (bundle.js:767)
    at fn (bundle.js:130)
    at Object../node_modules/react-markdown/lib/react-markdown.js (bundle.js:242511)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

This just started happening without much change, so I'm not sure what happened. We changed some runtime code but modules stayed the same. So I'm a little confused how to.

**What is the expected behavior?**

**Other relevant information:**
webpack version:  4.29.3 and 4.28.x
Node.js version: 10.10.0
Operating System: OSX Mojave

**Comment by natew** [comment]
Isolated the issue.

Psuedo code, before (working):

```
import 'electron-context-menu'
``

After:

```
function start() {
  if (process.env.SOMETHING === "true") {
     require('electron-context-menu')
  }
}
```

**Comment by sokra** [comment]
The code you screenshot is not webpack code. From which module is it?

**Comment by sokra** [comment]
Maybe try to run with `devtool: "eval"` to get a better stacktrace

**Comment by natew** [comment]
Funny when you re-run into old issues you forgot you opened, in a totally different context!

For some reason this only happens occasionally, if I refresh it goes away usually.

![image](https://user-images.githubusercontent.com/12100/57198913-852c5f80-6f2d-11e9-9b85-3d80f1ec2ba5.png)

Relevant line of code:

![image](https://user-images.githubusercontent.com/12100/57198916-95443f00-6f2d-11e9-95f1-2efe002de492.png)

I believe this code is from my index.html header:

![image](https://user-images.githubusercontent.com/12100/57198928-c755a100-6f2d-11e9-9811-24506dba241b.png)

I remember this being documented somewhere as a strategy to preserve the electron require. We support both electron/non-electron so I do this.

**Comment by evilebottnawi** [comment]
@natew problem still exists?
