### ISSUE TITLE
mode: 'production' conflicts with MiniCssExtractPlugin

### ISSUE THREAD

**Issue by damodog** [webpack/webpack#8792]
# Bug report

**What is the current behavior?**
Using `mode: 'production'` in conjunction with MiniCssExtractPlugin is preventing css from getting added to app.bundle.js (and the /dist folder). So it's not getting injected into the built index.html file.

The css file does correctly get added in development though.

I initially raised a SO question on this but luckily someone on Gitter found the cause of my issue. Changing `mode: 'production'` to `mode: 'none'` in my webpack.prod config file fixed this for me. 
https://stackoverflow.com/questions/54707928/css-not-added-to-dist-folder-using-webpack-4-and-minicssextractplugin

**If the current behavior is a bug, please provide the steps to reproduce.**
Please see repo here: https://github.com/damodog/webpack4-boilerplate

- Clone repo and after installing node packages run `npm start`. 
- Break out of that and run `npm run build`
- Notice the hashed app.css isn't present in the Asset list

<img width="1138" alt="screen shot 2019-02-15 at 10 58 39" src="https://user-images.githubusercontent.com/1637410/52854739-5e714080-3117-11e9-83bc-7c20d6b41a50.png">

**What is the expected behavior?**
The css should get bundled and added to the dist/css folder and injected into the dist/index.html file.

<img width="1133" alt="screen shot 2019-02-15 at 11 26 02" src="https://user-images.githubusercontent.com/1637410/52855007-26b6c880-3118-11e9-9dd7-a22328e95ec6.png">

**Other relevant information:**
webpack version:  4.29.3
Node.js version: v11.6.0
Operating System: macOs Sierra (10.12.6)
Additional tools:

**Comment by evilebottnawi** [comment]
Please reduce your minimum reproducible test repo. Also it is works for many developers for a long time so it is invalid configuration

**Comment by damodog** [comment]
@evilebottnawi Ok I'll try to get one created. I know this is a issue forum but does anything stand out as wrong in the config files in my repo? I've followed the docs which is why I'm unsure as to how the css wouldn't get included in the bundle. Is using `mode: 'none'` ok to have in my production config file?

**Comment by evilebottnawi** [comment]
@damodog no, we recommended use `mode: 'production'`

**Comment by damodog** [comment]
I've just rebuilt my Wwebpack boilerplate from scratch bit by bit and I cannot replicate the issue I was experiencing. Very strange!
