### ISSUE TITLE
module.hot.accept is transforming code incorrectly

### ISSUE THREAD

**Issue by rgranger** [webpack/webpack#8794]
# Bug report

**What is the current behavior?**

Webpack is transforming code incorrectly.
I'm not sure if it is Babel or Webpack, but my first guess is Webpack.

My Code :

```js
setupHMR () {
    if (module.hot) {
      // Setup hot module replacement
      module.hot.accept('ROUTES/make-routes', () => {
        setImmediate(() => {
          ReactDOM.unmountComponentAtNode(this.mountNode)
          this.routes = require('ROUTES/make-routes').default(this.store)
          this.render()
        })
      })
    }
  }
```

Transformed Code :

```js
setupHMR() {
    if (true) {
      // Setup hot module replacement
      module.hot.accept(/*! ROUTES/make-routes */ "./src/client/routes/desktop/make-routes.js", function(__WEBPACK_OUTDATED_DEPENDENCIES__) { /* harmony import */ ROUTES_make_routes__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ROUTES/make-routes */ "./src/client/routes/desktop/make-routes.js");
(() => {
        setImmediate(() => {
          react_dom__WEBPACK_IMPORTED_MODULE_3___default.a.unmountComponentAtNode(this.mountNode);

          this.routes = __webpack_require__(/*! ROUTES/make-routes */ "./src/client/routes/desktop/make-routes.js").default(this.store);
          this.render();
        });
      })(__WEBPACK_OUTDATED_DEPENDENCIES__); });
    }
  }
```

The problem here is `function(__WEBPACK_OUTDATED_DEPENDENCIES__)` whereas I put an arrow function in the module.hot.accept callback. Thus the `this`, which is perfectly legal in my code, becomes incorrect after Webpack transformation.

**If the current behavior is a bug, please provide the steps to reproduce.**

see code

Here is the babel config (in case Webpack isn't the culprit).

```js
export const BABEL_CONFIG_BROWSER = {
  cacheDirectory: false,
  babelrc: false,
  plugins: [
    '@babel/plugin-transform-runtime',
    ['@babel/plugin-proposal-class-properties', { loose: true }],
  ],
  presets: [
    ['@babel/preset-env', {
      targets: '> 1% and last 2 versions, not dead, not IE <= 11',
      modules: false,
    }],
    '@babel/preset-react',
  ],
  env: {
    production: {
      plugins: [
        'babel-plugin-transform-react-remove-prop-types',
        '@babel/plugin-transform-react-constant-elements',
      ]
    }
  },
}
```

**What is the expected behavior?**

`function(__WEBPACK_OUTDATED_DEPENDENCIES__)` should be `(__WEBPACK_OUTDATED_DEPENDENCIES__) => ...`

**Other relevant information:**
webpack version:  4.29.0
Node.js version: 10.15.0
Operating System: Windows 10
Additional tools: Babel 7

**Comment by sokra** [comment]
Yep webpack issue. For compat reasons we can't use arrow functions, but a solution would be to use `.bind(this)`. Do you want to send a PR?

**Comment by rgranger** [comment]
How do i send a PR ?

I tried cloning the repo and pushing a new branch but github tells me I don't have the correct access rights.

Anyways, the correction should be in this file :

https://github.com/webpack/webpack/blob/8a7597aa6eb2eef66a8f9db3a0c49bcb96022a94/lib/dependencies/HarmonyAcceptDependency.js#L37

replace

```js
source.insert(dep.range[1], ")(__WEBPACK_OUTDATED_DEPENDENCIES__); }");
```

with

```js
source.insert(dep.range[1], ")(__WEBPACK_OUTDATED_DEPENDENCIES__); }.bind(this)");
```

**Comment by sokra** [comment]
> How do i send a PR ?

You need to "Fork" the project.

https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by rgranger** [comment]
Here is the PR : https://github.com/webpack/webpack/pull/8803

Unfortunately, I don't have that much time to fix the linting, or other, issues, so I'll leave you guys to it.

**Comment by ShootPassSlam** [comment]
Since the above pull request was merged with master, should this Issue be closed?

#8803

**Comment by rgranger** [comment]
Yes, the issue has been correctly fixed by the PR. I'm closing this issue.
