### ISSUE TITLE
Webpack 4.29.4 depends on unpublished long@4.0.1 via git

### ISSUE THREAD

**Issue by leonyu** [webpack/webpack#8795]
# Bug report

**What is the current behavior?**
Latest webpack (4.29.4) pulls in `long@4.0.1` using Git. 

[long](https://www.npmjs.com/package/long) is still on 4.0.0, so 4.0.1 hasn't been published yet. This mean it is doing so via `git`, which creates a hard dependency on `git` for projects bundled with webpack. This creates issues w/CI pipelines that do not use `git`. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Simply install webpack with yarn/npm and inspect the lock files, and you should see something like: 
```
long "git://github.com/dcodeIO/long.js.git#8181a6b50a2a230f0b2a1e4c4093f9b9d19c8b69"
```

**What is the expected behavior?**

Webpack itself should not have a dependency on `git`. This is an unnecessary dependency for CI/build systems. 

**Other relevant information:**
webpack version:  4.29.4
Node.js version: v8.15.0
Operating System: Ubuntu 18.04.2 LTS 
Additional tools:

**Comment by xtuc** [comment]
Duplicated of https://github.com/xtuc/webassemblyjs/issues/486

**Comment by sokra** [comment]
Yeah that's an issue. We should fix that and setup a linting step to check the lockfile for git references.

**Comment by FloppyThePenguin** [comment]
![capture](https://user-images.githubusercontent.com/42390605/52906194-7aa2d980-320c-11e9-9d80-75a08e303a3f.PNG)
Webpack@latest

**Comment by Airkro** [comment]
If you using yarn, a temporary solution:
```json
// package.json
"resolutions": {
   "long": "4.0.0"
}
```

**Comment by sagitsofan** [comment]
Any new with this bug?

**Comment by sunshiner** [comment]
> Any new with this issue?

revert to 4.29.3 is a temporary solution

**Comment by sokra** [comment]
#8801 this PR ensures that this is will less likely happen in future. We can't fully prevent this, as any package could add a git dependency in a patch release.

**Comment by tforkmann** [comment]
Having the same issue.

**Comment by xtuc** [comment]
Should be fixed by https://github.com/webpack/webpack/pull/8802 (didn't auto close because of a typo).

**Comment by dogoku** [comment]
Hey @xtuc thx for the fix, can we expect an npm release for this within the day?
Otherwise we have to lock version to 4.29.3 until fix is published

**Comment by sinoo** [comment]
Having the same issue. Locking version to 4.29.3 worked for me. But still hoping it could be solved soon.

**Comment by xtuc** [comment]
https://github.com/webpack/webpack/releases/tag/v4.29.5 ha been published

**Comment by tforkmann** [comment]
works! thanks for the fast fix!

**Comment by mweibel** [comment]
Version 4.29.5 seems to have been released with that fix.

**Comment by kamok** [comment]
I'm still getting this unfortunately.
```
~/Documents/code/typescript-vue-tutorial (master)*$ npm install --save-dev webpack@4.29.5
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kamok/.npm/_logs/2019-02-26T14_49_38_894Z-debug.log
```
```
~/Documents/code/typescript-vue-tutorial (master)*$ npm -v
6.3.0
~/Documents/code/typescript-vue-tutorial (master)*$ node -v
v8.11.2
```

**Comment by xtuc** [comment]
The long package over git was removed in `webpack@4.29.5`, could you please try to clear your npm cache and reinstall?

**Comment by kamok** [comment]
I did `npm cache clean --force`, did not bear fruit.

I did however, commented out `_auth=XXX` in my `.npmrc` and that somehow worked. I read it somewhere on another repo's issues.

**Comment by Jokero** [comment]
@xtuc I still have the same issue:
```
3845 silly fetchPackageMetaData error for @xtuc/long@4.2.2 404 Not Found: @xtuc/long@4.2.2
```
Removed `node_modules`, `package-json.lock`, `.npmrc`, cleaned npm cache (`npm cache clean --force`). Nothing helped

**Comment by batusai513** [comment]
For the people that need the `.npmrc` file for private registry you can try login in into npm cli using `npm login` and add your npm credentials, that worked for me.

**Comment by mark51-dev** [comment]
"npm login" helped me
but you need to sign up on npm site
