### ISSUE TITLE
npm installation is resulting in a Maximum call stack size exceeded error on an empty project

### ISSUE THREAD

**Issue by cokert** [webpack/webpack#8796]
# Bug report

**What is the current behavior?**
Installing webpack on a fresh project causes npm to fail reporting "Maximum call stack size exceeded." 

Installation of other packages is working as expected.  The problem may be in some other downstream dependency, but I don't know where to begin on that.  The attached log looks like it's failing when installing the package `long`, but I'm able to install that package manually.  

**If the current behavior is a bug, please provide the steps to reproduce.**
`md test`
`cd test`
`npm init -y`
`npm install --save-dev webpack`

**What is the expected behavior?**
webpack installation should succeed.

**Other relevant information:**
webpack version:  latest
Node.js version: latest
Operating System: Windows 10

Additional tools:

[2019-02-15T16_55_58_135Z-debug.log](https://github.com/webpack/webpack/files/2870060/2019-02-15T16_55_58_135Z-debug.log)

**Comment by louiszawadzki** [comment]
I've had the same issue, I believe it's because git wasn't installed on my machine.

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/webpack/webpack/issues/8795
