### ISSUE TITLE
v4.29.4 RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by krisballistiq** [webpack/webpack#8798]
# Bug report
This only fails in a docker container during an npm install from my experience, but may just be a low memory failure. Does not fail locally.

**What is the current behavior?**
```
npm ERR! Maximum call stack size exceeded`
The command '/bin/sh -c npm install' returned a non-zero code: 1
```
log from the docker container:
![image](https://user-images.githubusercontent.com/38010995/52886033-6b0e8c80-3149-11e9-9502-c16b031eb2df.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Install docker for mac
2. create a package.json with version of `v4.29.4`
3. create a dockerfile and add latest node `node:lts-alpine`
4. assure it runs `npm install`

**What is the expected behavior?**
1. container builds and runs npm install without error

**Other relevant information:**
webpack version:  v4.29.4
Node.js version: v10.13.0 / npm 6.4.1
Operating System: OSX 10.13.4
Additional tools: Docker Version 2.0.0.3

**Comment by MangaOtaku** [comment]
Had to revert to 4.29.3. :(

**Comment by FloppyThePenguin** [comment]
Getting the same issue. I've reverted back to 4.29.3

**Comment by EJLearner** [comment]
This issue has the same root cause as issue #8795

**Comment by xtuc** [comment]
This is likely a npm bug, but I agree the root cause is probably #8795. We are working to remove the dependency to git.

**Comment by unguul** [comment]
Can confirm that reverting to 4.29.3 makes the max call stack error go away. Can also confirm it does not happen locally.

**Comment by sokra** [comment]
Should be fixed in 4.29.5

**Comment by evilebottnawi** [comment]
Somebody can confirm problem solved in `4.29.5`?

**Comment by unguul** [comment]
@evilebottnawi Works fine for me. Thank you!

**Comment by evilebottnawi** [comment]
Okey, let's close, feel free to feedback

**Comment by timbergus** [comment]
I came from #8808. Everything works fine with __webpack@4.29.5__. My problem came from a Nexus repository in my company. It appears that the NPM packages weren't updated and the last version cached was __webpack@4.29.4__, so the `^` in the version, broke the app. Thanks for your help :)
