### ISSUE TITLE
NamedChunksPlugin not setting chunk.name 

### ISSUE THREAD

**Issue by michellocana** [webpack/webpack#8806]
## Feature request
Make [NamedChunksPlugin](https://github.com/webpack/webpack/blob/master/lib/NamedChunksPlugin.js#L21) also set chunk.name

I don't know if the current behavior of setting only the chunk id is intended, but seems reasonable to me to also set the value on `chunk.name`

**What is the expected behavior?**
The plugin only sets `chunk.id`

**What is motivation or use case for adding/changing the behavior?**
I'm trying to use [preload-webpack-plugin](https://github.com/GoogleChromeLabs/preload-webpack-plugin), but it relies on chunk.name to preload chunks

**How should this be implemented in your opinion?**
```js
apply(compiler) {
  compiler.hooks.compilation.tap("NamedChunksPlugin", compilation => {
    compilation.hooks.beforeChunkIds.tap("NamedChunksPlugin", chunks => {
      for (const chunk of chunks) {
        if (chunk.id === null) {
          chunk.id = this.nameResolver(chunk);
          chunk.name = this.nameResolver(chunk);
        }
      }
    });
  });
}
```

**Are you willing to work on this yourself?**
yes

**Comment by sokra** [comment]
It was renamed to `NamedChunkIdsPlugin` in the `next` branch.

**Comment by michellocana** [comment]
Ok, so i think this is a plugin-related issue, i'm closing this by now.
Thanks for the quick reply!
