### ISSUE TITLE
Error with @webassemblyjs/wast-parser (installation freezes).

### ISSUE THREAD

**Issue by timbergus** [webpack/webpack#8808]
# Bug report

**What is the current behavior?**
I have just updated from __webpack@4.29.3__ to __webpack@4.29.4__ and I cannot install my modules anymore. I have the following error with @webassemblyjs/wast-parser. It stops installing.

![screenshot 2019-02-18 18 16 14](https://user-images.githubusercontent.com/1750734/52967115-56303400-33a9-11e9-9be8-466604f85f01.png)

And when cancelling:

![screenshot 2019-02-18 18 17 52](https://user-images.githubusercontent.com/1750734/52967175-88419600-33a9-11e9-9432-440c5a44bd19.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
Having __webpack@4.29.3__ and everything working, just delete node_modules and try to install again using __webpack@4.29.4__.

**What is the expected behavior?**
To have my modules installed with __webpack@4.29.4__ as I had with __webpack@4.29.3__. When installing using __webpack@4.29.3__, this is the result:

![screenshot 2019-02-18 18 24 01](https://user-images.githubusercontent.com/1750734/52967444-61379400-33aa-11e9-8e93-08a578f7ff16.png)

**Other relevant information:**
webpack version:  4.29.4
Node.js version: 11.10.0
Operating System: Mac OSX
Additional tools: VSCode

**Comment by xtuc** [comment]
Duplicated of https://github.com/webpack/webpack/issues/8798

Please install `webpack@4.29.5`

**Comment by evilebottnawi** [comment]
Please clear cache for `npm`/`yarn`

**Comment by timbergus** [comment]
Thanks for your suggestion @evilebottnawi, but __webpack@4.29.5__ saved the day. Thanks all for your help :)
