### ISSUE TITLE
Webpack 4 does not process css files from node_modules in production mode

### ISSUE THREAD

**Issue by maksimsemenov** [webpack/webpack#8814]
# Bug report

DISCLAIMER: this issue is a duplicate of #8782. The original issue was closed without (as I can see) any strong reason. I asked to reopen the original issue, but, unfortunately, did not hear back. This bug is stopping us from migrating to webpack 4 from 3 (it works correctly in webpack 3). It will be great if someone can take a look.

**What is the current behavior?**
I'm importing css files from a third party library (installed in node_modules) into my main entry point. When I run webpack in `development` mode, the css files are correctly processed and extracted into the separate css file.
However, in `production` mode the css files are not processed at all.

Webpack output in `development` mode:
<img width="619" alt="screen shot 2019-02-19 at 11 12 25 am" src="https://user-images.githubusercontent.com/3608139/53029831-ad7ce580-3437-11e9-9a06-e22e0274dc82.png">
As you can see it has `styles.css` and `styles.index.js`

Webpack output in `production` mode:
<img width="617" alt="screen shot 2019-02-19 at 11 13 16 am" src="https://user-images.githubusercontent.com/3608139/53029894-cbe2e100-3437-11e9-9f9d-34e81c3f2f94.png">
As you can see it **does not have** `styles.css` and `styles.index.js`

**If the current behavior is a bug, please provide the steps to reproduce.**
Please take a look at [GitHub repository](https://github.com/maksimsemenov/webpack-css-issue)

The repo has two absolutely identical configs except for `mode` property. I'm aware that it is not recommended to use split chunks in `development` mode. The purpose to have dev and prod configs identical is to illustrate that only difference in `mode` affects which files has been processed by webpack and which not.
 
Run:

```
yarn install

yarn build
yarn build:dev
```
Check the output of those commands. The webpack that run in `development` has a css files in the output, while the one that was in `production` does not.

**What is the expected behavior?**
Webpack should process css files from node_modules that are imported into entry point in `development` and `production` modes.

**Other relevant information:**
webpack version: 4.28.4
Node.js version: 11.6.0
Operating System: macOS Mojave
Additional tools: yarn 1.13.0

**Comment by evilebottnawi** [comment]
You have invalid configuration `splitChunks` as said in other issue, you need setup priority, you styles in `vendor` chunks

**Comment by maksimsemenov** [comment]
@evilebottnawi I copy paste my config from this example: https://github.com/webpack-contrib/mini-css-extract-plugin#extracting-all-css-in-a-single-file.

Are there any documentation about `priority` and how to set it up?

**Comment by evilebottnawi** [comment]
@maksimsemenov https://webpack.js.org/plugins/split-chunks-plugin/#splitchunkscachegroupspriority , feel free to send a PR to example

**Comment by sokra** [comment]
You config is correct.

Actually this is working as expected, I can tell you why. (It is a bug in blueprintjs though)

You imported the styles with `import '@blueprintjs/core/lib/css/blueprint.css';` but do no use any export of them.

`@blueprintjs/core` has `"sideEffects": false` in its `package.json`, which means: "No module has a side effect".

As you don't use exports of `import '@blueprintjs/core/lib/css/blueprint.css';` and it has no side-effects, webpack is allowed to drop the import while optimizing.

You can change the `package.json` to `"sideEffects": ["*.css"],`, which means: "Only .css files have side effects" and it will work correctly.

**Comment by maksimsemenov** [comment]
@sokra thank you so much. That makes sense now.

So in webpack 3 with `extract-text-webpack-plugin` the behavior was different?

**Comment by sokra** [comment]
> So in webpack 3 with `extract-text-webpack-plugin` the behavior was different?

No, but `sideEffects` was intruduce in webpack 4.

**Comment by maksimsemenov** [comment]
For future googlers: 
https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

**Comment by jaydiablo** [comment]
Ran into this situation today (Webpack 4 completely removing SCSS/CSS files from a production bundle when the CSS is from a package that has `"sideEffects": false` defined in its `package.json`) and was curious if there was a way to override this behavior until the packages used can update their `package.json` to allow CSS/SCSS imports like this.

Modifying the rule for the CSS/SCSS loader by adding `sideEffects: true` to the rule appears to have worked for me.

From this (this is in the webpack config):

```
{
    module: {
        rules: [
            {
                test: /\.(sa|sc|c)ss$/,
                use: [
                    {
                        loader: 'css-loader',
                        options: {
                            sourceMap: true
                        }
                    },
                    {
                        loader: 'sass-loader',
                        options: { 
                            sourceMap: true 
                        }
                    }
                ]
            }
        ]
    }
}
```

to this:

```
{
    module: {
        rules: [
            {
                test: /\.(sa|sc|c)ss$/,
                sideEffects: true,
                use: [
                    {
                        loader: 'css-loader',
                        options: {
                            sourceMap: true
                        }
                    },
                    {
                        loader: 'sass-loader',
                        options: { 
                            sourceMap: true 
                        }
                    }
                ]
            }
        ]
    }
}
```

Note the addition of the `sideEffects: true,` line.

This will tell webpack to treat all SCSS/CSS files as having side effects so they don't get tree shaken. Of course it's possible to narrow this down to whatever files you'd like by changing the test regex, in case there are situations where you do want CSS files to be tree-shaken if unused but there are other files that need to be included regardless.

If there's a better way to do this, I'm all ears :)  I couldn't find any other good examples that solved this issue.
