### ISSUE TITLE
Different output settings per-entry point

### ISSUE THREAD

**Issue by timkelty** [webpack/webpack#882]
I want to have a different `output.path` setting, per-endpoint.
Is this possible?

``` js
  entry: {
    'head': path.join('app/assets/js/head.js'),
    'tail': path.join('app/assets/js/tail.js'),
    'app': path.join('app/assets/css/app.css'),
  },
  output: {
    filename: '[name].[hash].js',
    chunkFilename: '[id].[hash].js',
    path: path.join('dist/assets'),
  },
```

With this setup, I end up with everything in `dist/assets`. Ultimately I'd like:
`dist/assets/js/head.js`
`dist/assets/js/tail.js`
`dist/assets/css/app.css`

Possible?

**Comment by sokra** [comment]
Stylesheets doesn't work this way.
http://webpack.github.io/docs/stylesheets.html

**Comment by timkelty** [comment]
Ok, thanks for the reply! I'll just stick everything in `assets/bundles` or something together.

**Comment by bugushi** [comment]
How can I keep the output not flatten?
```
entry: {
    'head': path.join('js/common/head.js'),
    'login': path.join('js/login/login.js'),
  },
```
expected output structure:
`dist/js/common/head.js`
`dist/js/login/login.js`

Is there a config options like Gulp's `base`?

**Comment by mako-taco** [comment]
I actually have pretty good use cases for this feature. I build a lot of files... and a lot of them need to be inlined in iframes.  I currently have a post-build process outside of webpack doing this, but that's gross. I'd rather be able to use a loader to create an inline script in an html page, along side of my normal js libraries.

I also use the commons chunk to utilize the browser cache and reduce loads on these iframes, which results in some interesting problems... anyway +1 on this feature.  And even more +1s to extend it beyond just `output` (entry-specific plugins would be wonderful, if possible).

**Comment by sskyy** [comment]
+1

**Comment by chrisregner-com** [comment]
+1. In my current case, I needed it to output my precompiled (AVA) test file elsewhere.
