### ISSUE TITLE
Load dependencies based on the format of the parent

### ISSUE THREAD

**Issue by desandro** [webpack/webpack#883]
Expanding on #333. I've had several issues opened on my packages from users having trouble using Webpack with my packages, even though I support Browserify/RequireJS/UMD with all dependencies. See desandro/masonry#679 and metafizzy/packery#239.

Package authors are set on a collision course with UMD and Webpack. Authors are encouraged to support both AMD and CommonJS exports, adhering to [UMD](https://github.com/umdjs/umd). Ideally, when you adhere to a community specification, things should work out of the box, without requiring users to add extra config or authors to re-tool their source for your loader.

My recommendation is that Webpack should load dependencies based on the format of the parent. For example:

```
alpha
  - beta
  - gamma
    - delta
```

When you load `alpha` with CommonJS, all its dependencies are loaded with CommonJS. Currently, Webpack will load `alpha` with CommonJS then load `beta` with whatever loader it first detects. I feel this behavior is problematic. As an author, I expect that CommonJS or AMD loading is silo-ed. My dependencies can be loaded with either format, but not in a combination.

The current solution is use `imports-loader` to resolve this. I feel this is a bandage to quell the symptom.

**Comment by reggi** [comment]
> When you load alpha with CommonJS, all its dependencies are loaded with CommonJS. 

Brilliant :clap: :+1:

**Comment by sokra** [comment]
Hmm I don't think it's so simple. The style of the parent is not relevant, the package manager (npm or bower) is. If a user likes to write AMD, but installs modules via npm this will break.

You assume that modules installed via npm always use CommonJs and modules installed via bower always use AMD. But with webpack this is not true anymore. Both styles can be used for both package manager. I see that this leads to an issue.

The cleanest solution would be to publish different modules to npm and bower. Each one only with the correct dependencies for the package manager. But this lead to an overhead. (I would do it this way: write your module in CJS, publish it to npm and use webpack to compile an UMD version for bower ;), this way you could split your modules into multiple files )

Here are some workarounds which would eliminate the configuration by the user:

* Add a `browser` field to `package.json` and alias the bower dependencies to the npm ones. Exclude `package.json` from bower publishing.
* Switch the order of AMD and CJS in your UMD part and hope that webpack users always install your modules via npm (I think the most do so).

**Comment by desandro** [comment]
Thanks for looking this over.

What I do assume is that if you load `alpha` with CommonJS, and `alpha` depends on `beta`, then `beta` will be loaded with CommonJS. I feel this is intuitive behavior. Webpack's current behavior feels problematic.

**Comment by sokra** [comment]
> What I do assume is that if you load alpha with CommonJS, and alpha depends on beta, then beta will be loaded with CommonJS. I feel this is intuitive behavior.

Yeah, but this is not correct. If you write your code in AMD you may still want to require a CommonJs module from npm. Of if you write your code in CommonJs you may still want to require a AMD module from bower...

**Comment by jhudson8** [comment]
@sokra is there a way to change the loader order so that CommonJS is always checked first?

I'm having an issue which seems related to this one in the fact that I'm using [exoskeleton](http://exosjs.com/) without jquery.  While jquery is not a requirement, it is a dependency from an amd standpoint (but not necessary from a CommonJS standpoint)

AMD jquery dependency
https://github.com/paulmillr/exoskeleton/blob/master/exoskeleton.js#L12

Why it is not necessarily required
https://github.com/paulmillr/exoskeleton/blob/master/exoskeleton.js#L22

**Comment by farneman** [comment]
+1 for a solution to this.

**Comment by NeXTs** [comment]
+1

**Comment by mguijarr** [comment]
+1

**Comment by thesublimeobject** [comment]
+1

**Comment by cmalven** [comment]
+1

**Comment by siddharthkchatterjee** [comment]
+1

**Comment by Jangla** [comment]
+1

**Comment by farneman** [comment]
Would it be possible to add a Webpack config option to let a user specify that they prefer a particular dependency type over others if a module exposes multiple (ie. UMD)? This could also include an option to use a dependency's parent type as the preferred type.

**Comment by kepek** [comment]
+1

**Comment by jordanegstad** [comment]
+1

**Comment by lbineau** [comment]
+1

**Comment by homerjam** [comment]
What about if a module is unresolved via AMD trying again with forced CommonJS? Would there be possibility for a plugin that does this?

**Comment by farneman** [comment]
@homerjam: That would not solve the issue here. This issue occurs when Webpack loads a UMD module that successfully resolves AMD. The problem is loading such a module from a CommonJS context still gets the AMD version since that's the first available from the UMD wrapper.

**Comment by devil1991** [comment]
+1

**Comment by danez** [comment]
I don't think this is necessarily a problem of webpack, but rather other packages (and as far as I see most of them are from @desandro) who assume that AMD === bower/requirejs/... and CJS === npm/node/..., which is not correct, as with all the browser-bundlers, both ways can be used in different ways.

> The cleanest solution would be to publish different modules to npm and bower. Each one only with the correct dependencies for the package manager. But this lead to an overhead. (I would do it this way: write your module in CJS, publish it to npm and use webpack to compile an UMD version for bower ;), this way you could split your modules into multiple files )

I think this is the best solution.

**Comment by jared83** [comment]
+1

**Comment by tafkanator** [comment]
+1

**Comment by bboydflo** [comment]
+1

**Comment by NeXTs** [comment]
Github announced +1 feature, please use it

**Comment by k41n** [comment]
👍

**Comment by t1m0n** [comment]
+1

**Comment by devboxr** [comment]
+1

**Comment by jolane** [comment]
+1

**Comment by massimiliano-delia** [comment]
+1

**Comment by fgilio** [comment]
+1 plase

**Comment by misterfitzy** [comment]
+1

**Comment by apokyro** [comment]
+1 it's essential!

**Comment by pacanionio** [comment]
+1

**Comment by MirkoJotic** [comment]
+1

**Comment by jkirkby91-2** [comment]
+1

**Comment by brianedelman** [comment]
+1

**Comment by medfreeman** [comment]
+1

**Comment by SomosAMambo** [comment]
+1

**Comment by craigster1991** [comment]
+1

**Comment by dominicjameskelly** [comment]
+1

**Comment by dominicjameskelly** [comment]
+1

**Comment by marcus-herrmann** [comment]
+1

**Comment by DasNaughtie** [comment]
+1

**Comment by patrickbjohnson** [comment]
+1

**Comment by HauntedSmores** [comment]
+1

**Comment by medero** [comment]
+1

**Comment by kirylpl** [comment]
+1

**Comment by jimblue** [comment]
+1

**Comment by Robula** [comment]
+1

**Comment by cbmaiolo** [comment]
+1

**Comment by tderleth** [comment]
+1

**Comment by prewk** [comment]
Somebody has to say it: **Stop posting "+1" on GitHub!**

The emoji buttons are there for a reason..
