### ISSUE TITLE
How could I build only one of multiple entries with webpack

### ISSUE THREAD

**Issue by juancafe4** [webpack/webpack#8832]
I have different apps which I want to put them in one webpack config with multiple entries. How can I trigger a build for a specific entry?

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
