### ISSUE TITLE
Support for outputting to System.register format.

### ISSUE THREAD

**Issue by joeldenning** [webpack/webpack#8833]
## Feature request

It would be great to be able to change webpack's `output.libraryTarget` to `system` so that it is compiled to System.register format. See related #2810 from a couple years ago.

**What is the expected behavior?**
```js
// webpack.config.js
module.exports = {
  entry: 'entry.js',
  output: {
    libraryTarget: 'system',
  },
}
```
```js
// entry.js
console.log('hi')
```

```js
// output bundle
System.register([], function(_export, _context) {
  return {
    setters: [],
    execute: function() {
      console.log('hi')
    }
  }
})
```

**What is motivation or use case for adding/changing the behavior?**
For projects that use SystemJS as their in-browser module loader, it's desireable to be able to `System.import('/path-to-webpack-bundle.js')` as a way to dynamically load bundles. Currently, this can only be done by changing webpack's libraryTarget to `amd` and then using the [amd extra for SystemJS](https://github.com/systemjs/systemjs#extras).

**How should this be implemented in your opinion?**
From the user's perspective, this should be implemented via `output.libraryTarget`. Places I would start with the webpack implementation: [LibraryTemplatePlugin](https://github.com/webpack/webpack/blob/52184b897f40c75560b3630e43ca642fcac7e2cf/lib/LibraryTemplatePlugin.js#L77) and [ExternalsPlugin](https://github.com/webpack/webpack/blob/52184b897f40c75560b3630e43ca642fcac7e2cf/lib/ExternalsPlugin.js).

The most ambiguous part of the implementation is how to do code splits. For that, I welcome thoughts/advice/feedback. I think a good place to start would be [rollup's implementation of code splitting with system format](https://rollupjs.org/repl?version=1.2.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolMjBEWU5BTUlDJTIwSU1QT1JUUyU1Q24lMjAlMjAlMjBSb2xsdXAlMjBzdXBwb3J0cyUyMGF1dG9tYXRpYyUyMGNodW5raW5nJTIwYW5kJTIwbGF6eS1sb2FkaW5nJTVDbiUyMCUyMCUyMHZpYSUyMGR5bmFtaWMlMjBpbXBvcnRzJTIwdXRpbGl6aW5nJTIwdGhlJTIwaW1wb3J0JTIwbWVjaGFuaXNtJTVDbiUyMCUyMCUyMG9mJTIwdGhlJTIwaG9zdCUyMHN5c3RlbS4lMjAqJTJGJTVDbmlmJTIwKGRpc3BsYXlNYXRoKSUyMCU3QiU1Q24lNUN0aW1wb3J0KCcuJTJGbWF0aHMuanMnKS50aGVuKGZ1bmN0aW9uJTIwKG1hdGhzKSUyMCU3QiU1Q24lNUN0JTVDdGNvbnNvbGUubG9nKG1hdGhzLnNxdWFyZSg1KSklM0IlNUNuJTVDdCU1Q3Rjb25zb2xlLmxvZyhtYXRocy5jdWJlKDUpKSUzQiU1Q24lNUN0JTdEKSUzQiU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtYXRocy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBzcXVhcmUlMjBmcm9tJTIwJy4lMkZzcXVhcmUuanMnJTNCJTVDbiU1Q25leHBvcnQlMjAlN0JkZWZhdWx0JTIwYXMlMjBzcXVhcmUlN0QlMjBmcm9tJTIwJy4lMkZzcXVhcmUuanMnJTNCJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMGN1YmUlMjAoeCUyMCklMjAlN0IlNUNuJTVDdHJldHVybiUyMHNxdWFyZSh4KSUyMColMjB4JTNCJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJzcXVhcmUuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwc3F1YXJlJTIwKCUyMHglMjApJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjB4JTIwKiUyMHglM0IlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMnN5c3RlbSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0ElMjIwMCUyMiU3RA==). Meaning that a dynamic `import()` would turn into a `_context.import()`.

**Are you willing to work on this yourself?**
Yep I'm happy to work on this. Plan on digging into this tonight a bit to get my feet wet. It was previously expressed in #2810 that this would be a good feature to have, but if anyone disagrees please let me know before I get too far in my implementation :)

**Comment by joeldenning** [comment]
cc @guybedford who'll have some thoughts on this and who I'll likely need some help from

**Comment by guybedford** [comment]
Note `setters` can be skipped in the wrapper when there are no dependencies so just:

```
System.register([], function(_export) {
  return {
    execute: function() {
      console.log('hi')
      _export({ named: 'exports', here });
    }
  };
});
```

should be fine for the wrapper.

**Comment by joeldenning** [comment]
Thoughts on the question with dynamic import? Should webpack do webpackJsonp stuff for system.register libraries? Or should it do `module.import()`?

I think this could be the hardest part of the implementation and maybe the most controversial aspect of the feature.

**Comment by guybedford** [comment]
I believe, unless this has chnaged, that Webpack explicitly has as a design goal not to support unknown dynamic imports in the runtime environment, so that this can be omitted in the output.

**Comment by joeldenning** [comment]
So maybe sticking to just the entry module being a System.register format, with subsequent code splits being webpack format and use webpackJsonp?

I still find value in the feature like that ^. Usually I care about getting the overall bundle into SystemJS but don't usually have a strong preference about whether it's SystemJS or webpack who implements the code splitting beyond that

**Comment by guybedford** [comment]
> So maybe sticking to just the entry module being a System.register format, with subsequent code splits being webpack format and use webpackJsonp?

Exactly!

**Comment by sokra** [comment]
Only entry module in System.register format -> `output.libraryTarget: "system"` (pretty easy)

Code Splitting with System.register and module.import -> `target: "system"` (more involved)

**Comment by guybedford** [comment]
@sokra thanks for the feedback here - could you perhaps suggest what the basic architecture of the approach might be for `output.libraryTarget: "system"` for anyone wanting to attempt an implementation here?

**Comment by sokra** [comment]
Best see `AmdMainTemplatePlugin` (copy this and change it).

The option values are referenced in `LibraryTemplatePlugin`, where the need plugin need to be added.

For support of dependencies, `system` also need to be added in `ExternalModule`

**Comment by SunHuawei** [comment]
Is there any further discussion on this? Or should we open another issue for that?
> Code Splitting with System.register and module.import -> target: "system" (more involved)
