### ISSUE TITLE
Allow optional `require.resolveWeak()` to fail without warning 

### ISSUE THREAD

**Issue by jamesknelson** [webpack/webpack#8838]
## Feature request

**What is the expected behavior?**

It should be possible to try to `require.resolveWeak()` a module that doesn't exist, *without* emitting a warning.

E.g. I can already do this:

```js
try {
      require.resolveWeak('not-here')
}
catch (e) {
      // no worries, it was optional anyway
}
```

And webpack will emit a warning:

```text
Module not found: Can't resolve 'not-here' in '/path/to/app'
```

I'd like to be able to ask webpack to not show this warning in some cases.

**What is motivation or use case for adding/changing the behavior?**

I'm creating a library that implements a number of extra features when specific packages are available, but the features are all optional. The required packages are on the large side, so I don't want to bundle them unless the user requires them.

Currently, optional require using `try/catch` works, but would introduce build warnings to any application that depends on my library unless it requires all of the optional dependencies, which would be rather confusing for users.

**How should this be implemented in your opinion?**

Webpack already marks dependencies as optional when they're inside a `try/catch` block, and switches from an error to a warning in these cases:

- https://github.com/webpack/webpack/blob/eb6831673afc6fdc109137bec4af47ac96247c5e/lib/dependencies/RequireResolveDependencyParserPlugin.js#L49
- https://github.com/webpack/webpack/blob/6389e41e4c65bf32a916e6fffa5d65f66538d483/lib/Compilation.js#L813

One option would be to just stop warning when dependencies are optional. Another would be to create a new function, e.g. `require.resolveWeakOptional()`, that sets a different flag on the dependency object that indicates not to warn:

```js
try {
  require.resolveWeakOptional('not-here')
}
catch (e) {
  // all good.
}
```

It may also be desirable to add support for silencing warnings on `import()` with a magic comment.

I'd be interested to hear any opinions on the best approach.

**Are you willing to work on this yourself?**

Yes, just need to know what approach would be most likely to be accepted.

**Comment by sokra** [comment]
> I'm creating a library that implements a number of extra features when specific packages are available, but the features are all optional. The required packages are on the large side, so I don't want to bundle them unless the user requires them.

I think using `require.resolveWeak('not-here')` is not a good metric here. It only checks if the module is currently available. In the case when the module is code-splitted and not yet loaded, but bundled, it still throw an error at runtime. Example

``` js
try { require.resolveWeak("something") }
catch(e) { /* will be entered here */ }

import("something")
```

---

I think you need something like this:

``` js
if(typeof __webpack_is_included__ !== "function" || __webpack_is_included__("something")) {
  // load logic for "something"
  // this branch will be dropped while minimizing when "something" is not included
}
```

**Comment by jamesknelson** [comment]
I think that would be amazing. Any idea on how to go about implementing it?

**Comment by sokra** [comment]
`__webpack_is_included__` will be a new Dependency.
You can add to parsing logic to the `APIPlugin`.

* Start by copying some existing Dependency, i. e. `RequireIncludeDependency` -> `WebpackIsIncludedDependency`
* `WebpackIsIncludedDependency.getReference()` set `weak` to true
* In `WebpackIsIncludedDependency.Template` check if `dep.module` is included in any chunk (`dep.module.getNumberOfChunks() > 0)`. In this case generate `true` otherwise `false`.
* While parsing in `APIPlugin` hook into
  * `parser.hooks.expression.for("__webpack_is_included__")` and add the new Dependency.
  * `parser.hooks.evaluateTypeof.for("__webpack_is_included__")` and `ParserHelpers.evaluateToString("function")`
* add test cases i. e. to `cases/parsing/typeof` and some custom cases for the included logic (maybe in `cases/parsing/is-included`

**Comment by jamesknelson** [comment]
Thanks! Might take me a little while as I'm new to the Webpack codebase, but will give it a shot.

**Comment by evilebottnawi** [comment]
bump

**Comment by evilebottnawi** [comment]
bump

**Comment by hipstersmoothie** [comment]
Stalebot strikes again 😢

**Comment by vankop** [comment]
I'll take a look
