### ISSUE TITLE
Webpack is not able to load styles from antd after proper configuration

### ISSUE THREAD

**Issue by kaiz123** [webpack/webpack#8840]
# Bug report

**What is the current behavior?**
antd styles do not load

**If the current behavior is a bug, please provide the steps to reproduce.**
This is the webpack.config.js inside my .storybook folder inside CRA project-

``` js
const path = require("path");

module.exports = {
    module: {
        rules: [
            {
                loader: 'babel-loader',
                exclude: /node_modules/,
                test: /\.js$/,
                options: {
                    presets: ["@babel/react"],
                    plugins: [
                        ['import', {libraryName: "antd", style: "less"}]
                    ]
                },
            },
            {
                test: /\.less$/,
                loaders: [
                    "style-loader",
                    "css-loader",
                    {
                        loader: "less-loader",

                        options: {
                            javascriptEnabled: true
                        }
                    }
                ],
                include: path.resolve(__dirname, "./")
            }
        ]
    }
};
```

**What is the expected behavior?**
Expected behavior is that styles should load from antd. However this is not the case and plain html elements show up

**Other relevant information:**
webpack version:  >3
Node.js version: any
Operating System: any
Additional tools: Babel, react, less loader

**Comment by sokra** [comment]
Seem to be related to the `import` babel plugin?

I don't see how webpack can help here?

**Comment by kaiz-growfitter** [comment]
Okay thanks !
