### ISSUE TITLE
Using splitChunks to create a chunk independent of other chunks

### ISSUE THREAD

**Issue by guylando** [webpack/webpack#8841]
We have a multi-entries config which creates an output file for each entry.
Right now we use splitChunks to create a "common" chunk for for the common code among the output files.
The goal is to separate some explicit list of modules out of "common" chunk into "connectedCommon" chunk which will only be loaded after user logs in.
Using the config below if we dont load connectedCommon into the page then the page does not execute some modules inside common even though they don't require connectedCommon.
Debugging this shows that some modules have connectedCommon chunk dependency in their "executeModules" list.

The question is: is there a way to add a chunk inside splitChunks which will not be added as a dependency to any other chunk? Or how to prevent webpack for not executing a module when connectedCommon is not loaded? Spefically the webpack checkDeferredModules function fails on the installedChunks check because it expects connectedCommon to be installed when its not.

`

        optimization.splitChunks = {
            name: "true",
            minChunks: 2,
            cacheGroups: {
                /* Turn off webpack defaults */
                default: false,
                vendors: false,
                /* Add our custom common chunks */
                connectedCommon: {
                    chunks: "all",
                    /* Create the chunk no matter what is the size of the chunk */
                    enforce: true,
                    /* If a module falls under many chunk groups, then module will be a part of chunk group with higher priority and if we decided to put a module in this chunk then it should here and not in the other chunk so put here higher priority */
                    priority: 2,
                    /* The common bundle's name, used the same as the entry bundles names to decide output file name */
                    name: `connectedCommon`,
                    /* Bundle here only libraries used after login */
                    test(currModule, currChunks) {
                        return isAuthenticatedModule(currModule, currChunks);
                    },
                },
                common: {
                    chunks: "all",
                    /* Create the chunk no matter what is the size of the chunk */
                    enforce: true,
                    /* Put lower priority than connectedCommon chunk to insert modules to connectedCommon first if they satisfy condition */
                    priority: 1,
                    /* The common bundle's name, used the same as the entry bundles names to decide output file name */
                    name: `common`,
                    /* Bundle here libraries not bundled in connectedCommon chunk */
                    test(currModule, currChunks) {
                        return !isAuthenticatedModule(currModule, currChunks);
                    },
                },
            },
        };
        optimization.runtimeChunk = {
            /* Making the name equal to the split chunk name makes them merge
                NOTE: Without this webpack creates multiple jquery instances instead of one. See:
                https://github.com/webpack/webpack/issues/6977#issuecomment-388826616
                https://gist.github.com/sokra/1522d586b8e5c0f5072d7565c2bee693
            */
            name: `common`,
        };
`

**Comment by guylando** [comment]
Basically what I want is simple: be able to choose a list of modules to be combined into a chunk which will not prevent other chunks from executing if this chunk is not "installed"

**Comment by guylando** [comment]
Inserting temporary stub in webpack webpackJsonp so it will think connectedcommon was loaded works but it does not play well with minification which obfuscates modules names:

```
<script>
                (window["webpackJsonp"] = window["webpackJsonp"] || []).push([["connectedcommon"],{
                    "./node_modules/moment/moment.js": function () {},
                    "./src/myConnectedModule.js": function () {},
                }]);
            </script>
```

Any other simple solution which works?

**Comment by sokra** [comment]
You can't solve this with configuration. You need to change your source code to not "depend" on the modules directly. Currently your entrypoint depends on modules inside of `connectedCommon` (probably because you `import` them). You need to load these modules on demand (i. e. with `import()`).

webpack will insert all chunks needed for the entrypoint into the `checkDeferredModules` check. Once you remove these dependencies it will no longer require the `connectedCommon` chunk as startup, but will load it on demand instead.

Once you've done these changes you actually don't need a `splitChunks` configuration at all.

**Comment by guylando** [comment]
Thanks for the answer.
I can't use the html inject plugin because the server side code is asp.net razor cshtml file. Will the client side know to load the chunks by default and know where to find it? Also I am afraid that this dynamic loading will create many different chunks which is undesired and I prefer it to be gathered into as few chunks as possible to prevent http request delays on different user actions.

Regarding the solution I wrote in the previous comment I actually made it work. I hooked webpack compilation finish event and took chunks ids and modules ids automatically from compilation object and auto generated a javascript file with code like in my previous comment but the ids dynamically inserted. Then I added code to automatically insert this javascript file content into appropriate script tag instead of connectedcommon chunk script in case user id not connected. Since all those imports don't really happen before login, this stub replacement works and allows the webpack module loading conditions to be satisfied allowing chunks to be executed and no errors happen.
It would be a good feature to have if you could add a webpack configuration somewhere which basically tells webpack that the developer knows what he is doing regarding loading the chunks into the page and dont prevent chunks execution even if webpack thinks a dependency module wasn't installed. If the developer didn't load the module and it will actually be used then there should be a runtime error.
Such configuration will be useful and only used by developers who use it for specific purpose and they knows what they are doing. This would prevent the need for such hacks as what I done.

**Comment by sokra** [comment]
> because the server side code is asp.net razor cshtml file

You can get the information about needed `<script>` tags from the webpack stats and create server logic to create script tags for that.

**Comment by billyvg** [comment]
> > because the server side code is asp.net razor cshtml file
> 
> You can get the information about needed `<script>` tags from the webpack stats and create server logic to create script tags for that.

I'm currently trying to remove the server logic needed to load our entrypoint so that we can make frontend-only deploys independent of backend. My plan was to have the runtime chunk and a "init" chunk that would dynamically import our main application both be static filenames (i.e. without `[contenthash]`), so that the server template will always load these two uncached bundles from CDN.

However I'm running into the same problems as the original author, where our vendor chunk is expected to be loaded. Ideally, I would have the "init" entry import the vendor chunk instead of in our HTML (as the vendor chunk will have a `[contenthash]` and we're trying to avoid the server template from needing to read a manifest file).

**Comment by alexander-akait** [comment]
https://github.com/webpack/webpack/issues/12863
