### ISSUE TITLE
Webpack 4 + jQuery + jQuery Migrate

### ISSUE THREAD

**Issue by juan-bastidas** [webpack/webpack#8843]
I'm facing an issue while moving from **Webpack v3 to v4**, my app is quite big and has an old part that relies on jQuery + jQuery Migrate, in webpack 3 it was working all OK as follows:

1. jQuery + jQuery Migrate are imported in a common.js entry file that is loaded for all pages.
2. In all other modules (used by other entries) we only import jQuery

In **v4** I've been playing with configurations and nothing works for me, basically what happens is that in any other entry file I get an error ($(...).live is not a function or $.browser is undefined) because migrate is not loaded in this case, I do not want to import migrate in all modules where I import jQuery, I just need that jQuery + jQuery Migrate are loaded together always, ideas? What should be the configuration for splitChunks?
Also seems that jQuery is not reused everywhere, with Webpack 4 I found a copy of it in all entry files, so I think Webpack 4 is not doing its magic

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by juan-bastidas** [comment]
Hi

This is a small repository showing the problem: https://github.com/juan-bastidas/webpack-4-jquery-issue

To recap:
1. This works OK using webpack v3
2. In v4 Jquery gets copied in all entry files
3. Do not want to import jQuery migrate in all my modules, I only imported it in common.js bundle and it was just enough to make it work
4. Build this repository, load page1.html and note the error in console about $(...).live not defined
5. I've played with many different splitChunks configurations to fix the problem but no luck

Thanks

**Comment by mozartilize** [comment]
Any update on this issue?
I got the same problem when SplitChunksPlugin does not work like CommonsChunkPlugin in webpack v3 and causes `TypeError: $(...).DataTable is not a function`
here is my example: [https://github.com/mozartilize/test_webpack_4](https://github.com/mozartilize/test_webpack_4)

**Comment by ngspinu** [comment]
Any updates on this one? It still looks to be an issue.
