### ISSUE TITLE
Webpack does not find my babel config in root

### ISSUE THREAD

**Issue by Elminday** [webpack/webpack#8845]
**I'm submitting a bug report**

**Webpack Version:**
4.12.0

**Babel Core Version**:
7.0

**Babel Loader Version**:
8.0.0-beta.0

**Please tell us about your environment:**
Ubuntu

**Folder structure**
Mono-repo. All projects in packages folder.
```
root
│   babel.config.js    
│   package.json    
└───packages
│       └───react-project
│                │  package.json
│                │  webpack.config.js
```

**Current behavior:**

In react-project I launch command:

`webpack-dev-server --config ./webpack.config.js`
I get an error which is caused because `babel.config.js` is not found.

```
Module build failed (node_modules/babel-loader/lib/index.js):
SyntaxError: src/index.js: Unexpected token (32:2)

  30 |
  31 | ReactDOM.render((
> 32 |   <Provider {...stores}>
     |   ^
```

* **What is the expected behavior?**

`babel.config.js` is found in root and used in `webpack` by `babel-loader`.

* **How does it work**

If i put the same `babel.config.js` in **react-project** and launch the same command it works.

* **My configs**

**webpack.config.js:**

```
const path = require('path');
const webpack = require('webpack');
const merge = require("webpack-merge");
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = env => {
  return merge([
    {
      entry: ['@babel/polyfill', path.resolve('src')],
      module: {
        rules: [
          {
            test: /\.js$/,
            exclude: /node_modules/,
            use: {
              loader: 'babel-loader'
            }
          },
        ]
      },
      plugins: [
        new HtmlWebpackPlugin({
          template: 'public/index.html',
          filename: 'index.html'
        }),
      ],
    }
  ])
};
```

**babel.config.js**

```
module.exports = {
  comments: false,
  presets: [
    [
      '@babel/preset-env',
    ],
    [
      '@babel/preset-react',
    ],
  ],
  plugins: [
    "@babel/plugin-syntax-dynamic-import",
    ['@babel/plugin-proposal-class-properties', {loose: true}],
    'transform-remove-console',
  ],
  env: {
    node: {
      sourceMaps: 'both',
      sourceType: 'unambiguous',
      sourceFileName: 'index.js',
    },
  },
  ignore: ['node_modules'],
};

```

**Comment by Elminday** [comment]
`rootMode: "upward"` passed to babel-loader options fixed the issue.

**Comment by mschipperheyn** [comment]
@mindaugasnakrosis I get this error on babel 7.8.4
`.rootMode is only allowed in root programmatic options`
