### ISSUE TITLE
can one project use more js framework as same ?

### ISSUE THREAD

**Issue by cleverboy32** [webpack/webpack#8846]
can i use many framework in one project ?
such as i use reat and vue

**Comment by montogeek** [comment]
Yes you can, that is independent of webpack.

It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
