### ISSUE TITLE
How to identify all chunks required for a module with webpack plugin?

### ISSUE THREAD

**Issue by tranvansang** [webpack/webpack#8847]
I posted my question in Stackoverflow and webpack Gitter 2 weeks ago. But it looks like there is no expert there who can help me.

I am struggle with a code splitting lib which should identify all chunks required for dynamic imported modules to be loaded in server side, named [react-loadable](https://github.com/jamiebuilds/react-loadable/blob/master/src/webpack.js)

It has bug and does not allow submit issue in github. Here is the final place which I can post for any help because this is seriously breaking my app.

I have `Login` component, it imports `Login.scss` module.
They are emitted to different chunks with id `24` and `26`.

To be able to render `Login`, `react-loadable`'s webpack plugin should load both 2 chunks. However, it only loads the first chunk with id `24`.

Original code

```
    const Login = loadable({
      loader: () => import( './Login'),
      loading: BackDropLoading
    })
```

is compiled to

```
    var Login = react_loadable__WEBPACK_IMPORTED_MODULE_4___default()({
      loader: function loader() {
        return Promise.all(/*! import() */[__webpack_require__.e(24), __webpack_require__.e(26)]).then(__webpack_require__.bind(null, /*! ./Login */ "e4e16af1e58ef872f736"));
      },
      modules: ['./Login'],
      webpack: function webpack() {
        return [/*require.resolve*/(/*! ./Login */ "e4e16af1e58ef872f736")];
      },
      loading: _containers_BackDrop__WEBPACK_IMPORTED_MODULE_5__["BackDropLoading"]
    });
```

**Is there anyway I can identify the above `24` and `26` numbers giving a rawRequest `import('./Login')` in a webpack plugin? How does webpack/babel find out these 2 magic numbers?**

This is the portion of code in `react-loadable` webpack plugin, which identifies chunks for dynamic import statements.

```
    function buildManifest(compiler, compilation) {
      var context = compiler.options.context;
      var manifest = {};
    
      compilation.chunks.forEach(function (chunk) {
        const m = []
        for(const mm of chunk.modulesIterable) m.push(mm.rawRequest)
        console.log(chunk.id, m, chunk.files)
        chunk.files.forEach(function (file) {
          chunk.forEachModule(function (module) {
            var id = module.id;
            var name = typeof module.libIdent === 'function' ? module.libIdent({ context: context }) : null;
            var publicPath = url.resolve(compilation.outputOptions.publicPath || '', file);
    
            var currentModule = module;
            if (module.constructor.name === 'ConcatenatedModule') {
              currentModule = module.rootModule;
            }
            if (!manifest[currentModule.rawRequest]) {
              manifest[currentModule.rawRequest] = [];
            }
    
            manifest[currentModule.rawRequest].push({ id: id, name: name, file: file, publicPath: publicPath });
          });
        });
      });
    
      return manifest;
    }
```

Output manifest is (partial):

```
      "./Login": [
        {
          "id": "e4e16af1e58ef872f736",
          "name": "./src/client/components/auth/Login.js",
          "file": "26.js",
          "publicPath": "http://127.0.0.1:8080/bundles/26.js"
        },
        {
          "id": "e4e16af1e58ef872f736",
          "name": "./src/client/components/auth/Login.js",
          "file": "26.js.map",
          "publicPath": "http://127.0.0.1:8080/bundles/26.js.map"
        }
      ],
```

and other portion in the output manifest

```
      "./Login.scss": [
        {
          "id": "61dac8f85433b72d4f5b",
          "name": "./src/client/components/auth/Login.scss",
          "file": "24.css",
          "publicPath": "http://127.0.0.1:8080/bundles/24.css"
        },
        {
          "id": "61dac8f85433b72d4f5b",
          "name": "./src/client/components/auth/Login.scss",
          "file": "24.js",
          "publicPath": "http://127.0.0.1:8080/bundles/24.js"
        },
        {
          "id": "61dac8f85433b72d4f5b",
          "name": "./src/client/components/auth/Login.scss",
          "file": "24.css.map",
          "publicPath": "http://127.0.0.1:8080/bundles/24.css.map"
        },
        {
          "id": "61dac8f85433b72d4f5b",
          "name": "./src/client/components/auth/Login.scss",
          "file": "24.js.map",
          "publicPath": "http://127.0.0.1:8080/bundles/24.js.map"
        },
        {
          "id": "61dac8f85433b72d4f5b",
          "name": "./src/client/components/auth/Login.scss",
          "file": "28.css",
          "publicPath": "http://127.0.0.1:8080/bundles/28.css"
        },
        {
          "id": "61dac8f85433b72d4f5b",
          "name": "./src/client/components/auth/Login.scss",
          "file": "28.js",
          "publicPath": "http://127.0.0.1:8080/bundles/28.js"
        },
        {
          "id": "61dac8f85433b72d4f5b",
          "name": "./src/client/components/auth/Login.scss",
          "file": "28.css.map",
          "publicPath": "http://127.0.0.1:8080/bundles/28.css.map"
        },
        {
          "id": "61dac8f85433b72d4f5b",
          "name": "./src/client/components/auth/Login.scss",
          "file": "28.js.map",
          "publicPath": "http://127.0.0.1:8080/bundles/28.js.map"
        }
      ],
```

Here is my webpack splitchunk configuration. There is mostly irrelevant setting, I just paste here for reference.

```
      optimization: {
        runtimeChunk: "single",
        splitChunks: {
          chunks: ({name}) => !['polyfill', 'assets', 'polyfill-modern', 'ja', 'en'].includes(name),
          cacheGroups: {
            vendors: {
              test: /\/node_modules\//,
              priority: -10
            },
            assets: {
              test: /\.(svg|ttf|otf|eot|woff2?|bmp|cur|gif|icns|ico|jpe?g|png|psd|tiff|webp|dds)$/,
              priority: -10
            }
          },
        },
      },
```

**Comment by sokra** [comment]
An `import()` references a `ChunkGroup` which references one or more `Chunk`s. It also has zero or more parent `ChunkGroup`s, from which at least one is expected to be loaded (expect for an `Entrypoint` (subclass of `ChunkGroup`), which doesn't have/need parents).

To create the manifest you can iterate over all `compilation.chunkGroups`. Each `ChunkGroup` has zero or more origins in `ChunkGroup.origins`. Each origin has a `request`, which is `./Login` here.

Each `Chunk` has a list of `files` which are needed.

Technically there could be multiple options of chunks which can be included, when there are multiple parent ChunkGroups. You can choose any path.

Once you loaded all these chunks you will be able to use the module id generated by `require.resolveWeak("./Login")` and the `__webpack_require__(moduleId)` function to load the module synchronously. This will give you the same value as `import()` resolves too **if the module is a ESM**. For non-ESM webpack generates a wrapper to make it a namespace object, but you can just say this case is not supported.

**Comment by tranvansang** [comment]
Thank you very much.

In the following days, I will implement your solution and give feedback if it is success.

I close the issue now to keep the dashboard clean

**Comment by tranvansang** [comment]
@sokra 

thank you very much for your suggestion. We have successfully patched the `react-loadable` package and used it in our products for a year.

Now, I am going to publish the fix we have used. But I have a question regarding the chunk group. Can you help?

For now, we only load all assets belong to the chunk group whose origin matches the request in the context.

These assets can be easily retrieved from the webpack's stats.namedChunkGroups.

However, there are `children`, and `childrenAssets` (but no `parent` nor `parentAssets`) in each chunkGroup's stats.

My question is "Is loading the direct assets of a chunk group enough for the module?". In other words, "Does chunk group have depedencies?".
