### ISSUE TITLE
ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' if you have invalid package.json

### ISSUE THREAD

**Issue by totty90** [webpack/webpack#885]
I've added by mistake the following line

```
// some comment
```

in the first line in package.json and got this error in webpack: `ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' ./src/client/index.js in C:\a`

This is solved if the comment is removed.

**Comment by jfilhoGN** [comment]
Your problem is occurring because JSON files not support comments.
