### ISSUE TITLE
Es syntax explanation

### ISSUE THREAD

**Issue by andrey-furman** [webpack/webpack#8861]
Why [here](https://webpack.js.org/configuration/) config file is written with es6 when at the same time you have to go it through babel to launch??

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Also please use `gitter`/`stackoverflow` for questions, thanks
