### ISSUE TITLE
Electron 5.0 beta, electron-renderer breaks on require

### ISSUE THREAD

**Issue by natew** [webpack/webpack#8862]
# Bug report

**What is the current behavior?**

Using with electron 5.0.0-beta.4 you get this error, "Uncaught ReferenceError: require is not defined":

![image](https://user-images.githubusercontent.com/12100/53705613-9b595a80-3dda-11e9-84bb-0343c5f14258.png).

"external" links to:

![image](https://user-images.githubusercontent.com/12100/53705620-af04c100-3dda-11e9-8ccc-0f7d003db2ef.png)

which comes from:

![image](https://user-images.githubusercontent.com/12100/53705627-b75cfc00-3dda-11e9-85a3-d10894d2445a.png)

which ultimately comes from webpack-dev-server somewhere:

![image](https://user-images.githubusercontent.com/12100/53705636-c774db80-3dda-11e9-8df3-32a4bebc6c86.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

Just loading electron 5 with a simple webpack app likely does it. Is there some easy place to do this online or do I need to create a repo?

**Other relevant information:**
webpack version:  4.29.3
Node.js version: 10
Operating System: Mojave

**Comment by evilebottnawi** [comment]
@natew Please create minimum reproducible test repo

**Comment by natew** [comment]
Turns out its due to this: https://github.com/electron/electron/issues/17208#event-2176872582
