### ISSUE TITLE
Imports inside template literals breaks when using Babel

### ISSUE THREAD

**Issue by stefanfisk** [webpack/webpack#8863]
# Bug report

**What is the current behavior?**

Imports used inside template literal expressions in calls to `require()` are not *mangled* correctly when using `@babel/plugin-transform-template-literals`.

**If the current behavior is a bug, please provide the steps to reproduce.**

In this code for example, `module1` in `module1('module2')` is not transformed to the import's variable name.

```
import module1 from './module1';

const foo = module1;

require(`./${foo('module2')}`);
require(`./${module1('module2')}`);
```

I have created an example project at https://github.com/stefanfisk/webpack-template-literal-bug.

**What is the expected behavior?**

That the import's name is mangled correctly.

**Other relevant information:**
webpack version:  4.29.6
Node.js version: 11.4.0
Operating System: macOS 10.14.3
Additional tools:

**Comment by stefanfisk** [comment]
Might this possible be related to https://github.com/webpack/webpack/issues/5674 / https://github.com/webpack/webpack/pull/5679?

**Comment by evilebottnawi** [comment]
Please report the problem to babel
