### ISSUE TITLE
"@import directive requires a url or quoted path"

### ISSUE THREAD

**Issue by j-low** [webpack/webpack#8865]
# Bug report

**What is the current behavior?**
`scss` files which either:
* are imported directly into a React component (e.g. with `import "./my-component-styling.scss";`), or
* use `@import "./some-other-stylesheet.scss"` in the file contents

throw the following error: `@import directive requires a url or quoted path`.  This occurs despite either no `@import` directive being present in the specified file body _or_ the `@import` directive being declared with a valid URL.

Here is an extended log of the error:
```
ERROR in ./assets/css/application.scss
Module build failed: ModuleBuildError: Module build failed: 
undefined
^
      @import directive requires a url or quoted path
      in /console/assets/css/application.scss (line 94, column 1)
    at runLoaders (/console/node_modules/webpack/lib/NormalModule.js:242:20)
    at /console/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /console/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/console/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.render [as callback] (/console/node_modules/sass-loader/lib/loader.js:52:13)
    at Object.done [as callback] (/console/node_modules/neo-async/async.js:8077:18)
    at options.error (/console/node_modules/node-sass/lib/index.js:294:32)
 @ multi ./assets/css/application.scss ./assets/js/application.tsx
```
The above error repeats (once for each file; totalling five errors).  Strangely, each error is thrown on `line 94, column 1` though none of the files in question contain a line 94.

**If the current behavior is a bug, please provide the steps to reproduce.**
[Gist of the relevant files](https://gist.github.com/j-low/ebc52a578217b8ac97ae16c2f77b26f4)

**What is the expected behavior?**
Webpack should compile.  SCSS files in `/assets/util/` should be available globally.  `@import` directives should work within file body.

**Other relevant information:**
webpack version:  4.5.0
Node.js version:  10.2.1
Operating System: OSX 10.12.6
Additional tools: sass-resources-loader 2.0.0, sass-loader 7.1.0, css-loader 1.0.0

**Comment by j-low** [comment]
Figured this out.  It turned out to have something to do with the way sass-resources-loader was transforming an `@import` statement.  Closing issue.

**Comment by markwilliamson05** [comment]
Can you elaborate on how you resolved issue? I'm having same issue.

**Comment by j-low** [comment]
Absolutely.  

So it turned out that I had a single `@import` statement in one of the global resources I was pointing sass-resources-loader to.  I was importing a google font with this statement: `@import url("https://fonts.googleapis.com/css?family=Roboto:400,500,700");`.  I don't know why but sass-resources-loader was transforming that statement into something like `../assets/css/url/https://fonts.googleapis.com/css?family=Roboto:400,500,700` which-- given the error `@import directive requires a url or quoted path`-- is an obviously invalid `@import url(...)` statement.  

Does that clarify things at all?

**Comment by SpeakInCode** [comment]
Thank you @j-low this was driving me nuts and was my exact same issue. Thank you for sharing your solution.

**Comment by dustinmichels** [comment]
Sorry, I can't tell what the solution was?

**Comment by Tummerhore** [comment]
I'm not sure if this was alsoj-low's solution but i solved it by setting the resolveUrl option to false.

**Comment by afn** [comment]
I had the same issue, with my `application.sass` containing:
```sass
@import "https://fonts.googleapis.com/icon?family=Material+Icons"
```

I fixed it by changing the line to:
```sass
@import url(https://fonts.googleapis.com/icon?family=Material+Icons)
```

**Comment by mihailthebuilder** [comment]
I resolved it by moving the import statement **outside** of the scss file that is used in **options.resources** for **sass-resources-loader** in **webpack.config.js**. Any other scss file will do. Check out src/index.scss and webpack.config.js in my repo: https://github.com/mihailthebuilder/tech-asia

**Comment by Sam-Dunne** [comment]
I had copied and pasted the @import from a blog, the quotation marks simply needed to be manually retyped...they weren't recognized properly from the copy/paste
