### ISSUE TITLE
Suppress warnings in console

### ISSUE THREAD

**Issue by natew** [webpack/webpack#887]
We do dynamic route requires in a library that's used by people, and a lot of them are confused by this messaging:

```
WARNING in ./app/routes.js
Critical dependencies:
25:16-23 require function is used in a way, in which dependencies cannot be statically extracted
```

Beyond some sort of console.log override, is there a way to suppress this warning even if only in the server-side output?

**Comment by dnutels** [comment]
Is there no response? At all?

Having the ability to control the tool's logging level/output seems instrumental, yet there is currently no way to show only errors, while skipping (or folding) warnings...

**Comment by jorilallo** [comment]
I would like to see a way to suppress warnings as well. As per #1617 many popular libraries (e.g. Quill, localforage) come build with Browserify, I don't really see the point of repackaging them and installing random loaders in the process. I would much rather use the original if it works and not see the warning contantly.

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#147
