### ISSUE TITLE
Add option to ProgressPlugin to send output to stdout

### ISSUE THREAD

**Issue by ecraig12345** [webpack/webpack#8871]
## Feature request

**What is the expected behavior?**
ProgressPlugin should have an option to send output to `process.stdout` rather than `process.stderr`. (This is somewhat related to #3520.)

It's already possible to do this (and maintain the nice default formatting) by copying the default handler implementation from the ProgressPlugin source into my config, changing the single line that sets the output stream, and passing it to the plugin instance as a custom handler...but this is far from ideal.

**What is motivation or use case for adding/changing the behavior?**
Using stderr for routine diagnostic output is misleading to tools which assume any output to stderr indicates an actual error (and then the tool may incorrectly indicate to the user that the build failed).

**How should this be implemented in your opinion?**
Add an option to the ProgressPlugin to use stdout instead of stderr. First idea is `useStdout: boolean` (default false) but open to suggestions. An idea borrowed from another plugin would be a `stream` option defaulting to `process.stderr` but you can pass in `process.stdout` or any other stream. 

**Are you willing to work on this yourself?**
yes -- mainly opening an issue to find out if the idea is welcome before doing it :)

**Comment by kemmis** [comment]
+100000

Please reconsider implementing this option. This is causing significant headaches downstream, and adding this option will make the world a better place!

**Comment by evilebottnawi** [comment]
@kemmis why do you need this?

**Comment by sokra** [comment]
while stderr is on fact the right location for such output, you can create a plugin which provides a custom infrastructureLogger which writes to stdout instead.

**Comment by kemmis** [comment]
@evilebottnawi Thanks for the quick response. So here's the story:

Over on the [asp.net core project](https://github.com/dotnet/aspnetcore/issues/17277) devs are pulling their hair out and in some cases taking cyanide pills during their lunch breaks. The magic part of the framework that pipes communications between asp.net core and the angular cli depends on turning on 'progress' messages so it gets a progress indicator saying everything is ready on the cli server side. However when you turn that progress setting to true, there's a fire hose of error message that flood the console from webpack. Honestly I'm not exactly sure why this just started happening now. I've read things on the asp.net core issues saying that "this is an angular cli issue" and that it's out of their hands. And I clearly see people screaming about this on various other projects not related to asp.net core.

I do understand that it is an option to create your own progress plugin. Yes that's an option. That would however create greater "technical debt" for lack of a better description. You guys have a really nice default progress plugin that, and if we fork it and have to use a modified version of it, then folks like us will likely lose any bug fixes or updates to your default plugin in the future. Or worse, we'll experience breaking changes in the future 😱

I know that the specific issue I linked to above is likely in the hands of the angular cli team. If you do add this option, I think it will make the angular cli team's job easier, as well as for the rest of the community that uses webpack. 

So please consider this as a feature request and not users just complaining that they don't think the progress should be considered stderr or not. I personally don't have an opinion. But I do think this feature would offer a solid amount of value to the webpack project. I think there's a lot of bang for your buck on this one.

Thanks for reading and considering!

**Comment by ambirdsall-gogo** [comment]
> while stderr is in fact the right location for such output

This is one interpretation, but considering the history and standards of cli tooling, it is a nonstandard one. For example, [the GNU C library](https://www.gnu.org/software/libc/manual/html_node/Standard-Streams.html) documents the stdout and stderr file handles as such:
> Variable: FILE * stdout
> The standard output stream, which is used for normal output from the program.
>
> Variable: FILE * stderr
> The standard error stream, which is used for error messages and diagnostics issued by the program.

Progress reports could arguably be considered diagnostic; but they are certainly part of the normal output of the program, much more than they are a natural fit for the grouping "error messages and diagnostics". For this reason, many downstream tools (appropriately) consider stderr output an indication of warnings or errors, which causes a great deal of noisy false positives when including webpack into conventional CLI pipelines, and can obscure legitimate error reporting.

I do hope you reconsider which behavior should be relegated to custom plugins and reopen this PR; but regardless, thank you for putting in the time and effort to maintain such a useful project.
