### ISSUE TITLE
Display a warning in the browser log for existing window.webpackJsonp on the page when mode = development

### ISSUE THREAD

**Issue by JanThiel** [webpack/webpack#8872]
## Feature request

**What is the expected behavior?**

When there are multiple WebPack compilations on a single page (two ore more total differnt projects being used on the same page e.g.) the code from the later loaded ones will not be executed as you expect. There is a note (kind of) hidden within the docs how to solve it ( https://webpack.js.org/configuration/output/#outputjsonpfunction ) as the **webpackJsonp** object is bound to the window object and will be merged together.

Strangely, the code *does* execute when being built in ```mode: development```. But this is another riddle to solve...

For this Feature Request, I would solely ask for hint (aka colsole.warn) from the code, being built in ```mode: development``` if there already is a ```window.webpackJsonp``` (or ```window.[output.jsonpfunction]```). It should note, that this might lead to unexpected issues or chunks not being executed at all. Maybe also pointing to the ```output.jsonpfunction``` documentation.

**What is motivation or use case for adding/changing the behavior?**

Could have saved me hours of searching and digging in an edge-case that is well known by the developers, documented and technically easy to detect. As there are no obvious errors in this case, it is very hard to trace back if you do not know about the particular **webpackJsonp** name that can and has to be configured. I found this solution more by chance than by debugging.

**How should this be implemented in your opinion?**

If there already is a window.webpackJsonp object defined and the bundle was built in mode: development, log / warn / error something to the console / log. This should increase developer happiness alot and prevents unexpected errors.

**Are you willing to work on this yourself?**
maybe

**Comment by JanThiel** [comment]
*bump* Still obviously an issue :-(

**Comment by Aswathprabhu** [comment]
Can I work on this @sokra ?

**Comment by JanThiel** [comment]
This issue also affects the "create react app" tool. I (as well as some others) opened a issue over there. Just for reference: https://github.com/facebook/create-react-app/issues/7959 . 
Maybe it would be a smart move to solve this issue at the root of the cause at all by randomly generating the name of the `webpackJsonp` function if it is not set manually?
This would make checks and any configurational solution obsolete.

Is there any special reason why the `webpackJsonp` function name has to be statically hardcoded (if not configured)?

**Comment by evilebottnawi** [comment]
bump

**Comment by ceejtron** [comment]
+1 to a solution that either warns of this condition, or prevents it by auto-generating a unique function name. This issue caused a system-wide outage at my company (affecting Fortune 500 companies).

**Comment by sokra** [comment]
Webpack 5 will generate a unique name by default based on the name in package.json

**Comment by ceejtron** [comment]
Excellent news @sokra ! Thanks for the quick reply 😄
