### ISSUE TITLE
Scope is incorrectly determined when using function expressions.

### ISSUE THREAD

**Issue by MathijsMeijer** [webpack/webpack#8874]
# Bug report

**What is the current behavior?**
The imported function `someFunction` in `index.js` is incorrectly called from within the inline function expression `someFunction` in `index.js` instead of calling itself recursively.

**If the current behavior is a bug, please provide the steps to reproduce.**
Gist:
https://gist.github.com/MathijsMeijer/660d19a5eaccb819a5c3ccb12b2e9323

Structure:
`wp.js` 
`src/index.js`
`src/someFunction.js`

Run `npm i webpack` and `node wp.js`.

**What is the expected behavior?**
The inline function expression `someFunction` in `index.js` should call itself recursively. The imported function `someFunction` should _not_ be called.

**Other relevant information:**
webpack version: 4.29.6 / 5.0.0-alpha.11
Node.js version: 10.15.0
Operating System: MacOS 10.14.3
Additional tools: n/a

**Comment by sokra** [comment]
hmm yes this seem to be a bug in the Parser. Do you want to try to send a PR fixing it?

This is the buggy code fragment:

https://github.com/webpack/webpack/blob/685a0626cb10664133ef2fb2e2f9f4cb3971402a/lib/Parser.js#L1593-L1609

I think you can fix it by concatenating the function name to the first argument of `inScope`.

For a test case you can add a directory in `test/cases/parsing`
