### ISSUE TITLE
The Webpack homepage doesn't handle all page widths properly

### ISSUE THREAD

**Issue by Ajacmac** [webpack/webpack#8878]
# Bug report

**What is the current behavior?**

The "It's" in "It's That Simple" gets partially clipped by the left side of the page if the page width is between 768 and 1050 px.

**If the current behavior is a bug, please provide the steps to reproduce.**

1.) Visit the homepage
2.) Adjust the width of the page to something between 768 and 1050 pixels.

**What is the expected behavior?**

To be able to read the text on the page.

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

This was a little tongue in cheek, but I didn't want the issue getting deleted!
I would have submitted a pr, but I couldn't find the code for the website anywhere. Maybe I'm just blind?

Thanks!

**Comment by Ajacmac** [comment]
Also, if there's a better place for this to go I'm happy to put it there.

Thanks again!

**Comment by montogeek** [comment]
@webpack-bot move to webpack/webpack.js.org
