### ISSUE TITLE
the 'entry' option doesn't work .

### ISSUE THREAD

**Issue by littlegrayss** [webpack/webpack#8882]
# Bug report

**What is the current behavior?**
```
const path = require("path");
module.export = {
    entry: './src/main.js',
    output: {
        filename: "[name].bundle.js",
        path: path.resolve(__dirname, "dist")
    }
}
```
when I set the `entry` to `'./src/main.js'` in `webpack.config.js` and tried to run it , I got an error `Can't resolve './src' in xxx...` just like [this issue](https://github.com/webpack/webpack/issues/6858). In that question someone said src folder didn't exist, but in this question I am sure that I have the src folder and it is in the correct site.

I tried other ways, I set the entry `'./public/index.js'`, it still told me `Can't resolve './src' in xxx...'`, I'm not set the src path! Even I set the `entry` empty string, I got the same error.

In the last, I created the `index.js` in the `src`, it ran correctly.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/littlegrayss/an-example-of-webpack-issue
1. clone down and install webpack
2. `npm run build`

**What is the expected behavior?**
I want to set the `entry` option as I like, but it seems not.
So, if we must follow this struct: 'src/index.js'? I cannot find any tips on document about it.

I am sorry about my terrible English, but,  no matter what, I hope someone can explain why it work strangely. I will thank for him.

**Other relevant information:**
webpack version:  4.29.6
Node.js version: v8.15.0
Operating System: Windows 10
Additional tools:

**Comment by devakrishna33** [comment]
Use module.exports = { ... } instead of module.export = { ... }

**Comment by littlegrayss** [comment]
@devakrishna33 it works，thank you！can you tell me why?

**Comment by montogeek** [comment]
Because it is `exports`.
