### ISSUE TITLE
output.futureEmitAssets option breaks compatibility with source map upload plugins

### ISSUE THREAD

**Issue by bengourley** [webpack/webpack#8883]
# Bug report

The [`output.futureEmitAssets`](https://github.com/webpack/webpack/pull/8642) option added in v4.29 breaks [`BugsnagSourceMapUploaderPlugin`](https://github.com/bugsnag/webpack-bugsnag-plugins#new-bugsnagsourcemapuploaderpluginoptswebpackplugin) (specific Webpack version tested: 4.29.6).

Full disclosure, I am the maintainer of [`webpack-bugsnag-plugins`](http://npm.im/webpack-bugsnag-plugins).

#### Related issues

https://github.com/bugsnag/webpack-bugsnag-plugins/issues/28
https://github.com/honeybadger-io/honeybadger-webpack/issues/85
https://github.com/thredup/rollbar-sourcemap-webpack-plugin/issues/61

### Current behaviour

The source map uploader implements an `afterEmit` plugin which makes use of [`source.existsAt` to find the location of the output files and their accompanying source maps](https://github.com/bugsnag/webpack-bugsnag-plugins/blob/4e9cc038e77e363edfc567f2ae755c5ef9d87bcd/source-map-uploader-plugin.js#L72-L73). When the new option `output.futureEmitAssets` is switched on (which I understand is to be the new default), the sources in the `afterEmit` hook no longer have the `existsAt` property. This property does not exist on the sources in the `emit` stage either, presumably because the files are not yet written to disk, but I assume the compiler must know where the files will end up being written?

### Steps to reproduce

Add `BugsnagSourceMapUploader` to any Webpack project using >=4.29 and enable `output.futureEmitAssets`. Or check out [this repro](https://github.com/bengourley/bugsnag-webpack-emit-assets-repro).

### Expected behaviour

At some stage around `emit`/`afterEmit` I would expect there to be information on where a file exists on disk, so that the `BugsnagSourceMapUploaderPlugin` can retrieve it. Prior to v4.29 this was the case, but subsequently it does not.

**Other relevant information:**
webpack version: 4.29.x
Node.js version: any compatible
Operating System: any
Additional tools:  [`webpack-bugsnag-plugins`](http://npm.im/webpack-bugsnag-plugins)

**Comment by sokra** [comment]
You don't need `existsAt`. Join filename and output path to get the full path.

https://github.com/webpack/webpack/blob/685a0626cb10664133ef2fb2e2f9f4cb3971402a/lib/Compiler.js#L333-L336

https://github.com/webpack/webpack/blob/685a0626cb10664133ef2fb2e2f9f4cb3971402a/lib/Compiler.js#L443

**Comment by bengourley** [comment]
Thanks! Switching to that kind of implementation worked for us. For anybody else interested here's the change we made: https://github.com/bugsnag/webpack-bugsnag-plugins/pull/29.
