### ISSUE TITLE
requireEnsure is not included in runtime chunk

### ISSUE THREAD

**Issue by smashercosmo** [webpack/webpack#8884]
# Bug report

**What is the current behavior?**
In certain circumstances requireEnsure function is not included in runtime chunk

**If the current behavior is a bug, please provide the steps to reproduce.**
Repro repo https://github.com/smashercosmo/webpack-require-ensure-issue
1. Run ```npm run build```
2. Then run ```npm run serve```
2. Open ```localhost:3000```
3. Check console output

**What is the expected behavior?**
requireEnsure function should be included in runtimeChunk

**Other relevant information:**
webpack version:   4.29.6
Node.js version: 11.11.0
Operating System: MacOS Sierra

**Comment by sokra** [comment]
Your repro works fine...

![image](https://user-images.githubusercontent.com/1365881/54442110-528c9480-473e-11e9-91c0-3b6ac414124b.png)

**Comment by smashercosmo** [comment]
@sokra I'm sorry. Haven't checked it properly. I updated the repo. Now you should see the issue.

**Comment by smashercosmo** [comment]
@sokra I assume that the problem is that 'intersection-observer' polyfill is included in vendor chunk and thus stops being an async chunk and thus requireEnsure function is not included in runtime.

**Comment by smashercosmo** [comment]
@sokra did you have a chance to look at the issue?

**Comment by smashercosmo** [comment]
@sokra hi, just asking again)

**Comment by smashercosmo** [comment]
@sokra friendly ping

**Comment by smashercosmo** [comment]
Still relevant

**Comment by evilebottnawi** [comment]
@smashercosmo yep, look like a bug, thanks for issue

**Comment by sokra** [comment]
Seem like webpack 5 doesn't have this problem.

**Comment by evilebottnawi** [comment]
@smashercosmo Fixed in webpack@5, thanks for issue
