### ISSUE TITLE
Vuejs after firebase deploy get no <%= htmlWebpackPlugin.files.publicPath %> in index.html

### ISSUE THREAD

**Issue by postalangel** [webpack/webpack#8887]
# Bug report

**What is the current behavior?**
After firebase deploy of vue js project I get blank page because <%= htmlWebpackPlugin.files.publicPath %> is not working and also webpack chunks have same behaviour

**If the current behavior is a bug, please provide the steps to reproduce.**
Using latest node, npm, vue3 cli initiated project with webpack (by running npm install -g @vue/cli-init), latest firebase and firebase-tools. After npm run build - then run firebase deploy and got same error - tried in 2 different directories

**What is the expected behavior?**
to load web app public path and chunks by rendering index.html correctly

webpack is loading index.html correctly on localhost

**Other relevant information:**
webpack version:  
4.29.6
Node.js version: 
10.15.3
Operating System: 
windows 10
Additional tools:
firebase 5.8.6

**Comment by evilebottnawi** [comment]
Please create issue in `html-webpack-plugin` or `vue-cli`, we can't do here on our side, thanks!
