### ISSUE TITLE
I can't build because Module not found: Error: Can't resolve 'validator'

### ISSUE THREAD

**Issue by lethienhoang** [webpack/webpack#8888]
in ....js 
I called this one `const validator = require('validator');`
After I run command by npm run dev:build
```
ERROR in ./src/modules/users/user.model.js
Module not found: Error: Can't resolve 'validator'
```

In webpack.development.config.js

```
const nodeExternals = require('webpack-node-externals');
const path = require('path');

module.exports = {
    mode: 'development',
    target: 'node',
    externals: [nodeExternals()],
    entry: {
        'index': './src/index.js'
    },
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: '[name].bundle.js',
        libraryTarget: 'commonjs2'
    },
    module: {
        rules: [{
            test: /\.js$/,
            exclude: /node_modules/,
            use: 'babel-loader'
        }]
    },
    resolve: {
        alias: {
            apiAlias: path.resolve(__dirname, './src/modules/')
        }
    }
}
```

Can everyone help me to resolve it? Thank you.

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
