### ISSUE TITLE
Module ids with trailing slash inconsistent with node.js behavior

### ISSUE THREAD

**Issue by nathan** [webpack/webpack#8889]
# Bug report

**What is the current behavior?**
`require('some-module/')` resolves to `node_modules/some-module.js` in webpack, while node resolves this to `node_modules/some-module/index.js` because of the trailing slash.

**If the current behavior is a bug, please provide the steps to reproduce.**
Here is a minimal example: https://gist.github.com/nathan/972d601c02fcf4cde50c43a3b91a5d9a

Note that `require('./local/')` with a trailing slash matches node's behavior, while `require('mod/')` doesn't. `require('mod/subdir/')` is also inconsistent with node.

**What is the expected behavior?**
Webpack should match the node behavior and respect the trailing slash in `require('some-module/')`.

**Other relevant information:**
webpack version:  4.29.6
Node.js version: 11.11.0
Operating System: macOS 10.14.3
Additional tools: none

**Comment by sokra** [comment]
yep this seem to be a bug in `enhanced-resolve`.

**Comment by evilebottnawi** [comment]
Bump

**Comment by evilebottnawi** [comment]
bump
