### ISSUE TITLE
i want kown why css be tree shaked ??? 

### ISSUE THREAD

**Issue by cleverboy32** [webpack/webpack#8891]
## Feature request
i look the introduce of tree shaking, still cant kown why css file will be remove.
i am very confiused, can someone help? 
and i watch the side-effect-plugin file , kown that you check if one module is side-effect-free to remove it. is that my css file be a module ? 

my vue file, has style block, i config `sideEffect: '.*css'`, it still be remove, unless i set my vue file is side effect.  why ？ in webpack, the css will be use by css-loader, like the official-document, it will not be remove right.

**What is the expected behavior?**

**What is motivation or use case for adding/changing the behavior?**

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
yes

**Comment by evilebottnawi** [comment]
@cleverboy32 please create minimum reproducible test repo, thanks!

**Comment by cleverboy32** [comment]
opps!  tree shaking,
i thought you kown the question, cause the document hava a tips.
![image](https://user-images.githubusercontent.com/17595456/54116211-3ed4eb80-4429-11e9-8266-17ebfbf7d650.png)

**Comment by evilebottnawi** [comment]
@cleverboy32 so we can close issue?

**Comment by cleverboy32** [comment]
here the reproducible [test repo](https://github.com/cleverboy32/tree-shaking-css)
you can build and open index.html , its no css file. 
and i set sideEffects: [" *.css "] , it still be remove. and i want to kown the reason。 and if i set sideEffects: false , mean i cant use the tree shaking feature, its will be no good is it ?

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.
