### ISSUE TITLE
[question] `module.rules`: what is the difference between `rule.rules` and `rule.oneOf`

### ISSUE THREAD

**Issue by lovetingyuan** [webpack/webpack#8892]
I have a question about nest rules.
What is the difference between `rule.rules` and `rule.oneOf`.
I know `rule.oneOf` will pick the first rule matched, what about `rule.rules`?
(sorry, I question it in stackoverflow and gitter, but no reply there.)

**Comment by devakrishna33** [comment]
The rule.rules applies all the loaders in order as appears in the array (rule.rules)
`rules: [
            {
                test: /\.css$/,
                rules: [
                    {
                        test: /\.css$/,
                        use: 'style-loader',
                    },
                    {
                        test: /\.css$/,
                        use: 'css-loader',
                    },
                ]
            }
        ]`

The above code is equivalent to `rules: [
            {
                test: /\.css$/,
                use: ['style-loader', 'css-loader']
            }
        ]`

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Answer https://github.com/webpack/webpack/issues/8892#issuecomment-471458654

Please use `gitter` or `stackoverflow` for questions, or you can create issue in `webpack-doc` repo, thanks!
