### ISSUE TITLE
Support built-in modules

### ISSUE THREAD

**Issue by philipwalton** [webpack/webpack#8896]
## Feature request

**What is the expected behavior?**

Chrome is currently shipping [KV storage](https://developers.google.com/web/updates/2019/03/kv-storage) (behind a flag, origin trial coming soon), which is the first of many planned [built-in modules](https://github.com/tc39/proposal-javascript-standard-library/) on the web.

The issue with webpack is that built-in modules are only consumable via native `import` statements, which webpack [does not currently support](https://github.com/webpack/webpack/issues/2933).

Ideally, a developer would be able to include the following in their source code, and webpack (perhaps with the help of a plugin) would know how to optimally load it.

```js
import {storage} from 'std:kv-storage';

storage.set('key', 'value');
```

**What is the motivation or use case for adding/changing the behavior?**

Built-in modules offer a way for developers to import code into their projects with no download, cost. And they're actually usable in production today because they have viable fallback mechanisms:

*   [Import maps](https://github.com/WICG/import-maps) provide a fallback for browsers that don't support the built-in modules.
*   And <code>[module/nomodule builds](https://philipwalton.com/articles/deploying-es2015-code-in-production-today/)</code> provide a fallback for browsers that don't support imports.

The only thing preventing webpack users from using built-in modules in their projects today is that webpack itself doesn't support outputting in module format.

Note: if you're curious, here's [a small demo](https://rollup-built-in-modules.glitch.me/) ([source code](https://glitch.com/edit/#!/rollup-built-in-modules?path=rollup.config.js:1:0)) of a site using built-in modules (via Rollup) and using the above fallbacks so it works in all browsers. In Chrome 74+ (with the experimental web platform features flag turned on), the built-in module is used. In all other browsers a polyfill is loaded.

**How should this be implemented in your opinion?**

In my opinion, the best way to enable this would be to add full support for ES module output, eliminating the current ES5 runtime code and depending entirely on `import` statements to load chunks.

But since I assume supporting ES module output would be a lot of work, it would be nice if (at minimum) webpack could be configured to preserve unresolved (or external) module import statements.

I've filed [a separate issue for this feature](https://github.com/webpack/webpack/issues/8895). If support were added, I think it would make it possible (albeit in a slightly hackish way) for webpack users to use built-in modules in their bundles while we wait for proper ES module support.

**Are you willing to work on this yourself?**

I'm willing to help, but cannot commit to full implementation.

**Comment by glen-84** [comment]
Possibly related: #2933, #8010.

**Comment by philipwalton** [comment]
@glen-84 definitely related, but I filed this separately because I suspect it may be easier to support built-in modules as an incremental change rather than needing to wait for full module support.

**Comment by evilebottnawi** [comment]
@philipwalton PR welcome :+1:

**Comment by vankop** [comment]
> That trial has ended, and KV Storage is no longer available.
