### ISSUE TITLE
Reuse/Reassign global variable in browser

### ISSUE THREAD

**Issue by Apidcloud** [webpack/webpack#8898]
Good afternoon!

I have a monorepo, where each included package gets its own UMD bundle. Thing is, when I import those bundles to the browser, it replaces the library variable every time (i.e., I will only be able to access the last included script). Is there any good way of reassigning to the same global variable? I would like to avoid creating a single bundle just because of the browser. I mean, the point of UMD is to be used on the browser too, so it seems kind of a waste to do another build. I would also like to **avoid assigning** the output directly to the `window`.

Here's my output:
```js
output: {
	// ...
    library: "MyLibrary",
    // export itself to UMD format
    libraryTarget: "umd",
    umdNamedDefine: true,
    // fix for https://github.com/webpack/webpack/issues/6525
    globalObject: `(typeof self !== 'undefined' ? self : this)`
  }
```

And the HTML page:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>My Javascript Library Test</title>
    <script src="../packages/one/dist/mylibrary-one.js"></script>
    <script src="../packages/two/dist/mylibrary-two.js"></script>
  </head>

  <body>
    <div id="app"></div>
    <script src="main.js"></script>
  </body>
</html>
```

As it is, I only only have access to `mylibrary-two` as it is creating `MyLibrary` global variable again.

Any suggestions? I have asked the same question on stackoverflow ([here](https://stackoverflow.com/questions/55035197/webpack-how-to-reuse-global-library-name-when-it-already-exists)) and twitter a few days ago, but got no answers.

Thanks!

**Comment by sokra** [comment]
Don't use the same library name twice.

Maybe `library: ["MyLibrary", "two"],` works for you.

**Comment by Apidcloud** [comment]
@evilebottnawi 	My bad, but no template was shown when I created the issue for some reason?

Thank you @sokra! That definitely seems a viable option. That makes accessible through `MyLibrary.two`. Any way to do that for multiple entries? Something like: `library: [["MyLibrary", "one"], ["MyLibrary", "two"]]`

**Comment by evilebottnawi** [comment]
@Apidcloud Can we close issue?

**Comment by Apidcloud** [comment]
Yes, thank you!

On 13 Mar 2019, at 06:05, Evilebot Tnawi <notifications@github.com<mailto:notifications@github.com>> wrote:


@Apidcloud<https://github.com/Apidcloud> Can we close issue?
