### ISSUE TITLE
Using query parameters to loaders when loader is implicit

### ISSUE THREAD

**Issue by altano** [webpack/webpack#89]
It is not obvious how I would specify a parameter to a loader that is implicitly mapped by extension.  For example, I'm writing a [handlebars](http://handlebarsjs.com/) loader and it requires taking a query parameter to specify that the template should be loaded as a partial and not a full template.  How should I advise end-users to use it?

One way would be to do this:

```
<add handlebars-loader to loader list for ".handlebars" files>
require("!!handlebars?partial!templates/highlight.handlebars");
var bookTemplate = require("templates/book.handlebars");
```

But in the docs you frown on using "!!" outside of loader internals, so I assume I'm doing something wrong.

Another would be to not add 'handlebars' to the loader list and always explicitly use it:

```
require("handlebars?partial!templates/highlight.handlebars");
var bookTemplate = require("handlebars!book.handlebars");
```

Is there some third way that is better, e.g.?:

```
<add handlebars-loader to loader list for ".handlebars" files>
require("templates/highlight.handlebars?partial");
var bookTemplate = require("templates/book.handlebars");
```

**Comment by wingrunr21** [comment]
Following up on the original question, is there indeed no way to pass a query parameter to a pre-configured loader?

As an example:

```
require('../assets/foo.svg')
require('?inline!../assets/foo.svg')
```

This would allow the same asset file to be loaded both inline or as an embedded asset. Right now, it works via

```
require('!svg?inline!../assets/foo.svg')
```

but if there's a way to use the already configured loader that'd be awesome
