### ISSUE TITLE
Module Error (from ./node_modules/eslint-loader/index.js):

### ISSUE THREAD

**Issue by Momodoujobe** [webpack/webpack#8900]
I am getting an error everytime I run yarn watch --debug

Module Error (from ./node_modules/eslint-loader/index.js):

![image](https://user-images.githubusercontent.com/46496452/54211628-04fef600-44b8-11e9-9cae-97f908566df7.png)

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
