### ISSUE TITLE
Module Error (from ./node_modules/eslint-loader/index.js)

### ISSUE THREAD

**Issue by Momodoujobe** [webpack/webpack#8901]
# Bug report

**What is the current behavior?**
I am getting this error when I run yarn watch --debug
Module Error (from ./node_modules/eslint-loader/index.js)
![image](https://user-images.githubusercontent.com/46496452/54217896-d8041080-44c2-11e9-91a0-f5ae8fffa557.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version: v4.29.6 
Node.js version: 10.1
Operating System: MacBook Pro
Additional tools: VS Code

**Comment by evilebottnawi** [comment]
@webpack-bot move to `webpack-contrib/eslint-loader`

**Comment by evilebottnawi** [comment]
@webpack-bot move to `webpack-contrib/eslint-loader`

**Comment by evilebottnawi** [comment]
Please create issue in https://github.com/webpack-contrib/eslint-loader and attach minimum reproducible test repo, thanks
