### ISSUE TITLE
Uncaught ReferenceError: ... is not defined

### ISSUE THREAD

**Issue by Re-Mind** [webpack/webpack#8902]
# Bug report

**What is the current behavior?**

```
Uncaught ReferenceError: Mechanism is not defined
  (anonymous function)	
  (anonymous function)	
  ./src/Car.ts	
  __webpack_require__	
  (anonymous function)	
  ./src/UserAI.ts	
  __webpack_require__	
  (anonymous function)	
  ./src/Mechanism.ts	
  __webpack_require__	
  (anonymous function)	
  ./src/Bus.ts	
  __webpack_require__	
  (anonymous function)	
  ./src/UserHuman.ts	
  __webpack_require__	
  (anonymous function)	
  ./src/app.ts	
  __webpack_require__	
  (anonymous function)	
  (anonymous function)	
```

**If the current behavior is a bug, please provide the steps to reproduce.**
There are 5 simple classes on TypeScript (es6 target and module):
UserHuman -> `Bus -> Mechanism`
UserAI -> `Car -> Mechanism`

Entry point:
`var user:UserHuman = new UserHuman();`

```
import UserAI from "./UserAI";

export default class Mechanism
{
	constructor()
	{
		if (user instanceof UserAI) // <-- problem occurs with any use 'UserAI'
		{
			//...
		}
	}
}
```
```
import Mechanism from "./Mechanism";

export default class Bus extends Mechanism
{
	constructor()
	{
		super();
	}
}
```
```
import Mechanism from "./Mechanism";

export default class Car extends Mechanism
{
	constructor()
	{
		super();
	}
}
```

```
import Bus from "./Bus";

export default class UserHuman
{
	private _target:Bus = new Bus();
}
```
```
import Car from "./Car";

export default class UserAI
{
	private _target:Car = new Car();
}
```

**The problem disappears when there are two flags in webpack.config.js:**
```
optimization: {
	   concatenateModules: true,
	   minimize: true,
}
```

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

>     "ts-loader": "^5.3.3",
>     "webpack": "^4.29.6",
>     "webpack-cli": "^3.2.3",
>     "webpack-dev-server": "^3.2.1"
>     "typescript": "^3.3.3333"

**Comment by evilebottnawi** [comment]
@Re-Mind using `minimize: false` solve problem?

**Comment by Re-Mind** [comment]
No. Only when both flags are on.
 `concatenateModules: true` and `minimize: true`
	   ,

**Comment by evilebottnawi** [comment]
@Re-Mind maybe, `ts` transpile problem? Can you write this using `js` and reproduce problem?

**Comment by Re-Mind** [comment]
@evilebottnawi 
I did the same in pure javascript. The problem did not disappear.
Works only with:
```
mode: "none",
optimization: {
	   concatenateModules: true,
	   minimize: true,
 }
```
**webpack.config.js (when an error occurs):**
```
let path = require("path");
let config =
{
	entry: "./src/app.js",
	output:
		{
			path: path.resolve(__dirname, "./build"),
			filename: "bundle.js",
			publicPath: "build/"
		},
	mode: "development"	
};
module.exports = config;
```

**Comment by sokra** [comment]
Look like a circular dependency in your code.
