### ISSUE TITLE
Code Splitting - need more information on using dynamic imports with splitChunksPlugin

### ISSUE THREAD

**Issue by gaurav5430** [webpack/webpack#8904]
The docs mention 3 general approaches, and establishes that the entry point approach can be improved by using the splitChunksPlugin.

But then it goes on to remove the splitChunksPlugin when using dynamic imports.

Is there a reason why we can't use both dynamic imports and splitChunksPlugin?
If we just use dynamic imports would it make sure that the runtime is not part of each bundle ?
or that common dependencies are not part of each bundle.

If no, is there a suggested way to use splitChunksPlugin to do those optimizations along with dynamic imports ?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by gaurav5430** [comment]
Hey, 
I didn't delete the issue template.
I raised this issue using "Other - Something else" template, because I didn't think that it is actually an issue with webpack , but possibly with docs.

I would create a new issue with the issue template, if that helps.

**Comment by montogeek** [comment]
Please create it on webpack/webpack.js.org repository.
