### ISSUE TITLE
worker is cached using worker-loader

### ISSUE THREAD

**Issue by mysisi** [webpack/webpack#8906]
# Bug report

my loader config is: 
`      
rules: [
        {
          test: /\.worker\.js$/,
          use: [
            {
              loader: 'worker-loader'
            }
          ]
        }
      ]`

and i don't know why worker file is always cached unless i rename the worker file or add some random number after the import, as "import A from './a.worker?123'"

**Other relevant information:**
webpack version:  4.28.4
Node.js version: 8.11.3
Operating System: macOS 10.12
Additional tools: vue-cli3

**Comment by evilebottnawi** [comment]
@webpack-bot move to `webpack-contrib/worker-loader`
