### ISSUE TITLE
[SplitChunkPlugin] priority does not affect actual entry dependencies

### ISSUE THREAD

**Issue by MhMadHamster** [webpack/webpack#8908]
# Bug report

**What is the current behavior?**
Assuming we have entries "a" and "b" and two vendors "vendor-a" and "vendor-b". Entry "a" depends on "vendor-a" and entry "b" depends on "vendor-b", "vendor-b" itself also depends on "vendor-a". Now if we have such a cacheGroup "b" that captures both vendor modules, and one separate cacheGroup "a" for "vendor-a" specifically, adding higher ``priority`` to the cacheGroup "a" will correctly place "vendor-a" in the cacheGroup, however entry "a" will be still dependant on result of cacheGroup "b", i guess, because, it **possibly** can contain "vendor-a". See the example: https://github.com/MhMadHamster/webpack-minimal-example-rep

**If the current behavior is a bug, please provide the steps to reproduce.**
clone example rep: https://github.com/MhMadHamster/webpack-minimal-example-rep run ``yarn start`` check that what i described above is true, then you can change configuration for cacheGroup with key "b" to this:
```javascript
b: {
  test: /vendor-b/,
  name: "vendor-b",
  enforce: true,
},
```
run ``yarn start`` again, the only thing that will change in the result code is that entry "a" is no more depends on "vendor-b" as expected, however "vendor-a" and "vendor-b" generated code stays the same.

**What is the expected behavior?**
If chunk moved to the cacheGroup via ``priority`` option, entries which require this chunk should not depend on the other cacheGroups, which could have that chunk unless ``priority``.

**Other relevant information:**
webpack version: 4.29.6
Node.js version: 8.11.3
Operating System: Windows 10
Additional tools:

**Comment by vkrol** [comment]
@sokra thank you very much! It was so fast.
