### ISSUE TITLE
runtime errors in production build when combining commons chunk and runtimeChunk

### ISSUE THREAD

**Issue by mxmul** [webpack/webpack#8911]
# Bug report

**What is the current behavior?**

In the Webpack configuration provided below with a commons chunk, runtimeChunk, and ModuleConcatenation plugin enabled, the emitted scripts fail with a runtime error:

```
Uncaught TypeError: Cannot read property 'call' of undefined
    at f (runtime~main.js:1)
    at t (runtime~main.js:1)
    at Array.r [as push] (runtime~main.js:1)
    at main.js:1
```

**If the current behavior is a bug, please provide the steps to reproduce.**

The minimal repro seems to be something like this, built with `webpack --mode=production`:

_webpack.config.js_
```
module.exports = {
    optimization: {
        runtimeChunk: true,
        splitChunks: {
            minSize: 0,
            cacheGroups: {
                common: {
                    chunks: 'initial',
                    minChunks: 1,
                }
            },
        },
    },
};
```
_src/index.js_
```
import './a';
```
_src/a.js_
```
import './b';
```
_src/b.js_
```
console.log('hello world');
```

---

I've provided a reproducible example of this issue at [mxmul/webpack_weirdness_repro](https://github.com/mxmul/webpack_weirdness_repro). You can quickly see the error by running:
```
$ git clone git@github.com:mxmul/webpack_weirdness_repro.git
$ cd webpack_weirdness_repro
$ yarn && yarn build && yarn serve
```
and visiting http://localhost:5000

**What is the expected behavior?**

The emitted scripts run without errors, and "hello world" is printed to the console. This is what happens when built with `webpack --mode=development`.

**Other relevant information:**
webpack version:  v4.29.6
Node.js version: v8.11.3
Operating System: macOS 10.14.2
Additional tools:

**Comment by evilebottnawi** [comment]
Setup: `concatenateModules: false` solve problem, looks like bug

**Comment by evilebottnawi** [comment]
Feel free to send a PR
