### ISSUE TITLE
Documentation: devserver --open flag docs incorrect Chrome name for macOS

### ISSUE THREAD

**Issue by sookoll** [webpack/webpack#8912]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

> The browser application name is platform dependent. Don't hard code it in reusable modules. For example, 'Chrome' is Google Chrome on macOS...

**If the current behavior is a bug, please provide the steps to reproduce.**
Check at documentation: https://webpack.js.org/configuration/dev-server/#devserveropen

**What is the expected behavior?**
> The browser application name is platform dependent. Don't hard code it in reusable modules. For example, **'google chrome'** is Google Chrome on macOS...

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
macOS 10.14.2; node v11.2.0; webpack 4.29.6

**Comment by montogeek** [comment]
@webpack-bot move to webpack/webpack.js.org
