### ISSUE TITLE
Circular dependencies are said to be supported, yet broke my app?

### ISSUE THREAD

**Issue by WebDeg-Brian** [webpack/webpack#8914]
# Bug report

**What is the current behavior?**
Circular dependencies are supposed to work, although it's a bad pattern. In some of my previous projects it worked fine, but for some reasons it breaks my app this time. 

**If the current behavior is a bug, please provide the steps to reproduce.**
The folder structure is quite complicated to explain, so please clone [this repo](https://github.com/WebDeg-Brian/webpack-bug-investigation). Navigate to `/packages/client/src/components/shared/ContentWrapper/ContentWrapper.js` - This is whether the import returns undefined. The same import is invoked in `/packages/client/src/components/App/App.js`, but returns the expected value. Feel free to look around, the code is pretty simple as I just got started on this.

**What is the expected behavior?**
The import should return the correct value instead of `undefined`.

**Other relevant information:**
webpack version:  4.29.3
Node.js version: 8.11.3
Operating System: Windows 10
Additional tools: babel, eslint, prettier, lerna

**Comment by sokra** [comment]
Circular dependencies behave like defined in the spec. This doesn't mean everything magically works.

Try changing `client/src/misc/index.js` to:

``` js
export { default as theme } from './theme';
import * as constants from './constants';
export { constants };
```

This should move `theme` before the cycle.

**Comment by WebDeg-Brian** [comment]
@sokra Is there a way to make sure all the imports are in correct order?
