### ISSUE TITLE
How to resolve sourcemap when using require.context

### ISSUE THREAD

**Issue by scssyworks** [webpack/webpack#8918]
I am using require.context to load async chunks. I observed that the sourcemap files generated are not resolved for async chunks when ``require.context`` is used. I am getting sourcemaps for everything else.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
