### ISSUE TITLE
Webpack throws  Error: Chunk.parents: Use ChunkGroup.getParents() instead CommonsChunkPlugin

### ISSUE THREAD

**Issue by JustAnotherSoftwareDeveloper** [webpack/webpack#8921]
# Bug report

**What is the current behavior?**
When using a custom webpack builder in angular, webpack throws an error about an unsupported method. This breaks the build

**If the current behavior is a bug, please provide the steps to reproduce.**
I unfortunately found this on a project developed by my company. As such, I cannot publish the source code. This should be present with an Angular 2+ or Hybrid application

Code that errors out is in CommonsChunkPlugin.js, line 268. It's just calling into a method that will throw an error.

**What is the expected behavior?**
Webpack builds, or at least gets past that part. The best description I can give is that that code path should not be calling into a method that will throw an error. 

**Other relevant information:**
https://github.com/webpack/webpack/issues/8131  is another bug that referenced it. I was gonna go on a mini-rant about how while it's annoying to not use the template, the devs should still at least attempt to diagnose a solution. Then I realized, according to your site: https://opencollective.com/webpack, you don't have a FT dev. So instead I'd like to take this time to thank everyone involved and hope you get more money. If you need any more information I'll do my best

webpack version:  4.29.6
Node.js version: 10.13.0
Operating System: Ubuntu Linux 18.04
Additional tools: Angular, NPM

**Comment by evilebottnawi** [comment]
@JustAnotherSoftwareDeveloper `CommonsChunkPlugin` is deprecated in `webpack@4`. Without minimum reproducible test repo it is hard to say what is wrong, also i strongly recommend update webpack

**Comment by sokra** [comment]
`CommonsChunkPlugin.js` doesn't exist in the webpack version you mentioned. Seems like you are mixing two webpack versions somehow...

**Comment by BonBonSlick** [comment]
```
    "mocha-webpack": "^1.1.0",
replace with
    "mocha-webpack": "^2.0.0-beta.0",

```
helped in my case
