### ISSUE TITLE
Webpack outputs invalid code when 'require' is assigned by object literal shorthand

### ISSUE THREAD

**Issue by LuminescentMoon** [webpack/webpack#8929]
# Bug report

**What is the current behavior?**
The way Webpack replaces `require` assigned using [object literal shorthand](https://eslint.org/docs/rules/object-shorthand) is not valid syntax.

Using [this config](https://hastebin.com/onuriqetiv.js), this:
```js
let x = {
  require
}
```
is replaced with this:
```js
let x = {
  __webpack_require__("./src sync recursive")
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Download and extract [this archive](https://www.dropbox.com/s/nt70wacmi2qseks/test.7z?dl=1).
2. `npm i`
3. `npm run compile`
4. Check output in `dist` folder

**What is the expected behavior?**
This:
```js
let x = {
  require
}
```
should be resolved to this:
```js
let x = {
  require: __webpack_require__("./src sync recursive")
}
```

**Other relevant information:**
webpack version: 4.29.6
Node.js version: 11.11.0
Operating System: Windows 10 Enterprise v1809 b17763.379
Additional tools: None

**Comment by evilebottnawi** [comment]
Looks like a bug, feel free to send a PR

**Comment by lightyaer** [comment]
I'm willing to contribute,
can you point me to the file?

**Comment by arkadyt** [comment]
@evilebottnawi, it looks like we'll need to modify the `acorn` AST tree in the Parser.

When the shorthand syntax is used, acorn assigns the same object reference to both `key` and `value` props of the tree node. When shorthand syntax is not used, `key` and `value` props both correspond to their respective counterparts in the expression.

I was thinking to deep clone the object and figure out how to appropriately modify `loc` and `range` props, but I think that I'm looking in the wrong direction.

Any suggestions?

**Comment by evilebottnawi** [comment]
Just check what it is call

**Comment by arkadyt** [comment]
@evilebottnawi there are many things happening down the line, which place exactly do you mean?
`CommonJsRequireDependencyParserPlugin.js`? Or some function other than `walkObjectExpression` in the Parser?

I was talking in the context of `walkObjectExpression` function in my prev. post.

I'll look into this once again when I get home.

**Comment by evilebottnawi** [comment]
bump
