### ISSUE TITLE
Documentation for using custom cache objects?

### ISSUE THREAD

**Issue by wordofchristian** [webpack/webpack#893]
The docs show that you can supply a custom object to be used as the cache between multiple processes, http://webpack.github.io/docs/configuration.html#cache but it doesn't say much about how that object should behave. Specifically I'd like to use memecached and https://github.com/alevy/memjs. Any ideas on how to do this?

**Comment by mako-taco** [comment]
The cache object is a JS object that will hold cached module information at runtime. You provide an object `{}`to it, as well as other configs.  If they all share the same object, the cache will be shared. If you want to persist this cache between processes, you'll probably have to write the cached object to disk somehow, and load it in your other processes.  If it's a simple object, JSON parse/stringify would work for this.

**Comment by sokra** [comment]
> If it's a simple object, JSON parse/stringify would work for this.

It's not. Sharing between processes is currently not possible.

**Comment by wordofchristian** [comment]
In what structure does webpack build this Object?

**Comment by mwager** [comment]
I cannot get this to work. In the second run I can see that my custom object is filled (Object.keys(myCacheObject).length > 0), but the build is not faster at all. Am I doing anything wrong?

Somewhere outside:

    var myCacheObject = {};

Config:

    cache: myCacheObject
