### ISSUE TITLE
Allow code splits from async and entry files to be named as an entry file

### ISSUE THREAD

**Issue by noahgrant** [webpack/webpack#8930]
# Bug report

**What is the current behavior?**
Following up after not receiving a response from the comments in [this issue](https://github.com/webpack/webpack/issues/7235#issuecomment-423979096), if I have, say, a vendor file that I want extracted from both my async splits and my entry files, the resulting file is named as `chunkFilename` instead of `filename` and it is requested as a dependency of the code split as opposed to a dependency of the entry file. I think this is a bug, because it prevents us (we don't use webpack to build our HTML, only our js) from lifting up to a top-level script and taking advantage of browsers' look-ahead parsers. It prevents us from doing that because our chunks are hashed (`chunkFilename: '[name]-[chunkhash].js'`) and our entry files are not, so that we can version them ourselves outside of webpack (`filename: '[name].js]`).

There are two ways I see to solve this:

* name the files that depend on both as `filename` instead of `chunkFilename` (preferred)
* request the common chunk as a dependency of the entry file, requested first, as opposed to the chunk. this is less preferred because it wouldn't take advantage of the look-ahead parser. however, it would still get requested much sooner (after the webpack runtime executes, which we extract into a small initial script that is quickly loaded)

**If the current behavior is a bug, please provide the steps to reproduce.**

here's our optimize section, where we define our vendor file to be extracted from all of our chunks and entry files:

```js
  optimization: {
    splitChunks: {
      automaticNameDelimiter: '-',
      // this is for our other common chunks outside of our vendor cacheGroup. these are
      // extracted from split files only
      chunks: 'async',
      name: true,
      maxAsyncRequests: 3,
      cacheGroups: {
        vendor: {
          // the vendor file can be taken from both split and the entry file,
          // since vendor.js is a top-level script executed before our main entry file
          chunks: (chunk) => !chunk.canBeInitial() || chunk.name === ENTRY_FILE,
          test: ({resource}) => /node_modules/.test(resource),
          name: 'vendor'
        }
      }
    }
  }
```

and here is our output config:

```js
  output: {
    filename: '[name].js',
    chunkFilename: '[name]-[chunkhash].js',
    // important for ensuring the HMR runtime won't crash our worker scripts
    globalObject: 'this',
    path: `${root}build/js`,
    publicPath: '/js/'
  }
```

**What is the expected behavior?**
This configuration results in this behavior, taken from our production website:

<img width="1243" alt="Screen Shot 2019-03-19 at 11 47 33 AM" src="https://user-images.githubusercontent.com/1355779/54633869-46564f00-4a3e-11e9-93ae-8e49e8cb89cc.png">

The hashed file is the one that webpack automatically requests, but I would expect that the hash-less we hack together (we do hash it, of course, but we hash it ourselves and pass the hash to our pre-processed HTML file, outside of webpack) to be where webpack requests the file. Vendor files containing critical libraries, for example, React on a javascript-heavy SPA, must be downloaded and executed in its entirety before our code can run, so it makes sense to make this a blocking script, ensure its execution order, and take advantage of the look-ahead parser.

**Other relevant information:**
webpack version:  4.8.3
Node.js version: 10.15
Operating System: Mac OS 10.14
Additional tools: don't believe any are relevant for this

**Thank you very much!!**

**Comment by ppJuan** [comment]
@noahgrant
 I was also getting this problem. I solved it by identifying the filename of the code split chunks:
```javascript
                cacheGroups: {
                    commons: {
                        name: 'common',
                        chunks: 'initial',
                        minChunks: 2,
                        filename: 'js/[name].js',
                    },
                },
```

**Comment by noahgrant** [comment]
thanks @ppJuan, but doing that gives me the following error:

```
Error: SplitChunksPlugin: You are trying to set a filename for a chunk which is (also) loaded on demand. The runtime can only handle loading of chunks which match the chunkFilename schema. Using a custom filename would fail at runtime. (cache group: vendor)
```

this is because, as mentioned above, i'm not pulling from `'initial'` but from both `'initial'` and `'async'` via:

```js
 cacheGroups: {
   vendor: {
     chunks: (chunk) => !chunk.canBeInitial() || chunk.name === 'myEntryFile',
     test: ({resource}) => /(node_modules)/.test(resource),
     name: 'vendor'
   }
 }
```

what I'm really looking for is to have split files that pull from both be treated as initial files and named as such instead of async files. or at least to have the `filename` property in the `cacheGroup` act as an override.
