### ISSUE TITLE
Cannot read property 'thisCompilation' of undefined

### ISSUE THREAD

**Issue by levalencia** [webpack/webpack#8931]
# Bug report

**What is the current behavior?**

When I run npm run-script build I got this error: Cannot read property 'thisCompilation' of undefined

**If the current behavior is a bug, please provide the steps to reproduce.**

I created a new project, totally blank using these instructions:
https://developer.microsoft.com/en-us/fabric#/get-started
Follow steps 1-4

The application works fine.

Once I run npm i webpack 

Then I get this error

my package.json
{
  "name": "lulo",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "office-ui-fabric-react": "^6.157.0",
    "react": "^16.8.4",
    "react-adal": "^0.4.22",
    "react-dom": "^16.8.4",
    "react-scripts-ts": "3.1.0",
    "redux": "^4.0.1"
  },
  "scripts": {
    "start": "react-scripts-ts start",
    "build": "react-scripts-ts build",
    "test": "react-scripts-ts test --env=jsdom",
    "eject": "react-scripts-ts eject"
  },
  "devDependencies": {
    "@types/jest": "^24.0.11",
    "@types/node": "^11.11.3",
    "@types/react": "^16.8.8",
    "@types/react-adal": "^0.4.1",
    "@types/react-dom": "^16.8.2",
    "typescript": "^3.3.3333",
    "webpack": "^4.29.6",
    "webpack-cli": "^3.3.0"
  }
}

**What is the expected behavior?**
its a new project, with no other packages installed, its just completely blank, I dont see why its failing.

**Other relevant information:**
webpack version:  4.29.6
Node.js version:  10.0.0 
Operating System:  mac os
Additional tools:

**Comment by evilebottnawi** [comment]
Please create issue in `react-scripts-ts`, not related to webpack
