### ISSUE TITLE
Dynamic import from node_modules is not working

### ISSUE THREAD

**Issue by Miaoxingren** [webpack/webpack#8934]
# Bug report

**What is the current behavior?**

I made a vue component package `my-custom-comp`, which contains dynamic import:
`my-custom-comp.vue`
```
<template>
  <component v-if="id && data" :is="`list-${id}`" :data="data" />
</template>

<script>
export default {
  props: ['id','data'],
  components: {
    'list-1': () => import(/* webpackChunkName: "MyTaglist0" */'./list-1.vue'),
    'list-2': () => import(/* webpackChunkName: "MyTaglist0" */'./list-2.vue'),
    'list-3': () => import(/* webpackChunkName: "MyTaglist1" */'./list-3.vue'),
    'list-4': () => import(/* webpackChunkName: "MyTaglist1" */'./list-4.vue')
  }
}
</script>
```
Output files in lib:
```
  my-custom-comp.common.js
  my-custom-comp.common.MyTaglist0.js
  my-custom-comp.common.MyTaglist1.js
```
I have `my-custom-comp` package installed in my app, and add package path to  `resolve.modules`:
`webpack.config.js`
```
module.exports = {
  ...
  resolve: {
    modules: [path.join(__dirname, '../node_modules'), path.join(__dirname, '../node_modules/my-custom-comp/lib')],
  }
  ...
}
```
but `MyTaglist0.js` can't be resolved:
```
GET http://localhost:8882/my-custom-comp.common.MyTaglist0.js net::ERR_ABORTED 404 (Not Found)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

How to resolve dynamic import  from node_modules?

**Other relevant information:**
webpack version:  4.28.4
Node.js version: 10.3.0
Operating System: windows
Additional tools:

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo

**Comment by sokra** [comment]
`resolve.modules` is unrelated to this.

You may want to look into `output.publicPath` to setup to correct URL.

**Comment by Miaoxingren** [comment]
@sokra Could you be more specific? :cry:
According to the document:
```
module.exports = {
  //...
  output: {
    // One of the below
    publicPath: 'https://cdn.example.com/assets/', // CDN (always HTTPS)
    publicPath: '//cdn.example.com/assets/', // CDN (same protocol)
    publicPath: '/assets/', // server-relative
    publicPath: 'assets/', // relative to HTML page
    publicPath: '../assets/', // relative to HTML page
    publicPath: '', // relative to HTML page (same directory)
  }
};
```
I should upload dist files of `my-custom-comp`  to cdn or copy dist files of `my-custom-comp`  to app's `assets` folder? Is it possible to make webpack search this file from node_modules?

**Comment by Miaoxingren** [comment]
Same problem as #7843. :disappointed:

**Comment by evilebottnawi** [comment]
@Miaoxingren Please create minimum reproducible test repo

**Comment by alex-ayala** [comment]
@evilebottnawi I have also been dealing on this and I was able to create an example repo that replicates this issue: https://github.com/alex-ayala/dynamic-import-issue.

**Comment by Miaoxingren** [comment]
@alex-ayala :smile: thanks!
@evilebottnawi Please look at this repo.

**Comment by Miaoxingren** [comment]
@evilebottnawi Please look at this repo: https://github.com/Miaoxingren/webpack-issue-8934.

**Comment by Miaoxingren** [comment]
@sokra @evilebottnawi Any updates on this issue?

**Comment by adrianjost** [comment]
Does anyone yet has found a solution? This looks like an obvious problem and with that many libraries out there, someone must have found a solution I guess.

**Comment by evilebottnawi** [comment]
bump

**Comment by daltonmenezes** [comment]
Same here :(

```js
import(`${folderName}`)
import(folderName)

// Uncaught (in promise) Error: Cannot find module 'x' at lib lazy ^.*$ namespace object:43**

**Comment by ufon** [comment]
Any updates on this?

**Comment by younabobo** [comment]
Apparently none wants to work on this

**Comment by evilebottnawi** [comment]
Let's solve solution for this, @Miaoxingren reproducible repo still has the problem? Sorry for delay

@ufon @younabobo Maybe you can provide reproducible test repo too?

**Comment by younabobo** [comment]
Here's my test repository https://github.com/younabobo/webpack-dynamic-import-test

**Comment by ufon** [comment]
@younabobo @evilebottnawi 
Finally I fixed this by setting `__webpack_public_path__` webpack setting.
My problem was closely related to https://github.com/webpack/webpack/issues/7417

And my final solution is

```
  // Problem is described here:
  // https://github.com/webpack/webpack/issues/7417
  // Dynamic import chunks is loaded from public url webpack. By default this url is empty string.
  // This causes situation when we on some nested route - we loading chunks from this nested route.
  // But this is wrong path. So for fixing that I introduced global variable `resourceBaseUrl`.
  // And we can dynamically set this path with `__webpack_public_path__` setting help

  window.resourceBaseUrl = '';

  if (window.parent && window.parent.resourceBaseUrl !== window.location.pathname) {
    window.resourceBaseUrl = window.parent.resourceBaseUrl;
  } else {
    window.resourceBaseUrl = window.location.pathname;
  }
  
  // Later in the code
__webpack_public_path__ = window.resourceBaseUrl;
```

**Comment by evilebottnawi** [comment]
@younabobo It is documented, we can't build module from `x`, it is runtime value and it is impossible to detect https://webpack.js.org/api/module-methods/#dynamic-expressions-in-import

@ufon You need this https://github.com/webpack/webpack/issues/11127, we will implement it for webpack@5

Original problem related to https://github.com/webpack/webpack/issues/11127

**Comment by muke1908** [comment]
Hi @Miaoxingren, curious how were you able to fix this issue? I am having same problem even with webpack 5
