### ISSUE TITLE
webpack use @babel/plugin-syntax-dynamic-import get error

### ISSUE THREAD

**Issue by seek-distance** [webpack/webpack#8935]
# Bug report

**What is the current behavior?**
when I use @babel/plugin-syntax-dynamic-import to import some pack,expamle
![image](https://user-images.githubusercontent.com/18638579/54738596-d687c600-4bef-11e9-9a2f-9b5e41db3247.png)
![image](https://user-images.githubusercontent.com/18638579/54738597-d687c600-4bef-11e9-92c4-d9867a0d1803.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  4.29.5
Node.js version: 10.15.1
Operating System:  chorme
Additional tools: babel @babel/plugin-syntax-dynamic-import

**Comment by seek-distance** [comment]
when I use webpack 4.8.0 , this bug is fixed

**Comment by montogeek** [comment]
What is your question?

**Comment by evilebottnawi** [comment]
Not enough information to identify the problem
