### ISSUE TITLE
potential copyright issue from transitive dependency "wordwrap"

### ISSUE THREAD

**Issue by beiwei30** [webpack/webpack#8936]
[wordwrap](https://github.com/substack/node-wordwrap) publishes its test directory in which a text file 'idleness.txt' is included. This may introduce potential copyright issue.

see more from https://github.com/substack/node-wordwrap/issues/21

**Comment by evilebottnawi** [comment]
Please use `terser-webpack-plugin`, `uglify-js-webpack-plugin` for compatibility reasons

**Comment by beiwei30** [comment]
here's the dependency tree which eventually introduce the file in question.

```
└─┬ webpack@3.12.0
  └─┬ uglifyjs-webpack-plugin@0.4.6
    └─┬ uglify-js@2.8.29
      └─┬ yargs@3.10.0
        └─┬ cliui@2.1.0
          └── wordwrap@0.0.2
```

**Comment by sokra** [comment]
This has already been fixed in webpack 4. webpack 3 is no longer supported. Please upgrade.
