### ISSUE TITLE
Code behaves strangely after webpack production build

### ISSUE THREAD

**Issue by motopia** [webpack/webpack#8937]
# Bug report

**What is the current behavior?**
some source code:
``` js
const store = new Vuex.Store({
  modules: {
    app,
    permission,
    user,
  },
  getters,
});

export default store;
```

webpack build after production get code:

``` js
new o.a.Store({
            modules: {
                app: r,
                permission: c,
                user: f
            },
            getters: h
        })
```
devtool console have errors info:
**vendor.31143c62.js:33 TypeError: Cannot read property 'getters' of undefined**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

``` js
        var p = new o.a.Store({
            modules: {
                app: r,
                permission: c,
                user: f
            },
            getters: h
        });
        t.a = p
```

**Other relevant information:**
webpack version:   3.6.2
Node.js version:  6.9
Operating System: linux
Additional tools:

**Comment by evilebottnawi** [comment]
@motopia how we should put feedback on issue, no reproducible test repo, no config, nothing (only part of code), please provide more information, thanks

**Comment by motopia** [comment]
@evilebottnawi  Project is a background management project, the amount of code is a little too much, now found in the routing file is probably in more than 156, began to appear above the abnormal behavior, so a simple example can not reproduce the problem

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.
