### ISSUE TITLE
Since I upgraded to Webpack , I cannot have an "include" in my "rules".  What's the right way of doing it now?

### ISSUE THREAD

**Issue by rain201607** [webpack/webpack#8939]

**Comment by rain201607** [comment]
Before:
 ```
{
  test: /\.js$/,
  loader: 'babel-loader',
  include: 'node_modules/v-tooltip',
}
```
Now:
```
{
  test: /\.js$/,
  use: [{ loader: 'babel-loader' }]
  ???
}
```
what should i do?

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.
