### ISSUE TITLE
Clearing require.cache for testing

### ISSUE THREAD

**Issue by kentor** [webpack/webpack#894]
I'm using karma + jasmine + webpack to test my react app, following https://www.codementor.io/reactjs/tutorial/test-reactjs-components-karma-webpack.

Since my stores are singletons, I am clearing the module cache in a global `beforeEach` as to reset the state of the store and any other related module (actions/dispatcher/etc):

```javascript
beforeEach(() => {
  var cache = require.cache;
  for (var moduleId in cache) {
    delete cache[moduleId];
  }
});
```

This works, but as an optimization I want to clear only the modules from my own project, not any of the modules installed in `node_modules`. Is there a way to do this currently?

**Comment by kentor** [comment]
Figured it out with contexts.

**Comment by sokra** [comment]
``` js
delete require.cache[require.resolve("./module")];
```

**Comment by frodosamoa** [comment]
@kentor

How did you figure it out with contexts?

**Comment by kentor** [comment]
@frodosamoa 

see: https://github.com/kentor/react-flux-testing/blob/master/tests.webpack.js#L8-L17
https://github.com/webpack/docs/wiki/context#context-module-api

**Comment by fixpunkt** [comment]
For anybody coming here and wondering why this doesn't work as shown in the example repository: I had to use the "inefficient" method of clearing the cache. Also make sure you don't use ES6-style imports for your unit under test but require() during the test case execution.

**Comment by ponelat** [comment]
@fixpunkt thanks for that, so here is what solved my case...

Use any method to clear cache, such that `delete require.cache[id]` happens.
`import` only works if placed at the top of the document, and it'll contain a reference to the original exported object, which can get mutated.
So we need to call `require('something')` during runtime, to get a fresh obj.

example:
```js
var SomeObj;

describe('Something', function() {
  beforeEach(function() {
    delete require.cache[require.resolve('./some-obj')] // Clear the cache, this can be done in a way described in the example repo. Does not have to happen here

    SomeObj = require('some-obj') // Update our reference, this needs to happen here
  })
  it('should work', function() {
     expect(SomeObj.one).toEqual(1)
     SomeObj.one = 2; // Mutate object, unless we bust the cache, this is a global mutation - scary!
  })
})
```

> Note: this will work with karma + webpack bundles.

**Comment by jharris4** [comment]
Is there an easy way to clear the cache for a module AND all of its children?

For example, I want to clear the cache for a module that is loaded with the help of a webpack loader, which under the hood seems to be caching things at each stage along the loader chain.

Digging through the require cache, I'm seeing the following structure (234 is the id of the module in the cache I want to clear):

234
  children: []
  parents: [233]

152
  children: [89]
  parents: [234]
  
89
  children: []
  parents: [147,152]  

147
  children: []
  parents: [152]

The things is, if I delete 234 from the cache, 152, 89, and 147 will still be present, but I need to clear those children as well for things to work properly for my scenario.

I find it odd that 152 has 234 as a parent, yet 152 does not show up in the children list of 234. This makes it tricky/non-trivial to do a traversal and delete the cached children... Am I missing something here?

**Comment by eugeneglova** [comment]
hey @jharris4 did you found a way how to clear cache for webpack build modules? I also need this feature for `mocha --watch` when it require file built by webpack it gets the file from webpack cache so it doesn't execute it again :(

**Comment by jharris4** [comment]
Sorry @eugeneglova it's been so long now, I can't recall exactly what I did to work around this issue.

I do know that I'm not using code that tries to clear the cache anymore. I think I changed approaches because a newer version of mocha introduced some changes that made it impossible for me to re-run the tests from within the browser. It's not ideal, but for now I just re-run the tests by refreshing the browser page...

**Comment by eugeneglova** [comment]
@jharris4 no worries, I've fixed my issue, I've used webpack common file with `async: true` options so load it asynchronous every test suite so it rewrite that window.webpackJsonp every time so cache cleared.

**Comment by kopax** [comment]
I am trying to achieve something similar without success  : 

```jsx
import { ENV } from '../index';

describe('environments configuration', () => {
  describe('default environment', () => {
    let config;
    beforeAll(() => {
      delete process.env.NODE_ENV;
      process.env.NODE_ENV = ENV.DEFAULT;
      config = require('../index');

    });

    it('should be default login url', () => {
      expect(config.url.login).toEqual('http://localhost:8080/login');
    });

    it('should store token in local storage', () => {
      expect(config.STORAGE.TOKEN.type).toEqual('localStorage');
    });
  });

  describe('development environment', () => {
    let devConfig;
    beforeAll(() => {
      delete process.env.NODE_ENV;
      process.env.NODE_ENV = ENV.DEVELOPMENT;
      console.log(process.env.NODE_ENV);
      console.log(require);
      delete require.cache[require.resolve('../index')] // doesn't do anything, require.cache is an empty object

      devConfig = require('../index');
      console.log(process.env.NODE_ENV, devConfig.url.login);
      expect(true).toBe(false);
    });

    it.only('should be development login url', () => {
      expect(devConfig.url.login).toEqual('https://dev.doma.com/login');
    });

    it('should store token in local storage', () => {
      expect(devConfig.STORAGE.TOKEN.type).toEqual('localStorage');
    });
  });

  describe('production environment', () => {
    let config;
    beforeAll(() => {
      delete process.env.NODE_ENV;
      process.env.NODE_ENV = ENV.PRODUCTION;
      config = require('../index');
    });

    it('should be production login url', () => {
      expect(config.url.login).toEqual('https://doma.com/login');
    });

    it('should store token in session storage', () => {
      expect(config.STORAGE.TOKEN.type).toEqual('sessionStorage');
    });
  });
});
```

It always keep the value of the first `require('../index')` call. I am using webpack `2.2.1`. Any Idea how I could achieve this ?

**Comment by fagerbua** [comment]
@kopax Could it be that you're using Jest? Deleting `require.cache` doesn't work work for me in that case, but calling `jest.resetModules()` does the trick. See https://facebook.github.io/jest/blog/2016/09/01/jest-15.html#module-registry-persistence

**Comment by broofa** [comment]
'Hope this isn't inappropriate.... I just published [resnap](https://www.npmjs.com/package/resnap), a standalone tiny module for capturing and restoring require() cache state.  The README has a 2-line example of how to reset module state in mocha tests.  tl;dr:
```
const resetCache = require('resnap')();  // Capture state here

describe(..., function() {
  beforeEach(resetCache);  // Restore captured state before each test
```

**Comment by gabsprates** [comment]
> 
> 
> @kopax Could it be that you're using Jest? Deleting `require.cache` doesn't work work for me in that case, but calling `jest.resetModules()` does the trick. See https://facebook.github.io/jest/blog/2016/09/01/jest-15.html#module-registry-persistence

Thanks to this comment I found another good option: [jest.isolateModules(fn)](https://jestjs.io/docs/en/jest-object#jestisolatemodulesfn)

It runs the module inside a kind of sandbox.
