### ISSUE TITLE
I want to pack a node project into single js file

### ISSUE THREAD

**Issue by fuguohong** [webpack/webpack#8941]
in `webpack.config.js` ， i set `target: 'node` and run webpack. I get a single js file，but when i require the file , it export nothing . I export some thing in the origin entry file.

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by sokra** [comment]
`output.libraryTarget`.

But you may also look at https://github.com/zeit/ncc which is webpack preconfigured for this use case.

**Comment by fuguohong** [comment]
Im sorry for deleting the template. and thank you, Iv solved the problem
