### ISSUE TITLE
FunctionModuleTemplatePlugin performance problem with replace

### ISSUE THREAD

**Issue by maksimr** [webpack/webpack#8949]
We have a problem with performance when enabling source-maps (cheap-module-eval-source-map) in our project. After some investigation I found an issue with `replace` function inside `FunctionModuleTemplatePlugin`. `replace` took too much time even when the string (req) is small.

```bash
webpack@3.12.0
webpack-dev-server@2.11.3
node@v10.15.0
npm@6.4.1
darwin 18.2.0 MacOs Mojave (10.14.3) 2.3GHz i5/ 8GB
``` 

https://github.com/webpack/webpack/blob/master/lib/FunctionModuleTemplatePlugin.js#L44-L46

```js
	source.add("/*!****" + req.replace(/./g, "*") + "****!*\\\n");
	source.add("  !*** " + req.replace(/\*\//g, "*_/") + " ***!\n");
	source.add("  \\****" + req.replace(/./g, "*") + "****/\n");
```

First simple solution just remove duplications `req.replace(/./g, "*")`.
Second I replaced `replace` with Array

```js
        const x = Array(req.length).fill("*").join('');
        const y = Array(req.length).fill(null).map((_, i) => (i > 0 && req[i - 1] === '*' && req[i] === '/') ? '_/' : req[i]).join('');
        source.add("/*!****" + x + "****!*\\\n");
        source.add("  !*** " + y + " ***!\n");
        source.add("  \\****" + x + "****/\n");

```

After this fixes rebuild time decreased `3-4` times.
Performance of `FunctionModuleTemplatePlugin` increased in ~15 times (by profile)

I have created a small test file which reproduces this problem
https://gist.github.com/maksimr/cff8cb1ebda05d530071c9c78cd0d82e

![image1553370705714](https://user-images.githubusercontent.com/616193/54871116-82800b80-4dc0-11e9-8714-e1ce09df60c6.png)
![image1553370308610 (1)](https://user-images.githubusercontent.com/616193/54871125-ad6a5f80-4dc0-11e9-851c-044706d05dd7.png)

[CPU profile for replace](https://gist.githubusercontent.com/maksimr/cff8cb1ebda05d530071c9c78cd0d82e/raw/c38c39206655d61716181d72df8c5777b7dec729/CPU-20190323T223837.cpuprofile)

[CPU profile for Array](https://gist.githubusercontent.com/maksimr/cff8cb1ebda05d530071c9c78cd0d82e/raw/c38c39206655d61716181d72df8c5777b7dec729/CPU-patched.cpuprofile)

All CPU profiles I have added to gist
https://gist.github.com/maksimr/cff8cb1ebda05d530071c9c78cd0d82e

Thanks

**Comment by sokra** [comment]
On the `next` branch the code has changed to this:

https://github.com/webpack/webpack/blob/14d6472444e7b67a433be8265c1d1198bff035ec/lib/FunctionModuleTemplatePlugin.js#L81-L85

**Comment by maksimr** [comment]
@sokra Is it possible to port this fix for version 3.x?

**Comment by sokra** [comment]
yes, send a PR.

**Comment by maksimr** [comment]
@sokra I have created [PR](https://github.com/webpack/webpack/pull/8953) for webpack@3.x.
Could you provide estimation when it would be merged and published? (If it's possible)

Thanks!

@noelebrun provided [PR](https://github.com/webpack/webpack/pull/8950) to master but I don't know does it make sense for master because you already fixed it in `next`

**Comment by noelebrun** [comment]
I didn't catch the 3.x an not the 4.x, my bad. Can we still merge some patches in `webpack-3` branch?

**Comment by sokra** [comment]
Oh sorry. I didn't see that you want to backport to v3. No, webpack 3 is outdated and won't get such fixes. A backport to v4 (master) is fine.

**Comment by sokra** [comment]
If you have a problem with performance, your should start by upgrading to webpack 4, which has a lot of performance improvements.
