### ISSUE TITLE
resolve.alias no longer working on 1.7.3

### ISSUE THREAD

**Issue by elayman** [webpack/webpack#895]
I was using 1.6.0 with resolve.alias configuration and now it no longer works with v1.7.3.

My config looks like this:

webpack: {
...
resolve: {
    alias: {
        rx: 'rx/index'
    }
}
...
}

and I get the following error: Module not found: Error: Cannot resolve module 'rx/index' in ...

I think this could be something to do with the alias referencing the index.js file, but it used to work in 1.6.0.

**Comment by elayman** [comment]
Actually the problem is alias does not override the following in package.json in rx
{
...
"browser": {
"index.js": "dist/rx.all.js"
}
...
}

I would expect the alias to override this

**Comment by elayman** [comment]
Figured it out:

resolve: {
moduleAlias: { 
browser: {
rx: false
}
}
},
alias: {
rx: 'rx/index'
}
}

**Comment by LFDM** [comment]
Hm, I am also having issues here - something like
```
resolve: {
  alias: {
    utils: path.resolve(__dirname, './path/to/utils')
  }
}
```

which perfectly worked fine for me in older versions, doesn't work anymore.
