### ISSUE TITLE
Possible bug with tree shaking between packages

### ISSUE THREAD

**Issue by Apidcloud** [webpack/webpack#8951]
# Bug report

I have also posted this issue on stackoverflow, because I don't know for sure if it's a bug or the expected behaviour: https://stackoverflow.com/questions/55320774/webpack-tree-shaking-not-working-between-packages

**What is the current behavior?**
Tree shaking doesn't seem to be working between packages. But it works for an individual package. 

Before going further, I have created a minimum repro that I will explain throughout this issue: https://github.com/Apidcloud/tree-shaking-webpack

**If the current behavior is a bug, please provide the steps to reproduce.**

For simplicity sake, the example above just uses webpack. **Babel is not used**.
Also, despite not using real dependencies between the packages in the above example, the behaviour is exactly the same. I tried that (including its own `webpack.config.js` and `package.json`) and the behaviour is the same.

The above example has **two packages**, both with their respective bundle:

- `core` - exports 2 functions, `cube` and `unusedFn`
- `consumer` - imports `cube` from `core` and exports its own function, `consumerFn`

## Core Package - **tree shaking works for this one**

![image](https://user-images.githubusercontent.com/3720818/54875622-fd98f000-4dc7-11e9-99f9-de45116724c7.png)

Note that `square` function is not exported in the `index.js` file. It's a way to know that tree shaking is indeed working within `core` at least, as it's not included in the final bundle (which is correct).

## Consumer Package - **doesn't seem to work for this one**

![image](https://user-images.githubusercontent.com/3720818/54875631-3638c980-4dc8-11e9-8689-8bc4360df406.png)

As you can see, only `cube` is being imported from `core`. It then exports its own function (`consumerFn`) consuming `cube`.

## Webpack config
```javascript
const path = require('path');

module.exports = {
  mode: 'production',
  entry: {
    core: './src/index.js',
    consumer: './consumer/index.js'
  },
  output: {
    filename: '[name].js',
    path: path.resolve(__dirname, 'dist'),
    // for simplicity sake I removed the UMD specifics here.
    // the problem is the same, with or without it.
  },
  optimization: {
    usedExports: true,
    sideEffects: true
  },
  stats: {
    // Examine all modules
    maxModules: Infinity,
    // Display bailout reasons
    optimizationBailout: true
  }
};
```

I also have `"sideEffects": false` in the `package.json`. Webpack is also running in `production` mode, and `ES6 modules` are being used despite the ModuleConcatenation plugin's warnings (which in essence might have a point because the bundle itself doesn't?)

**What is the expected behavior?**

The problem is that the `consumer` bundle is including everything from the `core` bundle. That is, it's **including** `unusedFn` **when it shouldn't** (?), resulting in a bigger bundle.

Ultimately, the goal is to do the same in a monorepo with multiple packages. There's no point on having them if each package is bundling the everything from the others. The goal is to bundle only what's necessary for each package.

Using `optimizationBailout` I can see that **ModuleConcatenation** plugin is issuing **some warning messages**. I also used `--verbose` flag:
![image](https://user-images.githubusercontent.com/3720818/54875667-d262d080-4dc8-11e9-8b7e-16567e33ca23.png)

And here are the sizes of the bundles:
![image](https://user-images.githubusercontent.com/3720818/54875708-66349c80-4dc9-11e9-8fc6-d285b06ed793.png)

As you can see, `consumer` almost doubles `core`, because it's essentially including unused functions within. I have been on this for couple days, but can't tell whether this is a bug or not.

**Other relevant information:**
webpack version: 4.29.6
webpack-cli version: 3.3.0
Node.js version: 8.15.0

**Comment by sokra** [comment]
Because you added `core` as entrypoint all exports are flagged as used.

**Comment by Apidcloud** [comment]
But the point is to have all packages in their own bundle, sharing only what’s needed. Or am I missing something?

**Comment by StJohn3D** [comment]
Same thing, I have a npm library with an index file containing a bunch of `export * from './foo'` statements.
My consuming app has to explicitly use `import { foo } from 'my-package/lib/foo'` because if I do `import { foo } from 'my-package'` it includes everything & forces me to have unused peer-dependencies installed.

I wish tree-shaking worked on my node-modules too. I even have `"sideEffects": false,` in node_modules/my-package/package.json

**Comment by swcarlosrj** [comment]
@Apidcloud thanks for such detailed issue, we are also dealing with this & I was wondering if you've found a solution besides importing explicitly functions as @StJohn3D really well explained. @sokra are there news here? maybe webpack 5 will support it?

**Comment by Apidcloud** [comment]
I couldn’t really find a solution for webpack at the time. I experimented with rollup and the code splitting was done by default as far as I can remember. Maybe you can accomplish the same here with code chunks.

On 21. Apr 2020, at 18:04, Carlos Rufo <notifications@github.com> wrote:

﻿

@Apidcloud<https://github.com/Apidcloud> thanks for such detailed issue, we are also dealing with this & I was wondering if you've found a solution besides importing explicitly functions as @StJohn3D<https://github.com/StJohn3D> really well explained. @sokra<https://github.com/sokra> are there news here? maybe webpack 5 will support it?

**Comment by sokra** [comment]
My recommendation here is to not bundle libraries. Publish them as EcmaScript modules in individual files.

Some optimizations depend on the module boundaries (e. g. side-effects flag in package.json).
Some optimizations depend on modules being EcmaScript modules (e. g. unused exports elimination).

So I recommend to keep the module structure in your published library, at least for consuming as ESM. You may provide an additional CommonJs version of your library for node.js usage, that can be bundled, webpack doesn't care as it doesn't use it if a ESM version is available. Use `main` and `module` field in package.json to provide both.

You could still do preprocessing steps with raw typescript or babel. 

You could also use rollup with `preserveModules: true` to keep module structure to do some optimizations like tree shaking. Note as it's unknown which exports of your library will be used, it can only tree-shake things that ain't used at all.

In my opinion the best way to structure an library to be optimize-able is to use an `index.js` as main entry which reexports each export with `export { something } from "./something"`. Each export should be placed in a separate file and have no side-effect. This allows to use `sideEffects: false` in package.json, which allows to skip complete modules and do not depend on static analysis to verify that these modules are really side-effect-free.

**Comment by ghbakhtiari** [comment]
@sokra 

I tried to implement almost all of your suggestions and there is still no luck in removing unused parts of my dependency package from my other project.

Inside the package, which uses Rollup, I've bundled separated versions for `es` and `cjs` (specified using `main` and `module` options in `package.json`), added `preserveModules: true` for the `es` version, and added `"sideEffects": false` in the `package.json`. Also the structure is pretty simple using an `index.js` which re-exports all of the components. (here there are a couple of exported components which will not be used in the other project, and I was expecting them to not exist in the final bundle!)

And inside the other project, which uses Webpack, the configs are pretty much common. Using `mode: 'production'`, babel (with `preset-env`'s `modules` set to false), `terser-webpack-plugin`, etc.

But the unused components form the dependency package are still present in the consumer's final bundle.

Are there some points that I've missed here?

**Comment by sokra** [comment]
Difficult to help you with the code. Maybe you could create a repro?

**Comment by sibelius** [comment]
Here is a github reproduction example https://github.com/sibelius/relay-workshop/blob/master/packages/ui/src/index.tsx ( a bit more complex)

we have our design system exporting all components in the index.tsx

```jsx
// mini design system
export { Card } from './Card';
export { CardActions } from './CardActions';
export { Content } from './Content';
export { TextArea } from './TextArea';
export { Button } from './Button';
export { getTheme, theme } from './theme';
export { default as BackButton } from './BackButton';

// form fields
export { default as TextField, TextFieldMaterial } from './TextField';
```

If my main app only consumes the `Button` it will get bundled all components of the UI design system package

here is the package.json https://github.com/sibelius/relay-workshop/blob/master/packages/ui/package.json#L10

does it need to have `module` and other flags?

the webpack config is here https://github.com/sibelius/relay-workshop/blob/master/packages/webpack/src/webpackConfig.js

**Comment by vankop** [comment]
Should work with `webpack@next`. Feel free to report new issue with reproducible repo.
