### ISSUE TITLE
Can't find options with ident 'ref--*-*' when Rule.use is a function

### ISSUE THREAD

**Issue by melan0802** [webpack/webpack#8952]
# Bug report

**What is the current behavior?**

When Rule.use is a function that return UseEntry **With Options**, the compilation failed with error "Can't find options with ident 'ref--4-1'"

**If the current behavior is a bug, please provide the steps to reproduce.**

`webpack.config.js`
```
const path = require('path')
module.exports = {
  mode: 'production',
  entry: './index.js',
  output: {
    path: path.resolve(__dirname, './dist')
  },
  module: {
    rules: [
      {
        test: /\.css/,
        use (info) {
          return [
            'style-loader',
            {
              loader: 'css-loader',
              options: {
                url: true
              }
            }
          ]
        }
      }
    ]
  }
}
```

**What is the expected behavior?**

behavior like it is a UseEntry Array

**Other relevant information:**
webpack version:  4.29.6
Node.js version: 10.15.3
Operating System: Windows 10

Check out the source and pretty sure it's a bug in RuleSet.js , the options references as RuleSet.references is assigned only when rule.use is an array. Should I make an PR?

**Comment by evilebottnawi** [comment]
Why do you use `function`? Feel free to send a PR

**Comment by melan0802** [comment]
@evilebottnawi Above `webpack.config.js` is just as an example. In my project I want to add a loader when issuer match a specific file, maybe `function` isn't designed for this?  But bug is still there as long as using `function`.

**Comment by 7iomka** [comment]
it is not fixed in latest ver!
Why?(

**Comment by BlueSky1997AL** [comment]
Is there any progress about this issue? Still not functional in latest version (4.39.2).

**Comment by aKzenT** [comment]
If I understand the PR correctly, it was merged to the next (v5) branch. Any chance to get this backported for the next minor 4.x release? I also need to define Rule.use as a function and getting this problem.

**Comment by jedmonsanto** [comment]
No need for it to be function. Please see below:
![image](https://user-images.githubusercontent.com/23548643/68766896-b31bfa80-065a-11ea-846d-3df3a47cb5f5.png)

**Comment by steventhan** [comment]
@jedmonsanto not relevant to the question I'm afraid

**Comment by ja0n** [comment]
Still not functional in the latest version (4.41.2)

**Comment by evilebottnawi** [comment]
You can use `ident: 'name-of-ident' to avoid that problem`

**Comment by underflow00** [comment]
> You can use `ident: 'name-of-ident'` to avoid that problem

Tried this. Issue still persists. Is there a workaround to this?

**Comment by evilebottnawi** [comment]
@underflow00 can you create reproducible test repo

**Comment by underflow00** [comment]
> @underflow00 can you create reproducible test repo?

Isn't the first post already it? I just added `ident: '...'` into the options and that didn't do anything.

**Comment by CressZZ** [comment]
...cant't we Rule.use function with options until releasing 5.x version ?

**Comment by evilebottnawi** [comment]
@underflow00 @CressZZ please create reproducible test repo

**Comment by evilebottnawi** [comment]
bump

**Comment by sokra** [comment]
Webpack 5 has a better error message for this case. It also fixes some problems here. Anyway you need an `ident` When using a function. `ident` should be next to options not inside of the options. `{ loader, options, ident }`

**Comment by evilebottnawi** [comment]
@sokra so we throw an error when ident doesn't exists?

**Comment by sokra** [comment]
Yes. We also have better names for the automatic indents in webpack 5.

**Comment by evilebottnawi** [comment]
If somebody faced with the issue again, please open a new issue with reproducible test repo, thanks
