### ISSUE TITLE
Add the ability for loaders to be resource providers

### ISSUE THREAD

**Issue by erickskrauch** [webpack/webpack#8957]
## Feature request

**What is the expected behavior?**

In the current implementation, loaders are not called unless a link to an existing resource is passed.

**What is motivation or use case for adding/changing the behavior?**

At the moment I am trying to solve the problem of generating images with text for each locale in my project using the library `text2png`. I want to get exactly the same behavior as if I'm loading a resource with an image, but getting it from the loader:

```js
const textStringUrl = require(`file-loader?name=hello-world.${locale}.png!text2png-loader?text=${textForCurrentLocale}`);
```

Implementation of this feature opens the way, for example, to create a dummy image loader:

```js
const dummyUrl = require(`file-loader!dummy-loader?320x150`);
```

**How should this be implemented in your opinion?**

In theory, this shouldn't be complicated: you should allow the loaders to run even without a given resource reference. The `content` argument will be empty. However, it's difficult for me to propose a solution for dynamic arguments, as in my task, because you will no longer have a reason to make a list of candidates (based on the file system) when forming the context.

**Are you willing to work on this yourself?**

I'll do my best, but I don't know where to start. I feel that the solution must be obviously simple or critical because of the complexity of the context described above.

**Comment by sokra** [comment]
You can also use loaders without resource and you can name it, which appies the loaders from configuration:

``` js
require("./hello-world.png!=!text2png-loader?text=hello world!");
```

You can't use runtime arguments inside of loaders and loaders query.

**Comment by erickskrauch** [comment]
@sokra, thanks, that solves my problem. I don't know, does this mentioned in documentation or not, but it would be nice to make that knowledge more accessible.

**Comment by erickskrauch** [comment]
@sokra, I have a problem with my loader and its combination with the `file-loader`. As you have noted, the file can be named and will be passed on to the loaders according to the configuration. My `text2png-loader` implementation is below:

```js
const { getOptions } = require('loader-utils');
const text2png = require('text2png');

module.exports = function() {
    this.cacheable && this.cacheable();

    const { text, ...options } = getOptions(this);
    if (!text) {
        this.emitError('The text param is required');
        return '';
    }

    return text2png(text, options);
};
```

And I have the next configuration for `png` files:

```js
{
    test: /\.(png|gif|jpg|svg)$/,
    loader: 'file-loader',
    query: {
        name: 'assets/[name]-[folder].[ext]?[hash]',
    },
},
```

Import statement is:

```js
import test from './hello.png!=!text2png-loader?text=Hello!';
```

Everything seems correct, but I'm getting the error:

```
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
    at Function.from (buffer.js:204:11)
    at writeOut (/Users/erickskrauch/www/email-renderer/node_modules/webpack/lib/Compiler.js:410:26)
    at Immediate.<anonymous> (/Users/erickskrauch/www/email-renderer/node_modules/memory-fs/lib/MemoryFileSystem.js:288:4)
    at processImmediate (timers.js:632:19)
```

Which happens after `file-loader` tries to load the generated file and didn't receive `content` value. Is there any way to workaround this?

**Comment by evilebottnawi** [comment]
Looks you loader run twice, add `!!` before to avoid this, if it is not help please create minimum reproducible test repo, thanks!

**Comment by erickskrauch** [comment]
@evilebottnawi,
With `./hello.png!=!!file-loader!text2png-loader?text=Hello!` I was finally able to build the module successfully. But the link turns out to be `/[hash].bin`, not a named output value. In general, this is still not what I expect. I have created a repository with a minimal replayable configuration.

https://github.com/erickskrauch/named-webpack-import-example.

**Comment by evilebottnawi** [comment]
Try to use `!!./hello-world.png!=!text2png-loader?text=hello world!`

**Comment by erickskrauch** [comment]
I [sent this version to my example repository](https://github.com/erickskrauch/named-webpack-import-example/commit/168a4fa898752f89accdd775ab7badd2ccaf2e4b).

I now get the following error for both formats:

```
ERROR in ./src/index.js
Module not found: Error: Can't resolve './test1.png' in '/Users/erickskrauch/www/named-webpack-import-example/src'
 @ ./src/index.js 1:14-51
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src

ERROR in ./src/index.js
Module not found: Error: Can't resolve './test2.png' in '/Users/erickskrauch/www/named-webpack-import-example/src'
 @ ./src/index.js 2:14-50
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src
```

**Comment by evilebottnawi** [comment]
Use:
```
const test1 = require("!!file-loader!my-loader?text=hello world");
```

**Comment by erickskrauch** [comment]
@evilebottnawi, it's not working as I expected. It just copies loader implementation as `.js` file, not the contents it's generating.

**Comment by evilebottnawi** [comment]
What you expected? What is weird you try to do?

**Comment by erickskrauch** [comment]
Please, take a look at the [sample repository](https://github.com/erickskrauch/named-webpack-import-example/blob/168a4fa898752f89accdd775ab7badd2ccaf2e4b/src/index.js#L5-L9).

**Comment by evilebottnawi** [comment]
Why don't add image url to query param?

**Comment by erickskrauch** [comment]
Because it does not exist and generated via my loader. Please, read again head message with an explanation of the problem, that I'm trying to solve.
