### ISSUE TITLE
Disable development in-memory bundle loading

### ISSUE THREAD

**Issue by javahemans** [webpack/webpack#8958]
## Feature request

**What is the expected behavior?**
To be able to see the files in `/public` folder and serve file from `/public` for development purpose. 

**What is motivation or use case for adding/changing the behavior?**
Let's say I am using Webpack CRA2 and Cordova and I want to have one development folder for both Cordova and React. In Create React App 2 which uses Webpack 4 `/public` folder has no js code to use for cordova as well. It reads it from memory and Cordova does not. 

If webpack output the file in `/public` then it can be picked up by other processors and applications as well. 

I have been searching and surfing web but I couldn't find anything... ( I know if I didn't find anything that doesn't mean the feature does not exist) but if it is just close and point it out... cheers 

**How should this be implemented in your opinion?**
It would be nice to have a switch enable/disable - inMemory: true/false ....

**Are you willing to work on this yourself?**
yes

**Comment by sokra** [comment]
Use `webpack --watch` + static server instead of `webpack-dev-server`.

**Comment by evilebottnawi** [comment]
You can use `writeToFile: true` for `webpack-dev-server` and all assets will be written to server

**Comment by FVolral** [comment]
@evilebottnawi I think it is `writeToDisk: true`
