### ISSUE TITLE
 Cannot find module 'webpack' 

### ISSUE THREAD

**Issue by gnesher** [webpack/webpack#8959]
# Bug report

**What is the current behavior?**

When running latest webpack (4.29.6) via npm under git bash / command prompt (windows 10) I receive an error
```
Error: Cannot find module 'webpack'
```
Running the same repository under Ubuntu (under Windows 10) works fine.

**If the current behavior is a bug, please provide the steps to reproduce.**

Can be reproduced using the following repo https://github.com/gnesher/phaser-capacitor (bug was reported by a user, I can reproduce it on my machine). It's a repository for a real project but it's tiny and the webpack.config.js is very small / easy to read

To reproduce simply clone, run npm install and then try to run ``` npm run build ```

**What is the expected behavior?**

I should be able to run webpack via npm without installing it globally

**Other relevant information:**
webpack version:  4.29.6/4
Node.js version: 11.12
Operating System: Windows 10
Additional tools:

**Comment by evilebottnawi** [comment]
Can't reproduce, i think problem related to npm/yarn than webpack, please provide more information - npm or yarn, version of package manager, version of windows, thanks

**Comment by gnesher** [comment]
npm v6.7.0
yarn 1.12.1
windows 10 - 10.0.17763 Build 17763

**Comment by evilebottnawi** [comment]
@gnesher still can't reproduce, are you sure problem not related to your environment?

**Comment by gnesher** [comment]
If I run the same project through bash for windows (the Ubuntu shell) in the same folder it works fine so this is probably tied to something with Windows - but I'm not sure if this is just an odd edge case that Webpack isn't handling vs something broken with my Windows installation

**Comment by wLove-c** [comment]
macOS Mojave 10.14 
npm 6.5.0
node v9.1.0
webpack 4.34.0
webpack-cli 3.3.4
![image](https://user-images.githubusercontent.com/24515513/59412117-55eff480-8def-11e9-9d0b-34a68c92e6b7.png)

**Comment by DanielRuf** [comment]
> but I use npm install -g webpack@3.6.0

Running this is not recommended. webpack should be installed locally, not globally. This should be called as part of a npm script which uses `node_modules/.bin/webpack` then.

**Comment by wLove-c** [comment]
> > but I use npm install -g webpack@3.6.0
> 
> Running this is not recommended. webpack should be installed locally, not globally. This should be called as part of a npm script which uses `node_modules/.bin/webpack` then.

ok！thanks~
