### ISSUE TITLE
`webpackMode` expected 'lazy', 'eager' or 'weak', but received: lazy-once

### ISSUE THREAD

**Issue by light0x00** [webpack/webpack#8961]
lib version:  
```
   "webpack": "^4.29.6",
    "webpack-cli": "^3.3.0"
```
code: 
```
import (/* webpackChunkName: "asyncA",webpackMode:"lazy-once" */'../common/async1')
```

error:
```
`webpackMode` expected 'lazy', 'eager' or 'weak', but received: lazy-once
```

when i set "lazy-once" for "webpackMode", the error will be reproduced
but I saw in the documentation that it was available
👉https://www.webpackjs.com/api/module-methods/

**Comment by evilebottnawi** [comment]
@light0x00 please use issue template

**Comment by light0x00** [comment]
> @light0x00 please use issue template

all right,i'm sorry,i have been relaunched a issue😄
