### ISSUE TITLE
Programatically transpile code from string inside a loader

### ISSUE THREAD

**Issue by LukasBombach** [webpack/webpack#8962]
## Feature request

**What is the expected behavior?**

I think it would be great to have an API for Webpack loaders that can take any `string` of code and transpile it according to the current Webpack config.

**What is motivation or use case for adding/changing the behavior?**

I am writing a Webpack loader that transpiles `.vue` files to React components:

https://github.com/LukasBombach/single-file-components

A `.vue` file can consist of a `<template>` `<script>` and `<style>` tag. As part of my implementation I want to imperatively load the `<script>` part and have it transpiled by Webpack for further processing. So if I have this `.vue` file:

```vue
    <template>
      <div>hello world</div>
    </template>
    
    <script>
    import something from "something";
    
    export default {
      data() {
        return {
          baz: "baz"
        };
      }
    };
    </script>
```

I basically want to do this (dummy code for the purpose of explanation):

**myLoader.js**

```js
    function myLoader(source) {
      // should return everything between <script> and </script> as a string
      const scriptCode = getCodeInsideScriptTags(source); 
    
      // transpiledJsCode should be es5 code that has been transpiled by Webpack
      const transpiledJsCode = this.theWebpackFunctionIAmLookingFor(scriptCode);

      // Now I can process the transpiledJsCode 
    }
```

**How should this be implemented in your opinion?**

In my opinion it could be part of the Loader Interface, like this:

```js
interface moduleDefinition {
  request: string;
  source: string;
  // ...
}

this.transpileModule(module: moduleDefinition, callback: function(err, source, sourceMap, module))
```

**Are you willing to work on this yourself?**
yes indeed

**Comment by evilebottnawi** [comment]
What do you mean "transpile code"? It is do babel loader. You can use babel inside you loader

**Comment by LukasBombach** [comment]
I'm sorry if that is already possible, but can I transpile a piece of code according to the Webpack setup I am currently in? Because if I run Babel programatically with _my_ settings, what if that differs from the Webpack setup my loader is currently used in? With vue you can add a `lang` property to determine which language a `script` (or `template` or `style`) block is written in. I would need to have my own setup for all possible cases and my setup could differ from the one the user is using.
