### ISSUE TITLE
`webpackMode` expected 'lazy', 'eager' or 'weak', but received: lazy-once

### ISSUE THREAD

**Issue by light0x00** [webpack/webpack#8963]
# Bug report
`webpackMode` expected 'lazy', 'eager' or 'weak', but received: lazy-once

**What is the current behavior?**
set "lazy-once" for "webpackMode" when use dynamic import

**If the current behavior is a bug, please provide the steps to reproduce.**
when i set "lazy-once" for "webpackMode", the error will be reproduced

there is repo than can reproduced
👉 https://github.com/light0x00/webpack-temp.git

**What is the expected behavior?**
 I saw "lazy-once" in the documentation that it was available
👉https://www.webpackjs.com/api/module-methods/

**Other relevant information:**
webpack version:  ^4.29.6
Node.js version: v8.12.0
Operating System: osx 10.14.3
Additional tools: 1

**Comment by sokra** [comment]
https://webpack.js.org/api/module-methods/#magic-comments

> "lazy-once": Generates a single lazy-loadable chunk that can satisfy all calls to import(). The chunk will be fetched on the first call to import(), and subsequent calls to import() will use the same network response. **Note that this only makes sense in the case of a partially dynamic statement, e.g. ``import(`./locales/${language}.json`)``, where there are multiple module paths that could potentially be requested.**
