### ISSUE TITLE
Server-side HMR not updating in node v11.11.0+

### ISSUE THREAD

**Issue by nikparo** [webpack/webpack#8970]
# Bug report

**What is the current behavior?**
Hot module reloading does not work in node v11.11.0+. This may be a node issue, but I'm posting it here first as I'm not familiar with webpack internals.

**If the current behavior is a bug, please provide the steps to reproduce.**
As of node v11.11.0 HMR no longer works for me, when updating server (node) code. It still works for client side code. I've tested using both `webpack/hot-node-example` (old webpack) and `create-razzle-app`. (new webpack). Same issue with both of them.

- `git clone https://github.com/webpack/hot-node-example.git`
- `nvm install 11.11.0` (npm v6.7.0)
- `npm run hot` & `npm run start`
-> Webpack bundles the script (`bundle.js`), but it is not loaded through `module.hot.accept(...)`

A few day older node version works as expected:

- `nvm install 11.10.1` (npm v6.7.0)
- `npm run hot` & `npm run start`
-> Webpack bundles and loads the new file

**What is the expected behavior?**
`module.hot.accept` should fire in node v11.11.0+ as well.

**Other relevant information:**
webpack version:  `1.15.0` (webpack/hot-node-example) `4.29.6` (create-razzle-app)
Node.js version: `v11.11.0` (earlier versions work)
Operating System: Arch Linux
Additional tools: `nvm`

**Comment by nikparo** [comment]
I can confirm that the same issue appeared on my Macbook when I upgraded from node `v11.10.0` to `v11.12.0`

**Comment by evilebottnawi** [comment]
@nikparo you use `webpack@1`, he is deprecated, please update you deps

**Comment by nikparo** [comment]
I have the same exact issue with `create-razzle-app` that uses `webpack  4.29.6`, as mentioned above.

**Comment by evilebottnawi** [comment]
@nikparo please create real reproducible test repo

**Comment by nikparo** [comment]
Unfortunately I don't know webpack well enough to quickly create a simple test repo, but it seems someone beat me to it anyway - [Server-side hot reload not working for Node 11.x #9012](https://github.com/webpack/webpack/issues/9012)
