### ISSUE TITLE
contenthash is inconsistent while build on multi machine

### ISSUE THREAD

**Issue by onlybye** [webpack/webpack#8972]
# Bug report

**What is the current behavior?**

we have deployed our webapp via two servers , index.html and static files are build and deployed seperately.when we apply the contenthash of webpack4.29.6, we found that the content hash of vendors and app are different when builded on multi machines, and some other cachegroup is same,such as angular. we have apply the  HashedModuleIdsPlugin and NamedChunksPlugin, and the content is defenitily identical。It's really confuse us.

**If the current behavior is a bug, please provide the steps to reproduce.**

webpack cacheGroups:
        optimization: {
            runtimeChunk: 'single',
            splitChunks: {
                cacheGroups: {
                    vendor: {
                        name: "vendor",
                        test: /[\\/]node_modules[\\/]/,
                        chunks: "all",
                        priority: 10
                    },
                    angular: {
                        name: "angular",
                        test: /[\\/]node_modules[\\/]angular/,
                        chunks: "all",
                        priority: 11
                    },

                }
            }

**What is the expected behavior?**

when build on multi machines, the contenthash can keep identical.

**Other relevant information:**
webpack version:  4.29.0
Node.js version: 11.12.0
Operating System: windows or linux
Additional tools:

@sokra

**Comment by evilebottnawi** [comment]
@onlybye please create minimum reproducible test repo

**Comment by onlybye** [comment]
> @onlybye please create minimum reproducible test repo

@evilebottnawi https://github.com/onlybye/test_hash

this is the test repo, run : npm install & npm run build ,on multiple server, the contenthash of vendor is different. We have found it's due to jquery , if set jquery as external module, contentHash is identical

**Comment by evilebottnawi** [comment]
@onlybye can you provide version/distrib of `windows` and `linux`

**Comment by evilebottnawi** [comment]
bump

**Comment by HydraOrc** [comment]
Same issue here

**Comment by evilebottnawi** [comment]
@HydraOrc do you have problem too? Can you create reproducible test repo? Want to ensure we fix all problems

**Comment by HydraOrc** [comment]
@evilebottnawi Well, I am not sure how can i create a reproducable repo, since the issue is between different machines, but i can share my webpack config. I am not sure what exactly is causing the problem. `filename: '[name].[contenthash:5].js'` and `chunkFilename: '[name].[contenthash:5].chunk.js'` have inconsistent names, but `extract-css-chunks-webpack-plugin` provides consistent names.

```
const path = require('path');
const ExtractCssChunks = require('extract-css-chunks-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const OptimizeCSSAssetsPlugin = require('optimize-css-assets-webpack-plugin');
const TerserJSPlugin = require('terser-webpack-plugin');
const webpackModule = require('./webpack.module');

module.exports = {
  target: 'web',

  mode: 'production',

  // In production, we skip all hot-reloading stuff
  entry: [
    'react', // Include this to enforce order
    'react-dom', // Include this to enforce order
    path.join(process.cwd(), 'client/index.js'),
  ],

  module: webpackModule,

  resolve: {
    extensions: ['.js'],
  },

  // Utilize long-term caching by adding content hashes (not compilation hashes) to compiled assets
  output: {
    filename: '[name].[contenthash:5].js',
    chunkFilename: '[name].[contenthash:5].chunk.js',
    publicPath: '/',
    path: path.resolve(process.cwd(), 'app'),
  },

  plugins: [
    // Minify and optimize the index.html
    new HtmlWebpackPlugin({
      template: 'client/index.html',
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeRedundantAttributes: true,
        useShortDoctype: true,
        removeEmptyAttributes: true,
        removeStyleLinkTypeAttributes: true,
        keepClosingSlash: true,
        minifyJS: true,
        minifyCSS: true,
        minifyURLs: true,
      },
      inject: true,
    }),
    new ExtractCssChunks({
      filename: '[name].[contenthash:5].css',
      chunkFilename: '[id].[contenthash:5].css',
    }),
  ],

  optimization: {
    minimizer: [new TerserJSPlugin({}), new OptimizeCSSAssetsPlugin({})],
    splitChunks: {
      cacheGroups: {
        styles: {
          name: 'styles',
          test: /\.css$/,
          chunks: 'all',
          enforce: true,
        },
      },
      chunks: 'async',
      minChunks: 2,
    },
  },

  performance: {
    assetFilter: (assetFilename) => !/(\.map$)|(^(main\.|favicon\.))/.test(assetFilename),
  },
};

```

**Comment by evilebottnawi** [comment]
Can you try to remove `ExtractCssChunks` and check again?

**Comment by bschmeck** [comment]
I have started running into this problem as well.  What I've learned is that although a chunk sorts its modules before computing the contenthash, a module's hash is constructed from its dependencies and those are not sorted.  I have not yet figured out why, but it appears our webservers occasionally traverse the graph in different orders, resulting in different hash values for the same module.

Would it be reasonable to sort dependencies, blocks and variables in the `updateHash` method of `DependenciesBlock`?  https://github.com/webpack/webpack/blob/v4.41.5/lib/DependenciesBlock.js#L79-L83

(We are running Rails and using Webpacker, which ties us to `^4.41.2` of webpack.)

**Comment by kritik** [comment]
same issue with v4.43.0. It started to happen randomly 1 day on 1 file. After I reverted changes (file persisted the same) contenthash still was different on different servers. Moreover, however css content chunk was the same, it's contenthash was different
```
result.append(
    'MiniCssExtract',
    new MiniCssExtractPlugin({
      filename: 'css/[name]-[contenthash:8].css',
      chunkFilename: 'css/[name]-[contenthash:8].chunk.css'
    })
  )
```

**Comment by bschmeck** [comment]
We were finally able to narrow down the cause of our issue to the inclusion of `babel-plugin-recharts`.  Removing that package returned us to consistent fingerprints across all servers.

**Comment by rapritchard** [comment]
Also having this happen with our builds, a few bundles content hashes stay consistent whilst most change despite no content changing. We're not using` babel-plugin-recharts`. 

I believe it might be an issue with pathings being different on the machines building the bundles?

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack/webpack/issues/9520
