### ISSUE TITLE
The hash of babel-plugin-react-css-modules does not match the hash of css loader

### ISSUE THREAD

**Issue by IAMSBLOL** [webpack/webpack#8973]
This is my project

https://github.com/IAMSBLOL/react-cli

this is my config --

https://github.com/IAMSBLOL/react-cli/blob/master/config/webpack.config.js

The style is invalid because the hash value does not match, but the webpack is packaged and can be viewed in the browser resource.

I am getting a mentality explosion by this shit problem.

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/css-loader/issues/877

**Comment by IAMSBLOL** [comment]
@evilebottnawi 
Fucking hell, I thought it might be my css-loader problem, so updating to the last version will take effect.
This huge problem has finally been solved.

**Comment by evilebottnawi** [comment]
@IAMSBLOL first and last notice about words what are you use
