### ISSUE TITLE
Cannot find module 'reflect-metadata'

### ISSUE THREAD

**Issue by victorschinaider** [webpack/webpack#8974]
# Bug report

**What is the current behavior?**
When i generate a bundle, it gives me `Cannot find module 'reflect-metadata'`.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here is a repro steps repository. 
To ensure steps:
- execute `npm run tsc && npm run webpack`
- get file `/bundle.js` and move to other folder without `node_modules`, execute `node bundle.js` in moved file.

Then, will get:

```
Error: Cannot find module '/home/schinaider/bundle.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```
https://github.com/victorschinaider/webpack-test-bug

**What is the expected behavior?**

I expected that when i generated the `bundle` file, i could move file to other folder and execute `node bundle.js` and get what i wanted to execute.

**Other relevant information:**
webpack version:  4.29.6, 3.3.0 (cli)
Node.js version: v10.15.0
Operating System: Ubuntu
Additional tools:

**Comment by evilebottnawi** [comment]
Looks something wrong in https://github.com/liady/webpack-node-externals/, can you try to disable `webpack-node-externals` and check again

**Comment by victorschinaider** [comment]
@evilebottnawi , it works. But this example was only a part of "full code", if i do not use "nodeExternals", then i get "Cannot find module "fs"", and "Cannot find module "tls"", etc. Any suggestion?

**Comment by victorschinaider** [comment]
Thanks!
