### ISSUE TITLE
plugin process env limits env var runtime visibility

### ISSUE THREAD

**Issue by orwell1984** [webpack/webpack#8975]
I've defined couple of plugins as follows:
```
 'process.env': {
          FOO: "BAR",
          SOMEOTHERTHING: true
```
Now process.env of my application only has those 2 keys. I can't access all other envvars that are visible via `env` command.

What am I doing wrong?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by evilebottnawi** [comment]
Also i can't understand what you want to do. You can use `webpack.DefinePlugin` for this case
