### ISSUE TITLE
webpack chunk split while using alias

### ISSUE THREAD

**Issue by aseroj** [webpack/webpack#8978]
# Bug report

**What is the current behavior?**

We are using webpack alias and chunk split to get the chunks splitted by routes.
currently we are using @loadable/component and the pattern we are using alias upon is the following

~~~~
api: path.resolve(__dirname, "./src/api"),
actions: path.resolve(__dirname, "./src/actions"),
assets: path.resolve(__dirname, "./src/assets"),
components: path.resolve(__dirname, "./src/components"),
constants: path.resolve(__dirname, "./src/constants"),
containers: path.resolve(__dirname, "./src/containers"),
providers: path.resolve(__dirname, "./src/providers"),
reducers: path.resolve(__dirname, "./src/reducers"),
screens: path.resolve(__dirname, "./src/screens"),
selectors: path.resolve(__dirname, "./src/selectors"),
store: path.resolve(__dirname, "./src/store"),
types: path.resolve(__dirname, "./src/types"),
utils: path.resolve(__dirname, "./src/utils"),
middlewares: path.resolve(__dirname, "./src/middlewares"),
parsers: path.resolve(__dirname, "./src/parsers")
~~~~

please note that each root folder has its own `index.js` file for ease of use while importing. the largest route is around 2.4kb and the rest are fairly smaller ones.

here is the split chunk config inside webpack config

##### Webpack splitChunks

~~~~~
 splitChunks: {
    cacheGroups: {
      // Split vendor code to its own chunk(s)
      vendors: {
        test: /[\\/]node_modules[\\/]/i,
        chunks: "all"
      },
      // Split code common to all chunks to its own chunk
      commons: {
        name: "commons",
        chunks: "initial", 
        minChunks: 2 
      }
    }
  }
~~~~~

**What is the expected behavior?**

our route components are located under screens directory but when we remove `index.js` from the root screen directory (it's alias), split runs but the chunks are unexpectedly small and do not contain the inner components logic and the logic chunks are being generated automatically under commons name.

**Other relevant information:**
webpack version:  4.29.6 
Node.js version: 11.0.1
Operating System: Linux(Ubuntu)

**Comment by evilebottnawi** [comment]
Please provide minimum reproducible test repo
