### ISSUE TITLE
Add FileSystemInfo to Webpack4

### ISSUE THREAD

**Issue by jantimon** [webpack/webpack#8982]
## Feature request

As @sokra [announced](https://github.com/jantimon/html-webpack-plugin/issues/1129#issuecomment-456078898) Webpack 5 will come with the new `FileSystemInfo` Api to help developers find out which files have changed since the last build.

I really like the API design a lot and I believe it is a great improvement over the previous way to access it using `compiler.fileDependencies` directly and do the diffing by yourself.

Could you please help us plugin developers to provide a good upgrade path?  
It would be awesome to deprecate `compiler.fileDependencies` in webpack 4 and provide the `FileSystemInfo` Api also for webpack 4.
What do you think?

That way I could already solve [html-webpack-plugin compatibility with webpack 4 & 5](https://github.com/jantimon/html-webpack-plugin/issues/1129) issue and provide support not only for webpack 5 but also for all who have not the time/money to upgrade from webpack 4.

**Comment by evilebottnawi** [comment]
@jantimon do you want send a PR?

**Comment by jantimon** [comment]
Hey @evilebottnawi cool that you are open to add that change 👍

I haven't looked to much into the webpack 5 `FileSystemInfo` api implementation.
And although I know that your time is quite limited right now but it would take me to long to do it by myself.

Can you briefly outline what would be necessary to do so it would be mergeable?

**Comment by evilebottnawi** [comment]
hm, why `compiler.fileDependencies` is bad? Can you provide examples/edge cases?

**Comment by jantimon** [comment]
It is not supported for webpack 5

**Comment by evilebottnawi** [comment]
@jantimon hm, it should be work, can you provide link/example where it is doesn't work?

**Comment by jantimon** [comment]
Sure we have an open issue for that:
https://github.com/jantimon/html-webpack-plugin/issues/1129

**Comment by jantimon** [comment]
Any updates?

**Comment by sokra** [comment]
No update yet.

It's on the list.

Here are some challenges with this. The watcher reports timestamps in a different format which misses some information needed for this API. So backporting probably makes the API pretty slow, as it has to read info from FS again.

**Comment by evilebottnawi** [comment]
Bump

**Comment by jwarkentin** [comment]
> backporting probably makes the API pretty slow, as it has to read info from FS again

I'm all for implementing a better solution if possible and reasonable but slow is still better than broken. Considering it just doesn't work at all right now and there's a completely new API that is fast, the slowness would only apply to plugins using the old API, which would presumably throw a deprecation warning and no longer exist after a reasonable transition period. It's better to have something that at least works and informs users why it's slow so they can pressure plugin developers to update their code.

**Comment by fivethreeo** [comment]
I tried switching html-webpack-plugin to using FileSystem api. The thisCompilation hook I need to use snapshotValid in is a SyncHook. The rest of the compilation runs before the result can affect it. Could the compilation hooks be AsyncSeries instead or am misunderstanding something?
