### ISSUE TITLE
when call watcher.close, webpack still hung up

### ISSUE THREAD

**Issue by lovetingyuan** [webpack/webpack#8987]
# Bug report

**What is the current behavior?**
```javascript
const compiler = webpack(webpackConfig)
const watcher = compiler.watch({}, () => {})
watcher.close(() => {
	// webpack should quit, but the process still hung up
})
```

**If the current behavior is a bug, please provide the steps to reproduce.**
just run code above

**What is the expected behavior?**
webpack should quit or exit after calling `watcher.close()`
If this method is not aim to close webpack, which api should I use to close webpack compiler?

**Other relevant information:**
webpack version:  4.29.6
Node.js version: 8.11.1
Operating System: windows 10
Additional tools: no

**Comment by evilebottnawi** [comment]
Can you create minimum reproducable test report?

**Comment by lovetingyuan** [comment]
I am so sorry, it is my fault, I forgot to close a child process. Apologize again, I will close this issue.
