### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by CT1994** [webpack/webpack#8988]
# Bug report

**What is the current behavior?**
RangeError: Maximum call stack size exceeded using html-webpack-plugin in development or production mode

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/CT1994/html-webpack-plugin-range-error

if you don't see the error bump up the for loop to increase the amount of plugins

**What is the expected behavior?**
you should not get a range error and compile without any issues when running in production mode

more details in this ticket and current situation:
https://github.com/jantimon/html-webpack-plugin/issues/1186

currently got a working version only in development mode.
https://github.com/CT1994/html-webpack-plugin

**Other relevant information:**
webpack version:  4.29.6
Node.js version: 11.12.0
Operating System: windows 10

**Comment by CT1994** [comment]
https://github.com/jantimon/html-webpack-plugin/issues/1186#issuecomment-480975190

based on sokra comment i have created a very barebones example of the issue here
https://github.com/CT1994/tapable-range-error

the issue seems to be coming from tapable

**Comment by CT1994** [comment]
@sokra I’ve created an example of the issue, it seems to be coming from https://github.com/webpack/tapable/blob/2a07fea1dc1f05a2d1de3c9e4be385947596a87d/lib/HookCodeFactory.js#L32

This is what I found to be causing the range error and was able to generate the arguments to test outside of tapable

https://github.com/CT1994/tapable-range-error/blob/master/fnRangeError.js

**Comment by sokra** [comment]
should be fixed by https://github.com/webpack/tapable/pull/95 resp. https://github.com/webpack/tapable/pull/96

**Comment by CT1994** [comment]
@sokra thank you this has resolve the issue :)
