### ISSUE TITLE
Animated GIFs don't get correctly processed

### ISSUE THREAD

**Issue by SetTrend** [webpack/webpack#8989]
### Synopsis

webpack fails when pushing animated GIFs into the loader pipeline. The file content is scrambled.

I tested this issue with both, `url-loader` and `file-loader`.

Other file types are processed correctly.

## System Data

* Operating System: Windows 10x64
* Node Version: v10.15.3
* NPM Version: 6.4.1
* webpack Version: 4.29.6
* url-loader Version: 1.1.2

## Expected Behavior

The following animated GIF should be rendered by the browser:

![InlineThrobber](https://user-images.githubusercontent.com/9283914/55327032-76afdb80-5489-11e9-94bc-a2e9ace4663b.gif)

### With `url-loader`
... the following, incorrect/invalid, `data:` URL is being created:

```
url(data:image/gif;base64,bW9kdWxlLmV4cG9ydHMgPSBfX3dlYnBhY2tfcHVibGljX3BhdGhfXyArICJpbWFnZXMvSW5saW5lVGhyb2JiZXIuZ2lmIjs=)
```

Which in turn, when decoded, results in:

```js
> atob("bW9kdWxlLmV4cG9ydHMgPSBfX3dlYnBhY2tfcHVibGljX3BhdGhfXyArICJpbWFnZXMvSW5saW5lVGhyb2JiZXIuZ2lmIjs=")

'module.exports = __webpack_public_path__ + "images/InlineThrobber.gif";'
```

### With `file-loader`
... the following, incorrect file content is being saved to the `dist` folder:

```batch
PS $ type .\InlineThrobber.gif
module.exports = __webpack_public_path__ + "images/InlineThrobber.gif";
```

### webpack.config.js

```js
const path = require('path');

const cleanWP = require('clean-webpack-plugin').default;

module.exports = {
  entry: {
    testIncrementalSearchWC: "./app/components/_mock/incremental-search/page",
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/i,
        use: 'ts-loader',
        exclude: [
          /[/\\]node_modules[/\\]/,
          /[/\\].*\.js/]
      },
      {
        test: /\.scss$/i,
        use: [{
          loader: 'style-loader' // creates style nodes from JS strings
        }, {
          loader: 'css-loader' // translates CSS into CommonJS
        }, {
          loader: 'sass-loader' // compiles SASS to CSS
        }]
      },
      {
        test: /\.(png)|(svg)|(je?pg)|(gif)$/i,
        use: 'url-loader',
        issuer: {
          include: /app[/\\]components[/\\].*\.(ts)|(scss)$/
        }
      }
    ]
  },
  resolve: {
    extensions: [".ts", ".js", ".scss"]
  },
  output: {
    filename: "[name].bundle.js",
    path: path.join(__dirname, 'dist'),
    publicPath: "/dist/"
  }
};
```

### Screenshots depicting the path information:

![url-loader-1](https://user-images.githubusercontent.com/9283914/55327180-d312fb00-5489-11e9-9413-c7b9db70ae4b.png)

![url-loader-2](https://user-images.githubusercontent.com/9283914/55327186-d4dcbe80-5489-11e9-85a0-94d576477619.png)

![url-loader-3](https://user-images.githubusercontent.com/9283914/55327191-d6a68200-5489-11e9-8608-fcb52c3a7d9a.png)

## How Do We Reproduce?

1. Recreate the depicted folder structure (presumably not required)
1. Create a SASS file, referencing an animated GIF
1. Create some TypeScript file, creating an element that's addressed by the above SASS file
1. Copy above `webpack.config.js` file
<br/>
<hr/>
/ref: webpack-contrib/url-loader#178

**Comment by evilebottnawi** [comment]
Not related to webpack, please don't duplicate issue

**Comment by tamelbrun** [comment]
@evilebottnawi Actually related to webpack adding the `url-loader` by default, causing it to be called twice for the same file. I found this out by debugging webpack and discovering that `url-loader` occurred twice in the list of loaders.
