### ISSUE TITLE
Watch mode not working when you have a context in your config.

### ISSUE THREAD

**Issue by szrenwei** [webpack/webpack#899]
when I use webpack --watch combine a context config, it's not watch the changes.

**Comment by Metallium** [comment]
watcher also does not watch for changes if you specify resolve.root and then require module relatively to this root

e.g.
file tree:
```
scriptsRoot/components/a.js
```
```javascript
    resolve: {
        root: 'scriptsRoot/',
        ...
    }
```
```javascript
require('component/a')
```
(changes in a.js do not trigger invalidation)

**Comment by Metallium** [comment]
aaah, it's not an issue
>context
>>The base directory (absolute path!) for resolving the entry option. If output.pathinfo is set, the included pathinfo is shortened to this directory.

> resolve.root
>>The directory (absolute path) that contains your modules. May also be an array of directories. This setting should be used to add individual directories to the search path.

>>It must be an absolute path! Don’t pass something like ./app/modules.

just use absolute path like 
```
context: require('path').join(__dirname, 'contextDir')
```

@sokra 
I think a precondition assert for absolute paths should be added - it's quite easy to make a mistake
