### ISSUE TITLE
Always getting production env in build

### ISSUE THREAD

**Issue by raj-here** [webpack/webpack#8991]
# How to handle multiple env in webpack

i have to handle multiple environment => production, Preprod, Staging and development
**What is the current behavior?**
I'm bundling js file from ts using below scripts.
```
     build": "webpack",
    "build:prod": "NODE_ENV=production npm run build",
    "build:preprod": "NODE_ENV=preprod npm run build",
    "build:dev": "NODE_ENV=development npm run build",
    "build:stage": "NODE_ENV=stage npm run build"
```

And running the build using below script

```
"start:prod": "NODE_ENV=production node build/server.js",
"start:preprod": "NODE_ENV=preprod node build/server.js",
"start:dev": "NODE_ENV=development node build/server.js",
"start:stage": "NODE_ENV=staging node build/server.js",

```

I'm loading Mongourl from .env.**ENVIROMENT_VARIABLE** file.

but whenever i'm running always it, getting a wired result. 
console.log(process.env.NODE_ENV) prints =>  **production**

**Other relevant information:**
webpack version:  4.29.6
Node.js version: 8.15.0
Operating System: Mac OS (HIGH Sierra)
Additional tools:

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by raj-here** [comment]
Hi @montogeek, thanks for a quick reply.

Here is my test Repo.

[https://github.com/raj-here/webpack-8991](https://github.com/raj-here/webpack-8991)

**Comment by raj-here** [comment]
Follow the below command to reproduce 

`npm run build`
`npm run start`

i'm printing
 `console.log('ENV', process.env.NODE_ENV);`

instead of printing environment name it is printing **mode**.
if you will change the mode name in webpack file. it will print accordingly.

**Comment by sokra** [comment]
`process.env` at build is not embedded into the bundle by default. You can use the EnvironmentPlugin to select environment variable to be embedded.

**Comment by raj-here** [comment]
@sokra ,I've fixed using **DefinePlugin**  plugin and working fine for me.
`new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development')
    })
`

**Comment by raj-here** [comment]
By the way Thanks @sokra , I'll try with EnvironmentPlugin.
