### ISSUE TITLE
Issue with webpack - Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by firojasha** [webpack/webpack#8992]
When doing server less webpack seeing the below errors, 
===============================
external "fs" 42 bytes {0} [not cacheable]
   [2] ./src/splunk.ts 2.13 kB {0} [built]
   [3] external "zlib" 42 bytes {0} [not cacheable]
   [4] ./src/splunklogger.ts 4.02 kB {0} [built]
   [5] external "url" 42 bytes {0} [not cacheable]
   [6] ./src 160 bytes {0} [built]

WARNING in ./src/splunklogger.ts
72:25-106 Critical dependency: the request of a dependency is an expression
==============================

**Comment by firojasha** [comment]
"webpack": "^3.10.0",
"serverless-webpack": "^2.2.3",

**Comment by evilebottnawi** [comment]
Please use issue template. Servless webpack is not official part of webpack, better create issue in their repo, thanks
