### ISSUE TITLE
Webpack4 image can‘t be packaged successfully

### ISSUE THREAD

**Issue by 1Crazy** [webpack/webpack#8993]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I want to package the image in my assets folder into the dist file. I don't know why the image is not packaged after npm run build, but no error is reported.Can you help me resovle this problem，Thanks！

**Other relevant information:**
webpack version:  4
Node.js version: 10.12.0
Operating System: windows7
Additional tools:

**Comment by 1Crazy** [comment]
https://github.com/1Crazy/TodoList-Vue   this is my github Repository

**Comment by evilebottnawi** [comment]
Please use stackoverflow or gitter for help, it is bug tracker, thanks

You use `url-loader` https://github.com/1Crazy/TodoList-Vue/blob/master/webpack.config.js#L49 what change you image to `data:stuff` URI
