### ISSUE TITLE
WebPack error on starting kibana 6.5.2

### ISSUE THREAD

**Issue by mudit94** [webpack/webpack#8994]
I was trying to update the kbn network graph plugin to support more than 2 nodes.
However i am getting the following error in the browser:
__webpack_require__(...).register is not a function 

Version: 6.5.2
Build: 18828
Error: __webpack_require__(...).register is not a function
@http://localhost:5601/bundles/commons.bundle.js:3:2547982
__webpack_require__@http://localhost:5601/bundles/vendors.bundle.js:2:1077
@http://localhost:5601/bundles/commons.bundle.js:3:344835
__webpack_require__@http://localhost:5601/bundles/vendors.bundle.js:2:1077
[6758]@http://localhost:5601/bundles/kibana.bundle.js:3:353930
__webpack_require__@http://localhost:5601/bundles/vendors.bundle.js:2:1077
requireLegacyFiles@http://localhost:5601/bundles/kibana.bundle.js:3:353606
LegacyPlatformService</LegacyPlatformService.prototype.start@http://localhost:5601/bundles/commons.bundle.js:3:834273
CoreSystem</CoreSystem.prototype.start@http://localhost:5601/bundles/commons.bundle.js:3:816463
[6757]@http://localhost:5601/bundles/kibana.bundle.js:3:353464
__webpack_require__@http://localhost:5601/bundles/vendors.bundle.js:2:1077
webpackJsonpCallback@http://localhost:5601/bundles/vendors.bundle.js:2:769
@http://localhost:5601/bundles/kibana.bundle.js:3:1

TypeError: __webpack_require__(...).register is not a function (http://localhost:5601/bundles/commons.bundle.js:3)

Version: 6.5.2
Build: 18828
Error: TypeError: __webpack_require__(...).register is not a function (http://localhost:5601/bundles/commons.bundle.js:3)
window.onerror@http://localhost:5601/bundles/commons.bundle.js:3:863016 

PFA the changes done by me in the js files.
Requesting for a resolution at the earliest
[public.zip](https://github.com/webpack/webpack/files/3037239/public.zip)

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Not related to webpack please open issue in `kibana`
