### ISSUE TITLE
为什么我不能打包文件夹

### ISSUE THREAD

**Issue by MemoryNoodles** [webpack/webpack#8995]
之前我记得可以用webpack src/ --out-dir esm/把src文件夹下的所有东西都打包到esm上，现在怎么不可以了啦

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
