### ISSUE TITLE
Unable to install webpack due to @xtuc/long dependencies

### ISSUE THREAD

**Issue by jzhangnu** [webpack/webpack#8998]
# Bug report

**What is the current behavior?**
1. npm install webpack
2. then get the error
`npm ERR! Maximum call stack size exceeded`
3. then check the log
`108 http fetch GET 404 https://registry.npmjs.org/@xtuc%2flong 479ms
109 silly fetchPackageMetaData error for @xtuc/long@4.2.2 404 Not Found: @xtuc/long@4.2.2
110 verbose stack RangeError: Maximum call stack size exceeded
110 verbose stack     at RegExp.test (<anonymous>)
110 verbose stack     at isDepOptional (/usr/local/lib/node_modules/npm/lib/install/deps.js:405:45)
110 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:414:9)
110 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)`

**If the current behavior is a bug, please provide the steps to reproduce.**
see above

**What is the expected behavior?**

**Other relevant information:**
webpack version:  latest
Node.js version:  10.15.3 (npm 6.4.1 yarn 1.15.2)
Operating System:  Ubuntu
Additional tools:

**Comment by evilebottnawi** [comment]
@jzhangnu do you use `npm` and/or yarn?

**Comment by evilebottnawi** [comment]
Looks problem with register, not with webpack, because https://registry.npmjs.org/@xtuc%2flong return 200

**Comment by xtuc** [comment]
See https://github.com/xtuc/webassemblyjs/issues/462 or https://github.com/webpack/webpack/issues/8798.

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/xtuc/webassemblyjs/issues/462
