### ISSUE TITLE
WebPack error on starting kibana 6.5.2

### ISSUE THREAD

**Issue by mudit94** [webpack/webpack#8999]
# Bug report

**What is the current behavior?**
The kibana UI is failing to start. After the loading is completed, webpack errors are coming.
typeError: __webpack_require__(...).register is not a function kibana 6.5.2
**If the current behavior is a bug, please provide the steps to reproduce.**
I had been trying to modify the kbn network plugin to support multi node relation. 
PFA the js file changes . I had made changes n network_vis and network_vis_controller file.

**What is the expected behavior?**
The kibana UI page should open. and the network plugin should be capable for doing multi node relation.

**Other relevant information:**
Node.js version: v11.12.0
Operating System: Windows 10 
Additional tools:

[public.zip](https://github.com/webpack/webpack/files/3040019/public.zip)

**Comment by evilebottnawi** [comment]
Please open issue in kibana, we can not be responsible for other people's projects
