### ISSUE TITLE
change examples template syntax

### ISSUE THREAD

**Issue by hiroppy** [webpack/webpack#9000]
# Bug report

**What is the current behavior?**

Currently, examples template for creating README is following syntax, but it is fixed by prettier when save.

```
``` javascript
{{example.js}}
```

It will be as follows when it is fixed by prettier.

```
{
	{
		example.js;
	}
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Don't fix by prettier. So we have to change this syntax.

**Other relevant information:**
webpack version:  master branch
Node.js version: N/A
Operating System: N/A
Additional tools: prettier

**Comment by hiroppy** [comment]
@evilebottnawi Do you have any idea?

**Comment by evilebottnawi** [comment]
@hiroppy don't look this issue, many other work, anyway feel free to investigate and fix it
