### ISSUE TITLE
Load chunks using import()

### ISSUE THREAD

**Issue by cromefire** [webpack/webpack#9003]
## Feature request

**What is the expected behavior?**
Loading chunks with `import()`

**What is motivation or use case for adding/changing the behavior?**
Imports are much cleaner than jsonp and in the future more and more browsers and platforms are going to support it, making a unified approach

**How should this be implemented in your opinion?**
Just use `import()` to load the chunk

**Are you willing to work on this yourself?**
Depending on how easy it is and with some help

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/webpack/webpack/issues/2933
