### ISSUE TITLE
Webpack doesn't throw error or warning when the entry file mentioned is config is not found.

### ISSUE THREAD

**Issue by jpmohan1111** [webpack/webpack#9004]
# Bug report

**What is the current behavior?**
Running webpack build through node api does not tell whether the entry file is present or not.

**If the current behavior is a bug, please provide the steps to reproduce.**
Try changing the entry file to any file that doesn't exist and run the build process. There is no errors or warning shown.

**What is the expected behavior?**
Show an error or warning when the entry file is not found.

**Other relevant information:**
webpack version:  3.0.0
Node.js version: v11.8.0
Operating System: Darwin(mac OS X)
Additional tools:

**Comment by evilebottnawi** [comment]
@jpmohan1111 please provide minimum reproducible test repo

**Comment by jpmohan1111** [comment]
```webpack.config.js:``` with valid file.
```
const path = require('path');

module.exports = {
  entry: path.resolve(__dirname, 'src/valid_file.js'),
  mode: 'production',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist')
  },
  devtool: 'source-map'
};
```


```webpack.config.js:``` with non existing file.
```
const path = require('path');

module.exports = {
  entry: path.resolve(__dirname, 'src/non_existing_file.js'),
  mode: 'production',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist')
  },
  devtool: 'source-map'
};
```

I am running the build through the node webpack API as below: node-build.js
```
const webpack = require('webpack');
const webpack_config = require('./webpack.config.js');

webpack(webpack_config, (err, stats) => {
	// console.log(stats)
	const info = stats.toJson();

	if (err || stats.hasErrors()) {
		console.log(err);
	}
	if (stats.hasWarnings()) {
		console.warn(info.warnings);
		}
	console.log('Build complete!!');
	// Done processing
});
```
```node node-build.js```

When the entry file exists it builds the file as expected, but when the entry file is not present, it shows no error/warning and there is no built file.

**Comment by evilebottnawi** [comment]
hm, yep, feel free to send a PR

**Comment by hiroppy** [comment]
@jpmohan1111 Please add `bail`.

**Comment by jpmohan1111** [comment]
@hiroppy thanks adding bail in the config throws the error.

**Comment by evilebottnawi** [comment]
I was wrong, it is expected, answer above

@hiroppy thanks

**Comment by hiroppy** [comment]
Yeah, I agree. I'll investigate this.

**Comment by sokra** [comment]
There is a error. The problem is in the same the error handling is written:

``` js
	if (err || stats.hasErrors()) {
		console.log(err);
	}
```

should be this instead:

``` js
	if (err) {
		console.log(err);
	}
	if (stats.hasErrors()) {
		console.log(info.errors);
	}
```
