### ISSUE TITLE
Webpack externals order

### ISSUE THREAD

**Issue by sneakyfildy** [webpack/webpack#9005]
## Feature request

**What is the expected behavior?**
Make possible to control the order of externals execution.

**What is motivation or use case for adding/changing the behavior?**
Sometime the order of including scripts is important, for example in legacy application we need to use angularjs + angular-ui-sortable plugin which is an adaptation of jQuery plugin, so it requires jQuery to exist in the moment of its first execution.
But if we put a list of externals its being "required" in the end script in alphabet order.

**How should this be implemented in your opinion?**
If externals are set as an array, use it in its array order, do not convert to any kind of dictionary

**Are you willing to work on this yourself?**
no

**Comment by evilebottnawi** [comment]
@sneakyfildy please provide minimum reproducible test

**Comment by sneakyfildy** [comment]
> @sneakyfildy please provide minimum reproducible test

https://github.com/sneakyfildy/shitpack

npm install
npm start

open index.html
you will see errors about lack of jQuery

comment "externals" section in webpack.lib and everything will work

**Comment by evilebottnawi** [comment]
@sneakyfildy first and last warning about `sh*t` word

**Comment by sokra** [comment]
The externals are executed in the order you call the `require`s in your application code.

**Comment by sneakyfildy** [comment]
> The externals are executed in the order you call the `require`s in your application code.

It's not true.
Check linked repo example and run webpack,
index.js which is used to build a lib:

```
window.$ = window.jQuery = require('jquery');
require('jquery-ui/ui/widgets/sortable');
require('angular');
require('angular-animate');
require('angular-ui-sortable');
require('angular-dragdrop');

```
In final result file:

```
(function webpackUniversalModuleDefinition(root, factory) {
            if (true)
                module.exports = factory(__webpack_require__(/*! angular */
                "./node_modules/angular/index.js"), __webpack_require__(/*! angular-animate */
                "./node_modules/angular-animate/index.js"), __webpack_require__(/*! angular-dragdrop */
                "./node_modules/angular-dragdrop/src/angular-dragdrop.js"), __webpack_require__(/*! angular-ui-sortable */
                "./node_modules/angular-ui-sortable/src/sortable.js"), __webpack_require__(/*! jquery */
                "./node_modules/jquery/dist/jquery.js"), __webpack_require__(/*! jquery-ui/ui/widgets/sortable */
                "./node_modules/jquery-ui/ui/widgets/sortable.js"));
            else {}
        }

```

**Comment by sneakyfildy** [comment]
So what? You want me to create another issue?

**Comment by evilebottnawi** [comment]
@sneakyfildy very strange, need investigate

**Comment by sneakyfildy** [comment]
Okay. I will try to dig this in.

**Comment by sneakyfildy** [comment]
Lol. 
Webpack makes different order of externals in production and development modes.
Anyone knows for what reason?

**Comment by evilebottnawi** [comment]
@sneakyfildy looks problem in `terser`, can open issue in `terser-webpack-plugin` with reproducible test repo, thanks

**Comment by sneakyfildy** [comment]
Finally.
It is not a bug actually, seems like it's conflict of different configurations ("externals" technique against webpack modes concepts).
--
If you want to keep an order of "externals" dependencies in a "development" mode of webpack use 
```
optimization: {
   namedModules: false,
   occurrenceOrder: true
}
```
And you'll be fine. Thanks everybody.
