### ISSUE TITLE
output.filename not working if function

### ISSUE THREAD

**Issue by SassNinja** [webpack/webpack#9007]
# Bug report

**What is the current behavior?**

When I use a function for `output.filename` it doesn't work for my dynamic imports: they get emitted as `1.js`, `2.js` etc. with identical chunk value (whereas chunk name is correct)

In addition things get worse when I set `optimization.runtime` to `single` what results in even the entries being affected (only `runtime.js` is correct then).

The same filename code as string works without problems and emits `foo.js`, `bar.js` etc.

```javascript
// working
filename: isProd ? '[name].[chunkhash].js' : '[name].js',

// not working
filename: data => isProd ? '[name].[chunkhash].js' : '[name].js',
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1) create `app.js` with dynamic imports

```javascript
// app.js
console.log('[entry] app');
import(/* webpackChunkName: 'foo' */ './foo').then(mod => console.log(mod.default));
import(/* webpackChunkName: 'bar' */ './bar').then(mod => console.log(mod.default));

// foo.js
export default '[dynamic] foo';

// bar.js
export default '[dynamic] bar';
```

2) change `output.filename` to function and run webpack via node api

**What is the expected behavior?**

I expect no difference when filename function returns the same string I've used for filename string before.

**Other relevant information:**
webpack version: 4.29.6
Node.js version: 10.15.0
Operating System: macOS Mojave (10.14)
Additional tools: -

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo, i think problem in configuration

**Comment by SassNinja** [comment]
@evilebottnawi sure, here's an example repo

https://github.com/SassNinja/webpack-filename-issue

Would be great if it's just a configuration problem (I'm afraid it's not)

**Comment by evilebottnawi** [comment]
Can't reproduce all woks as expected with string and with function

**Comment by evilebottnawi** [comment]
If i use
```
filename: data => isProd ? '[name]1.[chunkhash].js' : '[name]1.js',
```
Only `runtime1.js` has right name.

If i use:
```
filename: isProd ? '[name]1.[chunkhash].js' : '[name]1.js',
```

All chunks have `1` at end.

It is problem right?

**Comment by SassNinja** [comment]
> It is problem, right?

@evilebottnawi yes, that's exactly the problem!

```
filename: data => isProd ? '[name]1.[chunkhash].js' : '[name]1.js',
``` 
doesn't behave identical to 
```
filename: isProd ? '[name]1.[chunkhash].js' : '[name]1.js',
```

Can you confirm this is a bug?

**Comment by SassNinja** [comment]
For easy comparison here's what I get (you may run `node webpack --production` in my provided example repo to reproduce)

the former (function):

| Asset | Size | Chunks | | Chunk Names |
| --- | --- | --- | --- | --- |
| 0.js | 287 bytes | 0 | [emitted] | app |
| 1.js | 167 bytes | 1 | [emitted] | bar |
| 2.js | 166 bytes | 2 | [emitted] | foo |
| runtime.b961c074116a1b3bb974.js | 2.12 KiB | 3 | [emitted] | runtime |

the latter (string):

| Asset | Size | Chunks | | Chunk Names |
| --- | --- | --- | --- | --- |
| app.ff5a81c9d1f86af9f8a2.js | 287 bytes | 0 | [emitted] | app |
| bar.ce9e75201d12758066d6.js | 167 bytes | 1 | [emitted] | bar |
| foo.91e30753944ecaf1f323.js | 166 bytes | 2 | [emitted] | foo |
| runtime.ea2a2d132b94435396fd.js | 2.2 KiB | 3 | [emitted] | runtime |

**Comment by evilebottnawi** [comment]
I think it is bug, so feel free to send a PR (for webpack@5 because it is breaking change)

**Comment by sokra** [comment]
Only the `runtime` chunk is affected by `output.filename`. The other chunks are affected by `ouput.chunkFilename`.

If `output.filename` is a string, `output.chunkFilename` defaults to the same string. If it's a function `output.chunkFilename` defaults to `[id].js`. You cannot provide a function to `output.chunkFilename`.

**Comment by SassNinja** [comment]
@sokra this explains the behavior – thanks for clarifying it!

> You cannot provide a function to `output.chunkFilename`

I've already read this on some other issues but wasn't able to find an explanation why it's technical not possible to use a function for `output.chunkFilename`

Would you tell me the reason behind this?

For a current project I'm using `[name].[chunkhash].js` for most of the files. But because of some internal reasons there are some files that mustn't get hashed.
Therefore I'm looking for a way to define an other filename for these files.
Do you know any (pretty) way to achieve this or is a separate webpack config the only way?

**Comment by evilebottnawi** [comment]
@sokra 
> Only the runtime chunk is affected by output.filename. The other chunks are affected by ouput.chunkFilename.

I think it is misleading and has bad DX, maybe we can introduce `output.runtimeFilename` to avoid this misleading?

> If output.filename is a string, output.chunkFilename defaults to the same string.

Also i think it is misleading too :smile: Maybe we can change behavior in next version? Better don't override `chunkFilename` value from `filename` when it is string.

> You cannot provide a function to output.chunkFilename.

What about allow `chunkFilename` to be `Function` too?

**Comment by SassNinja** [comment]
Any update on this?

@sokra would be awesome if you can clarify things a bit (why `chunkFilename` can't be a function)

**Comment by evilebottnawi** [comment]
@SassNinja i think we can make `chunkFilename` as Function

**Comment by chumbalum** [comment]
I'm also facing this issue. I'm using pdf-js and have to set the workerSrc to the path of the bundled pdfjsWorker.js. Since all my chunks are hashed that's not possible. The solution would have been to bundle pdfjsWorker without a hash using the filename function instead of fixed string. But the filename function causes weird filename behaviour.

**Comment by HarshaLaxman** [comment]
+1

**Comment by AntiMoron** [comment]
> @SassNinja i think we can make `chunkFilename` as Function
Cannot agree more.

I found that the documentation mentioned:

> ##  output.chunkFilename
> `string = '[id].js'`
>
>This option determines the name of non-entry chunk files. See output.filename option for >details on the possible values.
>## output.filename
> `string function (chunkData) => string`

I assume that optional value types of `chunkFilename` is the same as those of `output.chunkFilename`.

Actually only `filename` works when passing function to'em.
