### ISSUE TITLE
Remove duplicate search results from localhost/workspace (file system)

### ISSUE THREAD

**Issue by rafaelcastrocouto** [webpack/webpack#9008]
## Feature request

**What is the expected behavior?**
After searching in the "search" bottom panel, only one the workspace files should appear.
After last update it shows both the "workspace file" and the "localhost file".

**What is motivation or use case for adding/changing the behavior?**
Making the search results more readable and avoid redundant items.
And avoid "this file has not been saved" yellow alert icon that appears in the edited "workspace files" every time you unwillingly edit the "localhost file" instead.

**How should this be implemented in your opinion?**
It was showing only the workspace one version ago, I think that's fine, but maybe this has a reason that I can't understand, so I think the best way would add an option.

**Are you willing to work on this yourself?**
yes, sure!

**Screenshot** 
![Capture](https://user-images.githubusercontent.com/422159/55644973-c0f8cb80-57ad-11e9-9ce0-56e0c4d1f730.JPG)

**Comment by evilebottnawi** [comment]
Can't understand then problem can you create minimum reproducible test repo with example what you have  and what you expected?

**Comment by rafaelcastrocouto** [comment]
Thanks for the response @evilebottnawi 

Step 1 - Add a folder to the "Workspace" on the "Filesystem" panel (in the "Sources" tab)
Step 2 - Create an html file in this folder.
Step 3 - Serve this html with any local server and access it on the localhost URL.
Step 4 - Under "More Tools", open the "Search" bottom panel
Step 5 - Search for a word that appears on the file you created.

**What is the expected behavior?** 
Only one result for the created file should appear as it used to happen one update ago.

**What is the error?** 
Now as you can see in the screenshot I provided in the 1st post, it's also showing the same file twice.
This causes users to unwillingly edit the downloaded file instead of the original one on disk.
And also prevents the changes on the correct file to be applied. 
Instead an yellow icon shows with the message "Changes to this file were not saved to the file system" - as you can see on the new screenshot below.

![Untitled](https://user-images.githubusercontent.com/422159/55720930-67c0b000-59d8-11e9-988a-b04e41ae986a.png)

**Comment by evilebottnawi** [comment]
It is only for css, right?

**Comment by rafaelcastrocouto** [comment]
No, it happens for all file types, (html, js, css) 
Seems like it's no longer able to map the served files to the one in the workspace.
