### ISSUE TITLE
Order in left column

### ISSUE THREAD

**Issue by berthold43** [webpack/webpack#9010]
Hallo!

Why have you change the order in left column it not so easy to follow any more. I mean the tutorial for webpack 4.29.6.

Thommy Johansson

**Comment by hiroppy** [comment]
Don't delete our issue template and you have to submit to https://github.com/webpack/webpack.js.org

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
