### ISSUE TITLE
Common module imported by more than one module was shown only once in `stats.json`

### ISSUE THREAD

**Issue by SidKwok** [webpack/webpack#9011]
# Bug report

**What is the current behavior?**
I'm trying to find all the modules that import `common.js` through `stats.json`, but only `a.js` shown in `common.js` field in `stats.json` such as:

```json
[
    ...
    {
        ...
        "id": null,
        "identifier": "/Users/guoxianglin/Desktop/demo/webpack-demo/src/common.js",
        "name": "./src/common.js",
        "issuer": "/Users/guoxianglin/Desktop/demo/webpack-demo/src/a.js",
        ...
    },
    ...
]

```

**If the current behavior is a bug, please provide the steps to reproduce.**

see the [repository](https://github.com/SidKwok/Reproduction/tree/webpack-stats-bug)

**What is the expected behavior?**
whant i'm expected is:

```json
[
    ...
    {
        ...
        "id": null,
        "identifier": "/Users/guoxianglin/Desktop/demo/webpack-demo/src/common.js",
        "name": "./src/common.js",
        "issuer": "/Users/guoxianglin/Desktop/demo/webpack-demo/src/a.js",
        ...
    },
    {
        ...
        "id": null,
        "identifier": "/Users/guoxianglin/Desktop/demo/webpack-demo/src/common.js",
        "name": "./src/common.js",
        "issuer": "/Users/guoxianglin/Desktop/demo/webpack-demo/src/b.js",
        ...
    },
    ...
]

```

**Other relevant information:**
webpack version:  4.29.6
webpack-cli version: 3.3.0
Node.js version: 10.15.3
Operating System: mac os

I'm not sure if it is a correct way to reach my goal, or is there a better way to do so?

**Comment by evilebottnawi** [comment]
Due `splitChunks.cacheGroups` configuration, you use module same module in difference chunk and you need to move their in own chunk (`default`/`commons`/`etc`). Can you provide minimum reproducible test repo, thanks!

**Comment by evilebottnawi** [comment]
Here default configuration https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsDefaulter.js#L239 and docs about this https://webpack.js.org/plugins/split-chunks-plugin/

You can use second example https://webpack.js.org/plugins/split-chunks-plugin/#splitchunkschunks to exclude this

**Comment by SidKwok** [comment]
I see...

My goal here is to build a tool that get a module's call-relationship and inject it into the runtime code. In this case is to find out who uses 'common.js' and the call-relationship like (see field `issuerPath`):
```javascript
[
    ...
    {
        ...
        "id": null,
        "identifier": "/Users/guoxianglin/Desktop/demo/webpack-demo/src/common.js",
        "name": "./src/common.js",
        "issuer": "/Users/guoxianglin/Desktop/demo/webpack-demo/src/a.js",
        "issuerPath": ['index.js', 'a.js']
        ...
    },
    {
        ...
        "id": null,
        "identifier": "/Users/guoxianglin/Desktop/demo/webpack-demo/src/common.js",
        "name": "./src/common.js",
        "issuer": "/Users/guoxianglin/Desktop/demo/webpack-demo/src/b.js",
        "issuerPath": ['index.js', 'b.js']
        ...
    },
    ...
]
```
and inject the scheme above into the runtime code.

But as you mentioned, webpack seems to combine them into one. Is there a better way to get the call-relationship?

**Comment by evilebottnawi** [comment]
Why? What is problem you try to solve? Looks very weird. Also i recommend you gitter or stackoverflow for questions because it is bug tracker, thanks

**Comment by SidKwok** [comment]
Yup, Thanks
