### ISSUE TITLE
Server-side hot reload not working for Node 11.x

### ISSUE THREAD

**Issue by eliot-akira** [webpack/webpack#9012]
# Bug report

**What is the current behavior?**

On Node.js 11.x, server-side hot reload does not work.

I tracked it down to the function `hotDownloadManifest` in `lib/node/NodeMainTemplate.runtime.js`, which is always returning undefined. It's the `require` statement that's failing - even though the manifest file `$hotMainFilename$` exists.

**If the current behavior is a bug, please provide the steps to reproduce.**

On Node.js 11.x, server-side bundle with `HotModuleReplacementPlugin`, with entry `webpack/hot/poll`.

**What is the expected behavior?**

The function `hotDownloadManifest` in `lib/node/NodeMainTemplate.runtime.js` should return the update data from the manifest, specifically this part:

```js
require("./" + $hotMainFilename$)
```

On Node.js 10.x, the exact same setup works correctly. That hints at the issue being not in Webpack, but Node itself..

**Other relevant information:**
webpack version: 4.29.6
Node.js version: 11.13.0
Operating System: macOS 10.14.3
Additional tools: yarn

**Comment by hiroppy** [comment]
Please submit a reproducible repository.

**Comment by eliot-akira** [comment]
OK, will try to set up a minimal example demonstrating the issue.

**Comment by eliot-akira** [comment]
Here's an example: https://github.com/eliot-akira/webpack-server-side-hot-reload-issue/

I use [n](https://github.com/tj/n) to switch between Node versions. I specifically confirmed with Node.js 10.15.3 and 11.13.0. With the former, the above repo has working hot reload; with the latter, it doesn't.

**Comment by hiroppy** [comment]
I confirmed this issue only Node11.

```
{ Error: Cannot find module './f7f5c34b7aecf12db41d.hot-update.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at hotDownloadManifest (/Users/xxx/Desktop/webpack-server-side-hot-reload-issue/build/server.js:11:26)
    at Object.hotCheck [as check] (/Users/xxx/Desktop/webpack-server-side-hot-reload-issue/build/server.js:203:19)
    at Timeout.checkForUpdate [as _onTimeout] (webpack:///(webpack)/hot/poll.js?:13:6)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5) code: 'MODULE_NOT_FOUND' }
```

**Comment by nikparo** [comment]
With the test repo I get the same behaviour that @eliot-akira does - in node.js 11.x, server-side hot reload does not work, in 10.x it does. I get no errors.

**Comment by eliot-akira** [comment]
As per #9015, this should be fixed in the next Node.js 11 release. I searched their issues and pulls but couldn't find the relevant commit. I'll keep this issue open and note when the fix is confirmed.

**Comment by eliot-akira** [comment]
The issue is solved on Node 12.x.
