### ISSUE TITLE
[i18n-webpack-plugin]: Using default locale throws 'Missing localization' warnings

### ISSUE THREAD

**Issue by cJayyy** [webpack/webpack#9013]
# Bug report

**What is the current behavior?**
If `null` is passed as `localization` argument while creating new I18nPlugin instance, warning about missing localizations occurs. 

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Clone [official example](https://github.com/webpack/webpack/tree/master/examples/i18n).
2. Initialize npm project with dependencies.
3. Define npm script: `"build": "webpack"` 
4. Run `npm run build`

Build succeeds but throws following warning:
```
WARNING in ./example.js
Missing localization: Missing Text
```

webpack.config.js:
```javascript
const languages = {
  en: null,
  de: require("./de.json")
};

module.exports = Object.keys(languages).map(function(language) {  
  return {
    ...
    plugins: [
      new I18nPlugin(languages[language]) // in case 'language' is 'en' we get 'null'
    ]
    ...
});
```

**What is the expected behavior?**
If passing `null` is recommended way how not to translate default language, plugin should behave differently than if try to get missing translation.

**Other relevant information:**
webpack version:  4.29.6
Node.js version: v11.12.0
Operating System: macOS Mojave 10.14.4

**Comment by hiroppy** [comment]
You should change `failOnMissing` to `true` if you want to get errors.
In addition, please submit this issue to https://github.com/webpack-contrib/i18n-webpack-plugin if you want to change behavior.

**Comment by evilebottnawi** [comment]
Yes, please open issue in plug-in repo, thanks

**Comment by cJayyy** [comment]
Thanks for an advice @hiroppy, although it's not what I was asking.  

My goal here isn't about getting errors instead of warnings. My goal is that **no** warnings (or errors) about missing translations should be invoked when passing `null` as translations argument - because we obviously know that `null` contains nothing and we are passing it because the strings we want to use with default language are hard-coded.

Thanks for redirecting me to plugin repository - my mistake, sorry. 

Moved to [i18n-webpack-plugin's issues](https://github.com/webpack-contrib/i18n-webpack-plugin/issues/80).
