### ISSUE TITLE
How can we dynamically load modules after compilation

### ISSUE THREAD

**Issue by navyaagarwal23** [webpack/webpack#9017]
# Bug report
I'm creating an enterprise app and I'm wanting to make it as flexible as possible when it comes to adding new features.

 While it's easy to load in external modules by adding them to your imports etc before you compile it, I'd like to make it easier to deploy modules as new features.

So say I've got a MyFace app, it has two modules:

AppRoot - Basically a container that has a router outlet and a menu on the left for the submodules.
MyFaceProfile - A profile page
MyFaceWall - A wall to post things
Then, I create MyFaceChat. If I've defined the interface (it, say, provides it's root URL and the name/icon of it's icon for a menu). Would it be possible to have AppRoot dynamically load this module and display it without recompiling the app?

This would mean we could just drop modules into the deployment folder to add new features.

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by evilebottnawi** [comment]
Please use stackoverflow and/or gitter for questions, it is bug tracker, thanks
