### ISSUE TITLE
Third party library is always provided with the wrong version of the buffer module

### ISSUE THREAD

**Issue by mkarajohn** [webpack/webpack#9018]
# Bug report

**What is the current behavior?**

My project has a dependency on [music-metadata-browser](https://github.com/Borewit/music-metadata-browser), which, itself, [has a dependency](https://github.com/Borewit/music-metadata-browser/blob/master/package.json#L91) on `buffer^5.2.1`. 

However, [importing `buffer`](https://github.com/Borewit/music-metadata-browser/blob/master/src/index.ts#L1), inside `music-metadata-browser`'s code, actually imports webpack's `node-libs-browser`'s `buffer^4.9.3` module, which is incompatible with `music-metadata-browser`

**If the current behavior is a bug, please provide the steps to reproduce.**

[Here](https://codesandbox.io/s/8ko40vxrml) is a sandbox I created. It is very simple; it's a `create-react-app` project, the only dependency is `music-metadata-browser`, and all it does is show the cover art of the track you uploaded (use the file "Beautiful Emptiness" from [here](https://drive.google.com/drive/folders/1Z8lUx_8BEKrrv9dMk4eO7TyC5M1VCDQe?usp=sharing))

As you can hopefully see, this example, running on codesandbox.io, works fine. Now

* create a new `create-react-app` project, locally, on your machine. ([instructions here](https://github.com/facebook/create-react-app#quick-overview))
* copy paste, from codesandbox to your local project, the contents of the following files:
* * `src/index.js`
* * `package.json`
* `yarn/npm install` and `yarn start`. You do not need to eject.

I have executed the above steps on 3 separate machines (2 running macOS and 1 running Ubuntu) and the `buffer` package is always getting pulled from the wrong place. Check the included screenshot and see the path of `checkOffset()`. It should be pulled from `node_modules/buffer` (which has v5.2) instead it gets pulled from `node_modules/node-libs-browser/node_modules/buffer` (which has v4.9)

<img width="1124" alt="Screen Shot 2019-04-04 at 13 42 47" src="https://user-images.githubusercontent.com/3789226/55550250-6f363f80-56e0-11e9-8c9e-0a3dfd4c80df.png">

**Extra reproduction steps**

My initial thoughts for this happening are explained [here](https://github.com/Borewit/music-metadata-browser/issues/15#issuecomment-479874726). So, the repo was forked and [these lines](https://github.com/Orfium/music-metadata-browser/commit/6130d8794d79a3d95e0f3a445fdec9ed1f130af6) were added, in order to force the compiler to keep the explicit `buffer` import.

However, compiling the new code and running it _still_ imports `buffer` from `node_modules/node-libs-browser/node_modules/buffer`

You can try it yourself, if you want, by cloning [the repo](https://github.com/Orfium/music-metadata-browser/tree/fix/buffer_import), switch to the `fix/buffer_import` branch, compile, and copy paste the resulting file inside your previous project's `node_modules/music-metadata-browser/dist/`, to see that there is no difference even though now the `buffer` package is imported explicitly.

**Extra comments**

Other things I also tried with no success, in the `webpack.config` file, were 

* adding `new webpack.ProvidePlugin({Buffer: 'buffer'})`
* stopping webpack from shimming `Buffer` by doing `node: { Buffer: false }` and adding `new webpack.ProvidePlugin({Buffer: 'buffer'})`

Prior discussions [here](https://github.com/Borewit/music-metadata-browser/issues/15#issuecomment-479874726) and [here](https://github.com/Borewit/music-metadata-browser/issues/15#issuecomment-480071736) (I'd say they are kinda important to read and get an idea of how `music-metadata` and `music-metadata-browser` work with each other)

**What is the expected behavior?**

The expected behaviour is that the explicit `buffer^5.2.1` import is respected and used instead of the `buffer` package that lives inside `node-libs-browser`

**Other relevant information:**
webpack version:  4.19.1
Node.js version: 10.10.1
Operating System: macOS 10.14.3, Ubuntu
Additional tools: `create-react-app`, `music-metadata-browser`

**Comment by evilebottnawi** [comment]
For this case package should provide bundle for browsers, not all package compatibility with browser, as workaround you can use https://webpack.js.org/plugins/normal-module-replacement-plugin/

**Comment by mkarajohn** [comment]
First of all THANK YOU SO MUCH, I have been dealing with this since last week, and this is the first time I managed to get it working.

However, I have a few questions, still:

What is the difference between `NormalModuleReplacementPlugin` and `ProvidePlugin` ? `ProvidePlugin` reads: 

>Whenever the identifier is encountered as free variable in a module, the module is loaded automatically and the identifier is filled with the exports of the loaded module

Which, theoretically should work when I did `new webpack.ProvidePlugin({Buffer: 'buffer'})`, no? The `music-metadata` package freely uses `Buffer` without any imports because it expects to be run in a node environment. So, why did `ProvidePlugin` not work in my case? Shouldn't webpack inject the `node_modules/buffer` package wherever a `Buffer` usage was met? I must be understanding something wrong. 

>For this case package should provide bundle for browsers, not all package compatibility with browser

I am not sure I understand this sentence completely. `music-metadata-browser` is _supposed_ to be exposing `music-metadata` in a way that allows the latter to be run in a browser environment, instead of node. So, `music-metadata-browser` importing (in the browser) shims for all the necessary stuff `music-metadata` needs to work in node (like `buffer^5.2.1`), should be enough, no?

My question, as to why the import of the `buffer` package from inside `music-metadata-browser` is not respected, still exists.

**Comment by evilebottnawi** [comment]
> What is the difference between NormalModuleReplacementPlugin and ProvidePlugin ? ProvidePlugin reads:

NormalModuleReplacementPlugin > for replace in `require`/`import`
ProvidePlugin > for include `require`/`import`

But you don't have `require`/`import` `Buffer`

> I am not sure I understand this sentence completely. music-metadata-browser is supposed to be exposing music-metadata in a way that allows the latter to be run in a browser environment, instead of node. So, music-metadata-browser importing (in the browser) shims for all the necessary stuff music-metadata needs to work in node (like buffer^5.2.1), should be enough, no?

https://github.com/defunctzombie/package-browser-field-spec

You should provide bundled version for browser using `browser` field. Why? Some modules can be polyfilled, some can be mocked, but not all. Example some packages can use modules like `child_process`, `worker_threads` and etc and no polyfills for this modules. And sometimes no way to fix it using `NormalModuleReplacementPlugin` because their logic require this modules (example package can try to load something from file system before run). 

In this case developers of library provide alternative version of package (developers use webpack or rollup for build this version and other change original source code - add more check, provide ability to mocking and/or polyfilling). 

Better use stackoverflow for this. Also if something misleading in docs, please open issue in webpack-docs repo.

**Comment by mkarajohn** [comment]
Ok, thank you very much, I am ok with closing this.
