### ISSUE TITLE
HotModuleReplacementPlugin allow for custom implementations of hotDownloadManifest and hotDownloadUpdateChunk

### ISSUE THREAD

**Issue by AlexLeung** [webpack/webpack#9026]
## Feature request

**What is motivation or use case for adding/changing the behavior?**

Sometimes you might want to have influence over how the HMR runtime fetches the manifest and update files. For example perhaps in node, you want to perform a XHR request rather than requiring the file from the operating system's file system. Another example: perhaps in a bundle which targets the web, you want the GET request to have some special headers for authentication.

**How should this be implemented in your opinion?**

In any file which is bundled, there could be a global api where we could register a class which implements some downloadHotFile method, and then this method is called by hotDownloadManifest and hotDownloadUpdateChunk from then on.

**Are you willing to work on this yourself?**
yes, after some discussion.

**Comment by evilebottnawi** [comment]
@AlexLeung you can implement own plugin, what is problem?

**Comment by AlexLeung** [comment]
You're saying it would be preferable for me to implement a substitute for HotModuleReplacementPlugin than to extend the behavior of the plugin?

**Comment by AlexLeung** [comment]
What I have been trying to accomplish is custom download of manifest and update chunk files generated by Webpack's HMR plugin. I evaluated a few approaches.

1. Extend the module.hot object to allow for setting a custom file download method which would take in the hotAddUpdateChunk method, public path, and chunk/manifest file name as an argument.
1. Expose the hotSetStatus and hotAddUpdateChunk methods directly on module.hot
1. Add a new method to module.hot which accepts a resulting hotUpdate directly, thus bypassing the module.hot.check workflow altogether.

I concluded that option 3 makes the most sense. I will be running some tests then submitting a PR for the change. Basically module.hot will have a new method named `applyWithOwnUpdateRetrievalStrategy`. Implementation will look like this:

```javascript
/**
 * Applies hot update downloaded in way other than typical "check" "apply" methods.
 * @param updatedModuleNameToNewModuleSourceMapping POJSO 
 *        mapping from update module id string to the new source string of the module.
 */
function hotApplyWithOwnUpdateRetrievalStrategy(updatedModuleNameToNewModuleSourceMapping) {
    if (hotStatus !== "idle") {
        throw new Error("applyWithOwnUpdateRetrievalStrategy() is only allowed in idle status");
    }
    hotSetStatus("prepare"); // Technically not necessary but kept for consistency.
    hotUpdate = updatedModuleNameToNewModuleSourceMapping;
    hotApplyOnUpdate = true;
    hotDeferred = {};
    var outdatedModulesPromise = new Promise(function(resolve, reject) {
        hotDeferred.resolve = resolve;
        hotDeferred.reject = reject;
    });
    hotUpdateDownloaded();
    return outdatedModulesPromise;
}
```

The benefits of the 3rd option are

1. Totally subverts check, apply workflow meaning less room for bugs, and fewer total requests possibly, and overall the client has total control of the way requests are made
1. Less internals exposed than 2nd option where client needs to understand how to set statuses correctly to not cause internal errors

The main drawback of the 3rd option is

1. The client needs to understand how to parse the manifest and hot update chunk files, and correctly translate their contents to the input of the function.

**Comment by evilebottnawi** [comment]
bump

**Comment by AlexLeung** [comment]
Thanks. Confirmed that my proposed change works https://github.com/skoville/webpack-hot-module-replacement/blob/49bf31bf00425d0cff00fe52f1b512e90a7ad7b6/packages/%40skoville/webpack-hmr-server-node-customizable/source/webpack-bootstrap-source-injection.ts

I will do some additional investigation on how this change should be made to webpack 5 before submitting a PR.

**Comment by Jack-Works** [comment]
![image](https://user-images.githubusercontent.com/5390719/94416483-7d6bfb80-01b1-11eb-935a-8d3784ceec5e.png)

Agree, I need to provide my own implementation of those hooks otherwise I need to dirty patch on the prototype of Web APIs to make HMR work

**Comment by Jack-Works** [comment]
Now I have a new problem. My environment have `fetch` but no `XMLHttpRequest`. HMR now reports "[HMR] Update check failed: Error: No browser support"
