### ISSUE TITLE
Dynamic Import replace path

### ISSUE THREAD

**Issue by yaroslavert** [webpack/webpack#9027]
other.js
var env = { url: " htts://any.domen.com" }
Index.js
import('./entry')
entry.js
console.log('run');
index.html

<script type="text/javascript" src="htttps://other.domen.com/other.js"></script> <script type="text/javascript" src="./index.js"></script>
build all and get index and entry chunk.

entry chunk I am storage in " htts://any.domen.com"

I need Dynamic change chunk URL

example import({ chunkName: ./entry', path: env.url })
but it is not working.
How can I do it?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by yaroslavert** [comment]
import(
  './entry'.
  env.url
);

when we back finished building I am needing in folder dist have index.js that include entry.js and using
this path (env.url + ./entry)(remote path) not this ./entry(local path)
