### ISSUE TITLE
https://webpack.js.org/ pages not loading CSS / images (404 errors)

### ISSUE THREAD

**Issue by DustinGaudet** [webpack/webpack#9028]
# Bug report

**What is the current behavior?**
Styles and images are missing on the webpack documentation pages at https://webpack.js.org/, console shows numerous 404 errors for image / css requests, across multiple pages.

**If the current behavior is a bug, please provide the steps to reproduce.**
Visit https://webpack.js.org/ on Chrome, Firefox or Safari (probably any browser, really)

**What is the expected behavior?**
CSS and image requests should not be returning 404 errors. The page should be styled in a way that makes it easy to navigate (on Firefox I am seeing GIANT hamburger menu, search and other icons among other strange visual bugs).

**Other relevant information:**
webpack version:  N/A
Node.js version: N/A
Operating System: OSX 10.14.4
Additional tools: Chrome, Firefox, Safari

**Comment by evilebottnawi** [comment]
@webpack-bot move to webpack/webpack.js.org
