### ISSUE TITLE
How to register a custom loader in webpack.config

### ISSUE THREAD

**Issue by lovedota** [webpack/webpack#903]
Hi guys.
I have a problem with https://github.com/webpack/jade-loader. It always return a function, but i want this loader always return a string. So that I intend to write a **custom loader** that return a string from **jade-loader template function.** It is very simple, but how can i use it ?
```
module.exports = function(source) {
  console.log(source);
  return source();
};
```
I want to use like that  "jade-loader -> template function -> jade-to-html -> return string -> ng-cache -> get this string for angular template-cache".
```
var jadeToHtmlLoader = require('./jade-to-html-loader');
//How can i use like this. Thanks !
{test: /\.jade/, loader: "jade-loader!jade-to-html-loader!ng-cache?prefix=[dir]/[dir]"},
```

**Comment by mogelbrod** [comment]
I'm wondering the same thing. There doesn't seem to be any documented way of doing this, apart from publishing the loader on npm?

**Comment by chenerlang666** [comment]
Is there any way can i test my loader worked before i publish it?

**Comment by ZombieHippie** [comment]
@chenerlang666 
You can use the `resolveLoader.alias` config option which works the same way that `resolve.alias` works.

For example: 
```javascript
  resolveLoader: {
    alias: {
      "jade-loader-custom": path.join(__dirname, "./jade-loader-custom")
    }
  },
  resolve: {
    modulesDirectories: ["src/scripts", "web_modules", "bower_components", "node_modules"],
    extensions: ["", ".js", ".coffee", ".json"],
    alias: require("./webpack-module-alias.js")
  },
```

**Comment by ZombieHippie** [comment]
In addition, they show a relative loader in the [introduction to loaders](http://webpack.github.io/docs/loaders.html#introduction)
```javascript
require("./loaders/my-loader!./my-awesome-module");
```

**Comment by airtonix** [comment]
Since all the pieces to solve this puzzle are not here or on the linked pages: 

```es6
// my-project/build/webpack.config.js
...
  module: { 
    loaders: [
      { test: /\.foo$/, loader: 'bar'}
    ]
  },
...
  resolveLoader: {
    fallback: [
      path.resolve(__dirname, 'loaders'),
      path.join(process.cwd(), 'node_modules')
    ]
  }
...
```

```es6
// my-project/build/loaders/foo-loader.js
var utils = require('loader-utils'),
	debug = require('debug')('loader/foo');

module.exports = function (source) {
  // do foo
 debug('start', source.length);
 return source;
}
```

**Comment by IAMtheIAM** [comment]
Now we need the webpack 2 compatible version of these scripts.

**Comment by Clinik** [comment]
With webpack 2 I could only make it work with:
`require.main.paths.concat(path.join(__dirname, 'my-loaders')); 
config = {...}
`

**Comment by vitkrv** [comment]
For Webpack 2 just update `resolveLoader` section.
I've dropped my custom loaders to **custom-webpack-loaders** folder.
```javascript
resolveLoader: {
   modules: ['node_modules', 'custom-webpack-loaders', path.join(process.cwd(), conf.paths.src)]
},
```

**Comment by jiayihu** [comment]
I paste my custom loader used in Webpack 2 for anyone interested in future:

```javascript
// Webpack config
resolveLoader: {
    alias: {
      'readme-loader': path.join(__dirname, './scripts/readme-loader'),
    },
 }


// In module.rules
{
    test: /\.md$/,
    use: ['readme-loader'],
 }
```

The `readme-loader` is very similar to `raw-loader` and exports an object with both parsed and raw markdown. The [raw-loader](https://github.com/webpack-contrib/raw-loader/blob/master/index.js) is a very nice and easy to understand example of loader.

**Comment by adriancmiranda** [comment]
This works too:
```javascript 
// In module.rules
{
    test: /\.js$/,
    loader: `${require.resolve('../loaders/your-loader')}`,
}
```

**Comment by DerZyklop** [comment]
@lovedota i was about to create the same loader. Did you create a public loader from your idea?

**Comment by DerZyklop** [comment]
@lovedota ah.. found it.. [function-to-string-loader](https://github.com/lovedota/function-to-string-loader)

**Comment by nikini** [comment]
@adriancmiranda Using it the way you are describing does not give you the proper context object (`this`). I used it like @jiayihu was suggesting and it works nicely 👍

**Comment by jiayihu** [comment]
It's not fault of toolchains, arrow functions bind `this` to the lexical value by spec, which is `undefined` for a module top-level function.
