### ISSUE TITLE
webpack4中CommonsChunkPlugin的示例修改建议

### ISSUE THREAD

**Issue by webvs2** [webpack/webpack#9030]
官方指南文档非常好，在阅读学习wepack4的代码分离中防止重复(prevent duplication)一章的CommonsChunkPlugin是使用示例希望修改，虽然看错误报告，然后百度一下可以解决.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please use english and `CommonsChunkPlugin` is deprecated in favor https://webpack.js.org/plugins/split-chunks-plugin/

**Comment by webvs2** [comment]
Oh, sorry, I have reviewed the suggested template, this is the first time I submit the question. If the Chinese contribution can be modified, I will try
