### ISSUE TITLE
Combine hashed class-names and readable class-names

### ISSUE THREAD

**Issue by goinnovative** [webpack/webpack#9033]
Hey,

I am using the React create-app to create a new React-App.

By default, any mechanism of webpack or the style-loader (?) deletes class-names from my component when building, which are not in use. 

`<Button className={'hello'} />`

would result in:

`<Button />`

In general this makes sense. But I want to add classes anyway. So I can affect the styling of the button from the "outside" of the React-app (e.g. the global CSS-file of the website, which includes my React-app).

The perfect solution for me, would be to define class-names, which get hashed and are used in the default way by the style-loader, combined with readable class-names which can be used from "external" css-files.

`<Button className={ classnames(styles.button, 'style-your-button-with-this-class') } />
`
results in:

`<Button class="da39a style-your-button-with-this-class" />`

Is this possible?

**Comment by hiroppy** [comment]
This issue will be closed if you don't use out issue template. /cc @goinnovative

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.


Please use stackoverflow or gitter in your case
