### ISSUE TITLE
Minify multiple CSS files compiled out of SCSS

### ISSUE THREAD

**Issue by getsetgopi** [webpack/webpack#9037]
I'm compiling multiple SCSS file to individual CSS file using file-loader. The file loader extracting to individual files and SCSS is compiling to CSS, but file-loader does not have feature to minify CSS.
Is there a plug-in that can read the output CSS path and minify the CSS?
I have tried the following pulg-ins with no luck.

- ExtractTextPlugin
- extract-text-webpack-plugin
- clean-css-loader
- and some others

Below is my Webpack config for reference. Any help is highly appreciated.
```
const webpack = require('webpack');
const path = require('path');
const devMode = process.env.NODE_ENV !== 'production';
const config = {
    entry: [
        './scss/test-1.scss',
        './scss/test-2.scss',
        './scss/test-3.scss',
        './scss/test-4.scss',
        './scss/test-5.scss',
        './scss/test-6.scss',
        './scss/test-7.scss',
        './scss/test-8.scss',
    ],
    output: {
        path: path.resolve(__dirname, 'css'),
        filename: 'bundle.js'
    },
    module: {
        rules: [{
            test: /\.scss$/,
            use: [{
                    loader: 'file-loader',
                    options: {
                        sourceMap: true,
                        name: '[name].css'
                    }
                },
                {
                    loader: "sass-loader",
                    options: {
                        name: '[name].scss',
                        sourceMap: true
                    }
                }
            ]
        }]
    },
    mode: 'production',
    devtool: devMode ? 'eval-source-map' : 'source-map',
}
module.exports = config;
```

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Minify css out of scope webpack right now

**Comment by evilebottnawi** [comment]
Please use https://github.com/NMFR/optimize-css-assets-webpack-plugin
