### ISSUE TITLE
Assertion `handle->flags & UV_CLOSING' failed.

### ISSUE THREAD

**Issue by haf** [webpack/webpack#904]
```
$ node node_modules/webpack/bin/webpack.js
node: ../deps/uv/src/unix/core.c:209: uv__finish_close: Assertion `handle->flags & UV_CLOSING' failed.
```

When compiling - not every time though.

Related? https://github.com/joyent/libuv/issues/949

Dockerfile:

```
WORKDIR /tmp
RUN curl -O -sL https://nodejs.org/dist/v0.12.0/node-v0.12.0-linux-x64.tar.gz && \
    tar zxf node-v0.12.0-linux-x64.tar.gz && \
    cp -rp node-v0.12.0-linux-x64 /usr/local/ && \
    ln -s /usr/local/node-v0.12.0-linux-x64/ /usr/local/node

# ...
```

devDependencies:

```
    "webpack": "*",
    "webpack-dev-server": "*"
```

**Comment by jedwards1211** [comment]
Also happening when I `grunt webpack-dev-server` with the following config:

```
    'webpack-dev-server': {
      options: {
        hot: true,
        port: 8000,
        webpack: webpackDevConfig,
        publicPath: '/assets/',
        contentBase: './<%= pkg.src %>/',
      },

      start: {
        keepAlive: true,
      }
    },
```

I've seen a few other assertion errors coming out of libuv as well.

**Comment by mako-taco** [comment]
What node version are you using?

**Comment by haf** [comment]
0.12

**Comment by eugene1g** [comment]
I had the same issue with node 0.12 and io.js 1.6.2. The workaround was to downgrade to sass-loader@0.5.0 which installed node-sass@3.0.0-alpha.0 and that combination worked at least on my project.

**Comment by haf** [comment]
I couldn't get it to work reliably, so I dropped SCSS completely. What a piece of crap node-sass' versioning and support.

**Comment by jedwards1211** [comment]
I had to downgrade to sass-loader 0.5.0 and node-sass 2.0.1, then the error went away. I didn't have any luck with node-sass 3.0.0-alpha.0 either.

I have to wonder, how much would I really suffer from the lower performance of a Sass compiler written in pure Javascript instead of C?  This experience validated the nervousness I feel everytime I see C code getting compiled during an `npm install`.

**Comment by jhnns** [comment]
@haf 

> What a piece of crap node-sass' versioning

The versioning says *beta*, so what did you expect?

> and support is.

Frauds! They don't give you A+ support after all the money you've spend...

Please calm down. We're doing this in our spare time, unpaid.

**Comment by haf** [comment]
@jhnns I expect them to provide a non-beta version, obviously!

**Comment by pkese** [comment]
@haf I wish github would have a Like button so I could like you comment. I'm sharing the same pain and I could not agree more with you.

**Comment by haf** [comment]
@pkese Thanks! It feels really good to know I'm not alone... =)

**Comment by saper** [comment]
How can I quickly reproduce this? (I am not using webpack). I also could not use `node-sass-3.0.0-beta.4` bacause it is not `>node-sass-3.0.0-pre`.  (Solved by changing package.json locally to `node-sass-3.0.0-rbeta.4`)

@am11 We shouldn't launch `-beta` after `-pre` :(

**Comment by istarkov** [comment]
I have the same issue (not every run but sometimes) width node v0.12 and sass-loader 1.01,

This issue is not reproducible if i use node-sass alone `node-sass -i ./pathto.sass`, it looks like the trouble is in custom importer which sass-loader uses.

**Comment by mingfang** [comment]
What is the status of this issue?
My development has been halted due to this issue.

**Comment by saper** [comment]
This issue is fixed in node-sass git `master`. You can fetch it directly from git.

**Comment by haf** [comment]
Closing as it's not webpack-specific, but specific to node-sass.

**Comment by jedwards1211** [comment]
I think we've all felt some frustration on this, but on the other hand, there's no one we can reasonably blame here for the dependency on C/C++ -- as far as I can tell the only popular Sass preprocessor (libsass) is written in C/C++ and so node-sass, which sass-loader uses, was just created to wrap it.

I forget to be thankful for things that are free...thank you Johannes for writing the sass-loader, it's worked great once I found a working version of node-sass!
