### ISSUE TITLE
Use resolve.modules from config in exec function in loader

### ISSUE THREAD

**Issue by artem-malko** [webpack/webpack#9041]
# Bug report

**What is the current behavior?**
**If the current behavior is a bug, please provide the steps to reproduce.**

I need to compile modules in my loader. So, I have my custom exec implementation in my loader:
```
const exec = (loaderContext: loader.LoaderContext, code: string, filename: string) => {
  const module = new Module(filename, loaderContext);
  module.paths = Module._nodeModulePaths(loaderContext.context);
  module.filename = filename;
  module._compile(code, filename);

  delete require.cache[filename];

  return module.exports;
};
```
I've got it from https://github.com/webpack/webpack.js.org/issues/1268#issuecomment-313513988
Actually, this exec implementation looks like exec from webpack itself https://github.com/webpack/webpack/blob/a67ffcda1c6ffe0a08a34d3b944fec0db38ad57a/lib/NormalModule.js#L175

In my webpack config I have custom resolver for modules:
```
  resolve: {
    modules: [path.resolve(__dirname, '..', 'node_modules'), path.resolve(__dirname, '..', 'src')],
    extensions: ['.ts', '.tsx', '.js'],
  },
```
In webpack 4.30.0 and older my exec function I tried to compile module with content:
```
const dt = require('something/another');
```
Folder structure:
```
src
--something
----another
```
Webpack throw error: can not resolve `something/another`;

If I will use relative path — everything will be ok(
**What is the expected behavior?**

Webpack will use resolve.modules in loader.

**Other relevant information:**
webpack version:  4.30.0 and older
Node.js version: it does not matter
Operating System: OS X
Additional tools:

**Comment by evilebottnawi** [comment]
Can you create minimum reproducible test repo?

**Comment by artem-malko** [comment]
@evilebottnawi I will try to do it tomorrow.

**Comment by artem-malko** [comment]
@evenstensberg here you are https://github.com/artem-malko/webpack-loader-exec-test
I described two problems with exec in loader. Will wait for feedback.

**Comment by artem-malko** [comment]
@evilebottnawi up!)

**Comment by evilebottnawi** [comment]
Because using require(something/other) mean load something package from node modules and load other from this package, I still can't understand problem and how it is related to execute

**Comment by artem-malko** [comment]
@evilebottnawi I have custom exec in my loader https://github.com/artem-malko/webpack-loader-exec-test/blob/master/loader/index.js#L7
I need it for some reasons. 
So, I try to execute this module https://github.com/artem-malko/webpack-loader-exec-test/blob/master/src/moduleA/index.js
You can find require('moduleB') there. This require is resolved by webpack config https://github.com/artem-malko/webpack-loader-exec-test/blob/master/webpack.config.js#L12 but in exec function this config is not used. So, I've got an error, that module 'moduleB' can not be resolved. If I'll change require('moduleB') to require('../moduleB') — everything will be ok, cause there will be relative path and resolve config from webpack.config.js is not used.

**Comment by sokra** [comment]
`exec` will execute the source code in node. This won't apply any webpack logic.

**Comment by artem-malko** [comment]
@sokra so, is it possible to apply webpack logic?)

**Comment by evilebottnawi** [comment]
multi compilation mode

**Comment by artem-malko** [comment]
@evilebottnawi what does it mean?

**Comment by evilebottnawi** [comment]
@artem-malko type, child complication, you can find example here https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/loader.js#L81

**Comment by artem-malko** [comment]
Oh, thanks) I'll try it
