### ISSUE TITLE
webpack' parser evaluates node-related expressions even when polyfills are disabled

### ISSUE THREAD

**Issue by lexaknyazev** [webpack/webpack#9042]
# Bug report

**What is the current behavior?**
webpack evaluates and optimizes-out node-related expressions even when polyfills are disabled.

**If the current behavior is a bug, please provide the steps to reproduce.**

**webpack.config.js**
```js
module.exports = {
    mode: 'none',
    node: false,
    optimization: {
        minimize: false
    }
}
```

**src/index.js**
```js
if (typeof __dirname !== 'undefined') {
    console.log(__dirname);
} else {
    console.log('undefined');
}
```

Compiled output (**dist/main.js**):
```js
if (true) {
    console.log(__dirname);
} else {}
```

**What is the expected behavior?**
webpack's parser should not make such strong assumptions about potentially undefined variables. It's also worth noting that adding one level of indirection bypasses this optimization:
```js
const hasDir = typeof __dirname !== 'undefined';
if (hasDir) {
```
remains intact.

**Other relevant information:**
webpack version:  4.30.0
Node.js version: 11.14.0

**Comment by evilebottnawi** [comment]
Can you create minimum reproducible test repo?

**Comment by lexaknyazev** [comment]
Sure. https://github.com/lexaknyazev/webpack_node

**Comment by lexaknyazev** [comment]
The issue is that `NodeStuffPlugin` always registers `__dirname` and `__filename` constants regardless of `node` configuration.

In the following example, even when `node.__dirname` is equal to `false`, the identifier will be registered:
https://github.com/webpack/webpack/blob/b72b96a2bc5d2c7a308d0943567e0db191d3c358/lib/NodeStuffPlugin.js#L78-L92

Compare with `NodeSourcePlugin` that adds its expressions only when they are explicitly enabled:
https://github.com/webpack/webpack/blob/b72b96a2bc5d2c7a308d0943567e0db191d3c358/lib/node/NodeSourcePlugin.js#L83-L94

**Comment by evilebottnawi** [comment]
I think it is expected for `webpack@4` (can you test this with `webpack@5`)? We can't change this because it is breaking change

**Comment by lexaknyazev** [comment]
`webpack@5` (taken today from the `next` branch) has the same issue since the plugin in question has the same logic.

The documentation [says](https://webpack.js.org/configuration/node/):
> Since webpack 3.0.0, the `node` option may be set to `false` to completely turn off the `NodeStuffPlugin` and `NodeSourcePlugin` plugins.

While in fact, only `NodeSourcePlugin` is being turned off completely:
https://github.com/webpack/webpack/blob/b72b96a2bc5d2c7a308d0943567e0db191d3c358/lib/node/NodeSourcePlugin.js#L14-L19

**Comment by sokra** [comment]
Looks like a bug. Send a PR
