### ISSUE TITLE
When web pack configures template using html-webpack-plugin plug-in, report Entrypoint undefined = index.html

### ISSUE THREAD

**Issue by shenanheng** [webpack/webpack#9043]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**
   Template report undefined

**What is the expected behavior?**
Normal display of pages

**Other relevant information:**
webpack version:  4.29.6
Node.js version: 10.8.0
Operating System: win10
Additional tools
![配置1](https://user-images.githubusercontent.com/24730317/56118284-83115980-5f9c-11e9-96f8-fc50d5eb3def.png)
![配置2](https://user-images.githubusercontent.com/24730317/56118302-8dcbee80-5f9c-11e9-8d1b-0cb99e8072ab.jpg)
![配置3](https://user-images.githubusercontent.com/24730317/56118314-96bcc000-5f9c-11e9-90dc-dce04179f040.jpg)
![未定义](https://user-images.githubusercontent.com/24730317/56118326-9de3ce00-5f9c-11e9-8a00-d5a92d0aeb0c.jpg)

**Comment by sokra** [comment]
html-webpack-plugin used to pass `undefined` as name for the entrypoint.

Since this commit https://github.com/jantimon/html-webpack-plugin/commit/f29ae886d7fad50e7fbb78ac7ff7d5bd9bc47f49#diff-ee97c5091b89979aace94674818996baR113 it passes a name.

**Comment by sokra** [comment]
cc @jantimon
