### ISSUE TITLE
.mjs ESM wildcard import from .js CJS causes incorrect build error

### ISSUE THREAD

**Issue by jaydenseric** [webpack/webpack#9044]
# Bug report

**What is the current behavior?**

An ESM wildcard import from a CJS `.js` file within a `.mjs` file incorrectly causes the following Webpack build error:

```
Can't import the namespace object from non EcmaScript module (only default export is available)
```

In reality ESM wildcard imports from CJS files has always worked in Node.js `--experimental-modules` mode:

<img width="1342" alt="Screen Shot 2019-04-17 at 5 32 13 pm" src="https://user-images.githubusercontent.com/1754873/56270262-154e6480-6139-11e9-9c18-1af25ba1342c.png">

**If the current behavior is a bug, please provide the steps to reproduce.**

With `a.js`:

```js
module.exports = {
  foo: 'bar'
}
```

And `b.mjs`:

```js
import * as a from './a'
console.log(a)
```

Run:

```sh
webpack b.mjs
```

To see the incorrect build error:

<img width="714" alt="Screen Shot 2019-04-17 at 5 55 50 pm" src="https://user-images.githubusercontent.com/1754873/56270701-1b911080-613a-11e9-8884-dbd3f6a8f885.png">

**What is the expected behavior?**

There should not be a build error.

If I change this line in the Webpack code:

https://github.com/webpack/webpack/blob/v4.30.0/lib/dependencies/HarmonyImportSpecifierDependency.js#L83

To:

```diff
- this._id !== "default"
+ this._id !== "default" && this._id !== null
```

The problem goes away. Although I don't know what the proper way to detect a wildcard import is.

**Other relevant information:**
webpack version:  4.30.0
Node.js version: 8.5.0 - 11.14.0
Operating System: macOS Mojave
Additional tools: N/A

**Comment by sokra** [comment]
Send a PR.

The behavior is already implemented, only the error need to be removed.
