### ISSUE TITLE
Package added to a higher precedence directory in resolve.modules does not trigger compile in watch mode

### ISSUE THREAD

**Issue by mvanbutselaar** [webpack/webpack#9045]
# Bug report

**What is the current behavior?**

When having multiple resolve.modules (e.g. override-packages, and base-packages), on building and initial webpack-dev-server compilation, the packages are correctly loaded from the directory with highest precedence.
However when a package is in base-packages on the first compilation, and you add an override package with the same name to override-packages (with or without source files in it), no rebuild is triggered.

**If the current behavior is a bug, please provide the steps to reproduce.**

I have created a minimal reproducible case on [Github](https://github.com/mvanbutselaar/webpack-package-override). See the README for instructions. It runs a dev-server and the adding and removing of an override package is automated, and tested by the script. I also included two arguments to modify cache and/or dependency behavior.

**What is the expected behavior?**

Since order is important in resolve.modules, and watching is enabled in webpack-dev-server, it should detect if a module now resolves to a different location.

**Things I have tried**

Some tests were done to trigger a correct rebuild. The only thing that worked was adding a context dependency on the whole context root (or on each module directory), AND disabling cache and resolve.cache. (Added arguments in the repository for this).
The watching of (part of) root context I can live with (We already do some context watching for a plugin we use in our case), but disabling the cache will be a severe performance hit.

**Other relevant information:**
webpack version:  4.30.0
Node.js version: 8.15.0
Operating System: MacOS 10.14.3
Additional tools: n/a

**Comment by sokra** [comment]
This is a shortcoming in webpack 4. It's fixed in webpack 5.
