### ISSUE TITLE
library isn't available anymore in window after adding splitChunks

### ISSUE THREAD

**Issue by joker-777** [webpack/webpack#9048]
# Bug report

**What is the current behavior?**

By using a library name and returning an object in our entry files we were able to make certain functionality accessible through window.<library name>.
Since we added the splitChunks optimization, this doesn't work anymore. `window.<library name>` is undefined.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here is the most important part of our webpack config file
```coffee
webpack = require("webpack")
path = require("path")

module.exports =
  entry:
    application: "./app/assets/javascripts/application.coffee"
  output:
    library: "application"
    publicPath: "/webpack/",
    filename: "[name].js"
    chunkFilename: "[name].js",
    path: path.resolve(__dirname, "public", "webpack")
  mode: "development"
  optimization:
    splitChunks:
      cacheGroups:
        default: false
        vendor_application:
          name: "vendor_application"
          chunks: (chunk) -> chunk.name == "application"
          test: /[\\/]node_modules[\\/]/
          enforce: true
```

the `application.coffee` looks similar to this here

```coffee
require("@babel/polyfill")
require("intersection-observer")

module.exports =
  jquery: require("jquery")
  odash: require("lodash")
```

**What is the expected behavior?**

The returned object from `application.coffee` should be available with `window.application`.

**Other relevant information:**
webpack version:  4.30.0
Node.js version: 10.15.0
Operating System: Arch Linux

**test repo**

https://github.com/joker-777/webpack-starter

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo

**Comment by joker-777** [comment]
@evilebottnawi Thanks for your response. A test repo you can find [here](https://github.com/joker-777/webpack-starter). 
IMPORTANT: I already figured out why it is happening. We want to load all javascript resources [asynchronously](https://github.com/joker-777/webpack-starter/blob/master/webpack.config.js#L35). If the js resources are loaded synchronously, the library window attribute is actually available.

**Comment by joker-777** [comment]
@evilebottnawi Would be great if you could have a look. Thanks!

**Comment by TheLarkInn** [comment]
@joker-777 Unless you are a Multipage App Architecture, I would recommend not using the `splitChunks` property. Does turning it off work also?

**Comment by joker-777** [comment]
@TheLarkInn Thanks a lot for your answer. Yes, it works without `splitChunks`. Why would you not recommend using it? When exactly do you think one should use `splitChunks`? When is an app for you a Multipage App Architecture?

**Comment by pavanreddy61** [comment]
I am facing the same issue. If we shouldn't use splitChunks, what is the alternative way suggested in webpack v4?

**Comment by joker-777** [comment]
@evilebottnawi Any updates?
@sokra It would be great if you could have a look here as well.

**Comment by gingerlime** [comment]
also curious to hear about this

**Comment by evilebottnawi** [comment]
@joker-777 sorry for big delay, problem still exists?

**Comment by joker-777** [comment]
@evilebottnawi yes, I think so

**Comment by joker-777** [comment]
@evilebottnawi Wait, I just updated my test repo with the latest `webpack` version and it seems to work now. I will keep investigating and let you know later.

**Comment by joker-777** [comment]
@evilebottnawi Nice, it really works. I can't say which update fixes it but it definitely works now.

**Comment by Anand2489** [comment]
@joker-777 What's the webpack version number for which it worked for you?. Could you check & let us know.

I tried with `webpack@4.41.6` but it didn't seem to work.

**Comment by gangstaJS** [comment]
I have the same issue

**Comment by shubhamkes** [comment]
I am also facing the same issue. Using webpack@4.41.2
when not using splitChunks, its works like charm. Can share my config if required. Someone from community please help as I have already wasted my 3 days into it.

**Comment by stejas123** [comment]
I am also facing the issue, when I implement splitchunk, the window object is returning index of my files instead of module

**Comment by continuum-tejas-sathe** [comment]
> @evilebottnawi Wait, I just updated my test repo with the latest `webpack` version and it seems to work now. I will keep investigating and let you know later.

@joker-777 which version you are using

**Comment by rpg-verodin** [comment]
Same issue here. Has anyone found a way around this?

**Comment by evilebottnawi** [comment]
Please update webpack to latest stable verison, if you still have a problem(s), please open new issue with reproducible test repo and we will help

**Comment by rpg-verodin** [comment]
@evilebottnawi The latest stable version as in Webpack 5? I tried the most recent version of Webpack 4 yesterday, and the same issue remains. We are not permitted to use a beta (Webpack 5) in our production environment.

**Comment by evilebottnawi** [comment]
@rpg-verodin webpack@4 is stable, if you have problems, please open a new issue with reproducible test repo

**Comment by rpg-verodin** [comment]
@evilebottnawi I will set up a simple repo as soon as possible.

**Comment by rpg-verodin** [comment]
@evilebottnawi Here's the test repo: https://github.com/rpg-verodin/splitchunks_issue_demo/tree/master

`master` shows the broken scenario, and `working` shows with `splitChunks` excluded where things work as expected.

**Comment by rpg-verodin** [comment]
@evilebottnawi Created a new issue here: https://github.com/webpack/webpack/issues/11152

**Comment by FIGHTING-TOP** [comment]
> @evilebottnawi Nice, it really works. I can't say which update fixes it but it definitely works now. You can close this issue. Thanks.

problem still exists now.  "webpack": "^5.24.2",
