### ISSUE TITLE
code splits broken in uglify build

### ISSUE THREAD

**Issue by acthp** [webpack/webpack#905]
When using code splits + uglify, uglify drops all the split module invocations.

Here's the source:

```javascript
if (document.location.pathname.match(/datapages\/$/)) {
	require.ensure(['datapages'], function () {
		require(['datapages']);
	});
} else if (document.location.pathname.match(/hub\/$/)) {
	require.ensure(['hub'], function () {
		require(['hub']);
	});
...
```

Here's the output of webpack:

```javascript
function(module, exports, __webpack_require__) {

	/*global document: false, require: false, __webpack_public_path__: true */
	'use strict';
	var config = __webpack_require__(1);
	__webpack_require__.p = config.baseurl;
	if (document.location.pathname.match(/datapages\/$/)) {
		__webpack_require__.e/* nsure */(1, function () {
			!/* require */(/* empty */[__webpack_require__(2)]);
		});
	} else if (document.location.pathname.match(/hub\/$/)) {
		__webpack_require__.e/* nsure */(2, function () {
			!/* require */(/* empty */[__webpack_require__(4)]);
		});
	...
```

And here's the uglify:

```javascript
function(t, n, e) {
    "use strict";
    var a = e(1);
    e.p = a.baseurl, document.location.pathname.match(/datapages\/$/) ? 
         e.e(1, function() {}) : document.location.pathname.match(/hub\/$/) ? 
         e.e(2, function() {}) : ...
```

Note that the callbacks are now empty. uglify throws warnings when this happens:

    WARNING in main.js from UglifyJs
    Dropping side-effect-free statement [./js/bogorouter.js:7,2]
    Dropping side-effect-free statement [./js/bogorouter.js:11,2]
    Dropping side-effect-free statement [./js/bogorouter.js:20,2]

Am I writing the splits incorrectly? Do I need to somehow tell uglify that the callbacks are side-effecting?

**Comment by acthp** [comment]
Possibly an uglify bug:

https://github.com/mishoo/UglifyJS2/commit/276b9a31cda2a2ef93e7af4e966baae91a434361

**Comment by acthp** [comment]
Confirmed this is fixed with the uglifyjs2 commit above. Should webpack be updated to depend on the fixed version?

**Comment by acthp** [comment]
A workaround if anyone needs it. The bug appears when doing an async require for side effects. Work-around is to access any property on the returned value, e.g.

```javascript
require(['datapages']).foo;
```

The property doesn't need to exist, it's just there so the AST won't match the uglify pattern that gets deleted.

**Comment by bebraw** [comment]
@acthp Can you give it a go now?
