### ISSUE TITLE
Wrong loaders order when using inline match resource

### ISSUE THREAD

**Issue by malash** [webpack/webpack#9053]
# Bug report

I'v create a repo to reproduce the issue here https://github.com/malash/webpack-inline-match-resource-issue

**What is the current behavior?**

The demo from [inline matchResouce document](https://webpack.js.org/api/loaders/#inline-matchresource) doesn't work.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
git clone https://github.com/malash/webpack-inline-match-resource-issue.git
cd webpack-inline-match-resource-issue
npm i
npm run build
```

**What is the expected behavior?**

The `extract-style-loader/index` convert `file.js` from

```js
/* STYLE: body { background: red; } */
console.log('yep');
```

to

```js
import './file.js.css!=!extract-style-loader/getStyles!./file.js';
console.log('yep');
```

To generate standalone `.css` file I use the `file-loader` to handle it:

```js
// webpack.config.js
module.exports = {
  mode: process.env.NODE_ENV || "development",
  devtool: "none",
  entry: resolve(__dirname, "./file.js"),
  output: {
    path: resolve(__dirname, "dist"),
    filename: "index.js"
  },
  module: {
    rules: [
      {
        test: /\.js/,
        use: [
          {
            loader: require.resolve("./extract-style-loader")
          }
        ]
      },
      {
        test: /\.css/,
        use: [
          {
            loader: "file-loader",
            options: {
              name: "[path][name].css"
            }
          }
        ]
      }
    ]
  }
};
```

It's expected to be:

```
file-loader!extract-style-loader/getStyles!./file.js
```

which means the `extract-style-loader/getStyles` extract a virtual file called `file.js.css` and then passed to the `file-loader`.

but in fact it is:

```
extract-style-loader/getStyles|file-loader!./file.js
```

The `file-loader` will write the original `file.js` to dist and return `module.exports = __webpack_public_path__ + "file.css"` and then the `extract-style-loader/getStyles` failds.

**Other relevant information:**
webpack version:  4.30.0
Node.js version: 11.0.0
Operating System: macOS 10.14.4
Additional tools:

** Related PR

https://github.com/webpack/webpack/pull/7462

**Comment by malash** [comment]
cc: @Jimexist @imyelo

**Comment by malash** [comment]
cc: @sokra @xtuc @yyx990803

**Comment by evilebottnawi** [comment]
PR welcome with fix
