### ISSUE TITLE
Reference to variable declared via spread operator is incorrectly replaced with module reference

### ISSUE THREAD

**Issue by mtlewis** [webpack/webpack#9055]
# Bug report

**What is the current behavior?**
When Webpack replaces module references during bundling, it incorrectly replaces shadowing variables with the same name as an imported module if those variables are declared via the spread operator.

**If the current behavior is a bug, please provide the steps to reproduce.**
[This repro](https://github.com/mtlewis/webpack-spread-issue-minimal-repro) reproduces the issue. In short, the following code is bundled incorrectly:

```javascript
import A from './a';

function go() {
  const { first, ...A } = {
    first: 'the first',
    greeting: 'hello world!'
  };

  console.log(A); // should be { greeting: 'hello world!' }, but after 
                  // bundling, the "A" on this line is replaced with the module
                  // identifier for the imported module at the top.
};
```

**What is the expected behavior?**
After the variable A is declared, subsequent references to it shouldn't be replaced with the module identifier.

**Other relevant information:**
I ran into this when bundling minified code - it seems possible that this could occur fairly often, given that minified code will make use of variable shadowing to maximise use of single-character identifiers.

webpack version: 4.30.0  
Node.js version: v8.12.0
Operating System: macOS Mojave

**Comment by evilebottnawi** [comment]
Yep bug, feel free to send a PR, thanks for issue
