### ISSUE TITLE
devServer open: 'chrome'

### ISSUE THREAD

**Issue by twickstrom** [webpack/webpack#9056]
# Bug report

**What is the current behavior?**
I am on macOS with Safari as my default browser. I am attempting to open Google Chrome with the following in my webpack config:

```
devServer: {
    open: 'chrome'
}
```

This only works is chrome is already open on my Mac. If all browsers are closed it will open Safari if Chrome is open it will open the build in Chrome.

I have also tried
```
devServer: {
    open: 'Google Chrome'
}
```
**If the current behavior is a bug, please provide the steps to reproduce.**

1. Using macOs set your default browser to Safari.
2. Make sure you have Google Chrome installed.
3. Add the following to your webpack config:

```
devServer: {
    open: 'chrome'
}
```

While all browsers are closed run a dev build of your code. Safari opens.

Then

Open Chrome and Safari and rerun your build, chrome opens.

**What is the expected behavior?**
If Chrome is installed, it should open chrome if it is closed.

**Other relevant information:**
webpack version:  6.9.0
Node.js version: 10.15.1
Operating System: MacOS 10.14.4
Additional tools:

**Comment by evilebottnawi** [comment]
It is `os` limitations, please read https://github.com/sindresorhus/open#app, we can't do something on our side, maybe you can open issue in https://github.com/sindresorhus/open repo
