### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by calebjanderson** [webpack/webpack#9058]
# Bug report

**What is the current behavior?**

Construction of webpack compilation instance throws TypeError.

**If the current behavior is a bug, please provide the steps to reproduce.**

From WSL with node installed
```
$ mkdir test
$ cd test
$ npm init -y
$ npm i webpack
$ touch index.js
$ cat > index.js
const webpack = require('webpack');

const compiler = new webpack.Compiler();
^D
$ node index.js
/mnt/c/Users/path/to/test/node_modules/webpack/lib/RequestShortener.js:16
        return request.replace(NORMALIZE_SLASH_DIRECTION_REGEXP, "/");
                       ^

TypeError: Cannot read property 'replace' of undefined
```

**What is the expected behavior?**

Calling `new webpack.Compiler()` should result in creation of webpack Compiler instance and not throw TypeError. 

**Other relevant information:**
webpack version: v4.30.0
Node.js version: v10.11.0
Operating System: Windows 10 Home Version 1809
Additional tools: Windows Subsytem for Linux Ubuntu 18.04

**Comment by evilebottnawi** [comment]
Please provide minimum reproducible tst repo

**Comment by sokra** [comment]
The `Compiler` constructor has an argument. Provide it.

But the better question is: Why do you want to instanciate a Compiler? Why not using the webpack node API: `webpack(options)` which returns a `Compiler`?

**Comment by calebjanderson** [comment]
Webpack documentation for [compiler hooks](https://webpack.js.org/api/compiler-hooks/) links to [this example](https://github.com/pksjce/webpack-internal-examples/tree/master/compiler-example) implementation. The example uses webpack version `^2.1.0-beta.25` and is not compatible with webpack v4.30.0. The version discrepancy was root cause of issue.
