### ISSUE TITLE
`ReferenceError` on circular dependencies with ES2015 `let`

### ISSUE THREAD

**Issue by filipesilva** [webpack/webpack#9060]
# Bug report

**What is the current behavior?**
When using `export let` and circular dependencies, runtime will have `ReferenceError` errors.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
git clone https://github.com/filipesilva/webpack-let-export
cd webpack-let-export
yarn
yarn test
```

This repository contains only three source files:
```
// ./src/index.js
import { ModuleOne } from './module-one';
import { ModuleTwo } from './module-two';

console.log(ModuleOne);
console.log(ModuleTwo);
```
```
// ./src/module-one.js
import { ModuleTwo } from './module-two';
export let ModuleOne = 'ModuleOne';
console.log(ModuleTwo);
```
```
// ./src/module-two.js
import { ModuleOne } from './module-one';
export let ModuleTwo = 'ModuleTwo';
console.log(ModuleOne);
```

Running `webpack-cli --mode development --devtool source-map` will produce a bundle at `dist/main.js` that can be ran but will error:

```
$ node dist/main.js
D:\sandbox\webpack-let-export\dist\main.js:117
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ModuleOne", function() { return ModuleOne; });
                                                                                                    ^

ReferenceError: ModuleOne is not defined
    at Module.ModuleOne (D:\sandbox\webpack-let-export\dist\main.js:117:101)
    at Module../src/module-two.js (D:\sandbox\webpack-let-export\dist\main.js:138:53)
    at __webpack_require__ (D:\sandbox\webpack-let-export\dist\main.js:20:30)
    at Module../src/module-one.js (D:\sandbox\webpack-let-export\dist\main.js:118:69)
    at __webpack_require__ (D:\sandbox\webpack-let-export\dist\main.js:20:30)
    at Module../src/index.js (D:\sandbox\webpack-let-export\dist\main.js:98:69)
    at __webpack_require__ (D:\sandbox\webpack-let-export\dist\main.js:20:30)
    at D:\sandbox\webpack-let-export\dist\main.js:84:18
    at Object.<anonymous> (D:\sandbox\webpack-let-export\dist\main.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
```

Inside `dist/main.js` we can find the following code:
```
/*!***************************!*\
  !*** ./src/module-one.js ***!
  \***************************/
/*! exports provided: ModuleOne */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ModuleOne", function() { return ModuleOne; });
/* harmony import */ var _module_two__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./module-two */ "./src/module-two.js");

let ModuleOne = 'ModuleOne';
console.log(_module_two__WEBPACK_IMPORTED_MODULE_0__["ModuleTwo"]);

/***/ }),
```

The important part is that `ModuleOne` is declared using `let`, but Webpack adds the `/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ModuleOne", function() { return ModuleOne; });` export before the declaration.

Since `let` statements are subject to the [temporal dead zone](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#Temporal_dead_zone), we get a `Reference error` when using the Webpack export.

This can be worked around by not using `let`. But a better fix would be for webpack exports to not reference variables before they are declared.

If you manually edit `dist/main.js` to have the exports after the declaration, the errors will not occur.
```
/*!***************************!*\
  !*** ./src/module-one.js ***!
  \***************************/
/*! exports provided: ModuleOne */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var _module_two__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./module-two */ "./src/module-two.js");

let ModuleOne = 'ModuleOne';
console.log(_module_two__WEBPACK_IMPORTED_MODULE_0__["ModuleTwo"]);

// ### Move this statement on both module-one and module-two ###
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ModuleOne", function() { return ModuleOne; });
/***/ }),
```
```
$ node dist/main.js
undefined
ModuleTwo
ModuleOne
ModuleTwo
```

**What is the expected behavior?**
No runtime errors.

**Other relevant information:**
webpack version:  4.30.0
Node.js version: v10.10.0
Operating System: Windows
Additional tools: none

**Comment by sokra** [comment]
This is working as intended. With circular dependencies you get TDZ errors.

It's similar to the errors you get in this code:

``` js
let ModuleTwo = 'ModuleTwo';
console.log(ModuleOne);
let ModuleOne = 'ModuleOne';
console.log(ModuleTwo);
```

**Comment by filipesilva** [comment]
Hi @sokra, thank you for looking at this. You're completely right. 

This is expected behaviour with circular dependencies and `let`/`class` (both suffer from TDZ). I also tried Rollup and Chrome with individual ES modules and they both behave the same as you describe.

**Comment by chriszrc** [comment]
So what's the answer here though, if we have classes that have circular dependencies? I've got typeorm entities that model database tables, and I don't see any way to not have the classes reference each other :(

**Comment by RobbieGM** [comment]
> So what's the answer here though, if we have classes that have circular dependencies? I've got typeorm entities that model database tables, and I don't see any way to not have the classes reference each other :(

@chriszrc I also use TypeORM and solved this problem by following this guide https://medium.com/visual-development/how-to-fix-nasty-circular-dependency-issues-once-and-for-all-in-javascript-typescript-a04c987cf0de and making sure to put my exports in the global export file in the order of superclasses first, subclasses last. The `@Column(type => Whatever)` shouldn't be a problem because the reference to `Whatever` is deferred. For me, the inheritance was where circular dependencies became a problem. Feel free to ask me if you have any questions.

**Comment by adamdport** [comment]
@RobbieGM thanks for that link, the diagrams in there were very helpful in understanding what's going on. That being said, his solution of the "internal module" ("global export file" as you call it) seems like it would make treeshaking impossible no? I'm curious if your refactor has the potential to increase bundle size. 

btw for anyone arriving here from the web looking for a quick and dirty solution, it looks like circular dependencies work fine if you target `es5` where hoisting is allowed.

**Comment by RobbieGM** [comment]
I'm not sure, you may want to test whether or not tree shaking still works. In my case I'm using webpack server side (with Next.js) so bundle size is a non-issue.
