### ISSUE TITLE
Webpack error with node 12

### ISSUE THREAD

**Issue by icezeko** [webpack/webpack#9064]
I updated my nodejs version on my machine to node 12.0 and when i run (npm run dev) to start my project i get a: 
ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! exiles@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the exiles@1.0.0 dev script.

The log file [log](https://pastebin.com/NPduWFPJ)

Is this a problem with node 12 ?

**Other relevant information:**
webpack version:  ^3.6.0
Node.js version: v12.0.0
Operating System: Windows 10

**Comment by evilebottnawi** [comment]
Problem in webpack-dev-server
