### ISSUE TITLE
Extra tiny chunk created when transitively dynamically importing a module that shadows Node builtin

### ISSUE THREAD

**Issue by captbaritone** [webpack/webpack#9067]
# Bug report

Creating a dynamic `import()` which either directly or transitively includes a module named `stream` results in an extra, tiny, chunk being generated.

**What is the current behavior?**

An extra chunk (`2.js`) is created:

```
╭─[16:06]: jordaneldredge at Jordans-MBP in ~/projects/stream-bug on master
╰─➤ yarn run build
yarn run v1.15.2
warning package.json: No license field
$ webpack
Hash: 2f6b544f06a325bb53cd
Version: webpack 4.30.0
Time: 1553ms
Built at: 04/25/2019 4:07:52 PM
    Asset      Size  Chunks             Chunk Names
     1.js    62 KiB       1  [emitted]
     2.js  98 bytes       2  [emitted]
webamp.js  2.03 KiB       0  [emitted]  webamp
Entrypoint webamp = webamp.js
 [0] multi ./index.js 28 bytes {0} [built]
 [1] ./index.js 17 bytes {0} [built]
 [5] (webpack)/buildin/global.js 472 bytes {1} [built]
[22] util (ignored) 15 bytes {2} [built]
[24] util (ignored) 15 bytes {2} [built]
    + 28 hidden modules
✨  Done in 2.57s.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Clone `https://github.com/captbaritone/webpack-node-import-bug`
2. cd into repo
3. `yarn`
4. `yarn build`

**What is the expected behavior?**

Only one chunk file.

**Other relevant information:**
webpack version:  "webpack": "^4.30.0", "webpack-cli": "^3.3.1
Node.js version: v11.10.1
Operating System: Mac

Setting `"node": false` in my config resolves this issue, but causes other ones.

I hit this in [Webamp](https://github.com/captbaritone/webamp) trying to lazy load https://www.npmjs.com/package/music-metadata-browser and https://github.com/Stuk/jszip since they both transitively depend upon `stream`. Music-metadata-browser is actually supplying it's own package [`stream`](https://www.npmjs.com/package/stream) which is browser safe but shadows the Node version.

So, a secondary question is: Is it expected that referencing a Node built in that is shadowed in `node_modules` results in getting the `NodeStuffPlugin` version?

**Comment by TheLarkInn** [comment]
@captbaritone Have you tried setting just 

```
node: {
   stream: false
}
```
?

**Comment by TheLarkInn** [comment]
@sokra is the empty chunk technically a bug?

**Comment by captbaritone** [comment]
@TheLarkInn I've confirmed that `node: { stream: false }` behaves the same as `node: false` and allows me to sidestep the issue in this specific case.

**Comment by sokra** [comment]
Yeah that's a bug in the SplitChunksPlugin when having a chunk with minimal app code and much vendor code.

**Comment by alexander-akait** [comment]
Fixed in webpack@5
