### ISSUE TITLE
vue项目build时候报内存溢出, 仅少数电脑出现这种情况, 同一个项目, 网上各种方法没法解决

### ISSUE THREAD

**Issue by a15218378694** [webpack/webpack#9068]
![Snipaste_2019-04-26_13-36-55](https://user-images.githubusercontent.com/29919045/56785586-79071a80-6828-11e9-86e3-b36c56122fe1.png)
![Snipaste_2019-04-26_13-37-21](https://user-images.githubusercontent.com/29919045/56785587-79071a80-6828-11e9-8e69-00636a89c91c.png)

**Comment by montogeek** [comment]
Please use English, that error is a RAM limit error.
