### ISSUE TITLE
Webpack crash on nodejs@12

### ISSUE THREAD

**Issue by joshuan** [webpack/webpack#9070]
# Bug report

**What is the current behavior?**

If use nodejs@12, webpack crash with error:

```
MacBook:~/www/$ webpack


#
# Fatal error in , line 0
# Check failed: U_SUCCESS(status).
#
#
#
#FailureMessage Object: 0x7ffeefbf4fc0Illegal instruction: 4
MacBook:~/www/
```

**If the current behavior is a bug, please provide the steps to reproduce.**

- `nvm use 12`
- `npm i webpack webpack-cli`
- `./node_modules/.bin/webpack`

**What is the expected behavior?**

Any, at least run

**Other relevant information:**
webpack version: 4.X.X and 5.X.X-alpha.X
Node.js version: 12.0.0
Operating System: Mac OS X
Additional tools: nvm

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by Zazck** [comment]
same issue here, when running an Aurelia project with `au run --watch`
it shows
`#
# Fatal error in , line 0
# Check failed: U_SUCCESS(status).
#
#
#
#FailureMessage Object: 00000090F37ADDC0`
the node version is
`node --version
v12.0.0`
so the example maybe just create a new aurelia project

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by joshuan** [comment]
@montogeek for reproduce issue you not need project. Just go this code: 
```cd /tmp && npm i webpack webpack-cli && ./node_modules/.bin/webpack```
it is only important - node.js version: 12.0.0

**Comment by junjie-lean** [comment]
我也发现了这个问题，webpack-dev-server在nodev12的环境下不能要运行。而vue-cli和Create-react-app都是用到了这个包。目前我的解决办法是把node环境降级到v11.5

**Comment by evilebottnawi** [comment]
I think problem in webpack-dev-server, please create minimum reproducible test repo

**Comment by axed** [comment]
I am getting the same result, taking the reproducing steps that OP provided. Any create-react-app that is based on webpack is now broken with node 12.0.0.

**Comment by hiroppy** [comment]
Currently, this problem does not occur in Node12.1.0 so I'll close.

> cd /tmp && npm i webpack webpack-cli && ./node_modules/.bin/webpack

**Comment by AlexTeixeira** [comment]
I confirm, updating to node 12.1.0 fix the issue.
