### ISSUE TITLE
Is it correct to use NamedChunkPlugin in production?

### ISSUE THREAD

**Issue by DJAlejandro** [webpack/webpack#9072]
I know the difference between HashedModuleIdsPlugin and NamedModulesPlugin .But What about NamedChunkPlugin.Is it correct to use NamedChunkPlugin in production?

**Comment by DJAlejandro** [comment]
```
module.exports = {
+ mode: 'development'
...
- optimization: {
-   namedModules: true,
-   namedChunks: true,
-   nodeEnv: 'development',
-   flagIncludedChunks: false,
-   occurrenceOrder: false,
-   sideEffects: false, //禁用tree shaking
-   usedExports: false, //禁用tree shaking
-   concatenateModules: false,
-   splitChunks: { //提取公共代码块
-     hidePathInfo: false,
-     minSize: 10000,
-     maxAsyncRequests: Infinity,
-     maxInitialRequests: Infinity,
-   },
...
- plugins: [
-   new webpack.NamedModulesPlugin(),
-   new webpack.NamedChunksPlugin(),
-   new webpack.DefinePlugin({ "process.env.NODE_ENV": JSON.stringify("development") }),
- ]
}
```

 If setting namedModules:true, namedChunks: true, moduleIds:hashed.Do I need NamedModulesPlugin, NamedChunksPlugin, HashedModuleIdsPlugin anymore???

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Yes it is normal to use this plugin, please use gitter or stackoverflow in future for questions, thanks
