### ISSUE TITLE
webpackChunkName: "[request]" only works with context dependencies

### ISSUE THREAD

**Issue by filipesilva** [webpack/webpack#9075]
# Bug report

**What is the current behavior?**
Using `webpackChunkName: "[request]"` on `import` only works if the request is a context dependency (one with a variable name).

**If the current behavior is a bug, please provide the steps to reproduce.**
- 
- create empty `src/lazy.js`
- create `src/index.js` with `import(/* webpackChunkName: "[request]" */ './lazy');`
- run `npx webpack-cli`:
```
Hash: 269240453362ab386250
Version: webpack 4.30.0
Time: 367ms
Built at: 04/29/2019 4:22:09 PM
       Asset      Size  Chunks             Chunk Names
[request].js  77 bytes       0  [emitted]  [request]
     main.js  1.99 KiB       1  [emitted]  main
```
- notice imported chunk is called `[request].js`
- replace `src/index.js` with `import(/* webpackChunkName: "[request]" */ './lazy' + globalVar);`
- run `npx webpack-cli`:
```
Hash: 729fe5220ba2d900b7ec
Version: webpack 4.30.0
Time: 653ms
Built at: 04/29/2019 4:21:09 PM
  Asset      Size  Chunks             Chunk Names
lazy.js  76 bytes       0  [emitted]  lazy
main.js  2.31 KiB       1  [emitted]  main
```
- notice imported chunk is called `lazy.js`

**What is the expected behavior?**
I expected both builds to create an important chunk with the name of the request.

If this isn't supposed to work by design, it should be mentioned in https://webpack.js.org/api/module-methods/#magic-comments.

**Other relevant information:**
webpack version:  4.30.0
Node.js version: v10.10.0
Operating System: Windows
Additional tools:

**Comment by sokra** [comment]
`[request]` is intended for cases were the name should depend on a variable expression.

In case of `import(/* webpackChunkName: "[request]" */ './lazy')` you can put the text into the comment to: `import(/* webpackChunkName: "lazy" */ './lazy')`. There is no need to use `[request]`.

**Comment by filipesilva** [comment]
Yes, I understand I could always put the name directly. I just thought I would also be able to use `[request]` on all the lazy imports so that they would default to using the request name. If it's truly not intended to work, then this isn't a bug. Perhaps missing documentation instead.
