### ISSUE TITLE
Follow-up on still needing to use require.ensure

### ISSUE THREAD

**Issue by noahgrant** [webpack/webpack#9076]
## Feature request

**What is the expected behavior?**/**What is motivation or use case for adding/changing the behavior?**

Awhile back I created an issue trying to make a case for [keeping around `require.ensure`](https://github.com/webpack/webpack/issues/5909), which I knew would get deprecated as `import()` was adopted. But the two are not interchangeable, and I'd like either to add webpack-specific shimming for `import()` or to keep around `require.ensure`.

**To recap their differences**: `require.ensure` only fetches the dependency scripts but does not install any individual module; `import()` fetches dependency scripts _and_ installs the individual module.

There are two specific issues I have, one of which will actually prevent us from upgrading to any version of webpack that doesn't have equivalent functionality:

1. A critical way that we know if a chunk is out-of-date (ie, a chunk with a new hash has been deployed in its place) is that the request 404s. So someone might be on our page with with entry file `-12345.js` and they click on a link to go to a new page, which fetches the related `page-54321.js`. if, before they click, we've deployed a new entry file, `-23456.js` (and accordingly, a new `page-65432.js`), the 404 they see when trying to fetch `page-54321.js` is critical in knowing that we should reload the page and get the freshest js files.

    With `require.ensure`, we _know_ that the error handler is responding to a request error, and we can handle it appropriately. With `import()`, the error may be from a request or from an error in the loaded module execution itself, and we don't know. It's hard for me to believe that [string-matching against the error message](https://github.com/webpack/webpack/issues/5909#issuecomment-341988046) is a good solution here.

2. An even bigger issue, and the one that will prevent us from upgrading, is that because `import()` also loads in the modules, there's no way to dynamically preload our chunks. `/* webpackPreload: true */` doesn't do us any good because we don't put hardcoded `<link rel='preload' />` tags in our markup—we dynamically preload a chunk that we know we'll need based on the url (which we know, of course, very early). Because we can't split up dependency loading and module installation, what we get as a result is double-module execution—once during our dependency preloading, and again when we actually intend to install the module. This leaves us vulnerable to unintended consequences.

In our case, something about d3 didn't like being executed twice and was erroring in Safari only (and this error, per number 1 above, goes into the same callback as any request errors).

**How should this be implemented in your opinion?**
I would ultimately like to see either:

1. `require.ensure` kept around
2. `/* webpackPreload: true */` magic comments implement current `require.ensure` functionality, loading in dependencies but not installing modules.

**Are you willing to work on this yourself?**
I could try!

Thank you all for your time!!

**Comment by sokra** [comment]
* There is no intent to remove `require.ensure`. It's not deprecated, it's only recommended to use `import()` over `require.ensure` because it's part of the ESM spec.
* We can add a magic comment to not evaluate the module (so only load the chunk). Maybe `/* webpackLoad: true | "prefetch" | "preload" */`. This was requested by somebody else before.
* double-module execution: Modules will never evaluate multiple times, even if you call `import()` multiple times. They are cached.

**Comment by noahgrant** [comment]
Thanks for time.

* I was going based on [this webpack v5 doc](https://github.com/webpack/changelog-v5/blob/master/README.md#other-minor-changes) that had this line, but maybe I'm mistaken on what that was referencing:

![image](https://user-images.githubusercontent.com/1355779/57384535-ab3c4480-7165-11e9-850f-0f4a52cc8482.png)

* That sounds good. but what's the difference between `prefetch` and `preload` here?

* Ahh, right, of course they're cached. The issue, then, might be that a code split is executing before it should—either that or there's a bug in the way Safari is caching them. Either way, what we were seeing was that it's currently not idempotent.

Finally, any other thoughts about conflating errors?

**Comment by evilebottnawi** [comment]
> I was going based on this webpack v5 doc that had this line, but maybe I'm mistaken on what that was referencing:

Hook was removed only

> That sounds good. but what's the difference between prefetch and preload here?

https://www.keycdn.com/blog/resource-hints

**Comment by noahgrant** [comment]
Oh yeah, I know the differences between preload and prefetch link tags, but you [already provide webpackPrefetch and webpackPreload magic comments](https://webpack.js.org/api/module-methods/#magic-comments). So my question was, in this context specifically, what would `webpackLoad: 'prefetch'` mean?

**Comment by sokra** [comment]
`webpackLoad: true` webpack would load the chunk with a `<script>` tag (normal priority)
`webpackLoad: "preload"` webpack would load the chunk with a `<link rel="preload">` tag (normal priority, but browser can choose to ignore it, i. e. when using a limited data plan)
`webpackLoad: "prefetch"` webpack would load the chunk with a `<link rel="prefetch">` tag (idle priority and browser can choose to ignore it)
