### ISSUE TITLE
Github issues are a mess

### ISSUE THREAD

**Issue by JonDum** [webpack/webpack#908]
I'm seeing way too many "How do I do X" questions in here.

Should we make a push to use StackOverflow to offset the influx of these questions to keep Github issues more clear for actual bugs and issues?

I think linking to the SO 'webpack' [tag](http://stackoverflow.com/questions/tagged/webpack) on the [main documentation page](http://webpack.github.io/docs/) and prominently in the readme might do the trick, no?

**Comment by JonDum** [comment]
Adopting a tagging system might be a nice idea too, to keep everything organized. It's too much work for just Sokra to do. Any volunteers for moderators? :D

**Comment by acthp** [comment]
or a google group? I expect users resort to github issues because gitter is such a fail: no threading; no useful search; slim chance a question will even be noticed, and good luck finding the response if it is.

**Comment by jhnns** [comment]
> I'm seeing way too many "How do I do X" questions in here.

You're right. I like the idea of linking the SO tag. Also, SO questions are usually better discovered by Google than Github issues.

One problem is that there is a lot of complexity coming from the fact that there is no "one true way" of JS or even web modules. And these issues arise particularly when webpack is used to unify all the different styles.

**Comment by JonDum** [comment]
> One problem is that there is a lot of complexity coming from the fact that there is no "one true way" of JS or even web modules. And these issues arise particularly when webpack is used to unify all the different styles.

All the more reason to put these questions on SO where they're more likely to get attention. SO points can actually be valuable (bounties), so devs are far more likely to pay attention there. 

Most important thing though is that this @sokra doesn't have to spend brain power on these types of questions that we can help him with. :)

I'll form a PR in a bit changing the docs page / readme. Is there already a mailing list/chat room we want to use too or are those dead?

**Comment by sokra** [comment]
:+1:

> Is there already a mailing list/chat room we want to use too or are those dead?

No mailing list.
Chat room: https://gitter.im/webpack/webpack

**Comment by jhnns** [comment]
> I'll form a PR in a bit changing the docs page / readme.

:+1: 

We probably also should use Github's [CONTRIBUTING.md feature](https://github.com/blog/1184-contributing-guidelines)

**Comment by JonDum** [comment]
@jhnns Oooh that is fantastic. Hadn't seen that yet.

**Comment by hkal** [comment]
Nice work getting this pull request opened, @JonDum.

I'm available to help triage issues if the need arises. However, I'm still not comfortable enough with the code to contribute meaningfully in that regard, though.

**Comment by sokra** [comment]
merged
