### ISSUE TITLE
how to make main.js to load chunk files with relative path (in same folder)

### ISSUE THREAD

**Issue by qiuzuhui** [webpack/webpack#9081]
I'm trying to use webpack to build a library which use for many project for my team. it build the files include main.js and chunk files in a folder. but when i copy it to a sub folder of other server. and after loading main.js , it can't found the chunk files.  according the code in "jsonScripSrc" it load chunk files from the root.

my proposal is load chunk files from the same folder of main.js. is there to do it (without limit the path put the library).

**Comment by qiuzuhui** [comment]
currently i override the jsonpScrptSrc function with 
`return __webpack_require__.p + document.currentScript.src+ "/../" + ({}[chunkId]||chunkId) + ".js"`
it's a hacking way , and i need know if there some good way for it ?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
