### ISSUE TITLE
compiler.hooks.emit get called when I return true in the needAdditionalPass at this first time

### ISSUE THREAD

**Issue by wood1986** [webpack/webpack#9082]
# Bug report

**What is the current behavior?**
`compiler.hooks.emit` get called when needAdditionalPass return true at this first time

```js
compiler.hooks.emit.tapAsync(this.constructor.name, (compilation, callback) => {
  console.log("emit");
  callback();
});

compiler.hooks.afterCompile.tapAsync(this.constructor.name, (compilation, callback) => {
  compilation.hooks.needAdditionalPass.tap(this.constructor.name, () => manifest === null);
  callback();
});

compiler.hooks.additionalPass.tapAsync(this.constructor.name, (callback) => {
  emitter.on("invalid", () => {
    injectCount = 0;
    callback();
  });
});
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I would expect if needAdditionalPass return true, it should not emit. Is it by design?

**Other relevant information:**
webpack version:  4.30
Node.js version: 11.14.0
Operating System: macOS 10.14.4
Additional tools:

**Comment by evilebottnawi** [comment]
It is by design on emit event some plugins can add other assets
