### ISSUE TITLE
webpack4 high CPU usage of dev-server on win10 system when server is idle even on "watch: false"

### ISSUE THREAD

**Issue by harrybin** [webpack/webpack#9085]
**Do you want to request a *feature* or report a *bug*?**
--> *bug*

**What is the current behavior?**
Using the latest versions of webpack and dev-server causes the dev-server to have high CPU usage in any case.

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a project using create-react-scripts, usage some material-ui components and the datagrid devextreme. (not sure if later two UI libs are really needed for the repro)
When starting the dev-server in my case it needs about 90s to complete.
Now wait some further time until there is only one node.exe process left, the dev-server process.
This process uses about 60% of my overall CPU (4xi5 cores).

**What is the expected behavior?**
When the server has nothing to do (even watch: false is set), there should not be that much CPU load. 

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
"webpack": "4.30.0",  
"webpack-dev-server": "3.3.1"
node version: tried several versions 10.15.3, 12.1.0...
Windows 10 (1809) 

Having a look at the node.exe process using procexp, you can see that there are four threads permanently polling script sources upon an fs_event. (see screeshot)
![image](https://user-images.githubusercontent.com/15869006/57122269-cd585000-6d7c-11e9-9606-5b4814b24b15.png)

I tried several settings in various combinations:
- watchOptions (poll: 2000, ignored.... etc.)
- watch: false
- hot: false
- thread-loader
- happypack
- removing all plugins and loaders possible when removing some code
nothing changed anything.

---
Further investigation shows that the dev-server seems load @material-ui/icons/*.d.ts again and again, although they are located in node_modules which is excluded.
--> I was not able to prevend the dev-server from excluding node_modules folder with any exclude, ignore or plugin.

[webpackDevServer.config.js.txt](https://github.com/webpack/webpack/files/3146575/webpackDevServer.config.js.txt)
[webpack.base.js.txt](https://github.com/webpack/webpack/files/3146576/webpack.base.js.txt)
[webpack.config.dev.js.txt](https://github.com/webpack/webpack/files/3146577/webpack.config.dev.js.txt)

**Comment by bjyoungblood** [comment]
I was also experiencing this exact same problem on macOS after having recently upgraded from Node 11 to 12. I was able to fix it by forcing a rebuild (`npm rebuild` or `yarn --force`). Deleting node_modules and reinstalling should have the same effect.

**Comment by harrybin** [comment]
@bjyoungblood thanks for your hint. I completely deleted the node_modules folder and installed again.
No change. The dev server still watches all d.ts files within the node_modules folder and causes 60% CPU.

**Comment by evilebottnawi** [comment]
Please open issue in `webpack-dev-server` with reproducible test repo
