### ISSUE TITLE
Unable to use SplitChunksPlugin in a child compilation

### ISSUE THREAD

**Issue by jeffposnick** [webpack/webpack#9088]
# Bug report

CC: @prateekbh

**What is the current behavior?**
I am creating a child compilation inside of a custom webpack plugin.

In that compilation, I'd like the entry (which is created via `SingleEntryPlugin`) to have the optimizations that `SplitChunksPlugin` performs applied to it.

However, the `optimization.splitChunks` settings from the parent compilation is not carried over to the child (which maybe is expected—it's not clear to me what is supposed to be carried over or not).

More to the point, I'm not able to manually create an instance of `SplitChunksPlugin` and apply it to the child compilation. When I try to do that, it doesn't accomplish anything or seemingly change the output.

**If the current behavior is a bug, please provide the steps to reproduce.**

I have a "live" example of this not working as expected at https://glitch.com/edit/#!/webpack-child-compilation-split-chunks?path=README.md:1:0

The minimal reproduction of my plugin that performs the child compilation, in which `SplitChunksPlugin` does nothing, is excerpted below:

```
  apply(parentCompiler) {
    const name = this.constructor.name;

    parentCompiler.hooks.make.tapPromise(name, async (compilation) => {
      const outputOptions = {
        path: parentCompiler.options.output.path,
        filename: this.file,
      };

      const childCompiler = compilation.createChildCompiler(name, outputOptions);

      childCompiler.context = parentCompiler.context;
      childCompiler.inputFileSystem = parentCompiler.inputFileSystem;
      childCompiler.outputFileSystem = parentCompiler.outputFileSystem;
      
      new SingleEntryPlugin(
          childCompiler.context,
          './' + this.file,
          'Child Compilation',
      ).apply(childCompiler);
      
      // This unfortunately doesn't seem to do anything.
      const splitChunksPlugin = new SplitChunksPlugin({
        chunks: 'all',
      });
      splitChunksPlugin.apply(childCompiler);

      // Not sure if this is necessary, but it seems to match
      // https://github.com/webpack/webpack/blob/9f0056b10d6997fd8e1472fec4b8c84b5d6b1db7/lib/WebpackOptionsApply.js#L419
      new NaturalChunkOrderPlugin().apply(childCompiler);

      await new Promise((resolve, reject) => {
        childCompiler.runAsChild((error, entries, childCompilation) => {
          if (error) {
            reject(error);
          } else {
            compilation.warnings = compilation.warnings.concat(childCompilation.warnings);
            compilation.errors = compilation.errors.concat(childCompilation.errors);

            resolve();
          }
        });
      });
    });
  }
```

**What is the expected behavior?**

I would expect to be able to manually create an instance of `SplitChunksPlugin` and apply it to a child compilation, and have that compilation split off vendor chunks like when happens in the parent compilation.

**Other relevant information:**
webpack version:  4.30.0
Node.js version: 8
Operating System: n/a 
Additional tools:

**Comment by jeffposnick** [comment]
@prateekbh, who's looked into similar issues in the past, came up with the following config for a manually created `SplitChunksPlugin` which appears to have some effect. (I need to tweak it a bit, but at least it is spitting out a new chunk.)

```
new SplitChunksPlugin({
  cacheGroups: {
  vendor: {
    test: new RegExp(
      `[\\/]node_modules[\\/]`
    ),
    chunks: "initial",
    name: "vendors-another",
    enforce: true
  }
 }
}).apply(childCompiler);
```

I'm not sure why `chunks: 'all'` wasn't sufficient, though. Maybe someone from the webpack core team has some thoughts there, and if anything, this issue could be used to keep track of the need to provide an example along those lines in the docs.

**Comment by sokra** [comment]
The default cache groups only apply to the root compilation. You need to specify cacheGroups when using the SplitChunksPlugin manually.

`optimization.splitChunks` and the plugin do not carry over to child compilations.

**Comment by jeffposnick** [comment]
Thanks for the confirmation—it would be lovely to get some more "official" documentation around child compilations ([this unofficial writeup](https://medium.com/@prateekbh/my-experience-writing-a-webpacks-child-compiler-plugin-a1237c175947) by Prateek was my best jumping-off point), but I think this issue is resolved.
