### ISSUE TITLE
HMR not working with copy file

### ISSUE THREAD

**Issue by apiel** [webpack/webpack#9092]
I am using a nodejs script to write source code files in "src" folder. Unfortunatelly HMR doesn't work very well with those files, sometime it detect the change, sometime not.

For that I am using `copy` from `fs-extra`. I tried as well with `readFile` and `outputFile`. What would be the right way to write in the src folder with nodejs and to get properly detected by HMR?

(I wonder if this would not be related to the "safe write" issue)

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

hmr use memory and you can't use `fs`, please use stackoverflow or gitter for questions
