### ISSUE TITLE
about Dynamic Load

### ISSUE THREAD

**Issue by zhuqingsong59** [webpack/webpack#9093]
i want to do Dynamic Load in webpack4,but faild
![image](https://user-images.githubusercontent.com/13329506/57215618-06fcb580-7020-11e9-9b93-0a5838955e1b.png)
![image](https://user-images.githubusercontent.com/13329506/57215652-2562b100-7020-11e9-89f9-1a109a7ed265.png)
it means i can not use 'require.ensure' like this way?
webpack: v4.30.0
babel-core: v6.22.1
vue-cli: v2.9.6

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please use gitter or stackoverflow for questions
