### ISSUE TITLE
Webpack seems to add non-ES5 compliant syntax to generated bundle

### ISSUE THREAD

**Issue by jackyef** [webpack/webpack#9095]
# Bug report

**What is the current behavior?**
On some of the generated chunks, we found that webpack added this snippet to them.
```
function n(r) {
    if (t[r]) return t[r].exports;
    var o = (t[r] = { i: r, l: !1, exports: {} });
    return e[r].call(o.exports, o, o.exports, n), (o.l = !0), o.exports;
}
```

In other generated chunks, we found that webpack added similar snippets to them, but with different variable
```
function n(i) {
    if (e[i]) return e[i].exports;
    var o = (e[i] = { i, l: !1, exports: {} });
    return t[i].call(o.exports, o, o.exports, n), (o.l = !0), o.exports;
}
```

Notice that the function is exactly the same, other than the different args used (`i` instead of `r`).

On the 2nd line of the 2nd function, we see that webpack is using shorthand object property because the argument variable is named `i`. 

```
var o = (e[i] = { i, l: !1, exports: {} });
```

This causes error in production because the syntax is not recognised on older browsers such as Chrome 41, which is the engine used by GoogleBot when crawling sites.

We have added `babel-loader` to transpile our codes, which contains usage of a lot of non ES5 syntaxes such as shorthand object property, and they have been transpiled correctly, so we suspect that this is a problem with webpack itself. 

**If the current behavior is a bug, please provide the steps to reproduce.**
-- to be provided --

**What is the expected behavior?**
No non-ES5 compliant syntax in the generated bundles.

**Other relevant information:**
webpack version:  4.29.6
Node.js version: 10.14.1
Operating System: macOS 10.14.3

**Comment by evilebottnawi** [comment]
Looks it is problem with minimizer, not webpack, please provide minimum reproducible test repo

**Comment by jackyef** [comment]
My bad, it was indeed a problem with the minimizer used. Closing this PR.
