### ISSUE TITLE
//@ sourceURL and //@ sourceMapURL is deprecated

### ISSUE THREAD

**Issue by jhnns** [webpack/webpack#91]
Chrome Canary is giving these nice notifications now:

> "//@ sourceURL=" source URL declaration is deprecated, "//# sourceURL=" declaration should be used instead.

https://code.google.com/p/v8/source/browse/trunk/ChangeLog#30

I think it's to prevent clashing with IE's [JScript compiler flags](http://stackoverflow.com/questions/3091802/reason-behind-a-javascript-parsing-error-in-msie-8).

**Comment by vkammerer** [comment]
This bug just showed up in my Canary again after upgrading

**Comment by jhnns** [comment]
What's the `devtool` setting in your `webpack.config.js`?

**Comment by trueter** [comment]
Im also affected, using `inline-eval-cheap-source-map`

**Comment by vkammerer** [comment]
Same as @trueter , `inline-eval-cheap-source-map`.
@trueter do you know which setting I should use in the mean time to prevent these errors? I disabled all sourcemaps yesterday because I was in a hurry but I need them back..

**Comment by trueter** [comment]
@vkammerer Sorry, no idea. As far as I see it two things are possible here:
1) Since it's only on Canary and not happening in stable Chrome it might be an issue with Canary we can't influence. 
2) There's been an issue with the devtool and Canary is reporting it while stable Chrome is not. 

Because it was apparently reporting back in 2013 and I don't see why they would remove that warning, I guess 1) is more likely.

**Comment by morenoh149** [comment]
seeing this as well. 
<img width="1052" alt="screen shot 2016-03-02 at 11 21 51 am" src="https://cloud.githubusercontent.com/assets/587438/13466783/75b86842-e069-11e5-8a43-6fe3d44bbed2.png">

**Comment by vkammerer** [comment]
My quick fix for the moment is to use 'cheap-source-map'

**Comment by sheepsteak** [comment]
I'm also getting this on Chrome Dev - 50.0.2657.0 dev (64-bit)

**Comment by dansullivan86** [comment]
Also seeing this using 'eval-source-map', changing it to '#eval-source-map' fixes it for now

**Comment by jhnns** [comment]
@sokra shouldn't `#` be the default now?

**Comment by sheepsteak** [comment]
[According to the docs](http://webpack.github.io/docs/configuration.html#devtool) `#` is the default now:

> Prefixing @, # or #@ will enforce a pragma style. (Defaults to #, recommended)

**Comment by himynameisdave** [comment]
Seeing it as well, anything I can do?

>`Chrome Version 50.0.2661.26 beta (64-bit)`

**Comment by trueter** [comment]
@himynameisdave You can switch to `cheap-source-map` for now.

**Comment by morenoh149** [comment]
@trueter :< I did that but now it's way harder to fix bugs in my code

**Comment by trueter** [comment]
Sorry, thats the only work around I know. Consider using stable Chrome instead?

**Comment by jhnns** [comment]
Can you post an example source map url that webpack is actually generating?

**Comment by morenoh149** [comment]
@jhnns how would one do that? In chrome it already inflates it to my source code.

I do see a footer
```
...

/*****************
 ** WEBPACK FOOTER
 ** ./~/tcomb/lib/intersection.js
 ** module id = 1414
 ** module chunks = 0
 **/
```

**Comment by jhnns** [comment]
Generate a bundle and open the file in a text editor :)

**Comment by AlexTes** [comment]
Here you go:
``` javascript
/* 1 */
/*!**********************!*\
  !*** ./src/entry.js ***!
  \**********************/
/***/ function(module, exports, __webpack_require__) {

	eval("'use strict';\n\n__webpack_require__(/*! pixi */ 2);\n\n__webpack_require__(/*! p2 */ 4);\n\n__webpack_require__(/*! phaser */ 6);\n\n__webpack_require__(/*! ./main */ 9);//@ sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiMS5qcyIsInNvdXJjZXMiOlsid2VicGFjazovLy9zcmMvZW50cnkuanM/MjU2YyJdLCJzb3VyY2VzQ29udGVudCI6WyJpbXBvcnQgJ3BpeGknO1xuaW1wb3J0ICdwMic7XG5pbXBvcnQgJ3BoYXNlcic7XG5yZXF1aXJlKCcuL21haW4nKTtcblxuXG5cbi8qKiBXRUJQQUNLIEZPT1RFUiAqKlxuICoqIHNyYy9lbnRyeS5qc1xuICoqLyJdLCJtYXBwaW5ncyI6Ijs7QUFBQTtBQUNBO0FBQUE7QUFDQTtBQUFBO0FBQ0E7QUFBQSIsInNvdXJjZVJvb3QiOiIifQ==");
```
Although I should mention I normally run the dev server.
Google Chrome version: 50.0.2661.37 beta

**Comment by jhnns** [comment]
Your webpack version is either outdated or you're using something like `devtool: "@eval"`. Just omit the `@` and update webpack.

With the latest webpack version `1.12.14` and `devtool: "eval"`, it should look like:

```javascript
eval(" [...js code here] //# sourceURL=webpack:///./a.js?");
```

**Comment by AlexTes** [comment]
I just updated wepack (1.12.13 -> 1.12.14). and tested a couple different devtool settings. I'm not prepending '@' anywhere. Not that I can see in any case.
eval - fine
cheap-eval-source-map - warnings
cheap-source-map - fine
cheap-module-eval-source-map - warnings (and wrong line numbers but that's only in code after importing a module that doesn't support es6 imports / modules in the first place)
cheap-module-source-map - fine
eval-source-map - warnings
source-map - warnings

the issues with cheap-module-eval-source-map are probably not webpacks fault and I don't mean to dig too deep here. For my purposes other options seem fine too, because I still get working source maps. As I understand (unless the 'bad' modules I'm using could cause these warnings) none of the devtool options should emit warnings and @morenoh149 wants to use one specifically that does cause warnings.

Again, I encourage other people with the issue to speak up, the project I currently have the issue with is just not 'clean' enough to expect everything to be right on my side.

**Comment by morenoh149** [comment]
I just changed to chrome stable. I'm assuming this is a regression on the canary team. Does anyone else concur?

**Comment by jkimbo** [comment]
Seeing this as well with `cheap-module-eval-source-map` as well.

```
└── webpack@1.12.14
```

**Comment by jkimbo** [comment]
@morenoh149 it's not a regression: https://developers.google.com/web/updates/2013/06/sourceMappingURL-and-sourceURL-syntax-changed?hl=en

**Comment by morenoh149** [comment]
but that's from 2013 (I've seen it before) so does that mean that the related change did not land in canary until ~Jan 2016?

**Comment by jkimbo** [comment]
@morenoh149 oh sorry didn't see the date. Not sure why it's only appearing now then!

**Comment by jhnns** [comment]
I can confirm this issue with `devtool: "cheap-module-eval-source-map"` (and probably other variations of it). It arises from [this line of code](https://github.com/webpack/webpack/blob/webpack-1/lib/EvalSourceMapDevToolModuleTemplatePlugin.js#L10) which has been already fixed in the webpack-2 branch.

[I've created PR for webpack-1](https://github.com/webpack/webpack/pull/2207)

**Comment by xcv58** [comment]
Same here, I downgrade my Chrome to stable release.

**Comment by jhnns** [comment]
Can you check if my PR solves the problem?

**Comment by tsm91** [comment]
filter the console messages with a simple regex until it gets fixed `^((?!sourceURL).)*$`

at least this is what i came up with

**Comment by jhnns** [comment]
The PR has been merged, btw

**Comment by omt66** [comment]
I am seeing the same issue. I am using the webpack via Yeoman Angular 2 generator ng2-webpack.

**Comment by danielstreit** [comment]
@jhnns Thanks for the fix!

Any estimate on when this can be published to npm?

**Comment by jhnns** [comment]
I don't know @sokra 's release plan for the 1.x branch... but usually I doesn't take too long.

**Comment by jasonm** [comment]
Looks like 1.13.0 was released 4 days ago 🎉  😄  

https://github.com/webpack/webpack/releases/tag/v1.13.0
https://www.npmjs.com/package/webpack

**Comment by 0x80** [comment]
I'm still getting these warnings with webpack >= 0.13.0 and `eval-cheap-module-source-map`?

**Comment by 0x80** [comment]
Using #eval-cheap-module-source-map fixed the problem for me. I would expect # to be the default already...

**Comment by zyy7259** [comment]
I use `devtool: 'source-map'`. Got an console error `Failed to parse SourceMap` with Google Chrome. However, no error with Google Chrome Canary.

```
webpack 1.13.1
Google Chrome Version 51.0.2704.84 (64-bit)
Google Chrome Canary Version 53.0.2762.0 canary (64-bit)
```

**Comment by BerndWessels** [comment]
Latest stable Chrome on my machine gives same error (Windows 10 64bit)

Google Chrome Version 51.0.2704.103 m
`config.devtool = 'eval';`

I get this error:

`Failed to parse SourceMap: http://localhost:3000/app.bundle.js.map`

I also noticed, when going directly to `http://localhost:3000/app.bundle.js.map` that it takes almost 4seconds to load - maybe that's a clue?

**Comment by halt-hammerzeit** [comment]
I'm also getting `Failed to parse` error in latest stable Chrome.
`eval-cheap-module-source-map` is a no go since it's not "production supported" as per the documentation.

**Comment by mischkl** [comment]
@halt-hammerzeit @BerndWessels @zyy7259 same problem here, but managed to fix it as suggested by @0x80 simply by adding "#" to the beginning of the devtool string.

**Comment by eaglet3d** [comment]
I'm seeing this warning as well.  It appears to be a regression bug.  When will this be fixed?

**Comment by isometriq** [comment]
I had the same problem.. and changing `source-map` to `#source-map` fixed it.
Using webpack 4.17.1

ps: Some IDE where OK (vscode, but with source map overrides in launch config) and some where not (phpstorm, required the `#`)
