### ISSUE TITLE
Changes publicPath: '../fonts' to 'https://local.dev/{pageName}'/fonts/[filename].[ext]'

### ISSUE THREAD

**Issue by pratirupm** [webpack/webpack#9103]
I am new to webpack and I can seem to find what I am doing wrong

Here What I Am Using For CSS:

    {
        test: /\.scss$/,
        use: [
            // creates style nodes from JS strings
            {
                loader: 'style-loader',
                options: {
                    sourceMap: true,
                },
            },
            {
                loader: 'css-loader',
                options: {
                    sourceMap: true,
                },
            }, // translates CSS into CommonJS
            {
                loader: 'postcss-loader',
                options: {
                    sourceMap: true,
                },
            },
            {
                loader: 'resolve-url-loader',
                options: {
                    sourceMap: true,
                },
            },
            {
                loader: 'sass-loader',
                options: {
                    sourceMap: true,
                },
            }, // compiles Sass to CSS
        ],
    },

And Here Is My Fonts :

    {
        test: /.(ttf|otf|eot|svg|woff(2)?)(\?[a-z0-9]+)?$/,
        use: [
            {
                loader: 'file-loader',
                options: {
                    name: '[name].[ext]',
                    outputPath: '../fonts',
                    publicPath: baseURL + 'fonts',
                },
            },
        ],
    },

And My baseURL `const baseURL = 'wp-content/plugins/pratirupm-plugin/inc/assets/dist/';`

What Ever I Put in my `publicPath: 'xyz'` the compiled blob file that `style-loader` adds to the dom appends the `page url + baseURL` 

so for example when I click on blog page the asset url changes to: 
`https://local.dev/blog/wp-content/plugins/pratirupm-plugin/inc/assets/dist/fonts/fa-brands-400.woff` 

I dont know why its acting like that as I said i am new to webpack and stuff but when I compile the js and css in production with `extract-text-plugin` and if my publicPath:'../fonts' it stays as '../fonts' in the css file as well..

Thanks For Your Time

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.
