### ISSUE TITLE
Include stack trace when reporting loading chunk error

### ISSUE THREAD

**Issue by rchl** [webpack/webpack#9109]
## Feature request

**What is the expected behavior?**

Loading chunk error includes stack trace with code that triggered chunk loading.

**What is motivation or use case for adding/changing the behavior?**

In my production site, with Sentry error logging enabled, "loading chunk" errors are the most frequent ones and given that the errors just say which chunk failed to load (chunk id and URL), it's hard to figure out steps to reproduce or in which situation error has triggered. Seing which code triggred loading of the chunk would help a lot.

**How should this be implemented in your opinion?**

I've hacked it locally like this: https://github.com/rchl/webpack/commit/fc64322f5da7726efbd546deb7af5ad0d0ff1966

The idea there is that I create Error object when stack hasn't unwinded yet and if loading fails, I use that error object later and pass it to `reject` promise.

Error object's stacktrace is created on creating the error object so doing it from load/error event of the script element (as is before my change) only includes current frame as stack has unwinded at that point.

I'm not sure that is an acceptable solution because creating an error object is potentially an expensive operation so doing that on loading every chunk could have some overhead. I don't really see any other solution though...

**Are you willing to work on this yourself?**

no (I'm very inexpirienced with webpack and would really struggle with making tests, for example)

**Comment by sokra** [comment]
Send a PR
