### ISSUE TITLE
resolve.alias not applied

### ISSUE THREAD

**Issue by KeKs0r** [webpack/webpack#911]
Hi,

I wanted to optimize my performance and therefore wanted to prefetch react:
`new webpack.PrefetchPlugin('react'),`
Problem with that, is that only a the index.js from react is prefetched and every other part of react 100+ files is still normally processed. I wanted to go around that by providing an alias for react to the distributed version with the following line:
```
    resolve: {
        alias: [
            { react: 'react/dist/react'}
        ],
```

This did not change anything, so I played around and also tried to completely screw it up with:
```
        alias: [
            { react: 'gulp'}
        ],
```
It is still normally processing my `require('react')` as there is no alias.

Any ideas?

**Comment by hkal** [comment]
I'm not familiar with the `alias` API, but from the examples I've seen, it does not appear to take an array as a parameter. Try:

``` javascript
resolve: {
  alias: {
    react: 'react/dist/react'
  }
}
```

**Comment by KeKs0r** [comment]
Perfect that did the trick.
