### ISSUE TITLE
"EMFILE: too many open files" error when emitting a large number of assets

### ISSUE THREAD

**Issue by MLoughry** [webpack/webpack#9117]
# Bug report

**What is the current behavior?**
I'm working on an i18n plugin to emit our localized strings on a per-locale, per-bundle basis. Given our build already emits ~1,400 code-split JS bundles, and we support nearly 100 locales, that results in a large number of files to emit. Given that Windows only supports ~1024 simultaneous file handles per process (by default, anyway), it's a near-certainty in this scenario that we hit this limit, and webpack fails ungracefully

**If the current behavior is a bug, please provide the steps to reproduce.**
Generate a webpack build/plugin that results in a large number of emitted files (>14k in our case)

**What is the expected behavior?**
Webpack should handle the error and gracefully back-off. Whether this is done by switching [`NodeOutputFileSystem`](https://github.com/webpack/webpack/blob/0293c3a5ee6e41d04f4c5e1fb0607fdb7a0b38a8/lib/node/NodeOutputFileSystem.js) to use [`graceful-fs`](https://www.npmjs.com/package/graceful-fs) or by implementing its own handling, webpack shouldn't fail without any attempt at retry in this case.

**Other relevant information:**
webpack version:  4.28.3
Node.js version: 11.4.0
Operating System: Windows 10 Pro (10.0.7134)
Additional tools:

**Comment by MLoughry** [comment]
This can be trivially fixed by using `graceful-fs`, but I'm not sure of the maintainers' view on using it as a dependency, or whether it would introduce other issues relating to perf or somesuch.

**Comment by sokra** [comment]
This commit should fix it: https://github.com/webpack/webpack/commit/9cb42256c67f77b24b04e1e19bd27c866febad6f
You need to upgrade to at least 4.29.0
