### ISSUE TITLE
unexpected chunk from node_module is generated even not referencing it 

### ISSUE THREAD

**Issue by wood1986** [webpack/webpack#9118]
# Bug report

**What is the current behavior?**
```
Hash: 4871b2f2b16960e685ac
Version: webpack 4.31.0
Time: 755ms
Built at: 05/11/2019 11:59:57 PM
                Asset       Size  Chunks             Chunk Names
  index.production.js  519 bytes       0  [emitted]  index
  react.production.js   6.52 KiB       1  [emitted]  react
vendors.production.js   3.98 KiB       2  [emitted]  vendors
Entrypoint index = vendors.production.js react.production.js index.production.js
[3] ./index.jsx + 2 modules 243 bytes {0} [built]
    | ./index.jsx 42 bytes [built]
    | ./utils/index.js 102 bytes [built]
    | ./utils/A.jsx 94 bytes [built]
    + 3 hidden modules
```

it has `react` chunk as I have not referenced the react code.

**If the current behavior is a bug, please provide the steps to reproduce.**

0. go https://github.com/wood1986/webpack-bug.git
1. `git clone https://github.com/wood1986/webpack-bug.git`
2. `yarn install`
3. `yarn build`

I do not know if it is the tree shaking issue, terser issue or it is by design. if it is by design, how should I avoid it ?

**What is the expected behavior?**
it should not output `react.production.js`

**Other relevant information:**
webpack version:  4.31.0
Node.js version: 10.15.3
Operating System: macOS 10.14.4
Additional tools:

**Comment by sokra** [comment]
`A.jsx` imports `react`. Even if you are not using the exports `react` need to be included and evaluated for its side-effects.

You might flag `A.jsx` or `react` as side-effect-free if you want to optimize it.

**Comment by wood1986** [comment]
Thanks for the explanation. Let me close it for now as I need to try side-effect-free stuff
