### ISSUE TITLE
Any plans to upgrade watchpack?

### ISSUE THREAD

**Issue by mmase** [webpack/webpack#9124]
Are there any plans to upgrade watchpack? The version of `fsevents` used by `chokidar` and consequently `watchpack@1.5.0` has issues with node 9 and 10 (no binaries available, high CPU usage).

**Comment by sokra** [comment]
`watchpack` won't be updated to version 2 in webpack 4 as this would be a breaking change.

It has already be updated to watchpack 2 in webpack 5 on the `next` branch.

**Comment by evilebottnawi** [comment]
Answer above, thanks

**Comment by jmalonzo** [comment]
Just FYI - `fsevents` now fails to build in Node v13. Any workaround for users of webpack 4, or should we advise not to use node v13 until webpack 5 is out?

**Comment by evilebottnawi** [comment]
@jmalonzo i don't have problem with webpack@4 and node@13, do you update lock file and deps?

**Comment by jmalonzo** [comment]
I removed my node_modules, recreated my lockfile and when reinstalling my
deps, the installation of fsevents failed.

**Comment by evilebottnawi** [comment]
@jmalonzo what is you os?

**Comment by jmalonzo** [comment]
I'm on OS X Catalina.

**Comment by evilebottnawi** [comment]
@jmalonzo still can't reproduce, maybe you can create a reproducible test repo and steps

**Comment by jmalonzo** [comment]
Sorry @evilebottnawi. It looks like it's a bad install of Xcode CommandLineTools. I reinstalled and it now seems to build and install fine.
