### ISSUE TITLE
Issue with Bootstrap reset css

### ISSUE THREAD

**Issue by Shelagh-Lewins** [webpack/webpack#9125]
# Bug report

**What is the current behavior?**
Bootstrap css reset is not being built correctly.

The file node_modules/bootstrap/dist/css/bootstrap.css contains this css:
```
*,
*::before,
*::after {
  box-sizing: border-box;
}
```

In my build output, it looks like this:
`*,::;after,::before{;box-sizing:border-box}`
Note the extra semi-colons, before the word 'after' and before the word 'box-sizing'.

I haven't edited the Bootstrap files, or the Webpack config.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
The css should be built as in the original file, without the extra semi-colons.

**Other relevant information:**
webpack version:  webpack@4.29.6
Node.js version: v8.16.0
Operating System: Linux Mint cinnamon
Additional tools:
Bootstrap: bootstrap@4.2.1
This is a Django app with a React / Redux front end built by Create React App 2.1.1

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by evilebottnawi** [comment]
Not related to webpack, problem in css minimizer, please open issue in css minimizer plugin or provide configuration here

**Comment by Shelagh-Lewins** [comment]
Thanks for the info. My Webpack package.json lists "css-loader": "^2.1.0", as a devDependency. Does that mean css-loader is the css minimizer plugin?

**Comment by evilebottnawi** [comment]
@Shelagh-Lewins css-loader is not minimizer and doesn't make minimize since with 1 version

**Comment by Shelagh-Lewins** [comment]
Thanks, so how do I find what is the minimizer? I don't see anything else in package.json that could be it?

**Comment by evilebottnawi** [comment]
https://webpack.js.org/configuration/optimization/#optimizationminimizer

**Comment by Shelagh-Lewins** [comment]
That link suggests the terser compiler is the default? I built the app using Create React App, so I don't have a Webpack config file to check. How would I find out which minimizer is in use?

Sorry for the dumb questions but I'm not familiar with the innards of Webpack!

**Comment by evilebottnawi** [comment]
@Shelagh-Lewins you still have configuration, look into CFA repo in `node_modules`
