### ISSUE TITLE
Change devtool example to something else

### ISSUE THREAD

**Issue by george-norris-salesforce** [webpack/webpack#9129]
https://github.com/webpack/webpack/blob/master/examples/source-map/webpack.config.js

Your docs point to this this example that is not very useful. That `webpack.config.js` resembles no `webpack.config.js` I've ever encountered. For examples that demonstrate complicated features like devtool, please make an example that resembles a real world project.

**Comment by sokra** [comment]
Send a PR and simplify it

**Comment by shaodahong** [comment]
I send a PR

In my see, source map is usually related to `mode`, `Production` or `Development` mode use different source map will good to debug code

**Comment by evilebottnawi** [comment]
bump
