### ISSUE TITLE
AMD require should be executed asynchronous

### ISSUE THREAD

**Issue by sebastiandeutsch** [webpack/webpack#913]
I'm currently migrating a large RequireJS based Chaplin app to webpack. All modules are required using AMD syntax. When loading controllers Chaplin is a little bit picky about the correct order that's why they ensure for non AMD requires (browserify) a setTimeout(..., 0) to make it asynchronous. With webpack I have the following problem: The if case for the AMD check is true https://github.com/chaplinjs/chaplin/blob/master/src/chaplin/dispatcher.coffee#L85 since webpack can handle AMD syntax - but the actual require call seems to be made synchronously. Wouldn't it be better if webpack ensures that a require via AMD is always asynchronous?

**Comment by ericnewton76** [comment]
This is of importance to me as well, as I have a few large RequireJS based projects that I'd like to move to webpack
