### ISSUE TITLE
Webpack chunking sourcemaps disappearing in browser

### ISSUE THREAD

**Issue by rob-barber** [webpack/webpack#9132]
# Bug report

**What is the current behavior?**
Webpack's source maps do not exist in browser after code splitting.

**If the current behavior is a bug, please provide the steps to reproduce.**
I have created a small project to better understand the issue. It can be downloaded here [https://github.com/rbarber1/Webpack-Chunk-Sourcemap-Bug.git](https://github.com/rbarber1/Webpack-Chunk-Sourcemap-Bug.git)

Steps to reproduce in the project are:
1. Install node packages `npm install`
2. run `npm run build` to build both bundles (main.js + second.js)
3. Open dist > index.html in any browser.
4. Open developer tools and examine the loaded files. 
    1. **Notice how there are source maps within the "webpack://" pseudo-path**
    
5. Open `webpack.config.js` and uncomment lines 36-41 (all lines pertaining to optimization)
6. run `npm run build` to build both bundles (main.js + second.js)
7. Open dist > index.html in any browser.
8. Open developer tools and examine the loaded files.
    1. **There are no longer any sourcemaps**

An example of what is being seen at: [No Sourcemaps after code splitting](https://github.com/rbarber1/Webpack-Chunk-Sourcemap-Bug/blob/master/Webpack-Chunking.png?raw=true)

**What is the expected behavior?**
Expected behavior is to see source maps for entry points and chunked code when using code splitting.

And example of this can be seen when not using code splitting. See image [here](https://github.com/rbarber1/Webpack-Chunk-Sourcemap-Bug/blob/master/Webpack-No-Chunking.png?raw=true)

**Other relevant information:**
webpack version:  4.31.0
Node.js version: v10.15.3, also tested on v10.8.0
Operating System: macOS 10.14.4
Additional tools: 
Babel 7.4.4. All other node_dependencies are saved within the package-lock.json

**Comment by sokra** [comment]
Is you code executed at all? Maybe you missed to include some `<script>` tags?

**Comment by rbarber1** [comment]
Code is executing fine. I print a string to the console upon opening the index.html file.

I haven't noticed any functionality issues at all actually. It's just that the source maps aren't created for bundles that have chunk files associated with them.
