### ISSUE TITLE
TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by jlapointe** [webpack/webpack#9133]
# Bug report

**What is the current behavior?**
I'm using code splitting (via SplitChunksPlugin) to extract common dependencies. I have multiple entry points. The output target is node.
When trying to run the successfully bundled code, I get the error `TypeError: Cannot read property 'call' of undefined`. 
When I remove code splitting from my config, the output runs without error.

Some commonalities with previous comments:
* I have multiple named entry points and one depends on the other, as in https://github.com/webpack/webpack/issues/959#issuecomment-397449112
* One of my files imports the relative path `'../../fixtures/mock_users.json'`, similar to https://github.com/webpack/webpack/issues/959#issuecomment-118394128.

**If the current behavior is a bug, please provide the steps to reproduce.**
I've provided a minimal project setup that reproduces the problem: https://gitlab.com/jlapointe/codesplittingtest

**What is the expected behavior?**
The code generated using code splitting should behave identically to the code generated without using code splitting.

**Other relevant information:**
webpack version:  4.31.0
Node.js version: 10.15.3
Operating System: Ubuntu 18.04 LTS
Additional tools: NodeExternals

**Comment by evilebottnawi** [comment]
Please update your webpack version to latest

**Comment by SigmaCoder** [comment]
I am also having the same issue. I have an application generated with jHipster. Here is my package.json file

`
{
  "name": "my-app",
  "version": "0.0.0",
  "description": "Description for MyApp",
  "private": true,
  "license": "UNLICENSED",
  "cacheDirectories": [
    "node_modules"
  ],
  "dependencies": {
    "@angular/animations": "^7.1.4",
    "@angular/cdk": "^7.2.0",
    "@angular/common": "^7.0.0",
    "@angular/compiler": "6.1.0",
    "@angular/core": "^7.1.4",
    "@angular/flex-layout": "github:angular/flex-layout-builds",
    "@angular/forms": "6.1.0",
    "@angular/material": "^7.2.0",
    "@angular/platform-browser": "6.1.0",
    "@angular/platform-browser-dynamic": "6.1.0",
    "@angular/router": "6.1.0",
    "@fortawesome/angular-fontawesome": "0.2.0",
    "@fortawesome/fontawesome-svg-core": "1.2.4",
    "@fortawesome/free-solid-svg-icons": "5.3.1",
    "@ng-bootstrap/ng-bootstrap": "3.0.0",
    "@progress/kendo-angular-buttons": "^4.3.2",
    "@progress/kendo-angular-charts": "^3.5.2",
    "@progress/kendo-angular-dateinputs": "^3.5.4",
    "@progress/kendo-angular-dialog": "^3.8.0",
    "@progress/kendo-angular-dropdowns": "^3.4.1",
    "@progress/kendo-angular-excel-export": "^2.2.0",
    "@progress/kendo-angular-gauges": "^2.4.1",
    "@progress/kendo-angular-grid": "^3.9.0",
    "@progress/kendo-angular-inputs": "^4.2.1",
    "@progress/kendo-angular-intl": "^1.7.0",
    "@progress/kendo-angular-l10n": "^1.4.0",
    "@progress/kendo-angular-layout": "^3.2.0",
    "@progress/kendo-angular-notification": "^1.2.0",
    "@progress/kendo-angular-popup": "^2.5.0",
    "@progress/kendo-angular-resize-sensor": "^3.1.2",
    "@progress/kendo-angular-scheduler": "^0.3.4",
    "@progress/kendo-angular-toolbar": "^1.0.0",
    "@progress/kendo-angular-tooltip": "^1.1.2",
    "@progress/kendo-angular-treeview": "^2.5.0",
    "@progress/kendo-angular-upload": "^4.3.1",
    "@progress/kendo-data-query": "^1.5.0",
    "@progress/kendo-date-math": "^1.4.0",
    "@progress/kendo-drawing": "^1.5.7",
    "@progress/kendo-recurrence": "^0.1.2",
    "@progress/kendo-theme-bootstrap": "^3.2.2",
    "@progress/kendo-theme-default": "^2.58.0",
    "@progress/kendo-theme-material": "^1.5.2",
    "angular-i18n": "^1.7.6",
    "bootstrap": "4.1.3",
    "caniuse-lite": "^1.0.30000967",
    "cldr-data": "^34.0.0",
    "core-js": "2.5.7",
    "cors": "^2.8.5",
    "cssnano-preset-default": "^4.0.5",
    "generator-jhipster-entity-audit": "^3.1.1",
    "hammerjs": "^2.0.8",
    "jquery": "^1.9.1",
    "moment": "2.22.2",
    "ng-diff-match-patch": "2.0.6",
    "ng-jhipster": "0.5.4",
    "ngx-color-picker": "^7.3.1",
    "ngx-cookie": "2.0.1",
    "ngx-infinite-scroll": "6.0.1",
    "ngx-webstorage": "2.0.1",
    "popper.js": "^1.14.3",
    "reflect-metadata": "0.1.12",
    "rxjs": "6.1.0",
    "rxjs-compat": "^6.5.2",
    "swagger-ui": "2.2.10",
    "tslib": "1.9.3",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@angular/cli": "6.1.2",
    "@angular/compiler-cli": "6.1.0",
    "@ngtools/webpack": "6.0.0",
    "@types/jest": "22.2.3",
    "@types/node": "9.4.7",
    "angular-router-loader": "0.8.5",
    "angular2-template-loader": "0.6.2",
    "browser-sync": "^2.26.3",
    "browser-sync-webpack-plugin": "2.2.2",
    "cache-loader": "1.2.2",
    "codelyzer": "4.2.1",
    "copy-webpack-plugin": "4.5.1",
    "css-loader": "0.28.10",
    "exports-loader": "0.7.0",
    "file-loader": "1.1.11",
    "fork-ts-checker-webpack-plugin": "0.4.1",
    "friendly-errors-webpack-plugin": "1.7.0",
    "generator-jhipster": "5.5.0",
    "html-loader": "0.5.5",
    "html-webpack-plugin": "3.2.0",
    "husky": "1.1.0",
    "jest": "22.4.3",
    "jest-junit": "5.1.0",
    "jest-preset-angular": "5.2.2",
    "jest-sonar-reporter": "2.0.0",
    "kill-port": "1.3.2",
    "lint-staged": "7.3.0",
    "merge-jsons-webpack-plugin": "1.0.14",
    "mini-css-extract-plugin": "0.4.2",
    "moment-locales-webpack-plugin": "1.0.5",
    "optimize-css-assets-webpack-plugin": "5.0.1",
    "postcss-loader": "2.1.1",
    "prettier": "1.11.1",
    "proxy-middleware": "0.15.0",
    "raw-loader": "0.5.1",
    "rimraf": "2.6.1",
    "simple-progress-webpack-plugin": "1.1.2",
    "style-loader": "0.20.3",
    "tapable": "^1.1.3",
    "terser-webpack-plugin": "1.0.0",
    "thread-loader": "1.1.5",
    "to-string-loader": "1.1.5",
    "ts-loader": "4.0.1",
    "tslint": "5.9.1",
    "tslint-config-prettier": "1.9.0",
    "tslint-loader": "3.6.0",
    "typescript": "^2.8.0",
    "webpack": "4.8.0",
    "webpack-cli": "2.1.3",
    "webpack-dev-server": "^3.1.5",
    "webpack-merge": "4.1.2",
    "webpack-notifier": "1.6.0",
    "webpack-visualizer-plugin": "0.1.11",
    "workbox-webpack-plugin": "3.2.0",
    "write-file-webpack-plugin": "4.2.0",
    "xml2js": "0.4.19"
  },
  "engines": {
    "node": ">=8.9.0"
  },
  "lint-staged": {
    "src/**/*.{ts,css,scss}": [
      "prettier --write",
      "git add"
    ]
  },
  "scripts": {
    "prettier:format": "prettier --write \"src/**/*.{ts,css,scss}\"",
    "lint": "tslint --project tsconfig.json -e 'node_modules/**'",
    "lint:fix": "npm run lint -- --fix",
    "ngc": "ngc -p tsconfig-aot.json",
    "cleanup": "rimraf target/{aot,www}",
    "clean-www": "rimraf target//www/app/{src,target/}",
    "start": "npm run webpack:dev",
    "start-tls": "npm run webpack:dev -- --env.tls",
    "stop": "kill-port 9000",
    "serve": "npm run start",
    "build": "npm run webpack:prod",
    "test": "npm run lint && jest --coverage --logHeapUsage -w=2 --config src/test/javascript/jest.conf.js",
    "test:watch": "npm test -- --watch --clearCache",
    "webpack:dev": "npm run webpack-dev-server -- --config webpack/webpack.dev.js --inline --hot --port=9060 --watch-content-base --env.stats=minimal",
    "webpack:dev-verbose": "npm run webpack-dev-server -- --config webpack/webpack.dev.js --inline --hot --port=9060 --watch-content-base --profile --progress --env.stats=normal",
    "webpack:build:main": "npm run webpack -- --config webpack/webpack.dev.js --env.stats=minimal",
    "webpack:build": "npm run cleanup && npm run webpack:build:main",
    "webpack:prod:main": "npm run webpack -- --config webpack/webpack.prod.js --profile",
    "webpack:prod": "npm run cleanup && npm run webpack:prod:main && npm run clean-www",
    "webpack:test": "npm run test",
    "webpack-dev-server": "node --max_old_space_size=5120 node_modules/webpack-dev-server/bin/webpack-dev-server.js",
    "webpack": "node --max_old_space_size=5120 node_modules/webpack/bin/webpack.js"
  },
  "jestSonar": {
    "reportPath": "target/test-results/jest",
    "reportFile": "TESTS-results-sonar.xml"
  }
}
`

I am getting these errors:
`
[HMR] Waiting for update signal from WDS...
polyfills.bundle.js:712 Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (polyfills.bundle.js:712)
    at fn (polyfills.bundle.js:95)
    at eval (polyfills.ts?21e8:22)
    at Object../src/main/webapp/app/polyfills.ts (polyfills.bundle.js:1075)
    at __webpack_require__ (polyfills.bundle.js:712)
    at fn (polyfills.bundle.js:95)
    at Object.0 (polyfills.bundle.js:1088)
    at __webpack_require__ (polyfills.bundle.js:712)
    at polyfills.bundle.js:764
    at polyfills.bundle.js:767
VM69 log.js:24 [HMR] Waiting for update signal from WDS...
main.bundle.js:712 Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (main.bundle.js:712)
    at fn (main.bundle.js:95)
    at eval (app.main.ts?38fd:1)
    at Object../src/main/webapp/app/app.main.ts (main.bundle.js:1075)
    at __webpack_require__ (main.bundle.js:712)
    at fn (main.bundle.js:95)
    at Object.2 (main.bundle.js:1088)
    at __webpack_require__ (main.bundle.js:712)
    at main.bundle.js:764
    at main.bundle.js:767
log.js?1afd:24 [HMR] Waiting for update signal from WDS...
global.bundle.js:712 Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (global.bundle.js:712)
    at fn (global.bundle.js:95)
    at eval (global.css?abcf:2)
    at Object../src/main/webapp/content/css/global.css (global.bundle.js:1074)
    at __webpack_require__ (global.bundle.js:712)
    at fn (global.bundle.js:95)
    at Object.1 (global.bundle.js:1087)
    at __webpack_require__ (global.bundle.js:712)
    at global.bundle.js:764
    at global.bundle.js:767
3VM16 localhost:9060:79 [WDS] Hot Module Replacement enabled.
`

I tried to remove node_modules and package-lock.json and run npm install. But the errors is still there. TypeScript compiles successfully

**Comment by SigmaCoder** [comment]
I am also having the same issue. I have an application generated with jHipster. Here is my package.json file


{
  "name": "my-app",
  "version": "0.0.0",
  "description": "Description for MyApp",
  "private": true,
  "license": "UNLICENSED",
  "cacheDirectories": [
    "node_modules"
  ],
  "dependencies": {
    "@angular/animations": "^7.1.4",
    "@angular/cdk": "^7.2.0",
    "@angular/common": "^7.0.0",
    "@angular/compiler": "6.1.0",
    "@angular/core": "^7.1.4",
    "@angular/flex-layout": "github:angular/flex-layout-builds",
    "@angular/forms": "6.1.0",
    "@angular/material": "^7.2.0",
    "@angular/platform-browser": "6.1.0",
    "@angular/platform-browser-dynamic": "6.1.0",
    "@angular/router": "6.1.0",
    "@fortawesome/angular-fontawesome": "0.2.0",
    "@fortawesome/fontawesome-svg-core": "1.2.4",
    "@fortawesome/free-solid-svg-icons": "5.3.1",
    "@ng-bootstrap/ng-bootstrap": "3.0.0",
    "@progress/kendo-angular-buttons": "^4.3.2",
    "@progress/kendo-angular-charts": "^3.5.2",
    "@progress/kendo-angular-dateinputs": "^3.5.4",
    "@progress/kendo-angular-dialog": "^3.8.0",
    "@progress/kendo-angular-dropdowns": "^3.4.1",
    "@progress/kendo-angular-excel-export": "^2.2.0",
    "@progress/kendo-angular-gauges": "^2.4.1",
    "@progress/kendo-angular-grid": "^3.9.0",
    "@progress/kendo-angular-inputs": "^4.2.1",
    "@progress/kendo-angular-intl": "^1.7.0",
    "@progress/kendo-angular-l10n": "^1.4.0",
    "@progress/kendo-angular-layout": "^3.2.0",
    "@progress/kendo-angular-notification": "^1.2.0",
    "@progress/kendo-angular-popup": "^2.5.0",
    "@progress/kendo-angular-resize-sensor": "^3.1.2",
    "@progress/kendo-angular-scheduler": "^0.3.4",
    "@progress/kendo-angular-toolbar": "^1.0.0",
    "@progress/kendo-angular-tooltip": "^1.1.2",
    "@progress/kendo-angular-treeview": "^2.5.0",
    "@progress/kendo-angular-upload": "^4.3.1",
    "@progress/kendo-data-query": "^1.5.0",
    "@progress/kendo-date-math": "^1.4.0",
    "@progress/kendo-drawing": "^1.5.7",
    "@progress/kendo-recurrence": "^0.1.2",
    "@progress/kendo-theme-bootstrap": "^3.2.2",
    "@progress/kendo-theme-default": "^2.58.0",
    "@progress/kendo-theme-material": "^1.5.2",
    "angular-i18n": "^1.7.6",
    "bootstrap": "4.1.3",
    "caniuse-lite": "^1.0.30000967",
    "cldr-data": "^34.0.0",
    "core-js": "2.5.7",
    "cors": "^2.8.5",
    "cssnano-preset-default": "^4.0.5",
    "generator-jhipster-entity-audit": "^3.1.1",
    "hammerjs": "^2.0.8",
    "jquery": "^1.9.1",
    "moment": "2.22.2",
    "ng-diff-match-patch": "2.0.6",
    "ng-jhipster": "0.5.4",
    "ngx-color-picker": "^7.3.1",
    "ngx-cookie": "2.0.1",
    "ngx-infinite-scroll": "6.0.1",
    "ngx-webstorage": "2.0.1",
    "popper.js": "^1.14.3",
    "reflect-metadata": "0.1.12",
    "rxjs": "6.1.0",
    "rxjs-compat": "^6.5.2",
    "swagger-ui": "2.2.10",
    "tslib": "1.9.3",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@angular/cli": "6.1.2",
    "@angular/compiler-cli": "6.1.0",
    "@ngtools/webpack": "6.0.0",
    "@types/jest": "22.2.3",
    "@types/node": "9.4.7",
    "angular-router-loader": "0.8.5",
    "angular2-template-loader": "0.6.2",
    "browser-sync": "^2.26.3",
    "browser-sync-webpack-plugin": "2.2.2",
    "cache-loader": "1.2.2",
    "codelyzer": "4.2.1",
    "copy-webpack-plugin": "4.5.1",
    "css-loader": "0.28.10",
    "exports-loader": "0.7.0",
    "file-loader": "1.1.11",
    "fork-ts-checker-webpack-plugin": "0.4.1",
    "friendly-errors-webpack-plugin": "1.7.0",
    "generator-jhipster": "5.5.0",
    "html-loader": "0.5.5",
    "html-webpack-plugin": "3.2.0",
    "husky": "1.1.0",
    "jest": "22.4.3",
    "jest-junit": "5.1.0",
    "jest-preset-angular": "5.2.2",
    "jest-sonar-reporter": "2.0.0",
    "kill-port": "1.3.2",
    "lint-staged": "7.3.0",
    "merge-jsons-webpack-plugin": "1.0.14",
    "mini-css-extract-plugin": "0.4.2",
    "moment-locales-webpack-plugin": "1.0.5",
    "optimize-css-assets-webpack-plugin": "5.0.1",
    "postcss-loader": "2.1.1",
    "prettier": "1.11.1",
    "proxy-middleware": "0.15.0",
    "raw-loader": "0.5.1",
    "rimraf": "2.6.1",
    "simple-progress-webpack-plugin": "1.1.2",
    "style-loader": "0.20.3",
    "tapable": "^1.1.3",
    "terser-webpack-plugin": "1.0.0",
    "thread-loader": "1.1.5",
    "to-string-loader": "1.1.5",
    "ts-loader": "4.0.1",
    "tslint": "5.9.1",
    "tslint-config-prettier": "1.9.0",
    "tslint-loader": "3.6.0",
    "typescript": "^2.8.0",
    "webpack": "4.8.0",
    "webpack-cli": "2.1.3",
    "webpack-dev-server": "^3.1.5",
    "webpack-merge": "4.1.2",
    "webpack-notifier": "1.6.0",
    "webpack-visualizer-plugin": "0.1.11",
    "workbox-webpack-plugin": "3.2.0",
    "write-file-webpack-plugin": "4.2.0",
    "xml2js": "0.4.19"
  },
  "engines": {
    "node": ">=8.9.0"
  },
  "lint-staged": {
    "src/**/*.{ts,css,scss}": [
      "prettier --write",
      "git add"
    ]
  },
  "scripts": {
    "prettier:format": "prettier --write \"src/**/*.{ts,css,scss}\"",
    "lint": "tslint --project tsconfig.json -e 'node_modules/**'",
    "lint:fix": "npm run lint -- --fix",
    "ngc": "ngc -p tsconfig-aot.json",
    "cleanup": "rimraf target/{aot,www}",
    "clean-www": "rimraf target//www/app/{src,target/}",
    "start": "npm run webpack:dev",
    "start-tls": "npm run webpack:dev -- --env.tls",
    "stop": "kill-port 9000",
    "serve": "npm run start",
    "build": "npm run webpack:prod",
    "test": "npm run lint && jest --coverage --logHeapUsage -w=2 --config src/test/javascript/jest.conf.js",
    "test:watch": "npm test -- --watch --clearCache",
    "webpack:dev": "npm run webpack-dev-server -- --config webpack/webpack.dev.js --inline --hot --port=9060 --watch-content-base --env.stats=minimal",
    "webpack:dev-verbose": "npm run webpack-dev-server -- --config webpack/webpack.dev.js --inline --hot --port=9060 --watch-content-base --profile --progress --env.stats=normal",
    "webpack:build:main": "npm run webpack -- --config webpack/webpack.dev.js --env.stats=minimal",
    "webpack:build": "npm run cleanup && npm run webpack:build:main",
    "webpack:prod:main": "npm run webpack -- --config webpack/webpack.prod.js --profile",
    "webpack:prod": "npm run cleanup && npm run webpack:prod:main && npm run clean-www",
    "webpack:test": "npm run test",
    "webpack-dev-server": "node --max_old_space_size=5120 node_modules/webpack-dev-server/bin/webpack-dev-server.js",
    "webpack": "node --max_old_space_size=5120 node_modules/webpack/bin/webpack.js"
  },
  "jestSonar": {
    "reportPath": "target/test-results/jest",
    "reportFile": "TESTS-results-sonar.xml"
  }
}


I am getting these errors:

[HMR] Waiting for update signal from WDS...
polyfills.bundle.js:712 Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (polyfills.bundle.js:712)
    at fn (polyfills.bundle.js:95)
    at eval (polyfills.ts?21e8:22)
    at Object../src/main/webapp/app/polyfills.ts (polyfills.bundle.js:1075)
    at __webpack_require__ (polyfills.bundle.js:712)
    at fn (polyfills.bundle.js:95)
    at Object.0 (polyfills.bundle.js:1088)
    at __webpack_require__ (polyfills.bundle.js:712)
    at polyfills.bundle.js:764
    at polyfills.bundle.js:767
VM69 log.js:24 [HMR] Waiting for update signal from WDS...
main.bundle.js:712 Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (main.bundle.js:712)
    at fn (main.bundle.js:95)
    at eval (app.main.ts?38fd:1)
    at Object../src/main/webapp/app/app.main.ts (main.bundle.js:1075)
    at __webpack_require__ (main.bundle.js:712)
    at fn (main.bundle.js:95)
    at Object.2 (main.bundle.js:1088)
    at __webpack_require__ (main.bundle.js:712)
    at main.bundle.js:764
    at main.bundle.js:767
log.js?1afd:24 [HMR] Waiting for update signal from WDS...
global.bundle.js:712 Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (global.bundle.js:712)
    at fn (global.bundle.js:95)
    at eval (global.css?abcf:2)
    at Object../src/main/webapp/content/css/global.css (global.bundle.js:1074)
    at __webpack_require__ (global.bundle.js:712)
    at fn (global.bundle.js:95)
    at Object.1 (global.bundle.js:1087)
    at __webpack_require__ (global.bundle.js:712)
    at global.bundle.js:764
    at global.bundle.js:767
3VM16 localhost:9060:79 [WDS] Hot Module Replacement enabled.


I tried to remove node_modules and package-lock.json and run npm install. But the errors is still there. TypeScript compiles successfully

**Comment by evilebottnawi** [comment]
@SigmaCoder stop spamming you information doesn't help to find problem

**Comment by jlapointe** [comment]
Sorry, there was a typo in my post (fixed). I am using the latest version of webpack, v4.31.0

**Comment by evilebottnawi** [comment]
@jlapointe problem still exists? Can you create minimum reproducible test repo

**Comment by sokra** [comment]
Unsure if this is the problem but `splitChunks.chunks: "all"` is not supported on `target: "node"` in webpack 4. Use `chunks: "async"` instead.

**Comment by jlapointe** [comment]
@evilebottnawi Yes the problem still exists. I provided the repo in the initial post; it's using the latest version, 4.31.0.

**Comment by jlapointe** [comment]
> Unsure if this is the problem but `splitChunks.chunks: "all"` is not supported on `target: "node"` in webpack 4. Use `chunks: "async"` instead.

Thanks for the insight! Doesn't solve the problem though. I tried each allowed value of `chunks` (`"all"`, `"async"`, and `"initial"`). 
* When using `chunks: "all"`, the duplicated code gets extracted into its own file, but I get `TypeError: Cannot read property 'call' of undefined` when I run the entry point.
* When using `chunks: "async"`, the duplicated code no longer gets extracted. The entry point runs without error.
* * When using `chunks: "initial"`, the duplicated code gets extracted into its own file, but I get `TypeError: Cannot read property 'call' of undefined` when I run the entry point. (Same as when I use `chunks: "all"`)

**Comment by sokra** [comment]
> * When using `chunks: "async"`, the duplicated code no longer gets extracted. The entry point runs without error.

Note that `splitChunks` is primary a performance optimization for downloading and caching in a web environment. So it should not hurt much to have this disabled in node.js

---

As workaround you can `import()` your old entry point in a new entry point.

``` js
// webServer.entry.ts
import("./webServer.ts");
```

---

webpack 5 supports `chunks: "all"` for `target: "node"`. You can try `webpack@next`.

**Comment by jlapointe** [comment]
@sokra Thanks for the reply :). 

> Note that splitChunks is primary a performance optimization for downloading and caching in a web environment. So it should not hurt much to have this disabled in node.js

I'm not using this feature for performance optimization; I'm (trying) to use it to design a build process I can be happy with :). For that purpose, I would like the code split.

> 

I'm not sure that workaround helps, since it looks quite similar to what I'm already doing (which doesn't generate the expected behaviour). 

I will try webpack@next and see if that helps; thanks for the suggestion!

**Comment by jlapointe** [comment]
@sokra this issue is fixed in 5.0.0-alpha.13, thank you!

**Comment by carlbergman** [comment]
We ran into the same problem and are very grateful for the solution in 5.0.0-alpha.13.

> webpack 5 supports chunks: "all" for target: "node". You can try webpack@next.

Are there plans to backport it to Webpack 4?

I would happily work on it if there are no reasons to keep Webpack 4 working as before.
