### ISSUE TITLE
access compiler's resolver in the "externals" configuration option

### ISSUE THREAD

**Issue by FranckFreiburger** [webpack/webpack#9142]
## Feature request

**What is the expected behavior?**

Give the ability for configuration externals function to access current compiler's resolver.
```
{
	target: 'node',
 	externals: [
		function({ context, request, resolve}, callback) { ...

```

**What is motivation or use case for adding/changing the behavior?**

1/ More accurate filtering modules contained in `node_modules` using compiler's resolver.
2/ create a list of packages that are required but not bundled.

**How should this be implemented in your opinion?**

Now that externals function is able to support more information (https://github.com/webpack/webpack/pull/8533), it should be fine to add a "resolve" property to { context, request } argument.

eg. `resolve(context, request)` -> full path of the request

_edit_: unfortunately it seems that the resolver is not available easily.

**Are you willing to work on this yourself?**
why not

**Comment by sokra** [comment]
Maybe it makes sense to run the `externals` check before and after resolving. So it could match the unresolved request or the fully resolved request. Similar happens for `IgnorePlugin` and `resolve.alias`, which also run on runresolved and resolved requests.

But this would be a breaking change, since it could change existing behavior.

**Comment by FranckFreiburger** [comment]
In order to avoid breaking change (and takes advantage of this feature earlier),
is it feasible to keep the current `externals` behavior and to add (something like) `externalsResolved` ?

**Comment by evilebottnawi** [comment]
bump

**Comment by piecyk** [comment]
bump

**Comment by FranckFreiburger** [comment]
bump

**Comment by FranckFreiburger** [comment]
maybe inactive but still valid :)
