### ISSUE TITLE
Webpack banner plugin work with file from another plugin

### ISSUE THREAD

**Issue by muhammaddicky** [webpack/webpack#9145]
Is there is a way to make webpack-banner-plugin can work to file from another plugin like copy-webpack-plugin that copy js/css file?, It's only process file from entry point, I'm trying set entryOnly to false but still not process another file beside from entry point

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.
