### ISSUE TITLE
[question]  profile timings

### ISSUE THREAD

**Issue by iliakan** [webpack/webpack#915]
I compile with `--profile` enabled.

Then `module.profile` stat equals an object like this `{ factory: 19265, dependencies: 166, building: 2288 } }`.

What does it mean? What denotes factory? dependencies? building?

**Comment by sokra** [comment]
factory = resolving
building = loaders + parsing
dependencies = time to process dependencies

**Comment by iliakan** [comment]
Can resolving take a lot?

**Comment by iliakan** [comment]
Recently my webpack build became very slow. Like 5 times slower.
I'm trying to discover why.

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#102
