### ISSUE TITLE
Isn't webpack switched to terser internally? Can I config terser without terser-webpack-plugin?

### ISSUE THREAD

**Issue by frederikhors** [webpack/webpack#9151]
Why should I need terser if webpack already uses it internally?

I need some non-default options, for example the comment strip in the final bundle and found around that I could do this:

```js
const TerserPlugin = require('terser-webpack-plugin');

module.exports = {
  entry: /*...*/
  output: /*...*/,
  module: /*...*/,
  optimization: {
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          output: {
            comments: false,
          },
        },
      }),
    ],
  },
}
```

Can I config webpack without require `terser-webpack-plugin`?

**Comment by sokra** [comment]
> Can I config webpack without require `terser-webpack-plugin`?

No. You can't pass options to the default minimizer. You can do it like in your code snippet.

Why? Did you remember when we change the default minimizer from uglifyjs to terser within webpack 4 without a breaking change. This won't be possible when we allow to pass options directly. Changing options from uglifyjs to terser would be a breaking change.

So this little boilerplate allows the default to be easier to change.

**Comment by evilebottnawi** [comment]
Answer above and don't duplicate issue in future, thanks
