### ISSUE TITLE
Support for executing files in an external process

### ISSUE THREAD

**Issue by fabiospampinato** [webpack/webpack#9157]
## Feature request

**What is the expected behavior?**

It's somewhat common to spawn specific files in another process like this:

```js
require ( 'child_process' ).spawn ( process.execPath, [path.join ( __dirname, 'foo.js' ) ] )
```
Currently WebPack isn't able to understand that the file at `path.join ( __dirname, 'foo.js' )` should be bundled, but even if it could this code would still not work, as this code expects to be able to spawn a specific file called `foo.js`, while WebPack would instead include `foo.js` in the bundle itself.

This sort of code should be bundle-able with WebPack.

I think there should be a way to tell WebPack when a file is required, when it should be bundled in a separate chunk, and perhaps what that chunk should be named (or at least webpack should implement some key-value store so that the app could query webpack for the chunk that's supposed to be named "foo.js", so that webpack can actually name it whatever it wants in order to avoid conflicts).

**What is motivation or use case for adding/changing the behavior?**

Some packages write this kind of code, including [`update-notifier`](https://www.npmjs.com/package/update-notifier), which is used in CLI apps, which should start as quickly as possible, so bundling them would make sense, but because of this issue they can't be bundled properly with WebPack.

**How should this be implemented in your opinion?**

Maybe this particular use case is simple enough that WebPack could support it without requiring any modification to existing code, but if that's not possible:

- Maybe there could be a magic comment added for telling webpack to bundle a specific file with a specific filename, like:

```js
/* webpack-trust-me-bundle-this-external-file: __dirname + '/foo.js' */
```

- And maybe a function for retrieving the path to that external file, like:

```js
typeof __webpack_path_to_external__ !== 'undefined' ? __webpack_path_to_external__ ( __dirname + '/foo.js' ) : __dirname + '/foo.js'
```

**Are you willing to work on this yourself?**

Yes, maybe with some pointers I could implement something like this.

**Comment by sindresorhus** [comment]
Not just for spawning child process, but also [worker threads](https://nodejs.org/api/worker_threads.html).

**Comment by evilebottnawi** [comment]
bump
