### ISSUE TITLE
Production mode minifies routerMiddleware of 'connected-react-router' as undefined

### ISSUE THREAD

**Issue by knightus** [webpack/webpack#9159]
# Bug report

**What is the current behavior?**
Production mode of webpack 4.32.0 cannot minify connected-react-router middleware properly, and produces `undefined`

**If the current behavior is a bug, please provide the steps to reproduce.**
- Using webpack 4.31.0, [connected-react-router v6.4.0](https://github.com/supasate/connected-react-router)
- Upgrade webpack from 4.31.0 to 4.32.0
- Run build (production mode)
- webpack minifies connected-react-router's middleware as `undefined`

This is a large proprietary project so I'm not sure how to extract this to a sample repo yet. But here's some screenshots from Chrome debugger (unminified)

![image](https://user-images.githubusercontent.com/5171973/58114726-9316fb80-7c22-11e9-884c-419767184146.png)

**What is the expected behavior?**
Webpack minifies this middleware successfully as a function.

![image](https://user-images.githubusercontent.com/5171973/58115675-c2c70300-7c24-11e9-8c2a-886cc24bfb84.png)
![image](https://user-images.githubusercontent.com/5171973/58116247-0c641d80-7c26-11e9-970c-58253cec0661.png)

**Other relevant information:**
webpack version:  4.32.0
Node.js version: 11.13.0
Operating System: Windows 10
Additional tools: yarn 1.16.0

**Comment by sokra** [comment]
I can't reproduce it with the instructions above.

It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by knightus** [comment]
Hi @sokra,

I've created a repo trying to describe the problem better, please check and tell me if you need more information: https://github.com/knightus/webpack-issue-9159

**Comment by sokra** [comment]
Thanks this helps

**Comment by sokra** [comment]
fixed in 4.32.2
