### ISSUE TITLE
webpack --watch

### ISSUE THREAD

**Issue by streamich** [webpack/webpack#916]
When running `webpack --watch` I sometimes get the following error, and program exits:

    Assertion failed: 0, file d:\jenkins\workspace\nodejs-msi\22874dd8\deps\uv\src\win\handle-inl.h, line 158

Then I execute `webpack --watch` again and it runs normally.

**Comment by rfastturnlow** [comment]
@streamich: Are you using the latest sass-loader? I have the same issue as well, but it goes away when I remove that particular loader.  Unfortunately I still haven't figured out much more than that at this time.

**Comment by streamich** [comment]
Yes, if I remove `sass-loader`, I don't see that error anymore. Now using WebStorm with `scss` watcher, which compiles `.scss` to `.css` automatically, and then included them in Webpack with `css-loader`.

**Comment by rfastturnlow** [comment]
Just to follow up, this issue went away for me when I upgraded my node-sass dependency to version 3.0.0-beta.5 so it does not seem to be an issue with webpack.

BTW: Props to the webpack team for all their hard work on this awesome project!
