### ISSUE TITLE
Provide an option to limit the number of workers for multi-config compiler

### ISSUE THREAD

**Issue by dmwmt** [webpack/webpack#9162]
## Feature request

Provide an option to limit the number of workers for multi-config compiler

**What is the expected behavior?**

Webpack should be able to limit the number of workers for multi-config compiler

**What is motivation or use case for adding/changing the behavior?**

We need to build multiple versions of our very small package (about 100 loc) so we export an array of configurations as explained [here](https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations).
One standalone build takes 4 seconds and about 150 Mb of memory (which is too much I believe but we can live with that)
16 parallel builds take 2:30 and about 1.5 Gb of memory.
So our concerns are:
1. parallel compilation takes 2.5x longer than sequential
2. peak memory consumption is too high for CI slave nodes

**How should this be implemented in your opinion?**

Provide an option to limit the number of parallel workers.
Limiting to 1 will essentially make the build sequential.
Optimal number would be the number of cpu cores and this should be its default value.

**Are you willing to work on this yourself?**
no

**Comment by DenysMikhalenkoWalmart** [comment]
Any comments on this?

**Comment by evilebottnawi** [comment]
Bump, multi-threading in our roadmap

**Comment by justin808** [comment]
@evilebottnawi what's the current multi-threading behavior of v4? What's the plan for v5?

**Comment by evilebottnawi** [comment]
@justin808 no `multi-threading` for v4. Yes, it is in the plan for v5. But persistent cache is more priority and we are working on it.

**Comment by sokra** [comment]
This is not about multi-threading, but still makes sense.
