### ISSUE TITLE
Error "ReferenceError: can't access lexical declaration `XXX' before initialization" when loading a webpack-ed app

### ISSUE THREAD

**Issue by julienw** [webpack/webpack#9173]
# Bug report
**What is the current behavior?**
When loading the home page, we get this error in the browser's console:
```
ReferenceError: can't access lexical declaration `reportTrackThreadHeight' before initialization app.js:1
    js app.js:1
    js TrackThread.js:243
```
This happens both in Firefox and Chrome (the error message is slightly different in Chrome).
This also happens in a dev server, or when building and loading the built app, both in dev and prod mode.

**If the current behavior is a bug, please provide the steps to reproduce.**

STR:
1. clone https://github.com/julienw/perf.html.git
2. switch to branch `webpack-bug`
3. run `yarn install`
4. run `yarn start`
5. open http://localhost:4242

=> notice the error in the console log

Steps 1 to 4 in a few commands:
```
git clone https://github.com/julienw/perf.html.git
cd perf.html
git checkout webpack-bug
yarn install
yarn start
```

Sorry this isn't quite a minimal testcase, but I believe the problem comes from some form of dependency mismanagement and the problem might not happen with a smaller testcase.

My initial theory is that the problem comes from `ModuleConcatenationPlugin` hoisting  this function where it shouldn't, but the problem happens in dev mode as well, where `ModuleConcatenationPlugin` shouldn't be configured by default. So I'm a bit confused here.

Other useful commands are:
* `yarn build` => builds a development bundle to `dist/`
* `yarn build-prod` => builds a production bundle to `dist/`

**What is the expected behavior?**

There's no error in the generated bundle and we should be able to load the homepage without an error.

**Other relevant information:**
webpack version:  4.32.1
Node.js version:  v10.15.1
Operating System: Linux
Additional tools: --

**Comment by anajavi** [comment]
I had the same error today. I managed to work around it by adding plugin to .babelrc:
```
 "@babel/plugin-transform-block-scoping"
```

I think the reason for the error is that webpack generates code which tries to access const before it is declared:
```javascript
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "CLEAR_STATE", function() { return CLEAR_STATE; });

const CLEAR_STATE = 'CLEAR_STATE';
```

As plugin-transform-block-scoping transforms const to var, it works around the problem.

**Comment by julienw** [comment]
That's what I don't get: this would be an problem if this `CLEAR_STATE` export was required before the `const`, but in our case I don't see that in the bundle. Yes, the "require function" is before the `const`, but the code that actually uses it is after.

**Comment by sokra** [comment]
This usually occurs in case of a circular dependency.

Here is a simplified example:

``` js
// app.js
import "./something";

export const VALUE = 42;
```

``` js
// something.js
import { VALUE } from "./app";

console.log(VALUE);
```

Note that this is not a webpack bug, but correct behavior according to the ESM spec.

---

Using `@babel/plugin-transform-block-scoping` won't fix the root problem. By using `var` instead of `const` you will receive `undefined` instead of the TDZ error. This probably lead to other issues.

---

Solution: Refactor your application. Try to do one of these things:

* Get rid of the circular dependency, or
* don't access circular exports in module evaluation

Example:

You can get rid of the circular dependency in my example by moving the constants to a new module:

``` js
// app.js
import "./something";
```

``` js
// constants.js
export const VALUE = 42;
```

``` js
// something.js
import { VALUE } from "./constants";

console.log(VALUE);
```

**Comment by julienw** [comment]
Thanks for the insight!
What's surprising in our case is that the problem appeared after _removing_ some dependencies. So we couldn't add new  circular dependencies. But of course this  could have exposed existing ones by rearranging some order ?

**Comment by julienw** [comment]
For anybody coming here, the webpack plugin [circular dependency](https://www.npmjs.com/package/circular-dependency-plugin) could be useful.
I wonder if such a functionality couldn't be added to webpack core, if the possible outcomes are so dramatic.

**Comment by sokra** [comment]
The problem is that circular dependencies are not wrong. They only lead to problems in some cases. Adding warnings for all circular dependencies is too much.

I can look into detecting cases where we are sure that a TDZ error will be thrown, but not sure if this is possible in a safe way.

**Comment by evilebottnawi** [comment]
bump

**Comment by evilebottnawi** [comment]
Let's bump, not high priority

**Comment by julienw** [comment]
Should this bug stay open ? Not sure :)

**Comment by sokra** [comment]
I think it can be closed

**Comment by Mohammed-Dekkers** [comment]
> 
> 
> This usually occurs in case of a circular dependency.
> 
> Here is a simplified example:
> 
> ```js
> // app.js
> import "./something";
> 
> export const VALUE = 42;
> ```
> 
> ```js
> // something.js
> import { VALUE } from "./app";
> 
> console.log(VALUE);
> ```
> 
> Note that this is not a webpack bug, but correct behavior according to the ESM spec.
> 
> Using `@babel/plugin-transform-block-scoping` won't fix the root problem. By using `var` instead of `const` you will receive `undefined` instead of the TDZ error. This probably lead to other issues.
> 
> Solution: Refactor your application. Try to do one of these things:
> 
>     * Get rid of the circular dependency, or
> 
>     * don't access circular exports in module evaluation
> 
> 
> Example:
> 
> You can get rid of the circular dependency in my example by moving the constants to a new module:
> 
> ```js
> // app.js
> import "./something";
> ```
> 
> ```js
> // constants.js
> export const VALUE = 42;
> ```
> 
> ```js
> // something.js
> import { VALUE } from "./constants";
> 
> console.log(VALUE);
> ```



> 
> 
> I think it can be closed

thank you for your help
