### ISSUE TITLE
It takes 10 minutes to pack a 20M bag.

### ISSUE THREAD

**Issue by 690284557** [webpack/webpack#9178]
# Bug report

**What is the current behavior?**
It takes 10 minutes to pack a 20M bag.
Execution 
node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "webpack/webpack.prod.js" "--profile"

**If the current behavior is a bug, please provide the steps to reproduce.**
![image](https://user-images.githubusercontent.com/38547105/58218731-9c938700-7d3a-11e9-9ee5-bfe482651eb6.png)

**What is the expected behavior?**
Packing faster

**Other relevant information:**
webpack version:  4.8
Node.js version: 8.11.3
Operating System: windows7
Additional tools: springboot+
[webpack.zip](https://github.com/webpack/webpack/files/3209922/webpack.zip)
angular4

**Comment by sokra** [comment]
> 20M bag

What does this even mean? A 20MB bundle?

**Comment by 690284557** [comment]
> > 20M bag
> 
> What does this even mean? A 20MB bundle?

All pictures, ts, html, CSS pages

**Comment by evilebottnawi** [comment]
And what you exptected?

**Comment by 690284557** [comment]
> And what you expected?
我想知道正常打包速度，然后提高速度。我用webpack2打包500M的vue工程也就3分钟

**Comment by 690284557** [comment]
Then I want to know how to solve the above error.

**Comment by evilebottnawi** [comment]
What error?

**Comment by 690284557** [comment]
> What error?

Picture, three lines above the red arrow

**Comment by evilebottnawi** [comment]
1. Some of plugin outdated
2. You need update deps

Also it is warning, not error, please use gitter or stackoverflow for helping in this case, it is bug tracker. You projects builds fine, so no bugs here.

**Comment by 690284557** [comment]
> 1. Some of plugins is outdated
> 2. You need update deps
> 
> Also it is warning, not error, please use gitter or stackoverflow for helping in this case, it is bug tracker. You projects builds fine, so no bugs here.

But few people understand it.
