### ISSUE TITLE
Warning for jsondiffpatch:Critical dependencies, the request of a dependency is an expression

### ISSUE THREAD

**Issue by jiyinyiyong** [webpack/webpack#918]
This was at first reported at jsondiffpatch: https://github.com/benjamine/jsondiffpatch/issues/76
but it turned out to be a trick to play with Browserify so it isn't packaged for browsers.

here's the controversial code, a veriable name in `requre()`:
```js
var formatterModuleName = './formatters';
var formatters = require(formatterModuleName);
exports.formatters = formatters;
```
as a result I keep receiving these warnings:
```
WARNING in ./~/jsondiffpatch/src/main.js
Critical dependencies:
48:19-49 the request of a dependency is an expression
53:18-46 the request of a dependency is an expression
 @ ./~/jsondiffpatch/src/main.js 48:19-49 53:18-46
```

Is there any solution for such case(meanwhile not breaking Browserify)?

**Comment by emmenko** [comment]
I would also like to know how to configure the `ContextReplacementPlugin` in this case...

**Comment by sokra** [comment]
see benjamine/jsondiffpatch#76

**Comment by emmenko** [comment]
@sokra I tried using browser spec as you suggested but haven't got to work it.

In my case I'm trying to bundle `node-fetch` which has [encoding](https://github.com/andris9/encoding) as dependency. The critical part is here https://github.com/andris9/encoding/blob/master/lib/encoding.js#L6-L12

Obviously I'm getting the warning

```bash
WARNING in ./~/node-fetch/~/encoding/lib/encoding.js
Critical dependencies:
9:12-34 the request of a dependency is an expression
 @ ./~/node-fetch/~/encoding/lib/encoding.js 9:12-34
```

I've tried with

```json
"browser": {
  "iconv": false
}
```

but no luck. 

Can you point me to the right direction? Thanks :)

**Comment by sokra** [comment]
Send a PR to "encoing" which changes

``` js
try {
    // this is to fool browserify so it doesn't try (in vain) to install iconv.
    var iconv_package = 'iconv';
    Iconv = require(iconv_package).Iconv;
} catch (E) {
    // node-iconv not present
}
```

to

``` js
Iconv = require('iconv').Iconv;
```

and adds

``` js
"browser": {
  "iconv": false
}
```

the the package.json

**Comment by emmenko** [comment]
Hmm, but what about the workaround for browserify? Also, if there is no dynamic dependency there is no need at all to ignore it, as I would not get the webpack warning.

I'm a bit confused now...

**Comment by sokra** [comment]
browserify supports the `browser` field in package.json too. The dynamic hack is only a other way to ignore a package in browserify (but it's more a hack, many people use because they don't know the `browser` field).

**Comment by emmenko** [comment]
Ok I see. Thanks for explaining, as always :)
