### ISSUE TITLE
How do I insert some content when Webpack read the entry file?

### ISSUE THREAD

**Issue by nostarsnow** [webpack/webpack#9181]
I want to insert some `import` to entry file only in dev mode
But I did not find a suitable `hook`

webpack.conf
```js
{ entry: 'index.js' }
```
index.js ``(source file)``
```js
console.log(window.test)
```
lib.js  ``(Another file I want to import but I don't want to write import 'lib' in index.js or entry)``
```js
window.test = 'test'
```

I want to insert `import 'lib'` when Webpack read `index.js`. Then Webpack will think that the content of `index.js` is like this:
```js
import 'lib'
console.log(window.test)
```
I can do this with `fs`. then have to delete `import 'lib'` when building.
but that is too bad.... -<

**Comment by sokra** [comment]
Maybe an array of entries works for you: `{ entry: ['lib', 'index.js'] }`
This doesn't inject an import, but is similar.

If you really need to inject an `import` use the https://github.com/webpack-contrib/imports-loader

**Comment by nostarsnow** [comment]
@sokra 
tks.
I don't want global variables...
I need to insert different content when Webpack read different entry file.
`import`/`lib`/`index.js`/`window`.these are just examples.
Sorry, I didn't make it clear.

Now.
I hope that it can be done in a `hook`. 
But I didn't find this `hook`...

**Comment by sokra** [comment]
You can write a loader. A loader can rewrite the file content in any way.

**Comment by nostarsnow** [comment]
> You can write a loader. A loader can rewrite the file content in any way.
tks...right!
I am always thinking about writing a plugin. but Ignore the loader.
I will try it now.
