### ISSUE TITLE
Webpack does not rename imports that are redefined using const/let in another block

### ISSUE THREAD

**Issue by DrRataplan** [webpack/webpack#9183]
# Bug report

**What is the current behavior?**
When I hide an import using a block-scoped variable (const/let) that is defined in another block, webpack seems to skip renaming of that variable where it should point to the import.

Input:
```js
import someFunction from './someFunction';

export default function myFunction () {
	if (someFunction()) {
		const someFunction = 123;
		return someFunction + 1;
	}

	someFunction();
}
```

Output:
```
...
/***/ "./src/index.js":
/*!**********************!*\
  !*** ./src/index.js ***!
  \**********************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "default", function() { return myFunction; });
/* harmony import */ var _someFunction__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./someFunction */ "./src/someFunction.js");


function myFunction () {
	if (someFunction()) {
		const someFunction = 123;
		return someFunction + 1;
	}

// The issue is here, someFunction should point to the import, and be renamed
	someFunction();
}


/***/ }),
...
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I have made a reproducible case: https://github.com/DrRataplan/webpack-variable-hiding-repro.
Clone it, run `npm i`, run `node ./wp.js`, look at the contents of the dist folder.

**What is the expected behavior?**

Hiding imports using block-scoped variables should work. Webpack should rename usages of those variables correctly. Another option would be to skip renaming these variables, this might make this code a bit more predictable, imho.

Agreed, variable hiding is bad practice, but my variable hiding is caused by terser, this may introduce hidden variables.

**Other relevant information:**
webpack version:  latest (at the time of writing: 4.32.2)
Node.js version: Irrelevant, I can repro this on multiple versions
Operating System:  Irrelevant, I have a repro on Ubuntu Linux and Mac OSX
Additional tools: -

**Comment by DrRataplan** [comment]
I had a look in how the Parser works, and it seems to me that there is no distinction between block-scoped and function-scoped variables.

If someone could give me some pointers in how to implement such a distinction, I can try to send in a pr for this. I also would like to know why we pack is renaming these variables. By skipping the rename, I feel that the whole issue would be circumvented.

In the meantime, we are disabling module-level renames in terser and we have an additional eslint rule in place in hopes of not running into this issue anytime soon.

**Comment by sokra** [comment]
> it seems to me that there is no distinction between block-scoped and function-scoped variables.

Yeah this is the problem. At the time webpack was created such distinction didn't exist in the spec...

The problem is that this is not an easy fix, because of the way the prewalking in the parser works.
