### ISSUE TITLE
Allow webpackChunkName to be specified when using require.context

### ISSUE THREAD

**Issue by DaniJG** [webpack/webpack#9184]
## Feature request

**What is the expected behavior?**

When using `require.context` it should be possible to specify the chunk name, same as when using [magic comments](https://webpack.js.org/api/module-methods#magic-comments) with dynamic import statements.

Ie it should be possible to write (assuming a 5th argument is added to [require.context](https://webpack.js.org/api/module-methods#requirecontext) for the chunk name):
```
require.context(
  '@/views', 
  true, 
  /\.async\.vue$/, 
  'lazy',
  '[request]')
```
which should generate the same chunks as when using
```
import(
  /* webpackChunkName: "[request]" */
  `@/views/${name}.async.vue`
);
```

**What is motivation or use case for adding/changing the behavior?**
I would like to automatically generate a chunk for every page in a Vue app that meets a certain convention. Ideally the chunk name would be based on the page name.

**How should this be implemented in your opinion?**
A 5th argument could be added to the [`RequireContextDependencyParserPlugin`](https://github.com/webpack/webpack/blob/8a7597aa6eb2eef66a8f9db3a0c49bcb96022a94/lib/dependencies/RequireContextDependencyParserPlugin.js) to extract the chunk name and pass it into the `RequireContextDependency` options.

**Are you willing to work on this yourself?**
yes

**Comment by PerspectivesLab** [comment]
that would be nice, as require.context doesnt generate any chunk

**Comment by JasKang** [comment]
```javascript
const children = context.keys().map(key => {
    const path = key
      .split('/')
      .map(str => str.replace(/\.vue/g, '').replace(/\./g, ''))
      .filter(str => str !== '');
    return {
      component: () => context(/* webpackChunkName: "[request]" */ key),
      name: `${ctxKey}-${path.join('-')}`,
      path: `${ctxKey}/` + path.join('/')
    };
  });
```
@DaniJG
I hope so

**Comment by evilebottnawi** [comment]
bump

**Comment by falcon03** [comment]
up. This issue is still relevant, especially considering that dynamic imports don't offer a feature similar to require.context

**Comment by Losses** [comment]
bump this issue

**Comment by Rhilip** [comment]
bump this issue

**Comment by Landen13** [comment]
bump this issue

**Comment by sokra** [comment]
This has been implemented since years

**Comment by sanmaozhao** [comment]
Where can I find the documentation or example?
Thanks!

**Comment by sokra** [comment]
Oh I misread this as `require.ensure` instead of `require.context`.

No this is not implemented, but it's not that difficult to add.

Send a PR. see RequireContextDependencyParserPlugin.js, add `chunkName` property to `options` argument of `new RequireContextDependency`.

**Comment by Tofandel** [comment]
Okay, I believe we should have control over the chunkName, just `request` would generate a chunk per file, I'd want to generate grouped request chunks (eg: require context a folder and the subfolder would be the chunk name)

**Comment by Tofandel** [comment]
PR implements the same features as import with comments

So now it would be possible to do

```js
require.context(
 /* webpackMode: "lazy" */
 /* webpackChunkName: "[request]" */
  '@/views', 
  true, 
  /\.async\.vue$/
 )
 ```

**Comment by vankop** [comment]
please use `import.meta.webpackContext` for that https://github.com/webpack/webpack/pull/15463
