### ISSUE TITLE
DllReferencePlugin option name has extension

### ISSUE THREAD

**Issue by hanagejet** [webpack/webpack#9185]
# Bug report

**What is the current behavior?**

Can not get correct output (not `string`):

![スクリーンショット 2019-05-24 11 18 53](https://user-images.githubusercontent.com/4067007/58298244-c2da2500-7e15-11e9-9a47-50f08c9e96ff.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

When `DllReferencePlugin` option name has extension, get output code like above image.
```js
new webpack.DllReferencePlugin({
  name: "./foo.js",
  manifest: 'path/to/manifest.json'
})
```

I folked webpack repository to reproduce:
https://github.com/hanagejet/webpack/commit/181efd756bf267647aadd7d392ed695138980785

**What is the expected behavior?**

Can get correct output like:
```diff
- module.exports = ./foo.js;
+ module.exports = "./foo.js";
```

**P.S**
I referred to [doc](https://webpack.js.org/plugins/dll-plugin/#dllreferenceplugin):
![スクリーンショット 2019-05-24 11 22 48](https://user-images.githubusercontent.com/4067007/58298398-4a279880-7e16-11e9-9dd2-9a61cf84b4b0.png)

**Other relevant information:**
webpack version:  4.32.2
Node.js version: v10.15.3
Operating System: macOS 10.14.4
Additional tools:

**Comment by sokra** [comment]
`name` should be an identifier not a file path. But it's usually taken from the manifest file so you don't have to pass it on the `DllReferencePlugin`.

**Comment by hanagejet** [comment]
@sokra Thank you reply!!

> name should be an identifier not a file path.

But can not working that `name` has identifier. Could you try this??

> But it's usually taken from the manifest file so you don't have to pass it on the DllReferencePlugin.

Yes, but when should we `name` option??

---

I confused when I got this error. So if `name` option is unnecessary, I wanna update doc for other DllReferencePlugin user.

**Comment by sokra** [comment]
`./foo.js` is not a valid identifier: https://developer.mozilla.org/en-US/docs/Glossary/Identifier

> Yes, but when should we `name` option??

In cases where `name` from `DllPlugin` differs from `name` in `DllReferencePlugin`. This is never the case in normal usage. It's for special cases when doing some magic with Dlls.

**Comment by hanagejet** [comment]
> ./foo.js is not a valid identifier

What do you mean??  Is this bug…?

>  It's for special cases when doing some magic with Dlls.

I can't understand.
If usually do not use `name` option, I think that it is better to update [doc](https://github.com/webpack/webpack.js.org/blob/master/src/content/plugins/dll-plugin.md#usage):

```diff
new webpack.DllReferencePlugin({
  context: __dirname,
  manifest: require('./manifest.json'),
-  name: './my-dll.js',
  scope: 'xyz',
  sourceType: 'commonjs2'
});
```

Developer will see doc and include `name` option. If usually don't use `name` option, remove it from this doc as it will confuse developer.

**Comment by sokra** [comment]
> Developer will see doc and include `name` option. If usually don't use `name` option, remove it from this doc as it will confuse developer.

Yep. That's not only confusing, but also wrong in the docs.

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack.js.org

see https://github.com/webpack/webpack/issues/9185#issuecomment-496091596

**Comment by hanagejet** [comment]
Thank you so much!! I can't write English well🙏

**Comment by Hideer** [comment]
@hanagejet Hi，when dllReferencePlugin  use commonjs2  can it work normally? I have some problems
