### ISSUE TITLE
SyntaxError on devtool:inline and import non-existing module

### ISSUE THREAD

**Issue by canadaduane** [webpack/webpack#9187]
# Bug report

**What is the current behavior?**
Under the following 3 conditions, webpack generates syntactically incorrect javascript by placing a `!` after the `new` reserved word:
1. Set Webpack config `devtool` to `inline`, and
2. Use `import` to import a module that doesn't exist, and
3. Instantiate a class with the `new` keyword.

**If the current behavior is a bug, please provide the steps to reproduce.**
Please see this minimal repro: https://github.com/canadaduane/webpack-test 

**What is the expected behavior?**
Generated code should not raise SyntaxError.

**Other relevant information:**
webpack version:  4.32.2
Node.js version: 10.15.3
Operating System: Mac OS X
Additional tools: babel

See also #6191 and #8762.

**Comment by ajaygangarde** [comment]
do you got any solution for above problem. i am also stuck into it. any Help would be appreciate

**Comment by canadaduane** [comment]
Sorry, I can't recall the workaround I used at the time. I hope this finds someone knowledgeable and willing to fix!

**Comment by ajaygangarde** [comment]
actually i am getting these issues due to typeorm with ssr build. hopefully will resolve. thanks for support.

**Comment by evilebottnawi** [comment]
bump

**Comment by evilebottnawi** [comment]
Fixed https://github.com/webpack/webpack/pull/10424 (webpack@5)
