### ISSUE TITLE
inputFileSystem support in watchpack.

### ISSUE THREAD

**Issue by 0xorial** [webpack/webpack#9189]
## Feature request

**What is the expected behavior?**
when I provide inputFileSystem to webpack it is used for watching as well.

**What is motivation or use case for adding/changing the behavior?**
I am trying to improve tests of fork-ts-checker-webpack-plugin to test watch-mode compilation. It would be quite convenient to use an in-memory fs.

**How should this be implemented in your opinion?**
From webpack consumer perspective providing own fs should be as easy as passing an it to webpack, as long as it is compatible with node fs.
Currently, I see that webpack has inputFileSystem, outputFileSystem and watchFileSystem. First two are node-fs-compatible and can be easily replaced, but third one has a lot of logic and consumes watchpack. Because of that it is not a good option to just provide own watchFileSystem. This can be improved as follows:

*Watchpack changes:*
For both methods watchpack needs to accept external fs, instead of relying on graceful-fs. To simplify transition, graceful-fs can be default option if no fs is provided.

*webpack changes:*

- webpack entry function should be modified to accept fs. This seems more future-proof than setting fs-properties after creation, because it gives webpack liberty to access fs during creation. and more freedom during initialization. Perhaps, add an option fsEnvironmentPlugin, which would default to NodeEnvironmentPlugin.

- NodeEnvironmentPlugin/fsEnvironmentPlugin should not depend on watchpack. creation of watchpack should be done independent of which fs is provided.

- Current NodeWatchFileSystem should become something like WatchpackWatcher, should accept watchFileSystem (or inputFileSystem extended with watch methods) and pass it to watchpack.

Also, it seems that there was not much change between webpack 4 and 5 in this area, so it should be easy to add this to both version.

**Are you willing to work on this yourself?**
yes

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by sokra** [comment]
I don't think this is a good idea. watchpack is very node.js specific. It deals with node.js-specific problems and OS-specific issues. It not possible to reliable replace the underlying filesystem. Instead watchpack should be considered as node.js specific solution.

That's why webpacks WatchFileSystem interface is above watchpack and watchpack powers only the NodeWatchFileSystem.

It should still be possible to replace Watch and Input file system with an in-memory one.

Orthogonal to this it should also be possible to add watching support to memory-fs.

For webpack watching with memory-fs watchpack isn't needed. You only need a simple wrapper.

**Comment by 0xorial** [comment]
@sokra, can you provide documentation for WatchFileSystem interface then (especially for callback parameters)? Or, even better an example implementation with memory-fs of [memfs](https://github.com/streamich/memfs) (I am using the second because it seems to provide more functionality, including watch functions)?

**Comment by sokra** [comment]
``` js
watch(
  // Array of files to be watched
  files,

  // Array of directories to be watched
  dirs,

  // Array of not-existing file entries to be watched
  missing,

  // Time (in the past) when watch should start
  startTime,

  // watchOptions
  options,

  // callback
  // function(error, changedFiles, changedDirs, changedMissing, fileTimestamps, contextTimestramps, removedFiles)
  // called after all changes where aggregated
  // see also watchOptions.aggregateTimeout
  callback,

  // callback: function()
  // called immediately after something changed
  callbackUndelayed
): Watcher

interface Watcher {
  // closes the watcher
  close();

  // stops emitting events
  // may keep watchers active if this makes sense
  pause();

  // returns an object with filename as key and timestamp as value
  getFileTimestamps();

  // returns an obejct with dirname as key and timestamp as value
  getContextTimestamps();
}
```
