### ISSUE TITLE
Mismatch between AMD and CommonJS module definition in UMD module

### ISSUE THREAD

**Issue by gcorne** [webpack/webpack#919]
While working on converting a project to webpack from browserify, I ran into an issue with one of the project's dependencies. The dependency [hashmap](https://www.npmjs.com/package/hashmap) is written as a UMD module, but the shape of the AMD module and the CommonJS module are different. Webpack favors the AMD definition, which caused an issue when compiling via webpack. 

The issue is demonstrated in https://github.com/gcorne/webpack/commit/4f115d8bd04e8ef064b150ae3b620727900fc5a4

My expectation coming from a node/commonjs mindset is that commonjs would be given a higher priority when parsing a UMD module or that there would be some configuration option to favor using the commonjs version over amd to allow for better compatibility with 3rd-party npm libraries.

**Comment by sokra** [comment]
webpack doesn't prioritise one over the other. It just supports both and which one is used depends on how the library tests for AMD/CJS support.

``` js
if (typeof define === 'function' && define.amd) {
	define([], factory);
} else if (typeof exports === 'object') {
	exports.foo = factory();
}
```

Here AMD is used because CJS is in the else clause.

``` js
if (typeof exports === 'object') {
	exports.foo = factory();
} else if (typeof define === 'function' && define.amd) {
	define([], factory);
}
```

Here CJS is used because AMD is in the else clause.

**Comment by gcorne** [comment]
> webpack doesn't prioritise one over the other. It just supports both and which one is used depends on how the library tests for AMD/CJS support.

That makes sense. I guess it becomes a question of whether a module that works in browserify should work with webpack automatically when used the same way. In this case, it turns out that `hashmap` has made an [adjustment](https://github.com/flesler/hashmap/issues/12) and I was able to fix the upstream module to use the new version, so my particular issue is resolved. I have no idea how often there are differences between the AMD and CJS implementations, but it would be kind of cool if it "just worked."

**Comment by wiktor256** [comment]
Is there a way to disable AMD altogether?

**Comment by wiktor256** [comment]
I am aware of this syntax: require("imports?define=>false!./file.js"). But I would like to apply it globally to all modules, so I can still do require('module').

**Comment by sokra** [comment]
You can apply it via config

**Comment by wiktor256** [comment]
Can you give an example? I tries this and it didn't work:
```
  imports: {
    define: false
  }
```

**Comment by sokra** [comment]
http://webpack.github.io/docs/using-loaders.html#configuration

**Comment by wiktor256** [comment]
Thanks. This works for me:
```
module: {
  loaders: [
    { test: /\.js/, loader: 'imports?define=>false'}
  ]
}
```

**Comment by gcorne** [comment]
The `imports-loader` solution works for me. Thanks!

**Comment by zsimo** [comment]
The imports-loader solution works for me. Thanks!
