### ISSUE TITLE
Loaders behaves different between function or array module.rules.use

### ISSUE THREAD

**Issue by otakustay** [webpack/webpack#9194]
# Bug report

**What is the current behavior?**

When `module.rules.use` is set to a function, and `babel-loader` is given an `options` property, the `worker-loader` as a final loader could report errors:

```text
ERROR in ./src/background.worker.js
Module build failed: Error: Final loader (./node_modules/worker-loader/dist/cjs.js) didn't return a Buffer or String
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I have submitted a reproduction repo: https://github.com/otakustay/webpack-issues/tree/use-function

The `use-function` branch reproduces this issue described in README, I don't quite understand whether the issue lies in `webpack`, `babel-loader`, or `worker-loader`, however this is a smallest reproduction case.

**What is the expected behavior?**

All 3 configurations should compile successfully.

**Other relevant information:**
webpack version:  4.32.2
Node.js version: v10.13.0
Operating System: macOS mojave
Additional tools:

**Comment by evilebottnawi** [comment]
Looks problem in `worker-loader` :disappointed:

**Comment by sokra** [comment]
It's a bug when using functions on `module.rules.use`

**Comment by evilebottnawi** [comment]
Because it is bug feel free to send a PR

**Comment by sokra** [comment]
In webpack 5 this should work when you provide an `ident` for options returned by `use` functions.

The automatic identing is disabled for `use` function, because you could return random values each time the function is invoked. webpack 5 will give you an error in these cases.

**Comment by vankop** [comment]
answered
