### ISSUE TITLE
rename file breaks watch

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack#9195]
for me the easiest way to reproduce was trying to change file extension, so another loader will be applied, but cache will not be invalidated for the previous loader.
Repo with repro is here https://github.com/Den-dp/webpack-issue-5523-repro and steps are in README too.

_Originally posted by @Den-dp in https://github.com/webpack/webpack/issues/5523#issuecomment-495682030_

**Comment by sokra** [comment]
Should be fix in webpack 5. Could you try it there?

**Comment by Den-dp** [comment]
@sokra @evilebottnawi just tested my case above with `webpack@5.0.0-alpha.14` and now renaming works perfect in watch mode.
Thank you guys 👍

**Comment by evilebottnawi** [comment]
Keep open for other developers until we release 5 version

**Comment by evilebottnawi** [comment]
Fixed in webpack@5, feel free to open new issue if you will face with problem
