### ISSUE TITLE
feat: loaders as required modules

### ISSUE THREAD

**Issue by AndersDJohnson** [webpack/webpack#9199]
## Feature request

**What is the expected behavior?**
I'd like webpack to support supplying loaders as `require()`d modules, so that they could be bundled with a tool via something like `webpack` or `rollup`, rather than requiring them to exist in local `node_modules` at runtime. So an example config could look something like:

```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: '/node_modules/',
        use: require('babel-loader')
      }
    ]
  }
};
```

**What is motivation or use case for adding/changing the behavior?**
I have an issue when I try to include a loader in a webpack config executed programmatically as part of a CLI tool that I want users to be able to execute with `npx`.

**How should this be implemented in your opinion?**
Simply check if the value(s) in `use` or `use.loader` (singular or array) is a string or not - if it's not, just use it directly, instead of trying to resolve its file path relative to current directory's `node_modules`.

**Are you willing to work on this yourself?**
yes

**Comment by sokra** [comment]
`use: require.resolve('babel-loader')`

**Comment by evilebottnawi** [comment]
Answer above https://github.com/webpack/webpack/issues/9199#issuecomment-496808517

**Comment by AndersDJohnson** [comment]
Thanks. It worked, but I had to use `__non_webpack_require__.resolve` instead of `require.resolve`, since webpack seems to replace the latter with just the argument passed to it wrapped in a comment, so the lookup doesn't happen at runtime.
