### ISSUE TITLE
output.path is "/" on apply()

### ISSUE THREAD

**Issue by jhnns** [webpack/webpack#92]
I'm currently writing a WebpackPlugin that wipes the output folder before compilation. Unfortunately `compiler.options.output.path` is `"/"` when the `apply()`-function is invoked.

I'm glad my fs blocked this request ... :smile:

**Comment by jhnns** [comment]
This is still an issue btw ^^. I don't get why the `compiler.options.output.path` is `'/'`. There is no way to get the output folder from the options.

**Comment by sokra** [comment]
maybe `compiler.options.output.path` is `'/'` when using the webpack-dev-server, as it has a in memory filesystem.

**Comment by jhnns** [comment]
Yes, you're right. I'm using the webpack-dev-middleware. The problem is, that I still have my public folder where I wanted to emit the generated `index.html` to. I expected to receive the same options as passed into webpack.

**Comment by sokra** [comment]
You shouldn't care about the output path. If you want to emit assets, add them to `compilation.assets` and they are emitted into the output path.

see https://github.com/ampedandwired/html-webpack-plugin

**Comment by jhnns** [comment]
K thx!
