### ISSUE TITLE
Enhancing release notes 

### ISSUE THREAD

**Issue by raiyanalam** [webpack/webpack#9201]
Hi, 
    I was going through the release section of the repo, i feel it can be improved to give a more richer information to users - like providing a list of changes, cross referencing it with issues and providing links to external resources. 
Since the repo already uses Azure pipelines for CI, we can potentially leverage its [built-in task](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/GitHubReleaseV0) to publish release notes to GitHub. The task can be configured to create a release only when the pipeline is triggered for a matching tag. It can compute an exhaustive list of changes done in this release, list them and cross reference it with the issues. Additionally, we can also provide a list links to external sources which we think will be useful for users to get started with the release. 
Here is a [sample repo](https://github.com/Microsoft/vscode-react-native/releases) that leverages this capability.  Being a built in task, this can be achieved with [minor changes](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops#examples) to the CI file.

PS: I am a PM for azure pipelines. I would be happy to help with the changes :)

**Comment by sokra** [comment]
This functionality relies on adding this information to commit messages. We don't do this, and we don't want to do that.

Anyway adding this list of commits to the release notes doesn't make much sense to me, as you can get this information from github or git anyway: https://github.com/Microsoft/vscode-react-native/compare/0.9.2...0.9.3

**Comment by raiyanalam** [comment]
You're right, however commits are just a pivoting criteria to show a list of changes. With each line there are links to issues that are referenced in the commit and  all this is in a more readable format.
I see your point though, if commit messages do not have adequate information, then collating release notes manually is the only way i believe. However, wouldn't it be nice to have a convention for commit messages so that they are more informative? Here are some standards repos use: [conventionalcommits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/), [Karma contribution guideline](http://karma-runner.github.io/4.0/dev/making-changes.html)

**Comment by sokra** [comment]
> However, wouldn't it be nice to have a convention for commit messages so that they are more informative? Here are some standards repos use: [conventionalcommits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/), [Karma contribution guideline](http://karma-runner.github.io/4.0/dev/making-changes.html)

Yeah, this was discussed before, but I don't really like it. It increases the cost of creating commits for contributors, merging PRs by maintainers. And as pushed commits should be treated as immutable, an incorrect commit message is not fixable.

It also forces to merge with squash, which throws away the commits of the original PR.

Instead I like to keep the original commits as written by the contributor and write useful release info manually.

**Comment by evilebottnawi** [comment]
Answer https://github.com/webpack/webpack/issues/9201#issuecomment-498586900, maybe we revisit this in future, thanks for issue
