### ISSUE TITLE
Using a function as module rule, as per documentation

### ISSUE THREAD

**Issue by kausters** [webpack/webpack#9204]
# Bug report

In the Webpack docs I noticed that it should support using a function to return a module rule (https://webpack.js.org/configuration/module/#useentry). This could've possibly solved a major issue I've been having in my project so I decided to give it a go.

**What is the current behavior?**

When using a function in the `rules` array in exactly the same way as in the sample, I get this error:

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[1] should be an object.
   -> A rule
```

**If the current behavior is a bug, please provide the steps to reproduce.**

This error occurs when using the function from the example in the docs, a no-op function, anything. Here's the example from the docs:

```
module.exports = {
  //...
  module: {
    rules: [
      {
        loader: 'file-loader',
        options: {
          outputPath: 'svgs'
        }
      },
      (info) => ({
        loader: 'svgo-loader',
        options: {
          plugins: [{
            cleanupIDs: { prefix: basename(info.resource) }
          }]
        }
      })
    ]
  }
};
```

**What is the expected behavior?**

The configuration should be considered to be valid.

The function should be called with the appropriate arguments.

**Other relevant information:**
webpack version:  4.32.2 (I though maybe this was a Webpack 5-specific feature which slipped into the docs without a warning, but didn't work on 5 too)
Node.js version: 10.15.3
Operating System: Windows 10
Additional tools: `webpack-cli@3.3.2`

**Comment by sokra** [comment]
Please read the documentation again. `Rule.use` can be a function, not the `Rule` itself.

**Comment by kausters** [comment]
Awesome, that worked. However the example in the docs does show `Rule` being the function.

**Comment by aariacarterweir** [comment]
The docs do indeed state that a UseEntry can be a function

**Comment by xxRockOnxx** [comment]
I'm using webpack@5.68.0 and neither UseEntry or Rule itself works if it's a function.
