### ISSUE TITLE
index.js is not resolved by dll reference plugin

### ISSUE THREAD

**Issue by yevhey** [webpack/webpack#9206]
* Operating System: macOS Mojave 10.14.3
* Node Version: v10.11.0
* NPM Version: 6.4.1
* webpack Version: 4.32.2

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Code
I created a repo to represent the problem: https://github.com/yevhey/dll-plugin-problem

But also the architecture is described below:
##### test.js
```js
  // resolve from 'components/beta/index' is fine
  import b from 'components/beta'; // not working

  alert(b);
```

##### webpack.config.js
```js
var path = require("path");
var webpack = require("webpack");

module.exports = {
  mode: 'development',
  entry: ['./test'],
  plugins: [
    new webpack.DllReferencePlugin({
      scope: 'components',
      manifest: require('./components.json')
    })
  ],
};
```

##### plugin.config.js
```js
var path = require("path");
var webpack = require("webpack");

module.exports = {
  mode: 'development',
  resolve: { alias: {} },
  entry: {
    components: ['./beta'],
  },
  output: {
    path: path.join(__dirname, '..'),
    library: '[name]'
  },
  plugins: [
    new webpack.DllPlugin({
      name: '[name]',
      path: path.join(__dirname, '..', '[name].json')
    })
  ]
};
```

##### components/beta/index.js
```
module.exports = "beta";
```

### Expected Behavior

It resolves `index.js` inside the specified folder without mentioning explicitly `/index.js`

### Actual Behavior

You need to write `/some-folder/index` to resolve the `index.js`

### How Do We Reproduce?

```
├── root folder                  
│   ├── components    
│   |   ├── beta
│   |   |   ├── index.js
│   |   ├── plugin.config.js
│   ├── webpack.config.js                                  
│   ├── test.js                                  
```

**Comment by evilebottnawi** [comment]
bump

**Comment by andrescst** [comment]
I would like to do this! Do you have any advice before starting with it?
I thought that maybe the issue could be related to the Module Resolution.

Do you have another idea or approach? It would be helpful!

**Comment by yevhey** [comment]
Honestly, I didn't think of the solution – sorry.

**Comment by andrescst** [comment]
No worries!
As a first step, I made tests to replicate the behavior from the repo you shared previously.
https://github.com/andrescst/webpack/tree/issue-9206
I'll be debugging it

**Comment by andruts** [comment]
The solution I found (not sure if the best) was to modify the manifest generation under the LibManifestPlugin file. 
Each time the manifest was generated it creates an object with a key for each javascript file you give as an entry.
In this case, you are only giving one so I assume that you want to be able to call the javascript file within the folder name and you only pretend to have one file per folder. So if the id for the javascript and the id on the manifest are the same, the id from the manifest gets modified and gets the name of the javascript file removed from it.

Older manifest generated
![Screen Shot 2020-01-02 at 14 20 47](https://user-images.githubusercontent.com/32336365/71690762-41fbe800-2d6b-11ea-8dee-eda9da3574f4.png)

New manifest generated
![Screen Shot 2020-01-02 at 14 20 02](https://user-images.githubusercontent.com/32336365/71690789-5344f480-2d6b-11ea-949f-4ebb324c5d84.png)

A restriction for this solution, the file under the folder should be called "index.js".

**Comment by andrescst** [comment]
The solution I found (not sure if the best) was to modify the manifest generation under the LibManifestPlugin file. 
Each time the manifest was generated it creates an object with a key for each javascript file you give as an entry.
In this case, you are only giving one so I assume that you want to be able to call the javascript file within the folder name and you only pretend to have one file per folder. So if the id for the javascript and the id on the manifest are the same, the id from the manifest gets modified and gets the name of the javascript file removed from it.

Older manifest generated
![Screen Shot 2020-01-02 at 14 20 47](https://user-images.githubusercontent.com/32336365/71690762-41fbe800-2d6b-11ea-8dee-eda9da3574f4.png)

New manifest generated
![Screen Shot 2020-01-02 at 14 20 02](https://user-images.githubusercontent.com/32336365/71690789-5344f480-2d6b-11ea-949f-4ebb324c5d84.png)

A restriction for this solution, the file under the folder should be called "index.js".

**Comment by wizardion** [comment]
> The solution I found (not sure if the best) was to modify the manifest generation under the LibManifestPlugin file.
> Each time the manifest was generated it creates an object with a key for each javascript file you give as an entry.
> In this case, you are only giving one so I assume that you want to be able to call the javascript file within the folder name and you only pretend to have one file per folder. So if the id for the javascript and the id on the manifest are the same, the id from the manifest gets modified and gets the name of the javascript file removed from it.
> 
> Older manifest generated
> ![Screen Shot 2020-01-02 at 14 20 47](https://user-images.githubusercontent.com/32336365/71690762-41fbe800-2d6b-11ea-8dee-eda9da3574f4.png)
> 
> New manifest generated
> ![Screen Shot 2020-01-02 at 14 20 02](https://user-images.githubusercontent.com/32336365/71690789-5344f480-2d6b-11ea-949f-4ebb324c5d84.png)
> 
> A restriction for this solution, the file under the folder should be called "index.js".

@andrescst, @yevhey  I found the way how to deal with the scope.
If you specify a scope option into `DllReferencePlugin` - then you need to be sure that your `DllPlugin` has the correct context, which refers to the folder where the files that you need to include.

For example: 
If the vendor's file (`vendor.js` for example) is under the `src` folder of the root project directory, at the first, you need to specify the context for the `DllPlugin` like this:
 ```
new webpack.DllPlugin({
      context: path.join(__dirname, './src/'),
     ...
```
then specify the scope for the `DllReferencePlugin`:
```
new webpack.DllReferencePlugin({
      scope: 'dll',
      ...
```
In this case, you will be able to include the file via the scope, just like this: `require("dll/vendor")`.
By default, the context of the `DllPlugin` refers to the root project directory, and if your src lib files aren't under that directory, you will have such errors `Module not found`. 

I figured this out by reading these sources: [DllReferencePlugin](https://github.com/webpack/webpack/blob/master/lib/DllReferencePlugin.js), [DelegatedModuleFactoryPlugin](https://github.com/webpack/webpack/blob/master/lib/DelegatedModuleFactoryPlugin.js)

**Comment by andrescst** [comment]
I'm trying to prove it on the code provided at the repo shared before and still not working.

 @wizardion, are my configuration files correct?

```javascript
var path = require("path");
var webpack = require("webpack");

module.exports = {
  mode: 'development',
  resolve: { alias: {} },
  entry: {
    components: ['./beta'],
  },
  output: {
    path: path.join(__dirname, '..'),
    library: '[name]'
  },
  plugins: [
    new webpack.DllPlugin({
      name: '[name]',
      path: path.join(__dirname, '..', '[name].json'),
      context: path.join(__dirname, './beta/')
    })
  ]
};
```

```javascript
var path = require("path");
var webpack = require("webpack");

module.exports = {
  mode: 'development',
  entry: ['./test.js'],
  output: {
    path: path.join(__dirname),
  },
  plugins: [
    new webpack.DllReferencePlugin({
      scope: 'components',
      manifest: require('./components.json')
    })
  ],
};

```

**Comment by wizardion** [comment]
@andrescst  Why do you need to store Webpack config file inside the `components` directory? Project configuration files suppose to be at the root project directory.

But according to the described code provided at the repo and the "build" command in the `package.json` - your attached configuration files are correct.
But there is one little thing:
- You need to include the index.js file under the directory `components/beta/`, not a folder `beta`
- And since the scope `components` is just reference to the folder _(context option in DllPlugin)_, the import should look like this: 
```
import b from 'components/index';
```
In this case, with your config files, the command `npm run build` will be working well.

**Comment by yevhey** [comment]
@wizardion config file is in the `components` directory just for the demo. Imagine everything inside this folder is a library exposed via webpack dll plugin and you want to import stuff from it without explicitly saying it's in the `index` file because react handles it by default and it's kinda unusual typing.

**Comment by wizardion** [comment]
@yevhey Everything that you import from this file has already built by another build command. With the first config, you build your library or common files that are being used by the second build. So for the HTML, it's just another .js file that includes all your stuff.

**Comment by juicelink** [comment]
https://github.com/webpack/webpack/issues/8648#issuecomment-455781259

adding `extensions: ['.js', '/index.js'] ` in DllReferencePlugin options did the job for me (the ability to import index.js with only typing folder name)

**Comment by alexander-akait** [comment]
Still valid for commonjs, but for ESM (in webpack v5) you need to write `@import 'components/beta/index.js'` (because ESM require it)
