### ISSUE TITLE
How does webpack handle require in logic?

### ISSUE THREAD

**Issue by moonlitnighta** [webpack/webpack#9208]
Some third-party libraries will introduce some modules in the logic, just like "enquire.js" below, but "enquire.js" does not exist in the current directory. In my opinion, if it parses it, it will get similar. "module not find" error, this code comes from 'antd/es/grid/row.js', I want to know how webpack handles dependencies like "enquire.js" during the build process? Or webpack will only Parsing top-level dependencies and ignoring dependencies in logic?
![image](https://user-images.githubusercontent.com/22231630/58652797-f1d92500-8346-11e9-88c8-f976ba80bd98.png)

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
