### ISSUE TITLE
when change target option from ’web‘ to 'electron-renderer',dev-server cannot reload after complited.

### ISSUE THREAD

**Issue by Bendjen** [webpack/webpack#9216]
# When change target option from ’web‘ to 'electron-renderer',dev-server cannot reload after complited.
# I use webpack node API to build development environment in Electron.
#The electron-app need node environment,so I changed target from 'web' to 'electron-renderer'

When target option is  'web',after edit and save code ,my electron window will reload by dev-server,everything is ok.

But if target is changed to 'electron-renderer'(I only changed this option),it cannot reload auto, need mannual operation(F5),and the page have been changed successfully. The change is work in page after I fresh the window myselfy ,but cannot reload auto by dev-server.

The development environment  can work with pressing F5 ,but just cannot reload by dev-server.
I wonder if the webpack-dev-server doesn't support the compiler which config's target is 'electron-renderer' or I just missed something to config?

my webpack config is:
![image](https://user-images.githubusercontent.com/20695625/58745931-931cc400-848a-11e9-9e89-3003602b52ae.png)

my dev-server config is:
![image](https://user-images.githubusercontent.com/20695625/58745940-ae87cf00-848a-11e9-8e71-ad4aa5dfce0c.png)

**Comment by evilebottnawi** [comment]
Fixed in latest webpack-dev-server version

**Comment by Bendjen** [comment]
thanks，It works in webpack-dev-server@3.5.1
