### ISSUE TITLE
Import file with same folder name ('./module' instead of './module/module')

### ISSUE THREAD

**Issue by gianlucadifrancesco** [webpack/webpack#9218]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
If I'm not wrong, currently, using `import module from './module'`, Webpack resolves it with this priority:
1. Checks if the file `./module.js` exists.
2. If not, checks if `./module/index.js` exists.

However, Webpack completely **ignores modules with the same name of the directory**, i.e. `./module/module.js` will always be ignored.
In fact, in this case you have to manually repeat the word "module":
`import module from './module/module'`.

**What is the expected behavior?**
Using `import module from './module'`, Webpack could resolve it with this priority:
1. Checks if the file `./module.js` exists.
2. If not, checks if `./module/index.js` exists.
3. **If not, checks if `./module/module.js` exists.**

Adding it as the "last" check, it won't break current projects, but it will only add a possibility.

Is this possible for Webpack to implement it? Would it be a good thing?

**What is motivation or use case for changing the behavior?**
My question/issue was the same as this: https://stackoverflow.com/questions/42870801/webpack-import-from-folder-folder-js-instead-of-folder-index-js. I saw many people using this folder/file structure, avoiding the `index.js`, so I thought it would be great to implement this.

I was just wondering if Webpack in this case, instead of giving an error, would check for the file with the same folder name, without installing any plugin (like https://www.npmjs.com/package/directory-named-webpack-plugin) or doing any "tricky" thing, like creating `package.json` to each folder, as suggested in the post I linked above.

What do you think? Am I missing something, or thinking wrongly?

Where appropriate, if you think it would be good, I'd like to contribute if possible! 🙂

(I'm currently using Webpack v4.28.3)

**Comment by sokra** [comment]
> Is this possible for Webpack to implement it? Would it be a good thing?

Yes, possible, as there is already a plugin doing so: https://www.npmjs.com/package/directory-named-webpack-plugin

But there is a spec for the resolving logic (inferred from node.js) so the default should not do this, as it will create incompatibility in the ecosystem.

**Comment by gianlucadifrancesco** [comment]
@sokra Thanks for the immediate response!

Yes, I already mentioned that plugin, in fact I was talking about a “by default” feature.

However, I understood, I assumed it.
Thanks!
