### ISSUE TITLE
ImportLoaders of css-loader  does not work

### ISSUE THREAD

**Issue by yh284914425** [webpack/webpack#9219]
# Bug report

**What is the current behavior?**
index.js
```
import './index.scss'
```

index.scss
```
@import './a.scss';

body {
    .dog {
        width: 300px;
        height: 300px;
    }
}
```
a.scss
```
body {
  .dog {
    transform: translate(100px, 100px);
  }
}
```
The option importLoaders allows you to configure how many loaders before css-loader should be applied to @imported resources.

```
module.exports = {
  module: {
    rules: [
      {
        test: /\.css$/i,
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              importLoaders: 0, // 0 => no loaders (default); 
            },
          },
          'postcss-loader',
          'sass-loader',
        ],
      },
    ],
  },
};
```
When I configured **importLoaders: 0** ，Why is the content inside a.scss prefixed?
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

no loader before css-loader should be applied to a.scss.

**Other relevant information:**
webpack version: 4.31.0
Node.js version: v11.12.0
Operating System: macos
Additional tools:

**Comment by sokra** [comment]
@webpack-bot move to webpack-contrib/css-loader
