### ISSUE TITLE
How to I use a CommonJS loader first rather than an AMD loader?

### ISSUE THREAD

**Issue by jhudson8** [webpack/webpack#922]
I'm trying to load [exoskeleton](http://exosjs.com/) and it has an [AMD dependency on jquery](https://github.com/paulmillr/exoskeleton/blob/master/exoskeleton.js#L13) but [this isn't a hard dependency](https://github.com/paulmillr/exoskeleton/blob/master/exoskeleton.js#L19) which is checked using try/catch if the CommonJS init block is executed.

It seems that webpack uses an AMD loader by default (or at least first) because ```require.amd``` is a truthy value.  How can I use a CommonJS loader instead of AMD?

I've tried the [amd: false webpack config](http://webpack.github.io/docs/configuration.html#amd) and that didn't seem to work.

Also, I believe I would also have to use this settings as well, correct?
```
    plugins: [
        new webpack.IgnorePlugin(/^jquery$/)
    ],
```

Thank you very much.

**Comment by sokra** [comment]
http://webpack.github.io/docs/shimming-modules.html#broken-amd

**Comment by jhudson8** [comment]
If anyone else has this issue, I wanted a webpack.config.js configuration rather than one that must be used with the require statement itself.  I did it using the following config
```
    plugins: [
        // ignjore "jquery" because exoskeleton will try to load it
        new webpack.IgnorePlugin(/^jquery$/)
    ],
```
and
```
        loaders: [
            { test: /exoskeleton\.js$/,    loader: "imports?define=>false"},
            { test: /backbone\.js$/,    loader: "imports?define=>false"},
            ...
```
And you must install https://github.com/webpack/imports-loader

**Comment by dbkaplun** [comment]
@sokra is there an updated link? That one is a 404.

**Comment by montogeek** [comment]
@dbkaplun Try https://webpack.js.org/guides/shimming/, there is a note regarding AMD at the end of the page.

**Comment by montogeek** [comment]
From the wiki https://github.com/webpack/docs/wiki/shimming-modules#broken-amd (Last update: August 22, 2017)
