### ISSUE TITLE
Terminal progress on multiple lines if line wraps 

### ISSUE THREAD

**Issue by ChristopherKiss** [webpack/webpack#9221]
# Bug report

**What is the current behavior?**
When the terminal is small enough so that the line of progress would wrap, it will create a new line instead of overwriting the current line of progress.

This works fine if the terminal is wide enough to fit the entire line on a single row without wrapping.

**If the current behavior is a bug, please provide the steps to reproduce.**
I'm getting this issue with angular cli:
1. create a new angular project `npm install -g @angular/cli` and `ng new test`
2. make the terminal small enough so that text wraps to a new line
3. run `ng serve` to get a progress output
4. observe that the progress is output on multiple lines
![image](https://user-images.githubusercontent.com/24984762/58792697-04e64080-8638-11e9-9ad4-70e75b84db13.png)
5. make the terminal large enough so that text does NOT wrap to a new line
6. run `ng serve` to get a progress output
7. observe that the progress did not output on multiple lines but overwrote the current line of progress
![image](https://user-images.githubusercontent.com/24984762/58792747-22b3a580-8638-11e9-8120-4685e83e640c.png)

**What is the expected behavior?**
Progress reported should always overwrite the current line instead of creating a new line if the line would wrap multiple lines.

**Other relevant information:**
webpack version:  4.3 I believe is what Angular uses.
Node.js version: 12.3.1 (also occurs on v11)
Operating System: Windows 10, build: 17763.259
Additional tools: angular cli

I can reproduce this in VS Code and Powershell directly.

I have reported this on VS Code, https://github.com/microsoft/vscode/issues/74695 they say the issue is not them, I have tried with conpty on and off.

I also reported it on angular cli: https://github.com/angular/angular-cli/issues/14623 they also say the issue is not them.

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo, looks something wrong in your environment

**Comment by ChristopherKiss** [comment]
@evilebottnawi,

This issue occurs on my repo here https://github.com/quick-foot/vision.

It's almost a bare bones Angular 8 app.

My VS Code settings:

```
{
    "editor.fontSize": 12,
    "editor.lineHeight": 23,
    "editor.detectIndentation": true,
    "editor.minimap.enabled": false,
    "editor.roundedSelection": false,
    "html.autoClosingTags": false,
    "terminal.integrated.fontSize": 13,
    "terminal.integrated.cursorStyle": "line",
    "workbench.startupEditor": "none",
    "workbench.statusBar.feedback.visible": false,
    "workbench.panel.defaultLocation": "right",
    "debug.toolBarLocation": "docked",
    "explorer.openEditors.visible": 0,
    "telemetry.enableTelemetry": false,
    "telemetry.enableCrashReporter": false,
    "highlight-matching-tag.highlightSelfClosing": true,
    "git.confirmSync": false,
    "gitlens.blame.heatmap.enabled": false,
    "gitlens.codeLens.enabled": false,
    "window.titleBarStyle": "custom",
    "editor.accessibilitySupport": "off",
    "typescript.updateImportsOnFileMove.enabled": "never",
    "javascript.updateImportsOnFileMove.enabled": "never",
    "npm-intellisense.packageSubfoldersIntellisense": true,
    "npm.enableScriptExplorer": true,
    "highlight-matching-tag.styles": {
        "opening": {
            "full": {
                "custom": {
                    "backgroundColor": "rgba(220, 220, 220, 0.15)"
                }
            },
            "left": {
                "custom": {
                    "borderWidth": "0px"
                }
            },
            "right": {
                "custom": {
                    "borderWidth": "0px"
                }
            }
        }
    },
    "git.autofetch": true,
    "eslint.validate": [
        "javascript",
        {
            "language": "typescript",
            "autoFix": true
        }
    ],
    "terminal.integrated.shell.windows": "C:\\\\Windows\\\\System32\\\\WindowsPowerShell\\\\v1.0\\\\powershell.exe",
    "terminal.external.windowsExec": "C:\\\\Windows\\\\System32\\\\WindowsPowerShell\\\\v1.0\\\\powershell.exe",
    "vsicons.presets.foldersAllDefaultIcon": true,
    "workbench.iconTheme": "vscode-icons",
    "vsicons.projectDetection.disableDetect": true,
    "terminal.integrated.windowsAllowConptyTasks": true
}

```

Workspace settings:
```
{
    "search.exclude": {
        "**/node_modules": true,
        "**/build": true,
        "**/coverage/**/*": true
    },
    "[yaml]": {
        "editor.tabSize": 4
    },
    "files.insertFinalNewline": true,
    "files.trimTrailingWhitespace": true,
    "editor.formatOnSave": true,
    "editor.tabSize": 4,
    "editor.detectIndentation": false,
    "editor.codeActionsOnSave": {
        "source.fixAll.tslint": true
    },
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "html.format.wrapAttributes": "force-aligned",
    "html.format.wrapLineLength": 100,
    "html.format.endWithNewline": true,
    "tslint.alwaysShowRuleFailuresAsWarnings": false,
    "prettier.singleQuote": true,
    "prettier.tabWidth": 4,
    "prettier.printWidth": 100,
    "prettier.proseWrap": "always",
    "prettier.htmlWhitespaceSensitivity": "ignore",
    "prettier.disableLanguages": ["html", "angular"],
    "prettier.tslintIntegration": true,
    "typescript.tsdk": "node_modules\\typescript\\lib"
}
```

**Comment by sokra** [comment]
Send a PR

**Comment by Bkucera** [comment]
I've got a PR open to trim progress text to `stderr.columns` if it exists, which should fix the problem
