### ISSUE TITLE
Overloading the term "Environment Variable" causing unnecessary confusion

### ISSUE THREAD

**Issue by Sequoia** [webpack/webpack#9223]
# Bug report

Webpack **function type** configurations take, as a first argument, a parameter named `env` & the documentation refers to this as ["environment variables"](https://webpack.js.org/guides/environment-variables)

**What is the expected behavior?**

This parameter is set via [Environment Variables](https://en.wikipedia.org/wiki/Environment_variable).

**What is the current behavior?**

This parameter (`env`) has **nothing to do with environment variables** & is actually set via command line switches.

**Why is this a problem?**

Reusing a term that's already used in this context needlessly misdirects programmers attempting to understand webpack configuration files, leading to confusion and wasted time. Just as it would be a bad idea to call webpack an "operating system" due to the confusion it would cause, it's bad to use the term "Environment Variables" to refer to a command line argument. 

This is especially so because actual Environment Variables can be and often are **also used** to configure webpack. In such a case, calling at CLI parameter an "environment variable" is almost certain to cause confusion when two programmers attempt to communicate about a webpack configuration.

If I ask how another programmer is switching webpack behaviour on staging & production and they reply "I use an Environment Variable", **how could I know which method they are referring to?.**

**Proposals**

1. Rename this `webpackEnv` in the code examples & replace "Environment Variables" with "Webpack Environment" in the docs _or_
2. Simply eliminate this parameter. It is also available in `argv` so `const env = argv.env` at the top of a configuration could fully replace the existing API, with the added benefits of increasing clarity & removing a needless parameter for users who use actual environment variables.

**Comment by evilebottnawi** [comment]
Bump

**Comment by Sequoia** [comment]
Is a pull request welcome here? May require a major version bump; is there a major release scheduled on the horizon?

Or am I missing something and this is actually a necessary feature? Thanks,

**Comment by sokra** [comment]
Yep you are right. The documentation should not call it "environment variables". Not sure how this happened. Instead `--env` should be better called `env option` or `env CLI option`.

> Using `argv`

This is very specific for CLI usage and also depends on the CLI option parsing lib. It also makes it possible to depend on other CLI arguments.

I think it was a mistake to expose `argv` to the configuration. I think it's better to make it very explicit which CLI arguments are exposed to the configuration.

> Using environment variables

My opinion here is similar. Using environment variables makes is less explicit which flags the configuration depends on. It's also more difficult to pass them when invoking the configuration from node.js

---

I also want to keep the use case calling a configuration file from node.js via script or with other CLI tools:

``` js
const config = require("./webpack.config.js")({
  mode: "production",
  product: "blah"
  // with types in webpack.config.js/ts you have completion and type check here
});
// can be called multiple times with different arguments
```

vs

``` js
process.env.MODE = "production";
process.env.PRODUCT = "blah";
// no completion, no type checks for typos
const config = require("./webpack.config.js");
// To call this multiple times you need to clear require.cache to require it again
```

**Comment by Sequoia** [comment]
To be honest I'm not sure how to verify this because I'm struggling to find documentation for the arguments passed to a webpack configuration function. I have one (working) that looks like this:

```js
module.exports = (env, argv = {}) => {
// ...
```

Given this API, would it not be possible for you to load your webpack config from node.js thus?

```js
const config = require("./webpack.config.js")(null, {
  mode: "production",
  product: "blah"
});
```

As an exported function, I don't see why the arguments could only be passed by CLI. Am I missing something?
