### ISSUE TITLE
Split chunks for styles css after migrating v3 -> v4

### ISSUE THREAD

**Issue by blackswanny** [webpack/webpack#9224]
# Bug report

I migrated from webpack 3 to webpack 4, and all good except my CSS is no longer working. I switched to MiniCssExtractPlugin of course, however, I debugged and found that right now my chunks of css are not included in my `style.css` file, like it was before. When I remove chunks at all , i see `style.css` is filled with my styles, but if a leave chunks, it's almost empty. I see that I generate chunks like [id].style.css, which works as expected, but in webpack 3 they still bundled into one file `style.css`. 
I use scss and import it in jsx files. debugging webpack I see that all assets\chunks are full with css styles. So something happens at the very last step, when they are rendered into file. I need this `style.css` file as I use some scaffold, which is designed to expect this only one file for stylesheets.
I also need `bootstrap` group of chunks as it's expected by that scaffold as `bootstrap.js`, so I can't remove all chunks. Can I switch off chunks only for css styles as alternative? Or I have to understand if it's a bug or it's a wrong config

My config is below

```
{ optimization: {
      splitChunks: {
        name: 'bootstrap',
        minChunks: Infinity,
        cacheGroups: {
          bootstrap: {
            filename: '[name].[chunkhash].js'
          },
          styles: {
            name: 'styles',
            test: /\.(css|sass|scss)$/,
            chunks: 'all'
          }
        }
      }
    }, plugins: [
      new MiniCssExtractPlugin({ filename: 'style.css' })
   ], rules: [
       {
          test: /\.(sa|sc|c)ss$/,
          use: [MiniCssExtractPlugin.loader,  'css-loader', 'sass-loader']
       }
   ] }
```

**What is the current behavior?**

Chunk group of styles does not bundle in one file after migrating from v3 to v4, and migrating from CommonsChunkPlugin to SplitChunksPlugin, and from extractTextWebpackPlugin to MiniCssExtractPlugin.

**If the current behavior is a bug, please provide the steps to reproduce.**

It might be a bug as migration from v3 to v4 was made accurately according to manual, or it's a wrong config, which needs to be fixed

**What is the expected behavior?**

Chunk group of styles should bundle in one file as it was before.

**Other relevant information:**
webpack version:  4.28.4
Node.js version:  8.15.0
Operating System:  Mac OS 10.14.3

**Comment by ovaldi** [comment]
+1

**Comment by docccdev** [comment]
+1

**Comment by evilebottnawi** [comment]
Somebody can create example for describe in issue what you actually have and what is expected

**Comment by yft** [comment]
Me too. And then I tried the following code:
```js
styles: {
    name: 'styles',
    chunks: 'all',
    enforce: true,
    test(module) {
    	return module.constructor.name === 'CssModule';
    }
}
```
It works. All css are extracted into one file. But I don't know why. I hope it's helpful for you.

**Comment by yft** [comment]
This is an [example](https://github.com/yft/webpack-9224-example). Looking forward to someone to explain.

# 1

```js
styles: {
    name: 'styles',
    chunks: 'all',
    enforce: true,
    test: /\.s?css$/
}
```

|  File                                   | Size             | Gzipped |
|--|--|--|
|  dist\js\app.7d99c416.js                | 112.78 KiB       | 39.94 KiB |
|  dist\js\chunk-75899478.9abf9418.js     | 2.82 KiB         | 0.92 KiB |
|  dist\js\about.9c70d2df.js              | 0.54 KiB         | 0.34 KiB |
|  **dist\css\app.05b0fd4b.css**          | 0.25 KiB         | 0.19 KiB |
| **dist\css\chunk-75899478.2fea4303.css** | 0.13 KiB         | 0.13 KiB |
|  **dist\css\about.4b84574e.css**        | 0.02 KiB         | 0.04 KiB |

# 2

```js
styles: {
    name: 'styles',
    chunks: 'all',
    enforce: true,
    test(module) {
    	return module.constructor.name === 'CssModule';
    }
}
```

| File                                  | Size               | Gzipped |
|--|--|--|
| dist\js\app.711776c0.js               | 112.14 KiB         | 39.73 KiB |
| dist\js\chunk-16c147d7.b824e22f.js    | 2.82 KiB           | 0.92 KiB |
| dist\js\about.2a8e9185.js             | 0.54 KiB           | 0.34 KiB |
| dist\js\styles.ce7f908e.js            | 0.12 KiB           | 0.11 KiB |
| **dist\css\styles.d477b25d.css**      | 0.40 KiB           | 0.27 KiB |
