### ISSUE TITLE
Hot reloading breaks the app. Final loader didn't return a Buffer or String

### ISSUE THREAD

**Issue by MarchWorks** [webpack/webpack#9228]
# Bug report

**What is the current behavior?**
Running the app initially works just fine but when changing a value in the loaded file the app breaks

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/MarchWorks/cutom-webpack-loader-hmr

The loader
```
const devalue = require('devalue')
const vm = require('vm');

module.exports = async function(source) {
    const callback = this.async()
    this.addDependency(this.resourcePath);
    const sandbox = {
    	require,
    	module
    }
    vm.createContext(sandbox);
	const mod = vm.runInContext(source, sandbox)
    const result = await mod(this.resourceQuery.replace('?name=', ''))
    console.log(result)
    return callback(null, `export default ${devalue(result)}`);
}
```
The loaded file
```
      const data = {
      	a: ()=> 8885555,
      	b: ()=> 55444
      }
      
      module.exports = name => {
        return data[name] && data[name]()
      }
```
Index.js
```
const a = require('./../data.js?name=a');

console.log(a)
```
Webpack.config
```
const path = require('path');
const webpack = require('webpack');

module.exports = {
  mode: 'development',
  context: path.join(__dirname, 'js'),
  entry: [
    'webpack-hot-middleware/client?path=/__webpack_hmr&timeout=20000',
    './index.js',
  ],
  output: {
    path: path.join(__dirname, 'www'),
    filename: 'bundle.js',
    publicPath: '/assets/',
  },
  module: {
    rules: [
      {
        test: /data\.js$/,
        use: [
          {
            loader: path.resolve('data-loader.js'),
            options: {}
          }
        ]
      }
    ]
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoEmitOnErrorsPlugin(),
  ],
};
```

**What is the expected behavior?**
The app should hot reload without breaking

**Other relevant information:**
webpack version:  4.32.2
Node.js version: 10.15.3
Operating System: Windows 10

PS: I already posted this in stackoverflow and gitter.im/webpack/webpack but without luck

**Comment by sokra** [comment]
When executing `data.js` you pass `module` from the loader. `data.js` overrides `module.exports`. As you passed `module` from the loader you are **overriding `module.exports` of the loader**. This corrupts the loaders. Next time the function exposed from `data.js` is the loader and called with the `source`. It returns undefined and webpack complains

**Comment by MarchWorks** [comment]
Thanks, I am not sure if it's the best way but I solved it by doing `const m = require('module')` and passing it to `sandbox`
