### ISSUE TITLE
[BUG] logLevel does not turn off

### ISSUE THREAD

**Issue by iMegaMaximus2** [webpack/webpack#9229]
i use this config

```javascript
 { 
    devServer: {
       contentBase:  [ 'C:\\localhost\\CallBot\\static',  'C:\\localhost\\CallBot\\dist\\renderer-dll' ],
       host: 'localhost',
       port: '51980',
       hot: true,
       overlay: true,
       stats: 'errors-only', // this
       clientLogLevel: 'none'  // this
    },

    stats: 'errors-only' // this
 }

```

and i even use this in main file
![image](https://user-images.githubusercontent.com/49617181/58924305-0b65dc80-874c-11e9-887e-cae7f1d762fa.png)

but i get 

![image](https://user-images.githubusercontent.com/49617181/58924357-3e0fd500-874c-11e9-8cd6-ed6f8b9e75fe.png)

===
webpack 4.33.0
webpack-dev-server 3.5.1

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Also it is not `webpack-dev-server` repo
