### ISSUE TITLE
Control over code splitting bundles

### ISSUE THREAD

**Issue by jlchereau** [webpack/webpack#923]
I am trying to handle localization and theming using code splitting in the following way.

A culture (herebelow ```./js/cultures/app.culture.de.js```) merges kendo UI cultures with a nodeJS i18n JSON file to make localized strings available client-side, as follows:

```js
(function(f, define){
    define(['./../kendo/cultures/kendo.culture.de-DE.js', './../kendo/messages/kendo.messages.de-DE.js'], f);
})(function() {

    (function () {
        var app = window.app || (window.app = { cultures: {} });
        app.cultures['de'] = require('../../culture/de.json');
    }());

    return window.app;

}, typeof define == 'function' && define.amd ? define : function(_, f){ f(); });
```

The HTML page has a select which is wired to the following event handler:

```js
$('#locale').change(function(e) {
    var locale = $(e.target).val() ;
    require.ensure([], function(require) {
        require('./cultures/app.culture.' + locale + '.js');
        window.app.localize(locale);
     });
});
```

Whatever the options I use in ```webpack.config.js```, all my cultures (de, en, fr) are bundled together in a file that starts as follows:

```js
webpackJsonp([3,5,6,7,8],[
/* 0 */,
/* 1 */,
/* 2 */,
/* 3 */,
/* 4 */
/***/ function(module, exports, __webpack_require__) {

	var map = {
		"./app.culture.de.js": 6,
		"./app.culture.en.js": 7,
		"./app.culture.fr.js": 8
	};
```

I have tried forcing a separate bundle for each culture with:

```js
var dePlugin =
    new webpack.optimize.CommonsChunkPlugin('de.js', ['./js/cultures/app.culture.de.js']);
```

but in this case ```de.js``` looks as follows:

```js
webpackJsonp([5,6,7,8],[]);
```

How can I enforce one js output file per culture concatenating:
- ./../kendo/cultures/kendo.culture.de-DE.js,
- ./../kendo/messages/kendo.messages.de-DE.js,
- ../../culture/de.json?

**Comment by sokra** [comment]
``` js
$('#locale').change(function(e) {
    var locale = $(e.target).val() ;
    require('bundle!./cultures/app.culture.' + locale + '.js')(function() {
        window.app.localize(locale);
     });
});
```

**Comment by jlchereau** [comment]
wunderbar!

How can I get a better name than 4.4.js, 5.5.js, .. for my i18n bundles?

**Comment by sokra** [comment]
`output.chunkFilename = "[name].js"` and `bundle?name=[name]!./culture...` should give you better names.

**Comment by sokra** [comment]
but the chunk name is usually not important...

**Comment by jlchereau** [comment]
Many thx.
