### ISSUE TITLE
Unable to import webpack-bundled UMD library as an ES6 import

### ISSUE THREAD

**Issue by feizhen** [webpack/webpack#9230]
same issue like that: [Unable to import webpack-bundled UMD library as an ES6 import](https://stackoverflow.com/questions/54818030/unable-to-import-webpack-bundled-umd-library-as-an-es6-import)

any anwser for that?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
