### ISSUE TITLE
clean-webpack-plugin

### ISSUE THREAD

**Issue by babyxu51521** [webpack/webpack#9231]
const clean_webpack_plugin  = require("clean-webpack-plugin");
new clean_webpack_plugin(["dist"]),
error clean_webpack_plugin   is not a constructor

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please open issue in `clean-webpack-plugin`
