### ISSUE TITLE
Unable to import webpack-bundled UMD library as an ES6 import

### ISSUE THREAD

**Issue by feizhen** [webpack/webpack#9232]
**Do you want to request a *feature* or report a *bug*?**
[BUG]

same issue: https://stackoverflow.com/questions/54818030/unable-to-import-webpack-bundled-umd-library-as-an-es6-import

I've authored a javascript library using Webpack. The entrypoint `someClass.js` looks like this:
```js
import x from './x'
/* several more imports here */

class SomeClass {}

export default SomeClass;
```
My webpack config that bundles this library is as follows:
```js
module.exports = {
    entry: './someClass.js',
    output: {
        path: __dirname,
        filename: 'lib.js',
        library: 'lib',
        libraryTarget: 'umd',
    },
}
```
I then import the generated `lib.js` into a simple `index.html` that is defined as follows:
```html
<!DOCTYPE html>
<html>
<head>
</head>

<body>
<script src="app.js" type="module"></script>
</body>
</html>
```
In `app.js`, I simply try to import the file as follows:
```js
import  * as lib from './lib.js';

console.log(lib);

// Output: Module {Symbol(Symbol.toStringTag): "Module"}   Symbol(Symbol.toStringTag): "Module"
```
**What is the current behavior?**

The only way I can access my library's default export `SomeClass` is if I do a global import statement in `app.js` as follows, which sets lib as an object on window:
```js
import './lib.js';
console.log(window.lib);

// Output: Module {default: ƒ, __esModule: true, Symbol(Symbol.toStringTag): "Module"} default: class SomeClass_SomeClass
```

**What is the expected behavior?**

I don't want my class to available at the global window, as it makes it tough to modularise my code.

I also want to be able to use this library in a variety of places on the web (vue app, react app, standalone html files, etc), and so want to minimize dependencies.

Is there anything I can do to import the module as an es6 import?

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

webpack version: 4.32.2

**Comment by sokra** [comment]
UMD doesn't support ESM

**Comment by feizhen** [comment]
@sokra what if i use babel-loader before output? does it work?

**Comment by sokra** [comment]
UMD doesn't support consuming as ESM. You can't use an UMD bundle with native browser `import`.

**Comment by Mati365** [comment]
@sokra but it is also returning wrong data when I use webpack / babel es6 parser that parses that imports :/

**Comment by yexiaofan** [comment]
Have you solved the problem?

**Comment by doums** [comment]
I just encountered exactly the same problem and I am currently stuck.
My webpack config:
```
const path = require('path')
const { CleanWebpackPlugin } = require('clean-webpack-plugin')

module.exports = {
  entry: {
    app: './src/index.js'
  },
  output: {
    filename: 'pakooo.js',
    path: path.resolve(__dirname, 'dist'),
    library: 'pakooo',
    libraryTarget: 'umd'
  },
  plugins: [
    new CleanWebpackPlugin(),
  ],
  module: {
    rules: [
      {
        test: /\.(js|jsx|mjs)$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        options: {
          cacheDirectory: true,
          presets: [
            [
              '@babel/preset-env',
              {
                useBuiltIns: 'entry',
                corejs: 3
              }
            ],
            '@babel/preset-react'
          ],
          plugins: [
            '@babel/plugin-proposal-export-default-from'
          ]
        }
      },
     ...
```
The source entry point of my lib `src/index.js` looks as follow:
```
export Button from './component/button'
export Input from './component/input'
```
Then I compile with webpack and the code is nicely transpiled through the babel-loader, then blunded as expected in the "dist" directory:
The build produces 2 files and their source-map:
- pakooo.js
- 1.pakooo.js (the vendors bundle)

In my `package.json` I set properly the `main` key to target the builded&transpiled bundle:
```
"main": "./dist/pakooo.js"
```

But now when I try to do something like this from another package:
```
import { Button }  from 'pakooo'
```

**Comment by privateOmega** [comment]
@sokra 
>UMD doesn't support consuming as ESM. You can't use an UMD bundle with native browser import.

Is it at all possible to transform UMD module to ESM or use UMD to be used with import statements?

**Comment by feizhen** [comment]
@doums maybe the`output.globalObject`  will help https://webpack.js.org/configuration/output/#outputglobalobject

**Comment by Mati365** [comment]
@yexiaofan Try add `module` entry to lib package.json that links to `ES` build, webpack should build it.

**Comment by seda1094** [comment]
I have changed
in  package.json 

"presets": [
      [
        "@babel/preset-env",
        {
          "loose": true,
          "modules": "umd" <-------------------------
        }
      ]
    ]
    
    and in webpack.config.js
    my settings are 
    
    {
        test: /\.js$/,
        exclude: /(node_modules)/,
        use: {
          loader: "babel-loader"
        }
      },
      
      and exporting the global object with module.exports 
      
      It works for me :)

**Comment by mdibenedetto** [comment]
> I have changed
> in package.json
> 
> ```
> "presets": [
>       [
>         "@babel/preset-env",
>         {
>           "loose": true,
>           "modules": "umd" <-------------------------
>         }
>       ]
>     ]
> ```
> 
> ```
> and in webpack.config.js
> my settings are 
> ```
> 
> ```
> {
>      test: /\.js$/,
>      exclude: /(node_modules)/,
>      use: {
>        loader: "babel-loader"
>      }
>    },
> ```
> 
> ```
>   and exporting the global object with `module.exports `
>   
>   It works for me :)
> ```

Hi i @seda1094 
could you share your webpack config please ?
