### ISSUE TITLE
Integrating the external local module into existing project

### ISSUE THREAD

**Issue by srikanthsunkari** [webpack/webpack#9233]
I have been trying to integrate an external react-native-sdk local module which contains few UI components, and it exports these components just like an npm module. When I try to use these components in an existing react native web project, the imported components are an undefined component when checked in logs. Created application code repository for the reproduction of issue in the below section,

[**Demo Application Code**](https://github.com/srikanthsunkari/react-native-web-sdk/)

> **ERROR:**

```
←→1 of 2 errors on the page
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `LoadMore`.
▶ 29 stack frames were collapsed.
./src/index.js
E:/React_Native/react-native-web-demo/rn-web-sdk/reactNativeSample/src/index.js:2
  1 | 
> 2 | import { AppRegistry } from "react-native";
  3 | // import App from "./App";
  4 | import LoadMore from './LoadMore'
  5 | // export default App;
View compiled
__webpack_require__
E:/React_Native/react-native-web-demo/rn-web-sdk/reactNativeSample/webpack/bootstrap:782
  779 | };
  780 | 
  781 | // Execute the module function
> 782 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  783 | 
  784 | // Flag the module as loaded
  785 | module.l = true;
View compiled
fn
E:/React_Native/react-native-web-demo/rn-web-sdk/reactNativeSample/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
0
http://localhost:3000/static/js/main.chunk.js:68:18
__webpack_require__
E:/React_Native/react-native-web-demo/rn-web-sdk/reactNativeSample/webpack/bootstrap:782
  779 | };
  780 | 
  781 | // Execute the module function
> 782 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  783 | 
  784 | // Flag the module as loaded
  785 | module.l = true;
View compiled
checkDeferredModules
E:/React_Native/react-native-web-demo/rn-web-sdk/reactNativeSample/webpack/bootstrap:45
  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | return result;
View compiled
Array.webpackJsonpCallback [as push]
E:/React_Native/react-native-web-demo/rn-web-sdk/reactNativeSample/webpack/bootstrap:32
  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;
View compiled
(anonymous function)
http://localhost:3000/static/js/main.chunk.js:1:57
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
```

> **Expected Behavior:** 

	I should be able to display the proper component when I use any component from react-native-sdk. 
	

> **Actual Behavior:** 

         The imported component is undefined when I use any component from react-native-sdk. 

Note: react-native-sdk module just export a Animated.View and returns the same. It doesn't contain any native module dependencies

> **Environment:**

Windows 10,
Device: browser
Browser: chrome
webpack : "^4.29.0",
webpack-cli : "^3.2.1",
webpack-dev-server : "^3.1.14"
react-native-web : "^0.10.0-alpha.3",
react : "^16.7.0",
react-dom : "^16.7.0",
react-native : "0.58.0",

As I am new to the webpack and react-native-web I have no idea why is this happening. are the external local module integration is supported with webpack and react-native-web?
Any help would be most helpful.

**Comment by evilebottnawi** [comment]
Please use issue template otherwise your issue was closed, thanks

**Comment by srikanthsunkari** [comment]
@evilebottnawi updated the issue with the template.

**Comment by evilebottnawi** [comment]
@srikanthsunkari still can't find there i can reproducible problem

**Comment by srikanthsunkari** [comment]
Hi Evilebot Tnawi,
    I have placed the demo application on the issue, for the reproduction.
Can you please once.
Thank you,
Srikanth,
Ph 837 407 6460.
