### ISSUE TITLE
Full page reload on syntax errors during hot reloads

### ISSUE THREAD

**Issue by andyhall** [webpack/webpack#9235]
* Operating System: Mac 10.13.6
* Node Version: 11.8.0
* NPM Version: 6.5.0
* webpack Version: 4.29.0
* webpack-dev-server Version: 3.1.14

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js
{
	mode: 'development',
	devServer: {
		contentBase: 'build/',
		hot: true,
	},
	plugins: [
		new webpack.HotModuleReplacementPlugin(),
	],
}
```

```js
// get a foo
var foo = require('./foo')

if (module.hot) {
    module.hot.accept('./foo', function () {
        // clean up the old foo
        foo.dispose()
        // replace it with a new one
        foo = require('./foo')
    })
}
```

### Actual Behavior

Above is a super-minimal version of my HMR setup - it works fine, whenever `foo.js` changes it gets hot reloaded, so far so good.

The problem occurs when there's some kind of error in the HMR handler - for example, a syntax error inside `foo.dispose()`. When that's the case, then whenever you edit `foo.js`, the HMR handler executes and dev-server catch the syntax error, and then fully reloads the page. This prevents the developer from knowing there's a syntax error - it just looks like HMR has stopped working.

### Expected Behavior

WDS should allow the error to be caught by the browser so the developer can see it - or if there's a really good reason not to, I guess have an option to prevent the automatic reloading?

### For Bugs; How can we reproduce the behavior?

As far as I can tell any kind of syntax error inside the HMR event handler function causes this.

Thanks!

**Comment by sokra** [comment]
If an error occurs in the accept handler, this this treated as HMR failed and full-reload is the fallback.

The error should be logged to the console.

This seem to me the correct behavior. Not reloading and leaving the app in a broken state seems wrong to me

**Comment by evilebottnawi** [comment]
> Second, reloading makes it harder to fix the problem because it prevents the developer from getting a stack trace / debugger / etc, as they would if WDS allowed the browser to handle the exception.

Sounds reasonable

/cc @sokra Maybe we can change behavior here?

**Comment by sokra** [comment]
> If an HMR handler is throwing exceptions, I don't think it makes sense for WDS to treat that as a temporary issue that doing a full reload might fix.

It indeed makes sense, because on full-reload accept handler code doesn't run.

> If an app has a bug in its HMR handling that's something the developer needs to see, but reloading the page covers it up and makes it harder to fix.

That's why the error is logged to the console. Make sure to not clear console on reload:

![image](https://user-images.githubusercontent.com/1365881/59157202-e1435000-8aa6-11e9-957b-3bc024a53a20.png)

> Second, reloading makes it harder to fix the problem because it prevents the developer from getting a stack trace / debugger / etc, as they would if WDS allowed the browser to handle the exception.

You get a stack trace in the console. You may even break on errors in devtools if you like to.

Note that there are two HMR mode for WDS: hot and hot-only. hot does full-reloads, while hot-only never does full-reloads and instead only print errors to console.

**Comment by andyhall** [comment]
Ohhh, I see what you mean. I had no idea that setting existed, and it might be reasonable to assume some developers may not know that certain HMR problems cannot be fixed unless it's enabled. Perhaps a log should also be written to stdout where it would be visible by default?

**Comment by sokra** [comment]
> Perhaps a log should also be written to stdout where it would be visible by default?

Possible but a bit weird, since the error occurs in the browser.

**Comment by andyhall** [comment]
> Possible but a bit weird, since the error occurs in the browser.

Again, from the developer's perspective the error here is "why is HMR intermittently failing?", and I think it would make sense for WDS to answer that question in stdout. It wouldn't necessarily make sense to log the content of the exception, but it would make sense to report why a full reload is being done.

The alternative is that the exception is (for default browser config) completely hidden from the user unless they already know where to look.

**Comment by wizulus** [comment]
This comment was the solution for me:

> Note that there are two HMR mode for WDS: `hot` and `hot-only`. `hot` does full-reloads, while `hot-only` never does full-reloads and instead only print errors to console.

So this solved my problem:

```javascript
devServer: {
  hot: 'only'
}
```
