### ISSUE TITLE
webpack child compiler does not perform any compilation

### ISSUE THREAD

**Issue by wood1986** [webpack/webpack#9240]
# Bug report

**What is the current behavior?**
I created `childCompiler` at `parentCompiler.hook.make` stage and I called `runAsChild` at `parentCompiler.hook.emit` stage. `childCompilation.assets` are nothing. I do not see any compilation.

Parent compilation is based on `web.webpack.config.js` whose target is `web`. Child compilation is based on another `webworker.webpack.config.js` whose target is `webworker`.

**If the current behavior is a bug, please provide the steps to reproduce.**

web.webpack.config.js

```js
"plugins": [
    new WorkboxPlugin(require("./webworker.webpack.config.js")(env, argv))
  ],
  "target": "web"
]
```

```js
const {DefinePlugin, WebpackOptionsApply, WebpackOptionsDefaulter} = require("webpack");
const NAME = "webworker-injection";

module.exports = class WorkboxPlugin {
  constructor(options) {
    this.options = new WebpackOptionsDefaulter().process(options);
  }

  apply(compiler) {
    const self = this;
    let childCompiler = null;

    debugHooks(compiler, NAME);

    compiler.hooks.emit.tapAsync(NAME, (compilation, callback) => {
      const stats = compilation.getStats().toJson();
      new DefinePlugin({
        "__PRECACHE_MANIFEST__": JSON.stringify({}),
      }).apply(childCompiler);
      childCompiler.runAsChild((err, entries, childCompilation) => {
        console.log(childCompilation.getStats().toJson()); <<<<<<<<<< this has nothing
        callback(err);
      })
    });

    compiler.hooks.make.tapAsync(NAME, (compilation, callback) => {
      childCompiler = compilation.createChildCompiler("child", self.options.output);
      childCompiler.options = new WebpackOptionsApply().process(self.options, childCompiler);
      childCompiler.context = compiler.context;
      debugHooks(childCompiler, "child");
      callback();
    });
  }
}

const debugHooks = (target, from) => {
  for (let hook in target.hooks) {
    if (target.hooks[hook].constructor.name.startsWith("Async")) {
      target.hooks[hook].tapAsync(from, (...args) => {
        console.log(`${hook}.${from}`);
        args[args.length - 1]();
      });
    } else {
      target.hooks[hook].tap(from, () => {
        console.log(`${hook}.${from}`);
      });
    }
  }
}
```

![image](https://user-images.githubusercontent.com/5212215/59151491-f8236d00-89e8-11e9-9086-b9f26db20816.png)

**What is the expected behavior?**
```js
childCompiler.runAsChild((err, entries, childCompilation) => {
  console.log(childCompilation.getStats().toJson()); <<<<<<<<<< this should have something
  callback(err);
});
```

**Other relevant information:**
webpack version:  4.30
Node.js version: 12.3.1
Operating System: macOS 10.14.5
Additional tools:

**Comment by sokra** [comment]
``` js
      childCompiler = compilation.createChildCompiler("child", self.options.output);
      childCompiler.options = new WebpackOptionsApply().process(self.options, childCompiler);
```

Not sure if this works... `createChildCompiler` already inherits most plugins from the parent compiler. `WebpackOptionsApply` readds all, which probably gives a lot of duplicate plugins.

**Comment by sokra** [comment]
It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by wood1986** [comment]
Thanks @sokra. and this is my repo https://github.com/wood1986/webpack-9240

**Comment by wood1986** [comment]
Hey @sokra, I have a webpack core question. In my example, parent compiler's target is web and child compiler's target is webworker. Does the webpack core support different targets in parent and child compiler?

**Comment by sokra** [comment]
> Does the webpack core support different targets in parent and child compiler?

Yes, i. e. the `worker-loader` does this: https://github.com/webpack-contrib/worker-loader

**Comment by wood1986** [comment]
Any update?

**Comment by evilebottnawi** [comment]
What update you wait?

**Comment by wood1986** [comment]
@evilebottnawi https://github.com/wood1986/webpack-9240 the child compiler does not run

**Comment by wood1986** [comment]
Hey @sokra and @evilebottnawi 

The `compiler` inside the `entryOption` hook callback in EntryOptionPlugin is not the childCompiler I pass. I am not sure it is by design. 

When I pass the childCompiler to `new WebpackOptionsApply().process(self.options, childCompiler);`
it recognize my entry `sw.js` correctly but the compiler is not childCompiler inside `entryOption` hook callback in EntryOptionPlugin.

See https://youtu.be/HmQeGtKYj6w

**Comment by wood1986** [comment]
I know why. If I add `"entryOption"` in https://github.com/webpack/webpack/blob/5523a0a9ac561b1d7b410db8d71d2026a72ac412/lib/Compiler.js#L515-L524, it builds my stuff.

My question is why do you need to inherit the hooks from the parent?

**Comment by TheLarkInn** [comment]
I have a theory here but I'm sure @sokra or @evilebottnawi can correct me. childCompiler is meant to let you run basically an instance of webpack inside of webpack, however there are going to be some settings/plugins you don't want to instantly inherit. Some plugins want to operate on a completely separate entry point and not the same entrypoint, and I think entryOption would automatically try to infer the same entrypoint based on `options.entry` from your config. 

@jantimon author of html-webpack-plugin also has a need to build a separate entrypoint however it does so via a `SingleEntryPlugin` https://github.com/jantimon/html-webpack-plugin/blob/master/lib/compiler.js#L18.

I don't know if it answers Q2 though.

**Comment by wood1986** [comment]
Thanks @TheLarkInn. The reason of using `new WebpackOptionsApply().process(self.options, childCompiler)` is webpack knows which plugins need to add to the childCompiler based on the `target` and I do not have to maintain or add the plugins one by one.

Hey @sokra, @evilebottnawi, and @TheLarkInn, Is a good idea on webpack side to remove the whole hooks inheritance for the child compiler and let us control which hooks we want to inherit? If it is not, is it a bad practice for doing this * to remove the built-in inheritance?

```js
childCompiler = compilation.createChildCompiler("child", self.options.output);
childCompiler.options = self.options;
childCompiler.context = compiler.context;
childCompiler.hooks["entryOption"].taps = []; <<<<<<<<<<<<<< *
childCompiler.options = new WebpackOptionsApply().process(self.options, childCompiler);
```
