### ISSUE TITLE
template parts in SourceMapDevToolPlugin's append option

### ISSUE THREAD

**Issue by ValeryVS** [webpack/webpack#9245]
## Feature request

**What is the expected behavior?**

Be able to use `[hash]` and other template indentifiers in `SourceMapDevToolPlugin`'s `append` option.
```
append: `\n//# sourceMappingURL=[url]?hash=[hash]`,
```

**What is motivation or use case for adding/changing the behavior?**

I have a setup with static file names like `index.min.js` and `.map` files stucked in browser's cache if people in team don't use "disable cache when devtool is open".

**How should this be implemented in your opinion?**

Compile `append` like `filename` option.

**Are you willing to work on this yourself?**
may be

**Comment by sokra** [comment]
Send a PR.

Call `compilation.getPath` in `SourceMapDevToolPlugin` to trigger the interpolation.

**Comment by nveenjain** [comment]
I'm taking this issue up.

**Comment by ekilah** [comment]
Note this was closed in favor of https://github.com/webpack/webpack/pull/9166 which was added in [`4.36.0`](https://github.com/webpack/webpack/releases/tag/v4.36.0).

I was having issues with this feature now, on `4.44.1`, and was having a hard time finding the source.

The [docs](https://webpack.js.org/plugins/source-map-dev-tool-plugin/#options) suggest that a few templates should work, but `[filename]` doesn't seem to work for me. `[url]` does work. Just noting for future visitors, and maybe someone who knows more about how this is supposed to work vs works now can update the docs?

![image](https://user-images.githubusercontent.com/3213339/105564819-a96b3980-5cd8-11eb-8c57-993f66f7bdf6.png)


``` new webpack.SourceMapDevToolPlugin({
    append: '\n//# sourceMappingURL=https://example.com/[url]',
    filename: '[file].map',
  }),```

**Comment by Anton-Evstigneev** [comment]
The actual added template is `[filebase]`, not `[filename]`. It stands for plain file name, without extension and path.

**Comment by VioletFlare** [comment]
> The actual template that worked & helped me was `[filebase]`, not `[filename]`. It stands for plain file name, without extension and path.

As of Webpack 5.90.3, I also had to specify the `filename`, without it the `[filebase]` placeholder wasn't getting resolved.

```	
plugins: [
	new webpack.SourceMapDevToolPlugin({
		filename: '[file].map',
		append: `\n//# sourceMappingURL=[filebase].map`
	})
]
```
