### ISSUE TITLE
Error: 

### ISSUE THREAD

**Issue by zhanghengxin** [webpack/webpack#9250]
Other relevant information:
webpack: 5.0.0
webpack-cli: 3.3.4
webpack-dev-server: 3.1.10
vue: 2.0.0
Node.js version: 8.4.11
Operating System: mac
Additional tools: VSCode
![image](https://user-images.githubusercontent.com/24197448/59269660-31c2d500-8c82-11e9-9c35-9e85ab4bae54.png)

**Comment by evilebottnawi** [comment]
Update your webpack version

**Comment by zhanghengxin** [comment]
![image](https://user-images.githubusercontent.com/24197448/59269864-95e59900-8c82-11e9-8f8e-b673bdceb13f.png)
dont has the file

**Comment by evilebottnawi** [comment]
@zhanghengxin https://github.com/webpack/webpack/issues/9250#issuecomment-500807844

**Comment by zhanghengxin** [comment]
> oh, don't use `webpack@5` with `webpack-cli`, they are not compatibility right now

but  i want use webpack@5

**Comment by zhanghengxin** [comment]
Do you have an alternative for update using webpack@5

**Comment by evilebottnawi** [comment]
@zhanghengxin webpack@5 in alpha stage so i strongly recommended use `webpack@4` for building right now, this version only for developers and early testing

> Do you have an alternative for update using webpack@5

Don't use `webpack-cli`, you can run webpack using node api

**Comment by zhanghengxin** [comment]
> @zhanghengxin webpack@5 in alpha stage so i strongly recommended use `webpack@4` for building right now, this version only for developers and early testing
> 
> > Do you have an alternative for update using webpack@5
> 
> Don't use `webpack-cli`, you can run webpack using node api

Thank you ~~
