### ISSUE TITLE
Variable renamer misses an "import { x as y }" reference

### ISSUE THREAD

**Issue by aleclarson** [webpack/webpack#9253]
# Bug report

**What is the current behavior?**

An import reference is not properly transformed into: `_react_spring_shared__WEBPACK_IMPORTED_MODULE_0__["is"]`

**If the current behavior is a bug, please provide the steps to reproduce.**

Follow the steps in here:
https://github.com/aleclarson/repro/tree/webpack-1

**What is the expected behavior?**
Proper variable reference mapping! :)

**Other relevant information:**
webpack version:  `4.33.0`
Node.js version: `11.10.1`
Operating System: `macOS 10.14.5`
Additional tools:
```json
"devDependencies": {
    "@babel/core": "^7.4.0",
    "@babel/plugin-proposal-class-properties": "^7.4.0",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/preset-env": "^7.4.2",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.5",
    "clean-webpack-plugin": "^2.0.2",
    "copy-webpack-plugin": "^5.0.3",
    "css-loader": "^2.1.1",
    "file-loader": "^3.0.1",
    "html-webpack-plugin": "^4.0.0-beta.5",
    "mini-css-extract-plugin": "^0.6.0",
    "node-sass": "^4.12.0",
    "prettier": "^1.18.2",
    "sass-loader": "^7.1.0",
    "style-loader": "^0.23.1",
    "webpack": "^4.29.6",
    "webpack-cli": "^3.3.0",
    "webpack-dev-server": "^3.2.1",
    "webpack-merge": "^4.2.1"
}
```

**Comment by sokra** [comment]
it's a bug

see also #9183
