### ISSUE TITLE
AMD define behaves differently from RequireJS when no callback is specified.

### ISSUE THREAD

**Issue by AlexanderOMara** [webpack/webpack#926]
Consider the following two files.

**main.js**
```js
define(["./test"]);
```

**test.js**
```js
define(function() {
	console.log('test.js');
	return { a: 1, b: 2 };
});
```

When used in RequireJS with the following HTML, `main.js` will load `test.js` and the string `test.js` will appear in the console.

```html
<script data-main="main" src="require.js"></script>
```

However, the same cannot be said for webpack. When I run `webpack main.js pack.js`, only `main.js` get's packed.

```
$ webpack main.js pack.js
Hash: a744b5ec3318be80a0cd
Version: webpack 1.7.3
Time: 40ms
  Asset     Size  Chunks             Chunk Names
pack.js  1.83 kB       0  [emitted]  main
   [0] ./main.js 20 bytes {0} [built]
```

In order to get the same behavior as RequireJS, I have to add an empty callback to the `define` function.

**main.js**
```js
    define(["./test" ], function() {});
```
Now webpack will pack `test.js` and the string `test.js` will appear in the console.
```
$ webpack main.js pack.js
Hash: 1f8dffb57c9279bef1ad
Version: webpack 1.7.3
Time: 49ms
  Asset     Size  Chunks             Chunk Names
pack.js  2.09 kB       0  [emitted]  main
   [0] ./main.js 36 bytes {0} [built]
   [1] ./test.js 77 bytes {0} [built]
```

Apparently calling `define` with just an array in webpack will literally define an array, but in RequireJS it will load the dependencies.

Now, before I start pull requesting large and popular AMD-based JavaScript libraries for webpack compatibility I thought I should ask. Is this intentional and/or is this behavior webpack would change?

**Comment by sokra** [comment]
I implemented it according to the AMD spec: https://github.com/amdjs/amdjs-api/wiki/AMD#define-function-

> ``` js
> define(id?, dependencies?, factory);
> ```

> ## factory

> The third argument, factory, is a function that should be executed to instantiate the module **or an object**. If the factory is a function it should only be executed once. If the factory argument is an object, that object should be assigned as the exported value of the module.

> If the factory function returns a value (an object, function, or any value that coerces to true), then that value should be assigned as the exported value for the module.

`dependencies` is optional. `factory` is not optional. So a one argument function has no `dependencies`.

**Comment by AlexanderOMara** [comment]
Thanks for confirming my suspicions! I'll pull request the libraries that I find are dependent on this. I've also created [a webpack loader](https://github.com/AlexanderOMara/amd-define-factory-patcher-loader) that can patch these problem files on-the-fly.
