### ISSUE TITLE
maintainer needed: https://github.com/webpack/node-libs-browser

### ISSUE THREAD

**Issue by goofballLogic** [webpack/webpack#9262]
I'd like to volunteer to maintain https://github.com/webpack/node-libs-browser so that PRs get merged.

**Comment by sokra** [comment]
Thanks for your help, but this lib has been removed in webpack 5, so it's basically deprecated.

**Comment by goofballLogic** [comment]
Ah ok, where are the browser versions of the core node libraries coming from now?


---- On Wed, 12 Jun 2019 22:10:05 +0100 Tobias Koppers <notifications@github.com> wrote ----


Thanks for your help, but this lib has been removed in webpack 5, so it's basically deprecated.
