### ISSUE TITLE
reading package.json in nested repository

### ISSUE THREAD

**Issue by k-five** [webpack/webpack#9263]
I have two nested repositories and both of them have been initialized with 
 - `npm init`

So there are two `package.json` files. One in the parent and other in the child.
The parent's one has `react`, `react-dom`, `babel-laoder`, etc.
The child's one has nothing in its `package.json` and it is empty.

But inside the child directory I have some `file.js` which are **React with JSX**.

Trying to bundle any file in the child directory throws exception:
```bash
ERROR in ./home/three-JSX-main-patterns.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /var/www/html/ir/jsfun/home/three-JSX-main-patterns.js: Unexpected token (5:27)
```

If I 
 - move the `file.js` out of that child (which has `package.json`) or
 - remove / delete the `package.json` file

then it works.

So when I run **webpack** inside parent directory it reads the `package.json` inside child directory!

Using neither `webpack.config.js` nor `webpack --config false --entry ...` from the command line worked.

the same question on stack-overflow with no answer:
[How to ignore package.json from subrepo](https://stackoverflow.com/questions/55396693/how-to-ignore-package-json-from-subrepo)

Almost the same issue in 2016 #3577
[How to ignore package.json at all?](https://github.com/webpack/webpack/issues/3577)

webpack --version `4.33.0`
node --version `8.9.1`
OS: `Linux Ubuntu 16.04`

**Comment by sokra** [comment]
Unclear how this is related to webpack. Seem more like a babel misconfiguration, but issue has too few information to say.

It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by k-five** [comment]
My best guess is that it related to **wepack** and not **babel**. The main issue is that **webpac** tries to read `package.json` file if there is any with the **entry** point 


Running `./node_modules/.bin/webpack` in the parent works fine if `.js` files are inside any other sub-directories and they (= sub-directories) do **NOT** have `package.json` file.

But if the child directory has `package.json` file then **webpack** throws an error which I know it relates to **babel misconfiguration** but this is not because of babel, it is because webpack reads `package.json` which is inside the child directory. And this `package.json` file is empty.

Removing `package.json` in the child directory or moving out **JXS** files from the child directory will fix the error and everything works fine.

![2019-06-13_1600x900_webpack-bug](https://user-images.githubusercontent.com/18571844/59410883-38129780-8dcf-11e9-8949-94ec4cf201f0.png)


if this is still unclear, then there is a problem with my explanation, and it is time to delete the issue!

**Comment by sokra** [comment]
webpack only read package.jsons to resolve modules, but here modules seem to resolve fine. It looks like babel configuration is different when in child1. Maybe you have your babel configuration in the package.json?

**Comment by k-five** [comment]
### .babelrc inside parent

```bash 
{
  "presets": ["@babel/preset-env", "@babel/preset-react"]
}
```

### package.json inside parent
```bash
{
  "name": "nodepost",
  "version": "1.0.0",
  "description": "A Static Distributed Blogging System",
  "main": "",
  "dependencies": {
    "body-parser": "^1.19.0",
    "cookie-parser": "^1.4.4",
    "express": "^4.16.4",
    "multer": "^1.4.1",
    "node-dev": "^4.0.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/preset-env": "^7.4.5",
    "@babel/preset-react": "^7.0.0",
    "autoprefixer": "^9.5.1",
    "babel-loader": "^8.0.6",
    "mocha": "^6.1.4",
    "postcss-cli": "^6.1.2",
    "webpack": "^4.33.0",
    "webpack-cli": "^3.3.3"
  },
  "scripts": {
  },
  "keywords": [
    "blog",
    "blogging"
  ],
  "author": "Shakiba Moshiri",
  "license": "MIT"
}
```

> webpack only read package.jsons to resolve modules

This is the issue, because in the child `package.json` is empty

```bash
$ cat child-1/package.json 
{
  "name": "child-1",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

**Comment by sokra** [comment]
https://babeljs.io/docs/en/config-files#file-relative-configuration

> Searching will stop once a directory containing a package.json is found, so a relative config only applies within a single package.

**Comment by k-five** [comment]
Okay. I apologize :(

For anyone with the same problem.

 - You want to programmatically create the configuration?
 - You want to compile `node_modules`?
> babel.config.js is for you!

 - You have a static configuration that only applies to your simple single package?
> .babelrc is for you!

[more info](https://babeljs.io/docs/en/configuration)

So I replaced my `.babelrc`:
```bash
{
  "presets": ["@babel/preset-env", "@babel/preset-react"],
}
```

width:
```bash
module.exports = function (api) {
  api.cache(true);

  const presets = ["@babel/preset-env", "@babel/preset-react"];

  return {
    presets
  };
}
```
Also file name from `.babelrc` to  `babel.config.js`
