### ISSUE TITLE
hapi.js + webpack middleware

### ISSUE THREAD

**Issue by phal0r** [webpack/webpack#927]
Hi Guys,

we are heavily using hapi.js and created a plugin for hapi, which uses the webpack compiler directly and is based on the original webpack dev server. If you are interested give it a try: https://github.com/atroo/hapi-webpack-dev-server-plugin

Any feedback appreciated. Thanks in advance!

**Comment by bebraw** [comment]
Can you try getting feedback from hapi/node developers? Looks like this wasn't a great way to achieve that.
