### ISSUE TITLE
issues：Using ”DllReferencePlugin“ still packages some third-party libraries

### ISSUE THREAD

**Issue by zhanghengxin** [webpack/webpack#9272]
**Do you want to request a *feature* or report a *bug*?**
：：bug

**What is the current behavior?**
I want to shorten the packing time，so，i use DllReferencePlugin and DllPlugin to Split third-party libraries
**If the current behavior is a bug, please provide the steps to reproduce.**
this is my config：
```
// webpack.base.conf.js
new DllReferencePlugin ({
            // 索引文件中请求的上下文
            context:dllPath,
            scope: 'var',
            manifest:require(path.join(dllPath, './vendor.manifest.json'))
        }),
        new DllReferencePlugin ({
            // 索引文件中请求的上下文
            context:dllPath,
            scope: 'var',
            manifest: require(path.join(dllPath, './uiLib.manifest.json'))
        }),
        new DllReferencePlugin ({
            // 索引文件中请求的上下文
            context:dllPath,
            scope: 'var',
            manifest: require(path.join(dllPath, './commonDict.manifest.json'))
        }),
        new DllReferencePlugin ({
            // 索引文件中请求的上下文
            context:dllPath,
            scope: 'var',
            manifest: require(path.join(dllPath, './pictureLib.manifest.json'))
        })
```
```
// webpack.dll.conf.js
const VueLoaderPlugin = require('vue-loader/lib/plugin')
var vueLoaderConfig = require('./vue-loader.conf')
const DllPlugin = require('webpack/lib/DllPlugin');
const path = require('path');
var config = require('../config')
const dllPath = path.join(config.build.assetsRoot,'/dll');

module.exports = {
    entry: {
        // 必要的
        'vendor': ['vue','vue/dist/vue.esm.js','jquery','vuex','vue-router','axios','echarts'],
        'uiLib':['iview','element-ui','pdfjs-dist'],
        'pictureLib':['viewerjs'],
        'commonDict':['./src/assets/libs/js/city.js','./src/assets/libs/js/focus.js','./src/assets/libs/js/openInputSelect.js']
    },
    output: {
        filename: '[name]_dll.js',
        path: dllPath,
        library: '[name]_dll'
    },
    module: {
        rules: [
            {
                test: /\.vue$/,
                loader: 'vue-loader',
                options: vueLoaderConfig
            },
            {
                test: /\.js$/,
                loader: 'babel-loader?cacheDirectory',
            },
        ]
    },
    plugins: [
        new VueLoaderPlugin(),
        new DllPlugin({
            name: '[name]_dll',
            context:dllPath,
            path: path.join(dllPath, '[name].manifest.json'),
        })
    ]
}

```

**What is the expected behavior?**
![图片](https://user-images.githubusercontent.com/24197448/59434391-1096eb80-8e1e-11e9-9904-b9c4a82d03c0.png)
this is dist for 'webpack.base.conf.js' of analysis
thire-party are still compiled
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

webpack : 4.33.0
node: 8.4.11
browser: chrome /firefox
operating sys : mac 10.14.5 (18F132)

**Comment by evilebottnawi** [comment]
Please fill all questions otherwise your issue was closed, thanks

**Comment by sokra** [comment]
`scope: "var"` looks wrong to me.

Please see documentation: https://webpack.js.org/plugins/dll-plugin/#scoped-mode

**Comment by zhanghengxin** [comment]
> `scope: "var"` looks wrong to me.
> 
> Please see documentation: https://webpack.js.org/plugins/dll-plugin/#scoped-mode

It has nothing to do with the questions
If the scope is removed, the program will report an error: uiLib_dll is not defined
look at it 
![image](https://user-images.githubusercontent.com/24197448/59485251-9a3ecb80-8ea7-11e9-89d2-a715345256e1.png)
AND
...
I rebooted my computer and found it ok
sorry and thanks
![image](https://user-images.githubusercontent.com/24197448/59485576-efc7a800-8ea8-11e9-9708-aee09b216e2d.png)
Reboot is a surprise！！！！！

**Comment by ZoneLabyrinth** [comment]
Same problems as you. Do you found the reason finally?

**Comment by rsshilli** [comment]
I also have this and a reboot didn't help. I'd love a pointer on how to get `pdfjs-dist` to bundle properly in my vendor lib.
