### ISSUE TITLE
Add TypeScript example  in examples  dir.

### ISSUE THREAD

**Issue by konojunya** [webpack/webpack#9275]
## Feature request

**What is the expected behavior?**

As there is an example of coffee-script but there is no example of TypeScript, is it better to add it?

**What is motivation or use case for adding/changing the behavior?**

Projects in the world have typescript
I thought it should be added because it is increasing.

**How should this be implemented in your opinion?**

Add  TypeScript  example to example directory.

**Are you willing to work on this yourself?**
yes, of course.

**Comment by montogeek** [comment]
Feel free to send a PR.
