### ISSUE TITLE
Using Webpack with monorepo

### ISSUE THREAD

**Issue by vtereshyn** [webpack/webpack#9276]
Hi.
Researching a way to use Webpack with front end monorepo. I was wondering if I can use one common Webpack config and place it to the root directory and then extend this config in other apps. But, when I tried to setup common configuration and extend it I was stuck into running context, so the building is running in the root directory, not in each of apps.

My question is: do you have Monorepo support or can I use common configs and then override what I need in each of the applications, but the main configuration is stored in the root?

Thank you in advance!

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.

**Comment by vtereshyn** [comment]
I haven't found any info according to my question in your documentation. So, if this info presents, it will be great if you add this to docs. So it can be a feature request.

**Comment by evilebottnawi** [comment]
Please open issue in webpack-docs, it is related to documentation

**Comment by vtereshyn** [comment]
@evilebottnawi not sure if it's related to documentation. Maybe Webpack can't do that, so documentation is empty according to this as well
