### ISSUE TITLE
HMR `hotDownload` path is wrong for node build

### ISSUE THREAD

**Issue by lettertwo** [webpack/webpack#928]
Given a webpack config like the following:

``` javascript
{
  entry: ['./src/browser/main'],
  target: 'node',
  output: {
    path: path.join(__dirname, './build/'),
    libraryTarget: 'commonjs2',
    filename: 'browser/main.js',
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
  ]
}
```

HMR fails to work. I think it's because the [node HMR machinery](https://github.com/webpack/webpack/blob/d5dc904a15d1eaa029f107e21924405acb0323b1/lib/node/NodeMainTemplatePlugin.js#L189-L193) expects the hot update chunks to be in the same location as the main chunk. Attempts to load the hot update manifest error (silently) with:

```
Error: Cannot find module './1386b84342c2ab56b95e.hot-update.json'
```

The build dir looks like:

``` shell
1386b84342c2ab56b95e.hot-update.js
1386b84342c2ab56b95e.hot-update.json
browser

./browser:
main.js
```

So, since the HMR update code is in `./browser/main.js`, but the hot update manifest (and patch) is at './', the updates aren't found and HMR doesn't work.

I tried adding the [`output.hotUpdateMainFilename`](http://webpack.github.io/docs/configuration.html#output-hotupdatemainfilename) setting, but to no avail. I think the fact that the update code expects to find the manifest and patch at './' is the root of the problem.

Any thoughts or advice?

**Comment by sokra** [comment]
As workaround you can set `output.filename: 'browser_main.js'
