### ISSUE TITLE
node_modules is found in bundle.js, you can analyse using stats

### ISSUE THREAD

**Issue by rajiff** [webpack/webpack#9286]
# Bug report

**What is the current behavior?**
Expecting `node_modules` to be not part of the bundle, but inseams to be 

I am having trouble reducing my bundle size, when built using webpack (both `development` and `production` modes)

When I analyse its stats, it shows bulk is due to node_modules, having trouble understanding if webpack is not excluding node_modules or I am doing something wrong

I used this to visualise stats https://chrisbateman.github.io/webpack-visualizer/
the visualisation is as below
<img width="719" alt="image" src="https://user-images.githubusercontent.com/1080415/59558839-199fdc80-9019-11e9-981d-7cc63cc85525.png">

```javascript
test: /\.(js|jsx)$/,
exclude: /node_modules/,
loader: "babel-loader",
```

I even tried analysing using http://webpack.github.io/analyse, it too lists most modules from node_modules only

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Take any simple webpack project
2. Build it
3. Generate stats using `webpack <any other configuration you want to pass> --json > stats.json`

**What is the expected behavior?**

Webpack should exclude `node_modules` and produce a bundle with minimal possible size

**Other relevant information:**
webpack version:  `^4.34.0`
webpack-cli version: `^3.3.4`,
Node.js version: `v12.3.0`
Operating System: `Mac OS`
Additional tools: `yarn`

**Comment by anikethsaha** [comment]
can you share your config file with the project structure?

**Comment by rajiff** [comment]
Hi

### Folder structure
```unix

project/
├── webpack.dev.js
├── webpack.common.js
├── webpack.prod.js
├── public
├── src
│   ├── components
│   │   ├── componentXYZ.jsx
│   │   └── index.js
└───├── theme.js
    └── index.js
```

### Common config
```javascript
const path = require('path');
const webpack = require('webpack');
const lodash = require('lodash');

const HtmlWebpackPlugin = require('html-webpack-plugin');
const LodashPlugin = require('lodash-webpack-plugin');
const MomentLocalesPlugin = require('moment-locales-webpack-plugin');

module.exports = {
  entry: './src/index.js',
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        loader: "babel-loader",
      },
      {
        test: /\.css$/,
        loaders: 'style-loader!css-loader?modules',
        exclude: '/node_modules/'
      },
      {
        test: /(\.scss|\.css)$/,
        loader: 'style!css?modules!sass',
        include: path.resolve(__dirname, 'react-flexbox-grid'),
        exclude: /node_modules/
      },
      {
        test: /\.svg$/,
        loader: 'raw-loader'
      }
    ]
  },
  resolve: {
    extensions: [".js", ".jsx"]
  },
  plugins: [
    new HtmlWebpackPlugin({
      title: 'AppTemplate',
      template: './public/index.html',
      favicon: './public/favicon.ico'
    }),
    new LodashPlugin(),
    new MomentLocalesPlugin()
  ],
  output: {
    filename: '[hash].bundle.js',
    path: path.resolve(__dirname, 'dist'),
    publicPath: '/'
  }
};
```

###  Prod config
```javascript
const merge = require('webpack-merge');
const webpack = require('webpack');

const CompressionPlugin = require('compression-webpack-plugin');
const BrotliPlugin = require('brotli-webpack-plugin');
const LodashPlugin = require('lodash-webpack-plugin');
const MomentLocalesPlugin = require('moment-locales-webpack-plugin');

const common = require('./webpack.common');

module.exports = merge(common, {
  mode: 'production',
  devtool: '',
  plugins: [
    new LodashPlugin(),
    new MomentLocalesPlugin(),
    new CompressionPlugin({
      test: /\.(js|css|html|svg|ico)$/,
      filename: '[path].gz[query]',
      algorithm: 'gzip',
      threshold: 10240,
      // threshold: 500,
      minRatio: 0.8,
      deleteOriginalAssets: false,
    }),
    new BrotliPlugin({
      test: /\.(js|css|html|svg|ico)$/,
      asset: '[path].br[query]',
      threshold: 10240,
      minRatio: 0.8,
      deleteOriginalAssets: false
    })
  ],
  optimization: {
    minimize: true
  }
});
```

**Comment by sokra** [comment]
``` js
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        loader: "babel-loader",
      },
```

The `exclude: /node_modules/` here only excludes the node_modules from the babel-loader. It doesn't exclude node_modules from the bundle.

**Comment by rajiff** [comment]
May be yes, my question is why should it even include so many files from `node_modules` how can we tell webpack to pick just the used files from node_modules

**Comment by anikethsaha** [comment]
@rajiff you can mention them in `include` field.
Also, I mentioned that `webpack-node-externals` cause it will help in not including the whole node_modules.
you need to mention it in `externals` field

**Comment by sokra** [comment]
> how can we tell webpack to pick just the used files from node_modules

It only picks used files expect in cases where it's not statically analyse-able.

You probably reference these node_modules somewhere...

**Comment by rajiff** [comment]
Ok, I thought the tree shaking feature takes care of it

I am not sure right now then how to proceed

I am closing this issue
