### ISSUE TITLE
[bug][alpha] cannot use same name for multiple cacheGroups

### ISSUE THREAD

**Issue by MhMadHamster** [webpack/webpack#9288]
# Bug report

As it stated in the title, if you use same "name" option for multiple cacheGroups webpack will fail with error like:
`some-module.js has no id. This should not happen.`

**What is the current behavior?**
there is an error which is not allowing you to compile

**If the current behavior is a bug, please provide the steps to reproduce.**
repo with example - https://github.com/MhMadHamster/webpack-no-module-id

**What is the expected behavior?**
No error should occur, there is no info about changing this behavior in the changelog for alpha.

**Other relevant information:**
I believe this is a regression after v5.0.0-alpha.12 (error starts to occur in 12, alpha 11 works just fine), to be more exact i'm talking about these changes:  https://github.com/webpack/webpack/commit/b66143f706112ee56df2b67361f49aa05d9dbc24#diff-64e8e63f33596df33d814452fa5d5b83R882 I've tried to remove it and it leads to getting same error, but if you have entry and chunkGroup with the same name (currently it will show you WebpackError and will not throw an error, allowing to compile) corresponding test: test/configCases/split-chunks/entry-point-error will fail. I managed to fix this behavior by adding additional check if given chunk is an entrypoint, but i am not sure if this is right fix to do, i haven't found original commit for these changes, and it clearly not from the stable version (even tho on github it shows as a part of v4.30 merge to next), in my perspective if this code is only for case when user makes an entrypoint and a cacheGroup with the same name, which is not allowed in v5 already, why not just throw an error earlier not allowing to compile with this configuration, i guess for backward compatibility?

webpack version:  v5.0.0-alpha.16
Node.js version: v10.15.3
Operating System: windows 10
Additional tools: webpack-cli v3.3.4

**Comment by sokra** [comment]
yep, there is a bug here...
