### ISSUE TITLE
Silently fails when loader doesn't exist

### ISSUE THREAD

**Issue by M-Pixel** [webpack/webpack#929]
If a loader is not installed, instead of throwing any sort of error, webpack compiles anyways without compile-time errors. As a result, any includes that require the loader are "not found" (for example, .coffee files if coffee-loader isn't installed). This error doesn't make it clear that the problem is caused by a missing module.

**Comment by sokra** [comment]
This is not true. There are errors when loaders are missing.

If you are using the node.js API you may not handle errors correctly: see documentation > node.js API > error handling

**Comment by juliankrispel** [comment]
@theqwertman I just ran into this and then noticed that my config was just wrong. This is how you need to define modules:

```
//webpack.config.js
module.exports = {
  module: {
    loaders: {...}
  }
};
```

**Comment by dancoates** [comment]
I've noticed the same issue and created a simple test case to reproduce it. Here's the steps to reproduce:

1. Clone this repo: https://github.com/dancoates/webpack-loader-bug-repro
2. Run `npm install`
3. Run `node build.js`

__Expected result__: an error message is logged stating that the loader could not be found.
__Actual result__: there is no error message and the build silently fails.

**Comment by dancoates** [comment]
Forgot to comment back on this, turns out I was handling the wrong errors. It's a little counter intuitive but the errors within the `stats` object need to be handled as well as the `err` argument. It is well documented here: https://webpack.github.io/docs/node.js-api.html#error-handling definitely a RTFM in my case.
