### ISSUE TITLE
Webpack --watch will be crashed when print donation info on Windows7

### ISSUE THREAD

**Issue by SuAutumn** [webpack/webpack#9292]
# Bug report

**What is the current behavior?**
the process raise a error : 
if (!e && fileOwnerId === process.getuid()) utimesSync(openCollectivePath, now, now);
                                                                                                  ^
TypeError: process.getuid is not a function

nodejs doc tips : there is no process.getuid on windows

**If the current behavior is a bug, please provide the steps to reproduce.**
"package.json"
  "watch": "webpack --watch"

npm run watch on MONDAY

**What is the expected behavior?**
process won't be crashed

**Other relevant information:**
webpack version:  4.33.0
Node.js version:  10.15.3
Operating System:  windows&
Additional tools: webpack-cli 3.3.3

**Comment by NathanQuayle** [comment]
I was getting the same error. Running `npm i` fixed it for me.

**Comment by sticky4loop** [comment]
Its not a bug, its a feature #longLiveUNIX

**Comment by SuAutumn** [comment]
well, it's a little error that occur by webpacl-cli cli.js
and I found the git commit, I think this case isn't consider other platform;
https://github.com/webpack/webpack-cli/commit/5284b7e97cb8450d479d8220d09222103871ef72#diff-22d5d2b57c69d2e1ac054c4d0f744ff1

> I was getting the same error. Running `npm i` fixed it for me.

you can

**Comment by SuAutumn** [comment]
click wrong

**Comment by evilebottnawi** [comment]
Please open issue in webpack-cli
