### ISSUE TITLE
[Webpack 5] getChunkFilenameRuntimeModule not respecting filename as a function

### ISSUE THREAD

**Issue by guybedford** [webpack/webpack#9296]
# Bug report

**What is the current behavior?**

When `output.filename` is a function, an error is thrown during chunk generation in Webpack 5 on the "next" branch.

This happens because in https://github.com/webpack/webpack/blob/next/lib/runtime/GetChunkFilenameRuntimeModule.js#L180, the `filename` is being run through `JSON.stringify`. Removing the `JSON.stringify` wrapper seems to resolve the issue.

**If the current behavior is a bug, please provide the steps to reproduce.**

Chunked build with `output.filename` as a function.

**What is the expected behavior?**

This should be supported as in the docs.

**Comment by sokra** [comment]
Which webpack version?

There was a fix in https://github.com/webpack/webpack/releases/tag/v5.0.0-alpha.11

**Comment by guybedford** [comment]
This was in alpha.12.

**Comment by sokra** [comment]
Yes that's a bug. I have a fix, but still need to create some more tests for this.
