### ISSUE TITLE
[Webpack 5] chunkFilename doesn't seem to be applying?

### ISSUE THREAD

**Issue by guybedford** [webpack/webpack#9297]
# Bug report

When setting `output.chunkFilename: "chunk-[id].js"` alongside `output.filename: "[name]"` in ncc development, we're finding that the chunk is still being output as just the ID - `655` instead of the `chunk-655.js` form.

**What is the current behavior?**

`output.chunkFilename` should be supported as in the docs.

**If the current behavior is a bug, please provide the steps to reproduce.**

This test is currently replicating the behaviour - https://github.com/zeit/ncc/blob/master/test/multi-entry.test.js, which remains unchanged when adding `chunkFilename` into https://github.com/zeit/ncc/blob/master/src/index.js#L134.

Sorry I can't do a better replication here, but my primary focus is on finding a workaround for now.

**What is the expected behavior?**

This should be supported as in the docs.

**Comment by sokra** [comment]
`chunkFilename` only affects on-demand loaded chunk. Is there a `import()` in these test case? That seem to be rare since node.js doesn't support it.

**Comment by sokra** [comment]
It seem to be a chunk created by the default `splitChunks` configuration. Both entries share common modules. This is not affect by `chunkFilename`, but by `filename`. You could override the default splitChunks.cacheGroups.default` cacheGroup and specify a `filename` here too if you want a other filename.

It's also possible to use `optimization.chunkIds: "named"` to let webpack generate a filename based on the chunk content (looks nice^^).

**Comment by guybedford** [comment]
Ahh, I see, thanks so much for clarifying here.

**Comment by Kamil93** [comment]
I can confirm the bug:

`chunkFilename: "assets/scripts/[name].js"`

For webpack v4 it works correctly, that chunk was placed in `assets/scripts` folder, now in webpack 5 path is ignored

**Comment by acarlstein** [comment]
I can confirm that there might be a bug with the `splitChunks` feature:

I have this webpack configuration:
```json
module.exports = {
  entry: {
    index: './src/js/index.js',
    about: './src/js/about.js'
  },
  output: {
    filename: 'js/[name]/[name].js',
    chunkFilename: 'js/[name].js'
  },
  optimization: {
    splitChunks: {
      chunks: 'all',
      name: 'vendor'
    }
  }
}
```

I was expecting that the Vue code will be saved inside the file `vendor.js` inside `/dist/js` directory as shown in the image below:
![image](https://user-images.githubusercontent.com/5709926/113320954-57462600-92d0-11eb-8d17-850f15ac67c5.png)

Instead, the Vue code is inside the file `vendor.js`, which is saved in the directory `/dist/js/vendor` as shown below:
![image](https://user-images.githubusercontent.com/5709926/113321167-8f4d6900-92d0-11eb-927f-22d41a5f8148.png)

**Comment by saulske** [comment]
Why is this closed? I am experiencing same bug.

**Comment by rodoabad** [comment]
Can someone explain why this was closed?

**Comment by vankop** [comment]
It was answered https://github.com/webpack/webpack/issues/9297#issuecomment-503061903

**Comment by nyngwang** [comment]
To @sokra:

> `chunkFilename` only affects on-demand loaded chunks. Is there a `import()` in these test case?

[From the doc](https://webpack.js.org/configuration/output/#outputchunkfilename) the wording is different:

> This option determines the name of **non-initial chunk** files. [...]

So those chunks created by `splitChunks `(i.e. SplitChunksPlugin) are NOT classified as "non-initial chunk"? This sounds very unintuitive :/.

**Comment by vankop** [comment]
> non-initial chunk

means non entrypoint chunk. e.g. in case 
index.js
```js
import("a");
```

webpack.config.js
```js
module.exports = {
   output: { filename: "main.js", chunkfilename: "chunk.js" }
};
```

`index.js` will be bundled in `main.js`, `a` will be bundled in `chunk.js`.

**Comment by nyngwang** [comment]
@vankop: OK, then for those chunks created by SplitChunksPlugin: will you classify them as initial or non-initial chunk? According to the [docs](https://webpack.js.org/concepts/under-the-hood/#chunks):

> `non-initial` is a chunk that may be lazy-loaded. It may appear when [dynamic import](https://webpack.js.org/guides/code-splitting/#dynamic-imports) or [SplitChunksPlugin](https://webpack.js.org/plugins/split-chunks-plugin/) is being used.

But from https://github.com/webpack/webpack/issues/9297#issuecomment-503061903 above:

> It seem to be a chunk created by the default `splitChunks` configuration. [...]

This seems to express that chunks created by SplitChunksPlugin are initial chunk (thus "This is not affect by `chunkFilename` [...]").

Contradiction?

**Comment by vankop** [comment]
yeah,  better name this as dynamic import chunk..
