### ISSUE TITLE
[Webpack 5] relative chunks are not being loaded properly

### ISSUE THREAD

**Issue by guybedford** [webpack/webpack#9298]
# Bug report

**What is the current behavior?**

In ncc we're supporting multi-entry builds with webpack code splitting, where `output.filename` is a function returning `chunk-[id].js` for chunks and `[name]` directly for entry points.

The entry points are being output with the following code in their bundles for loading the chunks:

```js
      /******/  /* webpack/runtime/get javascript chunk filename */
      /******/  !function() {
      /******/          // This function allow to reference async chunks and sibling chunks for the entrypoint
      /******/          __webpack_require__.u = function(chunkId) {
      /******/                  // return url for filenames based on template
      /******/                  return " + chunkId + ";
      /******/          };
      /******/  }();
```

with absolutely no reference to the `chunk-33.js` named form that is being used in the output configuration.

**If the current behavior is a bug, please provide the steps to reproduce.**

This can be replicated in ncc with `output.filename` being set to a function in the multi-entry test case.

**What is the expected behavior?**

This should work as described in the documentation.

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by sokra** [comment]
Looks like a bug. Which webpack version?

Could be affected by the fix in https://github.com/webpack/webpack/releases/tag/v5.0.0-alpha.11

**Comment by guybedford** [comment]
Also alpha.12.

**Comment by sokra** [comment]
I'm unsure what's causing this...

Could you create a repro repo for this?

**Comment by sokra** [comment]
I guess this is caused by you removing a `JSON.stringify` from the webpack source code. I also had this issue while working on #9296, but it should not occur in real cases.

**Comment by guybedford** [comment]
Yes, this would have been in combination with that change. Ok then it sounds like it's just that one bug at play here thanks.
