### ISSUE TITLE
Make it easier to access contents of emitted assets

### ISSUE THREAD

**Issue by jimmydief** [webpack/webpack#9299]
## Feature request

**What is the expected behavior?**

Prior to `futureEmitAssets` being added in #8642, it was possible to easily access the final contents of all emitted assets at `stats.compilation.assets`.

**What is motivation or use case for adding/changing the behavior?**

This was useful for tracking the size of our bundled assets to avoid unintentional bundle size regressions. While `size` is still exposed on `SizeOnlySource`, it's now harder to get access to the actual contents in order to track gzip/brotli/etc. size. Reading in the final emitted files from the file system would work fine but is harder than it probably should be as various plugins like `MiniCssExtractPlugin` support different public paths for different asset types.

**How should this be implemented in your opinion?**

Including the location of the emitted asset as part of the asset stats would make things easier. Perhaps this is already available somewhere but I've been unable to find it if so.

**Are you willing to work on this yourself?**
Yes.

**Comment by sokra** [comment]
The `publicPath` doesn't matter here.

The key in `compilation.assets` is the output filename in the `compilation.outputPath`.

**Comment by sokra** [comment]
But it probably makes sense to add a Hook which allows to introspect the in-memory file content just after it was emitted to measure i. e. gzip size, etc.

You could add a hook just before this line

https://github.com/webpack/webpack/blob/75c340c3d1f0d807e0548133ccf8e70252d66cd1/lib/Compiler.js#L400

i. e. `this.hook.assetEmitted.callAsync(file, content, callback)`

and similar here

https://github.com/webpack/webpack/blob/75c340c3d1f0d807e0548133ccf8e70252d66cd1/lib/Compiler.js#L415

**Comment by sokra** [comment]
Send a PR

**Comment by jamesgeorge007** [comment]
@sokra I would take this up :+1:

**Comment by jimmydief** [comment]
Thanks, I meant the output path and not public path. Joining with the output path from the output options did end up working for my use case, will leave the issue open to track that enhancement.
