### ISSUE TITLE
High severity vulnerabilities found in set-value and mixin-deep

### ISSUE THREAD

**Issue by LL782** [webpack/webpack#9308]
# Bug report

**What is the current behavior?**

Two vulnerabilities have been highlighted by [Synk](https://snyk.io/) in dependencies of `next@7.0.2`

**If the current behavior is a bug, please provide the steps to reproduce.**

Run `synk test` on a project that uses `next@7.0.2`

**What is the expected behavior?**

No vulnerabilities should be found.

**Other relevant information:**

webpack version:  4.20.2
Node.js version: v11.14.0

Our project is dependent on Webpack via [NextJS](https://nextjs.org/) and we've raised a similar [issue with them](https://github.com/zeit/next.js/issues/7620)

Links to vulnerabilities: 
- https://snyk.io/vuln/SNYK-JS-SETVALUE-450213
- https://snyk.io/vuln/SNYK-JS-MIXINDEEP-450212

It looks like [**set-value**](https://github.com/jonschlinkert/set-value/commit/95e9d9923f8a8b4a01da1ea138fcc39ec7b6b15f) and [**mixin-deep**](https://github.com/jonschlinkert/mixin-deep/commit/8f464c8ce9761a8c9c2b3457eaeee9d404fa7af9)  addressed this vulnerabilty yesterday but obviously there are several steps between **webpack** and **set-value** and **mixin-deep**

**Comment by DanielRuf** [comment]
Hi @LL782,

the full log of the Snyk audit would be helpful to see the chain of dependenies.

Also see https://github.com/webpack/webpack/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+author%3Asnyk-bot

**Comment by ematipico** [comment]
You should upgrade nextjs. Webpack it's just a dependency of nextjs.

**Comment by LL782** [comment]
@DanielRuf 

Good point. At the moment all I have is what I posted on the (NextJS issue)[https://github.com/zeit/next.js/issues/7620] From that it looks like **micromatch** is the common ancestor of all the issues, so that link you posted looks positive. 

It only mentions resolving the **set-value** issue but the other one may be on the way.  

I’ll be able to catch up properly on Monday but for now hope this helps: 

```
✗ High severity vulnerability found in set-value
  Description: Prototype Pollution
  Info: https://snyk.io/vuln/SNYK-JS-SETVALUE-450213
  Introduced through: next@7.0.2
  From: next@7.0.2 > webpack@4.20.2 > micromatch@3.1.10 > snapdragon@0.8.2 > base@0.11.2 > cache-base@1.0.1 > set-value@2.0.0
  From: next@7.0.2 > webpack@4.20.2 > micromatch@3.1.10 > braces@2.3.2 > snapdragon@0.8.2 > base@0.11.2 > cache-base@1.0.1 > set-value@2.0.0
  From: next@7.0.2 > webpack@4.20.2 > micromatch@3.1.10 > extglob@2.0.4 > snapdragon@0.8.2 > base@0.11.2 > cache-base@1.0.1 > set-value@2.0.0
  and 29 more...


✗ High severity vulnerability found in mixin-deep
  Description: Prototype Pollution
  Info: https://snyk.io/vuln/SNYK-JS-MIXINDEEP-450212
  Introduced through: next@7.0.2
  From: next@7.0.2 > webpack@4.20.2 > micromatch@3.1.10 > snapdragon@0.8.2 > base@0.11.2 > mixin-deep@1.3.1
  From: next@7.0.2 > webpack@4.20.2 > micromatch@3.1.10 > braces@2.3.2 > snapdragon@0.8.2 > base@0.11.2 > mixin-deep@1.3.1
  From: next@7.0.2 > webpack@4.20.2 > micromatch@3.1.10 > extglob@2.0.4 > snapdragon@0.8.2 > base@0.11.2 > mixin-deep@1.3.1
  and 13 more...
```

**Comment by LL782** [comment]
@ematipico don’t all the updates need to work their way up the chain first?

I was/am on the latest Next and Webpack. 

My idea was to speed the upgrade of Webpack forward so that Next can update sooner. It looks like a new version of Micromatch is available now with at least one of the issues fixed, so Webpack can be updated to use the latest Micromatch and then Next can update to use the latest Webpack.

**Comment by ematipico** [comment]
It should the other way around. The latest of next is 8.1.0 (which I'm using) and I don't have this vulnerability.

**Comment by DanielRuf** [comment]
In most cases deleting your lockfile and node_modules should also update these deep dependencies.

**Comment by LL782** [comment]
Thanks both. I'd totally missed the fact that I wasn't on the latest Next. My bad! I'll upgrade

**Comment by apnsngr** [comment]
What about #9313?

**Comment by DanielRuf** [comment]
@apnsngr the team is aware of it.
