### ISSUE TITLE
target: react-native

### ISSUE THREAD

**Issue by iamdustan** [webpack/webpack#931]
:) from my lack of knowledge of webpack internals I think this would be a great use case.

Then we can use https://github.com/gaearon/react-hot-loader in react-native apps!

Apparently, they tried it already. https://github.com/facebook/react-native/tree/master/packager#why-didnt-you-use-webpack

https://github.com/facebook/react-native/issues/5

(I also see that you were on that discussion over their a bit.) Does it make sense to track this here as well as a community package?

**Comment by bebraw** [comment]
Closing this in favor of #749.

**Comment by simonbuchan** [comment]
Note to future readers, the second link is dead, but the [permalink](https://github.com/facebook/react-native/tree/a829d01bfc3dff3a54a3bf3eaf87d9aab001e652/packager#why-didnt-you-use-webpack) is just a ref to the third.
