### ISSUE TITLE
Duplicate code when bundling the same module for an entry point as sync and async dependency

### ISSUE THREAD

**Issue by unasabovic** [webpack/webpack#9314]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
We are upgrading a giant codebase from Webpack 3 to 4 and are blocked on one issue. We are seeing significant code duplication in final bundles when the same JS module is required synchronously and asynchronously in the route code.

The JS module referenced from the entry point file contains synchronous require to the page code like this:

```
// entrypoints.js
"HomeDesktopPage":"HomeDesktopEntry.js"
```
`HomeDesktopEntry.js` requires the relevant page module `HomeDesktop.js` synchronously in order to bundle all dependencies for the initial page load:

```
// HomeDesktopEntry.js:

require("./logging");
// make sure component is part of the entry point
require("./HomeDesktop");
```

In another JS module in the `HomeDesktopEntry` dependency tree, we require `HomeDesktop` asynchronously:
```
require.ensure([], () => {
   returnValue.resolve({
       page: require("./pageTypes/ActivishDetailsPage/HomeDesktop"),
   });
});
```
Webpack will generate additional bundles for "HomeDesktopLazy" and load them on demand when this code is executed. The lazy loaded chunks contain duplicated JS modules that were already bundled and loaded initially when we navigated to `HomeDesktopEntry`. Even though we required  `HomeDesktop` in the entry point file and bundled all its dependencies, Webpack runtime generates and loads additional lazy chunks for the asynchronous require of that same module. I've built a little tool to measure the duplication and on our giant codebase, this amounted to additional 3MB of just duplicated JS modules. This creates some additional problems with page performance too since we need to wait for those async chunks to load in order to boot up the page client side.

**If the current behavior is a bug, please provide the steps to reproduce.**
The behavior happens only with some `splitChunks` configs. For example, with the below config we get 68 JS bundles for the `HomeDesktopPage` route but no duplication happens:
```
optimization: {
   splitChunks: {
       chunks: "all",
       minSize: 0,
       maxInitialRequests: Infinity,
       maxAsyncRequests: Infinity,
```

Trying to reduce the number of bundles and initial requests, however, does cause the above bug and significant JS duplication:
```
optimization: {
   splitChunks: {
       chunks: "all",
       minSize: 500000,
       maxInitialRequests: 5,
       maxAsyncRequests: 5,
```

Our codebase is huge, and I am not sure how easy it will be to create a minimal repro example. I am working on it, but wanted to post the problem in the meantime just in case there is a known solution or an explanation for it. Thanks so much for any help! 

**What is the expected behavior?**
No additional bundles are generated and loaded on demand when the same JS module is required asynchronously if it was previously required synchronously.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Node 8 and 10, we tried on both
webpack 4.28
MacOS
Chome

**Comment by sokra** [comment]
A few questions:

* Did you set `optimization.availableModules: false`?
* Do the chunk have more parent chunks than the mentioned entry point? i. e. other entry points?

**Comment by unasabovic** [comment]
Thanks for your response!
- I have tried setting `optimization.removeAvailableModules: true` explicitly even though it should be `true` by default (https://webpack.js.org/configuration/optimization/#optimizationremoveavailablemodules). I don't see `optimization.availableModules` in the docs but it seems like that's `removeAvailableModules` equivalent? It didn't make a difference.
- Yes. All entry point include the `routes` file which had lazy requires for client-side routing.
Update: we are not using "webpack": "4.35.0"

**Comment by sokra** [comment]
> * I have tried setting `optimization.removeAvailableModules: true` explicitly even though it should be `true` by default (https://webpack.js.org/configuration/optimization/#optimizationremoveavailablemodules). I don't see `optimization.availableModules` in the docs but it seems like that's `removeAvailableModules` equivalent? It didn't make a difference.

The default is fine. I just wanted to make sure you didn't opt-out here.

> * Yes. All entry points include the `routes` file which contains lazy requires `require.ensures` for client-side routing.

So it seem to be correct that the chunk contains `HomeDesktop` because other entry points need it. A module can only be omitted from a chunk when **all** parent chunks already contain the module.

In your case the chunk probably won't load at runtime, because all modules are already loaded.

**Comment by unasabovic** [comment]
> In your case the chunk probably won't load at runtime, because all modules are already loaded.
It does. This is the behavior I'm observing:
Navigating to `HomeDesktopPage` will load bundles `A` and `B` that were generated as `initial` assets for `HomeDesktopPage` entry point. However, while executing the page bootstrap code in the browser when this statement is encountered: 
```
require.ensure([], () => {
   returnValue.resolve({
       page: require("./pageTypes/ActivishDetailsPage/HomeDesktop"),
   });
});
```
webpack runtime will issue requests for additional lazy bundles `C` and `D`. These bundles contain all the same modules that were already included in bundles `A` and `B`.

I would expect this behavior when we navigate to say `SearchDesktopPage` whos entrypoint file 
does not include synchronous `require("./HomeDesktop");`
```
// SearchDesktopPage.js:

require("./logging");
// make sure component is part of the entry point
require("./SearchDesktopPage");
```
Now when we navigate to `SearchDesktopPage` I would expect webpack to lazy fetch bundles `C` and `D` when this code is executed:
```
require.ensure([], () => {
   returnValue.resolve({
       page: require("./pageTypes/ActivishDetailsPage/HomeDesktop"),
   });
});
```
Hope that makes sense, let me know if I didn't explain it well.

**Comment by sokra** [comment]
It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by unasabovic** [comment]
Ok, will try to create one.
