### ISSUE TITLE
Add TypeScript types for `DefinePlugin`

### ISSUE THREAD

**Issue by bfred-it** [webpack/webpack#9316]
`DefinePlugin` doesn't have any types in `webpack`. There are some in `@types/webpack` but they are incomplete: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/796b838a15fad73287bad7a88707a9ca04e60640/types/webpack/v3/index.d.ts#L726-L728

[`webpack.DefinePlugin.runtimeValue`](https://github.com/webpack/webpack/pull/6793) is missing both types and [docs](https://github.com/webpack/webpack.js.org/issues/2314)

**Comment by sokra** [comment]
You should send a PR to DefinitelyTyped

**Comment by bfred-it** [comment]
Why does `webpack` have some types but not others?
