### ISSUE TITLE
__webpack_public_path__ is Reset Across Entrypoints

### ISSUE THREAD

**Issue by fabb** [webpack/webpack#9319]
# Bug report

**Background Information**

My application build generates urls for image and other assets that depend on a runtime environment variable. Therefore I need to adapt the webpack public path at runtime, which is possible by setting `__webpack_public_path__` ([see documentation](https://webpack.js.org/guides/public-path/#on-the-fly)).

I use next.js which generates one entrypoint per page + entrypoints `_document.js`, `_app.js` and `_error.js` which are called from the page entrypoints. Since the `__webpack_public_path__` should be set for each of these entry points, I use the [entrypoint array functionality](https://webpack.js.org/concepts/entry-points/) to inject a short `public-path.js` file before each of the files referenced in the entrypoints. This file just sets the `__webpack_public_path__`. You can [see a short gist of this here](https://gist.github.com/fabb/adf9e62596529e81fb517b38dbf98eab).

**What is the current behavior?**

When my app runs and a page is requested, webpack loads modules from the page chunk (where it also correctly loads `public-path.js` and sets `__webpack_public_path__`), and in proceeding it loads needed modules from the `_document.js` and then `_app.js` chunks.

While the `__webpack_public_path__` is correctly set while the code executes modules from the page chunk, as soon as it continues to load modules from `_document.js`, the webpack chunk initialization code sets the `__webpack_public_path__` (or rather `__webpack_require__.p` in the built code) to an empty string `""`.

Even though the `_document.js` chunk also tries to load the `public-path.js` module, it does not set the `__webpack_public_path__` anymore, as the module is now cached in the `installedModules` cache, and therefore is not executed (with `call`) anymore.

**If the current behavior is a bug, please provide the steps to reproduce.**

See [this short gist](https://gist.github.com/fabb/adf9e62596529e81fb517b38dbf98eab).

**What is the expected behavior?**

I would either expect that 1. the `__webpack_public_path__` is not reset across entrypoints when a module of one entrypoint calls a module of a chunk in another entrypoint, or 2. there was a way to mark side effects as in `public-path.js` as such, and avoid caching in `installedModules`.

**Other relevant information:**
webpack version: 4.20.2
Node.js version: 10.15.3
Operating System: maxOS Mojave
Additional tools: next.js 7.0.3

**Comment by sokra** [comment]
The module cache and the public path is stored in the same location (runtime). public path should only reset at the same time the module cache is reset.

It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by fabb** [comment]
> The module cache and the public path is stored in the same location (runtime). public path should only reset at the same time the module cache is reset.
Then indeed it is a bug?

> It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.
On it.

**Comment by fabb** [comment]
Here you are: https://github.com/fabb/webpack-path-problem

Does this help?

**Comment by fabb** [comment]
It would be nice if someone of the core maintainers could have a look at the example I created.

**Comment by fabb** [comment]
@sokra please have a look at the example project i made.

**Comment by fabb** [comment]
Please reopen and inspect example.

**Comment by amaschas** [comment]
I have encountered this bug as well, and can confirm that the behavior changed at some point, because I have a repo build in 3.8.1 that can access split chunks in other bundles via the prefix defined in `__webpack_public_path__`, but as soon as I tried to upgrade to Webpack 4.43.0 it ignores any chunks that aren't split from the bundle that defines `__webpack_public_path__`. This means that I have to either:

a) define `__webpack_public_path__` in every bundle, which is not great given this is a large application with a lot of bundles with developers adding new ones regularly, or

b) find another way to dynamically pass the static path to Webpack at build time, which is a lot of work.

**Comment by amaschas** [comment]
Hey guys, any updates on this one? Potentially a workaround? Being unable to set the public path at runtime for multiple entrypoints is causing some really serious problems.

**Comment by evilebottnawi** [comment]
@amaschas You can override `__webpack_public_path__` in each entrypoint, anyway can you provide example of problem?

**Comment by amaschas** [comment]
@evilebottnawi I believe there's a repo linked in the earlier reply that demonstrates the issue. (for reference: https://github.com/fabb/webpack-path-problem) In my case, we have many entry points across multiple apps and multiple developers adding and removing them all the time, so it would take a lot of work to both implement and maintain. In our case we'll probably stick on Webpack 3 until this gets fixed given the amount of work involved, though we'd really prefer to upgrade.

**Comment by evilebottnawi** [comment]
Just interesting what your expected? You can use multi compiler mode with difference publicPath, you can override them in each script, you can inject value of `__webpack_public_path__` in each script

**Comment by amaschas** [comment]
> Just interesting what your expected? You can use multi compiler mode with difference publicPath, you can override them in each script, you can inject value of `__webpack_public_path__` in each script

I think that's really the issue, that I have to inject the value of `__webpack_public_path__` into each script. In the previous version of Webpack, I could set it once and it would be set everywhere.

**Comment by evilebottnawi** [comment]
@amaschas but `__webpack_public_path__` can be difference for each entry point

**Comment by Amberg** [comment]
> @amaschas but `__webpack_public_path__` can be difference for each entry point

Is there a way to define the __webpack_public_path__  for each entry point in config. If the entry point can differ for each entry point, then it should be possible to set it in the entry point configuration

**Comment by alexander-akait** [comment]
Why you need this?

**Comment by Amberg** [comment]
I have a MVC Application with multiple entry points. The entry point configuration is then automatically generated based on a naming convention. And at the moment don't see a way to set the `__webpack_public_path__` automatically in every entrypoint.

The value of `__webpack_public_path__`  is the same for every entry point, but I have to import it in every entry point. Can this somehow be done by configuration?

**Comment by alexander-akait** [comment]
You can write plugin for this, but I think you have something wrong in setup, because it is unnecessary in 99.99% cases

**Comment by Amberg** [comment]
@alexander-akait 
You are right, I had a mess in the file-loader and and mini-css-extract-plugin configurations. I fixed that and now i don't need to set the __webpack_public_path__  at all.

**Comment by alexander-akait** [comment]
@Amberg great :smile:
