### ISSUE TITLE
Stylesheet and script not loaded because of MIME-type

### ISSUE THREAD

**Issue by liixing** [webpack/webpack#9323]
# Bug report

**What is the current behavior?**

When I deployed the local code to the line, the online environment crashed directly.

"Refused to apply style from 'xxxx' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.".

My local wepback version is 4.31.0， on the line is 4.35.0.

The local is running normally, but the line is broken.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

I hope to fix this problem as soon as possible

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by HeiGesGit** [comment]
I also have this problem. How did you solve it?
