### ISSUE TITLE
Deprecated <script charset="utf-8">

### ISSUE THREAD

**Issue by BilyachenkoOY** [webpack/webpack#9327]
# Bug report

**What is the current behavior?**

Dynamically added scripts (via JSONP) contain `charset` attribute but it is deprecated ([check MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#Deprecated_attributes)).

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Use any default configuration with code splitting ([webpack.js.org/guides/code-splitting](https://webpack.js.org/guides/code-splitting/)).
2. Make sure your code is split into several chunks.
3. Launch your site, make sure chunks are loaded/added to HTML
4. Copy the HTML and paste to https://validator.w3.org/#validate_by_input
5. Check validation results there should something like 
![validation result](https://user-images.githubusercontent.com/10833213/60087738-44d7a980-9746-11e9-89a8-baf45526e1ff.png)

**What is the expected behavior?**

The `charset` attribute of `<script>` should not be inserted in modern browsers. Probably, this can be achieved by introducing setting to opt out the attribute (or to configure its value as described in #8659) so that people who relies on the attribute will still get it.

**Other relevant information:**
webpack version:  current
I believe it is added by [JsonpMainTemplatePlugin.js#L159](https://github.com/webpack/webpack/blob/master/lib/web/JsonpMainTemplatePlugin.js#L159).

**Comment by evilebottnawi** [comment]
I think option will be great

**Comment by evilebottnawi** [comment]
Bump

**Comment by aberezkin** [comment]
@evilebottnawi, what option do you mean, option to remove the encoding attribute entirely or to define custom encoding like described in #8659? If we can decide on that, I can make a PR.

**Comment by evilebottnawi** [comment]
@aberezkin i think option will be good, because some people use webpack for old browsers and difference environments

**Comment by aberezkin** [comment]
@evilebottnawi, looks like @sokra doesn't agree https://github.com/webpack/webpack/pull/8288#issuecomment-510047730

**Comment by evilebottnawi** [comment]
@aberezkin we can implement option like `output.charset: true | false`

**Comment by irudoy** [comment]
I think we should remove the `chraset` attribute by default and add an option, something like `chunkCharset`, for compatibility purposes. In this case, we will avoid deprecated attributes by default, but leave the way for adding it when needed.

**Comment by irudoy** [comment]
@evilebottnawi string maybe? To add the ability to specify encoding other than `utf-8`.

**Comment by evilebottnawi** [comment]
@irudoy `encoding` is deprecated in HTML spec, so we don't need this

**Comment by irudoy** [comment]
@evilebottnawi, in this case, it just should be removed, isn't it?

**Comment by ishmarwaha** [comment]
@irudoy Was the feature to add the boolean option discussed above implemented?

**Comment by irudoy** [comment]
@ishmarwaha as I know, it wasn't
