### ISSUE TITLE
Cant remove webpack/node_modules in Windows: path to long.

### ISSUE THREAD

**Issue by barrystaes** [webpack/webpack#933]
:information_source: This is not a Webpack bug, its a [NPM](https://github.com/npm/npm/issues/3697) + Windows issue. But its good (for both users and developers) to be aware of this:

The `webpack/node_modules` folder is to deep, windows cant remove it!
This is easily reproduced by cloning https://github.com/webpack/react-starter to a path with a length like / such as `C:\ProjectsGit\CLONE\My-Clone-Of-React-Starter\`.

**Impact**
You cant remove the folder in Windows, so doing a new / fresh `npm install` got harder.
I wonder what the impact is on Webpack. Does it function properly regardless?

**Solution**
None except avoiding Windows. I hope that Webpack devs can keep dependencies minimal (always a good idea) and NPM devs lower the odds of this problem recurring.

**Workaround**
is not easy, and in my case i could not. Unable to remove it;

  - using command prompt, 
  - [custom js code](http://www.geedew.com/remove-a-directory-that-is-not-empty-in-nodejs/), or
  - [rifram module](http://www.nikola-breznjak.com/blog/nodejs/how-to-delete-node_modules-folder-on-windows-machine/), or
  - [powershell](https://gist.github.com/abergs/e682cd1f98f5170e86a6).

I abandoned the folder and continued development elsewhere. Next time i'll try this [prune with empty dependencies trick](http://blog.pixelastic.com/2014/09/16/windows-filepath-too-long-when-deleting-node_modules/) which i found out about later.

**Comment by jlchereau** [comment]
1. removing node_modules/webpack form windows explorer raises the issue, but
2. ```npm remove webpack``` works like a charm.

**Comment by SimenB** [comment]
`npm` 3 wil flatten the dep tree on the file system, so this shouldn't be an issue

http://blog.npmjs.org/post/110924823920/npm-weekly-5

**Comment by sokra** [comment]
I know...
Closing as it's not related to webpack.

**Comment by programmersujeet** [comment]
**Install RimRaf:**
`npm install rimraf -g`

**Go the project directory and delete the node_modules folder with:**
`rimraf node_modules`

**Comment by amitesh786** [comment]
I have added few lines inside package.json:

` "scripts": {

    "clean": "rmdir /s /q node_modules",

    "reinstall": "npm run clean && npm install",

    "rebuild": "npm run clean && npm install && rmdir /s /q dist && npm run build --prod", 

    ....
}`

If you want to remove the package use this - ` rimraf node_modules` or `rm -rf  node_modules`.

Reinstall the pacakge -  `npm install`.

It works fine ;) :)
