### ISSUE TITLE
yarn start doesnt give error but chunks served through yarn build give application specific error

### ISSUE THREAD

**Issue by rajats123** [webpack/webpack#9330]
# Bug report

**What is the current behavior?**
I am migrating my react 15 application to react16.
`yarn start` works fine and doesnt throw application oriented errors but when chunks are served through `yarn build` , it throws my application oriented errors such as `cant read property of undefined` 

**If the current behavior is a bug, please provide the steps to reproduce.**
1.create a application through CRA
2. Do yarn eject
3. Copied my entire react15 application to src. Made changes according to react16 and used UNSAFE for deprecated methods.
4. then did `yarn start` , application works as intended.No application specific error.
5. Did `yarn build` and served the build folder using `serve -s build`, the build chunks give error such as `cant read property of undefined`.

**What is the expected behavior?**

Chunks served through `yarn build ` shouldnt give error.

**Other relevant information:**
webpack version:  4.29.6
Node.js version: v12.4.0
Operating System: Ubuntu 16.04.1 LTS
Additional tools: npm 6.9.0

**Comment by evilebottnawi** [comment]
Please open issue in CRA

**Comment by rajats123** [comment]
CRA  says that once you eject the application, open the issue in webpack/webpack.

**Comment by evilebottnawi** [comment]
@rajats123 Please create minimum reproducible test repo, we can't find problem using your infromation

**Comment by rajats123** [comment]
@evilebottnawi fixed it.
The error was thrown by this line in reducer `if (summary && summary.last_updated_on) {
    summary.last_updated_on = summary.last_updated_on && formatLastUpdatedDate(summary.last_updated_on);
  }`.

Before that it was, `if (summary) {
    summary.last_updated_on = summary.last_updated_on && formatLastUpdatedDate(summary.last_updated_on);
  }`, but this line didnt threw any error dev mode but threw error in prod build.I can see that above way is the correct way to do it but why didnt this line threw error in dev build.

**Comment by evilebottnawi** [comment]
Looks you use uglifyjs-webpack-plugin, please move to terser-webpack-plugin

**Comment by rajats123** [comment]
Boilerplate was created by CRA , so it came with inbuilt terser-webpack-plugin, i didnt add any plugin on my own, except those inbuilt in CRA.
