### ISSUE TITLE
Document Compiler and Compilation in Plugin API reference

### ISSUE THREAD

**Issue by elyobo** [webpack/webpack#9332]
## Feature request

The [Plugin API documentation](https://webpack.js.org/api/plugins/) is very good when it comes to the availability of hooks, but provides very little documentation of the Compilation and Compiler objects which are so heavily used in them - and the docs [even say](https://webpack.js.org/contribute/writing-a-plugin/#compiler-and-compilation) that

> Among the two most important resources while developing plugins are the compiler and compilation objects. Understanding their roles is an important first step in extending the webpack engine.

There are some [limited docs on the Compiler](https://webpack.js.org/api/node/#compiler-instance) (which is not referenced from the plugin docs), but it does not cover most of the available methods or properties of the compiler.  There doesn't appear to be even this much information on the Compilation, even though examples show some functionality (e.g. [the "writing a plugin" section](https://webpack.js.org/contribute/writing-a-plugin/#example) contains an example that writes to `compilation.assets` but there's no explanation of the `assets` property and how that works).

**What is the expected behavior?**

The documentation should contain all information needed to write plugins; as it is, most plugins will want to use one or both of Compilation and Compiler and so developers will need to read the code to figure it out instead.

**What is motivation or use case for adding/changing the behavior?**

Simplifying plugin development.

**How should this be implemented in your opinion?**

Those familiar with the Compilation and Compiler modules should document their API.

**Are you willing to work on this yourself?**

I'm not at all familiar with either (hence my problem).

**Comment by evilebottnawi** [comment]
Please open issue in webpack docs repo

**Comment by elyobo** [comment]
:blush: doh, yes, will do.

**Comment by elyobo** [comment]
Opened https://github.com/webpack/webpack.js.org/issues/3148, thanks.
