### ISSUE TITLE
I can't generate umd-formatted packages

### ISSUE THREAD

**Issue by iseekTo** [webpack/webpack#9333]
This may not be a mistake.
I'm sorry I wrote some template content ahead of time, because I'm really in a hurry.

**What is the current behavior?**
I wanted to generate umd-formatted packages, but I didn't.
Is it an IDE problem?
The project is simple.

webpack version:  4.35.0
Node.js version: 8.9.4
Operating System: Windos
Additional tools: IDE Vs Code

webpack.config.js--
module.exports = {
    mode: 'production',
    entry: './add.js',
    output: {
        library: "someLibName",
        libraryTarget: "umd",
        filename: "../someLibName.js",
        auxiliaryComment: "Test Comment"
    }
}

package.json--
    "build": "rm -rf someLibName.js && webpack --mode production"

There's also a simple function for exporting modules

**What is the expected behavior?**
I want a format like this.
(function webpackUniversalModuleDefinition(root, factory) {
    /** ... */
｝)(this, function(__WEBPACK_EXTERNAL_MODULE_1__) {
   /** ... */
 })

This may not be a bug. If there's something wrong, please forgive me.
Think you very much. my email is 15036830368@163.com

**Comment by iseekTo** [comment]
oh and This is what I typed in UMD format according to official documents.
just one line
!function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports.someLib}([function(e,t){e.exports=function(e,t){return e+t}}])});

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo and why you need this?

**Comment by iseekTo** [comment]
oh ！The solution is a system problem.
I'm sorry to disturb you.
