### ISSUE TITLE
Stackoverflow in terser plugin

### ISSUE THREAD

**Issue by mifopen** [webpack/webpack#9334]
# Bug report

**What is the current behavior?**
```
ERROR in main.js from Terser
RangeError: Maximum call stack size exceeded
```

**If the current behavior is a bug, please provide the steps to reproduce.**
```
git clone https://github.com/mifopen/terser-webpack-plugin-bug.git
cd terser-webpack-plugin-bug
yarn install
yarn build
```

**What is the expected behavior?**
Should not crash =)
I have tried to turn off terser-webpack-plugin and minify it with the same version of terser and it works

**Other relevant information:**
webpack version: 4.35.0
Node.js version: 12.4
Operating System: macOS Mojave 10.14.5
Additional tools: yarn 1.17.0

**Comment by evilebottnawi** [comment]
Please open issue in terser repo https://github.com/terser-js/terser with reproducible example

**Comment by mifopen** [comment]
@evilebottnawi Are you sure? As I said in the issue, I have tried terser alone and it works fine. Is terser-webpack-plugin supported by terser-js contributors?

**Comment by mifopen** [comment]
Moreover, terser-js/terser repo's bug report guide requires terser cli options but the bug has happened inside webpack build only

**Comment by evilebottnawi** [comment]
> I have tried to turn off terser-webpack-plugin and minify it with the same version of terser and it works

So problem in terser, we just pass your code in terser and return result from terser, double check your configuration, maybe you have old version of terser of have other minimizer too, a lot of projects use terser and no problem, so i think problem in terser(in some rare cases it is happens) or in your configuration

**Comment by evilebottnawi** [comment]
Please open issue in terser-webpack-plugin with reproducible test repo

**Comment by mifopen** [comment]
@evilebottnawi Maybe you missed it, but I have already creat reproducible test repo https://github.com/mifopen/terser-webpack-plugin-bug and added it to steps to reproduce. So you can check very fast, that my configuration is **really** minimal
Ok, I will copy the issue to https://github.com/webpack-contrib/terser-webpack-plugin

**Comment by evilebottnawi** [comment]
Yes, recreate issue in terser-webpack-plugin, thanks, i will see problem in near future

**Comment by sergiix** [comment]
I have the same issue. It's not clear why the issue is closed.
