### ISSUE TITLE
Uncaught TypeError: c.querySelectorAll is not a function at MutationObserver.<anonymous> 

### ISSUE THREAD

**Issue by radiocity** [webpack/webpack#9335]
# Bug report

**What is the current behavior?**

`Uncaught TypeError: c.querySelectorAll is not a function at MutationObserver.<anonymous> ` appears in browsers console with bundle script loaded. Current behavior started right after `npm i` today.
<details>
<pre><code class="language-js">Uncaught TypeError: c.querySelectorAll is not a function
    at MutationObserver.<anonymous>
(anonymous) @ content_script_bundle.js:16
</code></pre>
</details>

**If the current behavior is a bug, please provide the steps to reproduce.**

<details> 
  <summary>1. Config your webpack.config.js</summary>
  <pre><code class="language-js">     // ...
     entry: {
          main: [
               `${src}/js/main.js`,
          ],
     },
     // ...
     {
        test: /\.js$/,
        exclude: /(node_modules|scss)/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              presets: [
                [
                  '@babel/preset-env',
                  {
                    useBuiltIns: 'usage',
                    targets: {
                      chrome: '56',
                      ie: '11',
                    },
                    include: ['es6.promise', 'es7.promise.finally'],
                  },
                ],
              ],
              plugins: [
                '@babel/plugin-syntax-dynamic-import',
                '@babel/plugin-transform-runtime',
              ],
            },
          },
        ],
      },
      // ...
</code></pre>
</details>
<details> 
  <summary>2. Import class into main.js</summary>
  <pre><code class="language-js">import Table from './components/table';
// EOF
</code></pre>
</details>
<details> 
  <summary>3. Embed main.js into your html page</summary>
  <pre><code class="language-html">
<script type="text/javascript" charset="UTF-8" src="/main.js"></script>

</code></pre>
</details>

**What is the expected behavior?**
Scripts should not fail with an exceptions. 

**Other relevant information:**
webpack version:  4.35.0
Node.js version: v12.4.0
Operating System: Windows 10 x64 Pro
Additional tools: [package-log.json  diffs](https://www.diffchecker.com/nUD5Ef1U)

**Comment by radiocity** [comment]
I`m sorry. It was caused by Ghostery extension.

**Comment by RedactedProfile** [comment]
> I`m sorry. It was caused by Ghostery extension.

I was getting this error too in my Angular7 app, it was driving me insane wondering where and when this got introduced. Spent a hot while trying to determine what was causing it. 

You mentioning it was the ghostery extension.. I paused Ghostery and BAM, issue gone. 

What the hell.

**Comment by DanJBower** [comment]
Raised a ticket with them [here](https://ghostery.zendesk.com/hc/en-us/requests/27587)

**Comment by brentsowers1** [comment]
@DanJBower I am getting an error trying to open that link. Did you hear back from Ghostery on this?

**Comment by DanJBower** [comment]
@brentsowers1 I'm afraid I have not heard anything yet. There have been no comments or responses since I created the ticket 3 days ago. If the link is not working, I post any updates I get below.

**Comment by DanJBower** [comment]
I too now seem to be unable to access my ticket with them... But I did get an email off them saying they are bringing a fix out in their next update.

![Screenshot 2019-07-11 08 51 59](https://user-images.githubusercontent.com/40743213/61032412-50b7a280-a3b9-11e9-900a-58068c7ceae1.png)

**Comment by dasDaniel** [comment]
Thanks for following up with Ghostery. I guess I'll need to keep an eye out on this and disable for the time being.

**Comment by raybooysen** [comment]
Here is the Ghostery Github Issue: https://github.com/ghostery/ghostery-extension/issues/406

**Comment by wandersonsc** [comment]
Yeah, I literally just got the exact same error, but I am using _React/Redux_, as soon as I disabled **Ghostery** the error **vanished**.

**Comment by xtrasmal** [comment]
> Yeah, I literally just got the exact same problem, but I am using _React/Redux_, as soon as I disabled **Ghostery** the error **vanished**.

Mine vanished after trusting the site I'm working on :D

**Comment by Gidroponik** [comment]
thanks, i try to find error in my code, this is a problem with Ghostery extension
