### ISSUE TITLE
Source map + minimizer results in silent failure

### ISSUE THREAD

**Issue by underflow00** [webpack/webpack#9338]
# Bug report

**What is the current behavior?**
Using source map with minimizer causes silent failure. Output file not created. No console output.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create empty file `1.js`
2. Create `webpack.config.js` file with contents:
```
const TerserPlugin = require('terser-webpack-plugin');
module.exports = {
    devtool:  'source-map',
    entry: './1.js',
    resolve: {
        extensions: ['.js']
    },
    output: {
        filename: 'main.js',
        path: __dirname,
    },
    optimization: {
        minimize: true,
        minimizer: [
            new TerserPlugin({
                sourceMap: true,
            }),
        ],
    }
};
```
3. Run `webpack --config webpack.config.js`

**What is the expected behavior?**
Output file `main.js` is created. Console output.

**Other relevant information:**
webpack version:  4.35.0
Node.js version: 10.15.3
terser-webpack-plugin version: 1.3.0
Operating System: Win 10

**Comment by underflow00** [comment]
It works after reverting `terser-webpack-plugin` to v1.2.4. Something to do with the terser upgrade? Or is it a caching problem?

**Comment by sokra** [comment]
> It works after reverting `terser-webpack-plugin` to v1.2.4. Something to do with the terser upgrade? Or is it a caching problem?

@webpack-bot move to webpack-contrib/terser-webpack-plugin
