### ISSUE TITLE
You may need an appropriate loader to handle this file type error while importing packages

### ISSUE THREAD

**Issue by kottackalsulvin** [webpack/webpack#9339]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by kottackalsulvin** [comment]
I have installed some js-libp2p packages in my BlockChain application. But I am getting this error "You may need an appropriate loader to handle this file type" while importing the packages in the js file.

I tried to import the packages in the meanstack application and it works well. But showing an error, when it turns into blockchain application.

I’ve also tried every preset/plugin ( stage-0, stage-2, stage-3, transform-es2015-destructuring, transform-object-rest-spread, transform-es2015-spread, transform-es2015-parameter) but nothing works for me.

My webpack.config.js code is shown below,
```
module: {
rules: [
{
test: /\.css$/,
use: [ 'style-loader', 'css-loader' ]
}
],
loaders: [
{ test: /\.json$/, use: 'json-loader' },
{
test: /\.js$/,
exclude: /(node_modules|bower_components)/,
loader: 'babel-loader',
query: {
presets: ['es2015'],
plugins: ['transform-runtime']
}
}
]
},
```
The error message is:

> ERROR in ./node_modules/libp2p/src/index.js
> Module parse failed: Unexpected token (120:8)
> You may need an appropriate loader to handle this file type.
> | this._dht = new DHT(this._switch, {
> | datastore: this.datastore,
> | ...this._config.dht
> | })
> | }
> @ ./app/backend/app.js 17:132-149
> @ multi (webpack)-dev-server/client?http://localhost:8081 ./app/backend/app.js

**Environment**

Npm version: 6.9.0
Node version: 10.16.0
Webpack: 3.11.0
babel-loader: 7.1.0
Os:Ubuntu 18.04

Anyone please help me to resolve this issue.

**Comment by sokra** [comment]
Update your webpack version. Older version doesn't support ES2019 (the spread operator)
