### ISSUE TITLE
lazy load a dynamic require from separate chunks

### ISSUE THREAD

**Issue by jaredly** [webpack/webpack#934]
> I wasn't totally sure what the title should be, so feel free to claify it

In my app, I want to allow the dynamic loading of "plugins", which will offer extra functionality. However, these plugins can come with a large amount of code, and so I don't want them loaded on with the main entry point. Lazy loading to the rescue, right?

Here's the hack I need to make this work:

```js
function getThatPlugin(pluginName, done) {
  if (pluginName === "somemodule") {
    return require.ensure([], () => done(require("somemodule")))
  } else if (pluginName === "othermodule") {
    return require.ensure([], () => done(require("othermodule")))
  } else if () {
    ... etc.
  }
}
```

Importantly, each plugin gets its **own chunk**, and can be loaded independently.

What I'd much rather do is:

```js
function getThatPlugin(pluginName, done) {
  require.ensure([pluginName], () => done(require(pluginName)))
}
```

However (even with `ContextReplacementPlugin`), this creates a single context, such that *all* plugins are in the same chunk. I want there to be multiple chunks, keyed off of the `pluginName`.

Is it possible to get what I want by making a webpack plugin? I don't know how easy this would be to put together.

Calling the plugin would look something like:

```js
LazyExpressionPlugin(/* chunks = */["somemodule", "othermodule"])
```

And then the `require.ensure`, given the value of `pluginName`, would see if it is in the `LazyExpressionPlugin` list, and if it's there, load the appropriate chunk, otherwise throw an error.

My other option is to bypass webpack's require, have each plugin be an entry point, and write my own lazy-loading code. Which is less clean, but reasonable.

**Comment by sokra** [comment]
[contributing guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md)

> Please post a question to [StackOverflow with the webpack tag](http://stackoverflow.com/tags/webpack). Questions that include your webpack.config.js and relevant files are more likely to receive responses.
