### ISSUE TITLE
Webpack output missing quotes when using externals 

### ISSUE THREAD

**Issue by ImanMh** [webpack/webpack#9340]
# Bug report

**What is the current behavior?**
When I require an external module I see this line in my output which contains syntax error: 
```
module.exports = ./manifest.json;
```
with the following error: `SyntaxError: Unexpected token .`

**If the current behavior is a bug, please provide the steps to reproduce.**

This is the external config that **works**: 
```
externals: [
    { './manifest.json': 'require(\'./manifest.json\')' },
]
```
then try to:
```
import manifest from './manifest.json';
```

This is the same config with a different format that **does not work**:
```
externals: [
    './manifest.json',
]
```
I expect this to work due to this document: https://github.com/webpack/docs/wiki/configuration
search the line below in webpack wiki page.
```
   "./e" // "./e" is external (require("./e"))
```

**What is the expected behavior?**
producing: 
```
module.exports = require("./manifest.json");
```
instead of:
```
module.exports = ./manifest.json;
```

**Other relevant information:**
webpack version:  4.35.0
Node.js version: 8.11.4
Operating System: Ubuntu 18
Additional tools:

**Comment by sokra** [comment]
> I expect this to work due to this document: https://github.com/webpack/docs/wiki/configuration
> search the line below in webpack wiki page.

This is the webpack 1 documentation.

Take a look at the latest documentation. Also see `output.libraryTarget`

**Comment by evilebottnawi** [comment]
Answer above

**Comment by ImanMh** [comment]
@sokra I red the docs but I can't figure out how it can help with this particular issue. Could you provide a sample config object?

By the way I want to require the manifest file in my final bundle at runtime.

**Comment by alexander-akait** [comment]
@tavisca-kbobade can you open a new issue with reproducible test repo?
