### ISSUE TITLE
Require included by loader as externals

### ISSUE THREAD

**Issue by QuentinRoy** [webpack/webpack#935]
Hi webpack community!

I'm writing a library using handlebars templates and I want to use Webpack to bundle it.
I'm using [handlebars-loader][1] so that I can require and precompile the templates.

However I don't want handlebars (nor handlebars/runtime) to be included in my compiled library and thus, I would like to set them as externals.

Here is my config file:

```javascript
module.exports = {
    context: __dirname + '/src',
    entry: './index.js',
    output: {
        path: __dirname + '/dist',
        filename: 'stuff.js',
        libraryTarget: 'umd',
        library: 'Stuff'
    },
    externals: [{
        'jquery': {
            root: '$',
            amd: 'jquery',
            commonjs: 'jquery',
            commonjs2: 'jquery'
        },
        // useless does not work :-(
        'handlebars/runtime': {
            root: 'Handlebars',
            amd: 'handlebars.runtime',
            commonjs2: 'handlebars/runtime',
            commonjs: 'handlebars/runtime'
        },
        // useless too, not included anyway
        'handlebars': {
            root: 'Handlebars',
            amd: 'Handlebars',
            commonjs: 'handlebars',
            commonjs2: 'handlebars'
        },
        'backbone': {
            root: 'Backbone',
            amd: 'backbone',
            commonjs: 'backbone',
            commonjs2: 'backbone'
        }
    }],
    module: {
        loaders: [
            { test: /\.handlebars$/, loader: 'handlebars-loader' }
        ]
    }
};
```

Unfortunately it doesn't work and handlebars-loader still makes handlebars/runtime to be bundled...

I believe it is because handlebars/runtime is not required directly, rather it is required in the code added by the loader.

I know I need handlebars/runtime to compile my template. But as I am building a library, I want it to be provided by the user of the library instead of being included. This way, if my user is also using Handlebars, the library is not loaded twice.
I believe it is good practice for libraries to avoid bundling any dependency (it is something we see much too often in my humble opinion). And anyway I think it could be good if loader's dependencies could be external-able just as any dependency.

Thank you for your help.

  [1]: https://github.com/altano/handlebars-loader

**Comment by sokra** [comment]
[contributing guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md)

> Please post a question to [StackOverflow with the webpack tag](http://stackoverflow.com/tags/webpack). Questions that include your webpack.config.js and relevant files are more likely to receive responses.

**Comment by QuentinRoy** [comment]
Well actually [the question already asked][http://stackoverflow.com/questions/29349145/webpack-loaders-require-calls-as-externals/29355311?noredirect=1#comment46920110_29355311]...

But as I didn't get any answer and couldn't figured how to make it works I thought it may not be possible at all.

Sorry.

**Comment by sokra** [comment]
You may create a issue on the handlebar-loader issue tracker...
There is a `runtime` query parameter for the loader that may help.
