### ISSUE TITLE
tree shaking not working with 3rd party module if there is React.createElement

### ISSUE THREAD

**Issue by ziofat** [webpack/webpack#9352]
# Bug report

**What is the current behavior?**

A module has `"sideEffects": false` in its `package.json`, exports a object with a React component declaration on it (`React.createElement('div')`), will not be tree shaked.

**If the current behavior is a bug, please provide the steps to reproduce.**

I have a minimal repo to reproduce this: [https://github.com/ziofat/webpack-treeshaking](https://github.com/ziofat/webpack-treeshaking)

In this repo, I have a module called "some-react-module", imported by the project which is bundled by webpack. In project only `baz` got referred but in the output file, foo is also be bundled.

**What is the expected behavior?**

The object not used will be tree shaked.

**Other relevant information:**
webpack version:  4.35.2
Node.js version: 8.11.3
Operating System: macOS Mojave
Additional tools:

**Comment by sokra** [comment]
see https://github.com/webpack/webpack/issues/9337#issuecomment-507179765

**Comment by ziofat** [comment]
@sokra 
Thanks for the comment. If I understood correct, `sideEffects: false` only affects webpack at file level. Thus if a module has only one file (say it is also bundled by rollup), sideEffects will do nothing at all? Then the file will be handled by terser which will delete dead code but not respect to `sideEffects`.

**Comment by donifer** [comment]
@ziofat Did you manage to figure out the answer to your question?

> Thus if a module has only one file (say it is also bundled by rollup), sideEffects will do nothing at all? 

So if I can't use rollup what should I be using, just plain babel? But then wouldn't that mess it up since its doesn't know how to treat es-modules imports? 🤔

**Comment by ziofat** [comment]
@donifer I split my rollup bundle to several files so that webpack can handle them well by respecting `sideEffect: false`.

The thing is that webpack only know is a file imported or not. If you import a module with side-effect like below
```js
import 'some-module';
```
then webpack will eliminate it when package.json says `sideEffects: false`.

However, it seems webpack will still import the whole file when 

```js
import { Something } from 'some-module';
// Where Something is used below
```

and try to eliminate unused code by uglify plugin.
