### ISSUE TITLE
how to use webpack-dev-middleware in a  OrchardCore CMS with the HMR (Hotmodule reloader) connected

### ISSUE THREAD

**Issue by mmdqq** [webpack/webpack#9355]
how to use webpack-dev-middleware in a  OrchardCore CMS with the HMR (Hotmodule reloader) connected
I use Microsoft.AspNetCore.SpaServices
![image](https://user-images.githubusercontent.com/4881282/60556511-4ae80e80-9d74-11e9-81b6-8b9611b5a7a7.png)

![image](https://user-images.githubusercontent.com/4881282/60556498-360b7b00-9d74-11e9-9a1d-453908fba924.png)

**Comment by evilebottnawi** [comment]
Please use stackoverflow or gitter for question, configuration depends on many things, better open issue in `OrchardCore CMS`
