### ISSUE TITLE
jsonpScriptSrc may include a non-trivial amount of redundant bytes

### ISSUE THREAD

**Issue by gusvargas** [webpack/webpack#9357]
# Bug report

**What is the current behavior?**

When code splitting using a named chunk webpack outputs a function like:

```js
/******/ 	// script path function
/******/ 	function jsonpScriptSrc(chunkId) {
/******/ 		return __webpack_require__.p + "" + ({"feature":"feature"}[chunkId]||chunkId) + ".js"
/******/ 	}
```
where `feature` is the name of the split chunk.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/gusvargas/webpack-jsonpscriptsrc-bug
```
$ git clone git@github.com:gusvargas/webpack-jsonpscriptsrc-bug.git
$ cd webpack-jsonpscriptsrc-bug
$ yarn
$ yarn build
```

Examine the `jsonpScriptSrc` function in `dist/main.js`.

**What is the expected behavior?**

Given the `||chunkId` it should be reasonable to omit the name map entry for `feature` and simply let it fall back to the `chunkId`. For apps with a non-trivial amount of named splits (in our apps it's not uncommon to get into the 100s), having an "identity" entry for every named chunk yields a non-trivial amount of redundant bytes.

**Other relevant information:**
webpack version:  4.35.2
Node.js version: 8.9.1
Operating System: macOS 10.12.5
Additional tools:

**Comment by sokra** [comment]
It's more optimized in webpack 5 and omits key-value-pairs if they match chunkId.

In production mode `chunkId` is usually numeric so this shouldn't occur too often.
