### ISSUE TITLE
Dynamic import() only working for specific files

### ISSUE THREAD

**Issue by aaronjedwards** [webpack/webpack#9358]
# Bug report

**What is the current behavior?**
Dynamic Code Splitting is not working for specific files. I am using the following to code split:
```js
const myPage = React.lazy(() => import(/* webpackChunkName: "myPage" */'../pages/myPage/index'));
```
This is only resulting in one bundle file. However, if I create a new file and copy the contents of the previous file into it, and instead run: 
```js
const myPage = React.lazy(() => import(/* webpackChunkName: "myPage" */'../pages/myPage/different-file'));
```
then webpack outputs two bundles, as expected. Strangely enough, if I rename the original `index.js` file that I was importing at first and then create a new `index.js` file in the same folder, everything works as expected.

**If the current behavior is a bug, please provide the steps to reproduce.**
I am unable to recreate the behavior given its strange nature.

**What is the expected behavior?**
I am expecting that the `import()` statement should be causing a code split regardless of file names or underlying file metadata.

Given the number of seemingly unrelated things I have tried to correct this issue, my thought is that it has something to do with the file (metadata or other system information) itself that is causing the issue.

**Other relevant information:**
webpack version:  4.35.2
Node.js version: 11.7.0
Operating System: macOS
Additional tools: babel, babel-loader

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by itsjoekent** [comment]
Originally I thought I was having a bug with React, but starting to think it might be a build issue?

Here is a very simple code sandbox with a dynamic import and the React component seemingly not loading properly, https://codesandbox.io/s/angry-swanson-r4rf2

**Comment by aaronjedwards** [comment]
I will try and work together a reproducible example when I get a chance, however I'm unsure if I will be able to given I'm unsure of what is causing the issue in the first place. Ill take a crack at it and report back.

**Comment by aaronjedwards** [comment]
I was able to recreate the issue and I know what is happening, but not why.

It seems that there is an issue when exporting a set of components like so from one file:
```js
export { default as MyLazyComponent } from './lazyComponents/MyLazyComponent';
export { default as MyOtherComponent } from './otherComponents/MyOtherComponent';
```
And then trying to dynamically import one of them while importing the other one normally like this:
```js
import { MyOtherComponent } from './components'
const MyLazyComponent = React.lazy(() => import(/* webpackChunkName: "myLazyComponent" */'./components/lazyComponents/MyLazyComponent'));
```

This results in only one bundle being output from webpack:
```
yarn run v1.16.0
$ webpack
Hash: 03a7e5d4bed4c39cfa86
Version: webpack 4.35.3
Time: 480ms
Built at: 07/16/2019 7:06:07 PM
         Asset     Size  Chunks             Chunk Names
main.bundle.js  118 KiB       0  [emitted]  main
Entrypoint main = main.bundle.js
[8] (webpack)/buildin/global.js 472 bytes {0} [built]
[9] ./src/index.js + 2 modules 988 bytes {0} [built]
    | ./src/index.js 658 bytes [built]
    |     + 2 hidden modules
    + 8 hidden modules
✨  Done in 1.50s.
```
I've reproduced the issue in [this repo](https://github.com/aaronjedwards/webpack-dynamic-import-issue). Now that I know what is causing the issue I can work around it, but if someone could provide an explanation of why this is happening it would be much appreciated.

**Comment by sokra** [comment]
`import { MyOtherComponent } from './components'` also loads `MyLazyComponent`. So `import()` does nothing as all modules are already loaded.

You might thing `import { MyOtherComponent } from './components'` only loads `./otherComponents/MyOtherComponent` but this is not true by default. The spec says all dependencies need to be executed.

There is an optimization which might help, but this is opt-in as it's not spec-conform: see https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

**Comment by aaronjedwards** [comment]
Does that mean that by default my final bundle will include the unused components? I was under the (maybe naive) impression that there was some sort of default tree shaking happening with webpack. Is that not the case?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sokra** [comment]
> Does that mean that by default my final bundle will include the unused components?

yes

> I was under the (maybe naive) impression that there was some sort of default tree shaking happening with webpack. Is that not the case?

No this will only happen if you specify `sideEffects` in `package.json` as it would be against the ESM spec.

see here: https://webpack.js.org/guides/tree-shaking/#clarifying-tree-shaking-and-sideeffects

**Comment by aaronjedwards** [comment]
Thanks for the help explaining what is happening in this scenario! I hope to learn more about tree shaking and how it works to help slim down my bundle sizes.
