### ISSUE TITLE
Is it possible to specify loaders for specific node_modules?

### ISSUE THREAD

**Issue by yamalight** [webpack/webpack#936]
Hi there! Wasn't able to find the answer to this one in docs or google, so I thought I'd ask here.
We have a project written completely in ES6 and at the moment we use browserify with babel to compile it, but I'd really want to switch to webpack for a number of reasons. 
The problem I'd encountered while trying out the webpack is that I couldn't find a way to say that some of the dependencies in node_modules should be loaded using babel-loader. Browserify allows you to have the following entry in package.json to specify transform for module:
```json
"browserify": {
    "transform": [
      "babelify"
    ]
  }
```
Is there something similar for webpack? 
I'd tried writing complex regexp for ignoring non-our packages, but turned out that this is a terrible option since we have a nested structure of dependencies.

**Comment by evidens** [comment]
Did you try creating a loader rule for the module in question?
```javascript
{
  test: /node_modules\/<YOUR MODULE>\/.*\.js/,
  loader: "babel-loader"
},
```

**Comment by yamalight** [comment]
@evidens that's the way I used it, yep. Just thought there's a better way than creating rules for each of the modules that requires pre-compilation (sometimes we have quite a lot of them).

**Comment by andreypopp** [comment]
@yamalight you can try this https://github.com/andreypopp/webpack-package-loaders-plugin

**Comment by yamalight** [comment]
@andreypopp oh, that looks like something that might work perfectly, thanks!

**Comment by yamalight** [comment]
I guess I'll close the issue now.
