### ISSUE TITLE
how can i change rules in child compiler

### ISSUE THREAD

**Issue by hangaoke1** [webpack/webpack#9362]
in my application, i will use createChildCompiler to do something. but in child compiler i need to change the rules loader, but i don't know how to achieve.  help ~~~~

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
