### ISSUE TITLE
`require.context` with resource queries

### ISSUE THREAD

**Issue by bitttttten** [webpack/webpack#9364]
## Feature request

To be able to use require.context along with resource queries.

I have a loaded that uses `this.resourseQuery` to parse the file differently. It accepts `frontMatter` with a few options. If I use `require` it works great:

`require('./pages/about.en.md?frontMatter=only')`

Although if I want to use require.context to pick up all md files, and also use this resource query, it will fail:

`require.context('./data/', false, /\.md?frontMatter=only$/)`

or

`require.context('./data/', false, /\.md\?frontMatter=only$/)`

**What is the expected behavior?**

I hope that the loader will have resource queries passed on?

**What is motivation or use case for adding/changing the behavior?**

To use resource queries alongside require.context

**Are you willing to work on this yourself?**

If I am able to, then I would.. although it's not my strength so let's say I won't able to / no.

**Comment by sokra** [comment]
try this: `require.context('./data/?frontMatter=only', false, /\.md$/)`

**Comment by bitttttten** [comment]
Thanks!
