### ISSUE TITLE
Update acorn for dynamic import

### ISSUE THREAD

**Issue by westn** [webpack/webpack#9365]
Perhaps an idea to update `acorn` and remove `acorn-dynamic-import` now when https://github.com/acornjs/acorn/pull/834 is released (acorn 6.2.0)?

**Comment by evilebottnawi** [comment]
@westn please use issue template, also it is done for webpack@5

**Comment by sokra** [comment]
Actually it's not yet done for the `next` branch, so send a PR

**Comment by vankop** [comment]
Seems it is solved https://github.com/webpack/webpack/pull/9370

**Comment by evilebottnawi** [comment]
Yep, we can close :+1: need rebase for next too

**Comment by sokra** [comment]
> need rebase for next too

We don't need that, as master is merged into next after each release.
