### ISSUE TITLE
File paths from require.resolve do not load

### ISSUE THREAD

**Issue by itowlson** [webpack/webpack#9367]
# Bug report

**What is the current behavior?**

When you `require.resolve` a file, Webpack substitutes the file's module ID.  This means that trying to read the file with `fs.readfileSync` fails with an error.

**If the current behavior is a bug, please provide the steps to reproduce.**

Example code is in the following repro:

https://github.com/itowlson/require-resolve-webpack-woe

To see the intended behaviour, run `node src/index.js`.  This prints the contents of `src/foo.js`.

To see the webpacked behaviour, run `npm run compile` then `node dist/index.js`.  This prints an error message `TypeError: Cannot read property '1' of undefined`.

The key lines are these:

```javascript
const foopath = require.resolve('../src/foo');
const footext = fs.readFileSync(foopath, 'utf-8');
```

Webpack compiles them to:

```javascript
const foopath = /*require.resolve*/(2);
const footext = fs.readFileSync(foopath, 'utf-8');
```

which fails because 2 is not a file path.

**What is the expected behavior?**

The webpacked file `dist/index.js` should produce the same output as `src/index.js`.  E.g. the `require.resolve` call should be left alone or the `fs` module should be shimmed to accept Webpack module IDs.

**Why is this an issue?  Why are you doing things this way?**

I know this is a silly example - my real issue is trying to webpack a project that indirectly uses `jsonpath`, which includes the following:

```javascript
var file = require.resolve('esprima');
var source = fs.readFileSync(file, 'utf-8');

// inject '@' as a valid identifier!
source = source.replace(/(function isIdentifierStart\(ch\) {\s+return)/m, '$1 (ch == 0x40) || ');
```

and

```javascript
if (fs.readFileSync) {
  grammar.moduleInclude = fs.readFileSync(require.resolve("../include/module.js"));
  grammar.actionInclude = fs.readFileSync(require.resolve("../include/action.js"));
}
```

(I have tried using `externals` to exclude `esprima`, which might fix the first example.  Funnily, this externalised calls to `require('esprima')` but NOT calls to `require.resolve('esprima')`.  I can't see how to use externals to fix the second example.)

The `jsonpath` package is not under my control; even the NPM package that references it is not under my control so I can't remove the dependency. I can `externals` the whole `jsonpath` package, but then I need to whitelist all of its (transitive) dependencies to be include in my shipping `node_modules` folder, which is laborious and brittle (the context is a VS Code extension, where dependencies must be included in the zip file).

Hope this explains why this is a real problem - please let me know if I can provide any more info.

**Other relevant information:**
webpack version:  4.35.2
Node.js version: 10.1.0
Operating System: Windows
Additional tools: -

**Comment by sokra** [comment]
`require.resolve` returns the module identifier. This is not the filename in webpack. Actually since the module is bundled anyway there is no filename for a module anymore. Since it's bundled you can't `readFileSync` a module anyway.

Sorry, things like that are unsupported. Find a replacement or send a pullrequest to jsonpath...

**Comment by amerllica** [comment]
Hi @itowlson , how you fix your issue?

**Comment by itowlson** [comment]
@amerllica This is a terrible answer for the general problem, but I got lucky and found an upgrade that removed the problematic `jsonpath` dependency.  In my case the direct dependency was `@kubernetes/client-node` and they had since changed that to depend on a (forked? different?) JSONPath implementation, which did not have the `readFileSync` problem.  Unfortunately I can't remember the ID of the fixed JSONPath package...

**Comment by amerllica** [comment]
@itowlson, thanks for your answer, actually my issue comes from using `html-minifier`, I don't know why, but when I'm using it for minifying parsed HTML in the server of React SSR, just in the production version I face this issue.

Weird, but I comment the `import { minify } from 'html-minifier';` and return HTML simple the issue disappeared.

Ridiculous, but it is real.
