### ISSUE TITLE
how can i change rules in child compiler ?

### ISSUE THREAD

**Issue by hangaoke1** [webpack/webpack#9368]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
```js
// TODO: how can i add other rules or change rules for child compiler

const outputOptions = {
    filename: outputJSPath,
    publicPath: outputPublicPath
};

const childCompiler = compilation.createChildCompiler('vue-skeleton-webpack-plugin-compiler', outputOptions);

childCompiler.context = context;

// ...

childCompiler.runAsChild(callback);

```
in childCompiler i want to use different rules or change the parentCompiler rules loader,
but i don't how to achieve it 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
i can apply different rules in childComplier and it can work fine

**If this is a feature request, what is motivation or use case for changing the behavior?**
i can apply different rules in childComplier and it can work fine

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
webpack: v4.35.2

**Comment by sokra** [comment]
You can match on the compiler name in rules

``` js
module.rules: [
  {
    compiler: /vue-skeleton/,
    // compiler: { not: /vue-skeleton/ },
    use: "magic"
  }
]
```

**Comment by hangaoke1** [comment]
@sokra thank you very much it works, Is it possible to configure this rule in the plugin?

**Comment by sokra** [comment]
That's not how it's intended, but you could this in plugins:

* Change the options object to add the rule
* Add the loader in `NormalModuleFactory.hooks.afterResolve`

**Comment by hangaoke1** [comment]
@sokra ，Thank you, regarding the first point you mentioned above, where can I modify the options in the plugin? The method I tried below doesn't work. look forward to your reply
```js
   // my plugin
    apply(compiler) {
        let skeletons;
        if (compiler.hooks) {
           
            // try to change the webpack module rules
            compiler.options.module.rules = [...compiler.options.module.rules, ...styleLoaders({
                sourceMap: false,
                extract:  true
            })]
       }
    }
```

**Comment by dkamyshov** [comment]
> You can match on the compiler name in rules
> 
> ```js
> module.rules: [
>   {
>     compiler: /vue-skeleton/,
>     // compiler: { not: /vue-skeleton/ },
>     use: "magic"
>   }
> ]
> ```

Hi, @sokra! Is this somehow achievable with the new worker syntax?
