### ISSUE TITLE
Site without JS

### ISSUE THREAD

**Issue by haf** [webpack/webpack#937]
How can I configure webpack to spit out my html- and css-files on their own, so that I don't have to bootstrap anything with JS?

I have:

 - index.html
 - index.css
 - index.js

I want index.html to work with index.css even if index.js isn't loaded. Could you give a sample config?

**Comment by sokra** [comment]
[contributing guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md)

> Please post a question to [StackOverflow with the webpack tag](http://stackoverflow.com/tags/webpack). Questions that include your webpack.config.js and relevant files are more likely to receive responses.

In this case the information is also hidden in the [documentation](http://webpack.github.io/docs/).

**Comment by haf** [comment]
Where? I've read it all.

**Comment by haf** [comment]
What's missing is a way to say; copy things matching this regex, verbatim. Because if one encounters a bug in webpack's dependencies, like I've done with both node-sass and with style-loader!css-loader, you get stuck. So there's a need for an exit path, save sending a PR to the project or giving a failing test.

**Comment by sokra** [comment]
http://webpack.github.io/docs/stylesheets.html#separate-css-bundle

**Comment by haf** [comment]
That doesn't solve it for font-faces, which are imported by css files.
