### ISSUE TITLE
ESM modules are not scope hoisted because of global polyfilling

### ISSUE THREAD

**Issue by TrySound** [webpack/webpack#9372]
# Bug report

I found the problem why treeshaking still does not work and why esm gives bigger bundles.
https://twitter.com/IAmTrySound/status/1147174216095211520

**What is the current behavior?**

This piece of code leads to wrapping whole module and all its dependencies with webpack module
```js
var global$1 = (typeof global !== "undefined" ? global :
            typeof self !== "undefined" ? self :
            typeof window !== "undefined" ? window : {});
```

```js
/* WEBPACK VAR INJECTION */(function(global) {
...
/* WEBPACK VAR INJECTION */}.call(this, __webpack_require__(14)))
```

**If the current behavior is a bug, please provide the steps to reproduce.**

bundle this in production mode
```js
import jss from 'jss';

console.log(jss)

var global$1 = (typeof global !== "undefined" ? global :
            typeof self !== "undefined" ? self :
            typeof window !== "undefined" ? window : {});
```

This leads to larger bundles and global warming.

**What is the expected behavior?**

Inject `global` polyfill in scope without useless wrapping all freaking modules.

**Other relevant information:**
webpack version:  4.35.2
Node.js version: 
Operating System: 
Additional tools:

**Comment by sokra** [comment]
This is fixed in the `next` branch (webpack 5)

**Comment by evilebottnawi** [comment]
Fixed in `webpack@5`, if somebody will face with problem feel free to open new issue, thanks for using webpack
