### ISSUE TITLE
drop resolve.moduleExtensions and resolve.enforceModuleExtension

### ISSUE THREAD

**Issue by vankop** [webpack/webpack#9374]
# Bug report

**What is the current behavior?**

Seems like `resolve.moduleExtensions` and `resolve.enforceModuleExtension` are droped from usage, but still presented in JSON schema, Typescript definition and in documentation (https://webpack.js.org/configuration/resolve/#resolveloadermoduleextensions and https://webpack.js.org/configuration/resolve/#resolveenforcemoduleextension)

**If the current behavior is a bug, please provide the steps to reproduce.**

Just search usage of this parameters

**What is the expected behavior?**

Remove from JSON schema

**Other relevant information:**
webpack version:  ^4.0.0

This issue related to https://github.com/webpack/webpack/issues/3197 , but original one looks too old

**Comment by evilebottnawi** [comment]
PR welcome :+1:

**Comment by sokra** [comment]
Already dropped in `next` branch. Can't drop in `master` because it would be a breaking change.
