### ISSUE TITLE
TypeError: __webpack_require__(...) is not a function

### ISSUE THREAD

**Issue by zimtsui** [webpack/webpack#9379]
# Bug report

**What is the current behavior?**
```shell
TypeError: __webpack_require__(...) is not a function
```

**If the current behavior is a bug, please provide the steps to reproduce.**

it's a really simple situation that takes you 5 minutes to check the entire codes.

```js
// ./src/index.js
require('./other');


// ./src/other.js
module.exports = { a: 1 };


// ./babel.config.js
module.exports = {
    "presets": ["@babel/preset-env"],
    "plugins": ["babel-plugin-source-map-support"]
};


// ./webpack.config.js
const path = require('path');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const webpackNodeExternals = require('webpack-node-externals');

module.exports = {
    mode: 'development',
    target: 'node',
    devtool: 'source-map',
    entry: './src/index.js',
    output: {
        filename: 'index.js',
        path: path.resolve(__dirname, 'dist'),
    },
    module: {
        rules: [{ test: /\.js$/, use: 'babel-loader' }],
    },
    plugins: [
        new CleanWebpackPlugin(),
    ],
    externals: [webpackNodeExternals()],
};
```

```json
// package.json
{
  "name": "webpack-bug",
  "version": "0.0.1",
  "description": "",
  "main": "./dist/index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack"
  },
  "author": "",
  "license": "UNLICENSED",
  "devDependencies": {
    "@babel/cli": "^7.5.0",
    "@babel/core": "^7.5.0",
    "@babel/preset-env": "^7.5.0",
    "babel-loader": "^8.0.6",
    "babel-plugin-source-map-support": "^2.0.1",
    "clean-webpack-plugin": "^3.0.0",
    "webpack": "^4.35.2",
    "webpack-cli": "^3.3.5",
    "webpack-node-externals": "^1.7.2"
  },
  "dependencies": {
    "source-map-support": "^0.5.12"
  }
}
```

you can clone the repo for checking.

```shell
$git clone git@github.com:zimtsui/webpack-bug.git
$cd ./webpack-bug
$npm i
$npm run build
$node .
TypeError: __webpack_require__(...) is not a function
```

`babel-plugin-source-map-support` is a simple babel plugin, which just add a single line at the beginning.

```shell
$npx babel ./src/index.js
"use strict";

require("source-map-support/register"); // the plugin adds this line

require('./other');
```

if you disable the plugin and manually add that line in source file, everything will be ok:

```js
// ./babel.config.js
module.exports = {
    "presets": ["@babel/preset-env"],
    // "plugins": ["babel-plugin-source-map-support"]
};


// ./src/index.js
require('source-map-support/register');
require('./other');
```

if you use `exports` instead of `module.exports` to export, everything will be ok as well:

```js
// ./src/other.js
exports.a = 1;
// module.exports = { a: 1 };
```

**What is the expected behavior?**
to exit normally and output nothing.

**Other relevant information:**
webpack version:  4.35.2
Node.js version: 10.16.0 lts
Operating System: ubuntu 18.04
Additional tools:

**Comment by evilebottnawi** [comment]
Problems in `webpackNodeExternals`, it is package has invalid regexp

**Comment by zimtsui** [comment]
O(∩_∩)O xie xie

**Comment by zimtsui** [comment]
> Problems in `webpackNodeExternals`, it is package has invalid regexp

emmm...that seems unrelated with `webpackNodeExternals`

if you comment `externals`, the problem still exists

```js
// webpack.config.js
const path = require('path');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
// const webpackNodeExternals = require('webpack-node-externals');

module.exports = {
    mode: 'development',
    target: 'node',
    devtool: 'source-map',
    entry: './src/index.js',
    output: {
        filename: 'index.js',
        path: path.resolve(__dirname, 'dist'),
    },
    module: {
        rules: [{ test: /\.js$/, use: 'babel-loader' }],
    },
    plugins: [
        new CleanWebpackPlugin(),
    ],
    // externals: [webpackNodeExternals()],
};

```

**Comment by evilebottnawi** [comment]
@zimtsui can you create minimum reproducible test repo?

**Comment by zimtsui** [comment]
> @zimtsui can you create minimum reproducible test repo?

maybe that's already simplest repo. 2 source files of single line only.

`https://github.com/zimtsui/webpack-bug`

`git@github.com:zimtsui/webpack-bug.git`

something seems wrong with `webpack/buildin/harmony-module.js`

in the compiled file, `__webpack_require__(...)` returns an empty object `{}`, but used as a function.

**Comment by zimtsui** [comment]
babel-cli makes the same output for these 2 situations:

1. manually adding `require("source-map-support/register");` on the top of source file
2. adding `require("source-map-support/register");` with `babel-plugin-source-map-support`

therefore, theoretically, babel-load should output the same, and the bundler should run in the same context.

but actually, webpack used `webpack/buildin/harmony-module.js` for situation 2, but didn't for situation 1

```shell
// for situation 2
[./node_modules/webpack/buildin/harmony-module.js] (webpack)/buildin/harmony-module.js 670 bytes {main} [built]
[./src/index.js] 101 bytes {main} [built]
[./src/other.js] 84 bytes {main} [built]

// for situation 1
[./src/index.js] 60 bytes {main} [built]
[./src/other.js] 46 bytes {main} [built]
```

**Comment by sokra** [comment]
see https://babeljs.io/docs/en/options#sourcetype

babel-plugin-source-map-support seem to insert `import`s

**Comment by zimtsui** [comment]
> see https://babeljs.io/docs/en/options#sourcetype
> 
> babel-plugin-source-map-support seem to insert `import`s

but `import` will be compiled to `require` by `@babel/preset-env`

just try:
```shell
npx babel ./src/index.js
```

**Comment by evilebottnawi** [comment]
@zimtsui should be not, please provide your babel config

**Comment by zimtsui** [comment]
> @zimtsui should be not, please provide your babel config

[https://github.com/zimtsui/webpack-bug/blob/master/babel.config.js](https://github.com/zimtsui/webpack-bug/blob/master/babel.config.js)

```js
module.exports = {
    "presets": ["@babel/preset-env"],
    "plugins": ["babel-plugin-source-map-support"]
};
```

**Comment by evilebottnawi** [comment]
Can you try without `babel-plugin-source-map-support`?

**Comment by zimtsui** [comment]
that'd be correct. see the content above.

but i dont think it's problem of that plugin, because the output of babel-cli goes well

**Comment by evilebottnawi** [comment]
You should not content `import` to `require` fro webpack@4, you should keep `import`, if plugin change this, please look in options to disable this behavior or open issue about this in plugin repo, thanks

**Comment by zimtsui** [comment]
> You should not convert `import` to `require` for webpack@4, iif plugin change this, please look in options to disable this behavior or open issue about this in plugin repo

webpack@4 does support commonjs exactly. 

furthermore, if `source-map-support` has to be import as es6 module, nodejs should catch a runtime- error from the plugin, but not a type-error from webpack

**Comment by sokra** [comment]
> but `import` will be compiled to `require` by `@babel/preset-env`
> 
> just try:
> 
> ```shell
> npx babel ./src/index.js
> ```

The behavior for babel-cli and babel-loader differs. babel-loader doesn't compile to commonjs because webpack understands ESM.

**Comment by sokra** [comment]
Set `sourceType: "unambiguous"` as I recommended.

**Comment by zimtsui** [comment]
> > but `import` will be compiled to `require` by `@babel/preset-env`
> > just try:
> > ```shell
> > npx babel ./src/index.js
> > ```
> 
> The behavior for babel-cli and babel-loader differs. babel-loader doesn't compile to commonjs because webpack understands ESM.

since webpack understands esm, it should work if i make esm everywhere, just like:

```js
// ./src/index.js
import './other';


// ./src/other.js
export default { a: 1 };


// ./babel.config.js
module.exports = {
    "presets": ["@babel/preset-env"],
    "plugins": ["babel-plugin-source-map-support"],
};
```

but in fact it doesn't work.


even though I set `"sourceType": "unambiguous"` (`"target": "node"` has been set), webpack includes all build-in modules such as `fs` `path` ...

```shell
$ npx webpack

Hash: aca1fd6fa5a958740feb
Version: webpack 4.35.2
Time: 1093ms
Built at: 07/09/2019 3:53:54 PM
       Asset     Size  Chunks             Chunk Names
    index.js  131 KiB    main  [emitted]  main
index.js.map  217 KiB    main  [emitted]  main
Entrypoint main = index.js index.js.map
[./src/index.js] 162 bytes {main} [built]
[./src/other.js] 155 bytes {main} [built]
[fs] external "fs" 42 bytes {main} [optional] [built]
[module] external "module" 42 bytes {main} [optional] [built]
[path] external "path" 42 bytes {main} [built]
    + 14 hidden modules
```

im sure there is something wrong within webpack loading mechanism.

**Comment by zimtsui** [comment]
im not a free rider who's saying "hey, debug this for me"

[this repo](https://github.com/zimtsui/webpack-bug) is what i made specially for this bug.

sincerely, i suggest webpack members debug this problem **FOR WEBPACK**

**Comment by evilebottnawi** [comment]
@zimtsui it is not webpack problem as we said above, also i can't reproduce problem using your reproduce test repo

**Comment by sokra** [comment]
I could reproduce the problem with your repo.

Adding `sourceType: "unambiguous"` to babel.config.js fixes the problem.

> webpack includes all build-in modules such as `fs` `path` ...

These are modules `source-map-support/register` are using, so that's fine

**Comment by zimtsui** [comment]
> I could reproduce the problem with your repo.
> 
> Adding `sourceType: "unambiguous"` to babel.config.js fixes the problem.
> 
> > webpack includes all build-in modules such as `fs` `path` ...
> 
> These are modules `source-map-support/register` are using, so that's fine

that really makes sense. thank you very much O(∩_∩)O
