### ISSUE TITLE
csso crashes; can I do without it?

### ISSUE THREAD

**Issue by haf** [webpack/webpack#938]
I want to use the CSS code that I have written, that works well in the browser; but the css loader crashes, so I get stuck. Is there a way to tell webpack to take the file verbatim -- remember I reference resources, so I would need to have a way to specify each resource (manually is FINE!) that needs to be copied to the output somewhere.

Could you give me an example config for that? Thanks!

**Comment by sokra** [comment]
[contributing guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md)

> Please post a question to [StackOverflow with the webpack tag](http://stackoverflow.com/tags/webpack). Questions that include your webpack.config.js and relevant files are more likely to receive responses.

**Comment by haf** [comment]
If you have discovered a bug or have a feature suggestion, feel free to create an issue on Github.

Feature suggestion; a pass-through css-loader/parser that doesn't crash for things that its grammar doesn't support -- and just using file loader like in https://github.com/webpack/webpack/issues/395 doesn't work. I've read all the docs, so I can conclude it's not something you can configure easily.

The problem is that the css file does the 'importing' of the images and type-faces, and there's no other way for webpack to 'know' about them.

Correct me if I'm wrong?

**Comment by sokra** [comment]
let's discuss it here:

https://github.com/webpack/css-loader/issues/43
