### ISSUE TITLE
Multiple Webpack bundles override function names?

### ISSUE THREAD

**Issue by funglaub** [webpack/webpack#9381]
Hey there,

I have two Webpack bundles integrated into site. I added chunks: ‘initial’ to optimization in both projects and each bundle works isolated.  However, chunks from both projects seem to overwrite global functions, which leads to errors like: “n is not a function” if I load both bundles. Errors may change if I switch the order.

Is there a possibility to namespace functions and variables in the common chunks?

Thanks

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
