### ISSUE TITLE
Cannot load assets outside of webpack root with dynamic paths

### ISSUE THREAD

**Issue by DelvarWorld** [webpack/webpack#939]
There was a previous unresolved issue similar to this one: https://github.com/webpack/webpack/issues/580, but I don't think it has the same symptoms / cause.

In my code I have this setup of assets vs application code:

    project/
        app.js
        webpack.config.js
        node_modules/
    assets/
        img.png

In my `app.js` code I have a require statement:

    var img = require("../assets/" + val + ".gif")

And I have this loader:

      {test: /\.gif$/, loader: 'url'},

According to http://webpack.github.io/docs/context.html#dynamic-requires (it would be nice if this had its own page, "context" is not an obvious place to look for require problems) this should work fine, and it should pull in the image. However, on build, it warns with this:

    WARNING in ../common ^\.\/.*\.gif$
    Module not found: Error: Cannot resolve module 'url' in /assets
    @ ../assets ^\.\/.*\.gif$

And if you try it with the file loader:

    WARNING in ../common ^\.\/.*\.gif$
    Module not found: Error: Cannot resolve module 'file' in /assets
    @ ../assets ^\.\/.*\.gif$

They aren't just warnings, when running the app the dynamic images do not show up in the browser, with the error:

    Uncaught Error: Cannot find module './img.png'.

What gives? It looks like it's 404ing on the file based on the message, but the file exists...
Wait, maybe it can't find those loaders? But they exist, they're installed...
It works for paths inside the project...
It works for non-dynamic paths outside of the project...

I do not know the cause of this issue, however after much head-desk-banging I found out that if you do this **in the parent folder…**

    npm install --save-dev url-loader -file-loader

…then it works! This is very strange, it looks like webpack is trying to read `node_modules` from the wrong folder. Or something. I'm really not sure. But this doesn't look like desired behavior either way?

**Comment by sokra** [comment]
Workaround is using the `resolveLoader.root` option.
