### ISSUE TITLE
"verbose" preset is not outputting "everything" in stats.json

### ISSUE THREAD

**Issue by slavafomin** [webpack/webpack#9392]
Hello!

According to [the documentation](https://webpack.js.org/configuration/stats/#stats) the `verbose` preset should `"Output everything"` in `stats.json` file. However, in the [source code](https://github.com/webpack/webpack/blob/master/lib/Stats.js#L1362) the `modules` property is set to `false` for the `verbose` preset. Therefore, it's not outputting `"everything"`.

I've lost a whole day trying to figure out why the analyzing tools are not working correctly with my `stats.json` file and I was absolutely sure, that it contains all the needed information. Even more awful thing is that a lot of people encountering the same behavior and blame the tools for that, thinking that their `stats.json` is perfectly fine, [including the official analyze tool](https://github.com/webpack/analyse/issues/30) 😨

Should the documentation be updated or the preset itself?

---

One of the workarounds is to use the `webpack-stats-plugin` to generate the stats file:

```typescript
import { StatsWriterPlugin } from 'webpack-stats-plugin';

const plugins = [
  new StatsWriterPlugin({ fields: null }), // outputs all fields
];
```

**Comment by evilebottnawi** [comment]
Plese use issue template otherwise issue was closed

**Comment by sokra** [comment]
verbose is not intended to "output everything". It output much info, but not everything. I. e. you could include source code of modules too, this is also omitted. We could add a preset to output everything `"all"`.

Anyway we should fix the documentation.

We can't modify the `verbose` preset as this would be a breaking change.

**Comment by evilebottnawi** [comment]
@sokra maybe we can do it for webpack@5?

**Comment by evilebottnawi** [comment]
bump

**Comment by yeegor** [comment]
Still experiencing the issue in 2020 :'(

**Comment by snitin315** [comment]
Adding support of another `preset: all`  to output everything seems good to me.

**Comment by evilebottnawi** [comment]
@snitin315 Yes, maybe `vvv` (`very very verbose`)

**Comment by evilebottnawi** [comment]
Solved in webpack@5

`verbose` is not out everything because it will be very big output with extra unnecessary information in most of cases, anyway if you want to output `all`, please use:
```
stats: {
    all: true
  },
```
