### ISSUE TITLE
(Webpack > 4.3.10) ReferenceError: document is not defined

### ISSUE THREAD

**Issue by ianks** [webpack/webpack#9394]
# Bug report

**What is the current behavior?**

Before 4.31.0, webpack never referenced `document` when it is not defined. After this release, there is code somewhere which assumes a global `document` is available. This makes it so server side rendering does not work in our application.

**If the current behavior is a bug, please provide the steps to reproduce.**

Using webpack > 4.31.0, compile a simple app for the web target, then attempt to run in an environment without `document`.

**What is the expected behavior?**

Webpack should always check to see if `document` is defined before attempting to access it.

**Other relevant information:**
webpack version: any version > webpack@4.31.0
Node.js version: v10.15.0
Operating System: Linux

### Stack Trace

```
MiniRacer::RuntimeError:
  ReferenceError: document is not defined
JavaScript at length (/webpack:/__lib.[name]/webpack/bootstrap:48:1)
JavaScript at Array.forEach (<anonymous>)
JavaScript at r (/webpack:/__lib.[name]/webpack/bootstrap:41:1)
JavaScript at Array.apply (/webpack:/__lib.[name]/webpack/bootstrap:23:1)
JavaScript at Array.Object (/webpack:/__lib.[name]/webpack/bootstrap:18:1)
JavaScript at Array.Object (/webpack:/__lib.[name]/webpack/bootstrap:18:1)
JavaScript at Array.Object (/webpack:/__lib.[name]/webpack/bootstrap:18:1)
JavaScript at Array.Object (/webpack:/__lib.[name]/webpack/bootstrap:18:1)
JavaScript at Array.Object (/webpack:/__lib.[name]/webpack/bootstrap:18:1)
JavaScript at Array.Object (/webpack:/__lib.[name]/webpack/bootstrap:18:1)
```

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo

**Comment by evilebottnawi** [comment]
@Borming https://github.com/webpack/webpack/issues/9394#issuecomment-510186922
