### ISSUE TITLE
where is apply-loader to use with jade-loader

### ISSUE THREAD

**Issue by lovedota** [webpack/webpack#940]
@sokra 
I saw in the document, we have http://webpack.github.io/docs/how-to-write-a-loader.html
```
    jade-loader: Convert template to a module that exports a function.
    apply-loader: Takes a function exporting module and returns raw result by applying query parameters.
    html-loader: Takes HTML and exports a string exporting module.
```
I want to use apply-loader to return a string result from jade-loader function. How can I  do it ? Thanks !

**Comment by sokra** [comment]
It is just an example. But feel free to implement an apply-loader.

**Comment by lovedota** [comment]
@sokra 
One more questions, is there anyone to write a custom loader inside our project without using package.json.
example:
- Structure
```
   webpack.config.js
   apply-loader.js
```
- apply-loader.js
``` js
module.exports = function(source) {
  this.cacheable && this.cacheable(true);
  var func = eval(source.trim()),
      html = func();
  return html;
};
```
- webpack.config
``` js
{test: /\.jade/, loader: "ng-cache?prefix=[dir]/[dir]!apply-loader!jade-loader"},
```
- What i mean is **apply-loader** must be an install by npm install --save-dev apply-loader for working like that, what i want is how to manually config inside current project to tell **webpack**. Ex:
'apply-loader': './apply-loader.js'.
Thanks !

**Comment by mogelbrod** [comment]
I implemented a basic apply-loader, see [this gist](https://gist.github.com/mogelbrod/20e65bf18c710e6b808a).

**Comment by lovedota** [comment]
@mogelbrod 
Thanks It works. !!!!

**Comment by Kreozot** [comment]
@mogelbrod Don't you want to release it as npm package and add to official list of loaders?

**Comment by mogelbrod** [comment]
Thanks for the feedback @Kreozot! I published the package on npm as per your request:
https://www.npmjs.com/package/apply-loader
I'll see if I can get it added to list of loaders.

**Comment by Kreozot** [comment]
:+1:
