### ISSUE TITLE
alias options definition bug

### ISSUE THREAD

**Issue by vankop** [webpack/webpack#9404]
# Bug report

**What is the current behavior?**

Current alias options defined as
```
alias?:
		| {
				/**
				 * New request
				 */
				[k: string]: string | string[] | false;
		  }
		| {
				/**
				 * New request
				 */
				alias?: string | string[] | false;
				/**
				 * Request to be redirected
				 */
				name?: string;
				/**
				 * Redirect only exact matching request
				 */
				onlyModule?: boolean;
		  }[];
```

However, when array provided all fields are required

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/vankop/webpack-resolve-option-bug

`npm run build` - correct config
`npm run build:broken` - broken config

**What is the expected behavior?**

Expect to require all fields `alias`, `name`, `onlyModule`.

https://github.com/webpack/webpack/blob/next/schemas/WebpackOptions.json#L1250

Need to add `"required": ["alias", "name", "onlyModule"]`

**Other relevant information:**
webpack version:  5
Node.js version:  11.13.0
Operating System: OSX

**Comment by sokra** [comment]
send a PR

`"required": ["alias", "name"`

**Comment by evilebottnawi** [comment]
Fixed https://github.com/webpack/webpack/pull/9405
