### ISSUE TITLE
npm audit fails after installing latest webpack 4.35.3

### ISSUE THREAD

**Issue by abhisekpaul** [webpack/webpack#9406]
# Bug report

**What is the current behavior?**
npm audit fails after installing latest webpack 4.35.3

**If the current behavior is a bug, please provide the steps to reproduce.**
do an npm install webpack -D and then do npm audit.

**What is the expected behavior?**
0 security vulnerabilities

**Other relevant information:**
webpack version:  4.35.3
Node.js version: 10
Operating System: MAC
Additional tools:

**Comment by evilebottnawi** [comment]
Not related to webpack directly, please open issue in affected repos

**Comment by jpickwell** [comment]
@evilebottnawi, on the contrary, there are two packages (`micromatch` and `watchpack`) that webpack depends on that could be updated to resolve the issue.

**Comment by lawlietee** [comment]
btw webpack-cli and webpack-dev-server also having similar issues, 
now if you install webpack , webpack-cli, and webpack-dev-server, it would say "found 111 high severity vulnerabilities in 11358 scanned packages"
it seems that some packages webpack depends on have just released a new version of fixing some vulnerabilities.

**Comment by jpickwell** [comment]
@lawlietee, `webpack-cli` depends on `findup-sync` which still needs to be updated to support `micromatch@>=4.0.0`. For `webpack-dev-server` the following dependencies would need to be updated `chokidar` and `http-proxy-middleware`.

**Comment by evilebottnawi** [comment]
`http-proxy-middleware` already is latest, chokidar we can't update due 3 version require minimum node@8 we need open issue about backport fix in 2 version, about webpack-cli let's open issue in their repo

**Comment by jpickwell** [comment]
Sometimes I wish things moved faster, even though Node 6.x has only been EoL for about 2.5 months. 😜

**Comment by evilebottnawi** [comment]
We are working on this, but it is not easy due transitive dependencies and incompatibility them

**Comment by evilebottnawi** [comment]
Should be fixed, problem was on npm side (invalid affected range), just want to ensure all users have not problem, please give feedback

**Comment by KidPluto** [comment]
> Should be fixed
How do I get the fix.

**Comment by whanwells** [comment]
No more problems here.

**Comment by evilebottnawi** [comment]
Fixed, feel free to feedback
