### ISSUE TITLE
Configure how Webpack resolves loader modules or pass loader instance directly

### ISSUE THREAD

**Issue by slavafomin** [webpack/webpack#9409]
Hello!

We're developing a universal tool, which could be used to compile multiple similar packages using Webpack. Therefore all build dependencies and Webpack configuration is present only in the tool package itself and not in the final packages.

With such approach we can only add a single dependency for our tool in the final package and use the tool to compile it. If we need to re-configure the compilation, we could do it in a single place, this is very convenient for us because we have hundred of such packages and we don't want to duplicate the build configuration for each of them.

This works pretty fine with `npm`, because `npm` puts all dependencies including transitive ones in the `node_modules` directory of the package in question (so called "flat" node modules). So, if we install our tool, which itself depends on, say `babel-loader`, both dependencies will be added to the `node_modules` directory of the final package and Webpack will be able to find it when it gets executed.

However, when we switched to `Rush` and `pnpm`, we stumbled upon a problem. These tools behave more clever that `npm`. They install dependencies using an intricate system of symlinks and they make sure to only add dependencies which are directly requested by the package in question. This helps to solve problems with [phantom dependencies](https://rushjs.io/pages/advanced/phantom_deps/) and [NPM doppelgangers](https://rushjs.io/pages/advanced/npm_doppelgangers/), which is a really good thing.

But, such approach doesn't work in our case, because Webpack is trying to resolve module loaders like `babel-loader` not from the tool directory (where they are actually installed), but from the build directory (directory of the final package). I've tried to debug the module resolution, but it looks like Webpack is not using the default Node.js one.

We've got similar situation with Rollup, but we've just managed to load required modules ourselves and pass the instances to the Rollup. But it looks like Webpack insists on resolving loaders on it's own. Please correct me if I'm wrong.

So the question is:

1). Is there a way to tell Webpack where to search for loader packages?
2). Is there a way to require loader ourselves and pass the instance to the Webpack directly (prevent Webpack from loading the loaders on it's own).

Could you share your thoughts on this problem? Any feedback will be highly appreciated. Thank you.

**Comment by evilebottnawi** [comment]
> Is there a way to tell Webpack where to search for loader packages

yes, using plugin https://webpack.js.org/configuration/resolve/#resolveplugins

>  Is there a way to require loader ourselves and pass the instance to the Webpack directly (prevent Webpack from loading the loaders on it's own).

require.resolve

Anyway webpack@5 supports pnp (plug and play of yarn) out of box, maybe pnpm has some logic, anyway, can you create minimum reproducible test repo with example(s) to investigate how it can be solved, thanks
