### ISSUE TITLE
Provide a way to create a non-JS site

### ISSUE THREAD

**Issue by haf** [webpack/webpack#941]
Provide a way to configure webpack, possibly with 'manual overrides' beyond the 'extract css' (which extracts *all CSS*, which I don't want); which lets you handle other static assets; images, fonts, vector graphics, other html pages (can they be entry points themselves?).

This feature would be a great fallback when the dependencies inevitably fail, like JS projects do, like node-sass or csso. By having a feature like this, I could instruct webpack to simply ignore the failed asset, or I could provide the dependency analysis myself, through the configuration file.

I'll open this issue as a way to track such an implementation, because it's a very real pain-point for users.

**Comment by sokra** [comment]
It's not really clear to me what's your use case...

> which extracts all CSS, which I don't want

It only extract CSS which has the extract-text-plugin loader applied. You can provide an alternative `test`.

**Comment by haf** [comment]
The feature requested is to expand webpack from being just a compiler with entry points to being able to create sites that are not all JS. Currently the project is centered around these entry points and everything goes from there, but sometimes you bump into bugs which fail the compilation. Having the option to explicitly specify what file gets put where in the final output folder would make it possible to move forward.

If I were you I'd say: we are more interested in removing the bugs from the project than making infrastructure for workaround, even if those workarounds can be used as features in their own right and for other purposes than workarounds.

As such, closing.
