### ISSUE TITLE
resolve.alias not working in ssr

### ISSUE THREAD

**Issue by ycjcl868** [webpack/webpack#9410]
There's a problem for me to do SSR building, I config the `resolve.alias = { 'bar/sdk/react': dirname(join(process.cwd(), 'node_modules', 'react')) }` both in client and server webpackConfig.

```js
import React from 'bar/lib/sdk/react';
    
// not use
import React from 'react';

// bar/lib/sdk/react/index.d.ts not have index.js
// the `bar` is alias `lib/sdk/react` with `bar/node_modules/react`
```

I write in the project like

```js
import React from 'bar/sdk/react';
```

output in server dist bundle is 'bar/sdk/react' not use alias '/node_modules/_react@16.8.6@react'

so run in server, it's crash.

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by sayjeyhi** [comment]
I have this problem too

**Comment by evilebottnawi** [comment]
@sayjeyhi Please create reproducible test repo

**Comment by sayjeyhi** [comment]
@evilebottnawi unfortunately it is a private project and I could not share code.
but I have alias config in my `webpack` config like this: 
```javascript
  resolve: {
    modules: ['node_modules', 'app'],
    extensions: ['.js', '.jsx', '.react.js'],
    mainFields: ['browser', 'jsnext:main', 'main'],
    alias: {
      ducks: path.resolve(process.cwd(), 'app/ducks'),
      components: path.resolve(process.cwd(), 'app/components'),
      constants: path.resolve(process.cwd(), 'app/constants'),
      resources: path.resolve(process.cwd(), 'app/resources'),
    },
  },
```
this config let me import files like: `constants/Helpers/Helper.js` this import will work on csr but in
my express based SSR and I got could not resolve error :
```
Error: Cannot find module 'constants/Helpers/Helper.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/macbook/Desktop/snapp/new-website/app/ducks/basket/actions.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (/Users/macbook/Desktop/snapp/new-website/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (/Users/macbook/Desktop/snapp/new-website/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

I thouht maybe it is `webpackDevMiddleware` bug cuz it not happen in prodcution build but when I console the result of middleware it has my webpack resolve config : 
```javascript
const webpackMiddleware = webpackDevMiddleware(compiler, {
  hot: true,
  publicPath: config.output.publicPath,
  progress: true,
  stats: {
    colors: true,
    assets: true,
    chunks: false,
    modules: false,
    hash: false,
  },

});

console.log('..........', webpackMiddleware.context.compiler.options.resolve.alias);

server.use(
  webpackMiddleware
);
```

**Comment by srigar** [comment]
+1 Same issue

**Comment by davic64** [comment]
I can resolve the problem with babel-plugin-webpack-alias

[Here the solution](https://stackoverflow.com/questions/34683682/webpack-aliases-in-node-js-server-code)
