### ISSUE TITLE
jsdoc linting

### ISSUE THREAD

**Issue by vankop** [webpack/webpack#9416]
## Feature request

**What is the expected behavior?**

Currently there are `valid-jsdoc` rule and `eslint-plugin-jsdoc` that validate jsdoc. 

**What is motivation or use case for adding/changing the behavior?**

In this case could be some contradictions, for instance:

```
"valid-jsdoc": [
 "error",
 {
  prefer: {
   class: "DONTUSE"
 }
],
"jsdoc/check-tag-names": "error"
```

```
/** @constructor */ 
function A {}
```
`jsdoc/check-tag-names` error  👆 (`@class` preferable by default )

```
/** @class */ 
function A {}
```
`valid-jsdoc` error  👆

So motivation is to prevent such behaviour

**How should this be implemented in your opinion?**

Use `eslint-plugin-jsdoc`, since it implement more options

**Are you willing to work on this yourself?**
yes

**Comment by sokra** [comment]
Send a PR
