### ISSUE TITLE
Change url for Superagent based on build

### ISSUE THREAD

**Issue by akatreyt** [webpack/webpack#942]
I have a react app and for development I have Superagent hitting 127.0.0.1, but once I push this to production I'll need to change this to the dns name. Question is how can I include separate files, one for dev and one for build, that Superagent can read from and use the value as the url? This might bleed over into needing some help on Superagent but from a webpack perspective how would I include a file and have it read for other components to use?

**Comment by sokra** [comment]
[contributing guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md)

> Please post a question to [StackOverflow with the webpack tag](http://stackoverflow.com/tags/webpack). Questions that include your webpack.config.js and relevant files are more likely to receive responses.
