### ISSUE TITLE
error Couldn't find any versions for "webpack" that matches "^4.36.0"

### ISSUE THREAD

**Issue by limonte** [webpack/webpack#9423]
![image](https://user-images.githubusercontent.com/6059356/61374898-36dcfa80-a8a6-11e9-905f-fabf88224634.png)

Projects based on webpack are failing, example: https://travis-ci.org/sweetalert2/sweetalert2.github.io/builds/559920361

![image](https://user-images.githubusercontent.com/6059356/61374982-67249900-a8a6-11e9-9cde-f3d8b35ec26c.png)

**Comment by limonte** [comment]
Something is wrong with `v4.36.0`:

![image](https://user-images.githubusercontent.com/6059356/61375145-d00c1100-a8a6-11e9-8d0e-44e30542b263.png)

**Comment by evilebottnawi** [comment]
Looks something wrong with npm register https://www.npmjs.com/package/webpack/v/4.36.0 (versionb exists)

**Comment by RinSer** [comment]
My deploy was crashing as well until I've changed version to "<4.36.0". This version as I can see has been added just today, someone should check its availability.

**Comment by limonte** [comment]
All good now, I also think the issue was on npm register side. [GitHub registry](https://github.com/features/package-registry) will hopefully improve things for us.

**Comment by limonte** [comment]
Agrh, now the same issue with `v4.36.1`

`npm` :hankey:

**Comment by limonte** [comment]
Reported to `npm`'s issue tracker: https://npm.community/t/no-matching-version-found-for-webpack-4-36-1/8911

**Comment by limonte** [comment]
From https://npm.community/t/no-matching-version-found-for-webpack-4-36-1/8911

> We’ve been having some issues with the CDN cache not getting purged reliably. They’re looking into it, and we’re tracking the issue. It’s tricky to detect from our end, because everything looks good, the website gets updated, etc., but the availability on the registry itself hangs until their cache expires. That can take anywhere from a few minutes to an hour, depending on a lot of things outside of our direct control.
> 
> Our apologies for the inconvenience, I know it’s annoying. I’m talking with our SRE team to see what we can do to get more visibility into the issue.

So it is the npm register issue indeed.
