### ISSUE TITLE
the second parameter of `cleverMerge` could be undefined

### ISSUE THREAD

**Issue by 1234567vgt** [webpack/webpack#9424]
**Do you want to request a *feature* or report a *bug*?**
bug， the second parameter of `cleverMerge` could be undefined

![image](https://user-images.githubusercontent.com/21257524/61377469-dd8cbf80-a8d5-11e9-9587-c73f69db7c72.png)

**What is the current behavior?**

In [https://github.com/amireh/happypack/blob/master/lib/WebpackUtils.js#L137](https://github.com/amireh/happypack/blob/master/lib/WebpackUtils.js#L137)， `resolverFactory.get("loader")`  miss the second parameter，and then cause the problem above

![image](https://user-images.githubusercontent.com/21257524/61377795-84715b80-a8d6-11e9-9875-6a5276e7f5d0.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

**Comment by evilebottnawi** [comment]
How we can reproduce bug?

**Comment by neoimale** [comment]
same problem here.

**Comment by sokra** [comment]
The second argument is actual required. Unsure why it's omitted here by happypack. Anyway fix is on the way...

**Comment by BH-M87** [comment]
Met same problem.

**Comment by BH-M87** [comment]
Met same problem.

**Comment by ffjanhoeck** [comment]
Same problem

**Comment by sokra** [comment]
releases as 4.36.1

**Comment by phaistonian** [comment]
@sokra: Speaking of Happypack, this happens as of >= 4.36.0

```
Module build failed (from ./node_modules/happypack/loader.js):

TypeError: helpers(...).ensure is not a function
```

Downgrading to 4.35.3 fixes it.
