### ISSUE TITLE
Doesn't respect exclude: /node_modules/ when a module is linked

### ISSUE THREAD

**Issue by natew** [webpack/webpack#943]
I noticed this on 1.7.3, if I have a module linked via `npm link` it will still run loaders that have `exclude: /node_modules/`. If they aren't linked, it works as expected.

**Comment by natew** [comment]
I believe because webpack is now recognizing the files by their linked path, rather than the node_modules symlink. This is on mac btw.

**Comment by ooflorent** [comment]
Ran into the same issue. Is there any workaround?

**Comment by magsout** [comment]
I have exactly the same issue..

**Comment by Nyalab** [comment]
same issue here, it is very annoying, please do something :cry:

**Comment by sokra** [comment]
It's not a bug.

http://webpack.github.io/docs/configuration.html#module-loaders

Try to use `include` instead of `exclude`.

**Comment by ooflorent** [comment]
When using `include` loaders are not applied (expected behavior) but dependencies are not deduplicated. Linked packages still don't appear as external:

```
...
[100] /Users/fc/Development/external-pkg/lib/index.js 730 bytes {0} [built] << KO
[101] ./web_modules/pages/main/index.js 2.61 kB {0} [built]                 << GOOD
...
[210] ./~/react-router/~/qs/index.js 36 bytes {0} [built]                   << GOOD
...
```

**Comment by ooflorent** [comment]
@sokra If I remove links and use direct npm packages, dependencies are dedup and everything works fine (using `include`). Currently webpack can't handle linked modules the same way of published modules which is an issue.

**Comment by sokra** [comment]
node.js behaves the same way.

modules are looked up relative to the requiring module.

There is a workaround: `resolve.root = path.join(__dirname, "node_modules")`.

**Comment by sokra** [comment]
But that's a separate issue.

**Comment by revolunet** [comment]
same here

**Comment by jonjaques** [comment]
FYI: The `resolve.root = path.join(__dirname, "node_modules")` workaround fixes the React parent/ref issue. 

Thanks @sokra!

**Comment by sberney** [comment]
This still doesn't work, and `resolve.root` is no longer supported. I'm using yarn workspaces, and it's taking hours to figure out how to make my loaders all apply to the right targets.

**Comment by adamchenwei** [comment]
similar problem, not able to tell linter ignore the linked npm_module, but if installed, its fine. that's dumb...

**Comment by PaulRBerg** [comment]
Also using yarn workspaces and still not working. Any updates?

**Comment by c708423** [comment]
same issue
