### ISSUE TITLE
ERROR in Entry module not found: Error: Can't resolve './src' in '/Users/marcoisaac/MyDevRepos/human-spiral-front'

### ISSUE THREAD

**Issue by isaacdeleon** [webpack/webpack#9437]
# Bug report

**What is the current behavior?**

when i run npm run build i got this error:

ERROR in Entry module not found: Error: Can't resolve './src' in '/Users/marcoisaac/MyDevRepos/human-spiral-front'

<img width="235" alt="Screen Shot 2019-07-18 at 10 10 17 AM" src="https://user-images.githubusercontent.com/4961023/61489721-ef6f7080-a970-11e9-8979-d620ddbe1144.png">

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  4
Node.js version: 
Operating System: mac
Additional tools:

`{
"name": "humanspiral-front",
"description": "Human Spiral Image Generator Front End",
"version": "1.0.0",
"author": "Isaac Laurrabaquio marcodeleonmx@gmail.com",
"license": "MIT",
"private": true,
"scripts": {
"dev": "cross-env NODE_ENV=development webpack-dev-server --open --hot",
"build": "cross-env NODE_ENV=production webpack --progress --hide-modules --mode production --display-error-details"
},
"dependencies": {
"axios": "^0.19.0",
"vue": "^2.5.11"
},
"browserslist": [
"> 1%",
"last 2 versions",
"not ie <= 8"
],
"devDependencies": {
"babel-core": "^6.26.0",
"babel-loader": "^7.1.2",
"babel-preset-env": "^1.6.0",
"babel-preset-stage-3": "^6.24.1",
"copy-webpack-plugin": "^4.0.3",
"cross-env": "^5.0.5",
"css-loader": "^0.28.7",
"file-loader": "^1.1.4",
"uglifyjs-webpack-plugin": "^2.1.3",
"vue-loader": "^14.2.2",
"vue-template-compiler": "^2.4.4",
"webpack": "^4",
"webpack-cli": "^3.3.6",
"webpack-dev-server": "^3"
}
}`

`var path = require('path')
var webpack = require('webpack')
const TerserPlugin = require('terser-webpack-plugin');

module.exports = {
mode: 'production',
entry: path.resolve(__dirname,'./src/main.js'),
output: {
path: path.resolve(__dirname, './dist'),
publicPath: '/dist/',
filename: 'build.js'
},
module: {
rules: [
{
test: /.css$/,
use: [
'vue-style-loader',
'css-loader'
],
}, {
test: /.vue$/,
loader: 'vue-loader',
options: {
loaders: {
}
// other vue-loader options go here
}
},
{
test: /.js$/,
loader: 'babel-loader',
exclude: /node_modules/
},
{
test: /.(png|jpg|gif|svg)$/,
loader: 'file-loader',
options: {
name: '[name].[ext]?[hash]'
}
}
]
},
resolve: {
alias: {
'vue$': 'vue/dist/vue.esm.js'
},
extensions: ['*', '.js', '.vue', '.json']
},
devServer: {
historyApiFallback: true,
noInfo: true,
overlay: true
},
performance: {
hints: false
},
devtool: '#eval-source-map'
}

if (process.env.NODE_ENV === 'production') {
module.exports.devtool = '#source-map'
// http://vue-loader.vuejs.org/en/workflow/production.html
module.exports.plugins = (module.exports.plugins || []).concat([
new webpack.DefinePlugin({
'process.env': {
NODE_ENV: '"production"'
}
}),
new webpack.LoaderOptionsPlugin({
minimize: true
})
])
module.exports = {
optimization: {
minimizer: [new TerserPlugin()],
minimize: true
},
}
}`

**Comment by evilebottnawi** [comment]
Please create normal reproducible test repo (github repo), without copy/pasting configuration(s), it is unreadable

**Comment by sokra** [comment]
`module.exports = ` is called multiple times.
