### ISSUE TITLE
webpack --watch starts watching files case-insensitively, but then ignores changes to them

### ISSUE THREAD

**Issue by jacek-dargiel** [webpack/webpack#944]
When a file requires a module file which has a different file name than the actual existing file and the name differs by just a letter case, then `webpack --watch` first finds and includes the file, but when I modify the `require`d files it ignores them.

Please have a look at this repository I've created to showcase this issue:
https://github.com/jacek-dargiel/webpack-case-sensitivity

The file `entry.js` has a `require('./Content.js')` call, but the actual file on the filesystem is `content.js` (notice the difference in the case of the first letter). 

I would expect Webpack to behave consistently, by either ignoring the file on the first build (and throwing an error), or to not ignore changes to the `require`d file even though it differs in letter case.

Windows 8.1
node.js 0.10.33
Webpack 1.7.3

**Comment by raduamarie** [comment]
Have the same issue on Mac OSX 10.10.3 :)

I agree on the fact that Webpack should either throw a error or watch the file not only at the first run.

**Comment by Morhaus** [comment]
I had the same problem for a while but couldn't figure out what was wrong until I found this issue. I made  a [plugin](https://gist.github.com/Morhaus/333579c2a5b4db644bd5) to force case sensitivity with webpack.

**Comment by sokra** [comment]
The master branch of watchpack watches case insensitive. Feel free to try it.

**Comment by Industrial** [comment]
@Morhaus: Looks interesting (as a npm module :D). Could you elaborate a bit on what it does exactly?

**Comment by Morhaus** [comment]
@Industrial Right before a file is imported, the plugin checks whether the case of the resolved resource corresponds to the case of the file it maps to (on disk).

Now that I think of it, it won't check the case of parent directories, so `require('Lib/file')` for `lib/file.js` might still produce this error.

**Comment by kandros** [comment]
still an issue, just lost 2 hour for capital i, is there a patch?

**Comment by Urthen** [comment]
@kandros I rewrote the plugin with some optimizations, including checking parent directories: https://github.com/Urthen/case-sensitive-paths-webpack-plugin

**Comment by bebraw** [comment]
Can you see this in webpack 2?
