### ISSUE TITLE
Inferred TS declaration imports in monorepo are changed to relative imports

### ISSUE THREAD

**Issue by LiamMartens** [webpack/webpack#9441]
# Bug report
For some reason when generating ts declaration files, using either `ts-loader` or `awesome-typescript-loader`, the imports to local packages in the monorepo are changed to relative imports. They should remain as module imports.

**What is the current behavior?**
When building both packages the inferred lerna package import in the declaration files of typescript in the `my-package` package are converted to a relative import.

**If the current behavior is a bug, please provide the steps to reproduce.**
Reproduction repository and steps can be found [here](https://github.com/LiamMartens/webpack-ts-loader-declaration-import/)

**What is the expected behavior?**
These imports that reference a lerna package and are not explicitly specified should not be changed to a relative import and instead should remain a module import.

**Other relevant information:**
webpack version:  4.36.1
Node.js version: v11.15.0
Operating System: PopOS! 18.10
Additional tools: yarn, lerna

**Comment by sokra** [comment]
Unsure how webpack is related to this

@johnnyreilly

**Comment by LiamMartens** [comment]
@sokra I am not 100% certain whether it is webpack or not, however it happens with both `ts-loader` and `awesome-typescript-loader` which led me to believe it has something to do with webpack's module resolving

**Comment by evilebottnawi** [comment]
Please open an issue `ts-loader` or `awesome-typescript-loader`, sorry for delay, not related to webpack

**Comment by johnnyreilly** [comment]
Possibly related to this https://github.com/TypeStrong/ts-loader/pull/822 - long time ago though so I forget
