### ISSUE TITLE
Webpack shows previous info and thus console.clear() doesn't has affect

### ISSUE THREAD

**Issue by Yegorich555** [webpack/webpack#9442]
**What is the current behavior?**
When I clear terminal in VScode (for example) and made build via webpack, webpack shows previous info.
Result: terminal (console) contains info from previous builds. It is checked on the several machines with Windows 10. In this case, https://github.com/geowarin/friendly-errors-webpack-plugin also doesn't work properly (it clears console, but webpack pasts previous info again)

**If the current behavior is a bug, please provide the steps to reproduce.**
1) Run build via webpack (any basic project or https://github.com/Yegorich555/FromScratch_React/tree/wepback-info-bug)
2) Clear terminal (via Ctrl+L in powershell or adding command console.clear() in webpack.common.js)
3) Run build again

**What is the expected behavior?**
Terminal (console) has to contain only info of the current build

**Other relevant information:**
webpack version:  4.35.3
Node.js version: 11.10.0
Operating System: Windows 10x64
Additional tools: VScode 1.36.1, PowerShell, cmd (windows)

**Comment by sokra** [comment]
You better file this issue in the VSCode repo.

**Comment by Yegorich555** [comment]
Yes. I've found that with PowerShell works fine, but in Terminal of VSCode we have such weird behavior.
The issue for VSCode is created: https://github.com/microsoft/vscode/issues/77734
