### ISSUE TITLE
Webpack not working with PUG (Jade)

### ISSUE THREAD

**Issue by nmaxcom** [webpack/webpack#9444]
I've asked on discord, gitter, IRC..., I've searched in SO, google, Github's random repos, webpack docs, articles... I just can't make this work. Something's wrong. And this seems to be something people have been having troubles with very little or 0 help.

# Bug report

**What is the current behavior?**

In this last iteration I'm trying to run my simple MVC Express+Pug with `"webpack-dev-server --config webpack.config.js --env.NODE_ENV=development --mode=development --progress --open --host localhost`.

Using HMR (all the steps to config webpackDevMiddleware and webpack-hot-middleware), the html-webpack-plugin, webpack-dev-server, I expect a quick development experience, being able to see on the browser my *.pug files show data sent down by the controller. The static content is shown, but not the dynamic content from Express. Also, browser should auto refresh on pug changes, but it stays quiet.

Because I'm not doing a SPA, and I think one has to spawn a new plugin object per *.pug page, I made a simple js util to collect all the pages so I can do this:

```
    new HtmlWebPackPlugin({
      filename: 'index.html',
      template: './src/views/pages/index.pug',
      inject: true,
    }), ...pugPages.pages(env),
```
I've tested and it works so that's a ton of repetitive code I don't need to write.

With that hack, I get to see the PUG pages. But they don't receive the data sent down by the Express controller. 
For example:

`index.js:`
```javascript
router.get('/', (req, res, next) => {
  res.render('index', { msg: 'index page' });
  next();
});
```

`index.pug:`:
```pug
extends ../layout

block head
  include ../partials/head

block content
  h1 You ware in #{msg}
  //h1= htmlWebpackPlugin.options.title
  //p Welcome to #{htmlWebpackPlugin.options.title}
  //script.
  //  console.log(!{JSON.stringify(htmlWebpackPlugin.options)})

```
Shows "You are in ->" instead of "You are in -> index page".
As you can tell I **was trying with htmlWebpackPlugin.options.title**. But if that's the only way this works, I can't get pug the data from Express. And Webpack is not auto-reloading the browser on change (changes in pug files or anywhere else). I have to manually refresh the browser.

Also, in the current step of trying different approaches with the documentation and other articles, I now get a browser error:

![image](https://user-images.githubusercontent.com/8936090/61583297-7752a780-ab36-11e9-8893-cff60b165a34.png)

This is yet a new error that just appeared right now. You can see in the repo's package.json I have all the @babel packages, and .babelrc with `@babel/preset-env` preset.

**If the current behavior is a bug, please provide the steps to reproduce.**

I made a leaner branch with everything in place to make it easier. Here it is: https://github.com/nmaxcom/Express-pug-webpack

**What is the expected behavior?**

According to Webpack's docs, it should run the app, bundling static assets (which it does) and opening a local connection to see the current state of the site (which it does too).
I was expecting a correct "watch" of files, which on modification would reload server if necessary (although with HMR it shouldn't be) and update the browser view without a manual refresh.

**Other relevant information:**
```
Node.js v10.16.0
darwin 16.7.0
npm 6.9.0
webpack 4.29.0
html-webpack-plugin 3.2.0
```

**Comment by sokra** [comment]
Running pug templates with the HtmlWebPackPlugin runs them at build time and this is unrelated to your server code. Expecting to see your `msg` here doesn't make sense... You should not use HtmlWebPackPlugin if you want to pass variables from server here.

**Comment by nmaxcom** [comment]
Makes sense. But if don't use HtmlWebPackPlugin, I can't use webpack-dev-server because it won't render the templates.

I'm just really trying to make it work. After countless articles, docs and repos using express+pug+webpack, running express with a templating engine and a swift dev environment, doesn't seem possible.

Is there something I missed?

**Comment by sokra** [comment]
> I can't use webpack-dev-server because it won't render the templates.

You can. Use it only to generate JS assets. Setup proxy to your express server at the webpack-dev-server.
