### ISSUE TITLE
Data uri import does not work

### ISSUE THREAD

**Issue by LarsDenBakker** [webpack/webpack#9445]
# Bug report

**What is the current behavior?**
Data uri import does not work

**If the current behavior is a bug, please provide the steps to reproduce.**
When using a data uri in an import statement, webpack throws an error saying it can't find the import. For example:

```javascript
import "data:text/javascript;charset=utf-8;base64,Y29uc29sZS5sb2coJ2lubGluZSAxJyk7";
```

Neither base 64 encoded, or unencoded data uris work.

I know this is a bit of a strange pattern, but it's valid to use this in the browser so I was hoping webpack would support this as well.

My use case is that I have tool which converts legacy module syntax to es modules, and data uris are a nice way to handle executing code in-between imports when you want to preserve the order of the code. For example this is valid in commonjs, but not in an es module:

```javascript
require('./foo.js');
console.log('hello world');
require('./bar.js');
```

**What is the expected behavior?**
I expect webpack to create a module in the module graph using the decoded data uri. The result is bundled with the rest of the code as if it were any regular module.

**Other relevant information:**
webpack version:  v4.36.1
Node.js version: v10
Operating System: mac
Additional tools: none

**Comment by evilebottnawi** [comment]
Interesting use case, i think we should handle this case, /cc @sokra

**Comment by LarsDenBakker** [comment]
:(

**Comment by evilebottnawi** [comment]
You can send a PR

**Comment by goganchic** [comment]
@LarsDenBakker would you please explain what is expected behavior if encoded data type is not `text/javascript`, e.g. `image/jpeg`?
