### ISSUE TITLE
TypeError: 'undefined' is not a function

### ISSUE THREAD

**Issue by poolerMF** [webpack/webpack#9446]
# Bug report

**What is the current behavior?**
webpack not working with  wkhtmltopdf
problem started in file runtime.js, on line 
```
var oldJsonpFunction = jsonpArray.push.bind(jsonpArray);
```
when I try to debug it:
```
jsonpArray = array 
jsonpArray.push = function
jsonpArray.push.bind = undefined
```

**If the current behavior is a bug, please provide the steps to reproduce.**
```
install wkhtmltopdf
/usr/local/bin/wkhtmltopdf --debug-javascript --enable-javascript https://symfony.com test.pdf
```

**What is the expected behavior?**
It should work

**Other relevant information:**
webpack version:  doesnt'matter
Node.js version:  doesnt'matter
Operating System:  ubuntu 18
Additional tools: wkhtmltopdf 0.12.2.1 (with patched qt)

**Comment by sokra** [comment]
webpack requires ES5 to work. Use a Function.prototype.bind polyfill.

**Comment by poolerMF** [comment]
i'm sorry, what ???
my page normaly works ... it do not work, when I want to make screenshot or PDF of page using webpack

THIS REPOSITORY IS WEBPACK
file JsonpMainTemplatePlugin.js is generating code  `var oldJsonpFunction = jsonpArray.push.bind(jsonpArray);` into file runtime.js

how should I override it ? how should I make Function.prototype.bind polyfill ??

**Comment by nugen** [comment]
Hi @poolerMF 
Did you solve your issue ? I'm under Symfony 5 with Webpack encore and get the same error : My page is working fine without any error, except when rendered with wkhtmltopdf tool.
And i have the same exact error same line in runtime.js.
Thanks !

**Comment by poolerMF** [comment]
> Hi @poolerMF
> Did you solve your issue ? I'm under Symfony 5 with Webpack encore and get the same error : My page is working fine without any error, except when rendered with wkhtmltopdf tool.
> And i have the same exact error same line in runtime.js.
> Thanks !

I looked into code and I think I solve it with:
**webpack.config.js:**
````
.copyFiles([{
        from: './assets/js',
        to: '[name].[ext]',
        pattern: /polyfill_bind\.js$/
    }}
````

**polyfill-bind.js:**
````
// Taken from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind
if (!Function.prototype.bind) {
    Function.prototype.bind = function (oThis) {
        if (typeof this !== "function") {
            // closest thing possible to the ECMAScript 5
            // internal IsCallable function
            throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");
        }

        var aArgs = Array.prototype.slice.call(arguments, 1),
            fToBind = this,
            fNOP = function () {},
            fBound = function () {
                return fToBind.apply(this instanceof fNOP && oThis
                    ? this
                    : oThis,
                    aArgs.concat(Array.prototype.slice.call(arguments)));
            };

        fNOP.prototype = this.prototype;
        fBound.prototype = new fNOP();

        return fBound;
    };
}
````

but I switched to "nightmare", because phantomjs and wktohtml are not supporting flex box

**Comment by nugen** [comment]
> > Hi @poolerMF
> > Did you solve your issue ? I'm under Symfony 5 with Webpack encore and get the same error : My page is working fine without any error, except when rendered with wkhtmltopdf tool.
> > And i have the same exact error same line in runtime.js.
> > Thanks !
> 
> I looked into code and I think I solve it with:
> **webpack.config.js:**
> 
> ```
> .copyFiles([{
>         from: './assets/js',
>         to: '[name].[ext]',
>         pattern: /polyfill_bind\.js$/
>     }}
> ```
> 
> **polyfill-bind.js:**
> 
> ```
> // Taken from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind
> if (!Function.prototype.bind) {
>     Function.prototype.bind = function (oThis) {
>         if (typeof this !== "function") {
>             // closest thing possible to the ECMAScript 5
>             // internal IsCallable function
>             throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");
>         }
> 
>         var aArgs = Array.prototype.slice.call(arguments, 1),
>             fToBind = this,
>             fNOP = function () {},
>             fBound = function () {
>                 return fToBind.apply(this instanceof fNOP && oThis
>                     ? this
>                     : oThis,
>                     aArgs.concat(Array.prototype.slice.call(arguments)));
>             };
> 
>         fNOP.prototype = this.prototype;
>         fBound.prototype = new fNOP();
> 
>         return fBound;
>     };
> }
> ```
> 
> but I switched to "nightmare", because phantomjs and wktohtml are not supporting flex box

@poolerMF 
Thank your so much for your answer, i really appreciate, it solves the issue indeed !
Yes, we already had the problem when we switched to flexbox... We have a separate css to ovverride the flex box behaviour, and it is always a nightmare when adding new pages to be printed.
