### ISSUE TITLE
Need docs for plugin error handling

### ISSUE THREAD

**Issue by jasonkuhrt** [webpack/webpack#945]
I am trying to write a plugin for Webpack but unable to find documentation regarding how its error handling is supposed to work. For example if my plugin has a compile error on some file type I presumably should catch it and give it to webpack to present to the user. I cannot find guides or docs about this.

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#101

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#130
