### ISSUE TITLE
harmony-module overrides require.main

### ISSUE THREAD

**Issue by rytakahashi** [webpack/webpack#9453]
# Bug report

**What is the current behavior?**

When Webpack builds with `harmony-module.js`, [require.main === module](https://nodejs.org/api/modules.html#modules_accessing_the_main_module) check fails.

**If the current behavior is a bug, please provide the steps to reproduce.**

index.js

```
import util from 'util'; // to trigger harmony-module.js

if (require.main === module) {
  console.log('yay!');
}
```

webpack.config.js

```
export default {
  mode: 'development',
  entry: {
    index: `${__dirname}/src/index.js`,
  },
};
```

**What is the expected behavior?**

Node's documented test for whether or not the main module is accessed (`require.main === module`) should still hold.

**Other relevant information:**
webpack version:  4.36.1
Node.js version: v10.15.0
Operating System: macOS 10.14
Additional tools: @babel/core, @babel/preset-env, @babel/register, webpack-cli

**Comment by sokra** [comment]
I tried to fix it but this causes other problems.

Technically you are missing CommonJS constructs (`require.main`) with ESM constructs (CommonJS interop `module` in ESM) so I can live with this being a "won't fix"...

**Comment by rytakahashi** [comment]
I'd be ok with a "won't fix", but is there an alternative way to make this check with this setup?

A use case is running tests on the entry point without running the program itself.

**Comment by sokra** [comment]
I won't recommend mixing library and executable in a single file. Use different entries for different use cases.

**Comment by rytakahashi** [comment]
Ok, thanks for feedback, closing issue.
