### ISSUE TITLE
Error when using a function as a loader

### ISSUE THREAD

**Issue by ericmorand** [webpack/webpack#9464]
When I pass a function as loader, I get the following error message when bundling:

> WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema. - configuration.module.rules[0].use should be one of these: non-empty string | function | object { ident?, loader?, options?, query? } | function | [non-empty string | function | object { ident?, loader?, options?, query? }] -> Modifiers applied to the module when rule is matched Details: * configuration.module.rules[0].use[0].loader should be a string. * configuration.module.rules[0].use[0].loader should be one of these: non-empty string -> Loader name

Here is a snippet of my config:

```js
module: {
                rules: [
                    {
                        test: /\.foo$/,
                        use: [
                            {
                                loader: (source) => {
                                },
                                options: {}
                            }
                        ]
                    }
                ]
            }
```

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by ericmorand** [comment]
> Loader can't be Function

As you can see, you didn't need the issue template.
