### ISSUE TITLE
How to stop bundling when errors was occurred

### ISSUE THREAD

**Issue by hoangnkvti** [webpack/webpack#9465]
# Bug report

**What is the current behavior?**
I use webpack 4 to bundle VueJS code, but in `dev` mode, output is created although there is an error when bundling.
When I use `npm run prod`, output file is not created. So how do I can stop bundling in dev mode when error is occurred??

I added `--bail` option and installed `webpack-fail-plugin` but nothing can help me :(

**Other relevant information:**
webpack version:  4.0.0
Operating System: MacOS

**Comment by evilebottnawi** [comment]
We don't know what `npm run prod` mean

**Comment by hoangnkvti** [comment]
I don’t know exactly what config to do that. I read but i don’t know exaxtly. Please give me a hint, i will try my best to understand it

**Comment by evilebottnawi** [comment]
@hoangnkvti look in `package.json`

**Comment by hoangnkvti** [comment]
Thank you... i fixed my issue
Sorry about my hard to understand question.
