### ISSUE TITLE
web: inefficient shims for nextTick & setImmediate

### ISSUE THREAD

**Issue by ronag** [webpack/webpack#947]
The current shim webpack uses for nextTick and setImmediate uses `setTimeout(task, 0)` but there are better alternatives. See https://github.com/calvinmetcalf/immediate.

**Comment by svnlto** [comment]
:+1:

**Comment by STRML** [comment]
Just an FYI, this is something for https://github.com/defunctzombie/node-process, not here.

**Comment by nolanlawson** [comment]
`immediate` is not a shim for `nextTick`; it uses microtasks whereas `setTimeout` creates a macrotask. The closest thing to `nextTick` is https://github.com/defunctzombie/node-process which is indeed (correctly) based on `setTimeout`.

**Comment by STRML** [comment]
What I meant is, the bug is in `node-process` (webpack simply uses it), not in webpack itself. And `node-process` uses `setTimeout` for *both* `process.nextTick()` and for `setImmediate()`, but `setImmediate()` should have a microtask shim instead.

**Comment by nolanlawson** [comment]
Yes this issue should be closed because it doesn't apply to Webpack. Also FWIW I think the current node-process implementation is fine. It's the closest thing to the semantics of nextTick.

**Comment by STRML** [comment]
Hang on; no, this is backwards.

* `setImmediate` should use the macrotask queue, which it does via the [setimmediate shim](https://www.npmjs.com/package/setimmediate), which is imported by `timers-browserify`, which webpack correctly uses. Note that this is still faster than `setTimeout(func, 0)`. The OP was incorrect in saying that webpack uses `setTimeout` for `setImmediate` shimming; the current behavior is correct.
* `process.nextTick` should use the *microtask* queue, (note this changed in Node 0.9 from macro -> micro), and is incorrectly shimmed by `node-process` to use `setTimeout`, when it should use something like [next-tick](https://github.com/medikoo/next-tick) which uses `MutationObserver` when available. This is the bug.

**Comment by streamich** [comment]
For whoever is interested, I made a lib for queueing micro- and macro-tasks: [`entask`](https://github.com/streamich/entask).
