### ISSUE TITLE
CommonJS modules with "sideEffects": false still removes styles for single-file vue components in production builds

### ISSUE THREAD

**Issue by zengkan0703** [webpack/webpack#9471]
# Bug report

**What is the current behavior?**
I have a vue project with single-file vue components, I use babel  transform my ES2015 module syntax into CommonJS modules (for some reason), but i can`t find my styles from single-file vue component. Here are some config.
babelrc:
```javascript
"presets": [
    [
      "@babel/preset-env",
      {
        "modules": "commonjs"
      }
    ],
  ],
```
package.json:
```javascript
...
"sideEffects": false,
...
```
**If the current behavior is a bug, please provide the steps to reproduce.**
[Here is the demo](https://github.com/zengkan0703/webpack-sideEffects-bug)
change package.json to 
```javascript
"sideEffects": [
    "*.vue"
  ]
```
you can find component style from dist/main.[hash].css,
with package.json default, there is no component style in dist/main.[hash].css

**What is the expected behavior?**
I think that means the tree-shaking is working, but check the babel.rc, I transform my ES2015 module syntax into CommonJS modules.

[The documentation about tree-shaking](https://webpack.js.org/guides/tree-shaking/#conclusion) indicates if we use some compilers transform ES2015 module syntax into CommonJS modules, we can`t use tree-shaking.

According to the documentation, there should be my component style there  no matter with or without "sideEffects".

**Other relevant information:**
webpack version:  ^4.36.1
Node.js version: 10.16.0
Operating System: macOS 10.13.6 (17G65)
Additional tools:

**Comment by sokra** [comment]
by your configration your babel config only affects `.js` files, not `.vue` files and it's generates source code.

**Comment by zengkan0703** [comment]
@sokra Thanks for your replay.

According to [the documentation of vue-loader](https://vue-loader.vuejs.org/guide/#manual-setup), after I create a instance of VueLoaderPlugin, 

>  if you have a rule matching /\.js$/, it will be applied to <script> blocks in .vue files.

So I think my babel configration affects the ```.vue``` files too.

Here are my understanding of the whole thing: babel transform all js into CommonJS modules, including the ```.vue``` files , so tree-shaking should not work.

Am I misunderstanding the tree-shaking`s necessary conditions or babel configration？

Thank you again, have a nice day.

**Comment by zengkan0703** [comment]
@sokra Hello, you must be very busy.
I will be very grateful if you can point out my problem when you are free. Feel free if not 😊.

**Comment by sokra** [comment]
> if you have a rule matching /.js$/, it will be applied to <script> blocks in .vue files.

But it won't be applied to the generated code of the `.vue` file, only to the `<script>` portion.
