### ISSUE TITLE
webpack --watch; dynamic import chunks randomly switching from named to ID

### ISSUE THREAD

**Issue by SampsonCrowley** [webpack/webpack#9473]
# Bug report

**What is the current behavior?**

If I use named chunks with dynamic imports, webpack randomly errors out and switches between to trying to load chunks using the correct names, and the `chunkId` after the first save in development

this chunk is fetched perfectly fine from the server; both on first load (when it's properly executed), and after the save that makes it not found
```
client.js:176 ChunkLoadError: Loading chunk page-calendar failed.
(missing: https://lvh.me:4000/js/page-calendar.esm.js)
    at Function.requireEnsure [as e] (https://lvh.me:4000/js/shared-runtime.esm.js:127:26)
    at HTMLElement._loadPage (https://lvh.me:4000/js/app.esm.js:1322:121)
    at Array.<anonymous> (https://lvh.me:4000/js/app.esm.js:1264:12)
    at Function._broadcast (https://lvh.me:4000/js/app.esm.js:1107:31)
    at HTMLBodyElement.<anonymous> (https://lvh.me:4000/js/app.esm.js:1096:12) "test"
```

calling code:

```
  _loadPage(page) {
    let found = false;
    switch(page) {
      case 'home':
        import(
          /* webpackChunkName: "page-home" */
          'pages/home'
        ).then(() => {
          this._setMain('home')
        })
        break;
      case 'calendar':
        import(
          /* webpackChunkName: "page-calendar" */
          'pages/calendar'
        ).then(() => {
          this._setMain('calendar')
        })
        break;
      case 'counter':
        import(
          /* webpackChunkName: "page-counter" */
          'pages/counter'
        ).then(() => {
          this._setMain('counter')
        })
        break;
      default:
        import(
          /* webpackChunkName: "page-four-oh-four" */
          'pages/four-oh-four'
        ).then(() => {
          this._setMain('four-oh-four')
        })
    }

    this._page = page;
  }
```

Returned Chunk Header after first load, before any changes, for chunk `page-calendar`:
```
(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["page-calendar"],{
```

Returned Chunk Header after first save that modifies chunk `page-calendar`:
```
(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[5],{
```

webpack output config (yes, I have tried removing the global chunkFilename option):
```
output: {
  filename: '[name].esm.js',
  path: path.resolve(__dirname, '../priv/static/js'),
  publicPath: '/js/',
  chunkFilename: '[name].esm.js'
},
```

**If the current behavior is a bug, please provide the steps to reproduce.**

add magic comment for chunk name, save changes to file in imported bundle

I will create a fork of the private repo when I can

**What is the expected behavior?**

a named chunk stays named after saving in --watch mode, it should never revert switch between id schemes from a file change

**Other relevant information:**
webpack version:  4.35.2
Node.js version: 11.15.0
Operating System: Arch Linux x64 (cpu: i7, gpu: AMD Radeon rx 460)
Additional tools: Babel v7.4.5

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by SampsonCrowley** [comment]
@sokra will do
