### ISSUE TITLE
callAnyMember hook does not work

### ISSUE THREAD

**Issue by mstarets** [webpack/webpack#9480]
I am trying to get the .callAnyMember parser hook invoked for code similar to the following:
function test (foo, require) {
  const t = foo.bar(require); // I need to replace the foo.bar() call with a dynamic import

  return t;
}

The hook is being added in my plugin as follows:
parser.hooks.callAnyMember.for('foo').tap('MyPlugin', expression => {
                    debugger;
                });
It never gets invoked. It seems that the code in walkCallExpression() checks whether the callee is an identifier. However, the whole point of the callAnyMember hook it is to work with MemberExpression callees, is it not?

                        if (callee.isIdentifier()) {
				const callHook = this.hooks.call.get(callee.identifier);
				if (callHook !== undefined) {
					let result = callHook.call(expression);
					if (result === true) return;
				}
				let identifier = callee.identifier.replace(/\.[^.]+$/, "");
				if (identifier !== callee.identifier) {
					const callAnyHook = this.hooks.callAnyMember.get(identifier);
					if (callAnyHook !== undefined) {
						let result = callAnyHook.call(expression);
						if (result === true) return;
					}
				}
			}

**What is the current behavior?**
The hook never gets invoked

**If the current behavior is a bug, please provide the steps to reproduce.**
see above

**What is the expected behavior?**

The hook should be invoked CallExpressions with callee being a MemberExpression

**Other relevant information:**
webpack version:  4.36.1
Node.js version: 8.11.2
Operating System: MacOS
Additional tools:

**Comment by sokra** [comment]
The Parser invokes it's hooks only for "free variables". `foo` is declared via function parameters.

**Comment by mstarets** [comment]
Thanks. In my case, 'foo' gets passed in as a module parameter, so it definitely is in scope, and not what Webpack would call a 'free' variable. The doc does not say anything about the hook being limited to free variable though.

Would it make sense to file an feature request for extending support to all MemberExpression callees?

**Comment by sokra** [comment]
Can you tell me more about your use case? Why do you want to do that?

**Comment by mstarets** [comment]
Hey Sokra,
We have a client-side framework that was originally written to rely on requireJS. We now have some customers that are still using requireJS and r.js while others have switched to Webpack. To support the latter group, we have written a plugin for Webpack that deals with requireJS compatibility issues (mostly around the area around dynamic require() calls when the context cannot be established by Webpack automatically). More details about one such issue are below:

We have a class that exposes .getRequirePromise() method. The method takes the name of the module and the instance of require function as parameters. The call to the method would typically look like this (this is a simplified version):

define(['requireutils', 'require'], (RequireUtils, localRequire) => {
...
const promise = RequireUtils.getRequirePromise('somelocalmodule', localRequire);
promise.then(...;

});
During the webpack build, our plugin is replacing the entire RequireUtils.getRequirePromise() call with code that Webpack's dynamic import would have generated. We do so by replacing the entire call with ImportDependenciesBlock that is constructed with the name of the module passed into .getRequirePromise():
const depBlock = new ImportDependenciesBlock(
    module.string,
    [start, end - 1],
    {},
    parser.state.module,
    expr.loc,
    parser.state.module
  )
  parser.state.current.addBlock(depBlock);
We need to run the patching code from an expression parser hook (as opposed to evaluateCallExpressionMember or something similar), so our callback could return true, and thus prevent Webpack from having to evaluate the 'localRequire' parameter (that would generate the missing context warning). We can safely assume that the identifier of the class name will always be 'RequireUtils'.

We are open to other options for parser hooks into CallExpressions. For example, we would not mind being able to pass "*" into hooks.call() and then checking whether the callee is a MemberExpression with a certain object and property.

Thanks for looking into this!

Max

**Comment by prateekbh** [comment]
I am not sure if its related but I had similar problem.

Source code:
```js
import React from 'react'
..
..
..
export () => {
 return React.createElement('...', {});
}
```

Now, i wanted to get `React.createElement` and I did read that it works only with free variables. But I still took a look inside

Looks like webpack evaluated name by [getNameForExpression](https://github.com/webpack/webpack/blob/3f135f59b04b7a85e50564d882f860db67a754bf/lib/javascript/JavascriptParser.js#L2154). While this is straight forward for globals like `clearTimeout`/`setTimeout`. It produces `import var.createElement` for my desired node.

and i was able to get the node with `callAnyMember('imported var')` and an additional check that the var is `React`.

**My question:** This clearly works on all nodes. Can we simplify this so that callAnyMember('React') actually works?

**Comment by fabis94** [comment]
1. What's a "free variable"? I tried Googling this, but I couldn't find any resources that would properly explain what this is or why webpack would only be interested in those "free variables".
2. Why does webpack call hooks like `expressionAnyMember` only on these free variables? Hooks like `expressionAnyMember` are described in the docs as if they will be invoked for expressions on members, but in reality there's this weird seemingly arbitrary distinction that prevents this hook from being called unless the variable is "free"
3. The `walkCallExpression()` method of the Parser has a similar issue, only here the distinction isn't between free & non-free variables, but between call expression callee's that are or aren't identifiers. This is the issue that prevents `callAnyMember` and `call` from being called and requires plugin authors to do weird hacks where you're marking all relevant CallExpression instances as identifiers just to get Webpack to report on them.
