### ISSUE TITLE
After change file .js, webpack result is error.

### ISSUE THREAD

**Issue by EricAdonis** [webpack/webpack#9483]
- This is my project: [https://gitlab.com/EricAdonis/webpack-cra](https://gitlab.com/EricAdonis/webpack-cra)
- I'm working on a project boilerplate with webpack (optimized for bundler) but I have a very strange error in during installation.
- After the first run, it work.
![image](https://user-images.githubusercontent.com/49099200/62011418-6ba05a00-b1a2-11e9-8e2e-a0a463891d02.png)
- But after i changed file app.js, hot reload is work and reload, after i see result is error.
![image](https://user-images.githubusercontent.com/49099200/62011444-c33ec580-b1a2-11e9-9804-0bdb76bf6de7.png)
- And so on, after each change file *.js, i see result is error
![image](https://user-images.githubusercontent.com/49099200/62011473-ee291980-b1a2-11e9-98fb-1352a242a120.png)
- Can someone help me. I really need help. I thank you very much if you support me.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
