### ISSUE TITLE
import automatically put on top ignoring importScripts

### ISSUE THREAD

**Issue by frlinw** [webpack/webpack#9486]
# Bug report

service-worker-entry-point.js
```js
importScripts('/env.js')
import './sw/main.js'
```
generated code (dev example):
![image](https://user-images.githubusercontent.com/11896237/62079670-7cf37000-b24f-11e9-8385-41b68c54d2e2.png)

**What is the current behavior?**
Native `import`s are automatically put on top. The import order is not respected

**What is the expected behavior?**
I expect Webpack respecting the import order, it should consider `importScripts` as a valid `import` action.

**Other relevant information:**
webpack version:  4.x

**Comment by sokra** [comment]
> Native `import`s are automatically put on top. The import order is not respected

That's how it's spec'ed. That is correct and working as expected.

Try this instead:

``` js
import "./loadEnv";
import "./sw/main.js";
```

``` js
// loadEnv.js
importScripts("/env.js")
```
