### ISSUE TITLE
Even if target 'node' is specified, NodeStuffPlugin is activated

### ISSUE THREAD

**Issue by monkeythedev** [webpack/webpack#9487]
# Bug report

**What is the current behavior?**
Even when `target: "node"` options is specified, webpack overrides node variables (__dirname, __filename, path, etc...). The only way to avoid it is to add `node: false` option.
Actually that's confusing because the documentation explicitally says: 

> If the target is "web" (default) or "webworker", the NodeSourcePlugin plugin is also activated.

**If the current behavior is a bug, please provide the steps to reproduce.**
That's my full config file, actually it's pretty small:
```
{
  "mode": "development",
  "entry": {
    "app": "src/server/bin/www.js"
  },
  "output": {
    "path": "dist/server",
    "filename": "[name].js"
  },
  "target": "node",
  "externals": [nodeExternals()],
  "module": {
    "rules": [
      {
        "test": /\.ts$/,
        "use": [
          {
            "loader": "ts-loader",
            "options": {
              "compilerOptions": {
                "checkJs": false,
                "target": "esnext"
              }
            }
          }
        ]
      }
    ]
  },
  "resolve": {
    "extensions": [".ts", ".js"]
  }
}
```

**What is the expected behavior?**
I expect the node variables to not be touched by webpack when using `target: "node"`

**Other relevant information:**
webpack version:  4.38.0
Node.js version: 12.6.0
Operating System: Windows 10 Pro
Additional tools: Actually i'm using gulp 4 to run webpack and then i copy the generated bundle inside a node 12.6.0 docker container.

**Comment by sokra** [comment]
This has already been fixed in the `next` branch
