### ISSUE TITLE
Dependencies (micromatch) Security Vulnerabilities

### ISSUE THREAD

**Issue by michal-ayash** [webpack/webpack#9489]
# Bug report

**What is the current behavior?**
webpack package requires an old version of 'micromatch' (3.1.10) that requires 'set-value' with old version (2.0.0) which has vulnerability issue.

**If the current behavior is a bug, please provide the steps to reproduce.**
npm install webpack

**What is the expected behavior?**
Updating the package to require the latest version of ‘micromatch’ will resolve the issue.

**Other relevant information:**
webpack version:  4.38.0
Node.js version: 
Operating System: 
Additional tools:

**Comment by evilebottnawi** [comment]
It was bug in invalid `npm` range in audit base, latest `micromatch` in wepback doesn't contain vulnerabilities

**Comment by michal-ayash** [comment]
How can I get webpack npm with the right micromatch version?

Thanks

**Comment by evilebottnawi** [comment]
install latest webpack version and update lock file

**Comment by michal-ayash** [comment]
I tried to install the latest version in a new folder:
npm init
npm install webpack

and I still see in package-lock file micromatch with old version (3.1.18):

```
    "webpack": {
      "version": "4.38.0",
      "requires": {
        "@webassemblyjs/ast": "1.8.5",
        "@webassemblyjs/helper-module-context": "1.8.5",
        "@webassemblyjs/wasm-edit": "1.8.5",
        "@webassemblyjs/wasm-parser": "1.8.5",
        "acorn": "^6.2.0",
        "ajv": "^6.1.0",
        "ajv-keywords": "^3.1.0",
        "chrome-trace-event": "^1.0.0",
        "enhanced-resolve": "^4.1.0",
        "eslint-scope": "^4.0.0",
        "json-parse-better-errors": "^1.0.2",
        "loader-runner": "^2.3.0",
        "loader-utils": "^1.1.0",
        "memory-fs": "~0.4.1",
        "micromatch": "^3.1.8",
        "mkdirp": "~0.5.0",
        "neo-async": "^2.5.0",
        "node-libs-browser": "^2.0.0",
        "schema-utils": "^1.0.0",
        "tapable": "^1.1.0",
        "terser-webpack-plugin": "^1.1.0",
        "watchpack": "^1.5.0",
        "webpack-sources": "^1.3.0"
      }
```

**Comment by evilebottnawi** [comment]
Please read how semver works

**Comment by michal-ayash** [comment]
To resolve this issue we need 4.x.x version, and not 3.x.x version...
Did I miss anything?

**Comment by evilebottnawi** [comment]
@michal-ayash latest `micromatch@3` version doesn't contains vulnerabilities

**Comment by michal-ayash** [comment]
It requires set-value with old version (2.0.0) which causes vulnerability

**Comment by evilebottnawi** [comment]
@michal-ayash where you see what `2.0.0` is vulnerability, please provide link

**Comment by michal-ayash** [comment]
We got Prototype Pollution via OneBranch:
![image](https://user-images.githubusercontent.com/53402609/62134557-58e46d00-b2e9-11e9-89cf-adacf20db8ca.png)

If you can upgrade the package to require latest version of 'micromatch' it will resolve the issue.

Thanks,
Michal.

**Comment by evilebottnawi** [comment]
`OneBranch` has invalid audit report, latest `micromatch@3` doesn't contain vunariables, no we can't update because it is breaking change (micromatch@3` requires minimum node@8 )

**Comment by michal-ayash** [comment]
It looks that `set-value@2.0.0`  which `micromatch@3` requires has vulnerabilities.
Please see:
https://www.npmjs.com/advisories/1012

**Comment by evilebottnawi** [comment]
Latest `set-value` is `2.0.1`, please update deps
