### ISSUE TITLE
can't import from the constant defined by webpack.Defineplugin

### ISSUE THREAD

**Issue by inherithandle** [webpack/webpack#9490]
# Bug report

**What is the current behavior?**
I was going to put the statement `import a from API` which is defined by `webpack.DefinePlugin`. but I got the error, unexpected token.

```
// webpack.config.js
const path = require('path');
const webpack = require('webpack');

module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist')
  },
  plugins: [
    new webpack.DefinePlugin({
      API: JSON.stringify('./src/a.js')
    })
  ]
};

// index.js, this causes the error unexpected token
import a from API

// a.js
export default {
  a: 1
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**
```
git clone https://github.com/inherithandle/webpack-simple-bug
npm install
npx webpack
// you'll get the error unexpected token.
```

**What is the expected behavior?**
I expected my module to be bundled without the 'unexpected token' error.

**Other relevant information:**
webpack version: webpack@4.38.0
Node.js version: v11.10.0
Operating System: macOS Mojave, 10.14.1
Additional tools: webpack-cli@3.3.6

**Comment by tourze** [comment]
+1

**Comment by gregmartyn** [comment]
For anyone else finding this when searching, the better way to deal with custom imports is with [resolve.alias](https://webpack.js.org/configuration/resolve/#resolvealias).
