### ISSUE TITLE
"resolves.shift(...) is not a function" when using a forbidden entrypoint name

### ISSUE THREAD

**Issue by Lyrkan** [webpack/webpack#9491]
# Bug report

**What is the current behavior?**

Given the following config file (no matter what `./src/index.js` contains), two files will be created (`runtime.js` and `constructor.js`):

```js
module.exports = {
  mode: 'development',
  entry: {
    constructor: './src/index.js',
  },
  output: {
    path: __dirname + '/dist',
  },
  optimization: {
    runtimeChunk: 'single',
  }
};
```

Loading a page that includes those two files will result in the following error:

```
runtime.js:26 Uncaught TypeError: resolves.shift(...) is not a function
    at Array.webpackJsonpCallback [as push] (runtime.js:26)
    at constructor.js:1
```

This seems to be caused by the following part of the `runtime.js` file:

```js
if(installedChunks[chunkId]) {
  resolves.push(installedChunks[chunkId][0]);
}

installedChunks[chunkId] = 0;
```

`chunkId` being equal to `constructor` the condition always returns `true` since `({}).constructor` is... well, the constructor of the object.

It then fails later on because `installedChunks[chunkId][0]` is `undefined` instead of being a function.

The same thing can happen for `hasOwnProperty`, `toString`, etc. but it's probably less likely to happen in real life :)

**If the current behavior is a bug, please provide the steps to reproduce.**

See above.

**What is the expected behavior?**

It should either work at runtime, or display an error message during compilation (explaining that this is not an allowed entrypoint name).

**Other relevant information:**
webpack version: 4.38.0
Node.js version: 11.12.0
Operating System: N/A
Additional tools: N/A

**Comment by sokra** [comment]
Send a PR
