### ISSUE TITLE
Shared runtime for library & code splitting via the SplitChunksPlugin doesn't work properly (SystemJS & UMD)

### ISSUE THREAD

**Issue by thiscantbeserious** [webpack/webpack#9498]
# Bug report

**What is the current behavior?**

Code-splitting via the SplitChunksPlugin and/or via a shared Runtime leads to a non-functional library when being loaded by SystemJS. Chunks are never loaded.

If you disable both then, depending on the size of the files, webpack will create automatic Chunks that are properly loaded (provided if you have properly set the publicPath).

**If the current behavior is a bug, please provide the steps to reproduce.**

Minimal repository to reproduce the behaviour:

https://github.com/thiscantbeserious/webpack-library-code-splitting

Use yarn build && yarn start and see console output and the global window object.

**What is the expected behavior?**

Modules should be properly populated on request when being loaded by SystemJS - beware that modules here are spefically transpiled with new the 'system' libaryTarget. However the same behaviour occurs for UMD, so I guess it must be something else.

As per https://github.com/webpack/webpack/issues/8512 it seems like you're required to include all chunks manually ? Isn't that the purpose of the shared runtime? This doesn't seem feesible in any way for me.

**Other relevant information:**
webpack version:  4.38.0
Node.js version: v10.15.3
Operating System: Windows 8.1 and Debian 9
Additional tools: -

**Comment by thiscantbeserious** [comment]
Closing due to a lack of response/interest -> switched to Rollup which is more streamlined and works in my use-case.

**Comment by evilebottnawi** [comment]
Let's heep open for webpack@5

**Comment by evilebottnawi** [comment]
bump

**Comment by alexander-akait** [comment]
I don't think here was bug, the main problem here - you are missing splitted chunk from, the same problem happens when you forget do it for HTML, fixed code:
```
<script type="text/javascript">
    Promise.all([
      System.import("./bin/runtime.js"),
      // Because you split utils to own chunk, you need to import it
      System.import("./bin/all-src_utils_js.js"),
      System.import("./bin/componentLoader.js")
    ]).then(function([runtime, foo, loader]) {
      console.log(runtime.default, loader);
    });
  </script>
```

In real word I recommend to use `stats` from webpack and generate initial entrypoints (we have this in our stats) to avoid this problem, we have an issue in our repo to improve the error message here, sorry for delay
