### ISSUE TITLE
Loader called twice when used "inline"

### ISSUE THREAD

**Issue by ericmorand** [webpack/webpack#9499]
# Bug report

**What is the current behavior?**

When a loader is set "inline" in an import statement, the loader is called twice: once with the options on Webpack config file, once with the inline options.

It is explictly said that Webpack supports that:

https://webpack.js.org/concepts/loaders/#inline

**If the current behavior is a bug, please provide the steps to reproduce.**

* Create a webpack.config.js and add a rule there that link `.txt` files to `string-loader`.
* In your entry point, put this:

`import foo from 'string-loader!./foo.txt';`

* bundle your entry point

**What is the expected behavior?**

The loader should be called once. With a merge between the loader options from Webpack config and the inline options.

**Other relevant information:**
webpack version:  4
Node.js version: 11
Operating System: Xubuntu

**Comment by evilebottnawi** [comment]
Please provide you webpack.config.js

**Comment by ericmorand** [comment]
```
const {resolve: resolvePath} = require('path');

module.exports = {
    entry: resolvePath(__dirname, 'index.js'),
    mode: 'none',
    module: {
        rules: [
            {
                test: /\.txt$/,
                use: [
                    {
                        loader: 'string-loader'
                    }
                ]
            }
        ]
    }
};
```

**Comment by ericmorand** [comment]
And the result of the loader call:

```
(function(module, exports) {

module.exports = "module.exports = \"{{ foo }}\""

/***/ })
```

As you can see, it's been called twice - the two subsequent `module.exports`.

**Comment by evilebottnawi** [comment]
Please use `import foo from '!!string-loader!./foo.txt';`

**Comment by evilebottnawi** [comment]
you declare loader in config and in code so loader was called twice

**Comment by ericmorand** [comment]
Does it disable all loaders or only the ones that are inlined?

**Comment by evilebottnawi** [comment]
@ericmorand From docs:

> Prefixing with !! will disable all configured loaders (preLoaders, loaders, postLoaders)

**Comment by ericmorand** [comment]
Thanks a lot.
