### ISSUE TITLE
Respect "exports" field in "package.json"

### ISSUE THREAD

**Issue by mdreizin** [webpack/webpack#9509]
## Feature request

**What is the expected behavior?**

It would be nice if `webpack` respects `"exports"` filed defined in `package.json` and follow a new resolution strategy.

**What is motivation or use case for adding/changing the behavior?**

This feature is just landed in [`node@12.7.0`](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#2019-07-23-version-1270-current-targos) (see [`proposal-pkg-exports`](https://github.com/jkrems/proposal-pkg-exports/)).

**How should this be implemented in your opinion?**

1. Read `"exports"` filed and create `resolve.alias` map internally (ie if `resolve.useExports = true` is turned on) using proposed resolution strategy.

2. Allow to specify `resolve.mainFields = ['exports']` and check for this reserved keyword. If it is found then apply proposed resolution strategy. 

**Are you willing to work on this yourself?**

no

**Comment by sokra** [comment]
We can add this a experiment in webpack 5.

**Comment by mdreizin** [comment]
@sokra yes, it is good candidate to be included in `webpack@5`.

**Comment by evilebottnawi** [comment]
Bump

**Comment by just-boris** [comment]
In addition to `exports` field, the new module system also allows imports to reference its own package name: https://github.com/nodejs/node/pull/31002

More details on this feature: https://github.com/nodejs/modules/issues/306

**Comment by mgol** [comment]
The `exports` field is now available without any flag in Node.js `v13.7.0` and it will be unflagged in the [upcoming Node.js `v12.15.0`](https://github.com/nodejs/node/pull/31368), scheduled for 2020-01-28.

**Comment by evilebottnawi** [comment]
@mgol Don't worry, we will implement that for webpack@5

**Comment by trusktr** [comment]
Is this in the beta yet? I would like to test it if so.

**Comment by evilebottnawi** [comment]
No, but in roadmap, it will be implemented to stable version

**Comment by trusktr** [comment]
Someone mind fixing the typo in the title, "filed" -> "field", so that this may appear more easily in search results?

**Comment by evilebottnawi** [comment]
Done

**Comment by mgol** [comment]
An important note here: once the `exports` field is specified, it should be impossible to import any subpath that is not explicitly specified in the field.

More info at https://nodejs.org/api/esm.html#esm_package_exports:
> In addition to defining an alias, subpaths not defined by "exports" will throw when an attempt is made to import them
> ```js
> import submodule from 'es-module-package/private-module.js';
> // Throws ERR_MODULE_NOT_FOUND
> ```

This is a breaking change so please remember to include this restriction in Webpack 5.0.0 or it might have to wait until version 6!

**Comment by jhnns** [comment]
We also need to decide: what happens with the `module` field?

Tbh I'm not really decided yet. I think we can ignore/deprecate it as long as we support the `browser` target. This would allow package authors to specify different implementations for Node and for the browser:

```
    "exports": {
        "node": "./node-impl.js",
        "browser": "./browser-impl.js"
    }
```

**Comment by trusktr** [comment]
@mgol Actually that isn't completely true (I had some confusion with aspect of Node ESM). The Node.js docs needs better documentation in this area (cc @MylesBorins).

As an example, the following

```json
	"exports": {
		".": "./dist/index.js",
		"./": "./dist/"
	},
```

does allow you to import from any sub path of the `dist` folder.

**Comment by vankop** [comment]
I'll take a look on this

**Comment by jkrems** [comment]
If https://github.com/nodejs/node/pull/32869 lands, this likely should include support for `NODE_ENV` based resolution ("production" and "development").

**Comment by MHA15** [comment]
Hello

Is this feature implemented in v5? can we use it in v5-beta18 ?

Thanks

**Comment by vankop** [comment]
@MHA15 yes, this feature shipped with v5-beta18

**Comment by lcrosetto** [comment]
Is support for subpath export patterns supposed to be part of this? It seems to throw "module not found".

https://nodejs.org/api/packages.html#packages_subpath_export_patterns

**Comment by evilebottnawi** [comment]
@lcrosetto No, it is not implemented, please open a new issue, also it is `Experimental`

**Comment by siarheiyelin** [comment]
Are there any plans to support it in Webpack 4?

**Comment by alexander-akait** [comment]
No, only webpack v5

**Comment by HomyeeKing** [comment]
I've met an issue that my npm package **(`foo`  for example)**  need to be used in both webpack4.x and webpack5.x

how to let webpack4.x recognize exports fileds?  

Also I can't import through specific path(node_modules path) like `foo/bar/baz.js` in webpack5.x,  got an error `path ./bar/baz.js not exported from package`

**Comment by alexander-akait** [comment]
`exports` works only for webpack v5, v4 is not supported this

**Comment by ConnorLanglois** [comment]
I've run into an issue with this feature. Need to use `@vespaiach/axios-fetch-adapter` package, which imports modules from `axios`, but since axios has been updated to use the exports field this package now throws errors when trying to import those modules. I know we could wait for the package author to update their code, but as another option, could there be an option added to webpack to ignore this / force webpack to import the module? The exports still exist in axios in those files, so everything should work fine if webpack would just import it. It's along the lines of `Yes, thank you webpack, the exports field is cool and has benefits, but right now I do not care, just import the package anyway please` and anyone who uses this option would accept the fact they are playing with fire.

**Comment by ThiefMaster** [comment]
I fully agree with @ConnorLanglois. This MUST be something overridable. If I want to use an internal API, then this is my good right to do, and I understand the consequences (that it can break or be removed at any time). It's not up to webpack to decide that I can't.

FWIW, I'm trying to import `axios/lib/helpers/isURLSameOrigin` for some custom code that's directly related to axios so it even makes sense to use the same function there. If I have to copy this code into my project, there's actually a bigger risk of the two implementations diverging at some point, causing issues...

**Comment by snydergd** [comment]
In cases where you want to ignore the exports while package maintainers do updates, one option I am trying right now is to set the webpack config option `resolve.exportsFields` to an empty array.  It seems to work, though I'm not sure what other side effects larger projects might experience.
