### ISSUE TITLE
Progress messages are shown on multiple lines after upgrade to 4.39.0

### ISSUE THREAD

**Issue by doberkofler** [webpack/webpack#9511]
# Bug report

**What is the current behavior?**

After upgrading to from 4.38.0 to 4.39.0 the progress output is no longer shown on a single line but on multiple lines as visible here:

![image](https://user-images.githubusercontent.com/1009585/62347591-7fc5bd80-b4fa-11e9-9289-efabf42a8c23.png)

In the previous version the progress output was repeatedly (just a CR) shown on a single line that got overwritten on each step and now each step is shown on a separate (LF) line.

**If the current behavior is a bug, please provide the steps to reproduce.**

Just using the `--progress` option should be enough.

**What is the expected behavior?**

It's just a nuisance but having back the single line output of the progress messages not to clutter the screen would be nice.

**Other relevant information:**
webpack version:  4.39.0
Node.js version: 12.7.0
Operating System: Windows 7
Additional tools:

**Comment by sokra** [comment]
Which terminal?

**Comment by doberkofler** [comment]
ConEmu 190526

**Comment by sokra** [comment]
Could you try this PR #9513 if it fixes the problem?

add this to your package.json to test it: `"webpack": "webpack/webpack#bugfix/terminal-length"`

**Comment by doberkofler** [comment]
Wow, that's quick!
Yes, this PR fixes the problem!

**Comment by wldcordeiro** [comment]
I'm on that 4.39.1 patch release and still seeing these weird output things.

<img width="795" alt="Screen Shot 2019-08-05 at 9 52 26 AM" src="https://user-images.githubusercontent.com/580982/62477711-c0c20a00-b766-11e9-84c1-685b7190b281.png">

**Comment by sokra** [comment]
Could you file a new issue? Add information about which terminal is used.

**Comment by supercodepoet** [comment]
With 4.39.1 I also see the extended progress output with iTerm and Terminal on macOS Mojave running zsh
