### ISSUE TITLE
Custom JsonpTemplatePlugin to use fetch instead of script tag

### ISSUE THREAD

**Issue by mattkrick** [webpack/webpack#9516]
## Feature request

**What is the expected behavior?**
Asset requests include an `Origin` header.
 

**What is motivation or use case for adding/changing the behavior?**
- `Origin` is included in the Fetch API, it is _not_ included when js is loaded via `<script>`.
- Sending `Origin` is important because server respond differently based on the request headers. For example, if AWS S3 does not receive an `Origin` header, it does not reply with an `access-control-Allow-Origin` header or a `Vary: origin` header.
- Without a `Vary: origin` header, browsers like Chrome will cache 2 similar requests, even if their `Origins` are different.

**How should this be implemented in your opinion?**
Opt in to always using the Fetch API. Turning a flag on changes the `JsonpTemplatePlugin` to use fetch instead of `<script>`. This could be as simple as a boolean flag, or as complex as a plugin that, when present, overrides the internal `JsonpTemplatePlugin`.

**Are you willing to work on this yourself?**
yes. just need confirmation that the PR will be accepted

**Comment by SebastienTainon** [comment]
@mattkrick It looked a good idea, I would like to do the same thing. How have you solved it and/or why did you close it?

**Comment by mattkrick** [comment]
already built in
```
  output: {
    crossOriginLoading: 'anonymous'
  }
```
