### ISSUE TITLE
Can't use `[name]` in `webassemblyModuleFilename`

### ISSUE THREAD

**Issue by RReverser** [webpack/webpack#9517]
# Bug report

**What is the current behavior?**

Trying to use `[name]` in `output.webassemblyModuleFilename` config leads to:

```
ChunkRenderError: Path variable [name] not implemented in this context: 
```

**What is the expected behavior?**

`[name]` should be accepted and replaced with a basename of the Wasm file, like WebPack does in `filename` and `chunkFilename` contexts.

**Other relevant information:**
webpack version:  4.28.0
Node.js version: 12.7.0
Operating System: Windows 10
Additional tools:

**Comment by sokra** [comment]
Send a PR to enable `[file]` and `[filebase]` for wasm modules.

https://github.com/webpack/webpack/blob/f29445d46624ef4726465e27bbe6e003aa07f8be/lib/wasm/WebAssemblyModulesPlugin.js#L76-L78

Add `filename` property. Get the filename with `module.nameForCondition()`.

**Comment by RReverser** [comment]
Thanks for the pointers, going to try that!

**Comment by RReverser** [comment]
To be clear - will that automatically enable support for `name` too, or that needs to be added separately?

**Comment by sokra** [comment]
No `[name]` is the chunk name which is not available in module context

**Comment by RReverser** [comment]
I see. It's just that it works for regular modules (when they're imported asynchronously, thus being the "main" module in the chunk, thus following `chunkFilename` template), so feels like it would be consistent to have the same working for Wasm imports.

**Comment by sokra** [comment]
It works for JS because there is a 1 to 1 relation between chunk and js asset. But for wasm there is a n to m relation between chunk and wasm asset.

One chunk can contain multiple wasm modules.

One wasm module can be in multiple chunks.

**Comment by RReverser** [comment]
> One wasm module can be in multiple chunks.

Do you mean in multiple JS chunks? I was rather referring to "WASM chunks" (which probably don't exist and are just solitary WASM modules, but still feel like close enough conceptually to support same templating parameters).

**Comment by RReverser** [comment]
Hmm, I've added `filename` + `filebase` support, but realised it's not enough, as basename still includes the extension, making it hard to combine with hash in template.

**Comment by RReverser** [comment]
Even the one I've added is apparently not enough, still getting:

```
ERROR in chunk main [entry]
Path variable [filebase] not implemented in this context: "[filebase]." + {"1":"a36cec63b02caac8e61a","3":"a04390412f9500b1d7ae","4":"0a12d714e570b7fd9d8b"}[\wasmModuleId\] + ".wasm"
```

I see in console.log that the one I've added is correctly substituted for the original template, but apparently there is some other template that is still missing data...

**Comment by RReverser** [comment]
UPD: Looks like that's coming from `WasmMainTemplatePlugin.js`: https://github.com/webpack/webpack/blob/c36966a2c996c873b372f46d383f40b7d706fa3b/lib/wasm/WasmMainTemplatePlugin.js#L205-L231

**Comment by RReverser** [comment]
Okay, I think I can fix it, but, as noted above, it still won't lead to the original `[name]` I hoped to get.

@sokra I might need further help on deciding what to do here then - `[filename]` and `[filebase]` are not suitable variable to put a filename without extension, and I'm not sure which variable from the existing list would be... Do you think I can just add `chunk: { name: ... }` to the templating data just so that `[name]` would work for Wasm modules, even though it's not technically a chunk name?

**Comment by evilebottnawi** [comment]
Bump

**Comment by alexander-akait** [comment]
Still valid

**Comment by sokra** [comment]
`[name]` won't be implemented in context of `webassemblyModuleFilename` as it's related to chunks and `webassemblyModuleFilename` is related to modules.
