### ISSUE TITLE
Webpack PublicPath to be a function

### ISSUE THREAD

**Issue by hitmands** [webpack/webpack#9518]
## Feature request

The documentation says that `__webpack_public_path__` can be [overwritten at runtime](https://webpack.js.org/guides/public-path/#on-the-fly), something like `__webpack_public_path__ = '/www.something.com/`. 

We could extend this feature by allowing it to be a function:
```
__webpack_public_path__ = chunk => `www.something.com/${chunk}`
```

**What is the expected behavior?**
this would allow webpack to load files from different public paths, depending on the requested chunk.

**What is motivation or use case for adding/changing the behavior?**
Avoiding unnecessarily client's cache invalidation, further information: https://stackoverflow.com/questions/57337716/webpack-publicpath-use-different-urls-to-reuse-bundles

**How should this be implemented in your opinion?**
`__webpack_public_path__` as a function. It would retrieve the requested chunk as argument and return its absolute path.

**Are you willing to work on this yourself?**
yes

**Comment by hitmands** [comment]
Actually, 
the [doc](https://webpack.js.org/configuration/output/#outputpublicpath) also says that a function is allowed for `output.publicPath`:
![image](https://user-images.githubusercontent.com/5674833/62411871-da8e1080-b5f1-11e9-94f1-001ac3d1e1ed.png)

___
The function interface is not documented.

**Comment by hitmands** [comment]
https://github.com/webpack/webpack/issues/2776#issuecomment-299009032

**Comment by hitmands** [comment]
A similar use case is covered by this plugin: https://github.com/agoldis/webpack-require-from

**Comment by hitmands** [comment]
A different implementation could just be **exposing** this function:

```
/******/ 	function jsonpScriptSrc(chunkId) {
/******/ 		return __webpack_require__.p + "" + ({...}[chunkId]||chunkId) + ".js"
/******/ 	}

```

**Comment by hitmands** [comment]
https://github.com/webpack/webpack/issues/8115

**Comment by evilebottnawi** [comment]
Can be implemented for webpack@5

**Comment by hitmands** [comment]
I just found an implementation from @sokra 
https://github.com/webpack/webpack/pull/8462

**Comment by evilebottnawi** [comment]
Bump

**Comment by evilebottnawi** [comment]
Mistake, done here https://github.com/webpack/webpack/pull/8462/
