### ISSUE TITLE
Webpack 4 doesn't seem to minify imported packages that have been bundled in dev mode

### ISSUE THREAD

**Issue by linasmnew** [webpack/webpack#9527]
# Bug report

**What is the current behavior?**
I have 2 basic skeleton projects, an app and a library both using `webpack 4.39.1`. Bundling the library in production mode in isolation works fine, **_however_**, if I bundle this library in dev mode, `npm pack` it, and import it into the app and bundle this app in prod mode - said library does not get minified, however, when I switch the libraries webpack version to `3.10.0` and repeat the process - it does get minified as expected.

Looking at the libraries dev mode output between versions `4.39.1` & `3.10.0` the main difference seems to be that v4 is wrapping the code in `eval` whereas v3 isn't. Though not sure if that's relevant.

**If the current behavior is a bug, please provide the steps to reproduce.**
Can be reproduced or just observed if you don't want to pull the branch **_(have included the compiled output in the repo)_**: https://github.com/linasmnew/webpack-behaviour-checkin

Also, for those not willing to look at the repo (it's tiny) webpack configs used:
`library`
```
module.exports = {
    entry: './source/index.js',
    output: {
        path: path.resolve(__dirname, 'lib'),
        filename: 'testlibrary.js',
        library: 'testlibrary',
        libraryTarget: 'umd'
    },
    mode: 'development',
    module: {
        rules: [{ test: /\.js$/, exclude: /node_modules/, use: ['babel-loader'] }]
    }
}
```

`app`
```
module.exports = {
    entry: './source/index.js',
    output: {
        path: path.resolve(__dirname, 'public'),
        filename: 'app/[name].[chunkhash].js'
    },
    module: {
        rules: [{ test: /\.js$/, exclude: /node_modules/, use: ['babel-loader'] }]
    },
    optimization: {
      runtimeChunk: "single",
      splitChunks: {
        cacheGroups: {
          vendor: {
            name: 'vendor',
            test: /[\\/]node_modules[\\/]/,
            chunks: 'all',
            minSize: 0
        }
      }
    }
  }
}
```

**What is the expected behavior?**
The library should be optimized and minified when app is bundled in production mode instead of keeping its dev mode output.

**Other relevant information:**
webpack version:  4.39.1
Node.js version: 12.6.0
Operating System: MacOS Mojave 10.14
Additional tools:

**Comment by sokra** [comment]
Don't bundle your library. Transpile it with babel if your want to.

**Comment by linasmnew** [comment]
Hey, thanks for the reply.

I get that, but at the moment I got a use case where I need to make it work with what already exists, but that is definately on the roadmap.

**Comment by linasmnew** [comment]
Ok so looks like it's an issue with the default source map eval option, changing source maps to `source-map` fixes it.
