### ISSUE TITLE
Use .webpackrc in place of webpack.config.js?

### ISSUE THREAD

**Issue by gsklee** [webpack/webpack#953]
Benefits:

1. Match existing naming convention
2. No longer need to manually specify the location of the config file when using gulp-webpack, etc.

**Comment by xpepermint** [comment]
+1

**Comment by sokra** [comment]
How would you handle `webpack.config.js` `webpack.config.coffee` ...?

**Comment by gsklee** [comment]
Well, perhaps don't write it in CoffeeScript? Just like you can't do `package.yaml`, `package.toml` etc.

**Comment by troutowicz** [comment]
The webpack config is more than just lines of configuration though, it's a module with logic. Being able to handle other languages is important.

**Comment by gsklee** [comment]
I guess you're right... closing.

**Comment by akre54** [comment]
Side note: you can now write your config in yaml, toml, etc, or even csv if you so desire. #956
