### ISSUE TITLE
npm audit brought 82 (!) high risk warnings for webpack or webpack-cli

### ISSUE THREAD

**Issue by greenais** [webpack/webpack#9535]
# Bug report

**What is the current behavior?**
npm audit brought 82 high risk warnings for webpack or webpack-cli, referring, in particular, to:
mixin-deep (20 high risk issues)
set-value (62 high risk issues)

**If the current behavior is a bug, please provide the steps to reproduce.**
Run npm audit

**What is the expected behavior?**
No high risk warnings

For both faulty dependency packages in advisory section there are list of patched versions. Is npm wrong?

**Other relevant information:**
"webpack": "4.39.1",
 "webpack-cli": "3.3.6"
Node.js version: 10.16.1
Operating System:  Win 8-64

**Comment by evilebottnawi** [comment]
Please update your lock file, you you old deps

**Comment by greenais** [comment]
Do you mean I have to update webpack deps manually?
Both mentioned packages are used by webpack only - I never installed them separately
Why webpack install didn't update them during upgarde to new version if the are vulnerable?
Moreover - they don't appear when I fire npm outdated
Please clarify

**Comment by evilebottnawi** [comment]
Nothing in webpack deps is not vulnerable. You have oudated deps and/or lock file and need update this, or you use invalid audit register, install latest webpack and run `npm audit` (no problems)

**Comment by greenais** [comment]
Once again: 

> I never installed them separately

both were installed as webpack deps. So I expected that webpack during new version install will take care of updating them. Other packages do.

Regarding vulnerability - excerpt from just fired npm audit for latest webpack:

```
High            Prototype Pollution

  Package         mixin-deep

  Dependency of   webpack [dev]

  Path            webpack > watchpack > chokidar > readdirp > micromatch >
                  snapdragon > base > mixin-deep

  More info       https://npmjs.com/advisories/1013




  High            Prototype Pollution

  Package         mixin-deep

  Dependency of   webpack-cli [dev]

  Path            webpack-cli > findup-sync > micromatch > snapdragon > base >
                  mixin-deep

  More info       https://npmjs.com/advisories/1013
```

**Comment by evilebottnawi** [comment]
@greenais problem on register side, latest npm register doesn't have audit problems

**Comment by greenais** [comment]
@evilebottnawi I have latest node and therefore npm.
Probably you should look into webpack/-cli install scripts to eliminate such cases - that's why I filed bugreport.
```
What helped:
1) removing webpack and webpack-cli
2) deleting package-lock.json
3) intsalling both once again
```
No issues now, but it shouldn't be this way, my guess

**Comment by evilebottnawi** [comment]
> deleting package-lock.json

I written above about removing lock file, it is expected, because you have old deps

**Comment by greenais** [comment]
When you upgrade webpack you have no idea if its only deps are old or not.
Install scrip should check it - that's what I'm talking about.
Or - to be honest - one should add to install instructions: "Hey guys, we can''t manage it - so delete package-lock.json anyway, just in case"

**Comment by evilebottnawi** [comment]
> Install scrip should check it - that's what I'm talking about.

What is script? Npm script or yarn script? Or we should update your transitive dependencies and potentially break app/library?

> Hey guys, we can't manage it - so delete package-lock.json anyway, just in case

What? Are you sensuously? It is lock files, and we can't manage transitive dependencies, only way is update lock file, this is how package managers work.

**Comment by greenais** [comment]
> its only deps
