### ISSUE TITLE
“rules” is not allowed error with Webpack 4

### ISSUE THREAD

**Issue by mmmathur** [webpack/webpack#9549]
# Bug report

**Recently I have updated my webpack 1 with webpack@4.39.1 where as per Webpack documentation module.loaders is replaced by module.rules and I'm using the same in webpack.config.js file but still I'm getting following error: [1] "loaders" is required [2] "rules" is not allowed

My webpack.config looks like this:

I have tried removing entire node_modules folder and fresh npm install so that old webpack is no longer available also I verified global node_modules but webpack is not installed globally.**

webpack.config.js fragment
`rules: [
      {
        test: /\.ts$/,
        loader: 'ts-loader',
        exclude: /node_modules/
      },
      {
        test: /\.js$/,
        loader: 'ng-annotate-loader',
        exclude: /node_modules/
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        query: {
          cacheDirectory: true,
          compact: false
        }
      },
      {
        test: /\.css$/,
        use: [
          {
            loader: 'style-loader'
          },
          {
            loader: 'css-loader',
            options: {
              modules: true
            }
          }
        ]
      },
      {
        test: /\.(png|jpg|gif|woff|woff2|ttf|eot|svg)/,
        loader: 'url-loader'
      },
      {
        test: /\.html$/,
        loader: 'html-loader?minimize=false'
      },
      {
        test: /\.json/,
        loader: 'json-loader'
      },
      {
        test: /node_modules(\/|\\)globalize/,
        loader: 'imports?define=>false'
      },
      {
        test: /node_modules(\/|\\)cldrjs/,
        loader: 'imports?define=>false'
      }
    ]
  };
`

**If the current behavior is a bug, please provide the steps to reproduce.**

**Webpack 4 should accept rules and rather than loader**

**Other relevant information:**
webpack version:  4.39.1
Node.js version: 11.6.0
Operating System: Windows
Additional tools: css-loader, style-loader

**Comment by evilebottnawi** [comment]
You have invalid configuration

> If the current behavior is a bug, please provide the steps to reproduce.

Missing

We closing issue due incomplete template, fix this and we can help you

**Comment by mmmathur** [comment]
Missed copying proper braces in this post however my configuration returns valid on parse
`
module: {
    rules: [
      {
        test: /\.ts$/,
        loader: 'ts-loader',
        exclude: /node_modules/
      },
      {
        test: /\.js$/,
        loader: 'ng-annotate-loader',
        exclude: /node_modules/
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        query: {
          cacheDirectory: true,
          compact: false
        }
      },
      {
        test: /\.css$/,
        use: [
          {
            loader: 'style-loader'
          },
          {
            loader: 'css-loader',
            options: {
              modules: true
            }
          },
        ],
      },
      // {
      //   test: /\.cssm$/,
      //   loader: ExtractTextPlugin.extract('style-loader', 'css-loader?modules&importLoaders=1&localIdentName=[name]__[local]!postcss-loader!postcss-loader')
      // },
      {
        test: /\.(png|jpg|gif|woff|woff2|ttf|eot|svg)/,
        loader: 'url-loader'
      },
      {
        test: /\.html$/,
        loader: 'html-loader?minimize=false'
      },
      {
        test: /\.json/,
        loader: 'json-loader'
      },
      {
        test: /node_modules(\/|\\)globalize/,
        loader: 'imports?define=>false'
      },
      {
        test: /node_modules(\/|\\)cldrjs/,
        loader: 'imports?define=>false'
      }
    ]
  }
`

**Comment by evilebottnawi** [comment]
Remove `postcss` option, it is not allowed here
