### ISSUE TITLE
Combine modules if a module is used by only a single module

### ISSUE THREAD

**Issue by Linksku** [webpack/webpack#9550]
## Feature request

If a module is used by only one other module, combine them into a single module.

**What is the expected behavior?**

E.g.:

Source Component.js:

```
import styles from './ComponentStyles.scss';

...
render() {
  return (
    <div className={styles.style} />
  )
}
```

Source ComponentStyles.scss:
```.style {}```

Webpack output:

```
123: function(t, e, n) {
    t.exports = {
        input: "ComponentStyles__style"
    }
 },
...
var a = n(123), o = n.n(a);
...
return t("div", {
    class: o.a.style
})
```

Desired output:

Either:

```
var a = {
    input: "ComponentStyles__style"
};
...
return t("div", {
    class: a.input
})
```
Or even better:
```
return t("div", {
    class: "ComponentStyles__style"
})
```

**What is motivation or use case for adding/changing the behavior?**

One use-case is React + CSS modules. Since there's a 1-to-1 relationship between React components and CSS modules, it makes sense to combine them into a single module. Then, minimizers can optimize it further.

**How should this be implemented in your opinion?**

No idea.

**Are you willing to work on this yourself?**
no

SO question: https://stackoverflow.com/questions/57229989/is-there-a-way-to-combine-webpack-modules-to-decrease-file-size

**Comment by sokra** [comment]
We already do that when certain requirements are met.

both modules has to be ESM, in the same chunk, child is not used somewhere else, and some other minor things

**Comment by sokra** [comment]
I guess css-loader doesn't emit ESM

**Comment by evilebottnawi** [comment]
I think related https://github.com/webpack-contrib/css-loader/issues/509
