### ISSUE TITLE
compiler.getInfrastructureLogger is not a function

### ISSUE THREAD

**Issue by hannadrehman** [webpack/webpack#9553]
# Bug report

## "compiler.getInfrastructureLogger is not a function"

**steps to reproduce.**
Updated  webpack to `v4.39.1` and this error started showing.

```stderr: /Users/hannadrehman/workspace/healthifyme/web-frontend/node_modules/webpack-dev-ser
ver/bin/webpack-dev-server.js:97
    throw err;
    ^

TypeError: compiler.getInfrastructureLogger is not a function
    at ProgressPlugin.apply (/Users/hannadrehman/workspace/healthifyme/web-frontend/node_modules/webpack/lib/ProgressPlugin.js:79:14)
    at webpack (/Users/hannadrehman/workspace/healthifyme/web-frontend/node_modules/webpack-dev-server/node_modules/webpack/lib/webpack.js:49:13)
    at startDevServer (/Users/hannadrehman/workspace/healthifyme/web-frontend/node_modules/webpack-dev-server/bin/webpack-dev-server.js:89:16)
    at processOptions (/Users/hannadrehman/workspace/healthifyme/web-frontend/node_modules/webpack-dev-server/bin/webpack-dev-server.js:173:3)
    at processOptions (/Users/hannadrehman/workspace/healthifyme/web-frontend/node_modules/webpack-dev-server/lib/utils/processOptions.js:26:3)
    at Object.<anonymous> (/Users/hannadrehman/workspace/healthifyme/web-frontend/node_modules/webpack-dev-server/bin/webpack-dev-server.js:172:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)```



**Other relevant information:**
webpack version:  4.39.1
Node.js version: v10.16.2
Operating System: macOS 10.14.6
Additional tools:

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by sokra** [comment]
```
/Users/hannadrehman/workspace/healthifyme/web-frontend/node_modules/webpack
/Users/hannadrehman/workspace/healthifyme/web-frontend/node_modules/webpack-dev-server/node_modules/webpack
```

Seem like two different version of webpack are installed. Delete all webpack versions from your lockfile and reinstall.

**Comment by Cosen95** [comment]
I also encountered the same problem, but I don’t know the specific reason. Is there a specific solution now?

**Comment by dswtpvtltd** [comment]
I am facing same problem also

**Comment by Jobayerdev** [comment]
Now I'm suffering the same Point when webpack re-configuration

**Comment by jt3k** [comment]
I have the same problem.

**Comment by alexander-akait** [comment]
@jt3k Update webpack v4 to the latest version

**Comment by jt3k** [comment]
> @jt3k Update webpack v4 to the latest version

important for me is not to change the nodejs version. I am currently using nodejs version 8
if i change webpack version from v4 to v5 then i have to update nodejs as well but this is not possible in the current project.

Is it possible to fix the problem without changing the nodejs version?

**Comment by alexander-akait** [comment]
You don't need update Node.js, update v4 to the latest version

**Comment by aryanbhatt-clvt** [comment]
Getting same error, I also cannot find multiple versions of webpack. So what is the cause of this ?


C:\Users\U6071085\Music\CPDI\rapid-ui\node_modules\webpack-dev-server\lib\Server.js:263
    this.logger = this.compiler.getInfrastructureLogger("webpack-dev-server");
                                ^

TypeError: this.compiler.getInfrastructureLogger is not a function
    at new Server (C:\Users\U6071085\Music\CPDI\rapid-ui\node_modules\webpack-dev-server\lib\Server.js:263:33)
    at startWebpackDevServer (C:\Users\U6071085\Music\CPDI\rapid-ui\app\server\webpack-dev-server.js:38:18)
    at Object.<anonymous> (C:\Users\U6071085\Music\CPDI\rapid-ui\app\server\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49

Node.js v18.20.4
"webpack": "5.92.1",
    "webpack-dev-middleware": "7.2.1",
    "webpack-dev-server": "5.0.4",
    "webpack-hot-middleware": "2.26.1"

**Comment by aryanbhatt-clvt** [comment]
**webpack.config.dev.js**

`const path = require("path");
const webpack = require("webpack");
const autoprefixer = require("autoprefixer");
const ModuleScopePlugin = require("react-dev-utils/ModuleScopePlugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const _ = require("lodash");
const { log } = require("console");

const postcss = {
  loader: "postcss-loader",
  options: {
    postcssOptions: {
      plugins: [autoprefixer()]
    }
  }
};

module.exports = {
  devtool: "source-map",

  entry: {
    app: [
      "react-hot-loader/patch",
      path.resolve(__dirname, "client/polyfills.js"),
      path.resolve(__dirname, "client/index.js")
    ]
  },
  devServer: {
    contentBase: path.resolve(__dirname, "client"),
    hot: true,
  },

  output: {
    filename: "static/[name].js",
    chunkFilename: "static/js/[name].chunk.js",
    path: path.resolve(__dirname, "client/static"),
    publicPath: "/"
  },
  resolve: {
    modules: ["node_modules", path.resolve(__dirname, "client")],
    extensions: [".js"],
    alias: {
      "react-native": "react-native-web"
    },
    plugins: [
      new ModuleScopePlugin(path.resolve(__dirname, ".."), [
        path.resolve(__dirname, "../package.json")
      ])
    ]
  },
  module: {
    rules: [
      {
        oneOf: [
          {
            test: [/\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/],
            loader: require.resolve("url-loader"),
            options: {
              limit: 10000,
              name: "static/media/[name].[hash:8].[ext]"
            }
          },
          {
            test: /\.svg$/,
            use: [
              {
                loader: "babel-loader"
              },
              {
                loader: "react-svg-loader",
                options: {
                  jsx: true
                }
              }
            ]
          },
          {
            test: /\.(js|jsx)$/,
            exclude: /node_modules\/(?!(component-library))/,
            loader: require.resolve("babel-loader"),
            options: {
              cacheDirectory: true,
              plugins: ["react-hot-loader/babel"],
              ignore: /node_modules\/(?!(component-library))/
            }
          },
          {
            test: /global\.scss$/,
            use: [
              MiniCssExtractPlugin.loader,
              {
                loader: "css-loader",
                options: {
                  sourceMap: true,
                  importLoaders: 1
                }
              },
              {
                loader: "sass-loader",
                options: {
                  sourceMap: true,
                  modules: false,
                  importLoaders: 1,
                  includePaths: [
                    path.resolve(__dirname, "../node_modules"),
                    path.resolve(__dirname, "client/styles")
                  ]
                }
              },
              postcss
            ]
          },
          {
            test: /^((?!\.global).)*\.s?css$/,
            use: [
              MiniCssExtractPlugin.loader,
              {
                loader: "css-loader",
                options: {
                  sourceMap: true,
                  modules: true,
                  importLoaders: 100,
                  localIdentName: "[path][name]__[local]",
                  includePaths: [
                    path.resolve(__dirname, "../node_modules"),
                    path.resolve(__dirname, "client")
                  ]
                }
              },
              {
                loader: "sass-loader",
                options: {
                  sourceMap: true,
                  modules: true,
                  localIdentName: "[path][name]__[local]",
                  importLoaders: 1,
                  includePaths: [path.resolve(__dirname, "../node_modules")]
                }
              },
              postcss
            ]
          },
          {
            test: /\.raw$/,
            use: "raw-loader"
          },
          {
            test: /\.css$/,
            use: [
              MiniCssExtractPlugin.loader,
              {
                loader: "css-loader",
                options: {
                  sourceMap: true,
                  convertToAbsoluteUrls: true,
                  includePaths: [
                    path.resolve(__dirname, "../node_modules"),
                    path.resolve(__dirname, "client/styles")
                  ]
                }
              },
              postcss
            ]
          },
          {
            exclude: [/\.js$/, /\.html$/, /\.json$/],
            loader: require.resolve("file-loader"),
            options: {
              name: "static/media/[name].[hash:8].[ext]"
            }
          }
        ]
      }
    ]
  },
  plugins: [
    new webpack.DefinePlugin({
      "process.env": {
        NODE_ENV: JSON.stringify(process.env.NODE_ENV || "development")
      }
    }),
    new MiniCssExtractPlugin({
      filename: "bundle.css"
    }),
    new webpack.HotModuleReplacementPlugin()
  ],

  optimization: {
    splitChunks: {
      cacheGroups: {
        vendor: {
          name: "vendor",
          test: /[\\/]node_modules[\\/]/,
          chunks: "all",
          enforce: true
        }
      }
    },
    moduleIds: "named"
  },

  node: {
    __dirname: false,
    __filename: false,
    global: false
  },
  performance: {
    hints: false
  }
};

const privateModules = [
  "data-server",
  "component-library",
  "enterprise-ui",
  "enterprise-server",
  "data-client"
];

function isPrivate(userRequest) {
  return privateModules.some(module => userRequest.includes(`node_modules/${module}`));
}

function isExternal(userRequest) {
  return typeof userRequest === "string" && !isPrivate(userRequest) && userRequest.includes("node_modules");
}
`
