### ISSUE TITLE
Keep loaderContext._module.issuer in production mode

### ISSUE THREAD

**Issue by Maorey** [webpack/webpack#9557]
## Feature request

**What is the expected behavior?**
Keep [loaderContext._module](https://webpack.js.org/api/loaders/#this_module).issuer same with `development` [mode](https://webpack.js.org/configuration/mode/) in `production` mode

**What is motivation or use case for adding/changing the behavior?**
I want to inject variables to scss files by different entry (or directory):

``` JavaScript
function includes(module, entry) {
  return (
    !!module &&
    (module.context.includes(entry) || includes(module.issuer, entry))
  )
}
// ...
{
  loader: 'sass-loader',
  options: {
    data({ _module }) {
      if (includes(_module, 'src/main')) {
        return '$value: 100px;'
      } else if (includes(_module, 'src/about')) {
        return '$value: 200px;'
      }
      return ''
    },
  },
}
```
It works in `development` mode, but ineffective in `production` mode for which `loaderContext._module.issuer` is `null`.

Can webpack keep `module. issuer`, or there is a way to implement this?

**How should this be implemented in your opinion?**
Keep loaderContext._module.issuer in production mode

**Are you willing to work on this yourself?**
yes, but I'm unfamiliar with webpack code

**Comment by Maorey** [comment]
Use [latest version](https://github.com/webpack/webpack/tree/v4.39.1)

**Comment by evilebottnawi** [comment]
you can't use `_module`, because it is private field, also not related to webpack, please open issue in sass-loader
