### ISSUE TITLE
Webpack --watch still processes removed files, is it expected?

### ISSUE THREAD

**Issue by dko-slapdash** [webpack/webpack#9560]
(If it's not a bug, but an expected behavior, probably worth explaining the behavior of `--watch` option in the docs. Or it's a question to ts-loader?)

Looks like `--watch` mode still remembers the files which were removed and continues compiling them, even though they don't exist and aren't referenced from anywhere. Does webpack --watch listen to filesystem removal signal when building (on Linux)?

**Example**

```ts
// a.ts
export function aaa() {} // <- line to be removed
```

```ts
// b.ts    <- file to be deleted
import { aaa } from "./a";
aaa();
```

```ts
// entry.ts
import "./b";    // <- line to be removed
```

Now 1) remove `import "./b"` line from entry.ts, b) delete b.ts file, c) remove `export function aaa` from a.ts. I then see the following error:
```
ERROR in b.ts
[tsl] ERROR in b.ts <-- WTF? it's been deleted!
      TS2305: Module '"./a.ts"' has no exported member 'aaa'.
```

I.e., although file b.ts has been removed, webpack --watch still tracks it, and due to that it requires a.ts to still have aaa() function, although there are no more references to aaa() in the whole codebase.

**Comment by sokra** [comment]
The error is from typescript. What typescript related loaders and plugins do you use?

**Comment by dko-slapdash** [comment]
Just ts-loader 6.0.4 (I tried an older version too, same symptoms), also tsconfig-paths-webpack-plugin 3.2.0 (latest).

**Comment by sokra** [comment]
What's you tsconfig

**Comment by dko-slapdash** [comment]
```js
{
  "compilerOptions": {
    "allowJs": true,
    "baseUrl": "src",
    "jsx": "react",
    "lib": ["es6", "esnext.asynciterable", "dom"],
    "module": "commonjs",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "outDir": "dist",
    "pretty": true,
    "resolveJsonModule": true,
    "sourceMap": true,
    "target": "es5",
    "esModuleInterop": true,
    "noImplicitReturns": true,
    "strict": true,
    "paths": {
      "shared/*": ["../../server/src/shared/*"],
      "*": ["*", "../node_modules/@types/*", "../node_modules/*"] // essential for shared/ folder
    }
  },
  "exclude": ["node_modules"],
  "include": ["src/**/*"]
}
```

**Comment by sokra** [comment]
> ```js
>   "include": ["src/**/*"]
> ```

Afaik this includes every file in src, not only files that are imported by webpack, for typechecking.

**Comment by dko-slapdash** [comment]
Probably, but is it related to `webpack --watch` still seeing deleted files after they're deleted?

**Comment by sokra** [comment]
> Probably, but is it related to `webpack --watch` still seeing deleted files after they're deleted?

Try to reproduce the problem without typescript involved. Only raw JS files.

**Comment by walterqian** [comment]
@dko-slapdash Did you ever figure out how to resolve? Encountering the same issue.
