### ISSUE TITLE
polyfills.js and other non entry files?

### ISSUE THREAD

**Issue by basickarl** [webpack/webpack#9561]
https://webpack.js.org/concepts/entry-points/#separate-app-and-vendor-entries

>  Do not create an entry for vendors or other stuff that is not the starting point of execution.

Now I have to remove vendors from the config file. I have a polyfills.js and a vendor.js file, where am I supposed to add them?

This gets me thinking. Why don't you guys just offer the full webpack.config.js file with the default settings. It would make things so much easier for people to learn how webpack works and for people like me to just edit a few settings. Can one generate the config via the cli?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please use stackoverflow or gitter for questions, it is bug tracker. Also all issues related to docs please open in webpack docs repo. Thanks

**Comment by basickarl** [comment]
@evilebottnawi Your templates don't offer "questions". Questions that can't be answered by the SO community, exactly the reason why I come here to ask questions. Stop pointing at SO. This is YOUR framework. These simple questions such as mine should be answered in the documentation, but they aren't.

**Comment by evilebottnawi** [comment]
> Stop pointing at SO. This is YOUR framework repo. These simple questions such as mine should be answered in the documentation, but they aren't.

Please change the tone otherwise yours you will not get any answer.

Your question is related to the fact that you don’t understand something in the configuration, this sometimes happens, so we have a website for documentation and examples, and that’s why I ask you to create a problem there and not here. 

If we answer in the repository, the answers will be lost so such questions need to be opened in the documentation repository, this will help not only you but other developers.

**Comment by basickarl** [comment]
`It looks like you just deleted our lovely crafted issue template. It was there for good reasons. `, this set the tone. There is no template for questions as I said.

`Your question is related to the fact that you don’t understand something in the configuration`, something we can agree on.

`If we answer in the repository, the answers will be lost so such questions need to be opened in the documentation repository, this will help not only you but other developers.`, this is probably why the documentation should be updated, updated by people who know the answer to this question, so that these questions aren't lost anymore.

Tbh, I'd rather the information just exist in the proper place where myself and anyone can access it instead of having to bug other people.

Anyways I see my "templated" question was moved by you to https://github.com/webpack/webpack.js.org/issues/3244. You should reconsider the templates currently in use, they don't fulfill all scenarios.

**Comment by evilebottnawi** [comment]
@basickarl developers rarely create a problem in the wrong place, so we carry them manually, maybe we change templates in future, now we are working on webpack@5 so it is not high priority
