### ISSUE TITLE
Documentation lacking regarding non starting point of entry files.

### ISSUE THREAD

**Issue by basickarl** [webpack/webpack#9562]
# Bug report

**What is the current behavior?**

Documentation fails to explain how to handle files that are not the starting point of entry as they are not to be included in the entry field in the configuration.

**If the current behavior is a bug, please provide the steps to reproduce.**

1) goto: https://webpack.js.org/concepts/entry-points/#separate-app-and-vendor-entries
2) Read.

**What is the expected behavior?**

That the documentation will explain what will happen to the files that are not starting point of entry.

**Other relevant information:**
webpack version:  4.39.1
Node.js version:  v10.16.0
Operating System:  Linux
Additional tools:

**Comment by evilebottnawi** [comment]
@webpack-bot move to webpack/webpack.js.org
