### ISSUE TITLE
Uncaught ChunkLoadError: Loading chunk 0 failed.

### ISSUE THREAD

**Issue by puru0019** [webpack/webpack#9565]
# Bug report

**What is the current behavior?**

I have created one react library which has the components that are commonly used(Such as button, form elements, input, radio, checkbox, tabs, etc) and following is the webpack config file to it

`const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

const OUTPUT_PATH = path.resolve(__dirname, './dist');

module.exports = {
  context: path.resolve(__dirname, 'src'),
  entry: {
    main: './exports.js',
  },
  output: {
    filename: '[name].bundle.js',
    chunkFilename: '[name].[chunkhash].js',
    library: 'test-react-material',
    libraryTarget: 'umd',
    path: OUTPUT_PATH,
  },
  ......
  ......
  externals: {
    'lodash.isempty': 'lodash.isempty',
    moment: 'moment',
    react: 'react',
    'react-dates': 'react-dates',
    'react-dom': 'react-dom',
    'styled-components': 'styled-components',
  },
};
`

and my package.json file has
`main: dist/main.bundle.js`

My `./export.js` file has all components which are exported as follows 

`export { Button } from './common/button/button';

export { ColumnLayout } from './common/column-layout/column-layout';

export { Column } from './common/column-layout/column';

export { CloseButton } from './common/close-button/close-button';

export const Checkbox = lazy(() => import(/* webpackChunkName: "checkbox" */ './checkbox'));

export const CheckboxGroup = lazy(() => import(/* webpackChunkName: "checkbox-group" */ './checkbox-group'));

export const Autocomplete = lazy(() => import(/* webpackChunkName: "autocomplete" */ './autocomplete'));

.......
.......
......
few other components
......
.....
`
If you can observe few of my components are lazy loading (Inorder to decrease the bundle size I have did this. I am loading the form fields on demand)

Later I have build the code and  published that package into npm

I have build the code in prodcution mode and my dist file looks like

![image](https://user-images.githubusercontent.com/23036485/62879078-f8711900-bd47-11e9-879d-3bd1f61c56e7.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
Later I have installed that npm package into one of my other repository(Inorder to use those components) and started using it.
And got the following error
![image](https://user-images.githubusercontent.com/23036485/62878859-92849180-bd47-11e9-8fc7-da1311106661.png)

**What is the expected behavior?**

I should be able to load the lazy loading file as well

**Other relevant information:**
webpack version:  4.29.3
Node.js version: latest version
Operating System: Windows
Additional tools:

**Comment by evilebottnawi** [comment]
you can see what you have 404 error, so chunk was not loaded

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo

**Comment by sokra** [comment]
See publicPath in docs

**Comment by puru0019** [comment]
> Please create minimum reproducible test repo

I could not share you my actual code but tried to replicate the same with some sample code(I have lazy loaded the Button and Modal component in two separate files in order to reproduce the issues I am facing).Following is the link to repo. You can install the package as `npm install testpro1234@latest`

https://github.com/puru0019/testpro1

I do have one more question. Does package.json supports the multiple entry point. If you can look at my webpack file it has two entries, where as in my package.json `main: main.bundle.js` only supports one entry. How can I use my another entry point code when I building a common library
