### ISSUE TITLE
ModuleConcatenationPlugin force merge

### ISSUE THREAD

**Issue by zh99998** [webpack/webpack#9569]
## Feature request

**What is the expected behavior?**
now ModuleConcatenationPlugin will bailout when module not well contained.
https://webpack.js.org/plugins/module-concatenation-plugin/#optimization-bailouts

I request a new option to set some modules force merge, even it not meet the hoist policy.

**What is motivation or use case for adding/changing the behavior?**

It's will be really useful to handle some old big es5 scripts. like RPG Maker MV or Candy Chat.
there are many script file, its own plugin system in it, and reference each other by global variables.
there is too many global variables to shim them by import-loader or ProvidePlugin.

And, faster execution time in the browser..

**How should this be implemented in your opinion?**
```js
new ModuleConcatenationPlugin({
    forceMerge: ['a', 'b'], // merge these modules to current scope. keep order.
    forceMergeInGroup: [
       ['c','d'],       // merge these modules to a new module scope. keep order.
       ['e','f']        // merge these modules to a another module scope. keep order.
    ]
})
```

**Are you willing to work on this yourself?**
no

**Comment by sokra** [comment]
> even it not meet the hoist policy.

The bailouts are there for good reasons. Which bailout do you want to "override"? Do you have an example?

**Comment by zh99998** [comment]
> The bailouts are there for good reasons. Which bailout do you want to "override"? Do you have an example?

mainly for non-es6 module. 

example 
1. a RPG Maker MV game.

it's es5 project, no module as all. 
by default it loads all scripts in a html entrypoint, like this:

```html
<script src="libs/some_library.js"></script>
<script src="libs/another_library.js"></script>
...
<script src="some_class.js"></script>
...
<script src="main.js"></script>
```

I want to webpack it because
- it could merge all scripts in one request and minify then reduce load time. 
- resources could be hash as filename then I can config aggressive cache strategy.
- do some post-processing, like generate resources index for service workers.

the problem is, it's a es5 project and use global variables to contact each other everywhere
like:
`a.js`
```javascript
global.PIXI = ...
```
`b.js`
```javascript
var PIXI
PIXI.someMethod()
```
`c.js`
```javascript
function SomeClass() {...}
```
`d.js`
```javascript
new SomeClass()
```
hundred of global variables are used and it. all libraries, classes, and game data are global variables. it's really hard to shim it by `import-loader` or `ProvidePlugin`.

example 2.
Candy Chat

it's also a es5 script and use many global variables like before.
but it is a library.
my project is es6 module and I will import only little class from it. it can be done by `export-loader`
so I want to pack them into one separate module group, all candy scripts use global variables will work find and my project part is not dirty.

**Comment by sokra** [comment]
Module concatenation won't help you here. It doesn't change the semantics of the code. It will rename conflicting variables instead of merging them together.

Files that are scripts and don't use any module system need to be adapted to be compatible. i. e. by rewriting them or using some of the shimming loaders.
