### ISSUE TITLE
Error retrieving external webpack source maps for multi-part libraries in Firefox

### ISSUE THREAD

**Issue by pierlon** [webpack/webpack#9570]
# Bug report

**What is the current behavior?**

Enabling source maps for multi-part libraries results in errors such as:

```
Source map error: TypeError: Invalid URL: webpack://MyLibrary.[name]/webpack/bootstrap
Resource URL: http://localhost:8080/dist/alpha.js
Source Map URL: alpha.js.map
```

Example `webpack.config.js`:
```js
var mode = process.env.NODE_ENV || "development";
var devtool = ( mode === "production" ? false : "source-map" );
var path = require("path");

module.exports = {
    devtool,
	mode,
	entry: {
		alpha: "./src/alpha",
		beta: "./src/beta"
    },
    module: {
        rules: [
          {
            test: /\.js$/,
            use: ["source-map-loader"],
            enforce: "pre"
          }
        ]
    },
    output: {
        path: path.join(__dirname, "public/dist"),
        filename: "[name].js",
        library: ["MyLibrary", "[name]"],
        libraryTarget: "this"
    }
};
```

This is similar to #1194, but I think removing `[name]` from the source map output should resolve this issue.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  v5.0.0-alpha.19
Node.js version: v10.16.1
Operating System: Arch Linux

**Comment by sokra** [comment]
Try to set `output.devtoolNamespace` (https://webpack.js.org/configuration/output/#outputdevtoolnamespace) to a constant value not including `[name]`.

**Comment by pierlon** [comment]
Thanks, it worked :ok_hand:.
