### ISSUE TITLE
angular Lazy sub-modules cannot be packaged

### ISSUE THREAD

**Issue by sedll7809** [webpack/webpack#9574]
"webpack": "^4.39.1",
 "webpack-cli": "^3.3.6",
"@angular/animations": "^8.1.2",
    "@angular/cdk": "^8.1.1",
    "@angular/cli": "^8.1.2",
    "@angular/common": "^8.1.2",
    "@angular/compiler": "^8.1.2",
    "@angular/core": "^8.1.2",
    "@angular/forms": "^8.1.2",
    "@angular/platform-browser": "^8.1.2",
    "@angular/platform-browser-dynamic": "^8.1.2",
    "@angular/router": "^8.1.2",
# Bug report
When I upgraded angular to 8.0， I'm on angular  request，change my app.routing.ts ,
from
 " { path: 'dashboard', loadChildren: './dashboard/dashboard.module#DashboardModule'}"
to 
"{ path: 'dashboard', loadChildren: () => import('./dashboard/dashboard.module').then(m => m.DashboardModule)}" ,
But when I change it to this, the packaging can't be broken up.
When I go back to the original, the packaging can be broken up again。
Please tell me, what's wrong with this

![image](https://user-images.githubusercontent.com/41176517/62991465-5c97f800-be82-11e9-9e72-d23fbe8e9d91.png)

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by sedll7809** [comment]
thanks
this is my demo link https://github.com/sedll7809/angular-jrjz2t-kzill

**Comment by sedll7809** [comment]
please help me how to do thanks

**Comment by sokra** [comment]
Seem to be related to usage of `@ngtools/webpack`. Please report an issue there.
