### ISSUE TITLE
4.39.2 cannot have many outputs

### ISSUE THREAD

**Issue by wuhoubing** [webpack/webpack#9576]
<img width="500" alt="first" src="https://user-images.githubusercontent.com/31041022/63009594-62f49700-beb7-11e9-87a4-fba1ae3bfbd5.png">

<img width="851" alt="second" src="https://user-images.githubusercontent.com/31041022/63009640-77d12a80-beb7-11e9-8f19-2258c6b0cb45.png">

two entry but one output

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
