### ISSUE TITLE
Image loader from css file

### ISSUE THREAD

**Issue by grecdev** [webpack/webpack#9577]
When i load the files from `scss` in webpack.dev the filepath is good:

`background: url('../imgs/photo.jpg');`

But after build filepath is:

`background: url('assets/imgs/photo.jpg');`

I don't know why it changes `../` with `assets`.

Main Config:

![image](https://user-images.githubusercontent.com/37197922/63025775-95e85c00-beb2-11e9-945a-ca96eabc4c2b.png)

Development Config:

![image](https://user-images.githubusercontent.com/37197922/63025817-ad274980-beb2-11e9-8324-36f012a655f2.png)

Build / Production Config:

![image](https://user-images.githubusercontent.com/37197922/63025890-d34ce980-beb2-11e9-9418-b71ecf15e37a.png)

And this is my folder structure for development files:

![image](https://user-images.githubusercontent.com/37197922/63025936-ecee3100-beb2-11e9-88a7-669d9fd928f6.png)

And end build files:

![image](https://user-images.githubusercontent.com/37197922/63025978-01322e00-beb3-11e9-97bd-27d6f93ab4ac.png)

As you can see from `style.scss`, the filepath: `../imgs/photo,jpg` works perfectly.
But from the `dist` folder it changes to `assets/imgs/photo.jpg`.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

It is sass limitation https://github.com/webpack-contrib/sass-loader#problems-with-url
