### ISSUE TITLE
chore: Adopt commitlint standards

### ISSUE THREAD

**Issue by jamesgeorge007** [webpack/webpack#9578]
People are insisted to write a good commit message as per the [contributing guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md#submitting-changes). IMO it would be better to adopt the `commitlint` standards which make more sense :thinking: 

> we could trigger the respective check as part of the pre-commit hook

**Comment by jamesgeorge007** [comment]
@sokra thoughts :thinking:

**Comment by sokra** [comment]
I want to make contributing as easy as possible. Having "nice" commit messages puts an extra difficulty on creating PRs and has no real benefit to me.

**Comment by jamesgeorge007** [comment]
So, shall I close this one :thinking:
