### ISSUE TITLE
Configure persistent cache scope in v5

### ISSUE THREAD

**Issue by otakustay** [webpack/webpack#9581]
## Feature request

As I test the effect of persistent cache in webpack v5, it involves some issue when using `DefinePlugin` to inject `process.env`

I tried a entry js like:

```js
import 'lodash';

console.log(process.env.TEST_VALUE);
```

Production mode build cause 240ms the first time, and 50ms when cache is enabled, however **when `process.env.TEST_VALUE` is changed the output still remains the same**.

```shell
TEST_VALUE=123 webpack # cuases 240ms
TEST_VALUE=456 webpack # causes 50ms but outputs 123
```

I can generate `cache.version` depending on `process.env` but this cache version is way too dynamic, also I have something like git revision or timestamp into javascript via `DefinePlugin` so the persistent cache can never hit.

On the other side, I can definitely tell that only src javascript are  affected by those dynamic context, all third party node modules can be cached stably, but I can't find a way to configure persistent cache only on my src scripts.

**What is the expected behavior?**

I'd like to be able to specify only some scripts being persistent cached depending on their path and content.

**What is motivation or use case for adding/changing the behavior?**

This can boost build performance even some of the scripts is depending on dynamic context like process environments, build revisions, timestamps, feature flags, etc....

**How should this be implemented in your opinion?**

Try to add a `Condition` to `cache` configuration like:

```js
{
  cache: {
    test(path, content) {
      return path.includes('node_modules/') || !content.includes('process.env.');
    }
  }
}
```

Both `path` and `content` are required, `content` should be the raw content without any loader or plugin involved.

**Are you willing to work on this yourself?**

possibly not, I'm not familiar with webpack

**Comment by evilebottnawi** [comment]
Thanks for issue and feedback

**Comment by sokra** [comment]
Hmm I see. Thanks for trying the alpha version.

For values coming from outside the config file you have multiple options:

* `cache.name`: Create a separate cache for each value
* `cache.version`: Invalidates the cache when value changes
* If the value is from another module: `cache.buildDependencies`
* And these additional options when it's used with the `DefinePlugin`
  * If the value is from another file: `DefinePlugin.runtimeValue(() => ..., [ "/path/to/file" ])`
  * `DefinePlugin.runtimeValue(() => ..., true)`: Opt-out from caching for modules using this value.

For your cases:

### `TEST_VALUE=123`

If there are multiple constant options for this value: `cache.name`.

If the value changes infrequently: `cache.version`

If the value is always different or changes very often: `DefinePlugin.runtimeValue(() => ..., true)`

### git revision

`DefinePlugin.runtimeValue(() => getRev(), [path.resolve(__dirname, ".git/HEAD"), path.resolve(__dirname, ".git/info/refs")])`

### timestamp

`DefinePlugin.runtimeValue(() => Date.now(), true)`

### feature flags

`cache.name`

---

The complete syntax is:

``` js
new DefinePlugin({
  TEST_VALUE: DefinePlugin.runtimeValue(() => JSON.stringify(process.env.TEST_VALUE), true)
})
```

---

It probably make sense to allow separate cache name or versions per module to make it easier to add dependencies for modules.

I could image the following additions to make it easier to use the persistent cache:

``` js
module.rules: [
  {
    test: ...,
    cache: {
      // This would allow to handle loader options that depend on addition external values
      version: "...",
      name: "..."
    }
  }
]
```

``` js
DefinePlugin.dynamicValue(() => ..., {
  cacheVersion: "...",
  cacheName: "...",
  fileDependencies: [...], // <- that's what's currently provided as second argument
  contextDependencies: [...]
})
```

This would allow config like this:

``` js
const TEST_VALUE = process.env.TEST_VALUE;

module.exports = {
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: "babel-loader",
        options: {
          envName: TEST_VALUE
        },
        cache: {
          name: TEST_VALUE
        }
      }
    ]
  },
  plugins: {
    new webpack.DefinePlugin({
      TEST_VALUE: DefinePlugin.dynamicValue(() => TEST_VALUE, {
        cacheName: TEST_VALUE
      })
    })
  }
}
```

**Comment by evilebottnawi** [comment]
just my two cents, additional cache setup on loaders looks very complex setup, maybe good manual helps better understand this to new developers
