### ISSUE TITLE
Image url from css file

### ISSUE THREAD

**Issue by grecdev** [webpack/webpack#9582]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

When i load the files from `scss` in webpack.dev the filepath is good:

`background: url('../imgs/photo.jpg');`

But after build filepath is:

`background: url('assets/imgs/photo.jpg');`

I don't know why it changes `../` with `assets`.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

after `npm run build` the url image from `css` should be same as in `scss `file

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Node.js version: `v10.16.0`,
Webpack version: `4.36.1`,
OS: `Windows 10`

Main Config:

![image](https://user-images.githubusercontent.com/37197922/63080802-b663f500-bf4a-11e9-8296-a33795b07636.png)

Development Config:

![image](https://user-images.githubusercontent.com/37197922/63080836-cda2e280-bf4a-11e9-8cee-bde7be93bbac.png)

Build / Production Config:

![image](https://user-images.githubusercontent.com/37197922/63080858-d98ea480-bf4a-11e9-8321-6ed43de79d97.png)

And this is my folder structure for development files:

![image](https://user-images.githubusercontent.com/37197922/63080880-e27f7600-bf4a-11e9-9c93-e75ef0ea9c1d.png)

And end build files:

![image](https://user-images.githubusercontent.com/37197922/63080904-ef03ce80-bf4a-11e9-8296-c63cca0a599f.png)

As you can see from style.scss, the filepath: `../imgs/photo,jpg works perfectly`.
But from the dist folder it changes to `assets/imgs/photo.jpg`.

And after i tried with `resolve-url-loader` it gives me this error after build:

config with `resolve-url-loader`:

![image](https://user-images.githubusercontent.com/37197922/63081295-f081c680-bf4b-11e9-869e-60f0616d798c.png)

![image](https://user-images.githubusercontent.com/37197922/63081242-ce884400-bf4b-11e9-8702-ce858cabddd7.png)

![image](https://user-images.githubusercontent.com/37197922/63081262-d8aa4280-bf4b-11e9-964b-048a57e111e3.png)

**Comment by grecdev** [comment]
Ok so i figured out how to make the 'url' from 'css' file be the same as 'url from 'scss' file:

I removed 'resolve-url-loader'.

In Build / Production Config:

![image](https://user-images.githubusercontent.com/37197922/63089909-2fbb1200-bf62-11e9-96eb-8bca6731d0ed.png)

But now the problem is that the images that i use in css files doesn't copy in the 'dist/assets/imgs' folder and if i use `copy-webpack-plugin` i will copy all files included the ones in `html` file from `img src=""` and i will have duplicates so that's another problem. 😢

**Comment by evilebottnawi** [comment]
Because copy-webpack-plugin copy only assets exist on disk, file-loader copy emit images which used in `require`/`import`, please read docs and use stackoverflow and gitter for questions
