### ISSUE TITLE
memory-fs deprecationWarning in webpack v4 

### ISSUE THREAD

**Issue by BengBu-YueZhang** [webpack/webpack#9586]
# Bug report

when I use webpack v4 in this way:

```
const serverCompiler = webpack(serverConfig)
const MFS = require('memory-fs')
const mfs = new MFS()
serverCompiler.outputFileSystem = mfs
```

**What is the current behavior?**

show the warning below:

`DeprecationWarning: Tapable.plugin is deprecated. Use new API on .hooks instead`

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  4.39.2
Node.js version: 11.2.0
Operating System:  macOS Mojave 10.14.6 
Additional tools:

**Comment by sokra** [comment]
Could you run with `node --trace-deprecation` to get the stack trace?

**Comment by BengBu-YueZhang** [comment]
> Could you run with `node --trace-deprecation` to get the stack trace?

This error does not affect the use. Thank you
