### ISSUE TITLE
webpack@5.0.0-alpha.20 & webpack-cli - TypeError: Cannot read property 'length' of undefined #1023

### ISSUE THREAD

**Issue by ryanspice** [webpack/webpack#9591]
# Bug report

When using webpack-cli with the latest version of webpack i get the following issue: https://github.com/webpack/webpack-cli/issues/102

Seems it seems like validateschemea.js on webpack@5.0.0-alpha.20 doesnt have a return which is causing the issue, not sure if that is expected? 

Fixing in my node modules aloud for a compile. 

**What is the current behavior?**

Fails to compile with specified config file. 
We see webpackConfigurationValidationErrors is returning undefined.

**If the current behavior is a bug, please provide the steps to reproduce.**

New webpack@5.0.0-alpha.20, webpack-cli latest, run with empty webpack.config. 

**Other relevant information:**
webpack version:  webpack@5.0.0-alpha.20
webpack-cli version:  webpack@5.0.0-alpha.20
Node.js version: 3.3.7
Operating System: windows 10 bash

**Comment by sokra** [comment]
see https://github.com/webpack/webpack-cli/issues/1023
