### ISSUE TITLE
How to debug a randomly failing webpack build?

### ISSUE THREAD

**Issue by bitttttten** [webpack/webpack#9596]
My webpack build randomly fails (about 5% of the time) on our circleci server. Are there any flags or commands to help with debugging? I am guessing it is one of the loaders that fails and the error is being swallowed somewhere, or it's a race condition somewhere.

I am using a forked version of create-react-app with only a few minor changes of using emotionjs, loadable components, and added an mdx-loader. It emits "Ready to start the build.", which is common for CRA, to "Exiting.. Done in 31.66s.", finishing without outputting any files or even logging out the gzip differences.

```sh
#!/bin/bash -eo pipefail
yarn build
yarn run v1.17.3
$ node ./scripts/build_client.js
Ready to start the build.

Creating an optimized production build...

Exiting..
Done in 31.66s.
```

Where with a successful build it logs:

```sh
#!/bin/bash -eo pipefail
yarn build
yarn run v1.17.3
$ node ./scripts/build_client.js
Ready to start the build.

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  119.8 KB  client/static/js/3.edae8e4c.chunk.js
  62.64 KB  client/static/js/0.8dde5d85.chunk.js

The build/client folder is ready to be deployed.

Find out more about deployment here:

  https://bit.ly/CRA-deploy
 
Exiting..
Done in 37.50s.
```

The [full webpack config file is here](https://hastebin.com/ujicasenof.js).

**Comment by evilebottnawi** [comment]
Please use issue template and provide minimum reproducible test repo otherwise issue was closed, thanks

**Comment by bitttttten** [comment]
Understandable.

My problem is that it is not reproducible. When I select "Rebuild" on circleci after the build has failed, it may succeed. I appreciate that this issue looks more like a question than an issue.

**Comment by sokra** [comment]
Try to run with `--progress --profile`. Maybe this gives more information

**Comment by bitttttten** [comment]
It was an issue with `fork-ts-checker-webpack-plugin`. I don't know what the issue was, but at the emitting stage, it was `fork-ts-checker-webpack-plugin`'s turn and it would skip from 95% to exiting. Removing this plugin let the build complete.

Strange how locally I had no ts issues or even in linting. However, the problem lies in a plugin and not webpack.

Thanks for the tip!
