### ISSUE TITLE
output.publicPath ignored when module.exports = [{}, {}];

### ISSUE THREAD

**Issue by xpepermint** [webpack/webpack#960]
Example here https://github.com/webpack/webpack/tree/master/examples/i18n, when using webpack-dev-server. 
Also when adding the `SaveAssetsJson` plugin, only the last `locale` in array would write a manifest file.

**Comment by p0wl** [comment]
any updates on this? stops us from using multiple compilers (which we really want to use).

**Comment by sokra** [comment]
You need to use different filenames for every compilation.

**Comment by SpaceK33z** [comment]
This is related to https://github.com/webpack/webpack-dev-server/issues/641, so I'm closing this.
