### ISSUE TITLE
use prettier format md file before commit

### ISSUE THREAD

**Issue by shaodahong** [webpack/webpack#9606]
## Feature request

**What is the expected behavior?**
same formatted code

**What is motivation or use case for adding/changing the behavior?**
when I formating, some previous code is modified

**How should this be implemented in your opinion?**
`yarn pretty` unused, maybe in `lint-staged` with `prettier` help we format like `.md` file, I try it, it's good for the project

**Are you willing to work on this yourself?**
yes

**Comment by evilebottnawi** [comment]
@shaodahong please use issue template in future, thanks

**Comment by shaodahong** [comment]
@evilebottnawi ok
