### ISSUE TITLE
Allow polling for webpack to work over nfs for docker

### ISSUE THREAD

**Issue by yenif** [webpack/webpack#961]
Use webpack/watchpack#5 and setup a place in configuration to configure options to pass to watchpack which can include chokidar options to enable polling among other things.

Required to get webpack development working in docker when using nfs mounts or any other time inotify/fsevents aren't available.

**Comment by alexeits** [comment]
+1

**Comment by p0wl** [comment]
:+1:

this is also needed when using vagrant with nfs.

**Comment by sokra** [comment]
done
