### ISSUE TITLE
ChunkLoadError should give access to the source error

### ISSUE THREAD

**Issue by damiengarbarino** [webpack/webpack#9611]
## Feature request

**What is the expected behavior?**

Currently when a chunk fails to load we get from Webpack a ChunkLoadError instance.
We would need to access the source error to change the behavior of the application.

**What is motivation or use case for adding/changing the behavior?**

For example, when we deploy a new version of the application, the chunks will have different names. If a user, currently loggued, try to load a chunk, the chunk won't be available anymore and the server returns a 404.
So we want to handle the error differently if that case than any other network issue.

**How should this be implemented in your opinion?**
The ChunkLoadError can have a source property with the source error in it.

**Are you willing to work on this yourself?**
yes, if I have some indications on where this code is etc.

**Comment by sokra** [comment]
Here is the code:

https://github.com/webpack/webpack/blob/9b02c19c8a34df7022052453ec91e1429f1f6d97/lib/web/JsonpMainTemplatePlugin.js#L178-L206

Not sure if we have more information available

**Comment by damiengarbarino** [comment]
Thanks I understand now how it works.

This is using a script tag with the generic error handler. According to the spec, we do not have enough information on the error for 404s... This is not a XHR / fetch request...
