### ISSUE TITLE
Named Harmony imports are wrapped in Object(), while namespace imports are not

### ISSUE THREAD

**Issue by MLoughry** [webpack/webpack#9615]
# Bug report

**What is the current behavior?**

When using a named import (eg., `import { foo } from './bar';`), references to that import are wrapped in an Object constructor (`Object(r.foo)(parameter)`). This behavior doesn't take place for namespace imports (`import * as bar from './bar';` -> `bar.foo(paramater)`)

**If the current behavior is a bug, please provide the steps to reproduce.**

```
// harmony.js
export function add(a,b) {
    return a + b;
}

// index.namespace.js
import * as math from './harmony';

console.log(math.add(1,1));

// index.named.js
import {add} from './harmony';

console.log(add(1,1));
```

**What is the expected behavior?**
My expectation is that the wrapping `Object()` constructor is not needed in either case; at the very least, I'm unsure why it would be used in one case but not the other. 

The code in question is in [ConcatenatedModule.js](https://github.com/webpack/webpack/blob/f70933718a3ce7006413fa767d979542523ec873/lib/optimize/ConcatenatedModule.js#L112). I couldn't find any documentation, comments, or useful commit messages explaining the reason for the wrapper.

I came across this issue when upgrading our codebase from Typescript 3.5 to 3.6. Once change there was that all `tslib` imports were changed from namespace imports to named imports, presumably to enable tree-shaking. However, that change combined with this behavior means our bundle sizes increased by ~0.5%, which set off alarm bells.

**Other relevant information:**
webpack version:  4.31.0
Node.js version: 12.4.0
Operating System: Windows 10
Additional tools:

**Comment by sokra** [comment]
> Once change there was that all `tslib` imports were changed from namespace imports to named imports, presumably to enable tree-shaking.

Namespace objects are also tree-shaken. This change is not needed.

> My expectation is that the wrapping `Object()` constructor is not needed in either case

It is needed in same cases.

The difference between `math.add(1,1)` and `add(1,1)` is the value of `this` in the `add` function. In the first case it's `this === math`, in the second case it's `this === undefined` (strict mode) resp. `this === global` (non-strict mode). While nobody depends on the first case where `this === math`, there are cases where it's important that `this === undefined`. Consider this example:

``` js
// module.js
const sT = setTimeout;
export { st as setTimeout };

// entry.js
import { setTimeout } from "./module";

setTimeout(() => {}, 100);
```

The generated code for entry.js looks like:

``` js
Object(module.setTimeout)(() => {}, 100);
```

Which works fine. When omitting the `Object()` it would look like:

``` js
module.setTimeout(() => {}, 100);
```

Which results in `Uncaught TypeError: Illegal invocation` as you must not call `setTimeout` with a `this` context.

**Comment by MLoughry** [comment]
It sounds like a fairly rare corner case (exporting native methods). Is there a way to opt out of this? All of these wrappers are adding >40kB (or ~2%) of size to our boot bundle, and easily approaching 1MB to our entire app (Outlook Web)

**Comment by sokra** [comment]
It's not that rare

* https://github.com/webpack/webpack/issues/5111
* https://github.com/webpack/webpack/issues/5135

But I'm also a bit annoyed by this overhead and would like to enhanced the analysed information about exports to track if an function is using `this` in its body. I think this could eliminate 80% of the cases where `Object()` is needed.

**Comment by fatcerberus** [comment]
Is there a reason for `Object(module.fn)()` versus, say, `(0,module.fn)()`?  The latter is more compact and seems like it might be easier for the JS engine to optimize too as it's also a common pattern for e.g. triggering indirect `eval`.

**Comment by sokra** [comment]
`Object(module.fn)()` is ASI-safe, while `(0,module.fn)()` is not, but you are right this could be improved.

PR #9622 checks whether it's an ASI position and uses shorter construct when possible. This should only generate `Object()` when you are omitting semicolons in the source code, which nobody should do anyway...
