### ISSUE TITLE
__webpack_nonce__ is not working

### ISSUE THREAD

**Issue by eeronen** [webpack/webpack#9619]
# Bug report

**What is the current behavior?**
After adding `__webpack_nonce__ = "foobar";` in my `main.js` (the entry file) the resulting index.html does not contain nonce in the script tag.

I'm not sure if I'm meant to do some additional config on top of that, but this is all that [the documentation](https://webpack.js.org/guides/csp/) tells me to do so I assume this is a bug.

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a new minimal project with this kind of config:
```
const path = require("path");

module.exports = {
  entry: "./src/index.js",
  output: {
    filename: "main.js",
    path: path.resolve(__dirname, "dist")
  },
};
```
and in the index.js:
```
__webpack_nonce__ = "foobar";

function component() {
  const element = document.createElement("div");
  element.innerHTML = "Hello from JS";
  return element;
}

document.body.appendChild(component());
```

**What is the expected behavior?**
I expected to find `<script type="text/javascript" nonce="foobar" src="main.js">` from the resulting `dist/index.html` but found only `<script type="text/javascript" src="main.js">`. Using `__webpack_nonce__` doesn't seem to be doing anything.

**Other relevant information:**
webpack version:  4.39.2
Node.js version: 10.15.3
Operating System: Windows 10
Additional tools: -

**Comment by sokra** [comment]
`__webpack_nonce__` only affects on-demand-loaded script tags. You need to add `nouce` when generating the HTML.

**Comment by eeronen** [comment]
By "when generating the HTML" do you mean when the `index.html` is sent out from the server?

We currently are using just CopyWebpackPlugin to create `index.html` and the copied html file contains `<script src="main.js" nonce="<%= nonce %>"></script>`. The problem is that now we would want to split the code into chunks, and to avoid hard coding the chunk names it would be nice to use something like HTMLWebpackPlugin to create the `index.html`.

We could of course use some hooks to insert the nonces, but I got the impression from the docs that webpack could handle it quite easily out of the box.

**Comment by evilebottnawi** [comment]
I think it is related to HtmlWebpackPlugin

**Comment by vaaralav** [comment]
I had the same problem @eeronen described where I'd want to use Webpack generated `index.html` as a view template where the nonces are added per request to apply with Content-Security Policy. Didn't figure out a way to make it happen with `__webpack_nonce__`, but I was able to solve the problem with `script-ext-html-webpack-plugin` and a configuration like this:

webpack.config.js
```javascript
const HtmlWebpackPlugin = require("html-webpack-plugin");
const ScriptExtHtmlWebpackPlugin = require("script-ext-html-webpack-plugin");

module.exports = {
  plugins: [
    new HtmlWebpackPlugin(),
    new ScriptExtHtmlWebpackPlugin({
      custom: {
        test: /\.js$/,
        attribute: "nonce",
        value: "{{ cspNonce }}"
      }
    })
  ]
};

```
dist/index.html
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Webpack App</title>
  </head>
  <body>
  <script type="text/javascript" src="main.js" nonce="{{ cspNonce }}"></script></body>
</html>
```

**Comment by savolkov** [comment]
@vaaralav 

> but I was able to solve the problem with `script-ext-html-webpack-plugin`

This plugin is not compatible with webpack v5. Did you migrate to webpack 5 yourself? Do you have any workarounds or tips?

**Comment by vaaralav** [comment]
@savolkov, it's been a while and I was only working with Webpack 4 back then. Unfortunately I can't help you with Webpack 5.

**Comment by savolkov** [comment]
@vaaralav thanks for your reply!
