### ISSUE TITLE
Allow suppression of certain errors when running dev-server

### ISSUE THREAD

**Issue by natew** [webpack/webpack#962]
With [reapp](https://github.com/reapp), I ship a CLI that runs a dev-server for end users, but becuase I do dynamic requires in the core library, people are constantly opening tickets asking if it's broken due to the warning. If there was a way to access the output or rebuild it that I don't know of that would be perfect. Or, adding options to not show warnings.

**Comment by sokra** [comment]
Which line is causing the warning?

**Comment by natew** [comment]
This: https://github.com/reapp/hacker-news-app/blob/aff6e515b1a8175182588c386cf5007e4b68c962/app/app.js#L7

The dynamic require puts out a warning that looks very scary to a lot of users, it's bold and yellow and says "Critical" in it and takes up three lines:

```
WARNING in ./app/app.js
Critical dependencies:
15:21-28 require function is used in a way, in which dependencies cannot be statically extracted
 @ ./app/app.js 15:21-28
```

**Comment by NekR** [comment]
This warning also annoys me, it's not scary but it take places of almost all console window and in watch it's pretty uncomfortable because of it I cannot see errors from other modules. Can we have option to disable warnings at all or filter them? It would be good to have ```.setJson()``` or ```.setWarnings()``` to be update to set them back once ```.toJson()``` is called and warnings filtered.

**Comment by NekR** [comment]
Okay, just found a way:

```javascript
var webpackLog = function(err, stats) {
  if (err) throw new gutil.PluginError('webpack', err);

  // Get json of stats and prepare it for toString by setting second parameter
  // to |true|, so it will color entires as per stats.toString
  var jsonStats = stats.toJson(null, true);
  var toString = stats.constructor.jsonToString;
  jsonStats.warnings = [];

  gutil.log('[webpack]', toString(jsonStats, true));
};
```

But could Stats be exported directly to ```webpack``` module? And it would be good to document this thing..

**Comment by sokra** [comment]
The warning has a good reason.

If you want to create the context intentionally, you can use the `require.context` function:

``` js
router(require.context(".", true, /^\.\/.*$/),
  route('articles', '/',
    route('article', '/article/:id'),
    route('user', '/user/:id')
  )
);
```

**Comment by niftylettuce** [comment]
Thanks!

**Comment by niftylettuce** [comment]
@sokra how else should it be written?  (e.g. without `require.context`?)

**Comment by niftylettuce** [comment]
https://github.com/reapp/reapp/issues/64#issuecomment-148937610

**Comment by bebraw** [comment]
@natew Safe to close?
