### ISSUE TITLE
Removing an entrypoint by SplitChunksPlugin leads to mini-css-extract-plugin error

### ISSUE THREAD

**Issue by tardiva** [webpack/webpack#9621]
# Bug report

**What is the current behavior?**

After migration from webpack 3 + extract-text-webpack-plugin to webpack 4 + mini-css-extract-plugin we encountered the same problem in several of our projects - we found that it has already been described for mini-css-extract-plugin -  https://github.com/webpack-contrib/mini-css-extract-plugin/issues/341. 
We investigated this issue and found that the error occurs because of removing an entrypoint by SplitChunksPlugin while splitting a chunk. We tried to fix the problem with the plugin, but this did not help much, because although the CSS file was extracted correctly, neither it nor the js files were included in the HTML. Seems that html-webpack-plugin ignores these files because of the same reason - empty `compilation.entrypoints`.

**If the current behavior is a bug, please provide the steps to reproduce.**

example for reproducing - https://github.com/tardiva/webpack-example

Steps to reproduce: 

- try to execute `npm run build` on master to see mini-css-extract-plugin error
- then checkout html-webpack-plugin-issue branch
- execute `npm i` (to use changed version of mini-css-extract-plugin without producing an error)
- execute `npm run build` and note that resulting index.html does not include any css or js files

**What is the expected behavior?**

There is an issue  [#7230](https://github.com/webpack/webpack/issues/7230) about the problem similar to ours and PRs but they were not merged. 
Could someone please explain - what is the goal of this behavior and how important is to leave it as is?

https://github.com/webpack/webpack/blob/9dc49cf18bb87d167f7f915f69632d4cfdc41e94/lib/optimize/SplitChunksPlugin.js#L761-L765

What should we do in this situation? 
- Is such a configuration wrong and should we change it? Everything works well if we use name 'styles' (for example) for our css, not 'index', in example above.
 - Is it a plugin's problem and should be fixed for these two plugins?
 - Or is it a bug of SplitChunksPlugin?

**Other relevant information:**
webpack version:  4.39.2
Node.js version: 10.15.1
Operating System: macOS High Sierra 10.13.6
Additional tools: mini-css-extract-plugin 0.8.0, html-webpack-plugin 4.0.0-beta.5

**Comment by sokra** [comment]
splitChunks should not have the same name as an entrypoint. webpack 5 will even display an error in this case. In webpack 4 when splitChunks selects an existing entrypoint with its name, this entrypoint is no longer an entrypoint but converted to an normal async chunk

**Comment by tardiva** [comment]
Thanks for the explanation!

**Comment by goganchic** [comment]
@sokra would you please explain your point a bit more? It's a pity but for me it still unclear after exploring code and look at related issues. Why it's required to remove entrypoint from the entrypoints list if there is a chunks group with the same name?

**Comment by goganchic** [comment]
If I'm not mistaken this situation can be explained in such a way. Each `cacheGroup` creates a separate chunk (or reuse existing). If `cacheGroup` name is defined it's used as a name of new chunk. If some entrypoint already has such name it will be used as a chunk for `cacheGroup`, but SplitChunksPlugin wants all its chunks to be regular async chunks and entrypoint is not an async chunk because it is loaded synchronously. That is why SplitChunksPlugin removes entrypoint.

But I still don't understand why SplitChunksPlugin wants all its chunks to be regular async chunks.

@sokra whould you please approve or disapprove my assumption and give some more details?
