### ISSUE TITLE
[Question] how to remove '~' from file name ?

### ISSUE THREAD

**Issue by yspanchal** [webpack/webpack#9626]
Following is my webpack 4 config,

optimization: {
    runtimeChunk: 'single',
    splitChunks: {
        minSize: 400000,
        maxSize: 400000,
        cacheGroups: {
            vendor: {
                test: /[\\/]node_modules[\\/]/,
                name: 'vendors',
                enforce: true,
                chunks: 'all'
            }
        }
    }
  },
  entry: {
    MyJs: ['./frontend/src/MyJs.js'],
  },
  output: {
    filename: '[name].[id].bundle.js',
    path: '/home/xyz/static/'
  }

After compilation it generates following files,

vendors\~2a42e354.2.bundle.js
vendors\~9c5b28f6.4.bundle.js
vendors\~f9ca8911.5.bundle.js
vendors\~678f84af.3.bundle.js
MyJs\~c5b24172.0.bundle.js

How can i remove "~" and hash from filename ?

Final output:

vendors.2.bundle.js
vendors.4.bundle.js
vendors.5.bundle.js
vendors.3.bundle.js
MyJs.0.bundle.js

**Comment by sokra** [comment]
https://webpack.js.org/plugins/split-chunks-plugin/#splitchunksautomaticnamedelimiter

**Comment by yspanchal** [comment]
@sokra i want to remove '~2a42e354' from js file vendors~2a42e354.2.bundle.js so my final output would be vendors.2.bundle.js
