### ISSUE TITLE
Ability to keep static imports

### ISSUE THREAD

**Issue by unlight** [webpack/webpack#9627]
## Feature request
Allow keep some static imports, at the top level.
Right now we can disable harmony option in parser and keep all static imports, but they will stays in IIFE

**What is the expected behavior?**
```
import /* webpackIgnore: true */ { h } from '//unpkg.com/h-document-element?module';
```
1. Do not produce error
2. Must be on the top level in the bundle

**What is motivation or use case for adding/changing the behavior?**
Ability to generate esm library.
Browsers support 86.05% (26 Aug 2019) https://caniuse.com/#feat=es6-module

**How should this be implemented in your opinion?**
By insert special webpack comment (similar to dynamic import)
`webpackIgnore: true` or `webpackKeep: true`

**Comment by JohanSchobben** [comment]
It would be nice to have this feature for all ways to import modules.

`import defaultExport from "module-name";
import * as name from "module-name";
import { export1 } from "module-name";
import { export1 as alias1 } from "module-name";
import { export1 , export2 } from "module-name";
import { foo , bar } from "module-name/path/to/specific/un-exported/file";
import { export1 , export2 as alias2 , [...] } from "module-name";
import defaultExport, { export1 [ , [...] ] } from "module-name";
import defaultExport, * as name from "module-name";
import "module-name";`

**Comment by sokra** [comment]
This is planned, but not in the way you proposed. It won't be based on syntax, but instead use the existing `externals` feature.

Maybe like this:

``` js
externals: {
  "module-name": "module module-name"
}
```

or


``` js
output: {
  libraryTarget: "module"
},
externals: ["module-name"]
```

This would probably always result in `import * as __WEBPACK_EXTERNAL_MODULE_123__ from "module-name"` being generated, as it doesn't make a difference anyway.
