### ISSUE TITLE
Webpack how to ignore missing chunks at runtime

### ISSUE THREAD

**Issue by anbaran** [webpack/webpack#9628]
I have a question how to achieve to following using Webpack 4:

I have a web app  which I bundle using the Webpack (using it only for bundling and generating chunks)

Let's say after bundling I have the following output: 
`main.bundle.js`, 
`feature1.module.js`, 
`feature2.module.js`

On the html page (using a different tool) I include then: 
`main.bundle.js`, 
`feature1.module.js`, 
`feature2.module.js`

In this scenario it all works ok

However as my system is runtime configurable I also have a situation where on the html page only the following is included:
`main.bundle.js`, 
`feature1.module.js`, 

i.e. `feature2.module.js` is not included (because server app having this feature is not running).

When I run the app now, Webpack during runtime initialization does not complete but quit without any message, to be exact:
```javascript	
 	function checkDeferredModules() {
 		var result;
 		for(var i = 0; i < deferredModules.length; i++) {
 			var deferredModule = deferredModules[i];
 			var fulfilled = true;
 			for(var j = 1; j < deferredModule.length; j++) {
 				var depId = deferredModule[j];
				if(installedChunks[depId] !== 0) fulfilled = false;
 			}
 			if(fulfilled) {
 				deferredModules.splice(i--, 1);
				result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
 			}
 		}

 		return result;
 	}
```

The variable fullfilled is `false` and so the content of `main.module.js` is not loaded. 

When I "manually" set the variable `fulfilled` to `true` to tell Webpack something like: _ignore missing chunks because server app with this feature is not running and user will not have a access to features from `feature2.module.js`_

The above scenario worked without problems with Webpack 3

Is there any better way to say Webpack 4 to ignore missing chunks and continue with loading the app?

**Comment by evilebottnawi** [comment]
Please use issue template otherwise issue will be closed

**Comment by anbaran** [comment]
ok, although I explicitly used "other issue" where no template is available, any way I created [https://github.com/webpack/webpack/issues/9629](url)
