### ISSUE TITLE
Webpack: ignore missing chunks at runtime initialization

### ISSUE THREAD

**Issue by anbaran** [webpack/webpack#9629]
# Bug report

**What is the current behavior?**
I have a web app  which I bundle using the Webpack (using it only for bundling and generating chunks)

Let's say after bundling I have the following output: 
`main.bundle.js`, 
`feature1.module.js`, 
`feature2.module.js`

On the html page (using a different tool) I include then: 
`main.bundle.js`, 
`feature1.module.js`, 
`feature2.module.js`

In this scenario it all works ok

However as my system is runtime configurable I also have a situation where on the html page only the following is included:
`main.bundle.js`, 
`feature1.module.js`, 

i.e. `feature2.module.js` is not included (because server app having this feature is not running).

When I run the app now, Webpack during runtime initialization does not complete but quit silently without any message, to be exact:

```javascript	
 	function checkDeferredModules() {
 		var result;
 		for(var i = 0; i < deferredModules.length; i++) {
 			var deferredModule = deferredModules[i];
 			var fulfilled = true;
 			for(var j = 1; j < deferredModule.length; j++) {
 				var depId = deferredModule[j];
				if(installedChunks[depId] !== 0) fulfilled = false;
 			}
 			if(fulfilled) {
 				deferredModules.splice(i--, 1);
				result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
 			}
 		}

 		return result;
 	}
```

The variable fullfilled is `false` and so the content of `main.module.js` is not loaded. 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
When I "manually" set the variable `fulfilled` to `true` to tell Webpack something like: _ignore missing chunks because server app with this feature is not running and user will not have a access to features from `feature2.module.js`_

The above scenario worked without problems with Webpack 3

Is there any better way to say Webpack 4 to ignore missing chunks and continue with loading the app?

**Other relevant information:**
webpack version:  4.35.3
Node.js version: 10.14.0

**Comment by sokra** [comment]
Use multiple entry points for each feature with `optimization.runtimeChunk: true` instead.

**Comment by anbaran** [comment]
@sokra, Thank you for your answer. It looks like something I need, every chunk is then a module, if not present, the main one can start anyway.

However, with my config like the below:
`
   
    entry: {
        main: 'main.js',
        common: 'common.js',
        feature1: 'feature1.js',
        feature2: 'feature2.js',
    },
    output: {
        filename: '[name].module.js',
        path: './dist'
    },
    optimization: {
        minimize: false,
        splitChunks: {
            cacheGroups: {
                vendor: {
                    test: /[\\/]node_modules[\\/]/,
                    name: "vendor",
                    chunks: "initial",
                    enforce: true
                },
            }
        }`

the output is : 
`main.module.js,`  <- contains content of `common.module.js`
`common.module.js`, 
`feature1.module.js` ,  <- contains content of `common.module.js`
`feature2.module.js`  <- contains content of `common.module.js`

The generated bundles contain runtime chunk inside (OK) but main, feature1 and feature2 contain common.module.js instead of reference common.module.

 I tried manually separate `common.js` from other modules using:
```

optimization: {
    splitChunks: {
        cacheGroups: {
            common: {
                test: /common/,
                name: 'common',
                chunks:'initial',
                enforce:  true
            }
        }
    }
}
```

but then such separated chunks does not contain runtime. The question is:

1. why webpack does not split my files but instead put `common.js` in each file
OR
2.  why no runtime is generated when I manually create chunk

**Comment by sokra** [comment]
Omit the `common` entry point. splitChunks will automatically create such a chunk when needed.

``` diff
 entry: {
     main: 'main.js',
-    common: 'common.js',
     feature1: 'feature1.js',
     feature2: 'feature2.js',
 },
```

``` js
optimization: {
  runtimeChunk: "single", // <- allows all entrypoints to share module instances
  splitChunks: {
    chunks: "all" // <- allows to apply the defaults to initial chunks
    // you don't need manual cacheGroups
  }
}
```

**Comment by anbaran** [comment]
@sokra, thank you again for your answer. Unfortunately this is not yet what I need as in this solution there is only one runtime module (so all chunks must be there during load) and also I don't have control where which functionality is packed in. 

I will try to summarize/simplify the requirements and put a small config sample of what I am doing so far:

* multiple entry points (`main.js, feature1.js, feature2.js`)

* output the same files as entries (`main.module.js, feature1.module.js, feature2.module.js`), bundled and without duplication (every module contains only his own code and reference to other module if it uses features from other module (i.e. entry point) )

* it should be possible to load the main module even if some others are missing (missing but without dependency) for example: consider `main.js, feature1.js, feature2.js` and `feature2.js` depends only on `main.js` , so it is ok if `feature2.js` missing on `main.js` loading. It means `feature2.js` is not accessible in the UI anyway so no need to be present during load.

Can you think of a configuration that would satisfy the above needs? It used to work in webpack 3 by default but I cannot get it to run with webpack 4. Below I put what I have tried so far to solve it:

```
module.exports = {
    entry: {
        main: './src/main.ts',
        feature1: './src/feature1.js',
        feature2: './src/feature2.js',
    },

    output: {
        filename: '[name].module.js',
        path: 'dist/'
    },

      // loaders and plugins omitted

    optimization: {
        splitChunks: {
            cacheGroups: {
                vendor: {                                     <-- vendor splitting, everything ok
                    test: /[\\/]node_modules[\\/]/,
                    name: "vendor",
                    chunks: "all",
                    enforce: true
                },
              feature1: {         <-- splitting code of feature1 to be only in feature1.module.js
                    test: /feature1/,
                    name: "feature1",
                    chunks: "all",
                    enforce: true
                },
             feature2: {       <-- splitting code of feature2 to be only in feature2.module.js 
                    test: /feature2/,
                    name: "feature2",
                    chunks: "all",
                    enforce: true
                },
            }
        }
    }
}
```
With the above configuration modules are correctly splited, without duplication but all of them must be present when html page is loading ( there is only one runtime in main.module.js)

When I remove manual cache groups there is a runtime module for every entry point (i.e. not all of them must be present when html page is loading) but code is duplicated in the modules, `main.module.js` contains `feature1.module.js` and `feature2.module.js`

Background info: It is multi-module Angular 8 app (without using the Angular-CLI) with java microservices on the server side

**Comment by sokra** [comment]
It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by anbaran** [comment]
@sokra , I created small reproducible example, you can find it here: [webpack-splitting-angular](https://github.com/anbaran/webpack-splitting-angular)

**Comment by sokra** [comment]
Here is my proposal:

``` js
module.exports = {
    mode: 'production',
    entry: {
        main: pathUtil.join(__dirname, "./src/main.ts"),
        feature1: pathUtil.join(__dirname, "./src/feature1/feature1.module.ts"),
        feature2: pathUtil.join(__dirname, "./src/feature2/feature2.module.ts"),
    },
    output: {
        filename: '[name].bundle.js',
        path: pathUtil.join(__dirname, "dist")
    },
    module: {
        rules: [
            {
                test: /\.ts?$/,
                use: [{loader: 'ts-loader', options: {configFile: pathUtil.join(__dirname, "tsconfig.json")}}, {loader: 'angular2-template-loader'}]
            },
            {
                test: /\.html$/,
                use: 'raw-loader',
            }
        ]
    },
    resolve: {
        extensions: ['.ts', '.js']
    },
    optimization: {
        runtimeChunk: 'single', // important
        splitChunks: {
            chunks: "all",
            name: false, // optional, gives no names to automatic chunks (better for caching)
            maxInitialRequests: 20, // optional, allows more files per entrypoint
            maxAsyncRequests: 20, // optional
            cacheGroups: {
                // optional, if you want to enforce common-ui into a separate file
                // by default it would only be put into a separate file if > 30kb
                // I would recommend omitting this and stay with the defaults
                'common-ui': {
                    test: pathUtil.join(__dirname, "./src/common-ui"),
                    name: 'common-ui',
                    enforce: true
                },
            }
        }

    }

};
```

(It was a bit unclear how common-ui should work here. I assumed it is used only for some features. If you should be treated like a feature, remove that stuff. If it should be always active, add it to main.)

which results in:

``` text
              Asset      Size   Chunks                    Chunk Names
        2.bundle.js   344 KiB        2  [emitted]  [big]
        6.bundle.js   627 KiB        6  [emitted]  [big]
common-ui.bundle.js  1.99 KiB        0  [emitted]         common-ui
 feature1.bundle.js  1.59 KiB        3  [emitted]         feature1
 feature2.bundle.js  1.59 KiB        4  [emitted]         feature2
     main.bundle.js  4.37 KiB  5, 3, 4  [emitted]         main
  runtime.bundle.js  1.42 KiB        1  [emitted]         runtime
Entrypoint main [big] = runtime.bundle.js common-ui.bundle.js 2.bundle.js 6.bundle.js main.bundle.js
Entrypoint feature1 [big] = runtime.bundle.js common-ui.bundle.js 2.bundle.js feature1.bundle.js
Entrypoint feature2 [big] = runtime.bundle.js common-ui.bundle.js 2.bundle.js feature2.bundle.js
```

The list of entrypoints is very important in the stats. It lists which `<script>` tags need to be added for each feature.

``` text
Entrypoint main [big] = runtime.bundle.js common-ui.bundle.js 2.bundle.js 6.bundle.js main.bundle.js
Entrypoint feature1 [big] = runtime.bundle.js common-ui.bundle.js 2.bundle.js feature1.bundle.js
Entrypoint feature2 [big] = runtime.bundle.js common-ui.bundle.js 2.bundle.js feature2.bundle.js
```

i. e. for `main` + `feature1` you need to include all files listed here (omitting duplicates):

=> runtime.bundle.js common-ui.bundle.js 2.bundle.js 6.bundle.js main.bundle.js feature1.bundle.js

Note that webpack automatically extracted shared modules into a new chunk `2.bundle.js` to avoid including duplicate code in main and the features. When the number of features grow you may get more such files. Note that the number of files per entrypoint is capped to 4 by default so I increased that maximum with `maxInitialRequests`. You need to use HTTP/2 for optimal performance with higher number of files.

**Comment by anbaran** [comment]
Thank you for your detailed answer
