### ISSUE TITLE
using createChildCompiler

### ISSUE THREAD

**Issue by Topthinking** [webpack/webpack#9633]
When using createChildCompiler, how do I remove the plugin referenced by the parent compilation in the sub-compilation

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please use gitter or stackoverflow for questions. Why do you need remove this?
