### ISSUE TITLE
Javascript file path is same as the one from development mode

### ISSUE THREAD

**Issue by grecdev** [webpack/webpack#9637]
# Bug report

**What is the current behavior?**

After i use the `npm run build`  the production javascript `file paths` are the same as the ones which i use for development. The file paths from development is relative to the `webpack.dev.server` file. And the images doesn't copy neither so i can change `filepath` manually.

E.g:

Development: 
`/src/assets/imgs/image.jpg` -> relative to public folder because i use `webpack.dev.server`

Production files: `/src/assets/imgs/image.jpg`

Here you have my [config files](https://gist.github.com/grecdev/46c7a61c0038f621db2708e1ae16af3b)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Image path should be `../imgs/image.jpg` -> relative to the js file

**Other relevant information:**
webpack version:  `^4.36.1`
Node.js version:  `v10.16.0`
Operating System:  `Windows 10`
Additional tools: `Visual Code`

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).

**Comment by sokra** [comment]
Check `publicPath` option
