### ISSUE TITLE
Add Ethereum name or address to package.json

### ISSUE THREAD

**Issue by lastmjs** [webpack/webpack#9638]
## Feature request

**What is the expected behavior?**

An Ethereum name or address should be in the ethereum field of the package.json.

**What is motivation or use case for adding/changing the behavior?**

This will allow consumers of the project to know a canonical address to send funds to. For example, I'm building an application that will allow developers to automatically donate ETH to all of their npm dependencies that have an Ethereum address in their package.json file. 

Having an Ethereum address would allow various cryptocurrencies to be donated, including stablecoins pegged to USD, like USDC or DAI. Essentially it is another payment network like PayPal, but open and decentralized like the internet. Getting an address is relatively straightforward through something like MetaMask or Coinbase. You could also generate one on your own.

**How should this be implemented in your opinion?**

Get an Ethereum name or address and put it in the ethereum field of the package.json

**Are you willing to work on this yourself?**

Yes, I just need to know the address to put in

**Comment by sokra** [comment]
I don't think adding more non-standard fields to the package.json is a good idea. Maybe use better use a file in the repo instead: similar to `.github/FUNDING.yaml`

Anyway, we don't accept payments via Ethereum.
