### ISSUE TITLE
Module fails to run due to async dependencies not being loaded

### ISSUE THREAD

**Issue by tswaters** [webpack/webpack#9640]
# Bug report

**What is the current behavior?**

Under certain conditions, an entrypoint is not run due to an async chunk not being loaded.

**If the current behavior is a bug, please provide the steps to reproduce.**

I've tried to create a "reduced" test case but due to the complexity of loading the various modules, it ended up being much larger than I anticipated.... so, apologies for that but a bit of explanation as to what is in this repo may be in order:

https://github.com/tswaters/wtf-webpack

There is a "main" entrypoint, and an entrypoint for 3 "modules".  Each "module" is identical with only naming changes.

* main - does a "hello world" react app, requires react/react-dom & redux.

* modules - includes an entrypoint which import's a split component (which requires react), and a store definition (which requires reselect).

* each file has a console.log indicating it has loaded when viewing in the browser.

Under `HEAD` the build is successful.  If you `git apply break-it.patch` in the folder, it no longer works properly.  The only difference in the patch is to import `react-redux` from the modules instead of using stub versions.  Some interesting things happen after applying the patch:

* async chunks are re-ordered -- 0.js now includes most of the contents of `vendors~main` did, and 1/2/3 are exactly as they were before, still include a copy of reselect.

* `vendors~main`, which previously had react-dom is now gone (seemingly now it's an async chunk, 0) -- async 0 now includes react-redux.

* main.js now has an "executeModules" reference at the bottom pointing at chunk 0.

* attempting to load the page, the `main` entrypoint will never actually fire [looking at the console.log entries, lack of output on the screen].  It waits for chunk 0, but it is never loaded.

A few things I don't understand:

* react is loaded by all 4 entrypoints, and will split into the vendor chunk properly -- it's only requiring react-redux that tips it over the edge and forces everything into an async chunk.  Why is `react-redux` special here?  what causes it to move everything into an async chunk?

* why doesn't the webpack runtime realize that `main` requires chunk 0 to run and load it properly?  I think that's the real bug tbh.  I don't really care if it's async or not unless it fails to load for whatever reason and I get a white screen instead of the application.

**What is the expected behavior?**

Hello world is displayed on the page

The following console.log outputs:
* App
* Store
* Module1
* Module2
* Module3

**Other relevant information:**
webpack version:  4.39.3
Node.js version: 10.16.3
Operating System: Windows 10 (x64)
Additional tools: babel / html-webpack-plugin

^^ Also, I manually messed with the order of script tags that `html-webpack-plugin` generates and it looks to be doing the correct thing.  I'm fairly sure it can be ruled out.

**Comment by sokra** [comment]
The compilation states that it needs these script tags to work properly:

```
Entrypoint main = runtime.js 1.js main.js
Entrypoint module1 = runtime.js module1.js
Entrypoint module2 = runtime.js module2.js
Entrypoint module3 = runtime.js module3.js
```

but your `index.html` doesn't include `1.js`, so that doesn't load.

After upgrading to `html-webpack-plugin@4.0.0-beta.8` it works.
