### ISSUE TITLE
Takes too long to exit

### ISSUE THREAD

**Issue by muuvmuuv** [webpack/webpack#9641]
# Bug report

**What is the current behavior?**

When I start the webpack compilation everything is fine, its fast (1388ms) and smooth BUT it takes way to long to exit and I don't know why. It seems like it does something but I can't see what it is even with verbose everything.

**If the current behavior is a bug, please provide the steps to reproduce.**

This is my webpack.config.js: https://hastebin.com/hoxulapagu.js
And my package.json: https://hastebin.com/fibutigipa.json

1. setup these two
2. add a js and scss file
3. modify paths
4. run `npm run dev`

**What is the expected behaviour?**

After it prints the last asset that has compiled it should exit immediately or show at least another loading indicator that it is still doing something.

**Other relevant information:**
webpack version:  4.39.3
Node.js version: 10.16.0
Operating System: macOS 10.14.6
Additional tools:

**Comment by sokra** [comment]
Run a profiler to figure it out: `node --inspect-brk` + `chrome://inspect`

**Comment by muuvmuuv** [comment]
So I did that, but where should I look at? When I shrink the timeline to where the compilation ends (the _Time: 1677ms_ that webpack shows in the console) I see a __lot__ of stuff going on after that. Is that the expected behaviour?

Here is the profile: https://gist.githubusercontent.com/muuvmuuv/c384403bd9e3e8cffcda32562d0e4b3b/raw/8f6a8005b834d015e27f3e0882d97a5b60ad5ff2/profileEVEnts.json

**Comment by sokra** [comment]
Don't use the ProfilingPlugin, as it stops the profile when the compilation is done. You want to profile the part after the compilation.

Run it this way:

* `node --inspect-brk node_modules/webpack/bin/webpack.js`
* Open `chrome://inspect` in Chrome
* Click on `Open dedicated DevTools for Node`
* Open the `Profilier` tap (if it's not look in the dot dot dot menu)
* Click on `Start`
* Wait until the compilation has finished
* Click on `Stop`
* Check the profile in graph view

**Comment by muuvmuuv** [comment]
That is a nice tool! Didn't know about that, sorry!

There are still many things that happen after the 1502ms compilation time webpack shows in the console.
https://we.tl/t-iMoDwFgek9

**Comment by sokra** [comment]
Could you try removing the webpack-build-notifier?

**Comment by muuvmuuv** [comment]
That was it... wow 😄. Thank you! I'll open an issue on their end.

How have you "profiled" that? Is there a common way to indicate things like that?

**Comment by sokra** [comment]
> How have you "profiled" that? Is there a common way to indicate things like that?

It's in your profile file^^
