### ISSUE TITLE
Default chunk minsize of 30k ignored in dev mode

### ISSUE THREAD

**Issue by herrvigg** [webpack/webpack#9644]
# Bug report

**What is the current behavior?**

The default chunk minsize of 30k is not working properly in development mode. A vendor chunk of 17k is produced while it is not generated in prod mode, nor if the `minsize` value is explicitly set to 30000.

**If the current behavior is a bug, please provide the steps to reproduce.**

1) Default config:
```
splitChunks: {
  chunks: 'all'
}
```
1.1) Dev mode
```
webpack --mode=development
...
vendors~builds.bundle.js   1.24 MiB       3  [emitted]  vendors~builds
vendors~main.bundle.js    925 KiB       2  [emitted]  vendors~main
vendors~main~stats.bundle.js   17.6 KiB (!)      7  [emitted]  vendors~main~stats
vendors~stats.bundle.js   1.16 MiB       8  [emitted]  vendors~stats
```
The 3rd chunk should not be produced.

1.2) Prod mode
```
webpack --mode=production
...
vendors~builds.bundle.js    166 KiB       5  [emitted]         vendors~builds
vendors~main.bundle.js    269 KiB       6  [emitted]  [big]  vendors~main
vendors~stats.bundle.js    129 KiB       7  [emitted]         vendors~stats
```

2) Explicit config with minsize:
```
splitChunks: {
  chunks: 'all',
  minsize: 30000 # this is supposed to be the default value (?!)
}
```

2.1) Dev mode
```
vendors~builds.bundle.js   1.24 MiB       3  [emitted]  vendors~builds
vendors~main.bundle.js    943 KiB       2  [emitted]  vendors~main
vendors~stats.bundle.js   1.17 MiB       7  [emitted]  vendors~stats
```

2.2) Prod mode
```
vendors~builds.bundle.js    166 KiB       5  [emitted]         vendors~builds
vendors~main.bundle.js    269 KiB       6  [emitted]  [big]  vendors~main
vendors~stats.bundle.js    129 KiB       7  [emitted]         vendors~stats
```

**What is the expected behavior?**
In dev mode case 1.1 the 17k vendor chunk should not be generated. It is not generated in case 2.1 when specifying the minsize value to 30k which is supposed to be the default value.

**Other relevant information:**
webpack version:  4.39.2
Node.js version: 10.16.0
Operating System: Ubuntu 16.04 (WSL)
Additional tools:

**Comment by sokra** [comment]
In dev mode the default minSize is 10k, more chunks are better in dev mode for build performance

**Comment by herrvigg** [comment]
I can't really judge about the value, there may be some good reasons for this, but the documentation should describe more precisely the current behavior here: https://webpack.js.org/plugins/split-chunks-plugin where there is no mention of 10k in dev mode.

I just figured out it is detailed here: https://webpack.js.org/configuration/mode/#root. This part is correct, but now i see there are quite a few default options changing depending on the mode! 

Prod mode
```
-   splitChunks: {
-     hidePathInfo: true,
-     minSize: 30000,
-     maxAsyncRequests: 5,
-     maxInitialRequests: 3,
-   }
```

Dev mode (and none)
```
-   splitChunks: {
-     hidePathInfo: false,
-     minSize: 10000,
-     maxAsyncRequests: Infinity,
-     maxInitialRequests: Infinity,
-   }
```

Maybe those should be kept only in one place to make it easier to maintain, with links pointing to these where it is useful.

**Comment by sokra** [comment]
Yep, seem like a good opportunity to improve the docs.

Here is the source of all default values in webpack: https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsDefaulter.js
