### ISSUE TITLE
Deprecate "unqualified" loader name resolution for third-parties

### ISSUE THREAD

**Issue by arcanis** [webpack/webpack#9648]
## Feature request

**What is the expected behavior?**

Webpack 5 should warn third-party tools (CRA, Next, Vue-Cli, ...) when they reference a loader through their simple name rather than an absolute path.

**What is motivation or use case for adding/changing the behavior?**

Many tools do things like this:

```js
addWebpackLoader('cache-loader');
```

It works most of the time, but is almost always subtly broken: it'll cause Webpack to load `cache-loader` based on the resolution from the file that needs it, meaning that if the hoisting didn't put the loader at the top of the node modules the wrong will be used.

Even worse, in some situation (for example two packages depend on `cache-loader`) only one of them will be hoisted but it will be used for the two third-parties that initially depended on this - causing subtly semver-broken code whose behavior may change if the hoisting changes later.

The fix would be to use an absolute path (thanks to `require.resolve`), since that would totally disambiguate the resolution and would guarantee that each package will use the loader it expects:

```js
addWebpackLoader(require.resolve('cache-loader'));
```

**How should this be implemented in your opinion?**

It's difficult; my best suggestion would be to check when doing an unqualified name resolution that the specified package is present in the closest `package.json`. If it isn't, print a warning.

**Are you willing to work on this yourself?**

Possibly - I'm working on a lot of PRs for various projects so I'd prefer someone else to help me on that, but I can do it if necessary.

**Comment by sokra** [comment]
All loaders specified in the configuration resolve relative to the `context` (usually the root of the project) and not relative to the resource file. This was changed from webpack 3 to 4.

**Comment by arcanis** [comment]
Still, the problem is the same. For example, if a project like Gatsby, CRA, or Next.js specifies an unqualified loader name in the Webpack config, then Webpack will expect it to be a dependency of the `context` - which is usually the project application, not Gatsby's own package.
