### ISSUE TITLE
Failed to use async function in webpack configs

### ISSUE THREAD

**Issue by Kellercai** [webpack/webpack#9649]
I use a `async function` in `webpack.prod.conf.js`，to get the result to set a attribute(`PrerenderSpaPlugin`) in webpackConfig(which is to `module.exports`) from the  async function, in the process to run build，but it does not seem to take effect(no PrerenderSpaPlugin attribute).

"webpack": "^2.6.1"

code segment
![image](https://user-images.githubusercontent.com/20681598/64065655-a7678d00-cc42-11e9-95e7-c34dc3123eb7.png)

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by evilebottnawi** [comment]
Don't use outdated webpack version
