### ISSUE TITLE
Webpack fails to parse modules that use a json file as the index

### ISSUE THREAD

**Issue by murphyrandle** [webpack/webpack#965]
Hi there!

When I `require` the module https://github.com/dfcreative/color-name, Webpack fails with the following error:

```
ERROR in ./~/color-name/index.json
Module parse failed: [redacted]/node_modules/color-name/index.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "aliceblue": [240, 248, 255],
|   "antiquewhite": [250, 235, 215],
|   "aqua": [0, 255, 255],
 @ ./app/client/index.jsx 17:8-29
```

And it's because the color-name module specifies `index.json` as the module entrypoint in its `package.json`.

When I change the filename inside that module to `index.js` and modify it to use `module.exports = ...` everything works fine.

I tried addding json-loader to my webpack config, but it looks like webpack expects only to find .js files when requiring something from `node_modules`.

It's strange that the color-name module uses a json file as its index, but Node supports it, so it seems like Webpack maybe should too?

**Comment by sokra** [comment]
You need the json-loader

**Comment by murphyrandle** [comment]
@sokra If you look at my post above, I added json-loader already: 

> I tried addding json-loader to my webpack config, but it looks like webpack expects only to find .js files when requiring something from node_modules.

But it appears that the json-loader doesn't apply when requiring a module from node_modules whose index is a json file.

Please re-open this issue as it is not resolved.

**Comment by sokra** [comment]
> If you look at my post above, I added json-loader already

Can you paste your webpack.config.js? Maybe there is something wrong there.

**Comment by yonatanmn** [comment]
perhaps the `js` RegExp test is interfered somehow with `json`.
Any way - I had this problem, changed the order of loaders it worked, but now work somehow when I've returned the order, no clue why.

**Comment by murphyrandle** [comment]
Sorry I've taken so long to get back, here's what my webpack config looks like:

```
var path = require('path')

module.exports = {
  entry: "./app/client/index.jsx",
  output: {
    path: path.join(__dirname, 'app', 'static', 'generated'),
    filename: 'bundle.js'
  },

  resolve: {
    extensions: ['', '.js', '.jsx', 'index.js', 'index.jsx', '.json', 'index.json']
  },

  module: {
    preLoaders: [
        { test: /\.json$/, exclude: /node_modules/, loader: 'json'},
    ],
    loaders: [
        { test: /\.js$/, exclude: /node_modules/, loader: 'babel'},
        { test: /\.jsx$/, exclude: /node_modules/, loader: 'babel'},
        { test: /\.css$/, exclude: /static/, loader: 'style!css'}
    ]
  },

  devtool: '#eval'
}
```

**Comment by murphyrandle** [comment]
@yonatanmn can you give an example of changing the order of loaders?

**Comment by sokra** [comment]
Remove the exclude from the json-loader.

**Comment by murphyrandle** [comment]
@sokra, write as you wrote that I was reading through, and just now saw that. :sheep: <- (feeling sheepish) trying it now.

**Comment by murphyrandle** [comment]
@sokra Unfortunately removing the 'exclude' directive didn't change the error message at all. I removed it, so that the line now looks like this: 

```
    preLoaders: [
        { test: /\.json$/, loader: 'json'},
    ],
```

I then restarted webpack, reloaded the page, and I still get the same syntax error.

I tried moving the json line to "loaders", too, instead of "preLoaders".

**Comment by sokra** [comment]
``` js
module.exports = {
	module: {
		loaders: [
			{ test: /\.json$/, loader: "json-loader" }
		]
	}
}
```

``` text
webpack color-name bundle.js
```

works fine.

**Comment by murphyrandle** [comment]
I am so sorry.


This is very embarrassing. It does, in fact, work fine. I was editing the wrong webpack config.


![shamecube](https://cloud.githubusercontent.com/assets/1227109/7378913/1af65ddc-edae-11e4-85ac-de7c7bf83363.gif)

**Comment by basiclaser** [comment]
thanks for the fix 👍

**Comment by kelabang** [comment]
guys youre really big help thx, its working now

**Comment by Levino** [comment]
Is this not a bad way / wrong place to fix this? Should the maintainer of the color-name package not include a webpack.config that states, that json-loader is a necessary loader when using this package? Is this possible with webpack? Does anyone have guide / example?

**Comment by mkhanal** [comment]
@Levino I think webpack is not a standard that every package provider should look at. They just need to follow the npm standards. The standard is that the file can be a js or a json, and any module loader that loads packages should honour both.

**Comment by moskos88** [comment]
Many thx! This discussion helped me with very same problem ;)

**Comment by hedgepigdaniel** [comment]
I had this problem because I was applying the babel-loader to json files. I did this:
```javascript
{
  test: /\.js/,
  use: 'babel-loader'
}
```

I fixed it by doing this:
```javascript
{
  test: /\.js$/,
  use: 'babel-loader'
}
```

**Comment by bilalsarimeseli** [comment]
Hello everyone; 
I have a stubborn error that I have spent hours to be able to fix it: 
**"SyntaxError: Unexpected token e in JSON at position 0"**
This is the index.js probably error is thrown from: 
```
module.exports = function (source) {
  if (this.cacheable) this.cacheable();

  var value = typeof source === "string" ? JSON.parse(source) : source;

  value = JSON.stringify(value)
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');

  return `module.exports = ${value}`;
}
```
I would be so very glad if you can help me fix this. 
Thanks
