### ISSUE TITLE
Workflow assistance npm link

### ISSUE THREAD

**Issue by chrismcv** [webpack/webpack#966]
Hi, 
I've a currently a main shell package, and then a plugin package.  Both use React which I have set as a peerDependency.

I want to be able to develop the plugin standalone, so have `npm install react` done on it.

I then `npm link` it into my shell.

If I then do an `npm ls` in the shell project, I get the following:

```
$ npm ls | grep react@
├─┬ plugin-package@1.0.0 -> e:\code\plugin-packge
│ ├─┬ react@0.13.1
├─┬ react@0.13.1
```

This ends up causing an `Uncaught TypeError: Cannot read property 'firstChild' of undefined` error, (see https://github.com/facebook/react/issues/2402) which is caused by 2 reacts being loaded (even though they are the same version).

Can anyone advise on how I might configure my projects to avoid this issue?  I'm hoping it can be done by config rather than change require code to https://www.npmjs.com/package/parent-require.

(Also, if I `npm rm react` from the plugin, and build the shell, I get..)
```
Module not found: Error: Cannot resolve module 'react' in e:\code\touch\parser
 @ e:/code/plugin-package/index.js 1:12-28
```

Thanks, 
Chris

**Comment by chrismcv** [comment]
I should add that with config:
```
  resolveLoader: {
    modulesDirectories: ['node_modules'],
    fallback: path.join(__dirname, "node_modules")
  },
  resolve: {
    root: path.resolve(__dirname, './app'),
    fallback: path.join(__dirname, "node_modules"),
    extensions: ['', '.jsx', '.js', '.cjsx', '.coffee', '.css', '.styl']
  }
```
the second issue (`npm rm react`) is sorted, but if I then install react to work on the plugin locally, it fails again.

**Comment by SimenB** [comment]
Did you try `npm dedupe`?

**Comment by chrismcv** [comment]
just did, doesn't seem to help - issues remain as above

**Comment by sokra** [comment]
`resolve.root = path.resolve(__dirname, "node_modules")`.

This will prefer local install node_modules.

**Comment by chrismcv** [comment]
perfect - that sorts it - many thanks!

**Comment by tomhicks** [comment]
@chrismcv we had this problem and fixed it in a similar way in webpack (we actually used an alias for react, but it's basically the same thing), but we could never solve it for running unit tests via node (because that's not using webpack).

So just in case you have the need (or anyone else comes across this problem) to run this on node, the solution is to npm link your versions of react across projects:

```
cd node_modules/react
npm link
cd ../../../child-project
npm link react
```

This will also remove the need to have this resolve root setting in webpack.
