### ISSUE TITLE
Default configuration file should be renamed

### ISSUE THREAD

**Issue by xpepermint** [webpack/webpack#967]
This one is for all `code designers` :).

The long `webpack.config.js` filename does not look right every time I look at my project's directory structure. My proposal is to rename the default file to `webpack.js` or just add an additional default file name (like `gulpfile.js`, `package.json`).

It would also be helpful if we could add documentation on how to organize the code in case when projects get huge (it is kind of difficult to define everything inside a single file) - conventions, best practices. Well... I spend hours organizing the code because I like it clean and stylish.

What do you think?

**Comment by troutowicz** [comment]
You can name your config file whatever you want using the `--config` flag.

http://webpack.github.io/docs/configuration.html#cli

**Comment by sirlancelot** [comment]
I think `Webpackfile.js` would be more fitting. Also solves the problem of transpiled languages: `Webpackfile.coffee` or if you don't need logic: `Webpackfile.json`

**Comment by xpepermint** [comment]
@sirlancelot Even better. I think it should NOT be capitalized (linux, node = usually always down-cased).

**Comment by bebraw** [comment]
@sokra It's your call. webpack 2 would be the right place to do a change like this if needed.

**Comment by jaydenseric** [comment]
@sirlancelot why put "file" in the name? That has always irritated me with `gulpfile.js`, it is redundant to name a file "file". It would be similar to naming `node_modules` `node_modules_folder`. ESLint naming their config `eslintConfig` instead of just `eslint` in `package.json` also [grinds my gears](https://github.com/eslint/eslint/issues/4261#issuecomment-171850954).

**Comment by ThatTomPerson** [comment]
Just an idea
Gulp supports using the gulpfile as a folder, `gulpfile.js/index.js`
It looks ugly with the `.js` but if webpack could support `webpackfile/index.js'  it would allow users to organise for files inside the "webpackfile"

an example would be configs for production and development builds

thoughts?

**Comment by preco21** [comment]
Now actually [it has been supported](https://github.com/webpack/webpack/blob/master/bin/convert-argv.js#L36)?

BTW, how can I write babel favored config in `webpack@2` right way?
This seems working fine to me: `webpackfile.babel.js` like the `gulpfile.babel.js` with `babel-core` has installed.

Tested webpack version: `webpack@2.1.0-beta.20`

**Comment by bebraw** [comment]
I'm closing this as it's not going to change for webpack 2. We may revisit this decision in webpack 3 although *webpack.config.js* and the aforementioned variants are fairly established.
