### ISSUE TITLE
minimize and production setting for ~ of iteration code ReferenceError

### ISSUE THREAD

**Issue by scarfunk** [webpack/webpack#9674]
# Bug report

**What is the current behavior?**
here is sample code.
```
function test() {
    try {
        const arr = [1];
        const arr2 = [1, 2];
        for (const x of arr) {
            console.log(x);
        }
        console.log(arr2);
        return true;
    } catch (err) {
        throw err;
    }
}
```

here is config
```
module.exports =
	{
		mode: 'production',
		optimization: {
			minimize: true
		},
		devtool: 'inline-source-map',
	};
```
ReferenceError: arr is not defined

seems like (try catch + for of) code is not working.

here is test repo
https://github.com/scarfunk/webpackbug-minimize

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  4.39.3
Node.js version: 11.6.0 - ~/.nvm/versions/node/v11.6.0/bin/node
Operating System: macOS 10.14.4
Additional tools:

**Comment by evilebottnawi** [comment]
Please create issue in `terser` repo

**Comment by sokra** [comment]
yep, looks like a terser bug.

**Comment by sokra** [comment]
raw terser minimizes:

``` js
(function() {
    try {
        const arr = [1];
        for (const x of arr) {
        }
    } catch {
    }
})()
```

to

``` js
!function(){try{for(const c of arr);}catch{}}();
```
