### ISSUE TITLE
Webpack. Async chunk loading

### ISSUE THREAD

**Issue by NCoder2019** [webpack/webpack#9676]
I have an SPA apllication. It created it using vue.js, webpack. A ClientApp folder size - 422 Kb (contains components only). It's because I developed this application 4 months.

I have a components and loading it using lazy loading. Now I'm trying to split code using optimization property. But I can't understand how to do it. The bundle file size 687 Kb, but I need not bigger than 100 Kb.

I tried:
`optimization: {
    splitChunks: {
        chunks: 'all'
    }
}
`

If I use it, I have the bundle size 28 Kb. Also I get new file (vendor) 658 Kb. And I need to include this file too, because without it render is failure. But after that nothing is changed.

I want to load the code required for initial render, after that load another code in async mode.
How can I do it? And is that possible?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
