### ISSUE TITLE
Webpack wraps together unused methods from the import file

### ISSUE THREAD

**Issue by xuzhilin1** [webpack/webpack#9682]
```
// a.js 
export function a();
... b,c,d
export function e();
===
//b.js
import {a,b,c} from 'a.js'
```
a.js all function build to b.js,I just used the a,b,c method，but a,b,c,d,e, It's all packed in.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
