### ISSUE TITLE
Tree shake object literals

### ISSUE THREAD

**Issue by alshdavid** [webpack/webpack#9688]
## Feature request

**Platform details**
Webpack version: `4.39.3`
Node version: `10.16.2`
Operating System: MacOS

**What is the expected behavior?**
When importing items that are part of an object literal, unused items are not removed.

Say the following is exported in an index file:

```javascript
import { a } from './a'
import { b } from './b'
import { c } from './c'
import { d } from './d'

export const myLibrary = {
    a, b, c, d
}

export default myLibrary
```

When consumed:

```javascript
import myLibrary from 'my-library'

myLibrary.a('Only include this function')
```

All the bundled functions are included.

**What is motivation or use case for adding/changing the behavior?**

Namespacing modules/packages is a great way to avoid naming collisions and facilitate for grouping entities by concern.

**How should this be implemented in your opinion?**
**Are you willing to work on this yourself?**
Unfortunately I do not possess the skills to meaningfully contribute to the webpack project. I have starred the project though! 

EDIT:

This is also an issue when importing all of the exports of a module and grouping them with `*`
```javascript
import * as aLibrary from 'a-library'
```

**Comment by MrHBS** [comment]
@sokra Was this ever addressed?
