### ISSUE TITLE
CommonsChunkPlugin + HotModuleReplacementPlugin

### ISSUE THREAD

**Issue by maxkostow** [webpack/webpack#969]
Is it possible to use these together?

The CommonsChunk entry is not defined in my webpack entries (the plugin adds it?) and is not built when using the HotModuleReplacementPlugin.

**Comment by maxkostow** [comment]
Looks like you have to load the HotModuleReplacementPlugin before the CommonsChunkPlugin

**Comment by chapinkapa** [comment]
I am using both of these, but my hot module replacement is no longer working. It is getting stuck on `[WDS] App hot update...`

**Comment by dcworldwide** [comment]
I'm stuck on this too. 

I can get it working with a single bundle, but  how to combine it with CommonsChunkPlugin?
I.e.

```
 plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new webpack.optimize.CommonsChunkPlugin({
            name: 'vendor',
            minChunks: Infinity
        }),
    ],
```

How would I change server.js

```
var WebpackDevServer = require('webpack-dev-server');
var webpack = require('webpack');
var config = require('./webpack.config.js');
var path = require('path');

var compiler = webpack(config);
var server = new WebpackDevServer(compiler, {
  contentBase: 'dist',
  hot: true,
  // filename: '/dist/main.bundle.js',
  filename: 'bundle.js',
  publicPath: '/',
  stats: {
    colors: true,
  },
});
server.listen(8080, 'localhost', function() {});
```

..and my index.html (in dist folder)

```
<body>

  <div id="example"></div>

  <!-- Dependencies -->
  <script src="https://js.arcgis.com/3.17/"></script>

  <!-- Main -->
  <script src='/bundle.js'></script>
</body>

```

**Comment by truongsinh** [comment]
I know "no me too" policy, but I have to break it, because this issue is closed, while it's not supposed to be. `load the HotModuleReplacementPlugin before the CommonsChunkPlugin` does not solve it.
