### ISSUE TITLE
4.40.0 broke our release process

### ISSUE THREAD

**Issue by elorzafe** [webpack/webpack#9695]
# Bug report

**What is the current behavior?**
There was introduced a breaking change on 4.40.0 that was working before (didnt follow semver). I have my building using version 4.39.3 without issues.

**If the current behavior is a bug, please provide the steps to reproduce.**
Just run webpack

**What is the expected behavior?**

**Other relevant information:**
webpack version:  4.40.0 (worked 4.39.3 without issues)
Node.js version: 10.16.2
Operating System:  macOS Sierra
Additional tools:

**Comment by sokra** [comment]
> Just run webpack

I was unable to reproduce this.
