### ISSUE TITLE
Error: Conflict: Multiple assets emit to the same filename V4.40.0

### ISSUE THREAD

**Issue by JoeFirebaugh** [webpack/webpack#9699]
# Bug report

**What is the current behavior?**

> Error: Conflict: Multiple assets emit to the same filename

This is a new error I get when moving from V3.39.3 to V4.40.0, and if I had to make a guess it's from the fact that our build has multiple Stylesheet themes that it emits, that contain some of the same font files, because the filename it reports is a font file from both SCSS stylesheet builds.

**If the current behavior is a bug, please provide the steps to reproduce.**
I'm not 100% sure, but I think you just need a build that has two entry points to stylesheets that will emit the same assets.
`const config = {
        entry       : {
            app       : sourcePath + '/main.ts',
            LightTheme: sourcePath + '/themes/light/LightTheme.scss',
            SlateTheme: sourcePath + '/themes/slate/SlateTheme.scss'
        },`

**What is the expected behavior?**
On V3.39.3 our build runs normally without error.

**Other relevant information:**
webpack version:  4.40.0
Node.js version: 11.11.0
Operating System: MacOS Mojave
[webpack.config.js.zip](https://github.com/webpack/webpack/files/3609762/webpack.config.js.zip)

Additional tools:

**Comment by sokra** [comment]
Upgrade to 4.40.1

**Comment by JoeFirebaugh** [comment]
That worked!  I want to apologize for not searching the closed tickets
first.
