### ISSUE TITLE
Question : Can a relative path be the key for resolve.alias ? 

### ISSUE THREAD

**Issue by karyboy** [webpack/webpack#970]
I am trying to use resolve.alias for resolving relative modules, like 

     require('./moduleA')

So my config looks like this : 

    {
        resolve : {
           alias : { 
               moduleA$ : 'path/to/replacement/module' 
          } 
       }
    }

This doesnt seem to work.
But if require contains a module name like : 
     
     require('moduleA')

This works 

Is there support for relative modules in require? 

Thanks

**Comment by schovi** [comment]
:+1: Looking for that too!

**Comment by sairion** [comment]
I am trying to override `react/lib/invariant` (mostly due to https://github.com/facebook/react/issues/2686) but in React src, they all require it like './react' so it is impossible to replace it. Any suggestions?

**Comment by sairion** [comment]
Welp, ended up using `webpack.NormalModuleReplacementPlugin`
