### ISSUE TITLE
LimitChunkCountPlugin performance degradation

### ISSUE THREAD

**Issue by Tom910** [webpack/webpack#9703]
# Bug report
I upgrade webpack 4.20.0 to 4.40.2 and get performance degradation with plugin LimitChunkCountPlugin. First a long to x3 and rebuild to x30

**What is the current behavior?**
In my app
with `new webpack.optimize.LimitChunkCountPlugin({ maxChunks: 1 })`
first: 46.80s
rebuild: 31.63s

without
first: 15.79s
rebuild: 1.95s

**If the current behavior is a bug, please provide the steps to reproduce.**
Repo with reproduction https://github.com/Tom910/webpack-perf-degr-LimitChunk
with LimitChunkCountPlugin
Time: 148 782ms

without LimitChunkCountPlugin
Time: 4 934ms

**What is the expected behavior?**
Not much perf degradation. Or find out about an alternative to this plugin

**Other relevant information:**
webpack version:  4.40.2
Node.js version: v10.16.0
Operating System: Mac OS 10.14.5
Additional tools:
I have SSR with react and used webpack for node and browser. In my app
chunks: 140
modules: 12000

**Comment by spacekitcat** [comment]
This sort call in `LimitChunkCountPlugin.js` (line 56, master) seems to absolutely murder the performance:

```
.sort((a, b) => {
    // sadly javascript does an inplace sort here
    // sort them by size
    const diff1 = b[0] - a[0];
    if (diff1 !== 0) return diff1;
        const diff2 = a[1] - b[1];
    if (diff2 !== 0) return diff2;
        const diff3 = a[2].compareTo(b[2]);
    if (diff3 !== 0) return diff3;
        return a[3].compareTo(b[3]);
});
```

I get around ~130ms when I disable it and around ~800ms with it on.

**Comment by spacekitcat** [comment]
Ah, the behaviour was modified in this commit: https://github.com/webpack/webpack/commit/c04747f17d530b34f8535f2751b33c9948f37996

The old code is very fast compared to the current code.

**Comment by Tom910** [comment]
For the alternative LimitChunkCountPlugin, I start using babel plugin babel-plugin-dynamic-import-node which removes import and require.ensure

**Comment by evilebottnawi** [comment]
Thanks for issue

**Comment by spacekitcat** [comment]
If I get a chance, I'll take another look at it! I got as far as figuring what the code does, but I don't know enough of the why to fix it.

**Comment by vankop** [comment]
@sokra I think in `webpack@5` also possible some refactor. For instance [here](https://github.com/webpack/webpack/blob/next/lib/optimize/LimitChunkCountPlugin.js#L64) possible to merge reduce+map and reduce code complexity
