### ISSUE TITLE
Disable all loaders via webpack config?

### ISSUE THREAD

**Issue by wangyi7099** [webpack/webpack#9705]
> I use some scaffolds like `vue-cli` and they add their own rules in webpack config.

I know we can disable all loaders except specified loaders by adding  the prefix `!!`:
`import '!!/my-css-loader!./index.css'`.except itself, i.e, assume the config was `{disableOthers: true}` 

```js
const config = {
  module: {
    rules: [
      {
        test: /\.css$/,
        resouceQuery: /foo/,
        loader: 'my-css-loader',
        disableOthers: true 
      }
    ]
  }
};
```
And then I could import the css in js by adding resourceQuery `foo` and disable all external loaders.

```js
import './index.css?foo'
```

I think the second way is more convenient than the first one.

**Comment by evilebottnawi** [comment]
Please use issue template otherwise issue will be closed, what is use case disable all loaders?

**Comment by wangyi7099** [comment]
sorry.  I created issue by clicking `something else` button and don't see the content of issue template carefully.

My codebase is built with vue-cli. The scss has been resolved via sass-loader which is added into webpack cobfig by vue-cli. I want to process some certain scss files by my own scss loader. Currently I achieve this by inline loader: 
`import '!!my-style-loader!css-loader!scss-loader!./a.scss'` 

But I want to know whether there is way or not to achieve this by webpack config as what I have said in above.

**Comment by evilebottnawi** [comment]
I think better open issue in `vue-cli` and allow developers disable some built-in rule.

**Comment by wangyi7099** [comment]
Yes. If I look for help from `vue-cli`, the issue may be reolved, but what if other scaffolds do the same behaviors as `vue-cli` ? Like create-react-app or  umi ?
I just want to get the same functionality as the `!!` prefix in the webpack configuration.

Maybe it is a feature request? If I'm wrong, please close this issue.

**Comment by alexanderhorner** [comment]
@wangyi7099 was right. I would need this rn
