### ISSUE TITLE
Webpack 4.40.2 can't parse class properties

### ISSUE THREAD

**Issue by bgdavidx** [webpack/webpack#9708]
# Bug report

**What is the current behavior?**

Webpack fails with error:

```
ERROR in /var/app/src/util/bunyan/logstash.js 42:8
Module parse failed: Unexpected token (42:8)
You may need an appropriate loader to handle this file type.
| 
| let LogstashStream = exports.LogstashStream = class LogstashStream extends _events.EventEmitter {
>   _name = 'bunyan';
|   _level = 'info';
|   _server = _os2.default.hostname();
 @ /var/app/src/util/logger.js 24:16-44
 @ ./index.js
 @ multi babel-polyfill index.js
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Try compiling any file that uses class properties, for example:

```
class X {
  y = 1
}
```

or use the Parser directly:

```
> new (require('./node_modules/webpack/lib/Parser'))().parse('class X { y = 1 }', {})
Thrown:
[SyntaxError: Unexpected token (1:12)
] {
  pos: 12,
  loc: Position { line: 1, column: 12 },
  raisedAt: 13
}
```

**What is the expected behavior?**

This should not throw an error

**Other relevant information:**
webpack version:  4.40.2
Node.js version: 12.10.0
Operating System: Debian Buster (Debian 10)
Additional tools:

**Comment by tzsword** [comment]
you will have need to add babel-loader

> * [babel-loader](https://www.npmjs.com/package/babel-loader)
   * [@babel/plugin-proposal-class-properties
](https://babeljs.io/docs/en/babel-plugin-proposal-class-properties)

**Comment by bgdavidx** [comment]
We have babel-loader. We're trying to _not_ transform class-properties, since Node.js 12.x supports them natively. We're using Webpack for a server side app where overall compatibility doesn't matter.

**Comment by evilebottnawi** [comment]
Can you create minimum reproducible test repo?

**Comment by daveKoala** [comment]
I'm having very similar issue - I'm reusing authentication code i've used in a number of other recent Vue Cli built projects that use Vuetify 1.5

```
ERROR  Failed to compile with 1 errors                                                                                                            7:26:18 PM

 error  in ./src/auth/authService.js

Module parse failed: Unexpected token (18:10)
File was processed with these loaders:
 * ./node_modules/eslint-loader/index.js
You may need an additional loader to handle the result of these loaders.
| 
| class AuthService extends EventEmitter {
>   idToken = null;
|   profile = null;
|   tokenExpiry = null;

 @ ./src/router.js 6:0-38 42:52-56 46:2-6
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.15:3000/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```
I've posted on a number of forums with no success and lost track of the things and combinations of package versions with no success.

 
/auth/authService.js
```
const localStorageKey = "loggedIn";
const loginEvent = "loginEvent";

class AuthService extends EventEmitter {
  idToken = null;
  profile = null;
  tokenExpiry = null;

  login(customState) {
    webAuth.authorize({
      appState: customState,
    });
  }
```

vue.config.js
```
const webpack = require("webpack");

module.exports = {
  devServer: {
    port: 3000
  },
  configureWebpack: {
    plugins: [
      new webpack.ProvidePlugin({
        $: "jquery",
        jquery: "jquery",
        "window.jQuery": "jquery",
        jQuery: "jquery"
      })
    ]
  }
};
```
.eslint.js
```
module.exports = {
  root: true,
  env: {
    node: true
  },
  extends: ["plugin:vue/essential", "eslint:recommended", "@vue/prettier"],
  rules: {
    "no-console": process.env.NODE_ENV === "production" ? "error" : "off",
    "no-debugger": process.env.NODE_ENV === "production" ? "error" : "off",
    "comma-dangle": [
      "error",
      {
        arrays: "only-multiline",
        objects: "only-multiline",
        imports: "only-multiline",
        exports: "only-multiline",
        functions: "ignore"
      }
    ]
  },
  parserOptions: {
    parser: "babel-eslint"
  },
  overrides: [
    {
      files: ["**/__tests__/*.{j,t}s?(x)"],
      env: {
        mocha: true
      }
    }
  ]
};
```
package.json
```
{
  "name": "admin-sept-2019",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "test:unit": "vue-cli-service test:unit"
  },
  "dependencies": {
    "auth0-js": "^9.11.3",
    "core-js": "^2.6.5",
    "vue": "^2.6.10",
    "vue-router": "^3.0.3",
    "vuetify": "^2.0.0",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@babel/plugin-transform-classes": "^7.5.5",
    "@vue/cli-plugin-babel": "^3.11.0",
    "@vue/cli-plugin-eslint": "^3.11.0",
    "@vue/cli-plugin-unit-mocha": "^3.11.0",
    "@vue/cli-service": "^3.11.0",
    "@vue/eslint-config-prettier": "^5.0.0",
    "@vue/test-utils": "1.0.0-beta.29",
    "babel-eslint": "^10.0.1",
    "chai": "^4.1.2",
    "eslint": "^5.16.0",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-vue": "^5.0.0",
    "node-sass": "^4.9.0",
    "prettier": "^1.18.2",
    "sass": "^1.17.4",
    "sass-loader": "^7.1.0",
    "vue-cli-plugin-vuetify": "^0.6.3",
    "vue-template-compiler": "^2.6.10",
    "vuetify-loader": "^1.2.2"
  }
}
```
npm run serve will build my vue app

**Comment by evilebottnawi** [comment]
@bgdavidx I do not see `babel-loader` in your configuration

**Comment by evilebottnawi** [comment]
@bgdavidx you need use `babel-loader`, because webpack support only stage 4 and `import`

**Comment by sokra** [comment]
webpack only supports stage 4 proposals, similar to acorn, except for a few exceptions regarding ESM.

Once acorn supports class properties we will support them too.

**Comment by JerryCauser** [comment]
@sokra But what about target 'node'? Class Fields and Private Class Fields are already on LTS version of node and nodejs developers should wait until every browser include support of that feature?

**Comment by travi** [comment]
i ran into this issue when upgrading a node app that i was successfully bundling to the latest version of hapi, which now uses private class fields in a [few places like this](https://github.com/hapijs/teamwork/blob/0be41203961cf83e529bddaa7f3c767688bdd3bb/lib/index.js#L8-L10). i know node isn't as popular of a target, but i try to avoid applying the `babel-loader` to my `node_modules/` and would love to be able to continue that approach, at least when a package works without transpilation when not bundling.

since this is a closed issue, i'm happy to open a new one to track this with the specific goal of handling when the target is node. would that be worthwhile @sokra , or is the reality that we need to wait for the proposal to reach stage 4, regardless of existing support in node?

**Comment by franktopel** [comment]
> webpack only supports stage 4 proposals, similar to acorn, except for a few exceptions regarding ESM.
> 
> Once acorn supports class properties we will support them too.

Acorn has been supporting class fields for a while now, via plugin.

- https://github.com/acornjs/acorn-class-fields

**Comment by ilkkao** [comment]
@sokra class properties are now in stage 4 https://twitter.com/robpalmer2/status/1384208760420274176

Could we re-open this issue? For me personally, class properties are the only reason to use babel. Would love to get acorn updated soon. Acorn issue for tracking: https://github.com/acornjs/acorn/issues/1025

**Comment by voraciousdev** [comment]
Rollup is now allowing class properties in bundles which means Rollup-bundled libraries consumed by Webpack are now throwing errors because of the lack of support in Webpack.

**Comment by ilkkao** [comment]
Webpack recently added support for class properties. This issue should be closed I think.

**Comment by voraciousdev** [comment]
@ilkkao oh, perfect. Which version was it added to?

**Comment by ilkkao** [comment]
@voraciousdev the underlying JS parser was updated in https://github.com/webpack/webpack/releases/tag/v5.36.0
