### ISSUE TITLE
ProgressPlugin does not include most hooks on the compiler instance

### ISSUE THREAD

**Issue by hedgepigdaniel** [webpack/webpack#9714]
## Feature request

**What is the expected behavior?**
ProgressPlugin reports information about the current plugin in all hooks of the compiler instance (not just each compilation) 

**What is motivation or use case for adding/changing the behavior?**
For example, I had an issue with stylelint-webpack-plugin [taking a long time](https://github.com/webpack-contrib/stylelint-webpack-plugin/issues/181) in the `watchRun` hook of the compiler. ProgressPlugin did not output detailed information in this case about which plugin was causing the delay, because it does not instrument the `watchRun` hook of the compiler.

**How should this be implemented in your opinion?**
Similar to how ProgressPlugin has a (probablyish) complete list of hooks that it instruments on the compilation, it should instrument all the hooks on the compiler aswell.

**Are you willing to work on this yourself?**
yes

**Comment by sokra** [comment]
Send a PR

**Comment by evilebottnawi** [comment]
Bump

**Comment by evilebottnawi** [comment]
bump
