### ISSUE TITLE
webpack v3.6.0 split chunk issue

### ISSUE THREAD

**Issue by sumitkumardey91** [webpack/webpack#9715]
i am using vue js. i have installed vue init webpack test,
**code**
 this.temp = () => import(/* webpackChunkName: 'home' */  '@/components/HelloWorld.vue')

here separate chunk is not creating.

**Comment by ematipico** [comment]
Please provide a repository to reproduce the issue.

**Comment by sumitkumardey91** [comment]
thanks for replay.
https://github.com/sumitkumardey91/webpack-chunk
branch: master

**Comment by DRoet** [comment]
offtopic, but if you are new to `vue.js` I would highly recommend using the newer version of  `vue@cli` instead to create your project, since the webpack template is no longer being maintained.

more info [here](https://cli.vuejs.org/#getting-started)

**Comment by sumitkumardey91** [comment]
thanks.it working fine.
