### ISSUE TITLE
Chrome keeps indicating 'loading' status

### ISSUE THREAD

**Issue by b2times4** [webpack/webpack#9717]
# Bug report

**What is the current behavior?**
I know this is a shot in the dark, but here goes anyhow:
I have a SPA in React (Next.js) that is using webpack 4.39.0 and hot reloading.
When I load the page on localhost, the chrome spinner (where the favicon should be) on top of the tab keeps spinning.
Also - the reload button is showing an X (to stop loading of the page) - while the page has already (visually at least) fully loaded.

Remarkable behavior is that when I go to another tab and come back to the 'problematic tab' the 'fake loading' stops and I see in Console that 'webpack-hmr?page=/' has been called again (for the second time on that page).

So whenever 'webpack-hmr?page=/' is called a second time (after tab switch) the problem of the fake loading goes away.

Another remark > When I deploy my app to Now the problem goes away. It's only on localhost.

**If the current behavior is a bug, please provide the steps to reproduce.**
- this behavior started after activating auth0, I'll be posting there too, but I would love to get insights into why webpack seems related to this issue (second call to webpack 'fixes' the loading state)

**What is the expected behavior?**
The loading symbol should not appear in my browser and the reload button should display the reload button, not an X to stop loading.

**Other relevant information:**
webpack version:  4.39.0
Node.js version: 10.16.3
Operating System: macOS High Sierra
Additional tools: Chrome Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by b2times4** [comment]
thanks for chiming in @sokra 
This can be closed.
I would have come back here if I had known what the original issue was.
Truth be told : I refactored my entire application, so it's hard to tell what actually was the issue here.

This can be closed.

**Comment by simonbuchan** [comment]
I found this happens if chrome devtools has "disable cache" enabled, on one project. No idea what's up with that.
