### ISSUE TITLE
unknown filename with some different configuration in optimization.splitChunks

### ISSUE THREAD

**Issue by geekxue** [webpack/webpack#9722]
# Bug report
> The configuration of optimization.splitChunks  is 
```
optimization: {
        usedExports:true,
        splitChunks: {
            chunks: "all",
            cacheGroups: {
                test:/[\\/]node_modules[\\/]/,
            }
        }
    },
```

**What is the current behavior?**
It works and bundle the chunk with the name "test~lodash.chunk.js"

**If the current behavior is a bug, please provide the steps to reproduce.**

The office website about SplitChunksPlugin tells us that "splitChunks.cacheGroups.{cacheGroup}.test" controls which modules are selected by this cache group. It only chooses modules but not defines the name of chunk

**What is the expected behavior?**
If the code with such configuration should bundle the chunk with the name "vendors~lodash.chunk.js"

**Other relevant information:**
webpack version:  4.31.0
Node.js version: v10.15.1
Operating System: Mac OS 10.14.6
Additional tools:

**Comment by sokra** [comment]
``` diff
     optimization: {
         usedExports:true,
         splitChunks: {
             chunks: "all",
             cacheGroups: {
+                vendors: {
                     test:/[\\/]node_modules[\\/]/,
+                }
             }
         }
     },
```

**Comment by evilebottnawi** [comment]
@sokra maybe we can improve schema?
