### ISSUE TITLE
devtool: 'source-map' not work properly on somewhere

### ISSUE THREAD

**Issue by Aqours** [webpack/webpack#9725]
# Bug report

![QQ截图20190923184341](https://user-images.githubusercontent.com/8586286/65420322-6d4d6d80-de33-11e9-9a24-ec8d3657901c.png)

I could not add breakpoint at `if` statement on latest Chrome or Firefox when I use webpack(devtool: 'source-map')+TypeScript(sourcemap: true)+ts-loader tool chain.

**What is the current behavior?**
I could not add breakpoint at `if` statement.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Clone repo: https://github.com/Semibold/Apex-Launcher.git
2. `cd Apex-Launcher`
3. `npm run local -- --open`
4. search and debug `clause.tsx` file on browser
5. try to add breakpoint at line 6: `if (DEBUG) {`

You could try to change `--devtool` argument of npm `local` script in package.json, then repeat step 3~5.

**What is the expected behavior?**

![ok](https://user-images.githubusercontent.com/8586286/65420495-e220a780-de33-11e9-88cd-bfa3dcd64cb3.png)

I could add breakpoint at `if` statement.

**Other relevant information:**
webpack version:  4.39.3
Node.js version: v10.10.0
Operating System: Windows 10.1903
Additional tools: TypeScript 3.6.3 + ts-loader 6.1.0

**Comment by sokra** [comment]
Production optimizations like minimizing can rewrite your code in an optimized way so some statementno longer exist in the generated code.

I.e. `if(DEBUG)` is probably removed in production mode, and you can't set breakpoints on not existent code. Try to debug in development mode, or disable minimizing (`optimizarion.minimize: false`)

**Comment by Aqours** [comment]
Thanks. It seems you're right.
