### ISSUE TITLE
Option to skip initial build when using watch flag

### ISSUE THREAD

**Issue by alshdavid** [webpack/webpack#9730]
## Feature request

Option to skip initial build when using watch flag.

**What is the expected behavior?**

When `--watch --skip-initial-build`, the `skip-initial-build` flag tells webpack not to build initially, but instead build on subsequent detected changes.

**What is motivation or use case for adding/changing the behavior?**

When working with mono-repos that have multiple packages where some packages depend on higher level packages, developers must build the top level dependencies first, then watch everything.

So imagine there are two packages a and b
b depends on a, so to successfully build b, a must already be built.

Developers would:
build a
watch a && watch b

b will automatically rebuild when it detects a change to a, which the initial build from watching a will produce.
This triggers a waterfall of builds when starting.

a, b, a, b

You can only imagine how bad it gets in projects with a few too many packages

If a developer could skip the initial building on a watch the flow would be

build a
build b
watch skip a && watch skip b

**How should this be implemented in your opinion?**
**Are you willing to work on this yourself?**

Added a pull request
https://github.com/webpack/webpack/pull/9735

**Comment by sokra** [comment]
We can't skip the initial build as it's needed to figure out dependencies that need to be watched.

We could skip the initial emit.

But I think the better way to solve this is to avoid emitting assets if it matches the file on disk. This won't require a flag and will speed up all builds when assets already exist.

**Comment by alshdavid** [comment]
That's fair. The change in my PR only skips the initial emit behind a flag.

Great idea. Any clues on where that belongs? I might spend some time trying to add it in.

**Comment by alshdavid** [comment]
Alright, I have changed the option in my PR to `watchOptions.skipInitialEmit = false` and added tests to cover the behaviour.

https://github.com/webpack/webpack/pull/9735

**Comment by alshdavid** [comment]
Hey, any updates on this?

**Comment by evilebottnawi** [comment]
bump

**Comment by giulianok** [comment]
updates on this? very needed

**Comment by goldmont** [comment]
+1

**Comment by 1aurabrown** [comment]
+1

**Comment by RobbySingh** [comment]
Don't know how long this request will take. I wanted the feature so I had a look at the merge request.

The request itself is fairly simple. Though it's not recommended, you can apply the changes yourself. Just be aware that these changes will be overwritten during webpack updates 

https://github.com/webpack/webpack/pull/9735/files#

**Comment by jonahbron** [comment]
Bump

**Comment by alexander-akait** [comment]
I want to close it in favor https://github.com/webpack/webpack/issues/4991, because duplicate
