### ISSUE TITLE
context module API fails to exclude files

### ISSUE THREAD

**Issue by abhijithvijayan** [webpack/webpack#9733]
# Bug report

**What is the current behavior?**
context module API fails to exclude files in a directory that doesn't match the pattern

**If the current behavior is a bug, please provide the steps to reproduce.**
When used in Next.js [project](https://github.com/abhijithvijayan/abhijithvijayan.in/blob/master/pages/index.js)

```
const testContent = await importAll(require.context('../markdown/', true, /^(?!sample).*\.(md)$/));

console.log(testContent);
``````

This produces the content of `sample.md` along with contents of other markdown files even though regEx doesn't match the pattern

**What is the expected behavior?**

Exclude reading contents from sample.md files.

**Other relevant information:**
webpack version:  
Node.js version: 10.16.0
Operating System: Ubuntu 18.04.3
Additional tools:
	Next.js: 9.0.5

**Comment by evilebottnawi** [comment]
@abhijithvijayan link above has reproducible example?

**Comment by abhijithvijayan** [comment]
@evilebottnawi I will attach the link soon.

**Comment by sokra** [comment]
Try: `const testContent = await importAll(require.context('../markdown/', true, /^\.\/(?!sample).*\.(md)`

**Comment by abhijithvijayan** [comment]
@sokra Thanks. it works.
