### ISSUE TITLE
LimitChunkCountPlugin

### ISSUE THREAD

**Issue by vankop** [webpack/webpack#9734]
# Bug report

**What is the current behavior?**

LimitChunkCountPlugin still has `minChunkSize` as input parameter, but it does not use it anymore

**What is the expected behavior?**

As I understand it is a back forward compatibility, maybe for `webpack@5` breaking changes allowed

**Other relevant information:**
webpack version:  5 and 4

**Comment by evilebottnawi** [comment]
Yep, PR welcome in next

**Comment by sokra** [comment]
You can also PR that to master, as LimitChunkCountPlugin never had a `minChunkSize` option. I think this was a typo when the schemas were created.
