### ISSUE TITLE
code-splitting of different module versions

### ISSUE THREAD

**Issue by AndyOGo** [webpack/webpack#9739]
We `import` two mini-apps, both depend upon [`react-intl`](https://github.com/formatjs/react-intl), but each are using different versions of it (which leads to breaking changes)
- A: `react-intl`@**^2.7.3**
- B: `react-intl`@**^3.1.8**

[`SplitChunksPlugin`](https://webpack.js.org/plugins/split-chunks-plugin/) does not seem to be aware of the difference of the two 🤔 
It would be great if the official docs would clearly state how different module versions are handled, especially regarding breaking changes/major version numbers, is [`SplitChunksPlugin`](https://webpack.js.org/plugins/split-chunks-plugin/) aware of `package.json`'s dependecies version?

This issue has been raised  several times, but I think is not handled completely:
- https://github.com/webpack/webpack/issues/646
- https://github.com/webpack/webpack/issues/6505

**Comment by sokra** [comment]
What did you try?

Nothing in webpack cares about package version at all? webpack is file-oriented, it only cares about files and paths.

**Comment by AndyOGo** [comment]
@sokra Thanks for your clarification.

We build something similar to a micro-frontend architecture.
As we compose those micro-SPAs, we want to extract common chunks by `SplitChunksPlugin`.
Now each of these micro-SPAs are developed by different Teams and it's not guaranteed that they use the same version of shared modules.

**Comment by sokra** [comment]
Do you use a custom splitChunks configuration? Or the default one?

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by AndyOGo** [comment]
Thanks for your quick answer.
Yes we have a custom config your splitChunks.
I will need to contact a colleague to provide all requested information.

**Comment by LucaMele** [comment]
Here the config that we use:

```
const UglifyJSPlugin = require("uglifyjs-webpack-plugin"); // eslint-disable-line
const TerserPlugin = require("terser-webpack-plugin");
const autoprefixer = require("autoprefixer"); // eslint-disable-line
const path = require("path");
const webpack = require("webpack"); // eslint-disable-line
const { sep } = path;

const entry = {
  aaaa: "./aaaa/index.js",
  bbbb: "./bbbb/index.js",
  cccc: "./cccc/index.js",
  dddd: "./dddd/index.js",
  eeee: "./eeee/index.js",
  ffff: "./ffff/index.js",
  gggg: "./gggg/index.js",
  hhhh: "./hhhh/index.js"
};

const keys = Object.keys(entry);

const excludeRegexStr = keys.map(key => `(?!${sep}${key})`);

// dont want to transpile the pods itself
const excludeRegex = new RegExp(
  `node_modules${sep}@axa-ch(?!${sep}patterns-library)${excludeRegexStr.join(
    ""
  )}`
);

const entryRegexArr = keys.map(
  key => new RegExp(entry[key].replace("./", "").replace("/", sep))
);

const loaders = {
  css: {
    loader: "css-loader",
    options: {
      minimize: true
    }
  },
  postcss: {
    loader: "postcss-loader",
    options: {
      plugins: () => [
        autoprefixer({
          browsers: ["last 2 versions"]
        })
      ]
    }
  },
  sass: {
    loader: "sass-loader",
    options: {
      includePaths: [path.resolve(__dirname, "./src")]
    }
  }
};

module.exports = {
  // mode NONE as we stricly need NamedChunksPlugin due to incremental deploy. The rest of the seetings respect production mode as defined here:
  // https://webpack.js.org/concepts/mode/
  mode: "none",
  plugins: [
    new webpack.NamedChunksPlugin(),
    new TerserPlugin(/* ... */),
    new webpack.DefinePlugin({
      "process.env.NODE_ENV": JSON.stringify("production")
    }),
    new webpack.optimize.ModuleConcatenationPlugin(),
    new webpack.NoEmitOnErrorsPlugin()
  ],
  entry,
  performance: {
    hints: "warning"
  },
  output: {
    filename: "[name].bundle.js",
    path: path.resolve(__dirname, "dist"),
    pathinfo: false
  },
  optimization: {
    namedModules: true,
    namedChunks: true,
    nodeEnv: "production",
    flagIncludedChunks: true,
    occurrenceOrder: true,
    sideEffects: true,
    usedExports: true,
    concatenateModules: true,
    noEmitOnErrors: true,
    checkWasmTypes: true,
    minimize: true,
    minimizer: [new UglifyJSPlugin({})],
    runtimeChunk: "single",
    splitChunks: {
      hidePathInfo: true,
      name: "common",
      cacheGroups: {
        vendors: {
          name: "vendors",
          chunks: "initial",
          test: /[\\/]node_modules[\\/](?!@axa-ch)|[\\/]node_modules[\\/](@axa-ch\/patterns-library-polyfill)/,
          minChunks: 2,
          priority: -10,
          reuseExistingChunk: true
        }
      }
    }
  },
  module: {
    rules: [
      {
        test: /\.m?js$/,
        include: [
          // Midgard will transpile this modules from es6 to es5
          ...entryRegexArr,
          excludeRegex,
          new RegExp(`node_modules${sep}lit-html`),
          new RegExp(`node_modules${sep}lit-element`),
          new RegExp(`node_modules${sep}react-intl`)
        ],
        use: {
          loader: "babel-loader",
          options: {
            babelrc: false,
            presets: [
              [
                "@babel/preset-env",
                {
                  modules: false,
                  targets: {
                    browsers: ["last 2 versions", "safari >= 8", "not ie <= 10"]
                  }
                }
              ]
            ],
            plugins: [
              "@babel/plugin-proposal-class-properties",
              [
                "@babel/plugin-transform-runtime",
                {
                  absoluteRuntime: false,
                  corejs: false,
                  helpers: true,
                  regenerator: true,
                  useESModules: false
                }
              ]
            ]
          }
        }
      },
      {
        test: /\.scss|\.css$/,
        use: [loaders.css, loaders.postcss, loaders.sass]
      },
      {
        test: /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/,
        use: [
          {
            loader: "file-loader",
            options: {
              name: "[name].[ext]",
              outputPath: "../assets/fonts/"
            }
          }
        ]
      }
    ]
  },
  resolve: {
    extensions: [".js", ".scss", ".css"],
    modules: [path.resolve(__dirname), "node_modules"]
  }
};

```

**Comment by sokra** [comment]
ok, you specified to put (nearly) all node_modules into the `vendors` chunk. So will be put both versions of `react-intl`. I still don't understand the question? Which behavior are you expecting?

**Comment by AndyOGo** [comment]
Thanks for you quick  answer.

Our question is which versions of `react-intl` will be loaded in package **A** and **B**.
Let's assume this pseudocode:

**NPM Package A:**
```js
import reactIntl from 'react-intl';
// expect to import version ^2.7.3
```

**NPM Package B:**
```js
import reactIntl from 'react-intl';
// expect to import version ^3.1.8
```

**Bundled App A:**
```js
webpack_require('react-intl', ...);
// expected to load version ^2.7.3
```

**Bundled App B:**
```js
webpack_require('react-intl', ...);
// expected to load version ^3.1.8
```

Questions is which versions of `react-intl` get bundled into `vender.js` and which versions get loaded by each apps **A** and **B**:

- [ ] **A**  load `react-intl` @ ^2.7.3 and **B** loads `react-intl` @ ^3.1.8 (expected)
- [ ] **A** and **B** both load `react-intl` @ ^2.7.3 (not expected)
- [ ] **A** and **B** both load `react-intl` @ ^3.1.8 (not expected)

**Comment by sokra** [comment]
> * **A**  loads `react-intl` @ ^2.7.3 and **B** loads `react-intl` @ ^3.1.8 (expected)

This one, everything else would break modules.

`splitChunks` doesn't change the behavior of modules (in any configuration)

**Comment by LucaMele** [comment]
We have a different experience. I thought as well it should work like this but in our case it doesn't. In the next days I will try to make a sandbox

**Comment by sokra** [comment]
yeah, please make some repro repo

**Comment by Hardcore0331** [comment]
How to get the version of npm modules? We have the similar problem, we want to share a common js file by several projects, but only want the particular version of npm moduel into the file.

**Comment by AndyOGo** [comment]
Dear @webpack-bot , please dont close this 🙏

**Comment by nayeembadhusha** [comment]
@LucaMele @sokra @AndyOGo I also have similar issue of having multiple versions of gridstack in a particular micro frontend. i'm not having an idea how to make this work will multiple version, As everything resides in the window object we are trying to replace  the versions with a alias name.

**Comment by vankop** [comment]
duplicate of https://github.com/webpack/webpack/issues/985

**Comment by AndyOGo** [comment]
@vankop This is not about linked NPM modules. This is about different module versions. Is it really a duplicate?

**Comment by vankop** [comment]
yes, title is misleading.. but this is all about bundling duplicate packages.
Also https://github.com/webpack/webpack/issues/8886 https://github.com/webpack/webpack/issues/5593
