### ISSUE TITLE
How to exclude es2015 modules in webpack externals?

### ISSUE THREAD

**Issue by jeffersonvivanco** [webpack/webpack#9740]
Hi, I've been trying to find the answer for this but I cannot find it anywhere. Does anyone know how I can add a es2015 module called "@module/core" to webpack externals? I get the error invalid char "@"? Thank you in advance.

**Comment by sokra** [comment]
`externals: ["@module/core"]`?

**Comment by jeffersonvivanco** [comment]
I tried that but I get this error. I tried it with '@angular/core'. 

ERROR in main-es2015.js from Terser
Unexpected character '@' [main-es2015.js:101,17]

**Comment by sokra** [comment]
Seem like you missing a valid `output.libraryTarget` configuration. If you build an CommonJs module (and want externals to be `require`d) you need `output.libraryTarget: "commonjs2"`
