### ISSUE TITLE
wrong doc or wrong typedefine file.

### ISSUE THREAD

**Issue by vipcxj** [webpack/webpack#9744]
# Bug report

**What is the current behavior?**
No `resolverFactory` under `compiler` when using typescript to create a plugin. but the [document](https://webpack.js.org/api/resolvers/) say `resolverFactory` should be there.

**If the current behavior is a bug, please provide the steps to reproduce.**
type `compiler.resolverFactory` will cause error in typescript.

**What is the expected behavior?**
no error, or fix the document.

**Other relevant information:**
webpack version:  4.41.0
Node.js version: 
Operating System: 
Additional tools:
@types/webpack version: 4.39.1

**Comment by sokra** [comment]
There is a `resolverFactory` in the Compiler. Send a PR to the typings.
