### ISSUE TITLE
Describe index and index2 properties of different data structures

### ISSUE THREAD

**Issue by goganchic** [webpack/webpack#9749]
## Feature request

**What is the expected behavior?**

Purpose of index and index2 properties is clear.

**What is motivation or use case for adding/changing the behavior?**

I'm exploring source code of Webpack. There are two variables `index` and `index2` used in different data structures (module, chunk group) filled during [building chunk graph](https://github.com/webpack/webpack/blob/master/lib/buildChunkGraph.js). If I'm not mistaken `index` is a position of module in a chunk group and `index2` is a some sort of reversed position (?). For me as a newcomer it's difficult to understand the purpose of these fields, e.g. why `index2` is required? Why can't we just use `-index` or something like this. It will be much more easy if there will be short explanation in the code or at least names of these variables. If someone help me to understand purpose of these variables better I can try to add such description myself.

Unfortunately there is almost no chance to get this info from gitter chat or stackoverflow because only few developers need it and can explain.

**How should this be implemented in your opinion?**

Rename variables if it possible and add comments to the code.

**Are you willing to work on this yourself?**
yes

**Comment by sokra** [comment]
They were renamed to preOrderIndex and postOrderIndex in the `next` branch. Hope this makes it more clear that these are indices for the two different graph traversal orders.

**Comment by goganchic** [comment]
@sokra would you please tell me a bit more, how can I use these variables in plugins? Can you give me an example of task which requires these variables (graph traversal is very general example)? Maybe it's an internal variables and its shouldn't be used in plugins?

**Comment by sokra** [comment]
i. e. the mini-css-extract-plugin uses `index2` to sort styles topologically.

**Comment by goganchic** [comment]
@sokra is it correct to say that index is a position of module in chunk group if we count from the beginning and index2 is a position of module in chunk group if we count from the end? So it's not a graph, it's some sort of list.

**Comment by sokra** [comment]
No that's not correct.

Take a look at this wiki entry: https://en.wikipedia.org/wiki/Tree_traversal#Pre-order_(NLR)

Pre-order vs post-order.

It's a bit more involved, because the module graph is a graph not a tree (it can have circular references and multiple incoming reference for a node)

If all modules would be EcmaScript modules then post-order (index2) is the execution order.

If all modules would be CommonJs modules then pre-order is the order in which execution of the module starts. Execution of modules finish in post-order.

**Comment by sokra** [comment]
1. Chunk groups are the logical elements that are loaded and executed. Chunks are only deliver units. A chunk could occur in multiple chunk groups that have different execution orders of modules.

2. I think this never happen, as this algorithm creates the chunk groups.

**Comment by evilebottnawi** [comment]
bump

**Comment by goganchic** [comment]
@evilebottnawi in master branch index and index2 are already renamed so we can close this issue
