### ISSUE TITLE
deprecated API

### ISSUE THREAD

**Issue by vankop** [webpack/webpack#9755]
## Feature request

**What is motivation or use case for adding/changing the behavior?**

Diving into `webpack@5` sources I found out a lot of different methods to deprecate getters/setters/methods. For instance:
https://github.com/webpack/webpack/blob/next/lib/ModuleGraph.js#L1142
https://github.com/webpack/webpack/blob/next/lib/Chunk.js#L100
https://github.com/webpack/webpack/blob/next/lib/Module.js#L635
https://github.com/webpack/webpack/blob/next/lib/ChunkGroup.js#L551

**How should this be implemented in your opinion?**

Looks like most use cases could be solved with something like:
```typescript
deprecateFn(
     fn: function,
     {
          reason: "renamed" | "removed" | "moved" | "refactored",
          release: "major" | "minor" = "major", // maybe it is useful
          comment?: string,
          use?: string|string[]
     }
);

deprecate(
   class,
   properties: {[k: string]: {reason, comment?, use?, release?, fn?}}
)
```

So usage will looks like:
https://github.com/webpack/webpack/blob/next/lib/Module.js#L635
```typescript
deprecate(
   Module,
  {
       isUsed: {
           reason: "refactored",
           use: ["getUsedName", "isExportUsed", "isModuleUsed"]
      }
  }
)
```

https://github.com/webpack/webpack/blob/next/lib/ChunkGroup.js#L551
```typescript
ChunkGroup.prototype.getModuleIndex = deprecateFn(
   ChunkGroup.prototype.getModulePreOrderIndex,
  {
       reason: "renamed",
       comment: "to getModulePreOrderIndex"
  }
)
```

I think API design could be more flexible, my design is just to show some examples + I think deprecated API must use standard `util.deprecate` under the hood.

Maybe it is useful for other `webpack` ecosystem packages, too.

**Are you willing to work on this yourself?**
probably

**Comment by evilebottnawi** [comment]
bump

**Comment by vankop** [comment]
I don't know.. Lets keep it closed
