### ISSUE TITLE
[HMR] Hot Module Replacement is disabled after v4.40.3

### ISSUE THREAD

**Issue by phaistonian** [webpack/webpack#9757]
# Bug report

After upgrading from 4.40.2 to 4.40.3 or higher, this comes up.

![image](https://user-images.githubusercontent.com/796530/65862101-30730080-e376-11e9-9cdc-72ca33f44ed0.png)

As seen in the releases, 4.40.3 fixes an HMR-related issue, but somehow it has also triggered this one.

Dowgrading to 4.40.2 resolves the issue.

**Other relevant information:**
webpack version:  v4.40.3
Node.js version: 11.10.0
Operating System: OSX
Additional tools:

**Comment by phaistonian** [comment]
@sokra It's going to be tricky to _reduce_ the project to a small repo, but I will try when I get some time.

In case it's useful: I am not using webpack dev server, webpack bundling in dev mode involves using `webpack-dev-middleware` and `webpack-hot-middleware`.

**Comment by evilebottnawi** [comment]
I think problem in webpack-hot-middleware, it will be incompatibility with latest webpack@5 and need updated

**Comment by atoztoa** [comment]
The following was added to `HotModuleReplacementPlugin.js:153` in version `4.40.3`, which is causing the issue. It is comparing 2 complex objects with `!==`. Removing that fixes the error and everything is good.

```
// This applies the HMR plugin only to the targeted compiler
// It should not affect child compilations
if (compilation.compiler !== compiler) return;
```

**Comment by JoshRobertson** [comment]
Confirmed this broke our build. Had to pin to 4.40.2

**Comment by evilebottnawi** [comment]
It is expected behavior now, i strongly recommend don't pin webpack version, we need resolve issue, please create reproducible test repo

**Comment by xcv58** [comment]
> The following was added to `HotModuleReplacementPlugin.js:153` in version `4.40.3`, which is causing the issue. It is comparing 2 complex objects with `!==`. Removing that fixes the error and everything is good.
> 
> ```
> // This applies the HMR plugin only to the targeted compiler
> // It should not affect child compilations
> if (compilation.compiler !== compiler) return;
> ```

I can confirm it fixes the issue on my end.

**Comment by Curzy** [comment]
when i test this with

```
console.log(JSON.stringify(compilation.compiler) === JSON.stringify(compiler))
```
two compilers are deeply equal but in diferrent reference how do i fix it ?

**Comment by vipcxj** [comment]
The same issue, and fix through just add a `// `, need pr?

**Comment by michaelzangl** [comment]
Pinning webpack to 4.40.2 solves it for my project, too. Current webpack version (4.41.2) won't work.

using webpack-dev-server: 3.9.0

**Comment by faergeek** [comment]
I could provide minimal case for reproduction of that issue. Is it still needed? I get this error with HMR on the server

**Comment by faergeek** [comment]
Or can someone guide me on how to contribute? From which branch to start off? I can try to bissect and fix it by myself, knowing exactly where it happened the first time

**Comment by faergeek** [comment]
Can somebody help me in setting up proper dev env for webpack? I followed [this guide](https://github.com/webpack/webpack/blob/master/_SETUP.md), but after linking and trying to use it in my reproduction project, it starts to complain about absent webpack-cli and suggests to install it, but it can't. It seems `webpack` bin from `webpack` package just overrides bin from `webpack-cli`. `--no-bin-links` doesn't help. I'm not sure how to do that properly yet, it's the first time I use `yarn link`, but would like to try to fix this bug

**Comment by faergeek** [comment]
@sokra here's a [repo](https://github.com/faergeek/webpack-ssr-hmr-boilerplate) with reproduction. Currently webpack is pinned to 4.40.2. If you update it to 4.40.3, then when you run `yarn run dev:browser`, you'll see the problem. Hope that helps. Or you could help me with dev env setup (see above) and I'll try to narrow down what's causing this and contribute bugfix. It would be awesome 👍

**Comment by Curzy** [comment]
I've just guessed why `Hot Module Replacement is disabled` error caused

when we are using webpackDevServer or Middlware with this pattern
```
const compiler = webpack(config);
const devServer = new WebpackDevServer(compiler, options)
```

compiler in WebpackDevServer and compiler in webpack is deeply equal, because made with same webpack config

but have different references (made by webpack cli/your devServer code)

@phaistonian @sokra @faergeek (thanks for example repo)
