### ISSUE TITLE
Building for multiple environments with a single task

### ISSUE THREAD

**Issue by castasint** [webpack/webpack#9758]
**Do you want to request a *feature* or report a *bug*?**
I do not think my problem is a bug. It could very well be a feature request or somebody already has a solution to it and just that I'm unable to figure out the right way.

**What is the current behavior?**
In my app based on React, I have an environment file where I store certain configurable fields/items like URL for an environment. We've 5 environments to work with - DEV, TEST, UAT, STAGE, and PROD.  Currently, we change the value in the .env file for each of the environments and take a build.(The O/p directory in the webpack config is the same for all environments. We clean it up before generating a build for a given environment) 
**If the current behavior is a bug, please provide the steps to reproduce.**
Definitely, this is not a bug. 

**What is the expected behavior?**
Is there a way for me to issue a single command, and that command would generate the output for different environments?
**If this is a feature request, what is motivation or use case for changing the behavior?**
I am sure there will be people out there having a similar issue. If there is a solution present already, please help with it. Otherwise, this seems to be a genuine use case which could be a feature request. 
**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
OS: Windows 10
NodeJs: 10.16.3(LTS)
Webpack : 4.28.3

**Comment by evilebottnawi** [comment]
Maybe this https://github.com/webpack/webpack/tree/master/examples/multi-compiler?

**Comment by castasint** [comment]
This looks very similar to my problem but the thing that is missing/perhaps I didn't understand is - how do I tell the compiler to go to XYZ(environment file) for DEV and some ABC for TEST, and could be any other file for STAGE...

**Comment by evilebottnawi** [comment]
You can write own logic for this, we can't encapsulate this logic in webpack because it is out of scope

**Comment by sibelius** [comment]
I'd like to generate builds like this

plugin-dev.js
plugin-prod.js

only using multicompiler is this possible?

https://twitter.com/sseraphini/status/1314201201945112578

**Comment by evilebottnawi** [comment]
Yes, multi compiler mode, I think we will improve it in future, allow to define config for each entry (just sugar)

**Comment by sibelius** [comment]
maybe `plugin-[env].js`
