### ISSUE TITLE
detect `watchMode` in loader context

### ISSUE THREAD

**Issue by iamolegga** [webpack/webpack#9763]
## Feature request

**What is the expected behavior?**
It should be possible to detect `watchMode` inside loader context.

**What is motivation or use case for adding/changing the behavior?**
For now it's possible to detect `watchMode` inside loader context as `this._compiler.watchMode`. But `_compiler` property is marked as deprecated, so there should be one more variant of doing this.

**How should this be implemented in your opinion?**
It could be implemented as `watchMode` property on calling context.

**Are you willing to work on this yourself?**
yes

**Comment by evilebottnawi** [comment]
Just for information - what is use case?

**Comment by iamolegga** [comment]
> Just for information - what is use case?

I'm working on https://github.com/iamolegga/prettier-loader, so there is issue with double compilation in watchMode (https://github.com/iamolegga/prettier-loader/issues/1), now I'm working on some solution, but I need to know somehow, is loader working in watchMode or not

**Comment by iamolegga** [comment]
Also @evilebottnawi maybe you can help me: is it possible somehow to prevent new compilation from a loader or from a plugin at least?
I've read all the docs of loader API and plugin API and compilation and compiler, and could not find something about it

**Comment by evilebottnawi** [comment]
> is it possible somehow to prevent new compilation from a loader or from a plugin at least?

it is bad idea and you should not do this

**Comment by sokra** [comment]
Loader should not write to their input files. Loader do transformations on source code. Loaders should not change behavior in watch mode. `this._compiler` is not deprecated but private.

**Comment by sokra** [comment]
I don't think it makes sense to add watchMode as official flag

**Comment by iamolegga** [comment]
> this._compiler is not deprecated but private

But according to [docs](https://webpack.js.org/api/loaders/#deprecated-context-properties) it's under title `deprecated`.

Anyway, I get your point. Thanks for help

**Comment by iamolegga** [comment]
And the last one

> Loader should not write to their input files

Just wanted to let you know, that [eslint-loader](https://github.com/webpack-contrib/eslint-loader#fix), with more than 2 millions installs per week, does write to input files, and also has the same problem of double compilation

**Comment by evilebottnawi** [comment]
@iamolegga he used as `pre` loader

**Comment by iamolegga** [comment]
> @iamolegga he used as `pre` loader

Does it matter? Just checked it, regardless of having `enforce: "pre"` it compiles twice in both cases

**Comment by evilebottnawi** [comment]
@iamolegga yes, should be no twice compilation

**Comment by iamolegga** [comment]
@evilebottnawi https://github.com/iamolegga/eslint-loader-compile-twice-demo

**Comment by evilebottnawi** [comment]
@iamclaytonray please open issue in `eslint-loader`, anyway i recommend do not use beautifiers/linters/test-runners for webpack as loader or plugin, it is decrease compilation and very annoying at the time of development, also webpack not designed for it. This loaders/plugins exist due historical reasons. Almost all of these tools have CLI/node API so you can run lint process before running webpack using `npm/yarn scripts` or custom script (using node API).

**Comment by iamolegga** [comment]
https://github.com/webpack-contrib/eslint-loader/issues/303

**Comment by iamclaytonray** [comment]
I think you tagged the wrong dude 😉
