### ISSUE TITLE
Webpack cut path in source maps incorrectly

### ISSUE THREAD

**Issue by ilgonmic** [webpack/webpack#9764]
# Bug report

**What is the current behavior?**
Incorrect source maps
Short path
`webpack:///.._imported/baz/original_file`
instead of full path
`webpack:///foo/bar/packages_imported/baz/original_file`

**If the current behavior is a bug, please provide the steps to reproduce.**
`webpack.config.js` is in directory 
`/foo/bar/packages/baz/`

There is other javascript files in directory
`/foo/bar/packages_imported/baz/`
e.g.
`/foo/bar/packages_imported/baz/compiled_file`
Which have their own source maps, and which are required from entry file

Webpack cut original path to
`(webpack:///.._imported/baz/original_file`

**What is the expected behavior?**
Webpack should keep original path without cutting
for example
`webpack:///foo/bar/packages_imported/baz/original_file`

**Other relevant information:**
webpack version:  4.41.0
Node.js version: v12.10.0
Operating System: macOS Mojave 10.14.6
Additional tools:

**Detailed information**
Seems that I found relevant place in `RequestShortener.js`
https://github.com/webpack/webpack/blob/86a2829147c0ae78797b48c121bf5e11a8151562/lib/RequestShortener.js#L19-L22
Should it contain end slash in RegExp?
To produce RegExp
`/(^|!)\/foo\/bar\/packages\//g`
instead of
`/(^|!)\/foo\/bar\/packages/g`

**Comment by sokra** [comment]
Yep an slash should fix that. Send a PR
