### ISSUE TITLE
Transient failure: TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by gkadillak** [webpack/webpack#9766]
# Bug report

**What is the current behavior?**
We experienced a failure on getaround.com yesterday from ~3:35pm - 4pm PST. There was an error in the console:

```
getaround.js:1 Uncaught TypeError: Cannot read property 'bind' of undefined
    at getaround.js:1
    at getaround.js:1
```

This is because of the following two lines in the webpack runtime:

```js
var jsonpArray = window["webpackJsonp"] = window["webpackJsonp"] || [];
var oldJsonpFunction = jsonpArray.push.bind(jsonpArray);
```

`jsonpArray` was returning a function, rather than a list, so `jsonpArray.push` was returning `undefined`. The question that I have is how could this have happened? No changes to the bundle were made during that time and the issue self-resolved. Is it possible that the `window["webpackJsonp"]` line could return a different value?

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Set `window["webpackJsonp"]` to return function, rather than an array.

**What is the expected behavior?**
`window["webpackJsonp"]` should return an array, rather than a function.

**Other relevant information:**
webpack version:  4.39.2
Node.js version: 10
Operating System: macOS Mojave 10.14.6
Additional tools:

**Comment by sokra** [comment]
If you want to be safe you can also change the global variable i. e. by using this:

``` js
{
  output: {
    jsonpFunction: "o3iv79tz90732goag" // use your own random string here
  }
}
```

but this is usually not required.

**Comment by gkadillak** [comment]
Turns out that the root cause was Stripe: https://twitter.com/stripe/status/1179182163482333185

However, that's a great suggestion to avoid this sort of collision in the future @sokra 🙌

**Comment by blaiz** [comment]
Thanks so much for the quick reply @sokra

**Comment by evilebottnawi** [comment]
@sokra I think we can improve this out of scope, what about:
- `search package.json`
- `get name`
- calculate hash of `name`
- use `webpackJsonp[hashOfName]`

Should be safely

**Comment by my9074** [comment]
@sokra I had the same problem with IE8, but chrome is fine。
![image](https://user-images.githubusercontent.com/4555635/74031866-9723bd00-49ed-11ea-9ce2-9c403f158f70.png)
webpack.config.js
```js
output: {
    libraryTarget: 'window',
    path: resolve('dist'),
    filename: '[name].js',
    chunkFilename: '[name].[hash:6].js',
    jsonpFunction: '__ynavi2_webpackJsonp__'
  },
```

**Comment by stevenvachon** [comment]
I'm getting this error and changing `jsonpFunction` isn't fixing anything.

**Comment by vankop** [comment]
@stevenvachon could you provide repro?

**Comment by HandsomeHan515** [comment]
> #9446

IE 8 don't support bind function, add bind polyfill can solve this.

**Comment by asso1985** [comment]
> I'm getting this error and changing `jsonpFunction` isn't fixing anything.

@stevenvachon did you manage to fix this?

**Comment by stevenvachon** [comment]
> @stevenvachon did you manage to fix this?

I'm not working on that project anymore, so it's very likely still not fixed.

**Comment by alexander-akait** [comment]
It means you forget to include runtime code in your html file, run `ls -l ./dist` and look at files

**Comment by petermikitsh** [comment]
I can confirm this fix works in situations where, on a single webpage, one bundle is built with webpack 2.x and another bundle with 4.x. In this case, I added the `output.jsonpFunction` option to the webpack 4.x bundle.
