### ISSUE TITLE
CSS File imported with url imports looses original location

### ISSUE THREAD

**Issue by JustJarethB** [webpack/webpack#9774]
**Do you want to request a *feature* or report a *bug*?**
I believe this to be a bug

**What is the current behavior?**
Take a file within node_modules `file.css` containing style `background: url(default-skin.png) 0 0 no-repeat;`
with the original folder the png exists. When importing `@import "module/file.css"` the file looses reference to the original png location and now looks in the imported location (where it does not exist)

**If the current behavior is a bug, please provide the steps to reproduce.**
I found this with `photoswipe`

1. `npm install photoswipe`
2. inside main css  file `@import "photoswipe/dist/default-skin/default-skin.css";`
3. note build error ```ERROR in ./src/main/css/index.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve './default-skin.png' in '..../src/main/css'```

**What is the expected behavior?**
The file would maintain reference to it's original position and pull the file from the node_modules location
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
macOS 10.14.6
node 10.16.0
webpack 4.41.0
postcss-loader 3.0.0
sass-loader 8.0.0
css-loader 3.2.0

**Comment by evilebottnawi** [comment]
`photoswipe` have invalid url, it is not bug

**Comment by JustJarethB** [comment]
Thanks @evilebottnawi but I don't think it's the url, as when I copy the files to a different location they then get picked up and built (where they then get a url). It's trying to find them in the build directory. Also invalid url wouldn't affect the build, wouldn't it only throw errors on runtime in the browser?
I can still open in css-loader should you like. can you link the github?

**Comment by evilebottnawi** [comment]
@JustJarethB please open issue with reproducible test repo, i am link issue in future or reopen issue if problem will be in webpack

**Comment by jnns** [comment]
@JustJarethB  This worked for me while trying to get Photoswipe into my bundle using Webpack:

```scss
$pswp__assets-path: "../node_modules/photoswipe/src/css/default-skin/";
@import "~photoswipe/src/css/main";
@import "~photoswipe/src/css/default-skin/default-skin";
```

**Comment by AndreasDeveloper** [comment]
> @JustJarethB This worked for me while trying to get Photoswipe into my bundle using Webpack:
> 
> ```css-scss
> $pswp__assets-path: "../node_modules/photoswipe/src/css/default-skin/";
> @import "~photoswipe/src/css/main";
> @import "~photoswipe/src/css/default-skin/default-skin";
> ```

So I spent quite some time looking for a solution and this one would never pop into my head.. Great thing pal. Thanks a lot!
