### ISSUE TITLE
Unexpected end of JSON input while parsing near '...,"husky":"^3.0.2","is'

### ISSUE THREAD

**Issue by launchriot** [webpack/webpack#9779]
# Bug report

**What is the current behavior?**
After running `npm install` (where webpack is included in package.json) or after running `npm install webpack` (where webpack is not included in package.json), I get the following error:

`npm ERR! Unexpected end of JSON input while parsing near '...,"husky":"^3.0.2","is'`

**If the current behavior is a bug, please provide the steps to reproduce.**
Running `npm install` (where webpack is included in package.json) or run `npm install webpack` (where webpack is not included in package.json)

**What is the expected behavior?**
webpack installs and is added to node_modules and package-lock.json

**Other relevant information:**
webpack version:  4.41.0 (but also tried with previous version, as far back as 4.0.0)
Node.js version: v10.15.3
Operating System: macOS Mojave 10.14.6
Additional tools: npm --version 6.11.3

**Comment by launchriot** [comment]
Full log output:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'webpack' ]
2 info using npm@6.11.3
3 info using node@v10.15.3
4 verbose npm-session 90aeb470aa476a5d
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/webpack 1042ms (from cache)
8 silly fetchPackageMetaData error for webpack@latest Unexpected end of JSON input while parsing near '...,"husky":"^3.0.2","is'
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 2340ms
11 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...,"husky":"^3.0.2","is'
11 verbose stack     at JSON.parse (<anonymous>)
11 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
11 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
11 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
12 verbose cwd /Users/avizuber/IdeaProjects/backend/www
13 verbose Darwin 18.7.0
14 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "webpack"
15 verbose node v10.15.3
16 verbose npm  v6.11.3
17 error Unexpected end of JSON input while parsing near '...,"husky":"^3.0.2","is'
18 verbose exit [ 1, true ]
```

**Comment by evilebottnawi** [comment]
Problem on npm side, it looks like someone in your country is blocking the internet, or maybe npm register output invalid information, try contacting with npm technical support, sorry we can't help

**Comment by evilebottnawi** [comment]
Also you cab try to enable/disable internet

**Comment by launchriot** [comment]
the solution ended up being `npm clear cache --force` and then re-running `npm install` 
 ¯\_(ツ)_/¯

**Comment by evilebottnawi** [comment]
maybe old npm client version?

**Comment by gdswapnil11** [comment]
Use
npm cache clean --force

**Comment by ElizeuBraga** [comment]
npm cache clean --force solve my problem

**Comment by Gztabo21** [comment]
npm cache clean --force solve my problem

**Comment by karthik922** [comment]
Try this series of commands. It worked.

`npm cache clean --force`

`npm install npm@latest -g`

`npm install`

I think the issue is with npm.
