### ISSUE TITLE
[Question] : data/code sharing between different chained (pitch) loader 

### ISSUE THREAD

**Issue by LOLdevelopr** [webpack/webpack#9783]
I am trying to understand the main flow of normal and pitch  loader and The docs about this https://webpack.js.org/api/loaders/#pitching-loader is pretty straight forward and clear. 
One Thing I faced missing is about the code or data sharing between different loader using pitch method.
In normal loaders , The output of the prev is input of the next loader. Thats fine !
But in pitch loader,when a loader is in pitch phase, can it share a data to another chained loader who is also a pitch loader.
Example
```
|- a-loader `pitch`
  |- b-loader `pitch` // having a data say x
    |- c-loader `pitch`
      |- requested module is picked up as a dependency
    |- c-loader normal execution
  |- b-loader normal execution
|- a-loader normal execution
```
Now , here if loader `b`'s pitch method have `x` or creates `x` and now want to share this to other loader `c`, Can we get that ? if yes how ? like will it be available in `c`'s pitch method or in default .

Just curious to know, I dont know if there is any specific use-case of this would arise.

**Comment by LOLdevelopr** [comment]
One more doubt, 
As mentioned in the docs, returning from the `pitch` method cancels the execution of the rest of the loaders *(please correct me if I am wrong)*
Then in style loader, it using return in pitch method and I see people often uses style loader chained with css-loader. SO if it cancels the executions, how css-loader is doing stuffs and getting the source code.!

**Comment by sokra** [comment]
Usually loaders should not pass data in the pitch phase.

Loaders can pass data from pitch phase to normal phase with `this.data`. You may access this data from other loaders too (with `this.loaders`), but better reconsider your architecture if this is needed.

Loaders are allowed to modify `this.loaders` in the pitch phase. If you have a pair of loaders that usually work together, you can consider using only the first one and let this one add the other loader to `this.loaders`. This way you may also add `query` arguments to the second loader and this way data can be passed.



> As mentioned in the docs, returning from the `pitch` method cancels the execution of the rest of the loaders

yes

> Then in style loader, it using return in pitch method and I see people often uses style loader chained with css-loader.

It cancels execution, but creates a source file containing the remaining request in a require call.

``` js
// style-loader generated module
const css = require("-!css-loader!./source.css");
doSomethingWith(css);
```

**Comment by LOLdevelopr** [comment]
Sorry for the late reply 

Thanks a lot for your reply just one thing.

> and let this one add the other loader to this.loaders

Can you share one example of any loader doing this. THanks
