### ISSUE TITLE
Source map gets broken after entry name change and rebuild

### ISSUE THREAD

**Issue by andreyvolokitin** [webpack/webpack#9786]
# Bug report

**What is the current behavior?**
There is no problem when the project is built initially. Then if the entry name changes and the project gets rebuilt again — the source map gets broken, it doesn't work properly in chrome dev tools and `sources` property doesn't contain actual sources, but instead the bundle filename from the previous build.

If you delete `node_modules` folder, reinstall dependencies and build project again — generated source map starts to work properly.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. clone [the test repo](https://github.com/andreyvolokitin/webpack-sourcemaps-test), run `npm i` and `npm run build` inside it;
2. open `./dist/index.html` in the browser — source map is working correctly;
3. open `webpack.config.js`, change `entry` name, run `npm run build` again;
4. open `./dist/index.html` in the browser — source map doesn't work. Check the source map itself — the `sources` property contains wrong info;
5. delete `node_modules`, reinstall dependencies, build project again — source map starts to work correctly.

**What is the expected behavior?**
The source map should work correctly after entry name change and rebuild. The `sources` property should contain proper information.

**Other relevant information:**
webpack version:  4.41.0
Node.js version: 11.6.0
Operating System: OS X 10.11.6 (15G22010)
Additional tools:

**Comment by sokra** [comment]
This is a bug in the cache of terser-webpack-plugin.

Deleting `node_modules/.cache/terser-webpack-plugin` restores the good behavior.

@evilebottnawi

**Comment by evilebottnawi** [comment]
Investigate

**Comment by evilebottnawi** [comment]
@webpack-bot move to webpack-contrib/terser-webpack-plugin
