### ISSUE TITLE
WatchIgnorePlugin slows down incremental builds

### ISSUE THREAD

**Issue by pstoica** [webpack/webpack#979]
I tried WatchIgnorePlugin and eventually realized it was causing every change to go through the "build modules" phase for what seemed to be all the modules. When I disabled it, it took the appropriate amount of time to recompile.

**Comment by mindreframer** [comment]
same here, the recompile time goes from ca. 200 ms to  ca 7000ms. Not a great improvement overall...

**Comment by b2whats** [comment]
+1 
plugin not work with cache
