### ISSUE TITLE
react-styleguidist production build broken: Error: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kopax** [webpack/webpack#9794]
I am using Webpack `4.41.0` and I have issue with production build of documentations.

I got all my documentation production build broken for some reason.

Example: https://rollup-umd.github.io/test/

`Error:  RangeError: Maximum call stack size exceeded`

I haven't change anything in my source code. It just happen to be broken. 

I can't remove UglifyJS plugin because `react-styleguidist` forbid it. 

**Current behavior**

After running `npm run styleguide:build`, I have:

```bash
bundle.ebc589be.js:65 Uncaught RangeError: Maximum call stack size exceeded
    at e (bundle.ebc589be.js:65)
    at e (bundle.ebc589be.js:65)
   ...
Show 170 more frames
```

**To reproduce**

- Example: https://rollup-umd.github.io/test
- Local Reproduction:

```
git clone git@github.com:rollup-umd/test.git
cd test
npm i
npm run styleguide:build
npm i -g serve
serve public
# open chrome and http://localhost:5000
```

**Expected behavior**

- Work as in `npm run styleguide`.

**Related information**

It was working 24h ago, since then, I have not change anything in all my sources codes.

**All my production build** in all my projects are down.

I believe (unless I am wrong but to me it is the only valid reason): the dep tree as changed.

For those who ask why I don't have a lock file: It is because we do not use `package-lock.json` in distributed modules, because lock file are for application.

Does anybody have an idea of what changes recently?
Is there a way I can trace and find what cause all my documentations to be broken?

**Comment by evilebottnawi** [comment]
@kopax in dev mode all work fine?

**Comment by kopax** [comment]
Yes in dev mode all work fine. The code is open source as you can see.

I just added a breakpoint in the minified code and went up the trace, and it happen in a library called [color](https://github.com/Qix-/color), exactly [here](https://github.com/Qix-/color/blob/master/index.js#L409).

This file as not been changed since June, and the library where I use it [here](https://github.com/bootstrap-styled/bootstrap-styled/blob/master/src/theme/index.js#L179) as also not changed since February. 

When I run it in development it work fine. Something must have change somewhere in the prod build.

**Comment by evilebottnawi** [comment]
@kopax do you use `uglify-webpack-plugin` or `terser-webpack-plugin`? I can't clone you repo, can you provide public link?

**Comment by kopax** [comment]
Yes we use react-styleguidist that force the use of `uglify-webpack-plugin`:


**To reproduce**

- Example: https://rollup-umd.github.io/test
- Local Reproduction:

```
git clone git@github.com:rollup-umd/test.git
cd test
npm i
npm run styleguide:build
npm i -g serve
serve public
# open chrome and http://localhost:5000
```

**Comment by evilebottnawi** [comment]
> Please make sure you have the correct access rights and the repository exists.

**Comment by evilebottnawi** [comment]
@kopax uglify is abandoned, please switch on terser-webpack-plugin

**Comment by kopax** [comment]
react-styleguidist is not my module.

I have reported the issue here, I can't change that: https://github.com/webpack/webpack/issues/9794#issuecomment-540596331

**Comment by evilebottnawi** [comment]
@kopax 
> Note that react-styleguidist is not my module, I have reported your advice here: #9794 (comment)

Right solution.

 > It seems thay haven't change their code since July: https://github.com/webpack-contrib/uglifyjs-webpack-plugin/releases

The `uglify-js` package is not supported a long time and contains a lot of bugs. The plugin is not officially marked as deprecated in historical/legacy reason (we will do it in near future).

**Comment by kopax** [comment]
I have forked the repo and try to replace `uglify-js` myself. Are you confident this is the issue for me here?

**Comment by evilebottnawi** [comment]
@kopax give me some time, i investigate this

**Comment by kopax** [comment]
Thanks, I will have a try. I have checked and react-styleguidist use `terser-webpack-plugin@1.4.1`, not uglifyJS anymore.

**Comment by evilebottnawi** [comment]
My big recommendation is using lock files in future to avoid this situations.

**Comment by evilebottnawi** [comment]
@kopax you can use dependencies bots (like renovate/dependabot/etc) to run CI on each new package release and automatically update a lock file (you can setup it, how often it should happens - every day, every hour, every week/etc).

It is allow to you:
- catch regressions in dependencies (include transitive dependencies)
- keep stable development environment
- keep all dependencies up to day
- have the same dependencies in yourself and other developers

**Comment by kopax** [comment]
We use greenkeeper, and I am seriously reconsidering to apply your strategy for the futur. 

Are you still trying to understand why the minified build is causing error?

**Comment by evilebottnawi** [comment]
@kopax 
> We use greenkeeper, and I am seriously reconsidering to apply your strategy for the futur.

:+1: 

> Are you still trying to understand why the minified build is causing error?

Sorry, no. I don't have time on this, better if it do maintainers of terser

**Comment by kopax** [comment]
Thanks. I am digging into it. I haven't change my source code so I presume one library in the middle I didn't wrote is causing this, and it is related to terser because without the uglification it work.
