### ISSUE TITLE
Factor out sections that can be

### ISSUE THREAD

**Issue by fresheneesz** [webpack/webpack#98]
There is an impressive ton of code in this project. I have a gut feeling that much of the functionality in here can be separated out into a different project and used on its own (without adding in all the other functionality webpack provides). Its hard to contribute to a project like this. I'd like to look into that, since it might supercede what I'm doing https://github.com/fresheneesz/asyncify , but I'm worried I won't be able to understand the code well enough to contribute.

Don't build a framework, or a monolithic library. Build weakly coupled module ; ) .

**Comment by fresheneesz** [comment]
@altano Ok sorry it took me so long. In addition to what sokra mentioned:

[x] The watcher - one that I suggested elsewhere, and seems that's now done 
[ ] The logic that builds the tree of files that need to be bundled (maybe this is what sokra meant by 'parser'). Specifically, I'd like to use this to help build the deployment package for my project - I want to take a piece from my repo and package all the files it requires to run. This is only one piece in the repo, so packaging together all the files (what i'm currently doing) means there is a LOT of unnecessary copying going on. 

It sounds like sokra has taken this to heart for various internals i'm not familiar with, which is great!

**Comment by jhnns** [comment]
I think, the issue's topic is a more general one @sokra is constantly working on to improve it. Can we close this?

**Comment by fresheneesz** [comment]
@jhnns Yeah we can probably close this. I'll leave it up to you tho.
