### ISSUE TITLE
tree shaking will analyze unused files ?

### ISSUE THREAD

**Issue by zhangyuang** [webpack/webpack#9806]
# Bug report

when i open treeshaking, and use es6 import to load some files which i use, but when i run build, webpack will analyze unused files, although this files which unused will not be containing in dist bundle。due to some files hope be used in Node environment, when i build client bundle, webpack analyze this files cause error

so, i want to ask whether webpack will analyze all files even if some files is unused

**What is the current behavior?**
webpack will not analyze unused files

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/zhangyuang/treeshaking-example

here is my repo
you can run `npm run build`, entry is  `web/entry`
i find  `ykfe-utils/renderToStream.js`  hope be used in node, but when i build client bundle, webpack will analyze the file cause error
![image](https://user-images.githubusercontent.com/17424434/66674997-f8818c80-ec96-11e9-9a46-07d1aab98d95.png)
` to 
```js
// transform
import { getWrappedComponent, getComponent } from 'ykfe-utils'
// to
import  getWrappedComponent from 'ykfe-utils/es/components/getinitialProps'
import getComponent  from 'ykfe-utils/es/getComponent'` 
```
it can be build succeed

**Other relevant information:**
webpack version:  4.19
Node.js version:  10.0
Operating System: 
Additional tools:

**Comment by evilebottnawi** [comment]
@zhangyuang It makes no sense to analyze unused files

Problem what `ykfe-utils`, you try to build `aws-sdk` package what is not supported browser, i can't help because you don't use English and can't understand what you want and why you do this
