### ISSUE TITLE
add comment for __webpack_require__(moduleId)

### ISSUE THREAD

**Issue by chaosim** [webpack/webpack#982]
Webpack is really great!  These two days I tried to replace browserify with webpack, I felt good until I met the code like below: 

    window.app = __webpack_require__(1);
    __webpack_require__(2);
    __webpack_require__(3)(app);
    window.ajax = __webpack_require__(4);
    __webpack_require__(5)(window.app);
    __webpack_require__(6);

I had expected some code like requie('./some/path/to/my/module'), instead of some magic number...
I know it's very hard to change the design, and I were some disappointed and decided to back to browserify. And suddenly I had an idea: Why not comment the code with the module path? Just like below:

    __webpack_require__(2); // ./some/path/to/my/module, or
    __webpack_require__(2 /*./some/path/to/my/module*/); 

This will break nothing, but will be much helpful on reading and debugging...

**Comment by chaosim** [comment]
So cool, webpack has the option to add path info as comment. Thanks a lot. 
I digged into the source code and found the code like below:

	if(outputOptions.pathinfo) comment = "/*! " + requestShortener.shorten(dep.request) + " */ ";
	if(dep.module)
		var content = "__webpack_require__(" + comment + dep.module.id + ")";
	else
		var content = require("./WebpackMissingModule").module(dep.request);

I should have read more document before adding this issue. Please just close this issue .

**Comment by Daniel15** [comment]
In the Webpack CLI, that option is enabled by default in development mode (`-d` command-line parameter) or you can enable it via `--output-pathinfo`. In the config it's `output.pathinfo`.
