### ISSUE TITLE
Webpack prevents/stops console.log from outputting

### ISSUE THREAD

**Issue by natew** [webpack/webpack#9822]
# Bug report

`console.log` from inside a loader isn't output.

I've seen this behavior before and after a few searches I don't seem to see anything here or on SO. Basically, I'm creating a loader and it works in many simple cases. When I plug it into a bigger stack, it fails later on, but for some reason any `console.log` I put inside the loader isn't output.

It *will* output if the file is parsed early on. I'm not sure exactly what seems to prevent console.logs from outputting after a certain point, but it's fairly consistent, I've tried it on a few different stacks and they behavior remains.

**If the current behavior is a bug, please provide the steps to reproduce.**

I'm hoping this is something fairly obvious internally, like webpack re-assigning console.log at some point, so we can just discuss a workaround, better default, or option to prevent it.

**What is the expected behavior?**

I'd expect console.log to always work within loaders, no matter when they are run.

**Other relevant information:**
webpack version:  4.x

**Comment by sokra** [comment]
No we don't change console.log.

Are you using `--progress`? It may overrides console messages, because it overrides itself.

You can try `this.getLogger()` inside of a loader to print logging with the webpack logger instead. It's displayed in the stats. see `stats.logging`.

**Comment by natew** [comment]
Not using `--progress`, tried running webpack in watch mode & build mode, either seems to trigger it. Perhaps some other loader is causing it. It definitely happens after some amount of time, not immediately. Thank you for quick reply.

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by natew** [comment]
This must be something legit, I've removed most stuff from my webpack config and made a simple loader that logs what it's testing like so:

```
        {
          loader: require.resolve('./test'),
          include: function(x) {
            console.log('x is ', x)
            return false
          },
        },
```

And each time I run it will log the first ~20 things before stopping. It still succeeds at building, it just stops logging after a very specific amount of time. You can see it actually stops on different files each time, so it feels like a timer issue more than a logical issue:

```
ℹ ｢wds｣: Project is running at http://localhost:5003/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/nw/projects/motion/orbit/projects/gloss-webpack-test
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/index.js
x is  /Users/nw/projects/motion/orbit/projects/gloss-webpack-test/src/index.tsx
x is  /Users/nw/projects/motion/orbit/projects/gloss-webpack-test/src/index.tsx
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/socket.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/overlay.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/utils/log.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/utils/sendMessage.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/utils/reloadApp.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/utils/createSocketUrl.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/utils/log.js
x is  /Users/nw/projects/motion/orbit/node_modules/@babel/runtime/helpers/objectWithoutPropertiesLoose.js
x is  /Users/nw/projects/motion/orbit/node_modules/@babel/runtime/helpers/extends.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack/hot/log.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/clients/SockJSClient.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/clients/SockJSClient.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/utils/getCurrentScriptSource.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/clients/SockJSClient.js
x is  /Users/nw/projects/motion/orbit/node_modules/url/url.js
x is  /Users/nw/projects/motion/orbit/node_modules/querystring-es3/index.js
x is  /Users/nw/projects/motion/orbit/node_modules/querystring-es3/index.js
x is  /Users/nw/projects/motion/orbit/node_modules/react/index.js
x is  /Users/nw/projects/motion/orbit/node_modules/react-dom/index.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/clients/BaseClient.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/node_modules/strip-ansi/index.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack/hot/emitter.js
x is  /Users/nw/projects/motion/orbit/node_modules/querystring-es3/decode.js
x is  /Users/nw/projects/motion/orbit/node_modules/querystring-es3/encode.js
x is  /Users/nw/projects/motion/orbit/node_modules/url/util.js
x is  /Users/nw/projects/motion/orbit/packages/ui/src/index.ts
```

But if I run again:

```
ℹ ｢wds｣: Project is running at http://localhost:5003/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/nw/projects/motion/orbit/projects/gloss-webpack-test
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/index.js
x is  /Users/nw/projects/motion/orbit/projects/gloss-webpack-test/src/index.tsx
x is  /Users/nw/projects/motion/orbit/projects/gloss-webpack-test/src/index.tsx
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/socket.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/overlay.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/utils/log.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/utils/sendMessage.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/utils/reloadApp.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/utils/createSocketUrl.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/utils/log.js
x is  /Users/nw/projects/motion/orbit/node_modules/@babel/runtime/helpers/extends.js
x is  /Users/nw/projects/motion/orbit/node_modules/@babel/runtime/helpers/objectWithoutPropertiesLoose.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack/hot/log.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/clients/SockJSClient.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/clients/SockJSClient.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/utils/getCurrentScriptSource.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/clients/SockJSClient.js
x is  /Users/nw/projects/motion/orbit/node_modules/url/url.js
x is  /Users/nw/projects/motion/orbit/node_modules/querystring-es3/index.js
x is  /Users/nw/projects/motion/orbit/node_modules/querystring-es3/index.js
x is  /Users/nw/projects/motion/orbit/node_modules/react/index.js
x is  /Users/nw/projects/motion/orbit/node_modules/react-dom/index.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/client/clients/BaseClient.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack-dev-server/node_modules/strip-ansi/index.js
x is  /Users/nw/projects/motion/orbit/node_modules/webpack/hot/emitter.js
x is  /Users/nw/projects/motion/orbit/node_modules/url/util.js
x is  /Users/nw/projects/motion/orbit/node_modules/querystring-es3/decode.js
x is  /Users/nw/projects/motion/orbit/node_modules/querystring-es3/encode.js
x is  /Users/nw/projects/motion/orbit/packages/ui/src/index.ts
x is  /Users/nw/projects/motion/orbit/packages/gloss-theme/src/index.ts
```

I'll try and find an example repo and run it. I've actually noticed this problem for so long I assumed it was just something webpack did and everyone knew that, and perhaps there was some obvious workaround. Realizing this is not normal will let me debug more. It's unfortunate reporting bugs on webpack requires setting up a clean example when it's so incredibly environmentally dependent. Hope that won't require too much.

**Comment by natew** [comment]
@sokra any chance this could be due to synmlinks in a monorepo setup? I tried to replicate the repo this morning and set it up nearly identically. But it seems to log correctly. 

The main difference is that one of them is running in a monorepo and symlinked, where this one I isolated. Will keep on trying.

**Comment by natew** [comment]
Actually, running with progress and that also will stop outputting at the same time. So something really strange. I can't believe I'd always thought this was some eccentricity of Webpack, glad to be solving this. We have a custom loader/plugin so debugging should get far easier.

**Comment by natew** [comment]
Ok figured it out and wasn't webpack (of course), I was running via execa which was buffering things. Makes sense. Thanks for the help.
