### ISSUE TITLE
default cacheGroup not processed when mode set to production

### ISSUE THREAD

**Issue by daveisfera** [webpack/webpack#9838]
# Bug report

**What is the current behavior?**
Chunks for the `default` cacheGroup are generated when `mode` is `development` but not when `mode` is `production`

**If the current behavior is a bug, please provide the steps to reproduce.**
Run build with `mode` set to `development` and notice the chunks for `default` and then run it with `mode` set to `production` and the chunks for `default` aren't built

**What is the expected behavior?**
`default` cacheGroup behaves the same in both `development` and `production`. The workaround I found is to add `enforce: true` to the `default` cacheGroup and then the behavior is consistent

**Other relevant information:**
webpack version:  4.41.0
Node.js version: 10.16.3
Operating System: macOS 10.14.6
Additional tools: babel 7.5.5

**Comment by sokra** [comment]
The size minimum for chunk splitting is higher in production mode (30kb instead of 10kb). That's where the different origins from.

**Comment by daveisfera** [comment]
I just tried removing `optimization.splitChunks.default.enforce: true` and adding `optimization.splitChunks.minSize: 10000` and the build ran for almost 40 minutes and then ran out of memory when `mode` was `production` (which is what would happen before I added `enforce: true`), so I think that something else must be going on

**Comment by evilebottnawi** [comment]
@daveisfera can you create minimum reproducible test repo?

**Comment by daveisfera** [comment]
Is there an example repo that makes multiple bundles that I can use as a starting point to work with and try and get the same behavior going?

**Comment by evilebottnawi** [comment]
@daveisfera no, we need reproduce `almost 40 minutes and then ran out of memory`, so maybe simple example is not suitable

**Comment by daveisfera** [comment]
Unfortunately, the repo is private, so I can't share it. Is there a debug/diagnostic mode that I could run it in to get logs or some other helpful info?

**Comment by sokra** [comment]
increase the memory with `node --max-old-space-size 8192`

**Comment by daveisfera** [comment]
> @daveisfera debugging, you can remove sensitive data/code - just example

Can you be more specific? Are you referring to the [`stats` data](https://webpack.js.org/contribute/debugging/#stats)?

> increase the memory with `node --max-old-space-size 8192`

We're running with `--max-old-space-size 4096` and with `enforce: true` it builds in 5-10 minutes but without it, it takes a long time and runs out of memory

**Comment by evilebottnawi** [comment]
@daveisfera sorry without minimum reproducible test repo we can't help

**Comment by daveisfera** [comment]
I'm willing to help diagnose what's going on here. I just need to guidance on how to generate the debugging logs to send your way. Is it the stats data that I linked to or is there something else that I can provide?

**Comment by evilebottnawi** [comment]
@daveisfera as minimum show configuration, as maximum create reproducible test repo

**Comment by daveisfera** [comment]
How do I show the configuration?

**Comment by evilebottnawi** [comment]
@daveisfera get code from `webpack.config.js`
