### ISSUE TITLE
"target": "node" should prefer "main" over "module" for Node.js ESM support

### ISSUE THREAD

**Issue by FredKSchott** [webpack/webpack#9841]
## Feature request

**What is the expected behavior?**
Node.js ESM packages will ship ESM under "main". Currently, `"target": "node"` prefers "module" over "main". This will most likely be unexpected once Node.js ESM ships. 

**What is motivation or use case for adding/changing the behavior?**

https://github.com/gr2m/universal-user-agent/issues/23 - users having trouble using a universal package built with "module" for browsers/bundlers, and "main" for Node.js. While I understand Webpack's preference for "module" over "main" today, in the future this will be unexpected for packages published with "type": "module" where "main" will be for the Node.js build while "module"' will still be browsers/bundlers or undefined. See: https://nodejs.org/api/esm.html#esm_package_scope_and_file_extensions

Im filing this now because I saw that you had a v5.0 release coming up and an opportunity for a breaking change if you wanted to tackle this proactively.

**How should this be implemented in your opinion?**
N/A

**Are you willing to work on this yourself?**
just providing feedback for the team

**Comment by arlac77** [comment]
@FredKSchott how should a bundler (or node itself) pick the node runtime targeted (none browser) content as [universal-user-agent](https://github.com/gr2m/universal-user-agent) provides two implementations one for the browser and one for node?

**Comment by FredKSchott** [comment]
The current package.json entrypoint landscape is a mess, but can be summarized something like this:
- `main`: always used by Node.js, CJS expected
- `browser`: never used by Node.js, historically used for pre-bundled UMD builds
- `module`: only rule is that it's an ESM version of your code, historically has used by web bundlers for web ESM builds, preferred by most web bundlers

If you're asking me what I think the target should be, I'd recommend:
- `node` - main
- `browser` - module, browser, main
- `none` - module, main

**Comment by sokra** [comment]
> Node.js ESM packages will ship ESM under "main". Currently, `"target": "node"` prefers "module" over "main". This will most likely be unexpected once Node.js ESM ships.

Node.js ESM packages with ship with `"type": "module"`. Once we support that, we will only use `"main"`.

---

Some packages incorrectly use `"module"` to ship a browser build. This is not correct and these packages should be fixed. Sadly this is rarely notices since very few people build for node target.

The `"module"` field spec clearly states that this has nothing to do with environment targeting, but only with ESM vs CJS.

The `"browser"` field is used for browser targeting.

Combining both fields allows you to create entrypoints for browser and node, both with ESM and CJS:

``` js
"main": "./node-cjs.js",
"module": "./node-esm.js",
"browser": {
  "./node-cjs.js": "./browser-cjs.js",
  "./node-esm.js": "./browser-esm.js"
}
```

Not sure if you really need a browser-cjs.js, because all web bundlers support esm.

So you could go with this one:

``` js
"main": "./node-cjs.js",
"module": "./node-esm.js",
"browser": "./browser-esm.js"
```

**Comment by FredKSchott** [comment]
Fwiw almost no tools/bundlers (that I know of) support `"browser": {...}`. I know Rollup doesn't, and I assumed webpack didn't either. 

As you said, there is no "correct" answer here, since "module" is intentionally not specific to any one environment. By your own statement, `"module": "./node-esm.js"` is as incorrect as  `"module": "./browser-esm.js"`. I only filed this issue to give you all a heads up in case you wanted to make this breaking change now in v5 vs. later.

In case you're genuinely curious, "module" is preferred over "browser" by web tools/bundlers since it convey an ESM-browser entrypoint. "browser" has been around much longer and plenty of packages had already started using it to ship UMD and not ESM. For example, Preact's "browser" entrypoint is UMD and breaks when Rollup tries to analyze it, vs. its "module" entrypoint which is ESM.

**Comment by sokra** [comment]
> "module" is preferred over "browser" by web tools/bundlers since tools are better at ESM than UMD.

webpack prefers browser over module.

> For example, Preact's "browser" entrypoint is UMD and can break when Rollup tries to analyze it

There is no `"browser"` field in preacts package.json.

preact is a browser-only package, so you won't use it in node.js anyway. They can use the `main` field for browser code.

**Comment by sokra** [comment]
> > "module" is preferred over "browser" by web tools/bundlers since tools are better at ESM than UMD.
> 
> webpack prefers browser over module.

rollup does also prefer `browser` over `module`: https://github.com/rollup/rollup-plugin-node-resolve/blob/48a496b1f06a08ef4c56c5e8590d1063d4758a14/src/index.js#L72

**Comment by FredKSchott** [comment]
> There is no "browser" field in preacts package.json.

It looks like they just got rid of it for v10, but you can see it in previous versions here: https://unpkg.com/preact@8.5.2/package.json

See a user having trouble bundling when browser > module here:
https://github.com/pikapkg/web/pull/101

> rollup does also prefer browser over module 

You're pointing to the in-code documentation of an optional config property. From the actual README, where it's clearly described as ignored by default:

```
      // some package.json files have a "browser" field which specifies
      // alternative files to load for people bundling for the browser. If
      // that's you, either use this option or add "browser" to the
      // "mainfields" option, otherwise pkg.browser will be ignored
      browser: true,  // Default: false
```

> supports browser field aliasing

very cool!
