### ISSUE TITLE
[help]webpack "libraryTarget:amd",bundle js not executing,main page is blank.

### ISSUE THREAD

**Issue by houyaowei** [webpack/webpack#9847]
webpack：4.41.2
mac Os: 10.14.6
node: 10.16.0

If the config "libraryTarget: amd" is removed, it working well.

How can I fix this problem? thx.

`
const config = {
	mode: "development",
	// 入口文件配置
	context: path.join(__dirname, "src/"),

	// 入口文件配置
	entry: {
		app: "./app/app.js",
		login: "./app/login/script/index.js",
		echarts: "./assets/lib/echarts.js",
		portal: "./app/portal.js"
	},

	// 配置模块如何解析
	resolve: {
		extensions: [".js"],
		alias: {
			"@constants": path.join(__dirname, "./src/constants")
		}
	},

	// 文件导出的配置
	output: {
		path: path.join(__dirname, "/portal"),
		filename: "[name].js",
		publicPath: "/portal",
		library: "portal",
		libraryTarget: "amd"
	},
	plugins: [
		// 将样式文件 抽取至独立文件内
		new MiniCssExtractPlugin({
			filename: "app-[contenthash:20].min.css",
			allChunks: true,
			disable: false
		}),

		
		new CopyWebpackPlugin([
			{
				from: path.join(__dirname, "/src/favicon.ico"),
				to: "",
				toType: "file"
			},
			{
				from: "assets/lib/",
				to: "libs/",
				force: true
			}
		]),
		// 首页
		new HtmlWebpackPlugin({
			template: "index.html",
			excludeChunks: ["login"],
			chunks: ["app", "echarts", "main"],
			chunksSortMode: "manual"
		}),

		// 登录页
		new HtmlWebpackPlugin({
			filename: "login.html",
			template: "app/login/login.html",
			chunks: ["login"],
			excludeChunks: ["app"]
		}),

		// 微信登录页
		new HtmlWebpackPlugin({
			filename: "wxLogin.html",
			template: "app/login/wxLogin.html",
			chunks: ["login"],
			excludeChunks: ["app"]
		}),

		// 淘宝登录页
		new HtmlWebpackPlugin({
			filename: "tbLogin.html",
			template: "app/login/tbLogin.html",
			chunks: ["login"],
			excludeChunks: ["app"]
		}),

		// 打包分析
		new BundleAnalyzerPlugin({
			// 是否启动后打开窗口
			openAnalyzer: false
		}),
		new webpack.HotModuleReplacementPlugin()
	],
	externals: [/^requirejs$/],
	......
};
`

**Comment by evilebottnawi** [comment]
Please use issue template otherwise issue will be closed, also please create minimum reproducible test repo, thanks
