### ISSUE TITLE
MultiCompiler watcher: one compiler just "disappears"

### ISSUE THREAD

**Issue by apfelbox** [webpack/webpack#9850]
# Bug report

I am using a MultiCompiler, to build a modern build (for browsers with `type="module"`) and a legacy build (IE11+) in our build tool.

**What is the current behavior?**

I run a watcher in the multicompiler, which works for some time. But at some (random?) time only the modern builds are triggered anymore.

```js
compiler.watch(
    {}, 
    (error, stats) => console.log(stats.stats.length) // first 2, later 1
);
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I am using `kaba@9.0.0-1`, which is just a [config generator for webpack](https://github.com/Becklyn/kaba/blob/e7ef10ffcf47730bcd9d0c7edebb72322dffe431/src/Kaba.ts#L301), that [then runs webpack](https://github.com/Becklyn/kaba/blob/e7ef10ffcf47730bcd9d0c7edebb72322dffe431/src/runner/WebpackRunner.ts#L48-L98).

There is no error message, one compiler just "disappears" at one time.

**What is the expected behavior?**
Both compilers should keep running.

**Other relevant information:**
webpack version:  4.41.2
Node.js version: 12.11.1
Operating System: macOS 10.15 (19A583)
Additional tools: [kaba](https://github.com/Becklyn/kaba)

----

I am not looking for somebody to look out build tool `kaba` (you are free to, though) – but I am willing to debug this issue myself, to get to the bottom of this. I have already done some debugging in webpack, due to the history of building a build tool based on webpack..

So, if somebody could give me a hint on where to start or – for example – on how to get the currently registered compilers, that would be really great!

**Comment by apfelbox** [comment]
Another explanation, that would cause my bugs, would be:

> Is it possible, that (after some time..?) I don't get a single `handler` callback, but two separate ones?

**Comment by sokra** [comment]
The handler only include the "changed" stats.

**Comment by apfelbox** [comment]
Both compilers watch the exact same files (they only have different Babel presets basically), so how can it be that for some compilers the same set of files have changed and for the other not?

**Comment by keichinger** [comment]
I've had a closer look at this as well, and to me it feels weird that the initial call to the `onCompilationFinished` callback contains both stats and for every subsequent call only those that have changed.

I personally would prefer to have a more consistent logic to either get all stats or one stats per watcher, like in the subsequent calls.

**Comment by apfelbox** [comment]
But why don't they both change? They are using the same entry files...?

**Comment by keichinger** [comment]
In my case I always got two callbacks for any subsequent calls whenever I made changes to a local file. Instead of one callback with two stats I got two callbacks with one stat object each. It's kind of confusing and inconsistent IMO.

**Comment by sokra** [comment]
Both compilers probably don't finish exactly at the same time.

**Comment by apfelbox** [comment]
Ah, so it isn't guaranteed that the callback will be called once, when the whole (multi) compiler has finished, but instead the callback is called (probably debounced) for every individual compiler each?
