### ISSUE TITLE
Scale webpack in large projects by watching "observers" instead of files

### ISSUE THREAD

**Issue by purpledrgn** [webpack/webpack#9852]
## Feature request

Webpack performance improvement that is unaffected by scale of project.

**What is the expected behavior?**

Ideally I believe everyone wants that should you have a project that is 65,000 entry points[1] its just as fast as a project running just 1 entry point.

**What is motivation or use case for adding/changing the behavior?**

At the moment project re-build performance in development is tied directly to the performance of rebuilding all your entry points.

When you have a single entry point in your application you can only really make webpack faster by "make webpack **build** faster". However when you have a *N* entry points your performance degrades over time based on how many entry points you are building. 

Let's say N is 10 and webpack has come out with a new version that improves performance by 50%. All it takes is for you to reach 20 for N and the performance is now (likely) back to where it was previously. Even worse, once you reach 30 it's worse then it was originally, and going forward 50 it's now abysmal.

Each entry point itself will take verying time to compile based on it's complexity. However in general the developer is very motivated to keep it low and since there's only so much that can go on a page even in a full page js rendered page you'll hit some natural limits (outside of very special cases).

Some solutions do exist at the moment that try to address this, one of which is DLLs. Parts of the application are marked static and compiled into their own separate bundle using `webpack.DllPlugin` and thereby webpack doesn't need to deal with them. However this is not particularly ideal, you have to pick things to put into it and remember you put them into it. Everything you don't put into it is now your new N, which is unlikely to be 1.

**How should this be implemented in your opinion?**

The specific settings names & placement isn't important for this feature, so let's just say it's simply `mode` value of `observer` and when present the following happen.

1. webpack no longer re-compiles on change, only marks files as having changed in it's internal representation of the filesystem 
2. only fast error checks are performed if any at all; where fast means checks that can scale to (extremely) large number of files per project (may be disabled entirely; projects may be running their own language error checkers anyway, such as typescript)
3. under no circumstance will webpack decide to compile "everything" (exception: if next rule happens to apply to every file in the project)
4. a entry point or partial are recompiled only when they are "observed"

In the abstract, something is considered "observed" when:
1. the server was required to send the file
2. the user is viewing the page and the page is not in the background 
3. the partial (eg. async import, and similar patterns) was requested (this is added to the current page's "observed" parts; all parts together are the observed)

We'll need webpack to be "told" what is observed and what isn't. For this purpose we'll define a very simple protocol as follows. In observer mode, webpack listens on a predefined port and responds to the following messages:
 - `ID <id|uuid|etc>` tells the server who we are (a uuid is automatically assigned per connection otherwise)
 - `RESET` wipes the current list of observables (for the client). If multiple clients are connected each have their own list and webpack's complete list is the sum of all of them.
 - `OBSERVE <entity>` tells webpack whats being observed (for the client)
 - `BUILD` tells webpack to build it's current observable list, request only finishes when it's done
 - `TRY` like build but returns the list of all observables and their current build number (since each might have been build different number of times). This can be used on client side to determine if the state is stable.

The protocol should be simple so helpers can be easily implemented by hand if need be in practically any language. An alternative might be to implement it as a json protocol, the details aren't important.

We'll assume a `webpack-helper` exists that just implements the protocol.

**Example**

Let's say you have a site that is fully rendered by javascript. You have SSR support for it so every page is also another entry point. Some of your pages also import some of their features asynchronously. 

_We'll assume the example application has 65,000 entry points._

1. You open `/home`
2. The server uses the `webpack-helper` to send `RESET`, `OBSERVE home` (the entry point), `BUILD` then once it's finished sends the page and calls `RESET` (this instance of `webpack-helper` won't be reused for future requests). Webpack has now built just 1 entry point (out of 65,000). Likely took less then a second.
3. The client loads the bundle. Because we are in development mode a client version of `webpack-helper` was included. It sends `ID webpack-<uuid>` and then also sends `RESET`, `OBSERVE home` but this time does not send `BUILD` (since the http request to get the bundle is confirmation enough). Webpack is now aware of this new client with and it's set of observables.
4. You click `About` in your navigation. There is an about entry point but this time this is not done though the server but loaded directly. (Fundamentally there's just a bunch of `async import` calls that go to work.)
5. Since we are in development mode webpack wrapped all `async import` with `webpack-helper` calls, so our request for about turns into `OBSERVE about-target-partial` (or whatever is necessary), `TRY`. Using the output of try it determines if it's state is stable; if we happen to hit some strange case where the code won't work webpack will give us an error instead (we can simply refresh to solve the problem). Once `TRY` is succesful the import goes though as usual (since the file now exists) and everything works as expected.
6. You open a new tab. The page is now in the background. The client side webpack-helper sends `RESET` to the server to tell it to clear it's list.
7. You go back to the tab. The client side `webpack-helper` sends `RESET` and uses `OBSERVE` to rebuild the list of entities then it does a `TRY`. If the TRY takes more then 1 second then (as part of development mode) webpack places a dark gray overlay with a "Checking..." to indicate to you the tab may be stale. If after TRY the build numbers are unchanged compared to last build numbers webpack pops up a tiny confirmation "Build is fresh" in a corner otherwise it gives a "Build is old" in the corner (ideally configurable to "just refresh page" in options)
8. You close the tab, the `webpack-helper` sends a `RESET`

_If this was normal `--watch` long after the example above was done and over with, you would still be waiting for webpack to startup and finish it's initial build of the 65,000 entry points._

I don't think I need to convince anyone that not compiling things is the fastest way to compile, but if you simply want to see how much of a difference this sort of optimization would make in your own project you can simply comment out all entry points except a few and see what webpack's build time is for your app, when you change files. _For me it goes from a CPU / memory hog that can builds at snail pace (and I do use DLLs and everything I can) to less then a second._

In the example the webpack-helper was called in the server code directly. This honestly the simplest solution and might be even the best for anyone who wants to have control over it (its easy to understand and integrate). An alternative if you want it to be more transparent is to simply implement it as a proxy. You can then simply have servers such as nginx proxy_pass to it (this only replaces the server part of the example). So long as the protocol is kept to be simple, the webpack project doesn't really need to implement every variation of it, just the most basic.

**Are you willing to work on this yourself?**
I do not have the free time at the moment. (My understanding of webpack internals is also nonexistent.)

[1] approximation of FAT32 max directory size (every other filesystem is practically max filesystem files number)

**Comment by sokra** [comment]
Sounds like a good idea, but also something that would consume a lot of time to implement. I don't think we'll find somebody who wants to do this.

Next.js uses a similar approach. They only add entrypoints to the webpack build once they are requested by the server.

**Comment by evilebottnawi** [comment]
Let's bump if somebody want to implement that
