### ISSUE TITLE
contenthash doesn't calculate inline-source-map

### ISSUE THREAD

**Issue by zlk89** [webpack/webpack#9853]
# Bug report

**What is the current behavior?**
contenthash doesn't calculate inline-source-map, i.e., when inline source map is changed, the contenthash doesn't change.

**If the current behavior is a bug, please provide the steps to reproduce.**

- Go to https://github.com/zlk89/minimalist-typescript-webpack-starter
- `yarn` install packages
- `yarn build`
- save the compiled code `./dist/9284f96b54dde0bca6db.js`
- Go to `./src/index.ts`, update all `string` type to `number`:
   ```const fun1 = (a: number, b: number): number => a + b;```
- `yarn build` again
- check `./dist/9284f96b54dde0bca6db.js`, it has same contenthash as before, but the content is different (on the line starts with `//# sourceMappingURL=data:xxx`)

**What is the expected behavior?**
contenthash should be changed, whenever file content is different, even if it is inline sourcemap.

**Other relevant information:**
webpack version:  4.41.2
Node.js version: v8.11.2
Operating System: MacOS 10.14.6
Additional tools:

**Comment by zlk89** [comment]
@sokra @evilebottnawi This could cause production issue, imagine situation like this:
```
build files -> CDN -> user (enabled [SRI check](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity))
```

A file called a.js has been cached in CDN, and on next release we generates same file name but with different file content.
The CDN will keep serving the old a.js file, but it will be rejected on client side, because the integrity check doesn't pass.

**Comment by evilebottnawi** [comment]
Thanks for issue, i will look at this in near future

**Comment by zlk89** [comment]
@evilebottnawi any luck on this?

**Comment by evilebottnawi** [comment]
In todo, thanks for ping

**Comment by evilebottnawi** [comment]
Yes, it is designer problem, here the explanation https://github.com/webpack/webpack/issues/9520, also please do not use `inline-source-map` for production purpose, you can find documentation about it here https://webpack.js.org/configuration/devtool/ (look on the `production` column). Sorry we can't fix it in easy way, maybe we revisit it for webpack@5, but it is not high priority, but we fix it anyway in future, please use the `inline-source-map` value only for developing purpose and using `contenthash` is not recommended for developing

Closing in favor https://github.com/webpack/webpack/issues/9520, thanks for issue
