### ISSUE TITLE
How to exports two module into one global variable

### ISSUE THREAD

**Issue by s0ngyee** [webpack/webpack#986]
my page need use CryptoJS/sha1.js and CryptoJS/md5.js. both of these two file are assign to the global variable CryptoJS which i want to use as  CryptoJS.SHA1()/CryptoJS.MD5(). is it possiable to require two module and export to one global variable? Hope that i describe my question clearly. Thanks.

**Comment by bebraw** [comment]
Can you link to the project in question? I found [cryptojs](https://www.npmjs.com/package/cryptojs) but I'm not sure if that's the same.
