### ISSUE TITLE
node-libs-browser add some huge dependencies to production bundle

### ISSUE THREAD

**Issue by shablenko-sednor** [webpack/webpack#9860]
# Bug report

**What is the current behavior?**
Webpack bundles some dependecies which used only by webpack itself
bn.js
elliptic
hash.js
and so on
which increases bundle size significantly
why they are included, how to drop them from bundle?

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version: 4.41.2  
Node.js version: 10.16.3
Operating System: ubuntu 18 
Additional tools: babel, babel-env preset

![Selection_613](https://user-images.githubusercontent.com/37369710/67106276-f2c60280-f1d2-11e9-9914-a3248d60e7cf.png)

**Comment by evilebottnawi** [comment]
> why they are included, how to drop them from bundle?

Some libraries/packages use node built-in modules so `webpack@4` insert them, it is removed in `webpack@5`. 

https://webpack.js.org/configuration/node/
