### ISSUE TITLE
build slow with large assets

### ISSUE THREAD

**Issue by NichijouCC** [webpack/webpack#9867]
the static assets in public folder is very large about 5.0 G, i process it with CopyWebpackPlugin .my question is the build speed is so slow  every time i update code. i don't know how to solve it !!

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
