### ISSUE TITLE
can I use separate dependencies in dev mode vs. creating a production build?

### ISSUE THREAD

**Issue by jhudson8** [webpack/webpack#987]
I am using a dependency ( [React](http://facebook.github.io/react/) ) which has a production build that is more than just minified but has dev-friendly code removed.  Ideally, I would like to use the standard react module when developing but be able to specify a different artifact (something like ```react/dist/react.min.js```) when building for production (```webpack -p```).

Is this possible?  Thanks.

**Comment by sokra** [comment]
yep.

[contributing guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md)

> Please post a question to [StackOverflow with the webpack tag](http://stackoverflow.com/tags/webpack). Questions that include your webpack.config.js and relevant files are more likely to receive responses.

**Comment by jhudson8** [comment]
sorry
