### ISSUE TITLE
Output filename unable to use functions

### ISSUE THREAD

**Issue by justanotherdev96** [webpack/webpack#9873]
# Bug report

**What is the current behavior?**
When trying to use `output.filename` and pass it a function that returns a string, webpack is throwing an invalid API schema error and is requesting that the filename only accepts strings or regex patterns. 

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a simple webpack configuration which includes an `entry` and an `output` 
2. In the output create a `path` and a `filename`
3. For the `filename` create a simple function `filename: () => '[name.js]' which returns the filename as per the documentation guidelines.
4. Try running webpack 
5. You should get an error with Invalid API schema 

For the exact example which I tried follow https://webpack.js.org/configuration/output/#outputfilename 

![Webpack Docs Example](https://user-images.githubusercontent.com/56864428/67265878-1927be80-f4af-11e9-8e47-85de0be41a80.png)

**What is the expected behavior?**
Webpack should allow the use of functions that return string for `output.filename` as per the example provided on the official docs. 

**Other relevant information:**
webpack version:  4.41.2
Node.js version: v10.16.1
Operating System: Windows 
Additional tools: Bash Emulator, Command-Line, ECMAScript6

**Comment by sokra** [comment]
> Webpack should allow the use of functions that return string for `output.filename` as per the example provided on the official docs.

webpack 4 doesn't support this.

webpack 5 supports this.

**Comment by justanotherdev96** [comment]
Thank you! Then the docs are ahead with beta documentation.
