### ISSUE TITLE
splitchunk not working properly

### ISSUE THREAD

**Issue by LOLdevelopr** [webpack/webpack#9880]
# Bug report

**What is the current behavior?**
I have 3 webpack config file with one `common` ,`dev` and for `prop` each.
I am attaching the codesandbox link where you can  find those configs
[`sandbox`](https://codesandbox.io/s/webpack-splitchunk-issue-nc3jq)
Now in `webpack.common.js` i am using splitchunk for production build. But when using it, its generating huge 3-5 files which is fine but its not working . 
Here is the project tree

![image](https://user-images.githubusercontent.com/50070488/67310122-c4ba2880-f51a-11e9-9112-3f611237b418.png)

In this using webpack I am generating the `.js` files of `dist`. 
In production, I am going to send the `dist` folder

In `dist`, these are the folder I am getting, 

`public/js/`

![image](https://user-images.githubusercontent.com/50070488/67310339-33978180-f51b-11e9-84c9-15397178e31e.png)

I have `index.html` in `public` folder that is including the `app.bundle.js` i.e 
```html
<script src="./js/app.bundle.js"></script>	
```

`server/`

![image](https://user-images.githubusercontent.com/50070488/67310390-490cab80-f51b-11e9-83e7-54b8162fc324.png)

---

I am running `node dist/server` to run the server but nothing is happening.
the server file is doing `SSR` using `react`. 

#### Its working fine with the splitchunk and having the terser plugin

---

**If the current behavior is a bug, please provide the steps to reproduce.**

[![Edit webpack-splitchunk-issue](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/proud-microservice-nc3jq?fontsize=14)

> Note, all files are not included in the sandbox but overview of the project is same only

**What is the expected behavior?**
It should run the server

**Other relevant information:**
webpack version:  	
```json
"webpack": "^4.31.0",
"webpack-cli": "^3.3.5",
```

Node.js version:  `v10.15.3`

Operating System:  Win 10

# Thanks

**Comment by sokra** [comment]
> I have `index.html` in `public` folder that is including the `app.bundle.js` i.e
> 
> ```
> <script src="./js/app.bundle.js"></script>	
> ```

You probably need to include more script tags to load all the split chunks.

See Stats output for a list of files to include:

``` text
Entrypoint main = <list of needed script tags here>
```

**Comment by LOLdevelopr** [comment]
Oh. 
But how to run the server then? 
Cause I am using splitchunk for that too

**Comment by evilebottnawi** [comment]
@LOLdevelopr 
> But how to run the server then?
just like you ran earlier

**Comment by LOLdevelopr** [comment]
But it's not working with that. 
The server is also being splitted. So running `node server/index.js` is not working

**Comment by evilebottnawi** [comment]
@LOLdevelopr I don't know what `node server/index.js` do

**Comment by evilebottnawi** [comment]
@LOLdevelopr looks like `splitChunks` buggy for `node` target, why you are split code for node?

**Comment by LOLdevelopr** [comment]
No specific reason. Should I remove node target or remove the splitchunk?

**Comment by evilebottnawi** [comment]
@LOLdevelopr you can't avoid building node target, it is unnecessary in your case

**Comment by LOLdevelopr** [comment]
I am doing SSR using react so it's importing jsx, I need those loaders for that.. I think it will break if removing build for node

**Comment by evilebottnawi** [comment]
@LOLdevelopr disable `splitChunks` for `node` target

**Comment by LOLdevelopr** [comment]
Ok will try that and will let you know

**Comment by sokra** [comment]
In webpack 4 splitChunks with `chunks: "all"` is not supported with target node.
Webpack 5 will add support for that.

**Comment by evilebottnawi** [comment]
Answers above
