### ISSUE TITLE
Cannot have a named AMD module when using umd libraryTarget

### ISSUE THREAD

**Issue by jmdobry** [webpack/webpack#989]
I understand I am supposed to open an issue before opening a pull request to ensure that [my] precious work is not in vain, so here it is:

When using the "amd" libraryTarget, the resulting amd module [will be an anonymous `define`](https://github.com/webpack/webpack/blob/6173bb83bad2b07e8f9f965f19f1b777c652b2fb/lib/AmdMainTemplatePlugin.js#L30) if `output.library` was not set. If `output.library` _was_ set, then the amd module [will be named](https://github.com/webpack/webpack/blob/6173bb83bad2b07e8f9f965f19f1b777c652b2fb/lib/AmdMainTemplatePlugin.js#L28) based on the value of `output.library`. The `AmdMainTemplatePlugin` checks for `this.name` and handles both cases.

However, when using the "umd" libraryTarget it is impossible to achieve a named amd module. The `define` [will always be anonymous](https://github.com/webpack/webpack/blob/6173bb83bad2b07e8f9f965f19f1b777c652b2fb/lib/UmdMainTemplatePlugin.js#L102). `UmdMainTemplatePlugin` does _not_ check for `this.name` and just always makes an anonymous `define`.

This is a problem under the following conditions:

- Library `foo` is built with `output.libraryTarget: 'umd'` and `output.library: 'foo'`
- Library `bar` is built with `output.libraryTarget: 'umd'` and `output.library: 'bar'`
- Library `bar` depends on library `foo`, so `foo` is bundled within `bar`
- The bundled `bar` library now has _two anonymous defines_

This is a problem because r.js is incapable of normalizing an anonymously defined module that contains more than one anonymous `define`. This results in the infamous [mismatched anonymous define() modules](http://requirejs.org/docs/errors.html#mismatch) error for any developer who wants to consume library `bar` in their r.js build.

The problem disappears when the two anonymous defines are given names, which is impossible with the current implementation of UmdMainTemplatePlugin.

I propose that UmdMainTemplatePlugin be modified to check for `this.name` like AmdMainTemplatePlugin does, and `if (this.name)` then it should set the name of the `define` to `output.library`.

**Comment by sokra** [comment]
I'm unsure. Giving the module a fixed name can lead to other issues. I. e. when the filename doesn't match the module name.

Maybe we can embedd an `var define` instead to make r.js ignore any other `define` that occurs in code.

**Comment by jmdobry** [comment]
I hacked my way around this by making sure the `foo` `define` is not anonymous.

**Comment by josdejong** [comment]
@sokra I totally agree with you and see this as a problem of `r.js`.

But if I understand it correctly this behavior is already there when using the `amd` libraryTarget. Wouldn't it be consistent to apply this same behavior for both `amd` and `umd` targets? (Just for the AMD `define` part of course).

**Comment by coryvirok** [comment]
We are also running into this same problem but I think there should be a way for Webpack to generate a named AMD module for the UMD target. 

We are building a 3rd party library to distribute to customers. This means that if they have any other anonymous AMD defines they will see an error message: `Error: Mismatched anonymous define() module: ...`

This is happening for at least 1 of our customers who is using jQuery which calls `define(function...)`. This leads to a mismatch when our code executes the `define()` generated by the UMD target.

I'm working on a PR now and will send it over shortly.

**Comment by wmadden** [comment]
FWIW this is a problem for our team as well. We're also using `r.js` with a webpack UMD output file.

**Comment by riddla** [comment]
I stumbled upon this behavior also when trying to use https://github.com/jmdobry/angular-cache (which is build/bundled via webpack) in conjunction with `r.js`.

**Comment by voldern** [comment]
:+1:

This problem also affect us since one our customers is using a stripped down version of Almond that requires all of their AMD modules to be named.
