### ISSUE TITLE
import('xxxx') do not works as expect

### ISSUE THREAD

**Issue by weivea** [webpack/webpack#9895]
write like this~

![71571888636_ pic](https://user-images.githubusercontent.com/8197845/67452160-051dc180-f655-11e9-8c10-42ba80d3ba90.jpg)

output:
![91571888636_ pic](https://user-images.githubusercontent.com/8197845/67452204-1070ed00-f655-11e9-96e7-7a6c724bc1a2.jpg)

the code do not be splited~ they are all in one file~
no separate chunks generated

```
mode: 'production',
  optimization: {
    splitChunks: {
      chunks: 'async',
      minSize: 10,
      minChunks: 1,
      maxAsyncRequests: 5,
      maxInitialRequests: 3,
      automaticNameDelimiter: '~',
      name: true,
      cacheGroups: {
        vendors: {
          test: /[\\/]node_modules[\\/]/,
          priority: -10
        },
        default: {
          minChunks: 2,
          priority: -20,
          reuseExistingChunk: true
        }
      }
    }
  },
```

babel.config.js
```
module.exports = {
  'presets': [
    ['@babel/preset-env', {
      'targets': {
        'browsers': ['android >= 4.4']
      },
      'modules': 'commonjs',
      'useBuiltIns': 'usage'
    }]
  ],  
  'plugins': ['transform-vue-jsx', '@babel/plugin-syntax-dynamic-import'],
  sourceMaps: true
};
```
**### when I use `require.ensure` it`s work ~
no way~**

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Use `enforce` if you always want to create chunk. https://webpack.js.org/plugins/split-chunks-plugin/#splitchunkscachegroupscachegroupenforce

**Comment by bplok20010** [comment]
> 'modules': 'commonjs',

set false or 'auto'
