### ISSUE TITLE
Promise ponyfill

### ISSUE THREAD

**Issue by anilanar** [webpack/webpack#9898]
## Feature request

**What is the expected behavior?**
I need some webpack internals to use a `Promise` **ponyfill** instead of the global `Promise`.

**What is motivation or use case for adding/changing the behavior?**
I'm bundling a web app that runs on 3rd party websites and I **must not** pollute their global namespace with polyfills.

**How should this be implemented in your opinion?**
No idea, but I guess `Promise` is the only thing that needs a polyfill for IE11.

**Are you willing to work on this yourself?**
yes

**Comment by evilebottnawi** [comment]
Duplicate #3531
