### ISSUE TITLE
Enable conditional compilation through Uglify

### ISSUE THREAD

**Issue by altano** [webpack/webpack#99]
UglifyJS allows you to do get conditional compilation by compressing out dead code paths by defining an always-false global definition, like so:

```
uglify: {
  options: {
      compress: { global_defs: { DEBUG: false } }, // enables condition code compilation
      ...
```

Documentation here: http://lisperator.net/uglifyjs/compress

Would it be possible for webpack to either expose the UglifyJS options so they can be configured OR just set a global def where DEBUG=webpack.options.debug ?

**Comment by xgqfrms-gildata** [comment]
# how to set webpack ignore some keywords without uglify ?

> What's wrong with this? Anybody can help?

![image](https://user-images.githubusercontent.com/29531779/34377830-dd2a49b6-eb2d-11e7-9e69-7a786be52ec2.png)

**Comment by altano** [comment]
@xgqfrms-gildata this issue is from 2013 and your question doesn't seem to obviously be the same question, so it would probably be a good idea to post a new issue describing your problem.

And while you're at it, you should give a brief description of what problem you're trying to solve, how you're trying to solve it (i.e. your whole config and not a narrow section of it), and why it's not behaving as you'd expect.
