### ISSUE TITLE
Asynchronously loading scripts for an isomorphic app 

### ISSUE THREAD

**Issue by geekyme** [webpack/webpack#990]
In my isomorphic app, I have an entry point `application.js` file that runs on both the client and the server. 

``` javascript
var NotFoundPage = require("./pages/not-found");
var ErrorPage = require("./pages/error");
var LoadingPage = require("./pages/loading");
var LoginPage = require("./pages/auth/login");
var JoinPage = require("./pages/auth/join");

// some routing logic to render different pages given above
...
```

My problem is, when I attempt to use the following syntax to load scripts depending on the requested route :

```
require.ensure([], function(){
     // the page scripts
});
```

I get errors like `TypeError: undefined is not a function`, but yet if I use the synchronous syntax `require(...)`, my scripts will all be bundled up into a giant js file. 

What can I do to tell webpack to create async chunks for me given an isomorphic entry point?

**Comment by jregeimbal** [comment]
Having the same problem, although I'm not quite sure if webpack context will work they way I am anticipating.  Regardless require.ensure is not being processed correctly.

require.ensure(['react-router-proxy!./'+component], function(require) {
                return require('react-router-proxy!./'+component)
            }) : require('./' + component)) 

is compiling to:

__webpack_require__(29).ensure(['react-router-proxy!./'+component], function(require) {
	                return require('react-router-proxy!./'+component)
	            }) : require('./' + component))

**Comment by sokra** [comment]
You cannot have a expression in `require.ensure`. Just omit the `require.ensure`. It wrong here and `react-router-proxy` already uses async loading.

If you are doing this for prerendering this won't work, because the prerendered html doesn't fit the to rendered html. React will warn you!

Instead you need to replace the proxied component with a empty component (react-router-proxy should provide it), because in the initial page load the async component is not loaded yet.

**Comment by bebraw** [comment]
@geekyme Did you figure it out based on the tip?

**Comment by jypblue** [comment]
also, i have the same problem

**Comment by rcalabro** [comment]
Hi, if you are using `webpack-isomorphic-tools` you should set `patch_require: true`, it is false by default.

From documentation:

> // enables support for `require.context()` and `require.ensure()` functions. 
> // is turned off by default  
> // to skip unnecessary code instrumentation 
> // because not everyone uses it. 
> // 
> // patch_require: true, // is false by default

**Comment by TheLarkInn** [comment]
Closing as this is question.
