### ISSUE TITLE
webpackExclude doesn't work

### ISSUE THREAD

**Issue by volkanunsal** [webpack/webpack#9903]
# Bug report

**What is the current behavior?**

Given a dynamic import like this:

```js
const CompanyEdit = universal(/* webpackExclude: /(__generated__|__tests__)/ */ import('comps/Company/Edit'));
```

It does not exclude the files matching the pattern from the chunk generation. Here is a sample output from the `manifest.json` of the files that match the following pattern and are generated by this import

```
public/__generated__-GetKey.chunk-647967baa76de181db7c.js
public/__generated__-GetKey.chunk-647967baa76de181db7c.js.map
public/__generated__-RegenKey.chunk-4f4202d851a015422d6d.js
public/__generated__-RegenKey.chunk-4f4202d851a015422d6d.js.map
public/__generated__-updateCompany.chunk-c3ad3a2c0a71b001bb29.js
public/__generated__-updateCompany.chunk-c3ad3a2c0a71b001bb29.js.map
public/__tests__-AccessKeyManager-test.chunk-bed6e34b29ee6fbd5d72.js
public/__tests__-AccessKeyManager-test.chunk-bed6e34b29ee6fbd5d72.js.map
public/__tests__-__snapshots__-AccessKeyManager-test-js-snap.chunk-07f6461ec4547a0878ef.js
public/__tests__-__snapshots__-AccessKeyManager-test-js-snap.chunk-07f6461ec4547a0878ef.js.map
```

**What is the expected behavior?**

It is expected to exclude these files from the manifest.

**Other relevant information:**
webpack version:  4.41.0
Node.js version: 8.x.x
Operating System: Mac OS

**Comment by sokra** [comment]
You have to put it into the `import()`

``` js
universal(import(/* webpackExclude: /(__generated__|__tests__)/ */ 'comps/Company/Edit'));
```

**Comment by volkanunsal** [comment]
My code example above was wrong. This is what it actually looks like:

```js
const CompanyEdit = universal(
  import(
    /* webpackExclude: /(__generated__|__tests__)/ */
    'comps/Company/Edit'
  ),
  opts
);
```

This issue is discussed [on this thread as well.](https://github.com/faceyspacey/react-universal-component/issues/197)
