### ISSUE TITLE
Loading chunk {chunkId} failed

### ISSUE THREAD

**Issue by FuncWei** [webpack/webpack#9911]
# Bug report

**What is the current behavior?**
use react-lazy split code ,product evn user error loading chunk 7 failed.
Here is sentry error json (some sensitive information has been removed):
```
{
    "event_id":"",
    "project":313,
    "release":"",
    "dist":null,
    "platform":"javascript",
    "message":"",
    "datetime":"2019-10-28T09:02:13.335000Z",
    "time_spent":null,
    "tags":[],
    "breadcrumbs":''
    "contexts":{
        "device":{
            "model":"Smartphone",
            "brand":"Generic",
            "family":"Generic Smartphone"
        },
        "os":{
            "version":null,
            "name":"Android"
        },
        "browser":{
            "version":"74.0.3729",
            "name":"Chrome Mobile"
        }
    },
    "culprit":"HTMLScriptElement.o(webpack/bootstrap)",
    "exception":{
        "values":[
            {
                "stacktrace":{
                    "frames":[
                        {
                            "function":"HTMLScriptElement.o",
                            "abs_path":"webpack:///webpack/bootstrap",
                            "pre_context":[
                                "  var chunk = installedChunks[chunkId];",
                                "  if(chunk !== 0) {",
                                "  if(chunk) {",
                                "  var errorType = event && (event.type === 'load' ? 'missing' : event.type);",
                                "  var realSrc = event && event.target && event.target.src;"
                            ],
                            "post_context":[
                                "  error.type = errorType;",
                                "  error.request = realSrc;",
                                "  chunk[1](error);",
                                "  }",
                                "  installedChunks[chunkId] = undefined;"
                            ],
                            "filename":"webpack/bootstrap",
                            "module":"webpack/bootstrap",
                            "colno":1,
                            "in_app":false,
                            "data":{
                                "sourcemap":""
                            },
                            "context_line":"  var error = new Error('Loading chunk ' + chunkId + ' failed.\n(' + errorType + ': ' + realSrc + ')');",
                            "lineno":179
                        }
                    ]
                },
                "raw_stacktrace":{
                    "frames":[
                        {
                            "function":"HTMLScriptElement.o",
                            "abs_path":"/static/js/manifest.7dc1de53af528da70cd0.js",
                            "filename":"/static/js/manifest.7dc1de53af528da70cd0.js",
                            "lineno":1,
                            "colno":5194,
                            "in_app":false,
                            "context_line":"{snip} "===a.type?"missing":a.type),c=a&&a.target&&a.target.src,n=new Error("Loading chunk "+e+" failed.\n("+t+": "+c+")");n.type=t,n.request=c,r[1 {snip}"
                        }
                    ]
                },
                "value":"Loading chunk 7 failed.
(missing: /static/js/ModifyPurchase~QuotationResult.bddf74af307cd22a884d.js)",
                "mechanism":{
                    "type":"instrument",
                    "data":{
                        "function":"addEventListener",
                        "handler":"bound Pn",
                        "target":"EventTarget"
                    },
                    "handled":true
                },
                "type":"Error"
            }
        ]
    },
    "level":"error",
    "location":"webpack/bootstrap",
    "logger":"",
    "metadata":{
        "function":"HTMLScriptElement.o",
        "type":"Error",
        "value":"Loading chunk 7 failed.
(missing: /static/js/ModifyPurchase~QuotationResult.bddf74af307cd22a884d.js)",
        "filename":"webpack/bootstrap"
    },
    "received":1572253333.335,
    "request":{},
    "sdk":{
        "version":"5.1.1",
        "name":"sentry.javascript.browser",
        "packages":[
            {
                "version":"5.1.1",
                "name":"npm:@sentry/browser"
            }
        ],
        "integrations":[
            "InboundFilters",
            "FunctionToString",
            "TryCatch",
            "Breadcrumbs",
            "GlobalHandlers",
            "LinkedErrors",
            "UserAgent"
        ]
    },
    "timestamp":1572253333.335,
    "title":"Error: Loading chunk 7 failed.",
    "type":"error",
    "use_rust_normalize":true,
    "user":{
        "ip_address":"59.109.209.61",
        "data":{
            "Phone":"暂无",
            "Email":"暂无"
        }
    },
    "version":"7"
}
```
![image](https://user-images.githubusercontent.com/16984724/67755434-16ab0300-fa73-11e9-896b-83d74cc3406f.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
After the project is released, reports Loading chunk {chunkId} failed，a small number of users occur and cannot be reproduced

**What is the expected behavior?**
Asynchronous loading of the file loaded successfully

**Other relevant information:**
webpack version:  4.6.0
Node.js version: 8
Operating System: 
Additional tools:

**Comment by evilebottnawi** [comment]
It is network problem, somebody from your users was disconnected from the internet so can't download chunk, also you don't provide config(s) or minimum reproducible test repo so we can't help

**Comment by FuncWei** [comment]
> 这是网络问题，您用户中的某人已断开与Internet的连接，因此无法下载数据块，而且您也未提供配置或最低可重复的测试存储库，因此我们无济于事

If it is a network problem,error type should is 'timeout',  but this error type is 'missing'

webpack config:
`var path = require('path');
var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var MiniCssExtractPlugin = require("mini-css-extract-plugin");
var GitRevisionPlugin = require('git-revision-webpack-plugin');
var gitRevisionPlugin = new GitRevisionPlugin();
const AddAssetHtmlPlugin = require('add-asset-html-webpack-plugin');

function resolve(dir) {
    return path.join(__dirname, '..', dir)
}

function src(dir) {
    return resolve(path.join('src', dir))
}

var theme = {};
var pkgPath = resolve('package.json');
var pkg = require(pkgPath);
theme = pkg.theme;

module.exports = {
    entry: {
        main: src('index.jsx')
    },
    target: 'web',
    output: {
        path: resolve('dist'),
        filename: 'static/js/[name].js',
        chunkFilename: 'static/js/[name].js',
        publicPath: '/'
    },
    plugins: [
        new webpack.DefinePlugin({
            MOCK: !!process.env.MOCK,
            CODE_VERSION: JSON.stringify(gitRevisionPlugin.version()),
            CODE_ENV: JSON.stringify(process.env.CODE_ENV)
        }),
        new webpack.DllReferencePlugin({
            context: __dirname,
            manifest: require('../dll/vendor-manifest.json'),
        }),
        new webpack.DllReferencePlugin({
            context: __dirname,
            manifest: require('../dll/react-manifest.json'),
        }),
        new HtmlWebpackPlugin({
            template: src('index.html'),
            filename: 'index.html',
            minify: {
                minifyCSS: true,
                minifyJS: true
            },
            chunks: ['manifest', 'vendor', 'main'],
            favicon: src('favicon.ico'),
            chunksSortMode: 'dependency'
        }),
        new AddAssetHtmlPlugin([{
            filepath: resolve('dll/vendor.dll.js'),
            includeSourcemap: false,
            hash: true,
        }, {
            filepath: resolve('dll/react.dll.js'),
            includeSourcemap: false,
            hash: true,
        }])
    ],
    resolve: {
        alias: {
            'network': src('network'),
            'actions': src('actions'),
            'reducers': src('reducers'),
            'containers': src('containers'),
            'common': src('common'),
            'components': src('components'),
            'utils': src('utils'),
            'assets': src('assets'),
            'pages': src('pages'),
            'layouts': src('layouts'),
            'router': src('router'),
            'config': src('config'),
            'v3pages': src('v3pages'),
        },
        extensions: ['*', '.js', '.jsx']
    },
    module: {
        rules: [
            {
                test: /\.(js|jsx)$/,
                enforce: 'pre',
                use: ['thread-loader', 'eslint-loader'],
                exclude: /node_modules/,
                include: resolve('')
            },
            {
                test: /\.(js|jsx)$/,
                loader: 'babel-loader',
                exclude: /node_modules/,
                include: resolve(''),
                options: {
                }
            },
            {
                test: /\.svg$/,
                loader: 'svg-sprite-loader',
                include: resolve('src/assets/icons'),
                options: {
                    symbolId: 'icon-[name]'
                }
            },
            {
                test: /\.(png|jpe?g|gif)(\?.*)?$/,
                loader: 'url-loader',
                options: {
                    limit: 10240,
                    name: 'static/images/[name].[hash:8].[ext]'
                }
            },
            {
                test: /\.(woff2?|eot|ttf|otf|svg)(\?.*)?$/,
                loader: 'url-loader',
                exclude: resolve('src/assets/icons'),
                options: {
                    limit: 10240,
                    name: 'static/fonts/[name].[hash:8].[ext]'
                }
            },
            {
                test: /\.css?$/,
                use: [MiniCssExtractPlugin.loader, {
                    loader: 'css-loader',
                    options: {
                        minimize: true
                    }
                }]
            },
            {
                test: /\.less?$/,
                exclude: /node_modules/,
                use: [MiniCssExtractPlugin.loader, {
                    loader: 'css-loader',
                    options: {
                        minimize: true,
                        localIdentName: '[local]___[hash:base64:5]'
                    }
                }, 'postcss-loader', 'less-loader']
            },
        ]
    }
};
`
webpack prod config
`var path = require('path');
var webpack = require('webpack');
var base = require('./webpack.config');
var MiniCssExtractPlugin = require("mini-css-extract-plugin");
var BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
const TerserPlugin = require('terser-webpack-plugin');
const SentryPlugin = require('@sentry/webpack-plugin')
const GitRevisionPlugin = require('git-revision-webpack-plugin');
const gitRevisionPlugin = new GitRevisionPlugin();


base.mode = 'production';
base.devtool = 'hidden-source-map';
Object.keys(base.entry).forEach(function (name) {
    base.entry[name] = [].concat(base.entry[name]);
});
base.output.filename = 'static/js/[name].[contenthash].js';
base.output.chunkFilename = 'static/js/[name].[contenthash].js';

base.optimization = {
    minimizer: [
        new TerserPlugin({
            exclude: /\.min\.js$/,
            cache: true,
            parallel: true,
            sourceMap: true,
            terserOptions: {
                compress: {
                    drop_console: true,
                    reduce_vars: true,
                },
                output: {
                    comments: false,
                    beautify: false
                }
            }
        })
    ],
    runtimeChunk: {
        name: "manifest"
    },
    splitChunks: {
        cacheGroups: {
            vendor: {
                test: /[\\/]node_modules[\\/]/,
                name: "vendor",
                chunks: "all"
            }
        }
    }
};

base.plugins.push(
    new MiniCssExtractPlugin({
        filename: "static/css/[name].[contenthash].css"
    }),
    new webpack.HashedModuleIdsPlugin(),
    new SentryPlugin({
        include: './dist',
        configFile: 'sentry.properties',
        release: gitRevisionPlugin.version(),
        errorHandler: () => { },
    }),
);

if (!!process.env.ANALYZE) {
    base.plugins.push(new BundleAnalyzerPlugin());
}

module.exports = base;`

**Comment by evilebottnawi** [comment]
@FuncWei Please don't put configuration in issue, it is unreadable, create reproducible test repo

**Comment by FuncWei** [comment]
> @FuncWei Please don't put configuration in issue, it is unreadable, create reproducible test repo

> If it is a network problem,error type should is 'timeout', but this error type is 'missing' ？

**Comment by sokra** [comment]
maybe proxy/gateway-related. Or internet login page. Anyway we can do nothing here.

**Comment by novenn** [comment]
经过我半个月的努力 发现了解决这个问题的方法 看看是不是你的情况: https://blog.novenn.com/webpack%E4%B9%8BLoading-chunk-x-failed/

**Comment by SamKirkland** [comment]
In my case this was caused by some browsers/networks blocking the module because it contained a classname with the word "Ad".
So it was being blocked because it was thought to contain Ads.

**Comment by DigitalPromiseVictor** [comment]
@SamKirkland mind if I ask how ya'll investigated that? I'm running into a similar webpack failed chunk load issue with my webapp.
