### ISSUE TITLE
Datestamps displayed are not locale specific, always display in US format

### ISSUE THREAD

**Issue by plastikfan** [webpack/webpack#9921]
# Bug report

**What is the current behavior?**

Whenever webpack shows a date, the format used is US format. All dates displayed should be according to the system locale. I'm from the UK so I would either like to see dates displayed in a universal format (ISO) or the date should be formatted according to what the locale defines, which for the UK is DD/MM/YYYY. The date being shown is in the US format: MM/DD/YYYY.

**If the current behavior is a bug, please provide the steps to reproduce.**
Ensure locale is set to one which is not the US and is a different format to the US, eg UK.

Just build any webpack project and observe the date. Here is an example of the output:

```
Hash: 1c5cc2f7df1a9129ebac
Version: webpack 4.39.2
Time: 7210ms
Built at: 10/31/2019 4:49:31 PM
               Asset      Size  Chunks             Chunk Names
jaxom-test-bundle.js  6.77 KiB    main  [emitted]  main
Entrypoint main = jaxom-test-bundle.js
[./tests sync recursive .spec.ts$] ./tests sync .spec.ts$ 206 bytes {main} [built]
[./tests/all-tests-entry.js] 115 bytes {main} [built]
[./tests/converter/xpath-converter.class.spec.ts] 704 bytes {main} [optional] [built]
[chai] external "chai" 42 bytes {main} [built]
[dirty-chai] external "dirty-chai" 42 bytes {main} [built]
```

**What is the expected behavior?**

Assumingh the  system locale is UK, dates displayed in UK format eg:

```
Hash: 1c5cc2f7df1a9129ebac
Version: webpack 4.39.2
Time: 7210ms
Built at: 31/10/2019 4:49:31 PM
               Asset      Size  Chunks             Chunk Names
jaxom-test-bundle.js  6.77 KiB    main  [emitted]  main
Entrypoint main = jaxom-test-bundle.js
[./tests sync recursive .spec.ts$] ./tests sync .spec.ts$ 206 bytes {main} [built]
[./tests/all-tests-entry.js] 115 bytes {main} [built]
[./tests/converter/xpath-converter.class.spec.ts] 704 bytes {main} [optional] [built]
[chai] external "chai" 42 bytes {main} [built]
[dirty-chai] external "dirty-chai" 42 bytes {main} [built]
```

**Other relevant information:**
webpack version:  4.39.2
Node.js version: 10.16.1
Operating System: macos 10.14.6
Additional tools:

**Comment by sokra** [comment]
webpack 5 will display them as `YYYY-MM-DD`. Stats are always displayed in English so we don't do locale-specific display here.

**Comment by plastikfan** [comment]
Ok thats fine. The essential point was to request that dates are displayed in a non ambiguous format, cheers
