### ISSUE TITLE
Can't use 2 js files created in same library

### ISSUE THREAD

**Issue by matthew798** [webpack/webpack#9926]
**Do you want to request a *feature* or report a *bug*?**
Report A bug

**What is the current behavior?**
I'm not 100% sure this is a bug, and I also have an [SO question ](https://stackoverflow.com/questions/58660117/multiple-entries-result-in-library-outpts-overwriting-each-other)open.

When running webpack with 2 entries and one, common library name i.e.:
```
entry: {
        editor: path.resolve(__dirname, './src/js/FormrEditor.js'),
        renderer: path.resolve(__dirname, './src/js/FormrRenderer.js')
    },
    output: {
        filename: 'formr-[name].js',
        path: path.resolve(__dirname, 'dist/js'),
        library: 'Formr',
        libraryTarget: "umd"
    },
```
The output files are _not_ able to be loaded in the same context. That is to say that if, in html, one where to do:
```
<script src="formr-editor.js"></script>
<script src="formr-renderer.js"></script>
```

the browser would complain that `Formr.Editor() === undefined`. Upon further investigation, it seems that `formr-renderer.js` is _overwriting_ the result of `formr-editor.js` and the `Formr` object no longer contains a definition for `Editor`. It does however contain `Renderer`. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Create 2 js files, each with an empty class and bundle with the above config. Then include both js files in an html file and attempt to instantiate both classes.

**What is the expected behavior?**
I would have expected the `Formr.Renderer` "class" to be _added_ to the `Formr` "namespace"/library and being able to safely include both JS files

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
webpack 4.41.0

Here is my whole [webpack.config](https://gist.github.com/matthew798/93cbbed49debdeb9e24c6fb56a7bf43c)

**Comment by sokra** [comment]
Try `library: ['Formr', '[name]']`

**Comment by matthew798** [comment]
@sokra Unfortunately that results in me having to do `new Formr.editor.Editor();`

**Comment by sokra** [comment]
You can rename your entries

    entry: {
        Editor: path.resolve(__dirname, './src/js/FormrEditor.js'),
        Renderer: path.resolve(__dirname, './src/js/FormrRenderer.js')
    },

and use `output.libraryExport: "[name]"`

**Comment by matthew798** [comment]
@sokra yes that's an option, but if possible I'd like both the editor and the renderer to be in the "formr" "namespace".
