### ISSUE TITLE
Cannot chain style/useable with bundle

### ISSUE THREAD

**Issue by jlchereau** [webpack/webpack#993]
The following works:
```
var style = require("style/useable!css!./file.css");
style.use(); // = style.ref();
style.unuse(); // = style.unref();
```

But the following does not work
```
var style = require("bundle!style/useable!css!./file.css");
style.use(); // = style.ref();
style.unuse(); // = style.unref();
```

The console displays the following error:
```
Uncaught TypeError: style.use is not a function
```

Is there a way to have useable styles in separate js or css files (for theming an application), to only download the theme a user is using?

Note that bundling styles without /useable works, but in this case, styles are piled and the last stylesheet added to the pile wins so that changing theme from A to B works but then changing theme back from B to A won't work because A has already been loaded and replaced by B.

To help reproduce, I have a prototype which can be cloned from https://github.com/jlchereau/Webpack

Run https://github.com/jlchereau/Webpack/blob/master/index.html

The code to switch themes is located at https://github.com/jlchereau/Webpack/blob/master/js/index.js#L59

The chain ```bundle!style/useable``` is configured at https://github.com/jlchereau/Webpack/blob/master/webpack.config.js#L47

**Comment by jlchereau** [comment]
I have a prototype which can be cloned from https://github.com/jlchereau/Webpack

Run https://github.com/jlchereau/Webpack/blob/master/index.html

The code to switch themes is located at https://github.com/jlchereau/Webpack/blob/master/js/index.js#L59

The chain ```bundle!style/useable``` is configured at https://github.com/jlchereau/Webpack/blob/master/webpack.config.js#L47

**Comment by sokra** [comment]
https://github.com/webpack/bundle-loader

``` js
var styleBundle = require("bundle!style/useable!css!./file.css");
styleBundle(function(style) {
  style.use(); // = style.ref();
  style.unuse(); // = style.unref();
});
```

**Comment by jlchereau** [comment]
THx!
