### ISSUE TITLE
Conditional Dynamic import is not working

### ISSUE THREAD

**Issue by psdon** [webpack/webpack#9930]
# Bug report
I'm trying to do a conditional dynamic imports, where in each "route", it only import the necessary JavaScript.

**What is the current behavior?**
Even the `import()` is wrapped within an if statement, webpack let the module get imported and executed regardless of the condition.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
let view = document.getElementById('main_js').getAttribute('data-view')

data_routes = ["home"]

for (var i = 0; i < data_routes.length; i++){

    if (data_routes[i] == view){
    import('./view/' + data_routes).then(
        obj => {
        obj.default() })
        .catch(
            err => {
    //    console.log(err.stacktrace)
        });
    }
    else{

    }
}
```

**What is the expected behavior?**
I would like to do a conditional dynamic import, where you can import the module you only need for the specific route.

**Other relevant information:**
webpack version: `4.33.0`
Node.js version: `v12.7.0`
Operating System: `Debian Stretch`
Additional tools: `Python Flask`

**Comment by anymost** [comment]
The same issue I found, Can you tell me how to resolve it?

**Comment by psdon** [comment]
@anymost 
```
const loadModules = (modules) => Promise.all(
    modules.map((module) => import(`./view/${module}.js`)
        .then((obj) => {
          obj.default();
        })
        .catch(() => {}),),
  );

loadModules(dataRoutes);
```

For more info, check my example script here -> https://github.com/psdon/Flask-Manage-Webpack/blob/master/example/assets/js/main.js
