### ISSUE TITLE
create TypeScript definitions

### ISSUE THREAD

**Issue by vankop** [webpack/webpack#9936]
There is killer feature in TypeScript 3.7 for webpack - declaration now works with JS files, see https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#--declaration-and---allowjs

It allows to create one state of truth for types - code, right now code is separated from JSON schema and definitions files. So we can create one flow - code => definitions => JSON schema

Plus there is `asserts `feature that will be great for `schema-utils`, see https://github.com/webpack/schema-utils/pull/73

**Comment by evilebottnawi** [comment]
Feel free to send a PR

**Comment by sokra** [comment]
@ematipico wanted to implement this

**Comment by vankop** [comment]
> @ematipico wanted to implement this

👍

**Comment by evilebottnawi** [comment]
bump
