### ISSUE TITLE
Various questions

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack/webpack#994]
Hey there!

I just came across WebPack while being in the need to get rid of many requests just to gather together some resources (various scripts, etc). For now, I have been doing this using PHP. A Yii extension allows me to add together all my scripts into a single file. However, minification and things alike don't work. There also is no support for some advanced parsing and pre-processing.

So I have a few questions:

- Within webpack-app (the example app) you used the `jamjs` system for some dependencies. Would you recommend this to work nicely alongside webpack?
- I currently have quite a few dependencies that I am currently managing via - you are going to scream... - `git submodule`. As you can tell, this is **not** very elegant! My main dependencies include Bootstrap and jQuery, but also smaller jQuery plugins. How can I add these smaller plugins, that are oftenly just a single file, to webpack? Is there a recommended way to do so? As an example for this question, consider `jQuery.stickyFooter` and `jQuery.rangyInputs`.
- Am I right to assume that loaders are chained by separating them by exclamation points ("!")? I.e.: `style-loader!css-loader!scss-loader`
- I want to build a loader for [OJ](http://npmjs.org/ojc). It has a runtime that needs to be included for the browser to work. This runtime currently only supports the browser and needs to run in global space. Imagine I had done the loader, how would I go about loading `.oj` files?
- Within my app, I have a slightly changing demand for scripts. When I am at `/site/main` I only want jQuery, Bootstrap and some fancy stuff. But when I am within `/chat`, I would like to be able to load a lot more JS files. What is a good way to handle this? I know there is the async way of require-ing files. But how exactly does it work? Do I specify the path directly to the file? Say I have `main.js` and a subfolder called `chat/` containing a few various scripts specially for the chat. How do I load them all?
- Does webpack understand symlinks? I currently have the Socket.IO client library symlinked into my main folder. What is the best way to get this to the browser?

Sorry for the load of questions - but I decided that it was better to put it all here instead of spawning one issue per question - I hope you don't mind :)

Webpack looks very promising and I can't wait to use it. I am just currently considering how to. The CLI seems a bit sparse and I am unsure on how exactly I have to create my webpack.

Kind regards, Ingwie!

**Comment by bebraw** [comment]
> Within webpack-app (the example app) you used the jamjs system for some dependencies. Would you recommend this to work nicely alongside webpack?

I have stuck with NPM with Webpack. You can get very far with it. I'm not exactly sure what extra jamjs provides you.

> I currently have quite a few dependencies that I am currently managing via - you are going to scream... - git submodule. As you can tell, this is not very elegant! My main dependencies include Bootstrap and jQuery, but also smaller jQuery plugins. How can I add these smaller plugins, that are oftenly just a single file, to webpack? Is there a recommended way to do so? As an example for this question, consider jQuery.stickyFooter and jQuery.rangyInputs.

[jQuery.stickyFooter](https://github.com/miWebb/jQuery.stickyFooter) could be consumed through NPM by pointing at the repository via `package.json` (point at specific commit or tag if you want to play it safe). Looks like Bower could be an alternative in this case (works with Webpack). Or you could include the relevant files to project itself.

Regardless of the approach you choose, you can define [an alias](https://webpack.github.io/docs/configuration.html#resolve-alias) for the library. Then, in order to get it included within some bundle, you would invoke `require('jquery-stickfooter')` or whatever you set up at the alias. That seems like a clean approach to me.

If the library is used within many bundles, CommonsChunkPlugin, can deal with that (avoids duplication).

> Am I right to assume that loaders are chained by separating them by exclamation points ("!")? I.e.: style-loader!css-loader!scss-loader

Yeah, that's right. I like to keep these things at `webpack.config.js` (or equivalent) and keep the configuration out of require (cleaner code, easier to modify). You can see my approach at [react-component-boilerplate](https://github.com/bebraw/react-component-boilerplate).

> I want to build a loader for OJ. It has a runtime that needs to be included for the browser to work. This runtime currently only supports the browser and needs to run in global space. Imagine I had done the loader, how would I go about loading .oj files?

I cannot give you a straight answer for this one. You should check out some of the loaders for other languages like this to see how they manage it.

> Within my app, I have a slightly changing demand for scripts. When I am at /site/main I only want jQuery, Bootstrap and some fancy stuff. But when I am within /chat, I would like to be able to load a lot more JS files. What is a good way to handle this? I know there is the async way of require-ing files. But how exactly does it work? Do I specify the path directly to the file? Say I have main.js and a subfolder called chat/ containing a few various scripts specially for the chat. How do I load them all?

There are multiple ways to deal with this. Webpack can generate multiple bundles for you (bundle per entry point). I think you can find the approaches you need at amongst these [webpack presentation examples](https://github.com/unindented/webpack-presentation).

> Does webpack understand symlinks? I currently have the Socket.IO client library symlinked into my main folder. What is the best way to get this to the browser?

Maybe it's easier just to have that Socket.IO client library as a regular dependency and let Webpack find it at `node_modules` through a `require`?

I hope this helps. I've been working on [a book](https://github.com/survivejs/webpack_react) that starts from the basics and expands from there. Maybe you'll find it useful. See also [the cookbook](https://github.com/christianalfoni/react-webpack-cookbook/wiki) to find solutions for specific problems.

**Comment by IngwiePhoenix** [comment]
Thanks for the answers! They helped me a lot and I am beginning to re-structure my codebase in order to take full advantage of Webpack. I also just got to see the `ExtractTextPlugin`. This is going to be really nice. My current styles are written using a PHP framework, so I will make sure to write a loader for that too, so all my styles and scripts get packed. Webpack is a truely amazing solution.

Why isn't the presentation linked on this repo's page? It is very informative and gives great examples that actually made my mind click with this system. :)

I also found a plugin on NPM that lets me use my bower modules: https://www.npmjs.com/package/bower-webpack-plugin Very helpful.

Now a question to `require`ing stuff from `node_modules`. the OJ runtime is found within `node_modules/ojc/lib/runtime.js`. So can I just call it like: `require("ojc/lib/runtime");` ?

I also posted a question to the `ExtractTextPlugin` about chaining loaders. When this is resolved, I am pretty sure I have all that I need - except that I will be coding quite a few things for Webpack, mainly loaders.

Kind regards, Ingwie

**Comment by bebraw** [comment]
> Now a question to requireing stuff from node_modules. the OJ runtime is found within node_modules/ojc/lib/runtime.js. So can I just call it like: require("ojc/lib/runtime"); ?

Yeah. You can point to individual files through a package just like that though maybe what you are looking for is actually `require('ojc/src/runtime)` based on the source structure as I don't see `lib` directory there.

**Comment by IngwiePhoenix** [comment]
Oops! I had a derp there :) But yes, that is what i ment. Awesome. :)

Do you happen to know a solution for this issue? https://github.com/webpack/extract-text-webpack-plugin/issues/63

**Comment by IngwiePhoenix** [comment]
There we go, I got myself a base environment up, using the NodeJS API. But I am a little bit confused...

For testing and base-lining, I wrote a get-and-return loader (it comments out the entire code it gets and returns it.). So I ran my build and it was called twice?

```
Hash: eb1afd455132db5dfe4d
Version: webpack 1.8.8
Time: 42ms
  Asset       Size  Chunks       Chunk Names
main.js  313 bytes    0, 1       main
 lib.js    3.56 kB       1       lib.js
chunk    {0} main.js (main) 129 bytes {1}
    [0] ./test/main.js 43 bytes {0} [built]
    [1] ./test/lib.oj 86 bytes {0} [not cacheable] [built]
        cjs require ./lib.oj [0] ./test/main.js 2:0-19
chunk    {1} lib.js (lib.js) 0 bytes
   [0] ./test/main.js 43 bytes {0} [built]
   [1] ./test/lib.oj 86 bytes {0} [not cacheable] [built]
       cjs require ./lib.oj [0] ./test/main.js 2:0-19
```

`main.js`:
```javascript
console.log("meep.");
require("./lib.oj");
```

`lib.oj`:
```objective-c
@implementation Foo {}
+(id)bard {
    console.log("Foo is in Baz' bar.");
}
@end
```

And my config/invocation:
```javascript
        var commonsPlugin = new webpack.optimize.CommonsChunkPlugin('lib.js');
        var defines = new webpack.DefinePlugin({
            "__DEV__": JSON.stringify("true"),
            "__PRERELEASE__": JSON.stringify("true"),
            "__VERSION__": config.version,
            "__CDN__": cdn,
            "__APP__": app
        });
        var compiler = webpack({
            context: config.base,
            entry: {
                //main: "../web-lib/main.js"
                main: path.join(__dirname, "../test/main.js")
            },
            output: {
                // to cdn/app/
                path: app,
                filename: "[name].js",
                publicPath: "/cdn/app/"
            },
            resolve: {
                extensions: ["",".js",".json",".oj"],
                moduleDirectories: ['node_modules', 'bower_components'],
            },
            module: {
                loaders: [
                    { // OJ -> JS
                        test: /\.oj$/,
                        loader: path.join(__dirname,"oj-loader.js")
                    },{ // WingStyle -> CSS
                        test: /\.ws\.php$/,
                        loader: path.join(__dirname,"wingstyle-loader.js")
                    },{ // Images
                        test: /\.(png|jp?g|gif)$/,
                        loaders: [
                            // 20kb or smaller
                            "url?limit="+config.maxFileSize,
                            // optimize image
                            "img"
                        ]
                    },{ // Fonts
                        test: /\.(eot|woff?|svg|tiff)$/,
                        loader: "file"
                    },/*{ // Deal with JS
                        test: /\.(js)/,
                        loader: "strip"
                    },*/{ // Markdown
                        test: /\.(md|markdown)$/,
                        loader: "markdown"
                    },{ // HTML
                        test: /\.html$/,
                        loader: "html"
                    }
                ]
            },
            plugins: [commonsPlugin,defines]
        }, function(err, stats){
            // Is this also a compile step or...?
        }).run(function(err, stats){
            console.log(stats.toString({
                colors: true,
                version: true,
                timings: true,
                assets: true,
                modules: true,
                reasons: true,
                errorDetails: true
            }));
        });
```

So why is my `lib.oj` picked up twice - is it due to the chunk plugin, or what is the reason?

**Comment by bebraw** [comment]
> So why is my lib.oj picked up twice - is it due to the chunk plugin, or what is the reason?

Maybe it's related to `commonsPlugin`? You could try to simplify the configuration until you get something you expect.

**Comment by IngwiePhoenix** [comment]
Seems like it was the commons plugin altogether. Thanks for answering my questions - I am already a very happy webpack user. :) Next thing I am tackling is to compress my code further or trying to split jquery into parts, stuff like that... i really hope jQuery becomes smaller in some time soon.
