### ISSUE TITLE
Dead code still shown in Source Map

### ISSUE THREAD

**Issue by matzeeable** [webpack/webpack#9940]
# Bug report

**What is the current behavior?**
When I define a variable via `DefinePlugin` and use that within my coding, the minified `.js` file removes that dead code correctly but the source map still shows the coding inside that `if`. I do not know if this is a bug or the correct intendion.

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
// webpack.config.js
// [...]
    devtool: "#source-map",
    plugins: [
        new webpack.DefinePlugin({
            "process.env": {
                PLUGIN_CTX: JSON.stringify("lite"),
            }
        })
    ]
// [...]
```

```js
// index.js
if (process.env.PLUGIN_CTX === 'lite') {
    console.log("i am here!");
}
```

**What is the expected behavior?**
Remove dead code from source map, too.

**Other relevant information:**
webpack version:  4.33.0
Node.js version: 10.15.3
Operating System: WSL (Ubuntu)
Additional tools:
- Babel with `preset-typescript`

**Comment by sokra** [comment]
> Remove dead code from source map, too.

SourceMaps show to the **original** unmodified code. So it's indented to not remove code from the SourceMap.

**Comment by matzeeable** [comment]
Ok. So there is really no way to do make that work?

**Comment by sokra** [comment]
You can use a custom loader to remove code.

**Comment by matzeeable** [comment]
Ok, gut zu wissen. Danke Dir! 👍
