### ISSUE TITLE
dynamic import & magic comments: pre-processor strips comments; need "config" way

### ISSUE THREAD

**Issue by aappddeevv** [webpack/webpack#9941]
Some code pre-processors strip comments so using comments may not be a robust way.

This is a request to support "config" support to handle the magic comments.

Or perhaps move the comments inside the string and strip them out, kind of like inline loader config.

**Comment by evilebottnawi** [comment]
Please use issue template.

Can you provide tool who remove comments (link)?

**Comment by aappddeevv** [comment]
Sorry about that. A transpiler, https://www.scala-js.org/.

**Comment by evilebottnawi** [comment]
It is feature :smile: , because we don't support it right now and looks we need implement this, because comments doesn't work in some cases (as you written above).

**Comment by aappddeevv** [comment]
As a temporary fix, I'm thinking a loader might help here with some mappings. It looks like you can use "expressions" vs constants as well so I guess a regex matcher is needed. I think trying to do regex matching is probably not robust vs some runtime thing in the background that picks the expression value.

**Comment by evilebottnawi** [comment]
Maybe it will be `Function` so you can write any logic because using regexp is not always conveniently

**Comment by evilebottnawi** [comment]
bump
