### ISSUE TITLE
Deleting from require.cache doesn't reload module latest version from node_modules

### ISSUE THREAD

**Issue by iki** [webpack/webpack#9945]
# Bug report

**What is the current behavior?**

Deleting from [`require.cache`](https://webpack.js.org/api/module-methods/#requirecache) does re-execute and re-export the module, but doesn't reload its latest version, which is an [expected behavior](https://nodejs.org/api/modules.html#modules_require_cache) in Node.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Update module in node_modules
2. `delete require.cache[require.resolve('dependency')]` in app code, e.g. in `module.hot.dispose` handler

**What is the expected behavior?**

New module version should be imported, but it is **not**.

**Temporary workaround**

Workaround is possible using @maerzhase [webpack-clear-require-cache-plugin](https://github.com/maerzhase/webpack-clear-require-cache-plugin) solution to the same https://github.com/zeit/next.js/issues/5463 issue.

Using **both** `new ClearRequireCachePlugin([/dependency/])` in webpack plugins to clear the module from `require.cache` on each `compiler.hooks.afterEmit` **and**  `delete require.cache[require.resolve('dependency')]` in app code, e.g. in `module.hot.dispose` handler, to clear the module from `__webpack_require__.c` works **ok**.

**Proposed solution**

Make deleting from `require.cache` to reload the module latest version, which is an [expected behavior](https://nodejs.org/api/modules.html#modules_require_cache) in Node.

Possible implementation: Instead of transpiling `delete require.cache[<code>]` to `delete __webpack_require__.c[<code>]`, transpile it to a call to a new internal webpack bootstrap method that will remove the depedency from both `__webpack_require__.c` and `require.cache`, including it's children in the latter.

**Other relevant information:**
webpack version:  4.41.2
Node.js version: 13.1.0-x64
Operating System:  Windows 10.0.18362.418 x64
Additional tools: @vlazh [node-hot-loader](https://github.com/vlazh/node-hot-loader)

**Comment by evilebottnawi** [comment]
bump

**Comment by sokra** [comment]
It's not possible to reload changed chunk. This might work in some cases but is not a good idea in general. Use HMR for this use case.
