### ISSUE TITLE
webpack doesn't handle babel while running from npm install flow

### ISSUE THREAD

**Issue by alexey-sh** [webpack/webpack#9947]
# Bug report

**What is the current behavior?**
webpack doesn't run babel loader or babel loader doesn't work

**If the current behavior is a bug, please provide the steps to reproduce.**
Steps to reproduce:

1. `mkdir my_test_project`
2. `cd my_test_project`
3. `npm init`
4. `npm i --save git+https://github.com/alexey-sh/test_webpack_with_npm.git`
5. `cat node_modules/testname/dist/index.js`

It contains code with `class` declaration. but if I do

1. `git clone https://github.com/alexey-sh/test_webpack_with_npm.git`
2. `cd test_webpack_with_npm`
3. `npm i`
4. `cat dist/index.js`

I'll see a different code without `class` declaration (as expected)

There is also `fix/install` branch with working code
So the following steps works fine, and dist/index.js doesn't contain `class` declaration.

1. `mkdir my_test_project`
2. `cd my_test_project`
3. `npm init`
4. `npm i --save git+https://github.com/alexey-sh/test_webpack_with_npm.git#fix/install`
5. `cat node_modules/testname/dist/index.js`

**What is the expected behavior?**

It should work both from a repository and from package

**Other relevant information:**
webpack version:  latest
Node.js version:  v11.15.0, npm 6.13.0
Operating System: mac os x 10.14.6
Additional tools: babel

**Comment by sokra** [comment]
`exclude: /(node_modules|bower_components)/,`

You excluded node_modules. If your code is installed in node_modules babel-loader won't be applied.

Prefer `include` over `exclude`

**Comment by alexey-sh** [comment]
> If your code is installed in node_modules babel-loader won't be applied.

is it documented somewhere?
