### ISSUE TITLE
New files not being added during incremental build with require.context

### ISSUE THREAD

**Issue by Whoaa512** [webpack/webpack#995]
My issue is similar to #556 

I've got a webpack-dev-server setup to watch my files and inside my main `app.coffee` I have something like this:
```coffee

loadContext = (contextRequire)->
  contextRequire.keys().forEach (mod)-> contextRequire(mod)

#load all module subfiles
loadContext require.context('./common', true, /.*/)
loadContext require.context('./envelopes', true, /.*/)
loadContext require.context('./home', true, /.*/)
loadContext require.context('./preferences', true, /.*/)
loadContext require.context('./reports', true, /.*/)
loadContext require.context('./workspaces', true, /.*/)
```

This works great for file changes, however if I try to add a new file within one of these directories or their subdirectories the webpack-dev-server re-runs the build but the new files are not included in the bundle.

I've tried setting the cache option to false but the problem still presents itself :disappointed: 

Any tips or guidance would be much appreciated

**Comment by sokra** [comment]
This works for me... Wonder why it doesn't work for you...

**Comment by Whoaa512** [comment]
I've created a repo to reproduce the bug
https://github.com/Whoaa512/webpack-repro

**Comment by sokra** [comment]
Thanks. I hope it's now fixed... :)

**Comment by Whoaa512** [comment]
Yup it works for new files now! Thanks :)

It's not rebuilding if I try to delete the file though.

**Comment by sokra** [comment]
yep. But that not soo important... ;)

**Comment by Whoaa512** [comment]
True :) I've gone ahead and added the updated modules to my production repo and it works like a charm.

Thanks again @sokra! :shipit:

**Comment by bebraw** [comment]
@Whoaa512 Safe to close now?
