### ISSUE TITLE
Installing ArcGIS Desktop 10.5.1 using Windows Shell scripts

### ISSUE THREAD

**Issue by sivasgnhcl** [webpack/webpack#9952]
Trace-DSCJob : PowerShell DSC resource ArcGIS_Install  failed to execute Test-TargetResource functionality with error message: PowerShell Desired State Configuration does not
support execution of commands in an interactive mode. Please ensure that the underlying command is not prompting for user input, such as missing mandatory parameter,
confirmation prompt etc.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ArcGIS\ArcGIS.psm1:221 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob
 
Trace-DSCJob : The SendConfigurationApply function did not succeed.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ArcGIS\ArcGIS.psm1:221 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
