### ISSUE TITLE
module.fileDependencies undefined

### ISSUE THREAD

**Issue by arrowing** [webpack/webpack#9955]
# Bug report

**What is the current behavior?**
I try to writing a incremental build plugin with official documentation and catch an error report when I run build, look like this

```
class MyPlugin {
  apply(compiler) {
    compiler.hooks.emit.tapAsync('MyPlugin', (compilation, callback) => {
      // Explore each chunk (build output):
      compilation.chunks.forEach(chunk => {
        // Explore each module within the chunk (built inputs):
        chunk.getModules().forEach(module => {
          // Explore each source file path that was included into the module:
          module.fileDependencies.forEach(filepath => {
            // we've learned a lot about the source structure now...
          });
        });

        // Explore each asset filename generated by the chunk:
        chunk.files.forEach(filename => {
          // Get the asset source for each file generated by the chunk:
          var source = compilation.assets[filename].source();
        });
      });

      callback();
    });
  }
}
module.exports = MyPlugin;
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I can get the module.fileDependencies which includes css,image,js,json files and so on.

**Other relevant information:**
webpack version:  4.41.2
Node.js version: v10.13.0
Operating System: Windows 10
Additional tools:

**Comment by sokra** [comment]
It's `module.buildInfo.fileDependencies` but it's not set for all modules, so check if it's set before accessing it. You can also send a PR to the documentation to fix that.

**Comment by arrowing** [comment]
@sokra Thanks a lot.
I found there have no `module.buildInfo.fileDependencies` in some modules, and then the item of `module.buildInfo.fileDependencies` isn't a filepath but a Module Object. So I can't directly get the filepath. Can you give me some tips? 
Thanks in advance.

**Comment by arrowing** [comment]
I use hook `dependencyReference` of compilation to get dependencies now. I don't know if okay. It like thies:
```
class MyPlugin {
  apply(compiler) {

    let out = {}

    compiler.hooks.make.tapAsync('MyPlugin', (compilation, callback) => {
      compilation.hooks.dependencyReference.tap('MyPlugin', (dependencyReference, dependency, module) => {
        let fileDependencies = dependency.module.buildInfo.fileDependencies
        if(fileDependencies && module.resource){
          let resource = module.resource.split('?')[0]
          if(!out[resource]){
            out[resource] = fileDependencies
          }else{
            fileDependencies.forEach(file => {
              out[resource].add(file)
            })
          }
        }
      })
    })
  }
}
```

**Comment by sokra** [comment]
Note that `fileDependencies` are not dependencies in the graph. These are files the loader transformation depends on.

You get dependencies in the graph with `module.dependencies` and `module.blocks`

**Comment by arrowing** [comment]
@sokra Yeah, I see. But the item of `odule.dependencies` and `module.blocks` is an Object. How can I get the filepath with them? Any examples? 
Thank you so much.

**Comment by TheLarkInn** [comment]
`module` has request I believe

**Comment by arrowing** [comment]
@TheLarkInn Yes. I use the property `resource` as filepath to set up dependency map. I think that has a better way to do this. Thank you.
