### ISSUE TITLE
404 during loading chunks when using contenthash

### ISSUE THREAD

**Issue by PanFrontend** [webpack/webpack#9961]
# Bug report

**What is the current behavior?**
Splitting bundle into chunks using [contenthash] substitution in chunkFilename causes random changes in chunk name even if there were no changes to a file. Because of that some of the requested chunks did not exist anymore. That causes 404 and an app crash.

Setting a single runtimeChunk did not help. Other techniques used to avoid boilerplate described in [Caching](https://webpack.js.org/guides/caching/) don't work too. 

In my opinion related issues: #8419 #7179

**Detailed description:**
Let's say I'm building an app that consists total of around 20 chunks and 3 entry points.

```javascript
output: {
    path: path.resolve(__dirname, '../static/js/'),
    filename: '[name].bundle.js',
    chunkFilename: '[name].[contenthash].chunk.js',
    publicPath: '/static/js/',
},
```

[package.json shape stripped to related dev packages](https://gist.github.com/PanFrontend/91f13f9eea41a4a868cb6c886c9c415e)
[webpack config](https://gist.github.com/PanFrontend/64711839e60015cabdf0fd2fc6d49579)

I have to use [contenthash] substitution as without it chunks will be wrongly cached (after an app rebuild end-user browser won't ever know that chunks content changed so it will load old chunks from cache instead new chunks - that can cause an app crash I want to avoid with adding [contenthash]).

After build pass, webpack notifies me about created chunks. For the sake of this description let's focus on 3 of them with ids: 1, 2, 3.
```
Asset                               Size         Chunks                              
1.e3b2009f94d2bf9131f1.chunk.js     25.9 KiB     1        [emitted] [immutable]
2.bc6c43f9e093015d2b7f.chunk.js     22 KiB       2        [emitted] [immutable]
3.5bfc0cb13051a77d4b92.chunk.js     189 KiB      3        [emitted] [immutable]
react/panel.bundle.js               245 KiB      6        [emitted]
runtime.bundle.js                   2.67 KiB     2        [emitted]
```
After the build, the app is ready to be deployed to clients. As it lands on the production they download bundles and start using it. Then the next build comes in where changes are totally not related to the frontend spa and its bundles. As our build process involves `yarn install && yarn build` packages are rebuilt. No files were changed in the frontend spa source. Now some of the clients that were using the app earlier before that build comes to our app. The result will be like this - 404's on requests for some chunks:

![image](https://user-images.githubusercontent.com/3399141/68683610-5db2f100-0567-11ea-9e1b-60bd36193c75.png)

Let's see what's going on in build log:
```
Asset                               Size         Chunks                      
1.e3b2009f94d2bf9131f1.chunk.js     25.9 KiB       1      [emitted] [immutable]
3.a3c596835de321215805.chunk.js     22 KiB         3      [emitted] [immutable]
// where is chunk id 2?   
react/panel.bundle.js               245 KiB        6      [emitted]
runtime.bundle.js                  2.67 KiB        2      [emitted]
```

So as you can observe in the build log, even if files have not changed and all settings to avoid boilerplate was used, we still have different results. First of all contenthash for chunk id 3 differs (3.5bfc0cb13051a77d4b92 vs a3c596835de321215805) and there's no chunk id 2. And our panel.bundle.js is still requesting old chunks that cause 404 on that requests and app crash (asking user to refresh app is not considered as 'ok solution', it should work).

**If the current behavior is a bug, please provide the steps to reproduce.**
As mentioned in other issues related to 'contenthash changing even if files didn't change' it's hard to create minimum version of the repo to allow reproduction. Moreover from what I observed in other issues even if someone provided repo it never was 100% chances to reproduce that behavior.

**What is the expected behavior?**
One of:
1) Stable chunks & bundles names between builds
2) Entry bundle can somehow load chunks even if names containing contenthash has changed

**Other relevant information:**
webpack version:  ^4.41.2
Node.js version: 10.15.3
Operating System: Unix

**Comment by evilebottnawi** [comment]
It is really to hard investigate problem without reproducible test repo :disappointed: Maybe you can try to create repo?

**Comment by PanFrontend** [comment]
I'll try, but had not enough time today. I wanted to describe issue as best as possible in meantime :)

**Comment by sokra** [comment]
> Now some of the clients that were using the app earlier before that build comes to our app. The result will be like this - 404's on requests for some chunks

Do not remove old files from the server on deploy. Users might be still using the old version.

**Comment by PanFrontend** [comment]
@sokra I can't leave files on the server as every deploy is a clean, separate build of the app :(

**Comment by sokra** [comment]
> I can't leave files on the server as every deploy is a clean, separate build of the app :(

If your deploy doesn't force users to close their browser tab with your app, you should reconsider that.

You could also force reload the page if chunk load failed to force users to use the latest version.
