### ISSUE TITLE
webpackExclude doesn't work 

### ISSUE THREAD

**Issue by volkanunsal** [webpack/webpack#9963]
**Reposting with corrected code**

# Bug report

**What is the current behavior?**

Given a dynamic import like this:

```js
const CompanyEdit = universal(import(
/* webpackExclude: /(__generated__|__tests__)/ */ 
'comps/Company/Edit'));
```

It does not exclude the files matching the pattern from the chunk generation. Here is a sample output from the `manifest.json` of the files that match the following pattern and are generated by this import

```
public/__generated__-GetKey.chunk-647967baa76de181db7c.js
public/__generated__-GetKey.chunk-647967baa76de181db7c.js.map
public/__generated__-RegenKey.chunk-4f4202d851a015422d6d.js
public/__generated__-RegenKey.chunk-4f4202d851a015422d6d.js.map
public/__generated__-updateCompany.chunk-c3ad3a2c0a71b001bb29.js
public/__generated__-updateCompany.chunk-c3ad3a2c0a71b001bb29.js.map
public/__tests__-AccessKeyManager-test.chunk-bed6e34b29ee6fbd5d72.js
public/__tests__-AccessKeyManager-test.chunk-bed6e34b29ee6fbd5d72.js.map
public/__tests__-__snapshots__-AccessKeyManager-test-js-snap.chunk-07f6461ec4547a0878ef.js
public/__tests__-__snapshots__-AccessKeyManager-test-js-snap.chunk-07f6461ec4547a0878ef.js.map
```

**What is the expected behavior?**

It is expected to exclude these files from the manifest.

**Other relevant information:**
webpack version:  4.41.0
Node.js version: 8.x.x
Operating System: Mac OS

**Comment by sokra** [comment]
> ```js
> const CompanyEdit = universal(import(
> /* webpackExclude: /(__generated__|__tests__)/ */ 
> 'comps/Company/Edit'));
> ```

Your code **only** includes `comps/Company/Edit` so `webpackExclude` doesn't apply here. These chunks are generated by some **other** `import()`

**Comment by volkanunsal** [comment]
I think you're right. There is only one other place where I use a dynamic import. That is a sister component to `Company/Edit`. They are both imported from `Company/index.js`. This is what that import looks like:

```js
const Loader = universal(
  // $FlowFixMe
  (props: { path: string }) =>
    import(
      `./${props.path}`
    ),
  {
    minDelay: 0,
    loading: () => <i className="fa fa-spinner fa-spin" />,
  }
);
```

This was generating the following warning in my console:

```
WARNING in ./assets/comps/Company/__generated__/updateCompany.js 9:7
Module parse failed: Unexpected token (9:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

And when I put the `import` in the argument, rather than inside the function, the warnings went away.

```js
const Loader = universal(
  import(
    `./${props.path}`
  ),
  {
    minDelay: 0,
    loading: () => <i className="fa fa-spinner fa-spin" />,
  }
);
```
