### ISSUE TITLE
LimitChunkCountPlugin bug with maxChunks: 1

### ISSUE THREAD

**Issue by samuelcastro** [webpack/webpack#9964]
# Bug report

**What is the current behavior?**

Using `new webpack.optimize.LimitChunkCountPlugin({ maxChunks: 1 })` in my build process generates the following message:

```
chunk main [entry]
Cannot convert undefined or null to object
```

**If the current behavior is a bug, please provide the steps to reproduce.**

To reproduce just use the `LimitChunkCountPlugin` plugin with `maxChunks: 1`

**What is the expected behavior?**

Run without any error.

**Other relevant information:**
webpack version:  4.41.0
Node.js version: 10.16.0
Operating System: macOS Mojave 10.14.6

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by robertsonk82** [comment]
I too faced the same issue. `maxChunks: 2` and above was success but `maxChunks: 1` failed with same error.

Then realized that I am using lazy load in react which obviously, by it's design, needs a separate chunk.
```
const MyComponent = lazy(() => import("my-component"));
```

If you're facing same scenario, and if you need only one js and no more chunks you can remove lazy load. If you need lazy load, you need chunks.

**Comment by eliseumds** [comment]
@robertsonk82 exactly. We use *LimitChunkCountPlugin* only on the server to do SSR with React, but a Babel plugin takes care of converting those dynamic imports into static ones.

**Comment by agalatan** [comment]
@robertsonk82 React.lazy doesn't actually need a separate chunk. All it needs is a Promise of an object with key `default`.
This works: `const LazyComponent = React.lazy(() => Promise.resolve({ default: SomeComponent }))`
