### ISSUE TITLE
webpackPrefetch: false doesn't work

### ISSUE THREAD

**Issue by floydback** [webpack/webpack#9969]
I've import locales dynamically and I would prefer not to display `link rel="prefetch"` 
```
router.beforeEach((to, from, next) => {
    import(
      /* webpackChunkName: "lang-[request]", webpackPrefetch: false */
      `./locales/${lang}.json`
    )
      .then(messages => {
        i18n.setLocaleMessage(lang, messages.default)
        i18n.locale = lang
        next()
      })
})
```
`webpackPrefetch: false` does not affect. Is this a bug?

**Comment by evilebottnawi** [comment]
Please use issue template, otherwise issue will be closed, thanks

**Comment by sokra** [comment]
> `webpackPrefetch: false` does not affect.

That's the default. It makes no difference. By default no `<link rel="preferech">` tag is created.

**Comment by plehnen** [comment]
In vue cli the webpackPrefetch is automatically set for all chunk files. So here `webpackPrefetch: false` actually would make a lot of sence.
Not sure if this has to be fixed here or there (https://github.com/vuejs/preload-webpack-plugin/issues/6).
