### ISSUE TITLE
hot.status() returns wrong value

### ISSUE THREAD

**Issue by Leedehai** [webpack/webpack#9973]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by Leedehai** [comment]
@evilebottnawi  Hi I updated the issue, please re-open it, because I can't find the button to re-open it myself.

**Comment by Leedehai** [comment]
Update: in the source code of Webpack, I suspected the bug is in HotModuleReplacement.runtime.js, and specifically this:
```
// Management API
			check: hotCheck,
			apply: hotApply,
			status: function(l) {
				if (!l) return currentStatus; # here?
				registeredStatusHandlers.push(l);
			},
```

I checked how signal handlers are called (called by `setStatus()`), and it seems fine.

I might be wrong, though.

**Comment by Leedehai** [comment]
Opened another issue.
