### ISSUE TITLE
(updated) hot.status() returns wrong value

### ISSUE THREAD

**Issue by Leedehai** [webpack/webpack#9974]
I submitted the issue by mistake in #9973, I'm updating it here.

# Bug report

**What is the current behavior?**
`module.hot.status()` the status string fed to the status handler (registered via `module.hot.addStatusHandler()`) is different in some cases.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
module.hot.addStatusHandler(s => {
    console.log(`handler given ${s}, hot.status() is ${module.hot.status()}`);
});
```

In console:
```
handler given check, hot.status() is check
handler given prepare, hot.status() is prepare
handler given ready, hot.status() is ready
handler given dispose, hot.status() is dispose
handler given apply, hot.status() is apply
handler given idle, hot.status() is idle
handler given ready, hot.status() is idle # this is wrong
```

**What is the expected behavior?**
The last line of the console output: it should be
```
handler given ready, hot.status() is ready # expected
```

**Other relevant information:**
webpack version:  4.41.2
Node.js version:  10.5.3
Operating System: Linux
Additional tools: N/A

**Comment by Leedehai** [comment]
Update: in the source code of Webpack, I suspected the bug is in HotModuleReplacement.runtime.js, and specifically this:
```
// Management API
check: hotCheck,
apply: hotApply,
status: function(l) {
	if (!l) return currentStatus; # here?
	registeredStatusHandlers.push(l);
},
```

I checked how signal handlers are called (called by `setStatus()`), and it seems fine.

I might be wrong, though.

**Comment by ankingcodes** [comment]
@sokra is this issue valid ?

**Comment by evilebottnawi** [comment]
bump

**Comment by sokra** [comment]
I don't think it's still valid. There is no repro test verify. If this is still an issue open a new issue **with a repro** to verify it.

**Comment by Leedehai** [comment]
> I don't think it's still valid. There is no repro test verify. If this is still an issue open a new issue with a repro to verify it.
It _is_ valid. See the initial comment for console printout. I didn't make this up. But yeah, closing this issue is fine due to inactivity.

**Comment by evilebottnawi** [comment]
@Leedehai Can you provide old example?
