### ISSUE TITLE
Support "optionalDependencies" when target is node (or related, for example electron-main)

### ISSUE THREAD

**Issue by jhg** [webpack/webpack#9980]
## Feature request

Support `optionalDependencies` as NPM and Yarn do:
http://npm.github.io/using-pkgs-docs/package-json/types/optionaldependencies.html
https://yarnpkg.com/lang/en/docs/dependency-types/

It's useful for example when you need to use an package in Windows and other in Mac/Linux and packages support `os` then it can be not installed in the rest of operate systems but webpack doesn't check that and raise an error.

**What is the expected behavior?**

When you have an require/import inside an `if` to use module for that OS, which's installed, not raise errors for an optional package that won't be used and NPM and Yarn are ignoring when install packages.

**What is motivation or use case for adding/changing the behavior?**

Use optional packages feature of NPM and Yarn.

**How should this be implemented in your opinion?**

Checking `optionalDependencies` of `package.json` is ok.

**Are you willing to work on this yourself?**
I didn't develop webpack never before, I'm suggesting an feature that is so needed by comunity as you can see searching about dynamic dependencies or optional dependencies.

**Comment by Vict0r-Chen** [comment]
I also encountered this problem, I don't know how to make webpack skip the package in optionalDependencies
