### ISSUE TITLE
Webpack CLI, stats, display "hidden modules"

### ISSUE THREAD

**Issue by slavafomin** [webpack/webpack#9985]
Hello!

I'm trying to figure out what went into a Webpack bundle.

I'm running the build using CLI: `npx webpack` and I see a list of modules with a hint: `+ 310 hidden modules`.

I then run `npx webpack --display-max-modules 1000` and I see a slightly bigger list, but still with the hint: `+ 300 hidden modules`. No matter how big number I use for the `--display-max-modules` option it doesn't show all modules.

There is also an option `--display-modules` with the following description `Display even excluded modules in the output`. If I run `npx webpack --display-modules` I can see 324 modules and no hint.

However, the option description is very unclear. What are the `excluded modules` and what are the `hidden modules`? Excluded/hidden by who? Are those the same terms or somehow different? If it's the same term, why is it called differently in various contexts? Is it related to a tree-shaking or it's just a CLI output pre-configured behavior?

Looking at the documentation I can't answer all those questions. I believe the terminology should be more clear and consistent.

Could you elaborate on this, please? Thank you.

**Comment by evilebottnawi** [comment]
@webpack-bot move to `webpack/webpack-cli`
