### ISSUE TITLE
Webpack throw Error: EISDIR when I replace a file with a same name folder includes index.js

### ISSUE THREAD

**Issue by wt911122** [webpack/webpack#9988]
# Bug report

**What is the current behavior?**
Webpack throw Error: EISDIR when I replace a file with a same name folder includes index.js when webpack dev server running.

**If the current behavior is a bug, please provide the steps to reproduce.**
![image](https://user-images.githubusercontent.com/7549134/69105924-c6d6bf00-0aa7-11ea-9f3b-d4bb086ba5b1.png)
![image](https://user-images.githubusercontent.com/7549134/69106350-08b43500-0aa9-11ea-9534-24789b703cd6.png)
![image](https://user-images.githubusercontent.com/7549134/69106363-123d9d00-0aa9-11ea-9242-abb1b9ac7db0.png)

#### webpack.config.js
```
const path = require('path');

module.exports = {
    entry: './index.js',
    output: {
        filename: 'dist.js'
    },
    module: {
        rules: [
            { test: /\.vue$/, use: path.resolve(__dirname, 'loader.js') }
        ]
    }
};
```

#### index.vue
```vue
<template>
<div></div>
</template>

<script>
export default {
    data() {
        return 'xxxx';
    },
};
</script>

<style module>

</style>
```
#### loader.js
```javascript
module.exports = function(source){
    return `module.exports = \`${source}\``
}
```
#### index.js
```javascript
import './src/overview/index.vue';
```

#### package.json
``` json
{
  "name": "webpack-reload-testings",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "webpack-dev-server --config ./webpack.config.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "webpack": "^4.41.2",
    "webpack-cli": "^3.3.10",
    "webpack-dev-server": "^3.9.0"
  }
}
```

**What is the expected behavior?**
When I replace file index.vue with a folder named index.vue includes index.js, webpack should behave like usual. 

**Other relevant information:**
webpack version:  4.41.2
Node.js version: 10.15.0
Operating System:  Mac OSX
Additional tools:

**Comment by sokra** [comment]
fix in webpack 5

**Comment by evilebottnawi** [comment]
Answer above, feel free to feedback
