### ISSUE TITLE
Webpack default minimizer produces staled sourcemap 

### ISSUE THREAD

**Issue by icy0307** [webpack/webpack#9991]
# Bug report

**What is the current behavior?**
Built a simple project followed by this guide,
https://webpack.js.org/guides/typescript/
 the generated map's `sources` field point to a staled file path **no longer existed in the file system**.
Here is webpack config:
![image](https://user-images.githubusercontent.com/8952410/69138302-62445000-0af9-11ea-9bea-a4036d607345.png)
And here is the result:
![image](https://user-images.githubusercontent.com/8952410/69138382-89028680-0af9-11ea-9e9c-5ffe8b48083f.png)
There is no file named `main.js` in the file system. 

**If the current behavior is a bug, please provide the steps to reproduce.**

1.  Create a project follow this guide.https://webpack.js.org/guides/typescript/
2.  Change the output filename to `main.js` and build with sourcemap
3.  Change the output filename again to  `abc.js` and build again , then you can reproduce this bug.

**What is the expected behavior?**
Generate correct sourcemap.

**Other relevant information:**
webpack version:  
the package I am using:
![image](https://user-images.githubusercontent.com/8952410/69131414-52bf0a00-0aed-11ea-8175-1dc8d6d442bd.png)
Node.js version: 
Operating System: 
Additional tools:

**Comment by evilebottnawi** [comment]
@icy0307 What do you mean? Please read how package manager works

**Comment by icy0307** [comment]
> @icy0307 What do you mean? Please read how package manager works

Sorry, I accidentally clicked send button before finish editing, just updated.

**Comment by sokra** [comment]
SourceMaps doesn't point to the filesystem. These are URLs that can point anyway. The remote resource doesn't even have to exist if `sourcesContent` is provided in SourceMap (which webpack provides).

**Comment by icy0307** [comment]
> SourceMaps doesn't point to the filesystem. These are URLs that can point anyway. The remote resource doesn't even have to exist if `sourcesContent` is provided in SourceMap (which webpack provides).

But I suppose when I change the output's filename from `main.js` to `abc.js`, the source field in source map shouldn't be `main.js` anymore?
One more thing, when I downgrade `terser-webpack-plugin` version to `1.3.0`, everything works perfectly, like this:
![image](https://user-images.githubusercontent.com/8952410/69204813-f5759800-0b82-11ea-9c21-82de5f9ffa8a.png)

**Comment by sokra** [comment]
Seems like a caching issue @evilebottnawi

**Comment by evilebottnawi** [comment]
@sokra fixed in `2` version (already in webpack@5)

**Comment by casyalex** [comment]
I may got the same issue. There is no **sourcesContent** property in .map file that generate by 'source-map' mode.

Chrome can't load content for webpack:///...

In webpack-dev-server, the source map works fine.

    "webpack": "^4.42.0",
"webpack-cli": "^3.3.11",
