### ISSUE TITLE
Webpack parser.hooks.call does not working for imported functions

### ISSUE THREAD

**Issue by maykinayki** [webpack/webpack#9992]
# Bug report

**What is the current behavior?**
I'm trying to write webpack plugin for exporting translation keys per entry-point and export them to `.json` file.

`
compiler.hooks.normalModuleFactory.tap(pluginName, factory => {
          factory.hooks.parser.for('javascript/auto').tap(pluginName, (parser, options) => {
              parser.hooks.call.for("___").tap(pluginName, expression => {
                   console.log(expression);
              });
           });
    });
`

in `MyComponent.js` if I import the function `___` then `call` hooks above will not get triggered but if I define `___` as a global function and use it without importing then it works. So how should I solve this problem?

**Other relevant information:**
webpack version:  4.35.0
Node.js version: 10.15.0

**Comment by sokra** [comment]
The following works for webpack 5:

The hooks only apply for free variables and tagged variables.

If you want it to work for an imported symbol you need to tag the variable after importing. Similar to this:

https://github.com/webpack/webpack/blob/e82b870007eb353af62b6aa51b7656c67ecbceab/lib/dependencies/HarmonyImportDependencyParserPlugin.js#L62-L75

After that you can hook into parser hooks for the tag:

https://github.com/webpack/webpack/blob/e82b870007eb353af62b6aa51b7656c67ecbceab/lib/dependencies/HarmonyImportDependencyParserPlugin.js#L95-L97
