### ISSUE TITLE
webpack-dev-server issue

### ISSUE THREAD

**Issue by victorykong** [webpack/webpack#9996]
The proxy object's pathRewrite property is invalid, so we need to add /api

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Just do it, also invalid repo, please use https://github.com/webpack/webpack-dev-server
